### ISSUE TITLE
ImportError: No module named espnet.transform.transformation

### ISSUE THREAD

**Issue by Yingzhu-Zhao** [espnet/espnet#1045]
For new espnet 0.4.3, which running stage 1 feature generation, when running:
# compute global CMVN
compute-cmvn-stats scp:data/${train_set}/feats.scp data/${train_set}/cmvn.ark
there is one error:
Traceback (most recent call last):
File "/home/owner/expts/espnet_0.4.3_0801/egs/librispeech/asr1/../../../utils/copy-feats.py", line 6, in <module>
from espnet.transform.transformation import Transformation
ImportError: No module named espnet.transform.transformation
apply-cmvn --norm-vars=true data/train_100/cmvn.ark scp:exp/dump_feats/train/feats.1.scp ark:-
But the file is there.

**Comment by kan-bayashi** [comment]
Hi @Yingzhu-Zhao. Thank you for your report.
Which recipe did you use?

**Comment by Yingzhu-Zhao** [comment]
Hi, thanks for reply. I use librispeech training data 100hrs only.

**Comment by kan-bayashi** [comment]
I’m not sure why this is happened.
Please make sure your installation is successfully done.
You can check via `cd tools; make check_install`

And if you make your own recipe, please make sure `path.sh` is correctly working.
You can check via following command
```
$ cd <your recipe dir>
$ source path.sh
$ python
>>> from espnet.transform.transformation import Transformation
```

**Comment by Arafat4341** [comment]
@kan-bayashi I ran docker image of espnet. I get 
`File "/home/arafat/espnet/egs/ljspeech/tts1/../../../utils/merge_scp2json.py", line 15, in <module>
from espnet.utils.cli_utils import get_commandline_args
ModuleNotFoundError: No module named 'espnet'`

Why am I getting this?

**Comment by Esdsnqxz** [comment]
> @kan-bayashi I ran docker image of espnet. I get
> `File "/home/arafat/espnet/egs/ljspeech/tts1/../../../utils/merge_scp2json.py", line 15, in <module> from espnet.utils.cli_utils import get_commandline_args ModuleNotFoundError: No module named 'espnet'`
> 
> Why am I getting this?

hi,when i use docker ,i met the same problem,have you solved it ?
