### ISSUE TITLE
Yesno results really high

### ISSUE THREAD

**Issue by Youyoun** [espnet/espnet#1049]
Hi,

By running the yesno recipe, we get an Error rate of 31.5% (according to `egs/yesno/asr1/RESULTS`). 
How do you explain such a high WER for a task where kaldi gets 0% WER ?

**Comment by zqs01** [comment]
perhaps because the dataset is so small and is not suitable for deep learning. I just guess.

**Comment by sw005320** [comment]
> perhaps because the dataset is so small and is not suitable for deep learning. I just guess.

Yes, we made this recipe for the debugging purpose. We don't expect this to work normally due to very sparse training data.

**Comment by Youyoun** [comment]
All right, thanks for your answer. Was trying to play with the parametres to see the influence of each in the learning process, but I was getting 100% error everytime I changed a parameter. 

Will move on to another dataset for testing !
