### ISSUE TITLE
RuntimeError: Expected tensor for argument #1 'indices' to have scalar type Long; but got torch.cuda.FloatTensor instead (while checking arguments for embedding)

### ISSUE THREAD

**Issue by zqs01** [espnet/espnet#1051]
Hi everyone,

I use the transformer model for ASR, the default encoder type is "conv2d", but when I change the default encoder type to "embed", I get an error. How can I solve this problem? 

RuntimeError: Expected tensor for argument #1 'indices' to have scalar type Long; but got torch.cuda.FloatTensor instead (while checking arguments for embedding)

**Comment by kan-bayashi** [comment]
embed of Transformer encoder is used for TTS.
It cannot be used for ASR.
