### ISSUE TITLE
loss curve question

### ISSUE THREAD

**Issue by zqs01** [espnet/espnet#1052]
![TIM截图20190807082854](https://user-images.githubusercontent.com/40491290/62585860-7fa83200-b8ed-11e9-8962-e1e347efe638.png)

when I use the Transformer for ASR and set the parameter "mtlalpha: 0", the loss curve can only show two. Is there any problems? Thanks.

**Comment by kan-bayashi** [comment]
Thank you for your report.
I also confirmed similar phenomena.
I will investigate it.

**Comment by ShigekiKarita** [comment]
this is because loss equals loss_att if mtlalpha = 0.

https://github.com/espnet/espnet/blob/4f9c28e8193b58be97e80115d38c76f9275d9954/espnet/nets/pytorch_backend/e2e_asr_transformer.py#L190-L192
