### ISSUE TITLE
recog_wav.sh problem

### ISSUE THREAD

**Issue by robothubtokyo** [espnet/espnet#1071]
We tested trained models by using the following command and it doesn't work after 0.5.0. It seems that --cmvn is needed, but we cannot find such files. Could you tell me where cmvn files are? Thank you.

../../../utils/recog_wav.sh --recog_model exp/train_nodup_sp_pytorch_train/results/model.acc.best --lang_model exp/train_rnnlm_pytorch_lm/rnnlm.model.best --decode_config conf/decode.yaml --backend pytorch ~/voices/watashi3.wav

Error: models or set of cmvn, lang_model, recog_model and decode_config are required.

**Comment by sw005320** [comment]
You can find it at `data/train*/cmvn.ark`.
