### ISSUE TITLE
Multispeaker model published?

### ISSUE THREAD

**Issue by hadaev8** [espnet/espnet#1073]

**Comment by sw005320** [comment]
We could make it with the old ESPnet, but not for the latest one.
@simpleoier, I think it's good to redo your experiments with the latest ESPnet and share the model. Can you do that?

**Comment by simpleoier** [comment]
Yes, I can start doing it immediately!

**Comment by kan-bayashi** [comment]
Published.
https://github.com/espnet/espnet/blob/master/egs/wsj_mix/asr1/RESULTS.md
