### ISSUE TITLE
KeyError: 'validation/main/loss' in pytorch

### ISSUE THREAD

**Issue by Yingzhu-Zhao** [espnet/espnet#1084]
I use librispeech recipe and running train_100 data. However, when it finish training one epoch, there is one KeyError: 'validation/main/loss' error.

Exception in main training loop: 'validation/main/loss'
Traceback (most recent call last):
  File "/home/yingzhu.zhao/expts/espnet0630/tools/venv/lib/python3.6/site-packages/chainer/training/trainer.py", line 318, in run
    if entry.trigger(self):
  File "/home/yingzhu.zhao/expts/espnet0630/tools/venv/lib/python3.6/site-packages/chainer/training/triggers/minmax_value_trigger.py", line 52, in __call__
    value = float(stats[key])  # copy to CPU
Will finalize trainer extensions and updater before reraising the exception.
Traceback (most recent call last):
  File "/home/yingzhu.zhao/expts/espnet0630/egs/librispeech/asr1/../../../espnet/bin/asr_train.py", line 373, in <module>
    main(sys.argv[1:])
  File "/home/yingzhu.zhao/expts/espnet0630/egs/librispeech/asr1/../../../espnet/bin/asr_train.py", line 361, in main
    train(args)
  File "/home/yingzhu.zhao/expts/espnet0630/espnet/asr/pytorch_backend/asr.py", line 468, in train
    trainer.run()
  File "/home/yingzhu.zhao/expts/espnet0630/tools/venv/lib/python3.6/site-packages/chainer/training/trainer.py", line 349, in run
    six.reraise(*exc_info)
  File "/home/yingzhu.zhao/expts/espnet0630/tools/venv/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/home/yingzhu.zhao/expts/espnet0630/tools/venv/lib/python3.6/site-packages/chainer/training/trainer.py", line 318, in run
    if entry.trigger(self):
  File "/home/yingzhu.zhao/expts/espnet0630/tools/venv/lib/python3.6/site-packages/chainer/training/triggers/minmax_value_trigger.py", line 52, in __call__
    value = float(stats[key])  # copy to CPU
KeyError: 'validation/main/loss'
# Accounting: time=501 threads=1

It only happen after training one epoch successfully.

**Comment by ShigekiKarita** [comment]
How many iterations did you have in one epoch? If it was smaller than 100, decrease report interval by this option
https://github.com/espnet/espnet/blob/f1bb2416de55f14610d291e3c95dde1ec5028d7c/espnet/bin/asr_train.py#L55

**Comment by Yingzhu-Zhao** [comment]
one epoch have 3700 iteration

^[[J     total [..................................................]  0.98%
this epoch [################################################..] 97.63%
      3700 iter, 0 epoch / 100 epochs
    7.8019 iters/sec. Estimated time to finish: 13:21:43.525474.
^[[4A^[[J/home/yingzhu.zhao/expts/espnet0630/tools/venv/lib/python3.6/site-packages/sklearn/externals/joblib/ext
ernals/cloudpickle/cloudpickle.py:47: DeprecationWarning: the imp module is deprecated in favour of importlib; s
ee the module's documentation for alternative uses
  import imp
Exception in main training loop: 'validation/main/loss'

**Comment by Yingzhu-Zhao** [comment]
I use the default e2e_transformer tuning parameters.

**Comment by Yingzhu-Zhao** [comment]
Also it has this message:
cloudpickle.py:47: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp

**Comment by kan-bayashi** [comment]
I have some questions:
- What is your environment? 
   Please show the info via `cd egs/librispeech/asr1 && . ./path.sh && show_result.sh`.
- Is this error happened when you train from scratch? (Didn't you use `--resume` option?)

**Comment by Yingzhu-Zhao** [comment]
# RESULTS
## Environments
- date: `Thu Aug 15 12:39:38 CST 2019`
/home/yingzhu.zhao/expts/espnet0630/tools/venv/lib/python3.6/site-packages/chainer/backends/cuda.py:143: UserWarning: cuDNN is not enabled.
Please reinstall CuPy after you install cudnn
(see https://docs-cupy.chainer.org/en/stable/install.html#install-cudnn).
  'cuDNN is not enabled.\n'
- python version: `3.6.8 |Anaconda, Inc.| (default, Dec 30 2018, 01:22:34)  [GCC 7.3.0]`
- espnet version: `espnet 0.4.0`
- chainer version: `chainer 6.0.0`
- pytorch version: `pytorch 0.4.1`
- Git hash: `f6b55b38a8b5e12a7b88df887dd7d5aa5cd0f6e0`

Yes train from scratch, didn't use --resume option

**Comment by kan-bayashi** [comment]
One more question:
- Did you use multiple gpu in training?

**Comment by Yingzhu-Zhao** [comment]
yes use 3 gpu

**Comment by kan-bayashi** [comment]
OK. 
Then, could you check whether the same error will be occurred with a single gpu?

**Comment by Yingzhu-Zhao** [comment]
ok thanks let me see

**Comment by kan-bayashi** [comment]
I checked the behavior with transformer + 3 gpus in an4 recipe, but I cannot reproduce your error.

**Comment by Yingzhu-Zhao** [comment]
when I first time run it, it does not have this error, then I added stochastic resnet in encoder_layer and it has this error, but when I revert it back, the error persists

**Comment by kan-bayashi** [comment]
I'm not sure your code is correctly reverted.
Make sure report function is correctly working.
https://github.com/espnet/espnet/blob/7e4fa82740f484006a0bf0c5c81dc5d3c8acf923/espnet/nets/pytorch_backend/e2e_asr_transformer.py#L224
And evaluator is correctly set.
https://github.com/espnet/espnet/blob/7e4fa82740f484006a0bf0c5c81dc5d3c8acf923/espnet/asr/pytorch_backend/asr.py#L465

**Comment by Yingzhu-Zhao** [comment]
Thanks I find I miss the evaluator.

**Comment by AleiChan** [comment]
I see same error, please help me how to deal with. Thanks.

**Comment by AleiChan** [comment]
@zyzpower
