### ISSUE TITLE
How to recognize OOV's neighbors?

### ISSUE THREAD

**Issue by robothubtokyo** [espnet/espnet#1089]
We are trying CSJ recipe and got good results.
When there is an OOV in the sentence, however, some of the OOV's neighbor words cannot be recognized too.
What can we do to recognize such words?

**Comment by sw005320** [comment]
Since the encoder-decoder model has never seen the OOV in a sentence, this OOV may break the context as well, but not sure. 

> What can we do to recognize such words?

This is a difficult issue and there are a lot of studies.
The most straightforward way is to add data that includes OOV.
