### ISSUE TITLE
chainer is not working with `--ngpu 0`

### ISSUE THREAD

**Issue by ShigekiKarita** [espnet/espnet#1091]
In my environment `master`, `egs/mini_an4/run.sh --ngpu 0 --backend chainer` is not working now. I attached train.log
[train.log](https://github.com/espnet/espnet/files/3504860/train.log)

**Comment by sw005320** [comment]
@Fhrozen, can you follow up it?
We may need to have an integration test (https://github.com/espnet/espnet/blob/master/ci/test_integration.sh) for chainer.

**Comment by Fhrozen** [comment]
Ok, I will check it . Not sure why is using cupy.ndarray.
