### ISSUE TITLE
question:when I use Transformer model for ASR, how to set the beamsearch size?

### ISSUE THREAD

**Issue by zqs01** [espnet/espnet#1094]
When I use Transformer model for ASR without language model, I set the "beam-size:1" in the "decode.yaml" and the result is very good, but when I adjust the "beam-size:10", the result is so bad. Why does this happen? Is the beam size not normally set to 10?

**Comment by sw005320** [comment]
Can you report the errors in more details (insertion, deletion, and substitution errors)?

**Comment by ShigekiKarita** [comment]
Did you use Transformer with CTC? Without CTC and LM, I met a similar problem. You can check what hyps are inside beam, by `./run.sh --stage 5 --verbose 2 ...`. Sometimes, the large beam gets very wired hyps when it was large. I also found the beam size = 2 .. 4 might be ok at that time.

**Comment by zqs01** [comment]
@ShigekiKarita I only used Transformer. The same problem with you. I will try the method you said. Thank you!
