### ISSUE TITLE
chime5 e2e model trained with beamformed data

### ISSUE THREAD

**Issue by Peidong-Wang** [espnet/espnet#1114]
The chime5 folder only contains the results of the e2e model trained using the recordings of worn microphones.

I took a look at  espnet/milestones and did not find a plan in v0.5.2 or v0.6.0 for chime5 e2e model trained on beamformed data, which should be straightforward. 

What is the reason of the missing result using beamformed training data? I just started digging into chime5 data so forgive me for any silly questions.

**Comment by sw005320** [comment]
Hi @Peidong-Wang, thanks for pointing out the issue. We actually tried several data augmentation, but we still cannot get good improvement, although we did not try to include the beamformed data that you suggested. This would help to improve the performance to some extent I believe, but we may have some more fundamental issues for the CHiME-5 data.

**Comment by Peidong-Wang** [comment]
I see. Thanks for your reply.

**Comment by Peidong-Wang** [comment]
I saw from DIHARD 2 website that chime6 data is being prepared. Will it solve the problems in chime5?

**Comment by sw005320** [comment]
I don't think so. We would not change the training data basically.

**Comment by Peidong-Wang** [comment]
OK. Thanks.
