### ISSUE TITLE
A question about the implementation of RNNP? 

### ISSUE THREAD

**Issue by Marcovaldong** [espnet/espnet#1115]
@takenori-y @sw005320 @ShigekiKarita I noticed that you have implemented the rnn with projection layer. However, I found that you just added a linear layer after the lstm/gru layer, which is different with the idea of lstmp in [the original paper](https://static.googleusercontent.com/media/research.google.com/zh-CN//pubs/archive/43905.pdf). 

In original paper, lstmp layer will reduces the number of parameters, but this implementation does increases the number of parameters. In your experiments, is there an improvement by using your rnnp?

**Comment by sw005320** [comment]
The original paper's way cannot be easily implemented in the cudnn interface. We could implement it by ourselves but it's very slow compared with the current one based on cudnn.

**Comment by Marcovaldong** [comment]
@sw005320  emm, is there an improvement by using your rnnp?

**Comment by ShigekiKarita** [comment]
For training speed, I think without P is faster because it is pure CUDA fused layers by cudnn.

**Comment by Marcovaldong** [comment]
@ShigekiKarita enen, the focus of my current job is to improve the performance, so I want to know the implementation of lstmp and its performance. I'm looking for other structures which can achieve lower cer.

**Comment by ShigekiKarita** [comment]
Try Transformer. We rewrote many `egs/*/asr1/conf/train.yaml` for Transformer.

**Comment by Marcovaldong** [comment]
I implemented [the lstmp](https://github.com/Marcovaldong/lstmp.pytorch) last week, and I got a better performance using it. 

I'll try transformer.

**Comment by sw005320** [comment]
Sounds very cool.
How about the speed? (We may get some speed improvement in theory although cudnn LSTM is well optimized and may not outperform it).

**Comment by Marcovaldong** [comment]
@sw005320  I didn't see the obvious speed decay. I think the current decay is acceptable.

**Comment by sw005320** [comment]
This is very cool!
Can we port your implementation to espnet?

**Comment by Marcovaldong** [comment]
@sw005320  I'll do it when I am not busy.

**Comment by ShigekiKarita** [comment]
👍
