### ISSUE TITLE
missing test_set_iwslt2019.en directory in how2

### ISSUE THREAD

**Issue by sw005320** [espnet/espnet#1116]
@hirofumi0810, `how2/asr1/run.sh` is failed due to the missing test_set_iwslt2019.en directory, e.g., 
```
utils/split_scp.pl: Error opening input scp file data/test_set_iwslt2019.en/feats.scp: No such file or directory
```
Could you fix it?

**Comment by hirofumi0810** [comment]
Is test_set_iwslt2019 installed in `data/local/`?

**Comment by sw005320** [comment]
I think so. I found data/test_set_iwslt2019 but not data/test_set_iwslt2019.en

**Comment by sw005320** [comment]
Is it ok to use test_set_iwslt2019 instead of test_set_iwslt2019.en?
