### ISSUE TITLE
Why transformer on librispeech need 100 epochs？

### ISSUE THREAD

**Issue by Magic-Bubble** [espnet/espnet#1118]
I run the transformer model on LibriSpeech, but it need 100 epochs. Is it possible to achieve the same effect in fewer epochs? I see BiLSTM with just 10 epochs.

**Comment by ShigekiKarita** [comment]
It seems to depends on dataset size and regularization. When we did not use SpecAugment in LibriSpeech, it did not improve after 70 epochs. However, when we use it, it improved its accuracy even after 100 epochs.

**Comment by kan-bayashi** [comment]
And the required time of Transformer per epoch is much shorter than BiLSTM.

**Comment by Magic-Bubble** [comment]
OK. Have you tried decrease accum_grad to 1? It seems the number of optimizer steps within each epoch are small, maybe it leads to the large epochs?

**Comment by kan-bayashi** [comment]
Transformer requires a large batchsize to achieve good performance.
So if you use accum_grad=1, it causes serious performance degradation.

**Comment by Magic-Bubble** [comment]
> Transformer requires a large batchsize to achieve good performance.
> So if you use accum_grad=1, it causes serious performance degradation.

That's true. I have tried accum_grad=1, it speed up convergence in the first epoch, but diverged after that. Thank you very much!

**Comment by Shujian2015** [comment]
Have anyone tried even more epochs? I saw a post mentioned that SpecAug authors used 900 epochs for Libri (source: https://groups.google.com/d/msg/kaldi-help/_eer7j6SmKQ/LXnoGVvfAQAJ).

**Comment by sw005320** [comment]
Probably, yes. We actually observed some improvements, but we did not continue it as the gain was very small.

**Comment by kan-bayashi** [comment]
I tried until 150 epochs but no improvement was observed.
But if we use a larger model, might be different.
