### ISSUE TITLE
environmental variables for warp-transducer during installation

### ISSUE THREAD

**Issue by Peidong-Wang** [espnet/espnet#1123]
I encountered an error mentioned in [https://github.com/HawkAaron/warp-transducer/issues/15](https://github.com/HawkAaron/warp-transducer/issues/15) during installation (Ubuntu 16.04, Cuda 10.0) and solved it by adding the following environmental variables to my bash profile (after the variables for espnet):

export CUDA_TOOLKIT_ROOT_DIR=$CUDA_HOME
export LD_LIBRARY_PATH="$CUDA_HOME/extras/CUPTI/lib64:$LD_LIBRARY_PATH"
export LIBRARY_PATH=$CUDA_HOME/lib64:$LIBRARY_PATH
export CFLAGS="-I$CUDA_HOME/include $CFLAGS"

I think it may worth adding them to the installation instructions if you feel it is necessary. Or this post can simply be a reference for others facing the same problem.

**Comment by sw005320** [comment]
Thanks.
I actually found that we only need to add 
```
export CFLAGS="-I$CUDA_HOME/include $CFLAGS"
```
to https://github.com/espnet/espnet#step-1-setting-of-the-environment-for-gpu-support
I'll modify the description.
