### ISSUE TITLE
spm_train

### ISSUE THREAD

**Issue by bobchennan** [espnet/espnet#1132]
same problem as https://github.com/pytorch/fairseq/pull/972 for must_c

**Comment by sw005320** [comment]
Thanks, @bobchennan for your report.
@ShigekiKarita, can you fix it?

**Comment by ShigekiKarita** [comment]
cc @hirofumi0810 do you think this change is reasonable?

**Comment by hirofumi0810** [comment]
@ShigekiKarita This is fine.

**Comment by ShigekiKarita** [comment]
Can we remove your `.replace("\'", ""))`?
https://github.com/espnet/espnet/blob/9f51838d174ef159254f61dd5d7a466e70f84cc2/utils/spm_train#L17

**Comment by hirofumi0810** [comment]
@ShigekiKarita Yes. We can follow fairseq in exactly the same way.

**Comment by ShigekiKarita** [comment]
Thanks. I will send PR soon.
