### ISSUE TITLE
RNN-transducer on an4 corpus

### ISSUE THREAD

**Issue by Peidong-Wang** [espnet/espnet#1144]
I saw a RNN-transducer config in the voxforge folder [https://github.com/espnet/espnet/tree/master/egs/voxforge/asr1/conf/tuning](https://github.com/espnet/espnet/tree/master/egs/voxforge/asr1/conf/tuning) and tried it on an4. The results are bad (~86% error rate).

Is RNN-transducer working on voxforge, or is it still under development?

**Comment by b-flo** [comment]
Hi,

It is still under development however performances should not be so bad. As example I just reported results on voxforge for training from scratch and with pre-init : https://github.com/espnet/espnet/pull/1103#issuecomment-524901199

Which config did you use?

**Comment by b-flo** [comment]
When did you update your espnet and how did you train (cpu, gpu)? Also, I changed some things in #1129 as I had some degradations with LSTMCell.

**Comment by b-flo** [comment]
I attached the conf I used in edit 2. Could you try it? (rename to .yaml, it's not supported by github)
[train_transducer.txt](https://github.com/espnet/espnet/files/3542663/train_transducer.txt)
[decode_transducer.txt](https://github.com/espnet/espnet/files/3542665/decode_transducer.txt)

**Comment by b-flo** [comment]
Hum, I recommend updating your espnet please. If you don't have 8.7% CER on test with the configs I sent, I would be glad to have the logs! I trained on two different servers with one gpu and ended-up with the same score.
Thank you :)

**Comment by b-flo** [comment]
The configs I sent are for an4. I just reinstalled espnet on a new server and I end up with the same CER. Hum.

**Comment by b-flo** [comment]
Yes I have 8.7% CER on the an4 with the configs file I sent and by setting `recog_opts=""` in decoding stage!

**Comment by b-flo** [comment]
Ok great, thanks! You had the previous implementation, there was a problem in vanilla transducer I have to investigate.

**Comment by fotwo** [comment]
@b-flo , I worked on voxforge 'it' corpus as [this merge](https://github.com/espnet/espnet/pull/1129#issue-310426756) mentioned. 
I used the standard data preparation scripts, while the number of sentences in 'dt_it' is only 639, and the CER is much worse than the reported ['16.1%'](https://github.com/espnet/espnet/pull/1129#issue-310426756) via using configuration [file](egs/voxforge/asr1/conf/tuning/train_transducer.yaml).
My results:
```
exp/tr_it_pytorch_train_transducer/decode_dt_it_decode_transducer/result.txt`
 # | SPKR             | # Snt  # Wrd | Corr    Sub    Del    Ins    Err  S.Err |
 # | Sum/Avg          |  639   47976 | 76.4    8.2   15.4    3.6   27.2   99.8 |
exp/tr_it_pytorch_train_transducer/decode_dt_it_decode_transducer/result.wrd.txt
# | SPKR             | # Snt  # Wrd | Corr    Sub     Del    Ins    Err   S.Err |
# | Sum/Avg          |  639    7779 | 42.1   44.4    13.4    4.9   62.8    99.8 |
```
Any suggestions? Thanks.

**Comment by b-flo** [comment]
Hi!

Why do you have a lower number of sentences/characters? It should be :  `1082 79133`. I can't really say nor compare if I don't know which sentences where removed.

**Comment by fotwo** [comment]
@b-flo ,I find a large number of errors in `make_trans.log`, like:
```
The transcript for 'it-0155'(user 'AR4CAD-20130328-lki') is not properly normalized - skipped!
QUANDO SI FURONO RIMESSI DALLO STUPORE IL CORSARO ED IL SUO COMPAGNO ERANO GIà LONTANI
```
the characters like `à` seems that cannot be tackled.

**Comment by b-flo** [comment]
It sounds like an encoding problem.
The only things I touched is config files and run script. I'll check
