### ISSUE TITLE
Where is dict file of librispeech-asr1 demo?

### ISSUE THREAD

**Issue by potato-inoue** [espnet/espnet#1149]
I want the dict file of librispeech-asr1 demo to compare one of libritts-tts1 demo. (https://github.com/espnet/espnet/blob/master/egs/librispeech/asr1/RESULTS.md#pytorch-large-transformer-with-specaug-4-gpus--large-lm)
The dict is not included in model files.
Can I generate the same dict by using egs/librispeech/asr1/run.sh ?

**Comment by kan-bayashi** [comment]
You can find it in `model.json`.
It is saved as `char_list`.

**Comment by potato-inoue** [comment]
I found it. Thanks.

I don't understand what the token `"笆 ~~~" ` indicates.
Is there reference for understanding this token?

```
"<blank>",
"<unk>",
"'",
"A",
"ABETH",
...
"笆、BANDON",
...
"笆仝ROUGHT",
....
```

**Comment by potato-inoue** [comment]
I solved this problem.
"笆、BANDON"  is garbled text by editor.
"▁BANDON" is correct text and indicates word.
