### ISSUE TITLE
warpctc issue

### ISSUE THREAD

**Issue by sw005320** [espnet/espnet#115]
It seems that warpctc is not correctly installed, which makes travis check failed.

**Comment by ShigekiKarita** [comment]
maybe we have to fix the warpctc version by git submodule. breaking change
of warpctc happens too frequently for us. do you agree?

2018/03/10 11:55 "Shinji Watanabe" <notifications@github.com>:

**Comment by sw005320** [comment]
Yes. BTW, I used to use hash to manage this kind of problems, but git submodule has more benefit?

**Comment by ShigekiKarita** [comment]
Do you use hash only for detecting change? Git submodule is used for git
clone & checkout the specific commit.

2018/03/10 12:07 "Shinji Watanabe" <notifications@github.com>:

**Comment by ShigekiKarita** [comment]
If you mean 'hash' as git commit id, git submodule is same basically.

2018/03/10 12:12 "Karita Shigeki" <shigekikarita@gmail.com>:

**Comment by sw005320** [comment]
Yes, I'm talking about SHA1 hash

**Comment by ShigekiKarita** [comment]
BTW we should follow the latest warpctc version because it fixed the length / batch normalization that we patched in espnet.

**Comment by r9y9** [comment]
What errors are you seeing? It would be nice to report it to https://github.com/SeanNaren/warp-ctc/issues.

**Comment by ShigekiKarita** [comment]
@r9y9 there are two errors
- python2 cannot import warpctc https://travis-ci.org/espnet/espnet/jobs/351600502#L843
- our patched normalization conflicts to the warpctc_pytorch update https://travis-ci.org/espnet/espnet/jobs/351600503

the first one might related to your PR? https://github.com/SeanNaren/warp-ctc/pull/27

**Comment by r9y9** [comment]
@ShigekiKarita Thanks, I was thinking I fixed a py2 issue... I will take a look later today for the first one.

**Comment by r9y9** [comment]
@ShigekiKarita Sorry, that was my fault. The import error should be fixed by https://github.com/SeanNaren/warp-ctc/pull/31

**Comment by ShigekiKarita** [comment]
@r9y9 great! we will fix our normalization issue.

**Comment by r9y9** [comment]
@ShigekiKarita https://github.com/SeanNaren/warp-ctc/pull/31 PR was merged. Please let me know if it doesn't work.

**Comment by ShigekiKarita** [comment]
I will update warp-ctc to HEAD after merging Makefile in #125
