### ISSUE TITLE
Error training on Fisher/Switchboard data

### ISSUE THREAD

**Issue by dtkettler** [espnet/espnet#1150]
I'm trying to run the fisher_swbd recipe.  I have all the data, set the paths appropriately, and the recipe successfully makes it through the Data preparation and Feature Generation phases so something should be right.  But then this happens:

```
stage 2: Dictionary and Json Data Preparation
make a non-linguistic symbol list
[[skip]]
[laughter]
[laughter]-
[noise]
[noise]-
[pause]
[sneeze]
make a dictionary
54 data/lang_1char/train_units.txt
make json files
/home/dkettler/espnet/egs/fisher_swbd/asr1/../../../utils/data2json.sh --feat dump/train/deltafalse/feats.scp --nlsyms data/lang_1char/non_lang_syms.txt data/train data/lang_1char/train_units.txt
/home/dkettler/espnet/egs/fisher_swbd/asr1/../../../utils/feat_to_shape.sh --cmd run.pl --nj 1 --filetype  --preprocess-conf  --verbose 0 dump/train/deltafalse/feats.scp data/train/tmp-ZjF1A/input/shape.scp
/home/dkettler/espnet/egs/fisher_swbd/asr1/../../../utils/data2json.sh --feat dump/rt03_trim/deltafalse/feats.scp --nlsyms data/lang_1char/non_lang_syms.txt data/rt03_trim data/lang_1char/train_units.txt
/home/dkettler/espnet/egs/fisher_swbd/asr1/../../../utils/feat_to_shape.sh --cmd run.pl --nj 1 --filetype  --preprocess-conf  --verbose 0 dump/rt03_trim/deltafalse/feats.scp data/rt03_trim/tmp-M891B/input/shape.scp
/home/dkettler/espnet/egs/fisher_swbd/asr1/../../../utils/data2json.sh --feat dump/eval2000/deltafalse/feats.scp --nlsyms data/lang_1char/non_lang_syms.txt data/eval2000 data/lang_1char/train_units.txt
/home/dkettler/espnet/egs/fisher_swbd/asr1/../../../utils/feat_to_shape.sh --cmd run.pl --nj 1 --filetype  --preprocess-conf  --verbose 0 dump/eval2000/deltafalse/feats.scp data/eval2000/tmp-JXa57/input/shape.scp
Traceback (most recent call last):
  File "/home/dkettler/espnet/egs/fisher_swbd/asr1/../../../utils/merge_scp2json.py", line 223, in <module>
    .format(nutt, info[1], line))
RuntimeError: Format error 147th line in data/eval2000/tmp-JXa57/output/text.scp:  Expecting "<key> <value>":
>>> en_4170-A_043468-043489
```

Clearly there is something wrong with the formatting of the eval2000 data but the actual error is a bit inscrutable to me.  I tried looking at data/eval2000/tmp-JXa57/output/text.scp but it doesn't even exist.  The whole tmp-JXa57 directory doesn't in fact.  I guess it was deleted because it was tmp?  dump/eval2000/deltafalse/feats.scp does exist and even has a line with "en_4170-A_043468-043489" on it...but it looks just like every other line.  The "`Expecting <key> <value>`" error made me think something might be missing but that does not appear to be the case.

Any ideas?

**Comment by kan-bayashi** [comment]
Could you try to use `--allow-one-column` option?
https://github.com/espnet/espnet/blob/3f67cab64690806b6db8d46c32b2ddac8cc93479/egs/swbd/asr1/run.sh#L172-L173

**Comment by dkettlerveritone** [comment]
Thanks, I added that and it seemed to help.  Made it to stage 3 but it's still working away so I'll have to wait to see if any more problems pop up.

**Comment by qmpzzpmq** [comment]
how is going with it at stage 3?

**Comment by sw005320** [comment]
I strongly recommend you to also check `swbd/asr1/run.sh`. We recently revisited this recipe and got some reasonable performance compared with other studies.

**Comment by dkettlerveritone** [comment]
> how is going with it at stage 3?

Made it to stage 4 but I got an error there which seemed to be GPU memory related (running this on 2080 Tis).  Tried running it again with a smaller batch size and it seems to be OK now.  It's still going of course but I've finished the first epoch at least so it's should be fine.

> I strongly recommend you to also check `swbd/asr1/run.sh`. We recently revisited this recipe and got some reasonable performance compared with other studies.

What's different in that recipe exactly?  Looks like it's just using Switchboard data but not Fisher.

**Comment by sw005320** [comment]
> What's different in that recipe exactly? Looks like it's just using Switchboard data but not Fisher.

As far as I know, yes.

**Comment by dkettlerveritone** [comment]
So my training with the fisher_swbd recipe finished but the performance was very disappointing (WER int he 40s).  I thought I would give the swbd recipe mentioned a shot but I'm getting this error when I try to run that one:

```
stage 0: Data preparation
patching file data/local/dict_nosp/lexicon0.txt
Prepared input dictionary and phone-sets for Switchboard phase 1.
Switchboard-1 data preparation succeeded.
utils/fix_data_dir.sh: filtered data/train/segments from 264333 to 0 lines based on filter /tmp/kaldi.VKvP/recordings.
utils/fix_data_dir.sh: filtered data/train/wav.scp from 4876 to 0 lines based on filter /tmp/kaldi.VKvP/recordings.
utils/fix_data_dir.sh: filtered data/train/reco2file_and_channel from 4876 to 0 lines based on filter /tmp/kaldi.VKvP/recordings.
fix_data_dir.sh: no utterances remained: not proceeding further.
```

Not really sure what's going on there...
