### ISSUE TITLE
tensorboard summary values are different with the value of console log 

### ISSUE THREAD

**Issue by fanlu** [espnet/espnet#1161]
<img width="1674" alt="image" src="https://user-images.githubusercontent.com/1620875/64063369-30bc9680-cc26-11e9-8302-4d9216e58534.png">
<img width="1497" alt="image" src="https://user-images.githubusercontent.com/1620875/64063381-492cb100-cc26-11e9-8490-0674c064c2d2.png">
such as the value of main/acc at iter 1101 is 0.03810,but the value of console log is 0.0235669.
and all values (main/loss   main/loss_ctc  main/loss_att main/acc) between this two logs are different.

**Comment by ShigekiKarita** [comment]
how about validation?

**Comment by fanlu** [comment]
the validation value of this two log is the same.

**Comment by ShigekiKarita** [comment]
Can you also check exp/*/results/log? Which one is same to the file?

I suspect that tb might report values at iter while the console logger
reports avg values in training.

In validation, we manually trigger tb summary writer after epoch.

2019年9月1日(日) 1:02 fanlu <notifications@github.com>:

**Comment by fanlu** [comment]
exp/train_sp_pytorch_spec3_bs128_niter4/train.log is same to exp/train_sp_pytorch_spec3_bs128_niter4/results/log.
What do you mean? Does console log report the avg value of last 100 iter per report iteration?
