### ISSUE TITLE
unexpected keyword argument 'reduce'.  when run to stage=4, asr_train.py,  warp_ctc.CTCLoss(size_average=True, reduce=reduce)  

### ISSUE THREAD

**Issue by mfch101** [espnet/espnet#1171]
![image](https://user-images.githubusercontent.com/12197118/64131378-bf820c80-cdfa-11e9-9a21-573924a59f63.png)

self.ctc_loss = warp_ctc.CTCLoss(size_average=True, reduce=reduce)
 27 TypeError: __init__() got an unexpected keyword argument 'reduce'

**Comment by sw005320** [comment]
Which version and what task?
We have several test scripts for the CTC loss and we would not have such errors in the normal case.

**Comment by mfch101** [comment]
I have soved the problem. I  exchange an another version of warp-ctc with the parameter reduce in wrapctc_loss function.

**Comment by xcrpkuss** [comment]
> 我解决了这个问题。我在wrapctc_loss函数中使用参数reduce交换了warp-ctc的另一个版本。

which version will match pytorch 1.1.0, I also meet this problem.
In the Makefile .it says I can install by pip,but I failed.

**Comment by 3139725181** [comment]
> I have soved the problem. I exchange an another version of warp-ctc with the parameter reduce in wrapctc_loss function.

which version are you use?
Can you tell me where to download it?
