### ISSUE TITLE
question: how should I understand the att_ws files?

### ISSUE THREAD

**Issue by zqs01** [espnet/espnet#1176]
Hello, everyone! I only used the Transformer model without LM or CTC. After running the code, I can get the att_ws file. But I can't understand why there are three common file names? As shown below, there are three "encoder.encoders.0.self_attn.ep.100.png" in each epoch. How should I understand these?
Thank you in advance!
![image](https://user-images.githubusercontent.com/40491290/64258234-785e5d80-cf59-11e9-804d-31150ebbbd69.png)

**Comment by kan-bayashi** [comment]
`4k0c0303` represents utterance id.
So these three file are corresponding to different utterances.

**Comment by zqs01** [comment]
Oh, I get it. Thank you
