### ISSUE TITLE
How could I get number of parameters in model?

### ISSUE THREAD

**Issue by DTDwind** [espnet/espnet#1177]
Hello~
I want to get  the number of parameters in model, how could I do it best?
THX

**Comment by kan-bayashi** [comment]
Try following snippet.
```python
model_parameters = filter(lambda p: p.requires_grad, model.parameters())
params = sum([np.prod(p.size()) for p in model_parameters])
```

See also:
https://discuss.pytorch.org/t/how-do-i-check-the-number-of-parameters-of-a-model/4325/7

**Comment by DTDwind** [comment]
In the exp/**/result I can only get snapshot.ep.* , model.loss.best and model.json, they only have the information of the model, but don't have the architecture, so I can't not use touch.load the model.
It will say "AttributeError: 'collections.OrderedDict' object has no attribute 'parameters'"

**Comment by kan-bayashi** [comment]
You can use our utility to load model.
```python
from espnet.asr.pytorch_backend.asr_init import load_trained_model
model, _ = load_trained_model("/path/to/your_snapshot_or_model.loss.best")
```

**Comment by DTDwind** [comment]
I get error for this code.
![image](https://user-images.githubusercontent.com/22238266/64310989-ff045080-cfd4-11e9-966b-3d7736801fcf.png)

**Comment by kan-bayashi** [comment]
Did you modify `model.json`?

**Comment by DTDwind** [comment]
I didn't modify model.json, but I modified the node of VGG2L in encoders.py, and change its name to 
 VGGC.

**Comment by kan-bayashi** [comment]
If you do not want to revert, just count from snapshot:

```
[ins] In [11]: snapshot = torch.load("snapshot.ep.1", map_location="cpu")
[ins] In [12]: print(sum([np.prod(p.size()) for p in snapshot["model"].values()]))
26041386.0
```

**Comment by DTDwind** [comment]
It work!!!
Thank you very much <3
