### ISSUE TITLE
Error in install related to gcc version warp-ctc

### ISSUE THREAD

**Issue by yjw123456** [espnet/espnet#1178]
Dear all,

I meet this issue during install
The thing is I do not have the sudo authority of the server. The version of gcc on the server is 4.85 
and I install my own gcc 6 in anaconda.

The command I used  is:
make KALDI=/data1/tomasyu/tools/kaldi  PYTHON_VERSION=3.7 TH_VERSION=1.0.1 CUDA_VERSION=9.0

Can anyone provide some help? Thanks a lot!

########################################################################
-- Build files have been written to: /data1/tomasyu/tools/espnet/tools/warp-ctc/build
make[1]: Entering directory `/data1/tomasyu/tools/espnet/tools/warp-ctc/build'
make[2]: Entering directory `/data1/tomasyu/tools/espnet/tools/warp-ctc/build'
make[3]: Entering directory `/data1/tomasyu/tools/espnet/tools/warp-ctc/build'
[ 11%] Building NVCC (Device) object CMakeFiles/warpctc.dir/src/warpctc_generated_reduce.cu.o
In file included from /usr/local/cuda/include/cuda_runtime.h:78:0,
                 from <command-line>:0:
/usr/local/cuda/include/host_config.h:119:2: error: #error -- unsupported GNU version! gcc versions later than 5 are not supported!
 #error -- unsupported GNU version! gcc versions later than 5 are not supported!
  ^~~~~
CMake Error at warpctc_generated_reduce.cu.o.cmake:219 (message):
  Error generating
  /data1/tomasyu/tools/espnet/tools/warp-ctc/build/CMakeFiles/warpctc.dir/src/./warpctc_generated_reduce.cu.o

make[3]: *** [CMakeFiles/warpctc.dir/src/warpctc_generated_reduce.cu.o] Error 1
make[3]: Leaving directory `/data1/tomasyu/tools/espnet/tools/warp-ctc/build'
make[2]: *** [CMakeFiles/warpctc.dir/all] Error 2
make[2]: Leaving directory `/data1/tomasyu/tools/espnet/tools/warp-ctc/build'
make[1]: *** [all] Error 2
make[1]: Leaving directory `/data1/tomasyu/tools/espnet/tools/warp-ctc/build'
. venv/bin/activate; pip install cffi
Requirement already satisfied: cffi in ./venv/lib/python3.7/site-packages (1.12.3)
Requirement already satisfied: pycparser in ./venv/lib/python3.7/site-packages (from cffi) (2.19)
. venv/bin/activate; cd warp-ctc/pytorch_binding && python setup.py install # maybe need to: apt-get install python-dev
Could not find libwarpctc.so in ../build.
Build warp-ctc and set WARP_CTC_PATH to the location of libwarpctc.so (default is '../build')
make: *** [warp-ctc.done] Error 1
########################################################################

**Comment by sw005320** [comment]
@ysk24ok, do you know how to deal with it?

**Comment by kan-bayashi** [comment]
Why don’t you add conda’s gcc-6 installation before following line?
https://github.com/espnet/espnet/blob/04018e33ec50ddee87d63e91ddd93e6c19310695/tools/Makefile#L91

**Comment by ysk24ok** [comment]
Since the log says `unsupported GNU version! gcc versions later than 5 are not supported!`, why not installing older version of gcc in anaconda?
Building warpctc requires gcc>=4.9, so gcc 4.9.X will be fine.

**Comment by Peidong-Wang** [comment]
Maybe due to cuda version? 9.0 might be too old for pytorch 1.0.1 using python 3.7.

**Comment by b-flo** [comment]
@Peidong-Wang This should not be a problem, in my case : pytorch version is `1.0.1.post2`, cuda version is `8.0` and python3 version is `3.7.3`.

**Comment by ShigekiKarita** [comment]
It can be problem because the old CUDA limits gcc version in `#error`.

**Comment by ShigekiKarita** [comment]
I recommend the latest CUDA and GCC.
