### ISSUE TITLE
Only encoder + custom model

### ISSUE THREAD

**Issue by TParcollet** [espnet/espnet#1181]
Hi there !

Thank you for the toolkit 👍  

First, I'm wondering if it would be possible to not perform seq2seq training for ASR. Let's say I have a BLSTM model, and I want to directly train with CTC on it (with TIMIT, for example). Then, I would like to add a custom CNN model before the BLSTM, to finally have a CNN+BLSTM+CTC. Is it feasible ?

Thank you!

**Comment by sw005320** [comment]
Thanks.
This is possible.
Actually, if we set some parameter appropriately, you can switch to pure CTC or attention.
See https://github.com/espnet/espnet#ctc-attention-and-hybrid-ctcattention
Then, you can customize the encoder by yourself to realize CNN+BLSTM+CTC.

**Comment by TParcollet** [comment]
Thank you!
