### ISSUE TITLE
error when decoding TIMIT

### ISSUE THREAD

**Issue by TParcollet** [espnet/espnet#1187]
Hi there,

Just running the run.sh of the TIMIT receipe gives me:
<img width="690" alt="Capture d’écran 2019-09-08 à 16 53 27" src="https://user-images.githubusercontent.com/11910731/64490028-68949100-d259-11e9-85a6-0f4e87745e45.png">

Any idea?

**Comment by ShigekiKarita** [comment]
I also met similar error in that ctc prefix score. Can you try adding an option `--batchsize 0` into `asr_recog.py` in `run.sh`? That disables batch decoding and fixed my case.

**Comment by TParcollet** [comment]
Yep, it's working! Is it a problem only occuring with TIMIT?

**Comment by ShigekiKarita** [comment]
No. I met this in AN4. I will check recent changes in the ctc prefix score.

2019年9月9日(月) 18:50 Parcollet Titouan <notifications@github.com>:

**Comment by TParcollet** [comment]
Great! the results reported with TIMIT are reported as character error rate right? Is it possible to switch to Phoneme Error Rate?

**Comment by b-flo** [comment]
If `trans_type=phn` is set in `run.sh`, PER should be reported instead of CER, no?

**Comment by TParcollet** [comment]
Indeed! Thanks.

**Comment by ShigekiKarita** [comment]
@takaaki-hori can you also check your recent update (i.e., ctc_window) is working with TIMIT and AN4 (mtlalpha=0.5)?

**Comment by ReinholdM** [comment]
> If `trans_type=phn` is set in `run.sh`, PER should be reported instead of CER, no?

Is that only one thing that need to change if I want to model based on phone ? Anything else? My results are unstable now.

**Comment by ReinholdM** [comment]
@b-flo Is that only one thing that need to change if I want to model based on phone ? Anything else? My results are unstable now.

> If `trans_type=phn` is set in `run.sh`, PER should be reported instead of CER, no?

**Comment by b-flo** [comment]
Hi,

> Is that only one thing that need to change if I want to model based on phone ?

I suppose you're asking for TIMIT. In that case, yes, for what I remember.

> My results are unstable now.

Could you elaborate on the "unstable" part? You mean you can't reach reported performances?

**Comment by ReinholdM** [comment]
> Hi,
> 
> > Is that only one thing that need to change if I want to model based on phone ?
> 
> I suppose you're asking for TIMIT. In that case, yes, for what I remember.
> 
> > My results are unstable now.
> 
> Could you elaborate on the "unstable" part? You mean you can't reach reported performances?

@b-flo  Thanks! When I only change "trans_type" from char to phn, PER can just reach 28% ~ 30%. To my knowledge, PER should have 15% ~ 18% performance on TIMIT. So I wanna know whether I ignore something to change extrally.

**Comment by b-flo** [comment]
PER should be between 20.2 and 21.4 with the configuration given in `conf/tuning/trainX.yaml` (https://github.com/espnet/espnet/blob/master/egs/timit/asr1/RESULTS.md). Is that not the case?

@sknadig It seems the link for pre-trained model is missing. Could you add it please?

**Comment by ReinholdM** [comment]
> PER should be between 20.2 and 21.4 with the configuration given in `conf/tuning/trainX.yaml` (https://github.com/espnet/espnet/blob/master/egs/timit/asr1/RESULTS.md). Is that not the case?
> 
> @sknadig It seems the link for pre-trained model is missing. Could you add it please?

@b-flo Thanks! I got it. I just got PER 21.8 when mtl=0.5 are used. I think it becomes normal. Very thanks!

**Comment by sknadig** [comment]
@b-flo I don't have the models now as those experiments were done long ago. I could run them again and upload the models.

**Comment by b-flo** [comment]
@sknadig Sorry for the delayed reply. I don't think that's necessary in the end, sorry for the ping :)
