### ISSUE TITLE
OOP Task Trainer

### ISSUE THREAD

**Issue by ShigekiKarita** [espnet/espnet#1188]
Recently, ESPnet has a lot of duplicated lines in `def train(args): ...` of ASR, ASR-MIX, LM, MT, TTS, ST, etc. It is hard to maintain and update because lots of complicated things (custom fp, data loader, transfer learning) are copy-and-pasted in the huge GOD functions. I wanna unify those duplicated parts. How about unifying these with extensible OOP-based design?

```python
# task-dependent part
class TaskInterface:
    @staticmethod
    def add_arguments(parser):

    def init_dataset(self, ...):

    def init_model(self, ...):

    def init_criterion(self, ...):

    def init_sampler(self, ...):


# task-independent training loop
class TaskRunner:
    def train(self, task: TaskInterface):

    def eval(self, task: TaskInterface):

    def run(self):
```

see also: https://github.com/pytorch/fairseq/blob/master/fairseq/tasks/fairseq_task.py

**Comment by ShigekiKarita** [comment]
I will rework chainer-free trainer #688  soon but we need to discuss this first.

**Comment by kan-bayashi** [comment]
I agree with your idea but I'm wondaring that whether we can remove duplicated lines if we use this OOP design.

**Comment by ShigekiKarita** [comment]
Yeah, I'm also afraid that copying fairseq is not enough for us. My goal is
not just splitting task-dependent and task-independent parts because the
task-dependent part still can be duplicated.

(I believe that TaskRunner is just a common part of existing Trainer and
Evaluator in all the tasks)

However, this idea can make relationship between tasks explicitly (instead
of randomly importing symbols). For example, ASR mix class can be derived
from ASR. And ST class can be derived from ASR and MT.

2019年9月9日(月) 21:28 Tomoki Hayashi <notifications@github.com>:

**Comment by gs5264** [comment]
Are you still going on with the plan?

**Comment by gs5264** [comment]
This will be very helpful for distributed training of pytorch.
