### ISSUE TITLE
Are the RESULTS numbers with or without LM

### ISSUE THREAD

**Issue by siddalmia** [espnet/espnet#1189]
Hi @sw005320 , 

If the numbers mentioned in the RESULTS section is with LM rescoring, would it make sense to add a no LM results as well?

Thanks
Sid

**Comment by siddalmia** [comment]
After looking at some more files. It seems that all the numbers that are presented are with LM rescoring. Would it be possible to present numbers without LM as well? Just so that we know the model capability with and without LM.

**Comment by siddalmia** [comment]
I suppose just running the same decoding with `--lm-weight 0` should do the trick?

**Comment by sw005320** [comment]
We usually use an LM based on shallow fusion during beam search (not n-best rescoring). Yes, we can get the non-LM result with `--lm-weight 0`.

**Comment by lijuan123** [comment]
hi~  Can we use the BeamSearch function with general statistical language model such as n-gram model instead of rnn language model?  Looking forward to your reply, thank you!
