### ISSUE TITLE
Issues with adam and gru using docker image

### ISSUE THREAD

**Issue by bhigy** [espnet/espnet#1191]
Hi everyone,

I am trying to train some models on flickr8k audio captions corpus. I managed to train a baseline successfully using docker image and a configuration close to espnet/egs/chime4/asr1/conf/tuning/train_rnn.yaml. However, if I try to change the optimizer to adam, things break very badly (from ~7% CER to ~86%). Similar issue if I go from LSTM to GRU. Is there any known bug with GRU or adam? Or maybe some other parameter I should change to get reasonable results?

Bertrand

**Comment by sw005320** [comment]
How large is this data? We usually observe such significant degradations (sensitivities of the algorithms) for the small amount of training data (e.g., less than 20 hours). Also, this is related to the initialization, and other initializations may work.

**Comment by bhigy** [comment]
The amount of training data is around 35 hours so that might explain the bad results. Any recommendations on how I can solve the issue, like what can of initialization I should use?
