### ISSUE TITLE
TTS recipes: suggestion to limit frequency range for log-melspectrogram 

### ISSUE THREAD

**Issue by r9y9** [espnet/espnet#1192]
Currently we don't limit the maximum frequency for log-melspectrogram, however, I believe limiting the maximum frequency to 8000kHz or lower (e.g. 7680) alleviates the over-smoothing problem. This will be particularly important when we combine E2E models with a neural vocoder. 

Based on my limited experience though, using a full range of log-melspectrogram seems to suffer from over-smoothing. In my opinion, fmax=8000 (or 7680) is a good start for any dataset. As for the fmin, it highly depends on the dataset so fmin=0 (or 70 maybe?) may be a good choice.

For the reference, here's collected information about the frequency range used by prior work:

| Paper                              | Friendly name | Frequency range |
|------------------------------------|---------------|-----------------|
| https://arxiv.org/abs/1712.05884   | Tacotron 2    | 125 - 7600      |
| https://arxiv.org/abs/1904.04169   | Parrotron     | 125 - 7600      |
| https://arxiv.org/abs/1906.03402   | -             | 80 - 12000      |
| https://arxiv.org/abs/1811.00002 | WaveGlow      | 0 - 8000        |

Note: The table may be updated when I find a new, or feel free to edit it if you have write access to the issue description.

As another point, the WaveNet vocoder seems to have the capability to produce 24kHz good quality of audio using band-limited features. See https://arxiv.org/abs/1907.04927 and https://ieeexplore.ieee.org/document/8682320 for details. 

Any comments are appreciated!

**Comment by kan-bayashi** [comment]
Actually I did not compare so far.
We should limit the range, especially for > 16 kHz datasets.
Let us start to train those models!

**Comment by flip-arunkp** [comment]
Will fmin=125 and  fmax=7600 be applied to the ljspeech/tts1 recipes? Are the wavenet models for ljspeech trained with these limits or with no limits?

**Comment by r9y9** [comment]
Not fully agreed yet. Current pretrained models are trained with no limits, but in future we may consider using band-limited feautures IMO.

**Comment by flip-arunkp** [comment]
thanks
