### ISSUE TITLE
transduce cuDNN error

### ISSUE THREAD

**Issue by qmpzzpmq** [espnet/espnet#1199]
> 2019-09-17 18:14:49,907 (asr_train:290) WARNING: Skip DEBUG/INFO messages
> 2019-09-17 18:14:50,656 (e2e_asr_transducer:138) WARNING: Subsampling is not performed for vgg*. It is performed in max pooling layers at CNN.
> Traceback (most recent call last):
>   File "/data1/tanghaoyu/espnet/egs/voxforge/asr1/../../../espnet/bin/asr_train.py", line 356, in <module>
>     main(sys.argv[1:])
>   File "/data1/tanghaoyu/espnet/egs/voxforge/asr1/../../../espnet/bin/asr_train.py", line 343, in main
>     train(args)
>   File "/data1/tanghaoyu/espnet/espnet/asr/pytorch_backend/asr.py", line 359, in train
>     model = model.to(device=device, dtype=dtype)
>   File "/data1/tanghaoyu/espnet/tools/venv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 381, in to
>     return self._apply(convert)
>   File "/data1/tanghaoyu/espnet/tools/venv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 187, in _apply
>     module._apply(fn)
>   File "/data1/tanghaoyu/espnet/tools/venv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 187, in _apply
>     module._apply(fn)
>   File "/data1/tanghaoyu/espnet/tools/venv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 187, in _apply
>     module._apply(fn)
>   [Previous line repeated 1 more time]
>   File "/data1/tanghaoyu/espnet/tools/venv/lib/python3.7/site-packages/torch/nn/modules/rnn.py", line 117, in _apply
>     self.flatten_parameters()
>   File "/data1/tanghaoyu/espnet/tools/venv/lib/python3.7/site-packages/torch/nn/modules/rnn.py", line 113, in flatten_parameters
>     self.batch_first, bool(self.bidirectional))
> RuntimeError: cuDNN error: CUDNN_STATUS_EXECUTION_FAILED
> # Accounting: time=8 threads=1
> # Ended (code 1) at Tue Sep 17 18:14:56 CST 2019, elapsed time 8 seconds

Just wnat know is it a bug? My environment is CUDA 10.0 cuDNN 7.5. It is fine with configure train_pytorch_transformer.yaml. Dataset is voxforge

**Comment by qmpzzpmq** [comment]
both backend have this issue

**Comment by b-flo** [comment]
Only pytorch is supported for rnn transducer.
Despite the error reported by cudNN I suspect an out-of-memory issue. Could you try to reduce batch, dim, etc?

**Comment by qmpzzpmq** [comment]
I alreay changed it to 1, but still have same problem.

**Comment by b-flo** [comment]
Ok. Could you give me more details on your setup please: pytorch version, gpu, install, etc?
I'll try to reproduce the error and fix it. It could take some time though, this kind of issues can be an hassle to pinpoint.

**Comment by qmpzzpmq** [comment]
it is 
pytorch:1.0.1.post2,
there are 4 2080ti gpu,
I installed newest 0.5.2 version espnet
