### ISSUE TITLE
Colab link in Docs > Speech Recognition Library is broken

### ISSUE THREAD

**Issue by juandspy** [espnet/espnet#1200]
The [link ](https://colab.research.google.com/github/espnet/notebook/asr_library.ipynb) on the [documentation](https://espnet.github.io/espnet/notebook/asr_library.html#) redirects to a non valid notebook. 
It should redirect to https://colab.research.google.com/github/espnet/notebook/blob/master/asr_library.ipynb.
I can't find the web file in the repo to make a Pull Request.

**Comment by ShigekiKarita** [comment]
Thanks for reporting. I am planning to update the notebook with our recent notebooks in INTERSPEECH 2019. I will fix that after returning from INTERSPEECH.
