### ISSUE TITLE
Integrating waveglow with espnet fastspeech

### ISSUE THREAD

**Issue by enamoria** [espnet/espnet#1212]
Hello, is anyone try this approach? This seems the fastest combination at this moment.
I've tried but it seems there is something wrong with my implementation, which generated inaudible audio (I can vaguely hear some words but it's far from wavenet option)
Sample
[waveglow+fastspeech](https://drive.google.com/file/d/1Kh9rkRoWSBte0D2EE06HNFeP_IJNQXCT/view?usp=sharing)

**Comment by r9y9** [comment]
Did you use the exact same parameters for log-melspectrogram extraction? I guess the reason you got non intelligible speech is the feature mismatch between espnet and waveglow.

**Comment by kan-bayashi** [comment]
Unfortunately, as @r9y9 said, hyperparamers of feature extraction is different.
It is necessary to fix the setting to use waveglow.

**Comment by kan-bayashi** [comment]
I integrated with the real-time neural vocoder ParallelWaveGAN.
You can try in Google Colab.
https://colab.research.google.com/github/espnet/notebook/blob/master/tts_realtime_demo.ipynb
![img398](https://user-images.githubusercontent.com/22779813/68845686-24b58080-070f-11ea-91db-85f9198050cd.png)

**Comment by EsmaeilFarhang** [comment]
> Unfortunately, as @r9y9 said, hyperparamers of feature extraction is different.
> It is necessary to fix the setting to use waveglow.
----------------------------------------------------------------
Hi, 
can you tell me, which parameters for waveglow should be changed?
