### ISSUE TITLE
How to decode speech without text in test 

### ISSUE THREAD

**Issue by shunfeichen** [espnet/espnet#1213]

**Comment by shunfeichen** [comment]
I found the espnet decode speech need to make data2json file. However, if there is no text file in test, how to decode speech?
Thanks!

**Comment by b-flo** [comment]
Hi,

[recog_wav.sh](https://github.com/espnet/espnet/blob/master/utils/recog_wav.sh) is what you're looking for!

**Comment by shunfeichen** [comment]
> Hi,
> 
> [recog_wav.sh](https://github.com/espnet/espnet/blob/master/utils/recog_wav.sh) is what you're looking for as example!

Thank you,very much!
