### ISSUE TITLE
Subsample? 

### ISSUE THREAD

**Issue by TParcollet** [espnet/espnet#1214]
Hi there!

I'm unsure about the effect of the subsample parameter in the config file. Is it only impacting the first layer, or is it parametrized for each layer? Like 2 means skipping 1 frame every 1 frame? 

Thank you very much!

**Comment by sw005320** [comment]
> Like 2 means skipping 1 frame every 1 frame?

Correct.

`1_2_2_1_1` means that we skip 1 frame before they are fed to 2nd and 3rd LSTM layers respectively. `1` does not skip any frame. If we set `2_1_1`, this will skip 1 frame in the input (which is not recommended though).
However, our VGGBLSTM encoder includes the subsampling in the CNN stride function and this option is ignored.

**Comment by TParcollet** [comment]
Thanks for the fast answer, does it reduce the sequence size?

**Comment by sw005320** [comment]
Yes, this is the intention of this implementation.

**Comment by TParcollet** [comment]
Interesting, thank you!
