### ISSUE TITLE
about subsample

### ISSUE THREAD

**Issue by discdisk** [espnet/espnet#1222]
I'm training a CTC only asr model. I noticed that there are subsampling operations in RNNP module but didn't exist in RNN module .

I want to ask why there are no subasmpling in normal RNN module, isn't that slow down the training /decoding speed?

And I also want to ask is it possible to train csj task with word output?

**Comment by Fhrozen** [comment]
Hello there, 
 - The reason why RNNP has a subsampling module could be "Note that the outputs are often subsampled to reduce the computational complexity of the encoder network" https://www.merl.com/publications/docs/TR2017-190.pdf; and RNN seems to avoid this requirement.

- About CSJ task with word output, I could not find any example in an asian language with a word output. I suppose that this is related to the number of possible combinations that you may have and that, in contrast to a Latin language where you only have 28 ~ 30 characters to represent any word, the number of occurrence of a word in the Asian language become smaller than the occurrence of a single character. In any case, if you want to test, you can always try to use the example from librispeech to generate a bpe/word model https://github.com/espnet/espnet/blob/33ef80069c6f42bfbccffe2ea2f8d812f1cbeaaa/egs/librispeech/asr1/run.sh#L142-L196

@sw005320 may clarify more about these points later.

**Comment by sw005320** [comment]
I just want to follow up @Fhrozen's answers (that mostly answered them though).

- RNN is based on cudnn NStepLSTM. This does not allow us to perform subsampling, as we cannot access to the intermediate hidden state vectors between layers.

- We can use BPE or we may also use original word segmentation prepared in the CSJ corpus by modifying https://github.com/espnet/espnet/blob/master/egs/csj/asr1/local/csj_rm_tag_sp_space.sh

**Comment by discdisk** [comment]
Thanks for the answer, but can RNN module perform subsampling just like RNNP module?

https://github.com/espnet/espnet/blob/ec829fb95dbfcc61672960038643f4f8c8a19480/espnet/nets/chainer_backend/rnn/encoders.py#L78

Will that occur any problem?
Since I trained a model without the CNN block and only use CTC, so there is no subsampling performed, and the decoding speed is very slow and cost lot's of memory.

**Comment by sw005320** [comment]
Yes, it is possible.
If you insert this subsampling in every layer by calling one-layer NStepLSTM, you can do it for RNN as well, but it will lose training speed benefits of multiple-layer NStepLSTM.
