### ISSUE TITLE
A bug about ASR Transfromer decoding with GPU

### ISSUE THREAD

**Issue by MarkWuNLP** [espnet/espnet#1224]
When I use the master branch to decode the results using the Librispeech model and config, it can yield results successfully on CPU but failed on GPU.

Several .cpu(), .cuda(), device="gpu" operations are needed in the 
`def recognize(self, feat, recog_args, char_list=None, rnnlm=None, use_jit=False)`
function of the e2e_asr_transformer.py file.

**Comment by chengmengli06** [comment]
that is it, I also meet the same problem, and sloved by several to('cuda')  and to('cpu') functions.

**Comment by kan-bayashi** [comment]
You can try —api v2 for asr_recog.py
It may work with gpu.

**Comment by sw005320** [comment]
> that is it, I also meet the same problem, and sloved by several to('cuda') and to('cpu') functions.

Thanks.
@ShigekiKarita, could you fix it?

**Comment by ShigekiKarita** [comment]
No use v2 option as @kan-bayashi suggested
