### ISSUE TITLE
gpu 0 OOM for asr librispeech task

### ISSUE THREAD

**Issue by chengmengli06** [espnet/espnet#1225]
I try to train librispeech asr using conf/tuning/train_pytorch_transformer_large_ngpu4.yaml. It is said that only 12 G memory is necessary, however oom still happens even with 16G memory. I noticed that GPU:0 consumes more memory than the others. My start script is:

under espnet/egs/librispeech/asr1:
../../../tools/venv/bin/python3 ../../../espnet/bin/asr_train.py --config conf/tuning/train_pytorch_transformer_large_ngpu4.yaml --ngpu 4 --backend pytorch --outdir exp/train_960_pytorch_train/results --tensorboard-dir tensorboard/train_960_pytorch_train --debugmode 1 --dict data/lang_char/train_960_unigram5000_units.txt --debugdir exp/train_960_pytorch_train --minibatches 0 --verbose 0 --resume --train-json dump/train_960/deltafalse/data_unigram5000.json --valid-json dump/dev/deltafalse/data_unigram5000.json

Moreover, the training is too slow: it says that it will take 6 days to finish training on 4 V100 GPUs with 16 G memory. And the gpu usage is no more than 50%. So what do I miss?

**Comment by kan-bayashi** [comment]
Was the OOM error happened in the middle of training?
Due to specaug, sometimes the length of inputs becomes much longer, and then it causes OOM error.
Maybe it is better to reduce batch-bins and increase accum_grad to avoid OOM error while keeping the original batch-size.

And to increase the usage of GPU, you can try `--n-iter-processes 4 or more`.
It helps to reduce the bottleneck of loading batches.

**Comment by chengmengli06** [comment]
It seems not caused by data augmentation. Even data augment is closed, it could still oom. I want to know what is your device configurations for training conf/tuning/train_pytorch_transformer_large_ngpu4.yaml ?

**Comment by kan-bayashi** [comment]
Hmm, I used GTX Titan (pascal, 12GB memories) x 4 in this configuration.
That is strange. I have just running w/ that config, but it works around 8~11GB memory.
What is your pytorch version?

**Comment by chengmengli06** [comment]
# RESULTS
## Environments
- date: `Mon Sep 30 13:00:57 CST 2019`
- python version: `3.7.3 (default, Mar 27 2019, 22:11:17)  [GCC 7.3.0]`
- espnet version: `espnet 0.5.3`
- chainer version: `chainer 6.0.0`
- pytorch version: `pytorch 1.0.1.post2`
- Git hash: `33ef80069c6f42bfbccffe2ea2f8d812f1cbeaaa`
  - Commit date: `Sat Sep 28 21:17:19 2019 +0900`

## train_960_pytorch_train_specaug.good
### CER

|dataset|Snt|Wrd|Corr|Sub|Del|Ins|Err|S.Err|
|---|---|---|---|---|---|---|---|---|
|2703|68066|94.9|2.7|2.4|0.6|5.7|37.1|

### WER

|dataset|Snt|Wrd|Corr|Sub|Del|Ins|Err|S.Err|
|---|---|---|---|---|---|---|---|---|
|2703|54402|95.7|2.6|1.7|0.4|4.7|36.8|

**Comment by chengmengli06** [comment]
I use cuda 10.0

**Comment by kan-bayashi** [comment]
Hmm. It seems no problem in the environment.
Did you add any special processing like speed perturbation? 
If not, I have no idea why your environment requires so much GPU memory.

Easiest way to solve this issue is to reduce batch-bins (e.g. `batch-bins: 12000000` and `accum-grad: 5`).

**Comment by kan-bayashi** [comment]
@ShigekiKarita Do you have any idea?

**Comment by chengmengli06** [comment]
memory consumption on gpu:0 is continuously increasing. Do it has anything to do with torch.cuda.empty_cache(), and also what exactly the version of code you are using? @kan-bayashi

**Comment by kan-bayashi** [comment]
My environment is as follows.
```bash
## Environments
- date: `Wed Oct  2 08:37:30 JST 2019`
- python version: `3.7.3 (default, Mar 27 2019, 22:11:17)  [GCC 7.3.0]`
- espnet version: `espnet 0.5.3`
- chainer version: `chainer 6.0.0`
- pytorch version: `pytorch 1.0.1.post2`
- Git hash: `c6d6c094220da2065694149feb56b733c735e87c`
  - Commit date: `Mon Sep 30 09:51:53 2019 +0900`

## Cuda related
- CUDA: 10.0.130
- CuDNN: 7.6.2
- NCCL: 2.4.8
```
I used the current master.
I did not perform any processing to clear the gpu memory such as `torch.cuda.empty_cache()`.

**Comment by chengmengli06** [comment]
I also try 1080TI with 11GB memory, the result is the same:
RuntimeError: CUDA out of memory. Tried to allocate 685.00 MiB (GPU 0; 10.91 GiB total capacity; 3.07 GiB already allocated; 141.38 MiB free; 2.07 GiB cached)

On V100 16GB, I reduce sequence length to 12000000, the memory on gpu:0 is much larger than the others, which part of the code eats up extra memory:
|    0    126965      C   ...engli.cml/espnet/tools/venv/bin/python3 14475MiB |
|    1    126965      C   ...engli.cml/espnet/tools/venv/bin/python3 10785MiB |
|    2    126965      C   ...engli.cml/espnet/tools/venv/bin/python3 10709MiB |
|    3    126965      C   ...engli.cml/espnet/tools/venv/bin/python3  9167MiB |

**Comment by kan-bayashi** [comment]
Batch is sorted in the length (longer to shorter) and data parallel split into `#gpus` batches.
Therefore, GPU:0 basically requires a little bit larger memory than the other gpus (But 4GB seems a big difference).
The memory usage is updated during the training, so you can check the difference alway exists or not.

**Comment by chengmengli06** [comment]
I try the docker, which cannot start either, having no nvidia-smi and python, how could the docker work? I am really disappointed about the reproductivity.

**Comment by sw005320** [comment]
I know several people made it work (reproduce a similar result) and did not report such problems. This could be a problem with some specific cases (system, misuse, etc.).

**Comment by kan-bayashi** [comment]
@chengmengli06 I understood there is a gap among gpus in your environment, but if OOM error is not caused, it can be trained. Even if you adjust the batch-bins and accum-grad, does not it works without OOM error?

**Comment by chengmengli06** [comment]
If change to 12000000 instead of 15000000，then it can be trained with 16G memory
