### ISSUE TITLE
is possible using ngram to replace rnnlm through srilm and score interface

### ISSUE THREAD

**Issue by qmpzzpmq** [espnet/espnet#1228]

**Comment by kan-bayashi** [comment]
Yes, it can be done with —api v2 if you implement ScorerInterface for N-gram.

**Comment by ShigekiKarita** [comment]
I tried it before but I do not have any results now. see this snippet https://gist.github.com/ShigekiKarita/3b81a34b4530cf7cebb6754e30876985

**Comment by qmpzzpmq** [comment]
> I tried it before but I do not have any results now. see this snippet https://gist.github.com/ShigekiKarita/3b81a34b4530cf7cebb6754e30876985

Did you integrated into espnet? @ShigekiKarita

**Comment by Cescfangs** [comment]
I've been using ngram lm(Mandarin, character based) for shallow fusion, you can implement this using `KenLM` : 
```python
import kenlm
model = kenlm.Model('lm/test.arpa')
print(model.score('this is a sentence .', bos = True, eos = True))
```

**Comment by qmpzzpmq** [comment]
@Cescfangs yes, I use this as well. the result is as not as good as RNNLM.

**Comment by Cescfangs** [comment]
> @Cescfangs yes, I use this as well. the result is as not as good as RNNLM.

Do you train ngram lm on ASR corpus only? I trained ngram lm on much larger corpus and it worked quite well(comparable with RNNLM)

**Comment by qmpzzpmq** [comment]
rnnlm and ngram trained with same data,ASR corups

**Comment by chen1399** [comment]
> > @Cescfangs yes, I use this as well. the result is as not as good as RNNLM.
> 
> Do you train ngram lm on ASR corpus only? I trained ngram lm on much larger corpus and it worked quite well(comparable with RNNLM)
Are you training the ngram and rnnlm using the same corpus？
