### ISSUE TITLE
remove Chainer dependence maybe good for user

### ISSUE THREAD

**Issue by zh794390558** [espnet/espnet#1230]
Since most people only using pytroch and tensorflow, the  Chainer dependence is not good for user reading code. So remove Chainer or separate Chainer with pytroch is prefer.

**Comment by kan-bayashi** [comment]
@ShigekiKarita is experimentally working on this issue #688
But we have to discuss the interface. (See also #1188)

**Comment by zh794390558** [comment]
great work.
