### ISSUE TITLE
Normalization / standardization of the features.

### ISSUE THREAD

**Issue by TParcollet** [espnet/espnet#1233]
Hi there!

Are the input features supposed to be normalized / standardized outside the toolkit (before creating the JSON format)? 

I can't find a normalization strategy in asr.py.

Thank you!
Titouan.

**Comment by sw005320** [comment]
> Are the input features supposed to be normalized / standardized outside the toolkit (before creating the JSON format)?

Yes.

> I can't find a normalization strategy in asr.py.

We don't have the normalization function in `asr.py`, but we have it in https://github.com/espnet/espnet/blob/master/espnet/transform/cmvn.py.

**Comment by TParcollet** [comment]
Thanks!

**Comment by TParcollet** [comment]
Sorry to bother again, but I still have concern with the normalization / standardization procedure. From my understanding, it is done within Kaldi with the following steps (TIMIT recipe of ESPnet):

<img width="660" alt="Capture d’écran 2019-10-02 à 17 17 02" src="https://user-images.githubusercontent.com/11910731/66057271-b9399a00-e538-11e9-9e50-ee1aabbd3670.png">

Nonetheless, when I train a simple VGGBLSTM and I print the min and max values contained in the input vector (xs_pad) I obtain:
<img width="227" alt="Capture d’écran 2019-10-02 à 17 16 45" src="https://user-images.githubusercontent.com/11910731/66057338-d40c0e80-e538-11e9-9488-bdcde7c8a8cf.png">

From:

<img width="604" alt="Capture d’écran 2019-10-02 à 17 17 29" src="https://user-images.githubusercontent.com/11910731/66057363-e0906700-e538-11e9-8b9d-89f4e07538b4.png">

dump.sh calls apply-cmvn that should standardize the data right? So everything should be between -1 and 1 ? 

Am I wrong somewhere? 
Thanks!

**Comment by YoungKang1222** [comment]
i want to ask if my training data's format is "wav" and the feats_type is "raw",  whether the default strategy of espnet is  "normalization"?

**Comment by kan-bayashi** [comment]
As a default, we use global_mvn for feature normalization (mean variance normalization over training data).
https://github.com/espnet/espnet/blob/8c39ca54a89080c063970d20e23ccf54053a8e85/egs2/TEMPLATE/asr1/asr.sh#L95

**Comment by YoungKang1222** [comment]
@kan-bayashi thanks！
