### ISSUE TITLE
Libritts speaker numbers

### ISSUE THREAD

**Issue by JaejinCho** [espnet/espnet#1239]
The numbers of speakers in each subset of data generated from the current recipe for libritts are not matching with what's reported in the libritts paper: https://arxiv.org/pdf/1904.02882.pdf
Does anyone know some reasons for this?

**Comment by kan-bayashi** [comment]
Could you report the difference?

**Comment by JaejinCho** [comment]
I found the reason as you can see https://github.com/espnet/espnet/blob/2b14d3b04f3a3f8d8210410c8d88f22513d97399/egs/libritts/tts1/local/data_prep.sh#L51
Different chapters are considered different speakers and I found the number of speakers is the same as reported in the paper if I use only the ${reader}.
