### ISSUE TITLE
How to reduce training time

### ISSUE THREAD

**Issue by shunfeichen** [espnet/espnet#1247]
Hello， I trained a model use my dataset without speed perturb， which takes about 5 days( 50 epoches, and 4 gpus ). However,when I do speed perturb, It needs to long times about 30 days (40 epoches, and 4 gpus). In my opinion, It just need 12 days (5x3x0.8). Why does it take so long? And how can I reduce the training time.
Thanks

**Comment by kan-bayashi** [comment]
If the problem is caused by bottleneck of loading, you can add `n-iter-processes: 4 or more` in your yaml config.
(If the gpu util in `nvidia-smi` is too low, maybe the loading is bottleneck.) 
This might accelerate the batch making steps.

**Comment by shunfeichen** [comment]
> If the problem is caused by bottleneck of loading, you can add `n-iter-processes: 4 or more` in your yaml config.
> (If the gpu util in `nvidia-smi` is too low, maybe the loading is bottleneck.)
> This might accelerate the batch making steps.

Thank you, add `n-iter-processes: 24` will recude training time. However, It will be  stop, no error, and the gpu utils is 0%.

**Comment by kan-bayashi** [comment]
Oh maybe this issue is the same.
https://github.com/espnet/espnet/issues/404
Could you try adding following code in the beginning of the `asr_train.py`? 
```python
import multiprocessing as mp
mp.set_start_method('spawn')
```
Maybe you can add the above code just after following line:
https://github.com/espnet/espnet/blob/69f239c4ce116855f895b29d8d6d91aaeb5f359e/espnet/bin/asr_train.py#L355

**Comment by kan-bayashi** [comment]
I made PR to fix this issue (#1251).
But this issue is randomly happened I'm not confidence the solution works well or not.

**Comment by shunfeichen** [comment]
> Oh maybe this issue is the same as #404
> Could you try adding following code in the beginning of the `asr_train.py`?
> 
> ```python
> import multiprocessing as mp
> mp.set_start_method('spawn')
> ```
> 
> Maybe you can add the above code just after following line:
> https://github.com/espnet/espnet/blob/69f239c4ce116855f895b29d8d6d91aaeb5f359e/espnet/bin/asr_train.py#L355

Thank you very much. But I have set up as  you said, It still can't run.

**Comment by kan-bayashi** [comment]
> It still can't run.

You mean added the code but the training stop silently?

**Comment by shunfeichen** [comment]
> > It still can't run.
> 
> You mean added the code but the training stop silently?

Yes, Just like before.GPU utils become 0%.

**Comment by kan-bayashi** [comment]
Hmm... It is not solved yet...
Our latest branch `v.0.6.0` replaced the iterator with Pytorch implementation. 
I'm not sure the problem will be fixed but it is worthwhile to try.

**Comment by shunfeichen** [comment]
> Hmm... It is not solved yet...
> Our latest branch `v.0.6.0` replaced the iterator with Pytorch implementation.
> I'm not sure the problem will be fixed but it is worthwhile to try.

Thank you, I will try. I found it will appear warning "Was asked to gather along dimension 0, but all ' " when I set n-iter-processes.
