### ISSUE TITLE
the performance gap is too large between lstm and blstm in RNNT

### ISSUE THREAD

**Issue by hanqichen** [espnet/espnet#1248]
We use RNNT to train librispeech dataset, results are as follows：

| encoder type |  test-clean wer | 
| ---- | ----|
| 4 layer blstm |  5.0 |
| 8 layer lstm |  12.0 | 

The config of 4 layer blstm
[4 layer blstm.txt](https://github.com/espnet/espnet/files/3706309/4.layer.blstm.txt)

The config of 8 layer lstm
[8.layer lstm.txt](https://github.com/espnet/espnet/files/3706423/8.layer.lstm.txt)

Both of them train exceed 40 epoch.  What puzzled us is the **performance gap is too large** between lstm and blstm. 

So, what's the problem? Is the config problem or other?

**Comment by kan-bayashi** [comment]
This title is a little bit misleading.
```bash
$ diff 4.layer.blstm.txt 8.layer.lstm.txt
< batch-size: 20
---
> batch-size: 24
9c9
< sortagrad: 0
---
> sortagrad: 1
16,20c16,20
< etype: vggblstm
< elayers: 4
< eunits: 512
< eprojs: 512
< subsample: "1_1_1_1_1"
---
> etype: lstmp
> elayers: 8
> eunits: 1024
> eprojs: 1024
> subsample: "1_2_2_1_1_1_1_1"
```
There are many differences b/w these models (In lstm, no vgg, deep archtecture, sortgrad...)
Did you compare the models whose difference is only type?
And it is better to show the learning curves.

**Comment by b-flo** [comment]
Hi,

I didn't use unidirectional lstm in my experiments so I can't really talk about performances but there isn't any issue related to lstm encoder in transducer that I know.

About the performance gap you report, it is a bit difficult to comment with only config files. Moreover your network config in both experiments are quite different (e.g.: different etype, eunits, dunits, joint space, subsample, sortagrad, batchsize, etc.). Did you try to compare the same architecture with only `blstm` switched to `lstm` (or `vggblstm` switched to `vgglstm` in your case)?

**Comment by hanqichen** [comment]
thanks for responses!

I will train the same architecture with only vggblstm switched to vgglstm in the next few days.

**Comment by hanqichen** [comment]
Hi，

I have trained the same architecture with only vggblstm switched to vgglstm，but it can't converge. The learning curves and config are as follows(both train with 4 gpu):

vgglstm
[config](https://github.com/espnet/espnet/files/3715424/vgglstm.txt)
![image](https://user-images.githubusercontent.com/11291324/66620676-ea3e5c80-ec13-11e9-887d-cb1d0dcae8f8.png)

vggblstm
[config](https://github.com/espnet/espnet/files/3715425/vggblstm.txt)
![image](https://user-images.githubusercontent.com/11291324/66620922-de06cf00-ec14-11e9-8909-61617294042c.png)

**Comment by b-flo** [comment]
Thanks for the report! Just to be sure, 160k iterations in your case should correspond to ~10/11 epochs (given batch is set to 20 and you're training with the 960h dataset without augmentation), right?
Also, could you share the learning curves for your initial model (8 layers) please?

I don't have time until the 21st but after that I'm working on the streaming version so I'll investigate unidirectional lstm at the same time.

**Comment by sw005320** [comment]
The number of parameters of vgglstm is smaller and we may need to increase the unit size to compensate it.

**Comment by b-flo** [comment]
From what I observe in my current experiments with a similar sized dataset (~750hours), RNN-transducer seems to perform better with a deeper architecture and a small number of units compared to others methods (classic and hybrid). In our comparison, the RNNT architecture (enc: vgg+5x384 blstm, dec:1x256 lstm, joint:256) outperformed our best JCA architecture (enc: vgg+3x1024 blstm, dec:2x1024 lstm), even with the addition of LMs.

**Comment by sw005320** [comment]
OK, then maybe better to use deeper vgglstm to compensate for the model parameter difference.

**Comment by hanqichen** [comment]
Thanks for reply!

> Just to be sure, 160k iterations in your case should correspond to ~10/11 epochs (given batch is set to 20 and you're training with the 960h dataset without augmentation), right?

In my case, vgglstm ran 175k iterations which correspind to 14 epochs.

> Also, could you share the learning curves for your initial model (8 layers) please?

The 8 layers([config](https://github.com/espnet/espnet/files/3706423/8.layer.lstm.txt)) curve is as follows:
![image](https://user-images.githubusercontent.com/11291324/66692945-06a2cd80-ecd6-11e9-9787-786d0af5ec0d.png)

I'll try deeper vgglstm in the next few days.

**Comment by lijiangguo** [comment]
Can anyone explain how vgglstm generates features? Does the conv layer need the entire input sequence or it only moves in frequency dimension?

**Comment by tu1258** [comment]
Hi, @hanqichen 

Would you mind sharing the `run.sh` of RNN-T for LibriSpeech? I couldn't reproduce the same performance, if you could help that would be great!
