### ISSUE TITLE
Strong negative impact of LayerNorm on inputs

### ISSUE THREAD

**Issue by TParcollet** [espnet/espnet#1250]
Hi there!

I'm quite skeptical in front of a recent finding while using vgg+blstm on TIMIT. I just added a LayerNorm in the vgg encoder right in top of the FBANK like:
![Capture d’écran 2019-10-09 à 13 13 32](https://user-images.githubusercontent.com/11910731/66476748-a70aaf00-ea96-11e9-8928-2caaa74352aa.png)

The training is multi-task (0.5) with 5 layers of BLSTM as encoder and 2 as decoder. With such a small difference, the network is unable to train:

The pink curves are related to the LayerNorm model, while blue curves are equivalent to the same model but without LN.
![Capture d’écran 2019-10-09 à 13 15 30](https://user-images.githubusercontent.com/11910731/66476868-edf8a480-ea96-11e9-86ab-2b1dd4508482.png)

Any intuitions behind that? This LayerNorm is just a normalization of each time frame, it should help the training..

**Comment by kan-bayashi** [comment]
What is the motivation of the use of LayerNorm for inputs?
The input features are already normalized to be a mean 0, variance 1 in each dimension in feature extraction step.
And if we use `LayerNorm` for the inputs, these will be normalized to be mean 0 variance 1 over dimensions of each frame.
It does not make sense for me because for example information of the power of each frame will be lost (the power of each frame will be alway the same).

**Comment by TParcollet** [comment]
In fact, I'm having the same issue with a model that uses LayerNorm on the inputs (that are raw waveforms). And I just wanted to reproduce this issue on the standard VGG, where it might make way less sense. Nonetheless, this is just a standardization operation so it should not completely block the convergence. In the model I'm investigating LayerNorm at the input is crucial, and weirdly, when used in a end-to-end fashion with espenet, it's the inverse phenomenon (training ok without LayerNorm and not at all with LayerNorm). I was just wondering if adding a LayerNorm like this could interfere with some next operations that are part of the MT training (I don't see how, but this behavior is still weird to me).

**Comment by kan-bayashi** [comment]
As I mentioned, LayerNorm for the inputs lost important information, so this performance degradation is reasonable for me.
If we add the some trainable layers before LayerNorm, the performance will be improved.
Do you have any references which directly apply LayerNorm for feature sequences?

**Comment by TParcollet** [comment]
Hum. I'll try to put a LayerNorm after to see if the problem arises again. An example is SincNet: https://arxiv.org/pdf/1812.05920.pdf Note that the input features are raw waveforms.

**Comment by BitCalSaul** [comment]
> Hum. I'll try to put a LayerNorm after to see if the problem arises again. An example is SincNet: https://arxiv.org/pdf/1812.05920.pdf Note that the input features are raw waveforms.

Hi, @TParcollet I met the same situation. I tried to use Swin transformer for Cifar10. If I kept the Layernorm in the PatchMeging module, the loss cannot decrease. If I delete it, the result would be super good. I'm wondering if you have found any intuition for this?
