### ISSUE TITLE
Attention images generated?

### ISSUE THREAD

**Issue by TParcollet** [espnet/espnet#1254]
Hi!

I have two questions w.r.t to the attention images that are generated and available in Tensorboard. I'm training a very simple BLSTM on TIMIT with the config file provided in the recipe. At the end, I obtain 3 different pictures for the attention weights that are:
<img width="365" alt="Capture d’écran 2019-10-09 à 19 09 15" src="https://user-images.githubusercontent.com/11910731/66551154-2e176000-eb47-11e9-8059-ddf680897bcc.png">
<img width="365" alt="Capture d’écran 2019-10-09 à 19 09 19" src="https://user-images.githubusercontent.com/11910731/66551157-2e176000-eb47-11e9-915c-a2cc8ff113ef.png">
<img width="368" alt="Capture d’écran 2019-10-09 à 19 09 23" src="https://user-images.githubusercontent.com/11910731/66551159-2e176000-eb47-11e9-91dd-a5abe4296c49.png">

The first question is: What is this weird line happening at the beginning of the x axis? 
The second one: Why three images? (names on Tensorboard are: FADG0_SI649, FADG0_SI1279 and FADG0_SI1909.

Thank you very much!

**Comment by Fhrozen** [comment]
>The second one: Why three images? (names on Tensorboard are: FADG0_SI649, FADG0_SI1279 and FADG0_SI1909.

Is because the configuration for asr_train  as default saves three images. you can change it in your train.yaml file.

```
parser.add_argument('--num-save-attention', default=3, type=int,
                        help='Number of samples of attention to be saved')
```

**Comment by TParcollet** [comment]
Great thank you, any idea for the weird line?
