### ISSUE TITLE
subword modeling in Chinese

### ISSUE THREAD

**Issue by qmpzzpmq** [espnet/espnet#1255]
> Note that the performance of the CSJ, HKUST, and Librispeech tasks was significantly improved by using the wide network (#units = 1024) and large subword units if necessary reported by RWTH.

Hi, as mentioned, is subword modeling used in HKUST egs?

**Comment by sw005320** [comment]
It mentioned "if necessary".
The HKUST recipe does not use subword modeling.

**Comment by qmpzzpmq** [comment]
Thanks for your reply. And I checked the source word. It is seems therer is a multiple-level lm, but it haven't finished, isn't it?
