### ISSUE TITLE
A bug in the implementation of DNN-based WPE?

### ISSUE THREAD

**Issue by Emrys365** [espnet/espnet#1272]
Hi, I was just checking the code in the front-end part.
I found that at the end of `dnn_wpe.py`, a non-inplace operation is used without using the returned value. Should `masked_fill` be replaced with `masked_fill_`?

https://github.com/espnet/espnet/blob/33ef80069c6f42bfbccffe2ea2f8d812f1cbeaaa/espnet/nets/pytorch_backend/frontends/dnn_wpe.py#L82

**Comment by sw005320** [comment]
I think you're right.
@kamo-naoyuki, can you take a look at it?

**Comment by kan-bayashi** [comment]
Fixed #1273
