### ISSUE TITLE
How to use pretrained models

### ISSUE THREAD

**Issue by vcjob** [espnet/espnet#1275]
Hello everyone!
I'm sorry to ask such a question, but, I spent a couple of hours trying to understand how to use pretrained model, but still can't figure it out.  
Le't take an example: _https://github.com/espnet/espnet/blob/master/egs/ru_open_stt/asr1/RESULTS.md_
There you can see the link to pretrained model is available. I have downloaded it, unpacked the folders to the _egs/ru_open_stt/asr1/._ What should I do now? How to understand "_Results (paste them by yourself or obtained by $ pack_model.sh --results <results>)_"?
I tried to run asr_recog.py - no success (it needs result-label, which I don't have). Also tried change the step to 5 (in _run.sh_), but it still needs '_log_', which is also absent.
Thank you a lot for any hints!

**Comment by Fhrozen** [comment]
Let me understand. 
- First, did you execute the run.sh until stage 2? with: `./run.sh --stop_stage 2`
- Just in case, you execute until stage 1 `--stop_stage 1`, replace data/train/cmvn.ark with the one supplied by the download. also, maybe you need to replace data/lang_char/train_unigram100_units.txt in case the one generated in stage 2 is not similar to the one supplied by the download
- After that, did you executed run.sh with: `./run.sh --stage 5 --train_config conf/tuning/train_pytorch_transformer_large_ngpu4.yaml --decode_config conf/tuning/decode_pytorch_transformer_large.yaml `? This should be the command to generate the output.

BTW, @kan-bayashi, @ShigekiKarita. I saw that the recipe works in bpe and only the dict is supplied. Is it not necessary to additionally supply the bpe.model to get score the data?

**Comment by kan-bayashi** [comment]
Maybe you can understand by using demo script `recog_wav.sh`
https://github.com/espnet/espnet#asr-demo
This script will automatically download pretrained model and then perform recognition.

@Fhrozen actually yes, currently the script give the results with `_`but we can just replace them.

**Comment by vcjob** [comment]
> Let me understand.
> 
> * First, did you execute the run.sh until stage 2? with: `./run.sh --stop_stage 2`
> * Just in case, you execute until stage 1 `--stop_stage 1`, replace data/train/cmvn.ark with the one supplied by the download. also, maybe you need to replace data/lang_char/train_unigram100_units.txt in case the one generated in stage 2 is not similar to the one supplied by the download
> * After that, did you executed run.sh with: `./run.sh --stage 5 --train_config conf/tuning/train_pytorch_transformer_large_ngpu4.yaml --decode_config conf/tuning/decode_pytorch_transformer_large.yaml `? This should be the command to generate the output.
> 
> BTW, @kan-bayashi, @ShigekiKarita. I saw that the recipe works in bpe and only the dict is supplied. Is it not necessary to additionally supply the bpe.model to get score the data?

Thank you for the help. 
I did _./run.sh --stop_stage 2_ and had been waiting for more than one day for it to download everything and extract features. So now to run _./run.sh --stage 5_ I need to provide  _--snapshots_, which I don't have and not sure what is that? The models that I downloaded? Both for _train_rnnlm_pytorch_lm_unigram100_ and _train_pytorch_train_pytorch_transformer_large_ngpu4_? and what should I supply for --out key?
the error: _average_checkpoints.py: error: the following arguments are required: --snapshots, --out_

Thank you!

**Comment by vcjob** [comment]
> Or our tutorial notebook will help you.
> 
> You can check
> `4. Demonstration of the use of ASR pretrained models`
> in https://colab.research.google.com/github/espnet/interspeech2019-tutorial/blob/master/notebooks/interspeech2019_tts/interspeech2019_tts.ipynb

Thank you a lot! I just simply added a link to the Google drive for the corresponding model, and the script works just awesome!
