### ISSUE TITLE
Aishell pretrain weight names can't match with the model to be load.

### ISSUE THREAD

**Issue by Danielsen331** [espnet/espnet#1282]
I try to use the pretrain aishell model to decode a wav file. The error as follows:
RuntimeError: Error(s) in loading state_dict for E2E:
	Missing key(s) in state_dict: "encoder.embed.conv.0.weight", "encoder.embed.conv.0.bias", "encoder.embed.conv.2.weight", "encoder.embed.conv.2.bias", "encoder.embed.out.0.weight", "encoder.embed.out.0.bias", "encoder.after_norm.weight", "encoder.after_norm.bias", "decoder.after_norm.weight", "decoder.after_norm.bias".
	Unexpected key(s) in state_dict: "encoder.input_layer.conv.0.weight", "encoder.input_layer.conv.0.bias", "encoder.input_layer.conv.2.weight", "encoder.input_layer.conv.2.bias", "encoder.input_layer.out.0.weight", "encoder.input_layer.out.0.bias", "encoder.input_layer.out.1.pe", "encoder.norm.weight", "encoder.norm.bias", "decoder.output_norm.weight", "decoder.output_norm.bias".

It seams pretrain model use a new naming format for some weight, and has an additional weight name encoder.input_layer.out.1.pe.

For the similar name, can I replace the unexpected key name by the counterpart missing key name? And how can I handle the additional weight encoder.input_layer.out.1.pe?

Thanks very much!

**Comment by llearner** [comment]
Hi, i met the same problem as you, did you solve it? @Danielsen331

**Comment by unilight** [comment]
Same question here, not in tis dataset but the Librispeech. Any solution?
Another problem is that it seems like the shape of `encoder.input_layer.out.0.weight` is different if we use the same [config](https://github.com/espnet/espnet/blob/master/egs/librispeech/asr1/conf/tuning/train_pytorch_transformer_large_ngpu4.yaml) to initialize a new Transformer-ASR model.

**Comment by sw005320** [comment]
@ShigekiKarita, can you take a look at it?

**Comment by ArtemisZGL** [comment]
the hkust checkpoint also have this problem
