### ISSUE TITLE
Have anybody done Data Augumentation for Training?

### ISSUE THREAD

**Issue by takeofuture** [espnet/espnet#1284]
I wonder if somebody have tried the data augmentation on the training data on ESPNET.
If so, did you apply data augmentation on the spectrum after filter bank?

**Comment by Fhrozen** [comment]
I did for https://arxiv.org/abs/1811.02735.
In my case I applied it to the raw data (waveform) adding noise between 5 ~20 db

**Comment by WhiteFu** [comment]
> ng noise between 5 ~20 db

@Fhrozen How well does the Data Augmentation operation  work ? can you offer some samples?

**Comment by kan-bayashi** [comment]
ESPnet supports kaldi's data augmentation such as speed perturbation and volume perturbation, which are applied for waveform.
See the example:
https://github.com/espnet/espnet/blob/3a709c896ec631edd55455b38cc70ea4fe6d5895/egs/csj/asr1/run.sh#L85-L88

Also we support SpecAugment, which appleid to feature vector.
The process is applied during feature loading in training.
You can use this by specifying preprocess conf in run.sh.
https://github.com/espnet/espnet/blob/3a709c896ec631edd55455b38cc70ea4fe6d5895/egs/librispeech/asr1/run.sh#L23
https://github.com/espnet/espnet/blob/master/egs/librispeech/asr1/conf/specaug.yaml

**Comment by WhiteFu** [comment]
@kan-bayashi  Thanks a lot. I will try it.

**Comment by takeofuture** [comment]
@kan-bayashi @Fhrozen 
Thank you for your suggestion and example!
I will take a look.

**Comment by Fhrozen** [comment]
@WhiteFu , it worked pretty well. reducing the WER by 2% ave. on the CHiME-5 Corpus.
As @kan-bayashi mentioned, you can also try speed perturbation or spec-aug. But be careful, in case of librispeech (or similars) all of the proposed augmentation will work. In case of CHiME-5 or probably any similar corpus with similar acoustic characteristics, Spec-aug, speed perturb will only hurt the performance. Adding noise only works when this is added to the clean data (worn mic).

Bests
