### ISSUE TITLE
TensorFlow backend

### ISSUE THREAD

**Issue by sw005320** [espnet/espnet#1294]
I'd like to make an issue to consider a development plan for the TensorFlow backend. TensorFlow is getting better and better with 2.0, and this is a great opportunity to consider it. Frankly, I'd not currently have such resources, and if you are interested in such a project and help us with this development, please let us know (or directly contact me (shinjiw@ieee.org)). I also welcome if you have some requests related to the TensorFlow backend.

**Comment by sknadig** [comment]
I’m interested in this.
For feature extraction, in addition to the kaldi binaries, if we can have a pure TensorFlow [`tf.signal`](https://www.tensorflow.org/api_docs/python/tf/signal) based feature extraction, it would really help in porting models to [`tf.lite`](https://www.tensorflow.org/lite)/[`TensorFlow.js`](https://www.tensorflow.org/js) and other TensorFlow specific features.

I would like to get involved in this development.

**Comment by sw005320** [comment]
Thanks.
This is a good point. 
@hirofumi0810 and @kan-bayashi, can you also give us some comments?
Pytorch and chainer have the very similar base and we could have a unified design, but I'm not sure whether we can do the same thing for TF.

**Comment by hirofumi0810** [comment]
@sw005320 I don't really use TensorFlow anymore. But I will play the latest TensorFlow with my own framework. I will try to modify it so that it can be incorporated into ESPnet later.
