### ISSUE TITLE
Meaning of the variables used in decoder:

### ISSUE THREAD

**Issue by kobiche** [espnet/espnet#1300]
I've been trying to make some sense about the meaning of the variables used in the decoder (espnet/espnet/nets/pytorch_backend/rnn/decoders.py -> Decoder -> recognize_beam(...) ) and linking their meaning to the paper Hybrid CTC/Attention Architecture for End-to-End Speech Recognition. 

Leaving the CTC and LM aside, what are the meaning of the variables used in the lines 302-307 and how are they related to the paper above mentioned? 

Thanks a lot in advance!

**Comment by Fhrozen** [comment]
Are you referring to this part?:
https://github.com/espnet/espnet/blob/42dd17e382157e1038787c5f8dae1ecf360797c3/espnet/nets/pytorch_backend/rnn/decoders.py#L302-L307

If that is the case:
https://github.com/espnet/espnet/blob/42dd17e382157e1038787c5f8dae1ecf360797c3/espnet/bin/asr_recog.py#L82-L85

You can refer to the mentioned paper for `ctc-weight` (Eq. 45) \lambda

In case of `weights-ctc-dec`, it may refer to a different paper https://arxiv.org/pdf/1811.04903.pdf (Eq. 10?)

**Comment by kobiche** [comment]
Hey! I meant the variables att_c, att_w, ey_t, z_list and c_list.

**Comment by Fhrozen** [comment]
`att_c` is the attention weighted encoder state and `att_w` is the previous attention weight. More details in https://github.com/espnet/espnet/blob/master/espnet/nets/pytorch_backend/rnn/attentions.py.
In the paper, you may find `att_c` as `r_l` (Eq 27) and  `att_w` is `a_{lt}` (eq 26)

I cannot find ey_t in the code. Do you mean https://github.com/espnet/espnet/blob/f14b7e181f97851623348146d6725ac17bb81527/espnet/nets/pytorch_backend/rnn/decoders.py#L209 ??

z_list and c_list are the output and Cell states from the RNN respectively. `z_list` will be `q_l` (eq 36).
   c_list is a intern mechanism of RNN so it is not mentioned in the paper.

**Comment by kobiche** [comment]
Thanks! I think I grasped the general idea now! 
I meant the `ey` that is displayed in the `recognize_beam(...)` function (which has the same function as the one you show)
https://github.com/espnet/espnet/blob/f14b7e181f97851623348146d6725ac17bb81527/espnet/nets/pytorch_backend/rnn/decoders.py#L368
Why is it the concatenation of the last letter of the sequence and the attention state?

**Comment by Fhrozen** [comment]
From the paper:

>: The decoder network in Eq. (28)
is another recurrent network conditioned on the previous
output cl−1 and hidden vector ql−1, similar to an RNNLM,

**Comment by kobiche** [comment]
Thanks again!
