### ISSUE TITLE
how to make LM flexible | change & update it

### ISSUE THREAD

**Issue by vcjob** [espnet/espnet#1303]
Hello everyone!

I know, that the NN works in pair with LM, so LM kinda projects NN predicted phonemes to the real words, right?
Therefore, If the word is not presented in the LM, the ASR most likely suggest the closest word presented in LM, or just will omit it. 
My question is, is there a way to quickly update the LM (push a new word into it OR pop some special words out)? Will it reduce performance somehow? Is it only possible by re-training the LM model? Maybe I can 'on the fly' change some words importance (e.g. I know the text is about foreign languages, may I reduce the weight for "for an", so to insure "foreign" will be recognized correctly. I know, the example is not perfect, but I hope you've got the idea. Or knowing the text is about what a person wishes now for, I may want to reduce the probability of the "won't", so to ensure "want" will be recognized correctly)

Thank you a lot for your help!

**Comment by Fhrozen** [comment]
Hi there,
Maybe there are some parts to clarify (I apologize in advance if I misunderstood you):

>I know, that the NN works in pair with LM, 

For ESPnet, LM is used to improve the performance of the end-to-end deep model and the recipes in 
ESPnet works with words (or characters/sub-words) input and output. 

> so LM kinda projects NN predicted phonemes to the real words, right?

I think that there are some recipes that maybe works with phonemes like https://github.com/espnet/espnet/tree/master/egs/timit/asr1. But Most (all) of the ASR in ESPnet generates words (or characters/sub-words) 

>Therefore, If the word is not presented in the LM, the ASR most likely suggest the closest word presented in LM, or just will omit it.

Yes. But only if you use LM for decode. If you remove it, new words would (probably) be generated by the ASR. For that, comment (or delete) the following line  (egs. Librispeech ) https://github.com/espnet/espnet/blob/f14b7e181f97851623348146d6725ac17bb81527/egs/librispeech/asr1/run.sh#L290.

About you question: 

>is there a way to quickly update the LM (push a new word into it OR pop some special words out)? 

Do you mean to a dynamic lexicon (https://arxiv.org/abs/1906.04323). This feature is not implemented in ESPnet.

>Will it reduce performance somehow? 

Good question. (No answer, sorry)

>Is it only possible by re-training the LM model? 

Yes (But It will take time depending on the corpus size)

>Maybe I can 'on the fly' change some words importance (e.g. I know the text is about foreign languages, may I reduce the weight for "for an", so to insure "foreign" will be recognized correctly. I know, the example is not perfect, but I hope you've got the idea. Or knowing the text is about what a person wishes now for, I may want to reduce the probability of the "won't", so to ensure "want" will be recognized correctly

Once more dynamic lexicon.

I hope this may solve some of your questions. Later, someone else will be improving the provided answers.
