### ISSUE TITLE
tts phoneme models not training in docker 

### ISSUE THREAD

**Issue by flip-arunkp** [espnet/espnet#1322]
Hi,

When I use docker to train tts transformer v3 model which uses phonemes as input:

./run.sh --docker_gpu 0,1,2 --docker_egs ljspeech/tts1 --docker_folders /export/ljspeech/tts1 --ngpu 3 --train_config conf/tuning/transformer.v3.yaml

I get nltk module not found:

ModuleNotFoundError: No module named 'nltk'

I understand that it uses nltk (cmu) and g2p packages. How can we add these dependencies while building the image?

Thanks in advance

**Comment by sw005320** [comment]
I see.
I just searched `nltk` so I did not notice it.

**Comment by flip-arunkp** [comment]
OK. I think the old image is being used. I will clean them and build again. Thanks for prompt reply
