### ISSUE TITLE
utt2spk_to_spk2utt.pl has syntax error

### ISSUE THREAD

**Issue by lamudazh** [espnet/espnet#1325]
when install $ ./run.sh --backend chainer, there is a error happens, says utt2spk_to_spk2utt.pl line21 has syntax error
line21: 'if (@argv >1){ '

for x in test train; do
    for f in text wav.scp utt2spk; do
        sort data/${x}/${f} -o data/${x}/${f}
    done
    sudo bash utils/utt2spk_to_spk2utt.pl data/${x}/utt2spk > data/${x}/spk2utt

**Comment by kan-bayashi** [comment]
> sudo bash utils/utt2spk_to_spk2utt.pl data/${x}/utt2spk > data/${x}/spk2utt

Why did you use `sudo bash`?
This is the perl script.

**Comment by lamudazh** [comment]
restore to original also not work: 
utils/utt2spk_to_spk2utt.pl data/${x}/utt2spk > data/${x}/spk2utt
