### ISSUE TITLE
How to trace (torch.jit.trace) the E2E model?

### ISSUE THREAD

**Issue by sknadig** [espnet/espnet#1326]
How to serialize an [`E2E`](https://github.com/espnet/espnet/blob/master/espnet/nets/pytorch_backend/e2e_asr.py#L53) model using [`torch.jit.trace`](https://pytorch.org/docs/stable/jit.html#torch.jit.trace)

Here's a [sample notebook](https://gist.github.com/sknadig/3334de9c9db454eb89ac3542b38b7c9f) to replicate this issue.

I'm trying to add the graph to tensorboard. But, when I try to call the  `writer.add_graph()` function, I get an error `ValueError: Auto nesting doesn't know how to process an input object of type int. Accepted types: Tensors, or lists/tuples of them` at [this line](https://github.com/espnet/espnet/blob/master/espnet/nets/pytorch_backend/rnn/decoders.py#L192) 

```python
for i in six.moves.range(olength):
    if self.num_encs == 1:
        att_c, att_w = self.att[att_idx](hs_pad[0], hlens[0], self.dropout_dec[0](z_list[0]), att_w)
```

After some reading, I found that if we can trace the model using [`torch.jit.trace`](https://pytorch.org/docs/stable/jit.html#torch.jit.trace), we can also add it to the tensorboard graph for visualization.

Couple of things I tried so far (None working as of now):

- As we are using `torch.nn.ModuleList`, the [documentation](https://pytorch.org/docs/stable/jit.html#for-loops-over-constant-nn-modulelist) suggests adding these to `__constants__` list. So, I added it to [decoders.py](https://github.com/espnet/espnet/blob/master/espnet/nets/pytorch_backend/rnn/decoders.py#L48) and [e2e_asr.py](https://github.com/espnet/espnet/blob/master/espnet/nets/pytorch_backend/e2e_asr.py#L60)

```python
class Decoder(torch.nn.Module, ScorerInterface):
    __constants__ = ['decoder', 'dropout_dec']
    def __init__(self, eprojs, odim, dtype, dlayers, dunits, sos, eos, att, verbose=0,
                 char_list=None, labeldist=None, lsm_weight=0., sampling_probability=0.0,
                 dropout=0.0, context_residual=False, replace_sos=False, num_encs=1):
```

```python
class E2E(ASRInterface, torch.nn.Module):
    __constants__ = ['enc', 'ctc', 'att', 'dec']
    @staticmethod
    def add_arguments(parser):
```

- Checking out the commit before multi-encoder `25088caf9e0fe5676bc0454fd81e681ed1ce49eb` and defining the indices as constants for every module.

Any ideas on how to go about achieving this?
Does it require lot of changes to the base code?
This would also allow the models to be serializable and could be run independently from python in a C++ environment.

I am able to trace the `Encoder` and add it to the graph if I only use `model[0].enc` in my notebook. Thus, this seems to be an issue only with the `Decoder`.

**Comment by sw005320** [comment]
thanks for your report!
do you know more details about which functions in the decoder seem to cause the issue?
As you know the decoder part is more complicated and tricky due to the attention.

also how about trying it to the transformer?
the transformer forward is rathe simple.
