### ISSUE TITLE
How to speed up training

### ISSUE THREAD

**Issue by 943274923** [espnet/espnet#1328]
I tried training on 4GPUs(P100,16GB) on LibriSpeech 1000 hour data with conf/tuning/train_pytorch_transformer_large_ngpu4.yaml . it will  take me 9 days  for the training to complete. how to speed up training .

**Comment by ahmedalbahnasawy** [comment]
@943274923 its depend on the stage you want to start. so if you want to start from stage 3 which is training LM or skip it at start by training ASR model (stage 4). try to increase your batch_size and decrease number of epochs.

**Comment by 943274923** [comment]
Thank you，how many epochs do i need for 1000 hours data



---Original---

**Comment by kan-bayashi** [comment]
The librispeech recipe uses `SpecAug` as default.
This requires many epochs to converge.
Around 30 epochs the performance is already good but if you continue to train, the performance will gradually improve.
So it depends on you to stop the training.

If the GPU utilization is not high (you can check via `nvidia-smi`), you can add `n-iter-processes: 4 or more` in config file to accelerate batch making.
This helps to improve the GPU utilization.

**Comment by 943274923** [comment]
Thank you, I set&nbsp;n-iter-processes: 8&nbsp;but it can not work ,train log is :
"
/data/espnet/tools/venv/lib/python3.7/site-packages/torch/nn/parallel/_functions.py:61: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
&nbsp; warnings.warn('Was asked to gather along dimension 0, but all '
/data/espnet/tools/venv/lib/python3.7/site-packages/chainer/iterators/multiprocess_iterator.py:28: TimeoutWarning: Stalled dataset is detected. See the documentation of MultiprocessIterator for common causes and workarounds:
https://docs.chainer.org/en/stable/reference/generated/chainer.iterators.MultiprocessIterator.html
&nbsp; MultiprocessIterator.TimeoutWarning)
"



------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Tomoki Hayashi"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月3日(星期天) 晚上8:46
收件人:&nbsp;"espnet/espnet"<espnet@noreply.github.com&gt;;
抄送:&nbsp;"943274923"<943274923@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [espnet/espnet] How to speed up training (#1328)




The librispeech recipe uses SpecAug as default.
 This requires many epochs to converge.
 Around 30 epochs the performance is already good but if you continue to train, the performance will gradually improve.
 So it depends on you to stop the training.
 
If the GPU utilization is not high (you can check via nvidia-smi), you can add n-iter-processes: 4 or more in config file to accelerate batch making.
 This helps to improve the GPU utilization.

**Comment by sw005320** [comment]
`n-iter-processes:` seems to have some issues. We actually did not observe the benefit of it in CLSP. Also, it makes training unstable (too slow or crash). This depends on the cluster setup and may not always be applied to the others, but just a note.

**Comment by kaituoxu** [comment]
Hi @sw005320 , I get the same issue with @943274923 if I set `n-iter-processes=2 or 4`. And it seems that the training speed on 8 GPU is slower than on 4GPU, besides, the GPU-util is very small (20%+ on 8GPU, not stable on 4GPU: sometimes 0%, sometimes 20%, sometimes 90%).

I guess it because the dataloader of Chainer is slow, maybe implement dataloader with PyTorch will improve the training speed.

**Comment by 943274923** [comment]
i use pytorch



---Original---

**Comment by gs5264** [comment]
> Hi @sw005320 , I get the same issue with @943274923 if I set `n-iter-processes=2 or 4`. And it seems that the training speed on 8 GPU is slower than on 4GPU, besides, the GPU-util is very small (20%+ on 8GPU, not stable on 4GPU: sometimes 0%, sometimes 20%, sometimes 90%).
> 
> I guess it because the dataloader of Chainer is slow, maybe implement dataloader with PyTorch will improve the training speed.

PyTorch's speech is also slow. Gpu is not stable as well as chainer.

**Comment by ElijhaLee** [comment]
Did anyone check the usage of shared memory when n_iter_processes>1? Someone told me when n-ter-processes is set to 10, the training speed is greatly improved and the usage of shared memory is ~300M which can be observed by `df /dev/shm`, while in my situation only 17M is used, and I didn't see much improvement on the training speed.

Can anyone check your /dev/shm ?

**Comment by ElijhaLee** [comment]
@943274923 Do you have any update? I tried the same setting(original `conf/tuning/train_pytorch_transformer_large_ngpu4.yaml` and without any modification on any code), the speech is 0.25iter/sec, do u have the same situation?
