### ISSUE TITLE
New development plan

### ISSUE THREAD

**Issue by sw005320** [espnet/espnet#133]
I'm now managing several development plans upon requests.
Please feel free to ask us any functions that you feel it is beneficial for your research.
What I got requests so far are

- Fix VGG-BLSTM in PyTorch
- Generalize to accept multiple input/output streams
- Back compatibility
- Add unidirectional LSTM layer in the encoder
- Output attention weights 
- Output more detailed decoder information (e.g., each score at every output time step) for post processwing
- Scheduled sampling to handle exposure bias 
- Completely switch to pure CTC or seq2seq by mtlalpha = 0.0 or 1.0
- end of sentence norm and length norm
- Tensorboard X visualization for pytorch and chainer (https://github.com/lanpa/tensorboard-pytorch ???)

**Comment by sw005320** [comment]
We (@arendo and @m-wiesner) are planning to add speech translation recipes.

**Comment by hirofumi0810** [comment]
@sw005320 

I'm interested in the extension of espnet for speech translation tasks.
So I want to add new recipes and develop some modules.

**Comment by sw005320** [comment]
Thanks. I'm also planning it. Let's do it :)

**Comment by kan-bayashi** [comment]
Move on to #334
