### ISSUE TITLE
Parser in e2e_asr_transducer is missing a return statment

### ISSUE THREAD

**Issue by ahmedalbahnasawy** [espnet/espnet#1334]
In the code: https://github.com/espnet/espnet/blob/master/espnet/nets/pytorch_backend/e2e_asr_transducer.py

You're not returning parser in `add_arguments`. This throws an error when attempting to call `E2E.build()`

**Comment by sw005320** [comment]
Thanks for the report.
@b-flo, could you confirm it?

**Comment by b-flo** [comment]
Hi,

Thank you for the report!
I can confirm `parser` isn't returned as it should be. However before making any change, could you copy the error thrown please? I'm extensively using RNNT/RNNT-Att with arguments specific to the implementation and I did not encountered any errors. I'm a bit intrigued on why it wasn't reported/catched before.

**Comment by rai4** [comment]
User classes are considered mutable. Python doesn't have (absolutely) private attributes, so you can always change a class by reaching into the internals. So the parser variable is considered a call by reference. I also did not encountered any errors.

```
from espnet.utils.dynamic_import import dynamic_import
    if args.model_module is None:
        model_module = "espnet.nets." + args.backend + "_backend.e2e_asr:E2E"
    else:
        model_module = args.model_module
    model_class = dynamic_import(model_module)
    model_class.add_arguments(parser)

    args = parser.parse_args(cmd_args)
    args.model_module = model_module
```

**Comment by rai4** [comment]
User classes are considered mutable. Python doesn't have (absolutely) private attributes, so you can always change a class by reaching into the internals. So the parser variable is considered a call by reference. I also did not encountered any errors.

```
from espnet.utils.dynamic_import import dynamic_import
    if args.model_module is None:
        model_module = "espnet.nets." + args.backend + "_backend.e2e_asr:E2E"
    else:
        model_module = args.model_module
    model_class = dynamic_import(model_module)
    model_class.add_arguments(parser)

    args = parser.parse_args(cmd_args)
    args.model_module = model_module
```

**Comment by b-flo** [comment]
> Python doesn't have (absolutely) private attributes, so you can always change a class by reaching into the internals. So the parser variable is considered a call by reference

That's why I suspected but I wanted to be sure given the error! Thanks for the info!

**Comment by ahmedalbahnasawy** [comment]
Thanks for taking the time to review my issue.
The issue arises when trying to import E2E asr_transducer, then using the command E2E.build(). The error occurs when the line `default_args, _ = add_arguments(argparse.ArgumentParser()).parse_known_args()` is executed in the file `(...)/espnet/utils/fill_missing_args.py`.
Using the available train an eval files will not yield that error, but creating a new python file with the correct imports will create the error: `NoneType Object does not have attribute parse_known_args()`

**Comment by thethiny** [comment]
Thank you for the PR that fixes the issue. I read your explanation and came to understanding of your point. What you're doing is passing a `parser `object by reference to the `add_argument `function, which is working well for you. However, in your code `/path/to/utils/fill_missing_args.py` you're assuming that `parser `is returned, since you're calling `parse_known_args()` on the execution of the function, therefore failing in this case. Another solution can be introduced which is to change the line `default_args, _ = add_arguments(argparse.ArgumentParser()).parse_known_args()` into separate lines as so:
```
parser = argparse.ArgumentParser()
add_arguments(parser)
default_args, _ = parser.parse_known_args()
```

Regards,
