### ISSUE TITLE
Better performance with one GPU (with the exact same config)

### ISSUE THREAD

**Issue by dfelmanl** [espnet/espnet#1335]
I am currently working with AWS and created an image of a machine with ESPnet installed and tested.

Then I spun up two machines over that image: One with one GPU and another one with eight; and ran the LibriSpeech recipe over a small dataset of 5h (yes, I know it is very small but at the moment we are not prioritized to get SOTA results).

After more than an hour or running I realized that not only the machine with I GPU is just slightly slower, it also has a much better performance.

After the same amount of time running, these are the accuracy plots:
8 GPUs
![image](https://user-images.githubusercontent.com/24211334/68296103-753c3680-009c-11ea-8cf3-7ae7cfc92518.png)

1 GPU
![image](https://user-images.githubusercontent.com/24211334/68296170-a1f04e00-009c-11ea-99fc-e1618141249c.png)

How can this happen?

Thanks in advance

**Comment by kan-bayashi** [comment]
If you use multi-gpu, the batch-size will be automatically multiplied by the number of gpus (if batch size = 32 and the number of gpus = 3, the actual batchsize will be 96 during training). Maybe you can find the warning messages in the `train.log`. In the case of small amount of training data with RNN, a large batch size causes serious performance degradation.

**Comment by rai4** [comment]
@kan-bayashi The batch size increase log message is info level, not warning. 
Also I didn't know at first whether there was no warning and whether the batch size would increase automatically, and when I did it myself, it ran out of memory.
So i suggest changing to a warning level.

**Comment by kan-bayashi** [comment]
I agree. I will make PR.

**Comment by rai4** [comment]
@kan-bayashi, Thanks for your PR.
