### ISSUE TITLE
Speaker mumbling when synthesize very long sentence

### ISSUE THREAD

**Issue by enamoria** [espnet/espnet#1338]
Hello, I trained Transformer and Fastspeech and Tacotron2 (nvidia), all of them suffer from long sentence synthesis, when the speaker starts mumbling when the length of the (synthesized) audio exceed the maximum length of audio in the training set. I know cut the original sentence into slices can help fixing this, but it looks like a workaround to me, not a solution :D 

This is the predicted melspec, the first 10 seconds are good, but from that point on, it's disaster.
![image](https://user-images.githubusercontent.com/22177090/68361122-36b68280-0155-11ea-929c-86388ed67d1a.png)

Are there any ideas? Really looking forward to hearing some suggestion
Thanks!

**Comment by kan-bayashi** [comment]
Did you try forward attention in Tacotron~2?
I've never tried to generate too long sentences but it is worthwhile to try.

Recently google guys have proposed dynamic convolution attention to avoid such kind of issue.
This paper might be interesting for you.
https://arxiv.org/abs/1910.10288
We will plan to implement this feature in v.0.6.0 (#1329).

**Comment by r9y9** [comment]
I would like to consider this a fundamental problem we need to address in the future. Can we tag a proper label for the issue?
