### ISSUE TITLE
Run tts_train.py in the shell causes all CPU cores 100%

### ISSUE THREAD

**Issue by geekboood** [espnet/espnet#1345]
Hi, I try to run `tts_train.py` in the shell but it leads to all my CPU cores 100%. I encounter this under Linux and use `run.sh` under example dir will not cause this problem.

**Comment by geekboood** [comment]
Use `export OMP_NUM_THREADS=1` seems to fix this problem. But why? I thought this process is purely using PyTorch.

**Comment by kan-bayashi** [comment]
`OMP_NUM_THREADS` is the environmental variable to control the number of threads to be used in python libraries.
I'm not sure which part utilizes CPU power, but let me confirm whether you used gpu in the training.

**Comment by geekboood** [comment]
@kan-bayashi I use `nvidia-smi -lms` command and confirm that GPU is used. Also `export OMP_NUM_THREADS=1` is used by default in many `path.sh` file under examples in `egs` directory. To be more specific, I found this problem when I try to train the `csmsc/tts1` example.

**Comment by kan-bayashi** [comment]
By default, we use GPU but when you met the problem where all of cpu cores were used, did you use GPU?

**Comment by geekboood** [comment]
@kan-bayashi Yes. You can change the `export OMP_NUM_THREADS=1` to a larger number and  train the neural network by using GPU and see how it will utilize CPU.

**Comment by kan-bayashi** [comment]
OK. I think this is not problematic since there are many modules in training scripts such as data loader, hook functions, and so on.
So I will close this issue.
If you want a further investigation, please reopen this issue.
