### ISSUE TITLE
Help with extending functionality of synth_wav.sh?

### ISSUE THREAD

**Issue by adhamel** [espnet/espnet#1349]
I'm working on extending TTS to the languages and speakers available in /egs/m_ailabs but synth_wav.sh will only output a default speaker. 

I have followed this procedure: executed run.sh through step 2, brought in a tacotron checkpoint, executed one epoch of training to obtain a proper snapshot, executed run.sh Stage 4 Network Decoding, and then the following for wav synthesis.
```

../../../utils/synth_wav.sh --models ljspeech.tacotron2.v3 \
	--stage 3 \
	--stop_stage 4 \
	--cmvn data/fr_FR_bernard_train_trim/cmvn.ark \
	--dict data/lang_1char/fr_FR_bernard_train_trim_units.txt \
	--synth_model exp/fr_FR_bernard_train_trim_pytorch_train_pytorch_tacotron2.v3/results/model.last1.avg.best \
	--decode_config conf/decode.yaml \
	--vocoder_models ljspeech.wavenet.softmax.ns.v1 \
	example.txt
```

How are we able to produce synthesized voice in another language and voice? Also, can direct steps be taken to modify the produced voice further? Thank you for your guidance and I look forward to contributing to your community.

**Comment by kan-bayashi** [comment]
Hi @adhamel. Just now I made demo notebook for realtime generation.
https://colab.research.google.com/github/espnet/notebook/blob/master/tts_realtime_demo.ipynb
This notebook will help you!

**Comment by adhamel** [comment]
You are amazing!

**Comment by adhamel** [comment]
@kan-bayashi, this is great. I would like to expand to languages included in M-AILABS datasets. Do you know of any resources similar to open_jtalk that would make this possible?

**Comment by kan-bayashi** [comment]
@adhamel You means text front module?

**Comment by adhamel** [comment]
I mean cleaners such as pypinyin and pyjtalk, though I have found a workaround. I would love to extend to French, for instance. Do you have a gauge of how involved creating a workable parallel wavegan model would be?

Also, I find the Mandarin implementation works well on a control sentence I confirmed with a native speaker. In case you would like the text front-end print statement to be consistent between demos, here is "Input your favorite sentence in Mandarin!"
print("請用中文輸入您喜歡的句子!")

**Comment by kan-bayashi** [comment]
> I would love to extend to French, for instance

If you build character-based model, the NLP preprocessing tools can be used.
@hirofumi0810 Do you know the preprocessing tools for French?

> Do you have a gauge of how involved creating a workable parallel wavegan model would be?

The building of Parallel WaveGAN is easy. What we need is to prepare `wav.scp` for training, development, and evaluation sets. Might you can understand the flow from the recipe 
https://github.com/kan-bayashi/ParallelWaveGAN/blob/f07f2ef40ad2a604ae061d7ab397fc644ba8feb8/egs/ljspeech/voc1/run.sh
In stage 0, we made `data/{train_set,dev,eval}/wav.scp` and stage 1-3 are exactly the same among the recipes. So you can directly start from stage 1 if you reuse `wav.scp` created in the espnet recipe.

> Also, I find the Mandarin implementation works well on a control sentence I confirmed with a native speaker. In case you would like the text front-end print statement to be consistent between demos, here is "Input your favorite sentence in Mandarin!"
> print("請用中文輸入您喜歡的句子!")

That's nice. Thanks for your report.
You are right. I will change the statement.

**Comment by b-flo** [comment]
Hi @kan-bayashi ,

I'm mostly working with French resources (mainly for ASR though) so I could maybe provide some informations/tools if needed. However I'm not sure what you mean by "preprocessing tools for French"?

**Comment by kan-bayashi** [comment]
@b-flo Maybe text cleaner or g2p module. I know the g2p for Japanese, English, and Mandarin but I have never used for the other language. Do you know such kind of tools?

**Comment by b-flo** [comment]
For g2p, the two available resources I know are : https://github.com/mozilla/g2p/tree/master/dicts/french and https://montreal-forced-aligner.readthedocs.io/en/latest/pretrained_models.html. I would recommend looking at the first link, it contains the phonetic lexicon previously provided by the LIUM in Sphinx4 and the phone set used in the g2p phone is similar to the one commonly used in French ASR systems.  I didn't use the tool though, I have custom g2p models and scripts.

For text cleaner, I don't know any available resources unfortunately. I can't provide my own data preparation scripts but I can make a new script. However depending on the system, some things should be discussed such as typographic signs, diatrics, anglicism, liaison, etc.

**Comment by kan-bayashi** [comment]
That is nice. Thank you for your information, @b-flo. These modules will help you, @adhamel.

**Comment by adhamel** [comment]
@b-flo thank you for sharing this. I'm sure it will steer me in the correct direction.

@kan-bayashi I really appreciate all of your help here. Parallel WaveGAN is converging very nicely. 
The discriminator loss (started training at 100k) is the only stubborn decline, hovering around ~.496-.497. If you like, after training on this different data set. I can let you know if I find any of the problems with strange noise you mention.

**Comment by kan-bayashi** [comment]
It seems this issue is solved. I will close this issue.
