### ISSUE TITLE
--preprocess_conf is not needed to pack TTS models

### ISSUE THREAD

**Issue by kan-bayashi** [espnet/espnet#1353]
`--preprocess_conf` check is added in 
https://github.com/espnet/espnet/commit/a3ebc07a3ffd0885fa17af7f041e7d511743820d#diff-b61f0f75b4324fab7fa1a2e458cd00cb
But for TTS, it is not needed.

**Comment by hirofumi0810** [comment]
@kan-bayashi This is an option. Why should we remove this?

**Comment by hirofumi0810** [comment]
@kan-bayashi Sorry. I got it.
