### ISSUE TITLE
Obtaining output encodings for pretrained ASR models

### ISSUE THREAD

**Issue by danoneata** [espnet/espnet#1356]
Hello!

For the pretrained ASR models is there an easy way of getting the `token`s and `tokenid`s of the groundtruth text? As far as I can tell, these encodings are obtained with `spm_encode`, but this requires the `bpemodel`, which is not packaged in the pretrained models:

```
$ tree 
.
|-- conf
|   |-- decode.yaml
|   `-- train_d6.yaml
|-- data
|   `-- train_trim_sp
|       `-- cmvn.ark
`-- exp
    |-- train_rnnlm_pytorch_lm_unigram500
    |   |-- model.json
    |   `-- rnnlm.model.best
    `-- train_trim_sp_pytorch_train_d6
        `-- results
            |-- model.json
            `-- model.last10.avg.best
```

I could try to reverse engineer the process based on the `char_list_dict` in the RNN-LM model, but I wonder if there is a cleaner way of achieving this.

Thank you!

**Comment by Fhrozen** [comment]
You can find a similar situation at #1275. Try to run the recipe up to stage 2. The bpe units should be the same as the one provided by the pre-trained,.

**Comment by sw005320** [comment]
I think this is an important point. We should include the BPE model when we pack the model. I'll ask people to do it.

**Comment by danoneata** [comment]
@Fhrozen Thanks for the suggestion! That should work for now, but I agree with @sw005320 that it would be better to pack it with the model because _(i)_ it is inconvenient to download a large dataset and _(ii)_ it can be error prone to retrain, as it's not always clear what parameters were used for a given pretrained model. I believe that having access to the BPE model can be useful in a number of scenarios (_e.g._, fine-tuning).

**Comment by sw005320** [comment]
I fully agree with you. thanks for your suggestions!
