### ISSUE TITLE
Sclite "Segmentation fault" encountered for Fr-Commonvoice

### ISSUE THREAD

**Issue by ftshijt** [espnet/espnet#1357]
I recently found that the sclite for WER get "segmentation fault" when computing the decoded french trn files.

The error message is as follows:

`tools/espnet/utils/score_sclite.sh: line 121: 14394 Segmentation fault      sclite -r ${dir}/ref.trn trn -h ${dir}/hyp.trn trn -i rm -o all stdout > ${dir}/result.txt`

The two relating trn file is in the following links (for you to check the error):
https://drive.google.com/file/d/1vh7TbR_zHZI5yR3F3zTEufEIjID2VZS1/view?usp=sharing

**Comment by sw005320** [comment]
Can you tell me which file would have an issue (you can check it by feeding the same hyp or ref files for the script)?
Then, please try to find which line causes the issue.

**Comment by ftshijt** [comment]
After tests, a sample that caused the issue is recognized as follows. If we input the two lines to sclite, the segmentation fault can be reproduced.

`"MADAME DE FERNEUSE DONNA UN COUDAILLE TOUR D'ELLE, OBSERVANT ET DéTAIL.`
`M^{ME} DE FERNEUSE DONNA UN COUP D’œIL AUTOUR D’ELLE, OBSERVANT CES DéTAILS.`

The files can be found in the following link:
https://drive.google.com/file/d/1NvQWoYVETd4nmMLVal_ElKZ6GjoqPFWL/view?usp=sharing

For convenience, the command for sclite is 
`sclite -r ref2509.wrd.trn trn -h hyp2509.wrd.trn trn -i rm -o all stdout > test.txt`

**Comment by sw005320** [comment]
Thanks, we're almost there.
Could you find which character causes this issue?
`sclite` would work for Unicode and my guess is that some special ASCII symbols (e.g., ^, {, }, ") may cause some problems. My guess is "^". Actually, "M^{ME}" does not make sense for me and we could remove such references in the data preparation. But anyway, could you check to see which character causes the problem?

**Comment by ftshijt** [comment]
My experiment shows that the problem results from “**{}**”. The phrase "M^{ME}" occurs three times in the whole dataset (with the same text). I personally believe that maybe some specific notation for some grammar cases. However, consider its' rareness, I will remove it for further processing of the set (I will add it in further pr of commonvoice).

What do you think about it?

**Comment by b-flo** [comment]
Hi,

That's an unusual way of annotating a shortened version of a word (M^{ME} -> Mme -> Madame).
IMO it should be normalized to the complete form during data preparation.

**Comment by sw005320** [comment]
Thanks, @b-flo and @ftshijt.
I think we can remove them because this only happens three times (also the same text).
