### ISSUE TITLE
join_suffix.py script might affect BPE units in TED-LIUM 2 recipe

### ISSUE THREAD

**Issue by danoneata** [espnet/espnet#1361]
Hello! When running the TED-LIUM recipe `egs/tedlium2/asr1` I have some problems with the BPE model. Namely, among the units from `data/lang_char/train_trim_sp_unigram500_units.txt` I see tokens such as
```
FARTHERTHANTHESUN_2005-0022785-0022859 8
_1990-0059139-0059166 15
_1998-0065813-0065847 16
_2007-0021335-0021365 17
_2010-0114108-0114304 18
_2010G-0026501-0026536 19
```
which are obviously parts of the segment ids. Am I the only one experiencing this problem?

---

I did some debugging and the error traceback looks something along these lines:

1. The file `data/train_trim_sp/text` contains lines with no text, but only the segment id; the [`cut -f 2 -d " "` command](https://github.com/espnet/espnet/blob/master/egs/tedlium2/asr1/run.sh#L123) will return just the segment id in this, as it doesn't find the delimiter:
```
CarolineLavelleFARTHERTHANTHESUN_2005-0022785-0022859
```

2. The empty lines appear because in the `data/train.orig/stm` there is missing a space between the gender information `<o,f0,female>` and the text `'s`:

```
CarolineLavelleFARTHERTHANTHESUN_2005 A CarolineLavelleFARTHERTHANTHESUN_2005 227.85 228.59 <o,f0,female>'s
```

3. The missing space is caused by the `local/join_suffix.py` script which [joins a word starting with an apostrophe to the previous one](https://github.com/espnet/espnet/blob/master/egs/tedlium2/asr1/local/join_suffix.py#L24-L25).

**Comment by sw005320** [comment]
> I did some debugging and the error traceback looks something along these lines:
> 
> 1. The file `data/train_trim_sp/text` contains lines with no text, but only the segment id; the [`cut -f 2 -d " "` command](https://github.com/espnet/espnet/blob/master/egs/tedlium2/asr1/run.sh#L123) will return just the segment id in this, as it doesn't find the delimiter:
> 
> ```
> CarolineLavelleFARTHERTHANTHESUN_2005-0022785-0022859
> ```

I don't know why it happens, as the Kaldi text format is like that
```
<UTT ID> <word1> <word2> ...
```
and `cut -f 2- -d" " data/${train_set}/text ` should extract `<word1> <word2> ...`. Or do you mean to say that the generated text is not like the above?

**Comment by danoneata** [comment]
That is indeed the text format, but for some lines there is only `<UTT ID>` and no words; for example:

```
CarolineLavelleFARTHERTHANTHESUN_2005-0015816-0015843 you
CarolineLavelleFARTHERTHANTHESUN_2005-0022254-0022348 you
CarolineLavelleFARTHERTHANTHESUN_2005-0022785-0022859
```

Running the `cut -f 2- -d" "` command on these lines yields:

```
you
you
CarolineLavelleFARTHERTHANTHESUN_2005-0022785-0022859
```

**Comment by sw005320** [comment]
Oh, I got it.
If you add the option in `remove_longshortdata.sh --minchars 1` in  
```
https://github.com/espnet/espnet/blob/master/egs/tedlium2/asr1/run.sh#L86-L87
```
Then, it must be OK.
I think we need to change the default value of `minchars=1` in `remove_longshortdata.sh`.

**Comment by danoneata** [comment]
Thanks! Yes, that's one possible solution. Another one would be to add the `-s` flag to the `cut` command – this would filter out the lines that do not contain the delimiter. However, I believe the root cause is related to the way in which `join_suffix.py` interacts with the STM files; but fixing this will require a bit more work and care.

I have realized that the same problem also occurs in the original Kaldi recipe, but the effect there is not as obvious, as they use the text data only to evaluate the language model.
