### ISSUE TITLE
Is there any plan to support multi-machine multi-GPU ASR training?

### ISSUE THREAD

**Issue by kaituoxu** [espnet/espnet#1375]
Hello, I notice that espnet's PyTorch version uses `data_parallel` to support multi-GPU, but to my understanding, this can only be used in single-machine. Is there any plan to support multi-machine multi-GPU ASR training? So that making 10k+ hours training feasible in the industry. Thx.

**Comment by sw005320** [comment]
We have been working internally with several projects and it's working with some minor changes, but I want to move in this direction once we fix a new training abstraction design (e.g., #1372). We're thinking of a (super) major update for this.
