### ISSUE TITLE
Does output of the confidence value (porobability) suported on asr_recog.py or other decoding utility?

### ISSUE THREAD

**Issue by takeofuture** [espnet/espnet#1378]
I wonder if it is possible to get confidence value(probability) in output of decoding result.
I am checking asr_recog.py .
But if you know in your mind, I appreciate.

Thank you!

**Comment by sw005320** [comment]
You can get n-best (`--nbest`) and by normalizing the probability (from the total log probability per hypothesis by setting `--verbose 1`), you can get a posterior probability for each hypothesis.

**Comment by takeofuture** [comment]
@sw005320 
Thank you!
I tested, and for example if I --nbest 100 or so
I got scores on decode directory after running utils/recog_wav.sh (with --nbest 100 added --verbose 1 or 2) for each decoding results.
How can I interpret the scores? 
Looks like higher is better but it is minus values

```
espnet/egs/csj/asr1/decode/my_test$ cat result.json | grep score
                    "score": -12.956483840942383,
                    "score": -19.143564224243164,
                    "score": -20.607860565185547,
                    "score": -20.794517517089844,
                    "score": -21.406919479370117,
                    "score": -22.12215232849121,
                    "score": -23.07274627685547,
                    "score": -23.46160316467285,
                    "score": -23.72710609436035,
                    "score": -23.825206756591797,
                    "score": -23.852027893066406,
                    "score": -23.881881713867188,
                    "score": -24.010822296142578,
                    "score": -24.083030700683594,
                    "score": -24.106470108032227,
                    "score": -24.170551300048828,
                    "score": -24.372873306274414,
                    "score": -24.422998428344727,
                    "score": -24.62731170654297,
                    "score": -25.546606063842773,
                    "score": -32.2293815612793,
                    "score": -32.566200256347656,
                    "score": -32.659793853759766,
                    "score": -33.26021957397461,
                    "score": -33.45044708251953,
                    "score": -33.5009880065918,
                    "score": -34.020652770996094,
                    "score": -43.39907455444336,
                    "score": -43.74912643432617,
                    "score": -44.004756927490234,
                    "score": -44.13517379760742,
                    "score": -44.21462631225586,
                    "score": -44.286643981933594,
                    "score": -44.34130859375,
```

**Comment by sw005320** [comment]
this is based on "log probability" and you can make it back to the probability by taking `exp` and then perform normalization to satisfy the sum-to-one probability condition.

**Comment by takeofuture** [comment]
@sw005320 
Ah!  I see
Actually the first score with -12.956483840942383 
has the perfect decoding text and it has much higher than 2nd highest one (-19.143564224243164). 
It makes sense, so I should get very very high %  on th3 fist one if I normalizes it 
Thank you for your advise!

**Comment by chrisspen** [comment]
Are you sure the score value is log probability? The value doesn't make any sense. Even though some models get close to 100% accurate on my test data, the scores are all large negative values, meaning if   I convert them to probability, they're all effectively 0. Is that intentional? Are these models just highly uncertain of all their predictions? Or does the score represent error, and be inverted to represent certainty?

**Comment by takeofuture** [comment]
I did with --nbest 4 again and I got exactly the same score as --nbest 100
```
espnet/egs/csj/asr1/decode/my_0$ cat result.json | grep scor
                    "score": -12.956483840942383,  => Perfect Decoding One P1
                    "score": -19.143564224243164, 
                    "score": -20.607860565185547,
                    "score": -20.794517517089844,
```
I assume 
P1 = exp(-12.95) / (exp(-12.95)+exp(-19.14)+exp(-20.60)+exp(-20.79))
I can use it as confidence and my test result actually match 
 
My example works since the1st  best score is outstandingly higher than others (It is actually the perfect decoding result)
But possibly if the most of scores are very close each other for large number of nbest,
Then you might miscalculate the probability by dividing smaller denominator.

**Comment by sw005320** [comment]
Yes, to compute the probability you need to use the log sum exponential technique (https://en.wikipedia.org/wiki/LogSumExp) to avoid the underflow issues. Also, in this kind of case (not only for e2e ASR. It happens for the sequential data processing everywhere), the posterior becomes very peaky, i.e., the 1 best posterior becomes almost one and the others become almost zero. If you want to avoid peaky posteriors, you may introduce a smoothing hyperparameter, e.g., 
exp(value1), exp(value2), ... -> exp(_a_ * value1), exp(_a_ * value2) ,...

By setting a small value to _a_ , you can make all probabilities in a similar range, and you can avoid having peaky posteriors. But please note that _a_ is an additional hyperparameter. This is a well-known techniques.
