### ISSUE TITLE
2-C installation fails with compilation error

### ISSUE THREAD

**Issue by chrisspen** [espnet/espnet#1379]
I installed all the listed dependencies on Ubuntu 18.04, and tried to run the make command for the 2-C step like:

    git clone git@github.com:espnet/espnet.git
    cd espnet
    sudo apt-get install libprotobuf10 protobuf-compiler libprotobuf-dev
    sudo apt-get install libsndfile1-dev
    virtualenv -p python3.6 .env
    . .env/bin/activate
    cd tools
    time make CUPY_VERSION='' -j 10

but compilation fails with the error:

    Warning: IRSTLM is not installed by default anymore. If you need IRSTLM
    Warning: use the script extras/install_irstlm.sh
    All done OK.
    make[1]: Leaving directory '/home/chris/git/espnet/tools/kaldi/tools'
    cd kaldi/src; ./configure --shared --use-cuda=no; make depend; make all
    Configuring KALDI to use MKL.
    Checking compiler g++ ...
    Checking OpenFst library in /home/chris/git/espnet/tools/kaldi/tools/openfst-1.6.7 ...
    Doing OS specific configurations ...
    On Linux: Checking for linear algebra header files ...
    Configuring MKL library directory: ***configure failed: MKL libraries could not be found. Please use the switch --mkl-libdir or try another math library, e.g. --mathlib=ATLAS (would be slower) ***
    make[1]: Entering directory '/home/chris/git/espnet/tools/kaldi/src'
    Makefile:30: kaldi.mk: No such file or directory
    kaldi.mk does not exist; you have to run ./configure
    Makefile:90: recipe for target 'kaldi.mk' failed
    make[1]: *** [kaldi.mk] Error 1
    make[1]: Leaving directory '/home/chris/git/espnet/tools/kaldi/src'
    make[1]: Entering directory '/home/chris/git/espnet/tools/kaldi/src'
    Makefile:30: kaldi.mk: No such file or directory
    kaldi.mk does not exist; you have to run ./configure
    Makefile:90: recipe for target 'kaldi.mk' failed
    make[1]: *** [kaldi.mk] Error 1
    make[1]: Leaving directory '/home/chris/git/espnet/tools/kaldi/src'
    Makefile:44: recipe for target 'kaldi.done' failed
    make: *** [kaldi.done] Error 2

I'm not sure how to interpret this or identify what the failure is, but it looks like it had trouble finding a library called "MKL", which isn't listed as a dependency. Is that correct? How do I fix this?

**Comment by sw005320** [comment]
This is more-like a Kaldi issue, and I recommend you to search for solutions in the Kaldi documents 
 https://kaldi-asr.org/doc/matrixwrap.html may help your problem or forums.

**Comment by sw005320** [comment]
This is not fully related, but you could refer to the Docker building script and find what you require more exactly. https://github.com/espnet/espnet/blob/master/docker/prebuilt/runtime/Dockerfile. Required libraries depend on the environment, and it is not easy for us to fully support everything....
