### ISSUE TITLE
Question: RNN-T vs RNN-T Attn + What is the expected Vocab Size?

### ISSUE THREAD

**Issue by ridhwan-saal** [espnet/espnet#1381]
I'm trying to train espnet on a character-level dataset. My question would be, as for the English language, what is the expected vocab size? Currently I have a-z plus space and apostrophe, totaling 28. Should we add some EOS, UNK, and PADs manually to the dictionary, and is there a specific numbering scheme?
And what do you suggest to try with, RNN-T with or without Attention (bi-di/uni-di)?

Thanks

**Comment by b-flo** [comment]
Hi,

> Currently I have a-z plus space and apostrophe, totaling 28

Sounds good to me.

> Should we add some EOS, UNK, and PADs manually to the dictionary and is there a specific numbering scheme?

All special symbols are handled automatically (EOS/SOS, blank, " "/space and padding), you don't need to modify your transcripts. Also, note that RNN T / RNN T Att in espnet only deals with blank symbol, not EOS/SOS.

> And what do you suggest to try with, RNN-T with or without Attention (bi-di/uni-di)?

Depends on what you want to do and your dataset. From my experiments, RNN T with attention is slightly better in performance but is also slower than vanilla RNN T when dealing with characters.
For the architecture, it depends on your dataset. Bi-dir layers are preferred with current implementation though.

**Comment by ridhwan-saal** [comment]
@b-flo 
Thank you for the reply, however it got me confused when you said

> Also, note that RNN T / RNN T Att in espnet only deals with blank symbol, not EOS/SOS.

and 

> " "/space and padding)

So does that mean I should remove spaces from my dictionary?
Currently my dictionary looks like this:
```
  0
<eos> 2
<pad> 3
<space> 4
A 5
.
.
.
.
Z 30
' 31
```

**Comment by b-flo** [comment]
Sorry it lacked information.

Take a look at https://github.com/espnet/espnet/blob/master/egs/voxforge/asr1/run_rnnt.sh#L132-L139 (or any asr recipe) for a dict generation example.

First, we create a dict with `<unk> 1` as 0 is reserved for `<blank>` in espnet. Then, the text is tokenized (original space is converted to `<space>` by default and a -normal- space is inserted between each unit), sorted and we associate an ID to each unique unit (`<space> 2`, `' 3`, `A 4`, ...). In case of EOS/SOS, it's not included in the dictionary but the corresponding ID is `(last ID in dic)+1`.

>Thank you for the reply, however it got me confused when you said
>>    Also, note that RNN T / RNN T Att in espnet only deals with blank symbol, not EOS/SOS.

Sorry it was misleading. I just wanted to say that EOS/SOS symbols are not used in transducer implementations however you don't need to adapt your data preparation.

**Comment by ridhwan-saal** [comment]
Thank you for your helpful input, and you don't need to apologize as your help is greatly appreciated! This clears things up a lot. Thanks again.
