### ISSUE TITLE
failed at loading the model when decoding on fastspeech.v3.single

### ISSUE THREAD

**Issue by JoeyHeisenberg** [espnet/espnet#1382]
I try to train & decode on csmsc/conf/tuning/fastspeech.v3.single, but failed at decoding,
even with the model downloading from 
!./espnet/utils/download_from_google_drive.sh \
    https://drive.google.com/open?id=1T8thxkAxjGFPXPWPTcKLvHnd6lG0-82R downloads tar.gz > /dev/null 2>&1

![image](https://user-images.githubusercontent.com/33407667/69510965-b5932400-0f79-11ea-8515-edd2e3ca5965.png)

![image](https://user-images.githubusercontent.com/33407667/69510907-8e3c5700-0f79-11ea-9dc2-6957328693aa.png)

**Comment by kan-bayashi** [comment]
What is your espnet version?
v3 config needs `espnet>=0.5.3`.

**Comment by JoeyHeisenberg** [comment]
tts_decode.py --backend pytorch --ngpu 0 --verbose 0 --out exp/train_no_dev_pytorch_train_fastspeech.v3.single/outputs_model.last1.avg.best_decode/dev/feats.1 --json exp/train_no_dev_pytorch_train_fastspeech.v3.single/outputs_model.last1.avg.best_decode/dev/split16utt/data.1.json --model exp/train_no_dev_pytorch_train_fastspeech.v3.single/results/model.last1.avg.best --config conf/decode.yaml

**Comment by JoeyHeisenberg** [comment]
Thx， @kan-bayashi   After I update the version it did work！
![image](https://user-images.githubusercontent.com/33407667/69513442-be3c2800-0f82-11ea-9811-2bb9f20281db.png)
