### ISSUE TITLE
Is it possible to reuse Librispeech LM without wordpieces model?

### ISSUE THREAD

**Issue by smolendawid** [espnet/espnet#1383]
I'd like to use the LM model from here:

https://github.com/espnet/espnet/blob/master/egs/librispeech/asr1/RESULTS.md#pytorch-large-transformer-with-specaug-4-gpus--large-lm

Unfortunately, a word-pieces model isn't attached, so I am not able to train my own acoustic part, because I don't have unified inputs. Am I right? Is anyone able to share the correct BPE model with me?

**Comment by sw005320** [comment]
@ShigekiKarita or @kan-bayashi, could you upload the BPE model?

**Comment by kan-bayashi** [comment]
Here you are.
https://drive.google.com/drive/folders/1eO9uLEW0c6DlmpmSU8PdmTJDdJpyC5jp?usp=sharing

**Comment by sw005320** [comment]
Thanks a lot!

**Comment by smolendawid** [comment]
Thank you!
