### ISSUE TITLE
Toward fast decoding 

### ISSUE THREAD

**Issue by sw005320** [espnet/espnet#1384]
We're planning to work on the following items:

1. incorporate [batch decoding](https://github.com/espnet/espnet/blob/master/espnet/nets/pytorch_backend/rnn/decoders.py#L497) into our new [beam search interface](https://github.com/espnet/espnet/blob/master/espnet/nets/beam_search.py) (api_v2)
   - [x] batch beam search v2 for encoder-decoder, insertion penalty in transformer #1402
   - [ ] batch beam search v2 for CTC in transformer: wrap [CTCPrefixScoreTH](https://github.com/espnet/espnet/blob/6b4cb6aa6765b982cbf5b313c33f9334cca6048e/espnet/nets/ctc_prefix_score.py#L12) in [BatchScorerInterface](https://github.com/espnet/espnet/blob/6b4cb6aa6765b982cbf5b313c33f9334cca6048e/espnet/nets/scorer_interface.py#L83)
   - [ ] batch beam search v2 for RNN decoder: wrap [Decoder.recognize_beam_batch](https://github.com/espnet/espnet/blob/6b4cb6aa6765b982cbf5b313c33f9334cca6048e/espnet/nets/pytorch_backend/rnn/decoders.py#L632)
2. implement other scorers
    - [x] RNNLM, Transformer LM #1402
    - [x] N-gram LM #1946 #1992
    - [ ] Coverage
    - [ ] Multihead decoder
- The beauty of api_v2 is that we can combine all of them by adding a scorer class into the beam search algorithm with corresponding weights (see https://github.com/espnet/espnet/blob/e5bcce8d846efa65a963bbe49c7244ddc48f8143/espnet/nets/beam_search.py#L45-L48)
3. unify to use api_v2 for all other tasks including (probably we don't need additional implementation for some of them below).
    - [ ] asr_mix
    - [ ] mt
    - [ ] st
    - etc.? 
- Then, we should stop to have a beam search method for each decoder
4. RNNT is a different story as it is an input synchronous beam search. We may need to extend the beam search interface. Also, on-line processing would be another different story.

This change would perform the parallelization across both utterances and hypotheses and GPU computation becomes very fast (as we observed in batch decoding). Of course, we can expect significant speedups in CPU as well.
After item 1, we could distribute the implementation efforts to the others, and we may ask some of you.

**Comment by mowayao** [comment]
Any plan for hot-word decoding?

**Comment by sw005320** [comment]
What is hot-word decoding? Could you tell us the reference?

**Comment by mowayao** [comment]
> What is hot-word decoding? Could you tell us the reference?

Eh... I can't find any paper about this technique,  but the idea of hot-word decoding is quiet simple, that is, you can add some words in decoding procedure, which will bias the prediction words towards hot-words. Lots of ASR service provider company support this characteristics such as , https://www.huaweicloud.com/en-us/product/asrc.html

**Comment by sw005320** [comment]
I see. This is what the standard e2e cannot handle easily compared with HMM based one because of the lack of the acoustic, lexical, and language model modules. There are several studies to incorporate hot words in e2e systems but espnet currently does not support it.

**Comment by qmpzzpmq** [comment]
I have some experience with ngram implemented into decoding as I asking, if you need help.
#1228

**Comment by sw005320** [comment]
> I have some experience with ngram implemented into decoding as I asking, if you need help.
#1228

As you may know, this new decoder interface allows log-linear interpolation of multiple scorer instances  (including encoder-decoder, RNNLM, etc. This can be also used to combine multiple encoder-decoder and language models) in a unified way.
And, yes we're very interested in n-gram implementation.
It would be great if you consider some contributions.

**Comment by qmpzzpmq** [comment]
@sw005320 yes, I know that, I implement a simple ngram through ScorerInterface.
And I tested it implemented through _openfst_python _(@ShigekiKarita ) and _kenlm_ both.
It seems _kenlm_ is faster than _openfst_python_.

**Comment by sw005320** [comment]
Very cool. Could you make a PR?
I think this is great to have both kenlm and openfst_python options.

**Comment by ShigekiKarita** [comment]
can't wait to see it!

2020年2月21日(金) 11:42 Shinji Watanabe <notifications@github.com>:

**Comment by chen1399** [comment]
> > What is hot-word decoding? Could you tell us the reference?
> 
> Eh... I can't find any paper about this technique, but the idea of hot-word decoding is quiet simple, that is, you can add some words in decoding procedure, which will bias the prediction words towards hot-words. Lots of ASR service provider company support this characteristics such as , https://www.huaweicloud.com/en-us/product/asrc.html

You can do it in decode program by yourself.

**Comment by qmpzzpmq** [comment]
@ShigekiKarita @sw005320 
I already implement ngram it with kenlm in aishell recipe since it work badly in subword modeling.
In my test, ngram decoding indeed decrease the WER (test: 7.4% ->7.3% dev: 6.6->6.5%) with ngram weight 0.1. There is no any LM in my baseline.
but this implement decoding still slow than am model with lm model. Maybe we can talk about it?

**Comment by sw005320** [comment]
Sounds good!
(Sorry for the late reply...)
Could you send me an email (shinjiw@ieee.org)?

**Comment by ShigekiKarita** [comment]
I updated the items with check boxes and PR #.
