### ISSUE TITLE
Phoneme alignment

### ISSUE THREAD

**Issue by minhqp** [espnet/espnet#1386]
Hi there,

Does anyone know how to get phoneme alignment? I used Kaldi with ```yesno``` dataset, and get phoneme alignment in ```exp/mono_0a/ali.1.gz```. Espnet use same style with Kaldi, but after training, I cannot find any file which contain phoneme alignment.

**Comment by kan-bayashi** [comment]
Because ESPnet is based on end-to-end training, we do not use any phoneme alignment.

**Comment by minhqp** [comment]
Oh I see. Thank you!
