### ISSUE TITLE
Using trained Language Model for decoding process

### ISSUE THREAD

**Issue by kobiche** [espnet/espnet#1389]
Hi, 

I am currently trying to decode a sample dataset using the toolkit. 
Inside the recog_wav.sh file, on stage 2, a LM and its dictionary is trained based on the reference. Then on lines 131-139 different folders are given to the function data2json.sh along the new LM and dictionary in order to create the json files:
https://github.com/espnet/espnet/blob/448947bf5a93b03208bfda5e8acb5428b3ac93da/egs/tedlium2/asr1/run.sh#L131-L132

So far I know, this is important so that the reference json files contains codified text using the same dictionary that trained network will use later on the process. Otherwise the function score_sclite.sh will not be able to compare reasonably the rec_text and the ref_text.

My question is, why can't I use the already trained LM obtained from the Google Drive link (https://drive.google.com/open?id=1UqIY6WJMZ4sxNxSugUqp3mrGb3j6h7xe) to encode the ref text? In other words, instead of training a new LM and passing it to the function data2json.sh by the option --bpecode, use the trained LM. As it is, if I use it, the following error comes up:
`RuntimeError: Format error 1th line in data/dev/tmp-7oOnL/output/token.scp:  Expecting "<key> <value>":`

**Comment by kobiche** [comment]
Do you know where the problem lies?

**Comment by sw005320** [comment]
First, `run.sh` is a script to make all models (e2e and language models) from scratch. We did not intend it for the adaptation scenario. Second, it seems that you used an LM as an argument of `--bpecode`, right? LM and BPE model are different. You need to feed the BPE model. Currently, the uploaded language model does not include the BPE model (which is a known issue) and you need to make a BPE model again.

**Comment by kobiche** [comment]
Understood! Thanks! 

When do you think it is going to be possible to download the BPE model?
