### ISSUE TITLE
what does this do? FIXME: TOO DIRTY HACK

### ISSUE THREAD

**Issue by kaituoxu** [espnet/espnet#1392]
Hello, I want to know what does this part code doing. So that I can decide whether to remove or modify these code when I add Horovod to Espnet. Thx.
https://github.com/espnet/espnet/blob/master/espnet/asr/pytorch_backend/asr.py#L448-L450

**Comment by kan-bayashi** [comment]
This line is needed to use chainer’s trainer.
I think you can remove if you move on to the other trainer.

**Comment by kan-bayashi** [comment]
Maybe you will interested in our new design #1372.

**Comment by kaituoxu** [comment]
Got it. Thx.
