### ISSUE TITLE
ASR hybrid attention/ctc and put ctc weight 0

### ISSUE THREAD

**Issue by Yingzhu-Zhao** [espnet/espnet#1395]
One question regarding attention/ctc hybrid model. I want to include attention loss only, and change ctc-weight to 0.0 in decode_rnn.yaml, and mtlalpha to 0.0 in train_pytorch_transformer_lr5.0_ag8.v2.yaml. But the result is too much worse. Any idea why?

**Comment by kan-bayashi** [comment]
Please check #1318
