### ISSUE TITLE
Fisher Callhome Spanish ST recipe: lsm-type,lsm-weight missing

### ISSUE THREAD

**Issue by RSSharma246** [espnet/espnet#1396]
In espnet/bin/st_train.py, the parser was changed recently, and the conf files, and other files including e2e_st.py were not changed to reflect that. This seems to break the recipe in egs/fisher_callhome_spanish/st1/
Please check the recent commit made for that file: reverting that commit should fix the issues.

Thanks

**Comment by kan-bayashi** [comment]
@hirofumi0810 Could you check it?

**Comment by sw005320** [comment]
It may be better to have some integration tests for ST like https://github.com/espnet/espnet/blob/master/ci/test_integration.sh.

**Comment by hirofumi0810** [comment]
@RSSharma246 can you show me the error log?

**Comment by RSSharma246** [comment]
`Traceback (most recent call last):
  File "/x/espnet/egs/fisher_callhome_spanish/st1/../../../espnet/bin/st_train.py", line 311, in <module>
    main(sys.argv[1:])
  File "/x/espnet/egs/fisher_callhome_spanish/st1/../../../espnet/bin/st_train.py", line 305, in main
    train(args)
  File "/x/espnet/espnet/st/pytorch_backend/st.py", line 126, in train
    model = model_class(idim, odim, args)
  File "/x/espnet/espnet/nets/pytorch_backend/e2e_st.py", line 193, in __init__
    if args.lsm_type and os.path.isfile(args.train_json):
AttributeError: 'Namespace' object has no attribute 'lsm_type'`


Basically, the issue if that nets/pytorch_backend/e2e_st.py needs lsm_type, which is also in the conf files, but this was removed from the parser in st_train.py in the most recent commit. Adding 
`
parser.add_argument('--lsm-type', const='', default='', type=str, nargs='?', choices=['', 'unigram'],
                        help='Apply label smoothing with a specified distribution type')
`
to line 85 in st_train.py should fix it I think? @hirofumi0810 .

Also, the config file (https://github.com/espnet/espnet/blob/master/egs/fisher_callhome_spanish/st1/conf/tuning/train_rnn_char.yaml) has lsm-weight, which was removed from the argparser too. Maybe this needs to be removed from the config file?

**Comment by RSSharma246** [comment]
Looks like issue is resolved. Thanks
