### ISSUE TITLE
Error with install

### ISSUE THREAD

**Issue by wentaoxandry** [espnet/espnet#1399]
Hello,
I have tried with espnet install, during make I havn't got any error, but  run  make check_install, I got follow results:
. venv/bin/activate; python check_install.py
INFO: python version = 3.7.3 (default, Mar 27 2019, 22:11:17) 
[GCC 7.3.0]
INFO: library availableness check start.
INFO: # libraries to be checked = 9
INFO: --> espnet is installed.
INFO: --> kaldiio is installed.
INFO: --> matplotlib is installed.
INFO: --> torch is installed.
INFO: --> chainer is installed.
INFO: --> chainer_ctc is installed.
WARNING: --> warpctc_pytorch is not installed.
INFO: --> warprnnt_pytorch is installed.
INFO: --> cupy is installed.
INFO: library availableness check done.
INFO: 8 / 9 libraries are correctly installed.
INFO: please try to setup again and then re-run this script.
make: *** [Makefile:154: check_install] Error 1
I want to know how can I solve this problem?
Thank you

**Comment by sw005320** [comment]
We prepare most versions of pytorch warp CTC (see https://github.com/espnet/warp-ctc#for-pytorch-10-or-11). I guess you ran the Makefile with some different (unsupported) setup. Could you tell me more exact information? (What kind of environment, which option did you use for make etc.)?

**Comment by wentaoxandry** [comment]
Thank you for you reply.
I have changed a lot of envorioment config, now it is working:) thank you for your help
