### ISSUE TITLE
WARNING: --> espnet is not installed.

### ISSUE THREAD

**Issue by beidongjiedeguang** [espnet/espnet#1403]
When I installed everything and then executed `python check_install.py `  at `espnet/tools` , I got this: 
```bash
INFO: # libraries to be checked = 8
WARNING: --> espnet is not installed.
INFO: --> kaldiio is installed.
INFO: --> matplotlib is installed.
INFO: --> torch is installed.
INFO: --> chainer is installed.
INFO: --> chainer_ctc is installed.
INFO: --> warpctc_pytorch is installed.
INFO: --> cupy is installed.
INFO: library availableness check done.
INFO: 7 / 8 libraries are correctly installed.
INFO: please try to setup again and then re-run this script.
```
 What should I do ?

**Comment by sw005320** [comment]
Does it happen in the current master?

**Comment by beidongjiedeguang** [comment]
> Does it happen in the current master?

Thank you for your reply. It may not be, I run it in docker image "espnet/espnet:gpu-cuda10.0-cudnn7-u18". How can I fix it？

**Comment by sw005320** [comment]
oh, I see. Maybe the docker image is not updated.
@Fhrozen, could you fix it (if my understanding is correct)?

**Comment by Fhrozen** [comment]
@beidongjiedeguang I am wondering if you are trying with the docker images on the hub or a local built.?
The docker images on the hub are a little out-of-date (I will update them tomorrow).
Meanwhile, can you try first with:`./build.sh fully_local 10.0` inside the docker folder and check if the errors remains.

**Comment by Fhrozen** [comment]
@beidongjiedeguang #1409 just been merge with new updates for the docker container.
If you are using the one in the HUB please re-download it and test.

**Comment by yoonjune** [comment]
I have same issue with the latest version as you mentioned above.(espnet/espnet, tag "gpu-cuda10.0-cudnn7-u18"
I build docker image following command.

>      sudo ./run.sh --docker_gpu 0 --docker_egs chime4/asr1 --docker_folders /export/corpora4/CHiME4/CHiME3 --ngpu 

and got following error.
`stage 0: Data preparation
cat: /export/corpora4/CHiME4/CHiME3/data/WSJ0/wsj0/doc/indices/train/tr_s_wv1.ndx: No such file or directory
cat: /export/corpora4/CHiME4/CHiME3/data/WSJ0/wsj0/doc/indices/test/nvp/si_et_05.ndx: No such file or directory
find: '/export/corpora4/CHiME4/CHiME3/data/WSJ0/wsj0/si_dt_05': No such file or directory
find: '/export/corpora4/CHiME4/CHiME3/data/WSJ0': No such file or directory
run.sh done.
`

so I  run docker manually

> sudo docker run -it --runtime=nvidia 937b583f3b76 /bin/bash


and I got same issue.

> INFO: 7 / 8 libraries are correctly installed.
INFO: please try to setup again and then re-run this script.

**Comment by Fhrozen** [comment]
In case of use the containers from the Hub, you need first to delete the previously downloaded.
In case of use of building locally you need to modify the lines 

https://github.com/espnet/espnet/blob/3a4b65e95289fabbf6500d75336a60085e61c42e/docker/prebuilt/local/Dockerfile#L30-L32

to:

```
export CFLAGS="-I$CUDA_HOME/include $CFLAGS" && \
        sed -i '154s|install.py|install.py --no-cupy|' Makefile && \
        sed -i '21s|nvidia-smi|nvcc|' Makefile && \
        make KALDI=/kaldi CUDA_VERSION=${CUDA_VER}; \
```
I will try to update this in the master dockerfile

**Comment by sharockys** [comment]
> I have same issue with the latest version as you mentioned above.(espnet/espnet, tag "gpu-cuda10.0-cudnn7-u18"
> I build docker image following command.
> 
> > ```
> >  sudo ./run.sh --docker_gpu 0 --docker_egs chime4/asr1 --docker_folders /export/corpora4/CHiME4/CHiME3 --ngpu 
> > ```
> 
> and got following error.
> `stage 0: Data preparation cat: /export/corpora4/CHiME4/CHiME3/data/WSJ0/wsj0/doc/indices/train/tr_s_wv1.ndx: No such file or directory cat: /export/corpora4/CHiME4/CHiME3/data/WSJ0/wsj0/doc/indices/test/nvp/si_et_05.ndx: No such file or directory find: '/export/corpora4/CHiME4/CHiME3/data/WSJ0/wsj0/si_dt_05': No such file or directory find: '/export/corpora4/CHiME4/CHiME3/data/WSJ0': No such file or directory run.sh done. `
> 
> so I run docker manually
> 
> > sudo docker run -it --runtime=nvidia 937b583f3b76 /bin/bash
> 
> and I got same issue.
> 
> > INFO: 7 / 8 libraries are correctly installed.
> > INFO: please try to setup again and then re-run this script.

Hello, I have tried to resolve this problem by cloning the repo and install it with `pip install .` with python in /espnet/tools/venv. 
Somehow the installation worked but `from espnet import transfom` won't work, I copeid from the cloned repo `espnet/espnet` to `/espnet/tools/venv/bin/python3.7/site-packages/` and I made `check_install.py` worked.

**Comment by beidongjiedeguang** [comment]
> Somehow the installation worked but `from espnet import transfom` won't work, I copeid from the cloned repo `espnet/espnet` to `/espnet/tools/venv/bin/python3.7/site-packages/` and I made `check_install.py` worked and by copying the other folders to `/espnet` in docker from the cloned repo, I have sucessfully ran the recipe of common_voice.

Copy `/espnet/espnet`  to  ` /espnet/tools/venv/lib/python3.7/site-packages/ ` worked for me! @sharockys Thank you!
