### ISSUE TITLE
How to adjust the voice speed in fastspeech?

### ISSUE THREAD

**Issue by limitforever** [espnet/espnet#1404]
Hello,I have ran the  demo from"https://colab.research.google.com/github/espnet/notebook/blob/master/tts_realtime_demo.ipynb#scrollTo=PGLeZP1CCB2E"and yet got good results in synthsizing Chinese.
   And I want to have a futher study on FastSpeech.My question is how to adjust the voice speed in your code?Can you show me where I can find the parameter "alpha" which was noted in FastSpeech paper?

**Comment by kan-bayashi** [comment]
Hi @limitforever.
Sorry, the feature is not supported officially.
I will implement within a month.

**Comment by marzieh-razavi** [comment]
Hello, I was wondering if this feature (adjusting the voice speed) is currently supported.

**Comment by mapledxf** [comment]
Hi there. Has this function been implemented now?

**Comment by kan-bayashi** [comment]
Not yet. But this is easy. I will do it in this week.

**Comment by kan-bayashi** [comment]
@limitforever @marzieh-razavi  @mapledxf Sorry for late. I Implemented in #1894.
