### ISSUE TITLE
Multi encoder integration test is dead but not reported in CI

### ISSUE THREAD

**Issue by ShigekiKarita** [espnet/espnet#1405]
https://travis-ci.org/espnet/espnet/jobs/620043261#L14985

I'm afraid that this line does not work well.
https://github.com/espnet/espnet/blob/2b9e8476b357eee78c0d5896833eeaeb0d1d5efe/ci/test_integration.sh#L8

**Comment by kamo-naoyuki** [comment]
The following shell script returns 0, so the ci never stop excluding the last block.

```bash
( set -e; return 1; ) 
( set -e; return 0; ) 
```

Is there reason you use subshell? How about simply executing these commands in the main shell?

```bash
set -e
return 1; 
return 0; 
```

Or,

```bash
set -e
( set -e; return 1; )   # Stops here because the subshell also returns 1
( set -e; return 0; ) 
```

**Comment by ShigekiKarita** [comment]
Thanks! Just shellcheck asked me to use sub when I do cd. I will turn off
the warning here.

2019年12月14日(土) 8:26 Naoyuki Kamo <notifications@github.com>:
