### ISSUE TITLE
Mobile inference and training?

### ISSUE THREAD

**Issue by sbhamad** [espnet/espnet#141]
Hi ESPNet,

I wonder if i could deploy my Chainer trained ESPNet model on mobile devices for on-device inference?

On-device training would be amazing, but inference would do for now.

Thanks

**Comment by sw005320** [comment]
I think this is no problem.
Please let me know if you need some help.

Shinji

**Comment by saeedbinhamad** [comment]
I just need to know the best practice for deplpying a chaner model on mobile. 


Shall i use onnx or what

**Comment by Fhrozen** [comment]
Using ONNX will be the best practice. There is an example for pytorch (https://discuss.pytorch.org/t/onnx-deploying-a-trained-model-in-a-c-project/9593/2) that can be easily use for any deep learning framework.

**Comment by mdeisher** [comment]
I've been having difficulty exporting the model using torch.onnx.export due to not knowing how to set up the dummy input (second argument).  The examples on the web such as the one cited above are not much help.  Any suggestions?  Thanks!

**Comment by Fhrozen** [comment]
Just to know, there are large literature in the following links ( https://pytorch.org/tutorials/advanced/super_resolution_with_caffe2.html , https://pytorch.org/docs/stable/onnx.html ) 

```
# Input to the model
x = torch.randn(batch_size, 1, 224, 224, requires_grad=True)

# Export the model
torch_out = torch.onnx._export(torch_model,             # model being run
                               x,                       # model input (or a tuple for multiple inputs)
                               "super_resolution.onnx", # where to save the model (can be a file or file-like object)
                               export_params=True)      # store the trained parameter weights inside the model file
```

The current model of ESPnet is trained with variable utter lengths, so you will need to review some post about the enhance of shape for ONNX (https://github.com/onnx/onnx/issues/654).

Let us know if you are lacking some information. about this to try preparing a code for exporting the file to onnx.

**Comment by mdeisher** [comment]
I looked in asr_pytorch.py and examined the size of the first utterance loaded using kaldi_io_py.read_mat.  Then I wrote the attached script.  But somehow the type or dimensions of the dummy input are still wrong.  Any ideas?  Thanks!

[espnet_export_py.txt](https://github.com/espnet/espnet/files/2190282/espnet_export_py.txt)

**Comment by mdeisher** [comment]
We are still working on this but are not yet successful.  I think we are getting close.  EspNet conventions of storing parameters conflict with the ONNX exporter.  We are working on a patch.

**Comment by rzcwade** [comment]
Hi ESPnet, @sbhamad 

I have tried exporting ESPnet pytorch model to ONNX with different approaches and I found out the following issues:

The args of onnx function cannot be keyword arguments as defined in the source code of onnx export function. 

In the pytorch model case there’s dictionary inside the input, which caused exportation issue. You have to repacked the input data to model to avoid the keyword argument issue. I also

The model accepts the input format as a tuple – (a batch-sized list within which each element is a 2-D array that represents a utterance-length audio feature, a list of string numbers which represents output token id). ONNX export only takes Variable (tensor data format used as a placeholder), but in the ESPnet code there are tensor/numpy conversion involved within the model, which caused issues while the Variable type traverses through the model. I had to modify the code in the encoder layers which made the Variable traverse through the encoder, but then it’s stuck at ctc layer.

I changed my approach to separate the encoder and decoder from the model, sent in tensor shape placeholder to the encoder and successfully obtained visualization for encoder structure (pytorch graph visualization and onnx model export use similar techniques I believe). But ONNX model export still complains for some issue that’s rooted deep down in the Pytorch onnx source code implementation. I am still waiting for response from the Pytorch forum.

I would like to get feedback on this from everyone. 

Thanks

**Comment by sw005320** [comment]
Thanks for your reports. Our recent major modification (https://github.com/espnet/espnet/releases/tag/v.0.2.0) made the input as a Variable (e.g., https://github.com/espnet/espnet/blob/master/src/asr/asr_pytorch.py#L160-L163), but I may misunderstand your point.

**Comment by rzcwade** [comment]
Hi @sw005320 ,

Thank you for your response. The input not being Variable type was the main issue of exporting to ONNX in the earlier espnet version I used. I will upgrade to 0.20 and try to export again.

Thank you!

**Comment by sw005320** [comment]
Thanks!
If you have any progress, please report it.
We're interested in your work, and happy to help.
