### ISSUE TITLE
The utilization rate of gpu is strang when training transformer & fastspeech

### ISSUE THREAD

**Issue by JoeyHeisenberg** [espnet/espnet#1410]
when I trained TTS model on the  /csmsc/conf/tuning/fastspeech.v3&transformer.v1, the utilization rate of gpu would go to zero for a while(but the result is aceptable), but the rate of tacotron2.v3 was fine. Is there any explanation for that？
fastspeech on 3 gpu
![image](https://user-images.githubusercontent.com/33407667/70137854-ebe34880-16c9-11ea-8e44-0e5170a208ad.png)
transformer on 3 gpu
![image](https://user-images.githubusercontent.com/33407667/70138144-9491a800-16ca-11ea-8c34-c061f6cd4a56.png)
tacotron2 on 1 gpu
![image](https://user-images.githubusercontent.com/33407667/70138401-30bbaf00-16cb-11ea-9245-a0c27785958c.png)

**Comment by kan-bayashi** [comment]
Maybe IO is bottleneck.
Try num-iter-threads > 0.
https://github.com/espnet/espnet/blob/beaef4e8c5f09cc655a6f7011f257d3800d311f8/espnet/bin/tts_train.py#L93
For example, you can add num-iter-threads: 4 in yaml config.

**Comment by ShigekiKarita** [comment]
Maybe attention plot is also bottleneck because Transformer's plot is very large. You can try num-save-attention: 0 in the training yaml
https://github.com/espnet/espnet/blob/beaef4e8c5f09cc655a6f7011f257d3800d311f8/espnet/bin/tts_train.py#L121-L122

**Comment by JoeyHeisenberg** [comment]
@kan-bayashi @ShigekiKarita I have tested on the experiment what you suggested, and the result support your guess @ShigekiKarita ，thx both of you ：)

test on default
![image](https://user-images.githubusercontent.com/33407667/70199126-d6166780-174b-11ea-8b0f-cb28cdd522b5.png)

test on num-iter-porcessed = 4
![image](https://user-images.githubusercontent.com/33407667/70199157-f2b29f80-174b-11ea-9f5e-f44098fee19d.png)

test on num-save-attention = 0
![image](https://user-images.githubusercontent.com/33407667/70199182-02ca7f00-174c-11ea-897d-5b801aa8a17c.png)
