### ISSUE TITLE
Question:Integration of multiple optimizers for different layers

### ISSUE THREAD

**Issue by RSSharma246** [espnet/espnet#1414]
I am interested in using multiple optimizers to train different layers in my ASR model. I would appreciate any suggestions on how to integrate this with the chainer trainer/ knowing if there is some compatibility in any experiment

**Comment by sw005320** [comment]
We have some experience with it. You may need to touch the trainer part. 
First, you should make multiple optimizer instances (e.g., https://github.com/sw005320/espnet-1/blob/asrtts2/src/asrtts/asrtts_pytorch.py#L664-L667) and change the CustomUpdater to perform the optimization for each instance (e.g., https://github.com/sw005320/espnet-1/blob/asrtts2/src/asrtts/asrtts_pytorch.py#L401 and https://github.com/sw005320/espnet-1/blob/asrtts2/src/asrtts/asrtts_pytorch.py#L407).
The above example is based on a very old version, but it can be applied to the current version.

**Comment by RSSharma246** [comment]
Thanks.
