### ISSUE TITLE
Word timings, once again.

### ISSUE THREAD

**Issue by vcjob** [espnet/espnet#1417]
Hello everyone!

I know that question has already been asked multiple times, but anyway, DeepSpeech by Mozilla team has its feature, they use CTC as well, though. Therefore, are there any plans on implementing that feature? (I know it won't be perfect, but at least estimated). Or is there any helpful info on how where to start, where should one take CTC results (like when encoded is fed to beam search? Somewhere before that stage?)

Thank you for any info!

**Comment by kan-bayashi** [comment]
Section 4.4 in this notebook will help you.
https://colab.research.google.com/github/espnet/interspeech2019-tutorial/blob/master/notebooks/interspeech2019_asr/interspeech2019_asr.ipynb

**Comment by kan-bayashi** [comment]
And in the case of TTS, we calculate the duration of each character in the inputs using attention weight. 
https://github.com/kan-bayashi/espnet/blob/afb17e6f1a99a66b228f0026e84efb6ebc0e35d9/espnet/tts/pytorch_backend/tts.py#L570-L585
I think we can do similar things in ASR to get the word timing.

**Comment by sw005320** [comment]
> And in the case of TTS, we calculate the duration of each character in the inputs using attention weight.
> https://github.com/kan-bayashi/espnet/blob/afb17e6f1a99a66b228f0026e84efb6ebc0e35d9/espnet/tts/pytorch_backend/tts.py#L570-L585
> I think we can do similar things in ASR to get the word timing.

Very interesting.
What kinds of format do you prepare to output the alignment information?

**Comment by delip** [comment]
Had a related question: If I wanted to recover phoneme-level timing, instead of word-level timing information as above, would it be sufficient to just train espnet's tacotron model with phonemes enabled and follow the above suggestion?

**Comment by MerryOscar** [comment]
@kan-bayashi - do you know of an example of this being implemented for ASR?

**Comment by lumaku** [comment]
With a character-based model, you could do it with CTC segmentation:
```python
# load model
from espnet_model_zoo.downloader import ModelDownloader
d = ModelDownloader(cachedir="./modelcache")
wsjmodel = d.download_and_unpack("kamo-naoyuki/wsj")
# load audio
import soundfile
speech, rate = soundfile.read("./test_utils/ctc_align_test.wav")
# CTC segmentation
from espnet2.bin.asr_align import CTCSegmentation
aligner = CTCSegmentation( **wsjmodel , fs=rate , kaldi_style_text=False)
text = "THE SALE OF THE HOTELS IS PART OF HOLIDAY'S STRATEGY TO SELL OFF ASSETS AND CONCENTRATE ON PROPERTY MANAGEMENT"
text = text.split()
segments = aligner(speech, text)
print(segments)
# utt_0000 utt 0.26 0.67 -0.0037 THE
# utt_0001 utt 0.67 0.90 -1.6257 SALE
# utt_0002 utt 0.90 1.04 -3.5356 OF
# utt_0003 utt 1.04 1.17 -3.8524 THE
# utt_0004 utt 1.17 1.73 -0.7644 HOTELS
# utt_0005 utt 1.73 1.96 -3.0500 IS
# utt_0006 utt 1.96 2.17 -1.5643 PART
# utt_0007 utt 2.17 2.29 -3.3515 OF
# utt_0008 utt 2.29 2.71 -1.0947 HOLIDAY'S
# utt_0009 utt 2.71 3.19 -0.9577 STRATEGY
# utt_0010 utt 3.19 3.38 -3.1506 TO
# utt_0011 utt 3.38 3.61 -1.9263 SELL
# utt_0012 utt 3.61 3.79 -1.9919 OFF
# utt_0013 utt 3.79 4.20 -0.9954 ASSETS
# utt_0014 utt 4.20 4.40 -2.1309 AND
# utt_0015 utt 4.40 4.97 -0.8067 CONCENTRATE
# utt_0016 utt 4.97 5.10 -2.1937 ON
# utt_0017 utt 5.10 5.53 -0.9835 PROPERTY
# utt_0018 utt 5.53 6.10 -0.8282 MANAGEMENT
