### ISSUE TITLE
must-c st task loss dont converged

### ISSUE THREAD

**Issue by hyx100e** [espnet/espnet#1418]
I use the default config with egs/must-c/st1/conf/train.yaml. And the data preprocess keep consistent with run.sh (from stage 1 to 3). But when I run the network stage(Exactly the same as the original code except use ctc loss),  use 1 gpu(22G) training one day(about 80k steps) but the loss still keep about 100-300. I set 0.5 weight with ctc loss and mtl loss, and use warp-ctc. So can you tell me some detail with your train step, especially about loss cruve (with epoch or step or time)
thanks

**Comment by kan-bayashi** [comment]
In speech translation, the alignment between inputs and outputs is not causal but CTC forces to be causal. Consequently the use of CTC has bad effect on training of ST model, I think.

**Comment by hyx100e** [comment]
But it still never converged only use attention decoder. I noted that LabelSmoothing and KLdiv loss have been used, does it work well in your experimental?

**Comment by kan-bayashi** [comment]
Let me confirm your questions:
1. The model has never learned well if you use the default setting except for the use of `mtlalpha=0.5`.
2. If you use the default setting, the loss is not converged. Or did you make any change from the default settings? Please clarify the difference.

And it is better to add your training curve figure with the setting.

**Comment by hyx100e** [comment]
Hi,
I trained 17 epoch for 1 day on 4 P40. But both loss and acc dont have significantly improved, it seem too slow. The curve figure and config.txt has shown below.

![st_17epoch](https://user-images.githubusercontent.com/28775368/70586601-81b73000-1c02-11ea-9c72-f9d9387fcbdc.jpg)

[config.txt](https://github.com/espnet/espnet/files/3948158/config.txt)
