### ISSUE TITLE
Question:Using different versions of espnet, with the same configuration file, the results are different

### ISSUE THREAD

**Issue by zqs01** [espnet/espnet#1419]
Hello everyone, I have a question. Using different versions of espnet, with the same configuration file, I got different result. I use Transformer model for ASR without Language model, then  espnet(0.6.0) result is worse than espnet(0.5.3).
```
# network architecture
# encoder related
elayers: 12
eunits: 2048
# decoder related
dlayers: 6
dunits: 2048
# attention related
adim: 256
aheads: 4

# hybrid CTC/attention
mtlalpha: 0.0

# label smoothing
lsm-weight: 0.2

# minibatch related
batch-size: 32
maxlen-in: 512  # if input length  > maxlen-in, batchsize is automatically reduced
maxlen-out: 150 # if output length > maxlen-out, batchsize is automatically reduced

# optimization related
sortagrad: 0 # Feed samples from shortest to longest ; -1: enabled for all epochs, 0: disabled, other: enabled for 'other' epochs
opt: noam
accum-grad: 1
grad-clip: 5
patience: 0
epochs: 100
dropout-rate: 0.1

# transformer specific setting
backend: pytorch
model-module: "espnet.nets.pytorch_backend.e2e_asr_transformer:E2E"
transformer-input-layer: conv2d     # encoder architecture type
transformer-lr: 10.0
transformer-warmup-steps: 70000
transformer-attn-dropout-rate: 0.0
transformer-length-normalized-loss: true
transformer-init: pytorch

# Report CER & WER
report-cer: true
report-wer: true

```

**Comment by sw005320** [comment]
How much they are different?

**Comment by zqs01** [comment]
dataset: WSJ

espnet(0.5.3) 

eval92 CER:5.2, WER:13.6
dev93 CER:6.7, WER:16.5

espnet(0.6.0)

eval92 CER:5.5, WER:14.0
dev93 CER:7.5, WER:17.8

**Comment by zqs01** [comment]
dataset: WSJ

espnet(0.5.3)

eval92 CER:5.2, WER:13.6
dev93 CER:6.7, WER:16.5

espnet(0.6.0)

eval92 CER:5.5, WER:14.0
dev93 CER:7.5, WER:17.8

@sw005320 thank you for your reply

**Comment by sw005320** [comment]
Is this difference reproducible?
We've always observed small differences. 
If this degradation is consistent, we will try to find the reason.

**Comment by zqs01** [comment]
Ok, I will do a few more experiments to test, thank you!
