### ISSUE TITLE
Need modification to be compatible with pytorch v0.4

### ISSUE THREAD

**Issue by kan-bayashi** [espnet/espnet#143]
Hi all,

Pytorch is updated to version 0.4.
It requires some change to migrate from 0.3.1 to 0.4.
See detail from following url.
<http://pytorch.org/2018/04/22/0_4_0-migration-guide.html>

**Comment by sw005320** [comment]
This actually causes a problem when we install warp_ctc. @ShigekiKarita, can you fix it? 
Easy solution is 
```
pytorch: venv/bin/activate
        . venv/bin/activate && conda install pytorch==0.3.1 -c pytorch
```

**Comment by pozhijisi** [comment]
Is upgrading to 0.4.0 a desired change? It may lose the compatibility to earlier versions of pytorch. If this issue is no longer open, can you please close it? @kan-bayashi

**Comment by kan-bayashi** [comment]
@pozhijisi It's not desired change, but we have to move on pytorch v0.4 sooner or later due to the development of new functions.

**Comment by sw005320** [comment]
@arendu may comment about this. We had discussions about this today.

**Comment by arendu** [comment]
pytorch 4 has some significant changes compared to 3... maybe best to update after the workshop?
