### ISSUE TITLE
WarpCTC vs Pytorch CTC

### ISSUE THREAD

**Issue by RSSharma246** [espnet/espnet#1434]
Have users found a specific reason to use Warp-CTC instead of the Pytorch default CTC?
I would prefer to use Pytorch > 1.0 for faster training, but it seems like WarpCTC is not compatible with Pytorch 1.3?
Is there a way to make a clean break for not using Warp-CTC and is it planned to move over to Pytorch CTC completely in the future?

**Comment by sw005320** [comment]
> Have users found a specific reason to use Warp-CTC instead of the Pytorch default CTC?
> I would prefer to use Pytorch > 1.0 for faster training, but it seems like WarpCTC is not compatible with Pytorch 1.3?
> Is there a way to make a clean break for not using Warp-CTC and is it planned to move over to Pytorch CTC completely in the future?

We had some benchmarks that Warp-CTC is better than PyTorch 1.0X default CTC.
PyTorch 1.3+ default CTC does not seem to have some issues, and I agree that we should switch to it in the near future. 
Now, we're working on #1421 and if this is fixed, we may think of moving to default CTC.
