### ISSUE TITLE
Any semi-supervised recipe

### ISSUE THREAD

**Issue by takeofuture** [espnet/espnet#1440]
I am wondering if espnet has already the recipe for semi-supervised model
https://github.com/kaldi-asr/kaldi/blob/master/egs/fisher_english/s5/run.sh
https://github.com/ShigekiKarita/espnet-semi-supervised
I am trying to find how to prepare my own data.

**Comment by takeofuture** [comment]
I just read 
http://www.merl.com/publications/docs/TR2019-100.pdf
It seems that this experiment has been done on librispeech,
Is there any recipe of semi-supervised on librispeech?

Thank you!

**Comment by sw005320** [comment]
https://github.com/espnet/espnet/pull/818 corresponds to it.
Please check it.

**Comment by takeofuture** [comment]
Thank you!
I got reply from 
https://github.com/ShigekiKarita/espnet-semi-supervised as well.
Thank you!
