### ISSUE TITLE
Mask making in Transformer-based ASR and TTS are different

### ISSUE THREAD

**Issue by unilight** [espnet/espnet#1449]
Hi. I found that the making of masks in Transformer-ASR and Transformer-TTS is pretty different.

First, the source mask.
In Transformer-TTS, the [function](https://github.com/espnet/espnet/blob/master/espnet/nets/pytorch_backend/e2e_tts_transformer.py#L775-L802) below is used to make the source mask of shape `[batch_size, source_length, source_length]`:
```python
def _source_mask(self, ilens):
    x_masks = make_non_pad_mask(ilens).to(next(self.parameters()).device)
    return x_masks.unsqueeze(-2) & x_masks.unsqueeze(-1)
```
In Transformer-ASR, [one line of code](https://github.com/espnet/espnet/blob/master/espnet/nets/pytorch_backend/e2e_asr_transformer.py#L166) is used to make a mask of shape `[batchsize, 1, source_length]`:
```python
src_mask = (~make_pad_mask(ilens.tolist())).to(xs_pad.device).unsqueeze(-2)
```

Second, the source target mask
In Transformer-TTS, the [function](https://github.com/espnet/espnet/blob/master/espnet/nets/pytorch_backend/e2e_tts_transformer.py#L834-L864) below is used to make the source-target mask:
```python
def _source_to_target_mask(self, ilens, olens):
        x_masks = make_non_pad_mask(ilens).to(next(self.parameters()).device)
        y_masks = make_non_pad_mask(olens).to(next(self.parameters()).device)
        return x_masks.unsqueeze(-2) & y_masks.unsqueeze(-1)
```
In Transformer-ASR, [the mask from encoder output](https://github.com/espnet/espnet/blob/master/espnet/nets/pytorch_backend/e2e_asr_transformer.py#L167-L173) is directly used:
```python
hs_pad, hs_mask = self.encoder(xs_pad, src_mask)
...
pred_pad, pred_mask = self.decoder(ys_in_pad, ys_mask, hs_pad, hs_mask)
```
Why is the implementation different?

**Comment by kan-bayashi** [comment]
Thanks for your valuable report, @unilight.
I will check this difference make outputs different today.

**Comment by kan-bayashi** [comment]
Consequently, the calculated results are the same.
I made following test code. Please check it.
https://github.com/kan-bayashi/espnet/commit/0283738575f506a6d595b77102dacc15fb001e55
So I will unify the masking part.

**Comment by unilight** [comment]
Thank you very much!
