### ISSUE TITLE
Big difference between Default LM and Seq_RNN LM 

### ISSUE THREAD

**Issue by HuimengZhang** [espnet/espnet#1456]
I Trained the same dataset using Default LM and Seq_RNN LM with similar model size, and got very different results. With Default LM, I trained 40 epochs. And the best epoch is the last one, with ppl at 7. While using Seq_RNN LM, it early stop at epoch 5, with ppl at 37. I looked at two RNNLM models, it seems to have the same architecture, only the Default LM is trained token by token (using LSTMCell/GRUCell), and Seq_RNN is trained by sentences (Using LSTM/GRU). Am I getting this right? or did I miss something? How come there is such a big difference using these two LM models?

### lm_default.yaml:
layer: 4
unit: 1024
opt: sgd        # or adam
batchsize: 256   # batch size in LM training
epoch: 40      # if the data size is large, we can reduce this
patience: 3
maxlen: 100     # if sentence length > lm_maxlen, lm_batchsize is automatically reduced

### lm_seq_rnn.yaml:
layer: 4         # 2 for character LMs
unit: 1024       # 650 for character LMs
opt: sgd          # adam for character LMs
sortagrad: 0 # Feed samples from shortest to longest ; -1: enabled for all epochs, 0: disabled, 
batchsize: 256    # 1024 for character LMs
epoch: 40        # number of epochs
patience: 3
maxlen: 100        # 150 for character LMs
model-module: seq_rnn

**Comment by HuimengZhang** [comment]
I think I know what's wrong:

torch.nn.LSTM takes input's shape as [seq_len, batch, input_size], while what you feed into LSTM is a tensor with the shape of  [batch, seq_len, input_size]. The input tensor should be permuted before feeding into LSTM.

**Comment by gs5264** [comment]
Oh～This is really a problem. Has anyone tried this model?  ！

**Comment by sw005320** [comment]
I see.
This seems to be a bug...
@ShigekiKarita, could you check it (sorry to ask things when you're sick...)

**Comment by ShigekiKarita** [comment]
Yeah, it should be bug and initialized with batch_first=True. BTW I found this cudnn based impl is not faster than default, maybe I will remove this later instead of fixing it.

**Comment by sw005320** [comment]
We may not need to keep both RNNLMs and I agree with removing it.
@HuimengZhang, is that OK?

**Comment by HuimengZhang** [comment]
@sw005320 it's fine by me to remove the Seq_RNN.
