### ISSUE TITLE
How can I use the Chinese asr pretrained model？

### ISSUE THREAD

**Issue by Yogaht** [espnet/espnet#1457]

**Comment by sw005320** [comment]
You can use the following resources:

- Script: https://github.com/espnet/espnet/blob/master/utils/recog_wav.sh
- Pretrained models: 
  - HKUST https://drive.google.com/open?id=1x96BTGXpphdZU9_Ahb4hOqttQ5x-iuw1
  - AISHELL https://drive.google.com/open?id=1BIQBpLRRy3XSMT5IRxnLcgLMirGzu8dg
