### ISSUE TITLE
Combining multiple datasets to train a better pretrained model?

### ISSUE THREAD

**Issue by AndroYD84** [espnet/espnet#1459]
I'm really impressed with ESPnet results, it's the most accurate speech to text solution I've tried after Google Cloud, I got the best overall results using the Librispeech pretrained model, however, occasionally Common Voice (my second favourite) could detect some words that Librispeech couldn't, so, what do you think about combining more datasets together (ie. Librispeech + Common Voice) and train on them all? Couldn't that potentially deliver a pretrained model that surpasses all others? It would be great to have something comparable to Google Cloud's result, in fact, this is the very first time I've seen an open source solution that is almost capable of that. I was tempted to try it myself but I'd like to know exactly how you've trained your own as I've read often in the issues that others have tried to reproduce your results but they weren't just as accurate as yours. Thanks for the amazing repo.

**Comment by sw005320** [comment]
Thanks for your encouraging words!
Indeed, ESPnet can easily combine the multiple training data (but the use of pre-training model is not officially supported) by simply using `utils/combine_data.sh`.
You can find some examples in https://github.com/espnet/espnet/blob/master/egs/li10/asr1/run.sh and https://github.com/espnet/espnet/blob/master/egs/fisher_swbd/asr1/run.sh

@ftshijt, can you also think of making a PR of your super multilingual recipe?
This would also be a good example.

**Comment by s-tomic** [comment]
Did you manage to combine Common voice with Libri @AndroYD84 ?
I was trying to do so also, just common voice alone was failing on me in stage 1 due to Kaldi error.

**Comment by sw005320** [comment]
We did not encounter the problem of simply combining librispeech and common voice data (see https://github.com/espnet/espnet/blob/master/egs/li42/asr1/run.sh#L208-L217)

**Comment by nayankote** [comment]
@djo-koconi What exactly was the error and how did you fix it? I too am training on common voice and it is stuck at stage 1. It seems to run forever after executing steps/make_fbank_pitch.sh. 
Thanks in advance.
