### ISSUE TITLE
MemoryError for train_json = json.load(f)['utts']

### ISSUE THREAD

**Issue by xforceco** [espnet/espnet#1460]
> File ".../asr_pytorch.py", line X, in train
    train_json = json.load(f)['utts']
  File "...lib/python3.6/json/__init__.py", line 299, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "...lib/python3.6/json/__init__.py", line 349, in loads
    s = s.decode(detect_encoding(s), 'surrogatepass')
MemoryError

I have a data.json file that is >10GB to load, I guess that is the reason.
Wonder if this toolkit is intended to support loading that.

Note that I am using a pretty old version so it can happen that the latest version of espnet may have fixed the issue already, though I cannot find any related to `json.load`.
Do correct me if I miss anything related to that.

**Comment by sw005320** [comment]
This is a known issue, and we're trying to solve it with espnet2 (https://github.com/espnet/espnet/tree/v.0.7.0).
In espnet2, we decided not to use the json format but use the traditional Kaldi style scp format for the scalability purpose.
You can find some examples at https://github.com/espnet/espnet/tree/v.0.7.0/egs2.
We actually want someone to test it with large scale data, and I really appreciate if you test your experiments with this.

**Comment by AdolfVonKleist** [comment]
Probably a bit late to say, but we are currently using this with several thousands of hours of data [and getting very good results].  The JSON format can still be used without issue as long as you employ a serialization strategy more like what is used in logging libraries, e.g. `https://github.com/fluent/fluentd` or similar.  Every 'event', or in this case sample, is written unindented to a single line, with no encapsulating array.  Then it can be read in the same way, line by line, while still enjoying the benefits of a more flexible, standardized format.

**Comment by sw005320** [comment]
Thanks @AdolfVonKleist!
This is very interesting.
Actually, one of the motivations of espnets also comes from this issue (with the other problems).

**Comment by sw005320** [comment]
> Probably a bit late to say, but we are currently using this with several thousands of hours of data [and getting very good results]. The JSON format can still be used without issue as long as you employ a serialization strategy more like what is used in logging libraries, e.g. https://github.com/fluent/fluentd or similar. Every 'event', or in this case sample, is written unindented to a single line, with no encapsulating array. Then it can be read in the same way, line by line, while still enjoying the benefits of a more flexible, standardized format.

@AdolfVonKleist, can you explain a bit more details about how you make it?
We're very interested in it.
(you may make a new issue.)

**Comment by jfrfonseca** [comment]
I've had the exact same problem in an entirely unrelated application, and found this thread while googling the error.
The bottom my the stack trace looks like this:

```
MY CODE:
    if self._json is None: self._json = json.loads(self.raw_page)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^

STACK TRACE OF THE ERROR (truncated so only opensource code is shown)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\json\__init__.py", line 341, in loads
    s = s.decode(detect_encoding(s), 'surrogatepass')
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
```

At this moment the app is trying to memoize the json-parsed contents of a HTTPS API response, and the JSON data is relatively big (more than 100Mb in a single JSON object).
Since its the exact same problem faced, maybe the exact same solution may apply.

Instead of using the built-in, default "vanilla JSON" for parsing the data, I have switched to [ORJSON](https://github.com/ijl/orjson).
It is nearly similar and solves the problem. It seems "default JSON" has a bug when parsing large JSON data.
