### ISSUE TITLE
Error on install :(   - I spent a while on this (ubuntu)

### ISSUE THREAD

**Issue by craftfortress** [espnet/espnet#1461]
```
. venv/bin/activate; cd chainer_ctc && pip install .
/bin/sh: 59: venv/bin/activate: [[: not found
Processing /home/chris/source/espnet/tools/chainer_ctc
Building wheels for collected packages: chainer-ctc
  Building wheel for chainer-ctc (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/chris/source/espnet/tools/venv/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-wcj9qwix/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-wcj9qwix/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-s8f3t3me --python-tag cp36
       cwd: /tmp/pip-req-build-wcj9qwix/
  Complete output (79 lines):
  /home/chris/source/espnet/tools/venv/lib/python3.6/distutils/extension.py:131: UserWarning: Unknown Extension options: 'include'
```

**Comment by sw005320** [comment]
Can you give us more information (ubuntu version, cuda version, actual make command)?

**Comment by Fhrozen** [comment]
This problem is coming from conda, I also observed in the installations of the docker containers and also observed outside espnet. The situation is that (eg.):
```
. venv/bin/activate && conda install -y numpy
. venv/bin/activate && conda install -y matplolib
```
after a first call of the activate (numpy), the second time (and subsequent, I cannot remember) you call activate will generate the `not found` error. However, it was observed that the error does not break the installation, neither fails it <-(I will try to confirm this later, and maybe how to solve it). 
So I suppose that the problem to install chainer_ctc should be from a different error. 
Try to run `make chainer_ctc.done` and copy the whole output here please.

**Comment by craftfortress** [comment]
Hi, thank you very much for your replies. 

I am running Ubuntu on Windows. 

I was able to get around this error by manually installing the libraries one by one. 

However I now have one last library to install - Cupy. 

1 - Do I need to install Cuda to get Cupy working?

2 - And finally a question Ive been dreading to ask - if I need Cuda ( I got the impression from the readme that was a choice) - does that mean I 100% need an nVidia chipset?  

I am running this on a Lenovo X1 Carbon and wondering whether I need to purchase another laptop to get this running. 

Thank you for your time.

PS - I am not trying to train any models - I am just trying to run some existing example models on example text I have entered.

**Comment by Fhrozen** [comment]
| Do I need to install Cuda to get Cupy working?
Yes, 
| And finally a question Ive been dreading to ask - if I need Cuda ( I got the impression from the readme that was a choice) - does that mean I 100% need an nVidia chipset?
Yes

However, if you are running the examples, you do not need to install cupy. The framework works fine without cupy.

**Comment by craftfortress** [comment]
Thank you for your quick response and answering my question I will close this issue.  Keep up the great work.

**Comment by sw005320** [comment]
@craftfortress, I'm very curious whether espnet can be run with Ubuntu on Windows. Please post your progress if possible.

**Comment by craftfortress** [comment]
> @craftfortress, I'm very curious whether espnet can be run with Ubuntu on Windows. Please post your progress if possible.

I looked into this and found out the answer. 

You CANNOT use the ubuntu on windows system as it does not allow low level access to the graphics card. 

You also cannot use VirtualBox as this does not allow it either. 

The only solution I found was to create a bootable instance of Ubuntu on my geforce machine, and turn off signed third party modules in my BIOS.  Now I finally have access to my geforce card. 

Finally, please tell people or update the readme to tell them to install CUDA with the apt-get command , otherwise you will run into hundreds of issues including with kaldi. 

Thank you I hope this helps.
