### ISSUE TITLE
Train TTS in Other Language

### ISSUE THREAD

**Issue by EsmaeilFarhang** [espnet/espnet#1464]
Hi,
is there any document to train (espnet tts transformer tts and fast speech)my own dataset in my own language?

**Comment by Fhrozen** [comment]
I think that you can take any recipe as [example](https://github.com/espnet/espnet/tree/master/egs/csmsc/tts1)
Then replace the stage of data downloading and data preparation to fit your own dataset
https://github.com/espnet/espnet/blob/6309f709a9583b06563404b39ff2a4b77b021bec/egs/csmsc/tts1/run.sh#L57-L72
And then, just train and test.

**Comment by kan-bayashi** [comment]
Hi @EsmaeilFarhang.

As @Fhrozen said, what we need to prepare is the data preparation script.
Maybe our tutorial material helps you to understand recipe flow.
https://colab.research.google.com/github/espnet/interspeech2019-tutorial/blob/master/notebooks/interspeech2019_tts/interspeech2019_tts.ipynb

And I recommend using `egs/ljspeech/tts1` as a base recipe.
https://github.com/espnet/espnet/blob/master/egs/ljspeech/tts1/run.sh
(Recently, it supports knowledge distillation based FastSpeech.)

And note that in our experiment, Tacotron2-based knowledge distillation FastSpeech is better than Transformer-based KD FastSpeech.

**Comment by EsmaeilFarhang** [comment]
@Fhrozen, @kan-bayashi thank you for your attention.
@kan-bayashi you mean first, running tacotron2, then use pre-train tacotron2 as a teacher mode for FastSpeech?

**Comment by kan-bayashi** [comment]
@EsmaeilFarhang Right. I made a brief README about fastspeech training.
https://github.com/espnet/espnet/blob/master/egs/ljspeech/README.md#tts1-recipe
Please check it.

**Comment by EsmaeilFarhang** [comment]
> @EsmaeilFarhang Right. I made a brief README about fastspeech training.
> https://github.com/espnet/espnet/blob/master/egs/ljspeech/README.md#tts1-recipe
> Please check it.

Thanks a lot.

**Comment by kan-bayashi** [comment]
I will close this issue. If you have more questions, please re-open this issue.

**Comment by kyash14333** [comment]
hello, im trying to replace the dataset for fine tuning just adding some technical words in the tts model in your jvs recipe is ok to just change the jvs  recipe dataset into my data?
