### ISSUE TITLE
CTC+Att. vs pure CTC decoding

### ISSUE THREAD

**Issue by TParcollet** [espnet/espnet#1471]
Hi there !

I am observing some strong differences in term of PER (on TIMIT) when using CTC+Att. vs pure CTC. This sounds weird to me, since the CTC vocabulary is the list of phonemes in both cases thus involving that the observed Loss should be quite related to the final PER. Nonetheless, I obtain a test PER of 18.4 with CTC+Att. (that is quite competitive for an E2E model on TIMIT) vs 43% with pure CTC 👎 . However the pure CTC Loss is actually equivalent to the CTC Loss on a CTC+Att. training. Are the decoding strategy radically different in both cases ?

Thanks and Merry Christmas !!

**Comment by sw005320** [comment]
One clarification. Is it based on transformer (self-attention) or RNN?

**Comment by TParcollet** [comment]
Oh sorry, self-attention (it's 1D CNN-BLSTMP).

**Comment by sw005320** [comment]
Thanks.
Can you share the training and decoding config files of pure CTC?

**Comment by TParcollet** [comment]
Please note that the blstmz is just a term that I use to change the vgg encoder to a 1D CNN.
Could it be because of the ctc-weight = 0.5? 

**Training:**

etype: vggblstmz     # encoder architecture type
elayers: 5
eunits: 512
eprojs: 512
dlayers: 1
dunits: 512

atype: location
adim: 512
aconv-chans: 10
aconv-filts: 100

mtlalpha: 1.0

batch-size: 8
maxlen-in: 800  # if input length  > maxlen_in, batchsize is automatically reduced
maxlen-out: 150 # if output length > maxlen_out, batchsize is automatically reduced

sortagrad: 0
opt: adadelta
epochs: 15
patience: 0

sampling-probability: 0.0

**Decoding:**
beam-size: 20
penalty: 0.0
maxlenratio: 0.0
minlenratio: 0.0
ctc-weight: 0.5

**Comment by sw005320** [comment]
Yes. please first change `ctc-weight = 1.0`.
We may also first check to see whether it's working without beam search by setting `beam-size: 1` and then setting `beam-size: 20`

**Comment by TParcollet** [comment]
I'll try that thanks.

**Comment by TParcollet** [comment]
Ok so it went down to 25%, which is still a lot but way better.
