### ISSUE TITLE
Fail to decode when using word-rnnlm if '<space>' is not in the corpus

### ISSUE THREAD

**Issue by HuimengZhang** [espnet/espnet#1473]
Hi, there:

I trained a character based E2E model and a sentencepiece based LM model using my own dataset. While decoding, the LookAheadWordLM need a space token https://github.com/espnet/espnet/blob/master/espnet/lm/pytorch_backend/extlm.py#L116. But i don't have it in my corpus. Can I simply change it like this:

```
         if '<space>' in subword_dict:
             self.space = subword_dict['<space>']
         else:
             self.space = subword_dict['<blank>']
```

**Comment by sw005320** [comment]
LookAheadWordLM assumes space-boundary based word models, and I don't recommend it in the above setup.
If you want to make it work in your setup, you may need some hacking, e.g., inserting the space between sentencepiece subwords in the original transcriptions/text and train char-based E2E model and sentencepiece language model with them.
