### ISSUE TITLE
How to do ASR demo

### ISSUE THREAD

**Issue by dtchantao** [espnet/espnet#1474]
Hi there, I have trained an RNNT model. How shall I do ASR demo using my trained mode?

**Comment by sw005320** [comment]
Cool.
We did not prepare an ASR demo for RNNT, but this page would be a good reference for you.
https://github.com/espnet/interspeech2019-tutorial

**Comment by Selma-KA** [comment]
Hi, I find it hard to know which beamSearch class to use and with which parameters for RNN-T. I will be grateful if someone can help me. Thanks in advance!
