### ISSUE TITLE
transformer bug

### ISSUE THREAD

**Issue by kaituoxu** [espnet/espnet#1475]
https://github.com/espnet/espnet/blob/master/espnet/nets/pytorch_backend/e2e_asr_transformer.py#L172 should be `ys_mask = target_mask(ys_in_pad, self.eos)` ?

**Comment by kan-bayashi** [comment]
Here we want to make a mask for padded part so self.ignore_id (padding id) is correct.

**Comment by kan-bayashi** [comment]
Oh, I checked the padding part and ys_in_pad is padded with eos. I will check more detail.

**Comment by kan-bayashi** [comment]
`ys_in_pad` is padded with `self.eos` in `add_sos_eos`.
https://github.com/espnet/espnet/blob/ddeb5daac9ffae1ee655913b591b15b57d1a0158/espnet/nets/pytorch_backend/transformer/add_sos_eos.py#L12-L30

In making the target mask, `ys_in_pad` and `self.ignore_id` are used. 
https://github.com/espnet/espnet/blob/ddeb5daac9ffae1ee655913b591b15b57d1a0158/espnet/nets/pytorch_backend/e2e_asr_transformer.py#L172

So `ys_mask` in `target_mask()` will be all of 1.
https://github.com/espnet/espnet/blob/ddeb5daac9ffae1ee655913b591b15b57d1a0158/espnet/nets/pytorch_backend/transformer/mask.py#L32-L42
