### ISSUE TITLE
Fbank data preparation for TTS. What did I miss?

### ISSUE THREAD

**Issue by hieuthi** [espnet/espnet#1480]
I try to understand the structure of TTS recipe do I play around with ljspeech recipe.
To understand the acoustic feature, I used "convert_fbank.sh" to synthesize waveform with the extracted feature from training data. 
As I assume the feature in fbank/ folder is "raw", I don't reverse the cmvn but the generated speech sound a little off.
So what did I miss? Is there some form of filtering applied to the data stored in fbank/ folder?

[LJ001-0001.wav.zip](https://github.com/espnet/espnet/files/4004545/LJ001-0001.wav.zip)

**Comment by kan-bayashi** [comment]
Hi @hieuthi.
The sound seems strange.
Did you use exactly the same parameters for `make_fbank.sh` and `convert_fbank.sh`?

**Comment by hieuthi** [comment]
Found the problem.
The make_fbank.sh is run a long time ago with older version of the recipe with fmax and fmin is not set. while convert_fbank.sh is run with the newer version with famx=7600 and fmin=80
Thank you.
