### ISSUE TITLE
Running CMVN with python

### ISSUE THREAD

**Issue by Daniel-asr** [espnet/espnet#1484]
I am trying to run CMVN with python by adding the **.py** extensions to the _compute-cmvn-stats_ command on the run.sh file and to the _apply-cmvn_ command on the dump.sh file.

However, when I run apply-cmvn.py, it doesn't write to the feats.scp file (and feats.N.ark/scp) inside the dump directory. And then, in stage 2 I get the error:

```
utils/split_scp.pl: error: empty input scp file dump/train_clean_100/deltafalse/feats.scp
utils/split_scp.pl: You are splitting into too many pieces! [reduce $nj]
```

Does anyone know how to run CMVN with the python scripts?

Thanks in advance

**Comment by sw005320** [comment]
> I am trying to run CMVN with python by adding the **.py** extensions to the _compute-cmvn-stats_ command on the run.sh file and to the _apply-cmvn_ command on the dump.sh file.
> 
> However, when I run apply-cmvn.py, it doesn't write to the feats.scp file (and feats.N.ark/scp) inside the dump directory. And then, in stage 2 I get the error:
> 
> ```
> utils/split_scp.pl: error: empty input scp file dump/train_clean_100/deltafalse/feats.scp
> utils/split_scp.pl: You are splitting into too many pieces! [reduce $nj]
> ```
> 
> Does anyone know how to run CMVN with the python scripts?
> 
> Thanks in advance

Can you follow the instruction and reduce the number of jobs (`$nj`)?

**Comment by Daniel-asr** [comment]
I managed to solve the problem:

It was the parsing of the ark files from _apply-cmvn.py_ to  _copy-feats.py_ through sys.stdout.buffer. For some reason, copy-feats could not read the apply-cmvn's output from sys.stdout.buffer.

I walk over the problem by writing into files, so there might be a bug somewhere. See the solution below.

BEFORE:
```
${cmd} JOB=1:${nj} ${logdir}/dump_feature.JOB.log \
    apply-cmvn.py --norm-vars=true --norm-means=true ${cvmnark} scp:${logdir}/feats.JOB.scp ark:- \| \
    copy-feats.py --verbose ${verbose} --out-filetype ${filetype} \
        --compress=${compress} --compression-method=2 ${write_num_frames_opt} \
        ark:- ark,scp:${dumpdir}/feats.JOB.ark,${dumpdir}/feats.JOB.scp \
    || exit 1
```

AFTER:
```
${cmd} JOB=1:${nj} ${logdir}/dump_feature.JOB.log \
    apply-cmvn.py --norm-vars=true --norm-means=true ${cvmnark} scp:${logdir}/feats.JOB.scp ark:${logdir}/feats.JOB.ark
    
${cmd} JOB=1:${nj} ${logdir}/dump_feature.JOB.log \
    copy-feats.py --verbose ${verbose} --out-filetype ${filetype} \
        --compress=${compress} --compression-method=2 ${write_num_frames_opt} \
        ark:${logdir}/feats.JOB.ark ark,scp:${dumpdir}/feats.JOB.ark,${dumpdir}/feats.JOB.scp 
```

Thank you

**Comment by sw005320** [comment]
This solution is a little bit risky because the input and output file names and logfile names are the same. Also, this solution is not great for the disk access perspective.

> It was the parsing of the ark files from _apply-cmvn.py_ to _copy-feats.py_ through sys.stdout.buffer. For some reason, copy-feats could not read the apply-cmvn's output from sys.stdout.buffer.

@kamo-naoyuki, do you have some comments?

**Comment by kamo-naoyuki** [comment]
It works for me. What kaldiio version did you use? Recently some bugs of kaldiio are fixed.

I found that run.pl can't stops with command failing in the flow of apply-cmvn and copy-feats 

```bash
run.pl a.log false \| true
```
