### ISSUE TITLE
How should I reconfigure the `batch-bins` and `accum-grad` parameters in config?

### ISSUE THREAD

**Issue by houwenxin** [espnet/espnet#1489]
When running recipe of LibriSpeech, I found a reminding in egs/librispeech/asr1/run.sh:

> train_config=conf/train.yaml # current default recipe requires 4 gpus.
                             # if you do not have 4 gpus, please reconfigure the `batch-bins` and `accum-grad` parameters in config.

When I refer to the conf/train.yaml, I found the following settings.
> accum-grad: 4
batch-bins: 15000000

If I only have one gpu, how should I reconfigure these two parameters?

**Comment by houwenxin** [comment]
And I wonder what the default `batchsize` is during network training? Is it decided by `batch-bins`? Or they need to be set individually?

**Comment by houwenxin** [comment]
Thank you in advance.

**Comment by Fhrozen** [comment]
> If I only have one gpu, how should I reconfigure these two parameters?

For accum-grad: you can multiply it by 4 (gpus). Set --ngpu to 1. batch-bins should be also increased to 4 (because in multi gpu the batchsize increased by 4), but you will need to reduce the size depending on the memory capacity. 

>BTW, I am also wondering what the default batchsize is during network training? Is it decided by batch-bins? Or they need to be set individually?

if you set batch-bins, then you do not need to set batchsize, and vice versa.

**Comment by houwenxin** [comment]
> > If I only have one gpu, how should I reconfigure these two parameters?
> 
> For accum-grad: you can multiply it by 4 (gpus). Set --ngpu to 1. batch-bins should be also increased to 4 (because in multi gpu the batchsize increased by 4), but you will need to reduce the size depending on the memory capacity.
> 
> > BTW, I am also wondering what the default batchsize is during network training? Is it decided by batch-bins? Or they need to be set individually?
> 
> if you set batch-bins, then you do not need to set batchsize, and vice versa.

Thank you for your quick reply. But for `batch-bins`, I remembered that in PyTorch's DataParallel, the batch size for multiple gpus should be original batch size * npgu. So maybe the batch-bins should be decreased by a factor of 4 here?

**Comment by sw005320** [comment]
Another possibility is to use the configuration of https://github.com/espnet/espnet/blob/master/egs/librispeech/asr1/conf/tuning/train_pytorch_transformer_lr5.0_ag8.v2.yaml

This would provide reasonable performance with a single GPU (but slightly worse than 4GPU's one).

**Comment by houwenxin** [comment]
> Another possibility is to use the configuration of https://github.com/espnet/espnet/blob/master/egs/librispeech/asr1/conf/tuning/train_pytorch_transformer_lr5.0_ag8.v2.yaml
> 
> This would provide reasonable performance with a single GPU (but slightly worse than 4GPU's one).

Thank you very much.
