### ISSUE TITLE
e2e asr transducer (fbank with auxiliary information)

### ISSUE THREAD

**Issue by ahmedalbahnasawy** [espnet/espnet#1495]
I have a trained e2e ASR transducer model that trained on fbank features (Librispeech). I'm trying to concatenate auxiliary vector to the fbank input during testing. The idea is to feed the model contextual vector with the fbank vector. I reshaped the contextual vector C to concatenate it with the fbank, the input changed from [1, sequence, 83] to [1, sequence, 83+C]. The input to the first BLSTM from CNN is [1 ,sequence,19750] and the BLSTM layer always accepts [1 ,sequence,2688].
 I know whats the issue is but do you think the solution is to retrain the model again but with input dimension [83+C] or I can reshape the second dimention of the output to be 2688

**Comment by sw005320** [comment]
I think you should at least retrain the model.
I'm not sure exactly what is the auxiliary vector, but if it is a constant vector across frames in an utterance (like i-vector), applying a 2-D CNN to such vector seems to be less efficient.

**Comment by ahmedalbahnasawy** [comment]
> I think you should at least retrain the model.
> I'm not sure exactly what is the auxiliary vector, but if it is a constant vector across frames in an utterance (like i-vector), applying a 2-D CNN to such vector seems to be less efficient.

The Auxiliary vector is what FAIR suggest in this paper https://arxiv.org/abs/1904.05862. C vector is  combination of multiple time-steps to obtain contextualized representations.

**Comment by ahmedalbahnasawy** [comment]
@kan-bayashi @sw005320 could you help me to figure it out ?

**Comment by sw005320** [comment]
I see.
If this auxiliary vector is changed across the frame, you may apply normal 2-D CNN.
