### ISSUE TITLE
warp_ctc in chainer as default?

### ISSUE THREAD

**Issue by sw005320** [espnet/espnet#150]
warp_ctc has some speed benefits, but most of recipes use chainer_ctc as default. So, probably, we should switch to use warp_ctc in chainer as default.
Also, pytorch uses warp_ctc, and we can make chainer and pytorch more consistent.
@jheymann85, @ShigekiKarita, @kan-bayashi, do you agree?

**Comment by jheymann85** [comment]
Yes, sounds reasonable

**Comment by sw005320** [comment]
My hesitation is that the warp_ctc installation is unstable. Last few days, I was actually fighting with warp_ctc installation in our new environments. I think we need some improvements on the installation.

**Comment by sw005320** [comment]
#165 changes warpctc as default.
