### ISSUE TITLE
warp-transducer.done Error while installing

### ISSUE THREAD

**Issue by samin9796** [espnet/espnet#1507]
This is what I get after I run  **make check_install** command:

> [ 92%] Building CXX object CMakeFiles/test_time.dir/tests/random.cpp.o
[100%] Linking CXX executable test_time
make[3]: Leaving directory '/data/ahnaf/espnet_asr/espnet/tools/warp-transducer/build'
[100%] Built target test_time
make[2]: Leaving directory '/data/ahnaf/espnet_asr/espnet/tools/warp-transducer/build'
make[1]: Leaving directory '/data/ahnaf/espnet_asr/espnet/tools/warp-transducer/build'
. venv/bin/activate; cd warp-transducer/pytorch_binding && python setup.py install
running install
running bdist_egg
running egg_info
creating warprnnt_pytorch.egg-info
writing warprnnt_pytorch.egg-info/PKG-INFO
writing dependency_links to warprnnt_pytorch.egg-info/dependency_links.txt
writing top-level names to warprnnt_pytorch.egg-info/top_level.txt
writing manifest file 'warprnnt_pytorch.egg-info/SOURCES.txt'
reading manifest file 'warprnnt_pytorch.egg-info/SOURCES.txt'
writing manifest file 'warprnnt_pytorch.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build
creating build/lib.linux-x86_64-3.6
creating build/lib.linux-x86_64-3.6/warprnnt_pytorch
copying warprnnt_pytorch/__init__.py -> build/lib.linux-x86_64-3.6/warprnnt_pytorch
running build_ext
building 'warprnnt_pytorch.warp_rnnt' extension
creating build/temp.linux-x86_64-3.6
creating build/temp.linux-x86_64-3.6/src
gcc -pthread -B /data/ahnaf/espnet_asr/espnet/tools/venv/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/data/ahnaf/espnet_asr/espnet/tools/warp-transducer/include -I/data/ahnaf/espnet_asr/espnet/tools/venv/lib/python3.6/site-packages/torch/lib/include -I/data/ahnaf/espnet_asr/espnet/tools/venv/lib/python3.6/site-packages/torch/lib/include/torch/csrc/api/include -I/data/ahnaf/espnet_asr/espnet/tools/venv/lib/python3.6/site-packages/torch/lib/include/TH -I/data/ahnaf/espnet_asr/espnet/tools/venv/lib/python3.6/site-packages/torch/lib/include/THC -I/data/ahnaf/espnet_asr/espnet/tools/venv/include/python3.6m -c src/binding.cpp -o build/temp.linux-x86_64-3.6/src/binding.o -std=c++11 -fPIC -DWARPRNNT_ENABLE_GPU -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=warp_rnnt -D_GLIBCXX_USE_CXX11_ABI=0
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
In file included from /data/ahnaf/espnet_asr/espnet/tools/venv/lib/python3.6/site-packages/torch/lib/include/THC/THC.h:4:0,
                 from src/binding.cpp:8:
/data/ahnaf/espnet_asr/espnet/tools/venv/lib/python3.6/site-packages/torch/lib/include/THC/THCGeneral.h:17:10: fatal error: cublas_v2.h: No such file or directory
 #include "cublas_v2.h"
          ^~~~~~~~~~~~~
compilation terminated.
error: command 'gcc' failed with exit status 1
Makefile:98: recipe for target 'warp-transducer.done' failed
make: *** [warp-transducer.done] Error 1
(espnet) shafkat@server-master:/data/ahnaf/espnet_asr/espnet/tools$

Things I have done to install:
1. Installed the kaldi package using conda - **conda install -c conda-forge kaldi**
2. Cloned the espnet repo from github
3. Used this command: **make -j 10 PYTHON_VERSION=3.6 CUDA_VERSION=10.0**. Got kaldi.done error though.
4. Used this command after then: **make check_install** .  And got the above-mentioned error.

Am I missing something to do?

**Comment by sw005320** [comment]
Did you correctly specify the cuda path (see https://github.com/espnet/espnet#step-1-setting-of-the-environment-for-gpu-support)?

**Comment by samin9796** [comment]
@sw005320  I worked with different ASR tools using cuda before, so I thought my cuda path was set correctly. I found that my cuda version is 10.0 using the nvcc --version command. But in my pc, I can find only one file named "cublas_v2.h" which is located in this path **/usr/local/cuda-9.0** .  I can't find any folder for cuda 10.0 version in my pc but there is cuda 9.0 folder having the cublas_v2.h file - seems confusing to me. Any way to be sure about the cuda root path?

**Comment by sw005320** [comment]
Then, can you try it with cuda-9.0?
It seems that this is specific to your environments, and I could not give you more advice ([this](https://stackoverflow.com/questions/36279045/where-did-cuda-get-installed-in-my-computer) might help you???)

**Comment by ahmedalbahnasawy** [comment]
I had the same issue before and i fixed it 
```
export CUDA_HOME=$HOME/tools/cuda-9.0 # change to your path
export CUDA_TOOLKIT_ROOT_DIR=$CUDA_HOME
export LD_LIBRARY_PATH="$CUDA_HOME/extras/CUPTI/lib64:$LD_LIBRARY_PATH"
export LIBRARY_PATH=$CUDA_HOME/lib64:$LIBRARY_PATH
export LD_LIBRARY_PATH=$CUDA_HOME/lib64:$LD_LIBRARY_PATH
export CFLAGS="-I$CUDA_HOME/include $CFLAGS
```

**Comment by Arafat4341** [comment]
I am also getting error.

```
/content/espnet/tools/venv/lib/python3.7/site-packages/torch/lib/include/ATen/cuda/CUDAStream.h:6:10: fatal error: cuda_runtime_api.h: No such file or directory
 #include "cuda_runtime_api.h"
          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
error: command 'gcc' failed with exit status 1
Makefile:106: recipe for target 'warp-transducer.done' failed
make: *** [warp-transducer.done] Error 1
```

**Comment by Fuxuandi-Michelle** [comment]
I am setting the same error as well, 

> I had the same issue before and i fixed it
> 
> ```
> export CUDA_HOME=$HOME/tools/cuda-9.0 # change to your path
> export CUDA_TOOLKIT_ROOT_DIR=$CUDA_HOME
> export LD_LIBRARY_PATH="$CUDA_HOME/extras/CUPTI/lib64:$LD_LIBRARY_PATH"
> export LIBRARY_PATH=$CUDA_HOME/lib64:$LIBRARY_PATH
> export LD_LIBRARY_PATH=$CUDA_HOME/lib64:$LD_LIBRARY_PATH
> export CFLAGS="-I$CUDA_HOME/include $CFLAGS
> ```

I am still getting the same error after setting the environment. Does anyone know how to fix this?

**Comment by kan-bayashi** [comment]
@Fuxuandi-Michelle Why don't your add `CPATH`?

```
CUDAROOT=/path/to/cuda

export PATH=$CUDAROOT/bin:$PATH
export LD_LIBRARY_PATH=$CUDAROOT/lib64:$LD_LIBRARY_PATH
export CFLAGS="-I$CUDAROOT/include $CFLAGS"
export CPATH=$CUDAROOT/include:$CPATH
```

**Comment by Fuxuandi-Michelle** [comment]
> @Fuxuandi-Michelle Why don't your add `CPATH`?
> 
> ```
> CUDAROOT=/path/to/cuda
> 
> export PATH=$CUDAROOT/bin:$PATH
> export LD_LIBRARY_PATH=$CUDAROOT/lib64:$LD_LIBRARY_PATH
> export CFLAGS="-I$CUDAROOT/include $CFLAGS"
> export CPATH=$CUDAROOT/include:$CPATH
> ```

Thank you so much! The problem is solved. Turns out I typed the CUDA path wrongly.
