### ISSUE TITLE
useradd: UID 0 is not unique - Docker installation problem

### ISSUE THREAD

**Issue by samin9796** [espnet/espnet#1512]
I am getting this error. Any solution please?

> sudo ./run.sh --docker_gpu 7 --docker_egs chime4/asr1 --docker_folders /export/corpora4/CHiME4/CHiME3 --dlayers 1 --ngpu 1
[sudo] password for shafkat: 
Building docker image...
Now running docker build --build-arg FROM_TAG=gpu-cuda10.0-cudnn7-u18 --build-arg THIS_USER=shafkat --build-arg THIS_UID=0 -f prebuilt/Dockerfile -t espnet/espnet:gpu-cuda10.0-cudnn7-u18-user-shafkat .
Sending build context to Docker daemon  56.32kB
Step 1/8 : ARG FROM_TAG
Step 2/8 : FROM espnet/espnet:${FROM_TAG}
 ---> 937b583f3b76
Step 3/8 : LABEL maintainer "Nelson Yalta <nyalta21@gmail.com>"
 ---> Using cache
 ---> 5ed7c573bb6d
Step 4/8 : ARG THIS_USER
 ---> Using cache
 ---> 4069c79f1b2e
Step 5/8 : ARG THIS_UID
 ---> Using cache
 ---> ce5ad4c6bb5e
Step 6/8 : RUN if [ ! -z "${THIS_UID}"  ]; then     useradd -m -r -u ${THIS_UID} -g root ${THIS_USER};     fi
 ---> Running in c48c8624f984
useradd: UID 0 is not unique
The command '/bin/sh -c if [ ! -z "${THIS_UID}"  ]; then     useradd -m -r -u ${THIS_UID} -g root ${THIS_USER};     fi' returned a non-zero code: 4

**Comment by Fhrozen** [comment]
There are two solutions
- Execute run without `sudo` ( `./run.sh --docker_gpu 7 --docker_egs chime4/asr1 --docker_folders...`), the code is supposed to work for a user without root access so the files can be accessible after processing.
- For root user set the flag `docker_user=false`. Smth like this: `sudo ./run.sh --docker_gpu 7 --docker_egs chime4/asr1 --docker_user=false --docker_folders...`

Let me know if there is any additional problem.

**Comment by samin9796** [comment]
@Fhrozen I executed run without sudo but got this error:

> (esp_docker) shafkat@server-master:/data/ahnaf/espnet/docker$ ./run.sh --docker_gpu 7 --docker_egs chime4/asr1 --docker_folders /export/corpora4/CHiME4/CHiME3 --dlayers 1 --ngpu 1
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.40/images/json?filters=%7B%22reference%22%3A%7B%22espnet%2Fespnet%3Agpu-cuda10.0-cudnn7-u18%22%3Atrue%7D%7D: dial unix /var/run/docker.sock: connect: permission denied
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.40/images/create?fromImage=espnet%2Fespnet&tag=gpu-cuda10.0-cudnn7-u18: dial unix /var/run/docker.sock: connect: permission denied
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.40/images/json?filters=%7B%22reference%22%3A%7B%22espnet%2Fespnet%3Agpu-cuda10.0-cudnn7-u18-user-shafkat%22%3Atrue%7D%7D: dial unix /var/run/docker.sock: connect: permission denied
Building docker image...
Now running docker build --build-arg FROM_TAG=gpu-cuda10.0-cudnn7-u18 --build-arg THIS_USER=shafkat --build-arg THIS_UID=1003 -f prebuilt/Dockerfile -t espnet/espnet:gpu-cuda10.0-cudnn7-u18-user-shafkat .
ERRO[0000] failed to dial gRPC: cannot connect to the Docker daemon. Is 'docker daemon' running on this host?: dial unix /var/run/docker.sock: connect: permission denied 
error during connect: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.40/build?buildargs=%7B%22FROM_TAG%22%3A%22gpu-cuda10.0-cudnn7-u18%22%2C%22THIS_UID%22%3A%221003%22%2C%22THIS_USER%22%3A%22shafkat%22%7D&cachefrom=%5B%5D&cgroupparent=&cpuperiod=0&cpuquota=0&cpusetcpus=&cpusetmems=&cpushares=0&dockerfile=prebuilt%2FDockerfile&labels=%7B%7D&memory=0&memswap=0&networkmode=default&rm=1&session=9eeiu9xk2xj276kwynz97l53t&shmsize=0&t=espnet%2Fespnet%3Agpu-cuda10.0-cudnn7-u18-user-shafkat&target=&ulimits=null&version=1: context canceled

The second way of adding `docker_user=false` is giving the "useradd: UID 0 is not unique" error.

**Comment by Fhrozen** [comment]
- About the first option, as I can see, your user account does not have access to the docker. I am wonder if you can check this. Try to follow the post-installation of docker in case you do not (https://docs.docker.com/install/linux/linux-postinstall/) and restart your PC. It will be better if you can avoid the use of sudo.

- For the second option, I am checking the code and cannot get idea what is the cause. it is because `docker_user=false` disable the use of UID and uses the downloaded container (does not build a new one). 

Can you copy the output of second option, please.
Also, can you copy the docker properties.

**Comment by samin9796** [comment]
@Fhrozen  This is the output:

> (esp_docker) shafkat@server-master:/data/ahnaf/espnet/docker$ sudo ./run.sh --docker_gpu 7 --docker_egs chime4/asr1 --docker_folders /export/corpora4/CHiME4/CHiME3 --dlayers 1 --ngpu 1 --docker_user false
[sudo] password for shafkat: 
Building docker image...
Now running docker build --build-arg FROM_TAG=gpu-cuda10.0-cudnn7-u18 --build-arg THIS_USER=shafkat --build-arg THIS_UID=0 -f prebuilt/Dockerfile -t espnet/espnet:gpu-cuda10.0-cudnn7-u18-user-shafkat .
Sending build context to Docker daemon  56.32kB
Step 1/8 : ARG FROM_TAG
Step 2/8 : FROM espnet/espnet:${FROM_TAG}
 ---> 937b583f3b76
Step 3/8 : LABEL maintainer "Nelson Yalta <nyalta21@gmail.com>"
 ---> Using cache
 ---> 5ed7c573bb6d
Step 4/8 : ARG THIS_USER
 ---> Using cache
 ---> 4069c79f1b2e
Step 5/8 : ARG THIS_UID
 ---> Using cache
 ---> ce5ad4c6bb5e
Step 6/8 : RUN if [ ! -z "${THIS_UID}"  ]; then     useradd -m -r -u ${THIS_UID} -g root ${THIS_USER};     fi
 ---> Running in c48c8624f984
useradd: UID 0 is not unique
The command '/bin/sh -c if [ ! -z "${THIS_UID}"  ]; then     useradd -m -r -u ${THIS_UID} -g root ${THIS_USER};     fi' returned a non-zero code: 4


Docker properties:

> (esp_docker) shafkat@server-master:/data/ahnaf/espnet/docker$ sudo docker version
Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea838
 Built:             Wed Nov 13 07:29:52 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea838
  Built:            Wed Nov 13 07:28:22 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

**Comment by Fhrozen** [comment]
Ok, Thank you for the report, this seems like a bug for option 2.

It should not display
```
Now running docker build --build-arg FROM_TAG=gpu-cuda10.0-cudnn7-u18 --build-arg 
THIS_USER=shafkat --build-arg THIS_UID=0 -f prebuilt/Dockerfile -t espnet/espnet:gpu-cuda10.0-
cudnn7-u18-user-shafkat .
```

I will try to check and submit a PR. meanwhile you can test by commenting the lines:
https://github.com/espnet/espnet/blob/4733c9452eab5c87e7caf1cf5c061820cbf9a0b6/docker/run.sh#L75-L88
and also probably will need to move 
https://github.com/espnet/espnet/blob/4733c9452eab5c87e7caf1cf5c061820cbf9a0b6/docker/run.sh#L124
out of the if.

**Comment by samin9796** [comment]
@Fhrozen  Well, I followed option 1 and this is what I got:

> (esp_docker) shafkat@server-master:/data/ahnaf/espnet/docker$ ./run.sh --docker_gpu 7 --docker_egs chime4/asr1 --docker_folders /export/corpora4/CHiME4/CHiME3 --dlayers 1 --ngpu 1
Building docker image...
Now running docker build --build-arg FROM_TAG=gpu-cuda10.0-cudnn7-u18 --build-arg THIS_USER=shafkat --build-arg THIS_UID=1003 -f prebuilt/Dockerfile -t espnet/espnet:gpu-cuda10.0-cudnn7-u18-user-shafkat .
Sending build context to Docker daemon  56.32kB
Step 1/8 : ARG FROM_TAG
Step 2/8 : FROM espnet/espnet:${FROM_TAG}
 ---> 937b583f3b76
Step 3/8 : LABEL maintainer "Nelson Yalta <nyalta21@gmail.com>"
 ---> Using cache
 ---> 5ed7c573bb6d
Step 4/8 : ARG THIS_USER
 ---> Using cache
 ---> 4069c79f1b2e
Step 5/8 : ARG THIS_UID
 ---> Using cache
 ---> ce5ad4c6bb5e
Step 6/8 : RUN if [ ! -z "${THIS_UID}"  ]; then     useradd -m -r -u ${THIS_UID} -g root ${THIS_USER};     fi
 ---> Running in 9d822130f4cb
Removing intermediate container 9d822130f4cb
 ---> e4d8e8c6f68e
Step 7/8 : USER ${THIS_USER}
 ---> Running in 081c854b829a
Removing intermediate container 081c854b829a
 ---> fb5ff91df7ac
Step 8/8 : WORKDIR /
 ---> Running in d9e97e584e07
Removing intermediate container d9e97e584e07
 ---> 390eede12753
Successfully built 390eede12753
Successfully tagged espnet/espnet:gpu-cuda10.0-cudnn7-u18-user-shafkat
Using image espnet/espnet:gpu-cuda10.0-cudnn7-u18-user-shafkat.
Executing application in Docker
NV_GPU='7' nvidia-docker run -i --rm --name espnet_gpu7_20200116T0314 -v /data/ahnaf/espnet/egs:/espnet/egs -v /data/ahnaf/espnet/espnet:/espnet/espnet -v /data/ahnaf/espnet/test:/espnet/test -v /data/ahnaf/espnet/utils:/espnet/utils -v /export/corpora4/CHiME4/CHiME3:/export/corpora4/CHiME4/CHiME3 espnet/espnet:gpu-cuda10.0-cudnn7-u18-user-shafkat /bin/bash -c 'cd /espnet/egs/chime4/asr1; ./run.sh --dlayers 1 --ngpu 1'
./run.sh: line 156: nvidia-docker: command not found
run.sh done.

**nvidia-docker command not found** Will it be a problem?

I haven't worked with docker before. Can you please tell me what to do next given that I have prepared all the required files for asr training?

**Comment by Fhrozen** [comment]
Thank you for the report.
I also see this. The problem is that the current code is written for nvidia-docker 1.
While for new updates, is still not supported.

I will try to fix this ASAP.
meanwhile, you can change line https://github.com/espnet/espnet/blob/4733c9452eab5c87e7caf1cf5c061820cbf9a0b6/docker/run.sh#L100

with:

`docker run --gpus '"device=${docker_gpu}"'`

> Can you please tell me what to do next given that I have prepared all the required files for asr training?

I suppose that you are already at stage 2. So there are two options:
- Train from scratch LM and ASR and decode. 
- Download the pretrained model found at (https://github.com/espnet/espnet/blob/master/egs/chime4/asr1/RESULTS.md). And decode.

Follow the one fits you the most.

**Comment by samin9796** [comment]
@Fhrozen  Where can I follow the stages from? Any documentation on what command to use to start the training? I would like to train from scratch.

**Comment by Fhrozen** [comment]
Because of the recipe you are using is the  chime4/asr1, then you can check the code at https://github.com/espnet/espnet/blob/master/egs/chime4/asr1/run.sh
Detail information and example at the docs: https://espnet.github.io/espnet/notebook/asr_cli.html

**Comment by Fhrozen** [comment]
WIP
