### ISSUE TITLE
which path is the  teacher_model_path="" ?

### ISSUE THREAD

**Issue by xiaoyangnihao** [espnet/espnet#1517]
In the directory:   egs/ljspeech/tts1/run.sh  line 41. teacher_model_path=""

I fist run the this scirpt for with train_config=conf/tuning/train_pytorch_transformer.v2.yaml

Now I want to train a fastspeech model, but I am not sure which path is the teacher_model_path, does anybody can help me?

**teacher_model_path=""**
teacher_decode_config=conf/decode_for_knowledge_dist.yaml
do_filtering=false     # whether to do filtering using focus rate
focus_rate_thres=0.65  # for phn taco2 around 0.65, phn transformer around 0.9
                       # if you want to do filtering please carefully check this threshold

thanks for any help

**Comment by xiaoyangnihao** [comment]
Appereciate any help!

**Comment by kan-bayashi** [comment]
This README will help you.
https://github.com/espnet/espnet/blob/master/egs/ljspeech/README.md

You can specify your trained transformer model path (e.g. `exp/<path_to>/results/model.last1.best`).
Note that `transformer.v2` uses `reduction-factor: 2` and therefore you should modify `fastspeech.v4` config to make it use `reduction-factor: 2`.

**Comment by xiaoyangnihao** [comment]
@kan-bayashi thanks for your reply.  
For me, is this path: espnet/egs/ljspeech/tts1/exp/char_train_no_dev_pytorch_train_pytorch_transformer.v2/results/snapshot.ep.1000  , the last snapshot.ep actually is the teacher_model_path, right ?

By the way, if I train tts2: tacotron2+CBHG as the teacher model, in the second step, I just need to modify train_config=conf/train_pytorch_tacotron2+cbhg.yaml to train_fastspeech.v4.single.yaml in tts2/run.sh, right ?

**Comment by kan-bayashi** [comment]
Both `snapshot.ep.*` and `model.*.best` can be used as a teacher.
And the path should be absolute or relative path from `egs/ljspeech/tts1` so in your case `exp/char_train_no_dev_pytorch_train_pytorch_transformer.v2/results/snapshot.ep.1000`.

> By the way, if I train tts2: tacotron2+CBHG as the teacher model, in the second step, I just need to modify train_config=conf/train_pytorch_tacotron2+cbhg.yaml to train_fastspeech.v4.single.yaml in tts2/run.sh, right ?

Sorry, I've never tested fastpseech with tts2 (i.e. +CHBG). It may not work well.

**Comment by xiaoyangnihao** [comment]
@kan-bayashi  Thanks for your help, fastspeech model is training now.

I also wonder whether there is a simple way to sythesize some new sentences not in the raw LJSpeech data sets ?  Or on the other hand, how can I sythesize some new sentences with trained transformer model ?

**Comment by kan-bayashi** [comment]
Try `utils/synth_wav.sh` or please check the following notebook.
https://colab.research.google.com/github/espnet/notebook/blob/master/tts_realtime_demo.ipynb

**Comment by EsmaeilFarhang** [comment]
> In the directory: egs/ljspeech/tts1/run.sh line 41. teacher_model_path=""
> 
> I fist run the this scirpt for with train_config=conf/tuning/train_pytorch_transformer.v2.yaml
> 
> Now I want to train a fastspeech model, but I am not sure which path is the teacher_model_path, does anybody can help me?
> 
> **teacher_model_path=""**
> teacher_decode_config=conf/decode_for_knowledge_dist.yaml
> do_filtering=false # whether to do filtering using focus rate
> focus_rate_thres=0.65 # for phn taco2 around 0.65, phn transformer around 0.9
> # if you want to do filtering please carefully check this threshold
> 
> thanks for any help

please, can you tell me what config file you are used? 
I'm training tacotron2_v3 for my own language, and the result is so good., I'm trying to train train_fastspeech.v4.single.yaml config file with char_train_pytorch_tacotron2.v3 as a teacher mode, which parameters should be changed and should be set trans_type="phn" in this config file?
and what about training steps? is it similar to training tacotron_v3?

**Comment by kan-bayashi** [comment]
If your teacher model is based on char, you must use `trans_type=char` for fastspeech.
And if you want to train knowledge distillation-based fastspeech (`v4`), please check `egs/ljspeech/tts1/run.sh`.
You can specify the `teacher_model_path=<your_teacher_model_path>` in `run.sh` and `train_config=conf/train_fastspeech.v4.yaml`. 
And then run the `run.sh --stage 3`.

**Comment by dzungcamlang** [comment]
Hi @xiaoyangnihao, I want to train fastspeech v4 as same you, but I have confuse that, I has must training complete  with conf train_pytorch_tacotron2.v4.yaml or only traing first 1 epoch,
then I can start training fastspeech v4  with teacher model is result of train_pytorch_tacotron2.v4:
Am I correct?

**Comment by kan-bayashi** [comment]
@dzungcamlang You must complete the training of teacher model at first.
