### ISSUE TITLE
bash: line 1: 47826 Killed in recognition 

### ISSUE THREAD

**Issue by 18445864529** [espnet/espnet#1518]
I modified the model a little to make it fit my task and ran it with the WSJ recipe. In the training stage it worked well but when doing recognition, it gave error as follows. 

```
2020-01-19 15:57:39,849 (splitjson:40) INFO: /gs/hs0/tga-tslab/bowenz/espnet/tools/venv/bin/python3 /gs/hs0/tga-tslab/bowenz/espnet/egs/wsj/asr1/../../../utils/splitjson.py --parts 32 dump/test_dev93/deltafalse/data.json
2020-01-19 15:57:39,849 (splitjson:40) INFO: /gs/hs0/tga-tslab/bowenz/espnet/tools/venv/bin/python3 /gs/hs0/tga-tslab/bowenz/espnet/egs/wsj/asr1/../../../utils/splitjson.py --parts 32 dump/test_eval92/deltafalse/data.json
2020-01-19 15:57:39,881 (splitjson:52) INFO: number of utterances = 503
2020-01-19 15:57:39,882 (splitjson:52) INFO: number of utterances = 333
bash: line 1: 47824 Killed                  ( asr_recog.py --config conf/decode.yaml --ngpu 0 --backend pytorch --recog-json dump/test_dev93/deltafalse/split32utt/data.25.json --result-label exp/train_si284_pytorch_train_no_preprocess/decode_test_dev93_decode_lm_word65000/data.25.json --model exp/train_si284_pytorch_train_no_preprocess/results/model.last10.avg.best --word-rnnlm exp/train_rnnlm_pytorch_lm_word65000/rnnlm.model.best ) 2>> exp/train_si284_pytorch_train_no_preprocess/decode_test_dev93_decode_lm_word65000/log/decode.25.log >> exp/train_si284_pytorch_train_no_preprocess/decode_test_dev93_decode_lm_word65000/log/decode.25.log
bash: line 1: 47826 Killed                  ( asr_recog.py --config conf/decode.yaml --ngpu 0 --backend pytorch --recog-json dump/test_dev93/deltafalse/split32utt/data.5.json --result-label exp/train_si284_pytorch_train_no_preprocess/decode_test_dev93_decode_lm_word65000/data.5.json --model exp/train_si284_pytorch_train_no_preprocess/results/model.last10.avg.best --word-rnnlm exp/train_rnnlm_pytorch_lm_word65000/rnnlm.model.best ) 2>> exp/train_si284_pytorch_train_no_preprocess/decode_test_dev93_decode_lm_word65000/log/decode.5.log >> exp/train_si284_pytorch_train_no_preprocess/decode_test_dev93_decode_lm_word65000/log/decode.5.log
bash: line 1: 48096 Killed                  ( asr_recog.py --config conf/decode.yaml --ngpu 0 --backend pytorch --recog-json dump/test_eval92/deltafalse/split32utt/data.3.json --result-label exp/train_si284_pytorch_train_no_preprocess/decode_test_eval92_decode_lm_word65000/data.3.json --model exp/train_si284_pytorch_train_no_preprocess/results/model.last10.avg.best --word-rnnlm exp/train_rnnlm_pytorch_lm_word65000/rnnlm.model.best ) 2>> exp/train_si284_pytorch_train_no_preprocess/decode_test_eval92_decode_lm_word65000/log/decode.3.log >> exp/train_si284_pytorch_train_no_preprocess/decode_test_eval92_decode_lm_word65000/log/decode.3.log
```

The error led me to the log files decode.\*.log, but when I opened them, no error or traceback was shown in the log.
Also, most of the decode.\*.logs have already shown the predictions and recognition results, the results seem favorable enough, but still, I cannot avoid such 'line1: Killed' error. 
I've run the recognition part several times, it always gave three line1: killed errors, but the decode.\*.log files that were pointed to differed each time.
It would be very helpful if you can indicate what is probably going wrong as I don't really have any clue about it, thanks a lot.

**Comment by AdolfVonKleist** [comment]
Perhaps it is an out of memory error?

**Comment by Fhrozen** [comment]
Yes, I am wondering how many CPUs and Memory do you have.
You need to remember that the decoding is processed in parallel for all the recog_sets. 
https://github.com/espnet/espnet/blob/4733c9452eab5c87e7caf1cf5c061820cbf9a0b6/egs/wsj/asr1/run.sh#L247

Try reducing the previous number. As example. i have a pc with 12 processes (CPU) and 32G of memory and do not have that problem. If you have many CPUs but not enough memory, run.sh will start killing your jobs.

**Comment by 18445864529** [comment]
> Yes, I am wondering how many CPUs and Memory do you have.
> You need to remember that the decoding is processed in parallel for all the recog_sets.
> https://github.com/espnet/espnet/blob/4733c9452eab5c87e7caf1cf5c061820cbf9a0b6/egs/wsj/asr1/run.sh#L247
> 
> Try reducing the previous number. As example. i have a pc with 12 processes (CPU) and 32G of memory and do not have that problem. If you have many CPUs but not enough memory, run.sh will start killing your jobs.

Thanks a lot, and sorry for my late reply, Seems that reducing the nj number solved the problem :-)

**Comment by 18445864529** [comment]
> Perhaps it is an out of memory error?

Thank you for the help!
