### ISSUE TITLE
how much improvements can we get using pitch in ASR tasks?

### ISSUE THREAD

**Issue by Some-random** [espnet/espnet#1521]
Pitch is considerable harder to get compared to Fbank and usually we would only use FBank features. I'm wondering how much improvements can we get using pitch in ASR tasks (like HKUST and AISHELL)?

**Comment by b-flo** [comment]
I'm not sure in ESPNET (most recipe for tonal languages use fbank_pitch as default) but  https://www.cs.cmu.edu/~ymiao/pub/icassp2016_ctc.pdf report a 1% WER improvment on AISHELL adding pitch (with a CTC model).

**Comment by sw005320** [comment]
We actually referred that paper and included the pitch feature. We also recently observed the significant benefits of using the pitch feature for the Vietnamese corpus (https://github.com/espnet/espnet/pull/1497#discussion_r365274153)

**Comment by Some-random** [comment]
Thank you both for the quick answer! My problems are solved for now.
