### ISSUE TITLE
ESPNET with noise reduction

### ISSUE THREAD

**Issue by djo-koconi** [espnet/espnet#1548]
Hello and thank you for the great work.

Have anyone tried to successfully implement noise reduction as a espnet front end? I have tried multiple techniques without significant improvement. Or other pre-processing technique?

I consider implementing the noise reduction module into espnet and attempting to train them back to back. Any advice on the matter?

**Comment by Fhrozen** [comment]
Did you check for the DNN frontend? https://github.com/espnet/espnet/tree/master/egs/chime4/asr1_multich

You could try this for another multichannel recipe.

**Comment by stefantomic** [comment]
Thank you @Fhrozen . 

This one seems to be multi-channel front end, while I am dealing with mono audio (stereo in best case) coming out of a PC microphone.

**Comment by s-tomic** [comment]
Thank you @Fhrozen .
This seems to be a multi channel front end, while I am dealing with mono input from a PC microphone, stereo in best case.

**Comment by sw005320** [comment]
We usually did not get good improvements with single-channel enhancement, but it's worth to revisit it.
It would be great if you share your efforts when it works.

**Comment by s-tomic** [comment]
I agree @sw005320 , been trying multiple data augmentation (and noise reduction) techniques to increase model's robustness, but so far coudn't get it to exceed or improve the performance of Libri pre-trained one.
