### ISSUE TITLE
Number of layers in large transformer for Librispeech

### ISSUE THREAD

**Issue by djo-koconi** [espnet/espnet#1552]
Hello, 

I am unsure how the number of layers impacts the WER of the large transformer for Librispeech.
Is there a info about WER of a large transformer without the language model?

I am unable to train the large transformer due to cuda out of memory issue on 4 1080 gpus and test it out and in my own experiments.

**Comment by sw005320** [comment]
@Fhrozen and @ShigekiKarita, I think you have some results for the number of layers, right? Could you share the result with @s-tomic?

**Comment by ShigekiKarita** [comment]
I tried to train deeper ones but I evaluated only validation accuracy (no WERs) and I got no improvement at that time:
- 12 layers: 94.5% (baseline before [this paper](https://arxiv.org/pdf/1909.06317.pdf)) 
- 14 layers: 94.7%
- 16 layers: 94.5%
- 24 layers: 93.8%
- 48 layers: 92.6%
- 96 layers: 92.3%

However, when we wrote [this paper](https://arxiv.org/pdf/1909.06317.pdf), @kan-bayashi found that wider one (more heads and units) seems better than deeper one with the same GPU resource.

**Comment by s-tomic** [comment]
Thank you very much on this useful information @ShigekiKarita . I will look into the paper in depth.

I was actually curious about **performance comparison** between the default configuration in Libri with 4 layers and Large transformer one with 12. 
How much does that increase in number of layers affects the performance?

**Comment by ShigekiKarita** [comment]
We tried smaller models in WSJ before and we reproduced almost same performance to this paper https://ieeexplore.ieee.org/document/8462506
Honestly, I and (other ESPnet developers) have been lazy to test more settings because there are so many corpora and tasks (ASR, TTS, ST, MT). Maybe it is time to find more lightweight models as you mention.

**Comment by s-tomic** [comment]
Thank you @ShigekiKarita .

I will try to run the tests by myself and see the difference between large transformer and a 4 layer encoder which is in default train.yaml for Libri.
