### ISSUE TITLE
Installation system

### ISSUE THREAD

**Issue by kamo-naoyuki** [espnet/espnet#1559]
I was wondering what system is the best for installation in a few weeks, but I couldn't give good answer myself. 

Current:
We can find it in `tools/`. We are using Makefile.

Issues:
- Makefile has too difficult syntax. I don't think that all users understand it.
- Makefile  was originally developed mainly for compile language, e.g. c/c++.  Our usage seems strange and almost all advantage of Makefile is not available.
   - Makefile supports parallel compiling, but pip can't work in parallel and we don't need parallelization  for the installation of python module originally.
   - Reusing object codes is the biggest advantage, but we don't need it too.

- We have three main categories now: ASR, TTS, ST/MT. Each tasks have different dependencies, but it's not always obvious what tool is required.
- Similar one to above:  I heard that many people are using espnet only for inference now, not for 
training, but which tool is required for inference mode is also unclear.

My suggestion: 

(I don't have concrete plan yet)

```
tools/
  - common/
      install_python.sh
  - asr/
      - train/
      - eval/
          - install_sclite.sh
      - inference/
          - install_kaldi.sh
          - install_warpctc_pytorch.sh
  - tts/
  - st/
  - extra/
      - install_nkf.sh
  - Makefile
```

```
# To show the dependencies of each recipes
egs/
    csj/
         asr1/
             tools/install_nkf.sh  # -> ../../../../tools/extra/install_nkf.sh
```

```
# Makefile
asr: asr_train asr_inference asr_eval
asr_inference:
    ./asr/inference/install_warpctc_pytorch.sh
```

```bash
# How to use Makefile
make asr
make asr_inference
```

We may also need to make clear the dependencies from each task in `setup.py`

Any other suggestion do you have?
( I'd like someone to tackle this matter if possible.)

**Comment by sw005320** [comment]
At least making inference and training installations separately is one of our action items. 
Also, I used to have several suggestions from other people to use `shell` instead of `make` like your suggestions, and I think this is a reasonable plan. 

Is there any example of other open-source toolkits handling various tools and also allowing various modes (training and inference for several tasks)?
I only know Kaldi and I just want to check the other examples.

**Comment by Fhrozen** [comment]
if the idea is to move to shell, I think that the docker build could be a template. 
https://github.com/espnet/espnet/blob/master/docker/build.sh
I was also thinking about adding a second installation script for espnet2, because it does not need of chainer, cupy , and kaldi

**Comment by sw005320** [comment]
> I was also thinking about adding a second installation script for espnet2, because it does not need of chainer, cupy , and kaldi

Yes, this can simplify our build process.
