### ISSUE TITLE
How to synthesis Chinese with the "csmsc.fastspeech.v3" model?

### ISSUE THREAD

**Issue by fly12357** [espnet/espnet#1560]
If it is possible for you to provide a simple example for Chinese TTS under the trained model "csmsc.fastspeech.v3".

Follow the steps of  "ljspeech" English TTS example, I meet the following problem: (The Chinese characters has been converted to pinyin)

![image](https://user-images.githubusercontent.com/40494145/73824893-ed4e0000-4835-11ea-8d87-c731e97c2a1b.png)

**Comment by kan-bayashi** [comment]
Please check our notebook.
https://colab.research.google.com/github/espnet/notebook/blob/master/tts_realtime_demo.ipynb

**Comment by fly12357** [comment]
> Please check our notebook.
> https://colab.research.google.com/github/espnet/notebook/blob/master/tts_realtime_demo.ipynb

Thank you. Very useful~
