### ISSUE TITLE
How do I train a multiple-speaker model (speech synthesis) based on Tacotron 2 and espnet?

### ISSUE THREAD

**Issue by LetterLi1997** [espnet/espnet#1561]
I'm new to Speech Synthesis & Deep Learning.

I have problem in training a multi-speaker model which should be created by **[Tacotron2][1]**. And I was told I can get some ideas from **[espnet][2]**, which is a end-to-end audio tools library. In this way, I found a good dataset called **libritts:** http://www.openslr.org/60/. And it's also found at **espnet**: https://github.com/espnet/espnet#tts-results

[![enter image description here][3]][3]
---------

## Here is my initial thought：

1. Download libritts corpus / Read the **espnet** code: *../espnet/egs/libritts/tts1/run.sh*, learning how to train the libritts corpus by pytorch-backend. 

> **Difficulty:** But I cannot get it across that how the author trained a libritts.tacotron2.v1 as I didn't found anything about tacotron2 along those shells related to run.sh. Maybe He didn't make those codes open-source.

2. Read the tacotron2 code and tune it into a multi-speaker network:

> **Difficulty:** I found the code is really complex.... I just got lost in reading these codes, without a clear understanding about how to tune this model. Cause Tacotron2 was designed with a LJSpeech Dataset(only 1 person).

3. Training the multi-speaker model with tiny set of dataset (http://www.openslr.org/60/) to save time.

[![enter image description here][4]][4]
> they contains about 110 people's data, which can be enough for my scenario.

## In the end:
Coud you please help me about my questions. I've been puzzled by this problem for a long time...

  [1]: https://github.com/NVIDIA/tacotron2
  [2]: https://github.com/espnet/espnet
  [3]: https://i.stack.imgur.com/k2yQF.png
  [4]: https://i.stack.imgur.com/o8rHl.png

**Comment by sw005320** [comment]
Sure, we're happy to help.
Can you clarify the questions more?
Which part you cannot understand and which part you think complex?
I also don't recommend to try a complicated problem (in your case multispeaker TTS) with the tiny data.
This just increases the difficulty that comes from the tiny data.
Instead, you should try a simple problem (single speaker TTS) with a sufficient amount of data, and them move to a complicated problem.

The complex code comes from the computational efficiency, generalization to our varieties of tasks, general complexities of deep learning itself.

**Comment by LetterLi1997** [comment]
**I genuinelly thanks for your kindness and notice!**
> Which part you cannot understand and which part you think complex?
- Thanks~ I'm going to make my questions more clear.

> I also don't recommend to try a complicated problem (in your case multispeaker TTS) with the tiny data.
- Thanks~ Here I'd like to ask how do you release the **libritts.tacotron2.v1**? I was wondering whether my target is the same as what you have done? Actually, I'd like to train a multi-speaker model by Tacotron2. 
[![enter image description here][3]][3]
[![enter image description here][1]][1]
**I found it. Maybe I should try transferring to branch v0.3.0 or v0.3.1 and read the code.**
### My initial goal is like this:
1. When I finish training the model, I can load it and select a person(maybe input a person's ID as it is in the dataset, like man-111 / woman-87)
2. It waits me for typing a sentence, like "How is the weather today?"
3. Then the inference model begins to synthesis the man-111's voice for "How is the weather today?"


  [1]: https://i.stack.imgur.com/b8Rto.png
  [2]: https://github.com/espnet/espnet
  [3]: https://i.stack.imgur.com/k2yQF.png
  [4]: https://i.stack.imgur.com/o8rHl.png

**Comment by sw005320** [comment]
> * Thanks~ Here I'd like to ask how do you release the **libritts.tacotron2.v1**? I was wondering whether my target is the same as what you have done? Actually, I'd like to train a multi-speaker model based on Tacotron2.

Yes.

>   **I found it. Maybe I should try transferring to branch v0.3.0 or v0.3.1 and read the code.**

I don't recommend to check the old version.
Maybe you first start to check
https://github.com/espnet/espnet/blob/master/egs/libritts/tts1/run.sh
If you want to understand more details, you can just read https://github.com/espnet/espnet/blob/master/espnet/nets/pytorch_backend/e2e_tts_tacotron2.py
and 
https://github.com/espnet/espnet/tree/master/espnet/nets/pytorch_backend/tacotron2

> ### My initial goal is like this:
> 1. When I finish training the model, I can load it and select a person(maybe input a person's ID as it is in the dataset, like man-111 / woman-87)
> 2. It waits me for typing a sentence, like "How is the weather today?"
> 3. Then the inference model begins to synthesis the man-111's voice for "How is the weather today?"

This is feasible even with the current pre-trained model (without training).
If you read the above code, you can find speaker embedding input based on x-vector. If you change this part and throw specific speakers' audio data to extract the x-vector system, you can generate that person's voice.
We would not have a specific code for it and you may need some implementations (in https://github.com/espnet/espnet/blob/master/egs/libritts/tts1/run.sh level).

**Comment by LetterLi1997** [comment]
Thank you so much!  I've located this 2 files as you list above at the latest master branch.
To be honest, it's hard for me to tune the Tacotron2 model as I want it to be.

-------
Thanks for your tips to build multi-speaker model, I think your solution is probably convenient one. I'm going to try it these days.

BTW, I'd like to share a repo based on Tacotron2 and libritts for multi-spaker TTS.
https://github.com/NVIDIA/mellotron
