### ISSUE TITLE
Installation instructions do not work at all: Endless errors

### ISSUE THREAD

**Issue by lukecograph** [espnet/espnet#1562]
Hello.

I am on Ubuntu 18.04.

I have been struggling for a week now to get ESPNet up and running with no success so far. I believe that the installation instructions are incomplete and that many of the install scripts have errors.

I've had dozens and dozens and dozens of errors, most of which I have fixed, some of which I do not have a deep enough knowledge of the underlying framework to solve. I am going to assert that you should have a clear, step by step "it just works" guide for popular environments.

How to replicate:

- Install an Ubuntu 18.04 virtual machine
- Clone the repository.
- Follow the instructions in the read me.
- Deal with errors and missing packages galore, google solutions all day long, try the docker image, have the same or similar problems, learn about Kaldi, successfully set up Kaldi, go back to ESPNet and use that knowledge to fix all of the kaldi errors, get stuck on other errors, come to github finally and complain.

How to fix:
- Install a fresh Ubuntu 18.04 virtual machine
- Try to actually follow your own instructions
- Observe all the brokenness and do not proceed with installation without actually writing down precisely everything you do to fix said brokenness. This includes including all packages you install and all shell scripts that you need to edit and fix, as well as environmental variables and dependencies that you set up.
Do not assume prior knowledge of the underlying framework, dependencies, or how to configure everything.

Rather than asking question after question and reporting bug after bug, I decided to suggest this as a much quicker and more straightforward solution. Nobody can use your software if they can't figure out how to install it.

**Comment by kdubovikov** [comment]
After two days, I was finally able to successfully build espnet on Ubuntu 18.04. To do this, I had to build kladi manually:

```
export CUDAROOT=/usr/local/cuda-10.2
export PATH=$CUDAROOT/bin:$PATH
export LD_LIBRARY_PATH=$CUDAROOT/lib64:$LD_LIBRARY_PATH
export CUDA_HOME=$CUDAROOT
export CUDA_PATH=$CUDAROOT

# this command is missing from the manual, but were required to complete setup
export CPATH=/usr/local/cuda-10.2/targets/x86_64-linux/include:$CPATH

# install dependencies, I had disabled cuda for kaldi and it compiled successfuly after that
sudo apt-get install libatlas-base-dev

# build kaldi manually
cd kaldi/tools
make all
cd ../src
./configure --shared --mathlib=ATLAS --use-cuda=no; $(MAKE) depend; $(MAKE) all
make depend; make all

# continue espnet installation using make
cd ..
touch kaldi.done
make -j 4
```

**Comment by ShigekiKarita** [comment]
For Kaldi issues, ask Kaldi forum or use our prebuilt binary used in CI https://github.com/espnet/espnet/blob/master/ci/install_kaldi.sh

And also see our CI settings for Ubuntu 18.04 https://github.com/espnet/espnet/blob/master/.circleci/config.yml#L19

**Comment by kdubovikov** [comment]
@ShigekiKarita, this is a great suggestion. Although, I think that the installation manual should be updated. At least, it should include an OS version on which the setup scripts were tested, so the new users won't attempt to install it on other OS releases. I guess the current installation instructions at https://espnet.github.io/espnet/tutorial.html#installation were tested using Ubuntu 16.04? The links and steps you mentioned above could also be added to this page to simplify the installation process.
I see discussions about changing the entire installation system in  #1559, which may be a good way to go, but the project will need a minimum working installation time in the meantime.
I'd add those myself, but I am not yet experienced enough with the framework to write reliable documentation.

**Comment by sw005320** [comment]
I agree with @kdubovikov 
@ShigekiKarita, could you add some documentation in the installation part of README.md to include the sentences you mentioned above?

**Comment by kamo-naoyuki** [comment]
One of our problems about installation is having many options.

I think the installation for Kaldi via our Makefile is not practical. Actually, we need specify blas library and cuda path, at least. The parallel number for kaldi-make should be also different from our make-flow.

https://github.com/espnet/espnet#step-2-b-installation-including-kaldi-installation

**Comment by akreal** [comment]
Recently we got ASR inference to work without Kaldi at all, by replacing feature extraction with functions from `torchaudio` and normalization with regular torch operations. If feature extraction is the only function of Kaldi binaries in ESPnet, it may be possible to avoid compiling Kaldi.

**Comment by sw005320** [comment]
Thanks @kamo-naoyuki and @akreal!
**espnet2** could make it Kaldi-free, and we can make our installation process simple by that.
I'll not touch the major change for the installation-related part for now, but if we have some simple solutions, we can do it.
Also, we started a discussion about the torchaudio team. I hope we could officially support torchaudio based feature extraction soon in addition to our own and librosa ones.
