### ISSUE TITLE
Using recog_wav.sh with pertained model ru_open_stt

### ISSUE THREAD

**Issue by kdubovikov** [espnet/espnet#1563]
I am having problems with using models pretrained on ru_open_stt. I've downloaded models using the link in the [README.md](https://github.com/espnet/espnet/blob/master/egs/ru_open_stt/asr1/RESULTS.md) and extracted them into the experiment directory.
After that, I ran the following command to decode the wav file using those models:
```
../../../utils/recog_wav.sh --cmvn ./data/train/cmvn.ark --lang_model ./exp/train_rnnlm_pytorch_lm_unigram100/rnnlm.model.best --recog_model ./exp/train_pytorch_train/results/model.val10.avg.best --decode_config ./conf/tuning/decode_pytorch_transformer_large.yaml  ~/recording.wav
stage 0: Data preparation
stage 1: Feature Generation
steps/make_fbank_pitch.sh --cmd run.pl --nj 1 --write_utt2num_frames true decode/recording/data decode/recording/log decode/recording/fbank
steps/make_fbank_pitch.sh: no such file conf/fbank.conf
```

It seems that the [ru_open_stt](https://github.com/espnet/espnet/tree/master/egs/ru_open_stt/asr1) recipe is missing `conf/fbank.conf` configuration file. Is this the case, or am I doing something wrong?

**Comment by sw005320** [comment]
You could use https://github.com/espnet/espnet/blob/master/egs/ru_open_stt/asr1/conf/fbank.conf
It would be safe to execute `recog_wav.sh` at the recipe directory (that is `espnet/egs/ru_open_stt/asr1`).

**Comment by kdubovikov** [comment]
@sw005320 thanks, I've successfully managed to launch the script now. I think it's worth mentioning in the docs that the expected audio format for this model is mono wave with 16000 Hz frequency and 16 bits per channel. The script fails silently when the format is invalid

**Comment by sw005320** [comment]
Thanks for your input.
Can you suggest actual documentation about it?
I actually checked our `README.md` and in https://github.com/espnet/espnet/blob/master/README.md#asr-demo, it already says
```
You can recognize speech in a WAV file using pretrained models. Go to a recipe directory and run utils/recog_wav.sh as follows:

cd egs/tedlium2/asr1
../../../utils/recog_wav.sh --models tedlium2.transformer.v1 example.wav
where example.wav is a WAV file to be recognized. The sampling rate must be consistent with that of data used in training.
```
Also, inside ../../../utils/recog_wav.sh, it even provides an example to change the audio to 16k in https://github.com/espnet/espnet/blob/master/utils/recog_wav.sh#L54-L56

If you suggest additional descriptions to enrich this part, that is great!
