### ISSUE TITLE
ctc loss becomes 0.0 when --ctc_type "warpctc" was used

### ISSUE THREAD

**Issue by potato-inoue** [espnet/espnet#1571]
Now I'm trying to construct asr model. When I use `--ctc_type "warpctc"`, CTC loss becomes 0.0 at 1st epoch, and keeps the value 0.0 till the last epoch. I don't know whether this problem happens in only my environment.
#### loss.png of  `--ctc_type "warpctc"`
![loss](https://user-images.githubusercontent.com/38646618/74320865-b8592480-4dc4-11ea-950f-12a13e80ca5b.png)

When I use `--ctc_type "builtin"`, CTC loss becomes approximately 100 at 1st epoch, and decreases the value. Training seems to work well. 
#### loss.png of  `--ctc_type "builtin"`
![loss](https://user-images.githubusercontent.com/38646618/74320891-c3ac5000-4dc4-11ea-878c-beab39f4a931.png)

#### Training condition
- model config: `espnet/egs/tedlium2/asr1/conf/tuning/train_rnn.conf`
- data set: an4 (espnet/egs/an4/asr1), ljspeech (espnet/egs/ljspeech/tts1)
- pytorch: 1.0.0
- *No error happend when I tried "make check_install". 

Could you give me some advice on solving this?

**Comment by sw005320** [comment]
I just checked it in my environment with an4 with warpctc, and it seems to be working correctly...
```
        "validation/main/loss_ctc": 52.05878480275472,
        "validation/main/cer_ctc": 0.9985829269979597,
        "validation/main/loss_ctc": 44.1988730430603,
        "validation/main/cer_ctc": 0.9741787973596487,
        "validation/main/loss_ctc": 31.273692667484283,
        "validation/main/cer_ctc": 0.6414381440697945,
        "validation/main/loss_ctc": 24.197498162587483,
        "validation/main/cer_ctc": 0.550679326837122,
        "validation/main/loss_ctc": 18.041354313492775,
        "validation/main/cer_ctc": 0.38856195832834844,
```
At least the source code seems to be OK, but I did not reinstall it. So, I'll test it.
Could you also check to see what happened inside by using some debugger?

**Comment by yash-s20** [comment]
What CUDA version are you using? I think I've encountered a similar issue.

**Comment by yash-s20** [comment]
I would recommended checking this out - https://pypi.org/search/?q=warpctc-pytorch10. While in the virtualenv, find what version of warpctc is installed, find what CUDA version is installed, and most likely they're not compatible. Remove and install the right package if so, and run make check_install again to make sure nothing went wrong. Let me know if this works!

**Comment by sw005320** [comment]
Many thanks, @yash-s20!
@potato-inoue, could you check your environment again according to @yash-s20's suggestions?
