### ISSUE TITLE
On the fly feature generation from wav to spect for ASR

### ISSUE THREAD

**Issue by SeanNaren** [espnet/espnet#1578]
Hey guys,

Any chance ESPnet supports/will support on the fly feature generation? This is something that internally has helped us a lot with ever-changing datasets!

I'm more than happy to help do this if needs be and deemed worth it, if someone can point me to the right places.

**Comment by sw005320** [comment]
Thanks @SeanNaren for raising the issue.
We actually support the on-the-fly feature generation with our own feature extraction with https://github.com/espnet/espnet/blob/master/espnet/transform/transformation.py
@kamo-naoyuki, could you point out the documentation about it?

Also, espnet2 plans to make this on-the-fly feature generation default. (see https://github.com/espnet/espnet/blob/v.0.7.0/egs2/TEMPLATE/asr1/asr.sh#L43 and https://github.com/espnet/espnet/blob/v.0.7.0/egs2/TEMPLATE/asr1/asr.sh#L117)

**Comment by kamo-naoyuki** [comment]
Sorry, it's not well documented now, if the other guys didn't create.

ESPnet1 example:
https://github.com/espnet/espnet/tree/master/egs/chime4/asr1_multich

We implemented it as preprocessing for input data when data loading time and it can be configured by json or yaml file:

- wav -> stft example
https://github.com/espnet/espnet/blob/master/egs/chime4/asr1_multich/conf/preprocess.json
- fbank/stft -> spec-aug example
https://github.com/espnet/espnet/blob/master/egs/librispeech/asr1/conf/specaug.yaml


ESPnet2 takes different way from espnet1. i.e. it is combined in the model.
https://github.com/espnet/espnet/blob/v.0.7.0/espnet2/asr/frontend/default.py

ESPnet2 is under development, so I don't recommend you using, but I'm happy if you'll help to develop in any shape.

**Comment by SeanNaren** [comment]
Thanks guys! This can be closed but was just curious, when is ESPnet2 roughly scheduled to be released?

**Comment by sw005320** [comment]
Actually, the ASR part is almost fixed and we have performed a number of tests. It will be converged hopefully in a month and will have some initial release then. We'll keep both 1 & 2 for a while.

**Comment by SeanNaren** [comment]
That's awesome! Will close this for now, thanks guys :)
