### ISSUE TITLE
ESPnet ASR attention

### ISSUE THREAD

**Issue by desothier1** [espnet/espnet#1579]
hi,

This might be some naive questions, but when analyzing, attention .png files in folder results/att_ws,
having a look at Y-axis decoder index, and X-axis encoder index,
Am I right that the Y-axis decoder index corresponds to the _target_ output transcription and not to the actually _predicted_ transcription, during training? If that is the case, I would have expected to find the actually predicted transcription on the Y-axis.
(I used ESPnet version 0.3.1)

Is there ESPnet code available to generate attention heat maps for  input utterances during decoding (and not only during training)?

Thanks

**Comment by sw005320** [comment]
I thought that we have such functions, but I also could not find them. @kan-bayashi, could you answer it for me? I think this is a very important function.

**Comment by kan-bayashi** [comment]
TTS has it but ASR does not.
According to my memory, @potato-inoue has implemented such a function.

**Comment by sw005320** [comment]
where exactly in TTS? can you also put it in ASR?

**Comment by kan-bayashi** [comment]
This is taco 2 case.
https://github.com/espnet/espnet/blob/5d07e0b321d5270a5416b851642ea5374c76bea9/espnet/nets/pytorch_backend/tacotron2/decoder.py#L543-L567

**Comment by desothier1** [comment]
thanks, I will see what I can make of it
