### ISSUE TITLE
Why are we not using per-speaker normalization for HKUST and AISHELL

### ISSUE THREAD

**Issue by Some-random** [espnet/espnet#1582]
Looking at the shell script (https://github.com/espnet/espnet/blob/master/egs/hkust/asr1/run.sh) it seems like we're not using per-speaker normalization for input feature on HKUST and AISHELL. But using this would clearly improve the performance.

**Comment by sw005320** [comment]
We just do not want to use speaker information to make training simple (try to make e2e ASR work without using external knowledge like we don't use phoneme information).
If the performance improvement is very significant, we'll definitely revisit it. If you have such numbers, it is great if you share them with us!

**Comment by Some-random** [comment]
> We just do not want to use speaker information to make training simple (try to make e2e ASR work without using external knowledge like we don't use phoneme information).
> If the performance improvement is very significant, we'll definitely revisit it. If you have such numbers, it is great if you share them with us!

Thanks for the answer! I will share my results when I finished per-speaker normalization training of HKUST.
