### ISSUE TITLE
How to implement custom forward layer in ASR model?

### ISSUE THREAD

**Issue by teinhonglo** [espnet/espnet#1587]
Hi everyone!

I recently tried to customize the forward layer of the network, but I have some trouble.
The code changes in "espnet/nets/pytorch_backend/e2e_asr.py" are as follows:

First, I add this code to [L193](https://github.com/espnet/espnet/blob/master/espnet/nets/pytorch_backend/e2e_asr.py#L193):
`self.enc_2 = encoder_for(args, idim, self.subsample)`

Second, I add this code to [L259](https://github.com/espnet/espnet/blob/master/espnet/nets/pytorch_backend/e2e_asr.py#L259)
`hs_2_pad, hlens_2, _ = self.enc_2(hs_2_pad, hlens_2)`

I can train the model without errors, but I observe that there is no "enc_2" field in "model.json".
Does this mean that I did not save the parameters of "enc_2"?
How do I correctly add a custom forward layer and save its parameters?

Thanks in advance.
Tien-Hong

**Comment by b-flo** [comment]
Hi,

>I recently tried to customize the forward layer of the network, but I have some trouble.
The code changes in "espnet/nets/pytorch_backend/e2e_asr.py" are as follows:
>
>First, I add this code to L193:
self.enc_2 = encoder_for(args, idim, self.subsample)
>
>Second, I add this code to L259
hs_2_pad, hlens_2, _ = self.enc_2(hs_2_pad, hlens_2)

I'm not sure which forward layer you're talking about but you don't need to modify these lines if you're doing modifications within the encoder? As if, it look likes you only rename variables. 

> I can train the model without errors, but I observe that there is no "enc_2" field in "model.json".
Does this mean that I did not save the parameters of "enc_2"?
How do I correctly add a custom forward layer and save its parameters?

`enc_2` won't appear in `model.json`, you need to look at/print the model's parameters. It's not really human-readable but an easy/fast way is to open `model.loss.best` and search for `enc2.***`.
If you want to do that properly, you can look at `https://github.com/espnet/espnet/blob/master/espnet/asr/pytorch_backend/asr_init.py` to print parameters' keys and values when loading your model.

**Comment by teinhonglo** [comment]
OK, I got it. 
Thanks!
