### ISSUE TITLE
Tedlium 2: Pretrained transformer model not available

### ISSUE THREAD

**Issue by palle-k** [espnet/espnet#1590]
The pretrained Transformer (large model + specaug + large LM) model files for Tedlium 2 are unavailable at the link in the [RESULTS.md](https://github.com/espnet/espnet/blob/master/egs/tedlium2/asr1/RESULTS.md) file for Tedlium 2, as well as in the [Results and Demo section of the README of this project](https://github.com/espnet/espnet#results-and-demo) (tedlium2.transformer.v1).

In both cases, the link is https://drive.google.com/open?id=1mgbiWabOSkh_oHJIDA-h7hekQ3W95Z_U and it leads to the 404 page of Google Drive.

**Comment by ahmedalbahnasawy** [comment]
I think you are using recog_wav.sh file, you can replace it with your model if you have one.

**Comment by palle-k** [comment]
My issue is that I cannot access the pre-trained model. I know how to train my own model.

**Comment by sw005320** [comment]
@ShigekiKarita, can you fix the link?
I also confirmed that the link is broken.
Also, it would be better to put it to my google drive so that I could manage to fix it by myself.

**Comment by ShigekiKarita** [comment]
sorry I do not have access to that model file and GPU servers anymore. I
wish someone can rerun this exp and upload it...

2020年2月18日(火) 22:08 Shinji Watanabe <notifications@github.com>:

**Comment by ShigekiKarita** [comment]
If you can wait for 2 weeks, I will get back my GPU machine. I expect that I have downloaded the file there.

**Comment by ahmedalbahnasawy** [comment]
I downloaded Librispeech pre trained model before @palle-k 
I can share it with you if you don't mind

**Comment by sw005320** [comment]
@ahmedalbahnasawy, this is very helpful!
And also to avoid this issue, it would be better to put the model under my Google drive.
Could you send me your email address to shinjiw@ieee.org? Then, I'll send you an invitation.

**Comment by sw005320** [comment]
@ahmedalbahnasawy, @palle-k is asking about the Tedlium 2 model. Do you still have that?

**Comment by ahmedalbahnasawy** [comment]
yes i have it 
could you send me an invitation so i can share it with you

**Comment by sw005320** [comment]
Thanks! I just sent an invitation.
