### ISSUE TITLE
Using Trained Model with Microphone

### ISSUE THREAD

**Issue by jnoelvictorino** [espnet/espnet#1597]
Hi, 

I have read this issue about Online Decoding (#324). I am wondering if this idea will work.
My goal is to train a multi-speaker ASR based on WSJ-2mix recipe. I want to use trained model for transcribing speech to text from microphone. I looked at Kaldi's documentation and found [Online Decoding](https://kaldi-asr.org/doc/online_programs.html#audio_server). 

I was thinking if training in ESPnet then use trained model in Kaldi's Online Decoding.

**Comment by sw005320** [comment]
Unfortunately, we don't support such on-line decoding yet (we have ongoing projects though).

**Comment by jnoelvictorino** [comment]
I understand. Thank you for the quick response and I look forward to initial release of your projects. I am also ESPnet a lot. Thank you
