### ISSUE TITLE
torch unsqueeze is not inplace

### ISSUE THREAD

**Issue by TitouanT** [espnet/espnet#1604]
Unless I am missing something the `unsqueeze` method does not change the tensor inplace.
So in the lines below, since the result of the call is not stored, either these calls are artifact of debugging, either they are meant as inplace calls. Either way something is wrong here.

https://github.com/espnet/espnet/blob/226449ad2f9cc55b42b03393337c2586d41f688d/espnet/nets/pytorch_backend/rnn/decoders.py#L352-L355

For reference, here is the doc to torch `unsqueeze` function:
+ [torch.Tensor.unsqueeze](https://pytorch.org/docs/stable/tensors.html#torch.Tensor.unsqueeze)
+ [torch.unsqueeze](https://pytorch.org/docs/stable/torch.html#torch.unsqueeze)

A quick grep on the repo yield also those results (the last two are the ones cited above):
```
nets/pytorch_backend/e2e_asr_transformer.py:307:                vy.unsqueeze(1)
nets/pytorch_backend/e2e_mt_transformer.py:320:                vy.unsqueeze(1)
nets/pytorch_backend/e2e_st_transformer.py:376:                vy.unsqueeze(1)
nets/pytorch_backend/rnn/decoders.py:352:                vy.unsqueeze(1)
nets/pytorch_backend/rnn/decoders.py:355:                ey.unsqueeze(0)
```

**Comment by sw005320** [comment]
Many thanks.
This seems to be a problem.
@ShigekiKarita, do you have a bandwidth to take care of it?

**Comment by ShigekiKarita** [comment]
I see but it is not problem. We can safely delete them.

2020年2月24日(月) 22:24 Shinji Watanabe <notifications@github.com>:
