### ISSUE TITLE
MUST-C Transformer + ASR-MTL config

### ISSUE THREAD

**Issue by cookingbear** [espnet/espnet#1607]
what is the config of Transformer + ASR-MTL in the must-c RESULT?
I did not find any config with asr-weight!=0

**Comment by sw005320** [comment]
I think it must be https://github.com/espnet/espnet/blob/master/egs/must_c/asr1/conf/tuning/train_pytorch_transformer.yaml
@hirofumi0810, could you confirm it, and also add the config info to the `RESULTS.md`?

**Comment by cookingbear** [comment]
> I think it must be https://github.com/espnet/espnet/blob/master/egs/must_c/asr1/conf/tuning/train_pytorch_transformer.yaml
> @hirofumi0810, could you confirm it, and also add the config info to the `RESULTS.md`?

I found this Transformer + ASR-MTL result at the RESULT.md in the st directory, so does this "ASR-MTL" mean that ST is trained with ASR simultaneously or ASR is pre-trained using mtl?

**Comment by cookingbear** [comment]
@hirofumi0810, I just saw this result (Transformer + ASR-MTL | 22.31) of must-c st1 and wanna figure out what value the asr-weight and the mtlalpha is, thank you for sharing.

**Comment by hirofumi0810** [comment]
@cookingbear Sorry for the late reply. I was asr-weight: 0.3. Although the corresponding yaml file is not placed under `conf`, you can just set asr-weight to 0.3. I didn't modify any other settings.

**Comment by hirofumi0810** [comment]
@cookingbear And mtlalpha (CTC weight) was 1.0.
