### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by sw005320** [espnet/espnet#161]
ESPnet has several installation problems (many people pointed out).
#125 is one possible solution, and @jtrmal also proposed a shell script as follows

>  I have had a look at the Makefile and I'd suggest converting it to a shell script (or we should write a shell install script for each of the components). The way it's designed it's bound to generate tons of issues even in trivial cases like using python3

So, I'd like to ask your opinions, and want to fix this at least in a month for the workshop activity.

**Comment by kan-bayashi** [comment]
I’m not sure current installation problems, but shell script based installation is easy to understand fro me.

**Comment by sw005320** [comment]
I think we can at least check whether required modules are correctly imported after the installation by checking e.g., `python -c 'import chainer'`

**Comment by sw005320** [comment]
Thanks @kan-bayashi and @jnishi. @jtrmal, could you initiate to consider the shell based installation?

**Comment by sw005320** [comment]
Thanks @jtrmal 

The installation problems we had so far in addition to @jnishi's points are:

1. when our environments are updated (gcc 4.X -> gcc 6.X, cuda8.0 -> cuda9.1), warp_ctc cannot be correctly installed (the test is failed), @bobchennan is that correct?
2. the installation of `conda.mk` is failed when pytorch is updated from 0.31 to 0.40, again due to warp_ctc

I'll add others once I came up with. I can easily forget many things.
@m-wiesner, you also had some installation problems, right?

**Comment by bobchennan** [comment]
Yes for warp-ctc test_gpu will fail due to incompatibility. But we can ignore that error and continue the installation process.

**Comment by pozhijisi** [comment]
I am trying to install ESPnet with a (full) anaconda environment and will provide the installation recipe if succeeded. I know virtualenv is used in many places in ESPnet, but the installation experience with anaconda may be much better.

**Comment by jtrmal** [comment]
I don't think we should support too many ways how to install packages. In that case, I'd suggest offloading the work to the user, asking him/her to install the packages using the system-preferred installer. There is simply too much variability for us to be able to handle all of them well.
it can be either conda or venv or anything else, but just a single package manager. The packages we installed will be restricted to espnet tools anyway, so there is no danger (I think) to go for a single installation path.

**Comment by pozhijisi** [comment]
Yes, I partially agree with you that a single/uniform installation recipe should be enough. My concern is that using virtualenv may not be easy since itself may need root privilege to be installed. If you do not have the root privilege on a server/cluster, anaconda may generally be a better choice. I will recall my PR for now, but hopefully it may assist you in designing the installation script using virtualenv.

**Comment by harikrishnavydana** [comment]
is there a way to install without virtual environments. if the system has all the packages installed in miniconda. how to use them? with the current package?

**Comment by arendu** [comment]
all my install problems were solved when I used a clean bashrc file which only had the following lines:
```
CUDAROOT=/usr/local/cuda/

export PATH=$CUDAROOT/bin:$PATH
export LD_LIBRARY_PATH=$CUDAROOT/lib64:$LD_LIBRARY_PATH
export CUDA_HOME=$CUDAROOT
export CUDA_PATH=$CUDAROOT
```

So I suspect my bashrc had something conflicting before. Just FYI incase it helps others.
