### ISSUE TITLE
Disallowed UTF-8 whitespace character for  “CSMSC” validate_text

### ISSUE THREAD

**Issue by fly12357** [espnet/espnet#1613]
When I run the "CSMSC" recipe, I meet the follwing ERROR:

utils/validate_text.pl: The line for utterance 000001 contains CR (0x0D) character
utils/validate_text.pl: ERROR: text file 'data/train/text' contains disallowed UTF-8 whitespace character(s)

![image](https://user-images.githubusercontent.com/40494145/75222946-5c3cca00-57e0-11ea-9ac5-58c702b7d061.png)

**Comment by fly12357** [comment]
> When I run the "CSMSC" recipe, I meet the follwing ERROR:
> 
> utils/validate_text.pl: The line for utterance 000001 contains CR (0x0D) character
> utils/validate_text.pl: ERROR: text file 'data/train/text' contains disallowed UTF-8 whitespace character(s)
> 
> ![image](https://user-images.githubusercontent.com/40494145/75222946-5c3cca00-57e0-11ea-9ac5-58c702b7d061.png)

I solved this problem by convert the "^M" in "data/train/text" and "data/train/segments" .to "tab"
 
![image](https://user-images.githubusercontent.com/40494145/75317234-67582e80-58a2-11ea-832f-7316263150dc.png)


Will this convert bring new problems for "kaldiio"?

**Comment by sw005320** [comment]
Could you give me the example sentence including "^M"?

> Will this convert bring new problems for "kaldiio"?

I don't think so.

**Comment by kan-bayashi** [comment]
@fly12357 The newline code of the original phone label file is CRLF. Maybe this causes your problem. We convert it with `nkf` command to change to `LF` in the following lines.
https://github.com/espnet/espnet/blob/8bae85b68b2b2e890c0e6706c102033898aebe4f/egs/csmsc/tts1/local/data_download.sh#L23
Did you perform this conversion?

**Comment by sw005320** [comment]
Oh, I see (I forgot the CRLF issue).
Is #1618 related to this issue?

**Comment by kan-bayashi** [comment]
@sw005320 Right. The path is wrong, so it causes the error in the nkf converison part. Now it works correctly, I think.

**Comment by fly12357** [comment]
> @fly12357 The newline code of the original phone label file is CRLF. Maybe this causes your problem. We convert it with `nkf` command to change to `LF` in the following lines.
> https://github.com/espnet/espnet/blob/8bae85b68b2b2e890c0e6706c102033898aebe4f/egs/csmsc/tts1/local/data_download.sh#L23
> 
> 
> Did you perform this conversion?

Thanks～， I will update my code
