### ISSUE TITLE
Error while installing

### ISSUE THREAD

**Issue by tu1258** [espnet/espnet#1630]
My full script is as below:

> conda create --name espnet
> conda activate espnet
> git clone https://github.com/espnet/espnet
> cd espnet
> pip install -e .

And there are many errors when executing 
> pip install -e

There is one error talking about "install pysptk" and there is one claiming that protobuf would not match requirement(I pip install protobuf but still) and many others error.
The code is very short. I think it would be simpler to try it again by yourself than figure out my description.

Thanks!

**Comment by kamo-naoyuki** [comment]
Do you use python=3.8? If so use python3.7. pysptk and nnmnkwii don't support 3.8 yet due to cython.

**Comment by tu1258** [comment]
@kamo-naoyuki 
Hi, I use python 3.6 and there is only one error
`conda create --name espnet python=3.6`
> tensorboardx 2.0 has requirement protobuf>=3.8.0, but you'll have protobuf 3.7.1 which is incompatible.

`

**Comment by kamo-naoyuki** [comment]
Update protobuf, actually it requirements of chainer, or ignore the version warning.

**Comment by tu1258** [comment]
I update it to 3.11.4, but when I execute `pip install -e .` . It uninstall protobuf and install 3.7.1 version.
![image](https://user-images.githubusercontent.com/59950011/75628519-ca382580-5c14-11ea-8bc0-1ace70936af1.png

**Comment by kamo-naoyuki** [comment]
Of course. You don't need to install espnet after it. I say again, you can ignore this warning. Actually no problems happens.

**Comment by tu1258** [comment]
OK, thanks!

**Comment by tu1258** [comment]
Hi, @kamo-naoyuki 

I decide to follow the entire installation procedure in https://espnet.github.io/espnet/installation.html
But got problem at 
`make -j <NCPU>`
What should I insert in <NCPU> ?

**Comment by tu1258** [comment]
Hi, Since I finally install my cuda now, I decide to follow the entire instruction in https://espnet.github.io/espnet/installation.html

Here is my command

step1
```
CUDAROOT = usr/local/cuda-9.0
export PATH=$CUDAROOT/bin:$PATH
export LD_LIBRARY_PATH=$CUDAROOT/lib64:$LD_LIBRARY_PATH
export CFLAGS="-I$CUDAROOT/include $CFLAGS"
export CUDA_HOME=$CUDAROOT
export CUDA_PATH=$CUDAROOT
```
step 2
```
git clone https://github.com/kaldi-asr/kaldi
cd kaldi
cd tools
make -j 1
./extras/install_openblas.sh
cd src
./configure --openblas-root=../tools/OpenBLAS/install --use-cuda=no
make -j clean depend; make -j 4
```
step 3
```
git clone https://github.com/espnet/espnet
cd espnet
cd tools
make KALDI=../../kaldi PYTHON_VERSION=3.6 TH_VERSION=0.4.1 CUDA_VERSION=9.0
```
step4
```
cd tools
make check_install
```

When I execute `make check_install`, it shows
> rm -rf warp-transducer
> git clone https://github.com/HawkAaron/warp-transducer.git
> Cloning into 'warp-transducer'...
> remote: Enumerating objects: 894, done.
> remote: Total 894 (delta 0), reused 0 (delta 0), pack-reused 894
> Receiving objects: 100% (894/894), 243.46 KiB | 187.00 KiB/s, done.
> Resolving deltas: 100% (461/461), done.
> Checking connectivity... done.
> # Note: Requires gcc>=5.0 to build extensions with pytorch>=1.0
> if . venv/bin/activate && python -c 'import torch as t;assert t.__version__[0] == "1"' &> /dev/null; then \
>         . venv/bin/activate && python -c "from distutils.version import LooseVersion as V;assert V('5.4.0') >= V('5.0'), 'Requires gcc>=5.0'"; \
> fi
> . venv/bin/activate; cd warp-transducer && mkdir build && cd build && cmake .. && make; true
> /bin/sh: 1: cmake: not found
> . venv/bin/activate; cd warp-transducer/pytorch_binding && python setup.py install
> Could not find libwarprnnt.so in ../build.
> Build warp-rnnt and set WARP_RNNT_PATH to the location of libwarprnnt.so (default is '../build')
> Makefile:98: recipe for target 'warp-transducer.done' failed
> make: * [warp-transducer.done] Error 1

It seems it's because I didn't execute this? 
`mkdir -p espnet/tools/venv/bin; touch espnet/tools/venv/bin/activate`
It's in [Recipe](https://espnet.github.io/espnet/notebook/asr_cli.html) but not in [Installation](https://espnet.github.io/espnet/installation.html)

Any advice would be appreciate! Thanks!

**Comment by sw005320** [comment]
It says `/bin/sh: 1: cmake: not found`. Please install `cmake`.
(Check https://github.com/espnet/espnet/blob/master/.circleci/config.yml
You may need to install them in https://github.com/espnet/espnet/blob/master/.circleci/config.yml#L35-L36)
It is very difficult to give an entire install instruction since each person has a different environment.

**Comment by tu1258** [comment]
It goes well. Thanks!
