### ISSUE TITLE
Update support version on check_install.py

### ISSUE THREAD

**Issue by Fhrozen** [espnet/espnet#1631]
I observed that the current ESPnet with Pytorch backend can support torch > 1.0 (1.1 ...) but the supported versions on check_install has not been updated. 
Is there any problem to update the supported version on check_install. 
I cannot install docker with cuda 10.1 bc torch 1.0.1 does not support it. 
Should I update it?

**Comment by Fhrozen** [comment]
Yes, I will do.
Just to clarify:
In case of pytorch 1.2+, warpctc seems to not be working with (https://github.com/espnet/warp-ctc#for-pytorch-12).
So should I add an `if` in the Makefile https://github.com/espnet/espnet/blob/9bcab950d076808045bf48ece4be6385f1bd929a/tools/Makefile#L81 to avoid installing warpctc if `pytorch >=1.2`
and also in check_install.py 
to avoid checking warpctc version in the same scenario, given that calling warpctc generates a ImportError?

**Comment by sw005320** [comment]
Yes, I think this is a very good idea.
Probably, it would be better to have such handlings in https://github.com/espnet/espnet/blob/master/espnet/nets/pytorch_backend/ctc.py#L20 ?

Also, we may not seem to include the test for buildin ctc.
I think it is worth to add it.
