### ISSUE TITLE
How to train Transformer on your own dataset?

### ISSUE THREAD

**Issue by thrfdth** [espnet/espnet#1632]
Thanks for such a great repo!

I've worked on training a vocoder(Parallel wavegan) for Japanese but after training the vocoder on my own dataset and i changed the path for it to my tranined vocoder in e2etts colab file, i still hear the original speaker's voice even though the intermediate wav result which you get while training with kan-bayashi/ParallelWaveGAN sounds pretty good. so I'm guessing that i need to train Transformer(mel-spectrogram prediction model) on my own dataset as well. 

So How did you train the pretrained model? Is there available repos you used for training Transformer on github?

Thanks in advance.

**Comment by kan-bayashi** [comment]
Hi @thrfdth.
For Japanese, you can follow the egs/jsut/tts1 recipe.
(The model in colab notebook is trained on this recipe).

**Comment by thrfdth** [comment]
Thanks for your quick reply! @kan-bayashi 
I'll give it a try.
