### ISSUE TITLE
ASR decoding with time codes

### ISSUE THREAD

**Issue by ldeseynes** [espnet/espnet#1633]
Hi there, is there a way to retrieve time stamps from an audio file during decoding ? I mean something like a ctm file in Kaldi with every decoded word and related time code.

Thanks in advance,

**Comment by sw005320** [comment]
This is possible but not straightforward to get the time stamps for every token.
If we check the attention weight, we could get such information (but this is not precise).

**Comment by alexkararo** [comment]
Hello!
I also need to get some timestamps for recognized tokens, if for words is not possible. 

Anybody can point me to where I should start? 
Thank you in advance!

**Comment by sw005320** [comment]
You can use `utils/ctc_align_wav.sh`
https://github.com/espnet/espnet/blob/f0fd03d7864cbe5a84d17ae987e2396b970000dd/README.md#ctc-forced-alignment-demo although this is not very accurate, unfortunately.

**Comment by alexkararo** [comment]
> You can use `utils/ctc_align_wav.sh`
> https://github.com/espnet/espnet/blob/f0fd03d7864cbe5a84d17ae987e2396b970000dd/README.md#ctc-forced-alignment-demo although this is not very accurate, unfortunately.

Thank you! Will test this. 

If I may ask you one more question. I see in data.json that I can get the total log probability for each phrase. 
Is there a way to extract the log probability for each token / word?

**Comment by sw005320** [comment]
Unfortunately, it is not stored.
You may need to add a code to store it by yourself.

**Comment by ldeseynes** [comment]
> You can use `utils/ctc_align_wav.sh`
> https://github.com/espnet/espnet/blob/f0fd03d7864cbe5a84d17ae987e2396b970000dd/README.md#ctc-forced-alignment-demo although this is not very accurate, unfortunately.

There are no timestamps in result.json using ctc_align_wav.sh, should the config file be changed ? Also, is it possible to get these timestamps without providing the text beforehand ?

**Comment by sw005320** [comment]
Sorry that this is an advanced method requiring enough knowledge. 
What you can do is two-pass processing.
The first pass is based on normal decoding to get a result text and the second pass is to use `ctc_align_wav.sh`.
Also, `ctc_align_wav.sh` provides alignment information if you're familiar with CTC, and we can obtain timestamps based on the alignment information.

We are not planning to provide an entire function of performing the above steps for now, but we have a plan to extend `ctc_align_wav.sh` for more speech alignment purposes. We'll consider implementing such a function in that stage.

**Comment by alexkararo** [comment]
Hello again, 

I used the ctc_align_wav.sh, but I do not understand the output:

`{
    "utts": {
        "1_11": {
            "ctc_alignment": "T H E <blank> <blank> <blank> <blank> <blank> <unk> F <blank> <blank> <blank> A M <blank> <blank> I <blank> <blank> <blank> L <blank> Y <unk> T H E Y <unk> W E R E <blank> ............."
        }
    }
}`

Should I not get timestamps? 

Thank you!

**Comment by sw005320** [comment]
I think it's better to read some CTC papers to understand the output.
https://distill.pub/2017/ctc/ is good material.

**Comment by alexkararo** [comment]
Thank you!
