### ISSUE TITLE
[Feature Request]: allow to specify which gpu to use

### ISSUE THREAD

**Issue by qmeeus** [espnet/espnet#1634]
As far as I could see, there is no such option. To clarify, this is useful when running a script on a machine with more than one GPU, having a flag such as `--gpu 1` or `--device cuda:1` would be of great help!

Thanks for all the work!

**Comment by sw005320** [comment]
The GPU ID specification is different from the environment, and we did not prepare such options (we use to have that though).
The safe way is to do that through CUDA_VISIBLE_DEVICES, e.g., `CUDA_VISIBLE_DEVICES=0,1,2 ./run.sh --ngpu 3`

**Comment by qmeeus** [comment]
Correct me if I'm wrong, but [this](https://github.com/espnet/espnet/blob/master/espnet/bin/asr_train.py#L301) says otherwise.
From what I understand, you set the number of available gpus by counting the number of elements in `CUDA_VISIBLE_DEVICES` but it does not allow to choose a specific device.
If I may ask, why did you remove the option?

**Comment by sw005320** [comment]
This is because it is very safe to specify it through CUDA_VISIBLE_DEVICES. Otherwise, multiple jobs are wrongly thrown into the same GPU, which causes a lot of problems (memory and inefficiency).

**Comment by qmeeus** [comment]
Is it possible that you are missing a line after [this](https://github.com/espnet/espnet/blob/master/espnet/bin/asr_train.py#L324)?
```python
args.ngpu = ngpu
```

**Comment by sw005320** [comment]
Oh, this might be an issue.
@kan-bayashi, what do you think?
If we do not set this, the batch size of the multiple GPU is wrongly set (e.g., https://github.com/espnet/espnet/blob/9bcab950d076808045bf48ece4be6385f1bd929a/espnet/asr/pytorch_backend/asr.py#L409-L410)

**Comment by kamo-naoyuki** [comment]
Oh, this is my fault and must be a bug, but It's just giving args.ngpu with None to train(), so simply the program will be aborted.
