### ISSUE TITLE
Too often failed ci at downloading from google drive

### ISSUE THREAD

**Issue by kamo-naoyuki** [espnet/espnet#1636]
We all may know, ci is often failed with the following part:

https://github.com/espnet/espnet/blob/b55cbcc50090e56808b1b2f3abc7f9327b1af27b/test/test_e2e_compatibility.py#L33-L57

e.g.

https://github.com/espnet/espnet/pull/1570/checks?check_run_id=482370468

Can't we solve this?

**Comment by sw005320** [comment]
How about using https://github.com/wkentaro/gdown that @kan-bayashi introduced?

**Comment by kamo-naoyuki** [comment]
@kan-bayashi What do you think if we remove this test? 

Possibly there seems to be some limitations to access google drive per day(?), so it's not appropriate to test in the main repo's ci, anyway.
How about creating another repository to manage our pre-trained model and test there?

**Comment by kan-bayashi** [comment]
> @kan-bayashi What do you think if we remove this test? 

I agree. It is no problem.
