### ISSUE TITLE
Problem about the "char" based CSMSC recipes?

### ISSUE THREAD

**Issue by fly12357** [espnet/espnet#1640]
I trained a char based tacotron2 model for  "CSMSC" recipe. Then I used the "csmsc.parallel_wavegan.v1" model as the vocoder to synthesis Chinese. But, the result is bad. 

Can you give me some advice about how to improve the performance?

**Comment by kan-bayashi** [comment]
I'm not familiar with Mandarin, so let me ask some questions.
- What does "char" mean in Mandarin? (kanji?)
- What is the motivation for the use of "char" instead of pinyin?
- "Bad" means what? For example, totally failed (just like a noise) or the sound quality is not so good while it has meaningful content.

**Comment by fly12357** [comment]
> I'm not familiar with Mandarin, so let me ask some questions.
> 
> * What does "char" mean in Mandarin? (kanji?)
> * What is the motivation for the use of "char" instead of pinyin?
> * "Bad" means what? For example, totally failed (just like a noise) or the sound quality is not so good while it has meaningful content.

1. The "char" doesn't has meaning in Mandarin. I just split the pinyin to single character.
     e.g.  "zhong1 guo2"  -> "z h o n g 1 g u o 2"
     p.s. I add the "prosodic boundaries" in the training step.  #1, #2... in the "./downloads/CSMSC/ProsodyLabeling/000001-010000.txt"
2. The "initial" and "final" of the CSMCS dataset was not complete for any Chinese sentence; So I use the char as the input dict.
3. Bad means totally failed,

**Comment by fly12357** [comment]
> I'm not familiar with Mandarin, so let me ask some questions.
> 
> * What does "char" mean in Mandarin? (kanji?)
> * What is the motivation for the use of "char" instead of pinyin?
> * "Bad" means what? For example, totally failed (just like a noise) or the sound quality is not so good while it has meaningful content.
It's my mistake. I have retrain the char based "CSMSC" model. The result is OK.
