### ISSUE TITLE
Cannot reproduce WSJ Transformer RESULTS

### ISSUE THREAD

**Issue by wolverineq** [espnet/espnet#1643]
Hi I have noticed the latest WSJ RESULTS reporting WER 2.x% in eval92 using ctc-transformer models.
However I cannot reproduce the results with the same configurations.

My results:
PyTorch:1.1.0 espnet: 0.6.1 cuda: 9.0
data:using sample filtering (however with no utts excluded for train set )
model: ctc(PyTorch builtin)-transformer
WER: 5.2% CER:2.5%

Even I cannot decode similar results using the uploaded model files
I get WER 5.6% with the provided model files.

Maybe I have missing some important settings. Could you help me?

**Comment by sw005320** [comment]
@Emrys365, could you follow up on this discussion?

**Comment by Emrys365** [comment]
I just looked at the [RESULTS](https://github.com/espnet/espnet/blob/master/egs/wsj/asr1/RESULTS.md). It seems that I mistakenly used the wrong eval set (330 utterances) instead of the true eval92 set (333 utterances). I will check the setup again.

**Comment by Emrys365** [comment]
The best result in [RESULTS](https://github.com/espnet/espnet/blob/master/egs/wsj/asr1/RESULTS.md) turns out to be evaluated on eval92_5k, instead of eval92...
Can't believe I hadn't seen the bug in my setup for so long! Sorry for this.

I will test the model again on the true eval92 set and update the RESULTS.

**Comment by wolverineq** [comment]
> The best result in [RESULTS](https://github.com/espnet/espnet/blob/master/egs/wsj/asr1/RESULTS.md) turns out to be evaluated on eval92_5k, instead of eval92...
> Can't believe I hadn't seen the bug in my setup for so long! Sorry for this.
> 
> I will test the model again on the true eval92 set and update the RESULTS.

OK...that's a pity

**Comment by wolverineq** [comment]
BTW, anyone tries specaug on WSJ? any good results?
