### ISSUE TITLE
Error while stage 1(feature generation)

### ISSUE THREAD

**Issue by tu1258** [espnet/espnet#1645]
It is similar to #505
log file has this
```
bash: line 1: copy-feats: command not found
bash: line 1: paste-feats: command not found
```
path.sh is alright
but `your_espnet_root/tools/kaldi/src/featbin` only contains .cc file
then I `./check_dependencies.sh` and find that Intel MKL is not installed
so I run `./install_mkl.sh` but it fails
![89357470_1072629139789660_5036405640587640832_n](https://user-images.githubusercontent.com/59950011/75963470-825d1b00-5f00-11ea-85da-9b8bd6c88890.png)

this is when I enter http://ppa.launchpad.net/jonathonf/python-3.6/ubuntu/dists/xenial/main/binary-amd64/packages
![image](https://user-images.githubusercontent.com/59950011/75965147-5e4f0900-5f03-11ea-9f2b-81fce8b8b417.png)

Any advice would be appreciate. Thanks!

**Comment by b-flo** [comment]
Hi,

There was a problem reported in Kaldi some time ago with MKL (and also MKL repo) but it was fixed for what I remember. Is you kaldi up-to-date?

Also, if MKL is the only problem, you could to clean-up and try rebuilding with OPENBLAS.

**Comment by tu1258** [comment]
I think I might make a mistake. In [installation](https://espnet.github.io/espnet/installation.html), it git clone both kaldi and espnet. I am not sure the `/path/to/kaldi` in `make KALDI=/path/to/kaldi PYTHON=/usr/bin/python3.6 `. Is it ./kaldi (which means espnet/tools/kaldi) or ../../kaldi (which means "git clone kaldi").

I try ../../kaldi and the "git clone kaldi"  has correct file(there is not only .cc file) while espnet/tools/kaldi has only .cc file. But I try it in another computer and it works.
