### ISSUE TITLE
New argument `embed_unit` in language model breaks backward compability

### ISSUE THREAD

**Issue by unilight** [espnet/espnet#1646]
I'm using the pretrained Transformer ASR model on Librispeech as in [here](https://github.com/espnet/espnet/blob/master/egs/ljspeech/tts1/local/ob_eval/evaluate_cer.sh#L36-L40). Similar to issue #1638 , I think the new argument `embed_unit` in language model is breaking backward compatibility. In the original issue the solution seemed to be retraining it from scratch. I'm wondering if it is possible to fix the commit so I can still use the pretrained model normally.

**Comment by b-flo** [comment]
Hi,

>  I'm wondering if it is possible to fix the commit so I can still use the pretrained model normally.

I guess you could use `git revert commit-sha`?

**Comment by kan-bayashi** [comment]
This issue seems to affect all of the pretrained models. We should carefully keep backward compatibility.

**Comment by kan-bayashi** [comment]
I will fix this issue this evening.

**Comment by kan-bayashi** [comment]
Maybe fixed in #1649 
@unilight Could you check?

**Comment by unilight** [comment]
Thank you for the fix!

Sorry because in [the ASR evaluation script](https://github.com/espnet/espnet/blob/master/egs/ljspeech/tts1/local/ob_eval/evaluate_cer.sh), v2 was used. After using the fix, I still have trouble. But I can now successfully run by setting api to v1.
Could you also fix, I guess `espnet/asr/pytorch_backend/recog.py` for api v2?
Also I wonder what is the difference between v1 and v2?

**Comment by kan-bayashi** [comment]
Thanks, I will fix it in #1653.

**Comment by kan-bayashi** [comment]
Fixed.
