### ISSUE TITLE
Import error: No module named sentencepiece

### ISSUE THREAD

**Issue by david11252** [espnet/espnet#1656]
Hi, I tried to execute `run.sh` in LibriSpeech. At stage 2, there is an import error. 
> No module named sentencepiece

I `pip install sentencepiece` and it shows requirements already satisfied.
path `anaconda3/envs/espnet/lib/python3.7/site-packages` is also in sys.path
Is there any solution? Thanks!

**Comment by david11252** [comment]
I reinstalled with python=3.7.3. The problem still exists. Any advice?

**Comment by sw005320** [comment]
Did you install sentencepieice via our Makefile?

**Comment by david11252** [comment]
Hi, @sw005320 

> Did you install sentencepieice via our Makefile?

Yes! Below is my whole workflow.

step1
```
CUDAROOT = usr/local/cuda-9.0
export PATH=$CUDAROOT/bin:$PATH
export LD_LIBRARY_PATH=$CUDAROOT/lib64:$LD_LIBRARY_PATH
export CFLAGS="-I$CUDAROOT/include $CFLAGS"
export CUDA_HOME=$CUDAROOT
export CUDA_PATH=$CUDAROOT
```
step2
```
git clone https://github.com/kaldi-asr/kaldi
cd kaldi
cd tools
make -j 8
sudo ./extras/install_openblas.sh
cd ../src
./configure --openblas-root=../tools/OpenBLAS/install --use-cuda=no
make -j clean depend; make -j 8
```
step3
```
git clone https://github.com/espnet/espnet
cd
mkdir -p espnet/espnet/tools/venv/bin; touch espnet/espnet/tools/venv/bin/activate
cd espnet/espnet/tools
(PYTHON := /home/r08943133/anaconda3/envs/espnet/bin/)
(PYTHON_VERSION := 3.7.3)
(CUDA_VERSION := 9.0)
(KALDI := ../../kaldi)
make 
```
[Warning] torch 1.0.1 is not in .......
```
pip install torch==1.0.1.post2
```
step4
```
make check_install
```

**Comment by kan-bayashi** [comment]
We make virtualenv or conda in `tools/venv`. If you specify the PYTHON, the virtualenv will be created based on the specified python. I'm not sure when we use already created conda as a base python to create virtualenv. 

So, my recommendation is that:
- Deactivate your conda env before step3 
- Run `make` without specification of PYTHON

**Comment by david11252** [comment]
Hi, @kan-bayashi 

I try to install without any virtual environment(and change to `PYTHON := `), but still the same. Btw, I would only train/test grapheme model actually. It didn't show any error when I run the mtlalpha1.0 script in an4 and rnn-t in voxforge.(but I will  train a model for LibriSpeech eventually, which has import error now.) Is it necessary to install sentence piece? Thanks!

**Comment by kan-bayashi** [comment]
Actually sentencepiece is included in requirements, so usually we do not need to install manually. 
https://github.com/espnet/espnet/blob/94a066e7b669f5e78be6aba5863255d0a1a2d44e/setup.py#L42
But it is worthwhile to try it, e.g.,

cd egs/librispeech/asr1
. ./path.sh
pip install sentencepiece

If you do not use subword, sentencepiece is not needed.

**Comment by cstirling** [comment]
I also have this problem. And I found it caused by kaldi/tool/env.sh. So remove the first line ‘export PATH=/xxx/kaldi/tools/python:${PATH}’ then it works!

**Comment by jefflai108** [comment]
hi @kan-bayashi 
I followed the installation step carefully and got the same error mentioned by @david11252 
However, @cstirling's suggestion solve the issue
