### ISSUE TITLE
useradd: UID 0 is not unique

### ISSUE THREAD

**Issue by Arafat4341** [espnet/espnet#1663]
I ran docker on my t2.micro ec2 instance. I have a single CPU, 1gb RAM with no GPU.

I ran this command: `./run.sh --docker_gpu -1 --docker_egs chime4/asr1 --docker_folders /export/corpora4/CHiME4/CHiME3 --dlayers 1 --ngpu 0`

after completion of run I get this:
`
useradd: UID 0 is not unique
The command '/bin/sh -c if [ ! -z "${THIS_UID}"  ]; then     useradd -m -r -u ${             THIS_UID} -g root ${THIS_USER};     fi' returned a non-zero code: 4
`
What this is all about?

**Comment by sw005320** [comment]
See #1512
