### ISSUE TITLE
 warpctc_pytorch installation  failed  when using pytorch1.1.0

### ISSUE THREAD

**Issue by shanguanma** [espnet/espnet#1664]
I test newest Makefile, but I using pytorch 1.1.0， warpctc_pytorch can't install successfully.
My environment is as follow:
CentOS Linux 7
gcc: 5.2.0
PYTHON_VERSION = 3.7.3
CUPY_VERSION = 6.0.0
CUDA_VERSION = 10.0

**Comment by sw005320** [comment]
We do support the pytorch1.1.0 warpctc (see https://github.com/espnet/warp-ctc#for-pytorch-10-or-11). Could you give us more information?

**Comment by Fhrozen** [comment]
The problem is that warpctc is installed assuming  pytorch 1.0.1:
https://github.com/espnet/espnet/blob/9e2bfc5cdecbb8846f5c6cb26d22010b06e98c40/tools/Makefile#L90-L92
for pytorch 1.1.0 modify: `warpctc-pytorch10` to `warpctc-pytorch11`

**Comment by shanguanma** [comment]
@sw005320  @Fhrozen . Thank you for your reply. According to your suggestion,I modified warpctc-pytorch10 to warpctc-pytorch11. I just re-installed  espnet again. Now warpctc_pytorch works. Thank you for the help.
