### ISSUE TITLE
TTS evaluation metrics

### ISSUE THREAD

**Issue by sw005320** [espnet/espnet#1665]
The VCC'20 recipe is getting a good shape (#1641), and I think it's good time to discuss about the TTS evaluation metrics (this was partly discussed in https://github.com/espnet/espnet/issues/1329 already).

- [ ] ASR token error rate evaluation (both or either of CTC and Attention)
- [ ] spectral objective measure (e.g. RMSE, CD)
- [ ] [deepSpeechDistances](https://github.com/mbinkowski/DeepSpeechDistances)
- [ ] subjective evaluation instruction

My experience is that the above objective measures really help us to see what happened in the TTS algorithms in addition to listening to actual audios.
Are there any other objective measures?
Please let me know if someone is interested in this project.

**Comment by kan-bayashi** [comment]
An interesting measure is DeepSpeechDistances. 
https://github.com/mbinkowski/DeepSpeechDistances
We can use our pretrained model to calculate this measure.

**Comment by unilight** [comment]
> * [ ]  Add spectral objective measure (e.g. RMSE, CD)

In VC we often measure MelCD and we already have a script for calculating it. I can help with it.

**Comment by sw005320** [comment]
Many thanks.
I think the VCC recipe would be a good test case to implement such measures.
We can make some actions after the baseline is finished.
