### ISSUE TITLE
librispeech feature extraction details

### ISSUE THREAD

**Issue by xinqipony** [espnet/espnet#1668]
hi @sw005320 , @b-flo 
I am trying to finding out the  window length, hop_length, time stride, etc of the librispeech feature 

is this the right doc?
https://github.com/espnet/espnet/blob/master/egs/chime4/asr1_multich/conf/preprocess.json

thx

**Comment by sw005320** [comment]
Librispeech feature extraction is based on Kaldi.
So, please change https://github.com/espnet/espnet/blob/master/egs/librispeech/asr1/conf/fbank.conf
(Please check the Kaldi documentation for the configuration).
