### ISSUE TITLE
Guided attention and spectrogram conversion

### ISSUE THREAD

**Issue by anushaprakash90** [espnet/espnet#1670]
Hi,

I have a couple of queries:
1) Does guided attention constrain the attention weights to be almost diagonal (as given in this paper: http://150.162.46.34:8080/icassp2018/ICASSP18_USB/pdfs/0004784.pdf)? Or do you also include knowledge about (HMM) alignments?
2) Do you have any recipe for spectrogram-to-spectrogram conversion (as in the case of voice conversion with parallel data) ?

Thanks

**Comment by kan-bayashi** [comment]
Hi @anushaprakash90. I will answer your question.

1. Does guided attention constrain the attention weights to be almost diagonal (as given in this paper: http://150.162.46.34:8080/icassp2018/ICASSP18_USB/pdfs/0004784.pdf)? Or do you also include knowledge about (HMM) alignments?

We use the former one. We do not use HMM-alignment information.

2. Do you have any recipe for spectrogram-to-spectrogram conversion (as in the case of voice conversion with parallel data) ?

We do not support voice conversion with parallel data. 
But now we are constructing ASR-TTS-based voice conversion with non-parallel data. If you are interested in it, please check #1641.

**Comment by kan-bayashi** [comment]
@anushaprakash90 I will close this issue. If you have an additional questions, please re-open this issue.

**Comment by anushaprakash90** [comment]
@kan-bayashi Thanks. That answers my questions.
