### ISSUE TITLE
The CMVN transform is different between Kaldi and espnet

### ISSUE THREAD

**Issue by bob80333** [espnet/espnet#1671]
When using a Tacotron2 model I trained, I noticed that the espnet implementation of CMVN differs from Kaldi's implementation.  Specifically, Kaldi scales before biasing, and espnet biases before scaling. Is there some advantage to doing it the way espnet does it, instead of the way Kaldi does it?

**Comment by kamo-naoyuki** [comment]
In my memory tts recipe uses kaldi's cmvn, doesn't it @kan-bayashi ?
Anyway,  kaldi does equal operation to  `(x - mean) / std`:

https://github.com/kaldi-asr/kaldi/blob/c78875a685b8bf5907b5eeb49fc958e6dd44f436/src/transform/cmvn.cc#L92-L115

What kaldi does is:

```python
scale = 1 / std
offset = - scale * mean
return scale * x + offset   # = (x - mean) / std
```

**Comment by kan-bayashi** [comment]
Right. We use kaldi's method as the same as ASR.
https://github.com/espnet/espnet/blob/94a066e7b669f5e78be6aba5863255d0a1a2d44e/egs/ljspeech/tts1/run.sh#L118-L127

@bob80333 Which part do you mean?

**Comment by bob80333** [comment]
https://github.com/espnet/espnet/blob/master/espnet/transform/cmvn.py and https://github.com/espnet/espnet/blob/master/utils/apply-cmvn.py are espnet's versions of kaldi's tools was my assumption.

**Comment by kan-bayashi** [comment]
As @kamo-naoyuki shown, the operation is equal to kaldi operation. I will close this issue.
