### ISSUE TITLE
transformer model with pure ctc loss doesnot convergence

### ISSUE THREAD

**Issue by WanderingSven** [espnet/espnet#1673]
In order to use ctc loss only, I change ctc-weight and mtlalpha to one. And I use the following configuration，but I find it doesn't convergence.
![图片](https://user-images.githubusercontent.com/26950286/76677181-4adc2600-6606-11ea-9b9f-acd5b018f622.png)
![图片](https://user-images.githubusercontent.com/26950286/76677190-66473100-6606-11ea-9f1b-cd8b15deb6d9.png)

**Comment by Fhrozen** [comment]
Do you mind giving some information about the recipe you are using?. And also the output from exp/train**/results/train.log These two would be useful.

**Comment by WanderingSven** [comment]
ok, thanks. I am using librispeech recipe.


[train.log](https://github.com/espnet/espnet/files/4332630/train.log)

**Comment by WanderingSven** [comment]
@Fhrozen

**Comment by sw005320** [comment]
Your warp CTC may not be correctly installed.
Please check it or use the pytorch default ctc by with `--ctc_type builtin`

**Comment by WanderingSven** [comment]
Thanks for your reply . I used existing python for the installation and Check that all libraries are installed correctly. I find pure transorfomer without ctc loss also doesn't  convergence.In the previous use of espnet, it can convergence without using existing python  installation.
@sw005320 
![%%L_UV87E%H6JDH4$(9REG3](https://user-images.githubusercontent.com/26950286/76816185-924af800-683a-11ea-9661-644450198133.png)
![9_8S5NSJ$W 791SPHDKWZ_6](https://user-images.githubusercontent.com/26950286/76816381-0daca980-683b-11ea-812e-43844dda19ca.png)

**Comment by sw005320** [comment]
This looks very strange. 
Please check your experimental configurations again.

**Comment by ZhihaoDU** [comment]
I also meet this strange problem, the model can't converge with pure transformer when I set ctc_weight to 0.0. My espnet version is 0.10.7a1. 

When I set ctc_weight to 0.3, I get a log like this:
2023-07-13 10:32:28,061 (trainer:830) INFO: 24epoch:train:601-650batch: iter_time=1.51197e-04, forward_time=0.42818, loss_ctc=27.37509, loss_att=13.84451, acc=0.91709, loss=17.90368, backward_time=0.68019, optim_step_time=0.02077, optim0_lr0=0.00176, train_time=1.17830

However, if I set ctc_weight to 0.3 and keep other unchanged, I get a log like this:
2023-07-13 10:33:25,246 (trainer:830) INFO: 25epoch:train:301-350batch: iter_time=1.26404e-04, forward_time=0.41919, loss_att=139.18309, acc=0.30748, loss=139.18309, backward_time=0.66811, optim_step_time=0.02073, optim0_lr0=0.00173, train_time=1.15287

Do you have any ideas ?
