### ISSUE TITLE
Error while loading pre-trained model

### ISSUE THREAD

**Issue by Arafat4341** [espnet/espnet#1679]
I installed docker image of espnet and kaldi. kaldi inside the `espnet/tools/` directory.
I wanted to synthesize an example text with pre-trained models. I followed the instructions.

while downloading the pre-trained model I get this error: 

`gzip: stdin: not in gzip format`

`tar: Child returned status 1`

`tar: Error is not recoverable: exiting now`

`/home/arafat/espnet/egs/ljspeech/tts1/../../../utils/download_from_google_drive.sh: line 54: curl: command not found`

How can I get rid of this? Thanks in advance!

**Comment by chris-crucible** [comment]
@Arafat4341 I just ran into this myself. Did you solve it? What was the issue?

**Comment by chris-crucible** [comment]
I just switched the download_from_google_drive.sh to use wget instead of curl, but not sure why curl is unavailable in the image as it seems like it's listed in the base Dockerfile install.

**Comment by Arafat4341** [comment]
@chris-crucible curl was not installed. I also wonder why!

**Comment by sunnybala** [comment]
Having the same issue here with both of you. Another way to do the same thing if you don't want to swap out wget is to start the docker container in interactive mode as root and install it:

> apt-get update
> apt-get install curl

but it's odd that it's not installed by default in the image.
