### ISSUE TITLE
Espnet Module missing

### ISSUE THREAD

**Issue by Arafat4341** [espnet/espnet#1680]
I ran docker image of espnet and kaldi. Immediately after I tried to synthesize example text with pre-trained models. I tried the command:
`../../../utils/synth_wav.sh example.txt`

I get this error:
`  File "/home/arafat/espnet/egs/ljspeech/tts1/../../../utils/merge_scp2json.py", line 15, in <module>`
    `from espnet.utils.cli_utils import get_commandline_args`
`ModuleNotFoundError: No module named 'espnet'`

Where can I get espnet.py module? Why am I still getting this module missing errors even after installing docker image of espnet?

**Comment by Fhrozen** [comment]
How are you running the docker container? using run.sh? or with docker run?
In case of using the second option, then I recommend you to check the file [runs.h](https://github.com/espnet/espnet/blob/master/docker/run.sh)

Specially the following lines:
https://github.com/espnet/espnet/blob/45183b7f8160ee19a31f444d6ed1cc491371acd1/docker/run.sh#L117-L124

the original espnet folder is deleted from the container so you need to mount with the folders espnet, utils, and so on. 
Let me know if there is any problem later with the folder mounting.

**Comment by Arafat4341** [comment]
@Fhrozen I am running docker container for espnet with:
`./run.sh --docker_gpu -1 --docker_egs an4/asr1   --docker_user false  --ngpu 0`

By the way, I have an espnet folder inside `espnet/`. Will copying the `espnet` folder inside `espnet/tools` be good?

**Comment by Arafat4341** [comment]
@Fhrozen that solved the problem.

`Traceback (most recent call last):`
  `File "/home/arafat/espnet/egs/ljspeech/tts1/../../../utils/merge_scp2json.py", line 15, in <module>`
    `from espnet.utils.cli_utils import get_commandline_args`
  `File "/home/arafat/espnet/utils/espnet/utils/cli_utils.py", line 5, in <module>`
    `import numpy`
`ModuleNotFoundError: No module named 'numpy'`

Am I supposed to get this error? Why these basic packages are missing?!

**Comment by Fhrozen** [comment]
If you are using the docker container, then you should not have these errors. 
This last shows that the program is not loading the python env (conda) and is using the python from /usr/bin. I will try to check but when I did test I did not have any of these errors.
Not sure if it is related to root users or something like that

**Comment by Fhrozen** [comment]
I tested
```
./run.sh --docker_gpu -1 --docker_egs an4/asr1 --docker_user false --ngpu 0
```
In my computer, and have no problem. Can you test the same command in a personal PC. If I can remember you were using AWS. so not sure exactly where is the error. (But if is docker then it should not have any problem)

**Comment by Arafat4341** [comment]
@Fhrozen Thanks for your kind response!
I am using virtual ubuntu machine on my pc. 
In that case, was the docker not properly installed?

**Comment by Fhrozen** [comment]
> was the docker not properly installed?

I cannot be sure if it is the docker installation.  But, the error is quite strange .

> what troubles do root user cause?

Usually are folder access.

Anyway, can you try running `./build.sh test`. This will test the docker containers.

**Comment by Arafat4341** [comment]
Ran `./build.sh test` . Got this:

`Using Docker Ver.19.03.6
Testing docker containers
Building docker image...`
`Now running docker build --build-arg FROM_TAG=cpu-u18 --build-arg THIS_USER=arafat --build-arg THIS_UID=0 -f prebuilt/Dockerfile -t espnet/espnet:cpu-u18-user-arafat .`
`Sending build context to Docker daemon  51.71kB`
`Step 1/8 : ARG FROM_TAG`
`Step 2/8 : FROM espnet/espnet:${FROM_TAG}`
 `---> 7b32166ab6ab`
`Step 3/8 : LABEL maintainer "Nelson Yalta <nyalta21@gmail.com>"`
 `---> Using cache`
 `---> 6fc98c5ec376`
`Step 4/8 : ARG THIS_USER`
 `---> Using cache`
 `---> 16cb841bf90f`
`Step 5/8 : ARG THIS_UID`
 `---> Using cache`
 `---> 12f84ab272fc`
`Step 6/8 : RUN if [ ! -z "${THIS_UID}"  ]; then     useradd -m -r -u ${THIS_UID} -g root ${THIS_USER};     fi`
` ---> Running in 5313f898373f`
`useradd: UID 0 is not unique`
`The command '/bin/sh -c if [ ! -z "${THIS_UID}"  ]; then     useradd -m -r -u ${THIS_UID} -g root ${THIS_USER};     fi' returned a non-zero code: 4`
