### ISSUE TITLE
How to change backbond to RNN-T?

### ISSUE THREAD

**Issue by xiechen0692** [espnet/espnet#1682]
I can not find the tutorial on the main page. Can someone share how to use it and the performance results? Thanks a lot!

**Comment by sw005320** [comment]
Thanks for your comment.
You could find some examples and results in `egs/vivos/asr1/RESULTS.md` `egs/voxforge/asr1/run_rnnt.sh`, 
 
@b-flo, I think this is a good idea to put more detailed documentation about examples and results somewhere in the main `README.md`. Could you think of it?

**Comment by b-flo** [comment]
Hi,

Thank you for your interest and sorry for the lack of information! I'll add some documentation to highlight current results and usage for transducer when I have time, you can take a look at voxforge and vivos recipes for now as shinji said. I'm currently too busy to work on it right now, my apologies.

**Comment by xiechen0692** [comment]
> Thanks for your comment.
> You could find some examples and results in `egs/vivos/asr1/RESULTS.md` `egs/voxforge/asr1/run_rnnt.sh`,
> 
> @b-flo, I think this is a good idea to put more detailed documentation about examples and results somewhere in the main `README.md`. Could you think of it?

thanks you guys, is it available for other dataset?

**Comment by b-flo** [comment]
Yes, transducer is available for any dataset! You just need to have `model-module: "espnet.nets.pytorch_backend.e2e_asr_transducer:E2E"` in your config. However be aware there are some differences in terms of training and decoding parameters between MTL and transducer!
