### ISSUE TITLE
`venv/bin/activate` directory missing from `tools/`

### ISSUE THREAD

**Issue by Arafat4341** [espnet/espnet#1683]
I wanted to synthesize example text with pre-trained model after I ran docker image of espnet on my virtual ubuntu machine.
I get the following issue:
`./path.sh: line 12: /home/arafat/espnet/egs/ljspeech/tts1/../../../tools/venv/bin/activate: No such file or directory`
`stage 0: Data preparation`
`/home/arafat/espnet/egs/ljspeech/tts1/../../../utils/data2json.sh --trans_type char decode/example/data decode/download/ljspeech.transformer.v1/data/lang_1char/train_no_dev_units.txt`
`./path.sh: line 12: /home/arafat/espnet/egs/ljspeech/tts1/../../../tools/venv/bin/activate: No such file or directory`
`stage 2: Decoding`
`run.pl: job failed, log is in decode/example/log/decode.log`

Why is `venv/` folder missing inside `espnet/tools/`. Why is it not there? How can I get this?

**Comment by Fhrozen** [comment]
As I can see, you are no running the program inside the docker container.
First. espnet folder is located at `/espnet` inside the docker container, and when a recipe is execute, it runs in `/espnet/egs/<recipe>` in this case <recipe>= ljspeech. It seems that it is executed outside the docker container that is why you have `/home/arafat` in the output.

Could you please copy the command you are using that the whole output. I want to check why is not running docker.
