### ISSUE TITLE
TTS long sentence inference alignment

### ISSUE THREAD

**Issue by Ella77** [espnet/espnet#1696]
First of all, thank you for great and well arranged repository friendly for developers.

I am working on doing my own recipe using Korean TTS Fastspeech distilled from Transformer.v.3, Tacotron2 based on LJSpeech. Inferred results from sentence of normal lengths sound Ok, but as my dataset's wav length averaged about 3 seconds, long sentence inference sounds bad at the end of the statement. 

I have done experiments learned from [past issues.](https://github.com/espnet/espnet/issues/1360)
Adding some trimmings, configuring pos-weight and revising some decode config really helps, but I still have difficulty on long sentences. 

I came up with some augmentation method like making longer wav files combining existing datas but training speed lowered , and not sure about it's consequences. so I want to ask some advice for this issue. 

Wait for help and I'd be happy if I can contribute. 🙇‍♀ 

1) Does augmentation(or simply..:( combining) of existing data work in that it learns some longer alignments?
2) I heard that alignments improve better than distilled transformer model after training in paper, but can't see any dramatic improvement in my experiments.  
3) I saw [experimental PR for asr]( https://github.com/espnet/espnet/pull/1599) regarding location relative attention and dynamic convolution by google. I know it is experimental, but it might be solution for longer sentence as shown by google, so I have a plan for adjusting to tts. Any advice for this or plan for tts?

**Comment by sw005320** [comment]
I just would like to make sure what is an issue.
Is your long sentence example working with c.v.3 and Tacotron2?
If you still have some issues with Transformer but OK with Tacotron2, we could conclude that the problem comes from the self-attention and https://github.com/espnet/espnet/pull/1599 would be a good solution.

**Comment by kan-bayashi** [comment]
Hi @Ella77, thank you for raising interesting discussions.

> Does augmentation(or simply..:( combining) of existing data work in that it learns some longer alignments?

I have no experience data augmentation for TTS, especially in terms of long sentence generation. I tried several attention mechanisms, but the most effective one is attention constraint in decoding, which is introduced in Deep Speech 3. Did you try it?  (only available for Tacotron2)

> I heard that alignments improve better than distilled transformer model after training in paper, but can't see any dramatic improvement in my experiments.

Could you provide more information about this? Which paper do you mean? 

> I saw experimental PR for asr regarding location relative attention and dynamic convolution by google. I know it is experimental, but it might be solution for longer sentence as shown by google, so I have a plan for adjusting to tts. Any advice for this or plan for tts?

Yeah, it is nice to implement [Dynamic convolution attention](https://arxiv.org/abs/1910.10288), which can solve this issue for Tacotron 2. We will consider to implement it.

**Comment by Ella77** [comment]
experiment results 

> 1. Does augmentation(or simply..:( combining) of existing data work in that it learns some longer alignments?
-> for transformer, alignment gets better by combining data. 
> 2. I heard that alignments improve better than distilled transformer model after training in paper, but can't see any dramatic improvement in my experiments.
-> alignment gets little better when using attention constraint 
> 3. I saw [experimental PR for asr](https://github.com/espnet/espnet/pull/1599) regarding location relative attention and dynamic convolution by google. I know it is experimental, but it might be solution for longer sentence as shown by google, so I have a plan for adjusting to tts. Any advice for this or plan for tts?
-> I tried hard with transformer to align well on any long sentence but tacotron2 v3 works for any long sentence!

**Comment by kan-bayashi** [comment]
Thank you for sharing your experiments!
That is very useful.

> I tried hard with transformer to align well on any long sentence but tacotron2 v3 works for any long sentence!

So, your conclusion is that for long sentences, tacotron2 is better than transformer?
