### ISSUE TITLE
Python version conflict

### ISSUE THREAD

**Issue by Arafat4341** [espnet/espnet#1697]
While installing kaldi, I see python 2.7 as a requirement. When I ran extras/check_dependencies.sh in kaldi, I noticed python 2.7 as on of the required package. 
But the machine has also python 3. 
Now when I run `python --version`, machine doesn't recognize the command. And it tells to install python. But `python3 --version` or `python2.7 --version` works.

Which one should I set as default python??

**Comment by sw005320** [comment]
Please use Python 3.6.1+
See https://espnet.github.io/espnet/installation.html#requirements
