### ISSUE TITLE
time stamp per word

### ISSUE THREAD

**Issue by desothier1** [espnet/espnet#1702]
Hi,

Is there a way to have the time stamps at word boundary level
for reference and hypothesis transcriptions ?

Thanks

**Comment by sw005320** [comment]
It is not easy to get the word boundary level, but the token level is possible if we check the attention weight (or probably CTC results). We will think of implementing such functions upon the request.

**Comment by desothier1** [comment]
Ok, I can do with token level.
would it be ok, to give some advice about which script or which function to
use to extract time stamps per word for CTC?

Thanks

**Comment by sw005320** [comment]
I think it is possible if we take the best path from CTC prefix in https://github.com/espnet/espnet/blob/master/espnet/nets/ctc_prefix_score.py#L197 (but still token level).

**Comment by desothier1** [comment]
thanks!
