### ISSUE TITLE
how derease speed of speech

### ISSUE THREAD

**Issue by jamesMuWB** [espnet/espnet#1708]
i used  tts script synth_wav.sh synthesis a wav, but speed of speech is to fast.

how derease the speed

**Comment by GreenGarnets** [comment]
I had the same problem as this. This problem is related to sampleRate. The sampleRate should be adjusted to 22040 or 24000 to relearn and output the results.

**Comment by kan-bayashi** [comment]
Now we can control the speed with FastSpeech.
