### ISSUE TITLE
Processing of audio folder to convert data format to ESPNET2

### ISSUE THREAD

**Issue by SeanNaren** [espnet/espnet#1709]
Hey guys!

After speaking to Shinji who pointed me to a few issues it seems ESPNET2 is kaldi-free which is awesome! Still uses the kaldi format which is a good idea.

We currently use a simple file structure to hold our data. Basically a folder with a /wav /txt directory where the filenames match inside except for the extension. This is also the chosen format for [deepspeech.pytorch](https://github.com/SeanNaren/deepspeech.pytorch#custom-dataset).

For ASR what would be the easiest way to take this format and convert it into what is needed for ESPNET2? I had a look at the example script [here](https://github.com/espnet/espnet/blob/v.0.7.0/egs2/TEMPLATE/asr1/asr.sh) however I'm still unsure what the folder/data structure looks like, any information would be appreciated!

**Comment by kamo-naoyuki** [comment]
Hi, @SeanNaren 

I recommend you to run `egs2/mini_an4/asr1` once and I believe you can understand what is required quickly

You need to prepare two text files at least, referred as `scp` to describe the file id and the file path or the transcription (that are almost same as Kaldi format)

```
sample_id_1 /some/where/a.wav
sample_id_2 /some/where/b.wav
```

(We use soundfile to read audiofile, so not only wav format, all format which it supports can be also used. e.g. flac)

```
sample_id_1 hello world
sample_id_2  abc def
```

Note that there are no assumption about directory structure.

https://github.com/espnet/espnet/blob/8f3a0ff172dac2cb887878cda42a918737df8b91/egs2/TEMPLATE/asr1/asr.sh#L751-L776

You can also use the format other than `sound`, `text` and `kaldi_ark`, e.g. `npy`, `hdf5` by specifying it in `--train_data_path_and_name_and_type`.

**Comment by SeanNaren** [comment]
Perfect thank you! This is exactly what I wanted :) will close
