### ISSUE TITLE
GPU config without CudNN possible? 

### ISSUE THREAD

**Issue by LightTemplar** [espnet/espnet#1715]
I've got an old NVIDIA Tesla M2090, which can be used with Cuda 9.1 and r390 drivers, but it doesn't support CudNN at all. Can ESPnet still use it for speech recognition tasks?

**Comment by b-flo** [comment]
Hi,

Can pytorch be used without cudNN enabled? Yes, if not detected cudnn wrappers will be switched off. For espnet, cudnn is a requirement and there are multiple direct references/tests to it so I'm not really sure if it could work without modifications.

By the way I don't think using a GPU with a compute capability of 2.0 like yours would be better over using CPUs.
