### ISSUE TITLE
errro by running run.sh : /home/ai/espnet/egs/ljspeech/tts1/../../../tools/kaldi/tools/config/common_path.sh is not present

### ISSUE THREAD

**Issue by ohadianoush** [espnet/espnet#1716]
hi,

~/espnet/egs/ljspeech/tts1$ ./run.sh --backend chainer
The standard file /home/ai/espnet/egs/ljspeech/tts1/../../../tools/kaldi/tools/config/common_path.sh is not present -> Exit!

note1:both of kaldi & espnet is in home directory (/home/ai/ )ai is my username

note2: first lines of path.sh file:
MAIN_ROOT=$PWD/../../..
KALDI_ROOT=$MAIN_ROOT/tools/kaldi

note3: i do all step from https://espnet.github.io/espnet/installation.html

**Comment by b-flo** [comment]
Hi,

You didn't have any error at `Step 4) installation check`?

> note2: first lines of path.sh file:
> MAIN_ROOT=$PWD/../../..
> KALDI_ROOT=$MAIN_ROOT/tools/kaldi

The paths are correct.

> note1:both of kaldi & espnet is in home directory (/home/ai/ )ai is my username

Do you have a symbolic link to your kaldi directory in `espnet/tools` (`kaldi -> /home/ai/kaldi/`)?
