### ISSUE TITLE
Need help to analyze the results

### ISSUE THREAD

**Issue by brijmohan** [espnet/espnet#172]
Hi,

I am trying to optimize the MTL architecture for my data. I need help to analyze the errors made by the model. I wish to generate alignment between characters and acoustic frames as depicted in [this](https://arxiv.org/pdf/1609.06773.pdf) paper on page 4.

Can I use `att_c` and `att_w` variables [here](https://github.com/espnet/espnet/blob/master/src/nets/e2e_asr_attctc.py#L694) to generate these plots?

I will be grateful for any guidance.

Thanks in advance!

**Comment by sw005320** [comment]
Yes, `att_w` is an attention weight for each output time, and you can produce the alignments in the paper by simply  (2d) plotting `att_w` for all output time. We initially prepared such functions, but deleted it for some reason. It is great if you implement it and put a PR about it.

**Comment by kan-bayashi** [comment]
I implemented attention visualization function (#202).

**Comment by brijmohan** [comment]
Thanks @kan-bayashi :)
