### ISSUE TITLE
ASR demo with wsj_mix dataset

### ISSUE THREAD

**Issue by jujusudhur** [espnet/espnet#1721]
References to do ASR demo using wsj_mix dataset. Getting error in Data Preparation stage while following steps from ASR demo with an4 dataset in interspeech tutorial.

**Comment by sw005320** [comment]
wsj_mix dataset has special ways for data preparation because it requires multiple references. Please follow the data preparation in the wsj_mix recipe. Also, the Interspeech tutorial is not intended for the multispeaker case.

**Comment by jujusudhur** [comment]
![Screenshot from 2020-03-23 22-21-36](https://user-images.githubusercontent.com/18646215/77346440-3f9e9e00-6d5c-11ea-89e6-fb3c9ecf314f.png)

Getting this error while running wsj_mix recipe ./run.sh at Stage 0 - Data Preparation

**Comment by sw005320** [comment]
Do you have the WSJ data?
Then, you have to set the path of your WSJ data correctly instead of `/export/corpora/...`

**Comment by jujusudhur** [comment]
WSJ data needs license. I don't have. Are there any alternative?

**Comment by sw005320** [comment]
No.
It would be better to make it by yourself by following the wsj_mix data preparation.
We're creating the librispeech mixture data but it will not be finished soon.
