### ISSUE TITLE
pyopenjtalk error - TTS on Japanese

### ISSUE THREAD

**Issue by Arafat4341** [espnet/espnet#1722]
I am trying to test TTS on Japanese text. The pyopenjtalk is missing. I am inside virtual environment.
I tried `pip install pyopenjtalk`. Got `OSError: openjtalk library cannot be found`

Tried to install openjtalk with `sudo apt-get install open-jtalk open-jtalk-mecab-naist-jdic hts-voice-nitech-jp-atr503-m001`.
It gets installed. Then I ran again `pip installed pyopenjtalk`. I get same error: `OSError: openjtalk library cannot be found`

Can anyone tell me what is the appropriate way to install pyopenjtalk?
Thanks in advance!

**Comment by b-flo** [comment]
Hi,

I never used it so someone correct me if I'm wrong, but searching for `pyopenjtalk` leads to:

```
    echo "Error: pyopenjtalk is not installed." >&2
    echo "Error: please install pyopenjtalk and its dependencies as follows:" >&2
    echo "Error: cd ${MAIN_ROOT}/tools && make pyopenjtalk.done" >&2
```

`${MAIN_ROOT}` being espnet directory.
