### ISSUE TITLE
An issue related to "train_iter/valid_iter" from asr/pytorch_backend/asr.py

### ISSUE THREAD

**Issue by simpleoier** [espnet/espnet#1726]
Start from the ESPnet v.0.6.0, data loader was modified as a dictionary.
```
    train_iter = {'main': ChainerDataLoader(
        dataset=TransformDataset(train, lambda data: converter([load_tr(data)])),
        batch_size=1, num_workers=args.n_iter_processes,
        shuffle=not use_sortagrad, collate_fn=lambda x: x[0])}
    valid_iter = {'main': ChainerDataLoader(
        dataset=TransformDataset(valid, lambda data: converter([load_cv(data)])),
        batch_size=1, shuffle=False, collate_fn=lambda x: x[0],
        num_workers=args.n_iter_processes)}
```
This modification is incompatible with some functions, such as the `sortagrad` and the preprocessing functions for STFT features in ASR task due to the `converter([load_tr(data)])`.
E.g.
```
if use_sortagrad:
        trainer.extend(ShufflingEnabler([train_iter]),
                       trigger=(args.sortagrad if args.sortagrad != -1 else args.epochs, 'epoch'))
```

**Comment by sw005320** [comment]
@naxingyu, could you take a look at it? This causes a problem in several places including #1672 and I also got a report about this issue from the others.

**Comment by bobchennan** [comment]
In #1138 I did't check sortagrad cases since I didn't find any cases using sortagrad.

Let me fix it.

**Comment by bobchennan** [comment]
The problem is that we define iterator as a dictionary as mentioned in https://docs.chainer.org/en/stable/reference/generated/chainer.training.updaters.StandardUpdater.html :
`iterator – Dataset iterator for the training dataset. It can also be a dictionary that maps strings to iterators. If this is just an iterator, then the iterator is registered by the name 'main'.`

So maybe I should define dictionary only for updater.

**Comment by sw005320** [comment]
> The problem is that we define iterator as a dictionary as mentioned in https://docs.chainer.org/en/stable/reference/generated/chainer.training.updaters.StandardUpdater.html :
> `iterator – Dataset iterator for the training dataset. It can also be a dictionary that maps strings to iterators. If this is just an iterator, then the iterator is registered by the name 'main'.`
> 
> So maybe I should define dictionary only for updater.

Year, I think it would be better.
We have another report in #1672, so it would be great if you work on it soon.
