### ISSUE TITLE
TTS issue: All OOV instances gets replaced with 1

### ISSUE THREAD

**Issue by Arafat4341** [espnet/espnet#1727]
I am trying to test pre-trained `jsut.tacotron2.v1` and `jsut.molgan.mol.v1` on Japanese text. I get very poor synthesized audio. 
I noticed in Data Preparation Stage, All of the Japanese characters of the input text gets replaced by 1.
I don't know whats going on! I also tried to synthesize English text. English input text with all caps does okay but with small letters it does the same thing. All characters gets replaced by 1.

How can I get better performance?

**Comment by kan-bayashi** [comment]
Sorry, `synthesis_wav.sh` does not include text cleaning part.
Please try our colab notebook.
https://colab.research.google.com/github/espnet/notebook/blob/master/tts_realtime_demo.ipynb

**Comment by Arafat4341** [comment]
@kan-bayashi I tried colab notebook Its works fine! 
I tried to setup espnet in my local machine the same approach like colab notebook. I got it right for English Synthesis.
But for Japanese Synthesis, I am getting `ImportError: libopenjtalk.so.1.10: cannot open shared object file: No such file or directory` .
Though openjtalk is installed. 

I noticed in the colab notebook in "Install Japanese dependencies" section:
`cp tools/open_jtalk/src/build/*.so* /usr/lib64-nvidia`. It copies the .shared object files to the /usr/lib64-nvidia/ directory. I commented out the line and ran, I get same error as I am getting in my local machine: `ImportError: libopenjtalk.so.1.10: cannot open shared object file: No such file or directory`.

Can you kindly tell me what is equivalent to /usr/lib64-nvidia/ in a local ubuntu machine?
I have no GPU and I am running python with virtual environment.

**Comment by Arafat4341** [comment]
Solved the problem!
