### ISSUE TITLE
TTS - RAM keep increasing in inference 

### ISSUE THREAD

**Issue by dzungcamlang** [espnet/espnet#1740]
Hi all,
I had try this [demo](https://colab.research.google.com/github/espnet/notebook/blob/master/tts_realtime_demo.ipynb#scrollTo=3lMJyJcLCsd4) and when I synthesize on CPU with multiple sentence, I encountering ram increases every iteration and out memory.
This code like this:

```python
trans_type = "char"
dict_path = "tts_checkpoint/train_nodev_trim_units.txt"
model_path = "tts_checkpoint/model.loss.best"
vocoder_path = 'tts_checkpoint/checkpoint-360000steps.pkl'
vocoder_conf = 'tts_checkpoint/config.yml'
# define dependencies
import re
import numpy as np

# define E2E-TTS model
from argparse import Namespace
from espnet.asr.asr_utils import get_model_conf
from espnet.asr.asr_utils import torch_load
from espnet.utils.dynamic_import import dynamic_import
idim, odim, train_args = get_model_conf(model_path)
model_class = dynamic_import(train_args.model_module)
model = model_class(idim, odim, train_args)
torch_load(model_path, model)
model = model.eval().to(device)
inference_args = Namespace(**{"threshold": 0.5, "minlenratio": 0.0, "maxlenratio": 10.0})

# define neural vocoder
import yaml
import parallel_wavegan.models

with open(vocoder_conf) as f:
    config = yaml.load(f, Loader=yaml.Loader)
vocoder_class = config.get("generator_type", "ParallelWaveGANGenerator")
vocoder = getattr(parallel_wavegan.models, vocoder_class)(**config["generator_params"])
vocoder.load_state_dict(torch.load(vocoder_path, map_location="cpu")["model"]["generator"])
vocoder.remove_weight_norm()
vocoder = vocoder.eval().to(device)

# define text frontend
with open(dict_path) as f:
    lines = f.readlines()
lines = [line.replace("\n", "").split(" ") for line in lines]
char_to_id = {c: int(i) for c, i in lines}

def frontend(text):
    """Clean text and then convert to id sequence."""
    text = text.lower()
    text = cleaner(text).do()
    charseq = list(text)
    idseq = []
    for c in charseq:
        if c.isspace():
            idseq += [char_to_id["<space>"]]
        elif c not in char_to_id.keys():
            idseq += [char_to_id["<unk>"]]
        else:
            idseq += [char_to_id[c]]
    idseq += [idim - 1]  # <eos>
    return torch.LongTensor(idseq).view(-1).to(device)

def generate(input_text):
    with torch.no_grad():
        pad_fn = torch.nn.ReplicationPad1d(
            config["generator_params"].get("aux_context_window", 0))
        use_noise_input = vocoder_class == "ParallelWaveGANGenerator"
        x = frontend(input_text)
        c, _, _ = model.inference(x, inference_args)
        c = pad_fn(c.unsqueeze(0).transpose(2, 1)).to(device)
        xx = (c,)
        if use_noise_input:
            z_size = (1, 1, (c.size(2) - sum(pad_fn.padding)) * config["hop_size"])
            z = torch.randn(z_size).to(device)
            xx = (z,) + xx
        y = vocoder(*xx).view(-1)
        return y
```
Any help would be very much appreciated.
Thanks.

**Comment by windtoker** [comment]
Did you try gc.collect?

**Comment by dzungcamlang** [comment]
Not yet FIXED, 
I could found that, `y = vocoder(*xx).view(-1)` increase RAM ever step mel to audio,  when I try TTS split into two part, the first is text to mel and the second is mel to audio, the process mel to audio has consume multiple memory ram.
@kan-bayashi can you help me part vocoder?
Thanks...

**Comment by kan-bayashi** [comment]
@dzungcamlang Do you mean CPU memory?

**Comment by dzungcamlang** [comment]
@kan-bayashi  yes, i tried on cpu, When I synthesized multi sentence and  vocoder has occupied memory after returning the result, and I has try again synthesize encountering RAM (cpu) load full...
code I modified on your [demo](https://colab.research.google.com/github/espnet/notebook/blob/master/tts_realtime_demo.ipynb#scrollTo=3lMJyJcLCsd4) and same is [repo](https://github.com/NaoyaTAKIMOTO/auto-singer-songwriter/tree/40bb0f6d9b7d3aa34d24541de3852944a3b3de65/voice/src)
thanks you fast response for me...

**Comment by dzungcamlang** [comment]
@kan-bayashi can you help me, 
Thanks.

**Comment by kan-bayashi** [comment]
Hmm, I've never met your problem.
Is your problem happened even when using the same sentence multiple times?
e.g.
```
input_text = "This is a test."
for i in range(1000):
    generate(input_text)
```
What is the your pytorch version? Is your problem happened with different version?

Since the `vocoder.forward()` function just calls pytorch the methods such as Conv1d, I have no idea about the memory consumption.

**Comment by dzungcamlang** [comment]
Can you give me your email, I will send you my source, sorry I can't publish.
Thanks.

**Comment by kan-bayashi** [comment]
Could you answer my questions?

**Comment by dzungcamlang** [comment]
oh, I'm sorry, I don't  using the same sentence multiple times, and I tried on Pytorch 1.4.0, and I don't try with different version.

**Comment by kan-bayashi** [comment]
I want you to check what is happened when using the same sentence multiple times as shown the above in order to find the reason of the problem.

**Comment by dzungcamlang** [comment]
Thanks your suggest, I found the problem is version Pytorch 1.4, when I reinstall pytorch 1.1 everything is ok.
Thanks so much.
