### ISSUE TITLE
Synthesis takes long time (~40 sec for English, much more for Japanese)

### ISSUE THREAD

**Issue by Arafat4341** [espnet/espnet#1749]
I am trying to synthesis English and Japanese text using pre-trained models. I have made an API endpoint with a POST request containing Input text. The API is supposed to respond back to the client with synthesized audio as attachment.

Problem is synthesis takes a long time (~40 sec for English only). I also tried Japanese text synthesis. That takes even longer. Are there any solution to this?
Thanks in advance

**Comment by kan-bayashi** [comment]
It depends on the model type and the length of the inputs.
What kind of the model did you use?
Taco2, Transformer, or FastSpeech?
WaveNet, Parallel WaveGAN, or MelGAN?

**Comment by Arafat4341** [comment]
Transformer
Parallel WaveGAN

**Comment by kan-bayashi** [comment]
Transformer is the slowest model since the calculation cost O(len(input)^2).
If you want to speed up, try taco2 or FastSpeech.
