### ISSUE TITLE
Some questions about the TTS attention alignment

### ISSUE THREAD

**Issue by fly12357** [espnet/espnet#1753]
I trained the Tactron2 based on my own dataset; First, I use the default parameters in the CSMSC recipe. The alignment is:
![image](https://user-images.githubusercontent.com/40494145/78016906-0bd7ff80-737e-11ea-8cf2-355fd5036e2d.png)
Then I do the trim and set the reduction factor to 3, follows the steps mentioned in #1360 .
Then the alignment change to:
![image](https://user-images.githubusercontent.com/40494145/78017127-6bcea600-737e-11ea-8fa1-6ded6698dc9d.png)

I have no idea about the reason why the decoder is much longer than the encoder. I mean, why it is not a Diagonal?

The original wave is :
![image](https://user-images.githubusercontent.com/40494145/78017374-c536d500-737e-11ea-993e-01aec0da1274.png)

![image](https://user-images.githubusercontent.com/40494145/78017382-c9fb8900-737e-11ea-9a49-65cd804d4b15.png)

**Comment by kan-bayashi** [comment]
Sorry, this is a bug of the attention visualization.
Maybe the attention itself is diagonal.

**Comment by fly12357** [comment]
> Sorry, this is a bug of the attention visualization.
> Maybe the attention itself is diagonal.

Thanks for your reply. I'll check the bug of the attention visualization. 
BTW, Is there any length limitation of the input tokens in Tactron2 model?

**Comment by kan-bayashi** [comment]
I think this is also related to the bug of attention plot.
I made patch to fix the plot #1761. 
Please check it.

**Comment by kan-bayashi** [comment]
The patch #1761 does not fix the issue of `reduction_factor`.
We need to cut the decoder index according to the reduction factor but currently it is not performed.
I will make another PR to fix it.

**Comment by fly12357** [comment]
> ~The patch #1761 does not fix the issue of `reduction_factor`.~
> We need to crop the decoder index according to the reduction factor but currently it is not performed.
> ~I will make another PR to fix it.~
> 
> Update:
> I also fixed the issue when reduction_factor > 1 in #1761.

Thanks for your reply. I'll update my code and check the result.
