### ISSUE TITLE
ImportError: libopenjtalk.so.1.10: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by Arafat4341** [espnet/espnet#1756]
Running script to synthesis with Japanese. Getting this error:

`Traceback (most recent call last):`
  `File "jp_setup_all.py", line 38, in <module>`
    `import pyopenjtalk`
  `File "/home/yasin/espnet/tools/pyopenjtalk/pyopenjtalk/__init__.py", line 20, in <module>`
    `from .openjtalk import OpenJTalk`
`ImportError: libopenjtalk.so.1.10: cannot open shared object file: No such file or directory`

What does this mean?

**Comment by kan-bayashi** [comment]
openjtalk is not installed as the log said.
Make sure that you finished the installation.

See also:
https://github.com/espnet/espnet/tree/master/egs/jsut#tts1

**Comment by r9y9** [comment]
The log clearly says what was going wrong there. Please do investigate issues yourself before asking any questions.

Also, if you have a problem about pyopenjtalk, please file an issue to https://github.com/r9y9/pyopenjtalk repository instead.

**Comment by Arafat4341** [comment]
@kan-bayashi @r9y9  I installed openjtalk. 

-- Configuring done
-- Generating done
-- Build files have been written to: /home/yasin/new_espnet/espnet-20200331T011351Z-001/espnet/tools/open_jtalk/src/build
[100%] Built target openjtalk
Install the project...
-- Install configuration: "Release"
-- Up-to-date: /usr/local/lib/libopenjtalk.so.1.10
-- Up-to-date: /usr/local/lib/libopenjtalk.so
-- Up-to-date: /usr/local/include/openjtalk/jpcommon.h
-- Up-to-date: /usr/local/include/openjtalk/mecab.h
-- Up-to-date: /usr/local/include/openjtalk/mecab2njd.h
-- Up-to-date: /usr/local/include/openjtalk/njd.h
-- Up-to-date: /usr/local/include/openjtalk/njd2jpcommon.h
-- Up-to-date: /usr/local/include/openjtalk/njd_set_accent_phrase.h
-- Up-to-date: /usr/local/include/openjtalk/njd_set_accent_type.h
-- Up-to-date: /usr/local/include/openjtalk/njd_set_digit.h
-- Up-to-date: /usr/local/include/openjtalk/njd_set_long_vowel.h
-- Up-to-date: /usr/local/include/openjtalk/njd_set_pronunciation.h
-- Up-to-date: /usr/local/include/openjtalk/njd_set_unvoiced_vowel.h
-- Up-to-date: /usr/local/include/openjtalk/text2mecab.h

But still receiving that error

**Comment by Arafat4341** [comment]
Solved the problem!
I just had to copy *.so* files from openjtalk to usr/lib/
