### ISSUE TITLE
FastSpeech robustness

### ISSUE THREAD

**Issue by qo4on** [espnet/espnet#1759]
Your [FastSpeech model](https://colab.research.google.com/github/espnet/notebook/blob/master/tts_realtime_demo.ipynb) fails to pass [robustness test](https://speechresearch.github.io/fastspeech/) which official microsoft model does.
```
"Http0XX , Http1XX , Http2XX , Http3XX"
```
Why does this happen?

**Comment by kan-bayashi** [comment]
Could you tell me the detail? How failed?
I think the text frontend did not work well.

**Comment by qo4on** [comment]
Open your [notebook](https://colab.research.google.com/github/espnet/notebook/blob/master/tts_realtime_demo.ipynb). Run english FastSpeech, Parallel WaveGAN, Setup.
Place this in Synthesis:
```
input_text = "Http0XX , Http1XX , Http2XX , Http3XX"
```
Listen the result and compare it with [official](https://speechresearch.github.io/fastspeech/). It is totally wrong.

**Comment by kan-bayashi** [comment]
As I mentioned above, this is caused by text frontend.
When we use `H T T P 0 X X, H T T P 1 X X, H T T P 2 X X, H T T P 3 X X. ` as the input, it works correctly.

**Comment by qo4on** [comment]
It is clearly written, they use in robustness text:
```
input_text = "Http0XX , Http1XX , Http2XX , Http3XX"
```
not 
```
input_text = "H T T P 0 X X, H T T P 1 X X, H T T P 2 X X, H T T P 3 X X"
```
And your model fails to pass it.

**Comment by kan-bayashi** [comment]
I know. The text frontend part is different.
The reason why the generation is failed is our used g2p module could not parse the input sentence since if we use modified text, the generation does well.
Therefore, the reason of the failure is the text frontend, not fastspeech itself.

**Comment by kan-bayashi** [comment]
What do you want to know? I could not understand your intension.

**Comment by qo4on** [comment]
Ok, it's your text frontend fault, not a model. All I want is to let you know about this, so you'll be able to fix this in your later models, if you want to, of course.
Thanks.
