### ISSUE TITLE
Multi GPUs training freezes after first iter

### ISSUE THREAD

**Issue by Fhrozen** [espnet/espnet#176]
I found this error while I was training the network for CHiME5.

PC setup:
Server (CentOS) with nvidia K80 and docker environment.

It stops after reporting the mtl loss and do not update (I needed to stop one container after 2 days without any update).

I am not sure if this is related to the setup or chainer ver(4.0) or docker environment. I tested different models on chainer and docker single gpu without any problem.
I will test in my computer with 2 gpus. I will try in both docker and normal env. 

I am just notifying to check if something else related to multi gpu has a issue.

**Comment by rhoposit** [comment]
I am having this problem now on iwslt16, I tried setting gpu=4, and gpu=1, with different batch sizes.
