### ISSUE TITLE
support Minimum Bayes Risk Training for rnnt or las asr training?

### ISSUE THREAD

**Issue by xinqipony** [espnet/espnet#1763]
does espnet support it?

**Comment by b-flo** [comment]
Hi,

No, I suppose you're referring to: https://arxiv.org/abs/1911.12487
There are no plans to add mbr training right now, I'll look into it when the current works on transducer are finished. Any help is welcomed though!

**Comment by ShigekiKarita** [comment]
FYI: Our beam search implementation is already `torch.nn.Module` and uses `forward` to return hypotheses. I designed it for such training but it needs a little fix to backprop through this module. I expect the changes are not so large.
- https://github.com/espnet/espnet/blob/v.0.7.0/espnet/nets/batch_beam_search.py
