### ISSUE TITLE
"WARNING: Target sequences include empty token id (batch 2 -> 0)" and then error

### ISSUE THREAD

**Issue by yash-s20** [espnet/espnet#1768]
Hi! Three of my experiments with different datasets and configurations have all ended with the same error. The last 200 lines of a train.log are here attached -[train.log](https://github.com/espnet/espnet/files/4433137/train.log) (you can see all characters here are in devanagari, but other expts have english characters too).
It's seems that the batch is empty? What could cause this problem?
Any insights will be appreciated. Thanks!

**Comment by kan-bayashi** [comment]
As the log said, it seems that your data includes empty target.
Please check your `data/*/text` does not contain empty line.

**Comment by yash-s20** [comment]
Thanks. I had added the flag "allow-one-column" and thought everything would work fine with empty utterances. What these experiments had in common was a small batch size, and 2 continuous utterances were empty. Thanks. Resolved.
