### ISSUE TITLE
rnn transducer beam search decoding

### ISSUE THREAD

**Issue by cookingbear** [espnet/espnet#1770]
I saw your rnnt beam search decoding strategy in recognize_beam() of decoders_transducer.py and wonder if it is not a final or completed version because I did not see the merge procedure as below:
<img width="601" alt="image" src="https://user-images.githubusercontent.com/6813944/78470494-9fce1080-775c-11ea-858e-e6f10223ad8e.png">

**Comment by b-flo** [comment]
Hi,

It is intentional. Prefix search was removed based on https://arxiv.org/abs/1303.5778 and my experiments. The performance gain is omittable while decoding procedure is considerably faster.

I won't add it for the default version but it's an option for another search algorithm for transducer which is not available yet.

**Comment by cookingbear** [comment]
> Hi,
> 
> It is intentional. Prefix search was removed based on https://arxiv.org/abs/1303.5778 and my experiments. The performance gain is omittable while decoding procedure is considerably faster.
> 
> I won't add it for the default version but it's an option for another search algorithm which is not available yet.

sorry I still did not understand that if the merge procedure did not exist, "hyps" may contains candidates with same "yseq", how to explain this situation?

**Comment by b-flo** [comment]
Prefix search was used to avoid searching among all labels, similarly to CTC, by looking at prefixes of hypotheses. However, 1) the number of prefixes to expand will grows exponentially with the input sequence length, and 2) it does not necessary insure that the search space won't be redundant as no pruning is done.

While we cannot guarantee duplicates won't appear, in the end, most probable hypotheses are retained and the accuracy/proc. time trade-off is more interesting without prefix search.
