### ISSUE TITLE
Chinese ASR and TTS

### ISSUE THREAD

**Issue by Strong-Gavin** [espnet/espnet#1771]
Does the project support Chinese ASR and TTS? Can I directly use the model without training. Is there any document about Chinese AST and TTS. Thank you

**Comment by b-flo** [comment]
Hi,

> Does the project support Chinese ASR and TTS?

If you're asking for ASR or TTS recipes for chinese corpora, there are several that I know of, such as [Aishell (ASR)](https://github.com/espnet/espnet/tree/master/egs/aishell/asr1), [HKUST (ASR)](https://github.com/espnet/espnet/tree/master/egs/hkust/asr1) and [CSMSC (TTS)](https://github.com/espnet/espnet/tree/master/egs/csmsc/tts1)

>  Can I directly use the model without training. Is there any document about Chinese AST and TTS.

Yes, the [main README](https://github.com/espnet/espnet/blob/master/README.md) has link for several pre-trained models in both ASR and TTS for chinese. It also contains the the documentation, tutorial, examples, demo, etc, you need to train or use the models.

**Comment by Strong-Gavin** [comment]
> Hi,
> 
> > Does the project support Chinese ASR and TTS?
> 
> If you're asking for ASR or TTS recipes for chinese corpora, there are several that I know of, such as [Aishell (ASR)](https://github.com/espnet/espnet/tree/master/egs/aishell/asr1), [HKUST (ASR)](https://github.com/espnet/espnet/tree/master/egs/hkust/asr1) and [CSMSC (TTS)](https://github.com/espnet/espnet/tree/master/egs/csmsc/tts1)
> 
> > Can I directly use the model without training. Is there any document about Chinese AST and TTS.
> 
> Yes, the [main README](https://github.com/espnet/espnet/blob/master/README.md) has link for several pre-trained models in both ASR and TTS for chinese. It also contains the the documentation, tutorial, examples, demo, etc, you need to train or use the models.

sorry,i can't see pretrainned models  in both ASR and TTS for chinese and demos for  chinese .can you point at where they are.

**Comment by b-flo** [comment]
No problem!

Aishell (ASR): [models informations and download link](https://github.com/espnet/espnet/blob/master/egs/aishell/asr1/RESULTS.md#transformer-result-default-transformer-with-initial-learning-rate--10-and-epochs--50)
HKUST (ASR) : [model informations and download link](https://github.com/espnet/espnet/blob/master/egs/hkust/asr1/RESULTS.md#transformer-only-20-epochs)
CSMSC (TTS): [different models can be found directly here](https://drive.google.com/drive/folders/1WoG6mk65VVwFTpZGN71HeFQJEdR_oBPr)

**Comment by Strong-Gavin** [comment]
> No problem!
> 
> Aishell (ASR): [models informations and download link](https://github.com/espnet/espnet/blob/master/egs/aishell/asr1/RESULTS.md#transformer-result-default-transformer-with-initial-learning-rate--10-and-epochs--50)
> HKUST (ASR) : [model informations and download link](https://github.com/espnet/espnet/blob/master/egs/hkust/asr1/RESULTS.md#transformer-only-20-epochs)
> CSMSC (TTS): [different models can be found directly here](https://drive.google.com/drive/folders/1WoG6mk65VVwFTpZGN71HeFQJEdR_oBP

**Comment by Strong-Gavin** [comment]
> No problem!
> 
> Aishell (ASR): [models informations and download link](https://github.com/espnet/espnet/blob/master/egs/aishell/asr1/RESULTS.md#transformer-result-default-transformer-with-initial-learning-rate--10-and-epochs--50)
> HKUST (ASR) : [model informations and download link](https://github.com/espnet/espnet/blob/master/egs/hkust/asr1/RESULTS.md#transformer-only-20-epochs)
> CSMSC (TTS): [different models can be found directly here](https://drive.google.com/drive/folders/1WoG6mk65VVwFTpZGN71HeFQJEdR_oBPr)

but the asr demo list some available pretrained models not about chinese,how can i use pre-trained models for chinese.
![demo](https://user-images.githubusercontent.com/17334234/78501870-6ca57480-7790-11ea-9e96-b5e402a9930d.png)

**Comment by b-flo** [comment]
The pre-trained ASR models I linked can be used with `recog_wav.sh`. You need to pass `recog_model`, `cmvn` and `lang_model` (if available) from the downloaded archive.

**Comment by Strong-Gavin** [comment]
> The pre-trained ASR models I linked can be used with `recog_wav.sh`. You need to pass `recog_model`, `cmvn` and `lang_model` (if available) from the downloaded archive.

So can't this  `recog_wav.sh`  script be used directly for Chinese ASR？And how should I use the Chinese ASR pre training model?

**Comment by b-flo** [comment]
> So can't this recog_wav.sh script be used directly for Chinese ASR？And how should I use the Chinese ASR pre training model?

I think you should take a look at [recog_wav.sh](https://github.com/espnet/espnet/blob/master/egs/tedlium2/asr1/local/recog_wav.sh). As I said, you can use the script and specify the pre-trained models I mentioned.

**Comment by Strong-Gavin** [comment]
Well. I'll try. Thank you anyway

**Comment by Strong-Gavin** [comment]
I tried to test Chinese TTS with scripts, but I didn't get the expected results. What is the format of Chinese Pinyin input?
