### ISSUE TITLE
Chinese Pinyin format

### ISSUE THREAD

**Issue by Strong-Gavin** [espnet/espnet#1781]
I tried to test Chinese TTS with scripts, but I didn't get the expected results. What is the format of Chinese Pinyin input?

**Comment by kan-bayashi** [comment]
See https://github.com/espnet/espnet/issues/1754

**Comment by Strong-Gavin** [comment]
How do you use Chinese Pinyin speech synthesis？

**Comment by kan-bayashi** [comment]
Try https://colab.research.google.com/github/espnet/notebook/blob/master/tts_realtime_demo.ipynb

**Comment by Strong-Gavin** [comment]
> Please see our notebook. https://colab.research.google.com/github/espnet/notebook/blob/master/tts_realtime_demo.ipynb

I have tried.But I can't get the result.And I need to produce wav file,so I want to use synth_wav.sh script to synthesis chinese pinyin,but i cant't know the chinese pinyin format in the txt file for recognize.I tried "ni2 hao3"but not done well

**Comment by kan-bayashi** [comment]
> I have tried.But I can't get the result.And I need to produce wav file.

Why you cannot get results? 
You can download the wav file from the notebook.
And you can make the script to save generated wav by copy & paste of the code in notebook.

**Comment by Strong-Gavin** [comment]
> > I have tried.But I can't get the result.And I need to produce wav file.
> 
> Why you cannot get results?
> You can download the wav file from the notebook.
> And you can make the script to save generated wav by copy & paste of the code in notebook.

I use it in vmvare workstation

**Comment by kan-bayashi** [comment]
Sorry, I do not understand your meaning.
Why you did not use colab?

Anyway, you can follow the manner in `frontend` function in the notebook to get the pinyin format text.

**Comment by Strong-Gavin** [comment]
> > I have tried.But I can't get the result.And I need to produce wav file.
> 
> Why you cannot get results?
> You can download the wav file from the notebook.
> And you can make the script to save generated wav by copy & paste of the code in notebook.

I want know 

> Sorry, I do not understand your meaning.
> Why you did not use colab?
> 
> Anyway, you can follow the manner in `frontend` function in the notebook to get the pinyin format text.

Now I wonder if I can use the synth_wav.sh script for Chinese speech synthesis instead of tts_realtime_demo. Thank you

**Comment by Strong-Gavin** [comment]
I have tried use the chinese pin result produced by frontend function.But I cant't get the correct voice.So I don't know which format of pinyin should be used for speech synthesis。

**Comment by Strong-Gavin** [comment]
What is the sample file data for Chinese speech synthesis, like "ni2 hao3" or "164 73" or other formats?

**Comment by kan-bayashi** [comment]
I could not understand the reason why you did not use the notebook's code...

See the below example.
You can use `n i3 h ao3` as input text for `synth_wav.sh`.

```python
[ins] In [11]: from pypinyin import pinyin, Style
          ...: from pypinyin.style._utils import get_initials, get_finals

[ins] In [12]: def frontend(text):
          ...:     """Convert to pinyin format."""
          ...:     text = pinyin(text, style=Style.TONE3)
          ...:     text = [c[0] for c in text]
          ...:     clean_text = []
          ...:     for x in text:
          ...:         c_init = get_initials(x, strict=True)
          ...:         c_final = get_finals(x, strict=True)
          ...:         for c in [c_init, c_final]:
          ...:             if len(c) == 0:
          ...:                 continue
          ...:             c = c.replace("ü", "v")
          ...:             c = c.replace("ui", "uei")
          ...:             c = c.replace("un", "uen")
          ...:             c = c.replace("iu", "iou")
          ...:             # Special rule: "e5n" -> "en5"
          ...:             if "5" in c:
          ...:                 c = c.replace("5", "") + "5"
          ...:             clean_text += [c]
          ...:     return " ".join(clean_text)
          ...:

[ins] In [13]: text = "你好"

[ins] In [14]: clean_text = frontend(text)

[ins] In [15]: print(clean_text)
n i3 h ao3
```

**Comment by Strong-Gavin** [comment]
> I could not understand the reason why you did not use the notebook's code...
> 
> See the below example.
> You can use `n i3 h ao3` as input text for `synth_wav.sh`.
> 
> ```python
> [ins] In [11]: from pypinyin import pinyin, Style
>           ...: from pypinyin.style._utils import get_initials, get_finals
> 
> [ins] In [12]: def frontend(text):
>           ...:     """Convert to pinyin format."""
>           ...:     text = pinyin(text, style=Style.TONE3)
>           ...:     text = [c[0] for c in text]
>           ...:     clean_text = []
>           ...:     for x in text:
>           ...:         c_init = get_initials(x, strict=True)
>           ...:         c_final = get_finals(x, strict=True)
>           ...:         for c in [c_init, c_final]:
>           ...:             if len(c) == 0:
>           ...:                 continue
>           ...:             c = c.replace("ü", "v")
>           ...:             c = c.replace("ui", "uei")
>           ...:             c = c.replace("un", "uen")
>           ...:             c = c.replace("iu", "iou")
>           ...:             # Special rule: "e5n" -> "en5"
>           ...:             if "5" in c:
>           ...:                 c = c.replace("5", "") + "5"
>           ...:             clean_text += [c]
>           ...:     return " ".join(clean_text)
>           ...:
> 
> [ins] In [13]: text = "你好"
> 
> [ins] In [14]: clean_text = frontend(text)
> 
> [ins] In [15]: print(clean_text)
> n i3 h ao3
> ```

yes.I have tried "n i3 h ao3".But I can't recognize the mean from the result wav file.I will put the detail steps and logs later

**Comment by kan-bayashi** [comment]
`synth_wav.sh` requires to set various parameters, so I recommend to use notebook code.
Here is the example.
```bash
$ echo "n i3 h ao3" > example.txt
$ synth_wav.sh --models csmsc.fastspeech.v3 \
    --vocoder_models csmsc.parallel_wavegan.v1 \
    --fs 24000 \
    --n_fft 2048 \
    --n_shift 300 \
    --win_length 1200 \
    --fmax 7600 \
    --fmin 80 \
    --trans-type phn \
    example.txt
```

**Comment by Strong-Gavin** [comment]
![QQ截图20200407215546](https://user-images.githubusercontent.com/17334234/78678364-6c85b000-791b-11ea-8ee5-80c79ee2e6d4.png)
This is I use synth_wav.sh result。If I use notebook code,how can I produce result wav in local disk

**Comment by kan-bayashi** [comment]
See the above example.
To save wav file in colab, please google it by yourself.
