### ISSUE TITLE
TIMIT results?

### ISSUE THREAD

**Issue by kamo-naoyuki** [espnet/espnet#1787]
I'd like to use timit recipe for sanity check now, but the result seems not to exist.

https://github.com/espnet/espnet/tree/master/egs/timit/asr1

Anyone has?

**Comment by sw005320** [comment]
I haven't tested it.
@sknadig, do you have some results?
Could you make a PR to put your results like the other recipe?

**Comment by sknadig** [comment]
Yes, I have the results but not the trained models. I'll make a PR with the results.
