### ISSUE TITLE
Speaker embedding in TTS

### ISSUE THREAD

**Issue by anushaprakash90** [espnet/espnet#1790]
Hi,

Do you have a TTS recipe that includes speaker embedding in the **Tacotron2** framework? There is no parameter about speaker information in the config files, although speaker_embedding is a variable in the scripts that are called for training.

Is speaker embedding automatically considered from information in the utt2spk and spk2utt files in a multi-speaker scenario? Or do we need to explicitly include it?

I would also like to know what the variable use_second_target means.

Thanks

**Comment by kan-bayashi** [comment]
Yes, we have. This is the config example.
https://github.com/espnet/espnet/blob/master/egs/libritts/tts1/conf/train_pytorch_tacotron2%2Bspkemb.yaml
> `use-speaker-embedding: true` is important.

In our multi-speaker model, we use pretrained x-vector as speaker embeddings.
The following part is x-vector extraction.
https://github.com/espnet/espnet/blob/1fce0db473812265fcbdb874f847125366f91d51/egs/libritts/tts1/run.sh#L143-L159
During the stage, json is updated to include the information of extracted x-vector.

If we use speaker embedding, that is replicated and then concatenated with each encoder states as follows:
https://github.com/espnet/espnet/blob/1fce0db473812265fcbdb874f847125366f91d51/espnet/nets/pytorch_backend/e2e_tts_tacotron2.py#L536-L541

> I would also like to know what the variable use_second_target means.

This option is for the case where there are two target sequences.
E.g. text -> [Taco] -> Mel -> [CBHG] -> STFT

**Comment by anushaprakash90** [comment]
Thanks for your reply @kan-bayashi . I will look into the libriTTS recipe.

Just to confirm, the tts1 recipe of ljspeech does not include speaker embedding right?

**Comment by kan-bayashi** [comment]
Yes, ljspeech recipe does not include speaker embedding.
Multispeaker model is `egs/libritts/tts1` and `egs/jnas/tts1`.

**Comment by anushaprakash90** [comment]
Another doubt, how is the x-vector considered for test sentences, i.e., during evaluation?

**Comment by kan-bayashi** [comment]
Sorry for the late reply.
In the recipe, we use evaluation utterances to extract x-vector.
If you want to check the performance in a more realistic situation, it is better to use spk average x-vector or another utterance.

**Comment by anushaprakash90** [comment]
Thanks @kan-bayashi. That clears my doubts.
