### ISSUE TITLE
Multiple decoders

### ISSUE THREAD

**Issue by argideritzalpea** [espnet/espnet#1792]
Hello - I was wondering if there were any recipes / options for single encoder-to-multi-decoder models for espnet to jointly learn for two outputs (transcripts) from a single input audio source?

Thanks

**Comment by xingchensong** [comment]
As far as I know, `Hybrid CTC/attention`  can be seen as a simplified version of single-encoder-multi-decoder model to handle your different outputs?

**Comment by sw005320** [comment]
We have several studies including preparing multiple decoders (https://arxiv.org/abs/1804.08050 this is not merged to the master branch but it's based on espnet), multispeaker ASR (https://github.com/espnet/espnet/tree/master/egs/wsj_mix/asr1), and so on.
And yes, Hybrid CTC/attention can potentially handle different outputs (but there are a lot of assumptions that both outputs are the same).

Probably multispeaker ASR is most relevant.
Another possibility is to concatenate the two outputs and make it as a single sequence.
