### ISSUE TITLE
ESPnet2 results

### ISSUE THREAD

**Issue by argideritzalpea** [espnet/espnet#1796]
I am hoping to run models for CommonVoice data using ESPnet2 without Chainer or Kaldi dependencies. 

I noticed Kabyle model run results posted at the following location: https://github.com/espnet/espnet/blob/master/egs2/commonvoice/asr1/RESULTS.md
From my interpretation, it appears that the test WER for the kabyle data set is 37.5. Is this correct?

However, I don't see any configurations logged to achieve these results. For example, whether Kaldi preprocessing was turned on or off, how many epochs were achieved, etc.

Were these results achieved with realistic configurations, or are these just test runs trained for a limited period of time? Is it correct to interpret that ESPnet2 currently does not reproduce the results of ESPnet?

**Comment by kamo-naoyuki** [comment]
The configuration files is placed here? https://github.com/espnet/espnet/tree/master/egs2/commonvoice/asr1/conf

> Were these results achieved with realistic configurations, or are these just test runs trained for a limited period of time? Is it correct to interpret that ESPnet2 currently does not reproduce the results of ESPnet?

Yes. The first priority is just moving recipes. We may prepare the second round to retune recipes.
If you'll tune for now, it would be helpful.
