### ISSUE TITLE
add unit-tests and Travis CI (.travis.yml)

### ISSUE THREAD

**Issue by ShigekiKarita** [espnet/espnet#18]
Testing python2/3 and chainer/pytorch compatibility by our hand will be hell. we need some continuous integration on this. I think chainer's setting is good for us to test and build doc automatically. https://github.com/chainer/chainer/blob/master/.travis.yml

**Comment by sw005320** [comment]
I understand and I will work on it. But at least, our setup is based on virtualenv and making an isolated setup with python 2.7, which is one way to avoid this kind of issues. So I want you to follow this setup for now.

**Comment by ShigekiKarita** [comment]
gotcha 👌

**Comment by ShigekiKarita** [comment]
I wonder if there were tiny toy example in espnet to run end-to-end test and benchmark in a short time. Some frameworks use AN4 for that purpose. I want someone to create AN4 egs because I'm not very familiar with kaldi. 

- an4 in CNTK https://github.com/Microsoft/CNTK/tree/master/Examples/Speech/AN4
- an4 in torch deepspeech https://github.com/SeanNaren/deepspeech.torch
- an4 in pytorch deepspeech https://github.com/SeanNaren/deepspeech.pytorch

**Comment by ShigekiKarita** [comment]
I'm working on it in advance of you. I just copied chainer/.travis.yml and delete and add a few lines. Although I wrote only stupid tests, we can [see a python2/3 unicode problem here](https://travis-ci.org/ShigekiKarita/espnet/builds/318193090)

Also there can be several problems and discussions.
- pytorch installation on Travis-CI might not be possible now https://github.com/uber/pyro/pull/627
- end-to-end testing with smaller but real corpus
- need to lint python coding style like chainer? (I think it is too strict)

**Comment by sw005320** [comment]
Thanks for the suggestion.
I can definitely make an4 egs.
Wait for a while.

**Comment by ShigekiKarita** [comment]
@sw005320 now https://github.com/espnet/espnet/blob/master/.travis.yml is in this repo, you can enable travis ci. (I do not have such a permission.)

all you need to do is step1-2 in https://docs.travis-ci.com/user/getting-started#To-get-started-with-Travis-CI

**Comment by sw005320** [comment]
@ShigekiKarita I've finished the an4 example. I don't tune the performance so much, but I think it would be okay for the test purpose.

**Comment by ShigekiKarita** [comment]
Thanks!
