### ISSUE TITLE
KeyError: 'missing keys in state_dict  when decoding

### ISSUE THREAD

**Issue by zbcy12** [espnet/espnet#180]
Traceback (most recent call last):
  File "/home/bing/espnet/egs/librispeech/asr1/../../../src/bin/asr_recog.py", line 117, in <module>
    main()
  File "/home/bing/espnet/egs/librispeech/asr1/../../../src/bin/asr_recog.py", line 111, in main
    recog(args)
  File "/home/bing/espnet/src/asr/asr_pytorch.py", line 391, in recog
    model.load_state_dict(remove_dataparallel(torch.load(args.model, map_location=cpu_loader)))
  File "/home/bing/espnet/tools/venv/local/lib/python2.7/site-packages/torch/nn/modules/module.py", line 526, in load_state_dict
    raise KeyError('missing keys in state_dict: "{}"'.format(missing))
KeyError: 'missing keys in state_dict: "set([\'predictor.enc.enc1.bilstm1.bias_ih_l0_reverse\', \'predictor.dec.att.gvec.bias\', \'predictor.enc.enc1.bilstm1.weight_ih_l0\', \'predictor.enc.enc1.bt1.bias\', \'predictor.dec.att.mlp_enc.weight\', \'predictor.enc.enc1.bilstm1.weight_hh_l0\', \'predictor.dec.output.weight\', \'predictor.dec.embed.weight\', \'predictor.enc.enc1.bt1.weight\', \'predictor.enc.enc1.bt0.weight\', \'predictor.enc.enc1.bt2.bias\', \'predictor.enc.enc1.bilstm0.bias_ih_l0_reverse\', \'predictor.dec.decoder.0.weight_hh\', \'predictor.enc.enc1.bilstm0.weight_ih_l0_reverse\', \'predictor.enc.enc1.bilstm2.bias_ih_l0_reverse\', \'predictor.att.loc_conv.weight\', \'predictor.enc.enc1.bilstm2.bias_ih_l0\', \'predictor.dec.att.gvec.weight\', \'predictor.enc.enc1.bilstm0.weight_hh_l0_reverse\', \'predictor.enc.enc1.bilstm1.weight_ih_l0_reverse\', \'predictor.enc.enc1.bilstm0.bias_ih_l0\', \'predictor.enc.enc1.bilstm0.weight_hh_l0\', \'predictor.enc.enc1.bilstm1.bias_ih_l0\', \'predictor.enc.enc1.bilstm0.bias_hh_l0\', \'predictor.enc.enc1.bilstm2.weight_ih_l0_reverse\', \'predictor.ctc.ctc_lo.weight\', \'predictor.enc.enc1.bilstm2.weight_hh_l0_reverse\', \'predictor.att.mlp_dec.weight\', \'predictor.att.mlp_att.weight\', \'predictor.dec.decoder.0.bias_ih\', \'predictor.ctc.ctc_lo.bias\', \'predictor.enc.enc1.bilstm1.bias_hh_l0_reverse\', \'predictor.att.mlp_enc.bias\', \'predictor.dec.att.mlp_att.weight\', \'predictor.enc.enc1.bt0.bias\', \'predictor.dec.att.loc_conv.weight\', \'predictor.dec.decoder.0.bias_hh\', \'predictor.enc.enc1.bilstm1.bias_hh_l0\', \'predictor.enc.enc1.bt2.weight\', \'predictor.enc.enc1.bilstm2.bias_hh_l0_reverse\', \'predictor.dec.decoder.0.weight_ih\', \'predictor.dec.att.mlp_dec.weight\', \'predictor.enc.enc1.bilstm2.weight_ih_l0\', \'predictor.att.gvec.bias\', \'predictor.enc.enc1.bilstm0.weight_ih_l0\', \'predictor.enc.enc1.bilstm0.bias_hh_l0_reverse\', \'predictor.dec.output.bias\', \'predictor.enc.enc1.bilstm1.weight_hh_l0_reverse\', \'predictor.att.gvec.weight\', \'predictor.att.mlp_enc.weight\', \'predictor.enc.enc1.bilstm2.bias_hh_l0\', \'predictor.dec.att.mlp_enc.bias\', \'predictor.enc.enc1.bilstm2.weight_hh_l0\'])"'

**Comment by sw005320** [comment]
This might be related to #154, which was fixed by #178. Can you try it with the latest version?

**Comment by zbcy12** [comment]
I have tried both of them but I will check it again. This only happens when I use pytorch during decoding.

**Comment by kan-bayashi** [comment]
Now fixed.
