### ISSUE TITLE
Unable to decode with Word RNNLM when <space> is not in corpus

### ISSUE THREAD

**Issue by ajd12342** [espnet/espnet#1806]
I have trained a SentencePiece BPE token based E2E system and a word-based RNNLM.
While decoding, I get an error:
```
File "/home/anuj/espnet/espnet/lm/pytorch_backend/extlm.py", line 116, in __init__
    self.space = subword_dict['<space>']
KeyError: '<space>'
```
Is there any solution to this?
This is similar to #1473 but the setup described in that issue was different.

**Comment by sw005320** [comment]
BPE token is not supported for word RNNLM.
Also, it is not easy to make some error handling for this condition and we just leave it as it is.
