### ISSUE TITLE
change for persian language

### ISSUE THREAD

**Issue by ohadianoush** [espnet/espnet#1809]
hi, i download ljspeech and change csv file & waves file to my own language (persian) وwhat other changes are needed?
note: i do these changs in ParallelWaveGAN and build model but its not work fine and they said:
E2E-TTS model consists of two types networks:
    1-Text2Mel
    2-Mel2Wav (=vocoder, this repository)
Text2Mel model converts text sequence into mel spectrogram, which is basically language-dependent. Therefore, if you want to generate Persian language speech, you need to train not only the vocoder but also text2mel models (such as Tactoron 2, Transformer).

https://github.com/kan-bayashi/ParallelWaveGAN/issues/116

**Comment by sw005320** [comment]
You need to prepare Kaldi-like data preparation (see https://github.com/espnet/espnet/blob/master/egs/m_ailabs/tts1/local/data_prep.sh and others).
For example, you need to make a subdirectory under the `data` director, which contains `text`, `wav.scp`, `utt2spk`, and `spk2utt` (but `utt2spk`, and `spk2utt` can be dummy).
