### ISSUE TITLE
Espnet text frontend

### ISSUE THREAD

**Issue by qo4on** [espnet/espnet#1817]
Does Espnet offer more sophisticated text frontend which could split words (`taxidriver -> taxi driver`) and correctly convert abbreviations like `http, rfc` into phonemes?
`G2p` which you use returns bad results very often.

**Comment by b-flo** [comment]
Hi,

> Does Espnet offer more sophisticated text frontend

I'm aware of : https://github.com/espnet/espnet_tts_frontend but I don't know its full scope, sorry. I'll let you take a look or others can comment on that.

> correctly convert abbreviations like http, rfc into phonemes?
> G2p which you use returns bad results very often.

Again, I'm not familiar with the g2p used in espnet (https://github.com/Kyubyong/g2p), however from what I see the algorithm looks-up the CMU dict for non-homographs. For an OOV, a neural net is used to predict the corresponding pronunciation. Thus, if you have some important words not included in CMU dict and predicted pronunciation is not correct, I would advise adding them to the dict (I think a local copy is downloaded through nltk?) or use a custom dict.

**Comment by qo4on** [comment]
Thanks, @b-flo .
A few notes:
- [espnet_tts_frontend](https://github.com/espnet/espnet_tts_frontend/blob/master/tacotron_cleaner/cleaners.py) does not solve problems like `taxidriver, http, rfc`
- `predict` function which uses neural net returns wrong phonemes for `taxidriver, http, rfc...`. Adding these words to exception list is not the best solution. It's impossible to add all concatenated words and abbreviations.

**Comment by b-flo** [comment]
> espnet_tts_frontend does not solve problems like taxidriver, http, rfc

Sorry about that. @kan-bayashi can comment for other possible solution.

> predict function which uses neural net returns wrong phonemes for taxidriver, http, rfc....

Yes, I took a look at cmu dict and these words are not defined.

>  Adding these words to exception list is not the best solution. It's impossible to add all concatenated words and abbreviations.

Sorry, that was not what I implied. Given the base dict coverage and g2p procedure, I thought the list of additional/problematic words you wanted covered would be rather specific. Not "add all concatenated words and abbreviations" covered, which is not a realistic goal.

> Ideal solution would be to retrain this neural net model (or find another model) for supporting such words. But I'm not sure how to do that.

I don't know the tool but looking into the repo, this [tutorial](https://github.com/Kyubyong/nlp_made_easy/blob/master/PyTorch%20seq2seq%20template%20based%20on%20the%20g2p%20task.ipynb) is mentioned for training. It seems the cmu dict was also used for train the model (at least in tutorial).
For other available models, I don't know, sorry.

**Comment by qo4on** [comment]
They trained on `cmudict.dict`. But `cmudict.dict` does not have compound words and abbreviations. So it is expected that the model can't predict right phonemes for them.

**Comment by sw005320** [comment]
Right now, we did not fully integrate text preprocessing but we call external scripts or tools for each recipe since the text preprocessing fully depends on the language and task. In other words, if you find some external tools that perform what you want to do, you can use them in some espnet recipes by referring their ways of calling external scripts or tools.

**Comment by qo4on** [comment]
Unfortunately, I did not find a tool which correctly converts abbreviations and concatenated words to phonemes.
To retrain g2p model which you used we need an `abbreviations to phonemes` dataset.
