### ISSUE TITLE
CTC in pytorch 0.4 degrades the performance

### ISSUE THREAD

**Issue by hirofumi0810** [espnet/espnet#182]
I have confirmed that the warpctc pytorch binding degraded the CTC performance after updating to pytorch 0.4.
In addition, surprisingly, when building the master branch of pytorch (0.5), the CTC performance degraded further.
This is consistent to my experiments with TIMIT and CSJ corpora.

Therefore, I strongly recommend using pytorch 0.3 until releasing the new version of warp_ctc.
There was no significant deference between 0.3 and 0.4 regarding the attention-based seq2seq models .

If anyone confirmed the same problem, please tell me. Thank you.

**Comment by sw005320** [comment]
Thanks. Fortunately, the standard `Makefile` uses pytorch 0.3.1, and would not have serious problems. If we use `conda.mk`, it will be a deal (#143). This convinced me that we should keep to use pytorch 0.3 for a while.

**Comment by ShigekiKarita** [comment]
I think #250 fixes this issue. Could you test #250 in master.0.5.0?

**Comment by kan-bayashi** [comment]
Fixed.
