### ISSUE TITLE
transformer bug in Pytorch 1.2.0

### ISSUE THREAD

**Issue by RobotGF** [espnet/espnet#1832]
espnet/espnet/nets/pytorch_backend/transformer/mask.py 
`is_torch_1_2_plus = LooseVersion(torch.__version__) >= LooseVersion('1.2.0')
datatype = torch.bool if is_torch_1_2_plus else torch.uint8

def subsequent_mask(size, device="cpu", dtype=datatype):
    """Create mask for subsequent steps (1, size, size).
    :param int size: size of mask
    :param str device: "cpu" or "cuda" or torch.Tensor.device
    :param torch.dtype dtype: result dtype
    :rtype: torch.Tensor
    >>> subsequent_mask(3)
    [[1, 0, 0],
     [1, 1, 0],
     [1, 1, 1]]
    """
    ret = torch.ones(size, size, device=device, dtype=dtype)
    return torch.tril(ret, out=ret)
`
RuntimeError: "tril" not implemented for 'Bool'

pytorch 1.2.0 with GPU or CPU

**Comment by sw005320** [comment]
I thought that transformer is working on any pytorch versions.
Does it only happen in pytorch 1.2.0?

**Comment by RobotGF** [comment]
> I thought that transformer is working on any pytorch versions.
> Does it only happen in pytorch 1.2.0?

Yes，I test with 1.0.0 1.1.0 1.2.0 1.3.0 . It only happen in pytorch 1.2.0. Before 1.2.0 ,pytorch Tensor doesn't have Boolean Type, So it works. But when in 1.2.0, tril not implemented for Bool tensor. > 1.2.0 tril works for bool.

**Comment by sw005320** [comment]
Many thanks.
Hmm. This is very strange...
Please check PR in #1840 
@kamo-naoyuki, thanks for taking care of it.
