### ISSUE TITLE
CTC loss and feature extractor in espnet model with mixed precision

### ISSUE THREAD

**Issue by SeanNaren** [espnet/espnet#1836]
Hey guys! When I use `--train_dtype O1` as a parameter for `espnet2.bin.asr_train` I run into the below error message.

```
RuntimeError: "ctc_loss_cuda" not implemented for 'Half'
```
In deepspeech.pytorch this is handled by converting the loss to float32 as seen [here](https://github.com/SeanNaren/deepspeech.pytorch/blob/master/train.py#L253). We've tested this internally on a variety of scales and this works well for us.

Is this something acceptable for you guys? If so I don't mind making the change via a PR!

**Comment by kamo-naoyuki** [comment]
Thanks. I know it. It should be fixed as you said.

**Comment by SeanNaren** [comment]
@kamo-naoyuki will you be handling this? I'm more than happy to work on this if it will help you out!

**Comment by kamo-naoyuki** [comment]
Thanks. If you send PR, it's helpful. 
The reason I didn't is just laziness. There are too many things to do about espnet2.

**Comment by SeanNaren** [comment]
haha 100%, I'll make a PR today

**Comment by SeanNaren** [comment]
Hey @kamo-naoyuki just wanted to confirm something, the `espnet_model.py` wraps everything including the extraction of the features. Does this mean if we convert the model via Apex, that the input speech tensor will be converted to FP16? This I think is causing me issues

**Comment by kamo-naoyuki** [comment]
Are you concerned about O2/O3 case? Hmm, in my understanding, yes.

I don't know the detail of apex API. How should we do it if we exclude the extraction from apex?
These APIs are appropriate?
https://github.com/NVIDIA/apex/tree/master/apex/amp

**Comment by SeanNaren** [comment]
I was running into this issue using O1, should I not be running into this issue?

**Comment by RobotGF** [comment]
I think CTC loss has reduce operation which is not suitable for mix precision training.

**Comment by SeanNaren** [comment]
After further inspection this is going to be a difficult problem to solve and may require modifying the pipeline.

Using Apex, there are wrappers added to the forward methods to automatically convert specific modules into half, this is done to reduce the amount of boilerplate by users.

Since feature extraction is a part of the converted model and a lot of the functions are defined as torch modules they are being wrapped as well, leading to improper feature extraction. The two solutions I see is convert the feature extractions into non torch modules, or remove feature extraction as a part of the model but I don't have a clear view of the rest of the package to decide the path, @kamo-naoyuki any feedback?

**Comment by kamo-naoyuki** [comment]
@SeanNaren Thank you for clarification.
Can't we use `amp.register_float_function(module, function_name)` or `@amp.float_function` for the feature extraction?

**Comment by SeanNaren** [comment]
I tried wrapping [extract_feats](https://github.com/espnet/espnet/blob/master/espnet2/asr/espnet_model.py#L204) with the `@amp.float_function` as well as using the `amp.register_float_function` before we convert the model via amp initialize [here](https://github.com/espnet/espnet/blob/master/espnet2/tasks/abs_task.py#L1038) but both seemed to not work, it seems like the internal functions such as `torch.matmul` called in `log_mel.py` are still returning half tensors...

**Comment by kamo-naoyuki** [comment]
Thanks. Hmm. I'll read the apex code for detail and think about it.

**Comment by SeanNaren** [comment]
Cheers if I find out anything more will let you know!

**Comment by kamo-naoyuki** [comment]
We can't solve this problem in any way!
I concluded that apex.amp is non sense idea because it patches all torch functions globally regardless whether the model uses them or not. 

```python
model = Net()
model.cuda()
optimizer = torch.optim.Adam(model.parameters())

amp.initialize(model, optimizer, opt_level="O1")

x = torch.rand(2, 10).cuda()
w = torch.rand(10, 10).cuda()
print(x.matmul(w).dtype)  # torch.half
```

It means that any torch functions can't coexist at non training places with apex.amp.  This is crazy. They ought to implement some function to limit the scope.

I gave up to support apex.amp from now and I'll consider to use torch native amp only.
https://pytorch.org/docs/master/notes/amp_examples.html

The API looks sane unlike apex.amp. Maybe torch1.5 comes soon.

**Comment by SeanNaren** [comment]
This is unfortunate, let me make an issue on the Apex repo about this and see what the authors have to say!

**Comment by kamo-naoyuki** [comment]
@SeanNaren PyTorch1.5 is out now! We can consider to move apex.amp to torch.cuda.amp to solve this issue.

**Comment by SeanNaren** [comment]
Awesome timing however speaking to @mcarilli it seems a lot of the implementation for native AMP didn't make it into the PyTorch 1.5 release :( we should see if we can get it working regardless but if we run into a blocker it may be because of this!

**Comment by kamo-naoyuki** [comment]
Do you know what implementation has not been completed yet? The official documentation is not clear for me. Should we wait until pytorch1.6?

BTW, I got an idea. The patching can be avoided by copying torch functions, so we can solve this problem if the feature extractor uses copied functions, but this way is too dirty ?

```python
import torch
import copy
from apex import amp

model = torch.nn.Linear(10, 10)
model.cuda()
optimizer = torch.optim.Adam(model.parameters())

matmul = copy.copy(torch.matmul)
amp.initialize(model, optimizer, opt_level="O1")

x = torch.rand(2, 10).cuda()
w = torch.rand(10, 10).cuda()
print(torch.matmul(x, w).dtype)  # torch.float16
print(matmul(x, w).dtype)   # float32
```

Another thought, I have never tested amp actually. Does this problem affect the result so much?

**Comment by mcarilli** [comment]
Apex Amp has many known pain points (extension builds, forward/backward compatibility across Pytorch versions, DataParallel support, flaky checkpointing, global enablement has silent consequences, i don’t even know if it can be hacked to handle double backward/gradient penalty).

Rather than sink more time into Apex, I fixed these in the native integration. `torch.cuda.amp` is fully-featured in master and nightly pip/conda binaries:
https://pytorch.org/docs/master/amp.html
https://pytorch.org/docs/master/notes/amp_examples.html
The autocast context manager (which automatically selects precision in enabled regions) didn't make 1.5, unfortunately.

**Comment by kamo-naoyuki** [comment]
@mcarilli Oh, thank you for replying for here and also considering the native integration! 
I see. I'm looking forward to the completion.

**Comment by kamo-naoyuki** [comment]
@SeanNaren PyTorch 1.6.0 is out and amp becomes stable! https://github.com/pytorch/pytorch/releases
Now we can solve this problem, so I added amp to my TODO list.

**Comment by SeanNaren** [comment]
Thanks @kamo-naoyuki just to warn you (might not impact you) but torch native AMP is broken for nn.LSTM, see issue here: https://github.com/pytorch/pytorch/issues/36428

**Comment by kamo-naoyuki** [comment]
Hmm, thanks, I didn't know it.
