### ISSUE TITLE
model link for transformer in espnet/egs/tedlium3/asr1 not working

### ISSUE THREAD

**Issue by ORlGlN** [espnet/espnet#1839]
The model link with the following details returned 404 on Google Drive, anyone able to fix the link?
file path: espnet/egs/tedlium3/asr1/RESULTS.md
model name: Transformer (elayers=12, dlayers=6, units=2048, 8 GPUs, specaug) + large LM
model link: https://drive.google.com/open?id=1wYYTwgvbB7uy6agHywhQfnuVWWW_obmO

Thanks in advance.

**Comment by sw005320** [comment]
This is the same problem as https://github.com/espnet/espnet/issues/1590.
@ahmedalbahnasawy, do you also have a tedlium3 model?

**Comment by ahmedalbahnasawy** [comment]
@sw005320 done 
I uploaded it to your drive.

**Comment by sw005320** [comment]
Many thanks!
