### ISSUE TITLE
where is change_yaml.py

### ISSUE THREAD

**Issue by 200987299** [espnet/espnet#1845]
hello guys,

I am new to this, and may I ask where is change_yaml.py? My computer tells me it can't find it. And I can't run ./run.sh --train-config $(change_yaml.py conf/train.yaml -a batch-size=24 -a epochs=10). Thanks for your help.

Bests

**Comment by b-flo** [comment]
Hi,

The file is located here: https://github.com/espnet/espnet/blob/master/utils/change_yaml.py (or `espnet/utils`, given you're in espnet directory root )
