### ISSUE TITLE
install  PackagesNotFoundError: The following packages are not available from current channels: cudatoolkit=8.0

### ISSUE THREAD

**Issue by ferb2015** [espnet/espnet#1847]
Hello, while installing espnet:
. venv/bin/activate && conda install -y pytorch=1.0.0 cudatoolkit=8.0 -c pytorch
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - cudatoolkit=8.0

Current channels:

  - https://conda.anaconda.org/pytorch/linux-64
  - https://conda.anaconda.org/pytorch/noarch
  - https://repo.anaconda.com/pkgs/main/linux-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/linux-64
  - https://repo.anaconda.com/pkgs/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

make: *** [espnet.done] Error 1

**Comment by ferb2015** [comment]
but,conda has cudatoolkit 8.0：
               
$ conda search cudatoolkit

cudatoolkit                8.0                           3  defaults

i use miniconda to install

**Comment by kamo-naoyuki** [comment]
This question is not related to espnet. You should ask at pytorch forum.
cudatoolkit=8.0 doesn't exist. Use cuda80 or pip: https://pytorch.org/get-started/previous-versions/

**Comment by ferb2015** [comment]
> This question is not related to espnet. You should ask at pytorch forum.
> cudatoolkit=8.0 doesn't exist. Use cuda80 or pip: https://pytorch.org/get-started/previous-versions/

thank you, i install pytorch by "conda install pytorch==1.0.0 torchvision==0.2.1 cuda80 -c pytorch", and it works.


import torch
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
print(torch._C._cuda_getCompiledVersion())
print(device)

output:
1.0.0
8000
cuda:0

**Comment by brainfo** [comment]
Hi, I got `PackagesNotFoundError: The following packages are not available from current channels:

  - cuda80` and `PackagesNotFoundError: The following packages are not available from current channels:

  - cudatoolkit=8.0`. I've got conda 4.8.4. So anyone knows how to install cuda 8.0 using conda?

**Comment by ferb2015** [comment]
Thank you for your reply,&nbsp;I have solved this problem. Thank you very much.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "espnet/espnet"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月2日(星期三) 下午3:10
收件人:&nbsp;"espnet/espnet"<espnet@noreply.github.com&gt;;
抄送:&nbsp;"叶珑"<244065526@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [espnet/espnet] install  PackagesNotFoundError: The following packages are not available from current channels: cudatoolkit=8.0 (#1847)





 
Hi, I got `PackagesNotFoundError: The following packages are not available from current channels:
  
 
cuda80andPackagesNotFoundError: The following packages are not available from current channels:
 
 
 
cudatoolkit=8.0`. I've got conda 4.8.4. So anyone knows how to install cuda 8.0 using conda?

**Comment by abhatnag** [comment]
@brainfo  just run this command to search for the version of cudatoolkit on your anaconda"
`conda search 'cuda'`
