### ISSUE TITLE
Using NCCLv1.x instead of 2.x for chainer MultiGPU

### ISSUE THREAD

**Issue by Fhrozen** [espnet/espnet#185]
Hello there.

Just to notify that nccl 2x is not working with chainer when using multiple GPU. I tried installing version for cuda 9.0 and cuda9.2, but the Grad norm moves between inf to nan only when those version are used. This was only tested on versions installed with apt.
To work with multiple GPU, by the moment, build the nccl lib from the git (ver.1.x).

I would like to know if someone else tried multiple gpu with a different SetUp.

**Comment by sw005320** [comment]
Thanks. I'm actually using nccl_2.1.15-1+cuda8.0_x86_64 and did not have an issue. So, it would come from some specific versions/environments.

**Comment by Fhrozen** [comment]
Some details of my environ:
- CUDA 9.0 (installed by apt)
- CUDNN 7.0 (installed by apt)
- Chainer, cupy == 4.0 (installed by pip)

 I did not try to download the file from the NVIDIA website, so I am not sure if this is just related to apt or NCCL or some setups in my PC. But after making from pip. I did not have any trouble.

**Comment by lahirufano** [comment]
When I try to use multi-gpu training it gets stuck. 

Could anyone tell me the exact versions that are used to train with multiple GPUs for the code in master? 

I tried with multiple versions for CUDA, CUDNN and NCCL with no success.  I appreciate if someone can list working versions for above mentioned tools.

**Comment by Fhrozen** [comment]
Getting stuck when using multi-gpu is a problem with the configuration of the ACS (most of the time).
The short solution could be found in this link (https://github.com/NVIDIA/caffe/issues/10). 
```
#!/usr/bin/env bash
for i in $(lspci -d "10b5:" | awk '{print $1}') ; do
       o=$(lspci -vvv -s $i | grep ACSCtl)
       if [ $? -eq 0 ] ; then
               echo $o | grep "+"
               if [ $? -eq 0 ] ; then
                       setpci -s $i f2a.w=0000
               fi
       fi
done
```
And more details about similar problem on different framkeworks can be found here (https://devtalk.nvidia.com/default/topic/883054/multi-gpu-peer-to-peer-access-failing-on-tesla-k80-/?offset=26 https://www.linuxquestions.org/questions/linux-newbie-8/howto-list-all-users-in-system-380426/ https://www.supermicro.com/support/faqs/faq.cfm?faq=20732 https://github.com/pytorch/pytorch/issues/1637) 

I also have the same problem using docker in a server but I cannot check the values on the server. I checked in my computer, and the `ACSCtl:	SrcValid ` is set to `-`, that is why I have no problems running in my computer. 

Could you please confirm this?.

**Comment by lahirufano** [comment]
@Fhrozen You are correct. Disabling ACS resolved the issue. Thanks a lot!

**Comment by sw005320** [comment]
Thanks @Fhrozen, can you add this description somewhere in README? (adding short descriptions and link to this issue is fine).

**Comment by kan-bayashi** [comment]
This problem seems to be solved. I closed this issue.
