### ISSUE TITLE
pause bettween sentences in TTS

### ISSUE THREAD

**Issue by EsmaeilFarhang** [espnet/espnet#1851]
I've trained transformer and fastspeech. used egs/jsut config parameters(just train char base ). 
but after training, those models cannot pause after the sentence is over and start another sentence. 
in the case of fastspeech speed of reading is faster.
some examples are in below:

[samples.zip](https://github.com/espnet/espnet/files/4496141/samples.zip)

**Comment by unilight** [comment]
I think it depends on your training data. If your speech data contains a pause after the end of a sentence (depending on periods, maybe?), then the model should be able to learn to do that.

**Comment by EsmaeilFarhang** [comment]
thank you,
the training data don't contain two sentences in a row(each sentence ending with ? or .). but I think The same goes for LJspeech data.

**Comment by kan-bayashi** [comment]
How about adding a comma between text?

**Comment by EsmaeilFarhang** [comment]
> How about adding a comma between text?

The model can recognize comma. the training data contains a lot of commas.
training data is about 11 hours.

**Comment by kan-bayashi** [comment]
In that case, maybe you can use comma as pause symbol.
Why don't you check add the comma to the place you want to add pause?

**Comment by EsmaeilFarhang** [comment]
> In that case, maybe you can use comma as pause symbol.
> Why don't you check what is happened when adding the comma to the place you want to add pause?

I've done that, but comma can't convey the sense of ending sentences, like something for LJspeech data with tacotron2 or ....
