### ISSUE TITLE
Text degeneration issue

### ISSUE THREAD

**Issue by Daniel-asr** [espnet/espnet#1854]
Hey everyone,

At the moment, we are working on 15h of LibriSpeech with an attention-only transformer model that we extracted in order to run in faster iterations. But although we achieve a CER of 0.23 and a WER of 0.47, we are facing the problem of text degeneration, which increases our CER and WER greatly.

We've found in the literature this great [article by Amazon](https://arxiv.org/pdf/2002.05150.pdf), where they also executed their research on ESPnet and found the same text degeneration problem, which they solved using a Poisson distribution to predict and truncate the output maximum length. We have tried different model configurations/sizes and various decoding parameters, but like they had mentioned in the article it didn't help.

I was wondering if you faced this problem as well and if so, how have you managed to solve it.

Thank you very much,
Daniel

**Comment by sw005320** [comment]
Thanks for the interesting discussions.
I have never tried length prediction for this issue, but it's worth considering it.
Is there someone interested in working on it?

Our solution is to control the following parameters
```
penalty: 
maxlenratio: 
minlenratio: 
```
Probably the coverage term helps to improve the performance but our initial investigation shows that attention/CTC joint decoding is better (https://www.aclweb.org/anthology/P17-1048.pdf) not only in terms of the performance but also easiness of tuning.
But this makes the decoding complicated. Also, it assumes very strict monotonic alignments and it would not be adequate for other tasks.

**Comment by Daniel-asr** [comment]
Thank you for the fast and useful answer.

We have tried several parameters and configurations (including penalty and min/max len ratio) but unfortunately didn't mitigate the text degeneration issue as we want.

At the moment, we are working in pure attention mode but we will try now with CTC.

Is there is anyone working on the coverage implementation?
