### ISSUE TITLE
Conversion of acoustic models trained with ESPnet to Kaldi format

### ISSUE THREAD

**Issue by deeplearner01** [espnet/espnet#1859]
Hi

Can you please advise whether there is a script to make the conversion of acoustic models trained with ESPnet, for instance the model.acc.best files, to kaldi (nnet3 or nnet1) format?

Thank you very much.

DL

**Comment by sw005320** [comment]
No, we don't have such a conversion tool.
Kaldi acoustic models and espnet e2e models have different roles and cannot have a simple conversion.

**Comment by deeplearner01** [comment]
Thank you for the answer.
