### ISSUE TITLE
Fastest configuration to train a Transformer based end-to-end ASR model using Librispeech data

### ISSUE THREAD

**Issue by rppravin** [espnet/espnet#1862]
I have a multi-GPU machine (8 gpus). I wanted to to be able to quickly (in a day or two) train a reasonably performing end-to-end ASR model using Librispeech data, Transformer based architecture.

Can you please point me to an existing configuration file (yaml) or a new set of configuration that would hep me achieve this?

**Comment by sw005320** [comment]
This is the configuration with 4 GPUs (https://github.com/espnet/espnet/blob/master/egs/librispeech/asr1/conf/tuning/train_pytorch_transformer_large_ngpu4.yaml).
I think you can just use it.
You may need to tune `batch-bins` to make it faster.

**Comment by rppravin** [comment]
Thanks for the reply.

train_pytorch_transformer_large_ngpu4.yaml says that the configuration requires 4 gpus with 12 GB memory. But each of my GPU has only 10 GB memory.  Can you please let me know how can I tune the configuration file for this reduced memory?

**Comment by sw005320** [comment]
You can control the GPU memory with `batch-bins`. (see https://espnet.github.io/espnet/tutorial.html#how-to-set-minibatch)

**Comment by rppravin** [comment]
Thank you.
