### ISSUE TITLE
Freeze modules bug?

### ISSUE THREAD

**Issue by jxzhanggg** [espnet/espnet#1863]
https://github.com/espnet/espnet/blob/25862dd93081746ac623720f31f4f0f323c9750e/espnet/tts/pytorch_backend/tts.py#L331-L334

Do you think to freeze the module of the model, the line should be change into:
 if any(mod.startswith(key) for key in args.freeze_mods): 
?

**Comment by kan-bayashi** [comment]
Thank you for your report, @jxzhanggg.
You are right. I fixed in #1865.

**Comment by unilight** [comment]
Sorry for this mistake I made ... Thank you @kan-bayashi !
