### ISSUE TITLE
Further training of the ASR model

### ISSUE THREAD

**Issue by SazerLife** [espnet/espnet#1864]
Hi everyone!
First I would like to thank the author for the library. It's really helpful for me.

I got into ASR not so long ago and I have a question:
Is it able to execute additional training an existing "ru_open_stt" model using ESPnet toolkit?

This question concerns both the linguistic model and the acoustic model. Can I improve at least one of them using my data?

**Comment by sw005320** [comment]
Yes. If you follow our data preparation step with your data and make your data with our data format (data directory), you can just combine it with existing data (e.g., see https://github.com/espnet/espnet/blob/334aac95f207257da2fba3111c5654647b308494/egs/chime4/asr1/run.sh#L108-L111)

**Comment by SazerLife** [comment]
But in this case, I need to retrained model with my data, right? I thought about using already trained on o_stt model (https://drive.google.com/open?id=1zQfeMObvxAbVjE8vGyse4b0hz6q-lGMD) and add to it my data

**Comment by SazerLife** [comment]
> > Yes. If you follow our data preparation step with your data and make your data with our data format (data directory), you can just combine it with existing data (e.g., see
> > https://github.com/espnet/espnet/blob/334aac95f207257da2fba3111c5654647b308494/egs/chime4/asr1/run.sh#L108-L111
> > 
> > )

But in this case, I need to retrained model with my data, right? I thought about using already trained on o_stt model (https://drive.google.com/open?id=1zQfeMObvxAbVjE8vGyse4b0hz6q-lGMD) and add to it my data

**Comment by sw005320** [comment]
Oh, I see.
You are talking about re-training. 
I personally don't do it so often, but you can find a way in some issues.

@b-flo, can you point out it to @SazerLife?
Also, can you make one paragraph document about fine tuning in https://espnet.github.io/espnet/tutorial.html?
This is one of the most frequent questions.

**Comment by SazerLife** [comment]
> You are talking about re-training.

I guess we don't understand each other. Maybe I spoke not enough exactly. I mean "Transfer learning". Is there already an issue with this topic? Just I couldn't find it.

**Comment by sw005320** [comment]
RNN-T and speech translation are based on "transfer learning" (I just followed your terminology to avoid your confusion). We can wait for @b-flo's answer.

**Comment by b-flo** [comment]
Hi,

For transfer learning, the available options are these ones:

https://github.com/espnet/espnet/blob/master/espnet/bin/asr_train.py#L355-L378

We separated encoder (`--enc-init`) and decoder (`--dec-init`) initialization however you can specify the same model for both. The options take a snapshot/model path.
You can also choose the modules you want to initialize or discard for your new training.

> Also, can you make one paragraph document about fine tuning in https://espnet.github.io/espnet/tutorial.html?

Sure, I'll do that!

**Comment by SazerLife** [comment]
> Hi,
> 
> For transfer learning, the available options are these ones:
> 
> https://github.com/espnet/espnet/blob/master/espnet/bin/asr_train.py#L355-L378
> 
> We separated encoder (`--enc-init`) and decoder (`--dec-init`) initialization however you can specify the same model for both. The options take a snapshot/model path.
> You can also choose the modules you want to initialize or discard for your new training.
> 
> > Also, can you make one paragraph document about fine tuning in https://espnet.github.io/espnet/tutorial.html?
> 
> Sure, I'll do that!
 Thank you! I think it's that I need)

**Comment by yash-s20** [comment]
One more thing to mention when initialising a model for transfer learning - remember to use the same units file (that is generated as the dictionary of tokens in stage 2) that was used in training the model itself, else the dimensions won't match (if you have different or new tokens in the new data).

**Comment by SazerLife** [comment]
Hi again! 
I have a new problem with this topic:

I tried to prepare data for training but realized that I have no "train_unigram100.model" which used for this ASR model. I trained a new one on my data. But because of some unigrams that it selects that not in the glossary, I have a lot of "<unk>" symbols. 

Can you get a more qualitative solution?
