### ISSUE TITLE
Does inference based on transformer model support GPU decoding?

### ISSUE THREAD

**Issue by rppravin** [espnet/espnet#1874]
Hi, can you tell me if GPU decoding has been added for inference based on transformer model?

When I look at run.sh in Librispeech recipe for example, I see that CPU decoding has been forced in the inference stage (stage 5).

**Comment by ahmedalbahnasawy** [comment]
yes it supports GPU decoding. Read here https://espnet.github.io/espnet/tutorial.html#use-of-gpu
and set batch-size=1

**Comment by rppravin** [comment]
Thank you.
