### ISSUE TITLE
docker ljspeech/tts1 import tacotron.cleaners, espnet2

### ISSUE THREAD

**Issue by sunnybala** [espnet/espnet#1876]
Hi,

I'm having import issues when I run (only some) recipes through Docker. After checking that the docker/build tests were fine and training a few different ASR models without trouble, I tried ljspeech/tts1 and hit a few errors. 

### tacotron_cleaner ###
I'm running docker based on the commands from the tutorial (which have been successful for a few ASR recipes already, so I decided to try TTS).

`./run.sh --docker_egs ljspeech/tts1 10.0 --docker_cmd run.sh --docker_gpu 0 --verbose 1 --backend pytorch --ngpu 1 --tag attempt2`

This produces the following.

> stage -1: Data Download 
already exists. skipped. 
stage 0: Data preparation 
finished making wav.scp, utt2spk, spk2utt. 
**Traceback (most recent call last): 
  File "local/clean_text.py", line 10, in <module> 
    from tacotron_cleaner.cleaners import custom_english_cleaners 
ModuleNotFoundError: No module named 'tacotron_cleaner'** 
finished making text. 
utils/validate_data_dir.sh: WARNING: you have only one speaker.  This probably a bad idea. 
   Search for the word 'bold' in http://kaldi-asr.org/doc/data_prep.html 
   for more information. 
utils/validate_text.pl: ERROR: file 'data/char_train/text' is empty or does not exist 
run.sh done. 

I looked around for tacotron_cleaner and couldn't find it in this repo, but did find it in the espnet_tts_frontend -- one way around this is that I can modify the run.sh script for the recipe to install that.

`git clone https://github.com/espnet/espnet_tts_frontend`
`pip install -e espnet_tts_frontend`

### espnet2 ###
However after this I run into another import issue. The bash warning:

> run.pl: 32 / 32 failed, log is in exp/char_make_fbank/train/make_fbank_char_train.*.log

The entry from one of the 32 log files:
>Traceback (most recent call last):
  File "/espnet/egs/ljspeech/tts1/../../../utils/compute-fbank-feats.py", line 16, in <module>
    from espnet2.utils.types import int_or_none
ModuleNotFoundError: No module named 'espnet2'

**Is there some additional setup I'm supposed to do before I run the docker command to avoid this?** 

Happy to provide any other info. 

### additional details ###
I am running ubuntu 18.04 with an GTX 1070.  

Here's what the run.sh expands the docker command out to:
> docker run --gpus 'device=0' -i --rm --name espnet_gpu0_20200425T1102 -v /mnt/B/models/espnet/egs:/espnet/egs -v /mnt/B/models/espnet/espnet:/espnet/espnet -v /mnt/B/models/espnet/test:/espnet/test -v /mnt/B/models/espnet/utils:/espnet/utils espnet/espnet:gpu-cuda10.0-cudnn7-u18-user-sunny /bin/bash -c 'cd /espnet/egs/ljspeech/tts1; ./run.sh '

Here's what I see if I run check_install in the interactive instance.
>. venv/bin/activate; python check_install.py --no-cupy --torch-version 1.0.1 
INFO: python version = 3.7.3 (default, Mar 27 2019, 22:11:17)  
[GCC 7.3.0] 
INFO: library availableness check start. 
INFO: # libraries to be checked = 8 
INFO: --> espnet is installed. 
INFO: --> kaldiio is installed. 
INFO: --> matplotlib is installed. 
INFO: --> torch is installed. 
INFO: --> chainer is installed. 
INFO: --> chainer_ctc is installed.
INFO: --> warprnnt_pytorch is installed. 
INFO: --> warpctc_pytorch is installed. 
INFO: library availableness check done. 
INFO: 8 / 8 libraries are correctly installed. 
INFO: library version check start. 
INFO: # libraries to be checked = 4 
INFO: --> torch version is matched. 
INFO: --> chainer version is matched. 
INFO: --> warprnnt_pytorch version is matched. 
INFO: --> warpctc_pytorch version is matched. 
INFO: library version check done. 
INFO: 4 / 4 libraries are correct version. 
INFO: cuda availableness check start. 
INFO: --> cuda is available in torch. 
INFO: --> cudnn is available in torch. 
INFO: --> cuda is available in chainer. 
INFO: --> cudnn is available in chainer. 
INFO: --> nccl is installed. 
WARNING: --> it seems that only single gpu is available. 
WARNING: --> maybe your machine has only one gpu. 
INFO: cuda availableness check done.

**Comment by sw005320** [comment]
I think this is because we did not update the docker, @Fhrozen?

**Comment by Fhrozen** [comment]
About tacotron_cleaner is because is not installed. I think that most of the tools for tts are not installed so I will need to check and add this. 
About espnet2. As @sw005320 said. this is because docker was not updated after the last update. I will try to fix it ASAP. 
Meanwhile, you can add the folders egs2 and espnet 2 in the following line:
https://github.com/espnet/espnet/blob/90ea8c788075d4b8b6bd71250268da61309cf2a2/docker/run.sh#L117

**Comment by sunnybala** [comment]
ah got it, thank you both!

**Comment by Fhrozen** [comment]
This issue should be solved by #1909 .
Please Try it and let me know if there is any problem. 
Best.
