### ISSUE TITLE
Where is the lexicon file on TIMIT for ASR?

### ISSUE THREAD

**Issue by ReinholdM** [espnet/espnet#1877]
I know the espnet has two kinds of modeling granularity, which are "char" and "phn". Now I want to know whether there is a **lexicon file** to represent the relationship between them on espnet or not.

**Comment by sknadig** [comment]
There is no lexicon file as such. The recipe uses kaldi style data preparation to read PHN files in the dataset.
You could match the sample numbers from PHN and WRD files to get the mapping of a word to a sequence of phones.
