### ISSUE TITLE
ModuleNotFoundError: No module named 'espnet'

### ISSUE THREAD

**Issue by chengdongliang** [espnet/espnet#1882]
apply-cmvn --norm-vars=true data/train_100/cmvn.ark scp:exp/dump_feats/train/feats.16.scp ark:- 
Traceback (most recent call last):
  File "/home/Liangcd/Espnet/espnet/egs/librispeech/asr1/../../../utils/copy-feats.py", line 6, in <module>
    from espnet.transform.transformation import Transformation
ModuleNotFoundError: No module named 'espnet'

**Comment by sw005320** [comment]
You may not correctly install espnet.
Please check https://espnet.github.io/espnet/installation.html

**Comment by jiamliang** [comment]
I meet this Error too, i run in docker container, and map local folder in docker container. 
workaround:
export PYTHONPATH=/path/to/you/code/espnet:${PYTHONPATH}

**Comment by Esdsnqxz** [comment]
> I meet this Error too, i run in docker container, and map local folder in docker container.
> workaround:
> export PYTHONPATH=/path/to/you/code/espnet:${PYTHONPATH}

hi,i met the same problem ,what do you mean about '/path/to/you/code/espnet' in container? thanks.

**Comment by jiamliang** [comment]
> > I meet this Error too, i run in docker container, and map local folder in docker container.
> > workaround:
> > export PYTHONPATH=/path/to/you/code/espnet:${PYTHONPATH}
> 
> hi,i met the same problem ,what do you mean about '/path/to/you/code/espnet' in container? thanks.

the location of your "espnet" code.
