### ISSUE TITLE
decode time of transducer of espnet1 is slower.

### ISSUE THREAD

**Issue by shanguanma** [espnet/espnet#1883]
Hi everyone.
@b-flo,
I now test transducer model of espnet1, however I found its decoding stage is very time-consuming(about 11 hours test, but it takes three days). I think it may be wrong, however  I don't know where is wrong?

Note: I decode test set by using cpu, its job is 32.

decode config is as follows:

`espnet/egs/vivos/asr1/conf/tuning/transducer/decode_transducer.yaml`

```
# decoding parameters
batch: 0
beam-size: 20
score-norm-transducer: True
```

rnnlm config is as follows:

```
# common configure
opt: sgd        # or adam
sortagrad: 0 # Feed samples from shortest to longest ; -1: enabled for all epochs, 0: disabled, other: enabled for 'other' epochs
batchsize: 64   # batch size in LM training
epoch: 20      # if the data size is large, we can reduce this
patience: 3
maxlen: 100     # if sentence length > lm_maxlen, lm_batchsize is automatically reduced

# related configuration
model-module: default  # in espnet 0.5.2, it contains three kinds of lm ,they are default,seq_rnn,transformer
type: lstm             # choices=['lstm', 'gru'],Which type of RNN to use 
layer: 2               # Number of hidden layers
unit: 650   # Number of hidden units in feedforward layer
dropout-rate: 0.5
```

**Comment by b-flo** [comment]
Hi,

Inference part is rather slow for transducer model because we focused on performance for now. Other search algorithm will be added soon, it will be considerably faster and also enable batch decoding.

Could you share your network config please and which dataset you're working on?
Also, what do you mean by "(about 11 hours test, but it takes three days)"?

**Comment by shanguanma** [comment]
Thanks for your quickly reply. 

> Could you share your network config please and which dataset you're working on?

network config is from espnet/egs/vivos/asr1/conf/tuning/transducer/{train_transducer.yaml,train_transformer-rnn_transducer.yaml,train_transformer_transducer.yaml}
Data set is about 110 hours mandarin English code-switch corpus,  train set is about 101 hours , test set is 11 hours , however it is a non-public data set. 

> Also, what do you mean by "(about 11 hours test, but it takes three days)"?
when I use the decode config(e.g: espnet/egs/vivos/asr1/conf/tuning/transducer/espnet/egs/vivos/asr1/conf/tuning/transducer) with rnnlm to decode this test set,  It takes about three days to completely decode, Time is very long. 

However, compared with pure ctc (e.g: it is warp-ctc of epsnet1) model, this transducer performance is less than CTC performance  on above corpus.

**Comment by b-flo** [comment]
OK. I won't comment on the performance part then, you're gonna have to do some test/tuning by yourself to find a suitable network configuration. However, you should except better performances than CTC for similar configs.

For inference time: given the configs and number of jobs, 3 days to decode a 11-hour dataset seems awfully long, even with a 2-layer RNNLM.
What about inference time without RNNLM?

**Comment by shanguanma** [comment]
> OK. I won't comment on the performance part then, you're gonna have to do some test/tuning by yourself to find a suitable network configuration. However, you should except better performances than CTC for similar configs.

Yes, I will tune config of transducer  for my corpus to improve its performance. 

>  For inference time: given the configs and number of jobs, 3 days to decode a 11-hour dataset seems awfully long, even with a 2-layer RNNLM.

Yes , it looks like very strange. it customs too long time.  I use join ctc with encode-decode (e.g: RNN or transformer) network based on espnet. On this test set of corpus,   inference time is  about an hour and a half in "api v1". 

> What about inference time without RNNLM? Also, does your test corpus have any special "features" (e.g: really long utterances)?

Yes, I have decoded this test set without lm, (e.g: add lm-weight: 0.0 to decode config, is correct?),it is running , this test corpus doesn't really long utterances. Its longest utterance is about 28 seconds.

**Comment by b-flo** [comment]
> Yes, I have decoded this test set without lm, (e.g: add lm-weight: 0.0 to decode config, is correct?),

In fact, if rnnlm is specified, LM probs will be computed. Sorry about that, I should add a test for this case.

**Comment by BuaaAlban** [comment]
> > Yes, I have decoded this test set without lm, (e.g: add lm-weight: 0.0 to decode config, is correct?),
> 
> In fact, if a rnnlm is specified, LM probs will be computed. Sorry about that, I should add a test for this case.

Hi, I have used the default config for transformer train.yaml for librispeech, for stage5 decode, I have runned for 10 minutes without using an rnnlm, although the ngpu=4, I found this step didn't use GPU, how long it takes to get the result?
(I have commented this line for asr_recog.py #--rnnlm ${lmexpdir}/${lang_model})

the following is the log.
`$sh run.sh --train-config conf/train.yaml --stage 5
dictionary: data/lang_char/train_960_unigram5000_units.txt
stage 5: Decoding
best val scores = [0.93001271 0.92760211 0.92465866 0.92100396 0.91768747]
selected epochs = [19 18 17 16 15]
average over ['exp/train_960_pytorch_train_specaug/results/snapshot.ep.19', 'exp/train_960_pytorch_train_specaug/results/snapshot.ep.18', 'exp/train_960_pytorch_train_specaug/results/snapshot.ep.17', 'exp/train_960_pytorch_train_specaug/results/snapshot.ep.16', 'exp/train_960_pytorch_train_specaug/results/snapshot.ep.15']
2020-07-02 15:56:37,874 (splitjson:43) INFO: /proj/xcdhdstaff1/bokangz/anaconda3/envs/espnet/bin/python3 /scratch/workspace/bokangz/project/espnet-master/egs/librispeech/asr1/../../../utils/splitjson.py --parts 32 dump/test_other/deltafalse/data_unigram5000.json
2020-07-02 15:56:37,875 (splitjson:43) INFO: /proj/xcdhdstaff1/bokangz/anaconda3/envs/espnet/bin/python3 /scratch/workspace/bokangz/project/espnet-master/egs/librispeech/asr1/../../../utils/splitjson.py --parts 32 dump/test_clean/deltafalse/data_unigram5000.json
2020-07-02 15:56:37,875 (splitjson:43) INFO: /proj/xcdhdstaff1/bokangz/anaconda3/envs/espnet/bin/python3 /scratch/workspace/bokangz/project/espnet-master/egs/librispeech/asr1/../../../utils/splitjson.py --parts 32 dump/dev_clean/deltafalse/data_unigram5000.json
2020-07-02 15:56:37,875 (splitjson:43) INFO: /proj/xcdhdstaff1/bokangz/anaconda3/envs/espnet/bin/python3 /scratch/workspace/bokangz/project/espnet-master/egs/librispeech/asr1/../../../utils/splitjson.py --parts 32 dump/dev_other/deltafalse/data_unigram5000.json
2020-07-02 15:56:37,911 (splitjson:55) INFO: number of utterances = 2620
2020-07-02 15:56:37,912 (splitjson:55) INFO: number of utterances = 2939
2020-07-02 15:56:37,915 (splitjson:55) INFO: number of utterances = 2703
2020-07-02 15:56:37,915 (splitjson:55) INFO: number of utterances = 2864
`
