### ISSUE TITLE
Transformer v3 with phoneme input (not character)

### ISSUE THREAD

**Issue by marcosnetopires** [espnet/espnet#1884]
I'm trying to train a Transformer.v3 with LJspeech recipe for TTS with phonemes as inputs, but the preparation stages only output dictionary of characters. How do I signal the ./run.sh command that I need a phoneme dictionary? 
The configuration file for Transformer.v3 with char is the exact same as with phonemes.
Can't find any documentation regarding this, but in the link below there are specified 2 different models of Transformer V3, one with char and another with phonemes, which makes me believe that it is possible.
[https://github.com/espnet/espnet/blob/master/egs/ljspeech/tts1/RESULTS.md](url)

**Comment by kan-bayashi** [comment]
Please use `--trans_type` option.
E.g. `./run.sh --trans_type phn --stage 0`

**Comment by marcosnetopires** [comment]
It worked, thanks!
And thanks for the lightning fast reply
