### ISSUE TITLE
Some questions about transfer learning in ESPnet

### ISSUE THREAD

**Issue by SazerLife** [espnet/espnet#1887]
Hi everyone! 
I tried to train a new model based on the existing ru_open_std using:
https://github.com/espnet/espnet/blob/master/espnet/bin/asr_train.py#L355-L378
The training was completed successfully and I got the result, but the quality of the model became worse.
In this regard, I have several questions:

1. I tried to prepare data for training but realized that I have no "train_unigram100.model" which used for this ASR model. I trained a new one on my data. But because of some unigrams that it selects not in the dictionary, I have a lot of "unk" symbols. Can you get a more qualitative solution?

2. I assume that the degradation is also because learning occurs across all layers, is there an option in Asp net to freeze some layers?

3. And the last question - I couldn't figure out for a long time how to specify the modules that my model uses, until I looked at the parser. In the end this is what this part of my command looks like:
```
--enc-init-mods encoder.embed.conv.0.weight,encoder.embed.conv.0.bias,encoder.embed.conv.2.weight,encoder.embed.conv.2.bias,encoder.embed.out.0.weight,encoder.embed.out.0.bias,encoder.encoders.0.self_attn.linear_q.weight,encoder.encoders.0.self_attn.linear_q.bias,encoder.encoders.0.self_attn.linear_k.weight,encoder.encoders.0.self_attn.linear_k.bias,...
```
Is there any way to shorten this entry?

**Comment by b-flo** [comment]
Hi,

1. Could you share some more details on your process please? Stages re-done, details on the new BPE model, modules you transfered, etc.

2. For what I remember, freezing layer option was discarded because there was not so much interest at that time. I can add it or explain how to do it though, it's rather straightforward.

3. You don't need to specify each modules, only a partial match (beginning) is needed.
Let's say you want to transfer all encoder modules: `encoder.` would suffice. If you want embedding layer and first layer: `encoder.embed.,encoder.0.` would do the job. Etc.
I'll add some documentation for transfer learning, sorry about that.

**Comment by SazerLife** [comment]
> 1. Could you share some more details on your process please? Stages re-done, details on the new BPE model, modules you transfered, etc.

So looks my data preparation part of `run.sh`. I just hardcoded path to the dictionary (`dict` variable) and commented blocks that edit it.
```
dict=espnet-ru-open-stt/data/lang_char/train_unigram100_units.txt
bpemodel=data/lang_char/${train_set}_${bpemode}${nbpe}
echo "dictionary: ${dict}"
if [ ${stage} -le 2 ] && [ ${stop_stage} -ge 2 ]; then
    ### Task dependent. You have to check non-linguistic symbols used in the corpus.
    echo "stage 2: Dictionary and Json Data Preparation"
    mkdir -p data/lang_char/
#     echo "<unk> 1" > ${dict} # <unk> must be 1, 0 will be used for "blank" in CTC
    cut -f 2- -d" " data/${train_set}/text > data/lang_char/input.txt
    spm_train --input=data/lang_char/input.txt --vocab_size=${nbpe} \
	--model_type=${bpemode} --model_prefix=${bpemodel} --input_sentence_size=100000000
#     spm_encode --model=${bpemodel}.model --output_format=piece < data/lang_char/input.txt | tr ' ' '\n' | sort | uniq | awk '{print $0 " " NR+1}' >> ${dict}
#     wc -l ${dict}

    # make json labels
    data2json.sh --feat ${feat_tr_dir}/feats.scp --bpecode ${bpemodel}.model \
        data/${train_set} ${dict} > ${feat_tr_dir}/data_${bpemode}${nbpe}.json
```


> 2. For what I remember, freezing layer option was discarded because there was not so much interest at that time. I can add it or explain how to do it though, it's rather straightforward.

I would appreciate it if you could do some of this. I am a novice and probably do not have sufficient knowledge of this process.


> 3. You don't need to specify each modules, only a partial match (beginning) is needed.
>    Let's say you want to transfer all encoder modules: `encoder.` would suffice. If you want embedding layer and first layer: `encoder.embed.,encoder.0.` would do the job. Etc.
>    I'll add some documentation for transfer learning, sorry about that.

Thanks, I'll try to run it so next time!

**Comment by b-flo** [comment]
Hi,

Sorry I had some works to deal with. I proposed a PR ( #1897 ) to add a freezing option which should be available soon (or you can do the modification manually if you don't want to wait).

About `1.`, if I understand correctly, you trained a new BPE model on your own data which you used to encode the training text (from ru-stt or you own). However, you have a lot of OOV words.
In that case, why don't you increase the number of subwords to model? After that you could remove the output layer in transfer learning and specify a new output dimension.

P.S : editing a message to add a ping won't notify the user if he was already notified for the original message ;)

**Comment by SazerLife** [comment]
Thank you very much for your response and for the work you are doing! This is cool. I'll try to follow your instructions.
> Sorry I had some works to deal with. I proposed a PR ( #1897 ) to add a freezing option which should be available soon (or you can do the modification manually if you don't want to wait).

Yeah, you understood correctly. But I don't have a lot of data and I'm afraid that this may lead to a deterioration of the model, and increasing the number of words may increase the recognition time.

> About `1.`, if I understand correctly, you trained a new BPE model on your own data which you used to encode the training text (from ru-stt or you own). However, you have a lot of OOV words.
> In that case, why don't you increase the number of subwords to model? After that you could remove the output layer in transfer learning and specify a new output dimension.

Oh, ok. I got it. Thx! :)
> P.S : editing a message to add a ping won't notify the user if he was already notified for the original message ;)
