### ISSUE TITLE
pytorch instllation

### ISSUE THREAD

**Issue by sw005320** [espnet/espnet#19]
I'm just trying to play with the pytorch backend.
Here is my note:
```
$ cd egs/wsj/asr1
$ . ./path.sh
$ pip install pip --upgrade
$ pip install http://download.pytorch.org/whl/cu80/torch-0.3.0.post4-cp27-cp27mu-linux_x86_64.whl
$ pip install torchvision
```

Then,
```
$ ./run.sh --stage 3 --gpu jhu --backend pytorch
```
Then, I got the error:
```
Traceback (most recent call last):
  File "/export/a08/shinji/201707e2e/espnet_dev/egs/wsj/asr1/../../../src/bin/asr_train_th.py", line 567, in <module>
    main()
  File "/export/a08/shinji/201707e2e/espnet_dev/egs/wsj/asr1/../../../src/bin/asr_train_th.py", line 433, in main
    e2e = E2E(idim, odim, args)
  File "/export/a08/shinji/201707e2e/espnet_dev/src/nets/e2e_asr_attctc_th.py", line 152, in __init__
    self.ctc = CTC(odim, args.eprojs, args.dropout_rate)
  File "/export/a08/shinji/201707e2e/espnet_dev/src/nets/e2e_asr_attctc_th.py", line 247, in __init__
    from warpctc_pytorch import CTCLoss
ImportError: No module named warpctc_pytorch
```

**Comment by ShigekiKarita** [comment]
you need this because pytorch has not have its official ctc implementation
now

https://github.com/SeanNaren/warp-ctc/tree/pytorch_bindings/pytorch_binding

2017/12/18 15:09 "Shinji Watanabe" <notifications@github.com>:

**Comment by kan-bayashi** [comment]
Hi. 
Which libraries should we mainly focus on?
Chianer or pytorch?

**Comment by ShigekiKarita** [comment]
I think that chainer should be main at least until pytorch issues (loss normalization, vgg implementation in #9)  are closed

**Comment by sw005320** [comment]
@ShigekiKarita , can you please provide the installation of warp-ctc/pytorch_binding

**Comment by ShigekiKarita** [comment]
you can see it in my wip Makefile
https://github.com/espnet/espnet/pull/20/files


2017/12/19 16:17 "Shinji Watanabe" <notifications@github.com>:

**Comment by sw005320** [comment]
#33 fixed this issue.

**Comment by Arafat4341** [comment]
Hello everyone! I tried to synthesize example text with pre-trained models. I get this:
`Traceback (most recent call last):`
  `File "/home/arafat/espnet/egs/ljspeech/tts1/../../../utils/merge_scp2json.py", line 15, in <module>
    from espnet.utils.cli_utils import get_commandline_args`
`ModuleNotFoundError: No module named 'espnet'`
