### ISSUE TITLE
espnet2 nan during asr training

### ISSUE THREAD

**Issue by xforceco** [espnet/espnet#1903]
During asr training stage in espnet2, there are many nan warnings
`WARNING: The grad norm is nan. Skipping updating the model.`

Also, later on it crashes with
`RuntimeError: CUDA out of memory. Tried to allocate 844.25 MiB (GPU 0; 10.92 GiB total capacity; 9.52 GiB already allocated; 307.00 MiB free; 574.70 MiB cached)`
It seems the cache is not automatically managed and freed properly, because keep reducing the batch size does not make a difference.

These errors don't appear in espnet1.

**Comment by b-flo** [comment]
Hi,

> These errors don't appear in espnet1.

These errors can appear in espnet1. If you're directly comparing a experiment you did in espnet1 and you ported in espnet2, can you please specify: dataset you're working on, environnement, configuration you used in both versions, etc.

**Comment by kamo-naoyuki** [comment]
> `RuntimeError: CUDA out of memory. Tried to allocate 844.25 MiB (GPU 0; 10.92 GiB total capacity; 9.52 GiB already allocated; 307.00 MiB free; 574.70 MiB cached)`
> It seems the cache is not automatically managed and freed properly, because keep reducing the batch size does not make a difference.

I haven't met such problem yet. I think you may misunderstand something.

**Comment by xforceco** [comment]
Hi, I am using my own data that is >100 hours, on the aishell/wsj configuration by skipping stage 1 (because my own data is already in kaldi format)
I do not modify asr.sh, so I think it is straightforward to reproduce these errors

Below is my environment setup
- PyTorch: 1.0.1
- espnet: master

**Comment by kamo-naoyuki** [comment]
I guess your data just has too long sequence. I don't think there are a memory issue. I could notice it.
However, we can't distinguish whether your data has some problem or not. Please report an issue with not your own data.

**Comment by xforceco** [comment]
> I guess your data just has too long sequence. I don't think there are a memory issue. I could notice it.
> However, we can't distinguish whether your data has some problem or not. Please report an issue with not your own data.

I see, the sentence length thing is a good hint.
Let me try running experiments with public data and compare the data characteristics first, thanks.

**Comment by AdolfVonKleist** [comment]
The out-of-memory error can happen with overlong utterances, but running `https://github.com/espnet/espnet/blob/master/utils/remove_longshortdata.sh` on your dataset should eliminate it.

**Comment by xforceco** [comment]
1. For the `CUDA out of memory error`, I found it does not happen again when I aggressively reduce the network size (e.g. layer) and batch size at the same time.
- Because exactly the same data works perfectly in `espnet1` without the necessity of doing so, I try comparing the options between `espnet1` and `espnet2`
- I found `maxlen-in` and `maxlen-out` only appear in `espnet1` but NOT `espnet2` in `conf/train.yaml`
- without this option, according to what it describes, batch size will not automatically reduced according to input/output length, so it can cause occasionally crash in batches with long input/output
- is my above observation true? And is there any plan to extend `espnet2` with the above old options in the future, if so?

2. For the `NaN` thing, I still can't figure it out, it pops the warning ~200 times per epoch, for a training corpus ~1000 hrs with batch size = 10.
- Need some further investigation on the exact batch that causes the warning.
- Will do what @AdolfVonKleist suggested at the first place, thanks!

**Comment by kamo-naoyuki** [comment]
@xforceco Thank you for detail.

>    [-] I found `maxlen-in` and `maxlen-out` only appear in `espnet1` but NOT `espnet2` in `conf/train.yaml`

 `maxlen-in` and `maxlen-out` is referred as `fold_length` in espnet2.
See https://espnet.github.io/espnet/espnet2_training_option.html#change-mini-batch-type
`--batch_type numel` is better as far as memory efficiency.

I think the NAN error is no problem for training and we sometimes met it.

**Comment by xforceco** [comment]
Cool, batch_type numel solves the problem for rnn model training
