### ISSUE TITLE
torchaudio x espnet

### ISSUE THREAD

**Issue by sw005320** [espnet/espnet#1908]
I had a very good discussion with [torchaudio](https://github.com/pytorch/audio) people (@vincentqb and others).
They would seem to support several complex operations for our signal processing motivated neural networks used in ME2E.
I think it would be good to consider using it.

@kamo-naoyuki, @sas91, @Emrys365, do you have some comments about it? We could replace many functions used in ME2E with torchaudio ones.
I'm not sure we should also use torchaudio Kaldi readers because kaldiio is also very cool.

@kan-bayashi and @r9y9, do you have ideas/comments on the TTS side (e.g., GriffinLim?)?

**Comment by ahmedalbahnasawy** [comment]
@sw005320 I was able to infer Transformer ASR model using torchaudio and kaldi-io. I used Kaldi-io to extract pitch features which gives 1% improvement over fbank only.

**Comment by sw005320** [comment]
Sounds good.
As you may know, we also have our own Log Mel filiterbank and try to use both torchaudio and our own functions especially for standard ASR.
We're planning to put more emphasis on enhancement and separation (for ASR), and we'll try to use torchaudio more in this scenario.

**Comment by qmpzzpmq** [comment]
it seems the torchaudio recently could using gpu to extract fbank, I just test it.
