### ISSUE TITLE
ModuleNotFoundError: No module named 'espnet.bin'

### ISSUE THREAD

**Issue by murugeshmanthiramoorthi** [espnet/espnet#1913]
I was following the same procedure as in the [website](https://espnet.github.io/espnet/notebook/asr_cli.html), but I keep on getting this error 

ModuleNotFoundError: No module named 'espnet.bin' when I try to load  from espnet.bin.asr_recog import get_parser. 

But I did verify that the function actually exist in the [repo](https://github.com/espnet/espnet/blob/master/espnet/bin/asr_recog.py).

Can someone help me get rid of this error and continue with my project.

**Comment by sw005320** [comment]
This might be caused by some later refactoring.
Could you check it with older espnet (e.g., v.0.5.X?)

**Comment by sw005320** [comment]
@ShigekiKarita, do you know what happened?

**Comment by kamo-naoyuki** [comment]
@murugeshmanthiramoorthi I recommend you redoing the steps for installation. Probably, you just missed them. I summarized the information about Python installation: 

https://espnet.github.io/espnet/installation.html#step-3-a-installation-of-espnet

https://espnet.github.io/espnet/faq.html
