### ISSUE TITLE
Transducer multi-gpu error with status code 139

### ISSUE THREAD

**Issue by lilian0118** [espnet/espnet#1915]
When I use espnet/egs/mini_an4/asr1/conf/train_transducer.yaml or espnet/egs/vivos/asr1/conf/tuning/transducer/train_transducer.yaml config to train a RNN-T model, I meet a strange problem:
    If ngpu is larger than one, the train shell script will  exit with status 139 at hundreds of iterations. But if ngpu = 1, the train will success. I also changed the "etype" in "encoder" to "lstmp" and "blstm", if ngpu > 1, the train will exit with status 139.
    When I changed the train config to espnet/egs/vivos/asr1/conf/tuning/transducer/train_transformer-rnn_transducer.yaml, the train will success no matter ngpu > 1 or ngpu = 1.

My experiment environments is below:
- python version: `3.6.4 `
- espnet version: `espnet 0.7.0`
- chainer version: `chainer 6.0.0`
- pytorch version: `pytorch 1.4.0+cu100`
- Train Datasets: `About 1000H Mandarin corpus`

Has anyone ever encountered this question? Thanks.

**Comment by b-flo** [comment]
Hi,

Could you share the training log please?
It could be related to #1860 with multi-gpu behaviour though, as code status 139 in Unix means a SIGSEV (segmentation violation / illegal memory access) was received.

**Comment by lilian0118** [comment]
@b-flo Thanks for your reply.

I use this config(espnet/egs/mini_an4/asr1/conf/train_transducer.yaml) re-run the train script. I also set "verbose=1", but from the log I can't find any information about crash.
[train.log](https://github.com/espnet/espnet/files/4615275/train.log)

**Comment by b-flo** [comment]
Interesting. Some gdb usage may be needed to pinpoint the problem.
Could you try to re-build warp-transducer as suggested in #1860 though? It may be unrelated but there was an illegal memory problem in warp-transducer and I'm not sure how it behave in multi-gpu setup.

@ShigekiKarita maybe you have some comments on that?

**Comment by lilian0118** [comment]
@b-flo I followed you your suggestion and re-build warp-transducer, but the problem is still occur.

It's very strange than the problem only occur when train RNN-transducer, if I train transformer-rnn-transducer or transfomer-transducer, the train process on multi-gpu is ok.

**Comment by b-flo** [comment]
I did some experiment with RNN-transducer and multi-GPU in the same environment you provided, unfortunately I couldn't reproduce the error..
If you are familiar with gdb or any debugging tools, some logs/traces would be useful to pinpoint the issue.

**Comment by lilian0118** [comment]
@b-flo Thank you very much. I'll try to dump some core file.
