### ISSUE TITLE
Mel-spectrogram files missing

### ISSUE THREAD

**Issue by Arafat4341** [espnet/espnet#1916]
Hello. I am using tacotron2 for TTS. For an input text, I cannot find where mel-spec files are generated.

Can anyone tell where the mel-spec files are generated/located?

**Comment by unilight** [comment]
Do you mean the training or generated melspectrograms?
For training, the raw spectrograms are in the `fbank` directory by default. They are further normalized and stored in the `dump` directory.
The generated should be in `exp/<expdir>/<outdir>/<setname>`. For example, `exp/train_clean_460_pytorch_train_pytorch_tacotron2+spkemb/outputs_model.last1.avg.best_decode/dev_clean`. The ones further denormalized for synthesis are in `exp/<expdir>/<outdir>_denorm/<setname>`.

**Comment by Arafat4341** [comment]
@unilight Actually I am using pre-trained models for synthesis. I have searched the exp folder. There are no generated mel-specs in there.

**Comment by unilight** [comment]
If you use `utils/synth_wav.sh`, you can check here.
https://github.com/espnet/espnet/blob/master/utils/synth_wav.sh#L44
