### ISSUE TITLE
espnet 2 asr on custom dataset

### ISSUE THREAD

**Issue by lneukom** [espnet/espnet#1919]
Hi
we are working on a recipe for a custom dataset but have some questions regarding the results. Our recipe is based on the egs2/common_voice/asr1 recipe. We are using the train and decode config of the transformer model.

<img src="https://user-images.githubusercontent.com/7010688/81685752-7a69ac00-9458-11ea-8999-c0e2dfba6952.png" alt="cer" width="400"></img>
<img src="https://user-images.githubusercontent.com/7010688/81685781-7dfd3300-9458-11ea-981d-8584586d2fa3.png" alt="wer" width="400"></img>

1) At epoch 140 the valid cer is around 0.24 but the valid wer is around 0.995. Is there some bug with the wer calculation?
2) The cer during decoding of the valid set is higher (around 0.35) than the valid cer during training. Shouldn't the cer during decoding be the same or lower when using beam search? A possible explanation is that during validation teacher forcing is used, but im not sure if that's the case.
3) Is there some intuition why the ctc_weight is 0.3 for the training but during decoding 0.5?

Cheers, Lukas

**Comment by kamo-naoyuki** [comment]
Teacher forcing is used, yes.
Did you use BPE? On BPE mode, the WER corresponds to SER in the implementation for training ( I just didn't prepare it).

CTC weight is decided just by tuning, I think. Sometimes it's set as lower/higher value.

**Comment by lneukom** [comment]
Thanks for the help! 

Yes, I'm using BPE.  That explains the high values in the plot.

**Comment by kamo-naoyuki** [comment]
Also, I forgot to note that, and maybe you already knew, the CER in the training corresponds to the TER ( BPE Token).
