### ISSUE TITLE
Increased ASR performance on pre-trained model

### ISSUE THREAD

**Issue by ivanelgran23** [espnet/espnet#1921]
I recognize audio using the pre-trained **ru_open_stt** model. Unfortunately, it has low recognition optimization (10 second recording is recognized in 6-7 seconds) with parameters: `--backend pytorch --api v2 --ngpu 1`
I tried changing the parameters to `--backend chainer --api v1 --ngpu 1` and in response I get an error:

```# asr_recog.py --config decode/download/ru_open_stt/conf/tuning/decode_pytorch_transformer_large.yaml --ngpu 0 --backend chainer --debugmode 1 --verbose 1 --recog-json decode/13-05-2020__12_22_31/dump/data.json --result-label decode/13-05-2020__12_22_31/result.json --model decode/download/ru_open_stt/exp/train_pytorch_train/results/model.val10.avg.best --api v1 --rnnlm decode/download/ru_open_stt/exp/train_rnnlm_pytorch_lm_unigram100/rnnlm.model.best 
# Started at Wed May 13 07:22:33 Asia 2020
#
WARNING:root:CTC was set to builtin due to PyTorch version.
Traceback (most recent call last):
  File "/usr/app/egs/ru_open_stt/asr1/../../../espnet/bin/asr_recog.py", line 209, in <module>
    main(sys.argv[1:])
  File "/usr/app/egs/ru_open_stt/asr1/../../../espnet/bin/asr_recog.py", line 180, in main
    recog(args)
  File "/usr/app/espnet/asr/chainer_backend/asr.py", line 378, in recog
    chainer_load(args.model, model)
  File "/usr/app/espnet/asr/asr_utils.py", line 462, in chainer_load
    chainer.serializers.load_npz(path, model)
  File "/usr/local/lib/python3.6/dist-packages/chainer/serializers/npz.py", line 239, in load_npz
    with numpy.load(file, **_allow_pickle_kwargs) as f:
AttributeError: __enter__
# Accounting: time=2 threads=1
# Ended (code 1) at Wed May 13 07:22:35 Asia 2020, elapsed time 2 seconds
```

**Question 1**: Can I somehow fix the error to use this model with such parameters?
**Question 2**: Are there any other ways to increase recognition performance?

**Comment by sw005320** [comment]
The model is packed with the pytorch one. You cannot change the backend to chainer.

**Comment by ivanelgran23** [comment]
Okay Are there ways to increase productivity with pytorch backend?

**Comment by sw005320** [comment]
Sorry that it is too little information for me to give you advice.
In general, you could train the model with large amounts of training data matching your scenario.

**Comment by ivanelgran23** [comment]
Okay. Thank you to your help!

**Comment by akreal** [comment]
Hi, I guess you asked about recognition speed. Here is what you can try to make it to run faster.

1. Disable LM by adding `--use_lang_model false` to `recog_wav.sh`.
2. Increase batch size by adding `batchsize: 8` to `conf/decode.yaml`. More is better, but if it's too large, you'll get "out of memory" errors.
3. Use CPU instead of GPU. Change `OMP_NUM_THREADS` in `path.sh` to number of CPU cores for using as much cores as possible. This also needs `batchsize` in `conf/decode.yaml`.

I haven't tried it myself, so I don't know if it will help.

**Comment by ivanelgran23** [comment]
> Hi, I guess you asked about recognition speed. Here is what you can try to make it to run faster.
> 
> 1. Disable LM by adding `--use_lang_model false` to `recog_wav.sh`.
> 2. Increase batch size by adding `batchsize: 8` to `conf/decode.yaml`. More is better, but if it's too large, you'll get "out of memory" errors.
> 3. Use CPU instead of GPU. Change `OMP_NUM_THREADS` in `path.sh` to number of CPU cores for using as much cores as possible. This also needs `batchsize` in `conf/decode.yaml`.
> 
> I haven't tried it myself, so I don't know if it will help.

Thanks for your reply!
The advice from the first paragraph really helped, and slightly reduced the time for recognizing audio. But here the other two do not work, because with any version of api an error is issued: `Batch decoding is not implemented`
Reducing to `beam-size: 1` in `decode.yaml` file also helps a little. In this regard, are there any other options to affect performance?

**Comment by akreal** [comment]
Sorry, my knowledge about batch size was outdated. It is not needed in `decode.yaml`. But I did not find the error message `Batch decoding is not implemented` in the current ESPnet code. Maybe you need to update ESPnet.

You can also try to set `ctc-weight: 0.0` in `decode.yaml`.

Also you can try `dtype: float16` in `decode.yaml`, but it can be helpful only if GPU is new enough.

**Comment by jefflai108** [comment]
i also got the same error as @ivanelgran23 when i set batchsize larger than 0. Reducing `beam-size` definitely helps (default is 60) but you may want to experiment the optimal trade-off between performance and speed.
