### ISSUE TITLE
Installation Question - Where to put ESPNET?

### ISSUE THREAD

**Issue by picheny-nyu** [espnet/espnet#1928]
When I use git clone to get a copy of espnet do I put this under kaldi? Under kaldi/src? At the same level as kaldi? The documentation is not clear.

**Comment by sw005320** [comment]
Same level as kaldi.

**Comment by kamo-naoyuki** [comment]
There are no restrictions where an espnet repository is.

**Comment by picheny-nyu** [comment]
Thanks.
