### ISSUE TITLE
Errors in ESPNET installation

### ISSUE THREAD

**Issue by picheny-nyu** [espnet/espnet#1929]
**ERROR: tensorboardx 2.0 has requirement protobuf>=3.8.0, but you'll have protobuf 3.7.1 which is incompatible.
ERROR: languageflow 1.1.13a1 has requirement joblib==0.13.2, but you'll have joblib 0.14.1 which is incompatible.
ERROR: languageflow 1.1.13a1 has requirement scikit-learn==0.20.3, but you'll have scikit-learn 0.23.0 which is incompatible.
ERROR: underthesea 1.1.17 has requirement nltk<3.5,>=3.4, but you'll have nltk 3.5 which is incompatible.**
Installing collected packages: configargparse, typeguard, dataclasses, humanfriendly, scipy, cycler, kiwisolver, pyparsing, python-dateutil, matplotlib, pillow, editdistance, typing, typing-extensions, filelock, protobuf, chainer, tensorboard-plugin-wit, grpcio, absl-py, werkzeug, oauthlib, requests-oauthlib, pyasn1, rsa, pyasn1-modules, cachetools, google-auth, google-auth-oauthlib, zipp, importlib-metadata, markdown, tensorboard, tensorboardX, threadpoolctl, joblib, scikit-learn, llvmlite, numba, soundfile, audioread, decorator, resampy, librosa, pysptk, sentencepiece, click, regex, nltk, PyYAML, h5py, kaldiio, inflect, unidecode, jaconv, distance, g2p-en, cython, fastdtw, sklearn, nnmnkwii, python-crfsuite, tabulate, args, clint, languageflow, underthesea, espnet-tts-frontend, simplejson, pyrsistent, attrs, jsonschema, pytz, pandas, stempeg, pyaml, musdb, museval, pystoi, bottleneck, nara-wpe, torch-complex, pytorch-wpe, espnet
  Running setup.py develop for espnet
Successfully installed PyYAML-5.3.1 absl-py-0.9.0 args-0.1.0 attrs-19.3.0 audioread-2.1.8 bottleneck-1.3.2 cachetools-4.1.0 chainer-6.0.0 click-7.1.2 clint-0.5.1 configargparse-1.2.3 cycler-0.10.0 cython-0.29.17 dataclasses-0.6 decorator-4.4.2 distance-0.1.3 editdistance-0.5.2 espnet espnet-tts-frontend-0.0.1 fastdtw-0.3.4 filelock-3.0.12 g2p-en-2.1.0 google-auth-1.14.3 google-auth-oauthlib-0.4.1 grpcio-1.29.0 h5py-2.9.0 humanfriendly-8.2 importlib-metadata-1.6.0 inflect-4.1.0 jaconv-0.2.4 joblib-0.14.1 jsonschema-3.2.0 kaldiio-2.15.1 kiwisolver-1.2.0 languageflow-1.1.13a1 librosa-0.7.2 llvmlite-0.32.1 markdown-3.2.2 matplotlib-3.2.1 musdb-0.3.1 museval-0.3.0 nara-wpe-0.0.7 nltk-3.5 nnmnkwii-0.0.20 numba-0.49.1 oauthlib-3.1.0 pandas-1.0.3 pillow-7.1.2 protobuf-3.7.1 pyaml-20.4.0 pyasn1-0.4.8 pyasn1-modules-0.2.8 pyparsing-2.4.7 pyrsistent-0.16.0 pysptk-0.1.18 pystoi-0.3.3 python-crfsuite-0.9.6 python-dateutil-2.8.1 pytorch-wpe-0.0.0 pytz-2020.1 regex-2020.5.14 requests-oauthlib-1.3.0 resampy-0.2.2 rsa-4.0 scikit-learn-0.23.0 scipy-1.4.1 sentencepiece-0.1.86 simplejson-3.17.0 sklearn-0.0 soundfile-0.10.3.post1 stempeg-0.1.8 tabulate-0.8.7 tensorboard-2.2.1 tensorboard-plugin-wit-1.6.0.post3 tensorboardX-2.0 threadpoolctl-2.0.0 torch-complex-0.0.3 typeguard-2.7.1 typing-3.7.4.1 typing-extensions-3.7.4.2 underthesea-1.1.17 unidecode-1.1.1 werkzeug-1.0.1 zipp-3.1.0
touch espnet.done
. venv/bin/activate && pip install cupy-cuda100==6.0.0
Collecting cupy-cuda100==6.0.0
  Downloading cupy_cuda100-6.0.0-cp37-cp37m-manylinux1_x86_64.whl (354.4 MB)
     |████████████████████████████████| 354.4 MB 8.1 kB/s 
Requirement already satisfied: numpy>=1.9.0 in ./venv/lib/python3.7/site-packages (from cupy-cuda100==6.0.0) (1.18.1)
Collecting fastrlock>=0.3
  Downloading fastrlock-0.4-cp37-cp37m-manylinux1_x86_64.whl (31 kB)
Requirement already satisfied: six>=1.9.0 in ./venv/lib/python3.7/site-packages (from cupy-cuda100==6.0.0) (1.14.0)
Installing collected packages: fastrlock, cupy-cuda100
Successfully installed cupy-cuda100-6.0.0 fastrlock-0.4
touch cupy.done
if . venv/bin/activate && python -c 'import torch as t;major=t.__version__.split(".")[0];assert major == "1"' &> /dev/null; then \
	if [ ! -z "6.0.0" ]; then \
		. venv/bin/activate && pip install warpctc-pytorch10-cuda100; \
	else \
		. venv/bin/activate && pip install warpctc-pytorch10-cpu; \
	fi \
else \
	rm -rf warp-ctc; \
	git clone https://github.com/espnet/warp-ctc.git; \
	cd warp-ctc; git checkout -b pytorch-0.4 remotes/origin/pytorch-0.4; \
	mkdir build && cd build && cmake .. && make && cd ..; \
	. ../venv/bin/activate; pip install cffi; cd pytorch_binding && python setup.py install; \
fi
Collecting warpctc-pytorch10-cuda100
  Downloading warpctc_pytorch10_cuda100-0.1.3-cp37-cp37m-manylinux1_x86_64.whl (2.4 MB)
     |████████████████████████████████| 2.4 MB 9.6 MB/s 
Installing collected packages: warpctc-pytorch10-cuda100
Successfully installed warpctc-pytorch10-cuda100-0.1.3
touch warp-ctc.done
rm -rf warp-transducer
git clone https://github.com/HawkAaron/warp-transducer.git
Cloning into 'warp-transducer'...
remote: Enumerating objects: 11, done.
remote: Counting objects: 100% (11/11), done.
remote: Compressing objects: 100% (10/10), done.
remote: Total 905 (delta 1), reused 5 (delta 1), pack-reused 894
Receiving objects: 100% (905/905), 248.13 KiB | 0 bytes/s, done.
Resolving deltas: 100% (462/462), done.
# Note: Requires gcc>=5.0 to build extensions with pytorch>=1.0
**if . venv/bin/activate && python -c 'import torch as t;assert t.__version__[0] == "1"' &> /dev/null; then \
        . venv/bin/activate && python -c "from distutils.version import LooseVersion as V;assert V('4.8.5') >= V('5.0'), 'Requires gcc>=5.0'"; \
fi
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AssertionError: Requires gcc>=5.0
make: *** [warp-transducer.done] Error 1
(espnet-may142020) [map22@lion2 tools]$ type gcc
gcc is /usr/bin/gcc
(espnet-may142020) [map22@lion2 tools]$** 

Not sure how to handle these two things (top and bottom) please advise.

**Comment by kamo-naoyuki** [comment]
You can ignore the errors about version compatibility for the time being. 
You can avoid the second problem just using gcc>=5.0 as it said.

**Comment by picheny-nyu** [comment]
Seemed to work but got a lot of warnings about deprecated functions. 

warning : Instruction 'shfl' without '.sync' is deprecated since PTX ISA version 6.0 and will be discontinued in a future PTX ISA version
