### ISSUE TITLE
Unigram spm model and cmvn.ark

### ISSUE THREAD

**Issue by SazerLife** [espnet/espnet#1935]
Hello everyone!

I'm the guy who's still struggling with the transfer learning for the ru_open_stt model.
I've almost done it, but I can't do one thing. How I can tokenize my data according to the dictionary which using in a model? 

There isn't a unigram model in https://github.com/espnet/espnet/blob/master/egs/ru_open_stt/asr1/RESULTS.md

I tried to train a new one, as I already said in this issue (https://github.com/espnet/espnet/issues/1887), but in this case, I got a lot of "unk" tokens.

Maybe there is any way to train the same model as in the ru_open_stt recipe using "cmvn.akr"? I don't know what is it and for what it using. I'll be thankful if you tell me about it. 

If these questions seem you stupid, please, be tolerant, I just want to learn.

**Comment by b-flo** [comment]
Hi,

> How I can tokenize my data according to the dictionary which using in a model?

Sorry, I'm not sure I correctly understood the question. For BPE, the process is (roughly) the following:

- Train a BPE model based on a specified text.
- Encode a specified text (it can be a different one) using the trained BPE model.
- Generate the dictionnary based on the encoded text, by extracting each uniq subwords encountered.

> There isn't a unigram model in https://github.com/espnet/espnet/blob/master/egs/ru_open_stt/asr1/RESULTS.md

From what I understood `ru_open_stt` is free of use, thus you can train yourself the same unigram model. In `run.sh`, it's done here:

https://github.com/espnet/espnet/blob/master/egs/ru_open_stt/asr1/run.sh#L121-L125 

> Maybe there is any way to train the same model as in the ru_open_stt recipe using "cmvn.akr"? I don't know what is it and for what it using. I'll be thankful if you tell me about it.

CMVN corresponds to "Cepstral Mean and Variance Normalization" which is a technique to normalize the mean and variance of the raw cepstra. I'll let you google it yourself, there a lot of useful litterature on that :)

**Comment by SazerLife** [comment]
@b-flo 

> From what I understood `ru_open_stt` is free of use, thus you can train yourself the same unigram model. In `run.sh`, it's done here:
> 
> https://github.com/espnet/espnet/blob/master/egs/ru_open_stt/asr1/run.sh#L121-L125
> 

Yes, indeed o_stt is an open dataset. But the model I'm talking about is already quite old. Even the recipe specified in "egs" will not be able to run, because as far as I know, the old links are no longer supported (I tried it and failed). 
If I train a new bpe model on the updated o_stt dataset, it will differ from the one used in that training. It turns out that the dictionary, that it will collect, will differ from what is included in the model. If you run the encoding with an old dictionary, it starts substituting "unk" characters instead of tokens that it does not know. I will try to formulate a question like this: What tokenize method is possible if we don't have access to the original data? Or is there methods to train bpe model with ready-made dictionary?

> CMVN corresponds to "Cepstral Mean and Variance Normalization" which is a technique to normalize the mean and variance of the raw cepstra. I'll let you google it yourself, there a lot of useful litterature on that :)

Thx! I'll go to google =)

**Comment by akreal** [comment]
Hi, I don't have the original model, but here is new one trained on the same data: https://drive.google.com/file/d/1hdQaKwdK5XmjImZDzBVx9kptYrT_xAQ8/view?usp=sharing

I'm not sure how you will use it and if it will work. If it is for `score_sclite.sh`, then you can modify it to use dictionary instead of model, like in `recog_wav.sh`: https://github.com/espnet/espnet/blob/f36bbee58afe8c718dc465ceeb85b86041801e0c/utils/recog_wav.sh#L250

**Comment by b-flo** [comment]
Thanks for the help @akreal !

> Yes, indeed o_stt is an open dataset. But the model I'm talking about is already quite old. Even the recipe specified in "egs" will not be able to run, because as far as I know, the old links are no longer supported (I tried it and failed).

OK, I know understand the main problem (you didn't explain that issue with the dataset previously or I may have missed it, sorry). In that case, I guess the best solution would be to update the data preparation scripts to work with current corpus version and also update the models.
@akreal Do you have time to work on that? I can update the scripts if needed but I don't have the resources nor time right now to do the training part unfortunately.

**Comment by akreal** [comment]
Unfortunately I can't work on it anytime soon, but it is my plans for the next few months.

**Comment by SazerLife** [comment]
Thank you very much! I will try to use this in my train process.

> Hi, I don't have the original model, but here is new one trained on the same data: https://drive.google.com/file/d/1hdQaKwdK5XmjImZDzBVx9kptYrT_xAQ8/view?usp=sharing
> 
> I'm not sure how you will use it and if it will work. If it is for `score_sclite.sh`, then you can modify it to use dictionary instead of model, like in `recog_wav.sh`:
> 
> https://github.com/espnet/espnet/blob/f36bbee58afe8c718dc465ceeb85b86041801e0c/utils/recog_wav.sh#L250

Well, thank you, I'll try that too :)

> I guess the best solution would be to update the data preparation scripts to work with current corpus version and also update the models.

**Comment by sw005320** [comment]
Sounds good.
Year, let's try to maintain this recipe, and it would be great if some of you make a PR to fix the current issue.
I heard that this recipe interests several people as a large-scale public ASR database (like librispeech!).

**Comment by SazerLife** [comment]
@sw005320 @b-flo @akreal   Hi again, I tried to train a new model, but it takes up too much of my server's time (prediction is more than a month). Maybe you remember, how much time does it take up in the configuration that presents in the `readme.md`?

**Comment by akreal** [comment]
I guess it was around 2 weeks on 4 GPUs.

**Comment by akreal** [comment]
@b-flo @sw005320 

Now I can spend some resources to update the recipe.
- Should I use ESPnet 2 or 1?
- Should I use Conformer or Transformer? I could run both, if needed.

**Comment by sw005320** [comment]
If you have resource and time, I'd like to ask you to check the following model one-by-one
- espnet1 transformer
- espnet1 conformer
- espnet2 conformer

conformer may be a bit more sensitive than transformer in terms of the learning rate, and it would be better to check both.
Then, we can safely move to espnet2.
espnet2 is generally better than espnet1 but we still cannot get better performance in some limited tasks like librispeech. So, it would be safe to start from espnet1 to see espnet2 conformer is also reasonable or not.

**Comment by akreal** [comment]
Got it, thanks!

**Comment by SazerLife** [comment]
@akreal  
Thank you for not forgetting about my problem! Can I ask you to put the BPE model that you will use for training in the archive with the model?

**Comment by akreal** [comment]
@SazerLife
I've updated the recipe: https://github.com/espnet/espnet/pull/2776
New model archives contain the BPE model. Please let me know if you need anything else.

**Comment by SazerLife** [comment]
@akreal
Thank you very much! I can't ask for more than that!
