### ISSUE TITLE
Requesting suggestions on extracting layers from a Transformer ASR pre-trained model

### ISSUE THREAD

**Issue by rppravin** [espnet/espnet#1936]
Can you please provide suggestions on how to extract a few layers from a Transformer based pre-trained model such as the following:
https://github.com/espnet/espnet/blob/master/egs/librispeech/asr1/RESULTS.md#pytorch-transformer-accum-grad-8-single-gpu

The model corresponding to the above link contains a embedding layer followed by twelve {multi-head attention and position-wise feed forward} layers. I would like to keep only the embedding layer and a few, say half, of the  {multi-head attention and position-wise feed forward} layers.

Thanks for your help.

**Comment by b-flo** [comment]
Hi,

Let me understand: you want to extract the embedding layer and some specific modules from a pre-trained model to pre-initialize weights in a new model with different (smaller) architecture. Is that right?

If that's your intent, you can use `--enc-init-mods` and `--dec-init-mods` to select the modules you want to extract, however you will need to add a new method to modify the keys of the extracted modules to match the keys in the new model (e.g.: you extract `enc.11.*` to initialize encoder 4th module, you need to change it to `enc.4.*`).
Additionnaly, you should be careful to match the corresponding dimensions. Some works may be needed on that part.

**Comment by rppravin** [comment]
Thanks for your response.

Is it possible for you to share some code that extracts layers of a pre-trained model. I am only trying to have some example/reference code.

Thanks.

**Comment by b-flo** [comment]
Sure, all code related to finetuning can be found here: https://github.com/espnet/espnet/blob/master/espnet/asr/pytorch_backend/asr_init.py

The method extracting the AM modules weights (given a model's state dict and modules list) is this one : https://github.com/espnet/espnet/blob/master/espnet/asr/pytorch_backend/asr_init.py#L51-L70

**Comment by rppravin** [comment]
Thanks for sharing the files!
