### ISSUE TITLE
Publishing commit changes

### ISSUE THREAD

**Issue by shrutijpalaskar** [espnet/espnet#194]
Hello,

Would it be possible to publish "commit changes" -- a log of sorts where there is detailed information about commits, bug fixes, or pull requests that are merged into the master branch, which would also state or help users understand what changes are to be expected in the results across various commits. 

This would help us understand why the results are changing even with the same seed, across different commits of the master branch.

Thank you!

**Comment by sw005320** [comment]
Thanks for the suggestion!
We started to use GitHub release https://github.com/espnet/espnet/releases
We'll use this function for our future update.
