### ISSUE TITLE
Download a pre trained model for conversion

### ISSUE THREAD

**Issue by swachm** [espnet/espnet#1941]
I am looking to convert the model to ONNX format and would like to see how the conversion is done. Is there a pre-trained model for the English language available to download? 

Any help is greatly appreciated!

**Comment by b-flo** [comment]
Hi,

In the main [README](https://github.com/espnet/espnet/blob/master/README.md), you can click on "expand" to show results and download link for several models. Common Voice, Librispeech, TEDLIUM and WSJ are the english ones.

**Comment by swachm** [comment]
Found them, Thank you!
