### ISSUE TITLE
Multi-machine multi-gpu training with slurm appears cuda oom

### ISSUE THREAD

**Issue by saber5433** [espnet/espnet#1945]
In espnet1, I used two machines to train librispeech  and CUDA OOM happened.
All GPU memory is 12g
This is my training config file. Although I reduced the batch-bin to 7500000, 3750000, 937500 or even 512, it still didn't work. Strangely, I have no problem in training aishell with two machines
![image](https://user-images.githubusercontent.com/15922669/82407987-26387a80-9a9d-11ea-8e74-a43a17c81fe2.png)

**Comment by kamo-naoyuki** [comment]
Multi-machine multi-gpu training is not supported in espnet1. What are you talking about?

**Comment by sw005320** [comment]
Yes, it is only supported in espnet2.
Could you explain a bit more about your multiple machine setup?

**Comment by alexkararo** [comment]
I am also curios how you trained on multuple machines with ESPnet1. Could you elaborate?
