### ISSUE TITLE
Transformer input layer type error

### ISSUE THREAD

**Issue by yuexianghubit** [espnet/espnet#1948]
Hello there,

When I specify the transformer input layer as 'embed', it will occur problem:

`RuntimeError: Expected tensor for argument #1 'indices' to have scalar type Long; but got torch.FloatTensor instead (while checking arguments for embedding)`

I think it's due to that the type of the input tensor mismatched the type of input of torch.nn.Embedding. 
Hope you guys to fix this error.
Thanks

**Comment by sw005320** [comment]
Are you talking about https://github.com/espnet/espnet/blob/536d163870e29ea52bbaa4cc0b03cfc407df0c0b/espnet2/asr/encoder/transformer_encoder.py#L83?
Did you use it for your speech feature input?
This is intended for a one-hot representation like test input.

**Comment by yuexianghubit** [comment]
Oh, got it. Thanks!
 I was trying to use it for speech feature input.
