### ISSUE TITLE
AlignTTS Support ?

### ISSUE THREAD

**Issue by dathudeptrai** [espnet/espnet#1951]
Hi, i found an interested paper (https://arxiv.org/abs/2003.01950) called AlignTTS. With this model maybe we don't need alignment from other models to extract duration for fastspeech anymore. It's great if espnet support AlignTTS :D. @kan-bayashi :))

**Comment by unwritten** [comment]
@sw005320  any plan to support this? I think it's very useful too...

**Comment by sw005320** [comment]
I see. That looks interesting. @kan-bayashi, what do you think?

**Comment by dathudeptrai** [comment]
@kan-bayashi maybe we can consider implement glow-tts or alignTTS pytorch-TF compatible :)).

**Comment by puthhaggie** [comment]
the alignment model is aligntts is quite helpful especially when there's no teacher or some language doesn't have sr for force align, looking forward for this new feature on espnet @kan-bayashi  @sw005320

**Comment by kan-bayashi** [comment]
Sorry for the late reply.
AlignTTS is very interesting work but it still requires multi-stage training, which making the recipe complex.
After discussion with @dathudeptrai, [Glow-TTS](https://arxiv.org/abs/2005.11129) or [Flow-TTS](https://ieeexplore.ieee.org/abstract/document/9054484) seems to be better in terms of the simplicity of the training. 
I will consider the implementation.

**Comment by seantempesta** [comment]
For my 2 cents, I'm having wonderful results with Glow-TTS.  It's easy to train, trains super fast and is really stable.  I can generate minutes of audio and it sounds great.  :)

**Comment by seantempesta** [comment]
@dathudeptrai  So this is still pretty early (I've only been training for about 24 hours on a single 2080 on my laptop), but here's Trump performing Shakespeare: 

https://soundcloud.com/sean-tempesta/trump-performing-shakespeare

I've mostly been fighting with Waveglow to get decent audio quality, so I'm looking into switching over to MelGAN.  I haven't tried FastSpeech2.

**Comment by dathudeptrai** [comment]
@seantempesta can you check out my fastspeechv2 + mb-melgan and compared with ur glow-tts + waveglow here ? https://dathudeptrai.github.io/TensorflowTTS/

**Comment by seantempesta** [comment]
Yeah, the fastspeech2 + mb-melgan samples sound good.  I really can't judge what Glow-TTS is capable of yet, as I'm still very early in my experimentation.  The author has some pretty good samples on their github site though.

https://jaywalnut310.github.io/glow-tts-demo/index.html
