### ISSUE TITLE
Small mistake in the Installation doc, part "Step 3-A)"

### ISSUE THREAD

**Issue by LightTemplar** [espnet/espnet#1954]
there: https://espnet.github.io/espnet/installation.html in the "Step 3-A)", while trying to "make" with installed Anaconda I get an Error:
```
Can't open venv/bin/activate
Makefile:76: recipe for target 'espnet.done' failed
```
Solution: correct all "venv/activate" into "venv/bin/activate" in the docs.

**Comment by kamo-naoyuki** [comment]
Thanks!
