### ISSUE TITLE
How to perform TTS with pre-trained models and speaker embeddings

### ISSUE THREAD

**Issue by mapa17** [espnet/espnet#1973]
Hello,
I am new to espnet and TTS in general, so sorry if this question might not make too much sense. If I got some basic things wrong, don't hesitate to point it out please.

For a privat project, I would like to experiment with TTS using different voices. Doing a bit of research on the topic I think this is possible through providing different speaker embeddings to the pre-trained voice synthesis systems (like the two step process Tacotron+vocoder).

I found a previous [question](https://github.com/espnet/espnet/issues/1561) that is similar I think but to be honest I am not sure how to make use of the answers.

What I could gather so far is:
* Its possible to extract speaker embeddings from the [Libri TTS Corpus](http://www.openslr.org/60/) using some parts of the following [script](https://github.com/espnet/espnet/blob/81a383a9054cf1e42d2558f81cc30f2841075b70/egs/libritts/tts1/run.sh#L142-L180)
* The [E2E-TTS demo Colab notebook](https://colab.research.google.com/github/espnet/notebook/blob/master/tts_realtime_demo.ipynb#scrollTo=UBBAokMQegdK) makes use of the Tacotron2 model that supports in its prediction/inference step an speaker embedding argument (**spemb**)

So my question is:
* Can I get speaker embeddings by simply downloading the LSR60 dataset and run stage 3 of the script https://github.com/espnet/espnet/blob/81a383a9054cf1e42d2558f81cc30f2841075b70/egs/libritts/tts1/run.sh#L142-L180 ?
* Can I pass one of those embeddings to the pre-trained Tacotron2 model during inferencing? Or do I have to train the model and the embeddings by myself?

thank you!

**Comment by sw005320** [comment]
> So my question is:
> 
> * Can I get speaker embeddings by simply downloading the LSR60 dataset and run stage 3 of the script https://github.com/espnet/espnet/blob/81a383a9054cf1e42d2558f81cc30f2841075b70/egs/libritts/tts1/run.sh#L142-L180
>    ?

Yes.
This recipe includes the download of all required models and data.

> * Can I pass one of those embeddings to the pre-trained Tacotron2 model during inferencing? Or do I have to train the model and the embeddings by myself?

Yes, you can pass it during inference.
You can perform it even for unseen speakers during training and perform zero-shot speaker adaptation (to some extent. The quality is OK. Check the AD-EM audios in https://potato-inoue.github.io/demo/egs/unpair_spk_adapt/)
You don't need to train them.

**Comment by mapa17** [comment]
Hello, 
thank you for your answer, and sorry for my long delay.

After few days of struggling with the compilation and computation, I finished the x-vector extraction of a part of the training set (train-clean-100 only).

I found in 'espnet/egs/libritts/tts1/exp/xvector_nnet_1a/xvectors_train_clean_460' several xvector scp, and ark files. Are those the speaker embeddings in some kaldi format?

Can you give me some direction on how to extract the specific speaker embeddings from the file, and how to use them for speech synthesis?
Can I use/test them in the 'ESPnet real time E2E-TTS demonstration' colab book?

**Comment by sw005320** [comment]
> I found in 'espnet/egs/libritts/tts1/exp/xvector_nnet_1a/xvectors_train_clean_460' several xvector scp, and ark files. Are those the speaker embeddings in some kaldi format?

Yes.

> Can you give me some direction on how to extract the specific speaker embeddings from the file, and how to use them for speech synthesis?
> Can I use/test them in the 'ESPnet real time E2E-TTS demonstration' colab book?

This is a good suggestion. @kan-bayashi, is it supported? (maybe not)
@potato-inoue, could you also give us a comment since you have such an environment.

**Comment by kan-bayashi** [comment]
@mapa17 To extract x-vector, we need to install kaldi.
Colab demo notebook is the minimum setup so it is not supported.
Maybe this script will help you.
https://github.com/espnet/espnet/blob/abbbe00b4db72a3eb86a4ce77123afb86bc8e278/utils/synth_wav.sh#L255-L285

**Comment by mapa17** [comment]
@kan-bayashi I already have extracted x-vectors (for the dev, test, train_100 sets)

What i dont know is how to use them with any of the pretrained models, or better with one of the TTS pipelines like the 'ESPnet real time E2E-TTS demonstration' colab book.

**Comment by kan-bayashi** [comment]
In that case, you can use kaldiio to load your x-vector.
https://github.com/nttcslab-sp/kaldiio
And then convert to tensor and pass to the model as the argument (spemb):
https://github.com/espnet/espnet/blob/7e193fd8dc1f1b88688c121174b1ff1fa5766f21/espnet/tts/pytorch_backend/tts.py#L703

**Comment by kan-bayashi** [comment]
@mapa17 It seems that you use a single speaker model.
You should use the multi speaker model.
e.g. 
libritts taco2 / transformer
https://drive.google.com/drive/folders/1qtoyOgFwnLi9OJgUTuCwO8YHzc_TJ0Xh?usp=sharing
libritts pwg
https://drive.google.com/open?id=15ibzv-uTeprVpwT946Hl1XUYDmg5Afwz

**Comment by mapa17** [comment]
@kan-bayashi 
thank you! I am using your pretrained tacotron2 and the wavegen, and now the speakers definitely sound different.

https://www.dropbox.com/sh/0yfduvmtwqu7fv9/AABPLTgLLzELGRluqCj3-8cZa?dl=0

but do you know why they generated speech sounds much worse than with the models in the notebook? I am not sure to understand if this is due to the tacotron2 model, or wavgan?

**Comment by kan-bayashi** [comment]
I think the quality degradation came from the multi-speaker tacotron 2.
Basically, if we use open-speaker (not included in the training data) for the inference, the quality is not so good (especially, when the similarity is low compared to the training speakers).

**Comment by AyaHamdy** [comment]
@mapa17  please i need your help, if you can tell me the steps you followed to synthesize wavs using specific speaker

**Comment by mapa17** [comment]
@AyaHamdy here is a copy of instructions I recently wrote to someone else with similar issues

* clone and install Kaldi (https://github.com/kaldi-asr/kaldi/blob/master/INSTALL)
* clone ParallelWaveGAN
* clone the espnet repo

Within espnet, run the following script until step 3 (you need to adjust the script setting the end stage:3, number of gpus and parallel jobs you want to run).

	espnet/egs/libritts/tts1/run.sh

This will download the libritts dataset (www.openslr.org/resources/60) and extract the speaker embeddings (I did this for a subset of the data dev-clean test-clean train-clean-100, NOT train-clean-360)

If you are interested in those embeddings, you can find them as part of the artefacts that I am using in my project.

https://1drv.ms/u/s!AsC_YGX9uGhggZYnsjGU3Swtcb4ATA?e=n4W9Wk

The embeddings I have extracted from the scp files and stored them as pickle file (a simple dictionary containing the embeddings)

If its any use to you, you can find my ongoing work at https://github.com/mapa17/thousandVoices

**Comment by AyaHamdy** [comment]
@mapa17 Thanks for your help, i will follow your steps and if i face any problem i will back to you.

**Comment by deepanshi-s** [comment]
@mapa17 I tried to extract x-vectors according to the steps you mentioned. On modifying the run.sh file and running it, I get this error: compute-cmvn-stats: command not found. I have cloned kaldi in the espnet//tools folder. Could you please help me with this?
