### ISSUE TITLE
Bug in espnet/transform/cmvn.py

### ISSUE THREAD

**Issue by houwenxin** [espnet/espnet#1977]
line 75 : 
> count = count.flattten()[0]

https://github.com/espnet/espnet/blob/81a383a9054cf1e42d2558f81cc30f2841075b70/espnet/transform/cmvn.py#L75 

Maybe should be :
> count = count.flatten()[0]

**Comment by kamo-naoyuki** [comment]
Do you mean `count = count.flatten()[-1]`?

**Comment by houwenxin** [comment]
> Do you mean `count = count.flatten()[-1]`?

No, just a small typo, there is one more "t" in flatten.

**Comment by gullyboy007** [comment]
Can I work on it?

**Comment by sw005320** [comment]
@gullyboy007, yes, please!
