### ISSUE TITLE
package matching error in Installation 

### ISSUE THREAD

**Issue by curlneuron** [espnet/espnet#1978]
ERROR: Could not find a version that satisfies the requirement protobuf<3.8.0rc1,>=3.0.0 (from chainer==6.0.0->espnet==0.7.0) (from versions: none)
ERROR: No matching distribution found for protobuf<3.8.0rc1,>=3.0.0 (from chainer==6.0.0->espnet==0.7.0)
Makefile:61: recipe for target 'espnet.done' failed
make: *** [espnet.done] Error 1

--------------------------------------------------------------------------------------------

**Comment by kamo-naoyuki** [comment]
You can ignore the error. That is not a reason of failure for the make because pip doesn't return non-zero status for version mismatching.

**Comment by curlneuron** [comment]
$ cd <espnet-root>/tools
$ make KALDI=<kaldi-root> PYTHON=/usr/bin/python3.6
I follow the instruction above, but cannot install succeed. I don't know where the error comes from.

**Comment by kamo-naoyuki** [comment]
Would you show error?

**Comment by curlneuron** [comment]
Successfully built configargparse chainer librosa resampy pysptk nltk PyYAML kaldiio jaconv nnmnkwii pystoi absl-py audioread distance fastdtw sklearn simplejson bottleneck pyrsistent clint args
ERROR: tensorboardx 2.0 has requirement protobuf>=3.8.0, but you'll have protobuf 3.7.1 which is incompatible.
ERROR: languageflow 1.1.13a1 has requirement joblib==0.13.2, but you'll have joblib 0.15.1 which is incompatible.
ERROR: languageflow 1.1.13a1 has requirement scikit-learn==0.20.3, but you'll have scikit-learn 0.23.1 which is incompatible.
ERROR: underthesea 1.1.17 has requirement nltk<3.5,>=3.4, but you'll have nltk 3.5 which is incompatible.
Installing collected packages: configargparse, typeguard, dataclasses, humanfriendly, numpy, scipy, ........

**Comment by kamo-naoyuki** [comment]
Show all.

**Comment by curlneuron** [comment]
thx. It's been solved when I use change an environment.
But here comes out other issue.
'''
INFO: library availableness check start.
INFO: # libraries to be checked = 9
INFO: --> espnet is installed.
INFO: --> kaldiio is installed.
INFO: --> matplotlib is installed.
INFO: --> torch is installed.
INFO: --> chainer is installed.
INFO: --> chainer_ctc is installed.
INFO: --> warprnnt_pytorch is installed.
WARNING: --> cupy is not installed.
WARNING: --> warpctc_pytorch is not installed.
INFO: library availableness check done.
INFO: 7 / 9 libraries are correctly installed.
INFO: please try to setup again and then re-run this script.
Makefile:162: recipe for target 'check_install' failed
make: *** [check_install] Error 1
'''

While it can be seen from the log that the 2 package has been installed successfully.
1. 
Installing collected packages: fastrlock, cupy-cuda100
Successfully installed cupy-cuda100-6.0.0 fastrlock-0.4
touch cupy.done
2.
Installing collected packages: warpctc-pytorch10-cuda100
Successfully installed warpctc-pytorch10-cuda100-0.1.3
touch warp-ctc.done

Besides, by using pip install cupy to install this package. I run the make *** again, still print the log "cupy not installed".

**Comment by kamo-naoyuki** [comment]
I can't figure out the problem from the log only. Rerun Makefile.
