### ISSUE TITLE
Word boundary in CSJ

### ISSUE THREAD

**Issue by hirofumi0810** [espnet/espnet#198]
CSJ includes word boundary informatoin (wb) though it depends on morphological analysis.

However, the current preprocessing removes wb, so we cannot compute WER.
I know including wb increases computational complexity, but it provides additional information to the network.
In addition, if we can utilize wb, word-level LMs can be used in the decoding stage (off course @takaaki-hori 's multi-level LM decoding can be used).  

What do you think about them?

**Comment by sw005320** [comment]
My biggest concern is that this word boundary is based on a specific tool, and many people are using different tools (chasen or mecab with different dictionaries). Then, I had bad experience of having difficulties on comparing results. So, for now, I think we can ignore it.

**Comment by sw005320** [comment]
We can think of it after @takaaki-hori finished an implementation of multi-level LM decoding.
