### ISSUE TITLE
can't find file make_fbank_pitch.sh, only `make_fbank.sh`

### ISSUE THREAD

**Issue by OfekCohen1** [espnet/espnet#1981]
Hi

I'm trying to use a pretrained network to recognize a wav file (ASR). In `recog_wav.sh` the file `make_fbank_pitch.sh` is called to create a spectogram, but I can only find a `make_fbank.sh` file in the github / the files I downloaded to my PC.

The pretrained model expects an input with 83 frequency bins, while the spectogram of` make_fbank.sh` only has 80. I'm guessing the missing 3 are the pitch features created.

Where can I find `make_fbank_pitch.sh`? I'm pretty new at this, so I might be missing something.
Thanks!

**Comment by b-flo** [comment]
Hi,

`make_fbank_pitch.sh` is from Kaldi repo. By default, the one used/linked should be in `[espnet_dir]/tools/kaldi/egs/wsj/s5/steps/make_fbank_pitch.sh`

**Comment by OfekCohen1** [comment]
Is there a way to create the 83 features (i.e including the 3 pitch features), without going through kaldi? Preferably a python script similar to `compute-fbank-feats.py'`. 

Alternatively, are you familiar with a python script that creates these 3 features separately given the waveform so I can add them manually to `compute-fbank-feats.py`?
I'm trying to not be dependent on kaldi scripts and file types, and ideally do everything in python. 

Thanks!

**Comment by ahmedalbahnasawy** [comment]
@OfekCohen1 yes you can.
you can use torchaudio and kaldi-io to extract fbank and pitch respectively.

**Comment by OfekCohen1** [comment]
@ahmedalbahnasawy I looked at kaldi-io and could not find how to extract the pitch features from the waveform itself, only found functions related to scp/ark files etc. I would be happy if you could give me a link / direction as to which function calculates the pitch features. 

Did you perhaps mean that I can read the pitch scp file after running the .sh script? I'd prefer to do everything in python without shell if possible.

**Comment by ahmedalbahnasawy** [comment]
check this class https://pykaldi.github.io/api/kaldi.feat.html#kaldi.feat.pitch.compute_and_process_kaldi_pitch

**Comment by OfekCohen1** [comment]
@ahmedalbahnasawy Great, thanks!
