### ISSUE TITLE
Merge multiple data-set together for Japanese TTS

### ISSUE THREAD

**Issue by Arafat4341** [espnet/espnet#1982]
Hello!  I am using pre-trained tacotron-2 model for Japanese speech synthesis. I was thinking about enhancing the quality of speech.

I was wondering whether we can merge multiple speech corpus together to bring diversity in data for better quality in Japanese TTS.

My concern: Different dataset has different speakers. Do we have a chance to get weird output voice if we train on these type of merged dataset?

Plus can anyone tell without JSUT, is there any robust dataset for Japanese tts research?

Will only increasing training steps make a quality improvement?

**Comment by ATLAKT** [comment]
hello，Arafat4341 . I'm going to do some work about Japanese synthesis,could you tell me some open-source dataset for Japanese synthesis?Thank you very much.

**Comment by Arafat4341** [comment]
@ATLAKT jvs, jnas alongside jsut
