### ISSUE TITLE
wget in pretrained model setup returns error 404 (dead link)

### ISSUE THREAD

**Issue by OfekCohen1** [espnet/espnet#1985]
Hi

I'm planning to use a pretrained model for my research, so I followed the instructions here: 
https://espnet.github.io/espnet/notebook/pretrained.html

In the "Setup environment" there's a command `!wget https://18-198329952-gh.circle-artifacts.com/0/home/circleci/repo/ubuntu16-featbin.tar.gz` , and when running this command I receive `"ERROR 404: Not Found."`

Is there an alternate way to run this command / setup so I can use the pretrained models and continue the example notebook? Or alternatively, can the link be fixed? 

Thanks in advance

**Comment by sw005320** [comment]
Can you specify which links are dead?
This notebook might be getting outdated.

**Comment by OfekCohen1** [comment]
Yeah sorry, I copied the wrong command in my original comment.
The link is `!wget https://18-198329952-gh.circle-artifacts.com/0/home/circleci/repo/ubuntu16-featbin.tar.gz`. I also edited my original comment.

**Comment by sw005320** [comment]
Oh, I see. 
@ShigekiKarita, do you know what happens?

**Comment by ShigekiKarita** [comment]
oh it is outdated. we can safely use espnet/kaldi-bin releases instead

**Comment by sw005320** [comment]
Which link?
I actually tried but I could not...

**Comment by ShigekiKarita** [comment]
This is it. Maybe we should use this script instead https://github.com/espnet/espnet/blob/3ea59a0050e8a6a40138ac2365c258825b02f9cd/ci/install_kaldi.sh#L16

**Comment by sw005320** [comment]
Oh, I actually tried to use v0.3.0 by following https://github.com/espnet/kaldi-bin#kaldi-bin

**Comment by ShigekiKarita** [comment]
Maybe @kamo-naoyuki has some suggestions because he updated it

**Comment by kamo-naoyuki** [comment]
@sw005320 I wrote the README to tell you, administrator, how to upload the binary. Actually tag=v0.0.3 doesn't exist. 
https://github.com/espnet/kaldi-bin/releases

**Comment by OfekCohen1** [comment]
> This is it. Maybe we should use this script instead
> 
> https://github.com/espnet/espnet/blob/3ea59a0050e8a6a40138ac2365c258825b02f9cd/ci/install_kaldi.sh#L16

Thanks! this worked instead of  the original command.

Anyway, I kept using the notebook and got to the command  `cd espnet/tools; make sentencepiece.done` and got the error ` No rule to make target 'sentencepiece.done'.  Stop.`. It seems this file doesn't exist. I've also noticed that `cd warp-ctc/pytorch_binding && python setup.py install` has given me an error as well - `RuntimeError: Error compiling objects for extension`.

If this notebook is outdated, is there a different notebook I can use to setup the environment for pretrained models? Will the regular setup from the Installation Docs suffice for running the pretrained models?

**Comment by ZDisket** [comment]
@OfekCohen1 
I previously fixed the notebook by changing a few things after the setup Kaldi comment. Delete everything after said comment and paste this:

```
import os

!cd /content/espnet/tools; git clone https://github.com/kaldi-asr/kaldi
!echo "" > ./espnet/tools/kaldi/tools/extras/check_dependencies.sh # ignore check
!chmod +x ./espnet/tools/kaldi/tools/extras/check_dependencies.sh
!cd ./espnet/tools/kaldi/tools; make sph2pipe sclite
!rm -rf espnet/tools/kaldi/tools/python

os.chdir("/content")
!wget https://github.com/espnet/kaldi-bin/releases/download/v0.0.1/ubuntu16-featbin.tar.gz
!tar -xf ./ubuntu16-featbin.tar.gz # take a few minutes
!cp featbin/* espnet/tools/kaldi/src/featbin/

# make dummy activate
!mkdir -p espnet/tools/venv/bin
!touch espnet/tools/venv/bin/activate

```
I also based my fix on [this ](https://github.com/espnet/notebook/blob/master/tts_cli.ipynb)notebook which doesn't have `cd espnet/tools; make sentencepiece.done`. Also, your run.sh may not be able to find `compute-cmvn-stats`; in that case, replace it with `python /content/espnet/utils/compute-cmvn-stats.py`

> If this notebook is outdated, is there a different notebook I can use to setup the environment for pretrained models?

You can check out [my notebook](https://colab.research.google.com/drive/1-h4Qlp25ZSQ13WOicO2vBHQGvMjzQYkv?usp=sharing), although it's non-official and set up for a specific purpose: fine-tuning LJSpeech.

**Comment by OfekCohen1** [comment]
@ZDisket This works, Thanks!!
