### ISSUE TITLE
How much can one "strip down" a copy of this repo to only have the absolute minimum required for TTS synthesis

### ISSUE THREAD

**Issue by ZDisket** [espnet/espnet#1999]
I've been attracted to this Tacotron2 because of its very reasonable synthesis time on CPU (even in my bad dual-core), and I am looking to make a user-friendly GUI frontend for Windows that is easy to use for the average person with a computer(haven't decided what vocoder yet). 

Now, I can include an entire copy of ESPNet for each distribution (like in the E2-TTS demo notebook), but that's too bloated. So my question is, (before I take a dependency tracker and hammer away), how much of a size reduction could I achieve by deleting everything that isn't necessary for Tacotron2 inference? Or are all the modules too tightly knit?

**Comment by sw005320** [comment]
Tacotron2 inference does not need a complicated beam search and it only requires a minimum component. For example https://github.com/espnet/notebook/blob/master/tts_realtime_demo.ipynb does not install espnet (only git clone it). The most massive part is pytorch, but I believe you can find a lot of techniques for it.

**Comment by ZDisket** [comment]
@sw005320 
I know all of that; after all, I do have a very rough console demo I whipped up. I was just looking for ways not to clone (or distribute a frozen version of) the entire repo every time.
>The most massive part is pytorch

I don't really mind pytorch, it's not that big.

**Comment by sw005320** [comment]
You mean 31M is too big? (Also, you can get a [source code](https://github.com/espnet/espnet/archive/v.0.7.0.zip) only, which is 3M)

```
git clone --depth 1 https://github.com/espnet/espnet.git
Cloning into 'espnet'...
remote: Enumerating objects: 2164, done.
remote: Counting objects: 100% (2164/2164), done.
remote: Compressing objects: 100% (1706/1706), done.
remote: Total 2164 (delta 617), reused 948 (delta 238), pack-reused 0
Receiving objects: 100% (2164/2164), 2.52 MiB | 0 bytes/s, done.
Resolving deltas: 100% (617/617), done.
Checking out files: 100% (2869/2869), done.
$ du -hs espnet/
31M	espnet/
```

**Comment by ZDisket** [comment]
> You mean 31M is too big?

My impression was partially warped by Github's slow download speed. I'll check out the source code only.

**Comment by sw005320** [comment]
OK, now I understand what you mean to say. You can just download the source code from the released ones. Good luck!
