### ISSUE TITLE
loading Transformer ASR model using model.recognize with DefaultRNNLM

### ISSUE THREAD

**Issue by ahmedalbahnasawy** [espnet/espnet#2001]
i'm using load_language_model to load lm before pass it to model.recognice(fbank,...rnnlm=lm)
rnnlm and rnnlm_conf are parameters at ASR model.json
```model, train_args = load_trained_model(args.model)
    assert isinstance(model, ASRInterface)
    model.eval()
    vocab = train_args.char_list
    with open (model_dir + "/model.json", "r") as f:
        idim, odim, conf=json.load(f)
    vocab = conf["char_list"]
   lm =load_language_model(args.rnnlm, args.rnnlm_conf)`
def load_language_model(rnnlm,rnnlm_conf):

    lm_args = get_model_conf(rnnlm, rnnlm_conf)
    lm_model_module = getattr(lm_args, "model_module", "default")
    lm_class = dynamic_import_lm(lm_model_module,backend)
    lm = lm_class(4999, lm_args)
    torch_load(rnnlm,lm)
    lm.eval()
    print(lm)
    DefaultRNNLM(
  (model): ClassifierWithState(
    (lossfun): CrossEntropyLoss()
    (predictor): RNNLM(
      (embed): Embedding(4999, 2048)
      (rnn): ModuleList(
        (0): LSTMCell(2048, 2048)
        (1): LSTMCell(2048, 2048)

    return lm
```
I'm getting this **Error : AttributeError: 'DefaultRNNLM' object has no attribute 'predict'**
i'm able to use Beamsearch scorer 'api v2' but i would like to use jit.trace method.
Thanks

**Comment by sw005320** [comment]
>  i would like to use jit.trace method.

I see.
@ShigekiKarita, could you answer it for me?
I'm also curious about it.

**Comment by ShigekiKarita** [comment]
I'm not sure what you wanna do. BeamSearch class expects ScorerInterface that has no method named predict.

**Comment by ahmedalbahnasawy** [comment]
@ShigekiKarita indeed, predict is a function inside defaultRNNLM class and I 'm using ASRInterface.recognize(fbank , rnnlm= args.rnnlm) Not Beamsearch scorer. 
I want to use RNNLM during decoding while api = v1

**Comment by ahmedalbahnasawy** [comment]
@ShigekiKarita @sw005320 @kan-bayashi 
I think there is one more thing to discuss is that after tracing the model by giving it **sample_1** then save it and load it again. The traced model gives this warning "TracerWarning: Converting a tensor to a Python integer might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!"  . Furthermore, when feeding another sample test it gives the same result as the **sample_1** . This problem i can see its in the decoder part and its hard to solve because trace method accepts tensors only.  

Can anyone give suggestions on how the problem could be solve , or what i could do to make things better, any help would be greatly appreciated.

**Comment by ShigekiKarita** [comment]
If you are thinking about `use_jit` option in `recognize`, it is broken and returns different values from non-jit execution.
https://github.com/espnet/espnet/blob/6f6452a3891d11b0b0306084dd46a464ddf8e25c/espnet/nets/pytorch_backend/e2e_asr_transformer.py#L380-L385

Maybe we can gradually convert our scorers into jit supported models because jit is not perfect as you mentioned. I think RNNLM is the best candidate because pytorch official example already shows it is possible. 
https://github.com/pytorch/examples/blob/59423c5168095fe65f85c67a04f8ee703d5e6ea1/word_language_model/main.py#L196-L202

**Comment by ahmedalbahnasawy** [comment]
> If you are thinking about `use_jit` option in `recognize`, it is broken and returns different values from non-jit execution.
>   Applying jit could not be an option. I tried using jit to serve the model but it seems unreliable .
 https://github.com/espnet/espnet/blob/6f6452a3891d11b0b0306084dd46a464ddf8e25c/espnet/nets/pytorch_backend/e2e_asr_transformer.py#L380-L385
> 
> Maybe we can gradually convert our scorers into jit supported models because jit is not perfect as you mentioned. I think RNNLM is the best candidate because pytorch official example already shows it is possible.
>    Exporting RNNLM to ONNX format could be useful but the issue that ONNX cannot support variable length input, I will give a look to huggingface tool and see how to serve Transformer models also

https://github.com/pytorch/examples/blob/59423c5168095fe65f85c67a04f8ee703d5e6ea1/word_language_model/main.py#L196-L202

Thanks
