### ISSUE TITLE
Training/decoding scripts of Transfomer with CTC and LM

### ISSUE THREAD

**Issue by deeplearner01** [espnet/espnet#2002]
Hi

I wonder whether you have made available in ESPnet the training/decoding scripts for the "Transformer-based End-to-End Speech Recognition with Connectionist Temporal Classification and Language Model Integration", presented in this paper:
https://www.isca-speech.org/archive/Interspeech_2019/pdfs/1938.pdf

Thank you.

Best regards,
DL

**Comment by sw005320** [comment]
We already have it. All our transformer recipes basically follow the above paper.

**Comment by deeplearner01** [comment]
Many thanks! It's good to know this.
