### ISSUE TITLE
TTS on Tedlium

### ISSUE THREAD

**Issue by roholazandie** [espnet/espnet#2003]
Hi,
I searched the repo and egs but I didn't find a TTS that was trained on tedlium, Is it because it's not a good dataset for TTS training or just we don't have it here. And, second, I wonder why I can't find a male TTS. I am very new to text to speech.

**Comment by sw005320** [comment]
> I searched the repo and egs but I didn't find a TTS that was trained on tedlium, Is it because it's not a good dataset for TTS training. 

You're right.
tedlium is too noisy for TTS.
However, we also did not put a lot of investigations, and in general, it would be a good research direction of how we use noisy ASR data for TTS.

> And, second, I wonder why I can't find a male TTS. I am very new to text to speech.

@kan-bayashi, could you answer it?

**Comment by kan-bayashi** [comment]
We have several male TTS recipe.
- egs/tweb
- egs/mailabs

Or multi-speaker one.
- egs/libritts

**Comment by roholazandie** [comment]
> We have several male TTS recipe.
> 
> * egs/tweb
> * egs/mailabs
> 
> Or multi-speaker one.
> 
> * egs/libritts

So for libritts which is a multispeaker dataset, we have to just train on male audio parts of the dataset?
