### ISSUE TITLE
Training Parallel Wavegen on JVS

### ISSUE THREAD

**Issue by Arafat4341** [espnet/espnet#2006]
I have successfully trained Tacotron-2 on JVS.
But I see no way to train waveform generator (eg. parallel wavegen) on JVS.
Anyone kindly tell me how to do that!
Thanks in advance!

**Comment by sw005320** [comment]
Training of neural vocoder is not included in espnet.
Please check the original repo of neural vocoders.

**Comment by kan-bayashi** [comment]
I have not yet prepared.
Please follow the following instruction to make the recipe by yourself.
https://github.com/kan-bayashi/ParallelWaveGAN/tree/master/egs#how-to-make-the-recipe-for-your-own-dateset
