### ISSUE TITLE
Data download script missing in JNAS

### ISSUE THREAD

**Issue by Arafat4341** [espnet/espnet#2007]
I am trying to train tacotron-2 on JNAS. The default `--stage` param is set to -1 in `run.sh`. 
However there is no data downloading part in the script. It directly starts from stage 0: data preparation.

**Comment by b-flo** [comment]
A quick search tell me that the data are not freely available (http://research.nii.ac.jp/src/en/JNAS.html), that's why there is no download link. You need to purchase the corpus and set up the database structure as mentioned in `README.md`

**Comment by Arafat4341** [comment]
Thanks for the information!
