### ISSUE TITLE
Double Decoder Consistency for Tacotron2 support?

### ISSUE THREAD

**Issue by ZDisket** [espnet/espnet#2008]
I found this [very interesting post](https://erogol.com/solving-attention-problems-of-tts-models-with-double-decoder-consistency) while regularly checking up on erogol's blog. Apparently, the resultant model gets perfect alignment on 50 hard sentences and it learns attention faster. 
Any chance of this being added here? For reference, the dev branch of Mozilla TTS already has this implemented.

**Comment by sw005320** [comment]
Thanks for introducing an interesting post!
We'll take a look at it.
