### ISSUE TITLE
Train FastSpeech with Transformer parent model

### ISSUE THREAD

**Issue by marcosnetopires** [espnet/espnet#2012]
What to add to the run.sh command to give a parent model?
Can the parent model be a snapshot.ep file?

I'm using:
```
tmp = "/path/to/snapshot.ep"
./run.sh --stage 3 --stop-stage 3 --trans_type phn --train-config conf/tuning/train_fastspeech.v4.single.yaml --teacher_model_path $tmp 
```

But the log says:
```
usage: tts_train.py [-h] [--config CONFIG] [--config2 CONFIG2]
                    [--config3 CONFIG3] [--ngpu NGPU]
                    [--backend {chainer,pytorch}] --outdir OUTDIR
                    [--debugmode DEBUGMODE] [--seed SEED] [--resume [RESUME]]
                    [--minibatches MINIBATCHES] [--verbose VERBOSE]
                    [--tensorboard-dir [TENSORBOARD_DIR]]
                    [--eval-interval-epochs EVAL_INTERVAL_EPOCHS]
                    [--save-interval-epochs SAVE_INTERVAL_EPOCHS]
(...)
                   [--use-weighted-masking USE_WEIGHTED_MASKING]
tts_train.py: error: unrecognized arguments: /path/to/dump/phn_dev/data.json
```

I assume I did something wrong?...

**Comment by sw005320** [comment]
You did not seem to use the correct setup. Could you strictly follow https://github.com/espnet/espnet/blob/e860e7ca7bb8c780a49da8bee428cda2b1706ca5/egs/ljspeech/tts1/run.sh#L158-L197 ?

**Comment by marcosnetopires** [comment]
Are you are referring to using the option "-n ${teacher_model_path}" instead of " --train-confi" ? If so I got this error:
`Traceback (most recent call last):
  File "/content/espnet/egs/ljspeech/tts1/../../../espnet/bin/tts_train.py", line 355, in <module>
    main(sys.argv[1:])
  File "/content/espnet/egs/ljspeech/tts1/../../../espnet/bin/tts_train.py", line 349, in main
    train(args)
  File "/content/espnet/espnet/tts/pytorch_backend/tts.py", line 288, in train
    args.spc_dim = int(valid_json[utts[0]]["input"][1]["shape"][1])
IndexError: list index out of range
# Accounting: time=2 threads=1
# Ended (code 1) at Fri Jun 12 09:18:46 UTC 2020, elapsed time 2 seconds
`

**Comment by kan-bayashi** [comment]
I could not understand what is happened.
Could you attach the entire log of your first post?
And Let me check some points:
- I believe `tmp = "/path/to/snapshot.ep"` is an example. You should specify the current path of the snapshot e.g. `exp/.../snapshot.ep.200`.
- Did you modify the `conf/tuning/train_fastspeech.v4.single.yaml`?
- Did you finish the creation of new `data.json`? It will be created in 
https://github.com/espnet/espnet/blob/535e53a588ae511adeb61bba217f22e96c730116/egs/ljspeech/tts1/run.sh#L178-L179

**Comment by marcosnetopires** [comment]
- Ignore the path, I just renamed it here to simplify (in code it is correct)
- I did change the config file, but only added this line at the end `save-interval-epoch: 2`
- I've checked and all data.json files were created and have content (they are not empty)

I can't seem to be able to reproduce the error on my first comment, I must have changed something, but now when i run with the `teacher_model_path` option it kinda gets stuck with this log while still running: 
```
dictionary: data/lang_1phn/phn_train_no_dev_units.txt
stage 3: Text-to-speech model training
stage 0: Decoding for knowledge distillation
2020-06-15 10:17:21,806 (splitjson:43) INFO: /usr/bin/python3 /content/espnet/egs/ljspeech/tts1/../../../utils/splitjson.py --parts 32 /content/espnet/egs/ljspeech/tts1/exp/phn_train_no_dev_pytorch_train_pytorch_transformer.v3.single/outputs_snapshot.ep_decode_for_knowledge_dist/phn_train_no_dev/data.json
2020-06-15 10:17:21,828 (splitjson:55) INFO: number of utterances = 1797
2020-06-15 10:17:21,831 (splitjson:43) INFO: /usr/bin/python3 /content/espnet/egs/ljspeech/tts1/../../../utils/splitjson.py --parts 32 /content/espnet/egs/ljspeech/tts1/exp/phn_train_no_dev_pytorch_train_pytorch_transformer.v3.single/outputs_snapshot.ep_decode_for_knowledge_dist/phn_dev/data.json
2020-06-15 10:17:21,835 (splitjson:55) INFO: number of utterances = 250

```
And if I run with the option `-n` I get this error in log:
```
# tts_train.py --backend pytorch --ngpu 1 --minibatches 0 --outdir exp/phn_train_no_dev_pytorch_train_fastspeech.v4.single/results --tensorboard-dir tensorboard/phn_train_no_dev_pytorch_train_fastspeech.v4.single --verbose 1 --seed 1 --resume --train-json dump/phn_train_no_dev/data.json --valid-json dump/phn_dev/data.json --config conf/tuning/train_fastspeech.v4.single.yaml 
# Started at Mon Jun 15 09:21:33 UTC 2020
#
2020-06-15 09:21:38,300 (tts_train:339) INFO: ngpu: 1
2020-06-15 09:21:38,301 (tts_train:342) INFO: random seed = 1
2020-06-15 09:21:38,738 (deterministic_utils:26) INFO: torch type check is disabled
2020-06-15 09:21:38,800 (tts:279) INFO: #input dims : 77
2020-06-15 09:21:38,801 (tts:280) INFO: #output dims: 80
Traceback (most recent call last):
  File "/content/espnet/egs/ljspeech/tts1/../../../espnet/bin/tts_train.py", line 355, in <module>
    main(sys.argv[1:])
  File "/content/espnet/egs/ljspeech/tts1/../../../espnet/bin/tts_train.py", line 349, in main
    train(args)
  File "/content/espnet/espnet/tts/pytorch_backend/tts.py", line 288, in train
    args.spc_dim = int(valid_json[utts[0]]["input"][1]["shape"][1])
IndexError: list index out of range
# Accounting: time=6 threads=1
# Ended (code 1) at Mon Jun 15 09:21:39 UTC 2020, elapsed time 6 seconds

```

**Comment by kan-bayashi** [comment]
Maybe you did not finish the following part:
https://github.com/espnet/espnet/blob/535e53a588ae511adeb61bba217f22e96c730116/egs/ljspeech/tts1/run.sh#L166-L176
Did you use docker? Sometimes it hangs without any messages.
Could you try with small number of `${nj}` say (4 or 8)? 

> And if I run with the option -n I get this error in log:

What is the option `-n`?
From the log, the `data.json` path is wrong. 
`--train-json dump/phn_train_no_dev/data.json --valid-json dump/phn_dev/data.json`
We should specify the 
https://github.com/espnet/espnet/blob/535e53a588ae511adeb61bba217f22e96c730116/egs/ljspeech/tts1/run.sh#L178-L179

**Comment by marcosnetopires** [comment]
> Maybe you did not finish the following part:

Shouldn't the default values work ? The nj seems to have no impact, and the other options I believe they are correct.

> Did you use docker? Sometimes it hangs without any messages.

I am not using docker

> What is the option -n?
> From the log, the data.json path is wrong.
> `--train-json dump/phn_train_no_dev/data.json --valid-json dump/phn_dev/data.json`

Please ignore my comments from this option, I misread the run.sh options.

I said in my previous comment that the command runs and keeps running without ceasing or giving any sign of progress. What output should I expect? I imagined it would be an output directory much like the one found here `https://drive.google.com/open?id=1z8KSOWVBjK-_Ws4RxVN4NTx-Buy03-7c`

**Comment by kan-bayashi** [comment]
> I said in my previous comment that the command runs and keeps running without ceasing or giving any sign of progress.

OK. You mean this part is still running, not yet finished, right?
https://github.com/espnet/espnet/blob/535e53a588ae511adeb61bba217f22e96c730116/egs/ljspeech/tts1/run.sh#L166-L176
You can find the log in 
`/content/espnet/egs/ljspeech/tts1/exp/phn_train_no_dev_pytorch_train_pytorch_transformer.v3.single/outputs_snapshot.ep_decode_for_knowledge_dist/phn_dev/log/`
Please check it.

**Comment by marcosnetopires** [comment]
Not that comment, this:
```
dictionary: data/lang_1phn/phn_train_no_dev_units.txt
stage 3: Text-to-speech model training
stage 0: Decoding for knowledge distillation
2020-06-15 10:17:21,806 (splitjson:43) INFO: /usr/bin/python3 /content/espnet/egs/ljspeech/tts1/../../../utils/splitjson.py --parts 32 /content/espnet/egs/ljspeech/tts1/exp/phn_train_no_dev_pytorch_train_pytorch_transformer.v3.single/outputs_snapshot.ep_decode_for_knowledge_dist/phn_train_no_dev/data.json
2020-06-15 10:17:21,828 (splitjson:55) INFO: number of utterances = 1797
2020-06-15 10:17:21,831 (splitjson:43) INFO: /usr/bin/python3 /content/espnet/egs/ljspeech/tts1/../../../utils/splitjson.py --parts 32 /content/espnet/egs/ljspeech/tts1/exp/phn_train_no_dev_pytorch_train_pytorch_transformer.v3.single/outputs_snapshot.ep_decode_for_knowledge_dist/phn_dev/data.json
2020-06-15 10:17:21,835 (splitjson:55) INFO: number of utterances = 250
```

**Comment by marcosnetopires** [comment]
![Untitled](https://user-images.githubusercontent.com/11540929/84673333-78947c00-af21-11ea-9221-6c20def7e3e9.png)

When running this is what I see, there is no error so I assume it is doing the knowledge destilation(?)
There are a lot of log files (`decode.[1-28].log`) I give an example bellow.
[decode.10.log](https://github.com/espnet/espnet/files/4781146/decode.10.1.log)

From my understanding the training process is starting? but because it is heavy to preprocess the dataset it takes a while to give me feedback?

**Comment by kan-bayashi** [comment]
Actually, I'm very confused for your comments.
What is the problem now?

We create a new `data.json` in `setup_knowledge_dist.sh`.
We generate all of the training / validation data by using the teacher model and re-create for data.json for knowledge distillation training.
https://github.com/espnet/espnet/blob/535e53a588ae511adeb61bba217f22e96c730116/egs/ljspeech/tts1/run.sh#L166-L176
And then, we start to train the fastspeech.v4 model using a new data.json.
https://github.com/espnet/espnet/blob/535e53a588ae511adeb61bba217f22e96c730116/egs/ljspeech/tts1/run.sh#L178-L197

**Comment by marcosnetopires** [comment]
The initial problem was solved somehow.
This FastSpeech configuration uses knowledge distillation which I had not used before, the issue was me not understanding where the logs were and how the knowledge distillation steps worked, I understand it now, thanks.
