### ISSUE TITLE
Multilingual st with must-c recipe

### ISSUE THREAD

**Issue by TitouanT** [espnet/espnet#2020]
Hello,
I am trying to train a multilingual model with the must-c recipe and changing `tgt_lang=de` to `tgt_lang=de_fr` in `egs/must-c/st1/run.sh` didn't do the trick.
The recipe is failing in stage 1 during features extraction.

In stage 1, features extraction might need to happen per target languages separately and aggregated later in the end of stage 1 or stage 2 should be adapted to look into each language directory to generate the json for training.

Any help would be welcome :)

**Comment by sw005320** [comment]
I added @hirofumi0810 in this issue.

Yes, you need to perform stage 1 per language and later combine it by using `utils/combine_data.sh`
We would also need to do some other tricks (see https://arxiv.org/pdf/1910.00254.pdf) and it’s better to ask @hirofumi0810 for this item.

**Comment by hirofumi0810** [comment]
@TitouanT Actually I prepared another recipe designed for mutilingual ST on Must-C.
I will add it. But please wait for a while because I am investigating how to give language IDs to the Transformer models. I might take some time.
