### ISSUE TITLE
Transformer-transducer with espnet2

### ISSUE THREAD

**Issue by jiwidi** [espnet/espnet#2022]
Is this architecture supported with the new version of espnet2?

I'm fairly new to the package so sorry if I missed it, but I haven't been able to find it.

**Comment by kamo-naoyuki** [comment]
No, we haven't prepared transducer in espnet2, but we plan it.

**Comment by b-flo** [comment]
Hi,

I started working on the port but some other works I wanted to finish took longer than expected, sorry. I'll be able to give more information next week!

**Comment by jiwidi** [comment]
> Hi,
> 
> I started working on the port but some other works I wanted to finish took longer than expected, sorry. I'll be able to give more information next week!

No problem! The work you do here is great, just post here when you have something so I can check it :)
