### ISSUE TITLE
the grad norm of transformer with pure ctc is zero on gpu mode

### ISSUE THREAD

**Issue by WanderingSven** [espnet/espnet#2024]
hello,everyone. I am using transformer with pure ctc on librispeech recipe. I find the grad norm is zero when I use gpu and the loss donot convergence. The train.log and conf.yaml are as follow:
[train.log](https://github.com/espnet/espnet/files/4768494/train.log)

[train_pytorch_transformer.txt](https://github.com/espnet/espnet/files/4768495/train_pytorch_transformer.txt)

**Comment by WanderingSven** [comment]
Does it mean that there is a problem with the program when grad norm is 0
![图片](https://user-images.githubusercontent.com/26950286/84459805-e54a1500-ac9a-11ea-990a-ec600057bb2b.png)

**Comment by sw005320** [comment]
Thanks for the report.
This looks strange.
Actually, @hirofumi0810 found a bug (I thought that it would not affect the result even with this bug, but maybe I'm wrong). 
Could you try it after we merge https://github.com/espnet/espnet/pull/2023?
