### ISSUE TITLE
espnet2 calculate_all_attention questions

### ISSUE THREAD

**Issue by Cescfangs** [espnet/espnet#2025]
I believe we are plotting encoder-decoder alignments:
https://github.com/espnet/espnet/blob/8da1e963d7d01b24d54ad73f2b19dc71d89fa0d3/espnet2/main_funcs/calculate_all_attentions.py#L50-L55

but the output of `MultiHeadedAttention` is the context info (batch_size, time, d_model)
https://github.com/espnet/espnet/blob/8da1e963d7d01b24d54ad73f2b19dc71d89fa0d3/espnet/nets/pytorch_backend/transformer/attention.py#L73-L78

So I guess the attention plot would be like that(x-axis is attention dim, 256 here not input time):
![decoder decoders 0 src_attn](https://user-images.githubusercontent.com/11382612/84460489-a4530000-ac9c-11ea-9d2b-434cf6df5b3d.png)

**Comment by kamo-naoyuki** [comment]
I see, thanks.

**Comment by kamo-naoyuki** [comment]
I fixed. Please check it #2028
