### ISSUE TITLE
Visualizing Attention weights/layers in Transformer ASR

### ISSUE THREAD

**Issue by rppravin** [espnet/espnet#2033]
If you know of any tools that can be used with the ESPnet ASR code to visualize intermediate layers (such as attention weights) of a Transformer ASR model, can you please let me know.

**Comment by sw005320** [comment]
You can check them via tensorboard (see https://espnet.github.io/espnet/tutorial.html#logging)

**Comment by rppravin** [comment]
Thanks for the link.

Best,
Pravin
