### ISSUE TITLE
Which trans_type is preferable for transliterated text of custom language/dataset? 

### ISSUE THREAD

**Issue by ican24** [espnet/espnet#2039]
Dear Team,

I am using transliterated text for my custom language/dataset in EspNet TTS. 
The used transliteration is phonetic, but not G2P canonic. Therefore I kept
`trans_type="char"` 
in run.sh.  
Unfortunately the result is not yet satisfying․  
The 21 hours dataset is enough tested in the other TTS projects and I did all data preparing recomendations of espnet.
It looks like
`
arthur.saribekyan1_15974 ch y' n a y a c'   a rr a j i n y'   a r d e n   tw a gh a t   e' ,
arthur.saribekyan1_15975 i s k   y e r k r o r d i   g y' l u x y'   l y' r i v   s y' p i t a k a c' ։
`
Should the Tacotron2 training provide better result with trans_type="phn"?
Sorry for asking, but your solution demands much more time for training: about 4 days on my RTX 2080 TI  11GB.

Thank you in advance

**Comment by kan-bayashi** [comment]
In my experiments, phoneme-based models are always better than (at least equal to) char-based model (As you seen in #1937).

**Comment by ican24** [comment]
Thank you!
I'll try it and other options as I am full of mind to find better way for non common languages/datasets in EspNet.

**Comment by ican24** [comment]
Dear @kan-bayashi,

Finally I enforced epsnet TTS to work with my language with the help of phonemes. The result is a really good, especially I'm impressed by wonderful sound and speed of your Parallel WaveGAN. The Parallel WaveGAN is also troubleless solution: a rare project among many deep learning solutions in may way.
On the other hand I understand that serious bug of Tacotron2 technology, which is a big-big headache and obstacle for non-English/non-Latin languages, does not  belong to EspNet. 
By the way the Nvidia developers also recognized Tacotron2 bug.
https://github.com/NVIDIA/NeMo/issues/323#issuecomment-644426123

Frankly it is shocked and discriminating act of technology development.
In such manner ancient Armenians would not share their civilization achievements with other nations in the bronze and further eras like grain growing and metal production. Similarly the modern Armenians would not share many valuable inventions like color TV, ATM, automatic transmission, tomography... 
https://www.youtube.com/watch?v=4HnziuQE2Zo
    
In such situation I would like to ask you to help me and other developers to find any acceptable solution for non-common languages in your platform.
G2P is not well-documented. Maybe it was polished just for English, Japanese and Chinese only. The solutions like G2PS
https://github.com/uiuc-sst/g2ps
are practically wrong and useless. Any mistake in grapheme-to-phoneme conversation is extremely critical for speech synthesis. I spent 1 day to reach acceptable sounding manipulating phonemes/words separation.
Shortly I'll be so appreciated if you advise short and plain instruction how to convert graphemes into phonemes:
1. Do we need to use only core ACSII or extanded codes too?
2. How to separate the words, while we are separating phonemes by the space?
3. There are at least 3 punctuations in my language, which are placed above the letters. How to separate them and other puctuation characters correctly?          

Otherwise I'll ask to add warning that the espnet solutions do not support non-Latin/Japanese/Chinese languages directly.
Such way you'll save our time and nerves.

Thank you in advance!

**Comment by kan-bayashi** [comment]
> Finally I enforced epsnet TTS to work with my language with the help of phonemes. The result is a really good, especially I'm impressed by wonderful sound and speed of your Parallel WaveGAN.

I'm glad to hear that. Thank you for applying ESPnet for your language.

> Do we need to use only core ACSII or extanded codes too?

We can use non-ascii characters.

> How to separate the words, while we are separating phonemes by the space?

We can define your own separater symnol e.g. `<sep>`.

> There are at least 3 punctuations in my language, which are placed above the letters. How to separate them and other puctuation characters correctly?

Not sure but you can get insight from Mandarin, which represents pronunciation symbols as a number from 1 to 4.
E.g. `ka2 er2 pu3 pei2 wai4 sun1 wan2 hua2 ti1`

> Otherwise I'll ask to add warning that the espnet solutions do not support non-Latin/Japanese/Chinese languages directly.

I added a description of the phoneme-based TTS in README in #2079.

**Comment by kan-bayashi** [comment]
There are many languages I did not know in the world.
So if you can provide the recipe for your language, that is great.

**Comment by ican24** [comment]
Thank you!
You every instruction is really useful.
They provide true progress in our development.
As recipe could you describe/list which exactly I need zip and transfer you.

Thank you in advance!

**Comment by kan-bayashi** [comment]
> As recipe could you describe/list which exactly I need to zip and transfer you?

I mean the recipe is like `egs/XXX/tts1`.
If your corpus is free to access, you can make a PR for other researchers.

**Comment by ican24** [comment]
Dear @kan-bayashi,

Unfortunately our corpuses have no free access, but the reason is not a copyright or fear of commercial competition. It is much more deeper. I can not explain it publicly.
Below is my email address:
artak.hovsepian@gmail.com
Please send me empty message, I'll send you download link of recipe content without "dump", "fbank", "exp", "tensorboard" folders from Google Drive or our website. 
Is it ok?

I'll be so appreciated, if you help us to fix this last issue of grapheme-to-phoneme conversation. After 7 long months we can finally make fully advanced TTS solution available for public usage for my country. We are also going to write your name as active supporter of our project. By the way at 11th June we asked Japan International Cooperation Agency and Japan Development Service Co․ to intercede to Nagoya University and Human Dataware Lab. Co., Ltd., when they applied us in the frame of "Data Collection Survey on Promotion of Solution Business with Advanced ICT" initiative.

**Comment by kan-bayashi** [comment]
> Unfortunately our corpuses have no free access, but the reason is not a copyright or fear of commercial competition. It is much more deeper. I can not explain it publicly.

OK. In that case, you do not need to send me.

> We are also going to write your name as active supporter of our project.
By the way at 11th June we asked Japan International Cooperation Agency and Japan Development Service Co․ to intercede to Nagoya University and Human Dataware Lab. Co., Ltd., when they applied us in the frame of "Data Collection Survey on Promotion of Solution Business with Advanced ICT" initiative.

I'm not sure what you mean.
This open-source work is not directly related to my associations, please be careful.

**Comment by ican24** [comment]
It is a just plain request for consultation and support.
Your agencies asked us how they can help us as reply we told your name using information from your page https://github.com/kan-bayashi.
After TTS we would like to start development of other espnet solutions. Therefore we would not look like annoying.
Just a plain desire to make relations more solid.
That's all.

**Comment by ican24** [comment]
As you have no chance to investigate our case with grapheme-to-phoneme conversation, could you provide a piece of text of Japanese recipe? I'll try to analyse it. Do'nt worry a have a good friend from Japan, who may help me. 
unfortunately I could not find  grapheme-to-phoneme converted exmaples of espnet. 
Thank you

**Comment by kan-bayashi** [comment]
Try JSUT recipe `egs/jsut/tts1`.
You can find the phoneme sequence example.
https://github.com/espnet/espnet/blob/f34eee89813573482ab66d7030e93a7edd88edca/egs/jsut/tts1/run.sh#L31

**Comment by kan-bayashi** [comment]
See also:
https://github.com/espnet/espnet_tts_frontend#japanese

**Comment by ican24** [comment]
Thank you!
As my case I had discovered that the best sounding is possible, when I am removing double spaces between the words keeping single space only. The double spaces between the words generate unpredictable results with word missing and wrong speech.
If you like to see how espnet TTS Tacotron2 + Parallel WaveGAN differs from the Pythorch-DC+SSRN (highly tuned by me) sounding you may compare here 
https://arm.ican24.net/demovoice.php

I think I can finalize the sounding trying to use correct conversation for merged and not merged punctuation characters.

**Comment by ican24** [comment]
I'll try to publish main results of my experinece and impressions/thoughts here hoping it may be useful for other developers of the custom dataset/languages, if you do not mind. 

- my best dataset, which genereted best sounding on the pytorch-dc+ssrm allows me to synthesize perfect voice on ESPNet TTS + PWG, but it is not useful because of lack of training data. The dataset volume is about 10 hours. ESPNet TTS requires more data. Next time I will try to train 42 hours dataset to compare it with 20 hours datasets. Very important to know min and max volumes.

- Espnet+PWG may generate different results for same text string even for short (30-80 characters). I am trying to investigate case. Firstly I need to learn behavour of the punctuation characters. Right now I see sometimes after comma the software pauses or distorts speech. Without punctuations and short (sentences) union elements the difference is not a huge.

Will be updated

**Comment by ican24** [comment]
Dear @kan-bayashi,

Just I would like to say thank you and your and your team for great project.
All my issues were resolved!
Below is my last synthesized voice, which is really wonderful and practically natural like.
https://www.youtube.com/watch?v=7fVLj0Gsc8Q

I am fully satisfied with ESPnet quality and your team professionalism.  I'll recommend it to my friends with pleasure. 

Now I am going to test ESPnet ASR to compare it with Kaldi ASR. 
I hope it may be good alternative of Kaldi ASR for my language.
