### ISSUE TITLE
Inferencing on Large .wav file on recog_wav.sh

### ISSUE THREAD

**Issue by Parikshit22** [espnet/espnet#2048]
While Inferencing  on more than 1 minute long audio recog_sh.wav only return a small part of that audio in text format.

**Comment by sw005320** [comment]
Which model are you using?
What kind of audio data are you using?
We may need more information to give you some advice.

**Comment by Parikshit22** [comment]
I'm using librispeech.transformer.v1 and .wav format audio file for inferencing.

**Comment by sw005320** [comment]
Is it OK for a shorter segment of audios? Does only one-minute audio have such issues?

**Comment by Parikshit22** [comment]
Yes it's okay for audio file nearby 15 sec and smaller than that, file duration more than 15 sec have this issue.
It's like starting part of the audio of duration 15 sec is decoded rest is just ignored.
And in result.json that contains the text makes only one key, value pair of only starting segment.

**Comment by Parikshit22** [comment]
cd egs/librispeech/asr1 && . ./path.sh
recog_wav.sh --models librispeech.transformer.v1 example.wav

I'm running this command for inferencing.

**Comment by Parikshit22** [comment]
So, at which part the processing is not done for longer audios, at pre-processing level at stage 1 or decoding level at stage 3?
And what about changing some other model maybe tedlium2.transformer.v1 can they handle large audio files??

**Comment by Dicksonchin93** [comment]
Somehow i'm getting the error of 
`AttributeError: 'Namespace' object has no attribute 'transformer_encoder_selfattn_layer_type'` 
running `recog_wav.sh` on the latest master, are you using an older version? or I am missing something here?

**Comment by Parikshit22** [comment]
@Dicksonchin93 Using the newer version i'm also getting the same error, in previous commits it's working fine.

**Comment by kan-bayashi** [comment]
I fixed this issue.

**Comment by thesby** [comment]
> cd egs/librispeech/asr1 && . ./path.sh
> recog_wav.sh --models librispeech.transformer.v1 example.wav
> 
> I'm running this command for inferencing.

Hi, I use this command too. But I get an error `No such models`. The model is downloaded from pretrained models, and unziped to the directory.  And I tried to use just the zip file, the same error. How to set the model?
`bash ../../../utils/recog_wav.sh --models /home/xxx/project/espnet/egs/aishell/asr1/exp/pretrained/model.v1.tar.gz  /home/xxx/project/espnet/egs/aishell/asr1/data/data_aishell//wav/test/S0764/BAC009S0764W0248.wav`
