### ISSUE TITLE
Segment speech

### ISSUE THREAD

**Issue by FriedaSmith** [espnet/espnet#2052]
I am trying recognize long speech, but `steps/make_fbank_pitch.sh: [info]: no segments file exists: assuming wav.scp indexed by utterance.`
How to segment speech?

**Comment by b-flo** [comment]
Hi,

What you highlighted is only an information from `make_fbank_pitch.sh`, there is no issue. The script needs a wav.scp or segments file, if the later does not exist, the first token on each line of `wav.scp` will be for the utterance id.

If you want to create a segment file, you will need to create it yourself following this format:
`utt_id file_id start_time end_time`.

**Comment by FriedaSmith** [comment]
Hi. I create a segment file`segments` :`1 1 0.0 1.02`.
Espnet generates files automatically `utt2spk` : `nws_1.WAV X`.
So the following error occurred：
`utils/validate_data_dir.sh: Utterance list differs between decode/nws_1.WAV/data/utt2spk and decode/nws_1.WAV/data/segments`
`utils/validate_data_dir.sh: Lengths are 1 vs 1`
What should I do？

**Comment by sw005320** [comment]
You might have the wrong format or inconsistency of the data. 
Maybe you can first take a look at the Kaldi data preparation https://kaldi-asr.org/doc/data_prep.html
espnet follows the Kaldi data structure.

**Comment by FriedaSmith** [comment]
I'm just doing identification, not training. Do I have to create `text `and `wav `files myself?

**Comment by sw005320** [comment]
Yes, you need to prepare them, but you do not have to put actual text information but put some dummy information. It cannot be used for the actual inference.
BTW, I don’t know your purpose, but if you just want to play with recognition, you may just use https://github.com/espnet/espnet/blob/master/utils/recog_wav.sh
(Or are you already using it?)

**Comment by FriedaSmith** [comment]
Yes. I've used `recog_wav.sh`. Now I want to use it to recognize long speech. In the introduction of espnet,`Streaming decoding based on CTC-based VAD` can be implemented. But I don't know how to configure some files

**Comment by sw005320** [comment]
Oh I see. Now I got more context about what you want to do. Could you (or did you already) try https://github.com/espnet/espnet/blob/master/utils/recog_wav.sh#L61-L62 ?

**Comment by FriedaSmith** [comment]
I tried. It can recognize. But I want to segment with VAD to recognize long speech.

**Comment by sw005320** [comment]
@takenori-y, maybe I’m wrong but probably we need to add some options to make it work in the streaming (VAD) mode?

**Comment by takenori-y** [comment]
@sw005320 I do not think so. I think if we have more clear information, e.g., error message, a set of procedures that causes the error, we can have a good discussion.

**Comment by FriedaSmith** [comment]
@takenori-y Results of running `recog_wav.sh`:
$ ../../../utils/recog_wav.sh --models model.v1.transformerlm.v1 /media/Corpus/North_Wind_and_the_Sun_passage/M1/nws_1.WAV 
decode/download/model.v1.transformerlm.v1
stage 0: Data preparation
stage 1: Feature Generation
steps/make_fbank_pitch.sh --cmd run.pl --nj 1 --write_utt2num_frames true decode/nws_1.WAV/data decode/nws_1.WAV/log decode/nws_1.WAV/fbank
steps/make_fbank_pitch.sh: moving decode/nws_1.WAV/data/feats.scp to decode/nws_1.WAV/data/.backup
utils/validate_data_dir.sh: WARNING: you have only one speaker.  This probably a bad idea.
   Search for the word 'bold' in http://kaldi-asr.org/doc/data_prep.html
   for more information.
utils/validate_data_dir.sh: Successfully validated data-directory decode/nws_1.WAV/data
steps/make_fbank_pitch.sh: [info]: no segments file exists: assuming wav.scp indexed by utterance.
steps/make_fbank_pitch.sh: Succeeded creating filterbank and pitch features for data
/media/other/Code/espnet/egs/tedlium2/asr1/../../../utils/dump.sh --cmd run.pl --nj 1 --do_delta false decode/nws_1.WAV/data/feats.scp decode/download/model.v1.transformerlm.v1/data/train_960/cmvn.ark decode/nws_1.WAV/log decode/nws_1.WAV/dump
stage 2: Json Data Preparation
/media/other/Code/espnet/egs/tedlium2/asr1/../../../utils/data2json.sh --feat decode/nws_1.WAV/dump/feats.scp decode/nws_1.WAV/data decode/nws_1.WAV/dict
/media/other/Code/espnet/egs/tedlium2/asr1/../../../utils/feat_to_shape.sh --cmd run.pl --nj 1 --filetype  --preprocess-conf  --verbose 0 decode/nws_1.WAV/dump/feats.scp decode/nws_1.WAV/data/tmp-jXoSC/input_1/shape.scp
sym2int.pl: replacing X with 1
** Replaced 1 instances of OOVs with 1
stage 3: Decoding

Recognized text: ▁THE▁NORTH▁WIND▁AND▁THE▁SUN▁THE▁NORTH▁WIND▁AND▁THE▁SUN▁WERE▁DISPUTING▁WHICH▁WAS▁THE▁STRONGER▁WHEN▁A▁TRAVELER▁CAME▁ALONG▁WHIPPED▁IN▁A▁WARM▁CLOAK▁THEY▁AGREED▁THAT▁THE▁ONE▁WHO▁FIRST▁SUCCEEDED▁IN▁MAKING▁THE▁TRAVELER▁TO▁GO▁OFF▁SHOULD▁BE▁CONSIDERED▁STRONGER▁THAN▁THE▁OTHER▁THEN▁THE▁NORTH▁WIND▁BLEW▁AS▁HARD▁AS▁HE▁COULD▁BUT▁THE▁MORE▁HE'D▁BLOW▁THE▁MORE▁HE'D▁THINK▁OF▁THE▁TRAVELER▁OR▁HIS▁CLOTHES▁ON▁HIM▁AND▁AT▁THE▁LAST▁TO▁THE▁NORTH▁WIND▁HE'D▁GET▁OUT▁OF▁THE▁TENT▁THEN▁THE▁NORTH▁WIND▁SWUNG▁OUT▁TO▁THE▁SOUTHER▁AND▁THE▁SOUTHER▁AND▁THE▁SOUTHER▁TOOK▁ALL▁HIS▁CLOTHES▁AND▁THE▁SOUTHER▁THE▁NORTH▁WIND▁WAS▁TO▁COME▁FAST▁AND▁THE▁SUN▁WAS▁THE▁STRONGER▁OF▁THE▁TWO

Finished


I want to segment with VAD to recognize long speech, but I don't know what to do.

**Comment by FriedaSmith** [comment]
I used the model of `Streaming decoding based on CTC-based VAD`, but it made a error:
espnet/egs/tedlium2/asr1$ ../../../utils/recog_wav.sh --models model.streaming.v1 /media/Corpus/North_Wind_and_the_Sun_passage/M1/nws_1.WAV 
decode/download/model.streaming.v1
stage 0: Data preparation
stage 1: Feature Generation
steps/make_fbank_pitch.sh --cmd run.pl --nj 1 --write_utt2num_frames true decode/nws_1.WAV/data decode/nws_1.WAV/log decode/nws_1.WAV/fbank
steps/make_fbank_pitch.sh: moving decode/nws_1.WAV/data/feats.scp to decode/nws_1.WAV/data/.backup
utils/validate_data_dir.sh: WARNING: you have only one speaker.  This probably a bad idea.
   Search for the word 'bold' in http://kaldi-asr.org/doc/data_prep.html
   for more information.
utils/validate_data_dir.sh: Successfully validated data-directory decode/nws_1.WAV/data
steps/make_fbank_pitch.sh: [info]: no segments file exists: assuming wav.scp indexed by utterance.
steps/make_fbank_pitch.sh: Succeeded creating filterbank and pitch features for data
/media/other/Code/espnet/egs/tedlium2/asr1/../../../utils/dump.sh --cmd run.pl --nj 1 --do_delta false decode/nws_1.WAV/data/feats.scp decode/download/model.streaming.v1/data/train_trim_sp/cmvn.ark decode/nws_1.WAV/log decode/nws_1.WAV/dump
stage 2: Json Data Preparation
/media/other/Code/espnet/egs/tedlium2/asr1/../../../utils/data2json.sh --feat decode/nws_1.WAV/dump/feats.scp decode/nws_1.WAV/data decode/nws_1.WAV/dict
/media/other/Code/espnet/egs/tedlium2/asr1/../../../utils/feat_to_shape.sh --cmd run.pl --nj 1 --filetype  --preprocess-conf  --verbose 0 decode/nws_1.WAV/dump/feats.scp decode/nws_1.WAV/data/tmp-FaJgF/input_1/shape.scp
sym2int.pl: replacing X with 1
** Replaced 1 instances of OOVs with 1
stage 3: Decoding
run.pl: job failed, log is in decode/nws_1.WAV/log/decode.log

`Error log in decode/nws_1.WAV/log/decode.log`
Traceback (most recent call last):
  File "/media/other/Code/espnet/egs/tedlium2/asr1/../../../espnet/bin/asr_recog.py", line 296, in <module>
    main(sys.argv[1:])
  File "/media/other/Code/espnet/egs/tedlium2/asr1/../../../espnet/bin/asr_recog.py", line 266, in main
    recog_v2(args)
  File "/media/other/Code/espnet/espnet/asr/pytorch_backend/recog.py", line 38, in recog_v2
    raise NotImplementedError("streaming mode is not implemented")
NotImplementedError: streaming mode is not implemented
# Accounting: time=1 threads=1

**Comment by takenori-y** [comment]
Thank you for letting me know. The CTC-based VAD for Transformer model is not currently implemented. We cannot use Transformer models in streaming mode. When an RNN model is used, `--api v1` option is required as described in the usage of `recog_wav.sh`.

**Comment by FriedaSmith** [comment]
So can't these models (tedlium2.rnn.v1(or model.streaming.v1) and tedlium2.rnn.v2 (or model.streaming.v2)) be used  to recognize speech?

**Comment by FriedaSmith** [comment]
There are so many and the recognition accuracy is reduced  after set `api = 1`. What's more, I want to segment to recognize long speech.

decode/download/model.streaming.v1
stage 0: Data preparation
stage 1: Feature Generation
steps/make_fbank_pitch.sh --cmd run.pl --nj 1 --write_utt2num_frames true decode/nws_1.WAV/data decode/nws_1.WAV/log decode/nws_1.WAV/fbank
steps/make_fbank_pitch.sh: moving decode/nws_1.WAV/data/feats.scp to decode/nws_1.WAV/data/.backup
utils/validate_data_dir.sh: WARNING: you have only one speaker.  This probably a bad idea.
   Search for the word 'bold' in http://kaldi-asr.org/doc/data_prep.html
   for more information.
utils/validate_data_dir.sh: Successfully validated data-directory decode/nws_1.WAV/data
steps/make_fbank_pitch.sh: [info]: no segments file exists: assuming wav.scp indexed by utterance.
steps/make_fbank_pitch.sh: Succeeded creating filterbank and pitch features for data
/media/other/Code/espnet/egs/tedlium2/asr1/../../../utils/dump.sh --cmd run.pl --nj 1 --do_delta false decode/nws_1.WAV/data/feats.scp decode/download/model.streaming.v1/data/train_trim_sp/cmvn.ark decode/nws_1.WAV/log decode/nws_1.WAV/dump
stage 2: Json Data Preparation
/media/other/Code/espnet/egs/tedlium2/asr1/../../../utils/data2json.sh --feat decode/nws_1.WAV/dump/feats.scp decode/nws_1.WAV/data decode/nws_1.WAV/dict
/media/other/Code/espnet/egs/tedlium2/asr1/../../../utils/feat_to_shape.sh --cmd run.pl --nj 1 --filetype  --preprocess-conf  --verbose 0 decode/nws_1.WAV/dump/feats.scp decode/nws_1.WAV/data/tmp-oPBaY/input_1/shape.scp
sym2int.pl: replacing X with 1
** Replaced 1 instances of OOVs with 1
stage 3: Decoding

Recognized text: ▁nowing▁and▁the▁s<eos>▁to▁not▁so<eos><eos><eos><eos>▁doing<eos><eos>▁stronger<eos><eos>▁when<eos><eos>▁come▁alon<eos><eos>▁one<eos><eos><eos><eos>▁the▁agreed<eos><eos>▁the▁one<eos><eos>▁st▁in▁making▁the▁tug▁to<eos><eos>▁his<eos><eos>▁the▁consider▁strong▁the▁other<eos><eos>▁the▁northwell▁has▁a▁sec<eos><eos>▁but▁as▁the▁more▁blow<eos><eos>▁the▁more<eos><eos>▁t<eos><eos><eos><eos>▁he's▁on▁him<eos><eos>▁and<eos><eos>▁is▁the▁nose▁we▁end▁up<eos><eos>▁attempt<eos><eos>▁do<eos><eos>▁so▁all<eos><eos>▁and<eos><eos>▁the▁travel<eos><eos><eos><eos>▁and▁it's▁the▁no▁we<eos><eos>▁was<eos><eos>▁to▁to<eos><eos>▁the▁stone▁was▁strong<eos>

**Comment by sw005320** [comment]
In addition to this issue, we have several requests about the segmentation, and currently preparing CTC-based segmentation in #2095
