### ISSUE TITLE
depth option to git

### ISSUE THREAD

**Issue by johnjosephmorgan** [espnet/espnet#2053]
I am trying to install ESPNET with make kaldi=<KLDI_ROOT>. This invokes a command like test -d gitt --depth 1 https://<...>. My version of git does not take --depth as an option. Is there are required version of git?

**Comment by kamo-naoyuki** [comment]
I don't know when --depth option was implemented, but >=2.3.10 has the option anyway. 

https://git-scm.com/docs/git-clone/2.3.10

(--depth option is not mandatory. You can remove it)

By the way, if you specified make KALDI=..,, you wouldn't go to the branch, git --depth clone.

**Comment by johnjosephmorgan** [comment]
> Thanks. git --version tells me 2.7.4.
I must have run just make.
j

**Comment by johnjosephmorgan** [comment]
Actually, looking at that line again, I think the --depth 1 option should go after the clone command. Right?

**Comment by kamo-naoyuki** [comment]
> Actually, looking at that line again, I think the --depth 1 option should go after the clone command. Right?

Oh, yes, you are right.
