### ISSUE TITLE
Pretrained models for egs/m_ailabs

### ISSUE THREAD

**Issue by roholazandie** [espnet/espnet#2054]
Hi,
I was curious to know if there is a pre-trained model for egs/m_ailabs? If not how the script decides to choose male versus female voice for training? Is there any way that we can specify it?

**Comment by sw005320** [comment]
Yes, we have pre-trained models. See https://drive.google.com/drive/folders/1AzB7xtNY1LJM9aMQMOWCvLnq07KbH7gJ

**Comment by roholazandie** [comment]
> Yes, we have pre-trained models. See https://drive.google.com/drive/folders/1AzB7xtNY1LJM9aMQMOWCvLnq07KbH7gJ

Thanks! I tried this model with ljspeech parallel wavgan as vocoder but the outputs are really bad? What I miss here? I searched all your documents but I didn't found any python code that loads the model and vocoder for synthesis.

**Comment by sw005320** [comment]
Unfortunately, you may need to retrain the vocoder. Please check the github page of each vocoder technique. We don't include the training of the vocoder in our recipe.

@kan-bayashi, I think this kind of vocoder-training information should be emphasized more on `README.md`

**Comment by sw005320** [comment]
For now, you can simply use the Griffin-Lim vocoder...

**Comment by kan-bayashi** [comment]
@roholazandie 
> I tried this model with ljspeech parallel wavgan as vocoder but the outputs are really bad. What I miss here? 

M-ailabs recording quality is pretty bad and maybe sampling rate is different between m-ailabs and ljspeech (M-ailabs 16khz vs ljspeech 22.05 khz).
So you cannot combine m-ailabs model with ljspeech vocoder.
If you want to train the vocoder, please check my repository.
https://github.com/kan-bayashi/ParallelWaveGAN/tree/master/egs/README.md
There is no m-ailabs vocoder training recipe since the quality is not good but the recipe template will help you.
https://github.com/kan-bayashi/ParallelWaveGAN/tree/master/egs#how-to-make-the-recipe-for-your-own-dateset

@sw005320 
>  I think this kind of vocoder-training information should be emphasized more on README.md

We already have the info about the training of the vocoder.
https://github.com/espnet/espnet#tts-results
Should I extend the explanation?

**Comment by roholazandie** [comment]
> @roholazandie 
> > I tried this model with ljspeech parallel wavgan as vocoder but the outputs are really bad. What I miss here? 
> 
> M-ailabs recording quality is pretty bad and maybe sampling rate is different between m-ailabs and ljspeech (M-ailabs 16khz vs ljspeech 22.05 khz).
> So you cannot combine m-ailabs model with ljspeech vocoder.
> If you want to train the vocoder, please check my repository.
> https://github.com/kan-bayashi/ParallelWaveGAN/tree/master/egs/README.md
> There is no m-ailabs vocoder training recipe since the quality is not good but the recipe template will help you.
> https://github.com/kan-bayashi/ParallelWaveGAN/tree/master/egs#how-to-make-the-recipe-for-your-own-dateset
> 
> @sw005320 
> >  I think this kind of vocoder-training information should be emphasized more on README.md
> 
> We already have the info about the training of the vocoder.
> https://github.com/espnet/espnet#tts-results
> Should I extend the explanation?

Thanks for your reply. If this is the case I wonder how can i get some pretrained model+vocoder for male voice other than m-ailabs?

**Comment by sw005320** [comment]
> @sw005320
> 
> > I think this kind of vocoder-training information should be emphasized more on README.md
> 
> We already have the info about the training of the vocoder.
> https://github.com/espnet/espnet#tts-results
> Should I extend the explanation?

Yes. 
I know this description. But we still often had this kind of question, so it's better to extend it as you mentioned and may emphasize it more.

**Comment by kan-bayashi** [comment]
> Thanks for your reply. If this is the case I wonder how can I get some pretrained model+vocoder for a male voice other than m-ailabs?

Sorry, there is no good pretrained model for the male voice.
If you know the good corpus of the male voice, I can create the recipe for both text2mel and vocoder models. If you have an idea, please let me know.
