### ISSUE TITLE
Error: it seems that PESQ is not installed.

### ISSUE THREAD

**Issue by 200987299** [espnet/espnet#2057]
Dear all,

I have successfully installed pesq with commands `cd /home/dee/Documents/espnet/egs/chime4/asr1_multich/../../../tools && make pesq`

But I still got error like:
`Error: it seems that PESQ is not installed.
Error: please install PESQ as follows.
Error: cd /home/dee/Documents/espnet/egs/chime4/asr1_multich/../../../tools && make pesq`

when I run run.sh under egs/chime4/asr_multich, can someone help me how to solve this?

Bests
Dee

**Comment by sw005320** [comment]
@sas91, could you check this?

**Comment by kamo-naoyuki** [comment]
I'll check it

**Comment by sw005320** [comment]
> I'll check it

Thanks!
