### ISSUE TITLE
TTS training time comparison

### ISSUE THREAD

**Issue by JaejinCho** [espnet/espnet#2061]
Did anyone compare TTS training times between tacotron2 and fastspeech? If anyone could share just rough comparison results, that would be very appreciated.

I know that fastspeech is much faster in inference but I would like to train fast for my experiments. What I am seeing is fastspeech is slower than tactotron2 in training with the same resources while I expected fastspeech would be also faster in training due to its non-auto-regressiveness.

**Comment by Jackson-Kang** [comment]
When training, both models may be trained with Teacher-forcing to accelerate training speed.

https://towardsdatascience.com/what-is-teacher-forcing-3da6217fed1c

**Comment by Jackson-Kang** [comment]
Teacher-forcing seems to be used for training both models, meaning that they can trained parallelly. Therefore, Tacotron2 also trained non-autoregressively when training.

**Comment by unilight** [comment]
What do you mean by "fastspeech is slower than tactotron2 in training"? Do you mean that it takes longer for Fastspeech to train for one step? Or do you mean that the time to convergence is longer? Although Tacotron2 uses RNN and Fastspeech uses a Transformer-like model structure, Fastspeech is deeper so the computation speed is not guaranteed to be faster. And as mentioned, autoregressiveness is not a problem in training. Also, large models like Transformer-TTS and Fastspeech are more likely to take longer to converge. In my experience, Tacotron2 is still faster in terms of convergence speed.

**Comment by JaejinCho** [comment]
Thanks for the answers @Jackson-Kang @unilight.

@unilight This degree of comparison is enough for me now. I meant the training time taken to convergence when I said "fastspeech is slower than tactotron2 in training".
