### ISSUE TITLE
Python Module-only ASR and TTS Examples

### ISSUE THREAD

**Issue by seanle24245** [espnet/espnet#2073]
I'm trying to figure out how to do ASR and TTS using ONLY the ESPNet python module.  All of the examples and demos I have seen exploring the ESPNet page make use of cloning the ESPNet repository.  Are there any resources or guides for doing this?

**Comment by sw005320** [comment]
Training or inference?
Inference with python only is possible and you can find TTS examples in https://github.com/espnet/espnet#tts-demo

Training is not easy but you could find some examples at Section 4 in https://colab.research.google.com/github/espnet/interspeech2019-tutorial/blob/master/notebooks/interspeech2019_asr/interspeech2019_asr.ipynb#scrollTo=Saco557TUXrS ?

**Comment by seanle24245** [comment]
I'd like to just do inference.  I think I'm just misunderstanding what it means to just use ESPNet as a python module.  Both of the TTS examples require cloning ESPNet.  I was originally thinking I would be able to run a TTS script after doing the python module installation instructions: "pip install torch" and  "pip install espnet", on a virtual environment, without cloning espnet.  I assume that this is not possible then, correct?  Is what I am asking making sense?

**Comment by sw005320** [comment]
Unfortunately, we may need to `pip install` other tools as showing in https://colab.research.google.com/github/espnet/notebook/blob/master/tts_realtime_demo.ipynb, e.g., `pip install -q parallel_wavegan PyYaml unidecode ConfigArgparse g2p_en espnet_tts_frontend`

**Comment by seanle24245** [comment]
I did see that.  The Colab TTS demo still requires cloning the espnet repository.  Is cloning the whole repository always going to be necessary for doing TTS and ASR?

**Comment by sw005320** [comment]
I'm not sure about ASR. For TTS, you can change it to `pip install` but we did not test it.

**Comment by seanle24245** [comment]
Ok thank you.
