### ISSUE TITLE
Python module-only TTS with speaker selection

### ISSUE THREAD

**Issue by seanle24245** [espnet/espnet#2083]
I'm following the colab code for the TTS demo.  I'd like to be able to select a specific speaker.  It was referenced in a previous issue about modifying the "x-vector", if I recall correctly, inside of run.sh.  If I want to do speaker selection using the python module only and without a local clone of ESPNet, how would I approach this?  I assume I would first have to find a multi-speaker model to use first to sub in the "Download pretrained feature generation model" section.

**Comment by kan-bayashi** [comment]
If you want to use pre-calculated x-vector, it can be within Python.
See https://github.com/espnet/espnet/issues/1973
But since x-vector is extracted using kaldi, we cannot extract x-vector within python.

**Comment by seanle24245** [comment]
Thank you.
