### ISSUE TITLE
TTS Quality in the middle of training

### ISSUE THREAD

**Issue by RuslanSel** [espnet/espnet#2089]
I want to train ljspeech.tacotron2.v3, gpu 1.
But after 119 (from 200) epochs wav file sounds like this - https://www.sendspace.com/file/egdzmj.
Is it normal?
Thanks in advance.

**Comment by kan-bayashi** [comment]
It sounds strange. How did you synthesize the audio?

**Comment by RuslanSel** [comment]
1) average_checkpoints.py --backend ${backend} \
                         --snapshots snapshot.ep.119 \
                         --out model.119 \
                         --num 1
2) replaced decode/download/ljspeech.tacotron2.v3/exp/train_no_dev_pytorch_train_pytorch_tacotron2.v3/results/model.last1.avg.best with new model
3) run synth_wav.sh with
fmax=7600     # maximum frequency
fmin=80       # minimum frequency
models=ljspeech.tacotron2.v3
vocoder_models=ljspeech.parallel_wavegan.v1

**Comment by kan-bayashi** [comment]
Thank you for your info.
The `ljspeech.parallel_wavegan.v1` is trained with no-limit mel-spectrogram (0-11025 Hz).
Please use this one.
https://drive.google.com/open?id=1Grn7X9wD35UcDJ5F7chwdTqTa4U7DeVB

**Comment by RuslanSel** [comment]
It seems the quality has not changed.
https://www.sendspace.com/file/ncz8ql
For ljspeech.wavenet.mol.v1 and 100 epochs the sound is also strange: https://www.sendspace.com/file/c7og5d

**Comment by RuslanSel** [comment]
May be the snapshot will help - https://www.sendspace.com/file/4jotmj.

**Comment by kan-bayashi** [comment]
> It seems the quality has not changed.

Really? Did you change the vocoder model?
As you can see in README, `ljspeech.parallel_wavegan.v1` and `ljspeech.wavenet.mol.v1` are traiend with no-limit mel-spectrogram. You need to use the vocoder trained with matched condition.
https://github.com/espnet/espnet#tts-results

**Comment by RuslanSel** [comment]
Yes. Included directory with the same name confused me.
Thank you very much!
