### ISSUE TITLE
QUESTION Does ESPnet suport Melgan

### ISSUE THREAD

**Issue by lonnietc** [espnet/espnet#2093]
Hello,

I am a bit new to TTS & STT systems but am on the lookout for a very good implementation.

From my research so far, it seems that Melgan based vocoders are the latest and greatest thing as they have a much smaller footprint, are faster, and can even run in real-time on CPU based systems (At least from what I have read):

https://blog.descript.com/ultra-fast-audio-synthesis-with-melgan/

With this in mind, I am wondering if ESPnet has a Melgan model for an End-to-End system that could be used in a project?

What I am also wondering is if there is a Docker container version of such as system that could be run on a server and called as needed for STT processing?

Any suggestions would be greatly appreciated.
Thanks in advance

**Comment by kan-bayashi** [comment]
You can use my implementation with my MelGAN (or multi-band MelGAN) implementation.
https://github.com/kan-bayashi/ParallelWaveGAN
Docker image is also available.
But we do not provide the system like API using flask.

**Comment by lonnietc** [comment]
Thanks for the quick reply.

Let me dig into it more and see if I can figure out how to use the base system after which I can see about taking the next steps.

Cheers

**Comment by kan-bayashi** [comment]
For quick demonstration, you can try the following notebook:
https://colab.research.google.com/github/espnet/notebook/blob/master/tts_realtime_demo.ipynb

**Comment by lonnietc** [comment]
I was just trying to colab code and the first part gave some errors, but I am not sure if they are critical:

  Building wheel for parallel-wavegan (setup.py) ... done
  Building wheel for ConfigArgparse (setup.py) ... done
  Building wheel for librosa (setup.py) ... done
  Building wheel for kaldiio (setup.py) ... done
  Building wheel for distance (setup.py) ... done
  Building wheel for jaconv (setup.py) ... done
  Building wheel for clint (setup.py) ... done
  Building wheel for args (setup.py) ... done
ERROR: languageflow 1.1.13a1 has requirement joblib==0.13.2, but you'll have joblib 0.15.1 which is incompatible.
ERROR: languageflow 1.1.13a1 has requirement scikit-learn==0.20.3, but you'll have scikit-learn 0.22.2.post1 which is incompatible.
ERROR: underthesea 1.1.17 has requirement nltk<3.5,>=3.4, but you'll have nltk 3.2.5 which is incompatible.
Switched to a new branch 'v.0.7.0'

------------------------------------

Also, to give you an idea as to what I am moving towards for a Melgan based TTS system, I had also come across this Docker implementation:

https://registry.hub.docker.com/r/pedroetb/tts-api
https://github.com/pedroetb/tts-api

which is a TTS server and I would like to see if it is possible to get a very good Melgan based system installed into something like that as well.  I tested it locally and it work reasonably well but does not have a Melgan based model implemented.

I'm not the author, but like the idea of a independent TTS & STT docker container server so that it could be used on existing websites and other similar projects.

Cheers

**Comment by kan-bayashi** [comment]
You can ignore the errors.
ESPnet mainly focuses on the research so we do not have such a web API but it sounds great.

**Comment by lonnietc** [comment]
Thanks again.

I actually have two projects that I am working on.

One is a rudimentary IPA with Search Engine capabilities that I call "Scarlet" and which is based upon a number of existing libraries like Rasa-Chatbot, etc..

But, the other project is an advanced version of that system which will be Scarlet 2 and that system is highly based on AI and Neural Networks (Perception Evolution Networks which are an advancement over SOINN "Self Organized Incremental Neural Networks" in the unsupervised learning). This will be a true approach that will definitely need a TTS & STT channel for the PCN "Perception Coordination Network (PCN) layer for the NN system. 

I am thinking that your implementation of MelGAN will be extremely useful in this research.
Thanks again and have a good day

**Comment by lonnietc** [comment]
Hello Tomoki,

You gave me a link to the Google Colab:

For quick demonstration, you can try the following notebook:
https://colab.research.google.com/github/espnet/notebook/blob/master/tts_realtime_demo.ipynb

For the Colab testing, I chose the Fasespeech and Multi-band MelGAN after
which the output was really nice and reasonably fast.

I was able to run it on their system but am now wondering if there is a
complete Python script that will let me do the same thing locally on my
Debian 10 machine while not using Colab?

I downloaded some of the needed data files that the Python notebook uses
but could not get things to work locally.

Can you please help me with a single python file for the merger of the
"Setup" and "Synthesis" (English) sections as that would be a great help.

If I can make it run locally, then I can build up a docker container with
an API server that should work, but am still working on my Python skills as
I am coming from a C/C++. Lisp. Assembly, etc.. development background.

Thanks again,
Lonnie

**Comment by kan-bayashi** [comment]
We are developing such a function in #2092, but not yet merged.
I think just copy & paste the code in the notebook should be working.
