### ISSUE TITLE
commonvoice pretrained model bpe missing

### ISSUE THREAD

**Issue by Fpooyan** [espnet/espnet#2099]
Hi
I am trying to use commonvoice pretrained models provided in the repo. while running run.sh in strage 2, bpe model should be provided but it is missing from the downloaded model dir.
any help is highly appreciated!

**Comment by sw005320** [comment]
@ftshijt, could you re-pack the model by including the BPE model?

**Comment by ftshijt** [comment]
Sure, I will repack it soon.

**Comment by Fpooyan** [comment]
Hi.
Thanks for your quick response, but I can not find the added model file in the Persian model directory.
Is it also included?

**Comment by ftshijt** [comment]
> Hi.
> Thanks for your quick response, but I can not find the added model file in the Persian model directory.
> Is it also included?

Thanks for bringing it out. Please check again.
