### ISSUE TITLE
Early stop during TTS model training

### ISSUE THREAD

**Issue by marcosnetopires** [espnet/espnet#2100]
Hi, just wondering if there is a method to do early stopping during training so that I don't have to be constantly monitoring the progress of training.
I'm using the recipe for LJSpeech/tts1 with espnet (not espnet2) and training a Transformer.v3 model.
Thanks

**Comment by kan-bayashi** [comment]
You can change `patience` option.
https://github.com/espnet/espnet/blob/4073e00143e16a6e268b7b5da024cf1db3cf81a1/egs/ljspeech/tts1/conf/tuning/train_pytorch_transformer.v3.yaml#L69
But in the case of TTS model, the validation best model is not always the best in terms of the quality. 
please be careful.

**Comment by v-yunbin** [comment]
@kan-bayashi my training have been interupted when it is epoch 420 （total epoch 1000）, how i restart the training from epoch 420?
