### ISSUE TITLE
TTS Multi-band Melgan

### ISSUE THREAD

**Issue by RuslanSel** [espnet/espnet#2103]
ljspeech.multi_band_melgan.v1 or ljspeech.multi_band_melgan.v2 give this strange result https://www.sendspace.com/file/98j4j4.
With ljspeech.full_band_melgan.v1 or other vocoders everything ok.
Thanks in advance.

**Comment by kan-bayashi** [comment]
You forgot to apply PQMF.
If you use `parallel-wavegan-decode` command, please update `parallel_wavegan` (version 0.4.0).
