### ISSUE TITLE
espnet2 data preparation for the test sets

### ISSUE THREAD

**Issue by sw005320** [espnet/espnet#2105]
@kamo-naoyuki, in espnet2, I found that the eval sets are also pruned in stage 4, which we should not do because we cannot compare it with the other reports.
We should not even remove the utterance that does not have any token because it also changes the sentence error rate.
Could you fix it?

**Comment by kamo-naoyuki** [comment]
Okay

**Comment by kamo-naoyuki** [comment]
Maybe I can't work until the next weekend.
