### ISSUE TITLE
espnet2/bin/split_scps.py is slow

### ISSUE THREAD

**Issue by sw005320** [espnet/espnet#2106]
I found that `split_scps.py` is very slow.
I'm now trying to split the Librispeech text data (40,699,501), which is normal size as a text data, and it takes 20 minutes to process 1,000,000.
So, it would take approximately 800 minutes to split the data.

It may be specific to my own environments to some extent (because CPU load average is ~30%, which means that some data access bottleneck happens).

**Comment by kamo-naoyuki** [comment]
Maybe the following part is the reason: https://github.com/espnet/espnet/blob/e1873ef5cd514fd5aec0ec23d71be98e70ae6448/espnet2/bin/split_scps.py#L58-L62
