### ISSUE TITLE
qsub -N issue

### ISSUE THREAD

**Issue by sw005320** [espnet/espnet#2107]
I encountered qsub job name issue.
In espnet2, the job name is provided by the following option:
`--cmd "${cuda_cmd} --name ${asr_exp}/train.log"`
However, my grid engine qsub does not accept the name with "/".
Probably this is only for SGE and other job schedulers may not have this issue, but several institutes still use SGE and it's better to avoid using "/".

**Comment by kamo-naoyuki** [comment]
Hmm. SGE Is really bad. 
If avoiding "/", the advantage of this option loses totally.
I'll investigate the supporting of the other system, anyway.

**Comment by sw005320** [comment]
Yes, SGE is outdated and has a lot of problems, but it is very difficult to change the job scheduler...

**Comment by nzhoward** [comment]
I am also encountering the same issue with SGE. I have to manually change the name to something without a "/".

**Comment by kamo-naoyuki** [comment]
Sorry, I'll solve somehow if I have time.

**Comment by kamo-naoyuki** [comment]
I fixed
