### ISSUE TITLE
Docker image for raspbian

### ISSUE THREAD

**Issue by Fpooyan** [espnet/espnet#2113]
Hi
I've been trying to install espnet on raspberry pi for a couple of days with no success!! I am having trouble installing sentencepices.
I was wondering if I could use a raspbian-compatible docker image to run on raspberry (I am totally new to docker!).
could you please provide the raspbian image?
Thanks in advance

**Comment by kamo-naoyuki** [comment]
What is your purpose using espnet? It's not always necessary to install all dependencies.
(However, I think sentencepieces can be built on arm)

Raspberry pi is arm architecture and it is incompatible with espnet docker image, which is based on x_86, so you need to build docker image by yourself, but it's same cost as setup espnet without docker.

**Comment by Fpooyan** [comment]
Thanks for your quick response!
I am trying to test one of the pretrained models on RPi just for inference. Without sentencepiece, I could not install espnet and so I can not import it. is there any way to bypass sentencepiece installation?

**Comment by kamo-naoyuki** [comment]
Remove the following line.

https://github.com/espnet/espnet/blob/cb4e446ee220d3a52fd5b05dd85a283424163515/setup.py#L32

Your task is ASR?

The python module for sentencepiece for arm is not provided, you need to build sentencepiece yourself. See the following link.

https://github.com/google/sentencepiece/tree/master/python

**Comment by Fpooyan** [comment]
yes I am working on ASR models.
I once tried to build sentencepiece from source but it failed with the same error as installing using pip. but I'd try to test building from source again.
BTW, thanks for providing the link.
