### ISSUE TITLE
/kaldi/tools/config/common_path.sh is not present

### ISSUE THREAD

**Issue by jlian2** [espnet/espnet#2115]
Once I am running a recipe, it shows: The standard file /home/ubuntu/espnet/egs/an4/asr1/../../../tools/kaldi/tools/config/common_path.sh is not present -> Exit!

Once I checked tools under kaldi, there is actually no "config".
When "make check_install", it succeeds.

So, where is "config"?

**Comment by kamo-naoyuki** [comment]
You seems not to install Kaldi correctly. It exists here: https://github.com/kaldi-asr/kaldi/tree/master/tools/config
