### ISSUE TITLE
synthesis using multi-speaker tacotron libitts pre-trained model

### ISSUE THREAD

**Issue by AyaHamdy** [espnet/espnet#2118]
Please i need help,
i download multispeaker tacotron pretrained model, how i can use it for synthesizing wav using specific speaker ?

**Comment by sw005320** [comment]
There are several similar questions/discussions, e.g., https://github.com/espnet/espnet/issues/1973
Could you check them first?

@kan-bayashi, if @AyaHamdy still cannot follow it, maybe it’s good time to add some more documentations about multi-speaker tacotron. This is really nice function (thought the performance in the open speaker would be an issue (an interesting research direction)), and this would attract espnet-tts more :)
