### ISSUE TITLE
cupy out of memory error when running the voxforge example

### ISSUE THREAD

**Issue by meisongzhu** [espnet/espnet#212]
When I was running the voxforge example, the job failed in the stage 3: network training. In the log file, it indicates that an out of memory error occured. 

My working computer has only one Quadro M1000M GPU card which has 2GB display memory. What should I do to avoid this kind of error?

The log file is provided below:
[train.log](https://github.com/espnet/espnet/files/2092415/train.log)

**Comment by meisongzhu** [comment]
Thanks. I will try it later.

**Comment by shubham-IISc** [comment]
thanks a lot. it worked
