### ISSUE TITLE
 rnn-t streaming decoding

### ISSUE THREAD

**Issue by lyjzsyzlt** [espnet/espnet#2120]
Is there an implementation of rnn-t streaming decoding?

**Comment by b-flo** [comment]
Hi,

Streaming RNN-T is not available in espnet. Some work was done internally but it was put in standby. I can't really say when we'll work on it again as there are a lot of other works related to RNN-T/T-T we have to finish.

**Comment by lyjzsyzlt** [comment]
Thank you for your reply! I found that rnn-t beam search decoding was very slow. Will you optimize this next?

**Comment by b-flo** [comment]
Yes, I'll propose different beam search algorithms which significantly improve decoding time. It should be available really soon.
