### ISSUE TITLE
Libritts run.sh error

### ISSUE THREAD

**Issue by seanle24245** [espnet/espnet#2121]
I'm getting this error when I try to run run.sh in the libritts tts1 directory:

utils/validate_data_dir.sh: text contains 1 lines with non-printable characters

I don't know where I could be getting this error from.  I haven't made any modifications to anything inside of libritts.

**Comment by sw005320** [comment]
I encountered the same problem, which is recently introduced in Kaldi.
I'll report it to Kaldi people, but you can avoid this by directly editing `validate_data_dir.sh` as follows for now:
`non_print=true`

**Comment by kamo-naoyuki** [comment]
Should we fix kaldi version? I think the updating of Kaldi is unnecessary for us.
