### ISSUE TITLE
TTS Vocoder for new languages

### ISSUE THREAD

**Issue by mailong25** [espnet/espnet#2123]
Thanks for amazing repository. I'm interested in building TTS engine for Vietnamese language (with Vietnamese single-speaker dataset).

I have been successfully synthesize speech with Tacotron2(trained on Vietnamse dataset) and WaveGlow(trained on ljspeech).

However, when I try to use tacotron2 + parallel wavegan(trained on ljspeech) ([via this](https://github.com/kan-bayashi/ParallelWaveGAN/issues/169)), the results are much worse than WaveGlow.

**Should I retrain the parallel wavegan model on other language datasets?**. Our dataset is quite different than ljspeech dataset in term of audio quality.

Also, will transfer learning from english model help ?

**Comment by kan-bayashi** [comment]
> Should I retrain the parallel wavegan model on other language datasets?.

Yes, you should. ljspeech is a single speaker dataset. So the model has not so much robustness for different speakers. Or you can try a multi-speaker model (But I did not prepare 22.05k multi-speaker model, all models are 24k).

> Also, will transfer learning from english model help ?

In the case of vocoder, the language difference is not so affected. So I think you can use the ljspeech model as an initial model.

**Comment by mailong25** [comment]
Thanks for a quick response. I'm start the training now and will notify the result when it completed.

**Comment by mailong25** [comment]
It works beautifully !
