### ISSUE TITLE
Where is the recipe of Multi-speaker TTS ?

### ISSUE THREAD

**Issue by tranctan** [espnet/espnet#2125]
Hi, I saw an announcement of **Multi-speaker TTS with pretrained speaker embedding** in README file, but i cannot find which recipe and which model is used specifically. 

Can anyone tell me about this one. Thanks a lot !

**Comment by kan-bayashi** [comment]
Try `egs/libritts/tts1` for English or `egs/jnas/tts1` for Japanese.
