### ISSUE TITLE
scoring flexibility in espnet2

### ISSUE THREAD

**Issue by sw005320** [espnet/espnet#2127]
The current espnet2 scoring only deals with `sclite`. However, several measure tasks (e.g., SWBD and the original AMI Kaldi recipe) use a special scoring script (e.g., https://github.com/espnet/espnet/blob/master/egs/swbd/asr1/run.sh#L301-L305), special filtering, different tools (e.g., asclite). So this part should have some flexibility. We need some re-design for the scoring part.

**Comment by sw005320** [comment]
We can do it when we create the espnet2 swbd recipe.

**Comment by yash-s20** [comment]
So as I understand this is a kaldi dependency for espnet2?

**Comment by kamo-naoyuki** [comment]
You don't need to compile kaldi itself, but need to compile sctk only. Sorry this is not documented. I forgot it.

```sh
cd kaldi/tools
make sph2pipe sclite
```

You can also obtain it from https://www.openslr.org/resources/4/ manually.

**Comment by sw005320** [comment]
How about including the install of `sph2pipe` and `sclite` in espnet?

**Comment by sw005320** [comment]
But we may still need to set the path, so it is not an easy solution.

**Comment by yash-s20** [comment]
Thanks @kamo-naoyuki , I was able to run the entire pipeline now.

**Comment by rishabh135** [comment]
Fount this issue and moreover since it seems that sclite installation requires Python2.7, would be great if there can be an update on the readme to resolve this error!
