### ISSUE TITLE
Does LibriSpeech train and test with maxlen_in=800  and max_out=150

### ISSUE THREAD

**Issue by zh794390558** [espnet/espnet#213]
```
maxlen_in=800  # if input length  > maxlen_in, batchsize is automatically reduced
maxlen_out=150
```

**Comment by kan-bayashi** [comment]
Sorry, what is the your question?

**Comment by zh794390558** [comment]
Does LibriSpeech train and test with maxlen_in=800 and max_out=150

**Comment by kan-bayashi** [comment]
If not work due to out of memory error, please follow the instruction (#212).

**Comment by zh794390558** [comment]
I think if using `maxlen_in=800 ` and `max_out=150`, the training and test phase will not contained all data. Does this affect the result ?
