### ISSUE TITLE
inconsistent sampling rate

### ISSUE THREAD

**Issue by Fpooyan** [espnet/espnet#2131]
Hi
While doing inference using the commonvoice pretrained ASR models, I noticed that the train set sampling rate is 48000 while the sampling rate is set to 16000 in .conf files for feature extraction.
I would appreciate it if anyone could explain this!!

**Comment by kan-bayashi** [comment]
The sampling rate is changed to 16k during feature extraction stage on-the-fly manner.
https://github.com/espnet/espnet/blob/1bba19c599c1acc799b6da79bd8db4e3e86f1c92/egs/commonvoice/asr1/local/data_prep.pl#L57

**Comment by Fpooyan** [comment]
could you please explain a bit more? I am wondering if sampling rate of both train and inference stages must be the same.

**Comment by kan-bayashi** [comment]
> could you please explain a bit more? I am wondering if sampling rate of both train and inference stages must be the same.

Yes, all of the sets (train, dev, and eval) are downsampled to 16k during feature extraction.
If you want to use pretrained model, you must downsample your audio to 16k Hz.

**Comment by Fpooyan** [comment]
Yes your'e right! I didnt notice that
Thanks a lot
