### ISSUE TITLE
Error of default  language model setting for  espnet2 WSJ task

### ISSUE THREAD

**Issue by hchung12** [espnet/espnet#2143]
In the default LM training configuration file "espnet/egs2/wsj/asr1/conf/tuning/train_lm.yaml", the best_model_criterion may be wrong:
best_model_criterion:
-   - valid
    - acc
    - max

It should be 
best_model_criterion:
-   - valid
    - loss
    - min

**Comment by kamo-naoyuki** [comment]
Thanks! You are right.
