### ISSUE TITLE
About segment and window streaming implementation

### ISSUE THREAD

**Issue by lyjzsyzlt** [espnet/espnet#2152]
Could you tell me the implementation of segment and window streaming recognition in espnet based on which papers?

**Comment by sw005320** [comment]
The implementation is based on this technique
https://ieeexplore.ieee.org/abstract/document/9054358/
However, this technique only uses utterance-level streaming based on VAD.
We're planning to implement several streaming techniques, which have some latency control based on the window size.

**Comment by lyjzsyzlt** [comment]
ok,thank you~




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Shinji Watanabe"<notifications@github.com&gt;;
发送时间:&nbsp;2020年7月6日(星期一) 晚上9:52
收件人:&nbsp;"espnet/espnet"<espnet@noreply.github.com&gt;;
抄送:&nbsp;"爱可乐的松鼠"<444190504@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [espnet/espnet] About segment and window streaming implementation (#2152)





 
The implementation is based on this technique
 https://ieeexplore.ieee.org/abstract/document/9054358/
 However, this technique only uses utterance-level streaming based on VAD.
 We're planning to implement several streaming techniques, which have some latency control based on the window size.
