### ISSUE TITLE
Is there any recipe provides knowledge distillation for ASR?

### ISSUE THREAD

**Issue by gnlenfn** [espnet/espnet#2156]
Hello,

I'm planning to adopt knowledge distillation on asr.
Is there any recipe to use in espnet?

**Comment by sw005320** [comment]
We don't have such a recipe in ASR, but the TTS based on fastspeech https://github.com/espnet/espnet/search?q=knowledge+distilation&unscoped_q=knowledge+distilation uses knowledge distillation, and you may check it.

**Comment by gnlenfn** [comment]
Thanks for the reference.
Actually, I'm pretty new in KD.
Is it possible to make KD with  of tts to asr?
