### ISSUE TITLE
TTS training with small datasets

### ISSUE THREAD

**Issue by gafsd** [espnet/espnet#2159]
Hello, I am trying to use transfer learning with your pretrained tacotron v4 model on a small phoneme-based dataset (1 hour) and just wondering how to optimise this. It trains pretty well and quickly but the final model sometimes has issues generalising and will change pitch/fade away in long sentences even though attention looks good in training. What can I change to improve this?

Thoughts:
- I know the dataset size is small but it is difficult to increase size - I am ok with trading off some things as long as it roughly approximates the original voice
- I am wondering if I should finetune vocoder as well (and how to do this) - just using pretrained at the moment
- I have reduced size of deveval set substantially due to small dataset
- I am using your v4 model and wondering if I should prefer a different model
- I have tried training for a few thousand epochs but output quality is unstable and not improving much
- transformer is probably too slow and unstable training to use

**Comment by kan-bayashi** [comment]
>  will change pitch/fade away in long sentences even though attention looks good in training.

Short utterance is OK? In that case, you can try `use-att-constraint` to make the long sentence generation stable.

> I am wondering if I should finetune vocoder as well (and how to do this) - just using pretrained at the moment

In the case PWG, fine-tunning with a small amount of training data works well.

**Comment by gafsd** [comment]
I am already using this for vocoder inference:
"threshold": 0.5,
"minlenratio": 0.0, 
"maxlenratio": 15.0,
"use_attention_constraint": True, 
"backward_window": 1,
"forward_window": 3,

Short utterance <2s is usually ok but long deteriorates. https://www.dropbox.com/s/gcz3e2hknt0ljzu/individualImage.png?dl=0 example attention during training (not perfect but I expected reasonable output). I am trying training with some different parameters. 

I tried fine-tuning PWG but after 50k iterations the output started to degrade with lots of noise.

**Comment by kan-bayashi** [comment]
OK.
How was the preprocessing of your dataset?
You must carefully check the unnecessary silence.
Especially, if there is a silence which does not correspond to any token, that affects the performance.

**Comment by gafsd** [comment]
The dataset is not high quality recording and there is some background noise (unavoidable) but I have tried to remove all unnecessary silence. There may be some silences of 20ms or so at the start of some recordings - is that ok?

Example waveform:
![Capture](https://user-images.githubusercontent.com/62999745/87162307-54e20d00-c2f8-11ea-91ce-ed79b2495fe1.PNG)

**Comment by gafsd** [comment]
@kan-bayashi I wonder if this is result of text preprocessing? In my dataset I have removed all punctuation except apostrophe (no full stops or commas due to transcription process). Would adding 'fake' punctuation based on perceived sentence boundaries improve things do you think?

**Comment by kan-bayashi** [comment]
If your data includes pause which does not correspond to any symbol, it causes performance degradation and blurred attention. It is better to consider adding some punctuation.

**Comment by gafsd** [comment]
How long pause do you consider? Because the transcription has no punctuation I will have to add in commas and fullstops based on pause length.

**Comment by kan-bayashi** [comment]
I have no idea about the clear definition of the pause length.
Maybe more than a few frames.

**Comment by gafsd** [comment]
Tried with reworked punctuation but still having issues. I wonder if my inference setup is wrong? I am using modified colab notebook for espnet 1.x. 

https://gist.github.com/gafsd/0b397bdccb08b61078dda948092ef52d
