### ISSUE TITLE
'mtl_mode' in espnet/asr/pytorch_backend/asr.py

### ISSUE THREAD

**Issue by wxt1997** [espnet/espnet#2162]
Is this should be 'elif' in ctc mode? Otherwise, the "transducer" mode is not used. The source codes are as follows:
`if " transducer" in args.model_module:
    assert args.mtlalpha == 1.0
    mtl_mde = "transducer"
    logging.info("Pure transducer mode")
if args.mtlalpha == 1.0:
    mtl_mde = "ctc"
    logging.info("Pure CTC mode")`
Another question: why we must use ctc in transducer mode ?

**Comment by wxt1997** [comment]
```
if "transducer" in args.model_module:   
    assert args.mtlalpha == 1.0   
    mtl_mode = "transducer"   
    logging.info("Pure transducer mode")   
if args.mtlalpha == 1.0:   
    mtl_mode = "ctc"   
    logging.info("Pure CTC mode")
```

**Comment by b-flo** [comment]
Hi,

Thanks for pointing it out, I found out another typo after checking the file. I'll add the fixes in my current PR.
Btw, bote that it doesn't impact transducer training, only the log message displayed.

> Another question: why we must use ctc in transducer mode ?

Short answer: because ESPnet ASR was created and designed for CTC/Attention MTL. It was easier to base transducer mode on CTC mode rather than making global changes or duplicating a lot of parts.

**Comment by wxt1997** [comment]
> Hi,
> 
> Thanks for pointing it out, I found out another typo after checking the file. I'll add the fixes in my current PR.
> Btw, note that it doesn't impact transducer training, only the log message displayed.
> 
> > Another question: why we must use ctc in transducer mode ?
> 
> Short answer: because ESPnet ASR was created and designed for CTC/Attention MTL. It was easier to base transducer mode on CTC mode rather than making global changes or duplicating a lot of parts.

Thanks for your awesome work!  
I noticed that in `espnet/asr/asr.py` the use of transducer is to jump directly to `espnet/nets/pytorch_backend/e2e_asr_transducer.py` through `espnet/utils/dynamic_import.py` and the `mlt_mode` in asr.py is uselss.  
Therefore, is it possible to create a pure transducer without ctc by making some changes on `espnet/nets/pytorch_backend/e2e_asr_transducer.py` without change other files.

**Comment by b-flo** [comment]
`mtl_mode`, which is defined by `mtlalpha`, in `asr.py` controls several things such as used criterion and trainer definition! It may be easier to do a "pure" transducer mode now though, I'll have to check recent changes as I'm not up-to-date on some general modifications done is last months.
