### ISSUE TITLE
Q: egs2 still largely mentions Kaldi dir structures

### ISSUE THREAD

**Issue by vikrantsharma7** [espnet/espnet#2163]
I was under the assumption that espnet2 would largely be kaldi-free, but the TEMPLATE readme still has a huge section devoted to Kaldi data directory structures.
At least for TTS,  the LJSpeech directory structure is quite usable and straightforward and yet there are a bunch of steps just to transform the data to Kaldi expectations.
It may be beneficial for combining ASR and TTS "recipes", is what i gathered from TEMPALTE.
Just want to understand the motivations behind these decisions, and would love to know more.
Thanks.

**Comment by kamo-naoyuki** [comment]
We meant Kaldi-free by independent from the executable binary file of Kaldi and it doesn't mean discarding Kaldi style.

The benefit is that we can run experiment without compiling Kaldi and, for ASR, we can inference without Kaldi, that means, we can inference only using Python.

I'm not sure what you desire. Even if we discarded kaldi style and selected any other formats, there are still a trasformation steps to the disired format anyway. We just selected one of them.
