### ISSUE TITLE
How to debug in espnet code

### ISSUE THREAD

**Issue by Jxu-Thu** [espnet/espnet#2172]
How can I use debug tool like. 'PDB' to debug codes?

**Comment by sw005320** [comment]
I'm often using `pudb`. Then, my way is as follows:

1. set a path `. ./path.sh`
2. install `pudb` by `pip install pudb` (only first time)
3. get a full command argument from the log file, e.g. the third line in `head exp/exp/train_nodev_pytorch_train_mtlalpha1.0/train.log`
4. execute it with `pudb3 ../../../espnet/bin/asr_train.py <full command arguments>`

**Comment by Jxu-Thu** [comment]
Thanks for your kind reply!
