### ISSUE TITLE
Multi-Speaker Tacotron 2 Tensor Size Mismatch

### ISSUE THREAD

**Issue by seanle24245** [espnet/espnet#2174]
I'm trying to use the pre-trained multi speaker tacotron 2 combined with extracted speaker embeddings to produce individual speaker's voices.  I have the speaker embeddings stores in a .pkl file, and I am choosing one at random to produce.  Most of my code is identical to the TTS colab demo, except that I have changed the model and dict path to the respective places in the multi-tacotron2 folder.  I am getting an error in this line:

`c, _, _ = model.inference(x, inference_args, spemb=sps.to(device))`

Where sps is a tensor representing the speaker embedding.  I'm getting this error here:

'RuntimeError: size mismatch, m1: [3 x 2441], m2: [1024 x 128] at /pytorch/aten/src/TH/generic/THTensorMath.cpp:41'

The m1 dimensions change every time I run it, so I'm thinking it has to do with the speaker embeddings I'm providing it.  The 1st dimension "3" stays constant, but it is the second dimension "2441" that just keeps changing.  I've tried printing sps.size(), and the size changes every time, but I don't get how that relates to the dimensions the model needs, or how I would fix it.  If anyone could provide any hints or suggestions that would be greatly appreciated.  If it helps too here is a pastebin of the code: 

[https://pastebin.com/15Rc18GF](https://pastebin.com/15Rc18GF)

**Comment by kan-bayashi** [comment]
How did you extract x-vector?
I want to know the `sps.shape`.

**Comment by seanle24245** [comment]
I'm using @mapa17 's xvector_extractor.py linked here: [https://gist.github.com/mapa17/aa9ef769d8b1a906e75908e9686513a3](https://gist.github.com/mapa17/aa9ef769d8b1a906e75908e9686513a3)

For my last run I got `torch.Size([461])` for sps.shape.  Also the m1 dimension that I thought didn't change went from 3 to 5 this run.

**Comment by kan-bayashi** [comment]
Our used X-vector is 512 dimension.
So `sps.shape` should be `torch.Size([512])`.

**Comment by seanle24245** [comment]
I was extracting from the wrong folder.  I was able to extract x-vectors with the proper dimensions (512).  However, when I pass them into the multi-speaker tacotron2 the audio is unintelligible.  Strange.
