### ISSUE TITLE
Training TTS on Korean langauage

### ISSUE THREAD

**Issue by r406** [espnet/espnet#2175]
I would like to train the TTS with korean language speaker similar to that of of ljspeech using conf/tuning/train_pytorch_tacotron2.v3.yaml. Kindly could you guide on how to process the korean text data associated with audio recordings.

**Comment by sw005320** [comment]
As you can see in the ljspeech text processing part, it requires linguistic knowledge, and we may not able to help it due to the lack of knowledge about Korean.
