### ISSUE TITLE
Unsupported GPU architecture 'compute_30'

### ISSUE THREAD

**Issue by Arafat4341** [espnet/espnet#2177]
I am trying to setup espnet on a google cloud machine with Ubuntu 20.04. 
`NVIDIA-SMI 450.51.05    Driver Version: 450.51.05    CUDA Version: 11.0`

I am receiving an error while setting up:
`nvcc fatal   : Unsupported gpu architecture 'compute_30'`

Can anyone tell me the reason?!
Thanks in advance!

**Comment by kamo-naoyuki** [comment]
CUDA11 drops supporting of Kepler GPUs.

**Comment by Arafat4341** [comment]
@kamo-naoyuki Thanks for responding!
Can I install cuda10 for ubuntu 20.04 ?

**Comment by kamo-naoyuki** [comment]
See cuda documentation.

**Comment by Arafat4341** [comment]
Yes I have seen.. For ubuntu 20.04 they give cuda11.
I am finding the answer: if I uninstall cuda11 completely and install cuda 10, will it work!
Just not finding the answer! 
Sorry for bothering you!
