### ISSUE TITLE
How can I use custom data in Data Preparation pipeline?

### ISSUE THREAD

**Issue by ajaysg** [espnet/espnet#2178]

**Comment by sw005320** [comment]
I recommend you to check the Kaldi documentation https://kaldi-asr.org/doc/data_prep.html and other Kaldi tutorials.

**Comment by ajaysg** [comment]
THank you. Can I use only CPU for training and inference of espnet?

**Comment by kamo-naoyuki** [comment]
We define several options in run.sh

https://github.com/espnet/espnet/blob/cf12d0ea3f4bf2325310b4c2da397ff52f330ff8/egs/yesno/asr1/run.sh#L13

and ngpu=0 indicates cpu mode.

```sh
./run.sh --ngpu 0
``` 

but training on CPU is not realistic.

**Comment by ajaysg** [comment]
Atleast can I run inference in CPU?
