### ISSUE TITLE
chime5 results

### ISSUE THREAD

**Issue by wolverineq** [espnet/espnet#218]
Was the RESULTS in chime5/asr1 correspond to the run.sh?
For me I got about 10% worse WER than yours after running the original chime5/asr1/run.sh script and this makes me confused. Maybe you could offer me some tips on that? 
Thanks

**Comment by wolverineq** [comment]
@sw005320 I used the v.0.1.0 release. However, I still got worse results (about 4% worse in WER) after running the original run.sh script. Now I suspect maybe there was something wrong with my data preprocessing, so could you tell me how many utterances are there in your data/train_worn_u200k/feats.scp & data/train_worn/feats.scp?

**Comment by sw005320** [comment]
I don't have `data/train_worn/feats.scp` but I have `data/train_worn/segments`
```
 wc -l ../../chime5/asr1/data/train_worn_u200k/feats.scp ../../chime5/asr1/data/train_worn/segments
  359281 ../../chime5/asr1/data/train_worn_u200k/feats.scp
  159934 ../../chime5/asr1/data/train_worn/segments
```
I hope it will help you find some reasons.

**Comment by wolverineq** [comment]
Now I see the difference.
There were 159934 utts in my data/train_worn/segments too, however there were only 318835 utts remained in my data/train_worn_u200k/feats.scp after running this line in run.sh:

'remove_longshortdata.sh --nlsyms ${nlsyms} --minchars 1 data/train_worn_u200k_org data/train_worn_u200k'

So have you run this command or not? How many utts are there in your final dump/train_worn_u200k/deltafalse/feats.scp?

**Comment by wolverineq** [comment]
Could anyone answer that for me please, many thanks!

**Comment by sw005320** [comment]
Sorry, for the late response. I performed `remove_longshortdata.sh`, and then obtained the above utterance.
```
$ wc -l data/train_worn_u200k_org/feats.scp
359874 data/train_worn_u200k_org/feats.scp
```

**Comment by wolverineq** [comment]
Yes I also had 359874 utts in data/train_worn_u200k_org/feats.scp. 
What about the number in data/train_worn_u200k/feats.scp since that is the feature directory used in end-to-end training?

**Comment by sw005320** [comment]
359281 utterances, as I showed you in the previous thread.

**Comment by sw005320** [comment]
It might be caused by `--minchars 1`. Can you test it with `--minchars 0`?

**Comment by wolverineq** [comment]
Thanks very much! I get the problem now.

**Comment by sw005320** [comment]
This would be my fault. I was checking several configurations, and may leave wrong one. Once you get some similar results to my report, I'll fix it. So, please tell me your new result once you get it.

**Comment by wolverineq** [comment]
OK，I am re-running the baseline script and will keep you informed of the results.
