### ISSUE TITLE
Is the Multilingual ASR recipe in "li10" a Universal Speech Recognizer?

### ISSUE THREAD

**Issue by ElinaBaral** [espnet/espnet#2180]
Since the multilingual recipes seems to concatenate the data of different language and train them with the same ASR training script so I wanted to know if it works as universal speech recognizer or does it performs language identification task as a part of multitask learning by taking language code/set as language identifier.

**Comment by sw005320** [comment]
It's working as universal speech recognizer.
The recipe does not explicitly include the language ID token (https://github.com/espnet/espnet/blob/master/egs/li42/asr1/run.sh includes language ID tokens)
