### ISSUE TITLE
espnet/egs/chime4 notes

### ISSUE THREAD

**Issue by 200987299** [espnet/espnet#2182]
Dear all,

If you are going to run chime4 script, please be careful how you organized your export folder (data files). Make sure you generated isolated_1ch_track, isolated_2ch_track and the isolated_6ch_track according to the chime4 official website. Be aware that you need to delete the channel number part on all .wav files' name under 1 channel track folder. The Espnet recipe doesn't do that automatically. 

Make sure you extracted and re-arrange your wsj files under CHiME3 folder and also within the corpora5 folder. 

When I done stage 0-4, my server died in stage 5, all my PID status became zombie. I followed the instruction on 'use of GPU' but it doesn't work. Actually it gives an error when I delete the ngpu variable in run.sh (hope someone could edit the instruction page). The way I over pass here is by reducing the nj (how many parallel jobs) in stage 5 from 48 (or 32??) to 8, and used cpu mode in docker to execute. (Later, I tried the GPU version and it works as well).

Thanks for the help @yuekaizhang @sw005320 

Good luck guys

**Comment by sw005320** [comment]
Thanks for your note. Please let us know if you have something particularly required some help from us.
