### ISSUE TITLE
asr librispeech's results is much better than reported results

### ISSUE THREAD

**Issue by Jxu-Thu** [espnet/espnet#2184]
I follow librispeech ASR trainning recipe at espnet/egs/librispeech/asr1/run.sh.
I rerun run.sh and get the results as follows:
test clean

write a CER (or TER) result in ###/checkpoint_asr_nas/exp/train_960_pytorch_train_specaug/decode_test_clean_model.acc.best_decode_lm_no_avg/result.txt
|    SPKR           |    # Snt       # Wrd     |    Corr          Sub          Del          Ins           Err        S.Err    |
|    Sum/Avg        |     328         9771     |    97.7          1.5          0.8          0.3           2.6         27.1    |
write a WER result in /##/checkpoint_asr_nas/exp/train_960_pytorch_train_specaug/decode_test_clean_model.acc.best_decode_lm_no_avg/result.wrd.txt
|    SPKR            |    # Snt       # Wrd     |    Corr           Sub          Del           Ins           Err        S.Err     |
|    Sum/Avg         |     328         7809     |    98.2           1.5          0.3           0.2           2.0         27.1     |

My results is 2.0 that is much better than 2.5. Is is possible?
My model.json is attached.

[model.json.log](https://github.com/espnet/espnet/files/4944039/model.json.log)

**Comment by JiayiFu** [comment]
@Jxu-Thu Hi Jxu-Thu, have you found the cause of this result? How about the results if you remove the LM fusion?

**Comment by Jxu-Thu** [comment]
I am sorry that I made a mistake. The results was close to the published results. 
The results above are only part of all sentences. (328 / 2260)

**Comment by JiayiFu** [comment]
@Jxu-Thu I get it. Thanks for your reply.

**Comment by JiayiFu** [comment]
@Jxu-Thu How about your results if you remove the LM fusion? The RESULT file doesn't contain the WER without LM. So I'm curious about this. :-)
