### ISSUE TITLE
ASR support batch inference? Or any other methods to speed up inference?

### ISSUE THREAD

**Issue by Jxu-Thu** [espnet/espnet#2186]
Espnet is a good codebase. Thanks very much!
But I find that It is slow for inference. It takes about 10 hours to infer test-clean dataset of librispeech (utterances = 2620)
Could espnet support batch inference?  (Or I haven't found it but already support?)

I run the codes follow espnet/egs/librispeech/asr1/run.sh

**Comment by sw005320** [comment]
api v1 is rather fast, and also support GPU decoding (with multiple utterance batch processing).
We're also fixing api v2 speed, so if you want to use the default setup, please wait for a while.

**Comment by Jxu-Thu** [comment]
How to use api v1? 
Just change the "api --v2" to "api --v1"  and change the batchsize  at the run.sh script?

**Comment by sw005320** [comment]
yes, please try `--api v2` and increase the batch size.

**Comment by Jxu-Thu** [comment]
I tried it.
for --api v1 , it raise error
"NotImplementedError: Batch decoding is not supported yet."

for --api v2, it raise error
"NotImplementedError: multi-utt batch decoding is not implemented"

**Comment by b-flo** [comment]
Hi,

`--api v2` should be used with `batchsize: 1` in decode config to enable "batch decoding".
The issue is due to a naming which can be confusing for some users: "batch decoding" (processing multiple hypotheses in parallel) and "multi-utterances batch" (processing of multiple utterances and hypotheses in parallel).

Some documentation or changes will be added soon related to that.

**Comment by zwglory** [comment]
> I tried it.
> for --api v1 , it raise error
> "NotImplementedError: Batch decoding is not supported yet."
> 
> for --api v2, it raise error
> "NotImplementedError: multi-utt batch decoding is not implemented"

Hi，I got same problem about inference, have you fix it?

**Comment by zwglory** [comment]
> > I tried it.
> > for --api v1 , it raise error
> > "NotImplementedError: Batch decoding is not supported yet."
> > for --api v2, it raise error
> > "NotImplementedError: multi-utt batch decoding is not implemented"
> 
> Hi，I got same problem about inference, have you fix it?

it seem like just NOT ok for e2e_asr_transformer, may it work for e2e_asr.py with --api v1

**Comment by Peidong-Wang** [comment]
For e2e_asr_transformer, a workaround could be setting:

`nj` greater than 1, say 8, based on the memory of your GPU
`--batchsize 1`
`--api v2`
`--ngpu 1`

This may speed up decoding by 8x.

**Comment by ldeseynes** [comment]
@Peidong-Wang this workaround only works if you have mutliple short audio files to decode, doesn't it ?

Is there a way to speed up inference for long audio files using an e2e_asr_transformer and https://github.com/espnet/espnet/blob/master/utils/recog_wav.sh ? For example, decoding a 20min audio with librispeech.transformer.v1. 

For now the best solution so far is to perform external segmentation (because CTC VAD is not available for transformer models) of the audio and run decoding with `api v2` and `ngpu 1`, but increasing `nj` would only speed up a bit the feature computation part, which is not the critical step.

**Comment by sw005320** [comment]
Transformer for long audios is a hot research topic.
We have several studies based on block-wise self attentions (e.g., https://arxiv.org/abs/2006.14941), and we are also planning to implement some of them in espnet in the future, but it is not soon.
For now, the best solution is to use external VAD as you mentioned.

**Comment by zwglory** [comment]
e2e_asr_transformer only supply api.v2 decode when bachsize==1, I write batch-inference for transformer by myself just like e2e_asr:recognize_batch, and speed up decoding by 20x. 

The CTCPrefixScore is the bottleneck of batch inference, this is O(maxlen^2). But CTC is necessary for finding <eos>. i am tring to use subsample to fine tune transformer.

**Comment by ldeseynes** [comment]
@zwglory how have you changed recognize_beam_batch() to make it work for transformers ?

**Comment by zwglory** [comment]
> @zwglory how have you changed recognize_beam_batch() to make it work for transformers ?

`espnet/nets/pytorch_backend/e2e_asr_transformer.py:E2E.recognize()` is the decode method. 

You can achieve `E2E.recognize_batch()` just like `espnet/nets/pytorch_backend/e2e_asr.py:E2E.recognize_batch()` and `espnet/nets/pytorch_backend/rnn/decoders.py:Decoder.recognize_beam_batch()`.

And the encoder decoder functions already support for input shape(B, T, D). You only need to change the input and output of the RNN to Transformer.

But this only speed up 20x, and 50x after distillation and subsampling. Our goal is 100x, and ctc-prefix-score is the bottleneck. We are considering rewriting in C++ for this part. Chunk-wise Attention should also be a feasible method.

**Comment by tjysdsg** [comment]
Any updates on this? The decoding speed is too slow for CPU, and it seems that espnet2 doesn't support multi-gpu inference?

**Comment by sw005320** [comment]
We don't support multi-gpu inference but we support a parallel computing environment based on https://kaldi-asr.org/doc/queue.html

**Comment by wangydong** [comment]
> > @zwglory how have you changed recognize_beam_batch() to make it work for transformers ?
> 
> `espnet/nets/pytorch_backend/e2e_asr_transformer.py:E2E.recognize()` is the decode method.
> 
> You can achieve `E2E.recognize_batch()` just like `espnet/nets/pytorch_backend/e2e_asr.py:E2E.recognize_batch()` and `espnet/nets/pytorch_backend/rnn/decoders.py:Decoder.recognize_beam_batch()`.
> 
> And the encoder decoder functions already support for input shape(B, T, D). You only need to change the input and output of the RNN to Transformer.
> 
> But this only speed up 20x, and 50x after distillation and subsampling. Our goal is 100x, and ctc-prefix-score is the bottleneck. We are considering rewriting in C++ for this part. Chunk-wise Attention should also be a feasible method.



> > @zwglory how have you changed recognize_beam_batch() to make it work for transformers ?
> 
> `espnet/nets/pytorch_backend/e2e_asr_transformer.py:E2E.recognize()` is the decode method.
> 
> You can achieve `E2E.recognize_batch()` just like `espnet/nets/pytorch_backend/e2e_asr.py:E2E.recognize_batch()` and `espnet/nets/pytorch_backend/rnn/decoders.py:Decoder.recognize_beam_batch()`.
> 
> And the encoder decoder functions already support for input shape(B, T, D). You only need to change the input and output of the RNN to Transformer.
> 
> But this only speed up 20x, and 50x after distillation and subsampling. Our goal is 100x, and ctc-prefix-score is the bottleneck. We are considering rewriting in C++ for this part. Chunk-wise Attention should also be a feasible method.

Could you share the code of E2E.recognize_batch() in Transformer please?

**Comment by wangydong** [comment]
> > @zwglory how have you changed recognize_beam_batch() to make it work for transformers ?
> 
> `espnet/nets/pytorch_backend/e2e_asr_transformer.py:E2E.recognize()` is the decode method.
> 
> You can achieve `E2E.recognize_batch()` just like `espnet/nets/pytorch_backend/e2e_asr.py:E2E.recognize_batch()` and `espnet/nets/pytorch_backend/rnn/decoders.py:Decoder.recognize_beam_batch()`.
> 
> And the encoder decoder functions already support for input shape(B, T, D). You only need to change the input and output of the RNN to Transformer.
> 
> But this only speed up 20x, and 50x after distillation and subsampling. Our goal is 100x, and ctc-prefix-score is the bottleneck. We are considering rewriting in C++ for this part. Chunk-wise Attention should also be a feasible method.

I have solved this problem, it  can multi-utterances batch decoding now.

**Comment by srikanthk20** [comment]
@wangydong  ... can you pls share the code base of how you achieved the batch support... Will be an interesting learn
