### ISSUE TITLE
FastSpeech training results gradually deteriorate

### ISSUE THREAD

**Issue by RuslanSel** [espnet/espnet#2187]
I trained FastSpeech on Tacotron2 (custom dataset), but model gradually deteriorate.
https://www.sendspace.com/file/ce4trv - 10 epochs.
https://www.sendspace.com/file/ieel3r - 20 epochs.
https://www.sendspace.com/file/eyr5sz - 30 epochs.

Thanks in advance.

**Comment by kan-bayashi** [comment]
Could you provide the training curve?

**Comment by RuslanSel** [comment]
all_loss.png - [https://www.sendspace.com/file/2528kc](url)

**Comment by kan-bayashi** [comment]
The training curve seems strange, maybe preprocessing is something wrong.
Could you provide the procedure of your training?

**Comment by RuslanSel** [comment]
Train.log - https://www.sendspace.com/file/9asogl (i restart training from 20 epochs).
