### ISSUE TITLE
Update chainer to v6.7.0?

### ISSUE THREAD

**Issue by kamo-naoyuki** [espnet/espnet#2188]
I'm ignoring the version conflict of protobuf between chainer=6.0.0 and tensorboardX in a long time because we doesn't use chainer except for its trainer and also note that we doesn't need to use tensorboardX because pytorch already includes its function. It's really waste of time to spend our energy for this topic. 
However, now I faced a problem about version conflicting, so I must solve this problem.

I know that chainer=7 is incompatible with our espnet, so we need to use chainer=6 at least.
I found that chainer=6.5,6.6,6.7 doesn't include the version restriction for protobuf, https://github.com/chainer/chainer/blob/v6.7.0/setup.py, so maybe we should use v6.7.0.

I don't have any resources to test this, but I'd like to solve this problem soon. Can anyone test espnet with chainer=6.7.0?

**Comment by kamo-naoyuki** [comment]
Can anyone help, please.

**Comment by kan-bayashi** [comment]
I will check it this evening!

**Comment by kan-bayashi** [comment]
I tested with:

- chainer 6.7.0
- cupy 6.7.0

I confirmed that `egs/yesnot/asr1` worked well with both --backend chainer and pytorch.
And `ci/test_ingregration.sh` finished without errors.

**Comment by kamo-naoyuki** [comment]
Okay, thanks! Multi gpus also works well?

**Comment by kan-bayashi** [comment]
Hmm... Multi-GPU did not work well with chainer backend.

|    | cupy 6.0.0 | cupy 6.5.0 | cupy 6.7.0 | 
| :-: | :-: | :-: | :-: |
| chainer 6.0.0 | ○ | - | - | 
| chainer 6.5.0 | x | × | - |
| chainer 6.7.0 | x | - | × |

**Comment by kan-bayashi** [comment]
And I found that ESPnet1 with torch=1.5.1 + multi-gpu did not work well.

```bash
Exception in main training loop: Caught StopIteration in replica 0 on device 0.
Original Traceback (most recent call last):
  File "/home/t_hayashi/workspace3/work/espnet/tools/venv/lib/python3.7/site-packages/torch/nn/parallel/parallel_
apply.py", line 60, in _worker
    output = module(*input, **kwargs)
  File "/home/t_hayashi/workspace3/work/espnet/tools/venv/lib/python3.7/site-packages/torch/nn/modules/module.py"
, line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/work3/t_hayashi/work/espnet/espnet/nets/pytorch_backend/e2e_asr.py", line 357, in forward
    hs_pad, hlens, _ = self.enc(hs_pad, hlens)
  File "/home/t_hayashi/workspace3/work/espnet/tools/venv/lib/python3.7/site-packages/torch/nn/modules/module.py"
, line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/work3/t_hayashi/work/espnet/espnet/nets/pytorch_backend/rnn/encoders.py", line 320, in forward
    mask = to_device(self, make_pad_mask(ilens).unsqueeze(-1))
  File "/work3/t_hayashi/work/espnet/espnet/nets/pytorch_backend/nets_utils.py", line 24, in to_device
    device = next(m.parameters()).device
StopIteration
```

**Comment by kan-bayashi** [comment]
Related:
https://github.com/pytorch/pytorch/pull/33907
https://github.com/huggingface/transformers/issues/3936

**Comment by kamo-naoyuki** [comment]
>    device = next(m.parameters()).device

Someone already reported this issues? This line seems to send StopIteration, so it can be solved if we derives the device number using the other way, e.g. from input tensor.

**Comment by kan-bayashi** [comment]
> PyTorch 1.5 changes the handling of nn.Parameters in DataParallel replicas. (pytorch/pytorch#33907). The replicas now don't have parameters() anymore.

We should change `next(m.parameters()).device`

**Comment by kan-bayashi** [comment]
Oh already @unilight reported in #2169
