### ISSUE TITLE
CUDA check memory error

### ISSUE THREAD

**Issue by shubham-IISc** [espnet/espnet#219]
I am using single GPU for librispeech task. Is it necessary to use multiple GPU? I am getting following error while training.
THCudaCheck FAIL file=/pytorch/torch/lib/THC/generic/THCStorage.cu line=58 error=2 : out of memory
Exception in main training loop: cuda runtime error (2) : out of memory at /pytorch/torch/lib/THC/generic/THCStorage.cu:58

I have incorporated commit suggested in  FIXED VARIABLE FLAG IN EVALUATION #192 but still error remains the same.
can someone please guide?

Thanks

**Comment by kan-bayashi** [comment]
Please follow the instruction in the issue (#212).
