### ISSUE TITLE
Synthesized audio quality is poor by using pre-trained WaveNet vocoder model

### ISSUE THREAD

**Issue by mindmapper15** [espnet/espnet#2191]
I trained tacotron 2 model with LJSpeech Dataset with default setting.

Synthesized mel spectrogram seems to fine but when I converted synthesized mel spectrogram to audio with pre-trained WaveNet Vocoder model (ljspeech.wavenet.mol.v2) described in README page, the synthesized audio has very poor quality compared to synthesized mel spectrogram.

I extracted synthesized mel spectrogram from feats.ark and save those with npy format.

This is the synthesized mel spectrogram from LJSpeech dev set.
![fbank_espnet](https://user-images.githubusercontent.com/40658807/88029994-aa7aad00-cb75-11ea-991a-7075ddfa6471.png)

And this is the converted audio from synthesized mel spectrogram I attatched

![fbank_after_vocoder](https://user-images.githubusercontent.com/40658807/88031092-13165980-cb77-11ea-94e8-369c55b6cfd0.png)

[LJ049-0151.zip](https://github.com/espnet/espnet/files/4952159/LJ049-0151.zip)

I've done peak normalize to the synthesized audio because its amplitude is too small

Is this model trained properly? If so, did I put synthesized mel spectrogram to vocoder in wrong way?

**Comment by kan-bayashi** [comment]
It seems something wrong.
Please check the following points:
- Are the feature setting the same among the models? (fmax, fmin, ...)
- Did you use normalized features? (not `denorm`)

**Comment by kan-bayashi** [comment]
For reference:
https://drive.google.com/drive/folders/1JFNZapygWsHiP2CXMjTraLzf98h-tEBF?usp=sharing

**Comment by mindmapper15** [comment]
> * Are the feature setting the same among the models? (fmax, fmin, ...)

I used ljspeech.wavenet.mol.v2 model which was trained with mel range 80 ~ 7600Hz
This mel range is same as default setting in LJSpeech TTS recipe in espnet.

> * Did you use normalized features? (not `denorm`)

I extracted mel spectrogram from egs/ljspeech/tts1/exp/char_train_no_dev_pytorch_train_pytorch_tacotron2/outputs_model.last1.avg.best_decode_denorm/feats.ark. As far as I know, this feature file contains synthesized mel spectrogram which is denormalized at stage 5 in run.sh by following command.

`apply-cmvn --norm-vars=true --reverse=true data/${train_set}/cmvn.ark \
            scp:${outdir}/${name}/feats.scp \
            ark,scp:${outdir}_denorm/${name}/feats.ark,${outdir}_denorm/${name}/feats.scp`

so probably it's not the normalized feature I think.

**Comment by kan-bayashi** [comment]
Yes, that is de-normalized feature.
Please use outputs_model.last1.avg.best_decode/feats.ark as the  input of WaveNet.

**Comment by mindmapper15** [comment]
![Figure_1](https://user-images.githubusercontent.com/40658807/88122308-3981d680-cc03-11ea-9087-aa55cb50fe34.png)
[LJ049-0151.zip](https://github.com/espnet/espnet/files/4957236/LJ049-0151.zip)

I changed wavenet input to normalized feature and now it seems work!
Thank you for the corrections!

Problem solved so I'll close this issue.
