### ISSUE TITLE
Pretrained multi-speaker Tacotron2 with LJSpeech xvector

### ISSUE THREAD

**Issue by RuslanSel** [espnet/espnet#2194]
I made xvector for 1272_128104 speaker from LJSpeech corpus (18 files) with sid/nnet3/xvector/extract_xvectors.sh.
Then I run tts_decode.py with pretrained model train_clean_460_pytorch_train_pytorch_tacotron2+spkemb.
Then parallel-wavegan-decode with ljspeech.multi_band_melgan.v1.
The resulting wav file on utterance LJ049-0008 from LJSpeech is not so good - https://www.sendspace.com/file/hzloas.

Thanks in advance.

**Comment by seanle24245** [comment]
I'm having this issue as well except on the libritts experiment.  I'm using the same multi-speaker model as you and the audio is unintelligible.

**Comment by kan-bayashi** [comment]
Unfortunately, the quality of `egs/libritts/tts1` pretrained model for open speaker is not so good.
Recently, I implement global style token in ESPnet2 (#2139).
Not well documented yet, but you can try it.

**Comment by kan-bayashi** [comment]
I remembered that the input for `egs/libritts/tts1` pretrained model is uncased char, not phoneme.
(e.g. Hello, world.)

**Comment by RuslanSel** [comment]
Yes, it was the problem with the input format. I used uppercase characters like in LJSpeech.
Thank you!
