### ISSUE TITLE
RNN-T beam search loop break condition possibly sub-optimal

### ISSUE THREAD

**Issue by xkr1** [espnet/espnet#2195]
In the current implementation of the RNN-T beam search (https://github.com/espnet/espnet/blob/0fe5068a356f5e48beac25117fa1d6c2ad799452/espnet/nets/pytorch_backend/transducer/rnn_decoders.py#L214), analysing the code suggests to me that the following happens:

- At each timestep, pick the best existing hypothesis, new_hyp, from hyps and run prediction/joint network on final symbol using existing state history
- Loop through each candidate symbol in the output distribution and:
-- if it's the blank symbol, add the new path (new_hyp + blank) to the kept_hyps list
-- if it's not the blank symbol, add the new path (new hyp + symbol) to the hyps list for possible selection in a future iteration of the loop
- end the loop when len(kept_hyps) > k_range, where k_range will more often than not be the beam width

I think I may have noticed an issue with the loop exit condition. In Graves' original paper, this loop is terminated when "B contains less than W elements _more probable than the most probable in A_".

With the current approach I believe there's a risk of the following scenario:

- Imagine that all but one of the top hypotheses in the kept_hyps list from the previous step (now hyps) has a weak chance of outputting the blank symbol at the current time step.
- The first (best score from the previous time step) hypothesis to be chosen from hyps is evaluated and added to the new kept_hyps list after adding the blank label to the sequence. Remember, this score is pretty bad due to low probability of blank. 
- All other expanded hyps are added to the hyps list, and one of these symbols has a particularly high score, so the expanded hyp score is still high (let's pretend probabilities are blank = 0.00001 and symbol A = 0.99999 so the expanded path score remains almost the same as the original path score)
- Next time round the loop, we pick that last expanded path (from the previous step) from the hyps list as even after expansion the score is still higher than the others. We add the blank symbol, add that new hyp to the kept_hyps list and continue as usual. We now have two paths in the kept_hyps list that originate from one path in the original list.
- Now imagine that the expansion of the final hyp in the original kept_hyps list has a really high blank probability at the current time step, which would rank it above some of the other hyps in kept_hyps. The problem here is that it **will not be evaluated** as kept_hyps has already hit the k_range condition (the beam width)

This is where I believe the condition of "more probable than the most probable in A" becomes important in Graves' original algorithm as it would allow one (or more) of the low probability paths to be discarded to make way for the expansion of the final (least probable) path from the last step, which may end up actually ranked higher than another path which originally appeared more promising after all are expanded.

I hope the above is at least reasonably clear - please let me know if I've misunderstood something in the algorithm implementation.

**Comment by b-flo** [comment]
Hi,

> I think I may have noticed an issue with the loop exit condition. In Graves' original paper, this loop is terminated when "B contains less than W elements more probable than the most probable in A".
>
>With the current approach I believe there's a risk of the following scenario:
> ...

You're right, it could be a risk! After extensive test on several part of the algorithm, I found out the current condition was always satisfied but it could potentially end-up in a similar scenario that the one you described.
I already changed the condition to the original one in #2082 ;)

I'll close the issue, feel free to ask further questions if you want though!
