### ISSUE TITLE
Modifications to Colab TTS demo to work with Multi Speaker Model and LibriTTS

### ISSUE THREAD

**Issue by seanle24245** [espnet/espnet#2213]
I'm modifying the colab TTS demo code to work with speaker embeddings extracted from the libriTTS experiment.  In the TTS demo portion of the README it is stated that: 

"Important Note:
This code does not include text frontend part. Please clean the input text manually. Also, you need to modify feature configuration according to the model. Default setting is for ljspeech models, so if you want to use other pretrained models, please modify the parameters by yourself. For our provided models, you can find them in the below table."

If I want to use the multi-speaker tacotron 2, what are the "default" settings that I need to change within the colab code?  Is it inference_args?  What portion of the demo is specific for LJspeech that I need to change?

**Comment by kan-bayashi** [comment]
The main difference is feature extraction setting and input format.
If you want to use libritts pretrained model + PWG, please use uncased char as the inputs for `egs/libritts/tts1` pretrained model.

**Comment by seanle24245** [comment]
Thank you!  I didn't realize I had to change trans_type to "char" instead of "phn".  What exactly does phn mean?  Does trans_type mean transformer type?  Also, I see that on the list of usable pretrained vocoder models there is "libritts.wavenet.mol.v1".  Is this vocoder usable with the TTS-Demo code?  I see that the two files inside are of type .pth and .json instead of .pkl and .yaml.

**Comment by seanle24245** [comment]
I'm using the lj speech parallel wavegan for the moment during synthesis.  Would using the libritts wavenet potentially improve the quality?

**Comment by kan-bayashi** [comment]
> What exactly does phn mean?

phn means phoneme.

> Is this vocoder usable with the TTS-Demo code

Sorry, WaveNet model is not supported in colab demo.
Please check this part.
https://github.com/espnet/espnet/blob/43093fab17885cbf717ad505f978442364f1dcd0/utils/synth_wav.sh#L342-L354

> Would using the libritts wavenet potentially improve the quality?

It can improve, but the generation is super slow compared with PWG.

**Comment by seanle24245** [comment]
Thank you!
