### ISSUE TITLE
Espnet installation doubt!!

### ISSUE THREAD

**Issue by ajaysg** [espnet/espnet#2224]
Do I have to install Kaldi before running the following commands for CPU installation?
`$ cd <espnet-root>/tools`
`$ make KALDI=<kaldi-root> CUPY_VERSION='' -j 10`

or the above commands will install Kaldi?

Also one more question,
I have pre-installed conda in my system, but the above commands are downloading conda again and installing. Is it safer to run the above commands inside pre-installed conda environment?

**Comment by kamo-naoyuki** [comment]
Please read our documentation.

If you have an anaconda but you want to recreate it by the Makefile, then I recommend you deactivating the environment.

**Comment by ajaysg** [comment]
I read the documentation and Installed Kaldi as per Step 2. But when I run the above mentioned Commands for espnet installation as per Step 3B, Kaldi is again being downloaded and installed. That's why I asked the question.

**Comment by kamo-naoyuki** [comment]
Read the Makefile. You can understand it can't happen.
