### ISSUE TITLE
Can NOT reproduce the result of Transformer End-to-End ST on Must-C En-De

### ISSUE THREAD

**Issue by LittleChenCc** [espnet/espnet#2228]
I would like to ask if the config file given in the directory can be used to reproduce the results. I can reproduce the results of ASR-MTL, but not the results of e2e without MTL, or even fail to learn the semantic relation at all. Is there any trick I should be aware of? And can you tell me the number of GPUs you are using? Thanks a lot.

**Comment by hirofumi0810** [comment]
@LittleChenCc Multitask or pre-training is essential for training Transformer-based ST.

**Comment by LittleChenCc** [comment]
I saw there is a result which is 16.40 for Transformer in md. I thought it should be the result of end-to-end model without MTL or PT, right? But I can't reproduce the result. My model can only achieve a meaningless result lower than 5.

**Comment by LittleChenCc** [comment]
> @LittleChenCc Multitask or pre-training is essential for training Transformer-based ST.

I saw there is a result which is 16.40 for Transformer in md. I thought it should be the result of end-to-end model without MTL or PT, right? But I can't reproduce the result. My model can only achieve a meaningless result lower than 5.

**Comment by hirofumi0810** [comment]
Although I don't remember the details, I might have got that number based on the codebase at that time.
But it is not stable and not reliable (it depends on the seed etc.).
And we know the solutions.
Why do you stick to the training from scratch?

**Comment by LittleChenCc** [comment]
> Although I don't remember the details, I might have got that number based on the codebase at that time.
> But it is not stable and not reliable (it depends on the seed etc.).
> And we know the solutions.
> Why do you stick to the training from scratch?

I do agree with you, MTL or PT is essential for training ST. But I need a reasonable baseline result for my current research project, which does not use the transcription in ST, like [this paper](https://www.aclweb.org/anthology/N16-1109.pdf). So a comparable baseline is required. : )

**Comment by hirofumi0810** [comment]
I see. If you can use other ASR corpora, ASR encoder pre-training is effective. Otherwise, you might be able to train RNN models from scratch with a single ST objective.

**Comment by LittleChenCc** [comment]
> I see. If you can use other ASR corpora, ASR encoder pre-training is effective. Otherwise, you might be able to train RNN models from scratch with a single ST objective.

I am trying to train an RNN-base model to see the result, it's much slower than training Transformer. Anyways, thanks for your advice.

**Comment by HelloMaster1954** [comment]
@LittleChenCc Hi, i had the same problem. I can't reproduce the BLEU score of 16.40 in must_c dataset. 
The BLEU is lower than 5. This also confuses me. With the multi-task learning, i achieve the same BLEU of 22.31. 
Similar phenomena also appear in libri_trans dataset. The BLEU drops to 7.82 from 15.71 without multi-task learning.
Have you found anything new?
