### ISSUE TITLE
Could not find a version that satisfies the requirement cupy-cuda102==6.0.0 

### ISSUE THREAD

**Issue by HuJK** [espnet/espnet#2229]
```
ERROR: Could not find a version that satisfies the requirement cupy-cuda102==6.0.0 (from versions: 7.2.0, 7.3.0, 7.4.0, 7.5.0, 7.6.0, 8.0.0a1, 8.0.0b1, 8.0.0b2, 8.0.0b3, 8.0.0b4)
``` 
cupy-cuda102 doesn't have version 6.0.0 , upgrade ```CHAINER_VERSION := 6.0.0``` to ```CHAINER_VERSION := 7.4.0```, please

**Comment by kamo-naoyuki** [comment]
I see, thank you for the quick report. I'll update the makefile to care it, but ESPnet requires chainer=6.0.0, so the workaround is:

```sh
make PIP_CHAINER="chainer==6.0.0 cupy==6.0.0"   # Use not bundled cupy
make PIP_CHAINER="chainer==6.0.0"  # If you'll use pytorch backend only
make CHAINER_VERSION=""  # If you'll use espnet2 only
```

**Comment by kamo-naoyuki** [comment]
Sorry, I told false. Cupy==6.0.0 doesn't support 10.2, so `pip install cupy==6.0.0` is failed too, isn't it? I don't have cuda==10.2 now.

**Comment by HuJK** [comment]
```pip install cupy==6.0.0``` success,but ```pip install cupy-cuda102``` failed. 

https://github.com/espnet/espnet/blob/43093fab17885cbf717ad505f978442364f1dcd0/tools/Makefile#L39

**Comment by kamo-naoyuki** [comment]
Thanks. Officially cupy==6.0.0 with cuda=10.2 is not provided, so I'll decide disabling cupy if cuda=10.2 or later.

**Comment by HuJK** [comment]
They don't provide pre-built binary, but ```pip install cupy==6.0.0``` success.

I think use ```cupy==6.0.0``` instead of ```cupy-cuda102==6.0.0``` would better. (but slower, because  ```pip install cupy==6.0.0``` will compile cupy in time)

**Comment by kamo-naoyuki** [comment]
It doesn't support officially, so I think disabling is better. We can't test it for all cases.
