### ISSUE TITLE
bug: Expected object of backend CPU but got bacKend CUDA

### ISSUE THREAD

**Issue by mmmmayi** [espnet/espnet#2232]
When I run the egs/voxforge/asr1/run_rnnt.sh with 4 GPU and train cofig of conf/tuning/transducer/train_transducer_both_init.yaml, I met the error of 
`RuntimeError: Expected object of backend CPU but got backend CUDA for sequence element 1 in sequence argument 1 in sequence argument at position #1 'tensors'`.

The error occured beacuse of the code `ey = torch.cat((eys, att_c),dim=1)` in rnn_decoders.py.

**Comment by b-flo** [comment]
Hi,

I suppose you met the bug when `report_cer=True` or/and `report_wer=True`?

**Comment by mmmmayi** [comment]
> Hi,
> 
> I suppose you met the bug when `report_cer=True` or/and `report_wer=True`?

yes. do I need to set them as False? why?

**Comment by b-flo** [comment]
I was just guessing what was the reason for the bug :)

I'll fix that, you can set the options to False for now.

**Comment by b-flo** [comment]
I just tested CER/WER reporting with RNN-T att. and It seems I already fixed this bug when I unified search methods in my current PR. I'm closing this issue, the fix should be available next week I think!
