### ISSUE TITLE
Question: windowsize in location-aware attention

### ISSUE THREAD

**Issue by zhucq** [espnet/espnet#2234]
Hi, now I am use the LAS ASR model with "location-aware attention". I read the paper "Attention-Based Models for Speech Recognition", but find nothing about the windowsize.
In  your function "_apply_attention_constraint", "backward_window=1, forward_window=3". I am confused by those narrow window.
For example, my encode is 300 length, is it mean I will consume most 3 encode length when decoding a out?
What's wrong with my idea? Thank you.

**Comment by sw005320** [comment]
We use very long filter size for ASR (e.g., 100) https://github.com/espnet/espnet/blob/master/egs/voxforge/asr1/conf/tuning/train_rnn.yaml#L14
Please check the configuration file instead of the default value in the class.

**Comment by kan-bayashi** [comment]
`_apply_attention_constraint ` is the function for TTS, which is introduced in Deep Voice 3.
What you have to check is `aconv-filts`.

**Comment by zhucq** [comment]
> We use very long filter size for ASR (e.g., 100) https://github.com/espnet/espnet/blob/master/egs/voxforge/asr1/conf/tuning/train_rnn.yaml#L14
> Please check the configuration file instead of the default value in the class.

Thank you very much,
![image](https://user-images.githubusercontent.com/39935745/88798224-28266480-d1d7-11ea-9694-966f5c00677b.png)
Does you mean the k =10 and r = 100 ?
![image](https://user-images.githubusercontent.com/39935745/88798421-73407780-d1d7-11ea-80cf-e880b4c0068c.png)
And the “Sharpening” in this paper not apply ?

**Comment by sw005320** [comment]
> Does you mean the k =10 and r = 100 ?

yes.

> And the “Sharpening” in this paper not apply ?

yes. (https://github.com/espnet/espnet/blob/6f6452a3891d11b0b0306084dd46a464ddf8e25c/espnet/nets/chainer_backend/rnn/attentions.py#L124)

**Comment by zhucq** [comment]
> `_apply_attention_constraint ` is the function for TTS, which is introduced in Deep Voice 3.
> What you have to check is `aconv-filts`.



> > Does you mean the k =10 and r = 100 ?
> 
> yes.
> 
> > And the “Sharpening” in this paper not apply ?
> 
> yes. (
> 
> https://github.com/espnet/espnet/blob/6f6452a3891d11b0b0306084dd46a464ddf8e25c/espnet/nets/chainer_backend/rnn/attentions.py#L124
> 
> )

Understand, Thank you so much. I will close this.
