### ISSUE TITLE
Voxforge [en] - missing reference files

### ISSUE THREAD

**Issue by mdabek** [espnet/espnet#2236]
Hi,
I am using the Voxforge based experiment with RNN-T and I've set language to english in run_rnnt.sh
The training completes and during decoding I am receiving the following errors:
```
Error: Not enough Reference files loaded
Missing:
    (otuyelu-otuyelu-20101107-crp-b0213)
write a CER (or TER) result in exp/tr_en_pytorch_train_transducer/decode_et_en_decode_transducer/result.txt
Error: Not enough Reference files loaded

(...)

Error: Not enough Reference files loaded
Missing:
    (martin0amy-martin0amy-20111106-pwg-a0497)
write a CER (or TER) result in exp/tr_en_pytorch_train_transducer/decode_dt_en_decode_transducer/result.txt
Error: Not enough Reference files loaded
Missing:
    (martin0amy-martin0amy-20111106-pwg-a0497)
write a WER result in exp/tr_en_pytorch_train_transducer/decode_dt_en_decode_transducer/result.wrd.txt
./run_rnnt.sh: 2 background jobs are failed.
```
The training for italian language works fine. Is there any additional configuration I should update?

**Comment by desiredeveloper** [comment]
I am facing the same issue with the default arguments on 'en' dataset
```
python tokenize_text.py -f 2- --input - --output - --token_type char --non_linguistic_symbols none --remove_non_linguistic_symbols true
```
```
Error: Not enough Reference files loaded
Missing:
    (martin0amy-20111106-pwg-a0492)
    (otuyelu-20101107-crp-b0212)

```

**Comment by simpleoier** [comment]
I ran the voxforge on `en` dataset. I met the same problem and solved it in some hack way. First, the error message is
```bash
$ sclite -r ref.trn trn -h hyp.trn trn -i rm -o all stdout > result.txt 
Error: Not enough Reference files loaded
Missing:
    (otuyelu-otuyelu-20101107-crp-b0212)
    (otuyelu-otuyelu-20101107-crp-b0215)
```
I found that in the `ref.trn` and `hyp.trn` files, there are two similar uttids, one is `otuyelu-otuyelu-20101107-crp-b0212` and a similar one with case difference `Otuyelu-Otuyelu-20101107-crp-b0212`.

My solution is to rename one of them, e.g. `Otuyelu-Otuyelu-20101107-crp-b0212` -> `Otuyelu-Otuyelu-20101107-crp-b0212-1`. Similar thing was done for the second utterance. Then the error is resolved.

Not clear why this error happens. Maybe `sclite` cannot differentiate the case difference in utterance names.

**Comment by sw005320** [comment]
> Not clear why this error happens. Maybe `sclite` cannot differentiate the case difference in utterance names.

I think so.
Is it possible to add some patches to the recipe in the near future?
You could do it in the scoring stage or data preparation stage.

**Comment by simpleoier** [comment]
Yes, I will put this to my list, after this rushing period.
