### ISSUE TITLE
why egs2 get worse result than egs at aishell

### ISSUE THREAD

**Issue by sigpro** [espnet/espnet#2247]
From your results, egs2 get worse result in aishell , is there any different parameter ?
Thanks for your work!

**Comment by kamo-naoyuki** [comment]
Paarameter looks same and the feature is completely same, so It should reproduce the result originally. I'm not sure about this.

- There are some difference between espnet1 and 2( but, I don't think it affects much)
    - Optimizer scheduler
    - Batchify method
- The config file of espnet2 uses patience, but ESPnet1's config doesn't set it. (I think this is crucial)
- Some bugs?

We haven't tuned espnet2 configuration, so basically espnet2' result is worse than 1.

**Comment by sw005320** [comment]
> * There are some difference between espnet1 and 2( but, I don't think it affects much)
>   
>   * Optimizer scheduler
>   * Batchify method

This is actually very important (fortunately or unfortunately)
espnet1 finally found a very robust setup with @ShigekiKarita's efforts, but I still cannot find such hyperparameters in espnet2.

Also, the espnet2 default feature is critically different (pitch feature and 8ms shift), which affects the performance and hyperparameters related to the number of samples.

But for the aishell task, I'm getting the number close to espnet1. I'd share it once I confirm that this setup can be applicable to the other tasks like espnet1.

**Comment by kamo-naoyuki** [comment]
@sw005320 Oh, I'm grad to hear that.

**Comment by xvolica** [comment]
I am using hkust to test the difference between espnet1 and espnet2.
Using same parameters, the espnet2 get worse result than espnet1:


Corr | Sub | Del | Ins | Err | S.Err
-- | -- | -- | -- | -- | --
Espnet1.0 | 78.9 | 17.4 | 3.7 | 3.5 | 24.5 | 73
Espnet2.0,lr=0.005 | 74.9 | 20.1 | 5 | 3.2 | 28.3 | 77.2
Espnet2.0,noam | 76.5 | 18.8 | 4.7 | 3.3 | 26.8 | 75.9
