### ISSUE TITLE
why I need to set every python shell road?such lm_train.py asr_train.py

### ISSUE THREAD

**Issue by xcrpkuss** [espnet/espnet#2248]
In stage 3:LM Preparation and stage 4: Network Training, I also come across the same trouble:
![image](https://user-images.githubusercontent.com/56855140/88997778-17830500-d323-11ea-89bd-fd11118d9578.png)

"run.pl: job failed, log is in exp/train_nodev_pytorch_train_mtlalpha1.0/train.log"
and the log file is also simple:
![image](https://user-images.githubusercontent.com/56855140/88997482-6aa88800-d322-11ea-8bf8-486ba24d5160.png)
I know I can rewrite the road of asr_train.py in the run.sh,but for this problem, do I have some mistake while insatlling?
Why I need to reset every python road in run.sh?What can I do to reset them all?
Do this problem may impace the final result?

**Comment by xcrpkuss** [comment]
And every project,I have another same error:
"AttributeError: module 'matplotlib' has no attribute 'use'",the version of the matplotlib is 3.1.0
But they all have this error.
I delete the line to solve.But why it exist?
Thank you!

**Comment by kamo-naoyuki** [comment]
> asr_train.py: command not found.

I can't understand why you met this error.

- Could you show your `path.sh`?
- Could you show the contents of espnet/bin with `ls -l`?
- Do you have python at espnet/tools/venv?

> "AttributeError: module 'matplotlib' has no attribute 'use'",the version of the matplotlib is 3.1.0
I don't know why you met error, but matplotlib has `use` method basically: https://matplotlib.org/3.1.1/api/matplotlib_configuration_api.html?highlight=use#matplotlib.use

I don't know about this, but anyway, your matplotlib is not correct. I recommend you reinstalling it.

**Comment by xcrpkuss** [comment]
![image](https://user-images.githubusercontent.com/56855140/88999752-fe308780-d327-11ea-85b5-fbf0537c5ea5.png)
They all in espnet/bin,but I can't call them in run.sh.
And I  change the road of python in path.sh,do it make mistake?
![image](https://user-images.githubusercontent.com/56855140/88999689-d3deca00-d327-11ea-952d-930f8aca1aa0.png)
I don't use python in tools/venv/bin,but in my conda.
How can I solve it?
Really,Thank you!

**Comment by kamo-naoyuki** [comment]
It's obviously wrong. Why you rewrite path.sh so...

```sh
export PATH=$MAIN_ROOT/utils:$MAIN_ROOT/espnet/bin:$PATH
```
