### ISSUE TITLE
Bug in Colab

### ISSUE THREAD

**Issue by YangHan-Morningstar** [espnet/espnet#2262]
When I use the TTS demo in Colab, I got an error which is "fatal: Remote branch fix_import not found in upstream origin"in git clone. Could you tell me how to solve it? Thanks a lot!

**Comment by kan-bayashi** [comment]
Sorry, this is my fault.
To quick fix, please change the line as follows:
`!git clone -q https://github.com/kan-bayashi/espnet.git -b fix_import`
to 
`!git clone -q https://github.com/espnet/espnet.git`

I will fix lator.

**Comment by YangHan-Morningstar** [comment]
OK, thank you!
