### ISSUE TITLE
fail to install kenlm，"undefined reference to `pthread_create'"

### ISSUE THREAD

**Issue by xcrpkuss** [espnet/espnet#2264]
1.In run shell ./install_kenlm.sh,and have some errors. 
![image](https://user-images.githubusercontent.com/56855140/89252099-5ed30380-d64b-11ea-8b01-b738dc8c1d01.png)
"In function `main':CheckSymbolExists.c:(.text+0x1b):
 undefined reference to `pthread_create'"
![image](https://user-images.githubusercontent.com/56855140/89252123-701c1000-d64b-11ea-8b83-6df64211f0cf.png)

2.I search some solution,and add in CMakeList in kenlm,but still didn't work:
"
cmake_minimum_required(VERSION 2.6)

# Define a single cmake project
project(kenlm)

find_package(Threads REQUIRED)
set(THREADS_PREFER_PTHREAD_FLAG ON)
add_executable(${PROJECT_NAME} "CheckSymbolExists.c")
target_link_libraries(${PROJECT_NAME} PRIVATE Threads::Threads)
“
3.Can I replace this package?Or I need find way to install it?

**Comment by kamo-naoyuki** [comment]
The first one indicates that you don't have boost simply.

I can install kenlm without problem, so this is not an installation issue of espnet. You should ask at the other place.
At least, you should write your OS, gcc, and etc. whenever asking about compile issue.

**Comment by xcrpkuss** [comment]
> The first one indicates that you don't have boost simply.
> 
> I can install kenlm without problem, so this is not an installation issue of espnet. You should ask at the other place.
> At least, you should write your OS, gcc, and etc. whenever asking about compile issue.

Yes ,it's because the install of boost,when I set the location of boost.it run ok.

**Comment by kamo-naoyuki** [comment]
i see, thanks
