### ISSUE TITLE
Cannot use locally modified files from environment

### ISSUE THREAD

**Issue by yash-s20** [espnet/espnet#2270]
Hi!
I was using a locally modified version of espnet, and now I've been trying to use espnet2. However, imports find espnet and espnet2 from site-packages rather that local paths. I was using yesno to setup and debug, and espnet2.asr.specaug cannot be imported (on Stage 9) because the specaug submodule is not available in the site-package espnet2.

Full log is here -

Even espnet(1) is using site-packages now, rendering my local changes useless. These seems to be a new addition where site-packages are used instead, so I'd like to know how to possibly disable them. Thanks for your patience :)

**Comment by kamo-naoyuki** [comment]
I'm not sure, but do you ask about general importing system of Python?

- pip install <package-name/directory-path> (or, python setup.py install)
    - package are copied to the site-packages directory by default.
- pip install -e <directory-path>
    - Install on editable mode. i.e. The packages are not copied and you can use as it is. 
- Set $PYTHONPATH: Directly overwrite the import path. 

 If you follows our installation flow, espnet should be installed on editable mode.
If you wrongly installed espnet with normal mode, then you can change it with ` pip install -e` again.

**Comment by yash-s20** [comment]
Did not know about the usage of -e. Must've tripped over it in my older settings, and missed it in a resintallation. Thanks!
