### ISSUE TITLE
Question. Chinese/Japanese ASR models

### ISSUE THREAD

**Issue by Kyubyong** [espnet/espnet#2271]
Hi, this is not an issue but a question, but do you have a recipe for Japanese/Chinese ASR? I found the common voice datasets for the languages, but I'm not sure if they fit the currently provided recipe.

And there's one more question if it's okay. Is the original script (mix of Kana and Kanji) better than Romaji when it comes to ASR in Japanese? (Or similarly: are Chinese characters better than pinyin as output in Chinese ASR?) I guess if we use Romaji or pinyin we can reduce the vocabulary size and get better performance at the cost of postprocessing of converting them into the original script. Any ideas will be appreciated.

**Comment by sw005320** [comment]
> Hi, this is not an issue but a question, but do you have a recipe for Japanese/Chinese ASR? I found the common voice datasets for the languages, but I'm not sure if they fit the currently provided recipe.

Yes, we have several Japanese/Chinese ASR, and actually their numbers are very good.
Please check https://github.com/espnet/espnet/blob/master/egs/README.md

> And there's one more question if it's okay. Is the original script (mix of Kana and Kanji) better than Romaji when it comes to ASR in Japanese? (Or similarly: are Chinese characters better than pinyin as output in Chinese ASR?) I guess if we use Romaji or pinyin we can reduce the vocabulary size and get better performance at the cost of postprocessing of converting them into the original script. Any ideas will be appreciated.

We did not have very precise comparisons, but in general, the original script is comparable or better. Also, if we use Romaji or pinyin, the output sequence becomes longer, which increases the computational cost more than the benefit of reducing the vocabulary size.
