### ISSUE TITLE
How can automatically continue to train rather than training from scrath? (load checkpoint) And "--resume" means to do warm start ?

### ISSUE THREAD

**Issue by Jxu-Thu** [espnet/espnet#2272]
Thanks for such a great code tools espnet!
Here I have a problem. I find that if my program failed, the codes will train from scratch rather than from last checkpoint I have trained. 

And I'm confused with '--resume' option. 'resume' means that you should do 'warm start' from the resumed checkpoint? 
I find the code 
`chainer.serializers.load_npz(args.resume, trainer)`
but I'm not familiar with the chainer tools.

**Comment by sw005320** [comment]
> And I'm confused with '--resume' option. 'resume' means that you should do 'warm start' from the resumed checkpoint?
> I find the code
> `chainer.serializers.load_npz(args.resume, trainer)`
> but I'm not familiar with the chainer tools.

Yes, you're right.
