### ISSUE TITLE
The jobname issue in egs2/ 's newly update. 

### ISSUE THREAD

**Issue by shincling** [espnet/espnet#2273]
Hi, @kamo-naoyuki , I'm working on Espnet2-Enh realted works now.
I saw the newly update of egs2/Template/*/asr.sh or tts.sh about the jobname.
https://github.com/espnet/espnet/blob/981f5d63f1c2b9f80a534787e0bf77f1f5c39658/egs2/TEMPLATE/asr1/asr.sh#L711

I just install the lastest version of espnet, when I run egs2/mini_an4/asr1/run.sh it in JHU 's environment.  The jobname issue happens. 
I feel the sed command above maybe not correct to extract the queue.pl. 
Please check it. 

> (base) shijing2014@login:/export/c09/shijing2014/espnet/egs2/mini_an4/asr1$ ./run.sh --ngpu 1 --stage 7
> 2020-08-05T14:06:09 (asr.sh:203:main) ./asr.sh --lang en --train_set train_nodev --valid_set train_dev --test_sets train_dev test test_seg --srctexts data/train_nodev/text --ngpu 1 --stage 7
> 2020-08-05T14:06:12 (asr.sh:673:main) Stage 7: LM Training: train_set=dump/raw/srctexts, dev_set=dump/raw/train_dev/text
> 2020-08-05T14:06:12 (asr.sh:710:main) LM training started... log: 'exp/lm_train_bpe/train.log'
> 2020-08-05 14:06:15,887 (launch:93) INFO: /export/c09/shijing2014/espnet/tools/venv/envs/con_shin_espnet/bin/python3 /export/c09/shijing2014/espnet/espnet2/bin/launch.py --cmd 'queue-freegpu.pl --mem 2G --gpu 1 --config conf/queue.conf --name lm_train_bpe' --log exp/lm_train_bpe/train.log --ngpu 1 --num_nodes 1 --init_file_prefix exp/asr_train_raw_bpe/.dist_init_ --multiprocessing_distributed true -- python3 -m espnet2.bin.lm_train --ngpu 1 --use_preprocessor true --bpemodel data/token_list/bpe_unigram30/bpe.model --token_type bpe --token_list data/token_list/bpe_unigram30/tokens.txt --non_linguistic_symbols none --cleaner none --g2p none --valid_data_path_and_name_and_type dump/raw/train_dev/text,text,text --valid_shape_file exp/lm_stats/valid/text_shape.bpe --fold_length 150 --resume true --output_dir exp/lm_train_bpe --train_data_path_and_name_and_type dump/raw/srctexts,text,text --train_shape_file exp/lm_stats/train/text_shape.bpe
> 2020-08-05 14:06:16,230 (launch:345) INFO: log file: exp/lm_train_bpe/train.log
> 2020-08-05T14:08:49 (asr.sh:746:main) Stage 8: Calc perplexity: dump/raw/train_dev/text
> 2020-08-05T14:08:49 (asr.sh:749:main) Perplexity calculation started... log: 'exp/lm_train_bpe/perplexity_test/lm_calc_perplexity.log'
> 2020-08-05T14:09:09 (asr.sh:759:main) PPL: dump/raw/train_dev/text: 26.447825684891445
> 2020-08-05T14:09:09 (asr.sh:771:main) Stage 9: ASR collect stats: train_set=dump/raw/train_nodev, valid_set=dump/raw/train_dev
> 2020-08-05T14:09:09 (asr.sh:817:main) ASR collect-stats started... log: 'exp/asr_stats_raw/logdir/stats.*.log'
> /export/c09/shijing2014/espnet/tools/venv/envs/con_shin_espnet/bin/python3 /export/c09/shijing2014/espnet/espnet2/bin/aggregate_stats_dirs.py --input_dir exp/asr_stats_raw/logdir/stats.1 --output_dir exp/asr_stats_raw
> 2020-08-05T14:09:41 (asr.sh:864:main) Stage 10: ASR Training: train_set=dump/raw/train_nodev, valid_set=dump/raw/train_dev
> 2020-08-05T14:09:41 (asr.sh:929:main) ASR training started... log: 'exp/asr_train_raw_bpe/train.log'
> 2020-08-05 14:09:42,550 (launch:93) INFO: /export/c09/shijing2014/espnet/tools/venv/envs/con_shin_espnet/bin/python3 /export/c09/shijing2014/espnet/espnet2/bin/launch.py --cmd 'queue-freegpu.pl --mem 2G --gpu 1 --config conf/queue.conf --name exp/asr_train_raw_bpe/train.log' --log exp/asr_train_raw_bpe/train.log --ngpu 1 --num_nodes 1 --init_file_prefix exp/asr_train_raw_bpe/.dist_init_ --multiprocessing_distributed true -- python3 -m espnet2.bin.asr_train --use_preprocessor true --bpemodel data/token_list/bpe_unigram30/bpe.model --token_type bpe --token_list data/token_list/bpe_unigram30/tokens.txt --non_linguistic_symbols none --cleaner none --g2p none --valid_data_path_and_name_and_type dump/raw/train_dev/wav.scp,speech,sound --valid_data_path_and_name_and_type dump/raw/train_dev/text,text,text --valid_shape_file exp/asr_stats_raw/valid/speech_shape --valid_shape_file exp/asr_stats_raw/valid/text_shape.bpe --resume true --fold_length 80000 --fold_length 150 --output_dir exp/asr_train_raw_bpe --frontend_conf fs=16k --normalize=global_mvn --normalize_conf stats_file=exp/asr_stats_raw/train/feats_stats.npz --train_data_path_and_name_and_type dump/raw/train_nodev/wav.scp,speech,sound --train_data_path_and_name_and_type dump/raw/train_nodev/text,text,text --train_shape_file exp/asr_stats_raw/train/speech_shape --train_shape_file exp/asr_stats_raw/train/text_shape.bpe
> 2020-08-05 14:09:42,620 (launch:345) INFO: log file: exp/asr_train_raw_bpe/train.log
> queue.pl: Error submitting jobs to queue (return status was 512)
> queue log file is exp/asr_train_raw_bpe/q/train.log, command was qsub -v PATH -cwd -S /bin/bash -j y -l arch=*64* -o exp/asr_train_raw_bpe/q/train.log -l gpu=1 -q g.q -l mem_free=2G,ram_free=2G -N exp/asr_train_raw_bpe/train.log   /export/c09/shijing2014/espnet/egs2/mini_an4/asr1/exp/asr_train_raw_bpe/q/train.sh >>exp/asr_train_raw_bpe/q/train.log 2>&1
> Output of qsub was: qsub: argument to -N option must not contain /

**Comment by kamo-naoyuki** [comment]
My modification is correct, but you are using queue-freegpu.pl. I forgot the command.

**Comment by shincling** [comment]
> My modification is correct, but you are using queue-freegpu.pl. I forgot the command.

Thanks~
