### ISSUE TITLE
Bug Report: Automatically Exit when running path.sh

### ISSUE THREAD

**Issue by YangHan-Morningstar** [espnet/espnet#2278]
Hey, guys, when I use the command that "cd egs/ljspeech/tts1 && . ./path.sh", I automatically exit my Server and the message is "The standard file /home/yanghan/TTS/TTS_Self/espnet/egs/ljspeech/tts1/../../../tools/kaldi/tools/config/common_path.sh is not present -> Exit!", could you help me solve this? Looking forward to it~Thanks!

**Comment by kamo-naoyuki** [comment]
Did you install kaldi?
You don't have .../tools/kaldi/tools/config/common_path.sh as it said, so you need to put kaldi there.

**Comment by YangHan-Morningstar** [comment]
Ohh, sorry, it's my fault
