### ISSUE TITLE
recognize_beam gpu running need 10 second per audio

### ISSUE THREAD

**Issue by luweishuang** [espnet/espnet#228]
I run decoder module in gpu version with model.to_gpu() and rnnlm.to_gpu(). I found it need 10 second per audio and cpu version only need 4 second in a same audio.  With deeper analyse, I found in gpu version recognize_beam function need almost 9 second, espeacially ctc_prefix_score() and "hyps_best_kept = sorted(hyps_best_kept, key=lambda x: x['score'], reverse=True)[:beam]".  Is there some advice to speed up   recognize_beam() or some alternativly methods to achieve the same target

**Comment by sw005320** [comment]
Actually recognize_beam did not consider the speed so much, but recently @mn5k is working on it (basically we're making a batch for all hypothesis, and also care about GPU processing). So, it will be faster and also consider GPU processing. Please wait for a while.

**Comment by luweishuang** [comment]
I use a process pool to accelerate cpu calucate and just find it cost much more time,need 60 second per audio, here is some of my code.
         hyps_best_kept = []
            with concurrent.futures.ProcessPoolExecutor(max_workers=8) as executor:
                print("len(hyps) = %d " % len(hyps))
                futures = [executor.submit(recognize_beam_hyp_out, i, item, self.embed, self.att, self.lstm0, self.dlayers, self.output, self.eos, h, c_list, z_list, rnnlm, lpz, recog_args, ctc_beam, beam, ctc_weight) for item in hyps]
                for future in concurrent.futures.as_completed(futures):
                    startTime = datetime.datetime.now()
                    hyps_best_kept += future.result()
                    usedTimeMs = (datetime.datetime.now() - startTime).total_seconds() * 1000
                    # print("future usetime = %.0f ms" % usedTimeMs)
            hyps_best_kept = sorted(hyps_best_kept, key=lambda x: x['score'], reverse=True)[:beam]
