### ISSUE TITLE
error in training stage "Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

### ISSUE THREAD

**Issue by marynader6** [espnet/espnet#2282]
Hello guys!
we are running the recipe of ljspeech of version 0.8.0 but on our data set, we are using google colaboratory. At the stage of training we are getting this error "Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!". Any help ? 
log file is attached.
[train.log](https://github.com/espnet/espnet/files/5044468/train.log)

Thanks in advance

**Comment by HelloMaster1954** [comment]
Hi.
It may be some tensor is on the CPU and some on the GPU. 
I guess you can fix this bug with `tensor = tensor.to(device=torch.device("cuda:0"))`

**Comment by kamo-naoyuki** [comment]
@kan-bayashi This error occurs if pytorch=1.6.

**Comment by kan-bayashi** [comment]
Sorry, I misss this issue.
I will check it.

**Comment by kan-bayashi** [comment]
Fixed in #2317

**Comment by chaitrasj** [comment]
What is the solution for this probelm @kamo-naoyuki ? 
I am trying to train my model, the code is working totally fine on my server machine which has Pytorch 1.4.0 installed. But when I am trying to run it on Google colab which has latest Pytorch 1.6, it gives me this error in the very first tensor allocation.
In my code all objects are getting allocated in cuda, i don't understand why in Colab it is allocating any object on cpu and giving this error.

Thank you in advance.

**Comment by SiyuanHuang95** [comment]
> What is the solution for this probelm @kamo-naoyuki ?
> I am trying to train my model, the code is working totally fine on my server machine which has Pytorch 1.4.0 installed. But when I am trying to run it on Google colab which has latest Pytorch 1.6, it gives me this error in the very first tensor allocation.
> In my code all objects are getting allocated in cuda, i don't understand why in Colab it is allocating any object on cpu and giving this error.
> I checked #2317 but I do not see what changes I need to do from my end.
> 
> Thank you in advance.

Hi, have you found any solution w.r.t this issue, I am also struggling with this problem where I also installed the Pytorch 1.6

**Comment by kan-bayashi** [comment]
In my understanding, this issue is already solved in master.

**Comment by SiyuanHuang95** [comment]
> In my understanding, this issue is already solved in master.

Hi, sorry for troubling you, but I am not using your repo currently but still met the same problem when I am trying to train a network myself. I am here to seek the potential and general solution for that error.
