### ISSUE TITLE
Add teacher forcing option for transformers

### ISSUE THREAD

**Issue by qmeeus** [espnet/espnet#2286]
Hi,

I realised that it was not possible at the moment to use the decoder's prediction as input for the decoder's next step (the option is available for LSTMs with sampling-probability argument though). May I suggest to add this in the next release?

**Comment by sw005320** [comment]
Thanks.
Yes, we actually have the same request from the others, and we'll think about it.
@ShigekiKarita, I remember the discussion about this possibility. Could you remind me why we did not implement it? I just want to know If there are some technical difficulties.

**Comment by qmeeus** [comment]
I am happy to help if necessary

**Comment by sw005320** [comment]
@qmeeus, that is great if you contribute it!
As I said, there are certain amounts of the request about it, and it could have a great benefit for the community.
We'll do our best to help your contribution.
