### ISSUE TITLE
A question about how to train fastspeech model

### ISSUE THREAD

**Issue by HeYingnan** [espnet/espnet#2288]
hi, I want to use egs/ljspeech/tts1/conf/tuning/train_fastspeech.v2.yaml with its teacher model egs/ljspeech/tts1/conf/tuning/train_pytorch_transformer.v1.yaml,but i don't know
trans_type="char" or "phn"???
and i want to know in this conf egs/ljspeech/tts1/conf/tuning/train_fastspeech.v3.yaml,
why transfer-encoder-from-teacher: False???
thank you!

**Comment by HeYingnan** [comment]
teacher-model: exp/train_no_dev_pytorch_train_transformer.v1/results/model.last1.avg.best
               # you can download pretrained teacher model from google drive
               # https://drive.google.com/open?id=1arZAxZOLep-1W5ByQMD1lCX2tEASnw7p

in this url, i can't download the teacher model...

**Comment by kan-bayashi** [comment]
> egs/ljspeech/tts1/conf/tuning/train_pytorch_transformer.v1.yaml,but i don't know
trans_type="char" or "phn"???

It depends on you. You can try both cases.
You can find the results of various combination:
https://github.com/espnet/espnet/blob/master/egs/ljspeech/tts1/RESULTS.md

>  transfer-encoder-from-teacher: False???

This is because encoder structure is different from the teacher model.

> in this url, i can't download the teacher model...

Sorry, please find the pretrained model from here:
https://drive.google.com/drive/folders/1J1YCqm-B4Il6xjdXvLgSfhHJgZDyXKPq?usp=sharing

**Comment by HeYingnan** [comment]
> > egs/ljspeech/tts1/conf/tuning/train_pytorch_transformer.v1.yaml,but i don't know
> > trans_type="char" or "phn"???
> 
> It depends on you. You can try both cases.
> You can find the results of various combination:
> https://github.com/espnet/espnet/blob/master/egs/ljspeech/tts1/RESULTS.md
> 
> > transfer-encoder-from-teacher: False???
> 
> This is because encoder structure is different from the teacher model.
> 
> > in this url, i can't download the teacher model...
> 
> Sorry, please find the pretrained model from here:
> https://drive.google.com/drive/folders/1J1YCqm-B4Il6xjdXvLgSfhHJgZDyXKPq?usp=sharing

In fact, I don’t know how to set “train_config” and "teacher_model_path",i don't know which fastspeech model match which teacher model, can you give me a example?  I just started learning TTS. thank you very much.
# config files
train_config=conf/tuning/train_fastspeech.v2.yaml # you can select from conf or conf/tuning.
                                               # now we support tacotron2, transformer, and fastspeech
                                               # see more info in the header of each config.
decode_config=conf/decode.yaml

# knowledge distillation related
teacher_model_path="exp/phn_train_no_dev_pytorch_train_pytorch_tacotron2.v2/results/model.last1.avg.best"
teacher_decode_config=conf/decode_for_knowledge_dist.yaml

**Comment by kan-bayashi** [comment]
Sorry for the late reply.
The procedure of the training of FastSpeech in ESPnet1 is a bit complicated.
So I recommend trying ESPnet2 TTS.
I created documents about the ESPnet2 TTS training in #2312.
This will help you.

**Comment by HeYingnan** [comment]
thank you!
