### ISSUE TITLE
Training Self Encoder

### ISSUE THREAD

**Issue by YangHan-Morningstar** [espnet/espnet#2291]
Hi guys, recently I have trained self vocoder following you amazing project and it's really useful, but now I want to train my own encoder, such as transformer or fastspeech model, and my dataset is about Mandarin. Could you tell me how to do it? I'm looking forward to this. Thank you!

**Comment by kan-bayashi** [comment]
First, I recommend trying ESPnet2 CSMSC resiep (`egs2/csmsc/tts1`).
This is the recipe to train the Mandarin single speaker model.
Maybe you can understand the recipe flow and then try to build your own recipe (See https://github.com/espnet/espnet/tree/master/egs2/TEMPLATE).

**Comment by YangHan-Morningstar** [comment]
I’ll try it. Thanks a lot!

Tomoki Hayashi <notifications@github.com>于2020年8月15日 周六11:09写道：
