### ISSUE TITLE
Vertical attention during training

### ISSUE THREAD

**Issue by gafsd** [espnet/espnet#2295]
I am using ESPNet 1 ljspeech-like dataset for pretrained weights and am getting some attention graphs like this in training which I haven't seen before:
![individualImage](https://user-images.githubusercontent.com/62999745/89983349-f8349200-dca9-11ea-8f46-2ae8b7300890.png)

I recently updated to latest commit and I know there are lots of ESPNet2 changes so could this be version related?
I init from pretrained tacotron v4 with BCE-pos-weight 2.0

**Comment by sw005320** [comment]
Basically such changes would not cause this change, but it might be.
It would be great if you try it with several different versions (e.g., v08, v07), and identify the issue due to the version or your ljspeech-like dataset.

**Comment by gafsd** [comment]
@sw005320 I just try on v0.8.0 and the attention graphs look normal.

**Comment by sw005320** [comment]
Thanks. Then, it would be a bug. @kan-bayashi, could you check this issue?

**Comment by kan-bayashi** [comment]
How did you get this attention plot?
Is this a plot during training?

**Comment by gafsd** [comment]
Yes, from images tab in tensorboard, even after 11k steps.

**Comment by gafsd** [comment]
Sorry I did not save exact same data but here is a 0.8.0 graph after some small steps. I find these graphs helpful to track down utts with bad attention (there is sadly a limit to num-save-attention I think but I have set to 32 here).
![individualImage](https://user-images.githubusercontent.com/62999745/90045556-c9e2a100-dd01-11ea-800d-04da2ff2d1aa.png)

**Comment by kan-bayashi** [comment]
Thanks.
Could you try to remove `[::-1]` here?
https://github.com/espnet/espnet/blob/5410797ebc8c4db040a3c0e23eb47051ababe684/espnet/asr/asr_utils.py#L115

**Comment by gafsd** [comment]
Yes that seems to have fixed it.
![pre](https://user-images.githubusercontent.com/62999745/90048820-96564580-dd06-11ea-9b24-c84d3230001a.png)
![post](https://user-images.githubusercontent.com/62999745/90048827-98200900-dd06-11ea-9273-30f4fcd27dd6.png)

**Comment by kan-bayashi** [comment]
Thank you for your checking.
It really helps us!

@hirofumi0810 Is this change for ASR or ST?

**Comment by gafsd** [comment]
Thanks. If I could suggest it would be helpful to be able to see all attention plots in tensorboard if I set num-save-attention high. It is nice to check problematic input files.

**Comment by kan-bayashi** [comment]
Thank you for your suggestions.
In decoding, we support the attention plot of all of the data.
It might help you.
