### ISSUE TITLE
LibriTTS XVector Extraction with new speaker

### ISSUE THREAD

**Issue by seanle24245** [espnet/espnet#2297]
I've been able to use the extracted speaker embeddings during stage 3 of run.sh to produce specific voices from the libritts set.  If I have some new audio from someone I want to produce, what would be the easiest way to extract x-vectors from it?  I'm a little confused on what stages can run independently.  The only route I know would be to add new file to the whole training set and run run.sh, but I'm trying to find a way to just execute the process on the single new audio i have.

Also, what are the .ark files in xvector_nnet_1a?

**Comment by kan-bayashi** [comment]
You can refer this part to extract the x-vector.
https://github.com/espnet/espnet/blob/b4413f6259c49d2543db1e10417c08118a09d990/utils/synth_wav.sh#L237-L285

> what are the .ark files in xvector_nnet_1a?

That is an extracted x-vector files.

**Comment by b-flo** [comment]
> > what are the .ark files in xvector_nnet_1a?

> That is an extracted x-vector file.
> There are utterance-wise x-vector and speaker-averaged x-vector.

Small precision: `.ark` is a archive format of Kaldi containing a specific Kaldi object (generally a `KaldiMatrix`). It's used by the I/O utility.
