### ISSUE TITLE
About the meaning of forced alignment

### ISSUE THREAD

**Issue by sunnnnnnnny** [espnet/espnet#2300]
After I read the examples and codes about forced alignment, I think this is different from the perceived forced alignment. The result of forced alignment here is only the result of not deleted duplication and deleted blank after CTC decode?

**Comment by AdolfVonKleist** [comment]
If you are looking for something that provides timestamps at the word-level, maybe it is worth checking out :
 * https://github.com/cornerfarmer/ctc_segmentation

this knits everything together and is perhaps more similar in spirit to your perceived idea of forced-alignment (e.g., something like https://github.com/lowerquality/gentle )

**Comment by sunnnnnnnny** [comment]
@AdolfVonKleist  Thank you for your suggestion, I will try it now.

**Comment by sunnnnnnnny** [comment]
@AdolfVonKleist Initially, it turns out that neither of the two you said supports Chinese

**Comment by b-flo** [comment]
I'm not familiar with gentle but there is no language dependencies in CTC segmentation, it can be used for any language.

**Comment by AdolfVonKleist** [comment]
Just to be clear, I did not have anything to do with developing that module.  It is a subject for integration discussed here:

* https://github.com/espnet/espnet/issues/2192

as @b-flo mentions, it should work fine with any language for which you have compatible espnet model.  I can confirm it works very well for all the languages I have tried including English, French, Italian and German.

**Comment by lumaku** [comment]
@sunnnnnnnny You could train a Chinese model from the recipe `egs/aidatatang_200zh/asr1/` and use this to apply CTC segmentation. You don't need language model or attention-mechanism to generate alignments, only the CTC part. See pull request #2301 for the recipe.

**Comment by sunnnnnnnny** [comment]
Of course I also think that CTC-segment can be used in any language, but when I understand the char_list of TEDLIUM_release1.tar.gz pre-trained model, I think it is still very different from Chinese. Espnet Chinese speech recognition model modeling seems to be all In words

**Comment by sunnnnnnnny** [comment]
Of course I also think that CTC-segment can be used in any language, but when I understand the char_list of `TEDLIUM_release1.tar.gz `pre-trained model, I think it is still very different from Chinese. Espnet Chinese speech recognition model modeling seems to be all In words

**Comment by lumaku** [comment]
I would solve this by transcribing Hanzi to Pinyin with tone marks (我 --> wo3), and then either directly make a Pinyin dictionary or apply SentencePiece. There are NLP tools to convert Hanzi to Pinyin. It's not necessary for CTC segmentation, but a language model to convert Pinyin to Hanzi can be found in kaldi.

**Comment by sunnnnnnnny** [comment]
I  also do that as @lumaku said.
