### ISSUE TITLE
[Bug] Install error with src/binding.cpp:8:14: fatal error: THC.h: No such file or directory  #include "THC.h"

### ISSUE THREAD

**Issue by jamfly** [espnet/espnet#2302]
## Summary
Hi there, I follow the doc step by step
while I executing step 5. on Installation Espnet 

## How to reproduce
```
cd <espnet-root>/tools
make
```

I got 

```
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
src/binding.cpp:8:14: fatal error: THC.h: No such file or directory
 #include "THC.h"

compilation terminated
error: command 'gcc' failed with exit status 11
Makefile:146: recipe for target 'warp-transducer.done' failed
make: *** [warp-transducer.done] Error 1
```

after some googling, It seems to be cuda path issue, however, I can ensure `CUDA_HOME` is correct. It echo the right one

I attach my log in here 
[log.log](https://github.com/espnet/espnet/files/5070282/log.log)

## Env
python: python3.6 on conda
pytorch: 1.4.0
espnet: newest master. commit hash is `0658f88dd255fea6e76dd725f6d56f51014c803e`

Thank you.

**Comment by kamo-naoyuki** [comment]
I can't reproduce. pytorch1.4+cuda10.2 is the reason? Please test pytorch1.6.

**Comment by kamo-naoyuki** [comment]
pytorch1.4 doesn't support cuda10.2?
https://pytorch.org/get-started/previous-versions/
So, you need to use pytorch>=1.5 or cuda<=10.1

**Comment by jamfly** [comment]
Hi @kamo-naoyuki:
it solves my problem, thank you for your help

**Comment by kamo-naoyuki** [comment]
Okay, thanks. I'll fix Makefile to avoid this problem.
