### ISSUE TITLE
How to set warmup-steps

### ISSUE THREAD

**Issue by abnernn** [espnet/espnet#2313]
1.If i increase batch_ bins, how to set warmup-steps,What is the relationship to Nbatch or others.
2.If  ngpu and batch_ bins increased by 4 times(gpu:2->8,bins:15000000->70000000)，how to set accum_grad  and lr in espnet2

**Comment by kamo-naoyuki** [comment]
See:  https://espnet.github.io/espnet/espnet2_tutorial.html 

If batch_type=numel, increasing batch_bins indicates larger batch_size. We can't know the actual batch_size of each mini-batch and the number of batches before executing. `warmup_steps` is nothing related to batch type, but relatively the number of iterations decreases, so it's better to decrease `warmup_steps` also.

You can know typical options from some configuration files: e.g. https://github.com/espnet/espnet/blob/master/egs2/librispeech/asr1/conf/tuning/train_asr_transformer3.yaml

You can also change them by command line arguments: e.g.

```sh
python -m espnet2.bin.asr_train ... --config conf/tuning/train_asr_transformer3.yaml --ngpu 8 --batch_bins 70000000 --scheduler_conf warmup_steps=10000 --accum_grad 1 --optimizer_conf lr=0.005
```
