### ISSUE TITLE
How to fine tune espnet2 model?

### ISSUE THREAD

**Issue by khursani8** [espnet/espnet#2319]
I tried to fine tune espnet2 model using enc-init and dec-init and got
```
./asr.sh: invalid option --enc-init
```

I think because that is only for espnet v1
How to do it for espnet2?

Thanks

**Comment by kan-bayashi** [comment]
You can use `--pretrain_path` and `--pretrain_key` option.
https://github.com/espnet/espnet/blob/3cc59a16c3655f3b39dc2ae19ffafa7bfac879bf/espnet2/tasks/abs_task.py#L1040-L1054
You can add them in training config (*.yaml).

**Comment by khursani8** [comment]
Wow, thanks
