### ISSUE TITLE
[Dependency] mmseg on egs/hkust/asr1

### ISSUE THREAD

**Issue by jamfly** [espnet/espnet#2321]
## Summary

In run.sh stage 0: Data preparation

script requires mmseg on [hkust_segment.py](https://github.com/42qu/mmseg)
however, mmseg using pyhon 2.7
and in [hkust_data_prep.sh](https://github.com/espnet/espnet/blob/master/egs/hkust/asr1/local/hkust_data_prep.sh)
```
#transcripts normalization and segmentation
#(this needs external tools),
python3 -c "import mmseg" 2>/dev/null || \
  (echo "mmseg is not found. Checkout tools/extra/install_mmseg.sh" && exit 1;)

cat $train_dir/transcripts.txt |\
  sed -e 's/<foreign language=\"[a-zA-Z]\+\">/ /g' |\
  sed -e 's/<\/foreign>/ /g' |\
  sed -e 's/<noise>\(.\+\)<\/noise>/\1/g' |\
  sed -e 's/((\([^)]\{0,\}\)))/\1/g' |\
  local/hkust_normalize.pl |\
  python3 local/hkust_segment.py |\
  awk '{if (NF > 1) print $0;}' > $train_dir/text || exit 1;

cat $dev_dir/transcripts.txt |\
  sed -e 's/<foreign language=\"[a-zA-Z]\+\">/ /g' |\
  sed -e 's/<\/foreign>/ /g' |\
  sed -e 's/<noise>\(.\+\)<\/noise>/\1/g' |\
  sed -e 's/((\([^)]\{0,\}\)))/\1/g' |\
  local/hkust_normalize.pl |\
  python3 local/hkust_segment.py |\
  awk '{if (NF > 1) print $0;}' > $dev_dir/text || exit 1;
```
seems use python3 to execute python2 script

I also tried [py3mmseg](https://github.com/bxshi/py3mmseg)
unfortunately, it didn't work.

**Comment by D-Keqi** [comment]
I come into the same problem with you, and I used py3mmseg to solve it temporarily, but I found that the text I processed cannot contain useful text. 
details as follows：
20040527_210939_A901153_B901154-A-024861-025638 [VOCALIZED-NOISE]
20040527_210939_A901153_B901154-A-051456-051795 [VOCALIZED-NOISE]
20040527_210939_A901153_B901154-B-002285-002604 [VOCALIZED-NOISE]
20040527_210939_A901153_B901154-B-007090-007515 [VOCALIZED-NOISE]
20040527_210939_A901153_B901154-B-007927-008421 [VOCALIZED-NOISE]
20040527_210939_A901153_B901154-B-009462-009918 [VOCALIZED-NOISE]
20040527_210939_A901153_B901154-B-010283-010970 [VOCALIZED-NOISE]
20040527_210939_A901153_B901154-B-012097-012903 [VOCALIZED-NOISE]
20040527_210939_A901153_B901154-B-022339-022947 [VOCALIZED-NOISE]
20040527_210939_A901153_B901154-B-029227-029526 [VOCALIZED-NOISE]
20040527_210939_A901153_B901154-B-029526-030263 [VOCALIZED-NOISE]
20040527_210939_A901153_B901154-B-032428-032774 [VOCALIZED-NOISE]
20040527_210939_A901153_B901154-B-034483-034938 [VOCALIZED-NOISE]
20040527_210939_A901153_B901154-B-041601-042188 [VOCALIZED-NOISE]
20040527_210939_A901153_B901154-B-048354-049024 [VOCALIZED-NOISE]
20040527_210939_A901153_B901154-B-050204-050790 [VOCALIZED-NOISE]
20040527_210939_A901153_B901154-B-051212-051970 [NOISE]
20040527_210939_A901153_B901154-B-052214-052725 [NOISE]

**Comment by D-Keqi** [comment]
I also tried to set up a python2 environment, but I still encounter this kind of problem

**Comment by jamfly** [comment]
I downgrade to python2.7 and change those python3 command to python, i.e., `python local/hkust_segment.py `
only execute stage 0 and stop at 0
then switch to python 3.6 to execute following stage

**Comment by D-Keqi** [comment]
please check the file /espnet/egs/hkust/asr1/data/local/dev/text, in my condition, this file is wrong， it does not contain the correct text. Have you encountered a similar situation?

**Comment by jamfly** [comment]
mine seems work fine
```
20040503_222707_A000687_B000688-A-000000-000477 喂 喂 你叫 什么 名
20040503_222707_A000687_B000688-A-000656-001110 [LAUGHTER] 王 保 文 啊 你 是 我姓 曾
20040503_222707_A000687_B000688-A-001110-001533 我姓 曾 嗯 是啊
20040503_222707_A000687_B000688-A-001533-001915 啊 住在 哪里 呀
20040503_222707_A000687_B000688-A-001915-002472 学校 呀 在 什么 学校
20040503_222707_A000687_B000688-A-002472-003202 深圳 大学 呀 那 环境 一定 很好 了 不错 啊 [LAUGHTER]
20040503_222707_A000687_B000688-A-003202-003670 少 一点 女生 你 读 的 是 什么 学院 啊
20040503_222707_A000687_B000688-A-003670-004193 工程 啊 挺 好呀 [NOISE] [LAUGHTER]
20040503_222707_A000687_B000688-A-004502-005015 [LAUGHTER] 先 聊 下 手机 吧
20040503_222707_A000687_B000688-A-005015-005503 好
20040503_222707_A000687_B000688-A-006890-007326 是啊 现在 好啊 [LAUGHTER] 你用 的 是 什么 手机 呀
20040503_222707_A000687_B000688-A-007326-007739 是啊
20040503_222707_A000687_B000688-A-007739-008038 就 是嘛 没 手机 怎么 泡妞
20040503_222707_A000687_B000688-A-008797-009278 是啊 [LAUGHTER] 你用 的 是 什么 手机 呀
20040503_222707_A000687_B000688-A-009278-009845 便宜 你 觉得 哪 部 手机 比较 好用 啊
20040503_222707_A000687_B000688-A-010120-010585 不会 吧 我 觉得 诺基 亚 比 较好 噢
20040503_222707_A000687_B000688-A-010956-011465 不会 吧 [LAUGHTER] 三星 怎么 好啊
...
```

**Comment by D-Keqi** [comment]
What other changes have you made to this text hkust_data_prep.sh? The only thing I have changed is line 38: from iconv -f GBK -t utf-8-| perl -e 'to: iconv -f GBK -t utf -8 | perl -e'. This is because an error was reported at the time, and then modified according to other issues.
I really don't know what went wrong

**Comment by jamfly** [comment]
no, I did what I mentioned above, I use python 2.7 to prepare data, and execute following script by python 3.6
I did try py3mmseg, it produced unusable files. so, I guess, we need to use different versions base on dependency

**Comment by kamo-naoyuki** [comment]
We can't allow to use python2 at all places any more, so we must move it to python3.

> Due to unknown problem(probably the encoding problem), you need to pass bytes instead of str object to mmseg.
(From https://github.com/bxshi/py3mmseg)

Probably, the problem is here.
Could you insert encode and decode here with py3mmseg and tell me the result?
https://github.com/espnet/espnet/blob/a15fd3b33492e67d06e39de5c05f4a126af75518/egs/hkust/asr1/local/hkust_segment.py#L19-L20

```python
        for j in seg_txt(blks[i]).encode():
            out_line += " " + j.decode()
```

**Comment by D-Keqi** [comment]
> We can't allow to use python2 at all places any more, so we must move it to python3.
> 
> > Due to unknown problem(probably the encoding problem), you need to pass bytes instead of str object to mmseg.
> > (From https://github.com/bxshi/py3mmseg)
> 
> Probably, the problem is here.
> Could you insert encode and decode here with py3mmseg and tell me the result?
> https://github.com/espnet/espnet/blob/a15fd3b33492e67d06e39de5c05f4a126af75518/egs/hkust/asr1/local/hkust_segment.py#L19-L20
> 
> ```python
>         for j in seg_txt(blks[i].encode()):
>             out_line += " " + j.decode()
> ```

sorry, i does not work, and error message is as follows:

Traceback (most recent call last):
  File "/storage3/dengkeqi/tools/espnet/tools/venv/envs/esp/lib/python3.7/site-packages/mmseg-1.3.0-py3.7-linux-x86_64.egg/mmseg/_mmseg.py", line 131, in __iter__
    raise StopIteration
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "local/hkust_segment.py", line 19, in <module>
    for j in seg_txt(blks[i].encode()):
  File "/storage3/dengkeqi/tools/espnet/tools/venv/envs/esp/lib/python3.7/site-packages/mmseg-1.3.0-py3.7-linux-x86_64.egg/mmseg/__init__.py", line 11, in seg_txt
    for tok in algor:
RuntimeError: generator raised StopIteration
Traceback (most recent call last):
  File "/storage3/dengkeqi/tools/espnet/tools/venv/envs/esp/lib/python3.7/site-packages/mmseg-1.3.0-py3.7-linux-x86_64.egg/mmseg/_mmseg.py", line 131, in __iter__
    raise StopIteration
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "local/hkust_segment.py", line 19, in <module>
    for j in seg_txt(blks[i].encode()):
  File "/storage3/dengkeqi/tools/espnet/tools/venv/envs/esp/lib/python3.7/site-packages/mmseg-1.3.0-py3.7-linux-x86_64.egg/mmseg/__init__.py", line 11, in seg_txt
    for tok in algor:
RuntimeError: generator raised StopIteration

**Comment by D-Keqi** [comment]
> We can't allow to use python2 at all places any more, so we must move it to python3.
> 
> > Due to unknown problem(probably the encoding problem), you need to pass bytes instead of str object to mmseg.
> > (From https://github.com/bxshi/py3mmseg)
> 
> Probably, the problem is here.
> Could you insert encode and decode here with py3mmseg and tell me the result?
> https://github.com/espnet/espnet/blob/a15fd3b33492e67d06e39de5c05f4a126af75518/egs/hkust/asr1/local/hkust_segment.py#L19-L20
> 
> ```python
>         for j in seg_txt(blks[i].encode()):
>             out_line += " " + j.decode()
> ```

Sorry, it does not work, the error is as follows:
Traceback (most recent call last):
  File "/storage3/dengkeqi/tools/espnet/tools/venv/envs/esp/lib/python3.7/site-packages/mmseg-1.3.0-py3.7-linux-x86_64.egg/mmseg/_mmseg.py", line 131, in __iter__
    raise StopIteration
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "local/hkust_segment.py", line 19, in <module>
    for j in seg_txt(blks[i].encode()):
  File "/storage3/dengkeqi/tools/espnet/tools/venv/envs/esp/lib/python3.7/site-packages/mmseg-1.3.0-py3.7-linux-x86_64.egg/mmseg/__init__.py", line 11, in seg_txt
    for tok in algor:
RuntimeError: generator raised StopIteration
Traceback (most recent call last):
  File "/storage3/dengkeqi/tools/espnet/tools/venv/envs/esp/lib/python3.7/site-packages/mmseg-1.3.0-py3.7-linux-x86_64.egg/mmseg/_mmseg.py", line 131, in __iter__
    raise StopIteration
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "local/hkust_segment.py", line 19, in <module>
    for j in seg_txt(blks[i].encode()):
  File "/storage3/dengkeqi/tools/espnet/tools/venv/envs/esp/lib/python3.7/site-packages/mmseg-1.3.0-py3.7-linux-x86_64.egg/mmseg/__init__.py", line 11, in seg_txt
    for tok in algor:
RuntimeError: generator raised StopIteration

**Comment by kamo-naoyuki** [comment]
Okay, It's a simple bug. Could you use python3.6 for workaround? if you have time. (I will also)

**Comment by D-Keqi** [comment]
> Okay, It's a simple bug. Could you use python3.6 for workaround? if you have time. (I will also)

It works! Thank you very much！

**Comment by D-Keqi** [comment]
I used python 3,7 before, and then used py3mmseg, but I could not prepare the data correctly. Then I used Anaconda3 to create a new python2.7 environment, and then installed mmseg. It still failed, and later I found out that this new environment is still calling py3mmseg installed in the python3.7 environment. So I uninstalled py3mmseg under python3.7 environment, and the result suggested: no module: mmseg. After that, I followed the official installation steps of espnet and established a python2.7 environment. After installing mmseg, it succeeded. Finally, I followed the installation steps of espnet again, installed a python3.6 environment, and installed py3mmseg, which was also successful! @kamo-naoyuki Thank you agian!

**Comment by D-Keqi** [comment]
> I used python 3,7 before, and then used py3mmseg, but I could not prepare the data correctly. Then I used Anaconda3 to create a new python2.7 environment, and then installed mmseg. It still failed, and later I found out that this new environment is still calling py3mmseg installed in the python3.7 environment. So I uninstalled py3mmseg under python3.7 environment, and the result suggested: no module: mmseg. After that, I followed the official installation steps of espnet and established a python2.7 environment. After installing mmseg, it succeeded. Finally, I followed the installation steps of espnet again, installed a python3.6 environment, and installed py3mmseg, which was also successful! @kamo-naoyuki Thank you agian!

If you use py3mmseg, you need to modify the hkust_segment.py file according to @kamo-naoyuki 's suggestions

**Comment by kamo-naoyuki** [comment]
Okay, thank you for confirming. I'll fix later this.
