### ISSUE TITLE
error when training fastspeech2

### ISSUE THREAD

**Issue by marzieh-razavi** [espnet/espnet#2323]
Hello, Thanks for providing the fastspeech2 implementation in espnet2. I am getting the following error when trying to run fastspeech2. I am actually not sure how the phoneme durations are provided in the fastspeech2 implementation, should I provide it from the MFA or this step is done in your implementation itself while preparing the data?
Here is the error that I am currently getting: 
File "espnet2/tts/feats_extract/dio.py", line 113, in forward
    for p, d in zip(pitch, durations)
TypeError: zip argument #2 must support iteration

Thank you very much for your help.

**Comment by kan-bayashi** [comment]
Please follow this instruction.
https://github.com/espnet/espnet/tree/master/egs2/TEMPLATE/tts1#how-to-run
