### ISSUE TITLE
TTS: Some observations of active testing hoping to fix disovered issues

### ISSUE THREAD

**Issue by ican24** [espnet/espnet#2327]
Dear @kan-bayashi,

A long time I am testing ESPnet TTS+ParallelWaveGAN solution with the custom (Armenian) databases.
I would like to share with my observations hoping to fix disovered issues.
1. Some punctuation symbols like Comma, Colon ("." instead of ":") and another explanation mark ("`") are interpreted as pause or stop, while the Question ("՞") and Emphasis ("'") marks, which are directly used in the words, are working perfectly. Is there any way to avoid pause?
2. I meet 1-2% cases of noise without voice in the middle or end of sentences/phrases. Usually the repeating synthesis fix the issue. Do I need to tune the settings of ESPnet TTS or ParallelWaveGAN to avoid such behavior? Actually I can use output checking tools to pass wrong attempts and repeat it again, but I am not sure in it.    
3. In the vary rare cases the the solution may add a piece of random voices in the end of wave file.(not critical)
4. Is it possible to trim end of wav file? It could be very useful to avoid long pauses after phrase (less 1% of cases). I can do myself with the help of ffmpeg or sox. Just I need to know lower (voice) signal level. (not critical)

Thank you in advance!
You are really doing great job.

**Comment by ican24** [comment]
I hope you did not foget my request.
Additional observation:
The punctuation symbols are really trouble for ESPnet TTS. I did another machine learning with completely tested dataset and discovered that the run.sh at stage 5: Synthesis failed to decode, when it met punctuation symbols.
I am attaching generated png and wav files for same sample:
1. decoded png: exp/phn_train_no_dev_pytorch_train_pytorch_tacotron2/outputs_model.last1.avg.best_decode/phn_dev/att_ws/duma3hr_21813_att_ws.png  
2. decoded wav: exp/phn_train_no_dev_pytorch_train_pytorch_tacotron2/outputs_model.last1.avg.best_decode_denorm/phn_dev/wav/duma3hr_21813.wav
The original text is "**Բոլորի հայացքն ուղղվեց այդ մարդու վրա,** ոչ ոք, բացի Աթոսից, չգիտեր, թե ով է նա։"
I may suppose that you may see that the script failed to decode after the first comma (',').
[21813.zip](https://github.com/espnet/espnet/files/5128916/21813.zip)
I never touch basic/default configuration.

I look forward to your comments and adviсes.  

Thank you in advance

**Comment by kan-bayashi** [comment]
Sorry for the late reply.

> Some punctuation symbols like Comma, Colon ("." instead of ":") and another explanation mark ("`") are interpreted as pause or stop, while the Question ("՞") and Emphasis ("'") marks, which are directly used in the words, are working perfectly. Is there any way to avoid pause?

It depends on your dataset. If your data contains pause which corresponds to the punctuation symbols, the model interprets the symbols as the pause token. To avoid this issue, you need to remove the pause from your dataset.

> I meet 1-2% cases of noise without voice in the middle or end of sentences/phrases. Usually the repeating synthesis fix the issue. Do I need to tune the settings of ESPnet TTS or ParallelWaveGAN to avoid such behavior? Actually I can use output checking tools to pass wrong attempts and repeat it again, but I am not sure in it.

I think this is caused by the text2mel model part due to attention failure.
This is a common issue of the auto-regressive text2mel model.
Maybe you can avoid this issue by
- Use a large `bce_pos_weight` in training not to failed to stop the generation
- Use attention constraint in Tacotron2
- Use advanced attention mechanism such as [DCA](https://arxiv.org/abs/1910.10288) (You need to implement by yourself)
- Use non-autoregressive model (FastSpeech or FastSpeech2)

> In the vary rare cases the the solution may add a piece of random voices in the end of wave file.(not critical)

The same as the above problem.

> Is it possible to trim end of wav file? It could be very useful to avoid long pauses after phrase (less 1% of cases). I can do myself with the help of ffmpeg or sox. Just I need to know lower (voice) signal level. (not critical)

The best way is to use force alignment results.
If your dataset is clean, you can use librosa's trim function.

> I may suppose that you may see that the script failed to decode after the first comma (',').

I think this is basically the same as the above problem.
And also it is related to the cleaning of your datset.
As you mentioned the above, it seems that your dataset includes the long pause at the end of wav file.
This causes the error of generation stop.
So you need to carefully trim your training data as much as possible.

**Comment by ican24** [comment]
Thank you very much!
I'll study all your recomendations to find best solutions.
A few minutes ago I found that the main punctuation symbols like Comma, Colon  are not purely ASCII characters in my phonetic conversation table. Do you confirm that they may cause above mentioned troubles?

**Comment by kan-bayashi** [comment]
> Do you confirm that they may cause above mentioned troubles?

I think the character of the symbol is not related.
Any symbol will be OK to use.
The problem is that the relationship of the pause in the dataset and the symbol which corresponds to the pause.

**Comment by ican24** [comment]
Thank you for explanation!

**Comment by ican24** [comment]
> As you mentioned the above, it seems that your dataset includes the long pause at the end of wav file.

No my dataset is a clear in the start and end sections.  I had carefully trimmed it with the help of Kaldi tools.
Below is a sample.

![Screenshot from 2020-08-26 14-49-54](https://user-images.githubusercontent.com/19214100/91311994-9f85ee80-e7ab-11ea-9e37-f6425e3285b4.png)

Anyway your information is enough to start new investigation and testing.
I'll pubilsh results here.

Thank you again. Your support is a great! 
You can count on my help for your project, if necessary.

**Comment by kan-bayashi** [comment]
From your picture, the pause in the middle is too long.
It is better to remove the silence or divide into several sentences.

**Comment by ican24** [comment]
Dear @kan-bayashi,

> It is better to remove it or divide into several sentences.
(In my case, we modify the pause to be less than 0.5 sec.)

Have you any recommendation to do it automatically?  
Is there any tool to remove long pause from the middle of the audio file?

Thank you in advance!

**Comment by kan-bayashi** [comment]
I used the force alignment results with pause insertion.
(Just cut the pause part and concatenate them.)

**Comment by ican24** [comment]
Thanks a lot!
I am intensively using aeneas for dataset preparation.  So firstly I'll try it.
If you have other recommendation of  the force alignment tools, please inform me.

**Comment by ican24** [comment]
Much more easy to remove pause with the help of Audacity.
1. create new chain/macro with "Truncate Silence" + "Export wav"
2. apply to "files"
You may find your modified files in the "cleaned" folder of your files location.

**Comment by ican24** [comment]
Dear @kan-bayashi,

I found a real reason of pause after some punctuation symbols.
Actually I caused it myself, when splitting some long sentences more than 175 characters mainly using comma (",") and some other punctuation symbols in the middle sentence.
Sometimes the sentenes in my language are so long. More than 30% cases I am forced to split sentences.
1. Which is a reommended max size of the dataset line for ESPnet TTS?
2. Do I need to replcae  comma (",") and other punctuation symbols in the end of splitted line with end of the sentence symbol to avoid pause trouble?
3. How many hours optimal for dataset: 10, 15, 20?

Thank you in advance!

**Comment by kan-bayashi** [comment]
Sorry for late reply.

> Which is a reommended max size of the dataset line for ESPnet TTS?

What does it mean?
You mean the maximum length of each utterance?
You can refer the other well-structured dataset like ljspeech.
For example, the maximum length of ljspeech utterances is around 10 seconds.

> Do I need to replcae comma (",") and other punctuation symbols in the end of splitted line with end of the sentence symbol to avoid pause trouble?

I'm not sure. It is better to investigate.

> How many hours optimal for dataset: 10, 15, 20?

Of course longer is better. But 10 hours should be working.

**Comment by ican24** [comment]
Thank you!

**Comment by ican24** [comment]
I am glad to inform about Happy End of one project for new language customization.
All listed issues were successfully resolved! 
The new synthesized voice, which was developed by your recommendations,  is really wonderful!
https://youtu.be/W1AGRF6VrUw
I think all customers of the new generated voices will be thankful to ESPnet for its active support to one of ancient languages of the world Armenian with 5000 and more history.

Dear @kan-bayashi , one indirect question: could you advise me a good platform for Machine Translation?
Your professional advice is really valuable.

Thank you in advance!
