### ISSUE TITLE
How to load ESPnet1 ASR model in python

### ISSUE THREAD

**Issue by jamfly** [espnet/espnet#2328]
## Summary

I executed HKUST recipe work fine, from stage 0 to stage 5 all worked fine. I can train model well and get the decoded result.
but when I used [asr_cli](https://espnet.github.io/espnet/notebook/asr_cli.html) as reference to load my model, I got error.

## Re-produce
```
import os
import json
import matplotlib.pyplot as plt
import kaldiio

import torch
import argparse
from espnet.bin.asr_recog import get_parser
from espnet.nets.pytorch_backend.e2e_asr import E2E
from IPython.display import Audio

...
model_dir = root + "/exp/train_nodup_sp_pytorch_train/results"

# load model
with open(model_dir + "/model.json", "r") as f:
  idim, odim, conf = json.load(f)
model = E2E(idim, odim, argparse.Namespace(**conf))
checkpoint = '/model.loss.best'
model.load_state_dict(torch.load(model_dir + checkpoint)) <--- this is where problem occurred 
```

## Error message
full error message is:  [error.log](https://github.com/espnet/espnet/files/5094778/error.log)

## Decoded result
[decode_log.zip](https://github.com/espnet/espnet/files/5094801/decode_log.zip)
[decode_log_2.zip](https://github.com/espnet/espnet/files/5094802/decode_log_2.zip)

**Comment by kan-bayashi** [comment]
`from espnet.nets.pytorch_backend.e2e_asr import E2E` is RNN.
You need to use `from espnet.nets.pytorch_backend.e2e_asr_transformer import E2E`.
You can use this function to load model.
https://github.com/espnet/espnet/blob/3b68f3a7ef6b334003d1a69279a11765f3ce3f3d/espnet/asr/pytorch_backend/asr_init.py#L158

**Comment by jamfly** [comment]
Hi sorry for late response, it works. 
thanks for your help.
