### ISSUE TITLE
error: command 'gcc' failed with exit status 1

### ISSUE THREAD

**Issue by SazerLife** [espnet/espnet#2329]
Hi everyone! Could you help me with this issue? I tried to apply a lot of answers from other issues but have no found a solution. As I understand it, this problem is related to PyTorch and Cuda version? Now my Cuda version is 10.2.

```
src/binding.cpp:8:14: fatal error: THC.h: No such file or directory
     #include "THC.h"
              ^~~~~~~
compilation terminated.
error: command 'gcc' failed with exit status 1
Makefile:146: recipe for target 'warp-transducer.done' failed
make: *** [warp-transducer.done] Error 1
```

I get this error when to execute the last command in an install tutorial ("make" into <espnet-root>/tools

**Comment by kamo-naoyuki** [comment]
Sorry, this is know issue and not fixed yet: https://github.com/espnet/espnet/issues/2302

**Comment by SazerLife** [comment]
Sorry for the duplicate. I didn't found it before... And thx! This issue resolved my problem!
