### ISSUE TITLE
error when no ended hypothesis 

### ISSUE THREAD

**Issue by sw005320** [espnet/espnet#233]
The recognition program will be failed when there is no ended hypothesis.
This happens at
https://github.com/espnet/espnet/blob/master/src/nets/e2e_asr_attctc_th.py#L1894
https://github.com/espnet/espnet/blob/master/src/nets/e2e_asr_attctc.py#L824

We need to have some treatment, e.g., just pushing a null result to `ended_hyps` with warning when no ended hypothesis.

**Comment by kan-bayashi** [comment]
Fixed (#378)
