### ISSUE TITLE
Dependency joblib version conflict by setup.py of espnet ver. 0.9.1

### ISSUE THREAD

**Issue by artingithug** [espnet/espnet#2337]
##### Description:
By pip3, espnet ver. 0.9.1 cannot be installed due to the version conflict on the dependency joblib library specified
in setup.py

##### Detail:
As below, pipenv exposed the version conflict on the dependency joblib library (when I have let pipenv attempt
resolving dependency versions since I couldn't install espnet ver. 0.9.1 by pip3):

    pipenv.exceptions.ResolutionFailure: ERROR: Could not find a version that matches joblib==0.13.2,>=0.11,>=0.14
    (from librosa==0.8.0->espnet==0.9.1->-r /tmp/pipenvu7j3l31qrequirements/pipenv-7n050fn4-constraints.txt (line 2))
      joblib==0.13.2 (from languageflow==1.1.13a1->underthesea==1.1.17->espnet-tts-frontend==0.0.2->espnet==0.9.1->-r /tmp/pipenvu7j3l31qrequirements/pipenv-7n050fn4-constraints.txt (line 2))
      joblib>=0.11 (from scikit-learn==0.23.2->librosa==0.8.0->espnet==0.9.1->-r /tmp/pipenvu7j3l31qrequirements/pipenv-7n050fn4-constraints.txt (line 2))
      joblib>=0.14 (from librosa==0.8.0->espnet==0.9.1->-r /tmp/pipenvu7j3l31qrequirements/pipenv-7n050fn4-constraints.txt (line 2))

1.1.13a1 is the latest version of languageflow library what the latest espnet-tts-frontend ver. 0.0.2 depends on.<br />
Thereby the possible quick solution seems to downgrade the librosa version to 0.7.2 from 0.8.0 in the espnet's setup.py
file(?); please be advised that I didn't check librosa's change log or neither tested functional impact(s).

##### Environment:
- python: 3.8(.2)
- pip: 20.0.2 (and pipenv: 2020.8.13)
- OS: Ubuntu 20.04.1 LTS in a LXD container. (I'm aware that espnet doc states support upto Ubuntu 18; however, for this
joblib version conflict in installation by pip shouldn't be matter. If does matter, then please close this as user
error.)
- CUDA: N/A
- PyTorch: 1.6.0+cpu

##### Supplemental info:
- After changing librosa version to 0.7.2 (and some other changes) in setup.py, I could build and install espnet ver
0.9.1 by using pipenv (I used rather pipenv than pip for resolving versions in installation, because pip surprisingly
often misses and/or ignores version conflict in general; pip tended to blindly install conflicting nltk, underthesea,
languageflow and scikit-learn.)
    - Sanity check post espnet installation:
            
            ~/tools/espnet$ pip check
            No broken requirements found.
            
            ~/tools/espnet$ pip show espnet
            Name: espnet
            Version: 0.9.1
            ...
            Requires: configargparse, typeguard, humanfriendly, scipy, matplotlib, pillow, editdistance, gdown, tensorboard, librosa, resampy, pysptk, sentencepiece, nltk, morfessor, PyYAML, soundfile, h5py, kaldiio, inflect, unidecode, pyworld, nnmnkwii, espnet-tts-frontend, museval, pystoi, nara-wpe, torch-complex, pytorch-wpe, mir-eval, fastdtw
            Required-by:
            
            ~/tools/espnet$ pip3 freeze | grep -E 'joblib|languageflow|underthesea|espnet-tts-frontend|scikit-learn|librosa'
            espnet-tts-frontend==0.0.2
            joblib==0.13.2
            languageflow==1.1.13a1
            librosa==0.7.2
            scikit-learn==0.20.3
            underthesea==1.1.17
            
        For the whole list of the installed dependency versions:
        
        - by [pip freeze](https://gist.github.com/artingithug/1daf2822ba5af3f481e871390244a0f7/raw/68e5f53e3eff803f64ea29faad5551d7e713afb9/pip3.freese.out)
        - by [pipenv graph](https://gist.githubusercontent.com/artingithug/1daf2822ba5af3f481e871390244a0f7/raw/68e5f53e3eff803f64ea29faad5551d7e713afb9/pipenv.graph.out)
    
    - Change on setup.py:
            
            ~/tools/espnet$ git log --pretty="%h %ci %aN %d %s" --decorate=full -2 setup.py
            3629c9190 2020-08-15 16:27:57 +0900 Tomoki Hayashi  (tag: refs/tags/v.0.9.1) updated version
            5eb09dfba 2020-08-14 12:30:48 +0900 kamo-naoyuki  Update zeroth_korean
            
            ~/tools/espnet$ git log --pretty="%h %ci %aN %d %s" --decorate=full -1
            3b68f3a7e 2020-08-18 21:22:09 +0900 Naoyuki Kamo  (HEAD -> refs/heads/master, refs/remotes/origin/master, refs/remotes/origin/HEAD) Remove unused option from enh.sh:--feats_normalize (#2325
            
            ~/tools/espnet$ git diff -U1 setup.py
            index b630babd4..2fda85f7c 100644
            --- a/setup.py
            +++ b/setup.py
            @@ -9,6 +9,6 @@ requirements = {
                 "install": [
                     "setuptools>=38.5.1",
                        +        # "setuptools>=38.5.1",
                                 "configargparse>=1.2.1",
                                 "typeguard>=2.7.0",
                        -        "dataclasses",  # For Python<3.7
                        +        # "dataclasses",  # For Python<3.7
                                 "humanfriendly",
                        @@ -19,3 +19,4 @@ requirements = {
                                 "gdown",
                        -        "espnet_model_zoo",
                        +        # Commented espnet_model_zoo to avoid cyclic dependency loop back to espnet
                        +        # "espnet_model_zoo",
                                 # DNN related packages are installed by Makefile
                        @@ -25,5 +26,9 @@ requirements = {
                                 "tensorboard>=1.14",  # For pytorch>=1.1.0
                        -        "tensorboardX>=1.8",  # For pytorch<1.1.0
                        +        # Commented tensorboardX since using pytorch 1.6 and also causing
                        +        # protobuf version conflilct with chainer==6.0.0 above.
                        +        # "tensorboardX>=1.8",  # For pytorch<1.1.0
                                 # Signal processing related
                        -        "librosa>=0.8.0",
                        +        # "librosa>=0.8.0",
                        +        # Downgrade to avoid version conflick on joblib
                        +        "librosa==0.7.2",
                                 "resampy",
                        @@ -55,3 +60,4 @@ requirements = {
                                 "fastdtw",
                        -        "pyworld",
                        +        # Commented pyworld as already added above
                        +        # "pyworld",
                             ],
                        @@ -112,5 +118,6 @@ setup_requires = requirements["setup"]
                         tests_require = requirements["test"]
                        -extras_require = {
                        +# wrapped by dict due to avoid no attribute 'keys' on DictComp with pipenv
                        +extras_require = dict({
                             k: v for k, v in requirements.items() if k not in ["install", "setup"]
                        -}
                        +})

        Note:
        
        - I got to comment espnet_model_zoo; otherwise installation by pipenv got conflict on librosa again due to
        cyclic reference back - should be pipenv issue or my lack of knowledge.
                
                pipenv.exceptions.ResolutionFailure: ERROR: Could not find a version that matches librosa==0.7.2,>=0.8.0 (from -r /tmp/pipenv7eer73jlrequirements/pipenv-juwhxoue-constraints.txt (line 17))
                Tried: 0.2.0.linux-x86_64, 0.2.1.linux-x86_64, 0.2.0, 0.2.1, 0.3.0, 0.3.1, 0.4.0, 0.4.1, 0.4.2, 0.4.3, 0.5.0, 0.5.1, 0.6.0, 0.6.1, 0.6.2, 0.6.3, 0.7.0, 0.7.1, 0.7.2, 0.8.0
                Skipped pre-versions: 0.4.0rc2, 0.4.1rc0, 0.4.3rc0, 0.5.0rc0, 0.6.0rc0, 0.6.0rc1, 0.6.1rc0, 0.7.0rc1, 0.7.0rc1
                There are incompatible versions in the resolved dependencies:
                  librosa==0.7.2 (from -r /tmp/pipenv7eer73jlrequirements/pipenv-juwhxoue-constraints.txt (line 17))
                  librosa>=0.8.0 (from espnet==0.9.1->espnet-model-zoo==0.0.0a8->-r /tmp/pipenv7eer73jlrequirements/pipenv-juwhxoue-constraints.txt (line 34))

**Comment by kamo-naoyuki** [comment]
Pip3 will change the behaviour when version conflicting and such conflicting packages is not allowed after the updating. However, you can install espnet for now as it is if ignoring pipenv.

Anyway, we must solve this issue in the near future. 
I removed underthesea from the requirements for workaround. I think the requirement is crazy. We shouldn't use such module. @kan-bayashi
We still have conflicting for protobuf between chainer==6.0.0 and tensorboardX. i.e. chainer=6.0.0 will be unavailable soon.
