### ISSUE TITLE
Bug when install espnet 

### ISSUE THREAD

**Issue by JinmingZhao** [espnet/espnet#2358]
when make the espnet, there is a bug in the check_pytorch_cuda_compatibility.py

$cd espnet/tools
$make 

when use pytorch = 1.1.0  and there is no maybe_supported variable in   'espnet/tools/check_pytorch_cuda_compatibility.py'

How to fix:
add  'maybe_supported=[]'  in the begin of the function: check()

**Comment by kamo-naoyuki** [comment]
thanks, I missed,
