### ISSUE TITLE
sclite error while decoding

### ISSUE THREAD

**Issue by sathvikask0** [espnet/espnet#236]
Thanks everyone for this toolkit. I was successfully able to train model for librispeech dataset.
But while running stage 4 , I am getting the following error:.
It could not find ref.trn and hyp.trn. I could find only ref.wrd.trn and hyp.wrd.trn in the corresponding location. Kindly help.

**_sclite: Error, Reference file 'exp/train_960_blstmp_e8_subsample1_2_2_1_1_unit320_proj320_d1_unit300_location_aconvc10_aconvf100_mtlalpha0.5_adadelta_bs12_mli800_mlo150/decode_dev_clean_beam20_eacc.best_p0.0_len0.0-0.0_ctcw0.3/ref.trn' does not exist

write a CER (or TER) result in exp/train_960_blstmp_e8_subsample1_2_2_1_1_unit320_proj320_d1_unit300_location_aconvc10_aconvf100_mtlalpha0.5_adadelta_bs12_mli800_mlo150/decode_dev_clean_beam20_eacc.best_p0.0_len0.0-0.0_ctcw0.3/result.txt
sed: can't read exp/train_960_blstmp_e8_subsample1_2_2_1_1_unit320_proj320_d1_unit300_location_aconvc10_aconvf100_mtlalpha0.5_adadelta_bs12_mli800_mlo150/decode_dev_clean_beam20_eacc.best_p0.0_len0.0-0.0_ctcw0.3/ref.trn: No such file or directory
sed: can't read exp/train_960_blstmp_e8_subsample1_2_2_1_1_unit320_proj320_d1_unit300_location_aconvc10_aconvf100_mtlalpha0.5_adadelta_bs12_mli800_mlo150/decode_dev_clean_beam20_eacc.best_p0.0_len0.0-0.0_ctcw0.3/hyp.trn: No such file or directory
/home/srib/end2end/espnet-master/src/utils/score_sclite.sh: line 52:  4247 Segmentation fault      (core dumped) sclite -r ${dir}/ref.wrd.trn trn -h ${dir}/hyp.wrd.trn trn -i rm -o all stdout > ${dir}/result.wrd.txt
write a WER result in exp/train_960_blstmp_e8_subsample1_2_2_1_1_unit320_proj320_d1_unit300_location_aconvc10_aconvf100_mtlalpha0.5_adadelta_bs12_mli800_mlo150/decode_dev_clean_beam20_eacc.best_p0.0_len0.0-0.0_ctcw0.3/result.wrd.txt_**

**Comment by marvinzh** [comment]
same issue, anyone got a solution?
