### ISSUE TITLE
Bug: score_bleu.sh removes good tokens

### ISSUE THREAD

**Issue by formiel** [espnet/espnet#2363]
Hello,

While reproducing an experiment on MuST-C, I realized that the reference file used for computing BLEU is different from the original reference file: tokens such as `(_Gelächter_)` and `(_Applaus_)` are removed from both the reference and the hypothesis.

After checking `score_bleu.sh`, I think that the issue lies at [these lines](https://github.com/espnet/espnet/blob/d0846517c1a69cd32ac6c09dabd883ba8417ca48/utils/score_bleu.sh#L33-L36) for removing utterance IDs (they seem to remove everything between parentheses).

Could you please check this? The issue seems critical as it may impact results reported in published papers.

Thank you in advance!

**Comment by sw005320** [comment]
Indeed, it is critical.
@hirofumi0810, could you check this issue?

**Comment by hirofumi0810** [comment]
Thanks, @formiel! I think this is OK because these labels can be removed in the recent IWSLT evaluation campaign. 

@sw005320 What do you think about this? One possible solution is to make this an option.

**Comment by hirofumi0810** [comment]
@formiel One reference: https://www.aclweb.org/anthology/2020.acl-main.350.pdf
This recent ACL paper on simultaneous ST actually removed such labels in advance.

**Comment by sw005320** [comment]
> After checking score_bleu.sh, I think that the issue lies at these lines for removing utterance IDs (they seem to remove everything between parentheses).

@formiel, could you clarify it?
I could read that it processes the longest matching instead of the shortest matching.

@hirofumi0810, if it is based on the longest matching, this would be an issue.

**Comment by formiel** [comment]
@sw005320 @hirofumi0810  Thank you for your replies!

> > After checking score_bleu.sh, I think that the issue lies at these lines for removing utterance IDs (they seem to remove everything between parentheses).
> 
> @formiel, could you clarify it?

I think that these lines removing all characters (except for the character`)` ) between the parenthesis `()` together with the parenthesis itself. Since some tokens such as `Applaus`, `Gelächter`, etc. are put in the parenthesis (similar to utterance IDs), they are deleted as well when we remove the utterance IDs.

Below is a test case including some lines from tst-COMMON.en-de set. 
```
▁E ine ▁über ▁alle m ▁Ma ßen ▁gesch ät z te ▁Fre und lich keit ▁: ▁J em and ▁hatte ▁ihr ▁so gar ▁ein ▁P aar ▁Sch u he ▁ge bra cht ▁. (ted_01096-ted_01096_0159150_0165070)
▁( ▁Gelächter ▁) (ted_01096-ted_01096_0166725_0166925)
▁Also ▁le gen ▁Sie ▁los ▁; ▁ret ten ▁Sie ▁die ▁Sch u he ▁. (ted_01096-ted_01096_0216900_0219310)
▁Vi elen ▁Dank ▁. (ted_01096-ted_01096_0219880_0228600)
▁( ▁Applaus ▁) (ted_01096-ted_01096_0228525_0228725)
▁Und ▁ne in ▁, ▁es ▁ist ▁nicht ▁B urn ing ▁Man ▁oder ▁San ▁Francisco ▁. ▁( ▁Lachen ▁) ▁Me ine ▁D amen ▁und ▁Her ren ▁, ▁I hre ▁Ver w and ts chaft ▁. (ted_01102-ted_01102_0028360_0036790)
▁( ▁Lachen ▁) (ted_01102-ted_01102_0065055_0065255)
```
When I run `perl -pe 's/\([^\)]+\)//g;'` on this, the result is:
```
▁E ine ▁über ▁alle m ▁Ma ßen ▁gesch ät z te ▁Fre und lich keit ▁: ▁J em and ▁hatte ▁ihr ▁so gar ▁ein ▁P aar ▁Sch u he ▁ge bra cht ▁. 
▁ 
▁Also ▁le gen ▁Sie ▁los ▁; ▁ret ten ▁Sie ▁die ▁Sch u he ▁. 
▁Vi elen ▁Dank ▁. 
▁ 
▁Und ▁ne in ▁, ▁es ▁ist ▁nicht ▁B urn ing ▁Man ▁oder ▁San ▁Francisco ▁. ▁ ▁Me ine ▁D amen ▁und ▁Her ren ▁, ▁I hre ▁Ver w and ts chaft ▁. 
```

**Comment by sw005320** [comment]
Thanks for the clarification.
Unintentional longest matching seems to happen.

@hirofumi0810, could you fix it?
It would change the evaluation result, but I believe it would not be very large.

**Comment by hirofumi0810** [comment]
@formiel This is the expected behavior. We remove parenthesis together with characters inside.
Also, this is not the longest match. It should be the shortest match because `)` is included in the regular expression `'s/\([^\)]+\)//g;'`.

**Comment by sw005320** [comment]
I see. Thanks for the clarification!
Maybe it's better to leave some documents about it?

**Comment by formiel** [comment]
> @formiel This is the expected behavior. We remove parenthesis together with characters inside.

Well, I was aware of what that regex does, but is it really what we want? The authors of MuST-C didn't seem to do that in their evaluations so it would be difficult to have a fair comparison between papers.

Your suggestion about making this an option seems reasonable to me, but then I wonder how you could accurately detect such non-verbal tokens in the predictions (which, unlike the ground-truth, may be incomplete and random, e.g. `_( _Applaus_ _)_)_)`). I would suggest to leave this kind of pre-/post-processing to the users, and fix only the removal of the utterance IDs (currently it removes something else as well, which is not desirable). A solution could be e.g. replacing `(utterance_ID)` with `<id>utterance_ID</id>`.

**Comment by formiel** [comment]
Or a much simpler solution: just replacing `perl -pe 's/\([^\)]+\)//g;'` with `perl -pe 's/\([^\)]+\)\n/\n/g;'`.

**Comment by hirofumi0810** [comment]
The IWSLT organizers accept to remove these labels.

See 
https://hal.archives-ouvertes.fr/hal-02895893/document
https://groups.google.com/g/iwslt-evaluation-campaign/c/13pm6nGXKlQ/m/ypQCzO6TBQAJ

**Comment by sw005320** [comment]
Thanks, @hirofumi0810 for further clarification.
To reconcile the evaluation setups for both IWSLT and MuST-C, it's better to 1) add an option to switch them or 2) we can make a test set for both IWSLT and MuST-C but select either of them in iwslt19 and must_c recipes, or whatever.
In either case, we may need to add the note about the above (and set the link of this issue) in `run.sh`.

Is that OK for @hirofumi0810 and @formiel?

**Comment by formiel** [comment]
@sw005320 Sounds good to me. Thank you!

FYI, in my experiments, the new BLEU scores decrease from 0.02 to 0.31.

**Comment by sw005320** [comment]
Thanks!
I had a conversation with @hirofumi0810, and he would add some options in the script to switch between IWSLT and Must-C standards.

**Comment by formiel** [comment]
@sw005320 That's great! I'm glad to hear that. I look forward to the update.
