### ISSUE TITLE
Espnet 2 installation

### ISSUE THREAD

**Issue by samin9796** [espnet/espnet#2380]
I found this link in the docs - [https://github.com/espnet/espnet/blob/master/doc/installation.md](url)
Do I need to follow this doc for Espnet 2 installation or is it for Espnet 1?

*** In this doc, step 1 is kaldi installation. Do I need this for Espnet 2?

**Comment by kamo-naoyuki** [comment]
You don't need to compile Kaldi to use espnet2, but some features are restricted for ASR recipe. 

- Kaldi fbank and pitch feature are unavailable.
- Some recipe might still depend on Kaldi (This should be a bug. Please report me if you found.)

For ESPnet2 TTS/ENH recipe, there is no use to compile Kaldi.

**Comment by samin9796** [comment]
@kamo-naoyuki 
I am getting this error while running the `make` command.

> fatal error: cublas_v2.h: No such file or directory
 #include <cublas_v2.h>
          ^~~~~~~~~~~~~
compilation terminated.
error: command 'gcc' failed with exit status 1
Makefile:155: recipe for target 'warp-transducer.done' failed
make: *** [warp-transducer.done] Error 1

I don't find any cublas_v2.h file. I am using cuda 10.0 version.

**Comment by kamo-naoyuki** [comment]
I tested from scratch just now, I didn't met the error, but I don't have cublas_v2.h, too.

Please show the least information, pytorch version, cuda version, OS, gcc version, using anaconda or not. Did you use setup_cuda_env.sh correctly? Do you have  cublas_v2.h there? 

```sh
find ${CUDA_HOME} -name cublas_v2.h
```

**Comment by samin9796** [comment]
OS: Ubuntu 18.04 LTS
cuda version: 10.0
gcc version: 7.5.0
pytorch version: 1.2.0 (Trying to install it with `make TH_VERSION=1.2.0` command.

I am installing these under anaconda environment. I used this one - `. ./setup_cuda_env.sh /usr/local/cuda`
`find ${CUDA_HOME} -name cublas_v2.h` command returns nothing.

**Comment by kan-bayashi** [comment]
Did you install cuda correctly at `/usr/local/cuda`?
(You need to install cuda by yourself.
`cublas_v2.h` should be located in `/usr/local/cuda/include/`.
```
$ ls /usr/local/cuda-10.0/include/ | grep blas
cublas.h
cublas_api.h
cublas_v2.h
cublasXt.h
nvblas.h
```

**Comment by samin9796** [comment]
This is what I get:

> nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2018 NVIDIA Corporation
Built on Sat_Aug_25_21:08:01_CDT_2018
Cuda compilation tools, release 10.0, V10.0.130

> $ whereis cuda
/usr/include/cuda.h /usr/local/cuda

> $ ls /usr/local/cuda/include/ | grep blas
ls: cannot access '/usr/local/cuda/include/': No such file or directory

> $ ls /usr/local/cuda-9.0/include/ | grep blas
cublas_api.h
cublas.h
cublas_v2.h
cublasXt.h
nvblas.h

If I use cuda-9.0 path as cuda root path then I get compatibility issue with gcc version. Now should I try with cuda-9.0 for ESPnet 2 or instead install cuda-10.0 again?

**Comment by kan-bayashi** [comment]
If `cublas_v2.h` is located in `/usr/include`, why don't you make symlink (`/usr/local/cuda/include -> `/usr/include`)?

**Comment by tobiascornille** [comment]
I don't get how I can install ESPnet 2 without Kaldi, cause when I run make, I still need it is seems...
```
...espnet/tools $ make
expr: syntax error: unexpected argument ‘102’
test -f kaldi/egs/wsj/s5/utils/parse_options.sh || { echo -e "Error: Put Kaldi here!\n    $ ln -s <kaldi-root> kaldi"; exit 1; }
-e Error: Put Kaldi here!
    $ ln -s <kaldi-root> kaldi
```

**Comment by kan-bayashi** [comment]
You do not need to compile kaldi but must make the symbolic link. Just clone kaldi and make symlink as the document said.
