### ISSUE TITLE
How to use a large number to train a language model 

### ISSUE THREAD

**Issue by WuHao9408** [espnet/espnet#2387]
Can chainer use large-scale corpus （more than 100GB）to train a language model ? i don't know chainer Iterator whether need the whole dataset. I try to use pytorch IterableDataset to produce data to train, read lines as a batch, but it seems failed.

**Comment by kamo-naoyuki** [comment]
LM training reads the whole text data at startup, so you need large amount of memory as the corpus.
IterableDataset can solve this problem if you correctly implement, but it's hard to shuffle the corpus. I don't know whether it affects the training result or not.

I recently implemented a new feature in espnet2 to handle large corpus by another solution.
If you split a large text file into sub texts, data iterators can be created using them one by one in the training. You can enable this option by `--num_splits_lm` and `--num_splits_asr` in the recipe.
