### ISSUE TITLE
Recently updated setuptools cause installation failed 

### ISSUE THREAD

**Issue by keshawnhsieh** [espnet/espnet#2390]
[setuptools](https://pypi.org/project/setuptools/#history) updates its version to 50.0.0 yesterday and cause espnet installation failed. It's hard to debug because installation log doesn't show this failure cause explicitly, but rollback the version of setuptools to 49.6.0 do works.

**Comment by kamo-naoyuki** [comment]
Thanks, there are some problems reported at https://github.com/pypa/setuptools/issues, so we should care it for a while.
