### ISSUE TITLE
Is there a egs using the specaugment?

### ISSUE THREAD

**Issue by 7zhanghao** [espnet/espnet#2391]
I want to use specaugment proposed by Google, but i can't find a egs.

**Comment by kamo-naoyuki** [comment]
You can find it https://github.com/espnet/espnet/blob/master/egs/librispeech/asr1/run.sh#L24 for example.

**Comment by 7zhanghao** [comment]
> You can find it https://github.com/espnet/espnet/blob/master/egs/librispeech/asr1/run.sh#L24 for example.

Thanks a lot, it helps.
