### ISSUE TITLE
why subsample is not supported for transfomer

### ISSUE THREAD

**Issue by housebaby** [espnet/espnet#2398]
I notice that subsample is not supported for transformer . 
Can anyone tell me why ?
with tranformer_ctc model 300M  and RNN lm 200M , 
the real-time rate on GPU is almost 1, which we expect it will no more that 0.5.
How will subsample will affect transformer performance , when we want to use it reduce the reat-time-rate

**Comment by Fhrozen** [comment]
The transformer has its subsampling layer (Conv2D performs the subsample). While LSTM does not perform subsampling, and then it is required there.
>the real-time rate on GPU is almost 1, which we expect it will no more that 0.5.
I am not sure about this, but did you try to reduce the beam-search size? I am not sure which recipe are you using and some of the recipes includes larger beam-size: 
https://github.com/espnet/espnet/blob/b88e89fc7246fed4c2842b55baba884fe1b4ecc2/egs/librispeech/asr1/conf/tuning/decode_pytorch_transformer_large.yaml#L2

**Comment by housebaby** [comment]
> The transformer has its subsampling layer (Conv2D performs the subsample). While LSTM does not perform subsampling, and then it is required there.
> 
> > the real-time rate on GPU is almost 1, which we expect it will no more that 0.5.
> 
> I am not sure about this, but did you try to reduce the beam-search size? I am not sure which recipe are you using and some of the recipes includes larger beam-size:
> https://github.com/espnet/espnet/blob/b88e89fc7246fed4c2842b55baba884fe1b4ecc2/egs/librispeech/asr1/conf/tuning/decode_pytorch_transformer_large.yaml#L2

Yes ， if the beam-size is 60, real-time-rate is over 15; if beam-size = 5, real-time-rate is 0.96. And the wer of the latter is higher.

**Comment by housebaby** [comment]
> The transformer has its subsampling layer (Conv2D performs the subsample). While LSTM does not perform subsampling, and then it is required there.
> 
> > the real-time rate on GPU is almost 1, which we expect it will no more that 0.5.
> 
> I am not sure about this, but did you try to reduce the beam-search size? I am not sure which recipe are you using and some of the recipes includes larger beam-size:
> https://github.com/espnet/espnet/blob/b88e89fc7246fed4c2842b55baba884fe1b4ecc2/egs/librispeech/asr1/conf/tuning/decode_pytorch_transformer_large.yaml#L2

I notice that the in transformer subsample is only done in the input layer, but in RNN , subsample can be done in any layer.
Is it possible to use subsample in each layer of transformer

**Comment by Fhrozen** [comment]
> I notice that the in transformer subsample is only done in the input layer, but in RNN , subsample can be done in any layer.
Is it possible to use subsample in each layer of transformer, so the real time rate can be further reduced

The subsampling on the transformer is enough. I think that the problem is not related to the encoder (where the subsampling is performed) but with the decoder.
Additional subsampling on the encoder will only decrease the (recognition) performance and may affect the CTC. 
I will recommend you check additional parameters for decoding, using api_v2 for example (this is supposed to perform faster than api_v1).

**Comment by housebaby** [comment]
> > I notice that the in transformer subsample is only done in the input layer, but in RNN , subsample can be done in any layer.
> > Is it possible to use subsample in each layer of transformer, so the real time rate can be further reduced
> 
> The subsampling on the transformer is enough. I think that the problem is not related to the encoder (where the subsampling is performed) but with the decoder.
> Additional subsampling on the encoder will only decrease the (recognition) performance and may affect the CTC.
> I will recommend you check additional parameters for decoding, using api_v2 for example (this is supposed to perform faster than api_v1).

I already use api_v2.  I think current subsample is just like that in the picture. It is not in the encoder body, but before the encoder body. So you mean , it is not neccesary to do subsample in the encoder-body of transformer.?
![image](https://user-images.githubusercontent.com/9246556/91963583-9ca57380-ed40-11ea-8cf5-16ff137f9f4f.png)
