### ISSUE TITLE
CUDA Upgrade - Reinstall?

### ISSUE THREAD

**Issue by picheny-nyu** [espnet/espnet#2410]
When I originally installed espnet I did not think we had nccl installed. As it turns out, we do - in a higher level version of Cuda. Do I need to reinstall espnet to make sure nccl is accessible? What do I need to do to point espnet to this version of cuda?

**Comment by kamo-naoyuki** [comment]
The dependencies on cuda comes from pytorch and cupy only. NCCL is bundled in both libraries, so you don't need to have NCCL if you use bundled version of them. Actually CUDA library is also unnecessary originally, but to build pytorch warp transducer, we require local installation of CUDA.

I'm not sure whether we need to reinstall pytorch if upgrading CUDA driver. I think it's enough to reinstall after you met some errors. At least, you don't need to reinstall espnet, but it's enough to reinstall pytorch only , or if you use chainer-backend in espnet1, cupy, too.
