### ISSUE TITLE
Running esg2 after esg for AMI - Data Prep?

### ISSUE THREAD

**Issue by picheny-nyu** [espnet/espnet#2414]
I have run the esg/ami recipe (successfully!). I now want to try esg2. I don't want to download the data again. What needs to be set in the scripts to take advantage of the fact that I already have the ami downloaded...and prepared for the esg recipe? 

Thanks
Michael

**Comment by sw005320** [comment]
Please set the path of your AMI data in https://github.com/espnet/espnet/blob/master/egs2/TEMPLATE/asr1/db.sh#L88
Then, the download part will be skipped.
You can also check the AMI data predation script https://github.com/espnet/espnet/blob/master/egs2/ami/asr1/local/data.sh

**Comment by picheny-nyu** [comment]
I did that -  but it still seemed to try to download the data.

**Comment by picheny-nyu** [comment]
OK, let's clarify...I had pointed the script to the waveform data, not the data directories created by running the egs receipe. Should I be pointing to these - e.g. egs/asr1/data? The actual waveform data is someplace else.

**Comment by sw005320** [comment]
I meant to say that `./local/data.sh --stage 2` according to the comment in https://github.com/espnet/espnet/blob/master/egs2/ami/asr1/local/data.sh

**Comment by kamo-naoyuki** [comment]
It should skip downloading if already you have dataset even if `--stage 1`. It is a bug of ami recipe.
