### ISSUE TITLE
MUSTC Speech Translation multilingual recipe en --> 8 languages not available

### ISSUE THREAD

**Issue by sameerkhurana10** [espnet/espnet#2422]
Hi,

is the recipe for multilingual training for speech translation available?

the recipe [here](https://github.com/espnet/espnet/blob/master/egs/must_c/st1/run.sh#L59) claims that it is possible to train a multilingual ST system, but looking further down the script, it does not seem like it is supported.

**Comment by b-flo** [comment]
Hi,

Why do you think multilingual ST is not supported? I'm not familiar with the recipe but looking at the run script it seems any defined subset in `tgt_lang` will be processed (e.g.: `for lang in $(echo ${tgt_lang} | tr '_' ' '); do`)?

**Comment by b-flo** [comment]
> I was thinking about multi-task learning; predict translations from en --> 8 languages simultaneously. By the way, if you give the argument tgt_lang='de_fr_it', it will fail here.

I suppose you're saying there is an error in the body not the loop condition? Could you report the error please?
@hirofumi0810 can you comment on that maybe?

> Another problem that I am facing is:
>
>`utils/validate_data_dir.sh: text contains 3 lines with non-printable characters which occurs at this line`
>
> is there an older version of kaldi that I should be using?

Hum, I guess it's related to recent changes in Kaldi (https://github.com/kaldi-asr/kaldi/issues/4157), I don't know if a fix was merged yet, you can try updating your repo.

**Comment by sameerkhurana10** [comment]
just looking at this piece of code:

```
for lang in $(echo ${tgt_lang} | tr '_' ' '); do
        for x in train.en-${tgt_lang} dev.en-${tgt_lang} tst-COMMON.en-${tgt_lang} tst-HE.en-${tgt_lang}; do
            steps/make_fbank_pitch.sh --cmd "$train_cmd" --nj 32 --write_utt2num_frames true \
                data/${x} exp/make_fbank/${x} ${fbankdir}
        done
    done
```

1. The loop is iterating over `lang` but `lang` is not used anywhere inside the loop
2. If you use `tgt_lang='de_es_fr'`, then while extracting features, the script will look for the following folder: `data/train.en-de_es_fr`, which is never created. Maybe, the code should read:

```
for lang in $(echo ${tgt_lang} | tr '_' ' '); do
        for x in train.en-${lang} dev.en-${lang} tst-COMMON.en-${lang} tst-HE.en-${lang}; do
            steps/make_fbank_pitch.sh --cmd "$train_cmd" --nj 32 --write_utt2num_frames true \
                data/${x} exp/make_fbank/${x} ${fbankdir}
        done
    done
```

You will have to make similar changes at multiple places if you want to support, for example `tgt_lang='de_es_fr'`


About updating kaldi: I have the installation from Septemeber 2, 2020.

Could I ignore the call to `validate_data_dir.sh`?

**Comment by b-flo** [comment]
> just looking at this piece of code:
> 
> ```
> for lang in $(echo ${tgt_lang} | tr '_' ' '); do
>         for x in train.en-${tgt_lang} dev.en-${tgt_lang} tst-COMMON.en-${tgt_lang} tst-HE.en-${tgt_lang}; do
>             steps/make_fbank_pitch.sh --cmd "$train_cmd" --nj 32 --write_utt2num_frames true \
>                 data/${x} exp/make_fbank/${x} ${fbankdir}
>         done
>     done
> ```
> 
>     1. The loop is iterating over `lang` but `lang` is not used anywhere inside the loop
> 
>     2. If you use `tgt_lang='de_es_fr'`, then while extracting features, the script will look for the following folder: `data/train.en-de_es_fr`, which is never created. Maybe, the code should read:
> 
> 
> ```
> for lang in $(echo ${tgt_lang} | tr '_' ' '); do
>         for x in train.en-${lang} dev.en-${lang} tst-COMMON.en-${lang} tst-HE.en-${lang}; do
>             steps/make_fbank_pitch.sh --cmd "$train_cmd" --nj 32 --write_utt2num_frames true \
>                 data/${x} exp/make_fbank/${x} ${fbankdir}
>         done
>     done
> ```

Oh my you're right, sorry it seems I'm more tired than I thought, I read `${tgt_lang}` as `${lang}` in body. I'll let @hirofumi0810 handle the issue as he is the one who made the recipe!

> About updating kaldi: I have the installation from Septemeber 2, 2020.
>
> Could I ignore the call to validate_data_dir.sh?

OK, I saw some changes these days but I didn't check what was commited before asking. Just checked, it's unrelated.
Looking at current `validate_data_dir.sh` it seems there is `--non-print` option to "ignore the presence of non-printable characters.", you could use it.

**Comment by sameerkhurana10** [comment]
Okay, thanks.

Do you think it is better to change the label to 'bug'?

**Comment by hirofumi0810** [comment]
This is not a bug. `st1` does not support multilingual data processing. I have it in my local and it's under preparation.

**Comment by kan-bayashi** [comment]
> Could I ignore the call to validate_data_dir.sh?

`--non-print` option is recently added in kaldi and our recipes do not assume the use of this option.
To quick fix, I recommend editing this file directly to change `non_print=true` as a default.
https://github.com/kaldi-asr/kaldi/blob/40c71c5ee3ee5dffa1ad2c53b1b089e16d967bb5/egs/wsj/s5/utils/validate_data_dir.sh#L9

**Comment by sameerkhurana10** [comment]
yes, thanks. I did that.

**Comment by kan-bayashi** [comment]
@hirofumi0810 Do you plan to commit your multilingual setup?
