### ISSUE TITLE
Fine Tuning:

### ISSUE THREAD

**Issue by speechLearner** [espnet/espnet#2423]
Im currently working on Fine-tuning the [transformers architecture](https://github.com/espnet/espnet/blob/master/egs/hkust/asr1/conf/tuning/train_pytorch_transformer.yaml) . 

Im following the steps illustrated in the "How to use Finetuning] section of this [document](https://github.com/espnet/espnet/blob/master/doc/tutorial.md) .

I attempted to freeze all the layers of the network to get a Hands on experience on working with Finetuning by adding this argument to asr_train.py
"--freeze_mods 'encoder.embed.,decoder.embed.,decoder.decoders.0.,decoder.decoders.1.,decoder.decoders.2.,decoder.decoders.3.,decoder.decoders.4.,decoder.decoders.5.,encoder.encoders.0.,encoder.encoders.1.,encoder.encoders.2.,encoder.encoders.3.,encoder.encoders.4.,encoder.encoders.5.,encoder.encoders.6.,encoder.encoders.7.,encoder.encoders.8.,encoder.encoders.9.,encoder.encoders.10.encoder.encoders.11.' \" 

However The training accuracies and validation accuracies are changing and the network is learning as against the expectation of a flat line. 

Can you please guide me as to what is the error I'm committing and if there is any additional argument that is to be added and how I can get a flat line?

**Comment by kan-bayashi** [comment]
Maybe you miss some layers.
And you do not need to list all of layers as the document said.
What you have to do is as follows: `--freeze_mods 'encoder.,decoder.,ctc.'`
