### ISSUE TITLE
got all zeros result during decoding

### ISSUE THREAD

**Issue by happyjin** [espnet/espnet#2432]
I got incorrect results when I ran hkust dataset. Here are the results as below
![捕获](https://user-images.githubusercontent.com/18534928/92444986-3a3bef80-f1e6-11ea-9a7b-f3d8eaeb2b35.PNG)

During stage 0 to stage 5. I got the message which I am not sure if it leads to the wrong results.
![bug1](https://user-images.githubusercontent.com/18534928/92445020-4aec6580-f1e6-11ea-9b0d-c031f1d62870.PNG)
 Is there anybody who knows how to fix this error? Thanks in advance!

**Comment by speechLearner** [comment]
Hi @happyjin - Thats a warning message.. with reference to the 2nd screenshot I believe the pertubed data prep folder must be prepared having around 496332 utterances. 

with reference to the 1st screenshot, Attaching any log file present in the decode_train_dev_decode_lm/log would help to fix the error.

**Comment by happyjin** [comment]
Hi, @speechLearner Thanks for your awesome advice. I follow #2433 and solved this. I close this issue.
