### ISSUE TITLE
Error: in data/train, recording-ids extracted from segments and wav.scp

### ISSUE THREAD

**Issue by happyjin** [espnet/espnet#2433]
I got an error during stage 1 of run.sh using hkust dataset. The error message is as below:
![bug2](https://user-images.githubusercontent.com/18534928/92446945-2e9df800-f1e9-11ea-8b75-3cc47c627fb8.PNG)
Is there anybody who knows how to figure out this error? Thanks in advance!

**Comment by b-flo** [comment]
Hi,

You already opened the same issue a few days ago (#2415), I'm closing the other one then.

@sw005320 It seems you created the recipe a few years back, maybe you have some comments on that? Or maybe you know someone who used it recently?

**Comment by happyjin** [comment]
@b-flo  Thanks for your swift comment. I installed the latest espnet and kaldi, then follow the original recipe of hkust asr dataset. I get stuck during stage 1 as the screenshot displayed. I am wondering why it happens? And more importantly, how to fix this error.

**Comment by b-flo** [comment]
Sorry, I'll let others familiar with the dataset comment on the issue. A general fix would be to use `utils/fix_data_dir.sh` but I don't think such mismatch is expected, something went wrong during data preparation imo.

**Comment by kamo-naoyuki** [comment]
Did you see #2321 ?

**Comment by speechLearner** [comment]
Hi @happyjin - I have faced this error when I accidentally rerun the stage 1; even though the features were extracted during the previous run . I would suggest you clear the train and dev directory and rerun from stage 0 data preparation

**Comment by happyjin** [comment]
@kamo-naoyuki Thanks for your advice regarding #2321 . I follow the problem by following the detailed steps.
@speechLearner Thanks for your suggestion and I also remove the previous generated data etc folders and re-run it to get new folders. It works.

**Comment by kamo-naoyuki** [comment]
@speechLearner Thanks, we must fix it since hkust recipe has too much problem...

**Comment by kamo-naoyuki** [comment]
@speechLearner Thanks, we must fix it since hkust recipe has too much problem...

**Comment by kamo-naoyuki** [comment]
@speechLearner Thanks, we must fix it since hkust recipe has too much problem...

**Comment by kamo-naoyuki** [comment]
@speechLearner Thanks, we must fix it since hkust recipe has too much problem...

**Comment by kamo-naoyuki** [comment]
@speechLearner Thanks, we must fix it since hkust recipe has too much problem...

**Comment by kamo-naoyuki** [comment]
@speechLearner Thanks, we must fix it since hkust recipe has too much problem...

**Comment by kamo-naoyuki** [comment]
@speechLearner Thanks, we must fix it since hkust recipe has too much problem...

**Comment by kamo-naoyuki** [comment]
@speechLearner Thanks, we must fix it since hkust recipe has too much problem...
