### ISSUE TITLE
wav's pitch feature

### ISSUE THREAD

**Issue by 13913933991** [espnet/espnet#244]
Now I'm trying to extract wav's pitch feature by using python for performance considering, not by kaldi api from shell. Could you give me some advice?

**Comment by sw005320** [comment]
librosa (https://librosa.github.io/librosa/) may have such functions. @kan-bayashi, do you have some comments?

**Comment by kan-bayashi** [comment]
Actually, I've never use pitch extraction function of librosa.
In the speech synthesis task, we often use WORLD to extract pitch.
(There is python wrapper <https://github.com/JeremyCCHsu/Python-Wrapper-for-World-Vocoder>)
But it requires to set the range of f0 of each speaker appropriately to reduce the pitch estimation error.

**Comment by kan-bayashi** [comment]
Please check the WORLD api.
`sp` is spectrum components, and `ap` is aperiodicity components.
You can use only 'f0'.
