### ISSUE TITLE
Low GPU Utilization espnet2 single gpu AMI

### ISSUE THREAD

**Issue by picheny-nyu** [espnet/espnet#2441]
I am seeing what seems to be relatively low gpu utilization (like 25%) for a single GPU for the espnet2 AMI recipe. The gpu utilization seems very spikey - goes high, then goes low, goes high, then goes low. Any idea? Could this be an I/o problem?

**Comment by kan-bayashi** [comment]
Which configuration did you use?
I think this is I/O problem.
You can increase `num_workers` in config to address this issue.
And if your GPU memory has a room, it is better to increase batch size (or batch bins) in the case of Transformer.

**Comment by ShigekiKarita** [comment]
If you used the default config, batch setting can be problem
https://github.com/espnet/espnet/blob/d8e1bf011c4d791a5898b72f0f3f15eab3c95450/egs2/ami/asr1/conf/tuning/train_asr_transformer.yaml#L28-L29
I recommend to try `numel` and `batch-bins` like librispeech
https://github.com/espnet/espnet/blob/d8e1bf011c4d791a5898b72f0f3f15eab3c95450/egs2/librispeech/asr1/conf/tuning/train_asr_transformer.yaml#L1-L2
because it results in higher GPU utilization, and faster generally. See also https://github.com/espnet/espnet/pull/759#issuecomment-495910831

**Comment by picheny-nyu** [comment]
@kan-bayashi how do I change num_workers? I don't see this in the scripts...?

**Comment by picheny-nyu** [comment]
@ShigekiKarita I ran out of GPU memory. what do I do with the above parameter settings to lower GPU memory? IT looks like I have 10.92 GB available....

**Comment by kamo-naoyuki** [comment]
Please read the documentation about the usage.

**Comment by kamo-naoyuki** [comment]
There are also the iter_time log, so you can distinguish the IO problem and the other easily.

**Comment by picheny-nyu** [comment]
@kamo-naoyuki I did a search in the docs for "num_workers" and could not find it
Maybe the parameter has another name?

**Comment by kan-bayashi** [comment]
You can add `num_workers` arguments in yaml config as follows:
https://github.com/espnet/espnet/blob/d8e1bf011c4d791a5898b72f0f3f15eab3c95450/egs2/jsut/tts1/conf/tuning/train_tacotron2.yaml#L65
(That is the TTS config, but the format is the same).

**Comment by picheny-nyu** [comment]
@kan-bayashi I assume this works for ASR in the esg2 espnet2 recipes?

**Comment by kan-bayashi** [comment]
Yes.

**Comment by picheny-nyu** [comment]
@kan-bayashi I set num_workers to 4. definitely better. Should I increase further? It can be a  12 or 16 CPU machine

**Comment by kan-bayashi** [comment]
It depends on your environment. Please find the suitable value by yourself.

**Comment by kamo-naoyuki** [comment]
The documentation said that all option can be found by --help. We never write the usage for all options.

**Comment by ShigekiKarita** [comment]
[Unlike espnet1](https://espnet.github.io/espnet/apis/espnet_bin.html), espnet2 tools `--help` are not listed in GitHub pages yet. I think we should gather all the information on one doc.
