### ISSUE TITLE
How to do speaker adaption using espnet?

### ISSUE THREAD

**Issue by ymzlygw** [espnet/espnet#2446]
Hi, Firstly thanks for your work. And I want to know how to do speaker adaption using espnet.
I mean, for example, a tts model like tacotron2 is trained using LJSpeech and LJS dataset is a female voice. And I want to use another custom dataset of male voice or different male voice to retrain , and maybe can use the pre_model of tacotron2 so that the voice can change from one type to another.
How to achieve this by using espnet?

**Comment by kan-bayashi** [comment]
I recommend using ESPnet2.
First, make the recipe of your dataset.
https://github.com/espnet/espnet/tree/master/egs2/TEMPLATE/tts1#how-to-make-a-new-recipe-for-my-own-dataset
Then, try finetuning.
https://github.com/espnet/espnet/tree/master/egs2/TEMPLATE/tts1#how-to-finetune-the-pretrained-model
You can download several pretrained models of ESPnet2:
https://github.com/espnet/espnet_model_zoo
Pretrained model list:
https://github.com/espnet/espnet_model_zoo/blob/master/espnet_model_zoo/table.csv

**Comment by kan-bayashi** [comment]
If you have a further question, please re-open this issue.

**Comment by ymzlygw** [comment]
> If you have a further question, please re-open this issue.

Thanks!

**Comment by thehetpandya** [comment]
Hi @kan-bayashi,
I wanted to know how many samples would be sufficient for the model to sound good enough? Also, do the audios need to be of any maximum length. Like while training DCTTS, I came across a problem of keeping the audios to be of 14 secs or smaller. Does that apply here?
