### ISSUE TITLE
Kaldi install question

### ISSUE THREAD

**Issue by ymzlygw** [espnet/espnet#2447]
When i install the kaldi in Step 1's second step:Install tools, I meet errors:
My command line:-------------------------------
~/AI_/kaldi/tools# make -j 1
log:----------------------------------------------
extras/check_dependencies.sh
extras/check_dependencies.sh: automake is not installed.
extras/check_dependencies.sh: autoconf is not installed.
extras/check_dependencies.sh: gfortran is not installed
extras/check_dependencies.sh: neither libtoolize nor glibtoolize is installed
extras/check_dependencies.sh: subversion is not installed
extras/check_dependencies.sh: python2.7 is not installed
extras/check_dependencies.sh: Intel MKL is not installed. Run extras/install_mkl.sh to install it.
 ... You can also use other matrix algebra libraries. For information, see:
 ...   http://kaldi-asr.org/doc/matrixwrap.html
extras/check_dependencies.sh: Some prerequisites are missing; install them using the command:
  sudo apt-get install automake autoconf gfortran libtool subversion python2.7
Makefile:38: recipe for target 'check_required_programs' failed
make: *** [check_required_programs] Error 1

What's this meaning?

**Comment by b-flo** [comment]
Hi,

You're missing some dependencies to build Kaldi. Please read carefully and follow instructions:

```
extras/check_dependencies.sh: Some prerequisites are missing; install them using the command:
sudo apt-get install automake autoconf gfortran libtool subversion python2.7
```

**Comment by ymzlygw** [comment]
> Hi,
> 
> You're missing some dependencies to build Kaldi. Please read carefully and follow instructions:
> 
> ```
> extras/check_dependencies.sh: Some prerequisites are missing; install them using the command:
> sudo apt-get install automake autoconf gfortran libtool subversion python2.7
> ```

Yeah, I have read this, but I install it in anaconda env and I have install python 3.6. But I see the python2.7 install request and get confused. Should I install it?

**Comment by b-flo** [comment]
`Yeah, I have read this, but I install it in anaconda env`

Anaconda environment is used to install ESPnet not Kaldi, this isn't the standard installation : https://espnet.github.io/espnet/installation.html

**Comment by kan-bayashi** [comment]
@ymzlygw If you want to use only ESPnet2, you can skip kaldi installation.
Just cloning kaldi and making symlink is OK.

**Comment by ymzlygw** [comment]
> @ymzlygw If you want to use only ESPnet2, you can skip kaldi installation.
> Just cloning kaldi and making symlink is OK.

Thanks, and I want to know that is kaldi needed for VCC implementation? If not , I can skip that.

**Comment by kan-bayashi** [comment]
> Thanks, and I want to know that is kaldi needed for VCC implementation? If not , I can skip that.

VCC baseline is based on ESPnet1, so kaldi installation is needed.

**Comment by ymzlygw** [comment]
> > Thanks, and I want to know that is kaldi needed for VCC implementation? If not , I can skip that.
> 
> VCC baseline is based on ESPnet1, so kaldi installation is needed.

Thanks, I'll do that.

**Comment by ymzlygw** [comment]
> > Thanks, and I want to know that is kaldi needed for VCC implementation? If not , I can skip that.
> 
> VCC baseline is based on ESPnet1, so kaldi installation is needed.

Hi, I  want to know that for install of kaldi, firstly I create anaconda env and install python 3.6 and pytorch at the begining , then I install the  kaldi and the  ESPnet following the instruction, all these are in the conda env. is  it right?

**Comment by kan-bayashi** [comment]
Kaldi installation is independent from the espnet installation.
https://espnet.github.io/espnet/installation.html
First, you need to install (compile) kaldi.
Then, kaldi binary files are created in kaldi directory.

This is the step 1.
Next, we create the portable conda environment for espnet isntallation.
This is the step 2.

**Comment by ymzlygw** [comment]
> Kaldi installation is independent from the espnet installation.
> https://espnet.github.io/espnet/installation.html
> 
> First, you need to install (compile) kaldi.
> Then, kaldi binary files are created in kaldi directory.
> This is the step 1.
> 
> Next, we create the portable conda environment for espnet isntallation.
> This is the step 2.

oh, I get it. Thanks for your reply!

**Comment by kan-bayashi** [comment]
If you have a further problem, please re-open.
