### ISSUE TITLE
CommonPreprocessor_multi not defined

### ISSUE THREAD

**Issue by ShigekiKarita** [espnet/espnet#2450]
**Describe the bug**

This class is not defined
https://github.com/espnet/espnet/blob/d8e1bf011c4d791a5898b72f0f3f15eab3c95450/espnet2/tasks/enh_asr.py#L41
https://github.com/espnet/espnet/blob/d8e1bf011c4d791a5898b72f0f3f15eab3c95450/espnet2/tasks/enh_asr.py#L242

So I cannot import this module to generate the help doc in sphinx.

**Basic environments:**
- OS information: Linux 5.4.0-42-generic #46~18.04.1-Ubuntu SMP Fri Jul 10 07:21:24 UTC 2020 x86_64
- python version: `3.8.3 (default, May 19 2020, 18:47:26)  [GCC 7.3.0]`
- espnet version: `espnet 0.9.2`
- pytorch version: `pytorch 1.6.0`
- Git hash: `d8e1bf011c4d791a5898b72f0f3f15eab3c95450`
  - Commit date: `Wed Sep 9 08:39:26 2020 -0400`

**Environments from `torch.utils.collect_env`:**
Collecting environment information...
PyTorch version: 1.6.0
Is debug build: No
CUDA used to build PyTorch: 10.2

OS: Ubuntu 18.04.5 LTS
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
CMake version: version 3.17.3

Python version: 3.8
Is CUDA available: Yes
CUDA runtime version: 10.2.89
GPU models and configuration: GPU 0: GeForce GTX 1650 with Max-Q Design
Nvidia driver version: 440.95.01
cuDNN version: Could not collect

Versions of relevant libraries:
[pip3] numpy==1.19.1
[pip3] pytorch-ranger==0.1.1
[pip3] pytorch-wpe==0.0.0
[pip3] torch==1.6.0
[pip3] torch-complex==0.1.2
[pip3] torch-optimizer==0.0.1a15
[pip3] torchaudio==0.6.0
[pip3] torchvision==0.7.0
[conda] blas                      1.0                         mkl  
[conda] cudatoolkit               10.2.89              hfd86e86_1  
[conda] mkl                       2020.2                      256  
[conda] mkl-service               2.3.0            py38he904b0f_0  
[conda] mkl_fft                   1.1.0            py38h23d657b_0  
[conda] mkl_random                1.1.1            py38h0573a6f_0  
[conda] numpy                     1.19.1           py38hbc911f0_0  
[conda] numpy-base                1.19.1           py38hfa32c7d_0  
[conda] pytorch                   1.6.0           py3.8_cuda10.2.89_cudnn7.6.5_0    pytorch
[conda] pytorch-ranger            0.1.1                    pypi_0    pypi
[conda] pytorch-wpe               0.0.0                    pypi_0    pypi
[conda] torch-complex             0.1.2                    pypi_0    pypi
[conda] torch-optimizer           0.0.1a15                 pypi_0    pypi
[conda] torchaudio                0.6.0                    pypi_0    pypi
[conda] torchvision               0.7.0                py38_cu102    pytorch

**To Reproduce**

python -c "import espnet2.tasks.enh_asr"

**Error logs**
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/karita/Documents/repos/espnet/espnet2/tasks/enh_asr.py", line 41, in <module>
    from espnet2.train.preprocessor import CommonPreprocessor_multi
ImportError: cannot import name 'CommonPreprocessor_multi' from 'espnet2.train.preprocessor' (/home/karita/Documents/repos/espnet/espnet2/train/preprocessor.py
```

**Comment by kamo-naoyuki** [comment]
@LiChenda please fix.

**Comment by LiChenda** [comment]
I've made the bug fixing  #2460 , could @shincling also help to check it?
