### ISSUE TITLE
PyTorch Transformer based model into ONNX conversion issue

### ISSUE THREAD

**Issue by nehasoni3** [espnet/espnet#2458]
Hi
I am trying to convert ASR PyTorch Transformer based model into ONNX but
I’m getting error i.e.

 `  TypeError: forward() missing 2 required positional arguments: 'ilens' and 'ys_pad'   `

I am using this code for conversion.
 ` # Export the trained model to ONNX dummy_input = Variable(torch.randn(83,360)) # [83,360] will be the input to the model torch.onnx.export(model, dummy_input, "model.onnx")   `

Do needful.thanks

**Comment by kan-bayashi** [comment]
The log said the reason.
And you cannot convert to ONNX directly since the ASR model has many dynamic computations.
If you want to do it, you need to dive into our codes and refactor them by yourself.
I'll close this issue.

**Comment by nehasoni3** [comment]
What do it mean - refactor the code?
I don't get it.

**Comment by kan-bayashi** [comment]
We do not support the ONNX conversion.
To convert, you need to modify the code by yourself.

**Comment by nehasoni3** [comment]
> We do not support the ONNX conversion.
> To convert, you need to modify the code by yourself.

Ok. But how?

**Comment by kan-bayashi** [comment]
I have no clear answer for your question because a lot of parts are needed to be modified.
That is not a simple modification. I think we need to rewrite the most of parts to be the fixed length calculation.

**Comment by nehasoni3** [comment]
@kan-bayashi 

> The log said the reason.
> And you cannot convert to ONNX directly since the ASR model has many dynamic computations.
> If you want to do it, you need to dive into our codes and refactor them by yourself.
> I'll close this issue.

Will you please help me to understand this log msg.

And how can I pass fbank batch, their lengths, and output token batch to that torch.rand().

**Comment by kan-bayashi** [comment]
Your request is out of our support.
Please learn the basic of ONNX conversion by yourself.
