### ISSUE TITLE
about fastspeech-duration's length

### ISSUE THREAD

**Issue by HeYingnan** [espnet/espnet#2463]
I used python to read the content of duration (generated by teacher model transformer), and I found that the length of duration is one more than the length of text. I want to know how to use duration and why its length is one more than the length of text? 
thank you.
em, it is a bit difficult for me to read the source code, thanks!

**Comment by kan-bayashi** [comment]
+1 for `<eos>` symbol.

**Comment by HeYingnan** [comment]
> +1 for `<eos>` symbol.

so, if i want to use the duration, i can do this: for example, a text "ESP", when use "char" , the input is "E S P",and the duration is d = [2, 3, 4, 2],so i can do this d[0]*'E', d[1]*'S', d[2]*'P',is it right? i just use 'E' 'S' 'P' for the net abstract representation.

**Comment by kan-bayashi** [comment]
Do you want to remove the `<eos>`?
In your case, expanded sequence will be like `eessspppp<eos><eos>`.
In my implementation `<eos>` is concatenated in the network.

**Comment by HeYingnan** [comment]
i understand the meaning of the duration now!thank you, because another open source code I first looked at did not use <eos>, but that code's duration is not accurate, the result of his model training is not good, so I want to try it with your duration here, OK, you have answered my question, thanks again! Wish you all the best！

**Comment by kan-bayashi** [comment]
If you try FastSpeech with ESPnet, I recommend using ESPnet2.
https://github.com/espnet/espnet/tree/master/egs2/TEMPLATE/tts1
It supports both FastSpeech and FastSpeech2.

**Comment by HeYingnan** [comment]
> If you try FastSpeech with ESPnet, I recommend using ESPnet2.
> https://github.com/espnet/espnet/tree/master/egs2/TEMPLATE/tts1
> It supports both FastSpeech and FastSpeech2.

OK,thanks!
