### ISSUE TITLE
No tools/activate_python.sh but called from egs/wsj/asr1/path.sh

### ISSUE THREAD

**Issue by yunigma** [espnet/espnet#2474]
Hello!
In the latest release, the `/tools/activate_python.sh` script is called in the line 10 in `egs/wsj/asr1/path.sh ` but it is not in the `tools` folder:
```
export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:$MAIN_ROOT/tools/chainer_ctc/ext/warp-ctc/build
. "${MAIN_ROOT}"/tools/activate_python.sh && . "${MAIN_ROOT}"/tools/extra_path.sh
```
So, currently, I am using the previous approach.
Best, Yulia

**Comment by kamo-naoyuki** [comment]
You must create it by yourself. See documentation.

**Comment by yunigma** [comment]
Thank you!

**Comment by kamo-naoyuki** [comment]
Here: https://espnet.github.io/espnet/installation.html#step-2-installation-espnet

Recently I updated some installation flows, so if you have already installled espnet and pull the latest repo, you may encounter such issue...

**Comment by yunigma** [comment]
Thank you. Yes, I have pulled the latest version today. It helped me with another old issue but brought some new ones... I ll check my instalytion again
