### ISSUE TITLE
ESPnet Install Question

### ISSUE THREAD

**Issue by ymzlygw** [espnet/espnet#2479]
Hi, I am confused at the "4. Setup Python environment" of Step 2 in Installation ESPnet. 
Before this , I have finished substep 1-3 of Step 2 in the conda environment that I created. In the conda env, I have installed python 3.6 when creating conda env, so  I  am confused of following part and don't know how to do next:
_____________________________________________________________________________________________________
Option A) Setup Anaconda environment

$ cd <espnet-root>/tools
$ ./setup_anaconda.sh [output-dir-name] [conda-env-name] [python-version]
If [output-dir-name] is omitted, venv is generated. If [conda-env-name] and [python-version] are omitted, the root environment and the default Python of Anaconda are selected respectively.

This script tries to create a new miniconda at venv if it doesn’t exist. If you already have Anaconda and you’ll use it then,

$ cd <espnet-root>/tools
$ CONDA_TOOLS_DIR=$(dirname ${CONDA_EXE})/..
$ ./setup_anaconda.sh ${CONDA_TOOLS_DIR} [conda-env-name] [python-version]
__________________________________________________________________________________________________________
Should I need to install python and create conda env again using this command?
$ cd <espnet-root>/tools
$ CONDA_TOOLS_DIR=$(dirname ${CONDA_EXE})/..
$ ./setup_anaconda.sh ${CONDA_TOOLS_DIR} [conda-env-name] [python-version]

if so , [conda-env-name] [python-version] name is ?

**Comment by kamo-naoyuki** [comment]
[conda-env-name] [python-version] is is the name to be created and its python version. As document says all, if it doesn't exist, a new environment is created.

**Comment by ymzlygw** [comment]
> [conda-env-name] [python-version] is is the name to be created and its python version. As document says all, if it doesn't exist, a new environment is created.

I mean, now I am in an exiting conda env with python 3.6 . Do I still need to do  this step "4. Setup Python environment" ?

**Comment by kamo-naoyuki** [comment]
Yes of course

**Comment by kamo-naoyuki** [comment]
As the documentation says all, again.

**Comment by ymzlygw** [comment]
> Yes of course



> [conda-env-name] [python-version] is is the name to be created and its python version. As document says all, if it doesn't exist, a new environment is created.

So now my exiting installed conda env's name is "espnet ",and python version is 3.6.6. then in this conda env,  I try to create another conda env and python version, is it right ?   and [conda-env-name] [python-version] here should also be different from exiting conda env name , yes?

**Comment by kamo-naoyuki** [comment]
No. First of all, you existing anaconda is totally not related to espnet, so we can't expect the usage. If you'll use the existing one in espnet, use it as it is. It's your choice.

**Comment by ymzlygw** [comment]
> No. First of all, you existing anaconda is totally not related to espnet, so we can't expect the usage. If you'll use the existing one in espnet, use it as it is. It's your choice.

Sorry , I may be confused of  "4. Setup Python environment"  's meaning. If I do this step in exiting conda env is not related to espnet, I'll do it in base linux environment. And then "4. Setup Python environment" this step will help me first create a conda env just like command "conda create -n name python=3.6" . This is the right installation process that begin in base linux environment,right?

**Comment by ymzlygw** [comment]
> No. First of all, you existing anaconda is totally not related to espnet, so we can't expect the usage. If you'll use the existing one in espnet, use it as it is. It's your choice.

Thanks for your reply. I do this in base linux env and it exactly create a new conda env .So I shouldn't install it in exiting conda env.

**Comment by kamo-naoyuki** [comment]
Hmm, I'm not sure what confused you. Could you explain me? I'll update the documentation if necessary.

**Comment by ymzlygw** [comment]
> Hmm, I'm not sure what confused you. Could you explain me? I'll update the documentation if necessary.

Because in the beginning of ESPnet installation, I have create a conda env and activate it ,but in fact, this step is done in substep 4. I should begin in a base linux environment. That's the question that confuse me. Now ,It's ok.

**Comment by ymzlygw** [comment]
> Hmm, I'm not sure what confused you. Could you explain me? I'll update the documentation if necessary.

And  , I met error after that, please help . The following is the command and the Message:
________________________________________________________________________________________________________________________
(espnet_env) root@d6fbba8aac2b:~/AI_/espnet/tools# make TH_VERSION=1.0.0
Python 3.6.6 :: Anaconda, Inc.
[ -n "/usr/local/cuda-9.0" ] || { echo -e "Error: CUDA_HOME is not set.\n    $ . ./setup_cuda_env.sh <cuda-root>"; exit 1; }
CUDA_VERSION=9.0
. ./activate_python.sh && python3 check_pytorch_cuda_compatibility.py 1.0.0 9.0 || { echo "Change TH_VERSION or CUDA_VERSION"; exit 1; }
9.0
PYTHON=/root/anaconda3/envs/espnet_env/bin/python3
PYTHON_VERSION=
IS_CONDA=0
USE_PIP=
TH_VERSION=1.0.0
CONDA_PYTORCH=pytorch=1.0.0 cudatoolkit=9.0
PIP_PYTORCH=torch==1.0.0 -f https://download.pytorch.org/whl/cu90/torch_stable.html
CHAINER_VERSION=6.0.0
PIP_CHAINER=chainer==6.0.0
NO_CUPY=
. ./activate_python.sh && conda install -y pytorch=1.0.0 cudatoolkit=9.0 -c pytorch
Collecting package metadata (current_repodata.json): done
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.8.3
  latest version: 4.8.4

Please update conda by running

    $ conda update -n base -c defaults conda



## Package Plan ##

  environment location: /root/anaconda3/envs/espnet_env

  added / updated specs:
    - cudatoolkit=9.0
    - pytorch=1.0.0


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    cudatoolkit-9.0            |       h13b8566_0       237.0 MB  defaults
    ------------------------------------------------------------
                                           Total:       237.0 MB

The following NEW packages will be INSTALLED:

  blas               pkgs/main/linux-64::blas-1.0-mkl
  cudatoolkit        pkgs/main/linux-64::cudatoolkit-9.0-h13b8566_0
  intel-openmp       pkgs/main/linux-64::intel-openmp-2020.2-254
  mkl                pkgs/main/linux-64::mkl-2020.2-256
  mkl-service        pkgs/main/linux-64::mkl-service-2.3.0-py36he904b0f_0
  mkl_fft            pkgs/main/linux-64::mkl_fft-1.1.0-py36h23d657b_0
  mkl_random         pkgs/main/linux-64::mkl_random-1.1.1-py36h0573a6f_0
  ninja              pkgs/main/linux-64::ninja-1.10.1-py36hfd86e86_0
  numpy              pkgs/main/linux-64::numpy-1.19.1-py36hbc911f0_0
  numpy-base         pkgs/main/linux-64::numpy-base-1.19.1-py36hfa32c7d_0
  pytorch            pytorch/linux-64::pytorch-1.0.0-py3.6_cuda9.0.176_cudnn7.4.1_1



Downloading and Extracting Packages
cudatoolkit-9.0      | 237.0 MB  | ###################################################################################### | 100% 
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
touch pytorch.done
. ./activate_python.sh && { command -v cmake || conda install -y cmake; }
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.8.3
  latest version: 4.8.4

Please update conda by running

    $ conda update -n base -c defaults conda



## Package Plan ##

  environment location: /root/anaconda3/envs/espnet_env

  added / updated specs:
    - cmake


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    cmake-3.12.2               |       h52cb24c_0         5.6 MB  defaults
    rhash-1.3.6                |       hb7f436b_0         149 KB  defaults
    ------------------------------------------------------------
                                           Total:         5.7 MB

The following NEW packages will be INSTALLED:

  bzip2              pkgs/main/linux-64::bzip2-1.0.8-h7b6447c_0
  cmake              pkgs/main/linux-64::cmake-3.12.2-h52cb24c_0
  expat              pkgs/main/linux-64::expat-2.2.9-he6710b0_2
  libcurl            pkgs/main/linux-64::libcurl-7.61.1-heec0ca6_0
  libssh2            pkgs/main/linux-64::libssh2-1.8.0-h9cfc8f7_4
  rhash              pkgs/main/linux-64::rhash-1.3.6-hb7f436b_0



Downloading and Extracting Packages
cmake-3.12.2         | 5.6 MB    | ###################################################################################### | 100% 
rhash-1.3.6          | 149 KB    | ###################################################################################### | 100% 
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
touch cmake.done
. ./activate_python.sh && { command -v flac || conda install -y libflac -c conda-forge; }
Collecting package metadata (current_repodata.json): done
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.8.3
  latest version: 4.8.4

Please update conda by running

    $ conda update -n base -c defaults conda



## Package Plan ##

  environment location: /root/anaconda3/envs/espnet_env

  added / updated specs:
    - libflac


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    openssl-1.0.2u             |       h516909a_0         3.2 MB  conda-forge
    ------------------------------------------------------------
                                           Total:         3.2 MB

The following NEW packages will be INSTALLED:

  gettext            conda-forge/linux-64::gettext-0.19.8.1-hc5be6a0_1002
  libflac            conda-forge/linux-64::libflac-1.3.3-he1b5a44_0
  libogg             conda-forge/linux-64::libogg-1.3.2-h516909a_1002
  python_abi         conda-forge/linux-64::python_abi-3.6-1_cp36m

The following packages will be SUPERSEDED by a higher-priority channel:

  ca-certificates    pkgs/main::ca-certificates-2020.7.22-0 --> conda-forge::ca-certificates-2020.6.20-hecda079_0
  certifi               pkgs/main::certifi-2020.6.20-py36_0 --> conda-forge::certifi-2020.6.20-py36h9f0ad1d_0
  openssl              pkgs/main::openssl-1.0.2u-h7b6447c_0 --> conda-forge::openssl-1.0.2u-h516909a_0



Downloading and Extracting Packages
openssl-1.0.2u       | 3.2 MB    | ###################################################################################### | 100% 
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
touch flac.done
. ./activate_python.sh && { command -v ffmpeg || conda install -y ffmpeg -c conda-forge; }
Collecting package metadata (current_repodata.json): done
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.8.3
  latest version: 4.8.4

Please update conda by running

    $ conda update -n base -c defaults conda



## Package Plan ##

  environment location: /root/anaconda3/envs/espnet_env

  added / updated specs:
    - ffmpeg


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    libpng-1.6.37              |       hed695b0_2         359 KB  conda-forge
    ------------------------------------------------------------
                                           Total:         359 KB

The following NEW packages will be INSTALLED:

  ffmpeg             conda-forge/linux-64::ffmpeg-4.3.1-h167e202_0
  freetype           conda-forge/linux-64::freetype-2.10.2-he06d7ca_0
  gmp                conda-forge/linux-64::gmp-6.2.0-he1b5a44_2
  gnutls             conda-forge/linux-64::gnutls-3.6.13-h79a8f9a_0
  lame               conda-forge/linux-64::lame-3.100-h14c3975_1001
  libiconv           conda-forge/linux-64::libiconv-1.16-h516909a_0
  libpng             conda-forge/linux-64::libpng-1.6.37-hed695b0_2
  nettle             conda-forge/linux-64::nettle-3.4.1-h1bed415_1002
  openh264           conda-forge/linux-64::openh264-2.1.1-h8b12597_0
  x264               conda-forge/linux-64::x264-1!152.20180806-h14c3975_0



Downloading and Extracting Packages
libpng-1.6.37        | 359 KB    | ###################################################################################### | 100% 
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
touch ffmpeg.done
. ./activate_python.sh && { command -v sox || conda install -y sox -c conda-forge; }
/usr/bin/sox
touch sox.done
. ./activate_python.sh && { python3 -c "from ctypes.util import find_library as F; assert F('sndfile') is not None" || conda install -y libsndfile=1.0.28 -c conda-forge; }
touch sndfile.done
touch conda_packages.done
. ./activate_python.sh && ./installers/install_warp-ctc.sh
cuda_version=90
Collecting warpctc-pytorch10-cuda90
  Downloading warpctc_pytorch10_cuda90-0.1.3-cp36-cp36m-manylinux1_x86_64.whl (2.4 MB)
     |################################| 2.4 MB 7.2 MB/s 
Installing collected packages: warpctc-pytorch10-cuda90
Successfully installed warpctc-pytorch10-cuda90-0.1.3
touch warp-ctc.done
. ./activate_python.sh && ./installers/install_warp-transducer.sh
Cloning into 'warp-transducer'...
remote: Enumerating objects: 11, done.
remote: Counting objects: 100% (11/11), done.
remote: Compressing objects: 100% (10/10), done.
remote: Total 905 (delta 1), reused 5 (delta 1), pack-reused 894
Receiving objects: 100% (905/905), 248.13 KiB | 486.00 KiB/s, done.
Resolving deltas: 100% (462/462), done.
-- The C compiler identification is GNU 7.5.0
-- The CXX compiler identification is GNU 7.5.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found CUDA: /usr/local/cuda-9.0 (found version "9.0") 
-- cuda found TRUE
-- Building shared library with GPU support
-- Configuring done
-- Generating done
-- Build files have been written to: /root/AI_/espnet/tools/warp-transducer/build
make[1]: Entering directory '/root/AI_/espnet/tools/warp-transducer/build'
make[2]: Entering directory '/root/AI_/espnet/tools/warp-transducer/build'
make[3]: Entering directory '/root/AI_/espnet/tools/warp-transducer/build'
[  7%] Building NVCC (Device) object CMakeFiles/warprnnt.dir/src/warprnnt_generated_rnnt_entrypoint.cu.o
In file included from /usr/local/cuda-9.0/include/host_config.h:50:0,
                 from /usr/local/cuda-9.0/include/cuda_runtime.h:78,
                 from <command-line>:0:
/usr/local/cuda-9.0/include/crt/host_config.h:119:2: error: #error -- unsupported GNU version! gcc versions later than 6 are not supported!
 #error -- unsupported GNU version! gcc versions later than 6 are not supported!
  ^~~~~
CMake Error at warprnnt_generated_rnnt_entrypoint.cu.o.cmake:219 (message):
  Error generating
  /root/AI_/espnet/tools/warp-transducer/build/CMakeFiles/warprnnt.dir/src/./warprnnt_generated_rnnt_entrypoint.cu.o


CMakeFiles/warprnnt.dir/build.make:63: recipe for target 'CMakeFiles/warprnnt.dir/src/warprnnt_generated_rnnt_entrypoint.cu.o' failed
make[3]: *** [CMakeFiles/warprnnt.dir/src/warprnnt_generated_rnnt_entrypoint.cu.o] Error 1
make[3]: Leaving directory '/root/AI_/espnet/tools/warp-transducer/build'
CMakeFiles/Makefile2:72: recipe for target 'CMakeFiles/warprnnt.dir/all' failed
make[2]: *** [CMakeFiles/warprnnt.dir/all] Error 2
make[2]: Leaving directory '/root/AI_/espnet/tools/warp-transducer/build'
Makefile:129: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/root/AI_/espnet/tools/warp-transducer/build'
Makefile:159: recipe for target 'warp-transducer.done' failed
make: *** [warp-transducer.done] Error 2
(espnet_env) root@d6fbba8aac2b:~/AI_/espnet/tools# nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2017 NVIDIA Corporation
Built on Fri_Sep__1_21:08:03_CDT_2017
Cuda compilation tools, release 9.0, V9.0.176
(espnet_env) root@d6fbba8aac2b:~/AI_/espnet/tools# . ./activate_python.sh; python3 check_install.py
INFO: python version = 3.6.6 |Anaconda, Inc.| (default, Oct  9 2018, 12:34:16) 
[GCC 7.3.0]
INFO: pytorch version = 1.0.0
INFO: library availableness check start.
INFO: # libraries to be checked = 8
WARNING: --> cupy is not installed.
###### Raw Error ######
Traceback (most recent call last):
  File "check_install.py", line 95, in main
    importlib.import_module(name)
  File "/root/anaconda3/envs/espnet_env/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'cupy'
#######################
INFO: --> warpctc_pytorch is installed.
WARNING: --> espnet is not installed.
###### Raw Error ######
Traceback (most recent call last):
  File "check_install.py", line 95, in main
    importlib.import_module(name)
  File "/root/anaconda3/envs/espnet_env/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'espnet'
#######################
WARNING: --> kaldiio is not installed.
###### Raw Error ######
Traceback (most recent call last):
  File "check_install.py", line 95, in main
    importlib.import_module(name)
  File "/root/anaconda3/envs/espnet_env/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'kaldiio'
#######################
WARNING: --> matplotlib is not installed.
###### Raw Error ######
Traceback (most recent call last):
  File "check_install.py", line 95, in main
    importlib.import_module(name)
  File "/root/anaconda3/envs/espnet_env/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'matplotlib'
#######################
WARNING: --> chainer is not installed.
###### Raw Error ######
Traceback (most recent call last):
  File "check_install.py", line 95, in main
    importlib.import_module(name)
  File "/root/anaconda3/envs/espnet_env/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'chainer'
#######################
WARNING: --> chainer_ctc is not installed.
###### Raw Error ######
Traceback (most recent call last):
  File "check_install.py", line 95, in main
    importlib.import_module(name)
  File "/root/anaconda3/envs/espnet_env/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'chainer_ctc'
#######################
WARNING: --> warprnnt_pytorch is not installed.
###### Raw Error ######
Traceback (most recent call last):
  File "check_install.py", line 95, in main
    importlib.import_module(name)
  File "/root/anaconda3/envs/espnet_env/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'warprnnt_pytorch'
#######################
INFO: library availableness check done.
INFO: 1 / 8 libraries are correctly installed.
WARNING: please try to setup again and then re-run this script.
_____________________________________________________________________________________________________________

**Comment by kamo-naoyuki** [comment]
Read error. GCC version requirements. Please solve installation errors by yourself.
