### ISSUE TITLE
wrong parameter for tar -d

### ISSUE THREAD

**Issue by dqqcasia** [espnet/espnet#2485]
stage -1: Data Download
espnet/data/MUSTC_v1.0/MUSTC_v1.0_en-de.tar.gz exists and appears to be complete.
tar: You may not specify more than one '-Acdtrux', '--delete' or  '--test-label' option
Try 'tar --help' or 'tar --usage' for more information.
local/download_and_untar.sh: error un-tarring archive espnet/data/MUSTC_v1.0/MUSTC_v1.0_en-de.tar.gz

**Comment by sw005320** [comment]
Could you give us more information?
Which recipe are you using?
It would be better if you follow our bag report template to some extent.

**Comment by kamo-naoyuki** [comment]
Anyway, such a bug can be fixed easily for you, but it's hart for the other people without running the script. Please debug by yourself before reporting a as a bug.
I recommend you writing `set -x` in run.sh.
