### ISSUE TITLE
Voice conversion instructions?

### ISSUE THREAD

**Issue by Mikefizzy** [espnet/espnet#2487]
I cant seem to find any instructions on how to train/use the voice conversion model. I really really need this.

**Comment by b-flo** [comment]
Hi,

I guess you mean this: https://github.com/espnet/espnet/blob/master/egs/vcc20/README.md?

**Comment by sw005320** [comment]
We also have another example in https://github.com/espnet/espnet/tree/master/egs/arctic/vc1
We don't' prepare a particular demonstration (like a colab-based one) of voice conversion, but you can get some audio examples from https://github.com/espnet/espnet#vc-results

I also added @unilight to this issue.

**Comment by Mikefizzy** [comment]
Do you plan on making a demonstration in the future?

**Comment by sw005320** [comment]
@unilight, what do you think?
I think it is good in general, but for making a demonstration, espent2 is better.

**Comment by unilight** [comment]
I am not so familiar with ESPnet2, but I think @kan-bayashi is working on ESPnet2 based VC recipes. Maybe he can do it...?
I am a little busy for ICASSP submission recently, but I can think about preparing it after the deadline.

**Comment by shehrum** [comment]
Hi guys, is there any follow up on the collab tutorial for Voice conversion based on ESPnet2?

**Comment by ArkhamImp** [comment]
I think I can help with the demo for VC if you need.

**Comment by sw005320** [comment]
@kan-bayashi, what do you think?
I remember that you were working on VC in espnet2.
It would be great if you share your status.

**Comment by nikich340** [comment]
Any news?
