### ISSUE TITLE
'NgramPartScorer' object has no attribute 'batch_init_state'

### ISSUE THREAD

**Issue by cosmo1995** [espnet/espnet#2495]
Does batch decoding support ngram lm?

**Comment by Cescfangs** [comment]
https://github.com/espnet/espnet/blob/e83d24bfc1ff173de8ba0af70dcafcec3e4eaf05/espnet/nets/scorers/ngram.py#L80

I think it should inherit from `BatchPartialScorerInterface`  @qmpzzpmq ?

**Comment by 3139725181** [comment]
how to solve it...

**Comment by qmpzzpmq** [comment]
@Cescfangs no

**Comment by qmpzzpmq** [comment]
> how to solve it...

ngram right now doesn't support batch

**Comment by Newzq** [comment]
> 如何解决...

batch_size =0
