### ISSUE TITLE
Questions about espnet  espnet2 model compatibility

### ISSUE THREAD

**Issue by Ella77** [espnet/espnet#2507]
First, always thank you for improving this project. I am curious if the espnet model is compatible with the espnet2 model.
If possible, I want to make my own fastspeech2 recipe by using teacher tacotron2 model pretrained with same data, but my issue is that pretrained exp results are all based on espnet v1 (data.json, config.yaml, model.loss.best or snapshot) 

Should I pretrain tacotron2 model again from espnet2 ? 

I'm stuck with generating durations process([stage 7 ](https://github.com/espnet/espnet/tree/master/egs2/TEMPLATE/tts1#fastspeech-training )

```
./tts.sh \
     --train_config conf/tuning/train_tacotron2.yaml \  
     --tts_stats_dir exp/tts_stats_for_fastspeech2 \
     --write_collected_feats true \
    --train_args "--pretrain_path V1_TACOTRON/model.loss.best --pretrain_key null". 
```
 
 Neither    `tts.sh --tts_exp V1_TACOTRON (that contains config.yml, token_list) ` or code above works for me 

I tried to add some argument in training.conf file but there is error that somethings like token_list, odim, normalize ... are missing in namespace ([ somethings in task/tts.py](https://github.com/espnet/espnet/blob/180af1103997d4eb42ece85cdb92b049db5570c7/espnet2/tasks/tts.py#L93))

Is there any simple solution? I will appreciate with your help.

**Comment by kan-bayashi** [comment]
Unfortunately, we do not provide the compatibility between espnet1 and espnet2.
The most simple solution is to train Tacotron2 in ESPnet2.

If you use existing recipe, we provide pretrained models.
https://github.com/espnet/espnet_model_zoo

**Comment by Ella77** [comment]
> Unfortunately, we do not provide the compatibility between espnet1 and espnet2.
> The most simple solution is to train Tacotron2 in ESPnet2.
> 
> If you use existing recipe, we provide pretrained models.
> https://github.com/espnet/espnet_model_zoo

Thanks!
