### ISSUE TITLE
Docker build error

### ISSUE THREAD

**Issue by muramasa2** [espnet/espnet#2508]
# error content
 I got the error while building docker image
I run these commands.
- command
```
cd docker
./build.sh fully_local cpu
```
but the error was occared.
- the error sentence
```
Step 14/16 : RUN if [ -z "$( nvcc -V )" ]; then         echo "Build without CUDA" &&         MY_OPTS="CUPY_VERSION=";     else         echo "Build with CUDA" &&         export CFLAGS="-I${CUDA_HOME}/include ${CFLAGS}" &&         MY_OPTS="CUDA_VERSION=${CUDA_VER}" &&         sed -i 's|_install.py|_install.py --no-cuda|g' Makefile &&         sed -i 's|which nvidia-smi|which nvcc|g' Makefile;      fi;     if [ "${CUDA_VER}" = "10.1" ]; then         MY_OPTS="${MY_OPTS} TH_VERSION=1.3.1";      fi;     echo "Make with options ${MY_OPTS}";     make KALDI=/kaldi ${MY_OPTS}
 ---> Running in 59da3674b2df
/bin/sh: 1: nvcc: not found
Build without CUDA
Make with options CUPY_VERSION=
expr: syntax error
test -f kaldi/egs/wsj/s5/utils/parse_options.sh || { echo -e "Error: Put Kaldi here!\n    $ ln -s <kaldi-root> kaldi"; exit 1; }
-e Error: Put Kaldi here!
    $ ln -s <kaldi-root> kaldi
Makefile:65: recipe for target 'kaldi' failed
make: *** [kaldi] Error 1
The command '/bin/sh -c if [ -z "$( nvcc -V )" ]; then         echo "Build without CUDA" &&         MY_OPTS="CUPY_VERSION=";     else         echo "Build with CUDA" &&         export CFLAGS="-I${CUDA_HOME}/include ${CFLAGS}" &&         MY_OPTS="CUDA_VERSION=${CUDA_VER}" &&         sed -i 's|_install.py|_install.py --no-cuda|g' Makefile &&         sed -i 's|which nvidia-smi|which nvcc|g' Makefile;      fi;     if [ "${CUDA_VER}" = "10.1" ]; then         MY_OPTS="${MY_OPTS} TH_VERSION=1.3.1";      fi;     echo "Make with options ${MY_OPTS}";     make KALDI=/kaldi ${MY_OPTS}' returned a non-zero code: 2
```

# My environment:
OS: macOS Catalina. (I also tried on Ubuntu18.04, but the error was also happend.)

# I followed the error message, but other error occared.
I tried to add the command to Dokcerfile, but other error occard.
- added the command to `docker/prebuilt/local/Dockerfile`
```
RUN ln -s /kaldi kaldi
```

- another error
```
Step 15/17 : RUN if [ -z "$( nvcc -V )" ]; then         echo "Build without CUDA" &&         MY_OPTS="CUPY_VERSION=";     else         echo "Build with CUDA" &&         export CFLAGS="-I${CUDA_HOME}/include ${CFLAGS}" &&         MY_OPTS="CUDA_VERSION=${CUDA_VER}" &&         sed -i 's|_install.py|_install.py --no-cuda|g' Makefile &&         sed -i 's|which nvidia-smi|which nvcc|g' Makefile;      fi;     if [ "${CUDA_VER}" = "10.1" ]; then         MY_OPTS="${MY_OPTS} TH_VERSION=1.3.1";      fi;     echo "Make with options ${MY_OPTS}";     make KALDI=/kaldi ${MY_OPTS}
 ---> Running in fabc99f97da5
Build without CUDA
Make with options CUPY_VERSION=
/bin/sh: 1: nvcc: not found
expr: syntax error
test -f activate_python.sh || { echo "Error: Run ./setup_python.sh or ./setup_anaconda.sh"; exit 1; }
Error: Run ./setup_python.sh or ./setup_anaconda.sh
Makefile:68: recipe for target 'activate_python.sh' failed
make: *** [activate_python.sh] Error 1
The command '/bin/sh -c if [ -z "$( nvcc -V )" ]; then         echo "Build without CUDA" &&         MY_OPTS="CUPY_VERSION=";     else         echo "Build with CUDA" &&         export CFLAGS="-I${CUDA_HOME}/include ${CFLAGS}" &&         MY_OPTS="CUDA_VERSION=${CUDA_VER}" &&         sed -i 's|_install.py|_install.py --no-cuda|g' Makefile &&         sed -i 's|which nvidia-smi|which nvcc|g' Makefile;      fi;     if [ "${CUDA_VER}" = "10.1" ]; then         MY_OPTS="${MY_OPTS} TH_VERSION=1.3.1";      fi;     echo "Make with options ${MY_OPTS}";     make KALDI=/kaldi ${MY_OPTS}' returned a non-zero code: 2
```
After that, I tried to fix more following the error message, but error was still existed.

- added the command to `docker/prebuilt/local/Dockerfile`
```
RUN ./setup_python.sh $(which python3)
```

- another error
```
Step 15/18 : RUN ./setup_python.sh $(which python3)
 ---> Running in 83f7d133da5d
/usr/bin/pip3 doesn't exist.
The command '/bin/sh -c ./setup_python.sh $(which python3)' returned a non-zero code: 1
```
# I tried to fix and build was successed but installing ESPNet was imcomplete

- added the command to `docker/prebuilt/local/Dockerfile`
```
RUN ./setup_anaconda.sh
```

After that, building images is sccessed with no error.
but there are not all of content in ESPNet
e.g. espnet/espnet, espnet/utils and espnet/egs etc. are not existed.

```
ls espnet
```
```
CONTRIBUTING.md  README.md  doc   espnet.egg-info  setup.cfg  test_utils
LICENSE          ci         egs2  espnet2          setup.py   tools
```

**If someone knows how to fix it, please advice me.**

**Comment by Fhrozen** [comment]
@muramasa2 THe problem is that the docker was not updated for the new environment of ESPnet.
It has been new changes in the installation.
I will upload the fixes for all docker containers.

**Comment by muramasa2** [comment]
@Fhrozen I appreciate your support, thanks.

**Comment by Fhrozen** [comment]
@muramasa2, Please try to download/pull the updated version of docker.
I checked using local build, and have no problem. 
Let me know if there is any additional issue.

**Comment by muramasa2** [comment]
@Fhrozen Thank you for your response.
I'll check it.

**Comment by muramasa2** [comment]
@Fhrozen 
Now I checked the commit.
But additional issue still exists.

I tried the command in accodance with the official Doc(https://espnet.github.io/espnet/docker.html)
- My Environment
```
OS: Ubuntu18.04
GPU: Tesla V100
Driver Version: 440.33.01
Docker version: 19.03.9
ESPNet version: commit 01eaefef7698453d3c6497c17ba679c98e9f5f85 (latest commit)
```

- run the command
```
./build.sh local 10.0
```
- the error
```
Step 14/16 : RUN if [ -z "$( which nvcc )" ]; then         echo "Build without CUDA" &&         MY_OPTS='CUPY_VERSION=""  TH_VERSION=1.6.0';     else         echo "Build with CUDA" &&         sed -i '200s|install.py|install.py --no-cuda --no-cupy |' Makefile &&         export CFLAGS="-I${CUDA_HOME}/include ${CFLAGS}" &&         MY_OPTS="CUDA_VERSION=${CUDA_VER}" &&         . ./setup_cuda_env.sh /usr/local/cuda;      fi;     if [ "${CUDA_VER}" = "10.1" ]; then         MY_OPTS="${MY_OPTS} TH_VERSION=1.6.0";      fi;     echo "Make with options ${MY_OPTS}" &&     ln -s /kaldi ./ &&     ./setup_anaconda.sh /miniconda espnet 3.7.4 &&     make KALDI=/kaldi ${MY_OPTS}
 ---> Running in 0247fc6775da
Build with CUDA
Usage: /bin/sh CUDA_HOME [NCCL_HOME]
Make with options CUDA_VERSION=10.0

...

. ./activate_python.sh &&  ./installers/install_warp-rnnt.sh 10.0
Cloning into 'warp-rnnt'...
No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'
Traceback (most recent call last):
  File "setup.py", line 22, in <module>
    raise Exception("CPU version is not implemented")
Exception: CPU version is not implemented
Makefile:160: recipe for target 'warp-transducer.done' failed
make: *** [warp-transducer.done] Error 1
The command '/bin/sh -c if [ -z "$( which nvcc )" ]; then         echo "Build without CUDA" &&         MY_OPTS='CUPY_VERSION=""  TH_VERSION=1.6.0';     else         echo "Build with CUDA" &&         sed -i '200s|install.py|install.py --no-cuda --no-cupy |' Makefile &&         export CFLAGS="-I${CUDA_HOME}/include ${CFLAGS}" &&         MY_OPTS="CUDA_VERSION=${CUDA_VER}" &&         . ./setup_cuda_env.sh /usr/local/cuda;      fi;     if [ "${CUDA_VER}" = "10.1" ]; then         MY_OPTS="${MY_OPTS} TH_VERSION=1.6.0";      fi;     echo "Make with options ${MY_OPTS}" &&     ln -s /kaldi ./ &&     ./setup_anaconda.sh /miniconda espnet 3.7.4 &&     make KALDI=/kaldi ${MY_OPTS}' returned a non-zero code: 2
```

Now I also try to local build without GPU.
And I'll also try to rollback your commit 02d65ddb96a338e2275ccb67a8dd1fb2e800d311 and retry it in order to check whether or not the latest commit might create the error.

If you have some idea to fix it, please let me know.

**Comment by Fhrozen** [comment]
Let me check, because when I built the containers, this error wasn't displayed

**Comment by Fhrozen** [comment]
First, I will recommend you to delete all images from you env.
use `docker rmi $(docker images -aq)`, to download the new containers

**Comment by muramasa2** [comment]
Thank you for your advice, but I have already tried to do `docker rmi $(docker images -aq)` before running the command `./build.sh local 10.0`.
But error occared...

I'm not sure but perhaps the commit (120099f9c3440d8528928cdac6bea7c30075f582) is related to Warp rnnt (it's later than your commit).
and the error is also related to Warp rnnt , so I think the commit might cause the error.
I'll rollback from latest commit to your commit and retry it.

**Comment by Fhrozen** [comment]
When u use ./build local, it uses the prebuilt container `cuda-10.0` to build the new espnet.
In case u want to build from scratch, then you can use `./build.sh fully_local 10.0`

**Comment by muramasa2** [comment]
I see, so I'll also try to do it and after that I'll let you know how is the result.
Thank you.

**Comment by muramasa2** [comment]
Now I tried to build image without GPU, it was finished without some error but installing ESPNet was imcomplete
There are still not all of content in ESPNet
e.g. espnet/espnet, espnet/utils and espnet/egs etc. are not existed.

ls espnet
CONTRIBUTING.md  README.md  doc   espnet.egg-info  setup.cfg  test_utils
LICENSE          ci         egs2  espnet2          setup.py   tools

**Comment by Fhrozen** [comment]
Yes, these folders are deleted before installing or finishing the container building 
https://github.com/espnet/espnet/blob/01eaefef7698453d3c6497c17ba679c98e9f5f85/docker/prebuilt/devel/Dockerfile#L13

This is because these folders are then mounted from the current directory

https://github.com/espnet/espnet/blob/01eaefef7698453d3c6497c17ba679c98e9f5f85/docker/run.sh#L153-L158

when using ./run.sh, so if there is any change in your code then it can become visible inside the docker container.

**Comment by muramasa2** [comment]
I completely make sense, I forgot to check the sentence sorry.
So building without CUDA is LGTM, and  Now I try to `./build.sh fully_local 10.0`
I hope it will be finished without errors.

Can you success building image even if with CUDA?

**Comment by muramasa2** [comment]
Now I finished testing the command `./build.sh fully_local 10.0` but I got the same error https://github.com/espnet/espnet/issues/2508#issuecomment-698730667

So now I try to rollback your commit 02d65ddb96a338e2275ccb67a8dd1fb2e800d311 and retry it.

**Comment by muramasa2** [comment]
@Fhrozen Now I finished checking building docker image with CUDA after rollback to your commit 02d65dd.
it worked without problem as you said, so the commits after yours cause the error https://github.com/espnet/espnet/issues/2508#issuecomment-698730667.

Thank you for all of your support and kindness.
