### ISSUE TITLE
can't load asr model with speech2text = Speech2Text("asr_config.yml", "asr.pth", "lm_config.yaml", "lm.pth", nbest=10)

### ISSUE THREAD

**Issue by wac81** [espnet/espnet#2511]
@kamo-naoyuki 
i can't  load asr model with 
speech2text = Speech2Text("asr_config.yml", "asr.pth", "lm_config.yaml", "lm.pth", nbest=10)

with this model
Conformer (kernel size = 15) + SpecAugment + LM weight = 0.0 result
training config file: conf/tuning/train_pytorch_conformer_kernel15.yaml
preprocess config file: conf/specaug.yaml
decoding config file: conf/decode.yaml, set lm-weight = 0.0
model link: https://drive.google.com/file/d/15_aEje6i0-LVUHm_ntA345ADx8HILAx9/view  

please how to solve it?

_Originally posted by @wac81 in https://github.com/espnet/espnet/pull/2092#issuecomment-698090935_

**Comment by b-flo** [comment]
Hi,

@kamo-naoyuki already answered on the issue you linked:

>This is API for espnet2 and the model link is the one for espnet1.
>
>See about the available models: https://github.com/espnet/espnet_model_zoo

**Comment by wac81** [comment]
@b-flo you give link is espnet model zoo, i have seen before, but not info with **aishell** model loading.

speech2text = Speech2Text(**d.download_and_unpack("model_name"))  <----model zoo is not find aishell with Conformer , even not aishell .

i try other hand:

speech2text = Speech2Text(
                          asr_train_config='model.v1/exp/train_sp_pytorch_train_pytorch_transformer_lr1.0/results/model.json',
                          asr_model_file="model.v1/exp/train_sp_pytorch_train_pytorch_transformer_lr1.0/results/model.last10.avg.best",
                          lm_train_config='model.v1/exp/train_rnnlm_pytorch_lm/model.json',
                          lm_file='model.v1/exp/train_rnnlm_pytorch_lm/rnnlm.model.best'
                          )

but get ERROR:
Traceback (most recent call last):
  File "/home/wac/PycharmProjects/espnet_tts/asr_demo.py", line 14, in <module>
    lm_file='model.v1/exp/train_rnnlm_pytorch_lm/rnnlm.model.best'
  File "/home/wac/.local/lib/python3.6/site-packages/espnet2/bin/asr_inference.py", line 73, in __init__
    asr_train_config, asr_model_file, device
  File "/home/wac/.local/lib/python3.6/site-packages/espnet2/tasks/abs_task.py", line 1713, in build_model_from_file
    args = argparse.Namespace(**args)
TypeError: type object argument after ** must be a mapping, not list

**Comment by kamo-naoyuki** [comment]
Aishell model is not existing simply.

**Comment by wac81** [comment]
https://github.com/espnet/espnet/blob/master/egs/aishell/asr1/RESULTS.md

but this Aishell model ....?
how to loading?

**Comment by kamo-naoyuki** [comment]
Again, this is API for espnet2 and the model link is espnet1.  It's better to read the documentation of espnet.

- egs: espnet1
- egs2:  espnet2

To use espnet1 model, you need to use the script for it: https://github.com/espnet/espnet/blob/master/utils/recog_wav.sh

**Comment by wac81** [comment]
why not offer a method to transform egs model to egs2
