### ISSUE TITLE
Incorrect ID in ref.trn and hyp.trn

### ISSUE THREAD

**Issue by ajd12342** [espnet/espnet#2518]
**Describe the bug**
When decoding is done in a recipe (I use the Librispeech recipe) where the utterance ID does not contain a `_` or a `-`, sclite displays errors of the form 'Error: extract_speaker can't locate RM id <utt_id>' for each line in hyp.trn/ref.trn. This causes per-speaker Error Rates to not be displayed. This I can trace to the following problem in espnet2:

In hyp.trn or ref.trn in any of the decoding folders in espnet2, the part within brackets () on every line is supposed to be <spk_id>-<utt_id>. It was like this in espnet1, built using the utt2spk and spk2utt files. In espnet2, it is just <utt_id>. When sclite is run in espnet2, it is run with the utt-id as the 'RM' type. See extract_speaker in https://github.com/foundintranslation/Kaldi/blob/master/tools/sctk-2.4.0/src/sclite/align.c . If the type is RM, it uses the part before the '-' or '_' to get the speaker ID. Due to the espnet2 bug, the speaker ID is not present in the ID, so it says that it can't locate the speaker ID. Users may luckily have some `-` or `_` in their utt_ids, which slips through this bug, but is incorrect behaviour. This may have the following incorrect behaviour. Say there are two different utt_ids 1001-124 and 1002-124. These will be interpreted by sclite as being the same utterance ID with two speakers. So based on how it was coded, only the second utt_id results may be reported since the first one may be overwritten.

**Basic environments:**
- OS information: Linux 4.15.0-54-generic #58-Ubuntu SMP Mon Jun 24 10:55:24 UTC 2019 x86_64
- python version: `3.6.9 (default, Jul 17 2020, 12:50:27)  [GCC 8.4.0]`
- espnet version: `espnet 0.9.0`
- pytorch version: `pytorch 1.4.0`
- Git hash: `b9e0f66ca8b908c8e2d427e67755d822ff4053d0`
- Commit date: `Mon Aug 10 00:37:07 2020 +0000`
 
**Environments from `torch.utils.collect_env`:**
Collecting environment information...
PyTorch version: 1.4.0
Is debug build: No
CUDA used to build PyTorch: 10.1

OS: Ubuntu 18.04.2 LTS
GCC version: (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
CMake version: version 3.10.2

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 10.1.168
GPU models and configuration: 
GPU 0: GeForce GTX 1080 Ti
GPU 1: GeForce GTX 1080 Ti
GPU 2: GeForce GTX 1080 Ti
GPU 3: GeForce GTX 1080 Ti

Nvidia driver version: 418.67
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.1

Versions of relevant libraries:
[pip3] numpy==1.19.1
[pip3] pytorch-ranger==0.1.1
[pip3] pytorch-wpe==0.0.0
[pip3] torch==1.4.0
[pip3] torch-complex==0.1.1
[pip3] torch-optimizer==0.0.1a14
[pip3] torchaudio==0.4.0
[pip3] warprnnt-pytorch==0.1
[conda] nomkl                     3.0                           0

**Task information:**
 - Task: [ASR]
 - Recipe: [librispeech]
 - ESPnet2

**To Reproduce**
1. Move to a recipe directory, e.g., `cd egs2/librispeech/asr1`
2. Run `run.sh` with own dataset whose utt_ids don't contain `_` or `-`. 
3. See the printed errors during the scoring stage.

**Error logs**
`Error: extract_speaker can't locate RM id <utt_id>` for each utt_id.

**Comment by kamo-naoyuki** [comment]
I'm not sure understanding what you said.

I know sclite requires `<spk_id>-<utt_id>` and librispeech uttid is just like so, and we never get `extract_speaker can't locate RM id` warning in the recipe.
Are you talking about your dataset? If so, you are responsible to set the utterance id correctly. It's not our business.

Furthermore, it's not problem because it can show the WER without speaker ID.

**Comment by ajd12342** [comment]
I agree that Librispeech already has utterance IDs in this fashion, but many researchers repurpose existing recipes for their own datasets, in which case this error pops up and does not show per-speaker WERs.
Based on my limited experience with using espnet, in espnet1 an4 recipe, even if the utt_id was something like say 000010002, and the utt2spk file mapped 000010002 to speaker 00001, then the .trn files would automatically have 00001-000010002. I was wondering why the same was not happening here as well, since the expectation is that similar behaviour occurs. It could be helpful to have a README or documentation about setting up the dataset utterance IDs to follow this specific requirement. Thanks!

**Comment by kamo-naoyuki** [comment]
> Based on my limited experience with using espnet, in espnet1 an4 recipe, even if the utt_id was something like say 000010002, and the utt2spk file mapped 000010002 to speaker 00001, then the .trn files would automatically have 00001-000010002

Okay, I understood. I didn't know this behaviour of espnet1 because per speakers WER is not necessary for me and if need, we can get it with filtering speaker from the texts easily. 

This is done in here for espnet1.

https://github.com/espnet/espnet/blob/88bb9dba83636c4bf12f10a870a7d8c5f9515b9f/utils/json2trn.py#L92

This is a feature request as per speakers WER. I'll implement. Please wait for a while.
