### ISSUE TITLE
What's the most suitable gcc version and about cuda compatibility problem？

### ISSUE THREAD

**Issue by ymzlygw** [espnet/espnet#2522]
When install the espnet at the "make" step, it  failed beacuse of gcc version(My is gcc 7.5), error shows that gcc version later than 6 is not supported. Then  I try gcc 5.5, also have Compatibility issues and failed. It seems that gcc must be  >=4.9 and <6, so what's the suitable gcc version for install ?

**Comment by kamo-naoyuki** [comment]
Requires gcc>=5. More precisely, requires c++14, so gcc=5-9 should work if pytorch's documentation says true. I am using gcc=7.2.1.

Show your environment and your log following our issue template always. Otherwise, anyone can't answer.

**Comment by ymzlygw** [comment]
> Requires gcc>=5. More precisely, requires c++14, so gcc=5-9 should work if pytorch's documentation says true. I am using gcc=7.2.1.
> 
> Show your environment and your log following our issue template always. Otherwise, anyone can't answer.

Hi, this time I get the following error message:
____________________________________________________________________________________________________________
espnet_env) root@d6fbba8aac2b:~/AI_/espnet/tools# make TH_VERSION=1.0.1

/bin/sh: 5: /root/anaconda3/etc/conda/activate.d/activate-binutils_linux-64.sh: Syntax error: "(" unexpected
/bin/sh: 5: /root/anaconda3/etc/conda/activate.d/activate-binutils_linux-64.sh: Syntax error: "(" unexpected
[ -n "/usr/local/cuda-9.0" ] || { echo -e "Error: CUDA_HOME is not set.\n    $ . ./setup_cuda_env.sh <cuda-root>"; exit 1; }
CUDA_VERSION=9.0
. ./activate_python.sh && python3 check_pytorch_cuda_compatibility.py 1.0.1 9.0 || { echo "Change TH_VERSION or CUDA_VERSION"; exit 1; }
/bin/sh: 5: /root/anaconda3/etc/conda/activate.d/activate-binutils_linux-64.sh: Syntax error: "(" unexpected
Makefile:73: recipe for target 'showenv' failed
make: *** [showenv] Error 2

My cuda is 9.0 and should support pytorch 1.0.1 and 1.1.0 but It failed when I gave TH_VERSION=1.0.1and1.1.0.
Why this happen?

**Comment by kamo-naoyuki** [comment]
This is not obviously not the problem  of gcc version. Please ask correctly. 

You have a syntax error from the anaconda, but this is unexpected. Please write your environment more detail, again. Why didn't you do? Are you really want us to answer?

I guess your anaconda is something wrong and not compatible with posix shell. I recommend you building new anaconda.

**Comment by ymzlygw** [comment]
> This is obviously not the problem of gcc version. Please ask correctly.
> 
> You have a syntax error from the anaconda, but this is unexpected. Please write your environment more detail, again. Why didn't you do? Are you really want us to answer?
> 
> I guess your anaconda is something wrong and not compatible with posix shell. I recommend you building new anaconda.

sorry, I have correct the question name and My environment is:
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.3 LTS
Release:        18.04
Codename:       bionic

cnda list:

_libgcc_mutex             0.1                        main    defaults
asn1crypto                1.4.0                      py_0    defaults
blas                      1.0                         mkl    defaults
brotlipy                  0.7.0           py36h7b6447c_1000    defaults
bzip2                     1.0.8                h7b6447c_0    defaults
ca-certificates           2020.6.20            hecda079_0    conda-forge
certifi                   2020.6.20        py36h9f0ad1d_0    conda-forge
cffi                      1.14.0           py36h2e261b9_0    defaults
chardet                   3.0.4                 py36_1003    defaults
cmake                     3.12.2               h52cb24c_0    defaults
conda                     4.8.4                    py36_0    defaults
conda-package-handling    1.6.1            py36h7b6447c_0    defaults
cryptography              2.3.1            py36hc365091_0    defaults
cudatoolkit               9.0                  h13b8566_0    defaults
expat                     2.2.9                he6710b0_2    defaults
ffmpeg                    4.3.1                h167e202_0    conda-forge
freetype                  2.10.2               he06d7ca_0    conda-forge
gettext                   0.19.8.1          hc5be6a0_1002    conda-forge
gmp                       6.2.0                he1b5a44_2    conda-forge
gnutls                    3.6.13               h79a8f9a_0    conda-forge
idna                      2.10                       py_0    defaults
intel-openmp              2020.2                      254    defaults
lame                      3.100             h14c3975_1001    conda-forge
libcurl                   7.61.1               heec0ca6_0    defaults
libedit                   3.1.20191231         h14c3975_1    defaults
libffi                    3.2.1                hd88cf55_4    defaults
libflac                   1.3.3                he1b5a44_0    conda-forge
libgcc-ng                 9.1.0                hdf63c60_0    defaults
libiconv                  1.16                 h516909a_0    conda-forge
libogg                    1.3.2             h516909a_1002    conda-forge
libpng                    1.6.37               hed695b0_2    conda-forge
libssh2                   1.8.0                h9cfc8f7_4    defaults
libstdcxx-ng              9.1.0                hdf63c60_0    defaults
mkl                       2020.2                      256    defaults
mkl-service               2.3.0            py36he904b0f_0    defaults
mkl_fft                   1.1.0            py36h23d657b_0    defaults
mkl_random                1.1.1            py36h0573a6f_0    defaults
ncurses                   6.2                  he6710b0_1    defaults
nettle                    3.4.1             h1bed415_1002    conda-forge
ninja                     1.10.1           py36hfd86e86_0    defaults
numpy                     1.19.1           py36hbc911f0_0    defaults
numpy-base                1.19.1           py36hfa32c7d_0    defaults
openh264                  2.1.1                h8b12597_0    conda-forge
openssl                   1.0.2u               h516909a_0    conda-forge
pip                       20.2.2                   py36_0    defaults
pycosat                   0.6.3            py36h7b6447c_0    defaults
pycparser                 2.20                       py_2    defaults
pyopenssl                 19.0.0                   py36_0    defaults
pysocks                   1.7.1                    py36_0    defaults
python                    3.6.6                h6e4f718_2    defaults
python_abi                3.6                     1_cp36m    conda-forge
pytorch                   1.0.0           py3.6_cuda9.0.176_cudnn7.4.1_1    pytorch
readline                  7.0                  h7b6447c_5    defaults
requests                  2.24.0                     py_0    defaults
rhash                     1.3.6                hb7f436b_0    defaults
ruamel_yaml               0.15.87          py36h7b6447c_1    defaults
setuptools                49.6.0                   py36_0    defaults
six                       1.15.0                     py_0    defaults
sqlite                    3.33.0               h62c20be_0    defaults
tk                        8.6.10               hbc83047_0    defaults
tqdm                      4.48.2                     py_0    defaults
urllib3                   1.25.10                    py_0    defaults
warpctc-pytorch10-cuda90  0.1.3                    pypi_0    pypi
wheel                     0.35.1                     py_0    defaults
x264                      1!152.20180806       h14c3975_0    conda-forge
xz                        5.2.5                h7b6447c_0    defaults
yaml                      0.2.5                h7b6447c_0    defaults
zlib                      1.2.11               h7b6447c_3    defaults
And I install it in  anaconda environment after I established a conda env through the installation instruction step4  of ESPnet .
So I should install a new anaconda or just install the espnet from the beginning.
