### ISSUE TITLE
Finetune using alternate phonemes

### ISSUE THREAD

**Issue by gafsd** [espnet/espnet#2524]
I am trying to train a ~10 hour dataset using french pronunciation. I am able to get pronunciation in IPA but obviously some sounds in french are not pronounceable in ARPAbet pronunciations like g2p uses. There is no pretrained model for char anymore in espnet2. What is the best way to finetune ESPnet on my dataset? Is there an easy way to use custom phonemization tool and then finetune?

**Comment by sw005320** [comment]
Could you clarify your explanations more?
Is that for ASR or TTS?
Do you want to use espnet2 or is espnet1 still fine for your purpose?

**Comment by gafsd** [comment]
I am using TTS. I prefer espnet2 for code unification purposes and using gst.

**Comment by kan-bayashi** [comment]
First, make the recipe of your dataset.
https://github.com/espnet/espnet/tree/master/egs2/TEMPLATE/tts1#how-to-make-a-new-recipe-for-my-own-dataset

Then, you can add new G2P function.
https://github.com/espnet/espnet/tree/master/egs2/TEMPLATE/tts1#how-to-add-a-new-g2p-module

For fine-tuning:
https://github.com/espnet/espnet/tree/master/egs2/TEMPLATE/tts1#how-to-load-the-pretrained-model
https://github.com/espnet/espnet/tree/master/egs2/TEMPLATE/tts1#how-to-finetune-the-pretrained-model

**Comment by gafsd** [comment]
Which pretrain_key should I use to skip embedding layer?

**Comment by kan-bayashi** [comment]
It depends on the model.
For example, in the case of GST-Tacotron2:
```
pretrain_path:
    - /path/to/checkpoint.pth
	- /path/to/checkpoint.pth
	- /path/to/checkpoint.pth
pretrain_key:
    - tts.enc.convs
    - tts.enc.blstm
	- tts.gst
    - tts.dec
```

**Comment by gafsd** [comment]
I made outline of new g2p in a fork but I think it is not that useful and require some extra prerequisites. I will try and train and see if it improves on my dataset.

**Comment by gafsd** [comment]
I notice that Mozilla TTS is using espeak phonemes like I have implemented instead of g2p_en. It is working well but I have some issue passing language parameter to phoneme_tokenizer to make it clean from tts.sh so I leave it to you.
