### ISSUE TITLE
The pre-trained model of conformer in librispeech egs can't be correctly uncompressed.

### ISSUE THREAD

**Issue by JiayiFu** [espnet/espnet#2537]
Hi all, 
  I try to download the pre-trained conformer model from the [link](https://drive.google.com/drive/folders/1GFaqEKsI6M_dBbxHD7s84J3yi5WGeNNC?usp=sharing) in the [page](https://github.com/espnet/espnet/blob/master/egs/librispeech/asr1/RESULTS.md). But the downloaded file can't be uncompressed correctly.
  The error logs are:
 ```
  tar zxvf model.tar.gz
  conf/tuning/conformer/train_pytorch_conformer_large.yaml
  conf/decode.yaml
  data/train_960/cmvn.ark
  exp/train_960_pytorch_train_pytorch_conformer_large_specaug/results/model.val5.avg.best
  gzip: stdin: invalid compressed data--format violated
  tar: Unexpected EOF in archive
  tar: Unexpected EOF in archive
  tar: Error is not recoverable: exiting now
```

**Comment by ChaoyueDing** [comment]
I'm the same, don't know how to solve it

**Comment by sw005320** [comment]
Hi @yuekaizhang, can you check this?

**Comment by yuekaizhang** [comment]
> I'm the same, don't know how to solve it

Hi all, I have uploaded a new file called model.tar.gz. I have tested on my owner server. Would you mind testing it again? (The original file has been renamed to model_old.tar.gz)

**Comment by JiayiFu** [comment]
I have download the updated model file and uncompressed it correctly. Thank you! So I close this issue.
