### ISSUE TITLE
The preprocessing of spliting large text in LM training.

### ISSUE THREAD

**Issue by WuHao9408** [espnet/espnet#2539]
when i use 52GB data to train the LM, the split_scp.py processing time is estimated to exceeds 20 days. https://github.com/espnet/espnet/blob/master/espnet2/bin/split_scps.py

Each line of text writting in split_file need once opening operation, and 52GB text over 400million lines.

i have solved this problem, it still spend almost 5 hours.

**Comment by kamo-naoyuki** [comment]
How did you solve?

**Comment by kamo-naoyuki** [comment]
My idea:

- Keeping all file descriptors as open
- Shuffling scp files using linux `shuf` command somehow and split them without writing lines respectively. 
    - `shuf` command is fast.

**Comment by WuHao9408** [comment]
In a big text, read lines and use temporary list  to store lines, if the length of list exceed threshold, then write in text and clear list. Cycle the process until end.

If the threshold is larger, the processing is faster, in my data(52GB), threshold set 500000.
But be careful of oom.

[split.txt](https://github.com/espnet/espnet/files/5304389/split.txt)

**Comment by kamo-naoyuki** [comment]
I see.  Not bad.

**Comment by WuHao9408** [comment]
haha, hope the better solution.
