### ISSUE TITLE
Espnet2 TTS data dir and resume

### ISSUE THREAD

**Issue by RuslanSel** [espnet/espnet#2548]
Hi,

Two quick questions about Espnet2 TTS.
1) How to keep data, dump and exp directories not is egs2/.../tts1? Where I can set path to another directory?
2) How to resume training? For example, from 4th epoch.

Thanks in advance.

**Comment by RuslanSel** [comment]
Seems like it resumes by itself.

**Comment by kan-bayashi** [comment]
You can change the `dump` and `exp` directory via `--dumpdir` and `--expdir` options in `tts.sh`.
But currently we do not provide the option to change `data` directory.

If you run the training with existing tag, the training will automatically resume using latest checkpoint.

**Comment by RuslanSel** [comment]
Thank you!
