### ISSUE TITLE
Finetuning VCTK TTS Espnet2

### ISSUE THREAD

**Issue by gafsd** [espnet/espnet#2553]
I am interested in using your espnet2 VCTK weights and finetuning for my own datasets. I have a few problems: unsure how to prepare dataset for finetuning (especially because I have LJSpeech-style data not VCTK-style data) and second the VCTK is trained using fs==24000 but I have mostly fs==22050 data. Should I upsample?

**Comment by kan-bayashi** [comment]
I recommend creating the recipe of your dataset:
https://github.com/espnet/espnet/tree/master/egs2/TEMPLATE/tts1#how-to-make-a-new-recipe-for-my-own-dataset
Then, you can do finetuning:
https://github.com/espnet/espnet/tree/master/egs2/TEMPLATE/tts1#how-to-finetune-the-pretrained-model

About sampling rate, I've never tried mismatched condition but it is better to match the sampling rate.

**Comment by gafsd** [comment]
Yes, should I downsample VCTK corpus and retrain from scratch with fs==22050 perhaps?

**Comment by kan-bayashi** [comment]
That is the best, but I think upsampling might be working since we use limited mel band.

**Comment by gafsd** [comment]
Should I combine VCTK corpus with new speakers? Or just train with new speakers

**Comment by kan-bayashi** [comment]
It depends on your situation.
If you want to use it as a signal speaker model, just fine-tuning seems OK.
But if you want to use it as a multi-speaker model, training from scratch with mixed data seems better.
