### ISSUE TITLE
Import Error about Openjtalk after installed it

### ISSUE THREAD

**Issue by ymzlygw** [espnet/espnet#2557]
I am trying  to run script to synthesis with Japanese but it ask me to install pyopenjtalk module. After I install it  by <https://github.com/espnet/espnet/tree/master/egs/jsut#tts1> , It still has error message as follow:
____________________________________________________________________________________________________________________________
ImportError                               Traceback (most recent call last)
<ipython-input-14-9e9825ccdc29> in <module>
----> 1 speech, *_= text2speech("foobar")
      2 soundfile.write("out.wav", speech.numpy(), text2speech.fs, "PCM_16")

~/anaconda3/envs/espnet_env/lib/python3.7/site-packages/torch/autograd/grad_mode.py in decorate_no_grad(*args, **kwargs)
     41         def decorate_no_grad(*args, **kwargs):
     42             with self:
---> 43                 return func(*args, **kwargs)
     44         return decorate_no_grad
     45 

~/AI_/espnet/espnet2/bin/tts_inference.py in __call__(self, text, speech, durations)
    138         if isinstance(text, str):
    139             # str -> np.ndarray
--> 140             text = self.preprocess_fn("<dummy>", {"text": text})["text"]
    141         batch = {"text": text}
    142         if speech is not None:

~/AI_/espnet/espnet2/train/preprocessor.py in __call__(self, uid, data)
     87             text = data[self.text_name]
     88             text = self.text_cleaner(text)
---> 89             tokens = self.tokenizer.text2tokens(text)
     90             text_ints = self.token_id_converter.tokens2ids(tokens)
     91             data[self.text_name] = np.array(text_ints, dtype=np.int64)

~/AI_/espnet/espnet2/text/phoneme_tokenizer.py in text2tokens(self, line)
    136 
    137         line = "".join(tokens)
--> 138         tokens = self.g2p(line)
    139         return tokens
    140 

~/AI_/espnet/espnet2/text/phoneme_tokenizer.py in pyopenjtalk_g2p(text)
     11 
     12 def pyopenjtalk_g2p(text) -> List[str]:
---> 13     import pyopenjtalk
     14 
     15     # phones is a str object separated by space

~/AI_/espnet/tools/pyopenjtalk/pyopenjtalk/__init__.py in <module>
     18     raise ImportError("BUG: version.py doesn't exist. Please file a bug report.")
     19 
---> 20 from .openjtalk import OpenJTalk
     21 
     22 # Dictionary directory

### ImportError: libopenjtalk.so.1.10: cannot open shared object file: No such file or directory.

I also used pip to make sure that I have installed openjtalk:

~/AI_/espnet/tools# pip install pyopenjtalk
Requirement already satisfied: pyopenjtalk in ./pyopenjtalk (0.0.3+a3d30a6)
Requirement already satisfied: numpy>=1.8.0 in /root/anaconda3/envs/espnet_env/lib/python3.7/site-packages (from pyopenjtalk) (1.19.1)
Requirement already satisfied: cython>=0.21.0 in /root/anaconda3/envs/espnet_env/lib/python3.7/site-packages (from pyopenjtalk) (0.29.21)
Requirement already satisfied: six in /root/anaconda3/envs/espnet_env/lib/python3.7/site-packages (from pyopenjtalk) (1.15.0)

So  why this error occurs after I install it successfully?

**Comment by ymzlygw** [comment]
### There are  installed successfully information:
~/AI_/espnet/tools# make pyopenjtalk.done
. ./activate_python.sh && ./installers/install_pyopenjtalk.sh
Cloning into 'hts_engine_API'...
remote: Enumerating objects: 53, done.
remote: Counting objects: 100% (53/53), done.
remote: Compressing objects: 100% (35/35), done.
remote: Total 1040 (delta 32), reused 35 (delta 17), pack-reused 987
Receiving objects: 100% (1040/1040), 396.10 KiB | 732.00 KiB/s, done.
Resolving deltas: 100% (774/774), done.
Setting top to                           : /root/AI_/espnet/tools/hts_engine_API/src 
Setting out to                           : /root/AI_/espnet/tools/hts_engine_API/src/build 
Checking for waf version in 1.7.11-2.1.0 : ok 
Checking for 'gcc' (C compiler)          : /usr/bin/gcc 
Checking for header stdlib.h             : yes 
Checking for header string.h             : yes 

hts_engine_API has been configured as follows:

[Build information]
Package:                 hts_engine_API-1.0.9
build (compile on):      x86_64-linux
host endian:             little
Compiler:                gcc
Compiler version:        7.5.0
CFLAGS:                  -O2 -Wall -fno-common -Wstrict-prototypes

'configure' finished successfully (0.195s)
Waf: Entering directory `/root/AI_/espnet/tools/hts_engine_API/src/build'
/usr/bin/gcc
/usr/bin/gcc
[ 1/14] Compiling lib/HTS_pstream.c
[ 2/14] Compiling lib/HTS_gstream.c
[ 3/14] Compiling lib/HTS_audio.c
[ 4/14] Compiling lib/HTS_model.c
[ 5/14] Compiling lib/HTS_label.c
[ 6/14] Compiling lib/HTS_sstream.c
[ 7/14] Compiling lib/HTS_misc.c
[ 8/14] Compiling lib/HTS_engine.c
[ 9/14] Compiling lib/HTS_vocoder.c
[10/14] Compiling bin/hts_engine.c
[11/14] Compiling hts_engine_API.pc.in
../lib/HTS_model.c: In function ‘HTS_ModelSet_load’:
../lib/HTS_model.c:1165:27: warning: self-comparison always evaluates to false [-Wtautological-compare]
             if (is_msd[j] != is_msd[j])
                           ^~

[12/14] Linking build/lib/libhts_engine_API.so
[13/14] Linking build/bin/hts_engine
[14/14] Symlinking build/lib/libhts_engine_API.so
Waf: Leaving directory `/root/AI_/espnet/tools/hts_engine_API/src/build'
'build' finished successfully (0.660s)
Waf: Entering directory `/root/AI_/espnet/tools/hts_engine_API/src/build'
/usr/bin/gcc
/usr/bin/gcc
+ install /root/AI_/espnet/tools/lib/libhts_engine_API.so.1.0.9 (from build/lib/libhts_engine_API.so)
+ symlink /root/AI_/espnet/tools/lib/libhts_engine_API.so.1 (to libhts_engine_API.so.1.0.9)
+ install /root/AI_/espnet/tools/bin/hts_engine (from build/bin/hts_engine)
+ install /root/AI_/espnet/tools/include/HTS_hidden.h (from lib/HTS_hidden.h)
+ symlink /root/AI_/espnet/tools/lib/libhts_engine_API.so (to libhts_engine_API.so.1.0.9)
+ install /root/AI_/espnet/tools/include/HTS_engine.h (from include/HTS_engine.h)
+ install /root/AI_/espnet/tools/lib/pkgconfig/hts_engine_API.pc (from build/hts_engine_API.pc)
Waf: Leaving directory `/root/AI_/espnet/tools/hts_engine_API/src/build'
'install' finished successfully (0.017s)
Cloning into 'open_jtalk'...
remote: Enumerating objects: 1822, done.
remote: Total 1822 (delta 0), reused 0 (delta 0), pack-reused 1822
Receiving objects: 100% (1822/1822), 24.13 MiB | 8.99 MiB/s, done.
Resolving deltas: 100% (1407/1407), done.
-- The C compiler identification is GNU 7.5.0
-- The CXX compiler identification is GNU 7.5.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for include file ctype.h
-- Looking for include file ctype.h - found
-- Looking for include file dirent.h
-- Looking for include file dirent.h - found
-- Looking for include file fcntl.h
-- Looking for include file fcntl.h - found
-- Looking for include file inttypes.h
-- Looking for include file inttypes.h - found
-- Looking for include file io.h
-- Looking for include file io.h - not found
-- Looking for include file memory.h
-- Looking for include file memory.h - found
-- Looking for include file setjmp.h
-- Looking for include file setjmp.h - found
-- Looking for include file stdint.h
-- Looking for include file stdint.h - found
-- Looking for include file stdlib.h
-- Looking for include file stdlib.h - found
-- Looking for include file strings.h
-- Looking for include file strings.h - found
-- Looking for include file string.h
-- Looking for include file string.h - found
-- Looking for include file sys/mman.h
-- Looking for include file sys/mman.h - found
-- Looking for include file sys/stat.h
-- Looking for include file sys/stat.h - found
-- Looking for include file sys/times.h
-- Looking for include file sys/times.h - found
-- Looking for include file sys/types.h
-- Looking for include file sys/types.h - found
-- Looking for include file unistd.h
-- Looking for include file unistd.h - found
-- Looking for getenv
-- Looking for getenv - found
-- Looking for getpagesize
-- Looking for getpagesize - found
-- Looking for mmap
-- Looking for mmap - found
-- Looking for opendir
-- Looking for opendir - found
-- Looking for setjmp
-- Looking for setjmp - found
-- Looking for sqrt
-- Looking for sqrt - not found
-- Looking for strstr
-- Looking for strstr - found
-- Looking for iconv_open in iconv
-- Looking for iconv_open in iconv - not found
-- Looking for sqrt in m
-- Looking for sqrt in m - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of char
-- Check size of char - done
-- Check size of int
-- Check size of int - done
-- Check size of long
-- Check size of long - done
-- Check size of long long
-- Check size of long long - done
-- Check size of short
-- Check size of short - done
-- Check size of size_t
-- Check size of size_t - done
-- Configuring done
-- Generating done
-- Build files have been written to: /root/AI_/espnet/tools/open_jtalk/src/build
make[1]: Entering directory '/root/AI_/espnet/tools/open_jtalk/src/build'
make[2]: Entering directory '/root/AI_/espnet/tools/open_jtalk/src/build'
make[3]: Entering directory '/root/AI_/espnet/tools/open_jtalk/src/build'
Scanning dependencies of target openjtalk
make[3]: Leaving directory '/root/AI_/espnet/tools/open_jtalk/src/build'
make[3]: Entering directory '/root/AI_/espnet/tools/open_jtalk/src/build'
[  2%] Building C object CMakeFiles/openjtalk.dir/jpcommon/jpcommon.c.o
[  5%] Building C object CMakeFiles/openjtalk.dir/jpcommon/jpcommon_label.c.o
[  7%] Building C object CMakeFiles/openjtalk.dir/jpcommon/jpcommon_node.c.o
[ 10%] Building CXX object CMakeFiles/openjtalk.dir/mecab/src/char_property.cpp.o
[ 12%] Building CXX object CMakeFiles/openjtalk.dir/mecab/src/connector.cpp.o
[ 15%] Building CXX object CMakeFiles/openjtalk.dir/mecab/src/context_id.cpp.o
[ 17%] Building CXX object CMakeFiles/openjtalk.dir/mecab/src/dictionary.cpp.o
[ 20%] Building CXX object CMakeFiles/openjtalk.dir/mecab/src/dictionary_compiler.cpp.o
[ 23%] Building CXX object CMakeFiles/openjtalk.dir/mecab/src/dictionary_generator.cpp.o
[ 25%] Building CXX object CMakeFiles/openjtalk.dir/mecab/src/dictionary_rewriter.cpp.o
[ 28%] Building CXX object CMakeFiles/openjtalk.dir/mecab/src/eval.cpp.o
[ 30%] Building CXX object CMakeFiles/openjtalk.dir/mecab/src/feature_index.cpp.o
[ 33%] Building CXX object CMakeFiles/openjtalk.dir/mecab/src/iconv_utils.cpp.o
[ 35%] Building CXX object CMakeFiles/openjtalk.dir/mecab/src/lbfgs.cpp.o
[ 38%] Building CXX object CMakeFiles/openjtalk.dir/mecab/src/learner.cpp.o
[ 41%] Building CXX object CMakeFiles/openjtalk.dir/mecab/src/learner_tagger.cpp.o
[ 43%] Building CXX object CMakeFiles/openjtalk.dir/mecab/src/libmecab.cpp.o
[ 46%] Building CXX object CMakeFiles/openjtalk.dir/mecab/src/mecab-dict-index.cpp.o
[ 48%] Building CXX object CMakeFiles/openjtalk.dir/mecab/src/mecab.cpp.o
[ 51%] Building CXX object CMakeFiles/openjtalk.dir/mecab/src/nbest_generator.cpp.o
[ 53%] Building CXX object CMakeFiles/openjtalk.dir/mecab/src/param.cpp.o
[ 56%] Building CXX object CMakeFiles/openjtalk.dir/mecab/src/string_buffer.cpp.o
[ 58%] Building CXX object CMakeFiles/openjtalk.dir/mecab/src/tagger.cpp.o
[ 61%] Building CXX object CMakeFiles/openjtalk.dir/mecab/src/tokenizer.cpp.o
[ 64%] Building CXX object CMakeFiles/openjtalk.dir/mecab/src/utils.cpp.o
[ 66%] Building CXX object CMakeFiles/openjtalk.dir/mecab/src/viterbi.cpp.o
[ 69%] Building CXX object CMakeFiles/openjtalk.dir/mecab/src/writer.cpp.o
[ 71%] Building C object CMakeFiles/openjtalk.dir/mecab2njd/mecab2njd.c.o
[ 74%] Building C object CMakeFiles/openjtalk.dir/njd/njd.c.o
[ 76%] Building C object CMakeFiles/openjtalk.dir/njd/njd_node.c.o
[ 79%] Building C object CMakeFiles/openjtalk.dir/njd2jpcommon/njd2jpcommon.c.o
[ 82%] Building C object CMakeFiles/openjtalk.dir/njd_set_accent_phrase/njd_set_accent_phrase.c.o
[ 84%] Building C object CMakeFiles/openjtalk.dir/njd_set_accent_type/njd_set_accent_type.c.o
[ 87%] Building C object CMakeFiles/openjtalk.dir/njd_set_digit/njd_set_digit.c.o
[ 89%] Building C object CMakeFiles/openjtalk.dir/njd_set_long_vowel/njd_set_long_vowel.c.o
[ 92%] Building C object CMakeFiles/openjtalk.dir/njd_set_pronunciation/njd_set_pronunciation.c.o
[ 94%] Building C object CMakeFiles/openjtalk.dir/njd_set_unvoiced_vowel/njd_set_unvoiced_vowel.c.o
[ 97%] Building C object CMakeFiles/openjtalk.dir/text2mecab/text2mecab.c.o
[100%] Linking CXX shared library libopenjtalk.so
make[3]: Leaving directory '/root/AI_/espnet/tools/open_jtalk/src/build'
[100%] Built target openjtalk
make[2]: Leaving directory '/root/AI_/espnet/tools/open_jtalk/src/build'
Install the project...
-- Install configuration: "Release"
-- Installing: /root/AI_/espnet/tools/lib/libopenjtalk.so.1.10
-- Installing: /root/AI_/espnet/tools/lib/libopenjtalk.so
-- Set runtime path of "/root/AI_/espnet/tools/lib/libopenjtalk.so.1.10" to ""
-- Installing: /root/AI_/espnet/tools/include/openjtalk/jpcommon.h
-- Installing: /root/AI_/espnet/tools/include/openjtalk/mecab.h
-- Installing: /root/AI_/espnet/tools/include/openjtalk/mecab2njd.h
-- Installing: /root/AI_/espnet/tools/include/openjtalk/njd.h
-- Installing: /root/AI_/espnet/tools/include/openjtalk/njd2jpcommon.h
-- Installing: /root/AI_/espnet/tools/include/openjtalk/njd_set_accent_phrase.h
-- Installing: /root/AI_/espnet/tools/include/openjtalk/njd_set_accent_type.h
-- Installing: /root/AI_/espnet/tools/include/openjtalk/njd_set_digit.h
-- Installing: /root/AI_/espnet/tools/include/openjtalk/njd_set_long_vowel.h
-- Installing: /root/AI_/espnet/tools/include/openjtalk/njd_set_pronunciation.h
-- Installing: /root/AI_/espnet/tools/include/openjtalk/njd_set_unvoiced_vowel.h
-- Installing: /root/AI_/espnet/tools/include/openjtalk/text2mecab.h
make[1]: Leaving directory '/root/AI_/espnet/tools/open_jtalk/src/build'
Cloning into 'pyopenjtalk'...
remote: Enumerating objects: 28, done.
remote: Counting objects: 100% (28/28), done.
remote: Compressing objects: 100% (20/20), done.
remote: Total 202 (delta 9), reused 21 (delta 8), pack-reused 174
Receiving objects: 100% (202/202), 6.50 MiB | 4.54 MiB/s, done.
Resolving deltas: 100% (65/65), done.
Obtaining file:///root/AI_/espnet/tools/pyopenjtalk
Requirement already satisfied: numpy>=1.8.0 in /root/anaconda3/envs/espnet_env/lib/python3.7/site-packages (from pyopenjtalk==0.0.3+a3d30a6) (1.19.1)
Requirement already satisfied: cython>=0.21.0 in /root/anaconda3/envs/espnet_env/lib/python3.7/site-packages (from pyopenjtalk==0.0.3+a3d30a6) (0.29.21)
Requirement already satisfied: six in /root/anaconda3/envs/espnet_env/lib/python3.7/site-packages (from pyopenjtalk==0.0.3+a3d30a6) (1.15.0)
Installing collected packages: pyopenjtalk
  Running setup.py develop for pyopenjtalk
Successfully installed pyopenjtalk
touch pyopenjtalk.done

**Comment by ymzlygw** [comment]
### There are  installed successfully information:
~/AI_/espnet/tools# make pyopenjtalk.done
. ./activate_python.sh && ./installers/install_pyopenjtalk.sh
Cloning into 'hts_engine_API'...
remote: Enumerating objects: 53, done.
remote: Counting objects: 100% (53/53), done.
remote: Compressing objects: 100% (35/35), done.
remote: Total 1040 (delta 32), reused 35 (delta 17), pack-reused 987
Receiving objects: 100% (1040/1040), 396.10 KiB | 732.00 KiB/s, done.
Resolving deltas: 100% (774/774), done.
Setting top to                           : /root/AI_/espnet/tools/hts_engine_API/src 
Setting out to                           : /root/AI_/espnet/tools/hts_engine_API/src/build 
Checking for waf version in 1.7.11-2.1.0 : ok 
Checking for 'gcc' (C compiler)          : /usr/bin/gcc 
Checking for header stdlib.h             : yes 
Checking for header string.h             : yes 

hts_engine_API has been configured as follows:

[Build information]
Package:                 hts_engine_API-1.0.9
build (compile on):      x86_64-linux
host endian:             little
Compiler:                gcc
Compiler version:        7.5.0
CFLAGS:                  -O2 -Wall -fno-common -Wstrict-prototypes

'configure' finished successfully (0.195s)
Waf: Entering directory `/root/AI_/espnet/tools/hts_engine_API/src/build'
/usr/bin/gcc
/usr/bin/gcc
[ 1/14] Compiling lib/HTS_pstream.c
[ 2/14] Compiling lib/HTS_gstream.c
[ 3/14] Compiling lib/HTS_audio.c
[ 4/14] Compiling lib/HTS_model.c
[ 5/14] Compiling lib/HTS_label.c
[ 6/14] Compiling lib/HTS_sstream.c
[ 7/14] Compiling lib/HTS_misc.c
[ 8/14] Compiling lib/HTS_engine.c
[ 9/14] Compiling lib/HTS_vocoder.c
[10/14] Compiling bin/hts_engine.c
[11/14] Compiling hts_engine_API.pc.in
../lib/HTS_model.c: In function ‘HTS_ModelSet_load’:
../lib/HTS_model.c:1165:27: warning: self-comparison always evaluates to false [-Wtautological-compare]
             if (is_msd[j] != is_msd[j])
                           ^~

[12/14] Linking build/lib/libhts_engine_API.so
[13/14] Linking build/bin/hts_engine
[14/14] Symlinking build/lib/libhts_engine_API.so
Waf: Leaving directory `/root/AI_/espnet/tools/hts_engine_API/src/build'
'build' finished successfully (0.660s)
Waf: Entering directory `/root/AI_/espnet/tools/hts_engine_API/src/build'
/usr/bin/gcc
/usr/bin/gcc
+ install /root/AI_/espnet/tools/lib/libhts_engine_API.so.1.0.9 (from build/lib/libhts_engine_API.so)
+ symlink /root/AI_/espnet/tools/lib/libhts_engine_API.so.1 (to libhts_engine_API.so.1.0.9)
+ install /root/AI_/espnet/tools/bin/hts_engine (from build/bin/hts_engine)
+ install /root/AI_/espnet/tools/include/HTS_hidden.h (from lib/HTS_hidden.h)
+ symlink /root/AI_/espnet/tools/lib/libhts_engine_API.so (to libhts_engine_API.so.1.0.9)
+ install /root/AI_/espnet/tools/include/HTS_engine.h (from include/HTS_engine.h)
+ install /root/AI_/espnet/tools/lib/pkgconfig/hts_engine_API.pc (from build/hts_engine_API.pc)
Waf: Leaving directory `/root/AI_/espnet/tools/hts_engine_API/src/build'
'install' finished successfully (0.017s)
Cloning into 'open_jtalk'...
remote: Enumerating objects: 1822, done.
remote: Total 1822 (delta 0), reused 0 (delta 0), pack-reused 1822
Receiving objects: 100% (1822/1822), 24.13 MiB | 8.99 MiB/s, done.
Resolving deltas: 100% (1407/1407), done.
-- The C compiler identification is GNU 7.5.0
-- The CXX compiler identification is GNU 7.5.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for include file ctype.h
-- Looking for include file ctype.h - found
-- Looking for include file dirent.h
-- Looking for include file dirent.h - found
-- Looking for include file fcntl.h
-- Looking for include file fcntl.h - found
-- Looking for include file inttypes.h
-- Looking for include file inttypes.h - found
-- Looking for include file io.h
-- Looking for include file io.h - not found
-- Looking for include file memory.h
-- Looking for include file memory.h - found
-- Looking for include file setjmp.h
-- Looking for include file setjmp.h - found
-- Looking for include file stdint.h
-- Looking for include file stdint.h - found
-- Looking for include file stdlib.h
-- Looking for include file stdlib.h - found
-- Looking for include file strings.h
-- Looking for include file strings.h - found
-- Looking for include file string.h
-- Looking for include file string.h - found
-- Looking for include file sys/mman.h
-- Looking for include file sys/mman.h - found
-- Looking for include file sys/stat.h
-- Looking for include file sys/stat.h - found
-- Looking for include file sys/times.h
-- Looking for include file sys/times.h - found
-- Looking for include file sys/types.h
-- Looking for include file sys/types.h - found
-- Looking for include file unistd.h
-- Looking for include file unistd.h - found
-- Looking for getenv
-- Looking for getenv - found
-- Looking for getpagesize
-- Looking for getpagesize - found
-- Looking for mmap
-- Looking for mmap - found
-- Looking for opendir
-- Looking for opendir - found
-- Looking for setjmp
-- Looking for setjmp - found
-- Looking for sqrt
-- Looking for sqrt - not found
-- Looking for strstr
-- Looking for strstr - found
-- Looking for iconv_open in iconv
-- Looking for iconv_open in iconv - not found
-- Looking for sqrt in m
-- Looking for sqrt in m - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of char
-- Check size of char - done
-- Check size of int
-- Check size of int - done
-- Check size of long
-- Check size of long - done
-- Check size of long long
-- Check size of long long - done
-- Check size of short
-- Check size of short - done
-- Check size of size_t
-- Check size of size_t - done
-- Configuring done
-- Generating done
-- Build files have been written to: /root/AI_/espnet/tools/open_jtalk/src/build
make[1]: Entering directory '/root/AI_/espnet/tools/open_jtalk/src/build'
make[2]: Entering directory '/root/AI_/espnet/tools/open_jtalk/src/build'
make[3]: Entering directory '/root/AI_/espnet/tools/open_jtalk/src/build'
Scanning dependencies of target openjtalk
make[3]: Leaving directory '/root/AI_/espnet/tools/open_jtalk/src/build'
make[3]: Entering directory '/root/AI_/espnet/tools/open_jtalk/src/build'
[  2%] Building C object CMakeFiles/openjtalk.dir/jpcommon/jpcommon.c.o
[  5%] Building C object CMakeFiles/openjtalk.dir/jpcommon/jpcommon_label.c.o
[  7%] Building C object CMakeFiles/openjtalk.dir/jpcommon/jpcommon_node.c.o
[ 10%] Building CXX object CMakeFiles/openjtalk.dir/mecab/src/char_property.cpp.o
[ 12%] Building CXX object CMakeFiles/openjtalk.dir/mecab/src/connector.cpp.o
[ 15%] Building CXX object CMakeFiles/openjtalk.dir/mecab/src/context_id.cpp.o
[ 17%] Building CXX object CMakeFiles/openjtalk.dir/mecab/src/dictionary.cpp.o
[ 20%] Building CXX object CMakeFiles/openjtalk.dir/mecab/src/dictionary_compiler.cpp.o
[ 23%] Building CXX object CMakeFiles/openjtalk.dir/mecab/src/dictionary_generator.cpp.o
[ 25%] Building CXX object CMakeFiles/openjtalk.dir/mecab/src/dictionary_rewriter.cpp.o
[ 28%] Building CXX object CMakeFiles/openjtalk.dir/mecab/src/eval.cpp.o
[ 30%] Building CXX object CMakeFiles/openjtalk.dir/mecab/src/feature_index.cpp.o
[ 33%] Building CXX object CMakeFiles/openjtalk.dir/mecab/src/iconv_utils.cpp.o
[ 35%] Building CXX object CMakeFiles/openjtalk.dir/mecab/src/lbfgs.cpp.o
[ 38%] Building CXX object CMakeFiles/openjtalk.dir/mecab/src/learner.cpp.o
[ 41%] Building CXX object CMakeFiles/openjtalk.dir/mecab/src/learner_tagger.cpp.o
[ 43%] Building CXX object CMakeFiles/openjtalk.dir/mecab/src/libmecab.cpp.o
[ 46%] Building CXX object CMakeFiles/openjtalk.dir/mecab/src/mecab-dict-index.cpp.o
[ 48%] Building CXX object CMakeFiles/openjtalk.dir/mecab/src/mecab.cpp.o
[ 51%] Building CXX object CMakeFiles/openjtalk.dir/mecab/src/nbest_generator.cpp.o
[ 53%] Building CXX object CMakeFiles/openjtalk.dir/mecab/src/param.cpp.o
[ 56%] Building CXX object CMakeFiles/openjtalk.dir/mecab/src/string_buffer.cpp.o
[ 58%] Building CXX object CMakeFiles/openjtalk.dir/mecab/src/tagger.cpp.o
[ 61%] Building CXX object CMakeFiles/openjtalk.dir/mecab/src/tokenizer.cpp.o
[ 64%] Building CXX object CMakeFiles/openjtalk.dir/mecab/src/utils.cpp.o
[ 66%] Building CXX object CMakeFiles/openjtalk.dir/mecab/src/viterbi.cpp.o
[ 69%] Building CXX object CMakeFiles/openjtalk.dir/mecab/src/writer.cpp.o
[ 71%] Building C object CMakeFiles/openjtalk.dir/mecab2njd/mecab2njd.c.o
[ 74%] Building C object CMakeFiles/openjtalk.dir/njd/njd.c.o
[ 76%] Building C object CMakeFiles/openjtalk.dir/njd/njd_node.c.o
[ 79%] Building C object CMakeFiles/openjtalk.dir/njd2jpcommon/njd2jpcommon.c.o
[ 82%] Building C object CMakeFiles/openjtalk.dir/njd_set_accent_phrase/njd_set_accent_phrase.c.o
[ 84%] Building C object CMakeFiles/openjtalk.dir/njd_set_accent_type/njd_set_accent_type.c.o
[ 87%] Building C object CMakeFiles/openjtalk.dir/njd_set_digit/njd_set_digit.c.o
[ 89%] Building C object CMakeFiles/openjtalk.dir/njd_set_long_vowel/njd_set_long_vowel.c.o
[ 92%] Building C object CMakeFiles/openjtalk.dir/njd_set_pronunciation/njd_set_pronunciation.c.o
[ 94%] Building C object CMakeFiles/openjtalk.dir/njd_set_unvoiced_vowel/njd_set_unvoiced_vowel.c.o
[ 97%] Building C object CMakeFiles/openjtalk.dir/text2mecab/text2mecab.c.o
[100%] Linking CXX shared library libopenjtalk.so
make[3]: Leaving directory '/root/AI_/espnet/tools/open_jtalk/src/build'
[100%] Built target openjtalk
make[2]: Leaving directory '/root/AI_/espnet/tools/open_jtalk/src/build'
Install the project...
-- Install configuration: "Release"
-- Installing: /root/AI_/espnet/tools/lib/libopenjtalk.so.1.10
-- Installing: /root/AI_/espnet/tools/lib/libopenjtalk.so
-- Set runtime path of "/root/AI_/espnet/tools/lib/libopenjtalk.so.1.10" to ""
-- Installing: /root/AI_/espnet/tools/include/openjtalk/jpcommon.h
-- Installing: /root/AI_/espnet/tools/include/openjtalk/mecab.h
-- Installing: /root/AI_/espnet/tools/include/openjtalk/mecab2njd.h
-- Installing: /root/AI_/espnet/tools/include/openjtalk/njd.h
-- Installing: /root/AI_/espnet/tools/include/openjtalk/njd2jpcommon.h
-- Installing: /root/AI_/espnet/tools/include/openjtalk/njd_set_accent_phrase.h
-- Installing: /root/AI_/espnet/tools/include/openjtalk/njd_set_accent_type.h
-- Installing: /root/AI_/espnet/tools/include/openjtalk/njd_set_digit.h
-- Installing: /root/AI_/espnet/tools/include/openjtalk/njd_set_long_vowel.h
-- Installing: /root/AI_/espnet/tools/include/openjtalk/njd_set_pronunciation.h
-- Installing: /root/AI_/espnet/tools/include/openjtalk/njd_set_unvoiced_vowel.h
-- Installing: /root/AI_/espnet/tools/include/openjtalk/text2mecab.h
make[1]: Leaving directory '/root/AI_/espnet/tools/open_jtalk/src/build'
Cloning into 'pyopenjtalk'...
remote: Enumerating objects: 28, done.
remote: Counting objects: 100% (28/28), done.
remote: Compressing objects: 100% (20/20), done.
remote: Total 202 (delta 9), reused 21 (delta 8), pack-reused 174
Receiving objects: 100% (202/202), 6.50 MiB | 4.54 MiB/s, done.
Resolving deltas: 100% (65/65), done.
Obtaining file:///root/AI_/espnet/tools/pyopenjtalk
Requirement already satisfied: numpy>=1.8.0 in /root/anaconda3/envs/espnet_env/lib/python3.7/site-packages (from pyopenjtalk==0.0.3+a3d30a6) (1.19.1)
Requirement already satisfied: cython>=0.21.0 in /root/anaconda3/envs/espnet_env/lib/python3.7/site-packages (from pyopenjtalk==0.0.3+a3d30a6) (0.29.21)
Requirement already satisfied: six in /root/anaconda3/envs/espnet_env/lib/python3.7/site-packages (from pyopenjtalk==0.0.3+a3d30a6) (1.15.0)
Installing collected packages: pyopenjtalk
  Running setup.py develop for pyopenjtalk
Successfully installed pyopenjtalk
touch pyopenjtalk.done

**Comment by kan-bayashi** [comment]
For quick fixing:
export LD_LIBRARY_PATH=/path/to/espnet/tools/lib:$LD_LIBRARY_PATH

**Comment by ymzlygw** [comment]
> For quick fixing:
> export LD_LIBRARY_PATH=/path/to/espnet/tools/lib:$LD_LIBRARY_PATH

Thanks, but after I did this and put the "export LD_LIBRARY_PATH=/root/AI_/espnet/tools/lib:$LD_LIBRARY_PATH" to the end of ~/.bashrc file and activate it,  It still have the same error. However when I try to copy the libopenjtalk.so.1.10 file to the /usr/lib/, it solves the problem. I don't know why.
