### ISSUE TITLE
Possibility to train many-to-one VC?

### ISSUE THREAD

**Issue by yl4579** [espnet/espnet#2561]
I have read the paper and found the code here: [https://github.com/espnet/espnet/tree/master/egs/arctic](https://github.com/espnet/espnet/tree/master/egs/arctic), and it seems this method requires a small amount of parallel data but generalizes very well. I was wondering if it would be possible to use TTS to generate "multiple source speakers" to "target speaker" pairs and train a many-to-one VC model with the current implementation (i.e., without any modifications). 

Because [here](https://github.com/espnet/espnet/blob/master/egs/arctic/vc1/run.sh) in line 45, it looks it can only take one source speaker. Or some modifications are required to do this? It's extremely hard to read the code and modify it (so far I got to [espnet.vc.pytorch_backend.vc.train](https://espnet.github.io/espnet/_modules/espnet/vc/pytorch_backend/vc.html#train) but I don't know how to proceed), so can you please add the feature if it's not possible with the current implementation?

**Comment by ianlane-cmu** [comment]
Hi Yinghao, a student (Naoki Tsuda) and I have tested a many-to-one VC model with the current implementation (https://github.com/espnet/espnet/tree/master/egs/arctic/vc1) and it worked reasonably well. However, we used real-speech rather than using TTS to generate "multiple source speakers".

Try out a few things and let us know what works for you.

**Comment by yl4579** [comment]
> Hi Yinghao, a student (Naoki Tsuda) and I have tested a many-to-one VC model with the current implementation (https://github.com/espnet/espnet/tree/master/egs/arctic/vc1) and it worked reasonably well. However, we used real-speech rather than using TTS to generate "multiple source speakers".
> 
> Try out a few things and let us know what works for you.

@ianlane-cmu  Hi Ian, thanks for your reply. However, in the configuration files, I didn't see any ways to make it take more than one source speaker. I was wondering if you could elaborate more on how to do many-to-one training on it?

**Comment by unilight** [comment]
Hi @yl4579 , sorry for replying this late.

> I was wondering if it would be possible to use TTS to generate "multiple source speakers" to "target speaker" pairs and train a many-to-one VC model with the current implementation (i.e., without any modifications).

I have tried to generate <natural, synthetic> parallel data pairs to train VTN and it worked well. I have actually written a paper about it: https://www.isca-speech.org/archive/VCC_BC_2020/pdfs/VCC2020_paper_36.pdf. As for extending it for many-to-one VC, I have never tried it. But, it sounds feasible to me!

> I didn't see any ways to make it take more than one source speaker. I was wondering if you could elaborate more on how to do many-to-one training on it?

I assume you have generated the TTS synthetic speech. Then I think all you need to do is to extract the features and generate the `data.json` file like this stage: https://github.com/espnet/espnet/blob/master/egs/arctic/vc1/run.sh#L197-L221. Let me know if you have further problems.

Also, I suggest you look into the VCC2020 ASR+TTS recipe: https://github.com/espnet/espnet/tree/master/egs/vcc20. It can achieve any-to-one (unseen to seen) VC, although using two models (i.e. ASR & TTS).
