### ISSUE TITLE
RuntimeError: The number of lines mismatch between: "feat.scp" and "shape.scp"

### ISSUE THREAD

**Issue by Fahim-F** [espnet/espnet#2562]
In run.sh in the commonvoice with the language=fa, the following error has occurred:

make json files
/../../espnet/egs/commonvoice/asr1/../../../utils/data2json.sh --feat dump/train_fa/deltafalse/feats.scp --bpecode data/fa_lang_char/train_fa_unigram150.model data/train_fa data/fa_lang_char/train_fa_unigram150_units.txt
/../../espnet/egs/commonvoice/asr1/../../../utils/feat_to_shape.sh --cmd run.pl --nj 1 --filetype  --preprocess-conf  --verbose 0 dump/train_fa/deltafalse/feats.scp data/train_fa/tmp-1qGUk/input_1/shape.scp
Traceback (most recent call last):
  File "/../../espnet/egs/commonvoice/asr1/../../../utils/merge_scp2json.py", line 207, in <module>
    concat[0][1], concat[count][1]
**RuntimeError: The number of lines mismatch between: "data/train_fa/tmp-1qGUk/input_1/feat.scp" and "data/train_fa/tmp-1qGUk/output/shape.scp"**

I did not change anything in the run.sh except lang=fa
How can I resolve this problem?

_Originally posted by @Fahim-F in https://github.com/espnet/espnet/issues/659#issuecomment-704858096_

**Comment by ftshijt** [comment]
Could you please simply try fix_data_dir.sh before dumping? 

The current version is working with me (in fact, I rerun it after receive your message as well). I think there might be some processing errors ahead.

**Comment by Fahim-F** [comment]
I run  fix_data_dir.sh before dump.sh , 
Also checked,  All of the preprocessing steps before this error, successfully finished. 
Would you please help me how can find the reason for the related error?

**Comment by ftshijt** [comment]
Hi Have you tried simply rerun stage 1 and stage 2?

Given the feats.scp, the shape.scp should be aligned.

**Comment by Ore-an** [comment]
Could you check the output of exp/dump_feats/train/dump_feature.*.log?

I'm pretty sure this is a problem with dump.sh:
https://github.com/espnet/espnet/blob/master/utils/dump.sh#L59
https://github.com/espnet/espnet/blob/master/utils/dump.sh#L67

While the script does have the pipefail option, I don't believe run.pl/queue.pl care about pipefails at all. All that comes after the log file is a single block to run.pl, and copy-feats.py accepts input from stdin, so even if you only get part of your feats from apply-cmvn and then it fails, copy-feats.py won't notice, return 0 and the whole script will go on without failing.
