### ISSUE TITLE
./asr.sh: line 215: utils/parse_options.sh: No such file or directory

### ISSUE THREAD

**Issue by szmmm** [espnet/espnet#2576]
Hello,

I pulled the code to my directory and modified the 'TEMPLET/asr1/db.sh' file and added a path to the dataset BABEL_106 as I am working with Tagalog.

Then I navigated into the directory 

   'espnet/egs2/babel/asr1'

and I run the command './run.sh -langs 106 --stage 1 --stop stage 1'. The error says no parse_options.sh directory. I am assuming this is Kaldi-related but I am using ESPNet2 which should be Kaldi-free. Therefore I am reporting this issue. Do I need to install Kaldi still?

**Error logs**

./asr.sh: line 215: utils/parse_options.sh: No such file or directory

**Comment by sw005320** [comment]
Check https://espnet.github.io/espnet/espnet2_tutorial.html#main-changing-from-espnet1
Kaldi-free means that we do not have use compiled Kaldi binaries, but we still use a lot of utility functions. They are very useful.

See https://espnet.github.io/espnet/installation.html#step-2-installation-espnet 
You can just clone the Kaldi repository and put a symlink.
You don't have to compile it.

**Comment by szmmm** [comment]
> Check https://espnet.github.io/espnet/espnet2_tutorial.html#main-changing-from-espnet1
> Kaldi-free means that we do not have to use compiled Kaldi binaries, but we still use a lot of utility functions. They are very useful.
> 
> See https://espnet.github.io/espnet/installation.html#step-2-installation-espnet
> You can just clone the Kaldi repository and put a symlink.
> You don't have to compile it.

Hi, I linked Kaldi to <my_espnet_root>/tools as the instruction said so, but in the kaldi directory I do not see a utils/parse_option.sh? Do I need to change this path to something else if I do not complie kaldi? Thank you!

**Comment by sw005320** [comment]
I think you don't have to do it.
https://github.com/espnet/espnet/blob/master/egs2/babel/asr1/utils should point out the directory.
If you cannot see that you'd still have some mistakes.

**Comment by szmmm** [comment]
> I think you don't have to do it.
> https://github.com/espnet/espnet/blob/master/egs2/babel/asr1/utils should point out the directory.
> If you cannot see that you'd still have some mistakes.

Thanks this makes sense. This problem is resolved

**Comment by szmmm** [comment]
Hi again, I was in directory espnet/egs2/babel/asr1, and I typed in the following:

./run.sh --langs "106" --recog "106" --stage 1 --stop-stage 1

For which I think should run stage one of the recipe. However I get the following feed back: 

```
./asr.sh --lang noinfo --local_data_opts --langs 101 102 103 104 105 106 202 203 204 205 206 207 301 302 303 304 305 306 401 402 403 --recog 107 201 307 404 --use_lm true --lm_config conf/train_lm.yaml --token_type char --feats_type raw --nlsyms_txt data/nlsym.txt --asr_config conf/train_asr.yaml --inference_config conf/decode_asr.yaml --train_set train --valid_set dev --test_sets dev_404 eval_404 dev_307 eval_307 dev_201 eval_201 dev_107 eval_107 --srctexts data/train/text --langs 106 --recog 106 --stage 1 --stop-stage 1
./asr.sh: invalid option --langs
```

It looks like langs is not properly taken as input. What could be the source of the the error?

**Comment by kamo-naoyuki** [comment]
Please read the script before asking. 

The script doesn't take --langs option and --recog option. The README saying is wrong. You need to rewrite run.sh to give the arguments due to the restriction of parse_options.sh.
