### ISSUE TITLE
spent too long time on stage “ASR Collect  stats” 

### ISSUE THREAD

**Issue by JucyCherry** [espnet/espnet#2577]
Hi ~ I've been running the script of egs2/librispeech.
Running Step 9 “ASR Collect stats” took more than two days and is still running, it seems too long for a training of 30 hours‘ data; What could be the problem？

**Comment by kamo-naoyuki** [comment]
File IO speed is slow, or your process is hangup by some reason?

**Comment by JucyCherry** [comment]
Thanks~ i've found the error.
This stage could not continue running because several process reported an error：“**RuntimeError: DataLoader worker (pid 28581) is killed by signal: Bus error. It is possible that dataloader's workers are out of shared memory. Please try to raise your shared memory limit**.” 
rerun the docker container with “docker run --shm-size 8G  ” and solve the problom
