### ISSUE TITLE
Getting CUDA error 

### ISSUE THREAD

**Issue by Arafat4341** [espnet/espnet#2578]
I am trying to install espnet on my gpu machine. 
I installed cuda successfully and then I ran `. ./setup_cuda_env.sh /usr/local/cuda`.
Which returned result: `CUDA_HOME=/usr/local/cuda`.
But Then I tried to install espnet by running `make`. I get the following error:

```
[ -n "" ] || { echo -e "Error: CUDA_HOME is not set.\n    $ . ./setup_cuda_env.sh <cuda-root>"; exit 1; }
-e Error: CUDA_HOME is not set.
```
Would anyone kindly tell me why is this happening ?
Thanks in advance!

**Comment by kamo-naoyuki** [comment]
Make sure your environment variable CUDA_HOME is set in such case. 

echo $CUDA_HOME

**Comment by Arafat4341** [comment]
I did make sure by `echo $CUDA_HOME` which's value is: `/usr/local/cuda`.
Still getting:
```
[ -n "" ] || { echo -e "Error: CUDA_HOME is not set.\n    $ . ./setup_cuda_env.sh <cuda-root>"; exit 1; }
-e Error: CUDA_HOME is not set.
```

**Comment by kamo-naoyuki** [comment]
Hmm, it's really strange. I can't believe it. Try the following.

CUDA_HOME=/usr/local/cuda make

**Comment by Arafat4341** [comment]
Did that. Still no luck :( 
```
[ -n "" ] || { echo -e "Error: CUDA_HOME is not set.\n    $ . ./setup_cuda_env.sh <cuda-root>"; exit 1; }
-e Error: CUDA_HOME is not set.
    $ . ./setup_cuda_env.sh <cuda-root>
Makefile:73: recipe for target 'showenv' failed
make: *** [showenv] Error 1
```

**Comment by kamo-naoyuki** [comment]
I have no idea for it. If such issue really exists, even your unix system never work.

Which make do you use? make --version

**Comment by Arafat4341** [comment]
```GNU Make 4.1```

**Comment by Arafat4341** [comment]
I know it is weird! 
Besides I got 7 / 8 libraries are correctly installed except of cupy.

**Comment by Arafat4341** [comment]
By the way my cuda version is 10.1
Is this the problem ?

**Comment by kamo-naoyuki** [comment]
You can ignore cupy for now.

**Comment by Arafat4341** [comment]
I also face another problem. When I try to install pyopenjtalk I get
```RuntimeError: Cython is required to generate C++ code
```
Where Cython is clearly installed in my environment.
Anyways thanks a lot for your response!
