### ISSUE TITLE
How to cast DistributedDataParallel object to ESPnetASRModel object in ESPnet2 ?

### ISSUE THREAD

**Issue by hchung12** [espnet/espnet#2579]
I am working on distributed self-training using ESPnet2.

For distributed training in ESPnet2, "ESPnetASRModel" object is wrapped using  torch.nn.parallel.DistributedDataParallel module like below.
"dp_model = torch.nn.parallel.DistributedDataParallel"

However, to perform inference in the distributed training.
The "dp_model" has to be cast to original "ESPnetASRModel" class.

I tried this cast like below
def stt( asr_model: torch.nn.Module, batch,... )
  asr_model.__class__ = ESPnetASRModel
  decoder = asr_model.decoder

But, It raises exception. "AttributeError: 'DistributedDataParallel' object has no attribute 'decoder'"

Any idea to do such casting ?

**Comment by kamo-naoyuki** [comment]
I'm not sure what you want to do.
Do you mean that you are rewriting espnet2/train/trainer.py to invoke inference part in it?

**Comment by hchung12** [comment]
Yes, I inherit the Trainer class to handle both labeled corpus and unlabeled corpus, and modify Speech2Text class in the asr_inference.py to input currently trained model like below.

class Speech2Text:
    """Speech2Text class

    def __init__(
        self,
         asr_model: torch.nn.Module,
#      asr_train_config: Union[Path, str],
#     asr_model_file: Union[Path, str] = None,
       ....

        # 1. Build ASR model
        asr_model.to(dtype=getattr(torch, dtype)).eval()

        scorers = {}

        asr_model.__class__ = ESPnetASRModel
       decoder = asr_model.decoder  # It raises exception.

The inherited trainer load unlabeled and unlabeled batch data in a interleaved way.
For labeled batch, it just run supervised training. 
For unlabeled batch, the inherited trainer first tries to generate pseudo labels using inference part with the currently trained model, and then performs supervised training with the pseudo labels.

**Comment by hchung12** [comment]
I think I fixed it with the following code.

asr_model = asr_model.module
asr_model.__class__ = ESPnetASRModel
