### ISSUE TITLE
Generating empty files when running egs/ljspeech/tts1

### ISSUE THREAD

**Issue by 121898** [espnet/espnet#2581]
Hi,
       When I tried to run the egs/ljspeech/tts1 recipe and decode the trained model, I met the problem that the output of tts_decode is nearly empty, which makes the following synthesis also empty
![image](https://user-images.githubusercontent.com/73097599/96411766-977e8400-121b-11eb-9f56-59614496ba5c.png)

      Anyone could help to explain this failure? (I used the latest espnet which is installed from the master branch).
Thanks a lot!

**Comment by kan-bayashi** [comment]
I'm not sure what is happened.
Could you check the attention weight and stop probability visualization in decoding folder?
And recently I move on the ESPnet2-based TTS. 
If you want use the latest model such as fastspeech2, please try ESPnet2-TTS.
https://github.com/espnet/espnet/tree/master/egs2/TEMPLATE/tts1

**Comment by wsstriving** [comment]
> I'm not sure what is happened.
> Could you check the attention weight and stop probability visualization in decoding folder?
> And recently I move on the ESPnet2-based TTS.
> If you want use the latest model such as fastspeech2, please try ESPnet2-TTS.
> https://github.com/espnet/espnet/tree/master/egs2/TEMPLATE/tts1
The attention weight seems normal, I think it might be the problem of model averaging (not sure why). If I change the model from model_average_best to model_best (set n_average=0), everything works fine.

**Comment by kan-bayashi** [comment]
> The attention weight seems normal, I think it might be the problem of model averaging (not sure why). If I change the model from model_average_best to model_best (set n_average=0), everything works fine.

I see. Thank you for your report.
