### ISSUE TITLE
Language Models for Machine Translation Decoding

### ISSUE THREAD

**Issue by Uncertain-Quark** [espnet/espnet#2582]
I am relatively new to espnet. So incase this has already been addressed, I apologise for it.

I was trying to include a transformer LM as the language model to my Machine Translation model. However, found the in version 0.9.3 of the mt_trans.py, there is no option to include a language model altogether. Is there any specific reason for not having an option to include a Language Model.

` # rnnlm related
    parser.add_argument(
        "--rnnlm", type=str, default=None, help="RNNLM model file to read"
    )
    parser.add_argument(
        "--rnnlm-conf", type=str, default=None, help="RNNLM model config file to read"
    )
    parser.add_argument("--lm-weight", type=float, default=0.0, help="RNNLM weight")`

The above code block has been removed in the latest version of mt_trans.py. Is there any other way I can integrate a Language Model into Machine Translation Decode.

Also I am unable to use transformer LM for Machine Translation in versions 0.8.0 and lower. However, I am able to use an RNNLM on the other hand. Will there be inclusion for transformer LM for Machine Translation in the future?

Thank you

**Comment by hirofumi0810** [comment]
@Uncertain-Quark I recently removed the LM option for MT because it gives litter gains in general.
Instead, I will add knowledge distillation and back translation options in the future.

**Comment by Uncertain-Quark** [comment]
I observed the same that there was very little gain and was doubtful if I committed some error in implementation. Thank you for the reply.
