### ISSUE TITLE
TTS. FastSpeech2. Terrible speech for long utterances.

### ISSUE THREAD

**Issue by RuslanSel** [espnet/espnet#2584]
Hi @kan-bayashi,

Thank you. You are really doing a great job.

I trained phoneme-based Tacotron2 espnet2 model with ParallelWaveGAN vocoder on non-English single speaker dataset and it works and sounds very well.

Then I trained phoneme-based FS2 model according to https://github.com/espnet/espnet/tree/master/egs2/TEMPLATE/tts1#... and I have problems with this model.

If sentence short (less than 10 seconds) - it works fine. For longer sentences it produce terrible speech. Very fast, squeezed, with missed words and cutted phonemes. Where Tacotron2 gives 20 seconds of speech, FS2 tries to squeeze it into 10 seconds.

**Comment by kan-bayashi** [comment]
Hi @RuslanSel.
Which ESPnet version did you use?
There is a serious bug in the calculation of energy (#2469), which is fixed in v.0.9.3.
Maybe this is the reason of the failure of the long speech.
(After fixing this bug, I confirmed that fastspeech2 can generate over 60 seconds utterance well.)

**Comment by RuslanSel** [comment]
Thanks for quick reply.
ESPnet2.

**Comment by kan-bayashi** [comment]
I mean the version of toolkit (e.g. `python -c "import espnet; print(espnet.__version__)"`)

**Comment by RuslanSel** [comment]
0.7.0
20b0c89369d9dd3e05780b65fdd00a9b4f4891e5

**Comment by RuslanSel** [comment]
20b0c89369d9dd3e05780b65fdd00a9b4f4891e5 - commit used for training
0.9.4 - version used for decoding

**Comment by kan-bayashi** [comment]
Hmm. If you confirm the energy extraction is already fixed before the training, I have no clear answer for this problem.
Why don't you try Conformer-FastSpeech2?
In my experiments, it is better than FastSpeech2 especially in the case of very long speech generation (over 1 minute).

**Comment by RuslanSel** [comment]
I'll check again. Maybe the training was really on the old version.

**Comment by RuslanSel** [comment]
Seems like the training was after the bug fix.
I'll try Conformer-FastSpeech2.
Thanks.
