### ISSUE TITLE
Multi-speaker espnet2 random speaker output

### ISSUE THREAD

**Issue by BasmaOUKIT** [espnet/espnet#2585]
@kan-bayashi I am working with espnet2 English  models
[https://colab.research.google.com/github/espnet/notebook/blob/master/espnet2_tts_realtime_demo.ipynb#scrollTo=MuhqhYSToxl7](url) and the output is random (both tacotron and transformer), each time it gives a different speaker, is there any way to control the speaker beside using x-vectors?

**Comment by kan-bayashi** [comment]
The use of x-vector is not supported in ESPnet2 since it requires kaldi.

> each time it gives a different speaker, 

You mean the eve if you use the same utterances for the reference, the speaker becomes different?

**Comment by BasmaOUKIT** [comment]
Yes exactly, when I run the inference even with different utterances, each time it gives me a different speaker (both male and female voices), I can't find where to change the code so I can define what speaker I want in the output.

**Comment by kan-bayashi** [comment]
Let me confirm again.
Did you use the same `speech` in the notebook for each inference?
Did you use your own query speech?

**Comment by BasmaOUKIT** [comment]
I did use the same speech in the notebook, and experimented with different query speech , still gives random speakers. Thank you @kan-bayashi .

**Comment by kan-bayashi** [comment]
By introducing x-vector, this problem seems to be fixed.
#2764
