### ISSUE TITLE
Question about JVS RECIPE

### ISSUE THREAD

**Issue by ymzlygw** [espnet/espnet#2591]
Hi,  after I finished the JVS adaptation under the guide at https://github.com/espnet/espnet/tree/master/egs2/jvs/tts1 ,
I have some question about usage of fine-tuned model. 
#### 1.  JVS adaptation to the combination of all speakers or only  single speaker? 
Because in the JVS recipe, I don't find any argument to specify speaker id and in exp/tts_fintune_jsut_pretrained_tacotron2/decode_train.loss.ave/jvs010_eval1/wav  , it generated some mixed sound , the sample at https://drive.google.com/file/d/1Dw_Vd7HsD7rgajlljHbv9wfvv6rj05WJ/view?usp=sharing . So does JVS recipe fine-tune all the 100 speakers in JVS corpus and generate a mixed sound?
#### 2. The usage of fine-tuned model.
Can I use the fine-tuned model just like the usage of tts_model in Real-time TTS demo with ESPnet2 demo?

**Comment by kan-bayashi** [comment]
> So does JVS recipe fine-tune all the 100 speakers in JVS corpus and generate a mixed sound?

No. Single speaker. You can find the parameter `spk` in `run.sh`
https://github.com/espnet/espnet/blob/436cda87b05528356e0b40121383964841dfc6dc/egs2/jvs/tts1/run.sh#L21

> Can I use the fine-tuned model just like the usage of tts_model in Real-time TTS demo with ESPnet2 demo?

Of course.

**Comment by ymzlygw** [comment]
> > So does JVS recipe fine-tune all the 100 speakers in JVS corpus and generate a mixed sound?
> 
> No. Single speaker. You can find the parameter `spk` in `run.sh`
> https://github.com/espnet/espnet/blob/436cda87b05528356e0b40121383964841dfc6dc/egs2/jvs/tts1/run.sh#L21
> 
> > Can I use the fine-tuned model just like the usage of tts_model in Real-time TTS demo with ESPnet2 demo?
> 
> Of course.

Thanks , I'll try it again.
