### ISSUE TITLE
Can CTC align with token

### ISSUE THREAD

**Issue by s920128** [espnet/espnet#2592]
If I use spm_train and spm_encode, i.e. sentencepiece, in ESPNET.
The dictionary is subword units based or tokens.
Can I use ctc_segmentation directly (like tedlium2 example)?
It seems to be possibly raise "Audio is shorter than text!" error, where number of tokens is less than frame but  len(ground_truth) > lpz.shape[0]. (because len(ground_truth) is length of string)

**Comment by lumaku** [comment]
CTC segmentation also works with tokens, as long as the input string can be partitioned into these tokens with regular string comparisons.

Your issue sounds like there are long tokens in the dictionary. The error "Audio is shorter than text" appears when the `len(ground_truth)` in `prepare_text()` is longer than the number of frames.

I suspect that that there are longer tokens in your dictionary, such as "\<space\>" instead of just " ", which increase the length of ground truth. Could you show the dictionary (`config.char_list`)?

**Comment by s920128** [comment]
Yes , there are longer tokens in my dictionary.
```
char_list = [ "<blank>",
            "<unk>",
            "'",
            "0",
            "1",
            "10",
            "14",
            "15",
            "2",
            "3",
            "35",
            "4",
            "5",
            "50",
            "6",
            "7",
            "9",
            "<v-noise>",
            "[UNK]",
            "_",
            "a",
            "aa",
            "ab",
            "abandon",
            "abandoned",
            "abdomen",
            "abilities",
            "ability",
            "able",
            "about",
            "above",
            "absent",
            "absolute",
            "absorbed",
            ... ,
            "▁a",
            "▁aa",
            "▁aad",
            "▁ab",
            "▁aba",
            "▁abb",
            "▁abi",
            "▁ability",
            "▁able",
            "▁ables",
            "▁ably",
            "▁abo",
            "▁ac",
             etc.]
``` 
This is the information of the utterance, which raise "Audio is shorter than text!".
INFO: CTC segmentation of 52 chars to 1.84s audio (46 indices).
```
In data_json: 
    shape": [11, 12309],
    "text": "所 以 i am very surprised that i passed everything",
    "token": "所 以 i am very surprise ▁d that i passed everything",
    "tokenid": "10653 9722 2628 213 5925 5396 6785 5558 2628 3986 1911"
```

**Comment by lumaku** [comment]
The current implementation aligns each character to an audio frame. This method can handle many different dictionaries and is also compatible with tokenized text, as the text can be partitioned using string operations. As the algorithm shall be able to support many different dictionaries, e.g. with different blanks and sometimes unknown space chars, this is a complex issue.

Aligning chars to audio frames runs into a limitation, as you see in your short audio file: The length of the audio is shorter than the number of characters in the sequence. It's even worse considering that tokens are counted by their full length.

I can provide some functions in the next version of `ctc-segmentation` python package that mitigate this issue. However, if you know that your text contains only tokens that are separated by spaces and you want to align each token, it would be better to have a separate version of `prepare_text()` for already tokenized text.

For a quick mitigation for TEDlium, maybe it helps to re-name the most used non-char tokens to an unused single character that is not in your character list (in `align.py` at config), for example, blank:
```python
config.blank = "•"
config.char_list[0] = config.blank
```

**Comment by lumaku** [comment]
@s920128 I updated the CTC segmentation package [with a new option](https://github.com/lumaku/ctc-segmentation/blob/5b1a613a267df3dead4eea8bbd393209a208bac4/ctc_segmentation/ctc_segmentation.py#L47): `config.replace_spaces_with_blanks`. The default setting is True; that means that between words a space placeholder is inserted; this space placeholder does not need to be the space in the dictionary. Set it to False; This may help to reduce the length of your `ground_truth`.

**Comment by s920128** [comment]
Maybe in my experiment, some token have longer length such that the `ground_truth` large than frame.
so, I skip these utt for now.
Thank you for your help!

**Comment by lumaku** [comment]
OK, you should check the alignments. If the ground truth of an utterance is too long, the ending time and utterances after it may be misaligned. If you plan to write a `prepare_text()` for tokenized text, I can help you.

**Comment by s920128** [comment]
if I write a `prepare_text()` for tokenized text.
How should I modify from this `prepare_text()` ?
Should I change the `ground_truth` (in `prepare_text()`) to a list?

**Comment by lumaku** [comment]
Yes, you could modify `ground_truth` as list containing the token indices.

prepare_text() has two outputs, `ground_truth_mat` and `utt_begin_indices`. In your example `所 以 i am very surprise ▁d that i passed everything"` a possible output for your `prepare_text()` could look like this:

```
ground_truth_mat = np.array([[-1], [10653], [0], [9722], [0], [2628], [0], [213], [0], [5925], [0], [5396], [6785], [0], [5558], [0], [2628], [0], [3986], [0], [1911], [0]])
utt_begin_indices = [1]
# Or, alternatively, if you want to align each token separately.
utt_begin_indices = [1, 3, 5, ...]
```
 In this example I put blanks [0] in between the tokens for more flexibility, but not in between surprise and ▁d as its one word. You could also omit all blanks except: the first and the last one and the blank between each utterance. 

As I don't have your data or any token-based model at hand, I currently can't test this. Try out what works better.

**Comment by s920128** [comment]
I modify my `prepare_text()` output look like this:
```
ground_truth_mat = np.array([[-1], [10653], [0], [9722], [0], [2628], [0], [213], [0], [5925], [0], [5396], [6785], [0], [5558], [0], [2628], [0], [3986], [0], [1911], [0]])
# Or, alternatively, if you want to align each token separately.
utt_begin_indices = [1, 3, 5, ...]
````
but every token will have same duration  time (following example is 0.18) and  have small confidence score
```
NC12M-06NC12MAY_0101-00162-00459-0000 NC12M-06NC12MAY_0101-00162-00459 0.02 0.10 -9.622068405 
NC12M-06NC12MAY_0101-00162-00459-0001 NC12M-06NC12MAY_0101-00162-00459 0.10 0.18 -10.283547401 
NC12M-06NC12MAY_0101-00162-00459-0002 NC12M-06NC12MAY_0101-00162-00459 0.18 0.26 -9.723757744 
NC12M-06NC12MAY_0101-00162-00459-0003 NC12M-06NC12MAY_0101-00162-00459 0.26 0.34 -9.694031715 
```
state_list may like (doesn't have  self_transition 'ε' almost)
```
state_list = ['', '所', '•', '以', '•', 'i', '•', 'am', '•', 'very ', '•', 'surprise ', '▁d', 'that ', '•', 'i', '•', 'passed ', '•', '▁everything', '•' ,'' , '' , ...]
```
Should I modify the other part of `ctc_segmentation` ?
Whether the token (with length of 1) cause bad effect to alignment ?

**Comment by lumaku** [comment]
You don't need to change `ctc_segmentation()`. As you say, the ε is only rarely in the state_list, there is little freedom to align the segments. The low score indicates that at least one of the tokens is misaligned. It might help to remove the blank '•' between the words in this case. The blank helps to cover pauses between words, but in this case, there is no or almost no pause between tokens.

Pro Tip: You can listen to the segments and check whether they are correct using the sox audio player:
``` sh
play $audio_file trim 0.50 =2.00
```

**Comment by s920128** [comment]
I think I have succeeded.
Thanks for your help!

**Comment by lumaku** [comment]
@s920128 If your `prepare_text()` for tokenized text works, please consider to share the source code here in the issue or submit a pull request at https://github.com/lumaku/ctc-segmentation. Thanks!

**Comment by s920128** [comment]
Here is my `prepare_text()` for tokenized_text.
I am not sure if using the `config.tokenized_text` implement in the original `prepare_text()` is a good choice, so I wrote it as an independent function.
```
def prepare_tokenized_text(config, text, char_list=None):
    """Prepare the given tokenized text for CTC segmentation.
    """
    # temporary compatibility fix for previous espnet versions
    if type(config.blank) == str:
        config.blank = 0
    if char_list is not None:
        config.char_list = char_list
    blank = config.char_list[config.blank]
    ground_truth = [config.start_of_ground_truth]
    utt_begin_indices = []
    for utt in text:
        # One space in-between
        if not ground_truth[-1] == config.space:
            ground_truth += [config.space]
        # Start new utterance remember index
        utt_begin_indices.append(len(ground_truth) - 1)
        # Add tokens of utterance
        for token in utt.split():
            if token.isspace() and config.replace_spaces_with_blanks:
                if not ground_truth [-1] == config.space:
                    ground_truth += [config.space]
            elif token in config.char_list and token not in config.excluded_characters:
                ground_truth += [utt]
    # Add space to the end
    if not ground_truth [-1] == config.space:
        ground_truth += [config.space]
    logging.debug(f"ground_truth: {ground_truth}")
    utt_begin_indices.append(len(ground_truth) - 1)
    # Create matrix: time frame x number of letters the character symbol spans
    max_char_len = 1
    ground_truth_mat = np.ones([len(ground_truth), max_char_len], np.int) * -1
    for i in range(len(ground_truth)):
        if ground_truth[i] == config.space:
            ground_truth[i] == config.blank
        if ground_truth[i] in config.char_list:
            char_index = config.char_list.index(ground_truth[i])
            ground_truth_mat[i, 0] = char_index
        elif ground_truth[i] == config.space:
            ground_truth_mat[i, 0] = 0
    return ground_truth_mat, utt_begin_indices
```

**Comment by lumaku** [comment]
Looks already good. I is OK for now as independent function, but as both functions have much overlap, we can decide whether to merge those functions when they are more stable.

Some remarks:
For a sequence that was already split into tokens, `config.excluded_characters` should not be important. The function `split()` removes all spaces, but to determining whether there is a space beween tokens, the second token can be checked for the meta symbol `▁` as described in [sentencepiece](https://github.com/google/sentencepiece) (they write that is inserted instead of space, but not as connector....?). Also, the last part can be simplified a bit.

I made a branch for this and added you in the commit:
https://github.com/lumaku/ctc-segmentation/tree/prepare_tokenized_text
Could you test how this works for you? Thanks!
