### ISSUE TITLE
On the fly feature extraction & text preprocessing for training

### ISSUE THREAD

**Issue by 30stomercury** [espnet/espnet#2594]
As mentioned in [https://espnet.github.io/espnet/espnet2_tutorial.html](url), espnet2 supports on the fly feature extraction pipeline. However, related usage is not specified in the config. Is this function currently available?

Thanks!

**Comment by sw005320** [comment]
The JSUT ASR recipe includes such configs, e.g., 
https://github.com/espnet/espnet/blob/master/egs2/jsut/asr1/conf/tuning/train_asr_conformer.yaml#L3-L8

**Comment by kamo-naoyuki** [comment]
You can view all configurable parameters by --print_config option.

https://espnet.github.io/espnet/espnet2_training_option.html#show-usage

**Comment by 30stomercury** [comment]
Hi @sw005320 , @kamo-naoyuki , thanks for your reply. 
I read the config you provided [https://github.com/espnet/espnet/blob/436cda87b05528356e0b40121383964841dfc6dc/egs2/jsut/asr1/conf/tuning/train_asr_conformer.yaml#L5](https://github.com/espnet/espnet/blob/436cda87b05528356e0b40121383964841dfc6dc/egs2/jsut/asr1/conf/tuning/train_asr_conformer.yaml#L5). I noticed the conformer use 80-channel filterbanks features computed from a 25ms window with a stride of 10ms in their paper. However, the `win_length` and `hop_length` specified in the config are much larger. 
Why on the fly feature extraction requires larger `hop_length`? What about the performance difference between model using features and on the fly feature extraction setup.

Thank you for your precious time.

**Comment by kamo-naoyuki** [comment]
win_length=400 exactly corresponds to 25ms (=400/16000) and 160 corresponds to 10ms.

**Comment by 30stomercury** [comment]
I see! Thanks, I'll close this issue.
