### ISSUE TITLE
Speech recognition from raw audio using Lightweight Sinc Convolutions

### ISSUE THREAD

**Issue by lumaku** [espnet/espnet#2595]
I am happy to share our work on speech recognition from raw audio data, presented on INTERSPEECH 2020:
https://arxiv.org/abs/2010.07597
In it, we describe Lightweight Sinc Convolutions (LSC), a small module that works well for classification directly on raw audio.

You can browse the code here:
https://github.com/lumaku/espnet/tree/lightweight_sinc_convolutions
The code includes the integration of LSC into RNN models and Transformer models, as well as the recipes for TEDlium2, TIMIT and Librispeech.

@sw005320  If it's OK for you and you want to include it in ESPnet, I can prepare a pull request in the next days.

**Comment by sw005320** [comment]
That's very cool.
Yes, it would be great if you make a PR.
ASR from time-domain signals is one of the missing functions of espnet.
We could also combine some of our recent comforter efforts.

**Comment by Fhrozen** [comment]
@lumaka Thank you for sharing an interesting new proposal.
I would like to ask about the SincNet part. Did it take long for training? Did you compare the time for training on SincNet with a model without it?

BTW, about the data preparation, you could use the dump_pcm that ESPnet already has implemented and then match it with the transformation layer.
You can have an example of this: 
https://github.com/Fhrozen/espnet/blob/291f32969ce3000d97a5bef5ce8cc040020fca8f/egs/fearless/wav_asr2/run.sh#L80-L141

Transformation layer:
https://github.com/Fhrozen/espnet/blob/tst-fs02/espnet/transform/wave.py

**Comment by lumaku** [comment]
Yes, there is an increase in training time, but I did not yet measure by how much; it seemed moderate to me. As there are more layers, GPU memory consumption is increased, the batch size is reduced.

LSC has similarities to SincNet, but I'd like to emphasize that there are key differences between SincNet and LSC, mainly depthwise convolutions and log compression. LSC is optimized as lightweight input module to an end-to-end network.

My observation is that when the grouping in the depthwise convolutional layers is reduced - leading to a network that is more similar to SincNet - the complexity increases (memory consumption and training time). I think that the authors of the E2E-SincNet paper met the same problem and tried to mitigate using longer-time input context.

Also, @Fhrozen  thank you for the helpful suggestion on how to integrate this in the toolkit. I think that the dump_pcm is suitable and should be easy to port as it's similar to how we solved it.

It would make sense to pass configuration parameters to the input module (e.g. number of layers etc). I would tend to pass a string of a parseable python dictionary for flexibility. Do you have any preferences on this, alternatives, or maybe already a similar implementation?

**Comment by Fhrozen** [comment]
Arguments are usually set at the net argument definition. 
For RNN you can check here: https://github.com/espnet/espnet/blob/436cda87b05528356e0b40121383964841dfc6dc/espnet/nets/pytorch_backend/rnn/argument.py#L7
For transformer: https://github.com/espnet/espnet/blob/436cda87b05528356e0b40121383964841dfc6dc/espnet/nets/pytorch_backend/transformer/argument.py#L10
You can add in each group or probably write a new group and add it to the model parser: (for Transformer) 
https://github.com/espnet/espnet/blob/436cda87b05528356e0b40121383964841dfc6dc/espnet/nets/pytorch_backend/e2e_asr_transformer.py#L60-L72

**Comment by lumaku** [comment]
@Fhrozen Sorry, I did not yet fully understand how to use `dump_pcm.sh` for this task. I'd like to have pure raw audio data frames with a certain overlap. We did not apply a windowing function to the raw audio. Our solution was to combine kaldis [`make_raw.h`](https://github.com/lumaku/espnet/blob/4752982875310a2a3bcb1634a8b15b7ccda75547/utils/make_raw.sh) with a [small python script](https://github.com/lumaku/espnet/blob/4752982875310a2a3bcb1634a8b15b7ccda75547/utils/compute-raw-feats.py) to apply windowing and write to file; it also included a `preprocess.yaml` with regular SpecAugment for training.

As I understand, the full raw data is written to file by `dump_pcm.sh` and partitioning is not yet done (or maybe I missed this). Therefore, the windowing is done as pre-step to the network, done by the `Transformation` object in `dump_pcm.py`? Is this correct?
Processes in this module are sequential, so I imagine that a possible `preprocess.yaml` for the train set looks like this:

```yaml
mode: "sequential"
process:
  - type: "wave"
    frame_length: 400
    # frame_shift = frame_length - frame_overlap (160)
    frame_shift: 240
process:
  # these three processes are a.k.a. SpecAugument
  - type: "time_warp"
    max_time_warp: 5
    inplace: true
    mode: "PIL"
  - type: "freq_mask"
    F: 30
    n_mask: 2
    inplace: true
    replace_with_zero: false
  - type: "time_mask"
    T: 40
    n_mask: 2
    inplace: true
    replace_with_zero: false
```

Would this work as I expect? If not, in which part would I have to adapt the code? Also, how does the program distinguish between training and inference with respect to `preprocess.yaml`? Please advise.

@sw005320 You were asking the question regarding subsampling at the presentation session. As there is no connection in this module between time steps, or even between features in the depthwise convolution, subsampling can only be done at the encoder or at the input layer to the encoder. Keeping features/channels and time steps separated helps to reduce training complexity. If complexity of this module is still an issue, it's possible to reduce the number of depthwise convolutions.

**Comment by Fhrozen** [comment]
@lumaku :
`dump_pcm.sh` just convert the wave files (segments) into hdf5 (with a compression level).

> Therefore, the windowing is done as a pre-step to the network, done by the Transformation object in dump_pcm.py?
No, it is not performed by dump_pcm.py. in the case of using ESPnet frontend, this is performed during training. But you will need to call it during the JSON preparation to get the dimensions. 
e.g.:
https://github.com/espnet/espnet/blob/696ad1103b1eb28295acba0d0ba0e4d1f1fca774/egs/chime4/asr1_multich/run.sh#L162-L166
with the preprocess-conf argument.

>  partitioning is not yet done (or maybe I missed this).
Yes, this is not yet implemented. You will need to add a new partitioning in the transformation folder https://github.com/espnet/espnet/tree/master/espnet/transform
You could use the code that I have tested in a different branch 
https://github.com/Fhrozen/espnet/blob/tst-fs02/espnet/transform/wave.py

> Also, how does the program distinguish between training and inference with respect to preprocess.yaml?
https://github.com/espnet/espnet/blob/696ad1103b1eb28295acba0d0ba0e4d1f1fca774/espnet/transform/spec_augment.py#L95-L102
you see that the call definition has a `train` variable.  It becomes false when recognition.

**Comment by kamo-naoyuki** [comment]
@lumaku Could you consider using espnet2? It can be more easy and simple implementation for such time domain approach.

**Comment by kamo-naoyuki** [comment]
ESPnet1 is too complex and too dirty to have more features because the initial design was not suitable for development. We shouldn't add new features any more, basically. This is the reason why we started espnet2 project. Please follow our policy.
