### ISSUE TITLE
TTS. ESPnet2. Raw or fbank.

### ISSUE THREAD

**Issue by RuslanSel** [espnet/espnet#2596]
Hi, all!

I have
./tts.sh \
    --feats_type raw \

But in exp/tts_train_tacotron2_raw_phn_none/config.yaml:
feats_extract: fbank
feats_extract_conf:
    fs: 22050
    fmin: 80
    fmax: 7600

Thanks in advance!

**Comment by kan-bayashi** [comment]
`raw` means the feature extraction will be performed on the fly during the training.
Therefore, the feature is still mel-spectrogram.
