### ISSUE TITLE
Colab demonstration multi-speaker GST TTS not varying in style

### ISSUE THREAD

**Issue by ctlaltdefeat** [espnet/espnet#2597]
**Describe the bug**
The multi-speaker model demo (https://colab.research.google.com/github/espnet/notebook/blob/master/espnet2_tts_realtime_demo.ipynb) is, as far as I understand, supposed to demonstrate the capability of varying styles (intonation, pitch, identity, etc.) by conditioning on a GST that is derived from the ```speech``` variable provided.
However, when running with different randomized ```speech``` tensors, as well as ones derived from wavs (both from the VCTK dataset and external), the style of the generated audio does not seem to change at all. The only thing that appears to make a substantial difference is the size of the ```speech``` tensor rather than its value, which does not make intuitive sense to me.

**To Reproduce**
Run the colab multi-speaker demo. I ran it initially with 
```tag = "kan-bayashi/vctk_gst_tacotron2"```
```vocoder_tag = "vctk_multi_band_melgan.v2"```
but having played with different ones, they all seem to exhibit similar issues.

As an example:
https://gofile.io/d/xlamBs

```speech_1``` and ```speech_2``` were generated using two different random speech tensors of size 20000, and sound nearly identical to each other. ```speech_3``` and ```speech_4``` were generated using two different random speech tensors of size 5000 and sound nearly identical to each other, but completely different from the other ones.

**Comment by kan-bayashi** [comment]
Thank you for your report. I will check the code in detail.

**Comment by kan-bayashi** [comment]
I checked the generated samples again, which was generated with the GT audio of the generated audio as the reference speech.
https://drive.google.com/drive/folders/1Q-CRE5LzXE0CWX_WsPoKCVeAJpib-sXj?usp=sharing
It seems the speaker's characteristics are almost the same if we give a different length sample of the same speaker (but sometimes failed).
I'm thinking about the length of the random sample.
5000 is too small (around 0.2 sec), and which might be a problem.
What is happened when using 50000 vs 100000?

**Comment by ctlaltdefeat** [comment]
> What is happened when using 50000 vs 100000?
I think they will be almost the same.

They do, but the samples also sound basically the same with different random samples for ```speech```. There seems to be some sort of mode collapse happening.

I suspect there may be two separate issues:

1) A domain mismatch between the ```randn``` samples for speech (which is normally distributed around 0 with 1 variance I believe), and the samples of speech in the dataset, which causes all the random samples to generate almost identical audio. Perhaps some sort of normalization needs to be applied?

2) Relatively poor performance for the GST style adaptation for some reason (perhaps this is expected given it's essentially zero-shot). For example, look at the samples here: https://gofile.io/d/vkp6rC
(male samples generated from ```male_speaker_24khz.wav``` and female samples from ```female_speaker_24khz.wav```)
there is at least gender separation in the samples, but the reproducibility of the intonation and pitch and accent is poor, especially for the male samples.

**Comment by kan-bayashi** [comment]
> A domain mismatch between the randn samples for speech (which is normally distributed around 0 with 1 variance I believe), and the samples of speech in the dataset, which causes all the random samples to generate almost identical audio. Perhaps some sort of normalization needs to be applied?

If we use `randn` (Gaussian noise) for the speech, I think the generated sample should be almost the same. This is because the mel-spectrogram for Gaussian noise has almost the same power in each frequency bin. The reason why I used `randn` in the notebook is just for simplification (I do not want to add extra step to prepare the reference sample), not for the generation of various speech.

> Relatively poor performance for the GST style adaptation for some reason.

I agree with this point.
Actually I did not tune the parameters of the style encoder, we need to tune it for better quality.

**Comment by ctlaltdefeat** [comment]
That makes sense.
Specifically for the task of generating audio using the style of an unseen (in training) speaker, is there currently a recipe/colab notebook that works reasonably well?

**Comment by kan-bayashi** [comment]
> Specifically for the task of generating audio using the style of an unseen (in training) speaker, is there currently a recipe/colab notebook that works reasonably well?

Actually, I checked only the speaker characteristics of training speakers since I want to use the GST model as the multi-speaker model. Do you have any suggestions to check the style similarity?

**Comment by ctlaltdefeat** [comment]
Do you mean what kind of loss to use during training?
So far I just subjectively perceive the similarity to be rather poor.

**Comment by kan-bayashi** [comment]
> Do you mean what kind of loss to use during training?
So far I just subjectively perceive the similarity to be rather poor.

Loss or objective measure.
I want to measure the style similarity using the objective measure.
(I know that is difficult, but if it can be, that is great)

**Comment by gafsd** [comment]
I also notice poor style transfer with speech when training my own multi-speaker model. I wonder if the few-shot approach from here https://arxiv.org/pdf/2005.08484.pdf is better?

**Comment by kan-bayashi** [comment]
Thanks for the info. I will check it.
