### ISSUE TITLE
i want train model  'tts_train_conformer_fastspeech2' like model zoo

### ISSUE THREAD

**Issue by wac81** [espnet/espnet#2598]
i want train model  'tts_train_conformer_fastspeech2' like model zoo

i use csmsc recipe

i find train_conformer_fastspeech2.yaml, but I can't find the corresponding decode.yaml,  just have conf/tuning/decode_fastspeech.yaml， this file is that right？

**Comment by kan-bayashi** [comment]
You can use it.

**Comment by wac81** [comment]
ok ，let me try it

**Comment by wac81** [comment]
1.i notice this stage for fastspeech2 , how to setup /path/to/teacher_dumpdir? dir default is?  tacotron2 model dir?
# 3. Calculate statistics pitch and energy features
./run.sh --stage 5 --stop-stage 5 --conf conf/tuning/train_fastspeech2.yaml --teacher_dumpdir /path/to/teacher_dumpdir --tts_stats_dir exp/tts_stats_for_fastspeech2

2. decode_fastspeech have line : # (+ pitch & energy for FastSpeech2),   i have to create **pitch & energy manually**？

**Comment by kan-bayashi** [comment]
> how to setup /path/to/teacher_dumpdir? dir default is? tacotron2 model dir?

See https://github.com/espnet/espnet/blob/master/egs2/TEMPLATE/tts1/README.md#fastspeech2-training

> i have to create pitch & energy manually？

No. You do not need.
