### ISSUE TITLE
tts_train_conformer_fastspeech2 train issue

### ISSUE THREAD

**Issue by wac81** [espnet/espnet#2602]
1.i notice this stage for fastspeech2 , how to setup /path/to/teacher_dumpdir? dir default is? Specifically tacotron2 model dir?
```
  3. Calculate statistics pitch and energy features
./run.sh --stage 5 --stop-stage 5 --conf conf/tuning/train_fastspeech2.yaml --teacher_dumpdir /path/to/teacher_dumpdir --tts_stats_dir exp/tts_stats_for_fastspeech2
```

**Comment by wac81** [comment]
Who can help？

**Comment by kan-bayashi** [comment]
See
https://github.com/espnet/espnet/blob/master/egs2/TEMPLATE/tts1/README.md#fastspeech2-training
