### ISSUE TITLE
Online ASR

### ISSUE THREAD

**Issue by 2KANGHEE-RIT** [espnet/espnet#2603]
Hi,

What is differences between streaming and online on ASR? I am trying to inference the pre-trained streaming model (tedlium.rnn.v2). I want to make it to result texts frame by frame like Siri or any speech recognition service on portable device. How can I do using ESPNET? 

Thank you in advance.

**Comment by sw005320** [comment]
There are several internal activities for it, but we don't have publicly available versions yet.
You can also check https://github.com/cywang97/StreamingTransformer

**Comment by 2KANGHEE-RIT** [comment]
> There are several internal activities for it, but we don't have publicly available versions yet.
> You can also check https://github.com/cywang97/StreamingTransformer

@sw005320 Thanks for comment and Thanks for your works. I hope it will be released public version ASAP. Then, one more question here, what does 'streaming' mean in espnet config in detail?

**Comment by sw005320** [comment]
It can accept a 'streaming' audio (long-form without segmentation), and internally perform end-point detection, and output the result. It's similar to other streaming ASR, but we did not implement the output of the intermediate result (we can take it from the CTC output), and the behavior looks different since it looks like the result in espnet is finally produced. But it would be more about the implementation issue.

**Comment by sw005320** [comment]
Check https://arxiv.org/pdf/2002.00551.pdf

**Comment by Alex-Songs** [comment]
Hello, is there a corresponding training script for  CTC-BASED VAD streaming speech recognition, such as (tedlium.rnn.v2), in ESPNET? Whether it’s just training according to the normal process during training, and CTC truncation is only required for prediction?

**Comment by Alex-Songs** [comment]
@sw005320

**Comment by sw005320** [comment]
> Hello, is there a corresponding training script for CTC-BASED VAD streaming speech recognition, such as (tedlium.rnn.v2), in ESPNET? Whether it’s just training according to the normal process during training, and CTC truncation is only required for prediction?

Yes, you can just train a model with our RNN-based config. You don't need any change during training. This is one of the unique properties of our CTC-based VAD.

**Comment by Alex-Songs** [comment]
Thank you very much for your answers. I have another question: The CTC-BASED VAD method is similar to the CTC triggered_attention, and the CTC triggered_attention needs to use a non-streaming model to obtain the trigger point through Viterbi or forward-backward algorithms. Then why CTC-BASED VAD does not need it? @sw005320

**Comment by sw005320** [comment]
If we get accurate alignment information, it would be better to use Viterbi or forward-backward. If the task is to simply find the long silence region, CTC greedy decoding (shown in CTC-based VAD) is good enough.

**Comment by Alex-Songs** [comment]
Thank you very much for your answers! @sw005320

**Comment by Daniel-asr** [comment]
Is there currently a streaming solution implemented for a model I trained on ESPnet - one that outputs intermediate transcriptions during speech?

I checked https://github.com/cywang97/StreamingTransformer but I wanted to check if there is more native option already implemented on ESPnet.

TIA
