### ISSUE TITLE
wav2vec 2.0

### ISSUE THREAD

**Issue by dqqcasia** [espnet/espnet#2609]
Do you plan to support the pre-trained models of wav2vec 2.0?

**Comment by sw005320** [comment]
Yes, we're working on it.

**Comment by oadams** [comment]
Hi Shinji, just curious to know if there's any active work on this feature?

Hope you're save and doing well over the holiday period.

**Comment by sw005320** [comment]
@simpleoier finishes to import a pre-trained model and now he is testing fine-tuning. Once we make it work, we'll make a PR.

**Comment by simpleoier** [comment]
@dqqcasia @oadams Hi, I'm happy to know someone else are interested in this direction like us. Yes, I'm working on it now and it takes some time to complete the tuning/training process. I'll try to make it work as soon as possible. Stay tuned ^_^!

**Comment by flozi00** [comment]
https://github.com/huggingface/transformers/pull/9659#event-4279129673
Wave2vec 2 got merged into the transformers master, don't know if it helps ?
As I can see there is no training example at the moment, but the pretrained models by facebook can be loaded and used
