### ISSUE TITLE
Fastspeech 2 features

### ISSUE THREAD

**Issue by zooeygirl** [espnet/espnet#2610]
Hello,

First of all, thank you very much for making this library available. It's great!

I have a few questions regarding your Fastspeech 2 implementation:

1. What is used to obtain the word segmentation for the training data? And is this part of the pipeline in your implementation? I see pitch and energy extraction, but no duration.

2. What exactly are the features predicted by the model for pitch and energy? I saw some discussion about quantization and log values, but I'm not sure what was used in the final product. And is there a difference between training and inference?

My apologies if this information is already posted somewhere. Could you please point me to the right place if it is.

**Comment by kan-bayashi** [comment]
> What is used to obtain the word segmentation for the training data? And is this part of the pipeline in your implementation? I see pitch and energy extraction, but no duration.

I used the same manner as FastSpeech. Duration is calculated from the teacher model's attention weight.

> What exactly are the features predicted by the model for pitch and energy?

I used token-averaged continuous log F0 and energy.
The quantization is not performed.

> is there a difference between training and inference?

During the training, we use the groundtruth as the input of the decoder.
In the inference, we use the predicted one.

**Comment by zooeygirl** [comment]
Thank you for the quick response. I'm surprised to hear that the duration is calculated from the teacher model because I find the word alignments are much better with Fastspeech 2 than Fastspeech 1.

**Comment by kan-bayashi** [comment]
@zooeygirl Maybe this is because for FastSpeech2 we used teacher forcing to calculate the attention weights but for FastSpeech we did not use it due to the knowledge distillation.

**Comment by kan-bayashi** [comment]
If you have an additional question, please re-open.
