### ISSUE TITLE
Question: Generate audio using trained TTS model

### ISSUE THREAD

**Issue by szmmm** [espnet/espnet#2611]
Hello, I have beening learning to use espnet2 recipes to create my own TTS system on BABEL data set. What should I do in order to generate some waveform to listen to for debugging purposes after the training is done? I would be very glad if someone can give a detailed explanation, as I am at beginner level only. Any help would be appreciated! Thank you!

I have already looked at the google Colab demostration where you could download pre-trained models and input some text to testing, but because my model will be non-English I am not sure how much that can apply to my case. I hope I made my question clear.

**Comment by szmmm** [comment]
2. Additional question: Does ESPNet2 support x-vectors for speaker embedding, or I need to use GST for multi-speaker characteristics. Thank you!

**Comment by kan-bayashi** [comment]
Sorry for the late reply.

> Hello, I have beening learning to use espnet2 recipes to create my own TTS system on BABEL data set. What should I do in order to generate some waveform to listen to for debugging purposes after the training is done? 

If you already made the recipe for your dataset and ran the training stage, you can run the inference stage via the following command:
```sh
./run.sh --stage 7 --inference_model train.loss.best.pth
# you can select any *.pth file in the experimental directory for `--inference_model` option
```
You can generate the audio with the middle of the checkpoint.
Another choice is checking the attention weights (`exp/*/att_ws/`).
If the attention weights are diagonal, at least the model can generate something audible.

> my model will be non-English I am not sure how much that can apply to my case. I hope I made my question clear.

It depends on the `token_type`. Basically we use `token_type=phn` (i.e., phoneme) for better quality.
I'm not familiar with BABEL dataset, but obviously we can not apply our prepared G2P module for the text.
To address this issue, there are three choices:
- Make your own on-the-fly G2P module for BABEL dataset
- Convert text into phoneme with the offline processing and use `token_type=phn` and `g2p=none`.
- Use `token_type=char`

Char is the easiest solution but It makes it difficult to learn the diagonal attention.

> Additional question: Does ESPNet2 support x-vectors for speaker embedding, or I need to use GST for multi-speaker characteristics? If I want to add speaker identity to the output during inference, which part of the code should I look at?

X-vector is not supported in ESPnet2. Please use GST for the multi-speaker setting.
You can refer the multi-speaker demo in the notebook.
