### ISSUE TITLE
Question: How can I get the variable epoch in the validation code?

### ISSUE THREAD

**Issue by Jxu-Thu** [espnet/espnet#2612]
Thanks for your great code!
Here I just have a problem

In espnet, the validation procedure is conducted in the Class **CustomEvaluator**. (espnet/asr/pytorch_backend/asr.py)
Now my question is that how can I get the **epoch** variable in the class?  I need to know this is i-th epoch.

Thanks!

**Comment by kamo-naoyuki** [comment]
How about ` self._iterators["main"].epoch`? I'm not sure as I didn't use chainer recently.
