### ISSUE TITLE
Grad Nan. at the start of training. Using ESPNet2 TTS recipe

### ISSUE THREAD

**Issue by szmmm** [espnet/espnet#2614]
Hi, I have used The kaldi data preparation for BABEL dataset, and the feature type I used is fbank. When I finished stage 5 the (feature stats calculation), generated the feature stats and move on to stage 6 (training), I can see the following log message:

```
mysourcepath/espnet2/layers/global_mvn.py:54: RuntimeWarning: invalid value encountered in sqrt std = np.maximum(np.sqrt(var), eps)
```

Which is weird because I had run the script several times on the same data and features, but this is the first time I saw it. Then as the training started at 1epoch, the model does not update because all gradients are nan and the message keeps repeating. It seems the model cannot compute correctly the gradient. Does anyone know what might be the cause? For feature extraction I used the data prep steps in the BABEL recipe for ASR. Please let me know if you need more information. Thank you!

```
WARNING: The grad norm is nan. Skipping updating the model.
WARNING: The grad norm is nan. Skipping updating the model.
                                                ....
mysourcepath/espnet2/train/reporter.py:90: UserWarning: No valid stats found warnings.warn("No valid stats found")
```

**Comment by kan-bayashi** [comment]
> For feature extraction I used the data prep steps in the BABEL recipe for ASR

You mean the feature extraction was performed by kaldi? or you follow the ESPnet2 TTS recipe with `feat_type=fbank`?
If you use kaldi fbank, the fbank feature for TTS is different from the ASR one.
So if you want to generate audio, you cannot use it.
You can use the data prep script for the ASR recipe to create kaldi data directories (e.g. `wav.scp`, `text`, etc), but it is better to use `feat_type=raw` by following the ESPnet2-TTS recipe.

**Comment by szmmm** [comment]
> > For feature extraction I used the data prep steps in the BABEL recipe for ASR
> 
> You mean the feature extraction was performed by kaldi? or you follow the ESPnet2 TTS recipe with `feat_type=fbank`?
> If you use kaldi fbank, the fbank feature for TTS is different from the ASR one.
> So if you want to generate audio, you cannot use it.
> You can use the data prep script for the ASR recipe to create kaldi data directories (e.g. `wav.scp`, `text`, etc), but it is better to use `feat_type=raw` by following the ESPnet2-TTS recipe.

Hi, thank you for your reply.

I used the ESPNet2 BABEL ASR code for stage 1 data prep to generate ```text```, etc, and I followed the recipe but I changed the setting to```feat_type=fbank```. So this is not the correct way of using the recipe? What do I need to do if I want to use fbank type features? I thought the recipe also generates fbank feature for you during stage 2, but please correct me if I am wrong

**Comment by szmmm** [comment]
To add to the above content, here is my code showing the `feats_stats` values
```
data3 = numpy.load("C:/Users/matt/Desktop/feats_stats_part.npz")
mean3 = data3['sum'] / data3['count']
print(data3['sum_square'] / data3['count'] - mean3**2)
```
The output is
```
[ 6.69632581e-01  7.64433247e-01  8.94379061e-01  1.03835942e+00
                                               ......
  8.78724543e-01  8.70268540e-01 -3.69438223e-06 -3.69438223e-06
 -3.69438223e-06 -3.69438223e-06 -3.69438223e-06 -3.69438223e-06]
```
Noticed the very last few entries are negative, very small, and they are all the same. I hope this helps.

**Comment by szmmm** [comment]
> > For feature extraction I used the data prep steps in the BABEL recipe for ASR
> 
> You mean the feature extraction was performed by kaldi? or you follow the ESPnet2 TTS recipe with `feat_type=fbank`?
> If you use kaldi fbank, the fbank feature for TTS is different from the ASR one.
> So if you want to generate audio, you cannot use it.
> You can use the data prep script for the ASR recipe to create kaldi data directories (e.g. `wav.scp`, `text`, etc), but it is better to use `feat_type=raw` by following the ESPnet2-TTS recipe.

Also thank you for your reply in my previous question about inference. That helped alot. May I ask you what is the advantage of using `raw` features over `fbank` features? It is not necessary for me to stick with `fbank` if `raw` is overall better, as I just needed something that works.

**Comment by kan-bayashi** [comment]
> May I ask you what is the advantage of using raw features over fbank features? It is not necessary for me to stick with fbank if raw is overall better, as I just needed something that works.

`raw` means we use the same `fbank` but the feature extraction is performed on-the-fly manner during the training, and therefore, we use `raw` waveform as the input.

> I used the ESPNet2 BABEL ASR code for stage 1 data prep to generate text, etc, and I followed the recipe from stage 2 but I changed the setting tofeat_type=fbank.

It seems no problem.

@kamo-naoyuki I'm not sure why the variance will be negative.
Do you have any idea?

**Comment by kamo-naoyuki** [comment]
@szmmm, thank you. It seems a bug, but I don't know how it happens, but probably, either one of the calculation  statistics or computing fbank is wrong.

Could you print `data['sum_square']`, `data['sum']`,  and`data['count']`, and check the value of fbank using `feats.scp`?

```
import kaldiio
l = kaldiio.load_scp(".../feats.scp")
for k, v in l.items():
    print(v[-10:])
```

**Comment by szmmm** [comment]
> import kaldiio
> l = kaldiio.load_scp(".../feats.scp")
> for k, v in l.items():
>     print(v[-10:])
```print(data['sum'])```
The results are negative numbers
```
[-21780068. -20653752. -19394212. -18276400. -17462006. -17024380.
 -16884652. -16864430. -16851858. -16806950. -16726425. -16635796.
   .......
```
```print(data2['sum_square'])```
The result is
```
[6.1326256e+07 5.6843112e+07 5.2284604e+07 4.8664324e+07 4.6253780e+07
 4.4993140e+07 4.4520508e+07 4.4282400e+07 4.4074796e+07 4.3862484e+07
   ......
```
```print(data2['count'])
8597567
```

**Comment by kamo-naoyuki** [comment]
Could you print last 10 elements only?
You can 

> I can open the `feats.scp` file in `dump`and I can see pairs of file names and IDs. Below are the last few lines in that file. Please let me know if these are what you are looking for.

Either one is fine.

> I don't know if it is useful, but the data I have are 8kHz telephone call audios, so I changed some default settings in `tts.sh` regarding the feature extractions:
> 
> ```
> fs=8000
> fmax=5000
> window_length=200
> ```
> 
> I am not sure if I am doing things correctly. Are there any other parameterisation change I need to pay attention to? Also I found in the `wav.scp` the `sox -R -t wav - -t wav - rate 16000 dither` commands. Do I need to make changes to this?

Now the audio is resampled to 8khz (original) -> 16khz (by sox) -> 8khz ( when computing fbank). This is no problem, but useless. it's better to stop resampling.

BTW, I think babel is not suitable for tts training, originally...

**Comment by kan-bayashi** [comment]
`fmax=5000` may be a problem if you use `fs=8000`.
It must be less than 4000.

**Comment by szmmm** [comment]
> Could you print last 10 elements only?
>I will do this later and post it here, thanks 


> > I can open the `feats.scp` file in `dump`and I can see pairs of file names and IDs. Below are the last few lines in that file. Please let me know if these are what you are looking for.
> 
> Either one is fine.
> 
> > I don't know if it is useful, but the data I have are 8kHz telephone call audios, so I changed some default settings in `tts.sh` regarding the feature extractions:
> > ```
> > fs=8000
> > fmax=5000
> > window_length=200
> > ```
> > 
> > 
> > I am not sure if I am doing things correctly. Are there any other parameterisation change I need to pay attention to? Also I found in the `wav.scp` the `sox -R -t wav - -t wav - rate 16000 dither` commands. Do I need to make changes to this?
> 
> Now the audio is resampled to 8khz (original) -> 16khz (by sox) -> 8khz ( when computing fbank). This is no problem, but useless. it's better to stop resampling.
> How should I stop sampling? Do I remove this `sox` part of the code in the `data.sh` file? 

> BTW, I think babel is not suitable for tts training, originally...

Thank you for your advice, I am doing a project on this and will see what comes out...

**Comment by szmmm** [comment]
> `fmax=5000` may be a problem if you use `fs=8000`. It must be less than 4000.

Thank you, I have changed it to 3800

**Comment by szmmm** [comment]
May I also ask how I could make use of the GST multi-speaker model, assuming I have successfully trained a model?

For example I have a script that I want to generate audio from, what kind of information do I have to pass along with the text in order to tell the model to generate sound of a specified type of voice?

**Comment by kan-bayashi** [comment]
Pass the reference audio as the auxiliary input.
See multi-speaker example in the following notebook.
https://colab.research.google.com/github/espnet/notebook/blob/master/espnet2_tts_realtime_demo.ipynb

**Comment by szmmm** [comment]
> Pass the reference audio as the auxiliary input.
> See multi-speaker example in the following notebook.
> https://colab.research.google.com/github/espnet/notebook/blob/master/espnet2_tts_realtime_demo.ipynb

Thank you. Is there any place in the recipe wher I can pass the auxiliary audio, or do I have to implement this myself somewhere in the code.

**Comment by szmmm** [comment]
Now the training does not report error about Nan gradients. However the process has been staying on the first epoch. See log below
```
[air207] 2020-11-03 13:18:36,231 (abs_task:1073) INFO: Scheduler: None
[air207] 2020-11-03 13:18:36,238 (abs_task:1082) INFO: Saving the configuration in exp/tts_train_gst_tacotron2_raw_char_tacotron/config.yaml
[air207] 2020-11-03 13:18:36,910 (abs_task:1429) INFO: [train] dataset:
ESPnetDataset(
  text: {"path": "dump/raw/train/text", "type": "text"}
  speech: {"path": "dump/raw/train/wav.scp", "type": "sound"}
  preprocess: <espnet2.train.preprocessor.CommonPreprocessor object at 0x2b3f8eb75310>)
[air207] 2020-11-03 13:18:36,910 (abs_task:1430) INFO: [train] Batch sampler: NumElementsBatchSampler(N-batch=575, batch_bins=1000000, sort_in_batch=descending, sort_batch=descending)
[air207] 2020-11-03 13:18:36,910 (abs_task:1431) INFO: [train] mini-batch sizes summary: N-batch=575, mean=18.1, min=7, max=66
[air207] 2020-11-03 13:18:36,966 (abs_task:1429) INFO: [valid] dataset:
ESPnetDataset(
  text: {"path": "dump/raw/dev/text", "type": "text"}
  speech: {"path": "dump/raw/dev/wav.scp", "type": "sound"}
  preprocess: <espnet2.train.preprocessor.CommonPreprocessor object at 0x2b3f8eb75370>)
[air207] 2020-11-03 13:18:36,966 (abs_task:1430) INFO: [valid] Batch sampler: NumElementsBatchSampler(N-batch=66, batch_bins=1000000, sort_in_batch=descending, sort_batch=descending)
[air207] 2020-11-03 13:18:36,966 (abs_task:1431) INFO: [valid] mini-batch sizes summary: N-batch=66, mean=17.5, min=6, max=51
[air207] 2020-11-03 13:18:36,998 (abs_task:1429) INFO: [plot_att] dataset:
ESPnetDataset(
  text: {"path": "dump/raw/dev/text", "type": "text"}
  speech: {"path": "dump/raw/dev/wav.scp", "type": "sound"}
  preprocess: <espnet2.train.preprocessor.CommonPreprocessor object at 0x2b3f8eb75c40>)
[air207] 2020-11-03 13:18:36,998 (abs_task:1430) INFO: [plot_att] Batch sampler: UnsortedBatchSampler(N-batch=1153, batch_size=1, key_file=exp/tts_stats_raw_char_tacotron/valid/text_shape.char, 
[air207] 2020-11-03 13:18:36,999 (abs_task:1431) INFO: [plot_att] mini-batch sizes summary: N-batch=3, mean=1.0, min=1, max=1
[air207] 2020-11-03 13:18:37,076 (trainer:196) INFO: 1/40epoch started
```

I am using raw feature now. Is the process hanging or it is just being slow? I am not sure how to tell...

**Comment by szmmm** [comment]
Just to note that the training is now working, thanks you both for helping out!
