### ISSUE TITLE
Installing with CUDA 11.0

### ISSUE THREAD

**Issue by iiscleap** [espnet/espnet#2626]
**Describe the issue**
Hello, I have been trying to install espnet with CUDA 11.0. But, I ran into an error mentioning compatibility issues for pytorch with CUDA 11. Is there a way to make the installation work with CUDA 11?

**Environments from `torch.utils.collect_env`:**
```
Collecting environment information...
PyTorch version: 1.4.0
Is debug build: No
CUDA used to build PyTorch: Could not collect

OS: CentOS Linux 7 (Core)
GCC version: (GCC) 4.8.5 20150623 (Red Hat 4.8.5-16)
CMake version: version 3.18.2

Python version: 3.8
Is CUDA available: No
CUDA runtime version: Could not collect
GPU models and configuration: 
GPU 0: Quadro P5000
GPU 1: Quadro P5000

Nvidia driver version: 450.51.06
cuDNN version: Could not collect

Versions of relevant libraries:
[pip3] numpy==1.19.2
[pip3] torch==1.4.0
[conda] blas                      1.0                         mkl  
[conda] cpuonly                   1.0                           0    pytorch
[conda] mkl                       2020.2                      256  
[conda] mkl-service               2.3.0            py38he904b0f_0  
[conda] mkl_fft                   1.2.0            py38h23d657b_0  
[conda] mkl_random                1.1.1            py38h0573a6f_0  
[conda] pytorch                   1.4.0               py3.8_cpu_0  [cpuonly]  pytorch

```

**Error logs**
~> make
[ -n "/usr/local/cuda" ] || { echo -e "Error: CUDA_HOME is not set.\n    $ . ./setup_cuda_env.sh <cuda-root>"; exit 1; }
CUDA_VERSION=11.0
. ./activate_python.sh && python3 check_pytorch_cuda_compatibility.py 1.4.0 11.0 || { echo "Change TH_VERSION or CUDA_VERSION"; exit 1; }
Traceback (most recent call last):
  File "check_pytorch_cuda_compatibility.py", line 73, in <module>
    main()
  File "check_pytorch_cuda_compatibility.py", line 69, in main
    check(**vars(parser.parse_args()))
  File "check_pytorch_cuda_compatibility.py", line 54, in check
    raise RuntimeError(
RuntimeError: Not compatible: pytorch=1.4.0, cuda=11.0: Supported cuda versions: ['10.1', '10.0', '9.2']
Change TH_VERSION or CUDA_VERSION
make: *** [Makefile:75: showenv] Error 1

**Comment by kamo-naoyuki** [comment]
Use pytorch1.7.

make TH_VERSION=1.7.0

See pytorch documentation: https://pytorch.org/get-started/locally/

**Comment by iiscleap** [comment]
> Use pytorch1.7.
> 
> make TH_VERSION=1.7.0
> 
> See pytorch documentation: https://pytorch.org/get-started/locally/

I am using pytorch 1.7.0 with cuda 11.0 and getting the following error.

[ -n "/usr/local/cuda" ] || { echo -e "Error: CUDA_HOME is not set.\n    $ . ./setup_cuda_env.sh <cuda-root>"; exit 1; }
CUDA_VERSION=11.0
. ./activate_python.sh && python3 check_pytorch_cuda_compatibility.py 1.7.0 11.0 || { echo "Change TH_VERSION or CUDA_VERSION"; exit 1; }
11.0
PYTHON=/home/shrutinaa/espnet/tools/venv/bin/python3
PYTHON_VERSION=Python 3.8.3
IS_CONDA=0
USE_PIP=
TH_VERSION=1.7.0
CONDA_PYTORCH=pytorch=1.7.0 cudatoolkit=11.0
PIP_PYTORCH=torch==1.7.0 -f https://download.pytorch.org/whl/cu110/torch_stable.html
CHAINER_VERSION=6.0.0
PIP_CHAINER=chainer==6.0.0
NO_CUPY=0
. ./activate_python.sh && ./installers/install_warp-transducer.sh
Cloning into 'warp-transducer'...
remote: Enumerating objects: 11, done.
remote: Counting objects: 100% (11/11), done.
remote: Compressing objects: 100% (10/10), done.
remote: Total 905 (delta 1), reused 5 (delta 1), pack-reused 894
Receiving objects: 100% (905/905), 248.13 KiB | 362.00 KiB/s, done.
Resolving deltas: 100% (462/462), done.
-- The C compiler identification is GNU 7.3.1
-- The CXX compiler identification is GNU 7.3.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /opt/rh/devtoolset-7/root/usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /opt/rh/devtoolset-7/root/usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found CUDA: /usr/local/cuda (found version "11.0") 
-- cuda found TRUE
-- Building shared library with GPU support
-- Configuring done
-- Generating done
-- Build files have been written to: /home/shrutinaa/espnet/tools/warp-transducer/build
make[1]: Entering directory '/home/shrutinaa/espnet/tools/warp-transducer/build'
make[2]: Entering directory '/home/shrutinaa/espnet/tools/warp-transducer/build'
make[3]: Entering directory '/home/shrutinaa/espnet/tools/warp-transducer/build'
[  7%] Building NVCC (Device) object CMakeFiles/warprnnt.dir/src/warprnnt_generated_rnnt_entrypoint.cu.o
nvcc fatal   : Unsupported gpu architecture 'compute_30'
CMake Error at warprnnt_generated_rnnt_entrypoint.cu.o.cmake:220 (message):
  Error generating
  /home/shrutinaa/espnet/tools/warp-transducer/build/CMakeFiles/warprnnt.dir/src/./warprnnt_generated_rnnt_entrypoint.cu.o


make[3]: *** [CMakeFiles/warprnnt.dir/build.make:84: CMakeFiles/warprnnt.dir/src/warprnnt_generated_rnnt_entrypoint.cu.o] Error 1
make[3]: Leaving directory '/home/shrutinaa/espnet/tools/warp-transducer/build'
make[2]: *** [CMakeFiles/Makefile2:102: CMakeFiles/warprnnt.dir/all] Error 2
make[2]: Leaving directory '/home/shrutinaa/espnet/tools/warp-transducer/build'
make[1]: *** [Makefile:149: all] Error 2
make[1]: Leaving directory '/home/shrutinaa/espnet/tools/warp-transducer/build'
make: *** [Makefile:160: warp-transducer.done] Error 1

**Comment by kan-bayashi** [comment]
See the log.
>  fatal : Unsupported gpu architecture 'compute_30'

It seems that you used too old GPU.

**Comment by r4nc0r** [comment]
I have the same error but my gpu is a rtx 3090 so not too old but too new?

**Comment by kamo-naoyuki** [comment]
> fatal : Unsupported gpu architecture 'compute_30'

This error comes from https://github.com/HawkAaron/warp-transducer/blob/f546575109111c455354861a0567c8aa794208a2/CMakeLists.txt#L48

You can avoid this problem with commenting this line.
