### ISSUE TITLE
Unable to download kan-bayashi/csj_asr_train_asr_transformer_raw_char_sp_valid.acc.ave

### ISSUE THREAD

**Issue by Co-Graph-Okuda** [espnet/espnet#2627]
**Describe the bug**
Unable to download kan-bayashi/csj_asr_train_asr_transformer_raw_char_sp_valid.acc.ave.

**Basic environments:**
 - OS information: Docker Ubuntu 18.0.4
 - python version: 3.7.3
 - espnet version: 0.9.4
 - Git hash c1e81983f035923fc0b47a266ec73a292f3e0c43
   - Commit date Wed Sep 30 20:04 2020 +0900
 - torch version: 1.7.0
 
You can obtain them by the following command
```
cd <espnet-root>/egs2/asr1
./run.sh --skip_data_prep false --skip_train true --download_model kan-bayashi/csj_asr_train_asr_transformer_raw_char_sp_valid.acc.ave
```

**Environments from `torch.utils.collect_env`:**
```
Collecting environment information...
Torch version: 1.7.0
Is debug build: No
CUDA used to build PyTorch: 10.2

OS: Ubuntu 18.04.5 LTS
GCC version: (GCC) 7.5.0
CMake version: version 3.10.2

Python version: 3.6.9
Is CUDA available: Yes
CUDA runtime version: 10.2
GPU models and configuration:
GeForce GTX 1060

Nvidia driver version: 450.80.02
cuDNN version: Could not collect

Versions of relevant libraries:
[pip3] numpy==1.19.3
[pip3] pytorch-wpe==0.0.0
[pip3] torch==1.7.0
[pip3] torch-complex==0.2.0
[pip3] torchvision==0.8.1
[conda] Could not collect
```

**Task information:**
 - Task: ASR
 - Recipe: csj
 - ESPnet2

**To Reproduce**
1. move to a recipe directory, `cd egs2/csj/asr1`
2. execute `run.sh` with specific arguments, `run.sh --skip_data_prep false --skip_train true --download_model kan-bayashi/csj_asr_train_asr_transformer_raw_char_sp_valid.acc.ave`
3. specify the error log, `Fill the value of 'CSJDATATOP' of db.sh`

**Error logs**
```
Stage 1: Data preparation for data/train_nodup, data/train_dev, etc.
local/data.sh
Fill the value of 'CSJDATATOP' of db.sh
```

**Comment by kamo-naoyuki** [comment]
If you'll evaluate CSJ data, you must buy CSJ corpus and fill $CSJDATATOP. If you need to download the model only,  use model_zoo API: https://github.com/espnet/espnet_model_zoo

**Comment by Co-Graph-Okuda** [comment]
OK, thanks. Applied for user registration of CSJ.

**Comment by Co-Graph-Okuda** [comment]
I registered with CSJ online version, but it seems that corpus is not available. Do we have to purchase the CSJ offline version?

**Comment by kamo-naoyuki** [comment]
Yes, you have to purchase.

**Comment by Co-Graph-Okuda** [comment]
> Yes, you have to purchase.

OK, thanks.
