### ISSUE TITLE
How to get duration outputs from TTS inference with Fastspeech2

### ISSUE THREAD

**Issue by mailong25** [espnet/espnet#2629]
Hi

I currently using the TTS FastSpeech2 model with the following code:

```
from espnet2.bin.tts_inference import Text2Speech
text2speech = Text2Speech('models/text2mel/config.yaml','models/text2mel/best.pth')
x = 'this is a test sentence'
with torch.no_grad():
    wav, c, outs_denorm, probs, att_ws, duration, focus_rate = text2speech(x)

```
I don't know why the duration output is always None. How can I config the inference pipeline so that it can return the duration?

Thanks

**Comment by kan-bayashi** [comment]
Currently, only the AR models return the duration but Non-AR also calculated internally.
I will consider to change to output the duration.
For quick fixing, you can change the following parts (`d_outs` is estimated duration).
https://github.com/espnet/espnet/blob/b5f3966911a890e445bd87b0cccabfcb6de7f21d/espnet2/tts/fastspeech2.py#L534
https://github.com/espnet/espnet/blob/b5f3966911a890e445bd87b0cccabfcb6de7f21d/espnet2/tts/fastspeech2.py#L593
