### ISSUE TITLE
Conformer Pre-train time

### ISSUE THREAD

**Issue by ZLKong** [espnet/espnet#2630]
Hi  @yuekaizhang :  

From this issue   https://github.com/espnet/espnet/issues/2537#issuecomment-703191762_

Can you provide the training time and how many GPU used for pre-training the conformer-large model? Thanks!

Best,
ZLK

**Comment by yuekaizhang** [comment]
I used 8 v100 gpus with 32 Gb memory. It takes about 3~4 days.

**Comment by aqlv** [comment]
Hi @yuekaizhang : 

I am wandering how many epochs you trained? I use 8 v100 gpus too, and the train.log shows that the estimated training time for 120 epochs is 12days. 

Best,
aqlv

**Comment by yuekaizhang** [comment]
Hi,

I trained 120 epochs which take about 4 days. Perhaps you could check your GPU utilizes rate. Also, you could increase your num-worker to prefetch data.

**Comment by renepeinl** [comment]
Hi,
we have two machines with 2x Titan RTX 24 GB GPU each. Do you see a way for us to train the Conformer model? We have a NVLink bridge for both machines, and Pytorch is supporting [Model Parallel training](https://pytorch.org/tutorials/intermediate/model_parallel_tutorial.html). A naive approach would think, that you simply have to cut the Conformer model in half and transfer the outputs of the last layer on GPU 1 as input to the first layer on GPU 2. However, it seems the modification to ESPnet ist not trivial to implement something like this.
Any suggestions?
René

**Comment by sw005320** [comment]
> Hi,
> we have two machines with 2x Titan RTX 24 GB GPU each. Do you see a way for us to train the Fastspeech2 Conformer model? We have a NVLink bridge for both machines, and Pytorch is supporting [Model Parallel training](https://pytorch.org/tutorials/intermediate/model_parallel_tutorial.html). A naive approach would think, that you simply have to cut the Conformer model in half and transfer the outputs of the last layer on GPU 1 as input to the first layer on GPU 2. However, it seems the modification to ESPnet ist not trivial to implement something like this.
> Any suggestions?
> René

This issue is about conformer ASR.
I suggest you make a new issue.
Also, we usually don't support the model parallel training.

**Comment by renepeinl** [comment]
Thanks. I've done as you recommended.
https://github.com/espnet/espnet/issues/2949
