### ISSUE TITLE
GTA mode for TTS inference

### ISSUE THREAD

**Issue by fosimoes** [espnet/espnet#2631]
Is groud truth alignment (GTA) mode for TTS inference implemented is espnet?

**Comment by kan-bayashi** [comment]
ESPnet2 can do it. Please `use_teacher_forcing = True`.
https://github.com/espnet/espnet/blob/b5f3966911a890e445bd87b0cccabfcb6de7f21d/egs2/ljspeech/tts1/conf/tuning/decode_tacotron2.yaml#L16
