### ISSUE TITLE
Qn: Examples of ASR-TTS cycle-consistency training/speech chain using ESPNet2?

### ISSUE THREAD

**Issue by szmmm** [espnet/espnet#2633]
Hi, there! It was great that some of you helped me with the problem I had. Now may I ask if there is any existing example scripts where ASR and TTS training have been combined using ESPNet2 structures and recipes? I know there are some publications based on ESPNet 1 (e.g. https://arxiv.org/pdf/1905.01152.pdf) but because there is a change from ESPNet to ESPNet2 in many aspects, I wonder if there is any examples based on ESPNet2 I can learn from. Lots of questions from me I apologies! Thank you very much!

**Comment by sw005320** [comment]
Unfortunately, we don't have such an ESPnet2 example yet, but we are working on it. We may not finish it soon, but we're still thinking this is one of the most important projects. Please stay tuned. If you have some progress or discussions about ASR-TTS joint modeling, feel free to post things here.

**Comment by lbehringer** [comment]
Hello, 
I had the same question and found this thread - are there potentially any updates about this? Thanks a lot!
