### ISSUE TITLE
How to set the parameter ngpu.

### ISSUE THREAD

**Issue by YeBobr** [espnet/espnet#2635]
The parameter  ngpu is 1 during the collect_stats stage, and it is 4 during the asr_train stage. Is it ok ?

This problem stems from the following codes.

espnet/espnet2/main_funcs/collect_stats.py 

2. Extract feats
                if ngpu <= 1:
                    data = model.collect_feats(**batch)
                else:
                    # Note that data_parallel can parallelize only "forward()"
                    data = data_parallel(
                        ForwardAdaptor(model, "collect_feats"),
                        (),
                        range(ngpu),
                        module_kwargs=batch,
                    )

**Comment by kamo-naoyuki** [comment]
For collect_stats mode, ngpu is 0 by default. For training stage, ngpu is the value specified by --ngpu option.
