### ISSUE TITLE
asr.sh with feats_type "extracted"

### ISSUE THREAD

**Issue by sun-peach** [espnet/espnet#2638]
**Describe the bug**
when the feats_type is "extracted", the utils/copy_data_dir.sh always gives errors

**Basic environments:**
 - OS information: Linux 3.10.0-1.3.2.el7.x86_64 #1 SMP Tue Mar 31 06:25:43 UTC 2020 x86_64
 - python version: 3.7
 - espnet version: espnet 0.8.0
 - pytorch version [e.g. pytorch 1.1.0]

**To Reproduce**
This is ASR task
Finish feature extraction (feats.scp is ready), get utt2spk, spk2utt and text ready. Use compute-cmvn-stats to compute cmvn (I tried with and without utt2spk)
run run.sh with --feats_type extracted

**Error logs**
When use utt2spk in cmvn, it shows utt_map not have key ***； when not use utt2spk in cmvn, it shows spk_map not have key ****.

**Comment by yuekaizhang** [comment]
Do you try to use utils/fix_data_dir.sh data/train to ensure all files have the same order and keys?

**Comment by sun-peach** [comment]
no, I only run the run.sh which calls the asr.sh. I checked that it seems that the scripts does not have the fix_data_dir.sh by default under the "extracted" feats_type.

Now, I removed the cmvn parts, and directly copy a dummy wav.scp there. Everything is fine. Just remind you that there is a bug. @yuekaizhang
