### ISSUE TITLE
Does epsnet plan to support streaming speech recognition, such as MoCHA and triggered_attention?

### ISSUE THREAD

**Issue by Alex-Songs** [espnet/espnet#2640]
Does epsnet plan to support streaming speech recognition, such as MoCHA and triggered_attention?

**Comment by sw005320** [comment]
This is ongoing, but most likely we'd not support triggered_attention except that if MERL people want to do.

**Comment by Alex-Songs** [comment]
thanks!

**Comment by poor1017** [comment]
Have plan of streaming mode for transformer?

**Comment by sw005320** [comment]
It would be a transformer, but we cannot commit when it would be finished.
