### ISSUE TITLE
Inference Code for ESPnet Tranied Model

### ISSUE THREAD

**Issue by nehasoni3** [espnet/espnet#2641]
Hi
I have trained a model using ESPNet for ASR.
Can I use this code for inferencing. - 
```
import json
import torch
import argparse
from espnet.bin.asr_recog import get_parser
from espnet.nets.pytorch_backend.e2e_asr import E2E

root = "espnet/egs/an4/asr1"
model_dir = root + "/exp/train_nodev_pytorch_train_mtlalpha1.0/results"

# load model
with open(model_dir + "/model.json", "r") as f:
  idim, odim, conf = json.load(f)
model = E2E(idim, odim, argparse.Namespace(**conf))
model.load_state_dict(torch.load(model_dir + "/model.loss.best"))
model.cpu().eval()

# load token dict
with open(root + "/data/lang_1char/train_nodev_units.txt", "r") as f:
  token_list = [entry.split()[0] for entry in f]
token_list.insert(0, '<blank>')
token_list.append('<eos>')

# recognize speech
parser = get_parser()
args = parser.parse_args(["--beam-size", "2", "--ctc-weight", "1.0", "--result-label", "out.json", "--model", ""])
result = model.recognize(fbank, args, token_list)
s = "".join(conf["char_list"][y] for y in result[0]["yseq"]).replace("<eos>", "").replace("<space>", " ").replace("<blank>", "")

print("groundtruth:", info["output"][0]["text"])
print("prediction: ", s)`
```
I have got it from [SEE LOAD MODEL SECTION](https://espnet.github.io/espnet/notebook/asr_cli.html) and [SEE RECOGNIZE SPEECH](https://espnet.github.io/espnet/notebook/asr_library.html#Recognize-speech)
Thanks

**Comment by yuekaizhang** [comment]
https://github.com/espnet/espnet/blob/master/utils/recog_wav.sh
FYI, you could check this.

**Comment by nehasoni3** [comment]
> FYI

I know this way of doing inference. But can I use stated above code for inference.

**Comment by yuekaizhang** [comment]
Sure, I believe you could do this with correct conda environment.

**Comment by nehasoni3** [comment]
> Sure, I believe you could do this with correct conda environment.

That means, If I can use this way, I am getting output from Encoder-Decoder-CTC-attention complete network. Right?

**Comment by b-flo** [comment]
> That means, If I can use this way, I am getting output from Encoder-Decoder-CTC-attention complete network. Right?

If "this way" means "without changing the provided snippet": no. You need to change `--ctc-weight` option (and pass a CTC-Att model obviously), it's currently setup for CTC-only.

**Comment by nehasoni3** [comment]
> > That means, If I can use this way, I am getting output from Encoder-Decoder-CTC-attention complete network. Right?
> 
> If "this way" means "without changing the provided snippet": no. You need to change `--ctc-weight` option (and pass a CTC-Att model obviously), it's currently setup for CTC-only.
I have provided CTC weight and Beam search values and pass it to arguments. 

Thing is, my model is Hybrid CTC/attention based Transformer model. Do I use above inference way to get output?

**Comment by b-flo** [comment]
At first glance, you would need to change the following : 

- l.1: modify import -> `from espnet.nets.pytorch_backend.e2e_asr_transformer import E2E`
- l.25 : change `ctc-weight` param value

I may have missed or forgotten something, it's been a while since I've used this example

**Comment by nehasoni3** [comment]
> At first glance, you would need to change the following :
> 
> * l.1: modify import -> `from espnet.nets.pytorch_backend.e2e_asr_transformer import E2E`
> * l.25 : change `ctc-weight` param value
> 
> I may have missed or forgotten something, it's been a while since I've used this example

Yes. I have done this. 
After these changes, my output will be from Hybrid CTC/attention based Transformer model.Right?

**Comment by b-flo** [comment]
Yes

**Comment by nehasoni3** [comment]
Thanks @b-flo
