### ISSUE TITLE
ValueError: assignment destination is read-only

### ISSUE THREAD

**Issue by yuekaizhang** [espnet/espnet#2644]
https://github.com/espnet/espnet/blob/1122ae9abdf8af006d5cc9455d2043f2df3f791a/espnet/transform/spec_augment.py#L64-L89

I met a bug on line 89. I can't give 0 to the left. It said ValueError: assignment destination is read-only. 

I have to change line 73 to x.copy().

Does anyone know the reason?

Thanks.

**Comment by sw005320** [comment]
Could you explain a bit more? 
When did it happen?
We did not encounter a problem in normal use.

**Comment by yuekaizhang** [comment]
Yeah, I actually did not know why it happens.  I didn't encounter the problem before. I just bash run.sh, and the script failed after some specaug steps. I didn't change any code related specaug. 
I am not sure whether it is related to the big dataset. I am using a 6.2Gb data.json. I have fixed the error by changing cloned =x to cloned = x.copy(). Just mark here.

**Comment by sw005320** [comment]
I see. We can leave as it is, but if you (or others) seem to reproduce the same bug, lets' fix it.
