### ISSUE TITLE
Global Style Token during inference/testing stage for ESPNet2 TTS recipe

### ISSUE THREAD

**Issue by szmmm** [espnet/espnet#2646]
Hi, I recently trained a TTS model based on GST+Tacotron2 and want to debug the various stages that might result in bad audio quality. I plotted the output mel-spectrogram and it looked very bad and audio was just low frequency noise. 

I tried looking into `tts.sh` at stage 7 the decoding stage, but I do not see where explicitly a Style Token was applied to aid synthesis, could you please point it out for me? Thank you and let me know if you need more info!

**Comment by kan-bayashi** [comment]
To simplify, the recipe used the groundtruth audio as the reference speech.
https://github.com/espnet/espnet/blob/6a42baad86914dfea1a43b8e91c94395c76fd7a9/egs2/TEMPLATE/tts1/tts.sh#L895

style embedding is added here:
https://github.com/espnet/espnet/blob/6a42baad86914dfea1a43b8e91c94395c76fd7a9/espnet2/tts/tacotron2.py#L420-L422

Style encoder code is here:
https://github.com/espnet/espnet/blob/master/espnet2/tts/gst/style_encoder.py

**Comment by szmmm** [comment]
> To simplify, the recipe used the groundtruth audio as the reference speech.
> https://github.com/espnet/espnet/blob/6a42baad86914dfea1a43b8e91c94395c76fd7a9/egs2/TEMPLATE/tts1/tts.sh#L895
> 
> style embedding is added here:
> https://github.com/espnet/espnet/blob/6a42baad86914dfea1a43b8e91c94395c76fd7a9/espnet2/tts/tacotron2.py#L418-L434
> 
> Style encoder code is here:
> https://github.com/espnet/espnet/blob/master/espnet2/tts/gst/style_encoder.py

Thank you very much for your reply. That helps a lot.

Now for debugging purposes, I want to synthesize some of my training data using the trained model with teacher_forcing (i.e. pass ground truth audio to aid inferencce), and I believe by default ESPNet does not save the trained synthesis audio. Does it work if I pass my training data directory `dump/fbank/train/text` and `dump/fbank/train/feats.scp` to these arguments in stagte 7? (using fbank features here)
```
${python} -m espnet2.bin.tts_inference \
--data_path_and_name_and_type "${_data}/text,text,text" \
--data_path_and_name_and_type ${_speech_data}/${_scp},speech,${_type} \
```
Is there anyway I apply teacher forcing in this case? Thank you very much, and please let me know if you need more info

**Comment by kan-bayashi** [comment]
You can simply change the `--test_sets`.
e.g. 
```
# decode all of the data with teacher forcing
./run.sh --stage 7 --test_sets "tr_no_dev dev eval1" --inference_args "--use_teacher_forcing true"
```

> BTW is teacher-forcing using in training by default, or is it something I have to set in the .yaml configuration file?

The training always uses teacher forcing. No need to specify option.

**Comment by szmmm** [comment]
> You can simply change the `--test_sets`.
> e.g.
> 
> ```
> # decode all of the data with teacher forcing
> ./run.sh --stage 7 --test_sets "tr_no_dev dev eval1" --inference_args "--use_teacher_forcing true"
> ```
> 
> > BTW is teacher-forcing using in training by default, or is it something I have to set in the .yaml configuration file?
> 
> The training always uses teacher forcing. No need to specify option.

This is very helpful, thank you!
