### ISSUE TITLE
Nondeterministic output from Transformer 

### ISSUE THREAD

**Issue by deepconsc** [espnet/espnet#2647]
Config - `transformer.v3.yaml`
Epochs - `2000<`
Dataset - `Custom, 40hr<`

While training, I'm iteratively checking model's robustness to many type of samples (long/short utterances, hard samples, char misplacement, etc.). 

What I've noticed at any stage of training of Transformer is that - output is nondeterministic, it never gives the same spectrogram. 
The differences vary in: 1. energy levels; 2. pitch; 3. duration; 4. consistency of words (sometimes, randomly, words vanish).

In the implementation , you don't use any random noise. Speaker embeddings are optional.

Any ideas?

**Comment by kan-bayashi** [comment]
This is caused by the use of `Prenet`, which always applies the dropout as the same as the Tacotron2.

**Comment by deepconsc** [comment]
@kan-bayashi Thanks for answer.
Would manual seeding help it to run deterministically, or we'd have to mimic dropout non-randomly. 
And, if you've played with it - how it'd affect above-mentioned measurements (energy, pitch, duration..).

**Comment by deepconsc** [comment]
> @kan-bayashi Thanks for answering.
> Would manual seeding help it to run deterministically, or we'd have to mimic dropout non-randomly.
> And, if you've played with it - how it'd affect above-mentioned measurements (energy, pitch, duration..).

Yup, manual seed works like a charm. Tested with various inputs - you just have to find 'the right' seed, equilibrium. 
Closing this issue.
