### ISSUE TITLE
Training Conformer on a smaller dataset (Librispeech train_clean_100)

### ISSUE THREAD

**Issue by unilight** [espnet/espnet#2652]
Hi, this is not really a bug but I am just wondering if anyone has experience with this kind of situation before. I want to train a Conformer model on the train_clean_100 subset of the Librispeech model. I used the default configuration: https://github.com/espnet/espnet/blob/master/egs/librispeech/asr1/conf/tuning/train_pytorch_conformer_large.yaml. The figure below is what I get so far. The loss exploded after 40 epochs. Is there any suggestion on which parameter I should tune? I also found that this model config is quite different from that in the original paper, so I don't know what causes this problem. Hope to hear some advice. Thanks in advance!
![image](https://user-images.githubusercontent.com/11516009/98461489-75a76a00-21e7-11eb-9bb6-6011d383a4ae.png)

**Comment by yuekaizhang** [comment]
Hi, I think you could change the transformer-lr to 1.0 or smaller number like 0.5 to avoid the issue. The default config you used is for training 960hrs. For small dataset, I think you could use this https://github.com/espnet/espnet/blob/master/egs/librispeech/asr1/conf/tuning/train_pytorch_transformer.yaml, just add the conformer related config. Also, to compare between conformer and transformer, our conformer use the similar config with our transformer. So it is different with google's. I believe you could try the google config and share your result.
Thanks!

**Comment by jubang0219** [comment]
In the case of the Transformer, it showed the normal behaviors when I 1) increased the batch-bins, 2) decreased the learning-rate, or 3) increased the warmup-steps. (https://github.com/espnet/espnet/issues/2154)
