### ISSUE TITLE
Normalizing the dataset

### ISSUE THREAD

**Issue by roholazandie** [espnet/espnet#2663]
I have a dataset and I ran your Tactron, Fastspeech and Fastspeech2 with ParallelWaveGAN (all trained from scratch on my dataset). The results are good but still a little bit robotic. I was trying to understand what might go wrong. All the time I tried to compare my dataset with LJSpeech. I realized a difference: my dataset has a higher variance in terms of sound amplitude (in time domain) compared to LJSpeech. I mean the voices are recorded with different sound volumes. Is this something that I have to worry about or the preprocessing stages of ESPNet take care of it? 
I am asking this because if it affects the quality of the results I have to rerun all the experiments again.
And if the ESPNet doesn't have a built-in mechanism to normalize the sound volumes what is the best way to do it?

Thanks

**Comment by kan-bayashi** [comment]
> The results are good but still a little bit robotic.

It is better to determine where the problem came from (text2mel or mel2wav).
Maybe you can check the sample in the analysis-synthesis condition (using natural mel for the mel2wav).

> I mean the voices are recorded with different sound volumes. Is this something that I have to worry about or the preprocessing stages of ESPNet take care of it?

We did not care about it. It is better to normalize the amplitude by yourself.
In my personal experiment, I do the following processings:
(This is a little bit complicated, but if you want to do the best quality, it is worthwhile to try.)
1. Perform the force alignment to get phoneme alignment with pose information
2. Remove the silence at the beginning and the end of the audio with the alignment
3. Adjust the pose length to be the same length with the alignment (e.g. 0.2 sec)
4. Normalize the amplitude of the audio with the average power of the voiced part (i.e., except pose part)

Or if the amplitude of the audio is stable, simply using `sox norm` command is OK.

**Comment by kamo-naoyuki** [comment]
> 1. Perform the force alignment to get phoneme alignment with pose information
> 2. Remove the silence at the beginning and the end of the audio with the alignment
> 3. Adjust the pose length to be the same length with the alignment (e.g. 0.2 sec)
> 4. Normalize the amplitude of the audio with the average power of the voiced part (i.e., except pose part)

@kan-bayashi Do you have some scripts for these items? Can we have it in espnet?  I'm a little interested in that

**Comment by kan-bayashi** [comment]
I have it but it depends on the language and the other tools... (I used Julius force aligner).

**Comment by sw005320** [comment]
Maybe we could continue the discussion on the other issue, but how about using CTC segmentation?
If we prepare a pre-trained phoneme model for each language, does it work?
We may also build a single multilingual phoneme model for this purpose?

**Comment by kan-bayashi** [comment]
Important point is the accuracy of the pose estimation.
To speak of extremes, only the pose segment information is needed to perform the above preprocessing.

**Comment by lumaku** [comment]
Regarding CTC segmentation:
Given correctly transcribed utterances, I would expect that alignments obtained from Julius and from CTC segmentation are similar.

I did not evaluate how well pauses are detected, but expect that pauses between utterances are detected correctly by CTC segmentation as the time between utterances. It works without a separate token for pauses, but caveat, if a spoken part is not in the transcription, it is then probably also detected as pause. Furthermore, the new option to set the transition cost for blank to zero (`--gratis-blank`) should really help for longer pauses; I tested this successfully with segments of up to several seconds long.

**Comment by sw005320** [comment]
Yes, I was intending to refer to your recent work.
We may probably realize this pause estimation with CTC alignment.
If the pause estimation is an essential part, we may not need a phoneme model.
We could make some generic pause estimater by building a domain robust (multilingual, mixed corpora) ASR and using it for CTC alignment.

**Comment by Mingrg** [comment]
> > The results are good but still a little bit robotic.
> 
> It is better to determine where the problem came from (text2mel or mel2wav).
> Maybe you can check the sample in the analysis-synthesis condition (using natural mel for the mel2wav).
> 
> > I mean the voices are recorded with different sound volumes. Is this something that I have to worry about or the preprocessing stages of ESPNet take care of it?
> 
> We did not care about it. It is better to normalize the amplitude by yourself.
> In my personal experiment, I do the following processings:
> (This is a little bit complicated, but if you want to do the best quality, it is worthwhile to try.)
> 
> 1. Perform the force alignment to get phoneme alignment with pose information
> 2. Remove the silence at the beginning and the end of the audio with the alignment
> 3. Adjust the pause length to be the same length with the alignment (e.g. 0.2 sec)
> 4. Normalize the amplitude of the audio with the average power of the voiced part (i.e., except pause part)
> 
> Or if the amplitude of the audio is stable, simply using `sox norm` command is OK.

@kan-bayashi Hi, 
What is the `average power` in:
` 4. Normalize the amplitude of the audio with the average power of the voiced part (i.e., except pause part)`
Does power=db?

**Comment by kan-bayashi** [comment]
It means averaged amplitude.
