### ISSUE TITLE
The result is bad when I use reduction factor=1 on tacotron2 recipe

### ISSUE THREAD

**Issue by WanderingSven** [espnet/espnet#2665]
hello everyone:
         I am trying to implement asr and tts joint training by espnet1. When I use defualt libritts config under tacotron 2, the attention map is seems to be right.  However, asr model can't get high accuracy rate. To facilitate TTS training, I add 50 ms fixed-length mute to start of sentence and 100ms fixed-length mute to end of the sentence on each utterance. I try to set reduction factor to 1 and max frame length to 2000, but I can't get clear attention map. Has anyone tried to get a correct result when the reduction factor is equal to 1?

The feature extraction is as follow:
```
fs=16000         # sampling frequency
fmax=""           # maximum frequency
fmin=""           # minimum frequency
n_mels=128    # number of mel basis
n_fft=800       # number of fft points
n_shift=160    # number of shift points
win_length="" # window length
```

The config is as follow:
```
# encoder related
embed-dim: 512
elayers: 1
eunits: 512
econv-layers: 3 # if set 0, no conv layer is used
econv-chans: 512
econv-filts: 5
# decoder related
dlayers: 2
dunits: 1024
prenet-layers: 2  # if set 0, no prenet is used
prenet-units: 256
postnet-layers: 5 # if set 0, no postnet is used
postnet-chans: 512
postnet-filts: 5
use-speaker-embedding: true
# attention related
atype: location
adim: 128
aconv-chans: 32
aconv-filts: 15      # resulting in filter-size = aconv-filts * 2 + 1
cumulate-att-w: true # whether to cumulate attetion weight
use-batch-norm: true # whether to use batch normalization in conv layer
use-concate: true    # whether to concatenate encoder embedding with decoder lstm outputs
use-residual: false  # whether to use residual connection in encoder convolution
use-masking: true    # whether to mask the padded part in loss calculation
bce-pos-weight: 1.0  # weight for positive samples of stop token in cross-entropy calculation
reduction-factor: 1
# minibatch related
batch-size: 64
batch-sort-key: output # shuffle or input or output
maxlen-in: 150         # if input length  > maxlen-in, batchsize is reduced (if use "shuffle", not effect)
maxlen-out: 400        # if output length > maxlen-out, batchsize is reduced (if use "shuffle", not effect)

# optimization related
lr: 1e-3
eps: 1e-6
weight-decay: 0.0
dropout-rate: 0.5
zoneout-rate: 0.1
epochs: 60
patience: 0
```
The attention map after 50 epoch(modeling unit:phone): 
![image](https://user-images.githubusercontent.com/26950286/98621273-d945aa80-2341-11eb-9538-1fe8a92150d2.png)
The attention map after 60 epoch(modeling unit:phone): 
![image](https://user-images.githubusercontent.com/26950286/98621489-4f4a1180-2342-11eb-8822-02c0061f9f40.png)
The attention map after 50 epoch(modeling unit:character): 
![image](https://user-images.githubusercontent.com/26950286/98683456-06c14100-23a0-11eb-9ee5-a07ecd10156f.png)
The attention map after 60 epoch(modeling unit:character): 
![image](https://user-images.githubusercontent.com/26950286/98683573-29ebf080-23a0-11eb-967c-3226a7ecf55a.png)

**Comment by kan-bayashi** [comment]
To get the diagonal attention, the difference between adjoined frames is important.
If the difference is small, the decoder tend to be like an auto-encoder, no diagonal attention is obtained. 
In your case, the shift size is relatively small compared to the TTS setting.
This is the one of the reasons why you could not get the diagonal attention.
Another problem is libritts text. LibriTTS text does not contain the pause information, which makes it difficult to learn the diagonal attention (see the discussion in #2565).

One of the solutions is to use guided attention loss, which help to learn the diagonal attention.
https://github.com/espnet/espnet/blob/e83d24bfc1ff173de8ba0af70dcafcec3e4eaf05/egs/ljspeech/tts1/conf/tuning/train_pytorch_tacotron2.v3.yaml#L33

**Comment by WanderingSven** [comment]
Thank you for the detailed reply.
