### ISSUE TITLE
can anyone tells me why the loss looks like this?

### ISSUE THREAD

**Issue by 200987299** [espnet/espnet#2666]
this happened when I do experiments on chime 4 data. I changed nothing but config the experiment using only att or ctc. this happens when I do training using attention along but it also happened one time when I used ctc + att with rnn-rnn stracture.

Thanks for the hints.

![Screenshot from 2020-11-10 10-13-05](https://user-images.githubusercontent.com/33377212/98626254-478f6a80-234c-11eb-9482-1c83760396d8.png)

**Comment by 200987299** [comment]
there was one post said that this happens because the training was interrupted and it did not resume from where it was interrupted. But I am not 100% sure. If anyone had this issue before, please let me know.

Thank you!

**Comment by WanderingSven** [comment]
You may have more than one "events.out.tfevents" file in your showed directory, you should only save one file.

**Comment by 200987299** [comment]
> You may have more than one "events.out.tfevents" file in your showed directory, you should only save one file.

thank you !
