### ISSUE TITLE
How to use transfer learning in espnet2

### ISSUE THREAD

**Issue by lin-nerd** [espnet/espnet#2667]

**Comment by lin-nerd** [comment]
Hi, everyone

I have seen the #670 and use the same way, but it seems that this function is not used in espnet2.

**Comment by kamo-naoyuki** [comment]
Sorry, it's not well documented,  but we  --pretrain_path and --pretrain_key option.

```sh
# Initialize the model
python -m espnet2.bin.asr_train --pretrain_path some/where/model.pth
# e.g. Assign decoder weight
python -m espnet2.bin.asr_train --pretrain_path some/where/decoder.pth --pretrain_key decoder
```

Practical example can be seen here for tts recipe:  https://github.com/espnet/espnet/blob/master/egs2/jvs/tts1/README.md#4-run-fine-tuning

**Comment by lin-nerd** [comment]
@kamo-naoyuki 
Ok, thanks

I got another issue, if i enter--pretrain_key ""
I get these  reply:
size mismatch for tts.enc.embed.weight: copying a param with shape torch.Size([52, 512]) from checkpoint, the shape in current model is torch.Size([44, 512]).

But if i enter --pretrain_key "decode"
AttributeError: 'ESPnetTTSModel' object has no attribute 'decode'

**Comment by kan-bayashi** [comment]
> size mismatch for tts.enc.embed.weight: copying a param with shape torch.Size([52, 512]) from checkpoint, the shape in current model is torch.Size([44, 512]).

This means that your token_list is different from the pretrained one.

> But if i enter --pretrain_key "decoder"

If you want to load only the decoder, try `--pretrain_key tts.dec`

**Comment by lin-nerd** [comment]
> > size mismatch for tts.enc.embed.weight: copying a param with shape torch.Size([52, 512]) from checkpoint, the shape in current model is torch.Size([44, 512]).
> 
> This means that your token_list is different from the pretrained one.
@kan-bayashi 
Ok, I see.

I have seen #1693, how to load all of the parameters except the pretrained token list?
Or what --pretrain_key option can fix this problem?

Thanks a lot!!!!!

**Comment by kan-bayashi** [comment]
A little bit complicated but you can make the config as follows (Tacotron2 case):
```yaml
pretrain_path:
  - /path/to/model.pth
  - /path/to/model.pth
  - /path/to/model.pth
pretrain_key:
  - tts.dec
  - tts.enc.convs
  - tts.enc.blstm
```

**Comment by kan-bayashi** [comment]
Or remove the mismatch key from the `pth` file (in your case `tts.enc.embed`).

**Comment by kamo-naoyuki** [comment]
> ```yaml
> pretrain_path:
>   - /path/to/model.pth
>   - /path/to/model.pth
>   - /path/to/model.pth
> pretrain_key:
>   - tts.dec
>   - tts.enc.convs
>   - tts.enc.blstm
> ```

Sorry, --pretrain_key might be a bit confusing, but this is not working. The right usage is as follows:

```python
torch.save("decoder.pth", tts_model.tts.dec.state_dict())
```
```
--pretrain_path decoder.pth --pretrain_key tts.dec
```

**Comment by kamo-naoyuki** [comment]
When I added this option,  I didn't think deeply about this. 

I'll remove these options and rename it to `--init_param`:

```sh
--pretrain_path <file_path>:<src_key>:<dst_key>

# e.g. Initialize model
--init_param model.pth
# e.g. Initialize model.decoder
--init_param model.pth:decoder:decoder

# e.g. Initialize model.decoder (Current behaviour)
--init_param decoder.pth::decoder
```

**Comment by kan-bayashi** [comment]
Document updated.
#2680 #2685

**Comment by lin-nerd** [comment]
Thanks a lot!
