### ISSUE TITLE
Further training of ASR models in espnet2

### ISSUE THREAD

**Issue by r4nc0r** [espnet/espnet#2668]
Hi,

I trained an asr model on the german commonvoice dataset and wanted to further improve it with the data from the german voxforge dataset. How do I do that?

**Comment by kamo-naoyuki** [comment]
If you ask about fine-tuning/transfer-learning on espnet2: See I wrote at #2667.  If you used bpe tokens for training,  but I don't know the commonvoice bpe model is good with the voxforge dataset. Maybe, no problem.

If you'll merge two datasets and train from scratch, you can concatenate the text files: `wav.scp`, `text`, etc.

**Comment by r4nc0r** [comment]
okay thanks :)
