### ISSUE TITLE
Support Ngram LM for espnet2 asr decoding ?

### ISSUE THREAD

**Issue by JucyCherry** [espnet/espnet#2670]
hi~ Could I use ngram LM to do ASR decoding for espnet2 models？Is there any egs for example？
by the way~ What might be the reason why rnnLM get a worse performance than omitting LM

**Comment by kamo-naoyuki** [comment]
No, ngram is not ported yet, but it's very easy to port. I didn't because I don't have enough time.

**Comment by JucyCherry** [comment]
thanks a lot !~
