### ISSUE TITLE
Quality of speech is dependent on target speech in Multispeaker Tacotron

### ISSUE THREAD

**Issue by Piteryo** [espnet/espnet#2671]
**Describe the bug**
I'm trying to train Multispeaker GST Tacotron 2 using my own multispeaker Russian dataset with 3 speakers. The dataset is cleared, audio is trimmed. I'm using default Tacotron 2 parameters from VCTK config with changed FS to 22050, n_fft to 1024, win_length to 1024 and n_shift to 256 as these parameters worked better with other implementations of Tacotron 2. Also, I changed cleaner and phoneme tokenizer for my dataset (I've tested it, it seems that it works well). As a result, I have good alignment on images even after 6-7 epochs of training and it won't change over time:
![image](https://user-images.githubusercontent.com/4750178/98795037-ce127d80-241a-11eb-8d3b-7aa46cec7586.png)

The problem is that when I test it I get bumbling speech: each word is pronounced correctly but every pause is super long and at the end of each word the ending is repeated or blurred. Sometimes it stops producing output at the beginning of a sentence (and only outputs emptiness for 3-4 seconds instead of text). Moreover, I noticed, that when I use different target speech samples, the text is pronounced differently - in some cases, it produces better output with less bumbling, in other cases the output is worse for the same text. Also, I've tried not adding GST to the output of the encoder after training - the speech is still bumbling. 

What am I doing wrong and what can help to solve this issue?
**Basic environments:**
 
I'm using your docker container for training. I'm using 5 Nvidia Tesla v100 GPUs.

**Comment by kan-bayashi** [comment]
Let me confirm some points:

- Does your dataset include a long pause in the middle of text?
- Does your dataset include a symbol which is corresponding to the pause?
- How many speakers are there in your dataset?
- Do you tune `gst_tokens`? I think we need to tune this parameter according to the number of speakers.
- Is the attention plot in training? How was it in decoding?

> every pause is super long and at the end of each word the ending is repeated or blurred.

Is this phenomena happened even if we use the sample of the training speaker as the reference?

> Moreover, I noticed, that when I use different target speech samples, the text is pronounced differently 

This is normal behavior, I think. Originally GST tries to change the pronunciation according to the reference speech.

**Comment by Piteryo** [comment]
@kan-bayashi 
Sorry for the late reply. That was my bad, in my dataset separation symbol was a tab and it is somehow was deleted on the last stage of preprocessing. So in the data folder, I have all necessary tokens and texts containing tab separation symbols but in dump dir, a tab is missing (it is replaced to space). That's why I didn't notice it earlier.

After training on corrected transcriptions the audio is much better, however, using some reference audios even from training dataset produce long pauses (even if this file doesn't contain them). Reducing the number of `gst_tokens` does not solve this problem but it is possible to find reference audios that don't produce extra pauses.

As it was my fault I'm closing this issue, but please notice that there is this strange behaviour in preprocessing, that some symbols may disappear (didn't find any references to this in the documentation).
