### ISSUE TITLE
ASR batch decoding (api v2) uses only one cpu core in stage 3

### ISSUE THREAD

**Issue by mrazizi** [espnet/espnet#2682]
I am using **recog_wav.sh** script to decode a wav file. I followed what @b-flo suggested [here](https://github.com/espnet/espnet/issues/2186#issuecomment-662295543) (using api v2 with batch size 1).

By monitoring my cpu usage using **htop**, we can see that only one CPU core is being used in **stage 3: Decoding** (figure below):

![onecpu3](https://user-images.githubusercontent.com/10348086/99180501-f6acb700-273b-11eb-94d7-91e2eb16c18d.png)

Is there a way to use multiple CPUs (for a single file) in **stage 3: Decoding** to make decoding faster?

**Basic environments:**
I'm using **espnet/espnet:gpu-cuda10.1-cudnn7-u18** docker image.

**decode.yaml:**
```
batchsize: 1
beam-size: 10
penalty: 0.0
maxlenratio: 0.0
minlenratio: 0.0
ctc-weight: 0.5
lm-weight: 0.3
```

**Command I'm using to decode:**
``../../../utils/recog_wav.sh --cmvn trained_model/cmvn.ark --lang_model trained_model/lm/rnnlm.model.best --recog_model trained_model/am/model.acc.best --decode_config conf/decode.yaml asr_test_set_small/P006056.wav``

**Time Reports:**
Test file duration: **9.480** s
Total time recog_wav.sh takes: **11.492** s
 

**Trained Model:**
I used commonvoice recipe and used **run.sh** script to train a model on commonvoice persian dataset.

**Comment by keshawnhsieh** [comment]
If you have GPU enabled in you environment, set ngpu=1 to use gpu to speed up decoding may be a good idea.

**Comment by sw005320** [comment]
We force to set the single thread CPU decoding as default for some stable use of the cluster environment.
https://github.com/espnet/espnet/blob/master/egs/an4/asr1/path.sh#L13
If you change this part, you could enable multi-threading and CPU decoding becomes faster.

**Comment by mrazizi** [comment]
> We force to set the single thread CPU decoding as default for some stable use of the cluster environment.
> https://github.com/espnet/espnet/blob/master/egs/an4/asr1/path.sh#L13
> If you change this part, you could enable multi-threading and CPU decoding becomes faster.

Thanks! That's what I was looking for.
I close this issue.
