### ISSUE TITLE
How to improve the utilization rate of GPU in ASR training

### ISSUE THREAD

**Issue by chenwuchen** [espnet/espnet#2683]
**Describe the issue**
pytorch backend , GPU utilization is only 30%，How to improve the utilization rate of GPU in ASR training

**Comment by sw005320** [comment]
Could you follow the bug report templated?
GPU utilization is based on a lot of factors.

**Comment by chenwuchen** [comment]
**Describe the bug**
pytorch backend , GPU utilization is only 30%，How to improve the utilization rate of GPU in ASR training


**Basic environments:**
 - OS information: [Linux  3.10.0_3-0-0-17 #181 SMP Thu Feb 8 16:34:08 CST 2018 x86_64 x86_64 x86_64 GNU/Linux]
 - python version: [3.6.5]
 - espnet version: [espnet 0.9.2]
 - Git hash [4fe8946]
   - Commit date []
 - pytorch version [ pytorch 1.0.0]
 
- OS information: Linux 3.10.0_3-0-0-17 #181 SMP Thu Feb 8 16:34:08 CST 2018 x86_64

PyTorch version: 1.4.0
Is debug build: No
CUDA used to build PyTorch: 10.2

OS: CentOS Linux release 6.3 (Core)
GCC version: (GCC) 4.8.2
CMake version: version 3.10.1

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 10.2
GPU models and configuration:
GPU 0: Tesla P40
GPU 1: Tesla P40
GPU 2: Tesla P40
GPU 3: Tesla P40
GPU 4: Tesla P40
GPU 5: Tesla P40
GPU 6: Tesla P40
GPU 7: Tesla P40


**Task information:**
 - Task: [ASR]
 - Recipe: [aishell]
 - ESPnet1

**Comment by chenwuchen** [comment]
> Could you follow the bug report templated?
> GPU utilization is based on a lot of factors.
What are the influencing factors,
What are the main factors？

**Comment by sw005320** [comment]
Thanks!
Could you check this?
https://espnet.github.io/espnet/tutorial.html#multiple-gpu-tips
`--n-iter-processes` will mitigate the issue.

**Comment by chenwuchen** [comment]
> --n-iter-processes
I have set this parameter --n-iter-processes=8, but the GPU utilization rate is still only 30% 
Are there other influencing factors?

**Comment by sw005320** [comment]
batch size may be too small?

**Comment by chenwuchen** [comment]
> batch size may be too small?
32

**Comment by chenwuchen** [comment]
> batch size may be too small?
I will try
