### ISSUE TITLE
X-Vector at Testing Stage ESPNet1 TTS

### ISSUE THREAD

**Issue by szmmm** [espnet/espnet#2688]
Hello, I realised for the evaluation data set the xvectors are extracted from the test utterance. But to test performance I would like to use the training x-vectors to synthesize the evaluation transcription. Does this make sense? Am I right to say that the x-vectors extracted from the evaluation utterances are not seen by the model during training, so would not be good to use when testing its performance?

Because the speaker IDs used in the evaluation set are different from the training set. I realised it is impossible to use 
`local/update_json.sh ${dumpdir}/eval/data.json ${nnet_dir}/xvectors_train/spk_xvector.scp` directly. How can I append training x-vectors in the `.json` file for the evaluation data set?

If my question is not clear please ask. Thank you!

**Comment by kan-bayashi** [comment]
> But to test performance I would like to use the training x-vectors to synthesize the evaluation transcription. Does this make sense?

Your concern is right. It is better to use the different utterance to extract x-vector for the fair evaluation.
Current recipe uses evaluation utterance to simplify the preparation step.

> How can I append training x-vectors in the .json file for the evaluation data set?

The easiest way is directly modifying .json file to replace x-vector path.

**Comment by szmmm** [comment]
> > But to test performance I would like to use the training x-vectors to synthesize the evaluation transcription. Does this make sense?
> 
> Your concern is right. It is better to use the different utterance to extract x-vector for the fair evaluation.
> Current recipe uses evaluation utterance to simplify the preparation step.
> 
> > How can I append training x-vectors in the .json file for the evaluation data set?
> 
> The easiest way is directly modifying .json file to replace x-vector path.

Thank you, I will look into that. What if the evaluation set is large, is there a more efficient way of doing so?
