### ISSUE TITLE
Qn: Attention Plot Issue when turning on guided_attn_loss ESPNet1 TTS

### ISSUE THREAD

**Issue by szmmm** [espnet/espnet#2689]
Hello, it is me again. I am using Tacotron 2 + x-vector to doing synthesis on BABEL data, and I used `use-guided-attn-loss: true` Could someone explain to me why my attention plot looks like the following?

![106_00300_A_20120415_005214_022433 ep 86](https://user-images.githubusercontent.com/64835377/99418442-edb21600-28f2-11eb-9f5a-d9aea317a58e.png)
![106_00300_A_20120415_005214_017358 ep 82](https://user-images.githubusercontent.com/64835377/99418482-facf0500-28f2-11eb-913d-7cc4dac88125.png)

The first plot looks like the decoder side does not make use of any encoder information after location 20. The second plot seems to say that although all encoder attentions are used by the decoder, beyond location 40 on the decoder side there is no longer attention information. What might be the cause of this behaviour?

Apologies for the consequetive posts of questions, as I am really new to TTS and you have been very kind and patient to answer my questions. I really appreciate it. If you need more info please let me know.

**Comment by kan-bayashi** [comment]
Which version did you use?
I think this is a plot bug which is already fixed (#1761).

**Comment by szmmm** [comment]
> Which version did you use?
> I think this is a plot bug which is already fixed (#1761).

Thank you for you reply.
I used this old version https://github.com/creatorscan/espnet/tree/asrtts3-v.0.4.0/egs/librispeech/asrtts. 
May I ask you if this bug was just a bug for the plot or was a bug of attention learning?

**Comment by kan-bayashi** [comment]
Just a plot problem.
