### ISSUE TITLE
Tuning ESPnet2 ASR recipe

### ISSUE THREAD

**Issue by kamo-naoyuki** [espnet/espnet#2694]
This is a status report.

Anybody, please help us to update the espnet2 recipes!! 
I must develop the core modules of espnet2 for future, so I can't assign much times for updating recipes.

### Regulation

- Use `feats_type=raw`
  - Don't use `feats_type=fbank_pitch`
- Use ASR conformer/transformer model (and transformer LM)
- Use Character/BPE level LM instead of Word level LM. 
  - ESPnet2 doesn't support Word LM. 
- Use `batch_type=numel` and `batch_bins`
  - Don't use `batch_type=folded` for training efficiency
- We don't need to compare the result fairly with espnet1. 
    - It's impossible to compare fairly in many cases.
    - Please try also the other setting of espnet1.
- Please upload your pretrained model.
- Any number of GPUS can be used.
   - Please make the batch_bins larger as possible if it doesn't degrade the performance,

### Note

- It's better to refer the perplexity when LM tuning. It's really correlated to the recognition performance.

### Status

| Task                   |Dataset|Criterion| ESPnet1 | ESPnet2 | Assign|
| -----------            | :----:| :----:   | :----:  | :----:  | :----: |
| Aishell |dev/test  |CER          | 4.6/5.1    | 4.4/4.7   | Done  |
| AMI|ihm_dev/ihm_test  |WER          | 25.0/25.6  | 19.1/18.3   | Done  |
|CHiME4 | et05_real_isolated_1ch_track |WER|11.3|||
| Common Voice |dev/test   |WER    |    |   |Done|
| CSJ |eval1/eval2/eval3  |CER    | 5.7/3.8/4.2     | 4.5/3.3/3.6      | Done |
| Dirha_wsj  |Beam_Circular_Array |WER |29.7| 11.8 |Done|
|JSUT |dev/eval1 | CER |13.0/14.5 |12.0/13.9|Done|
| Librispeech |dev_clean/dev_other/test_clean/test_other | WER  |1.9/4.9/2.1/4.9   | 1.9/4.6/2.1/4.7|Done|
|REVERB |et_real_far/et_real_near , no_frontend, |WER|57.7/60.4| 6.3/6.0 | Done |
| HKUST |dev  |CER            | 23.5    |  21.2 | Done |
|Switchboard | (eval2000) callhm/swbd | WER|14.0/6.8||
| TEDLIUM2 |dev/test |WER           |   8.6/7.2     |   | |
|TEDLIUM3 |dev/test |WER |9.6/7.6||@kamo-naoyuki|
|TIMIT phone |dev/test |WER |N/A/20.5|17.9/19.5|Done|
| WSJ |dev93/eval92      |WER      | 7.0/4.7  | 6.6/4.6     | Done |

**Comment by hchung12** [comment]
@kamo-naoyuki , I am going to tune the recipes for Common Voice and JSUT domains.

**Comment by kamo-naoyuki** [comment]
@hchung12 Great, thanks!

**Comment by yuekaizhang** [comment]
FYI, for aishell, espnet1's result w/o external LM? However, espnet2's result is w/ LM?

**Comment by kamo-naoyuki** [comment]
@yuekaizhang Yes

**Comment by kamo-naoyuki** [comment]
@yuekaizhang I added wo LM result. 
 https://github.com/espnet/espnet/tree/master/egs2/aishell/asr1#without-lm

**Comment by hchung12** [comment]
@kamo-naoyuki, I created PR #2720  for JSUT conformer recipe that achieves 12.0/13.9 CER(%) for JSUT domain.

**Comment by hchung12** [comment]
@kamo-naoyuki, In the status table, The espnet1 WER of common voice is 2.2/2.3. Which domain is the performance for?

I can not find such WER in https://github.com/espnet/espnet/blob/master/egs/commonvoice/asr1/RESULTS.md and
https://github.com/ftshijt/espnet/blob/master/egs/commonvoice/asr1/RESULTS.md.

**Comment by kamo-naoyuki** [comment]
I just copied it from https://github.com/espnet/espnet#asr-results, but I can't find it, too.

@sw005320 @ftshijt Do you know what is this?

**Comment by ftshijt** [comment]
@kamo-naoyuki Hi Kamo, those are still in PR #2739 
I will update the model links by the end of tomorrow and it will be ready at that time.

**Comment by yuekaizhang** [comment]
@kamo-naoyuki , Hi, anyone is tuning swbd for espnet2? I'd love to do that if no one is doing it now.

**Comment by kamo-naoyuki** [comment]
@yuekaizhang Thank you! I'm glad if you do that!
