### ISSUE TITLE
larger difference between train and valid in the same training stage in conformer than transformer

### ISSUE THREAD

**Issue by housebaby** [espnet/espnet#2695]
I trained conformer on librispeech 960 hours.
I found that the acc and loss difference between train and validation is much larger in conformer than in transformer.
Though training loss and acc of conformer is better that transformer,  the valid loss and acc is worse.
Is the conformer over-fitted? I use the default config conf/tuning/train_pytorch_conformer_large.yaml
How to make the difference between train and valid （loss/acc) smaller?
    | conformer | transformer
-- | -- | --
main/loss_ctc | 8.067525618 | 28.10925629
main/loss_att | 6.341286743 | 12.79333486
main/acc | 0.966620617 | 0.935232206
main/loss | 6.859158418 | 17.38811153
validation/main/loss_ctc | 21.89373405 | 20.69619303
validation/main/loss_att | 25.12428984 | 12.53324396
validation/main/acc | 0.878702232 | 0.91740611
validation/main/loss | 24.1551229 | 14.98212893
epoch | 25 | 25

transformer acc and loss
![image](https://user-images.githubusercontent.com/9246556/99610254-6e385a00-2a4c-11eb-8f72-15bf0a976437.png)
conformer acc and loss
![image](https://user-images.githubusercontent.com/9246556/99610284-7b554900-2a4c-11eb-8b4a-9c56661ca408.png)

**Comment by kan-bayashi** [comment]
Maybe it is better to show the training curve.

**Comment by housebaby** [comment]
> Maybe it is better to show the training curve.
Trainging carve is added. Looking forward for your feedback
