### ISSUE TITLE
Problem in Data Preparation

### ISSUE THREAD

**Issue by roholazandie** [espnet/espnet#2698]
I made some preprocessing to my dataset wav files but haven't change the names (I checked the number of files etc) but this time after running it stuck at data preparation:
```
2020-11-18T09:46:06 (tts.sh:275:main) Stage 1: Data preparation for data/tr_no_dev, data/dev, etc.
2020-11-18T09:46:06 (data.sh:16:main) local/data.sh 
2020-11-18T09:46:06 (data.sh:39:main) stage -1: Data Download
already exists. skipped.
2020-11-18T09:46:06 (data.sh:44:main) stage 0: Data Preparation
utils/validate_data_dir.sh: WARNING: you have only one speaker.  This probably a bad idea.
   Search for the word 'bold' in http://kaldi-asr.org/doc/data_prep.html
   for more information.
utils/validate_data_dir.sh: file data/train/utt2spk is not sorted or has duplicates
```
It is weird because it used to work before I made the preprocessing. What can go wrong here?

**Comment by kamo-naoyuki** [comment]
What's recipe?
When rerunning the data preparation script, some recipes are failed to run.  

e.g. The following script has such a problem.

https://github.com/espnet/espnet/blob/ff29b02342fce16f41afcb462d4edd4fa8fae9ab/egs2/jsut/asr1/local/data_prep.sh#L38-L42

`>>` can cause this problem.

This should be a bug, but espnet is created by many contributors, so such thoughtless scripts are likely to be mixed.
A workaround is removing your data directory before rerunning script.

For your case, you should have run the script without  the data preparation stage. e.g `--stage 2`

**Comment by roholazandie** [comment]
This is the recepie for LJSpeech. I started from ```--stage 2``` but it gives me the following error:
```
2020-11-18T12:01:50 (tts.sh:187:main) ./tts.sh --lang en --feats_type raw --fs 22050 --n_fft 1024 --n_shift 256 --token_type phn --cleaner tacotron --g2p g2p_en_no_space --train_config conf/train.yaml --inference_config conf/decode.yaml --train_set tr_no_dev --valid_set dev --test_sets dev eval1 --srctexts data/tr_no_dev/text --audio_format flac --stage 2
2020-11-18T12:01:50 (tts.sh:292:main) Stage 2: Format wav.scp: data/ -> dump/raw/
copy_data_dir.sh: no such file data/tr_no_dev/utt2spk

```

**Comment by kamo-naoyuki** [comment]
You must rerun.

**Comment by kan-bayashi** [comment]
@kamo-naoyuki 
The file is removed at the first, so I think the duplication is not caused.
https://github.com/espnet/espnet/blob/ff29b02342fce16f41afcb462d4edd4fa8fae9ab/egs2/jsut/asr1/local/data_prep.sh#L28-L31

@roholazandie 
> This is the recepie for LJSpeech.

A statement is a bit confusing.
The correct one is your own recipe based on ljspeech recipe.

I think the problem is simply unsorted file.
The easiest solution is to use `utils/fix_data_dir.sh` at the last stage of `data.sh`.
e.g. `utils/fix_data_dir.sh data/tr_no_dev`

**Comment by kamo-naoyuki** [comment]
@kan-bayashi Oh, sorry, you are right. 

I can't understand why this happens. Do you have same name wav files in "${db_root}/LJSpeech-1.1"?

**Comment by kamo-naoyuki** [comment]
As you said you modified wav file, but how did you do the original wav files?
For example, if you just renamed the directory name in same place to keep the original data, it can cause this problem.

```sh
mv ${db_root}/LJSpeech-1.1/wav ${db_root}/LJSpeech-1.1/wav.bak
```

**Comment by roholazandie** [comment]
@kan-bayashi yes you are right my recepie is based on LJSpeech not the LJSpeech itself. I used the script ```utils/fix_data_dir.sh data/train``` to fix it. I get the following:

```
utils/fix_data_dir.sh: file data/train/utt2spk is not in sorted order or not unique, sorting it
utils/fix_data_dir.sh: file data/train/wav.scp is not in sorted order or not unique, sorting it
fix_data_dir.sh: kept all 11279 utterances.
fix_data_dir.sh: old files are kept in data/train/.backup
```
But when I run ```./run.sh``` or ```./run.sh --stage 2``` I still get the same error:

```
2020-11-19T09:46:27 (tts.sh:187:main) ./tts.sh --lang en --feats_type raw --fs 22050 --n_fft 1024 --n_shift 256 --token_type phn --cleaner tacotron --g2p g2p_en_no_space --train_config conf/train.yaml --inference_config conf/decode.yaml --train_set tr_no_dev --valid_set dev --test_sets dev eval1 --srctexts data/tr_no_dev/text --audio_format flac
2020-11-19T09:46:28 (tts.sh:275:main) Stage 1: Data preparation for data/tr_no_dev, data/dev, etc.
2020-11-19T09:46:28 (data.sh:16:main) local/data.sh 
2020-11-19T09:46:28 (data.sh:39:main) stage -1: Data Download
already exists. skipped.
2020-11-19T09:46:28 (data.sh:44:main) stage 0: Data Preparation
utils/validate_data_dir.sh: WARNING: you have only one speaker.  This probably a bad idea.
   Search for the word 'bold' in http://kaldi-asr.org/doc/data_prep.html
   for more information.
utils/validate_data_dir.sh: file data/train/utt2spk is not sorted or has duplicates

```

**Comment by kamo-naoyuki** [comment]
`./run.sh --stage 1` overwrites the data directory, so if you once run it, you need to apply utils/fix_data_dir.sh again if the problem is unsorted.
It's better to validate after creation of data directory.

```sh
utils/fix_data_dir.sh ...
utils/validate_data_dir.sh ...
```

**Comment by kamo-naoyuki** [comment]
Did you modify path.sh? Do you set LC_ALL=C? I can't understand why it's not sorted.

**Comment by roholazandie** [comment]
So I run ```./utils/fix_data_dir.sh data/train/```:
```
./utils/fix_data_dir.sh: file data/train//utt2spk is not in sorted order or not unique, sorting it
./utils/fix_data_dir.sh: file data/train//wav.scp is not in sorted order or not unique, sorting it
fix_data_dir.sh: kept all 11279 utterances.
fix_data_dir.sh: old files are kept in data/train//.backup
```
and then I run ```./utils/validate_data_dir.sh --no-feats data/train```:
```
/utils/validate_data_dir.sh: WARNING: you have only one speaker.  This probably a bad idea.
   Search for the word 'bold' in http://kaldi-asr.org/doc/data_prep.html
   for more information.
./utils/validate_data_dir.sh: Successfully validated data-directory data/train

```
finally I run ```./run.sh --stage 2```:
```
2020-11-19T10:15:45 (tts.sh:187:main) ./tts.sh --lang en --feats_type raw --fs 22050 --n_fft 1024 --n_shift 256 --token_type phn --cleaner tacotron --g2p g2p_en_no_space --train_config conf/train.yaml --inference_config conf/decode.yaml --train_set tr_no_dev --valid_set dev --test_sets dev eval1 --srctexts data/tr_no_dev/text --audio_format flac --stage 2
2020-11-19T10:15:45 (tts.sh:292:main) Stage 2: Format wav.scp: data/ -> dump/raw/
copy_data_dir.sh: no such file data/tr_no_dev/utt2spk

```
No, I haven't touch path.sh. I copied it from LJSpeech. Now I checked it and I see this line:
```
export LC_ALL=C
```

**Comment by kamo-naoyuki** [comment]
Why did you apply fix_data_dir to data/train? It's not used for ljspeech recipe.

https://github.com/espnet/espnet/blob/4b848aab49c8d0bc4a8be4dd94e791e47063eb78/egs2/ljspeech/tts1/run.sh#L20-L22

Why don't you have data/tr_no_dev/utt2spk? It's should be created here.

https://github.com/espnet/espnet/blob/4b848aab49c8d0bc4a8be4dd94e791e47063eb78/egs2/ljspeech/tts1/local/data.sh#L76-L84


I think you procedure is something wrong.

**Comment by kamo-naoyuki** [comment]
It's better not to use `--stage 2` option. Maybe you are confused by my comments.
It's better to insert fix_data_dir.sh in local/data.sh as @kan-bayashi said.

**Comment by roholazandie** [comment]
Perfect! I just added ```fix_data_dir.sh data/train``` before ```./utils/validate_data_dir.sh --no-feats data/train``` in ```local/data.sh``` and it fixed the problem! Thank you so much. Do you think you add this line to the recipe of LJSpeech then other people don't have the same problem as me?

**Comment by kamo-naoyuki** [comment]
Good. 

Thanks, but I can't still understand why this happens...

**Comment by kamo-naoyuki** [comment]
I checked my LJSpeech data, but the naming seems different from yours.
Why?

```
LJ001-0001.wav  LJ006-0221.wav  LJ012-0076.wav
...
```

**Comment by roholazandie** [comment]
The names are different because I am working on a different dataset. I will release and open-source it soon. I think I will update you to put a recipe for my dataset too. It's a one speaker male dataset.
I also don't know why this happens. It is interesting because it was working a week ago on the same dataset!!

**Comment by kamo-naoyuki** [comment]
Could you show the head of directory containing?

**Comment by kamo-naoyuki** [comment]
I guess the problem is your naming.

**Comment by roholazandie** [comment]
here is the head of my file names:
```
total 1556716
-rw-r--r-- 1 rohola rohola 144528 Nov 12 03:35 RY0001-0000.wav
-rw-r--r-- 1 rohola rohola 140954 Nov 12 03:35 RY0001-0001.wav
-rw-r--r-- 1 rohola rohola 247304 Nov 12 03:35 RY0001-0002.wav
-rw-r--r-- 1 rohola rohola 109064 Nov 12 03:35 RY0001-0003.wav
-rw-r--r-- 1 rohola rohola 204030 Nov 12 03:35 RY0001-0004.wav
-rw-r--r-- 1 rohola rohola 113498 Nov 12 03:35 RY0001-0005.wav
-rw-r--r-- 1 rohola rohola 317530 Nov 12 03:35 RY0001-0006.wav
-rw-r--r-- 1 rohola rohola 185284 Nov 12 03:35 RY0001-0007.wav
-rw-r--r-- 1 rohola rohola 173258 Nov 12 03:35 RY0001-0008.wav
-rw-r--r-- 1 rohola rohola 247318 Nov 12 03:35 RY0001-0009.wav
-rw-r--r-- 1 rohola rohola 172042 Nov 12 03:35 RY0001-0010.wav
-rw-r--r-- 1 rohola rohola 278856 Nov 12 03:35 RY0001-0011.wav
-rw-r--r-- 1 rohola rohola 190876 Nov 12 03:35 RY0001-0012.wav
-rw-r--r-- 1 rohola rohola 203156 Nov 12 03:35 RY0001-0013.wav
-rw-r--r-- 1 rohola rohola 234918 Nov 12 03:35 RY0001-0014.wav
-rw-r--r-- 1 rohola rohola 198874 Nov 12 03:35 RY0001-0015.wav
-rw-r--r-- 1 rohola rohola 181064 Nov 12 03:35 RY0001-0016.wav
-rw-r--r-- 1 rohola rohola 230292 Nov 12 03:35 RY0001-0017.wav
-rw-r--r-- 1 rohola rohola 194774 Nov 12 03:35 RY0001-0018.wav

```

I tried to make everything just like LJSpeech.

**Comment by kamo-naoyuki** [comment]
Hmm, I don't know why...

Could you rerun with changing this line to

https://github.com/espnet/espnet/blob/4b848aab49c8d0bc4a8be4dd94e791e47063eb78/egs2/ljspeech/tts1/local/data.sh#L59

```
    find ${db_root}/LJSpeech-1.1 -follow -name "*.wav" | LC_ALL=C sort | while read -r filename;do
```

Though, maybe, same problem happens.

**Comment by kamo-naoyuki** [comment]
And could you check which line is unsorted?

You can check this 

```
LC_ALL=C sort -k1 data/train/text > sorted.txt
diff data/train/text sorted.txt
```

**Comment by roholazandie** [comment]
this
```
LC_ALL=C sort data/train/utt2spk > sorted.txt
diff data/train/utt2spk sorted.txt
```
gives me nothing. I also tried it myself in python. it is really sorted! that's why I am confused!

**Comment by kamo-naoyuki** [comment]
Hmmmmmm. Just to make sure, could you validate your data/train again in the current state?

```
utils/validate_data_dir.sh data/train
```

**Comment by roholazandie** [comment]
it gives me this:
```
utils/validate_data_dir.sh: WARNING: you have only one speaker.  This probably a bad idea.
   Search for the word 'bold' in http://kaldi-asr.org/doc/data_prep.html
   for more information.
utils/validate_data_dir.sh: Successfully validated data-directory data/train

```

**Comment by kamo-naoyuki** [comment]
???
Did you remove fix_data_dir.sh to reproduce the problem?

**Comment by roholazandie** [comment]
Now the code is running. I will try it as soon as I am finished with the training.
