### ISSUE TITLE
visualize ctc values

### ISSUE THREAD

**Issue by desothier1** [espnet/espnet#2706]
Hi,
I worked with ESPnet version 0.3.1
Is there a way to easily see the CTC values per predicted character in my test output?
In this version 0.3.1, in order to achieve this, I tried to modify code in espnet/espnet/nets/pytorch_backend/decoders.py
but did not succeed.
So any help is welcome.

Thank a lot

Best regards

**Comment by sw005320** [comment]
The latest espnet1 has a CTC visualization function.
See https://github.com/espnet/espnet/pull/2221

**Comment by desothier1** [comment]
ok, thanks.
Last question,
what is exactly meant with 'encoder **index**'

**Comment by sw005320** [comment]
Could you clarify what you are mentioning?
This one?
https://github.com/espnet/espnet/blob/dab2092bc9c8e184c48cc6e603037333bd97dcd1/espnet/asr/asr_utils.py#L249
This is a subsampled time index in an encoder network, and it will be one of the axes to depict an attention map.

**Comment by desothier1** [comment]
Thx for your answer, it was indeed what i meant.
Am I correct that the maximum length of the attention encoder length is defined by the parameter adim (number of attention dimensions) in asr_train.py that is by default 320 (ESPnet version 0.3.1)?

FYI I used ESPnet for spoken language understanding, and am supposed to be able to explain my results, also related to attention.

Thanks a lot
