### ISSUE TITLE
(Minor) ctc_type argument in asr_train.py does nothing

### ISSUE THREAD

**Issue by ayhyap** [espnet/espnet#271]
Unless i'm mistaken, the ctc_type argument for asr_train.py does nothing.

I've followed the code through multiple times - the pytorch implementation always uses warpctc and the chainer implementation always uses chainer's built-in ctc.

Recommend removing the argument or actually allowing more options?

**Comment by sw005320** [comment]
> the pytorch implementation always uses warpctc 

yes

> and the chainer implementation always uses chainer's built-in ctc.

https://github.com/espnet/espnet/blob/master/src/nets/e2e_asr_attctc.py#L138-L145

chainer CTC can be switched. Default is warpctc

**Comment by ayhyap** [comment]
Yes, my bad. I forgot that the arguments are passed all the way to the model constructor so i skipped over checking that file.
