### ISSUE TITLE
Multi-speaker TTS with ESPnet mel-spectrograms

### ISSUE THREAD

**Issue by migi-gon** [espnet/espnet#2710]
Hello!

I have been following the system described in this paper by Y. Jia, et al [Link](https://arxiv.org/abs/1806.04558). So far, I am done training the synthesizer module using ESPnet-Tacotron 2 multi-speaker tts scripts provided here: [Link](https://github.com/espnet/espnet/tree/master/egs/libritts/tts1). I finished the training and resulted to intelligible speech, albeit robotic, using Griffin-Lim.

Now, in order to improve the synthesized outputs, I decided to train a wavenet vocoder using the synthesized mel-spectrograms (produced mel-specs of the train set) as described in the paper. I trained the model for 1000k steps and checked the output which resulted to garbled speech. I then extended the training (without changing the hparams) to 1600k steps but still no improvements. Sample synthesized audio files (and the hparams file) can be found here: [Link](https://drive.google.com/drive/folders/1XDcWc3FmOWqFMY4qDDhiDdlsE-yYP3Yo).

Any help or insights on how I could continue would be very much appreciated. Thanks!

**Comment by kan-bayashi** [comment]
How did you generate the sample?
Generate mel-spectrogram with teacher forcing -> WaveNet?

**Comment by migi-gon** [comment]
I actually just followed the recipe in `egs/libritts/tts1` for the multi-speaker setup. I did not change any parameters in the configuration files.

**Comment by kan-bayashi** [comment]
Again, how did you generate the sample?
How did you prepare the mel-spectrogram for the vocoder training?
e.g. Use teacher forcing or free running or use natural mel-spectrogram

**Comment by migi-gon** [comment]
Hello, sorry for the delay.

For the mel-spectrograms, I generated synthesized mel-specs of the train-set using the trained decoder model (recipe in `egs/libritts/tts1`). After generating these, I preprocessed the mel-specs with the same codes for preprocessing in r9y9's wavenet vocoder scripts (i.e. frame length matching with the audio wav files). I followed the recipe in `wavenet_vocoder/egs/mol`.

When I checked, there are no options for `teacher-forcing` in both espnet and wavenet scripts and since I used the decoded mel-specs, I didn't have to use the natural mel-spectrogram of the audio files.

**Comment by kan-bayashi** [comment]
> I generated synthesized mel-specs of the train-set using the trained decoder model

If you use the generated mel-spectrogram for the training of WaveNet, there is a mismatch between mel-spectrogram and waveform since the generated mel-spectrogram has a different temporal structure from the mel-spectrogram extracted from the waveform. 
Therefore, your training is failed.
If you want to train WaveNet, you need to use natural mel-spectrogram + waveform or generated mel-spectrogram with teacher forcing + waveform.

**Comment by migi-gon** [comment]
I understand the error now, thank you for the insights.
