### ISSUE TITLE
ctc forced_align got repeated labels and is too slow

### ISSUE THREAD

**Issue by Cescfangs** [espnet/espnet#2711]
ground truth token list
```
66,16,14,32,177,26,39,17,32,86,14,32,36,100,2,88,50,123,369,139,48
```
ctc forced_align result
```
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,66,0,0,0,0,0,0,16,0,0,0,0,0,0,0,0,0,14,0,32,32,177,177,26,39,39,17,17,17,17,32,32,86,86,14,14,32,32,32,36,36,36,0,0,0,0,0,100,0,0,0,0,2,0,0,0,0,88,0,0,0,50,0,0,0,0,123,0,0,0,0,0,0,369,0,0,0,0,0,0,139,0,0,0,0,0,0,48,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
```
I also tried [CTC viterbi aligner](https://github.com/ydhira/ctc_viterbi_aligner/blob/ded3f951bf211ae8f03ab9e1bc5f85ab289759da/viterbi_align.py), the result is correct:
```
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,66,0,0,0,0,0,0,16,0,0,0,0,0,0,0,0,0,14,0,32,0,177,0,26,39,0,17,0,0,0,32,0,86,0,14,0,32,0,0,36,0,0,0,0,0,0,0,100,0,0,0,0,2,0,0,0,0,88,0,0,0,50,0,0,0,0,123,0,0,0,0,0,0,369,0,0,0,0,0,0,139,0,0,0,0,0,0,48,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
```
And the `forced_align()` is too slow compared with `viterbi_align()`, I've tested a 20,000,000 utt dataset, the `forced_align()` took one week to finish, and `viterbi_align()` only cost 6 hours

**Comment by lumaku** [comment]
The `forced_align()` function in [`ctc.py`](https://github.com/espnet/espnet/blob/master/espnet/nets/pytorch_backend/ctc.py#L153) was part of an older version of the alignment tool in ESPnet, so I'm not sure whether this function is still maintained or actively used. Also, to evaluate run time of the algorithms, I think that more information of the used dataset is necessary (length of audio files, etc).

If your aim is to align utterance starts and endings, you might want to take a look at [`asr_align.py`](https://github.com/espnet/espnet/blob/master/espnet/bin/asr_align.py) that uses CTC segmentation (code in this [repository](https://github.com/lumaku/ctc-segmentation)). The variable `state_list` in `asr_align.py` corresponds to the per-timestep alignments.
