### ISSUE TITLE
Why spk_embed_dim in VCTK (multispeaker is null)

### ISSUE THREAD

**Issue by alxmamaev** [espnet/espnet#2716]
I found that spk_embed_dim is null in VCTK egg2, it is a multispeaker model, why is that?

https://github.com/espnet/espnet/blob/1e443b12e2fd95c2adf9c5e1e0a84de02e2ebaaf/egs2/vctk/tts1/conf/tuning/train_gst_tacotron2.yaml#L39

**Comment by kan-bayashi** [comment]
This is because in ESPnet2, we use GST instead of pre-trained speaker embedding.
