### ISSUE TITLE
espnet/transform/perturb.py NoiseInjection BUG!!!

### ISSUE THREAD

**Issue by BYRTIMO** [espnet/espnet#2722]
**Describe the bug**
line 273 compute scale
Should write like that "scale = numpy.sqrt((x ** 2).mean()) / ratio"

**Comment by kamo-naoyuki** [comment]
The comment is wrong. Maybe, I intended singal-to-noise ratio.


https://github.com/espnet/espnet/blob/1f106b9f63d5b282ee848668c066a5b8bc3b16f1/espnet/transform/perturb.py#L265

This function has not been used in espnet recipe and not maintenanced now. Please ignore.
