### ISSUE TITLE
AMI Recipe for espnet2 config question

### ISSUE THREAD

**Issue by picheny-nyu** [espnet/espnet#2728]
I see that for the espnet2 recipe for ami run.sh points to conf/decode_asr.yaml, but there is only a conf/decode.yaml. Is that the correct yaml file for the recipe or do I need to copy it from somewhere? 

Thanks
Michael

**Comment by sw005320** [comment]
Yes, `conf/decode.yaml` (but it's a symlink pointing https://github.com/espnet/espnet/blob/master/egs2/ami/asr1/conf/tuning/decode_transformer.yaml).
We'll fix it soon.
Thanks, @picheny-nyu!
We also welcome any feedback from you ;)
