### ISSUE TITLE
librispeech asr1 recipe emits error at stage 2

### ISSUE THREAD

**Issue by jaesong** [espnet/espnet#2730]
```
$ cd <espnet>/egs/librispeech/asr1
$ bash ./run.sh --dumpdir ... --datadir ... --stop-stage 1
...
$ bash ./run.sh --dumpdir ... --datadir ... --stop-stage 2 --stage 2
dictionary: data/lang_char/train_960_unigram5000_units.txt
stage 2: Dictionary and Json Data Preparation
cut: data/train_960/text: No such file or directory
```

Stage 1 produces `train_960_org`, `train_sp_org` (with speed perturbation) and `train_sp` (via `remove_longshortdata.sh`), but it does not produce `train_960`.
However, stage 2 tries to read `data/${train_set}/text` whereas `train_set=train_960`.

I guess it is related to recent changes regarding speed perturbation (https://github.com/espnet/espnet/pull/2617).

**Comment by sw005320** [comment]
Thanks, @jaesong!
Year, I think you're right. This is a bug.
@yuekaizhang, could you fix it?
We can just use `data/${train_set}_org/text` (before pruning too long/short utterances) at stage 2.
The same thing happens in stage 3.

If your pre-trained model is based on the text data after pruning too long/short utterances, it might be better to prepare `data/${train_set}/text` to avoid the mismatch.

**Comment by yuekaizhang** [comment]
Sure, I would fix it. Thank you jaeson. Sorry, I didn't care too much about LM training since I used previous LM.
