### ISSUE TITLE
[Bug] fisher_callhome st1 recipe failed on stage 1

### ISSUE THREAD

**Issue by jamfly** [espnet/espnet#2734]
**Describe the bug**

cannot read input while executing ```make_fbank_pitch```

I get the error message run.pl: 2 / 32 failed, log is in exp/make_fbank/fisher_dev/make_fbank_pitch_fisher_dev.*.log

**Basic environments:**
 - OS information: Ubuntu 18.04.1 LT
 - python version: 3.6.3
 - espnet version: 0.9.6
 - Git hash: f0ff3c07ef066e09a28045c70cd0c4203de00a79
 - pytorch version: 1.4.0
 
**Task information:**
 - Task: ST
 - Recipe: fisher_callhome/st1
 - ESPnet1

**To Reproduce**
1. move to a recipe directory: `cd egs/fisher_callhome/st1`
2. execute `run.sh` with specific arguments `bash run --stage 1 --stop-stage 1`
3. specify the error log, `run.pl: 2 / 32 failed, log is in exp/make_fbank/fisher_dev/make_fbank_pitch_fisher_dev.*.log`

**Error logs**
I attach error log in here [make_fbank_pitch_fisher_dev.1.log](https://github.com/espnet/espnet/files/5621399/make_fbank_pitch_fisher_dev.1.log)

**Comment by kamo-naoyuki** [comment]
> my_root_name/CORPUS/LDC2010S01/data/speech/20051009_182032_217_fsp.sph

You don't have it? This is your problem.

**Comment by jamfly** [comment]
Hi @kamo-naoyuki:

I have both speech and transcription, I've checked the path and they are corrected

**Comment by kamo-naoyuki** [comment]
At least, the following command is failed by some reason. 

```
sph2pipe -f wav -p -c 1 my_root_name/CORPUS/LDC2010S01/data/speech/20051009_182032_217_fsp.sph | sox -R -t wav - -t wav - rate 16000 dither
```

**Comment by jamfly** [comment]
is there any issue with sph2pipe? since I can run this recipe two or three moths before

**Comment by kan-bayashi** [comment]
First, we should run the command in your terminal and check whether the problem is reproduced or not:
`sph2pipe -f wav -p -c 1 my_root_name/CORPUS/LDC2010S01/data/speech/20051009_182032_217_fsp.sph | sox -R -t wav - -t wav - rate 16000 dither`

**Comment by jamfly** [comment]
I did it, and get the following message
```
Unable to open my_root_name/CORPUS/LDC2010S01/data/speech/20051009_182032_217_fsp.sph as input
sox FAIL formats: can't open input  `-': WAVE: RIFF header not found
sox FAIL formats: can't open input  `-': WAVE: RIFF header not found
```

**Comment by kan-bayashi** [comment]
Then, obviously `my_root_name/CORPUS/LDC2010S01/data/speech/20051009_182032_217_fsp.sph` has a problem. It's not a problem of the recipe.
