### ISSUE TITLE
VOICE CONVERSION TRAINING ISSUE

### ISSUE THREAD

**Issue by tulasiram58827** [espnet/espnet#2737]
**Describe the bug**
I just followed the instructions given [here](https://github.com/espnet/espnet/tree/master/egs/arctic/vc1) in the Voice Conversion tutorial then I got this error.
>  File "/home/ram/Speech_projects/espnet/egs/arctic/vc1/../../../espnet/bin/vc_train.py", line 364, in <module>
    main(sys.argv[1:])
  File "/home/ram/Speech_projects/espnet/egs/arctic/vc1/../../../espnet/bin/vc_train.py", line 358, in main
    train(args)
  File "/home/ram/Speech_projects/espnet/espnet/vc/pytorch_backend/vc.py", line 309, in train
    model = load_trained_modules(idim, odim, args, TTSInterface)
  File "/home/ram/Speech_projects/espnet/espnet/asr/pytorch_backend/asr_init.py", line 264, in load_trained_modules
    model_state_dict, is_lm = get_trained_model_state_dict(model_path)
  File "/home/ram/Speech_projects/espnet/espnet/asr/pytorch_backend/asr_init.py", line 214, in get_trained_model_state_dict
    model_class = dynamic_import(model_module)
  File "/home/ram/Speech_projects/espnet/espnet/utils/dynamic_import.py", line 22, in dynamic_import
    m = importlib.import_module(module_name)
  File "/home/ram/anaconda3/envs/espnet/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'espnet.nets.pytorch_backend.vc_transformer'

To reproduce just follow the steps [here](https://github.com/espnet/espnet/tree/master/egs/arctic/vc1)

@unilight @kan-bayashi

**Comment by unilight** [comment]
@tulasiram58827 Hi, thank you for reporting the issue. This is because I accidentally uploaded an older version of the pretrained model. I have uploaded the latest one. Could you execute stage -1 and try to download again? Note that you might need to delete the `.complete` file so the script will download it again for you.

**Comment by tulasiram58827** [comment]
Thanks @unilight after re-downloading the checkpoint the metioned issue is solved. 

I am having one more issue. Sorry for asking lame question. I am getting CUDA out of memory error while I was training and FYI my GPU RAM is 6GB. To decrease the batch size I can't see any parameter named batch size in the [configuration file](https://github.com/espnet/espnet/blob/master/egs/arctic/vc1/conf/train_pytorch_transformer.tts_pt.single.yaml) provided in the vc folder

**Comment by unilight** [comment]
You can start by halving this number: https://github.com/espnet/espnet/blob/4f0f4c30385e85453d05a98fb765d828ddc1d256/egs/arctic/vc1/conf/tuning/train_pytorch_transformer.tts_pt.v1.1.single.yaml#L35

**Comment by tulasiram58827** [comment]
Thank you so much @unilight for the quicker response.

**Comment by tulasiram58827** [comment]
@unilight  Just a question What are the recommended epochs to train. I can see you added 1000 as an example in the inference code. Do you recommend 1000 epochs? Or What is the recommended loss till the model should be trained?

It would be really helpful if you can add these pointers.

**Comment by unilight** [comment]
The number of epochs in the configs are my recommended amounts. You can of course train for a large amount of epochs, and then save every N steps and decode to choose based on the validation MCD, CER and WER, but basically the numbers I set were the empirically minimum amount to get the numbers in the paper.

**Comment by tulasiram58827** [comment]
Hi @unilight  Thanks for the detailed information.

I successfully trained the VC model and the wave-forms are generated successfully. But at the evaluation stage "Stage 6" I am getting this error.
> stage 6: Objective Evaluation
local/ob_eval/evaluate.sh --nj 16 --db_root downloads --vocoder PWG exp/clb_slt_pytorch_vtn_tts_pt/outputs_snapshot.ep.1000_decode clb_slt_dev
MCD calculation
step 0: Model preparation
local/ob_eval/evaluate.sh: line 85: download_from_google_drive_2.sh: command not found

I believe some file is missing in the repository.

Also I didn't seen any inference code to give any custom input text and generate the audio waveform with the target speaker voice. If it takes time to add the inference code for you to add guide me so that I will try myself and let you know the update.

**Comment by unilight** [comment]
> local/ob_eval/evaluate.sh: line 85: download_from_google_drive_2.sh: command not found

Sorry, this is my mistake again... Please change to `download_from_google_drive.sh`. 

> Also I didn't seen any inference code to give any custom input text and generate the audio waveform with the target speaker voice.

Please note that this is a voice conversion recipe so we input speech rather than text. I think what you are describing is TTS.

**Comment by tulasiram58827** [comment]
Sorry that's my mistake I was intended asking how to input my speech. So is it possible to add my audio as input and get output audio as target speaker voice(with which I am trained with).

**Comment by tulasiram58827** [comment]
@unilight  Any comment?

**Comment by unilight** [comment]
Sorry for this late reply.

> So is it possible to add my audio as input and get output audio as target speaker voice(with which I am trained with).

Note that the arctic/vc1 recipe is for one-to-one VC, i.e. the model can only map from a specific source to a specific target. Thus the performance might not be optimal if using your voice as input, which is unseen to the model. On the other hand, you can take a look at the vcc20 recipe. https://github.com/espnet/espnet/tree/master/egs/vcc20 This recipe supports any-to-one VC, where conversion from unseen source is possible.

**Comment by tulasiram58827** [comment]
@unilight  But for the recipe you mentioned I cannot see any link to download dataset from the official website http://www.vc-challenge.org/ 
It would be great if you can help for downloading the dataset.

**Comment by tulasiram58827** [comment]
> Note that the arctic/vc1 recipe is for one-to-one VC, i.e. the model can only map from a specific source to a specific target. Thus the performance might not be optimal if using your voice as input, which is unseen to the model. On the other hand, you can take a look at the vcc20 recipe. https://github.com/espnet/espnet/tree/master/egs/vcc20 This recipe supports any-to-one VC, where conversion from unseen source is possible.

Also, this works for me. But I just want to know is there any provision to give one audio file as input and check the resulted output audio file. If there is no provision like that just help me with some pointers so that I will also add PR of the separated file which may help for other users also for doing inference.

**Comment by unilight** [comment]
Currently, we don't have such a demo script for inputting one arbitrary sentence and convert to a specific speaker yet. If you can create a demo script like the ESPnet-TTS Colab demos, I believe it will be very useful for other users! 👍

**Comment by tulasiram58827** [comment]
> Currently, we don't have such a demo script for inputting one arbitrary sentence and convert to a specific speaker yet. If you can create a demo script like the ESPnet-TTS Colab demos, I believe it will be very useful for other users! 👍

Yes but can you help me for getting the flow. Like Conversion flow and files to use in high level.

**Comment by unilight** [comment]
I suggest you to look deeper into the recipes and the colab demo. Most of them are pretty well-documented. It’s hard to tell what level of guideline you still need if you dont try first. Of course you are still welcomed to post questions you encounter. It will be easier for us to help you, too.

**Comment by tulasiram58827** [comment]
Ok I will let you know if I stuck somewhere

**Comment by tulasiram58827** [comment]
@unilight I created [Colab Notebook](https://colab.research.google.com/gist/tulasiram58827/f59a7c122d50c457db9601719cbf8a80/voice_coversion_transformer.ipynb) which is self-contained. It will download all the trained models and model configuration files required and will do inference.

Output is generated. The pitch of the output generated is high but the quality of the output seems good. Can you check the [Notebook](https://colab.research.google.com/gist/tulasiram58827/f59a7c122d50c457db9601719cbf8a80/voice_coversion_transformer.ipynb) once why it is generating high pitch audio.

FYI: For now I am using ready made ark file as input. I am in the process of writing code to generate ark file from wav file.

Please share if you have any other comments.

**Comment by unilight** [comment]
Hi @tulasiram58827 

This looks very cooool! 🚀 I appreciate your good work!

> The pitch of the output generated is high but the quality of the output seems good. Can you check the Notebook once why it is generating high pitch audio.

I think it is because of the vocoder mismatch. You are converting from clb to slt but you are using a vocoder trained on ljspeech. Could you change the vocoder to the one I provided in the recipe, which was pretrained on slt? https://github.com/espnet/espnet/blob/master/egs/arctic/vc1/local/pretrained_model_download.sh#L23

> I am in the process of writing code to generate ark file from wav file.

Yes please do this. I think this is really good work. After you refactor and polish this notebook, please send a PR.
@sw005320 @kan-bayashi , do you have some comments?

**Comment by tulasiram58827** [comment]
@unilight Thanks for appreciation.

> I am in the process of writing code to generate ark file from wav file.

Can you help me here. I already spend a lot of time figuring out. It would be helpful if you can help me here.

**Comment by unilight** [comment]
@tulasiram58827 I think this code snippet can help you. https://github.com/espnet/espnet/blob/master/utils/recog_wav.sh#L196-L216

In high level,
1. Make necessary files including `wav.scp`, `spk2utt`, `utt2spk`, `text` first. (Maybe not all of them are needed or well-generated. Some of them can be dummy files.)
2. Use `make_fbank.sh` rather than `steps/make_fbank_pitch.sh` to extract fbanks. 
3. Use `dump.sh` to normalize.

Then you should be able to get the ark file you want.

**Comment by tulasiram58827** [comment]
Thanks @unilight  

Will open PR soon after refactoring.

**Comment by tulasiram58827** [comment]
Hi @unilight 

Sorry for the delay. I am working from past 3 days regarding this. I can successfully able to compute fbank features from audio file and it is added in this [Colab Notebook](https://colab.research.google.com/gist/tulasiram58827/ccb57181fd8a7488dca4bd227dec2cc9/voice_coversion_transformer.ipynb). But I cannot compute `cmvn` features from it. I am able to compute cmvn features in the local laptop with this command
> /home/ram/Speech_projects/espnet/egs/arctic/vc1/../../../utils/dump.sh --cmd run.pl --nj 1 --do_delta false /home/ram/Downloads/raw_fbank_clb.1.scp data/clb_train/cmvn.ark /home/ram/Downloads/ /home/ram/Downloads/

But I am not able to do the same in colab due to kaldli path issues. I need your help in normalization of fbank features.

**Comment by unilight** [comment]
Hmm. Maybe you can try this script? https://github.com/espnet/espnet/blob/master/utils/apply-cmvn.py
I personally have never tried before but it should work...

**Comment by tulasiram58827** [comment]
Thanks @unilight .

With your help I successfully completed code to do voice conversion from audio wave file to generate converted audio file. All the code is available in this [Notebook](https://colab.research.google.com/gist/tulasiram58827/f9a22ba32569a476bfeb107fb1c872b4/voice_coversion_transformer.ipynb). But the output is not expected. I request you to examine the flow and let me know if I missed or did anything wrong.

**Comment by unilight** [comment]
I suggest you check the steps one by one and check some intermediate results. For example, you can check the attention plots, change the vocoder from PWG to GL, or visualize the spectrogram.

**Comment by tulasiram58827** [comment]
I was checking step by step and comparing outputs. I found out `fbank` features are matching but `cmvn` features are not matching (around 99.8% elements mismatched). I am using the file you suggested to compute `cmvn` features.
https://github.com/espnet/espnet/blob/master/utils/apply-cmvn.py

**Comment by fabien-benoit-1984** [comment]
@tulasiram58827, @unilight There's some runtime error with [notebook](https://colab.research.google.com/gist/tulasiram58827/f9a22ba32569a476bfeb107fb1c872b4/voice_coversion_transformer.ipynb), [gist](https://gist.github.com//tulasiram58827/f9a22ba32569a476bfeb107fb1c872b4)
Screenshots:
1. [101](https://user-images.githubusercontent.com/74528656/109262640-f334cb80-7812-11eb-9e08-94977f876120.png)
`FileNotFoundError: [Errno 2] No such file or directory: 'cmvn.ark'`
Any ideas?

**Comment by unilight** [comment]
Hi @fabien-benoit-1984 , I did not run the notebook, but as the error log reads, the cmvn file is missing. Can you check if it is correctly placed?

**Comment by fabien-benoit-1984** [comment]
I'm not sure. I'm reading at the moment https://github.com/espnet/espnet/tree/master/egs/vcc20/vc1_task1. Need to figure out what way it works. I thought @tulasiram58827 has managed to feed a custom .wav file. I assume that `cmvn.ark` is an intermediate file. I might be wrong. I'm getting familiar with espnet, kaldi and `vcc20`. It will take 1-2 weeks for me.

**Comment by fabien-benoit-1984** [comment]
@unilight 
Screenshots:
1. [1](https://user-images.githubusercontent.com/74528656/109606452-c268d500-7b37-11eb-98eb-1d36907af6d5.png)
have got stuck with `sed: can't read downloads/tts1_TEF1/spk_xvector.scp: No such file or directory` (took 8 minutes before getting this error, will continue tomorrow)
```
2. Conversion

Execute the main script to convert SEF1 to TEF1:

$ ./run.sh --stage 11 \
  --srcspk SEF1 --trgspk TEF1 \
  --tts_model_dir <expdir> \
  --pretrained_model_name tts1
```

**Comment by fabien-benoit-1984** [comment]
@unilight 
Screenshots:
1. [image.png](https://user-images.githubusercontent.com/74528656/109760993-be54ba00-7c00-11eb-9f05-9fc8d617dde6.png)
I'm catching an error at stage 12. `local/update_json.sh: line 30: copy-vector: command not found`, `2021-03-03 06:12:12,998 (splitjson:52) INFO: number of utterances = 0 2021-03-03 06:12:12,998 (splitjson:54) ERROR: #utterances < #splits. Use smaller split number.` Will figure out why stage 12 fails tomorrow.

**Comment by fabien-benoit-1984** [comment]
@vinson-zhang nah, perhaps i've given up back then.
[image](https://user-images.githubusercontent.com/74528656/175007669-8ceedbbc-c930-4889-86a8-ce58794645a6.png)

**Comment by vinson-zhang** [comment]
@fabien-benoit-1984 
Recompiling Kaldi will solve this problem
