### ISSUE TITLE
Dockerfile git clone kaldi errors

### ISSUE THREAD

**Issue by xiaosujie** [espnet/espnet#2738]
I run the command  ./build.sh fully_local 10.1, then prebuilt/runtime/Dockerfile, in this container, I can not git clone kaldi from github, errors as follows:
Cloning into 'kaldi'...
error: RPC failed; curl 56 GnuTLS recv error (-54): Error in the pull function.
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed

How can I solve this problem?

**Comment by kamo-naoyuki** [comment]
@Fhrozen 
Now kaldi repo is too large.
It's better to write either one of the followings in Dockerfile


```sh
git clone --depth 1 https://github.com/kaldi-asr/kaldi
```

```sh
git config --global http.postBuffer 2M
```

**Comment by Fhrozen** [comment]
@kamo-naoyuki Got it, thank you for the notification.
The problem should be on fully_local that builds with the recent kaldi.
@xiaosujie If is possible you could use local instead of fully_local while I am checking on this error.

**Comment by kamo-naoyuki** [comment]
> The problem should be on fully_local that builds with the recent kaldi.

I agree, thanks, I prefer this direction.

**Comment by xiaosujie** [comment]
> @kamo-naoyuki Got it, thank you for the notification.
> The problem should be on fully_local that builds with the recent kaldi.
> @xiaosujie If is possible you could use local instead of fully_local while I am checking on this error.

Now prebuilt/runtime/Dockerfile run successful, but the prebuilt/devel/gpu/10.1/cudnn7/Dockerfile failed, the errors as follows:
Get:1 http://archive.ubuntu.com/ubuntu bionic-updates/universe amd64 gnupg2 all 2.2.4-1ubuntu1.3 [5324 B]
debconf: unable to initialize frontend: Dialog
debconf: (TERM is not set, so the dialog frontend is not usable.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (This frontend requires a controlling tty.)
debconf: falling back to frontend: Teletype
dpkg-preconfigure: unable to re-open stdin: 
Fetched 5324 B in 0s (14.8 kB/s)
Selecting previously unselected package gnupg2.
(Reading database ... 20506 files and directories currently installed.)
Preparing to unpack .../gnupg2_2.2.4-1ubuntu1.3_all.deb ...
Unpacking gnupg2 (2.2.4-1ubuntu1.3) ...
Setting up gnupg2 (2.2.4-1ubuntu1.3) ...
Warning: apt-key output should not be parsed (stdout is not a terminal)
curl: (56) Unexpected EOF
gpg: no valid OpenPGP data found.
The command '/bin/sh -c apt-get update && apt-get install -y --no-install-recommends gnupg2 curl ca-certificates &&     curl -fsSL https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/7fa2af80.pub | apt-key add - &&     echo "deb https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64 /" > /etc/apt/sources.list.d/cuda.list &&     echo "deb https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64 /" > /etc/apt/sources.list.d/nvidia-ml.list &&     apt-get purge --autoremove -y curl &&     rm -rf /var/lib/apt/lists/*' returned a non-zero code: 2

can you help me? Thank you.

**Comment by Fhrozen** [comment]
> Warning: apt-key output should not be parsed (stdout is not a terminal)
> curl: (56) Unexpected EOF
> gpg: no valid OpenPGP data found.

Can you try to clean up all the docker images with` docker rmi $(docker image -aq)`. 
I am building the containers now, and did not have that error.
