### ISSUE TITLE
Error while installing warp-rnnt

### ISSUE THREAD

**Issue by RuslanSel** [espnet/espnet#2751]
Hi,

I got the error:

Obtaining file:///home/ubuntu/tts/espnet/tools/warp-rnnt/pytorch_binding
    ERROR: Command errored out with exit status 1:
     command: /home/ubuntu/tts/espnet/tools/venv/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/ubuntu/tts/espnet/tools/warp-rnnt/pytorch_binding/setup.py'"'"'; __file__='"'"'/home/ubuntu/tts/espnet/tools/warp-rnnt/pytorch_binding/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-_s7wjfxn
         cwd: /home/ubuntu/tts/espnet/tools/warp-rnnt/pytorch_binding/
    Complete output (6 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/ubuntu/tts/espnet/tools/warp-rnnt/pytorch_binding/setup.py", line 22, in <module>
        raise Exception("CPU version is not implemented")
    Exception: CPU version is not implemented
    No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

Thanks in advance.

**Comment by b-flo** [comment]
Hi,

`warp-rnnt` doesn't have a CPU version however it shouldn't attempt to install it if no GPUs are found. That's weird. I'll take a look.

Could you edit your main post and follow the `installation issue template` please provided when creating an issue?

**Comment by RuslanSel** [comment]
I switched to GPU instance and the error disappeared.
Thanks. :-)

**Comment by v-yunbin** [comment]
@RuslanSel how to switched to GPU instance？

**Comment by RuslanSel** [comment]
It's AWS instance.

**Comment by v-yunbin** [comment]
@RuslanSel I do not see it .  I met same error .

**Comment by RuslanSel** [comment]
I switched to GPU instance in Amazon Web Services (AWS).

**Comment by b-flo** [comment]
@RuslanSel Could you update your original post with the template issue provided when opening a new issue please? Or @v-yunbin can open a new one if you don't have the logs anymore.

As I said, `warp-rnnt` is optional, `warp-transducer` being the main one, and ESPnet shouldn't attempt to install it if no GPU are found. I would like to investigate when I have time for that, maybe something was modified I'm not aware of.

**Comment by RuslanSel** [comment]
@b-flo Yes. I don't have the logs anymore.

**Comment by v-yunbin** [comment]
@b-flo I met the error because i have not activate my conda env.  after activating my env,  it worked normally.

**Comment by karthik19967829** [comment]
@RuslanSel I am facing issues with installation on AWS instance , could you tell me what AWS AMI and instance you uses to install ?

**Comment by b-flo** [comment]
@karthik19967829 What error are you encountering? The post is about `warp-rnnt` we removed one year ago

**Comment by karthik19967829** [comment]
oh okay my bad ,I was facing some issue warp-transducer. Default installation script fails when it cannot find the CUDA path . But by following the instruction warp-transducer to cmake with cuda path param works .
Anyways I will try to add some error message or doc there to help others .
Thanks

**Comment by b-flo** [comment]
Hum, could you open a new issue please? Depending on the error, we may directly update `warp-transducer` or change install scripts.
