### ISSUE TITLE
freeze-mod missed in espnet2

### ISSUE THREAD

**Issue by silnos** [espnet/espnet#2752]
--init-mod is implemented as --init_params in espnet2 as in ##2667,

--freeze-mod is not implemented in espnet2 yet.

Is there any near plan to implement it?

**Comment by kamo-naoyuki** [comment]
okay

**Comment by silnos** [comment]
Great, thanks.

Possible, adding the fifth item in --init-param, and
dealing in load_pretrained_model as following would work
'''
    if freeze is not None:
        import logging
        for mod, param in model.named_parameters():
            if any(mod.startswith(m) for m in excludes.split(",")):
                logging.info(f"freezing {mod}, it will not be updated.")
                param.requires_grad = False
'''

**Comment by b-flo** [comment]
Hi,

Depending on the pytorch version, an additional filtering should be applied when passing weights to optimizer. C/c'ing note from a previous PR:

> ...
> Also we should add something like:
>
> `model_params = filter(lambda x: x.requires_grad, model.parameters())`
>
> and pass it to optimizer to avoid update when weights value are 0 in some pytorch version.

I don't remember which pytorch versions are impacted though...
