### ISSUE TITLE
Can espnet build on Redhat 7?

### ISSUE THREAD

**Issue by okkteam** [espnet/espnet#2753]
It is written that espnet supports centos 7, but I only have a computer with a redhat 7 linux system. 
May I ask if espnet could built on redhat 7?

**Comment by sw005320** [comment]
centos 7 is a free version of redhat 7, and I think it would work with redhat 7

**Comment by okkteam** [comment]
> centos 7 is a free version of redhat 7, and I think it would work with redhat 7

Thanks for your awsome work and reply!
