### ISSUE TITLE
Installation problem of warp-ctc.sh

### ISSUE THREAD

**Issue by mahbubnoor** [espnet/espnet#2759]
_I am having a problem during installation of warpctc-pytorch from the installers directory and same problem i face if i do like this --> $pip install warpctc-pytorch
and my error message is showing like this in the following:_

> 

 /Data/user_mhb/ESPnet/espnet/tools/installers$ ./install_warp-ctc.sh
  cuda_version=101
  Collecting warpctc-pytorch==0.2.1+torch14.cuda101
    Downloading warpctc_pytorch-0.2.1%2Btorch14.cuda101-cp36-cp36m-manylinux1_x86_64.whl (3.1 MB)
       |████████████████████████████████| 3.1 MB 4.5 MB/s
  ERROR: Requested warpctc-pytorch==0.2.1+torch14.cuda101 from https://files.pythonhosted.org/packages/af/23/207ee1c4c3f841c75                  d32d1f9422a8b5fec90dda5afb6b6d57a7d35e674d9/warpctc_pytorch-0.2.1%2Btorch14.cuda101-cp36-cp36m-manylinux1_x86_64.whl#sha256=                  9751923b9b2b80bf734f439c8a88848d8ff51fde04e62b3befe8a0ff575df951 has different version in metadata: '0.2.1'
>

_So, can anybody please tell me how to solve this problem, If i change a line in asr_train.py file in line number 140 like this --> default="builtin",  instead of default="warpctc",,  then asr recipes are running smoothly but problem is i am getting little bit lower CER score. ANd if i use default="warpctc"  then recipes are not running , showing error during Network Training stage, it shows NoModuleFInd error for warpctc-pytorch. That is why i wanted to install warpctc-pytroch.  However, previously last few months i was using earlier versions of espnet. Today i was going to install new espnet and deleted all of my earlier python environments. My current python version is 3.6.12, pip version is 20.3.1

**Comment by kan-bayashi** [comment]
See https://github.com/espnet/espnet/issues/2743

**Comment by kan-bayashi** [comment]
Keep open until we fix the PEP440 issue.

**Comment by mahbubnoor** [comment]
> Keep open until we fix the PEP440 issue.

Thank you very much for your quick reply, But i changed earlier already and did  downgrade my pip 20.3.1 to 20.2.4 then warpctc-pytorch install successfully but during running recipes i get different problems . Here in the following i gave the error messages i train.log file:_

> # asr_train.py --config conf/train.yaml --ngpu 1 --backend pytorch --outdir exp/train_nodev_pytorch_train/results --tensorboard-dir tensorboard/train_nodev_pytorch_train --debugmode 1 --dict data/lang_1char/train_nodev_units.txt --debugdir exp/train_nodev_pytorch_train --minibatches 0 --verbose 1 --resume --train-json dump/train_nodev/deltafalse/data.json --valid-json dump/train_dev/deltafalse/data.json 
> # Started at Tue Dec  8 14:29:12 CST 2020
> #
> 2020-12-08 14:29:14,744 (asr_train:589) INFO: ngpu: 1
> 2020-12-08 14:29:14,744 (asr_train:592) INFO: python path = (None)
> 2020-12-08 14:29:14,744 (asr_train:595) INFO: random seed = 1
> 2020-12-08 14:29:14,744 (asr_train:614) INFO: backend = pytorch
> 2020-12-08 14:29:14,807 (deterministic_utils:26) INFO: torch type check is disabled
> 2020-12-08 14:29:14,876 (asr:413) INFO: stream1: input dims : 83
> 2020-12-08 14:29:14,876 (asr:414) INFO: #output dims: 9
> 2020-12-08 14:29:14,876 (asr:434) INFO: Multitask learning mode
> 2020-12-08 14:29:14,877 (nets_utils:426) INFO: subsample: 1 2 2 1
> 2020-12-08 14:29:14,885 (encoders:298) INFO: BLSTM with every-layer projection for encoder
> Traceback (most recent call last):
>   File "/Data/user_mhb/ESPnet/espnet/egs/yesno/asr3/../../../espnet/bin/asr_train.py", line 638, in <module>
>     main(sys.argv[1:])
>   File "/Data/user_mhb/ESPnet/espnet/egs/yesno/asr3/../../../espnet/bin/asr_train.py", line 624, in main
>     train(args)
>   File "/Data/user_mhb/ESPnet/espnet/espnet/asr/pytorch_backend/asr.py", line 441, in train
>     idim_list[0] if args.num_encs == 1 else idim_list, odim, args
>   File "/Data/user_mhb/ESPnet/espnet/espnet/nets/pytorch_backend/e2e_asr.py", line 151, in __init__
>     self.ctc = ctc_for(args, odim)
>   File "/Data/user_mhb/ESPnet/espnet/espnet/nets/pytorch_backend/ctc.py", line 231, in ctc_for
>     odim, args.eprojs, args.dropout_rate, ctc_type=args.ctc_type, reduce=reduce
>   File "/Data/user_mhb/ESPnet/espnet/espnet/nets/pytorch_backend/ctc.py", line 41, in __init__
>     import warpctc_pytorch as warp_ctc
>   File "/home/mhb/.conda/envs/py3.6/lib/python3.6/site-packages/warpctc_pytorch/__init__.py", line 6, in <module>
>     from ._warp_ctc import *  # noqa
> ImportError: libtorch_cpu.so: cannot open shared object file: No such file or directory
> # Accounting: time=3 threads=1
> # Ended (code 1) at Tue Dec  8 14:29:15 CST 2020, elapsed time 3 seconds

**Comment by kan-bayashi** [comment]
Please use the issue template.

**Comment by mahbubnoor** [comment]
Yes, now i followed the way it was written in that issue, but this time i am getting different error

**Comment by kan-bayashi** [comment]
Again, please use the issue template and report your environment.

**Comment by mahbubnoor** [comment]
OK, Sorry sir, i did not understand that word using issue template, Now i think i got it, you are meaning me to ask question in that issue not here. Now i will delete my whole espnet and python environment. And if i face again this problem i will ask in that issue template. Thank you again. And sorry for my mistake.
