### ISSUE TITLE
Run Teacher forcing decoding ESPNet1 TTS

### ISSUE THREAD

**Issue by szmmm** [espnet/espnet#2762]
Hello! I have been using this version of ESPNet1 to build a TTS system https://github.com/creatorscan/espnet/tree/asrtts3-v.0.4.0/egs/librispeech/asrtts. Now I want to check the decoded test-set mel-spectrogram using teacher forcing decoding. Is this functionality available in my version of ESPNet? I tried to add `use_teacher_forcing: true` in the decoding configuration `conf/decode_tts.yaml` but it does not recognise this argument. By the way I am assuming teacher forcing is used for training, but not for decoding by default. Are my assumptions correct?
```
usage: tts_decode.py [-h] [--config CONFIG] [--config2 CONFIG2]
                     [--config3 CONFIG3] [--ngpu NGPU]
                     [--backend {chainer,pytorch}] [--debugmode DEBUGMODE]
                     [--seed SEED] --out OUT [--verbose VERBOSE]
                     [--preprocess-conf PREPROCESS_CONF] --json JSON --model
                     MODEL [--model-conf MODEL_CONF]
                     [--maxlenratio MAXLENRATIO] [--minlenratio MINLENRATIO]
                     [--threshold THRESHOLD]
tts_decode.py: error: unrecognized arguments: --use_teacher_forcing=True
```

Thank you very much and let me know if you need more info.

**Comment by szmmm** [comment]
Hi, I just want to know if ESPNet 1 TTS support teacher-forcing decoding. What is the command to achieve this? If someone could tell me I can simply check with my TTS system to see if it works. Thank you!

**Comment by kan-bayashi** [comment]
I think I have not implemented it.
Maybe you can do it call `forward` function instead of `inference`.

**Comment by szmmm** [comment]
> I think I have not implemented it.
> Maybe you can do it call `forward` function instead of `inference`.

Thank you for your reply. Do you mean under `espnet/tts/pytorch_backend/tts.py ` Line 490?
```
            # decode and write
            outs = model.inference(x, args, spemb)[0]
            if outs.size(0) == x.size(0) * args.maxlenratio:
                logging.warning("output length reaches maximum length (%s)." % utt_id)
            logging.info('(%d/%d) %s (size:%d->%d)' % (
                idx + 1, len(js.keys()), utt_id, x.size(0), outs.size(0)))
            f[utt_id] = outs.cpu().numpy()
```

Does it work if I simply change `outs = model.inference(x, args, spemb)[0]` to `outs = model.forward(x, args, spemb)[0]`? Is there anything else I need to change?

**Comment by kan-bayashi** [comment]
I checked code but unfortunately you need to implement by yourself.
You can implement new function by using the part of forward function.

**Comment by szmmm** [comment]
> I checked code but unfortunately you need to implement by yourself.
> You can implement new function by using the part of forward function.

OK, thanks. I will have a look.

**Comment by szmmm** [comment]
> I checked code but unfortunately you need to implement by yourself.
> You can implement new function by using the part of forward function.

Just to confirm again, teacher forcing is used during training, is that correct?

**Comment by kan-bayashi** [comment]
Yes.

**Comment by szmmm** [comment]
> I checked code but unfortunately you need to implement by yourself.
> You can implement new function by using the part of forward function.

Hello. I think I need to implement this functionality myself. Could you please give me more hint as in how to do this? E.g. Where is the forward function and how might I able to use 'part of the forward function'? Thank you very much!

**Comment by kan-bayashi** [comment]
> Is this variable necessary? 

`args` is not needed.

> Also how can I get the value of ilens and y?

`ilens` can be calculated from the input length (e.g. if `xs` is `(1, T)`, `ilens=[T]`). 
Since the teacher forcing will use the groundtruth mel-spectrogram (`y`), you need to load it.

**Comment by szmmm** [comment]
> `ilens` can be calculated from the input length (e.g. if `xs` is `(1, T)`, `ilens=[T]`).
> Since the teacher forcing will use the groundtruth mel-spectrogram (`y`), you need to load it.

Thank you for your reply. I now have changed `load_input=True` in `LoadInputsAndTargets()`, and I can load the target using
```y = data[1][0]
y = torch.FloatTensor(y).to(device)
```
Is `FloatTensor(y).to(device)` a necessary step?

**Comment by szmmm** [comment]
Update: 

I now have successfully decoded which seems to be using teacher forcing:
```
            outs = model.decode_tf(xs, ilens, ys, spembs)[0]
```
Where the `decode_tf()` function is derived from the `forward` function under `espnet/nets/pytorch_backend/e2e_tts_tacotron2.py`

```
    def decode_tf(self, xs, ilens, ys, spembs=None):
        # check ilens type (should be list of int)
        if isinstance(ilens, torch.Tensor) or isinstance(ilens, np.ndarray):
            ilens = list(map(int, ilens))

        # calculate tacotron2 outputs
        hs, hlens = self.enc(xs, ilens)

        if self.spk_embed_dim is not None:
            spembs = F.normalize(spembs).unsqueeze(1).expand(-1, hs.size(1), -1)
            hs = torch.cat([hs, spembs], dim=-1)
        after_outs, before_outs, logits, att_ws = self.dec(hs, hlens, ys)

        return after_outs, before_outs, logits
```

If there is anything that is obviouly wrong with the code please let me know. But it appears to produce what looks likee audio features so far.

**Comment by migi-gon** [comment]
Hello! Have you implemented this teacher forcing in espnet 1 tts? I am also trying to do the same  but with no luck so far.

**Comment by szmmm** [comment]
@migi-gon Please read about the changes I mentioned above. Make sure you understand them and then in `espnet/tts/pytorch_backend/tts.py`, after data is loaded use the following code at the end:

```
            if train_args.use_speaker_embedding:
                spemb = data[2][0]  
                spemb = torch.FloatTensor(spemb).to(device)
            else:
                spemb = None
            x = data[0][0]
            x = torch.LongTensor(x).to(device)

            y = data[1][0]
            y = torch.FloatTensor(y).to(device)

            outs = model.decode_tf(xs, ilens, ys, spembs)[0]
            out = outs[0]
            if out.size(0) == x.size(0) * args.maxlenratio:
                logging.warning("output length reaches maximum length (%s)." % utt_id)
            logging.info('(%d/%d) %s (size:%d->%d)' % (
                idx + 1, len(js.keys()), utt_id, x.size(0), out.size(0)))
            f[utt_id] = out.cpu().numpy()
```

The problem I had was the dimensionality of the tensors need to match the format used in functions, hence the `unsqueeze`. It is better to print out the tensors to see exactly what's going on. This might not be the optimal solution but should work. I hope this helps
