### ISSUE TITLE
What is the truly batchsize?

### ISSUE THREAD

**Issue by Jxu-Thu** [espnet/espnet#2772]
Thanks for your great codes! 

Version : espnet 0.9.6

The truly batch size is set to NUM_OF_GPU * Batch or just Batch?

For example, the espnet/egs/librispeech/asr1/conf/tuning/train_pytorch_conformer_large.yaml
batchsize : 32

Does it mean we always the 32 sentences for training no matter how many GPUs I used?
Or the true batch size is given by GPUs * batch size?

**Comment by kamo-naoyuki** [comment]
NUM_OF_GPU * Batch, in espnet1

**Comment by Jxu-Thu** [comment]
Many thanks!
