### ISSUE TITLE
Does espnet2 no longer support Word LM? 

### ISSUE THREAD

**Issue by Alex-Songs** [espnet/espnet#2773]
Does espnet2 no longer support Word LM? Thanks!

**Comment by sw005320** [comment]
A word LM is very powerful on small scale data like WSJ, but we don't use it so much for the other tasks. So, we don't have a plan to do it right now. If you and other people request this function, we'll make it a higher priority.

**Comment by Alex-Songs** [comment]
Thank you for your answer. @sw005320
