### ISSUE TITLE
Espnet2 TTS How to save all models in the training

### ISSUE THREAD

**Issue by RuslanSel** [espnet/espnet#2775]
Hi,

How don't remove the model files excluding n-best epoch and latest epoch in the training?

Thanks in advance.

**Comment by kamo-naoyuki** [comment]
No, you can't, but you can make n-best larger.
For my inference, can i hear why you need it?

**Comment by RuslanSel** [comment]
Thanks.
Just to test models 100, 200, and so on iterations.
