### ISSUE TITLE
espnet2: how to direct to use pinyin to solve read not right？

### ISSUE THREAD

**Issue by wac81** [espnet/espnet#2780]
espnet2 TTS:how to direct to use pinyin to solve read not right？

ex:
百万医疗--->bai2 wan4 yi1 liao2 (right spelling)

but model output：百万医疗--->bai2 wan4 **yi4** liao2 (wrong spelling)

i  want input 百万医(**yi1**)疗  to solve this issue, then i want elegant implementation a func to solve this ？

**Comment by kan-bayashi** [comment]
If you can prepare `text` with pinyin, you can use `--g2p none`.


```
# before
utt_id_1 百万医疗

# after 
utt_id_1 bai2 wan4 yi1 liao2
```

https://github.com/espnet/espnet/tree/master/egs2/TEMPLATE/tts1#supported-text-frontend

**Comment by wac81** [comment]
i use espnet2 with python code:
how to use it?
```
    with torch.no_grad():
        wav, c, *_ = text2speech(text)
        wav = vocoder.inference(c)
```
i found 
`        self.preprocess_fn = TTSTask.build_preprocess_fn(train_args, False)`

maybe I call build_preprocess_fn? and define args g2p in train_args?

another way, i reconstruct a class implement a text --> pinyin---> Initials finals---->token list id?

which one or other better way？

**Comment by kan-bayashi** [comment]
Do you want to change wihtout the training?
Then, it is better to create a new g2p module, and specify it for `g2p`.
https://github.com/espnet/espnet/blob/master/egs2/TEMPLATE/tts1/README.md#how-to-add-a-new-g2p-module

**Comment by wac81** [comment]
if i set g2p = none , then i have to set token_type = chr?

**Comment by kamo-naoyuki** [comment]
`token_type=phn` with `g2p = none` indicates splitting by space: e.g. `bai2 wan4 yi4 liao2` -> `bai2, wan4, yi4, liao2`

https://github.com/espnet/espnet/blob/master/espnet2/text/phoneme_tokenizer.py#L103-L104

`token_type=char` is character level. e.g. `百万医疗` -> `百, 万, 医, 疗`

**Comment by wac81** [comment]
thanks, i will try

**Comment by wac81** [comment]
@kamo-naoyuki @kan-bayashi 
to train Chinese-English hybrid model TTS model， I choose which g2p type？

**Comment by kan-bayashi** [comment]
We have no such a G2P module.
Please define by yourself or prepare `text` with phoneme and then use `g2p=none`.

**Comment by wac81** [comment]
thanks

**Comment by wac81** [comment]
> `token_type=phn` with `g2p = none` indicates splitting by space: e.g. `bai2 wan4 yi4 liao2` -> `bai2, wan4, yi4, liao2`
> 
> https://github.com/espnet/espnet/blob/master/espnet2/text/phoneme_tokenizer.py#L103-L104
> 
> `token_type=char` is character level. e.g. `百万医疗` -> `百, 万, 医, 疗`

are you sure 
`token_type=phn with g2p = none`
because i get error :
```
 File "/usr/local/lib/python3.6/dist-packages/espnet2/text/build_tokenizer.py", line 54, in build_tokenizer
    raise ValueError("g2p_type is required if token_type=phn")
ValueError: g2p_type is required if token_type=phn
```
and i found out code in build_tokenizer.py conflict
```
    elif token_type == "phn":
        if g2p_type is None:
            raise ValueError("g2p_type is required if token_type=phn")
```
