### ISSUE TITLE
ESPNet TTS-Transformer PyTorch-ONNX export failed on ATen operator new_zeros

### ISSUE THREAD

**Issue by nehasoni3** [espnet/espnet#2783]
HI
I am working on ESPNet TTS transformer PyTorch model. I am trying to convert the model into ONNX using this code-
```
torch.onnx.export(
        model,
        x, 
        onnx_model_name,
        export_params = True,
        opset_version = 10,
        do_constant_folding = True,
        input_names = ['input'],
        output_names = ['output'],
        dynamic_axes= {'input':[0],
                       'output':[0]})
```
Here, 
Model's input (x): torch.Size([1, 5])
Model's output: torch.Size([1, 80, 50])

I am getting this error:
```
/home/nehasoni/EspnetAnaconda/envs/ESPnet3.6/lib/python3.6/site-packages/torch/onnx/utils.py:655: UserWarning: ONNX export failed on ATen operator new_zeros because torch.onnx.symbolic_opset10.new_zeros does not exist
.format(op_name, opset_version, op_name))

KeyError Traceback (most recent call last)
in ()
32 format="%(asctime)s (%(module)s:%(lineno)d) %(levelname)s: %(message)s",
33 )
---> 34 main()

in main()
24 output_names = ['output'],
25 dynamic_axes= {'input':[0],
---> 26 'output':[0]})
27 print("Done!")
28
```

Please do needful in this regard. Thank You.

**Comment by kan-bayashi** [comment]
ONNX conversion is not supported.
You need to modify by yourself.

**Comment by nehasoni3** [comment]
> ONNX conversion is not supported.
> You need to modify by yourself.

I have refactor the code and try to convert.
#https://github.com/pytorch/pytorch/issues/49692

**Comment by nehasoni3** [comment]
> ONNX conversion is not supported.
> You need to modify by yourself.

I have refactored the code but still some ops are not convertible to ONNX.

**Comment by mudong0419** [comment]
Any news?

**Comment by neso613** [comment]
> Any news?

not yet :(
