### ISSUE TITLE
Training procedure for voice conversion

### ISSUE THREAD

**Issue by sarrbranka** [espnet/espnet#2789]
Hi, Thank you for your awesome work!
I have some question.
In the training process for voice conversion model, do you have to change one's voice to text once and then convert the text 
 into the target's voice? Is it hard to directly change one's voice to another's like voice changer app?

**Comment by unilight** [comment]
We have a mel-spec to mel-spec recipe: https://github.com/espnet/espnet/tree/master/egs/arctic/vc1
