### ISSUE TITLE
Question: How can I enable SpeedPerturbation data augment?

### ISSUE THREAD

**Issue by Jxu-Thu** [espnet/espnet#2795]
Thanks for your great codes!
In code [ESPNET 1, master]
**_espnet/egs/librispeech/asr1/readme.txt_**
I observe that large conformer using **SpeedPerturbation** can get better performance.

But I do not find any tutorials about how to enable SpeedPerturbation to improve the performance. 

Could you provide the tutorials about how to enable **SpeedPerturbation**? especially on the **librispeech** and the conformer model.

**Comment by kamo-naoyuki** [comment]
It's applied by default, here:

https://github.com/espnet/espnet/blob/53f6aa11d8702c76fc3220ca94ea279a11dbcf19/egs/librispeech/asr1/run.sh#L108-L112

**Comment by Jxu-Thu** [comment]
Many thanks!
