### ISSUE TITLE
CUDA out of memory

### ISSUE THREAD

**Issue by Selma-KA** [espnet/espnet#2798]
I'm trying to train 90 hours ASR data(fbank created by kaldi) under espnet,  but I get CUDA out of memory. I tried to reduce the batch size but I got the same problem. 

**PS:** this is my first time using espnet so I don't know much about it and I'm still a beginner with deep learning.

Any insights into this problem would be appreciated. Thanks in advance.

**Environment:**
 - OS: Ubuntu 18.04
 - python version: 3.6
 - pytorch version: 1.3.1
 - Nvidia driver version:  450.80.02
 - CUDA runtime version: 10.1
 - GPU:  RTX 2060 Super 8 Go
 
 ./run.sh --stage 4 --ngp 1
run.pl: job failed, log is in exp/train_nodev_pytorch_train/train.log

[train.log](https://github.com/espnet/espnet/files/5729636/train.log)

**Comment by kamo-naoyuki** [comment]
Why don't try smaller batch_size?

**Comment by kamo-naoyuki** [comment]
If you still got error with batch_size=1, your dataset has too long sequence. It's better to consider removing long sequence or splitting using forced alignment.

**Comment by Selma-KA** [comment]
> If you still got error with batch_size=1, your dataset has too long sequence. It's better to consider removing long sequence or splitting using forced alignment.

Yes, that was the problem. I remove utt having more than 3000 frames and more than 400 characters and everything is working fine at the moment. Thanks a lot

**Comment by okkteam** [comment]
![image](https://user-images.githubusercontent.com/49552492/106376419-1dd86380-63d0-11eb-98dc-0f4ee4235cde.png)
