### ISSUE TITLE
ESPnet2  Distributed training Error

### ISSUE THREAD

**Issue by panpanli521** [espnet/espnet#2803]
![image](https://user-images.githubusercontent.com/15307422/102980511-a5fe5a00-4542-11eb-8081-c82fa8e9cebc.png)

when I execute this command，error occur as follows:
![image](https://user-images.githubusercontent.com/15307422/102980605-cd552700-4542-11eb-845c-74b768211023.png)

Someone else could give me a valid example? Thanks.

**Comment by kamo-naoyuki** [comment]
here:

https://github.com/espnet/espnet/blob/master/egs2/TEMPLATE/asr1/asr.sh
