### ISSUE TITLE
ESPnet2  Distributed training

### ISSUE THREAD

**Issue by panpanli521** [espnet/espnet#2804]
Espnet Doc: https://espnet.github.io/espnet/espnet2_distributed.html
![image](https://user-images.githubusercontent.com/15307422/102984169-26738980-4548-11eb-9832-9432bfe505b4.png)

when I execute this command , 
`python -m espnet2.bin.asr_train --ngpu 1 --multiprocessing_distributed true`
error occurs.
![image](https://user-images.githubusercontent.com/15307422/102984784-17410b80-4549-11eb-97b4-e18d1b6914fc.png)

After I modify this command like this: 
`python -m espnet2.bin.asr_train --ngpu 1 --multiprocessing_distributed true --output_dir conf --token_list data/token_list/bpe_unigram30/tokens.txt --bpemodel data/token_list/bpe_unigram30/bpe.model --train_data_path_and_name_and_type dump/raw/lm_train.txt,speech,text --allow_variable_data_keys true`
error occurs too
![image](https://user-images.githubusercontent.com/15307422/102984548-b4e80b00-4548-11eb-9a2a-3389e7529111.png)

Someone else run into this problem?

**Comment by kamo-naoyuki** [comment]
A
