### ISSUE TITLE
How we can perform greedy decoding for RNN_T ?

### ISSUE THREAD

**Issue by Selma-KA** [espnet/espnet#2805]
Hi,
I trained an RNNT model using vivos recipe. I performed the decoding using beam search successfully now I'm trying to perform the decoding with greedy search I thought I could do that by setting beam-size parameter to 1:

**# decoding parameters**
batch: 0
**beam-size: 1**
search-type: default
score-norm: True

 but I got this error:

  File "/home/selma/espnet/espnet/asr/pytorch_backend/asr.py", line 1074, in recog
    js[name], nbest_hyps, train_args.char_list
  File "/home/selma/espnet/espnet/asr/asr_utils.py", line 828, in add_results_to_json
    rec_text, rec_token, rec_tokenid, score = parse_hypothesis(hyp, char_list)
  File "/home/selma/espnet/espnet/asr/asr_utils.py", line 796, in parse_hypothesis
    tokenid_as_list = list(map(int, hyp["yseq"][1:]))
TypeError: string indices must be integers

So I would like to know how could I perform greedy decoding for my model.
Thanks in advance!

**Comment by Selma-KA** [comment]
I fixed this error by making these changes:

![image](https://user-images.githubusercontent.com/56079125/103017105-6ab05b00-4543-11eb-844f-73d93e3a9b66.png)

in https://github.com/espnet/espnet/blob/master/espnet/asr/asr_utils.py
But I don't know if this is the best way to do it or not.

**Comment by sw005320** [comment]
@b-flo, could you check it?
I think the greedy decoding is important for the debugging purpose and we may include it as a test.

**Comment by b-flo** [comment]
Sorry, this is a silly mistake in `beam_search_transducer.py` (l.161) I introduced during a refactoring for CER/WER reporting. Decoding methods should return a list of hypotheses during inference.

@sw005320 Greedy should covered be in unit test though, I'll take a look later sorry.
