### ISSUE TITLE
why calling espnet2 module in a espnet script????

### ISSUE THREAD

**Issue by 200987299** [espnet/espnet#2806]
I was running chime4/asr1/run.sh and the following error occurred:

 File "/espnet/espnet/nets/beam_search_transducer.py", line 19, in <module>
    from espnet2.asr.decoder.abs_decoder import AbsDecoder
ModuleNotFoundError: No module named 'espnet2'

**Comment by b-flo** [comment]
Hi,

BeamSearch interface for espnet1 and espnet2 where unified in the past and split again later, that's why. It shouldn't cause any issue though?

**Comment by 200987299** [comment]
> Hi,
> 
> Beam search interface for espnet1 and espnet2 were unified in the past and split again later, that's why. It shouldn't cause any issue though, could you give more information? You can remove import and change typing l.38 but I'll modify if necessary.

Thanks for replying. Can you guys try to run the scripts both on a local machine and on a server using docker before release the code? If you tried you can see there are errors. 

bests

**Comment by b-flo** [comment]
> Thanks for replying. Can you guys try to run the scripts both on a local machine and on a server using docker before release the code? If you tried you can see there are errors.
>
> bests

If you want us to investigate, you'll have to report the errors yourself. When you created an issue, a template with all needed information to report was given.
Outside docker I'm not using, I can at least tell you that other users and I have no issues with transducer-based models and other recipes.

**Comment by kamo-naoyuki** [comment]
@Fhrozen Could you check. I agree we should add a test for docker in ci.

**Comment by Fhrozen** [comment]
@kamo-naoyuki , well, I forgot about this situation. Docker container on espnet1 only calls espnet1 folders while espnet2 calls both so this is the main reason. It will be better to remove the call from espnet1

**Comment by 200987299** [comment]
> @kamo-naoyuki , well, I forgot about this situation. Docker container on espnet1 only calls espnet1 folders while espnet2 calls both so this is the main reason. It will be better to remove the call from espnet1

Thanks for the attention, you are right and this bug could be easily fixed by moving beam_search_transducer.py into any espnet1 folder and call it from there. 

There is still a bug (hope that I am wrong), I will make a pull request after I can run chime4 script using docker if no other developer is fixing it.

bests

**Comment by 200987299** [comment]
> > Thanks for replying. Can you guys try to run the scripts both on a local machine and on a server using docker before release the code? If you tried you can see there are errors.
> > bests
> 
> If you want us to investigate, you'll have to report the errors yourself. When you created an issue, a template with all needed information to report was given.
> Outside docker I'm not using, I can at least tell you that other users and I have no issues with transducer-based models and other recipes. And btw, our code is obviously tested before each release...

thanks for your reply
