### ISSUE TITLE
ESPnet2 Distributed training

### ISSUE THREAD

**Issue by panpanli521** [espnet/espnet#2810]
**Describe the bug**
![image](https://user-images.githubusercontent.com/15307422/103071355-6137f900-45fe-11eb-897c-d2bc1ef249e2.png)
when I execute this command ,
`python -m espnet2.bin.asr_train --ngpu 1 --multiprocessing_distributed true`
error occurs.
![image](https://user-images.githubusercontent.com/15307422/103071046-d2c37780-45fd-11eb-8c2f-baab67bf5b5e.png)
After I modify this command like this:
`python -m espnet2.bin.asr_train --ngpu 1 --multiprocessing_distributed true --output_dir conf --token_list data/token_list/bpe_unigram30/tokens.txt --bpemodel data/token_list/bpe_unigram30/bpe.model --train_data_path_and_name_and_type dump/raw/lm_train.txt,speech,text --allow_variable_data_keys true`
error occurs too
![image](https://user-images.githubusercontent.com/15307422/103071089-e373ed80-45fd-11eb-86b6-1afed4c55205.png)
Someone else run into this problem?
**Basic environments:**
 - OS information: [e.g., Linux 4.9.0-11-amd64 #1 SMP Debian 4.9.189-3+deb9u2 (2019-11-11) x86_64]
 - python version: [e.g. 3.7.3 (default, Mar 27 2019, 22:11:17) [GCC 7.3.0]]
 - espnet version: [e.g. espnet 0.8.0]
 - Git hash [e.g. b88e89fc7246fed4c2842b55baba884fe1b4ecc2]
   - Commit date [e.g. Tue Sep 1 09:32:54 2020 -0400]
 - pytorch version [e.g. pytorch 1.4.0]
 1.3.1
You can obtain them by the following command
```
cd <espnet-root>/tools
. ./activate_python.sh

echo "- OS information: `uname -mrsv`"
python3 << EOF
import sys, espnet, torch
pyversion = sys.version.replace('\n', ' ')
print(f"""- python version: \`{pyversion}\`
- espnet version: \`espnet {espnet.__version__}\`
- pytorch version: \`pytorch {torch.__version__}\`""")
EOF
cat << EOF
- Git hash: \`$(git rev-parse HEAD)\`
  - Commit date: \`$(git log -1 --format='%cd')\`
EOF
```

**Environments from `torch.utils.collect_env`:**
e.g.,
```
Collecting environment information...
PyTorch version: 1.4.0
Is debug build: No
CUDA used to build PyTorch: 10.0

OS: CentOS Linux release 7.5.1804 (Core)
GCC version: (GCC) 7.2.0
CMake version: version 2.8.12.2

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: 10.0.130
GPU models and configuration:
GPU 0: TITAN RTX
GPU 1: TITAN RTX
GPU 2: TITAN RTX
GPU 3: TITAN RTX

Nvidia driver version: 440.33.01
cuDNN version: Could not collect

Versions of relevant libraries:
[pip3] numpy==1.18.5
[pip3] pytorch-ranger==0.1.1
[pip3] pytorch-wpe==0.0.0
[pip3] torch==1.4.0
[pip3] torch-complex==0.1.1
[pip3] torch-optimizer==0.0.1a14
[pip3] torchaudio==0.4.0
[pip3] warprnnt-pytorch==0.1
[conda] blas                      1.0                         mkl
[conda] mkl                       2020.1                      217
[conda] mkl-service               2.3.0            py37he904b0f_0
[conda] mkl_fft                   1.1.0            py37h23d657b_0
[conda] mkl_random                1.1.1            py37h0573a6f_0
[conda] pytorch                   1.4.0           py3.7_cuda10.0.130_cudnn7.6.3_0    pytorch
[conda] pytorch-ranger            0.1.1                    pypi_0    pypi
[conda] pytorch-wpe               0.0.0                    pypi_0    pypi
[conda] torch-complex             0.1.1                    pypi_0    pypi
[conda] torch-optimizer           0.0.1a14                 pypi_0    pypi
[conda] torchaudio                0.4.0                    pypi_0    pypi
[conda] warprnnt-pytorch          0.1                      pypi_0    pypi
```
You can obtain them by the following command

```
cd <espnet-root>/tools
. ./activate_python.sh
python3 -m torch.utils.collect_env
```

**Task information:**
 - Task: [e.g., ASR, TTS, ST, ENH]
 - Recipe: [e.g. librispeech]
 - ESPnet1 or ESPnet2

**To Reproduce**
1. move to a recipe directory, e.g., `cd egs/librispeech/asr1`
2. execute `run.sh` with specific arguments, e.g., `run.sh --stage 3 --ngp 1`
3. specify the error log, e.g., `exp/xxx/yyy.log`

**Error logs**
Paste the error logs. If applicable, add screenshots to help explain your problem.

**Comment by kamo-naoyuki** [comment]
I already answered, don't open issue without any reason.
