### ISSUE TITLE
VCTK stage 2: format_wav_scp.py get Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by zhang-wy15** [espnet/espnet#2811]
**Describe the bug**
I run the scripts with no modification on VCTK egs. In stage 2, I get the Segmentation fault (core dumped) error.
<img width="1438" alt="截屏2020-12-24 下午3 24 46" src="https://user-images.githubusercontent.com/31053400/103070271-29c84d00-45fc-11eb-984e-2d79a01979d4.png">
There is no traceback and error report in the log file.
I test the following command on vctk dev set
```
pyscripts/audio/format_wav_scp.py --fs 24000 --audio-format flac --segment=dump/raw/org/dev/logs/segments.1 data/dev/wav.scp dump/raw/org/dev/data/format.1
```
After it finish the processing, it happen the same error as below.
<img width="1437" alt="截屏2020-12-24 下午3 31 48" src="https://user-images.githubusercontent.com/31053400/103070766-27b2be00-45fd-11eb-80c1-387d6966611c.png">
There are 17 lines in ``dump/raw/org/dev/logs/segments.1 ``. It means that it finished processing, but an error is still reported.

I also test on vctk train set and change the ``--nj`` options. It remains the same error.

**Basic environments:**
 - OS information: Linux 4.4.0-142-generic # 168-Ubuntu SMP Wed Jan 16 21:00:45 UTC 2019 x86_64
 - python version: 3.7.4 (default, Aug 13 2019, 20:35:49)  [GCC 7.3.0]
 - espnet version: espnet 0.9.6
 - Git hash 31abeb702df734fb15ba08209db7f14cda00275b
   - Commit date Sun Dec 13 08:04:10 2020 +0000
 - pytorch version pytorch 1.6.0
 
**Environments from `torch.utils.collect_env`:**
```
Collecting environment information...
PyTorch version: 1.6.0
Is debug build: No
CUDA used to build PyTorch: 10.2

OS: Ubuntu 16.04.6 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609
CMake version: version 3.5.1

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: 10.0.130
GPU models and configuration: 
GPU 0: GeForce RTX 2080 Ti
GPU 1: GeForce RTX 2080 Ti
GPU 2: GeForce RTX 2080 Ti
GPU 3: GeForce RTX 2080 Ti
GPU 4: GeForce RTX 2080 Ti
GPU 5: GeForce RTX 2080 Ti
GPU 6: GeForce RTX 2080 Ti
GPU 7: GeForce RTX 2080 Ti
GPU 8: GeForce RTX 2080 Ti
GPU 9: GeForce RTX 2080 Ti

Nvidia driver version: 450.57
cuDNN version: Could not collect

Versions of relevant libraries:
[pip3] deepspeech-pytorch==0.1
[pip3] numpy==1.19.2
[pip3] pytorch-ranger==0.1.1
[pip3] pytorch-wpe==0.0.0
[pip3] torch==1.6.0
[pip3] torch-complex==0.2.0
[pip3] torch-optimizer==0.0.1a17
[pip3] torchaudio==0.6.0
[pip3] torchelastic==0.2.0
[pip3] torchfile==0.1.0
[pip3] torchvision==0.7.0
[pip3] warpctc-pytorch==0.1
[conda] cudatoolkit               10.0.130                      0  
[conda] deepspeech-pytorch        0.1                       dev_0    <develop>
[conda] numpy                     1.19.2                   pypi_0    pypi
[conda] pytorch-ranger            0.1.1                    pypi_0    pypi
[conda] pytorch-wpe               0.0.0                    pypi_0    pypi
[conda] torch                     1.6.0                    pypi_0    pypi
[conda] torch-complex             0.2.0                    pypi_0    pypi
[conda] torch-optimizer           0.0.1a17                 pypi_0    pypi
[conda] torchaudio                0.6.0                    pypi_0    pypi
[conda] torchelastic              0.2.0                    pypi_0    pypi
[conda] torchfile                 0.1.0                    pypi_0    pypi
[conda] torchvision               0.7.0                    pypi_0    pypi
[conda] warpctc-pytorch           0.1                      pypi_0    pypi
```

**Task information:**
 - Task: TTS
 - Recipe: vctk
 - ESPnet2

**To Reproduce**
1.  `cd egs2/vctk/tts1`
2. `run.sh --stage 2 --stop_stage 2`

**Comment by kamo-naoyuki** [comment]
In general, if you met segmentation fault, it is not a problem of espnet or python module, but a problem of some c/c++ libraries. 

You need to debug using gdb to detect your issue. Otherwise, create new Python environment.

**Comment by mthrok** [comment]
@zhang-wy15 Did you locate which line of `format_wav_scp.py` causes the segmentation fault?

**Comment by zhang-wy15** [comment]
> @zhang-wy15 Did you locate which line of `format_wav_scp.py` causes the segmentation fault?

`format_wav_scp.py` finished its process because each audio in the file has been processed. I guess when it returns to `format_wav_scp.sh` where it calls `format_wav_scp.py`, the error occurs. There is no other error information, so I can't locate it.

**Comment by kamo-naoyuki** [comment]
Did you solve? Can I ask what was problem?

**Comment by zhang-wy15** [comment]
> Did you solve? Can I ask what was problem?

Sorry, I can't find the problem. But it is OK when I change the python environment from python in anaconda to anaconda and remake in `tools`. It means that I first setup python with `./setup_python.sh $(command -v python3)` where python3 is installed in anaconda and the error would occur. If I use `./setup_anaconda.sh ~/anaconda3 espnet 3.6`, it will be OK.

**Comment by kamo-naoyuki** [comment]
Okay, thanks.
