### ISSUE TITLE
is normalization in fastspeech/T2 reversible？

### ISSUE THREAD

**Issue by Mingrg** [espnet/espnet#2819]
Hi,
   In fastspeech/T2 training, we use `compute-cmvn-stats` to generate the `cmvn.ark`.
   My question is: Does the normalization use `cmvn.ark` is exactly reversible?

   For example:
   I got a tensor [1.0, 2.0, 3.0]. 
   After normlize, it changed to [1.3, 2.5, 3.1].
   When I use `apply-cmvn --norm-vars=true --reverse=true` to denorm the tensor, does it suppose to `exactly equal` [1.0, 2.0, 3.0]?
    But in my experiment, it not  exactly equal [1.0, 2.0, 3.0], maybe [1.1, 2.9, 3.8] or something like that, just not equal.
    Is that normal?

**Comment by kan-bayashi** [comment]
It’s reversible.
If you give us codes to reproduce the behavior, I may have some more ideas.
