### ISSUE TITLE
Why does ErrorCalculatorTransducer.convert_to_char use y_true for seq_hat?

### ISSUE THREAD

**Issue by Oktai15** [espnet/espnet#2824]
Hello!

I can't understand why `ErrorCalculatorTransducer.convert_to_char` method uses `y_true` lengths (i.e target info) for creating `seq_hat` (i.e model answer).

https://github.com/espnet/espnet/blob/9605c61c6dcef71bb8ab54343c186b3c98879712/espnet/nets/e2e_asr_common.py#L346

**Comment by b-flo** [comment]
Hi,

Sorry it seems I missed this issue... It's fixed in #2932!
