### ISSUE TITLE
distributed training error

### ISSUE THREAD

**Issue by panpanli521** [espnet/espnet#2829]
**Describe the bug**
when I run espnet/egs2/an4/asr1  with 2 machines, and one gpu in every machine, the first node has log as follows:
`2021-01-02T12:27:05 (asr.sh:218:main) ./asr.sh --lang en --train_set train_nodev --lm_config conf/train_lm.yaml --valid_set train_dev --test_sets train_dev test --lm_train_text data/train_nodev/text --ngpu 1 --num_nodes 2 
2021-01-02T12:27:05 (asr.sh:375:main) Stage 1: Data preparation for data/train_nodev, data/train_dev, etc.
2021-01-02T12:27:05 (data.sh:22:main) local/data.sh
2021-01-02T12:27:05 (data.sh:38:main) stage 1: Data Download
local/download_and_untar.sh: an4 directory already exists in ./downloads
2021-01-02T12:27:05 (data.sh:45:main) stage 2: Data preparation
utils/subset_data_dir.sh: reducing #utt from 948 to 100
utils/subset_data_dir.sh: reducing #utt from 948 to 848
2021-01-02T12:27:05 (data.sh:68:main) Successfully finished. [elapsed=0s]
2021-01-02T12:27:05 (asr.sh:394:main) Skip stage 2: Speed perturbation
2021-01-02T12:27:05 (asr.sh:404:main) Stage 3: Format wav.scp: data/ -> dump/raw
/espnet/tools/lib:/espnet/tools/lib64:/home/work/cuda/lib64:/home/opt/nvidia_lib:/usr/local/openmpi-3.1.0/lib:
utils/copy_data_dir.sh: copied data from data/train_nodev to dump/raw/org/train_nodev
utils/validate_data_dir.sh: Successfully validated data-directory dump/raw/org/train_nodev
2021-01-02T12:27:05 (format_wav_scp.sh:42:main) scripts/audio/format_wav_scp.sh --nj 4 --cmd ssh.pl --audio-format flac --fs 16k data/train_nodev/wav.scp dump/raw/org/train_nodev
2021-01-02T12:27:06 (format_wav_scp.sh:109:main) [info]: without segments
ssh.pl: 2 / 4 failed, log is in dump/raw/org/train_nodev/logs/format_wav_scp.*.log`

But the second node is wrong with `FileNotFoundError: [Errno 2] No such file or directory: 'dump/raw/org/train_nodev/logs/wav.2.scp'` in log file dump/raw/org/train_nodev/logs/format_wav_scp.2.log. And `FileNotFoundError: [Errno 2] No such file or directory: 'dump/raw/org/train_nodev/logs/wav.4.scp'` in log file dump/raw/org/train_nodev/logs/format_wav_scp.4.log.

**Basic environments:**
 - OS information: Ubuntu 18.04.5 LTS
 - python version: 3.7.4
 - espnet version: [e.g. espnet 0.8.0]
 - Git hash [e.g. b88e89fc7246fed4c2842b55baba884fe1b4ecc2]
   - Commit date [e.g. Tue Sep 1 09:32:54 2020 -0400]
 - pytorch version: pytorch 1.3.1

```
Collecting environment information...
PyTorch version: 1.4.0
Is debug build: No
CUDA used to build PyTorch: 10.1

OS: CentOS Linux release 7.5.1804 (Core)
GCC version: (GCC) 7.5.0
CMake version: version 2.8.12.2

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: V10.1.243
GPU models and configuration:
GPU 0: Tesla V100-SXM2


Nvidia driver version: 440.33.01
cuDNN version: Could not collect

Versions of relevant libraries:
[pip3] numpy==1.18.5
[pip3] pytorch-ranger==0.1.1
[pip3] pytorch-wpe==0.0.0
[pip3] torch==1.4.0
[pip3] torch-complex==0.1.1
[pip3] torch-optimizer==0.0.1a14
[pip3] torchaudio==0.4.0
[pip3] warprnnt-pytorch==0.1
[conda] blas                      1.0                         mkl
[conda] mkl                       2020.1                      217
[conda] mkl-service               2.3.0            py37he904b0f_0
[conda] mkl_fft                   1.1.0            py37h23d657b_0
[conda] mkl_random                1.1.1            py37h0573a6f_0
[conda] pytorch                   1.4.0           py3.7_cuda10.0.130_cudnn7.6.3_0    pytorch
[conda] pytorch-ranger            0.1.1                    pypi_0    pypi
[conda] pytorch-wpe               0.0.0                    pypi_0    pypi
[conda] torch-complex             0.1.1                    pypi_0    pypi
[conda] torch-optimizer           0.0.1a14                 pypi_0    pypi
[conda] torchaudio                0.4.0                    pypi_0    pypi
[conda] warprnnt-pytorch          0.1                      pypi_0    pypi
```
You can obtain them by the following command

```
cd <espnet-root>/tools
. ./activate_python.sh
python3 -m torch.utils.collect_env
```

**Task information:**
 - Task: ASR
 - ESPnet2

**Error logs**
The second node error as follows:
`2021-01-02 12:08:51,467 (format_wav_scp:43) INFO: /miniconda/envs/espnet/bin/python3 pyscripts/audio/format_wav_scp.py --fs 16k --audio-format flac dump/raw/org/train_nodev/logs/wav.2.scp dump/raw/org/train_nodev/data/format.2
Traceback (most recent call last):
  File "pyscripts/audio/format_wav_scp.py", line 243, in <module>
    main()
  File "pyscripts/audio/format_wav_scp.py", line 142, in main
    with Path(args.scp).open("r") as fscp, out_wavscp.open(
  File "/miniconda/envs/espnet/lib/python3.7/pathlib.py", line 1193, in open
    opener=self._opener)
  File "/miniconda/envs/espnet/lib/python3.7/pathlib.py", line 1046, in _opener
    return self._accessor.open(self, flags, mode)
FileNotFoundError: [Errno 2] No such file or directory: 'dump/raw/org/train_nodev/logs/wav.2.scp'`

This is my error log, someone else has a solution to resolve this problem? Thank you very much.

**Comment by kamo-naoyuki** [comment]
The directories used by scripts, i.e. `dump` in your case,  must be synced between all nodes if using multiple node.

Please read the error message before opening an issue.

**Comment by panpanli521** [comment]
All the nodes have the directory: `dump/raw/org/train_nodev/logs`, in this directory, the first node has files like format_wav_scp.1.log , format_wav_scp.3.log , wav.1.scp, wav.2.scp, wav.3.scp and wav.4.scp, but the second node only has files like format_wav_scp.2.log and format_wav_scp.4.log. And the error in format_wav_scp.2.log is `FileNotFoundError: [Errno 2] No such file or directory: 'dump/raw/org/train_nodev/logs/wav.4.scp'`

**Comment by kan-bayashi** [comment]
You need to share the directory among the nodes (e.g. NFS mounted NAS).

**Comment by panpanli521** [comment]
ok, I will have a try. Thank you very much.
