### ISSUE TITLE
padding with `nan` in tts_pytorch?

### ISSUE THREAD

**Issue by arendu** [espnet/espnet#283]
Just wondering if we should change this
```
def pad_ndarray_list(batch, pad_value=float("nan")):
```
in `tts_pytorch.py`. I believe @ruizhilijhu and @sw005320 mentioned that this can cause grad to become `nan`.

**Comment by kan-bayashi** [comment]
Hi @arendu, thank you for your report.
Actually, Nan is the default value of padding, but when using, I specified the value 0 to pad.
Therefore, it does not cause a problem.
But I think we should remove default value to make it more clear.
I will fix it.

**Comment by kan-bayashi** [comment]
Fixed (#284)
