### ISSUE TITLE
Cannot install warp-ctc

### ISSUE THREAD

**Issue by picheny-nyu** [espnet/espnet#2835]
I am trying to install warp-etc on the latest version of espnet using pytorch 1.4 and cuda 10.1 and get the following error message. I turned on tracing in the shell script for clarity. Help!!!!!

Thanks
Michael

./installers/install_warp-ctc.sh
+ MAKE=make
+ '[' 0 '!=' 0 ']'
++ python3
+ torch_17_plus=false
++ python3
+ torch_11_plus=true
++ python3
+ torch_10_plus=true
++ python3
+ torch_version=14
++ python3
+ cuda_version=101
+ echo cuda_version=101
cuda_version=101
+ false
+ true
+ warpctc_version=0.2.1
+ '[' -z 101 ']'
+ python3 -m pip install warpctc-pytorch==0.2.1+torch14.cuda101
Collecting warpctc-pytorch==0.2.1+torch14.cuda101
  Using cached warpctc_pytorch-0.2.1%2Btorch14.cuda101-cp38-cp38-manylinux1_x86_64.whl (3.1 MB)
ERROR: Requested warpctc-pytorch==0.2.1+torch14.cuda101 from https://files.pythonhosted.org/packages/f5/97/28387755a608f3d8ca6794384be2f887d1ed7f8053b066efa55970e05937/warpctc_pytorch-0.2.1%2Btorch14.cuda101-cp38-cp38-manylinux1_x86_64.whl#sha256=08b2499943957b3113378b6a96bd8ab81a0ceeaaf83c076d7d68a9482f96c74e has different version in metadata: '0.2.1'

**Comment by kan-bayashi** [comment]
This is known issue.
See #2743.
