### ISSUE TITLE
Extract duration using the installed espnet2

### ISSUE THREAD

**Issue by roholazandie** [espnet/espnet#2839]
I have followed your demo in
https://colab.research.google.com/github/espnet/notebook/blob/master/espnet2_tts_realtime_demo.ipynb
and it works perfectly fine. My question is how to extract the durations of phonemes? I tried to following:

```
# synthesis
with torch.no_grad():
    start = time.time()
    wav, outs, outs_denorm, probs, att_ws, durations, focus_rate = text2speech(text)
    wav = vocoder.inference(outs)
```

But it returns ```None``` for durations, att_ws Looks like I can't get durations for Transformer based models. I even dig into the library and realized that the ```att_ws``` should not be ```None``` then we can have durations but the inference always returns ```None``` in tts_inference.
Is there any simple and clean way to extract durations without changing the internals?

**Comment by kan-bayashi** [comment]
Did you use fastspeech?
Currently, only tacotron2 and transformer return `durations`.

**Comment by kan-bayashi** [comment]
Related #2629

**Comment by roholazandie** [comment]
I have changed the code to be able to return the durations. I think it's necessary to have it for all the models though.

**Comment by turian** [comment]
@roholazandie do you mind sharing your code?
