### ISSUE TITLE
Domain adaptation for existing model

### ISSUE THREAD

**Issue by Sebinsky** [espnet/espnet#2845]
Hello,

I am trying to do a domain adaptation for an existing model in a STT context by only providing a text corpus (no speech data). All the tutorials I can find teach how to create a new model from scratch but not how do a domain adaptation for an existing model. 

I currently use the model `Shinji Watanabe/librispeech_asr_train_asr_transformer_e18_raw_bpe_sp_valid.acc.best` for my basic tests and would like to adapt this model to achieve better STT WER results in a specific domain.

My first question is, is it even possible with ESPnet / Kaldi to do a domain adaptation like this and secondly, if it is possible are there any tutorials out there that provide a starting point for my issue?

**Comment by sw005320** [comment]
What you can do is to re-train the language model with this text corpus.
We don't have a specific script to do it, but it would be relatively easy.

If you want to do more than that (e.g., re-train the attention/decoder network or using TTS to generate the corresponding audio), it is more about research topics and I recommend you to check related papers and implement it by yourself.
Our group has a couple of investigations but there are a lot of recent studies along with this direction.
- https://arxiv.org/pdf/1807.10893.pdf
- https://arxiv.org/pdf/1803.10299.pdf

**Comment by Sebinsky** [comment]
Thank you very much for your answer! I think the re-training solution is sufficient for me.

I am still pretty new to ESPnet so I wonder where to start with the training. I have followed the installation instructions for ESPnet and Kaldi at https://espnet.github.io/espnet/installation.html but i sadly can't figure out how to start with the training. Is there any tutorial or any other type of resource I can follow?

**Comment by sw005320** [comment]
See https://espnet.github.io/espnet/espnet2_tutorial.html

**Comment by Sebinsky** [comment]
Thanks again!

The normal training process with one of the provided recipes as described in the espnet2 tutorial is no problem for me. 
The problem is with the re-training. As you mentioned alread, there is no specific script for this task. I went through some of the source code but could not find any way to provide an existing model an re-train it with a text corpus. I would be really thankful if you could provide me with some more information on how to achieve this task.

I am sorry for the inconvenience I am causing!
