### ISSUE TITLE
Better GPU utilization?

### ISSUE THREAD

**Issue by picheny-nyu** [espnet/espnet#2851]
I am training a 4-GPU single compute node model on malach using espnet (not espnet2). It does use all 4 GPUs but the utilization is around 30%-40% per GPU which seems small. Granted this may be particular to my local configuration, but just wondering if there are some magic settings or other easy tricks to use to improve the utilization numbers?

Thanks
Michael

**Comment by kan-bayashi** [comment]
Why don't you increase `n-iter-processes`?
https://github.com/espnet/espnet/blob/21c2f586d9b6a2357d7cf02fcec1e8d40c8f7c7a/espnet/bin/asr_train.py#L263-L268

**Comment by picheny-nyu** [comment]
Thanks. To what value? The number of gpus? The number of cpus?

**Comment by Fhrozen** [comment]
Read https://espnet.github.io/espnet/tutorial.html#multiple-gpu-tips

**Comment by prajwaljpj** [comment]
Is there a similar parameter for TTS VITS Training?
