### ISSUE TITLE
CTC values didn't display properly

### ISSUE THREAD

**Issue by wenjie-p** [espnet/espnet#2852]
Hi, when I run the TIMIT recipe using the `Pure CTC mode` and then to visualize the CTC output values, I found there are two issues in the visualization results:

1.  the number of frames in the visualization results is mismatched to the actual wav content specified by the filename. In other words, the filename and the content in the visualization results is mismatched. After modified the above line
https://github.com/espnet/espnet/blob/21c2f586d9b6a2357d7cf02fcec1e8d40c8f7c7a/espnet/asr/asr_utils.py#L348-L350

to ` self.data = copy.deepcopy(data)`, this mismatch disapears. I think the comments in #349-350 clearly indicates why this mismatch occurs.

2. the number of frames in the visualization results is less than the actual wav content. In my `timit/asr1` recipe, it is a quarter of the actual frames. After look through the training routine, I found it will subsample the frames in each layer. In my `conf/train.yaml`, it is configured with  `subsample: "1_2_2_1_1"`, I think it is the case. To validate my assumption, I modified the config to `subsample: 1_1_1_1_1`, that woks.

Thanks for the great toolkit you have built, if you need further information, please let me know.

**Comment by sw005320** [comment]
Thanks for the report.
Maybe we need to have some documentation about it.

**Comment by wenjie-p** [comment]
Hi, I think the second mismatch may be solved by passing a variable like: `plt.gca().get_xaxis().set_major_formatter(FuncFormatter(lambda x, p: format(int(x*t_scale), ',')))`, where t_scale should be 4 in my case.
As for the first mismatch, I am not familiar with the reason why we make the data sorted in the ascending order as indicated in the comment, my naive thought is that maybe we can keep its order the same to that input to model?
