### ISSUE TITLE
Help getting simple ASR example to work in ESPNET2

### ISSUE THREAD

**Issue by weiyengs** [espnet/espnet#2854]
Does the following ASR example(from the main page) work for ESPNET2 as well?

```
# go to recipe directory and source path of espnet tools
cd egs/tedlium2/asr1 && . ./path.sh
# let's recognize speech!
recog_wav.sh --models tedlium2.transformer.v1 example.wav
```
It's throwing me errors:
bash: line 1: copy-feats: command not found
bash: line 1: paste-feats: command not found

Which from my further search requires me to install Kaldi but I thought the idea of ESPNET2 is not to install kaldi?

Thanks!

**Comment by kan-bayashi** [comment]
That is espnet1 example.
You can use https://github.com/espnet/espnet_model_zoo for espnet2.
