### ISSUE TITLE
CUDA out of memory - How much gpu memory is needed for TTS training?

### ISSUE THREAD

**Issue by Arafat4341** [espnet/espnet#2856]
I am trying to trainTTS model on my local gpu machine.
I am getting the following error:
`RuntimeError: CUDA out of memory. Tried to allocate 56.00 MiB (GPU 0; 5.94 GiB total capacity; 4.98 GiB already allocated; 5.38 MiB free; 5.12 GiB reserved in total by PyTorch)`

My machine has ~6 GB memory. And it is unable to train.
What is the minimum amount of gpu memory required for training?

**Comment by kan-bayashi** [comment]
See header in `yaml` config.
I wrote the info about the GPU.
