### ISSUE TITLE
How to inference single audio file?

### ISSUE THREAD

**Issue by qute012** [espnet/espnet#2859]
thanks for great works!

I have trained ASR based on transformer by Ksponspeech script.

It's training continuously.
![image](https://user-images.githubusercontent.com/33983084/104081440-dbf54b00-5271-11eb-8f69-7661e598a9d3.png)

I want to check performance it in the middle of studying.
![image](https://user-images.githubusercontent.com/33983084/104081437-d4ce3d00-5271-11eb-971b-5d025534227c.png)

How to process audio file and inference model in python code? Maybe pre-processing is based on kaldi script, is that right?

Thank you in advance.

**Comment by sw005320** [comment]
If you just want to check the training process is working well, you can check the validation score (e.g., check acc.png, loss.png, log).
If you want to check the current model is working, you can just run the inference (stage 5).
Yes, espnet1 requires Kaldi pre-processing and it's better to follow stage 5.

**Comment by qute012** [comment]
Thank you for feedback.
I already tried stage 5. It doesn't have problem.
My question means How to infer single audio file? How to implement fbank - asr_recog.py pipeline directly not preparing any files(e. g. .trn, .scp, .ark)

**Comment by kan-bayashi** [comment]
See the script as an example:
https://github.com/espnet/espnet/blob/master/utils/recog_wav.sh

**Comment by qute012** [comment]
@kan-bayashi 
Thank you!!
