### ISSUE TITLE
Memory and GPU usage in inference mode

### ISSUE THREAD

**Issue by roholazandie** [espnet/espnet#2860]
I realized that using fastspeech2 (or even other models) even in inference mode takes about 2GB of RAM and 2GB of GPU. Is there any way to decrease this? Or is it just part of ESPNet?

**Comment by kan-bayashi** [comment]
Sorry for the late reply.
The required memory depends on the length of inputs.
You can consider the windowed attention for encoder block to reduce the required memory in Transformer-based model (it is not supported but not so difficult).

**Comment by roholazandie** [comment]
How hard it is to implement? Can you point me to some codes or part of your repo that needs to be edited?
