### ISSUE TITLE
Optimize   evaluation of model

### ISSUE THREAD

**Issue by prilcool** [espnet/espnet#2862]
Hi  
I am using  Fast Text   and model    model.last1.avg.best    
With  Parallel WaveGAN  vocoder ,It works very nice , I am not using cuda or gpu but  just using cpu.

But because I'm using this on a very low end device , I want to lower the processing parameters so it doe's  synthesis quicker .
Do you know which evaluation parameters I can tune to make it faster  i understand it can have worse quality .

So far i am looking at the vocoder file for  Parallel WaveGAN   config.yml    and   model.json for Fast text .

what to adjust to make it quicker or have lesser load.

**Comment by kan-bayashi** [comment]
I'm not sure what is `FastText`. The important factor is `#layers` for PWG. But if you want to accelerate the inference, please consider the use of MB-MelGAN (slightly worse than PWG, but faster).
