### ISSUE TITLE
should it be sorted?

### ISSUE THREAD

**Issue by gary083** [espnet/espnet#2864]
https://github.com/espnet/espnet/blob/3458c70f8e639d02268ee16efcd4980feddc681b/espnet2/bin/aggregate_stats_dirs.py#L46

This function will aggregate some stats into one file, but the keys(name of text) will be sorted before merging together. 
It will cause the order is different between lm_train_text and text_shape, and i right?

**Comment by kamo-naoyuki** [comment]
The input texts are splited keeping the order, thus the merged file is also sorted.
If the result is not sorted, the input text at splitting stage is not sorted.

**Comment by gary083** [comment]
https://github.com/espnet/espnet/blob/e962a3c609ad535cd7fb9649f9f9e9e0a2a27291/egs2/TEMPLATE/asr1/asr.sh#L582
Okay, i meet this problem because of this script (egs/TEMPLATE/asr1/asr.sh). 
It only merge all the text into lm_text, not sort the text by name. 
But i use some external text and named it in my own order. 
This will make this aggregate function fail in my case.

**Comment by kamo-naoyuki** [comment]
I see. We should insert sort command at the line. I'll fix.

BTW, this tool can change the text order, but the text doesn't require sorted in our recipe except for --num_splits_* option.

**Comment by gary083** [comment]
yap, it happen when i split it into numbers of lm text. my solution in my case is remove the sorted function in aggregate function. Anyway, thanks for replying.
