### ISSUE TITLE
Mapping multiple special tokens in dictionary

### ISSUE THREAD

**Issue by miguelvr** [espnet/espnet#287]
Hey guys,

I'm trying to train the CGN (Dutch) corpus with ESPNET, and I would like to know what are the best practices for the data preparation, specifically to handle the transcriptions:

1) I have 2 special tokens in the transcriptions `xxx` and `ggg` which I have mapped to `<unk>` in the transcription file. However, in the dictionary creation step,  If I use the flag `--non-lang-syms` with a file containing only the `<unk>` symbol, I end up with a dictionary with 2 `<unk>` entries. If I don't use the flag, I'm getting entries for the `<` and `>` symbols, which I don't want...

My dictionary building process:
```
dict=data/lang_1char/${train_set}_units.txt
if [ ${stage} -le 3 ]; then
    ### Task dependent. You have to check non-linguistic symbols used in the corpus.
    echo -e "\nstage 3: Dictionary Preparation\n"
    echo "dictionary: ${dict}"
    mkdir -p data/lang_1char/
    echo "<unk> 1" > ${dict} # <unk> must be 1, 0 will be used for "blank" in CTC
    text2token.py --skip-ncols 1 --nchar 1 --non-lang-syms local/non-language-symbols.txt data/${train_set}/text \
        | cut -f 2- -d" " | tr " " "\n" | sort | uniq | grep -v -e '^\s*$' | awk '{print $0 " " NR+1}' >> ${dict}
    wc -l ${dict}
fi
```

2) Is there any advantage of mapping accented chars to its unaccented counterpart?

Best regards,
Miguel

**Comment by sw005320** [comment]
> I have 2 special tokens in the transcriptions xxx and ggg which I have mapped to <unk> in the transcription file. However, in the dictionary creation step, If I use the flag --non-lang-syms with a file containing only the <unk> symbol, I end up with a dictionary with 2 <unk> entries. If I don't use the flag, I'm getting entries for the < and > symbols, which I don't want...

We did not expect that the training text includes <unk>.  How about just using another unk tag, e.g., <unk2> for xxx and ggg?

> Is there any advantage of mapping accented chars to its unaccented counterpart?

Of course it would reduce the confusability and  reduce the softmax dimension, but I think it would not have a big effect in terms of both speed and accuracy, but I just don't test it.

**Comment by miguelvr** [comment]
@sw005320 My solution was to remove consider `<unk>` as a non-language symbol, but I remove it from the dictionary, forcing all `<unk>` symbols to be mapped to 1. But I guess your solution would work as well.

**Comment by sw005320** [comment]
I see. Thanks for your suggestion. I'll revisit this part to consider when we have `<unk>` in transcripts.
