### ISSUE TITLE
How to get the model.last10.avg.best in TTS?

### ISSUE THREAD

**Issue by halin1999** [espnet/espnet#2870]
Hi,everyone

I want to create a web to demo the TTS model, but i read this notebook https://espnet.github.io/espnet/notebook/tts_realtime_demo.html

I don't have this model.last1.avg.best file in my exp/

how can i get this file?

**Comment by kan-bayashi** [comment]
Try online demo.

For espnet2 (recommend)
https://colab.research.google.com/github/espnet/notebook/blob/master/espnet2_tts_realtime_demo.ipynb

For espnet1 
https://colab.research.google.com/github/espnet/notebook/blob/master/tts_realtime_demo.ipynb
