### ISSUE TITLE
setting mtlalpha to 1.0 does not create results/model.acc.best file

### ISSUE THREAD

**Issue by arendu** [espnet/espnet#288]
When I train with `mtlalpha=1.0` the training completes with no errors but there is no `model.acc.best` model in results (although `model.loss.best` is created).

This breaks the subsequent decoding step.

Seems related to #262

**Comment by sw005320** [comment]
yes, please use `--recog_model loss.best`
See https://github.com/espnet/espnet#ctc-attention-and-hybrid-ctcattention
