### ISSUE TITLE
Unable to run the Recipe for Voice Conversion Challenge 2020 baseline.

### ISSUE THREAD

**Issue by nischal-sanil** [espnet/espnet#2881]
Hi,

I am trying to run the recipe for voice conversion (`vcc20/vc1_task1`), after installing the required dependencies and running the following script:
```
$ ./run.sh --stop_stage 6 \
  --spk TEF1 \
  --pretrained_model_name tts1
```
I am getting the following error at stage 0.

```stage -1: Data and Pretrained model download
Already exists. Skip download.
Pretrained TTS model exists: tts1
PWG model exists: downloads/pwg_task1
stage 0: Data preparation
finished making wav.scp, utt2spk, spk2utt.
finished making text.
utils/data/get_utt2dur.sh: segments file does not exist so getting durations from wave files
utils/data/get_utt2dur.sh: could not get utterance lengths from sphere-file headers, using wav-to-duration
utils/data/get_utt2dur.sh: wav-to-duration is not on your path
```

I am very sorry if the above mentioned info is not much informative. Currently, I have not clue on why this is happening. 

Even If I could understand the possible reasons on why this might be happening, it would be very helpful.

Thanks in Advance,

**Comment by kamo-naoyuki** [comment]
wav-to-duration  is a  command of Kaldi. It seems not to install Kaldi yet.
See documentation: https://espnet.github.io/espnet/installation.html#step-1-optional-install-kaldi
