### ISSUE TITLE
Faster ASR inference

### ISSUE THREAD

**Issue by Arafat4341** [espnet/espnet#2890]
I was wondering if we can faster the inference for asr!
I have a single gpu machine. I am kind of running espnet as a single process service in my machine. When I check the gpu memory consumption of espnet process, I see almost 4 gb gpu memory is consumed. Much of the memory is not used by the process. 
I am trying to find out what factors are responsible for a faster inference time for asr! Do I need to fine tune any config.yaml parameters?
I am using the espnet2 CSJ pre-trained transformer model. Any help is much appreciated!

Thanks in advance!

**Comment by sw005320** [comment]
I think you can just reduce the beam size to make inference faster.

**Comment by Arafat4341** [comment]
@sw005320 Thanks a lot! That really worked!
Although, shorter beam_size leads less accurate result for Japanese. But that certainly speed-ed up the inference.
