### ISSUE TITLE
conformer asr model performs worse on short utterance

### ISSUE THREAD

**Issue by keshawnhsieh** [espnet/espnet#2893]
After applying the SOTA conformer asr model on my own dataset, I find that this model performs worse on short utterance, for example the utterance that shorter than 2 seconds. There are lots of substitution happened compared to conventional model like LAS.

I noticed there are some bugs in relative positional encoding implementations in current espnet. And it has been fixed in this [pull](https://github.com/espnet/espnet/pull/2816). I update my code but the situation keeps the same.

I also worried about the cnn kernel size=31 may introduce too many zero paddings to effecet the performance on short utterance, but nothing get improved when I decrease kernel size to 3.

Any idea for the degradation on short utterance for conformer model?

Few weeks ago, I also noticed conformer model performed not well on long utterance and post the issue [here](https://github.com/espnet/espnet/issues/2797). However, I don't think this have any relations with the problem I posted here.

**Comment by sw005320** [comment]
Many thanks, @keshawnhsieh, I think this is a very important discussion.
I also had the same discussion during SLT.
In addition to conformer vs. transformer in encoder-decoder, we have some similar discussions in non-autoregressive vs. autoregressive.

@pengchengguo, is it possible to show us the WER/CER breakdown for utterance lengths for a couple of tasks you have?

I think we should also have some analysis tools to check the WER/CER breakdown for utterance lengths.
Given our analysis, we can create such an analysis tool.

**Comment by pengchengguo** [comment]
Hi @sw005320 and @keshawnhsieh,
Thanks so much for the information. I have the well-trained models on Aishell1 and Switchboard. I am computing the CERs/WERs for the utterance of different lengths. (Sorry, my internet is not very good, it takes some time to download the models.)

**Comment by WanderingSven** [comment]
I also have done some experiment about short and long utterance on transformer and las. When the transformer model use absolute positional encoding, the performance on long utterance is worse than las and a large number of deletion errors at the end of the utterance. When the transformer use relative positional embedding, the deletion error will disappear. On the short utterance, the transformer and  las have  similar performance. I implement relative positional embedding proposed by "Self-Attention with Relative Position Representations“.

**Comment by keshawnhsieh** [comment]
> I also have done some experiment about short and long utterance on transformer and las. When the transformer model use absolute positional encoding, the performance on long utterance is worse than las and a large number of deletion errors at the end of the utterance. When the transformer use relative positional embedding, the deletion error will disappear. On the short utterance, the transformer and las have similar performance. I implement relative positional embedding proposed by "Self-Attention with Relative Position Representations“.

Did you use the RPE implemented in espnet or you just implemented it by yourself. The RPE implementation in espnet has some problems by now. Refer to this [PR](https://github.com/espnet/espnet/pull/2816)

**Comment by GaofengCheng** [comment]
@WanderingSven can you show more exact data, like how long is long ?

**Comment by WanderingSven** [comment]
I implement it by myself. It is different from the method used by conformer model @keshawnhsieh

**Comment by sw005320** [comment]
We also have the same experimental results with modified RPEs for long recording (we found it independently on https://github.com/espnet/espnet/pull/2816). We'll share this result once it is ready.
Basically, the current bug in RPEs makes the issue in the long recording (but not very sure about the short recording).
So I hope https://github.com/espnet/espnet/pull/2816 would mitigate the issue to some extent.
Also, it looks clear to me that we need an analysis tool for various lengths of recordings.
We'll make it.

**Comment by WanderingSven** [comment]
I used a frame length of 25ms and a frame shift of 10ms for feature extraction. And I set the utterance that longer than 2 seconds as the long utterance. @GaofengCheng

**Comment by keshawnhsieh** [comment]
> Hi @sw005320 and @keshawnhsieh,
> Thanks so much for the information. I have the well-trained models on Aishell1 and Switchboard. I am computing the CERs/WERs for the utterance of different lengths. (Sorry, my internet is not very good, it takes some time to download the models.)

Today I got some new updates to share. I tested WER on LibriSpeech with difference length of audio splits. I roughly split test clean into 3 parts which are 0-2s, 2-10s and 10s+ and tested WER accordingly. 

The trained model I used was the one provided in [RESULTS](https://github.com/espnet/espnet/blob/master/egs/librispeech/asr1/RESULTS.md) of LibriSpeech recipe.
I decode with beam size =10. lm_weight and ctc_weight were set to 0 during decoding.
||0-2s|2-10s|10s+|
|----|----|----|----|
|utt nums|36|1970|614|
|conformer with sp|6.3|2.8|3.2|
|transformer|7.7|3.7|3.3|

Although the WER on short utterance was obviously worse than median and long utterance, this results still can't prove the transformer or conformer model performance worse as the percentage of short utterance in test set is too low.

**Comment by pengchengguo** [comment]
Hi all, 
I compared the CER results of utterances with different lengths on the Aishell-1 test set. The maximum length of the Aishell-1 corpus is 1468 frames, while the minimum length is 184 frames. Most of the utterances are shorter than 800 frames. I split the whole test set into four subsets, which are 0-400, 400-800, 800-1200, 1200-1600 frames. Here are some results.

| | 0-400 | 400-800 | 800-1200 | 1200-1600
| -- | -- | -- | -- | -- |
| #utts | 2249 | 4530 | 392 | 5
| Transformer | 5.4 | 5.6 | 7.5 | 15.9
| Conformer | 4.9 | 5.0 | 7.0 | 16.7
| Conformer (new rel_pos:https://github.com/espnet/espnet/pull/2816) | 4.9 | 4.9 | 6.9 | 19.8

Sorry, I don't have a LAS model. It seems the modifications of https://github.com/espnet/espnet/pull/2816 are better for shorter utterances. I will try a variable-length corpus (like swbd or WSJ) and post some results later.

**Comment by sw005320** [comment]
Many thanks for the detailed report!
Hmm, new RPE seems to degrade the performance in the long recording (although we'd not have so many samples in this range and it is not very statistically reliable).
Do you have some ideas of why it does not work in the long recording, @pengchengguo?

**Comment by pengchengguo** [comment]
Sorry, I am not sure about the reason. Maybe I can test on more datasets and try to figure out it.

**Comment by Mddct** [comment]
Any update on this？
