### ISSUE TITLE
Is it possible to use Pre-trained ASR model for end-to-end ASR ?

### ISSUE THREAD

**Issue by saharghannay** [espnet/espnet#2894]
Hi,

I would like to use a pre-trained ASR model (trained on out of domain data), and fine tune it on in domain data.
Is it possible to do that with the current version of espnet ?

Thank you

**Comment by sw005320** [comment]
See https://espnet.github.io/espnet/tutorial.html#how-to-use-finetuning for espnet1 and https://github.com/espnet/espnet/issues/2319 for espnet 2

**Comment by saharghannay** [comment]
Hi,
Thank you for your answer.
But it seems that the Initialization with pre-trained ASR encoder is not implemented in "https://github.com/espnet/espnet/blob/master/espnet/asr/pytorch_backend/asr.py" , do we have to implement it ?

**Comment by sw005320** [comment]
It is implemented and used for RNN-T and speech translation training for example.
You may also check some rnnt recipes.
Again please check https://espnet.github.io/espnet/tutorial.html#how-to-use-finetuning
If you specify the parameters (encoder, attention, decoder, whatever), you can fine-tune your model of the specific part.

**Comment by saharghannay** [comment]
But for speech translation they implemented the Initialization with pre-trained ASR encoder and MT decoder https://github.com/espnet/espnet/blob/master/espnet/st/pytorch_backend/st.py
