### ISSUE TITLE
MultiHeadAttention output depends on the number of heads

### ISSUE THREAD

**Issue by yuriyarabskyy** [espnet/espnet#2896]
Hi,

I was going through the MultiHeadAttention code https://github.com/espnet/espnet/blob/master/espnet/nets/pytorch_backend/transformer/attention.py
and noticed at line 36
```
self.linear_out = nn.Linear(n_feat, n_feat)
```
that the dimensionality of the output layer is n_feat and in your formulation `n_feat = n_heads x d_k`, which would mean that your output dimensionality of the attention layer depends on the number of heads. However, in the original formulation from "Attention is all you need" (https://arxiv.org/pdf/1706.03762.pdf), the output dimension defined as `d_model` is a separate variable and I would expect it to be usually `d_model < n_feat`.

Is that a bug or is there some reason for the current implementation?

Thanks!
Yuriy

**Comment by sw005320** [comment]
@ShigekiKarita, could you answer this question?
Yes, we know this setup, and when we tune the number of attention heads and attention dimensions, we consider it appropriately.

**Comment by yuriyarabskyy** [comment]
Yes, but if we imagine that `n_feat = 512, n_heads = 8  ->  d_k = 64` and the output of attention is then fixed to `n_feat = 512`, but maybe it's worth being able to specify the output dimension separately. Because let's say we want to increase the number of heads but keep the `d_k` fixed, then we would need to increase the `n_feat` variable in addition to increasing `n_heads` which would in turn increase the output size of the attention module. I would think that this is not always desirable.

Maybe this doesn't have a big impact on the results, but I just wanted to verify.

**Comment by kan-bayashi** [comment]
I think the current implementation uses fixed output dimension for the residual connection.

**Comment by ShigekiKarita** [comment]
IIRC I forked onmt and it has the same definition.
https://github.com/OpenNMT/OpenNMT-py/blob/58bae872d814e457a82dcb29d7688b965315b885/onmt/modules/multi_headed_attn.py#L54

> but maybe it's worth being able to specify the output dimension separately.

Do you know existing implementations doing that? Just curious.

**Comment by yuriyarabskyy** [comment]
Oh I see, I was looking at this implementation 

https://github.com/jadore801120/attention-is-all-you-need-pytorch/blob/fec78a687210851f055f792d45300d27cc60ae41/transformer/SubLayers.py#L22

So maybe this can also be tried out if you want to play around with this parameter :) I think the residual connection should not be a problem, because the input/output dimension can stay fixed. It just allows you to independently vary the number of heads and context size inside of the attention module.
