### ISSUE TITLE
anaconda make

### ISSUE THREAD

**Issue by sw005320** [espnet/espnet#29]
@ShigekiKarita can you include your anaconda based make in Makefile?
If it is complicated, you can prepare different Makefile. Also do you have your own anaconda based path.sh? Is it possible to use one path.sh to handle both venv and anaconda environments?

**Comment by ShigekiKarita** [comment]
OK, I will do it. It is nice to create env including the specific python interpreters. I think Makefile's venv/bin/activate rule can be as complicated as the following travis-CI script.
https://conda.io/docs/user-guide/tasks/use-conda-with-travis-ci.html#the-travis-yml-file

**Comment by ShigekiKarita** [comment]
And I expect `path.sh` is OK because we can create `venv/bin/activate` with `conda create --prefix $(pwd)/venv` or something like that.

**Comment by sw005320** [comment]
I see.
