### ISSUE TITLE
Audio Segmentation Package ESPNet1 TTS

### ISSUE THREAD

**Issue by szmmm** [espnet/espnet#2902]
Hello! I am trying to manually segment an audio data set I have now. Each audio file is in .wav format, a few minutes long and I have the start and end time information for each utterance in the audio file. I want to ask what package is installed in ESPNet1 that might be handy to use to manually segment my own data set, and later on extract filter-bank features that are compatible to TTS training.

Thank you very much and please let me know if the question is not clear.

**Comment by sw005320** [comment]
If you have the start and end time information for each utterance, you can deal with this it through the `segment` file. You do not have to cut it by yourself. It would be internally handled. I don't know whether the `segment` file is used in TTS, but there are a lot of examples of using the `segment` file in the ASR recipe (e.g., tedlium2).

See also https://kaldi-asr.org/doc/data_prep.html
We follow the Kaldi data format.

**Comment by sknadig** [comment]
@szmmm If you have the `segments` file, you might find Kaldi's  [extract_wav_segments_data_dir.sh](https://github.com/kaldi-asr/kaldi/blob/master/egs/wsj/s5/utils/data/extract_wav_segments_data_dir.sh) (which uses the `extract-segments` binary) useful.

**Comment by szmmm** [comment]
Thank you very much for your reply. In the Kaldi documentation it says for data preparation the four files `text`, `utt2spkr`, `segment` and `wav.scp` would be sufficient. Can I use the same utterance name for the speaker name in `utt2spkr` if I do not know the speaker?


Are these files enough to do feature extraction later on and also generate the JSON files used for actual training? The exact scripts I might need to follow some of the exsiting recipes but I want to first ask what files I need to manually generate so that I can do TTS training using any data set I have.

Also separate `text`, `utt2spkr`, `segment` and `wav.scp` are needed for train, dev and evaluation sets, am I correct?

Thank you very much again for your help!

**Comment by sknadig** [comment]
AFAIK you should have `wav.scp`, `text`, `segments`, `utt2spk`, `spk2utt` to move to the next steps.
Each segment corresponds to an utterance, so the keys in `segments` and `text` should match.
If you consider each audio file as a unique speaker, `utt2spk` will have the same keys as the `segments` file and speaker ID same as keys in `wav.scp`.
`wav.scp` can have different keys (maybe file name of audio), since each audio file can have multiple segments associated with it.
Yes, these files are required for train, dev and test sets.

Same data dirs can be used with ESPnet2 (you can skip the data preparation steps).

**Comment by szmmm** [comment]
> AFAIK you should have `wav.scp`, `text`, `segments`, `utt2spk`, `spk2utt` to move to the next steps.
> Each segment corresponds to an utterance, so the keys in `segments` and `text` should match.
> If you consider each audio file as a unique speaker, `utt2spk` will have the same keys as the `segments` file and speaker ID same as keys in `wav.scp`.
> `wav.scp` can have different keys (maybe file name of audio), since each audio file can have multiple segments associated with it.
> Yes, these files are required for train, dev and test sets.
> 
> Same data dirs can be used with ESPnet2 (you can skip the data preparation steps).

Thank you. What if I have multiple speakers in one audio file (it's a conversation recording), and I do not have the information of which speaker spoke which utterance? Can I just use the same utterance name as the speaker ID? This might mean I will have the same number of speakers as the number of utterances. Will this be a problem? I thought this might be ok because x-vectors are extracted for each utterance individually anyway, is that correct?

**Comment by kan-bayashi** [comment]
@szmmm Since we do not use speaker information, that is no problem.
You can use the same speaker e.g., `dummy`.
