### ISSUE TITLE
Question about continue training

### ISSUE THREAD

**Issue by okkteam** [espnet/espnet#2909]
**Describe the Question**
Thanks for your awesome work! 
How to continue training after training is interrupted for some reason? When I tried `--enc-init=exp/{model}/result/snapshot.ep.10` and `--dec-init=exp/{model}/result/snapshot.ep.10`, the re-training loss of the beginning 200 iterations are still very high.

**Comment by b-flo** [comment]
Hi,

> How to continue training after training is interrupted for some reason? When I tried --enc-init=exp/{model}/result/snapshot.ep.10 and --dec-init=exp/{model}/result/snapshot.ep.10, the re-training loss of the beginning 200 iterations are still very high.

You should use `resume` option instead. You can find it at the top of `run.sh` (or you can specify `--resume` to your training command). The option takes a model snapshot path similarly to transfer learning options

**Comment by okkteam** [comment]
> You should use `resume` option instead. You can find it at the top of `run.sh` (or you can specify `--resume` to your training command). The option takes a model snapshot path similarly to transfer learning options

Now it has resumed, thank you very much! Can I close this question?

**Comment by b-flo** [comment]
No problem, I'll do it!
