### ISSUE TITLE
Multi GPU Support for RNNLM

### ISSUE THREAD

**Issue by miguelvr** [espnet/espnet#291]
Is there any know bottleneck preventing the language model to be wrapped with an `nn.DataParallel` call? 

Otherwise, I can do a PR for multi GPU support (for pytorch).

Best regards,
Miguel

**Comment by sw005320** [comment]
Sounds great!
Please do a PR.

**Comment by sw005320** [comment]
@kan-bayashi, can you consider to implement multiple GPU functions in LM training?
