### ISSUE TITLE
./tts.sh: line 192: utils/parse_options.sh: No such file or directory

### ISSUE THREAD

**Issue by evelynyhc** [espnet/espnet#2912]
hello,  i have a question. when i want to run the vctk/tts1/run.sh, there are some problems like this:

./tts.sh: line 192: utils/parse_options.sh: No such file or directory

how can i save it? please help me, thanks!

**Comment by sw005320** [comment]
You do not seem to set up the Kaldi correctly.
Please follow https://espnet.github.io/espnet/installation.html

**Comment by evelynyhc** [comment]
> 您似乎没有正确设置Kaldi。
> 请遵循https://espnet.github.io/espnet/installation.html

if i use egs2,  do i still need to install kaldi?

**Comment by sw005320** [comment]
You don’t have to install Kaldi, but you have to put it under the espnet directory. But if you follow   https://espnet.github.io/espnet/installation.html, it should be done.
Again please carefully follow https://espnet.github.io/espnet/installation.html

**Comment by evelynyhc** [comment]
> 您不必安装Kaldi，但必须将其放在espnet目录下。但是，如果您遵循 https://espnet.github.io/espnet/installation.html，则应完成此操作。
> 再次请仔细遵循https://espnet.github.io/espnet/installation.html

thx, i have sovled this problem by reading installation.html.
