### ISSUE TITLE
Converting numpy arrays to kaldi-style ark files

### ISSUE THREAD

**Issue by lnalborczyk** [espnet/espnet#2913]
Hi,

thank you again for developing and maintaining this great toolkit!

I have some externally processed features stored in numpy arrays that I would like to convert to kaldi-style .ark files so that I can use them as input to train an ASR model. I was wondering whether such a function would be readily available in Kaldi and/or ESPnet?

Thanks!

**Comment by sknadig** [comment]
See if kaldiio's [WriteHelper](https://github.com/nttcslab-sp/kaldiio#writehelper) solves your use case.
