### ISSUE TITLE
Typo: idim should be odim

### ISSUE THREAD

**Issue by jackyguo624** [espnet/espnet#2914]
https://github.com/espnet/espnet/blob/5160363973a1505b3987d6b37976bc04e1d4dad8/espnet/nets/pytorch_backend/transducer/blocks.py#L195

```bash
<<< out_dim = blocks_arch[-1]["idim"] 
>>> out_dim = blocks_arch[-1]["odim"]
```

**Comment by b-flo** [comment]
Nice catch, thanks!
