### ISSUE TITLE
[Question] Implementation of  Conformer's Relative Multi-Head Attention

### ISSUE THREAD

**Issue by sooftware** [espnet/espnet#2917]
First of all, thank you for making a great open source. it is been helping me a lot in research.
  
As far as I understand, It is understood that Relative Positional Encoding Multi-Head Attention proposed in [Transformer-XL](https://arxiv.org/abs/1901.02860) paper is used in Conformer concept. I referred to [this class](https://github.com/espnet/espnet/blob/5298913c0b9c648dd5859ce15789eecfb6e18c27/espnet/nets/pytorch_backend/transformer/attention.py#L117) implementation.But, I don't understand why `rel_shift` method used.  
  
It is understood that zero paddings are added to the front of the sequence, so can I see why this is necessary for the attention of the Conformer?
  
Thank you!

**Comment by pengchengguo** [comment]
Hi @sooftware,

The relative positional encoding used in Conformer is the same as Transformer-XL. Actually, the `rel_shift` function is an efficient computation trick proposed in Appendix B of the Transformer-XL paper. 

By the way, we also find some issues with the current implementation and make a new PR to fix such bugs. More details can be referred to https://github.com/espnet/espnet/pull/2816.

If you still have some questions about Appendix B of the Transformer-XL paper, please feel free to contact me.

**Comment by sooftware** [comment]
Thanks for your answer!!
