### ISSUE TITLE
Input data format for testing asr ru_open_stt models

### ISSUE THREAD

**Issue by MNCTTY** [espnet/espnet#2925]
Hello! I want to test on my wav data this pretrained model (Dataset v1.01, Conformer (4 GPUs, specaug) + Transformer LM (4 GPUs)). And I found out, that I dont understand how I need to prepare audio data for it. I found this parameters in code
```:param ndnarray x: input acoustic feature (B, T, D) or (T, D)```
but can you explain what do they mean?

Thank you

**Comment by akreal** [comment]
Hi! You can try to use https://github.com/espnet/espnet/blob/master/utils/recog_wav.sh to run the model on your wav data.

**Comment by MNCTTY** [comment]
Thank you! I saw this code, but, as I understood, I need use one model from the list "Available pretrained models in the demo script are listed as below." from main read.me, and models for ru_open_stt aren't in it

If I wrong, correct me please

**Comment by akreal** [comment]
You can edit this list and add model's link and name here:

https://github.com/espnet/espnet/blob/a5742a3b23d8a27c0c0ef02d105e1ab9d6321e08/utils/recog_wav.sh#L132-L139

**Comment by MNCTTY** [comment]
Yeah, that list. And there is no model I wanted to test (I want to test this https://github.com/espnet/espnet/blob/master/egs/ru_open_stt/asr1/RESULTS.md)

Does you or anybody know what I should do with .wav file to feed it to the model?

**Comment by sw005320** [comment]
You can just use  https://drive.google.com/file/d/1Gj--PtomC5j8pczdJdRMdxInIZsO-jxK/view?usp=sharing that @akreal shared with us. You can edit `espnet/utils/recog_wav.sh` and add this model to the above list, as @akreal mentioned, e.g., 
```
"ru_open_stt.conformer.v1") share_url="https://drive.google.com/file/d/1Gj--PtomC5j8pczdJdRMdxInIZsO-jxK" ;; 
```
