### ISSUE TITLE
Training Tacotron2 with two speaker data for TTS

### ISSUE THREAD

**Issue by r406** [espnet/espnet#2944]
I have two female speaker audio data. I would like to train tacotron2 as multi-speaker with just two speaker data. 
Can i used follow the run.sh of libritts to train the same.

**Comment by kan-bayashi** [comment]
You can do it. I recommend making your own recipe.
https://github.com/espnet/espnet/tree/master/egs2/TEMPLATE/tts1#faq
And then, you can use configurations in libritts or VCTK recipes.
