### ISSUE TITLE
tts_inference

### ISSUE THREAD

**Issue by evelynyhc** [espnet/espnet#2945]
great work! i have a question, when i want to infer my trained models(vctk), i have this problem:
"tts_inference.py", line 137, in __call__
    raise RuntimeError("missing required argument: 'speech'")
RuntimeError: missing required argument: 'speech'

please tell me how to solve it, thanks!

**Comment by kan-bayashi** [comment]
Please provide code snippet to reproduce your error.
I could not find the reason without them.

**Comment by evelynyhc** [comment]
> Please provide code snippet to reproduce your error.
> I could not find the reason without them.

![image](https://user-images.githubusercontent.com/31717612/107012993-be65c380-67d4-11eb-8789-e23b3115ef86.png)
i write cmd like this, when i print wav=text2speech("Hello World")[0]
the error raised, i do not know what is the problem?

**Comment by kan-bayashi** [comment]
Please try colab at first.
You can understand.
https://colab.research.google.com/github/espnet/notebook/blob/master/espnet2_tts_realtime_demo.ipynb
