### ISSUE TITLE
continue training

### ISSUE THREAD

**Issue by evelynyhc** [espnet/espnet#2948]
hello, i am a new student in tts, and i want to train a multi-speakers by vctk, but i have some problems.
when i stop the training, i got some .pth , but i want to continue training, how can i use the pretrained models to continue it?

**Comment by kan-bayashi** [comment]
You can continue the training by re-running from stage 6, e.g., `run.sh --stage 6`.

**Comment by evelynyhc** [comment]
> You can continue the training by re-running from stage 6, e.g., `run.sh --stage 6`.

but i want to use my pretrained models, like 100epoch.pth, where should  i add it?

**Comment by kan-bayashi** [comment]
The training will continue from the latest epoch automatically.

**Comment by evelynyhc** [comment]
> The training will continue from the latest epoch automatically.

if i want to use the  specific model, how can i do it? thank you

**Comment by kan-bayashi** [comment]
Only the latest checkpoint can be used for the resume because the other .pth file does not include optimizer states. If you want to initialize the model parameters, please use init_param option.
https://espnet.github.io/espnet/espnet2_training_option.html#transfer-learning-fine-tuning-using-pretrained-model

**Comment by evelynyhc** [comment]
ok, i got it, thanks for your reply, and it's a great work!

**Comment by evelynyhc** [comment]
> Only the latest checkpoint can be used for the resume because the other .pth file does not include optimizer states. If you want to initialize the model parameters, please use init_param option.
> https://espnet.github.io/espnet/espnet2_training_option.html#transfer-learning-fine-tuning-using-pretrained-model
ok, i got it, thanks for your reply, and it's a great work!
