### ISSUE TITLE
Changes in original Torch SpecAugment

### ISSUE THREAD

**Issue by PrathamSoni** [espnet/espnet#2952]
Hello!

There's a pretty significant bug in the original repo by zcaceres. I've currently put up a PR for it on that repo and thought you all may be interested in that. Briefly, the process of choosing fitting points differs significantly from the original TF implementation.

I believe it's in https://github.com/espnet/espnet/blob/1f0baf29a3bba6f9740ff0da93b97af64a411882/espnet/utils/spec_augment.py#L67
and perhaps other locations as well; unfortunately, have not had the time to delve into this repo to great depth.

PR (https://github.com/zcaceres/spec_augment/pull/16)

**Comment by sw005320** [comment]
Thanks for the variable information.
@bobchennan, could I ask you to take a look at this?
