### ISSUE TITLE
minlenratio may not be working as intended

### ISSUE THREAD

**Issue by hfujihara** [espnet/espnet#2953]
Hi,

Please correct me if I am wrong as I am not 100% sure about this and I might have missed something.

I encountered a case the decoder outputs very short results in ASR inference even when I set `minlenratio` to hight value.
I looked into the `espnet/blob/master/espnet/nets/beam_search.py` and found that, after `minlen` variable was calculated from `minlenratio` and logged like
https://github.com/espnet/espnet/blob/1f0baf29a3bba6f9740ff0da93b97af64a411882/espnet/nets/beam_search.py#L357-L360,
the variable is not used afterwards anymore in this file.

I suspect `post_process` function should take `minlen` argument and there should be an if-clause to filter out short hypothesis in the last block of the function
https://github.com/espnet/espnet/blob/1f0baf29a3bba6f9740ff0da93b97af64a411882/espnet/nets/beam_search.py#L445-L458
Maybe a line like this might be needed in the 450th line above.
```
                if len(hyp.yseq) < minlen: continue
```

**Comment by sw005320** [comment]
Oh, I think you're right...
@ShigekiKarita, can you make time to fix this?
