### ISSUE TITLE
TTS Phone/Token boundaries? 

### ISSUE THREAD

**Issue by sunasu91** [espnet/espnet#2958]
Hi,

I have built an English TTS system on LJSpeech (Tacotron2 model). Is there a way to get the phone level boundaries of the trained files? Token ID boundaries work too.

I could not figure out how to extract these boundaries. Can you please help?

**Comment by kan-bayashi** [comment]
Sorry for late reply.
You can find `durations` file in the decoding directory.
The file represents the number of frames of each input token.

**Comment by sunasu91** [comment]
Hello,

Thank you for your reply. 
However, in the directory ljspeech, I cannot find the decoding directory. I ran the recipe as is. Can you please let me know if you think I have made an error?

**Comment by kan-bayashi** [comment]
Try egs2.
https://github.com/espnet/espnet/tree/master/egs2/ljspeech/tts1
https://github.com/espnet/espnet/blob/master/egs2/TEMPLATE/tts1/README.md#how-to-run
