### ISSUE TITLE
Speeding up decoding (batch decoding?)

### ISSUE THREAD

**Issue by karkirowle** [espnet/espnet#2961]
I'm writing because would like to speed up/parallelise the decoding a bit, and I'm stuck with it.

(1) I tried with the espnet_model_zoo interface and it takes between 7 to 11 seconds on a GeForce RTX 3090
Python multiprocessing makes it only a tiny bit faster (2-2.5 hour in total for 2000 utterances). Ideally, what I'm aiming for is to be able to do 2000 5-10 seconds long utterances within an hour or so. Let me know if this is unrealistic.

(2) The utils/recog_wav.sh also does not allow for parallelisation, i.e when I try 

    File "/home/boomkin/repos/espnet/espnet/asr/pytorch_backend/recog.py", line 36, in recog_v2
        raise NotImplementedError("multi-utt batch decoding is not implemented")

It also doesn't seem to provide an njob argument to multiprocess it, as similar kaldi/espnet-style scripts.

Do you have any experience/advice regarding batch decoding or parallelization with ESPNet? Do you have any plans for adding this as a feature to your framework?

Thanks in advance!

**Comment by sw005320** [comment]
Batch decoding across the utterance is not supported yet in our current beam search functions (API v2)
Old beam search (API v1) has such functions.
We will develop this batch decoding but it would not be in the near future.

Note that I often use CPU multiple jobs (espnet recipe usually supports it), which is more efficient in terms of utilizing both CPU and GPU resources.

**Comment by karkirowle** [comment]
Thanks for your reply. Looking forward to the added feature.

"Note that I often use CPU multiple jobs (espnet recipe usually supports it), which is more efficient in terms of utilizing both CPU and GPU resources."

I had a deeper look and I realise that it can be indeed parallelised by rewriting in utils/recog_wav.sh

 ${decode_cmd} ${decode_dir}/log/decode.log \
 ${decode_cmd} JOB=1:${nj} ${expdir}/${decode_dir}/log/decode.JOB.log \

For some reason, I was looking for --njobs arg, but asr.sh gave a hint.
