### ISSUE TITLE
How to synthesize with different voices with pretrained/localled trained models

### ISSUE THREAD

**Issue by Wenlong-Y** [espnet/espnet#2983]
I am wondering whether I can use any pretrained model to generate speeches with difference voices. I tried libritts.wavenet.mol.v1 and libritts.tacotron2.v1 pretrained model and they work well. But I don't know how to input speaker's information so I can get speeches with different voices.

I also trained the libritts model  for 30 epocs on my own machine. Could you tell me how I can use the model I trained (snapshot.ep.xx I suppose) to synthesize voices?
Thanks!

**Comment by kan-bayashi** [comment]
You can check the following script:
https://github.com/espnet/espnet/blob/master/utils/synth_wav.sh

To change the speaker, we need to extract x-vector from the reference speech.
In ESPnet2, I prepared multi-speaker demo.
https://colab.research.google.com/github/espnet/notebook/blob/master/espnet2_tts_realtime_demo.ipynb
Please check it.

**Comment by Wenlong-Y** [comment]
Thanks a lot for the answer!

I tried the multi-speaker demo. It works well! I can generate speeches of difference voices by choosing from the list of speakers.

However, the reference speech doesn't seem to change the result much.

If I understand correctly, if I want the machine to generate speech with my own voice. I need to record an audio of myself with 24,000Hz mono and use this file as a reference file. 

I made a 7 second audio but the reference doesn't seem to change the result much. The random generated speech variable seems to have the same effect as wav file containing my own voice. 

My feeling is that spembs is playing a major role in synthesis. Is there a way to generate spembs from my own voice? 

How can I let the model to generate speeches with my own voice? Is there any tips for making the reference wav file?

Thanks!

**Comment by kan-bayashi** [comment]
> My feeling is that spembs is playing a major role in synthesis. Is there a way to generate spembs from my own voice?

Your insight is right.
If the model uses x-vector (i.e.s, spembs) + GST (extracted from reference speech), x-vector is dominant on the decision of speaker characteristics.
The demo does not support the extraction of x-vector since it requires kaldi.
It was a little bit complicated, but you can follow the following parts to extract x-vector.
https://github.com/espnet/espnet/blob/2cfecaf70a2d2826e43db9a2aa34305c6628c5a5/utils/synth_wav.sh#L290-L314

**Comment by Wenlong-Y** [comment]
Thanks! I ended up copying my wav to the etc folder of the downloaded pretrained model. Then use synth_wav.sh of espnet  to generate a random sentence and get the xvector for the wav file. It works!

**Comment by kan-bayashi** [comment]
You need to install kaldi.
https://espnet.github.io/espnet/installation.html#step-1-optional-install-kaldi
