### ISSUE TITLE
Pre-trained model for Streaming Transformer ASR

### ISSUE THREAD

**Issue by Huang17** [espnet/espnet#2989]
@eml914  I noticed the Streaming Transformer ASR model has been merged into master branch. I am wondering if there are available pre-trained models for English and Chinese?

**Comment by eml914** [comment]
Thank you for the question.  Our previous work was done in another implementation and the merged implementation is a re-written version for espnet2.  So unfortunately there is no available pre-trained model for espnet2 yet.

**Comment by Huang17** [comment]
I see, thanks for your quick reply!

**Comment by sw005320** [comment]
If I have time, I’ll make some pre-trained models. I’ll discuss it with @eml914 internally.

**Comment by eml914** [comment]
I'm currently making aishell model but for librispeech it would take some time.  I will let you know if I finished.

**Comment by sw005320** [comment]
Thanks! I think aishell and librispeech are enough for now, but if you need some help, please let me know.

**Comment by Huang17** [comment]
Aishell and librispeech are good enough! Thanks for help again! @sw005320  @eml914
