### ISSUE TITLE
the state-of-the-art model for TTS

### ISSUE THREAD

**Issue by rs-lin** [espnet/espnet#2990]
Hi,

I have been trying to generate audio from text with pertained models and this is by far the best open-source library for TTS I have found online. I really appreciate your effort.

I noticed that there're some differences between the audio generated by ESPnet and, say by Google Cloud's (https://cloud.google.com/text-to-speech) when given the same text. For example, if the text is something like the stock ticker (T-S-L-A), the models in ESPnet seems read it as a word, instead of reading each letter out loud. 

1) Were the difference caused by using different dataset? Since Google Cloud is not open-sourced, I was only guessing.
2)There are many pre-trained models in the library. I have tried most of them but theoretically I would like to know which model & vocoder implemented in ESPnet represents the current state-of-the-art industry standard for TTS?

Thank you.

**Comment by wac81** [comment]
may be comformer fastspeech2 model, but i think it's not difference from fastspeech2

**Comment by jens-totemic** [comment]
I'm experiencing the same issue. For example in this sentence here:
"TTS comes with pretrained models, tools for measuring dataset quality and already used in 20+ languages for products and research projects."

In this sentence, the abbreviation "TTS" is  not correctly spoken letter by letter and the "+" in 20+ is also omitted.

I tried it in both espnet 1 and 2 notebooks here with the pretrained models:
* https://colab.research.google.com/github/espnet/notebook/blob/master/tts_realtime_demo.ipynb
* https://colab.research.google.com/github/espnet/notebook/blob/master/espnet2_tts_realtime_demo.ipynb

Is there any setting I can tweak to improve this?

**Comment by kan-bayashi** [comment]
The problem of G2P.
You can use easier representation for G2P.
e.g. "T T S" or "20 plus"

**Comment by jens-totemic** [comment]
Thank you @kan-bayashi. I filed an improvement request to the g2p project - if it would be handled there it could avoid the separate pre-processing step.
