### ISSUE TITLE
how to retrain just with LM model in asr.sh

### ISSUE THREAD

**Issue by wac81** [espnet/espnet#2992]
how to retrain just with LM model in asr.sh

**Comment by sw005320** [comment]
how about `./run.sh --stage 7 --stop_stage 8`?

**Comment by wac81** [comment]
how can I just create new text train data without audio?

**Comment by WuHao9408** [comment]
1. prepare your new train text (per line like "sent_id sent")
2. create  directory "dump/",  which is in the same path as "asr.sh"
 "/asr1/dump/srctexts" store train text  , "/asr1/dump/dev/text" store dev text, "/asr1/dump/test/text"  store test text.
3. ./run.sh --stage 5 --stop_stage 8 (if you want to use custom dictionary, replace token_list and start with 6)

**Comment by wac81** [comment]
> 1. prepare your new train text (per line like "sent_id sent")
> 2. create  directory "dump/",  which is in the same path as "asr.sh"
>    "/asr1/dump/srctexts" store train text  , "/asr1/dump/dev/text" store dev text, "/asr1/dump/test/text"  store test text.
> 3. ./run.sh --stage 5 --stop_stage 8 (if you want to use custom dictionary, replace token_list and start with 6)

thank you, I have a question: this procedure can create a new dictionary with old train text? or just create a new dictionary with a new train set?

**Comment by WuHao9408** [comment]
> > 1. prepare your new train text (per line like "sent_id sent")
> > 2. create  directory "dump/",  which is in the same path as "asr.sh"
> >    "/asr1/dump/srctexts" store train text  , "/asr1/dump/dev/text" store dev text, "/asr1/dump/test/text"  store test text.
> > 3. ./run.sh --stage 5 --stop_stage 8 (if you want to use custom dictionary, replace token_list and start with 6)
> 
> thank you, I have a question: this procedure can create a new dictionary with old train text? or just create a new dictionary with a new train set?

if you start with stage 5,  new dictionary will be created from new train text.
you had better to use dictionary from old train text,  which can keep same with acoustic model.
just start training at stage 6, and store old dictionary at "/asr1/data/token_list/char/tokens.txt", if you use "char".

the above directory  is not "dump/", the right path is "dump/fbank_pitch/", if you use "fbank_pitch"

**Comment by wac81** [comment]
thank you， i will try
