### ISSUE TITLE
copyright issues

### ISSUE THREAD

**Issue by ShigekiKarita** [espnet/espnet#30]
@ShigekiKarita (me) need to update test/*.py copyrights

@sw005320 I think you need to fill this line 

https://github.com/espnet/espnet/blob/67359ba3c3dcd37243d9b93a98ce4e1ba6a3e299/LICENSE#L189

**Comment by sw005320** [comment]
Thanks.
Will do.

**Comment by sw005320** [comment]
#33 fixed it
