### ISSUE TITLE
Default Makefile installs pytorch 4.0

### ISSUE THREAD

**Issue by ramon-astudillo** [espnet/espnet#300]
Had to change this in `tools/Makefile`

```
-       . venv/bin/activate; pip install pip --upgrade; pip install torch
+       . venv/bin/activate; pip install pip --upgrade; pip install torch==0.3.1
```

BTW In my platform pytorch 4.0 causes a warp_ctc compile error.

**Comment by miguelvr** [comment]
I think that is the intended behavior, as described in the README

**Comment by ramon-astudillo** [comment]
From the other issues it seemed that we were delaying the transition to 4.0.

**Comment by ramon-astudillo** [comment]
We are transiting to 4.0, all clear now. 

To make Pytorch 4.0 run in my platform (SUSE) , the solution was to set the GCC to version 5 or more e.g. in your `~/.bashrc` set

```
# This is needed for warp_ctc and Pytorch 0.4
export CUDA_TOOLKIT_ROOT_DIR=$CUDAROOT
export CC=/usr/bin/gcc-6
export CXX=/usr/bin/gcc-6
```
Props to @creatorscan for this.
