### ISSUE TITLE
No module named espnet.utils.cli_utils

### ISSUE THREAD

**Issue by zyzpower** [espnet/espnet#3003]
I have a bug when I run asr transformer stage 5 decoding.
utils/splitjson.py", line 20, in <module>
    ImportErrorfrom espnet.utils.cli_utils import get_commandline_args
: No module named espnet.utils.cli_utils

**Basic environments:**
 - OS information: Linux 3.10.0-327.ali2012.alios7.x86_64 #1 SMP Mon Oct 9 14:09:14 CST 2017 x86_64
 - python version: 3.6.8
 - espnet version: 0.4.0
 - Git hash f6b55b38a8b5e12a7b88df887dd7d5aa5cd0f6e0
   - Commit date `Wed Jun 26 12:40:31 2019 -0400`
 - pytorch version 1.7.1
 
I checked that there is no cli_utils file,  can you help?

**Comment by sw005320** [comment]
Which recipe did you use?

Also, could you confirm that the path is correctly set?
(It's usually done correctly if you follow https://espnet.github.io/espnet/installation.html)

**Comment by zyzpower** [comment]
I use librispeech. How to check if the path is correctly set? Actually previously my program has no such problem, not too sure what happened...

**Comment by sw005320** [comment]
Could you try to re-install espnet by following the instruction?
`espnet.utils.cli_utils` do exist in
https://github.com/espnet/espnet/blob/master/espnet/utils/cli_utils.py#L13
I actually don't know why it happens.

**Comment by evelynyhc** [comment]
> I use librispeech. How to check if the path is correctly set? Actually previously my program has no such problem, not too sure what happened...

hello, i meet the same problem, what can i do to solve it?
