### ISSUE TITLE
conformer asr model meets bottleneck on larger dataset

### ISSUE THREAD

**Issue by keshawnhsieh** [espnet/espnet#3007]
By doing experiment on internal English asr dataset (~3000h), we see conformer based end-to-end model doesn't perform better than vanilla transformer based model.

Does anyone see such similar phenomenon?

**Comment by sw005320** [comment]
The conformer model is more difficult to tune.
If it is well tuned, you may get better performance than transformer, but I believe the difference is not very large.

**Comment by keshawnhsieh** [comment]
Which part should I concern when tuning conformer model?

As you mentioned some tips in [paper](https://arxiv.org/abs/2010.13956) of recent developments on espnet with conformer, LR and Conv kernel size are two main points, however I don't see any special settings in Aishell and LibriSpeech recipe related with LR.

**Comment by sw005320** [comment]
LR: https://github.com/espnet/espnet/blob/master/egs/aishell/asr1/conf/tuning/train_pytorch_conformer_kernel31.yaml#L36
Conv kernel size: https://github.com/espnet/espnet/blob/master/egs/aishell/asr1/conf/tuning/train_pytorch_conformer_kernel31.yaml#L48

We did not record such information in the final config to make the recipe simple, but if you check the conformed training config of the other recipe, you can find some difference, which comes from our internal tuning.
