### ISSUE TITLE
got error: Keys are mismatched.

### ISSUE THREAD

**Issue by wac81** [espnet/espnet#3025]
run this code:
`./run.sh --stage 7    --tts_exp exp/tts_train_raw_phn_pypinyin_g2p_phone  --inference_args "--use_teacher_forcing true"    --test_sets "tr_no_dev dev eval1"`

I got the error:

RuntimeError: Keys are mismatched. Text files are not sorted or not having the same keys at L2

 which files do i check?

**Comment by kan-bayashi** [comment]
Not sure from the log. You can try: 
```
utils/fix_data_dir.sh dump/raw/tr_no_dev
utils/fix_data_dir.sh dump/raw/dev
utils/fix_data_dir.sh dump/raw/eval1
```
