### ISSUE TITLE
 how to fix special layers(load pre-trained model and don't update it) in espnet2 ?

### ISSUE THREAD

**Issue by shanguanma** [espnet/espnet#3031]
When I am working on the joint enhanced model and asr model based on espnet2,  But I want to load a pre-trained enhanced model and fixed it, and only update the parameter of the ASR model. I put the below code into the trainer.py.
```
for module in dp_model.modules():
            #logging.info(f"dp_model contain module is {module}")
            if module._get_name() == 'TFMaskingNet1':  #(this is my modified enhanced model)
                logging.info(f"layer: {module._get_name()}")
                for param in module.parameters():
                    param.requires_grad_(False)
                    logging.info(f"param should be no grad , {param}")
```
I compared the log between the enhanced module output of the joint model and the pure output of the enhanced model, The results are different. I don't know that whether it is correct or not. Could you help me? Thanks

**Comment by kamo-naoyuki** [comment]
`--freeze_param`:
https://espnet.github.io/espnet/espnet2_training_option.html#freeze-parameters
