### ISSUE TITLE
gpu_id should be set to empty when cpu used

### ISSUE THREAD

**Issue by ramon-astudillo** [espnet/espnet#304]
Right now is set to [-1] e.g.

https://github.com/espnet/espnet/blob/974ade39bda50b5c8f88548a83748e29f005259b/src/asr/asr_pytorch.py#L257

This leads to false number of gpus used in places where the init function takes argument`device=gpu_id` and has
```
self.num_gpu = len(device)
```
Example: `PytorchSeqUpdaterKaldi`

https://github.com/espnet/espnet/blob/974ade39bda50b5c8f88548a83748e29f005259b/src/asr/asr_pytorch.py#L105

setting `gpu_id=[]` would solve this, although I can not track all the the code instances where this is used.

**Comment by kan-bayashi** [comment]
This `num_gpu` is used only for the scaling of loss/gradient in the case of multi-gpu.
So it causes no problem even if we use cpu.
