### ISSUE TITLE
Default "cudnn_deterministic=true" may make the training extremely slow in specific environment. 

### ISSUE THREAD

**Issue by LiChenda** [espnet/espnet#3041]
Edited:
I don't think this is a bug, somehow the system tag this issue with `Bug` automatically and I don't know how to remove it.

**Describe the bug**

Hi, when I use ESPnet2-SE to train a speech enhancement model with pytorch 1.7.1 and cudnn 8005, I have observed that the `ConvTranspose1d` and `torch.nn.functional.conv_transpose1d` become 10 times slower (In the jupyter test demo below) with  "cudnn_deterministic=true" . This does not happen when I use torch 1.5.0.

By default, `torch.backends.cudnn.deterministic` is `Flase` in pytorch. And ESPnet2 makes it `True` to keep the training reproducible. In the pytroch official documentation, they have some [notes](https://pytorch.org/docs/stable/generated/torch.nn.ConvTranspose1d.html) for the computation cost. 

Most models in ESPnet will not be influenced because they don't have or have fewer `ConvTranspose1d` layers.
However, in my real application for an SE model with many `ConvTranspose1d` layers, the total forward time becomes about 100 times slower.

I think this is not a bug and we can avoid this by set "cudnn_deterministic=false" in the training configuration. 
Somehow, it looks very strange at the very beginning when I encountered the extremely slow training speed.  I debuged the forward model and backward functions in Jupyter notebook and everything is Okey, when the model is trained with the whole framework, it becomes 100 times slow again. And finally I find the "cudnn_deterministic" issue.

Maybe we can raise some warning for the "cudnn_deterministic" parameter in the training log to remind users for this speed issue ?

**Basic environments:**
- OS information: Linux 5.4.0-58-generic # 64-Ubuntu SMP Wed Dec 9 08:16:25 UTC 2020 x86_64
- python version: `3.8.8 (default, Feb 24 2021, 21:46:12)  [GCC 7.3.0]`
- espnet version: `espnet 0.9.8`
- pytorch version: `pytorch 1.7.1`

**Environments from `torch.utils.collect_env`:**
```
OS: Ubuntu 20.04.2 LTS (x86_64)
GCC version: (Ubuntu 8.4.0-3ubuntu2) 8.4.0
Clang version: Could not collect
CMake version: version 3.16.3

Python version: 3.8 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: GeForce RTX 3090
Nvidia driver version: 460.56
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.2
[pip3] pytorch-ranger==0.1.1
[pip3] pytorch-wpe==0.0.0
[pip3] torch==1.7.1
[pip3] torch-complex==0.2.0
[pip3] torch-optimizer==0.1.0
[pip3] torchaudio==0.7.2
[pip3] torchvision==0.8.2
[conda] blas                      1.0                         mkl    defaults
[conda] cudatoolkit               11.0.221             h6bb024c_0    defaults
[conda] mkl                       2020.2                      256    defaults
[conda] mkl-service               2.3.0            py38he904b0f_0    defaults
[conda] mkl_fft                   1.3.0            py38h54f3939_0    defaults
[conda] mkl_random                1.1.1            py38h0573a6f_0    defaults
[conda] numpy                     1.19.2           py38h54aff64_0    defaults
[conda] numpy-base                1.19.2           py38hfa32c7d_0    defaults
[conda] pytorch                   1.7.1           py3.8_cuda11.0.221_cudnn8.0.5_0    pytorch
[conda] pytorch-ranger            0.1.1                    pypi_0    pypi
[conda] pytorch-wpe               0.0.0                    pypi_0    pypi
[conda] torch-complex             0.2.0                    pypi_0    pypi
[conda] torch-optimizer           0.1.0                    pypi_0    pypi
[conda] torchaudio                0.7.2                    pypi_0    pypi
[conda] torchvision               0.8.2                py38_cu110    pytorch
```

**Task information:**
 - Task: [Enh]
 - Recipe: [ - ]
 - ESPnet2

**To Reproduce**

Activate the ESPnet python envrionment and test the following code in jupyter notebook:

```
import torch
import torch.nn as nn
import time
print(torch.backends.cudnn.version())
print(torch.__version__)
```
8005
1.7.1

```
tpconv = nn.ConvTranspose1d(256, 256, stride=15, kernel_size=33).cuda()
x = torch.ones((2, 256,  10 * 1000)).cuda()
```

```
torch.backends.cudnn.deterministic = False
torch.cuda.synchronize()
start = time.time()
a = 0
for i in range(100):
    a += tpconv(x)
torch.cuda.synchronize()
end = time.time()
print(f"time cost: {end - start}")

```
 time cost: 1.2274892330169678

```
torch.backends.cudnn.deterministic = True
torch.cuda.synchronize()
start = time.time()
a = 0
for i in range(100):
    a += tpconv(x)
torch.cuda.synchronize()
end = time.time()
print(f"time cost: {end - start}")
```
time cost: 11.568689823150635

**Comment by sw005320** [comment]
Thanks, @LiChenda!
Of course, the best solution is that it should be fixed by PyTorch since the deterministic option is useful for debugging, but let us think of making deterministic false as default given this.

**Comment by kamo-naoyuki** [comment]
Thank you.
Could you compare the time cost of 1.5.0 with 1.7.1.  If it's significantly slower than 1.5.0, it might be a bug of pytorch.

**Comment by LiChenda** [comment]
Hi, I have made the test. 
In `1.5.0`, using `deterministic` is also slower than not using it, but it looks more acceptable than that in `1.7.1`.

Here I copy the test code and results : 

```
import torch
import torch.nn as nn
import time
print(torch.backends.cudnn.version())
print(torch.__version__)
```
7603
1.5.0

```
tpconv = nn.ConvTranspose1d(256, 256, stride=15, kernel_size=33).cuda()
x = torch.ones((2, 256,  10 * 1000)).cuda()
```

```
torch.backends.cudnn.deterministic = False
torch.cuda.synchronize()
start = time.time()
a = 0
for i in range(100):
    a += tpconv(x)
torch.cuda.synchronize()
end = time.time()
print(f"time cost: {end - start}")
```
time cost: 1.5392048358917236

```
torch.backends.cudnn.deterministic = True
torch.cuda.synchronize()
start = time.time()
a = 0
for i in range(100):
    a += tpconv(x)
torch.cuda.synchronize()
end = time.time()
print(f"time cost: {end - start}")
```
time cost: 3.6717991828918457

**Comment by kamo-naoyuki** [comment]
Thanks. I got similar result as you. Maybe, latest cudnn has some problem. It's better to report at pytorch issue, I think.

Anyway, we probably should change the default to False. This is serious difference even if using old cudnn.

**Comment by sw005320** [comment]
@yuyfujit, you may be interested in this discussion.
The reason we did not observe good speed improvement of light-weight/dynamic conv may come from this.
