### ISSUE TITLE
torch.matmul in AttLoc.forward requires much more GPU memory

### ISSUE THREAD

**Issue by kan-bayashi** [espnet/espnet#305]
I found that `c = torch.matmul(w.unsqueeze(1), self.enc_h).squeeze(1)` in `AttLoc.forward` requires much more memory.
https://github.com/espnet/espnet/blob/master/src/nets/e2e_asr_attctc_th.py#L797-798

I confirmed that this causes OOM error when using ljspeech TTS recipe.

- Original version
batchsize 32 -> working

- Matmul version 
batchsize 32 -> OOM error
batchsize 25 -> OOM error
batchsize 20 -> OOM error
batchsize 16 -> working

I think we should avoid the use of matmul version.

**Comment by ShigekiKarita** [comment]
I agree. Could you revert it?

**Comment by ShigekiKarita** [comment]
Does it only appear in CPU mode?

**Comment by kan-bayashi** [comment]
Merged.
