### ISSUE TITLE
why not use larger batch size while training transformer lm?

### ISSUE THREAD

**Issue by keshawnhsieh** [espnet/espnet#3051]
According to the conf in librispeech [recipe](https://github.com/espnet/espnet/blob/master/egs/librispeech/asr1/conf/tuning/lm_transformer.yaml), it cost 60days for 50 epochs. Obviously the batch size can be larger than 32 and thus the training time should be much shorter.

What's the concern here to keep a relatively small batch size when training transformer lm?

**Comment by kamo-naoyuki** [comment]
Larger batch size is used in the following recipe.

https://github.com/espnet/espnet/blob/master/egs2/librispeech/asr1/conf/tuning/train_lm_transformer2.yaml
