### ISSUE TITLE
About run environment 

### ISSUE THREAD

**Issue by shanhaidexiamo** [espnet/espnet#3052]
Sorry, I would like to ask if ESPnet supports 3090GPU. I tried Pytorch1.7.1 + Cuda10.1 and found that the code does not work

**Comment by Fhrozen** [comment]
I tried RTX 3060Ti with Pytorch 1.7.1 + CUDA 11.0 and found no problem

**Comment by shanhaidexiamo** [comment]
Does espnet support cuda11.0?

**Comment by shanhaidexiamo** [comment]
> I tried RTX 3060Ti with Pytorch 1.7.1 + CUDA 11.0 and found no problem

Does espnet support cuda11.0?

**Comment by Fhrozen** [comment]
yes, pretty well:

```
espnet/tools$ python check_install.py 
[x] python=3.7.9 (default, Aug 31 2020, 12:42:55)  [GCC 7.3.0]

Python modules:
[x] torch=1.7.1
[x] torch cuda=11.0
[x] torch cudnn=8005
[x] torch nccl
[x] chainer=6.0.0
[ ] chainer cuda
[ ] chainer cudnn
[ ] cupy
/utils/python3.7/envs/nar/lib/python3.7/site-packages/torchaudio/backend/utils.py:54: UserWarning: "sox" backend is being deprecated. The default backend will be changed to "sox_io" backend in 0.8.0 and "sox" backend will be removed in 0.9.0. Please migrate to "sox_io" backend. Please refer to https://github.com/pytorch/audio/issues/903 for the detail.
  '"sox" backend is being deprecated. '
[x] torchaudio=0.7.2
[x] torch_optimizer=0.1.0
[ ] warpctc_pytorch
[ ] warprnnt_pytorch
[ ] warp_rnnt
[ ] chainer_ctc
[ ] pyopenjtalk
[ ] kenlm
[ ] mmseg
[x] espnet=0.9.7

Executables:
[ ] sclite
[x] sph2pipe
[ ] PESQ
[ ] BeamformIt
```

**Comment by shanhaidexiamo** [comment]
> yes, pretty well:
> 
> ```
> espnet/tools$ python check_install.py 
> [x] python=3.7.9 (default, Aug 31 2020, 12:42:55)  [GCC 7.3.0]
> 
> Python modules:
> [x] torch=1.7.1
> [x] torch cuda=11.0
> [x] torch cudnn=8005
> [x] torch nccl
> [x] chainer=6.0.0
> [ ] chainer cuda
> [ ] chainer cudnn
> [ ] cupy
> /utils/python3.7/envs/nar/lib/python3.7/site-packages/torchaudio/backend/utils.py:54: UserWarning: "sox" backend is being deprecated. The default backend will be changed to "sox_io" backend in 0.8.0 and "sox" backend will be removed in 0.9.0. Please migrate to "sox_io" backend. Please refer to https://github.com/pytorch/audio/issues/903 for the detail.
>   '"sox" backend is being deprecated. '
> [x] torchaudio=0.7.2
> [x] torch_optimizer=0.1.0
> [ ] warpctc_pytorch
> [ ] warprnnt_pytorch
> [ ] warp_rnnt
> [ ] chainer_ctc
> [ ] pyopenjtalk
> [ ] kenlm
> [ ] mmseg
> [x] espnet=0.9.7
> 
> Executables:
> [ ] sclite
> [x] sph2pipe
> [ ] PESQ
> [ ] BeamformIt
> ```

OK，nice . Thank you  very much !
