### ISSUE TITLE
Question on the espnet1 ASR decoding mechanism

### ISSUE THREAD

**Issue by wenjie-p** [espnet/espnet#3067]
Hi,

According to the paper `Hybrid CTC/Attention Architecture for End-to-End Speech Recognition`, the decoding mechanism seems to be very complicated. And my understanding is that:

`espnet` decoding = CTC/Attention Hybrid + LM, where the CTC/Attention can be two-pass or one-pass decoding, and the LM is integrated by shallow fusion.

Please correct me if I am wrong. My question is that how to decide the decoding mechanism for CTC/Attention, i.e. one-pass or two-pass, is there a switch to specify that? 

Thanks in advance!

**Comment by sw005320** [comment]
All of our implementations are one-pass and score combinations of attention, CTC, and LM are done during beam search.
We don't officially provide two-pass decoding

**Comment by wenjie-p** [comment]
Hi,

Sorry to reopen this issue, but I have another related question:

 I have noticed that word-based rnnlm can be enabled for joint decoding by passing `--word-rnnlm` option to `espnet/espnet/bin/asr_recog.py`. However, I didn't see any option explicitly to enable word-based ngram decoding. I pass the word-ngram model directly but found it perform worse than word-piece ngram. Is there a switch for me to specify whether word or wp based ngram?

**Comment by sw005320** [comment]
Please use the exactly same word-piece for n-gram by following https://github.com/espnet/espnet/blob/master/egs/aishell/asr1/run.sh#L192-L193 and https://github.com/espnet/espnet/blob/master/egs/aishell/asr1/run.sh#L266

We don't support a word-based n-gram.

**Comment by wenjie-p** [comment]
Thanks for your reply!

**Comment by Dabuk** [comment]
has this changed since March ?
I'm working on shallow fusion of external word based lm with transducer decoder.
Is this possible now ?

**Comment by sw005320** [comment]
It is possible with k2 but with CTC (not transducer)
https://github.com/espnet/espnet/tree/master/egs2/librispeech/asr1#ctc-decoding-with-nbest-rescoring-from-decoder-and-lm-using-k2

**Comment by monicasunkara** [comment]
Is there any plan for supporting ngram word level lm into transducer decoding?
