### ISSUE TITLE
Question on chunk shift in ChunkIterFactory.build_iter()

### ISSUE THREAD

**Issue by hchung12** [espnet/espnet#3072]
In the code, shift width is calculated as a ratio of utterance length as follows:
S = int(L * self.chunk_shift_ratio)

Shouldn't shift width be calculated as a ratio of chunk length like below ?
S = int(W * self.chunk_shift_ratio)

**Comment by kamo-naoyuki** [comment]
Oh, thanks! You are right. I'll fix.
@ftshijt You may use ChunkIterFactory? This is a serious bug, sorry.

**Comment by ftshijt** [comment]
> Oh, thanks! You are right. I'll fix.
> @ftshijt You may use ChunkIterFactory? This is a serious bug, sorry.
> (though I think it doesn't change the training result)

Oh, this should be a problem. Thanks for letting me know. For current diarization training, I'm setting the shift to 0, so it should not have problems with that

**Comment by hchung12** [comment]
In  the _generate_mini_batches() function in chunk_iter_factory.py, batch data is constructed like below
        while len(id_list) >= bs:

However, if len(id_list) is smaller than batch size, empty batch data is returned.
It should be modified something like below.
        for _ in range(0, len(id_list), bs):
