### ISSUE TITLE
csmsc/tts1   HTTP request sent, awaiting response... 403 Forbidden

### ISSUE THREAD

**Issue by gbaian10** [espnet/espnet#3075]
As title, I can't start a brand new CSMSC training.

**Comment by kan-bayashi** [comment]
Now CSMSC is not free.
You need to apply the form to get the dataset.

**Comment by gbaian10** [comment]
I have CSMSC data, but I don't know how to skip Download step and conform to the format.

**Comment by kan-bayashi** [comment]
You can follow this script.
https://github.com/espnet/espnet/blob/master/egs/csmsc/tts1/local/data_download.sh

**Comment by kan-bayashi** [comment]
I added the instruction in #3109.
