### ISSUE TITLE
asr.sh fails in stage 4 if we have reco2dur

### ISSUE THREAD

**Issue by sw005320** [espnet/espnet#3078]
**Describe the bug**
When we have `reco2dur` in the data directory, `asr.sh` fails in stage 4 with the following error message:
```
2021-03-13T09:39:01 (asr.sh:527:main) Stage 4: Remove long/short data: dump/raw/org -> dump/raw
apply_map.pl: undefined key AUD0000000003 in dump/raw/train/utt_map
```
It seems that `apply_map.pl` tried to use the recording ID (`AUD0000000003` in the above case) instead of the segment ID (`-AUD0000000003_S0000001` in the above case)

**Basic environments:**
- OS information: Linux 3.10.0-862.11.6.el7.x86_64 #1 SMP Tue Aug 14 21:49:04 UTC 2018 x86_64
- python version: `3.8.5 (default, Sep  4 2020, 07:30:14)  [GCC 7.3.0]`
- espnet version: `espnet 0.9.8`
- pytorch version: `pytorch 1.7.1`
- Git hash: `d72e8d7c442882b92541b8cac0d95f2cf51fa254`
  - Commit date: `Fri Mar 12 22:14:43 2021 -0500`

**Task information:**
 - Task: ASR 
 - Recipe: malash and gigaspeech https://github.com/espnet/espnet/pull/3077
 - ESPnet2

**To Reproduce**
If we have `reco2dur` in `data/***/***/`, this happens in the stage 4.
In the malash recipe, I exclude using `reco2dur` in the data preparation.
In the gigaspeech recipe, I'm planning to remove `reco2dur` in the data preparation.
But this is not the perfect solution.
Also, this is not easy to figure out this issue from the current error logs only.

**Error logs**
```
2021-03-13T09:39:01 (asr.sh:527:main) Stage 4: Remove long/short data: dump/raw/org -> dump/raw
apply_map.pl: undefined key AUD0000000003 in dump/raw/train/utt_map
```

**Comment by peter-yh-wu** [comment]
+1 Experienced this bug as well
