### ISSUE TITLE
Questions about training conformer on librispeech using egs2

### ISSUE THREAD

**Issue by Shengqiang-Li** [espnet/espnet#3084]
I have only 4 GPUS in my server，but the default config need 16 GPUS，how can i modify the config file so that i can train conformer on librispeech using egs2？

**Comment by kamo-naoyuki** [comment]
https://espnet.github.io/espnet/espnet2_training_option.html#gradient-accumulating

There are two ways.

- Halve batch_bins and double accum_grad as you need.
- torch.utill.checkpoint: You need to modify the model to use it.

**Comment by Shengqiang-Li** [comment]
Thank you very much. I have changed the batch_bins to 1/4 of default set, and set the accum_grad to 4 times of the default set.  Is that right?

**Comment by Shengqiang-Li** [comment]
The batch type in egs2 is numel, is the batchsize unified for each iteration? Can i change the batch_bins and accum_grad and keep batch_bins*accum_grad same as original value?

**Comment by Shengqiang-Li** [comment]
Thank you very much.
