### ISSUE TITLE
Bad output for asr inference for 8 KHz input audio

### ISSUE THREAD

**Issue by Arafat4341** [espnet/espnet#3086]
I am trying `kan-bayashi/csj_asr_train_asr_transformer_raw_char_sp_valid.acc.ave` pre-trained model for transcribing japanese speech.

I am getting better results for a 16000 sample rate, 16 bit, mono input.
But I am getting terrible results for an actual 8000 Hz 16 bit mono input. No matter if I convert the audio into 16 KHz or not, I always get same output.

Is there any way to improve the quality for the input audio that is originally of 8 KHz sample rate?
Thanks in advance.

**Comment by sw005320** [comment]
The model would not be robust for such changes.
So, I recommend you retrain the CSJ model with 8kHz downsampled audios (or retrain it with first downsampling the audio to 8kHz and then upsampling it to 16 kHz by sox).

**Comment by Arafat4341** [comment]
Unfortunately I cannot afford the CSJ dataset! Thanks for the advice though! Now I know why I was getting poor results!
