### ISSUE TITLE
Positional encoding in conformer subsampling layer 

### ISSUE THREAD

**Issue by kevinghst** [espnet/espnet#3088]
Hi,

First of all, thanks for the great work!

I am currently trying to use your [Conformer Encoder](https://github.com/espnet/espnet/blob/master/espnet2/asr/encoder/conformer_encoder.py):

I notice that as in the original Conformer paper, it uses relative position in the [RelPositionMultiHeadedAttention](https://github.com/espnet/espnet/blob/de0a3f5e69e691fd069ee4381873a784e6ff9d56/espnet/nets/pytorch_backend/transformer/attention.py#L212) module.

But I also notice that the positional encoding is also included in the [Conv2dSubSampling](https://github.com/espnet/espnet/blob/de0a3f5e69e691fd069ee4381873a784e6ff9d56/espnet/nets/pytorch_backend/transformer/subsampling.py#L42) layer.

Why do you include positional information in the Conv Subsampling process if it is already taken care of in the attention layers?

Thanks,
K.

**Comment by sw005320** [comment]
Thanks for your question.
I see your point.
@pengchengguo, did you test it with and without RPE in the Conv2dSubSampling layer?

**Comment by pengchengguo** [comment]
Hi @kevinghst,

Thanks so much for your interest.

The class `Conv2dSubSampling` includes two main modules, which are a multi-layer `Conv2d` to subsample the input frames and a `PositionalEncoding` to compute some positional encodings. In other words, this class has two different functions. For Transformer models, it will return the scaled summation of  `x` and `pos_emb`, while for Conformer models, it will return these two tensors separately and the `pos_emb` will be used in the `RelPositionMultiHeadedAttention` module.

Some open-source implementations may regard the subsampling layer and positional encoding layer as two different modules, while we integrate them into a single module `Conv2dSubSampling`.

We also have some experiments to compare the Conformer model w/ or w/o RPE. Here are some results on Aishell-1 dataset.


Model | Dev | Test
-- | -- | --
Conformer + SpecAug + w/ RPE | 4.6 | 5.1
Conformer + SpecAug + w/o PRE | 4.8 | 5.5

**Comment by kevinghst** [comment]
Interesting. Thanks!
