### ISSUE TITLE
Make attention plots during ESPNet1 TTS decoding

### ISSUE THREAD

**Issue by szmmm** [espnet/espnet#3093]
Hello, I am trying to use the ESPNet1 Tacotron 2  for syngthesis, and I would like to do some investigations on the attention during decoding. I am using this old version of [ESPNet](https://github.com/creatorscan/espnet) so there might be some differences in the code (I fixed the plot bug mentioned in [#1761](https://github.com/espnet/espnet/pull/1761) )

I understand that during training some attention plots of selected `dev` data utterances will be generated and put in the `att_wt` directory along with the model snapshots, etc. 

May I ask which part of the code should I modified (sorry if this is too broad) in order to produce attention plots whenever I decode an utternace, using a given model snapshot? 
Plese let me know if my question is clear, and some explanation would be much appreciated, thank you!

**Comment by kan-bayashi** [comment]
Current decoding script support the saving of attention weight.
You can refer this part.
https://github.com/espnet/espnet/blob/96e6eb97bacb428d9979661725657b5c38a17dee/espnet/tts/pytorch_backend/tts.py#L570-L748
