### ISSUE TITLE
using arpabet during inference 

### ISSUE THREAD

**Issue by sciai-ai** [espnet/espnet#3097]
Hi I was wondering if it's possible to use arpabet or cmu symnols during inference so that we can control the pronunciations of different words? for example. 

Does the g2p_en model supports this

I tried this in the inference notebook but the model still produce {HH AW1 S S T AH0 N}  as individual letters

```
x= 'Turn left on {HH AW1 S S T AH0 N} Street.'
# synthesis
with torch.no_grad():
    start = time.time()
    wav, c, *_ = text2speech(x)
    wav = vocoder.inference(c)
rtf = (time.time() - start) / (len(wav) / fs)
print(f"RTF = {rtf:5f}")

# let us listen to generated samples
from IPython.display import display, Audio
display(Audio(wav.view(-1).cpu().numpy(), rate=fs))


```

**Comment by sciai-ai** [comment]
can anyone please help, I believe that the espnet tacotron is trained on english cleaners and phoneme based using g2p, the symbols (tokens) are also listed in the config file, such as, AH0, IY etc. Is it possible to use these symbols to get a required pronunciation during inference?

**Comment by kan-bayashi** [comment]
You can build such g2p by yourself.
Current `g2p_en` function is very simple.
https://github.com/espnet/espnet/blob/bed4d4dc7df33bbfa5e2295612e556d5d9fa11e0/espnet2/text/phoneme_tokenizer.py#L99-L107
You can modified this to accept your desired input.

**Comment by sciai-ai** [comment]
@kan-bayashi  thank you for your kind reply. I am getting good results with the tacotron + PWG.
However some words pronunciations is not very good. I can try to imprve the G2P mode too.

But I believe the tacotron espnet is trained on phoneme symbols which are generated in the config.yaml file. Should not the model support phoneme input text instead of character text? This will allow directly changing the phoneme in a word to make the model output a certain pronunication.

**Comment by sciai-ai** [comment]
In Espnet1 (egs1) I am able to use the phn  model which allows me to specify Phonemes during inference.
`x = 'HH AW1 S S T AH0 N .'
 
This is not possible in ESPNET2(eg2) PHN model. Can i get the same functionality for the ESPNET2(eg2) PHN model?

**Comment by kan-bayashi** [comment]
You can do it by changing `g2p=none`.
You can edit `g2p` option in the config of the pretrained model.
See https://github.com/espnet/espnet/tree/master/egs2/TEMPLATE/tts1#supported-text-frontend

**Comment by sciai-ai** [comment]
@kan-bayashi thank you, this is a great tool for TTS development. I will try this and close this issue for now

**Comment by sciai-ai** [comment]
@kan-bayashi I tried using g2p=none in config.yaml of a pretrained model. I get this error

![image](https://user-images.githubusercontent.com/52277510/124909654-4e769600-e01d-11eb-98d2-9aa1b5031270.png)

**Comment by kan-bayashi** [comment]
If you directly edit `config.yaml`, use `g2p: null`.
