### ISSUE TITLE
volume questions about tts results

### ISSUE THREAD

**Issue by animebing** [espnet/espnet#3098]
When I use the tts model trained on csmsc dataset with fastspeech2 , I have following issues
1. when do tts on a long sentence, I will split it into several short sentences, then do tts on each short sentence, and finally concatenate short audio to a long audio. In the long audio, I find the volume of the beginning of next sentence is a little larger than previous sentence, which is a little strange. I don't know this phenomenon is introduced by training data or the model.

**Comment by unilight** [comment]
Can you give some samples?

**Comment by animebing** [comment]
@unilight Thanks for your response. One audio sample is in the attachment, which is composed by three short audio. The text used here is ["作为本地生活服务领域的两大寡头。", "当下美团和饿了么的竞争早就不止于最初的外卖服务。", "而是涉及到本地生活服务的众多维度。"]. And the volume in 0:03 and 0:07 (beginning of new sentence) is a little larger than previous sentence.

[1616402826.7082512.zip](https://github.com/espnet/espnet/files/6180706/1616402826.7082512.zip)

**Comment by unilight** [comment]
@animebing I opened the file you attached with Audacity, but I don't really observe the issue you mentioned.
![image](https://user-images.githubusercontent.com/11516009/112029379-24838b80-8b74-11eb-98a9-349c210d563a.png)

**Comment by animebing** [comment]
@unilight Thanks for your response, maybe the sample I choose is not very representative. In order to clarify the problem, I synthesis 600 short audios and compute the energy of each audio using the method provided in espnet2, then split the energy into 10 parts evenly along frames and compute mean energy in each part, finally average each part in all audios and I get the following figure. From the figure, we can find the energy of the beginning is a litter larger than the following parts, which is what I feel confused about.

![valid_energy_10](https://user-images.githubusercontent.com/19849456/112123946-c64ebb00-8bfc-11eb-89a4-cbbac4bcd4c8.png)

**Comment by unilight** [comment]
Hmm, interesting. Have you plotted the same figure for the training data? Maybe such tendency (larger volume at the beginning of the sentence) is the nature of the training data and the model just learnsed it.

**Comment by animebing** [comment]
Yes, you are right, I do the same operation on 20% of training data, which gives the same result as following figure.

![valid_energy_train](https://user-images.githubusercontent.com/19849456/112133942-2ea29a00-8c07-11eb-8df1-79e91566ed23.png)

**Comment by kan-bayashi** [comment]
This is interesting.
Since the fastspeech2 models the energy, the model can learn such a tendency.
A little bit complicated, but you can modify or limit the energy of each token if you dig into the energy predictor part.
