### ISSUE TITLE
Question about sentencepiece versioning and speed

### ISSUE THREAD

**Issue by AdolfVonKleist** [espnet/espnet#3099]
Is the espnet configuration for [sentencepiece](https://github.com/google/sentencepiece) pinned to a lower version due to performance issues with later versions of sentencepiece?

I noticed that if I install the latest version of sentencepiece via pip, or build it from source that the `unigram` type model is prohibitively, effectively unusably, slow to train.  It runs for hours and hours and never does anything.  I couldn't figure out why it seemed so much slower until I realized that espnet is pinning to a much older version:

https://github.com/espnet/espnet/blob/96e6eb97bacb428d9979661725657b5c38a17dee/setup.py#L36

after installing `0.1.86` in a separate venv, `python -m pip install sentencepiece==0.1.86` and running training again, the speed again came right back to the espnet installation.  So is this a known issue, and the reason for the pinning?  Has anyone looked at why it is so much slower?  The difference is really dramatic for more than trivially small vocabularies.  Training effectively stops at the `Extracting frequent sub strings...` step.

**Comment by sw005320** [comment]
Thanks for the report.
The reason for using the old version is for stable installation and leave it as it is https://github.com/espnet/espnet/issues/832

@jnishi, do you have some comments about it?

**Comment by AdolfVonKleist** [comment]
I don't know about the integration issues, but I am fairly sure that I found the issue related to the training time degradation, and now submitted a possible fix:
- https://github.com/google/sentencepiece/pull/642

this can be closed.

**Comment by AdolfVonKleist** [comment]
My pull request on this topic was merged today:
 - google/sentencepiece#642

I think this conclusively resolves the issue [the unigram model training should be fast again as well].
