### ISSUE TITLE
Memory leaking in tts_pytorch

### ISSUE THREAD

**Issue by kan-bayashi** [espnet/espnet#310]
I found that `tts_pytorch` has memory leaking problem.
But I have not yet found the reason.

**Comment by ShigekiKarita** [comment]
@kan-bayashi Do you still have this issue? Maybe I can help now because I'm trying some TTS recipes recently.

**Comment by kan-bayashi** [comment]
Thank you @ShigekiKarita. I need your help.
Yes, tts recipe still has memory leaking issue.
I’ve tried several methods:
- Use `gc.colloct()` in the end of `update_core`
- removal of `batch` variable  in `update_core`
But there is no effect, memory is still leaking...

**Comment by kan-bayashi** [comment]
@ShigekiKarita Did you get any idea?

**Comment by ShigekiKarita** [comment]
Thanks for ping. I have done several experiments through this month with
- egs: librispeech/tts1, ljspeech/tts1
- pytorch: 0.4.1
- python: 3.6

Strangely, I have **never** seen MemoryError. If you might use Python2.7 (I remember), please try Python 3 instead.

**Comment by kan-bayashi** [comment]
Thanks @ShigekiKarita.
I will try to use python3.

**Comment by ShigekiKarita** [comment]
And also I found a strange line here
https://github.com/espnet/espnet/blob/f417aee2fc7b97155ae83392cfd31e8c724027cd/src/tts/tts_pytorch.py#L260-L266

I do not believe that chainer.iterators.MultiprocessIterator has maxtasksperchild in chainer 4.4.0? I'm using this without maxtasksperchild instead. What `chainer.__version__` are you using?

http://docs.chainer.org/en/stable/reference/generated/chainer.iterators.MultiprocessIterator.html

**Comment by ShigekiKarita** [comment]
Oh this one https://github.com/chainer/chainer/pull/4972?

**Comment by kan-bayashi** [comment]
Yes, maybe that's one.
Now we use @jnishi patched chainer.
See https://github.com/espnet/espnet/blob/master/tools/prefetch.patch
