### ISSUE TITLE
Question: importing a trained ESPnet ASR model to C++

### ISSUE THREAD

**Issue by hyung8758** [espnet/espnet#3103]
Hello all.

I saw a plan for updating torch script support in Development plan note v0.10.0 and I wonder when it will be updated.
I trained a few ASR models based on transformer networks and I would like to import this model in C++.
Or is there anyone who knows how to import the trained ESPnet ASR model in C++ instead of using torch script, then please let me know.

Thank you in advance.

**Comment by sw005320** [comment]
I just added a feature request tag.
Indeed it is useful, but I personally don't have such experience.
I heard that some of them already tried it, and it would be great if they give us their experience about it.

**Comment by hyung8758** [comment]
Thanks! it would be a very useful feature so I'm looking forward to it.
