### ISSUE TITLE
chinese tts with some english words

### ISSUE THREAD

**Issue by animebing** [espnet/espnet#3105]
How to do chinese tts for texts with some english words which is very common these days? There are some difficulties I have met:
1. there is not tts dataset with both chinese and english.
2. whether I can just use chinese tts model to do the work.

**Comment by mudong0419** [comment]
Any update? I have the same problem.

**Comment by kan-bayashi** [comment]
I don't know such a dataset.
One possibility is to 
- Concatenate English and Mandarin dataset
- Apply different G2P for English and Mandarin 
- Make a mixed token list (English phoneme + Mandarin phoneme)
- Train the multi-speaker model with concatenated dataset + mixed tokens

**Comment by animebing** [comment]
@mudong0419 I have not solved the problem, I just find a github repo [BigCiDian](https://github.com/speechio/BigCiDian) which can be used to combine chinese and english phoneme together.

**Comment by mudong0419** [comment]
@animebing Thanks for your information. I find a github [Multilingual_Text_to_Speech](https://github.com/Tomiinek/Multilingual_Text_to_Speech), but it not support English.

**Comment by anirpipi** [comment]
Hi..i am working on a similar problem like the one mentioned above..
i have trained a multispeaker Tacotron2 model with the concatenated dataset + mixed tokens; with 2 lang ids/spk ids.
i basically followed _https://github.com/espnet/espnet/tree/master/egs2/css10/tts1_
Now i want to do inference with the code switched text of both the languages e.g. **_APPLE 的新 MACBOOK PRO 真漂亮_**
But during inference , how to give the **spembds** and/or **spk ids** for such code switched text input

# synthesis
    wav = text2speech(x, spembs=spembs, sids=sids)["wav"]

Any help will be very grateful..
