### ISSUE TITLE
Error during finetuning: No such file: conf/tuning/finetune_tacotron2.yaml

### ISSUE THREAD

**Issue by rs-lin** [espnet/espnet#3111]
Hi,

I'm learning how to fine tune a pre-trained model following the example [here](https://github.com/espnet/espnet/blob/master/egs2/jvs/tts1/README.md) and I ran into this file not found issue during step 4.

Could you take a look at this?

Thanks!

**Comment by kan-bayashi** [comment]
Please refer jvs recipe one.
https://github.com/espnet/espnet/blob/master/egs2/jvs/tts1/conf/tuning/finetune_tacotron2.yaml
