### ISSUE TITLE
why is fastspeech2 different with paper？

### ISSUE THREAD

**Issue by yileld** [espnet/espnet#3113]
In the paper，length_regulator is after duration_predictor，but yours is after all three predictor. Is this better than original?

**Comment by kan-bayashi** [comment]
We use token-averaged embedding like fastpitch.
https://github.com/espnet/espnet/blob/bed4d4dc7df33bbfa5e2295612e556d5d9fa11e0/espnet2/tts/fastspeech2.py#L42-L54
See discussion in #2019
