### ISSUE TITLE
What does metrics like Corr mean?

### ISSUE THREAD

**Issue by kouohhashi** [espnet/espnet#3115]
Hi, I'm new here and I have question about the metrics.

There are metrics like "Snt", "Wrd", "Corr",  "Sub", "Del", "Ins", "Err", "S.Err" in egs2 sections.
I can guess "Snt" means number of sentences and "Wrd" means number of words.
"Err" is error rate  and "S.Err" seems to be sentence error rate.

But I don't know "Corr", "Sub", "Del", and "Ins".
What do these mean?

And what is "TER" means?

Could someone give me urls I can learn the metrics?

Thanks in advance.

**Comment by kalvinchang** [comment]
I believe Corr means # of correct words

TER refers to token error rate
