### ISSUE TITLE
fine tuning errors

### ISSUE THREAD

**Issue by rook86** [espnet/espnet#3121]
I want to perform a fine tuning by following https://github.com/espnet/espnet/tree/master/egs2/jvs/tts1 

However, when downloading a pretrained model, error message appears. What can I do to solve this issue. Here is the error message.

Download file from Zenodo: error: unrecognized arguments: --cache_dir kan-bayashi/jsut_tacotron2

**Comment by kan-bayashi** [comment]
Please write the whole command to reproduce errors.

**Comment by rook86** [comment]
> Please write the whole command to reproduce errors.

espnet_model_zoo_download --unpack true --cache_dir downloads kan-bayashi/jsut_tacotron2

this is the command that I wrote. This was done under espnet/egs2/jvs/tts1

**Comment by kan-bayashi** [comment]
Sorry, there is a typo.
Please tyr:
`espnet_model_zoo_download --unpack true --cachedir downloads kan-bayashi/jsut_tacotron2`

**Comment by rook86** [comment]
It worked! Thank you very much!
