### ISSUE TITLE
About transfer learning

### ISSUE THREAD

**Issue by rook86** [espnet/espnet#3124]
Hi, I want to execute transfer learning on my own dataset using the pretrained model that was trained by JVS. Is there any links that would be helpful? Also, what should I do to my own dataset to use it for transfer learning?

**Comment by kan-bayashi** [comment]
First, make your own recipe for your dataset.
https://github.com/espnet/espnet/tree/master/egs2/TEMPLATE/tts1#how-to-make-a-new-recipe-for-my-own-dataset
Then, follow the following the steps:
https://github.com/espnet/espnet/tree/master/egs2/TEMPLATE/tts1#how-to-finetune-the-pretrained-model
