### ISSUE TITLE
Difference in WERs from single vs multi-GPU

### ISSUE THREAD

**Issue by arsyed** [espnet/espnet#3125]
I've run the AMI recipe (espnet v1) using the RNN model `train_rnn.yaml` with `ngpu=1` and `ngpu=2`.  The WERs are quite different (27.1 vs 41.1  -- result output pasted below).  

Is this expected or is there any configuration I can tweak to improve the multiple GPU result?  I'd prefer to use multiple GPUs since it would help me run my experiments faster.  Thank you.

`ngpu=1`
```
| SPKR                         | # Snt # Wrd | Corr    Sub    Del    Ins    Err  S.Err |
| Sum/Avg                      |12612  89635 | 75.7   18.1    6.3    2.8   27.1   57.9 |
```

`ngpu=2`
```
| SPKR                         | # Snt # Wrd | Corr    Sub    Del    Ins    Err  S.Err |
| Sum/Avg                      |12612  89635 | 62.7   27.6    9.8    3.8   41.1   64.8 |
```

**Comment by kan-bayashi** [comment]
This is caused by the large batchsize.
If you used ngpu=2, the batch size will be doubled in ESPnet1.
In the case of RNN-based model, the large batch size caused less generalization performance.

**Comment by arsyed** [comment]
Thank you, I'll experiment with the batch size.
