### ISSUE TITLE
JSUT PWG model  loading error

### ISSUE THREAD

**Issue by sciai-ai** [espnet/espnet#3126]
I trained the JSUT PWG vocoder model using egs2 recipe. When i try to load the model `vocoder = load_model(vocoder_path).to("cuda").eval()
` 
I get the error

 [enforce fail at inline_container.cc:145] . PytorchStreamReader failed reading zip archive: failed finding central directory

When i used the pretrained JSUT PWG model from zoo i dont get this error. @kan-bayashi Can you please help? Than you

**Comment by kan-bayashi** [comment]
I cannot reproduce. Please provide the code to reproduce this error.

**Comment by sciai-ai** [comment]
@kan-bayashi the problem was happening as the device type was not consistent for vocoder and tacotron2 during inference, cpu vs gpu. Resolved and closing this.

**Comment by sciai-ai** [comment]
@kan-bayashi the problem was happening as the device type was not consistent for vocoder and tacotron2 during inference, cpu vs gpu. Resolved and closing this.
