### ISSUE TITLE
Transfer pre-trained CSJ model to JSUT asr training in ESPNet2

### ISSUE THREAD

**Issue by Arafat4341** [espnet/espnet#3127]
I want to train JSUT asr in espnet2. I want to load pre-trained CSJ model to transfer it's learning into JSUT ASR training. Basically I want to down-sample the audios of JSUT to 8K and train the transformer model but use the learning of pre-trained CSJ Transformer model.
Is there any way to do what I am trying to do?
Thanks in advance!

**Comment by Arafat4341** [comment]
@sw005320 Thanks a lot for your response. 
Actually I want to use the STT model in a situation where input audios will be 8K audios.

**Comment by sw005320** [comment]
I see.
Anyway please check https://github.com/espnet/espnet/issues/2667 for pre-training and fine-tuning.
