### ISSUE TITLE
Option to perform inference deterministically and disable dropout?

### ISSUE THREAD

**Issue by turian** [espnet/espnet#3130]
**Describe the bug**

[edited]

When running inference twice in the colab, different results are obtained. I am aware that one can use a manual seed https://github.com/espnet/espnet/issues/2647

I understand that for many TTS applications, non-determinism is value. However, there are also TTS experiments where determinism is important. I propose a configuration option that disables dropout and makes inference deterministic.

**Basic environments:**

https://colab.research.google.com/github/espnet/notebook/blob/master/espnet2_tts_realtime_demo.ipynb#scrollTo=tlGW6KjPwgKY

**Task information:**
 - Task: TTS
 - Recipe: Colab recipe
 - ESPnet2

**Comment by unilight** [comment]
Hi @turian, as answered by @kan-bayashi in #2647, the Tacotron 2 paper said "In order to introduce output variation at inference time, dropout with probability 0.5 is applied only to layers in the pre-net of the autoregressive decoder." So dropout is applied by default in Tacotron 2 and many other TTS models that used a prenet-like module. See section 2.2 in https://arxiv.org/pdf/1712.05884.pdf.

**Comment by turian** [comment]
@unilight Having read the section, I understand that there is a desire in many TTS applications for varying output.

Nonetheless, there are also TTS applications in which determinism is important. That is why I propose a "deterministic" option.

I am aware from #2647 that one can set a manual seed. It has worked for me in the colab, but not in other experiments I have done.

Overall, I would like a specific configuration to operate deterministically and without dropout.

[editing my original comment]

**Comment by unilight** [comment]
>  It has worked for me in the colab, but not in other experiments I have done.

why not? did you get non-deterministic values even when fixing the seed?

**Comment by turian** [comment]
@unilight I find that if a single phoneme changes, even with deterministic seed, a *lot* of the previous speech changes too, even if you re-use the duration. My main problem is I can't identify where the phonemes are in the speech based upon the duration: https://github.com/espnet/espnet/issues/3132

**Comment by sw005320** [comment]
I also want to second @turian for the deterministic **option**.
The deterministic option will be important for some investigation.
Of course, we can still keep the non-deterministic version as the default, and it would not affect the current users.
@kan-bayashi, could you consider it?

**Comment by kan-bayashi** [comment]
> @unilight I find that if a single phoneme changes, even with deterministic seed, a lot of the previous speech changes too, even if you re-use the duration. My main problem is I can't identify where the phonemes are in the speech based upon the duration: #3132

That is reasonable since the encoder encodes the whole of the input phoneme sequence.
If you change one of the input, the output should be changed.

**Comment by kan-bayashi** [comment]
> @kan-bayashi, could you consider it?

I can add the option like `manural_seed` to fix the outputs.

**Comment by turian** [comment]
@kan-bayashi would it also be possible to add --disable-dropout? I would be curious to hear what happens if dropout is disabled entirely. Thank you for the wonderful software.

**Comment by kan-bayashi** [comment]
@turian Maybe the following issue helps you.
https://github.com/mozilla/TTS/issues/50
I've never tried, but the inference without dropout seems to degrade the performance.

**Comment by turian** [comment]
@kan-bayashi yes I seem to have read this in another paper too, that they leave on dropout during inference. Manual seed would be nice.

**Comment by lijuncheng16** [comment]
> I also want to second @turian for the deterministic **option**. The deterministic option will be important for some investigation. Of course, we can still keep the non-deterministic version as the default, and it would not affect the current users. @kan-bayashi, could you consider it?

This seems to be a persisting problem with Tacotron 2. The only solution (hacky patch) for now seems to be here (replacing dropout with BN) [https://github.com/mozilla/TTS/issues/50](url)
