### ISSUE TITLE
Parallel Tacotron 2 

### ISSUE THREAD

**Issue by deepconsc** [espnet/espnet#3131]
Tacotron team has released Parallel Tacotron 2, with novel duration modelling technique.
```
This section introduces the proposed Parallel Tacotron 2 model,
specifically differentiable duration modeling and learned upsampling, which don’t require supervised duration signals. The
network architecture is illustrated in Fig. 1. It is designed to
enable error gradients to be propagated through duration modeling, which is essential for automatically learning reasonable
alignments between token and frame sequences without supervision. 
```

Paper:  ```https://arxiv.org/pdf/2103.14574.pdf```

Would be awesome to see it implemented into espnet!

**Comment by keonlee9420** [comment]
Hi @deepconsc , I've implemented the code (using Pytorch), but still, the model does not converge. So I'm currently debugging and tunning the model based on the original authors' advice on my implementation. It would be boosted a lot if anyone can contribute as a speech domain expert. Thanks!

**Comment by zzw922cn** [comment]
By the way, I also implemented its hard parts in TensorFlow, welcome to submit any issues to me! 

Soft-DTW, forward and backward algorithms:
https://github.com/zzw922cn/TF2_soft_dtw

Upsampling Auxiliary Attention:
https://github.com/zzw922cn/TF2_UpsamplingAuxiliaryAttention
