### ISSUE TITLE
N-gram model in espnet2

### ISSUE THREAD

**Issue by hanna-dav** [espnet/espnet#3134]
Hey!
I would like to run decoding on ESPNET2 using an n-gram model.
In ESPNET (original version), there is an option to run decoding using api=v2 which calls the recog_v2 function that supports n-gram.
Has anyone found something similar in ESPNET2?
Thanks in advance! :)

**Comment by sw005320** [comment]
I forgot the status of it.
We have added an n-gram model in our scorer interface by @qmpzzpmq.
espnet2 also uses that scorer interface, and it is ready to be used for espnet2.

@qmpzzpmq, could you give us some comments about it?

**Comment by qmpzzpmq** [comment]
I will look at it. But it will take time since recently I am busy for move house. Thanks for you @sw005320

**Comment by sw005320** [comment]
Many thanks!
Yes, of course, take your time and do it with your own schedule.
But this would be a great addition for espnet2 ;)

**Comment by qmpzzpmq** [comment]
@sw005320 get start work

**Comment by qmpzzpmq** [comment]
@hanna-dav please follow the WIP PR 
https://github.com/espnet/espnet/pull/3345
