### ISSUE TITLE
TTS Style Change ？is there any idea ？

### ISSUE THREAD

**Issue by wac81** [espnet/espnet#3135]
https://cloud.google.com/text-to-speech/?hl=zh-cn
like google wavenet method，and there are 4 wavenet {A/B/C/D}, i think it's add any array for tts model or vocodar model to change tts output voice.

so it’s any simple method to change TTS voice style for fastspeech2?

**Comment by kan-bayashi** [comment]
We support Multi-speaker + GST fastspeech2.
You can try in the notebook.
https://colab.research.google.com/github/espnet/notebook/blob/master/espnet2_tts_realtime_demo.ipynb
