### ISSUE TITLE
Finetuning an english base model using tacotron 2 

### ISSUE THREAD

**Issue by sciai-ai** [espnet/espnet#3141]
HI,

I have tried fine tuning using the JVS recipe (https://github.com/espnet/espnet/tree/master/egs2/jvs/tts1). 

I first trained using a model using a custom dataset for a single English speaker and got good results. Now I tried to finetune the model using a smaller datasets of 30 minutes, I used the JVS finetuning recipe however the results are not meaningful. I removed silences and cleaned the dataset prior finetuning too When i looked at the attention plots they seem to get worse as the epochs increases. I am confused by this, is there anything I can do to improve this?

![image](https://user-images.githubusercontent.com/52277510/113968599-fb4a4700-9865-11eb-95da-8165f2eb3151.png)

**Comment by ymzlygw** [comment]
> HI,
> 
> I have tried fine tuning using the JVS recipe (https://github.com/espnet/espnet/tree/master/egs2/jvs/tts1).
> 
> I first trained using a model using a custom dataset for a single English speaker and got good results. Now I tried to finetune the model using a smaller datasets of 30 minutes, I used the JVS finetuning recipe however the results are not meaningful. I removed silences and cleaned the dataset prior finetuning too When i looked at the attention plots they seem to get worse as the epochs increases. I am confused by this, is there anything I can do to improve this?
> 
> ![image](https://user-images.githubusercontent.com/52277510/113968599-fb4a4700-9865-11eb-95da-8165f2eb3151.png)

Hi could you please help me about my problem? thanks !
in stage 6, When I using recommeded command :
$ ./run.sh --stage 6 --train_config conf/tuning/finetune_tacotron2.yaml
--train_args "--init_param downloads/2dc62478870c846065fe39e609ba6657/exp/tts_train_tacotron2_raw_phn_jaconv_pyopenjtalk/199epoch.pth"
--tag finetune_jsut_pretrained_tacotron2
**I get the following error:**
tts_train.py: error: unrecognized arguments: --init_param downloads/2dc62478870c846065fe39e609ba6657/exp/tts_train_tacotron2_raw_phn_jaconv_pyopenjtalk/199epoch.pth

Is the command error?

**Comment by ymzlygw** [comment]
Hi could you please help me about my problem? thanks !
in stage 6, When I using recommeded command :
$ ./run.sh --stage 6 --train_config conf/tuning/finetune_tacotron2.yaml
--train_args "--init_param downloads/2dc62478870c846065fe39e609ba6657/exp/tts_train_tacotron2_raw_phn_jaconv_pyopenjtalk/199epoch.pth"
--tag finetune_jsut_pretrained_tacotron2
I get the following error:
tts_train.py: error: unrecognized arguments: --init_param downloads/2dc62478870c846065fe39e609ba6657/exp/tts_train_tacotron2_raw_phn_jaconv_pyopenjtalk/199epoch.pth

Is the command error?

**Comment by sciai-ai** [comment]
@kan-bayashi Any tips on how to improve this? Many thanks!

> HI,
> 
> I have tried fine tuning using the JVS recipe (https://github.com/espnet/espnet/tree/master/egs2/jvs/tts1).
> 
> I first trained using a model using a custom dataset for a single English speaker and got good results. Now I tried to finetune the model using a smaller datasets of 30 minutes, I used the JVS finetuning recipe however the results are not meaningful. I removed silences and cleaned the dataset prior finetuning too When i looked at the attention plots they seem to get worse as the epochs increases. I am confused by this, is there anything I can do to improve this?
> 
> ![image](https://user-images.githubusercontent.com/52277510/113968599-fb4a4700-9865-11eb-95da-8165f2eb3151.png)

@kan-bayashi any tips on how to imropve the finetuning? Many thanks! I also tried mozilla TTS but it also does not work for this task

**Comment by sciai-ai** [comment]
> Hi could you please help me about my problem? thanks !
> in stage 6, When I using recommeded command :
> $ ./run.sh --stage 6 --train_config conf/tuning/finetune_tacotron2.yaml
> --train_args "--init_param downloads/2dc62478870c846065fe39e609ba6657/exp/tts_train_tacotron2_raw_phn_jaconv_pyopenjtalk/199epoch.pth"
> --tag finetune_jsut_pretrained_tacotron2
> I get the following error:
> tts_train.py: error: unrecognized arguments: --init_param downloads/2dc62478870c846065fe39e609ba6657/exp/tts_train_tacotron2_raw_phn_jaconv_pyopenjtalk/199epoch.pth
> 
> Is the command error?

you need space before --init_param

**Comment by ymzlygw** [comment]
> > Hi could you please help me about my problem? thanks !
> > in stage 6, When I using recommeded command :
> > $ ./run.sh --stage 6 --train_config conf/tuning/finetune_tacotron2.yaml
> > --train_args "--init_param downloads/2dc62478870c846065fe39e609ba6657/exp/tts_train_tacotron2_raw_phn_jaconv_pyopenjtalk/199epoch.pth"
> > --tag finetune_jsut_pretrained_tacotron2
> > I get the following error:
> > tts_train.py: error: unrecognized arguments: --init_param downloads/2dc62478870c846065fe39e609ba6657/exp/tts_train_tacotron2_raw_phn_jaconv_pyopenjtalk/199epoch.pth
> > Is the command error?
> 
> you need space before --init_param

Thanks ! Ihave solved it!

**Comment by kan-bayashi** [comment]
Most of the cases, the cleaning of training data is critical.
- remove silence 
- adjust pose length
- add missing symbols
- etc..

See tips:
https://github.com/espnet/espnet/tree/master/egs2/TEMPLATE/tts1#why-the-model-cannot-be-trained-well-with-my-own-dataset

Related issue:
https://github.com/espnet/espnet/issues/2327
https://github.com/espnet/espnet/issues/2565
