### ISSUE TITLE
The libricss dataset decoding time is too long

### ISSUE THREAD

**Issue by yangyi0818** [espnet/espnet#3143]
@akreal 
hello, when I run the decoding step of libricss dataset in path-to-espnet/egs/libri_css/asr1/run.sh, I find it cost too much time.
The decoding of dev set, which only contains about 500 utterances, takes about 1 hour. The eval set, takes more than 9 hours. Why is that? Is it right?

**Comment by akreal** [comment]
Hello! Yes, it's quite slow, mostly because of relatively large beam size, I guess. You can try decreasing the beam size to 10 or 15 (currently hardcoded in `run.sh`) or increasing number of jobs.

**Comment by sw005320** [comment]
Yes, as @akreal mentions, the recipe overly tuned for the off-line best ASR setup. The ASR/LM model is very large and the beam size is extremely large, which is not our normal setup. Please let me know if decreasing the beam size does not completely solve your issues. We'll think of preparing a smaller model for fast inference (and minimizing the degradation).
