### ISSUE TITLE
Construction of  a noise robust speech recognition model.

### ISSUE THREAD

**Issue by ken57** [espnet/espnet#3146]
We are struggling to build a noise robust speech recognition model.
I have questions about the noise robust speech recognition model using Espnet.

(1) Which method do you think is better on building a noise robust model: training with noise data augmentation or sound enhancement before recognition?
(2) I feel its difficult to recognize in environments where multiple people are talking simultaneously. I found several papers on speech separation and speech recognition where they experimented on using the data sets with speech audio data like WSJ0-2mix. Is it ok to expect methods proposed in these studies are effective in real-world settings?

Any help is appreciated.

**Comment by ken57** [comment]
I'm sorry. I labeled this issue "installation" by mistake.
However, I don't know how to fix it...

**Comment by sw005320** [comment]
Thanks for bringing important discussions.

My suggestion is to work on the noise data augmentation first.
espnet chime6 recipe includes such a process (https://github.com/kaldi-asr/kaldi/tree/master/egs/aspire/s5).
You can also find more examples in the Kaldi recipes (e.g., https://github.com/kaldi-asr/kaldi/tree/master/egs/aspire/s5).

We also have speech enhancement/separation + ASR recipes but they are a bit experimental.
For example,
- https://github.com/espnet/espnet/tree/master/egs2/chime4/asr1 can do both speech enhancement and ASR.
- https://github.com/espnet/espnet/tree/master/egs2/wsj0_2mix/enh1 and https://github.com/espnet/espnet/tree/master/egs2/wsj0_2mix_spatialized/enh1 can do separation followed by the ASR evaluation, but they are based on the simulation and would have some difficulties when we apply them to the real environment.

**Comment by ken57** [comment]
Thank you for your reply.

First, I will try the noise data augmentation reading the chime6 recipe.

I will also read the speech enhancement/separation recipes you introduced.
