### ISSUE TITLE
Mask-CTC pretrained model on large-scale English benchmark datasets

### ISSUE THREAD

**Issue by unilight** [espnet/espnet#3158]
Hi, is it possible to release Mask-CTC pretrained models on large-scale English benchmark datasets? For example, the Tedlium2 model described in the paper. Other datasets like Librispeech would also be fine. Thanks a lot!

**Comment by sw005320** [comment]
Those are good suggestions!
@YosukeHiguchi, @Jzmo, can you upload your configs and models?

**Comment by Jzmo** [comment]
> Those are good suggestions!
> @YosukeHiguchi, @Jzmo, can you upload your configs and models?

Sure, I will add the model link and configs when making pull request of my code.
