### ISSUE TITLE
Version of Pytorch and Warp-CTC

### ISSUE THREAD

**Issue by jnishi** [espnet/espnet#316]
Pytorch 0.4.1 is released at yesterday. Now pytorch is fixed to 0.4.0 because older version of warp-ctc pytorch binding cannont be build with pytorch 0.4.1 (cf. https://github.com/espnet/espnet/pull/312).

Current version of original repository of warp-ctc now supports pytorch 0.4.1, but it cannot be built with pytorch 0.4.0. It means if my repository followed it, all user must use pytorch 0.4.1. I think it is difficult to switch version in installing, because it is difficult to describe conditional statement in Makefile.

Do you have any opinion about this?

**Comment by ShigekiKarita** [comment]
Thanks for report. I think supporting only 0.4.1 is the best.

**Comment by ShigekiKarita** [comment]
in SeanNaren branch, there already has been size_average option that is same to our normalization https://github.com/SeanNaren/warp-ctc/blob/pytorch_bindings/pytorch_binding/warpctc_pytorch/__init__.py#L41

**Comment by kan-bayashi** [comment]
I also want to support only 0.4.1.
And we should conduct refactoring of scripts to remove the part related to `torch_is_old`.

**Comment by sw005320** [comment]
I agree

**Comment by kan-bayashi** [comment]
Now is fixed.
