### ISSUE TITLE
Error while finetuning a fastspeech2 model 

### ISSUE THREAD

**Issue by WadoodAbdul** [espnet/espnet#3161]
**The bug**
I'm trying to finetune the fastspeech2 model, "kan-bayashi/vctk_xvector_conformer_fastspeech2" on my own data. However a size mismatch error pops up in the stage 6, while copying checkpoint parameters.

**Basic environments:**
 - OS information: Ubuntu 18.0.4
 - python version:3.7.4 [GCC 7.3.0]]
 - espnet version: 0.9.9
 - pytorch version [ 1.4.0]
 
**Environments from `torch.utils.collect_env`:**
PyTorch version: 1.4.0
Is debug build: No
CUDA used to build PyTorch: 10.1

OS: Ubuntu 18.04.5 LTS
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
CMake version: version 3.10.2

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: 10.1.243
GPU models and configuration: GPU 0: Tesla M60
Nvidia driver version: 460.32.03
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.5

Versions of relevant libraries:
[pip] numpy==1.19.4
[pip] pytorch-ranger==0.1.1
[pip] pytorch-wpe==0.0.0
[pip] torch==1.4.0
[pip] torch-complex==0.2.0
[pip] torch-optimizer==0.0.1a16
[pip] torchaudio==0.4.0
[pip] torchfile==0.1.0
[pip] torchvision==0.5.0
[pip] warpctc-pytorch==0.2.1
[pip] warprnnt-pytorch==0.1
[conda] pytorch-ranger            0.1.1                    pypi_0    pypi
[conda] pytorch-wpe               0.0.0                    pypi_0    pypi
[conda] torch                     1.4.0                    pypi_0    pypi
[conda] torch-complex             0.2.0                    pypi_0    pypi
[conda] torch-optimizer           0.0.1a16                 pypi_0    pypi
[conda] torchaudio                0.4.0                    pypi_0    pypi
[conda] torchfile                 0.1.0                    pypi_0    pypi
[conda] torchvision               0.5.0                    pypi_0    pypi
[conda] warpctc-pytorch           0.2.1                    pypi_0    pypi
[conda] warprnnt-pytorch          0.1                       dev_0    <develop>

**Task information:**
 - Task: TTS
 - Recipe: self
 - ESPnet2

**To Reproduce**
- Create kaldi style /data directory with my multispeaker-data
- Run stages 2,3,4 with `use_vector=true`
- Run stage 7 , decode with a download_model, to generate durations
- Run stage 5, 
>```./run.sh --stage 5 \ --stop-stage 5 \ --train_config conf/tuning/train_xvector_tacotron2.yaml \ --teacher_dumpdir exp/kan-bayashi/ljspeech_tacotron2/decode_use_teacher_forcingtrue_train.loss.ave \ --tts_stats_dir exp/stats \ --write_collected_feats true```
- Download the model I want to use, replace tokens and stats
- Stage 6, the error comes up,
>```./run.sh --stage 6 --stop-stage 6 --train_config conf/tuning/train_xvector_conformer_fastspeech2.yaml \ --train_args "--init_param pretrained/a7f32c2dfd9a5395607dc0589b3a2d2c/exp/tts_train_xvector_conformer_fastspeech2_transformer_teacher_raw_phn_tacotron_g2p_en_no_space/train.loss.ave_5best.pth" \ --tag finetune_fastspeech2```

One thing to note is that, the pitch_stats.npz and energy_stats.npz files were not generated in the exp/stats directory and I had copied that from the downloaded_model_dir/a7f32c2/exp/tts_train_xvector_transformer_raw_phn_tacotron_g2p_en_no_space/decode_use_teacher_forcingtrue_train.loss.ave/stats/train/ folder.

```
Traceback (most recent call last):
  File "/opt/miniconda/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/miniconda/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/miniconda/lib/python3.7/site-packages/espnet2/bin/tts_train.py", line 22, in <module>
    main()
  File "/opt/miniconda/lib/python3.7/site-packages/espnet2/bin/tts_train.py", line 18, in main
    TTSTask.main(cmd=cmd)
  File "/opt/miniconda/lib/python3.7/site-packages/espnet2/tasks/abs_task.py", line 976, in main
    cls.main_worker(args)
  File "/opt/miniconda/lib/python3.7/site-packages/espnet2/tasks/abs_task.py", line 1143, in main_worker
    else "cpu",
  File "/opt/miniconda/lib/python3.7/site-packages/espnet2/torch_utils/load_pretrained_model.py", line 81, in load_pretrained_model
    obj.load_state_dict(dst_state)
  File "/opt/miniconda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 830, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for ESPnetTTSModel:
	size mismatch for feats_extract.logmel.melmat: copying a param with shape torch.Size([1025, 80]) from checkpoint, the shape in current model is torch.Size([513, 80]).
```
### Some Questions:
1. How can we know if a model was trained using espnet1?(as espnet1 and espnet2 models are incompatible?)
2. How can I generate the pitch_stats.npz and energy_stats.npz files for my data? (As I would need these for training from scratch?)

Note: I had changed the variables in tts.sh according to the ones mentioned in teh config.yaml file in the downloaded model directory.

**Comment by kan-bayashi** [comment]
> RuntimeError: Error(s) in loading state_dict for ESPnetTTSModel:
	size mismatch for feats_extract.logmel.melmat: copying a param with shape torch.Size([1025, 80]) from checkpoint, the shape in current model is torch.Size([513, 80]).

It seems the fft and shift point settings are different.
And you need to also 
- specify `--use_xvector` in stage 5 and stage 6
- use xvector fastspeech2 config in stage 5 (feature statistics calculation)


> How can we know if a model was trained using espnet1?(as espnet1 and espnet2 models are incompatible?)

In espnet_model_zoo, there are only espnet2 models.
If the model directory contains yaml format config file, that is espnet2.

> How can I generate the pitch_stats.npz and energy_stats.npz files for my data? (As I would need these for training from scratch?)

They will be created in stage 5 if we use fastspeech2 config.

**Comment by WadoodAbdul** [comment]
@kan-bayashi Could you please suggest a config for finetuning fastspeech model that has worked for you? Currently I've just reduced the learning rate and epochs.
