### ISSUE TITLE
Instructions for training vocoder in voice conversion example

### ISSUE THREAD

**Issue by vishal16babu** [espnet/espnet#3165]
https://github.com/espnet/espnet/tree/master/egs/arctic/vc1 run.sh script downloads pretrained vocoder for the target actor. Is there a recipe for training the vocoder? I want to do voice conversion from a single speaker A to another speaker B which are not part of the dataset used in the example

**Comment by kan-bayashi** [comment]
Please use https://github.com/kan-bayashi/ParallelWaveGAN.
