### ISSUE TITLE
Could you please tell me how to improve vc performance ?

### ISSUE THREAD

**Issue by ymzlygw** [espnet/espnet#3172]
Hi, I have followed the jvs recipe to do the spk adaption and get some good . Really insteresting, but also find that  pronunciation of some words is a little strange.
And I want to know that how to improve the performance by using small datase(ex..100-200 utt) .
What params should i do some change on them ?  Really thanks for your recommendtations!

**Comment by kan-bayashi** [comment]
In the case of Japanese, g2p method affects the pronunciation.
You can find several choices:
https://github.com/espnet/espnet/blob/55160fc20c48686808cbdf208919e668e3b1451a/egs2/jvs/tts1/run.sh#L31-L45

And non-autoregressive model requires smaller amount of the training data than AR models.
The adaptation step is a little bit complicated, but it is worthwhile to try.
(Adap AR model -> generate duration -> Adap NAR model ...)

**Comment by ymzlygw** [comment]
> In the case of Japanese, g2p method affects the pronunciation.
> You can find several choices:
> https://github.com/espnet/espnet/blob/55160fc20c48686808cbdf208919e668e3b1451a/egs2/jvs/tts1/run.sh#L31-L45
> 
> 
> Note that you need to match `g2p` with pretrained model.
> And non-autoregressive model requires smaller amount of the training data than AR models.
> The adaptation step is a little bit complicated, but it is worthwhile to try.
> (Adap AR model -> generate duration -> Adap NAR model ...)

Thanks, I'll try it!

**Comment by ymzlygw** [comment]
> In the case of Japanese, g2p method affects the pronunciation.
> You can find several choices:
> https://github.com/espnet/espnet/blob/55160fc20c48686808cbdf208919e668e3b1451a/egs2/jvs/tts1/run.sh#L31-L45
> 
> 
> Note that you need to match `g2p` with pretrained model.
> And non-autoregressive model requires smaller amount of the training data than AR models.
> The adaptation step is a little bit complicated, but it is worthwhile to try.
> (Adap AR model -> generate duration -> Adap NAR model ...)

By the way, Could you please tell me is there any recipe about how to train multi-speaker model  of Japanese? Thanks!

**Comment by kan-bayashi** [comment]
> By the way, Could you please tell me is there any recipe about how to train multi-speaker model of Japanese? Thanks!

Currently, we have not yet supported Japanese multi-speaker recipe.
(You may be able to transfer egs/jnas/tts1 recipe to espnet2)

If you have such a dataset, you can try by following 
https://github.com/espnet/espnet/tree/master/egs2/TEMPLATE/tts1#multi-speaker-model-with-x-vector-training

**Comment by ymzlygw** [comment]
> > By the way, Could you please tell me is there any recipe about how to train multi-speaker model of Japanese? Thanks!
> 
> Currently, we have not yet supported Japanese multi-speaker recipe.
> (You may be able to transfer egs/jnas/tts1 recipe to espnet2)
> 
> If you have such a dataset, you can try by following
> https://github.com/espnet/espnet/tree/master/egs2/TEMPLATE/tts1#multi-speaker-model-with-x-vector-training

Sorry for late and thanks for your reply!  So it means If I use jnas corpus I can follow the  (egs/jnas/tts1) under the Espnet1, this is Espnet1 needed; But If I have another multi-spk corpus  and I can follow the Espnet2 recipy as (https://github.com/espnet/espnet/tree/master/egs2/TEMPLATE/tts1#multi-speaker-model-with-x-vector-training).
If so, could you please tell me which has the better  performance? Thanks and wait for your reply!

**Comment by kan-bayashi** [comment]
> But If I have another multi-spk corpus and I can follow the Espnet2 recipy as

Yes, once you make your own recipe using multi-spk, you can build the model.
(What you needed to make the recipe is the same as the single spk case, what you needed is just add the option when running)

> If so, could you please tell me which has the better performance? Thanks and wait for your reply!

You mean the configuration? I have never compared the performance strictly, but maybe x-vector + GST is the best.

**Comment by ymzlygw** [comment]
> > But If I have another multi-spk corpus and I can follow the Espnet2 recipy as
> 
> Yes, once you make your own recipe using multi-spk, you can build the model.
> (What you needed to make the recipe is the same as the single spk case, what you needed is just add the option when running)
> 
> > If so, could you please tell me which has the better performance? Thanks and wait for your reply!
> 
> You mean the configuration? I have never compared the performance strictly, but maybe x-vector + GST is the best.

Oh, Thanks! How many 

> > But If I have another multi-spk corpus and I can follow the Espnet2 recipy as
> 
> Yes, once you make your own recipe using multi-spk, you can build the model.
> (What you needed to make the recipe is the same as the single spk case, what you needed is just add the option when running)
> 
> > If so, could you please tell me which has the better performance? Thanks and wait for your reply!
> 
> You mean the configuration? I have never compared the performance strictly, but maybe x-vector + GST is the best.

Thanks for advice! By the way, with your experience, usually how many utts of each speaker  is enough for better training  in multi-spk dataset?

**Comment by ymzlygw** [comment]
@kan-bayashi Sorry I am also confused that why GST and X-vector now I find that  is jsut used for multi-spk model. If i can use only one speaker's data with GST/X-vector, because like single-spk model , I may be just want to change the prosody for one specific speaker.
