### ISSUE TITLE
The question marks (?) and exclamation symbols (!) don't make any difference in the speech

### ISSUE THREAD

**Issue by AMG222** [espnet/espnet#3179]
**Describe the bug**
The question marks (?) and exclamation symbols (!) don't make any difference in the speech
I'm tryan to make three types of enphasis: advice, warnings and informative. If someone know how to change the enphasis or the intonation like the natural language please heal me

**Comment by sw005320** [comment]
Thanks for your question.
@kan-bayashi, can you answer it for me?
I have checked espnet1 ASR recipe since it is easy to access the cleaned text and I found that the training data includes "?". So, I thought that it would work to some extent, but is my understanding wrong?
Did you prune the punctuation somewhere?

**Comment by kan-bayashi** [comment]
It depends on the language and dataset.
In the case of English, we use ! and ? for the input.
However, since the model reflect the nature of the training data, the effect of such symbols depends on samples in the training data.

**Comment by sw005320** [comment]
Thanks.
Year, the ljspeech espnet1 recipe includes "?" in several training utterances, so I thought that it would change some intonations during inference, but I could not recognize some changes as @AMG222 reported.

**Comment by sciai-ai** [comment]
I am also experiencing the same issue, with a custom dataset as well as LJspeech. There is no effect of '?' or '!' in the synthesised speech.

**Comment by sciai-ai** [comment]
I have looked at Transformer TTS for LJ speech, I can confirm that in their implmentaion ? or ! has in effect. You can try the demo here

[](https://colab.research.google.com/drive/1akxtrLZHKuMiQup00tzO2olCaN-y3KiD?usp=sharing#scrollTo=gXDxzTFBBxjH)

**Comment by Laope94** [comment]
I've run into same issue while trying to train JETS model for german language. I am using Bernd Ungerer dataset. First I tought that portion of exclamation sentences and questions in the dataset might be an issue, but I am training VITS with Piper simultaneously using same data and question marks are recognized just fine. I've debugged my inference script, after transcription to phonemes punctuation is preserved and is present at the moment of input into the model. Punctuation is present training data's Text file. So my guess is that whatever causes the issue happens during training.
My training has crashed after approximately 290k training steps on CUDA OOM, not sure why, but probably some unfortunate batch with long sentences (I've used last checkpoint for inference btw) - 290k should be probably enough in my opinion, speech quality and pronounciation is really good, but maybe model hasn't grabbed concept of raising voice in question etc yet. I am considering trying to simply restart from checkpoint and give it more training, or strart from scratch in case I've made a mistake somewhere, some flag or parameter in config... Has anyone run into same thing and managed to solve it?

My run command:
`./run.sh --stage 2 --ngpu 1 --fs 22050 --n_fft 1024 --n_shift 256 --win_length null --dumpdir dump/22k --expdir exp/22k --cleaner none --tts-task gan_tts --g2p espeak_ng_german --lang de --train_config ./conf/tuning/train_jets.yaml`

**Comment by mush42** [comment]
Just for future reference for anyone who comes to this:

I'm developing [OptiSpeech](https://github.com/mush42/optispeech) which is based on JETS with a lot of enhancements from latest research.

Good handling of '?' and '!' depends on good pitch extraction.
