### ISSUE TITLE
About time_warp

### ISSUE THREAD

**Issue by Lostsy** [espnet/espnet#3181]
Hi

I was using the time_warp module in Espnet. And I find some comments that the time_warp does not support batch style input. I think I have a solution for it.

File:
https://github.com/espnet/espnet/blob/master/espnet2/layers/time_warp.py

line 91
 ys.append(_y)

Then pad_list function accepts tensor of 2D. So, we just need to change the _y tenor from 3D to 2D.
My code:
ys.append(_y.squeeze(dim=0))

Regards

Yang

**Comment by kan-bayashi** [comment]
I think the problem is how to remove for loop here.
https://github.com/espnet/espnet/blob/55160fc20c48686808cbdf208919e668e3b1451a/espnet2/layers/time_warp.py#L85-L90

**Comment by Lostsy** [comment]
Hi, kan-bayashi

I think if we apply different timewarp in the batch, it will be difficult to remove the warp. I have no idea for the moment.

Regards

Yang
