### ISSUE TITLE
CMU arctic database audios are not parallel

### ISSUE THREAD

**Issue by vishal16babu** [espnet/espnet#3182]
In order to use https://github.com/espnet/espnet/tree/master/egs/arctic/vc1 ,  I downloaded the arctic dataset using the first step and compared two corresponding audio files:

1. egs/arctic/vc1/downloads/cmu_us_clb_arctic/wav/arctic_a0001.wav
2. egs/arctic/vc1/downloads/cmu_us_slt_arctic/wav/arctic_a0001.wav

Both audios have the same transcript but they're definitely not temporally aligned. https://github.com/espnet/espnet/blob/master/egs/arctic/README.md says that this dataset is a parallel dataset.

A  screenshot showing the audio profiles on Audacity:
![image](https://user-images.githubusercontent.com/11586028/116294433-970c0a80-a7b5-11eb-907d-45ccc6dd243b.png)

Based on this I have a few doubts:
1. Does the VTN model still work on datasets where the content of the utterances is the same but the audio is not temporally aligned?
2. Is there a preprocessing step to align these audios temporally using methods like dynamic time warping?

**Comment by kan-bayashi** [comment]
> Does the VTN model still work on datasets where the content of the utterances is the same but the audio is not temporally aligned?
> Is there a preprocessing step to align these audios temporally using methods like dynamic time warping?

Since our model is based on sequence-to-sequence model, there is no need to align the pair of audio.
Attention will handle the time alignment issue.

**Comment by vishal16babu** [comment]
I also had the same expectation. Thanks a lot for the confirmation.
