### ISSUE TITLE
Streaming inference mode

### ISSUE THREAD

**Issue by AmirHussein96** [espnet/espnet#3184]
While I was investigating how streaming works I noticed that the encoder encodes the entire speech before it fed to the decoder.  I thought based on the paper (https://arxiv.org/abs/2006.14941) each encoded block is fed to the decoder once they are encoded so that the decoder does not need to wait until the entire segment is encoded. As far as I understand this is not a streaming inference mode, right? If yes, how can one run the model in the streaming inference mode? 

My observation is from the following lines in the `espnet/espnet2/bin/asr_inference.py/` :
```
# a. To device 
 batch = to_device(batch, device=self.device)
# b. Forward Encoder
enc, _ = self.asr_model.encode(**batch)
assert len(enc) == 1, len(enc)

# c. Passed the encoder result and the beam search
nbest_hyps = self.beam_search(
    x=enc[0], maxlenratio=self.maxlenratio, minlenratio=self.minlenratio
)
nbest_hyps = nbest_hyps[: self.nbest]  
```

**Comment by will-rice** [comment]
I have the same question. As far as I can tell most open-source implementations encode the full spectrogram. However, the way I interpreted the papers lead me to think that each chunk is encoded, then decoded. I'd really like to see how a person would know which to use based on the papers.

**Comment by eml914** [comment]
Thank you for your comment.
The paper is based on the system that encodes each chunk then decode synchronously.  However, to fit the implementation into current espnet2 pipeline, I had to once aggregate all the encoded features and fed into the decoder.  In the decoder, or `self.beam_search`, the encoded features are split again into chunks, so that it reproduce streaming inference.  `self.beam_search` refers `espnet/nets/batch_beam_search_online_sim.py` here.  So, basically it is simulation of the streaming inference.
I also used  C++ implementation for latency evaluation in the paper, which is fully streaming (i.e. chunk-wise), but unfortunately I cannot share the code for now.

**Comment by AmirHussein96** [comment]
> Thank you for your comment.
> The paper is based on the system that encodes each chunk then decode synchronously. However, to fit the implementation into current espnet2 pipeline, I had to once aggregate all the encoded features and fed into the decoder. In the decoder, or `self.beam_search`, the encoded features are split again into chunks, so that it reproduce streaming inference. `self.beam_search` refers `espnet/nets/batch_beam_search_online_sim.py` here. So, basically it is simulation of the streaming inference.
> I also used C++ implementation for latency evaluation in the paper, which is fully streaming (i.e. chunk-wise), but unfortunately I cannot share the code for now.

Thank you @eml914 for the clarification.  So theoretically if I removed the aggregation part from the encoder and fed the encoded representations once they are encoded directly to the decoder the model will run in streaming mode, right? Please let me know if my understanding is correct. Also, do you think such modification requires changing the currently available `espnet/nets/batch_beam_search_online_sim.py` or espnet/espnet2/bin/asr_inference.py?

**Comment by eml914** [comment]
Yes, you are correct.
If you want to run it in fully streaming way, you need to modify `spnet/espnet2/bin/asr_inference.py` or recreate it as `asr_inference_streaming.py`, and feed input features chunk by chunk rather than as a whole.
I also am going to work on this in the near future.
