### ISSUE TITLE
VTN results not as good as demo samples

### ISSUE THREAD

**Issue by vishal16babu** [espnet/espnet#3194]
I used https://github.com/espnet/espnet/tree/master/egs/arctic/vc1 to train the VTN model with the exact set of steps. 
The results sound like the target speaker but the content itself is not clear. It's very hard to guess what is being said just by listening to the generated samples.
The demo samples that are shown at https://unilight.github.io/Publication-Demos/publications/transformer-vc/ on the other hand are very clear.

[Generated sample](https://t1856418.p.clickup-attachments.com/t1856418/f1d10bd6-f039-4036-89f9-67adf8128f2f/arctic_b0539.wav)
[Demo sample
](https://unilight.github.io/Publication-Demos/publications/transformer-vc/samples/vtn-932/clb-slt/arctic_b0442-feats_gen.wav)

1. Is the setup mentioned in the recipe the same as the one used to train and generate the demo samples?
2. What can be done to improve these results and get the same quality as that of the demo samples?

**Comment by unilight** [comment]
Hi @vishal16babu , thanks for reporting this! The sample you attached did seem to sound a bit worse than my impression. To get a clear picture of what happened, can you run step 6 in https://github.com/espnet/espnet/blob/master/egs/arctic/vc1/run.sh and show the MCD, CER and WER? Thanks in advance!

**Comment by vishal16babu** [comment]
Hi @unilight , I ran the experiment with original split and the results are much better(as shown in demo samples). So something is definitely not working as expected.

I did the following experiments in the same order(each experiment was done because the earlier was not working as expected): 
1. Train on my dataset with custom split
      total utt : 131 utterances
      conf: train_pytorch_transformer.tts_pt.n80.single.yaml. 
      split : last 11 for both dev and eval
      result quality : all output samples are silent
      [sample](https://drive.google.com/file/d/1UrETgWkT9t-AcOCwASFWq50TLnPLP_E_/view?usp=sharing)
2. Train on given dataset by taking only first 120 sentences
      total utt : 120 utterances
      conf: train_pytorch_transformer.tts_pt.n80.single.yaml. 
      split : last 11 for both dev and eval
      result quality : voice matches target speaker but content is highly unintelligible
      [sample](https://drive.google.com/file/d/1Dq-I_5DXBtveCbl8hDaj-mvRcCo8f4V5/view?usp=sharing)
3. Train on given dataset with custom split
      total utt : 1132 utterances
      conf: train_pytorch_transformer.tts_pt.single.yaml. 
      split : last 11 for both dev and eval
      result quailty: voice matches target speaker but content is unintelligible partially
      [sample](https://drive.google.com/file/d/1qlPcw85MEjMN1jMJiryrthf_aMGnBCJX/view?usp=sharing)
4. Train on given dataset
      total utt : 1132 utterances
      conf: train_pytorch_transformer.tts_pt.single.yaml. 
      split : last 100 for eval, last but 100 for dev
      result quailty: voice matches target speaker but content is also intelligible
      [sample](https://drive.google.com/file/d/1ewt7Ay1tt3L69dEAgSb76Uh9-NNKirTu/view?usp=sharing)

The result quality is written taking all the samples into account .All the samples of the four experiments can be found [here](https://drive.google.com/drive/folders/1CGeKO2yTjgKRubccQYjXV8n8aTPcJmKh?usp=sharing)

I'd be great if I can get the same quality of results as experiment-3 in experiment-1 and experiment-2.

**Comment by vishal16babu** [comment]
Hi @unilight ,

The objective measures for experiment 2 are the following:
```
|     SPKR        |     # Snt          # Wrd      |     Corr             Sub            Del             Ins             Err           S.Err      |
|     Sum/Avg     |       11             425      |     33.9            42.6           23.5            10.4            76.5           100.0      |
write a WER result in exp/clb1_slt1_pytorch_vtn_tts_pt/outputs_model.loss.best_decode_denorm.ob_eval/librispeech.transformer.ngpu4_asr.result.v2/clb1_slt1_dev/result.wrd.txt
|     SPKR        |      # Snt          # Wrd      |     Corr              Sub             Del             Ins              Err           S.Err      |
|     Sum/Avg     |        11              98      |     12.2             81.6             6.1            11.2             99.0           100.0      |
write a WER result in exp/clb1_slt1_pytorch_vtn_tts_pt/outputs_model.loss.best_decode_denorm.ob_eval/librispeech.transformer.ngpu4_asr.result.v2/clb1_slt1_dev/result_w_punc.wrd.txt
|     SPKR        |      # Snt          # Wrd      |     Corr              Sub             Del             Ins              Err           S.Err      |
|     Sum/Avg     |        11              98      |     12.2             81.6             6.1            11.2             99.0           100.0      |
```
The measures for experiment 3 are already mentioned [here](https://github.com/espnet/espnet/issues/3194#issuecomment-833809663). 

I did use a PWG vocoder fine-tuned for my target speaker in experiment 1. It gave good results when I used the baseline method. Anyway, I am planning to redo experiment 1 once I am able to reproduce the results for experiment 2. 

For all experiments, I did use `m_ailabs.judy.vtn_tts_pt` as the pre-trained model. 

More info:
For experiment 1 and experiment 2, I only kept `etc`, `wav` folders with `etc/arctic.data` containing the transcripts and `wav` containing the corresponding audio files. I also created an empty `lab` folder. I hope this setup is enough?

**Comment by terbed** [comment]
Hi @unilight @vishal16babu!
I could not execute the basic steps presented in the readme. I received the following error in the log file:

> 2021-09-07 14:56:36,585 (asr_init:249) INFO: Reading model parameters from downloads/m_ailabs.judy.vtn_tts_pt/m_ailabs.judy.vtn_tts_pt/snapshot.ep.500
> 2021-09-07 14:56:36,585 (asr_utils:694) INFO: reading a config file from downloads/m_ailabs.judy.vtn_tts_pt/m_ailabs.judy.vtn_tts_pt/model.json
> 2021-09-07 14:56:36,610 (encoder:170) INFO: encoder self-attention layer type = self-attention
> 2021-09-07 14:56:36,661 (decoder:127) INFO: decoder self-attention layer type = self-attention
> 2021-09-07 14:56:36,824 (asr_init:68) ERROR: Some specified modules from the pre-trained model don't match with the new model modules:
> 2021-09-07 14:56:36,824 (asr_init:72) ERROR: Pre-trained: {('encoder.after_norm.bias', torch.Size([384])), ('encoder.after_norm.weight', torch.Size([384]))}
> 2021-09-07 14:56:36,824 (asr_init:73) ERROR: New model: set()
> # Accounting: time=2 threads=1
> # Ended (code 1) at Tue Sep  7 14:56:37 CEST 2021, elapsed time 2 seconds

Somehow the model cannot be initialized with the pretrained weights. Do you have any ideas about what could go wrong?

**Comment by devanshkhandekar** [comment]
> Hi @unilight @vishal16babu! I could not execute the default steps presented in the readme: `./run.sh --stop_stage 4 --norm_name judy --pretrained_model m_ailabs.judy.vtn_tts_pt --train_config conf/train_pytorch_transformer.tts_pt.single.yaml --tag vtn_tts_pt`
> 
> I received the following error in the log file:
> 
> ```
> 2021-09-07 14:56:36,585 (asr_init:249) INFO: Reading model parameters from downloads/m_ailabs.judy.vtn_tts_pt/m_ailabs.judy.vtn_tts_pt/snapshot.ep.500
> 2021-09-07 14:56:36,585 (asr_utils:694) INFO: reading a config file from downloads/m_ailabs.judy.vtn_tts_pt/m_ailabs.judy.vtn_tts_pt/model.json
> 2021-09-07 14:56:36,610 (encoder:170) INFO: encoder self-attention layer type = self-attention
> 2021-09-07 14:56:36,661 (decoder:127) INFO: decoder self-attention layer type = self-attention
> 2021-09-07 14:56:36,824 (asr_init:68) ERROR: Some specified modules from the pre-trained model don't match with the new model modules:
> 2021-09-07 14:56:36,824 (asr_init:72) ERROR: Pre-trained: {('encoder.after_norm.bias', torch.Size([384])), ('encoder.after_norm.weight', torch.Size([384]))}
> 2021-09-07 14:56:36,824 (asr_init:73) ERROR: New model: set()
> # Accounting: time=2 threads=1
> # Ended (code 1) at Tue Sep  7 14:56:37 CEST 2021, elapsed time 2 seconds
> ```
> 
> Somehow the model cannot be initialized with the pretrained weights. Do you have any ideas about what could go wrong?
You must have changed the config file or edited the config file
