### ISSUE TITLE
Any training config suggestion?

### ISSUE THREAD

**Issue by yuekaizhang** [espnet/espnet#3196]
I am training swbd on espnet2. However, the curves looks not well. Please see the attachment img. I have tried reduce the lr rate (using 0.0005, 0.0001, 0.00005) Also, increase the epoch from 35 to 50. 
![acc](https://user-images.githubusercontent.com/28823245/117229815-4dbf5900-ae4e-11eb-9757-6e2cd57fd29d.png)
![loss](https://user-images.githubusercontent.com/28823245/117229820-51eb7680-ae4e-11eb-8b87-14e2cc502235.png)
For the current config file, I used the same model with swbd recipe in espnet1 and the same specaug config. Other configs:
![image](https://user-images.githubusercontent.com/28823245/117229960-a0007a00-ae4e-11eb-894f-d1a93282c780.png)
![image](https://user-images.githubusercontent.com/28823245/117230043-bdcddf00-ae4e-11eb-8d83-c2bf342eaf12.png)
I was wondering if you have some advice. For example warmup steps or accum_grad parameters?

**Comment by sw005320** [comment]
One confirmation.
Did you set the feature extraction setup appropriately for 8kHz data?

**Comment by sw005320** [comment]
Or if you upsample it with 16kHz, that is fine (it is not perfect though).

**Comment by sw005320** [comment]
Also, did you perform speed perturbation?
I want to understand the behavior more exactly.

**Comment by yuekaizhang** [comment]
Sure. I used speed perturbation 0.9, 1.1, 1.0 and I have upsampled all data to 16k

**Comment by sw005320** [comment]
Did you increase the learning rate?
The learning curve does not look steep enough.

**Comment by sw005320** [comment]
Do you still observe `nan` warning issue?
If so, can you change the hop size from 256 to the smaller value?
The length of the input might be relatively shorter to train this task (this also depends on the BPE size).

**Comment by yuekaizhang** [comment]
Nan issue would not effect the training after adding the ignore nan option. I would try to increase the learning rate first. If it still can't work, maybe I change the hop size to 128 to see.

**Comment by sw005320** [comment]
Can you also tell me the BPE size?
Also, you may consider using transformer instead of conformer (I'm assuming that you're using conformer).
Transformer is easier to tune.

**Comment by yuekaizhang** [comment]
I use the same 2000 as espnet1. I used conformer in this experiment. I will see how transformer works and then tune the conformer.

**Comment by v-yunbin** [comment]
whether  espnet can automatically  upsample 8khz to 16khz？

> Sure. I used speed perturbation 0.9, 1.1, 1.0 and I have upsampled all data to 16k

@sw005320 whether  espnet can automatically  upsample 8khz to 16khz？I have mixed data with 16khz and 8khz

**Comment by sw005320** [comment]
I think this is related to https://github.com/espnet/espnet/issues/5093
I just added it as a pointer.
