### ISSUE TITLE
Data preparation of Machine translation

### ISSUE THREAD

**Issue by teinhonglo** [espnet/espnet#3198]
I have a short question about how to prepare data.json in espnet1 recipe of the machine translation.
If I want to translate English to France (English->France), the target1 in data.json is "France" and target2 in data.json is English. Is this correct?
I got a little bit confused about two recipes:

1. libri_trans:
https://github.com/espnet/espnet/blob/master/egs/libri_trans/mt1/run.sh#L164

2. fisher_callhome_spanish:
https://github.com/espnet/espnet/blob/master/egs/fisher_callhome_spanish/mt1/run.sh#L173

The direction of the source language and the target language of above two recipes seems different?

**Comment by hirofumi0810** [comment]
@teinhonglo yes, you are right. The option regarding reverse direction enables target-to-source MT.

**Comment by teinhonglo** [comment]
I got it.
Thanks a lot!
