### ISSUE TITLE
Error in finetuning "kan-bayashi/ljspeech_conformer_fastspeech2" in stage 6

### ISSUE THREAD

**Issue by mishra011** [espnet/espnet#3202]
I am trying to finetune kan-bayashi/ljspeech_conformer_fastspeech2. 
I followed all steps as mentioned [here](https://github.com/espnet/espnet/blob/master/egs2/jvs/tts1/README.md) and ran into this error in stage 6: Please Help

**TypeError: __init__() missing 1 required positional argument: 'stats_file'**
When I ran following stage 6 command:

**./run.sh --stage 6 --train_config conf/tuning/ft_conformer_fs2.yaml     --train_args "--init_param downloads/59c43ac0d40b121060bd71dd418f5ece/exp/tts_train_conformer_fastspeech2_raw_phn_tacotron_g2p_en_no_space/train.loss.ave_5best.pth"     --tag finetune_full_LJ_pretrained_conformer**

Follow are the logs:

# Started at Sun May  9 14:27:34 IST 2021
#
/home/deepak/miniconda3/envs/espnet_env/bin/python3 /home/deepak/miniconda3/envs/espnet_env/lib/python3.7/site-packages/espnet2/bin/tts_train.py --use_preprocessor true --token_type phn --token_list data/token_list/phn_tacotron_g2p_en_no_space/tokens.txt --non_linguistic_symbols none --cleaner tacotron --g2p g2p_en_no_space --normalize global_mvn --normalize_conf **stats_file=exp/tts_stats_raw_phn_tacotron_g2p_en_no_space/train/feats_stats.npz** --resume true --fold_length 150 --fold_length 204800 --output_dir exp/tts_finetune_full_LJ_pretrained_conformer --config conf/tuning/ft_conformer_fs2.yaml --feats_extract fbank --feats_extract_conf fs=22050 --feats_extract_conf fmin=80 --feats_extract_conf fmax=7600 --feats_extract_conf n_mels=80 --feats_extract_conf hop_length=256 --feats_extract_conf n_fft=1024 --feats_extract_conf win_length=null --train_data_path_and_name_and_type dump/raw/tr_no_dev/text,text,text --train_data_path_and_name_and_type dump/raw/tr_no_dev/wav.scp,speech,sound --train_shape_file exp/tts_stats_raw_phn_tacotron_g2p_en_no_space/train/text_shape.phn --train_shape_file exp/tts_stats_raw_phn_tacotron_g2p_en_no_space/train/speech_shape --valid_data_path_and_name_and_type dump/raw/dev/text,text,text --valid_data_path_and_name_and_type dump/raw/dev/wav.scp,speech,sound --valid_shape_file exp/tts_stats_raw_phn_tacotron_g2p_en_no_space/valid/text_shape.phn --valid_shape_file exp/tts_stats_raw_phn_tacotron_g2p_en_no_space/valid/speech_shape --init_param downloads/59c43ac0d40b121060bd71dd418f5ece/exp/tts_train_conformer_fastspeech2_raw_phn_tacotron_g2p_en_no_space/train.loss.ave_5best.pth --ngpu 4 --multiprocessing_distributed True
Process SpawnProcess-1:
Traceback (most recent call last):
  File "/home/deepak/miniconda3/envs/espnet_env/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/deepak/miniconda3/envs/espnet_env/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/deepak/miniconda3/envs/espnet_env/lib/python3.7/site-packages/espnet2/tasks/abs_task.py", line 1095, in main_worker
    model = cls.build_model(args=args)
  File "/home/deepak/miniconda3/envs/espnet_env/lib/python3.7/site-packages/espnet2/tasks/tts.py", line 332, in build_model
    pitch_normalize = pitch_normalize_class(**args.pitch_normalize_conf)
**TypeError: __init__() missing 1 required positional argument: 'stats_file'**
Process SpawnProcess-4:

**Comment by kan-bayashi** [comment]
You need to prepare the durations and calculate extra statistics in stage 5 for pitch and energy.
See
https://github.com/espnet/espnet/blob/master/egs2/TEMPLATE/tts1/README.md#fastspeech2-training

**Comment by mishra011** [comment]
Hi @kan-bayashi  I am trying to fine finetune ljspeech_conformer_fastspeech2 model on my own data set. What output will get , more accurate TTS for my domain data or the TTS audio will be get similar to my training data audio?

I want to achieve both.

**Comment by kan-bayashi** [comment]
> more accurate TTS for my domain data or the TTS audio will be get similar to my training data 

Sorry, I could not understand the sense of the difference.
Basically, the speaker characteristics will be your training data with fine-tuning.
