### ISSUE TITLE
Feature Extraction

### ISSUE THREAD

**Issue by Selma-KA** [espnet/espnet#3203]
Hi everyone, 
I'm trying to implement an end-to-end ASR model with the commonly used 80-dimensional log Mel feature with the additional pitch features (in total, 83 dimensions for each frame). But I'm not very familiar with the feature extraction step,  so I have these two questions;

- Why are there 3 features for pitch and not just one feature? 

- How can I have a 40-dimensional log Mel feature instead of 80? 

Thanks a lot for helping,

**Comment by sw005320** [comment]
For the pitch feature, we refer to https://www.cs.cmu.edu/~ymiao/pub/icassp2016_ctc.pdf (see Section 6.2). In espent1, we use Kaldi feature extraction and you can change the log Mel feature from 80 to 40 by modifying the configuration file (e.g., https://github.com/espnet/espnet/blob/master/egs/an4/asr1/conf/fbank.conf).
