### ISSUE TITLE
espnet2.bin.asr_inference Speech2Text multiple threads performance is poor

### ISSUE THREAD

**Issue by BarryKCL** [espnet/espnet#3205]
espnet==0.9.7

**Comment by sw005320** [comment]
Could you give me more information about it?

**Comment by BarryKCL** [comment]
> Could you give me more information about it?

Speech2Text is not thread-safe,when I use multiple threads do inference.

**Comment by kamo-naoyuki** [comment]
I don't have any idea for the reason of thread unsafe. All codes of the inference part are written in Python except for PyTorch, so basically such code is thread safe.

Please give more information.

- How did you run asr in multi threads? Could you give minimal reproducible code? 
- How was the result changed?

**Comment by BarryKCL** [comment]
> I don't have any idea for the reason of thread unsafe. All codes of the inference part are written in Python except for PyTorch, so basically such code is thread safe.
> 
> Please give more information.
> 
> * How did you run asr in multi threads? Could you give minimal reproducible code?
> * How was the result changed?

1:
if __name__ == '__main__':
    speech2text = Speech2Text("asr_config.yaml", "valid.acc.ave_10best.pth",
                              "lm_config.yaml","valid.loss.ave_10best.pth",
                              device='cuda',ctc_weight = 0.6,lm_weight = 0.3)

    pool = ThreadPoolExecutor(max_workers=2)
    task_list = []
    wav_path = ["142.wav","3.wav"]

    start = time.time()
    for i in range(10):
        for wav_file in wav_path:
            audio, rate = soundfile.read(wav_file)
            task_id = pool.submit(speech2text,audio)
            task_list.append(task_id)
        wait(task_list, timeout=None, return_when='ALL_COMPLETED')
    print("cost time:",(time.time() - start))
2:
I find thread unsafe in ctc.py line 99:
self.impl = CTCPrefixScoreTH(logp, xlen, 0, self.eos)

So,set ctc_weight = 0.0,multiple threads asr_inference also correct.

**Comment by kamo-naoyuki** [comment]
Thanks.

CTCPrefixScoreTH is written in Python code depending on PyTorch.
Python codes is always thread safe in principle, so if it's not really thread unsafe, it means PyTorch is also thread unsafe.

Could you investigate which function in CTCPrefixScoreTH is thread unsafe?

**Comment by kamo-naoyuki** [comment]
Okay, I understood why CTCPrefixScoreTH is not thread safe. It changes a member field in __call__:

https://github.com/espnet/espnet/blob/08feae5bb93fa8f6dcba66760c8617a4b5e39d70/espnet/nets/ctc_prefix_score.py#L82

I'm not sure the other class doesn't have same bug since I didn't write them. I'll fix it after I check whether all codes are thread safe or not.
