### ISSUE TITLE
controlling pause duration in TTS

### ISSUE THREAD

**Issue by sciai-ai** [espnet/espnet#3209]
Hi,

a) I have trained a TTS model on a custom dataset using tacotron2 + PWG using espnet2 with g2p_en frontend . The synthesis quality is good, but I am unable to introduce long pauses in the audio. I tried by using multiple commas but the effect is the same as using one comma. Is there a way I can  introduce long pauses?

b) for the JSUT model, I have the same question. What symbol is used for pause and how we can increase pause duration?

c) Is it possible to control the duration of each word during inference, for example, cat can become caaaat, so there is a long duration for 'a'?

d) How to fix manual seed to espnet2 tacotron + PWG?

Thank you for your help!

**Comment by sciai-ai** [comment]
@kan-bayashi any comments will be very useful. Thank you

**Comment by kan-bayashi** [comment]
Sorry for the late reply.

a) It depends on the training data. To control the length of pause, we need to carefully clean the data to match the pause length which is corresponding to a single pause symbol. Then, the pause length should be fixed. If the multiple pause symbols do not work, maybe we consider the augmentation of the training data by adding extra pause and pause symbols.

b) In phoneme level `pau`, which is converted from `、`.

c)  A little bit hacky, but you can increase the duration manually if you use fastspeech-like architecture.

d) https://github.com/espnet/espnet/issues/2875

**Comment by sciai-ai** [comment]
Thanks @kan-bayashi 

May I check how can i add new symbol to the token list in TTS. I made a new token ~ to represent silence at beginning of sentences but it is not created in the tokens.txt file during training.
