### ISSUE TITLE
Problem with creating docker image

### ISSUE THREAD

**Issue by alirezadir** [espnet/espnet#321]
When I'm trying to run `./run.sh --docker_gpu 0 --docker_egs chime4/asr1 --docker_folders /export/corpora4/CHiME4/CHiME3 --dlayers 1 --ngpu 1` from docker folder to create a docker image, I get the following error: 
`E: Held packages were changed and -y was used without --allow-change-held-packages.`
I tried adding the flag `--allow-change-held-package` after all `apt-get -y install`s in the  `espnet.devel`, but still getting the same error. I appreciate your help.

**Comment by Fhrozen** [comment]
Hello there, I am wondering about your error. Could you try to prune your docker environment. 
I tried with multiple environments (CentOS & Ubuntu) and I had no problem in the installation.
Could you give me more details about your PC and environment.

**Comment by Fhrozen** [comment]
Hello there, 
You need to add `--allow-change-held-packages` in the `apt-get remove -y libnccl`. This part of the code is the one which is raising the error. I will push a commit with this updates after some additional tests with docker.

**Comment by dneelagiri** [comment]
Hello, I had same issue mentioned above "Held packages" and  followed your recommendation to add --allow-change-help-packages and the script executed without failing at "Held packages" and failed with below error. I tried to install nvidia-docker but still see the same error

sudo ./run.sh --docker_gpu 0 --docker_egs chime4/asr1 --docker_folders /export/corpora4/CHiME4/CHiME3 --dlayers 1 --ngpu 1 
Using image nvidia/cuda:9.0-cudnn7-devel-ubuntu16.04.
Executing application in Docker
NV_GPU='0' nvidia-docker run -i --rm --name espnet_gpu0 -v ~/espnet/egs:/espnet/egs -v ~/espnet/src:/espnet/src -v ~/espnet/test:/espnet/test -v /export/corpora4/CHiME4/CHiME3:/export/corpora4/CHiME4/CHiME3 espnet:cuda9.0-cudnn7-ubuntu16.04 /bin/bash -c 'cd /espnet/egs/chime4/asr1; ./run.sh --dlayers 1 --ngpu 1; chmod -R 777 /espnet/egs/chime4/asr1'
nvidia-docker | 2018/08/06 16:38:14 Error: Could not load UVM kernel module. Is nvidia-modprobe installed?
run.sh done.

Looking forward to hearing from you and appreciate your help!!

**Comment by Fhrozen** [comment]
@dneelagiri I found smth in the net about drivers error (https://github.com/NVIDIA/nvidia-docker/issues/319) Could you please check the link and follow the instructions to check your drivers. 
If the error persist, could you give more details about your environment. I am wondering if you installed nvidia-docker(1) or 2.

**Comment by alirezadir** [comment]
Hi, I added the flag `--allow-change-held-packages`, but now I'm getting the following error (just pasting the tail of the error): 
```
In file included from generic/THTensor.h:1:0,
                 from /espnet/tools/venv/local/lib/python2.7/site-packages/torch/utils/ffi/../../lib/include/TH/THGenerateFloatTypes.h:10,
                 from /espnet/tools/venv/local/lib/python2.7/site-packages/torch/utils/ffi/../../lib/include/TH/THGenerateAllTypes.h:10,
                 from /espnet/tools/venv/local/lib/python2.7/site-packages/torch/utils/ffi/../../lib/include/TH/THTensor.h:11,
                 from /espnet/tools/venv/local/lib/python2.7/site-packages/torch/utils/ffi/../../lib/include/THC/THCTensor.h:4,
                 from /espnet/tools/venv/local/lib/python2.7/site-packages/torch/utils/ffi/../../lib/include/THC/THC.h:13,
                 from /espnet/tools/warp-ctc/pytorch_binding/src/binding.cpp:9:
/espnet/tools/venv/local/lib/python2.7/site-packages/torch/utils/ffi/../../lib/include/TH/generic/THTensor.h:10:16: note: forward declaration of 'THTensor {aka struct THTensor}'
/espnet/tools/venv/local/lib/python2.7/site-packages/torch/utils/ffi/../../lib/include/TH/generic/THTensor.h:10:16: note: forward declaration of 'THTensor {aka struct THTensor}'
 typedef struct THTensor THTensor;
                ^
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
Makefile:37: recipe for target 'warp-ctc' failed
make: *** [warp-ctc] Error 1
The command '/bin/sh -c make venv/lib/python2.7/site-packages/torch USE_VENV=OFF && make warp-ctc USE_VENV=OFF' returned a non-zero code: 2
```

**Comment by Fhrozen** [comment]
@alirezadir I finished some test with docker and I could run voxforge example using cuda9.1. It seems that the docker build employs the cuda folder already installed in your machine. So, if you are trying to install a cuda9.0 into a cuda9.1, it will raise the error that you described. I left the `--docker-cuda flag` in 9.0 for some test, but it is better to set it to your own pc cuda ver. or just leave it blank and the program will detect the cuda ver. installer.

**Comment by alirezadir** [comment]
@Fhrozen thanks for your response. On my own machine (ubuntu 16.04), I have cuda 8.0 with cudnn 5.1.10. I was trying the default values in your run.sh (cuda9.0) when it was throwing that error. 
Now I left the docker_cuda and docker_cudnn empty, but I'm getting the following errors:
`E: Unable to locate package libnccl-dev
E: Unable to locate package libnccl2`

**Comment by Fhrozen** [comment]
That seems to be a problem with the CUDA
 8 Docker container. It seems that it has not installed the nccl libs by default as the CUDA 9+. You need to delete the apt remove from the dockerfile. I will need to test on old version to check if there is any additional problem.

**Comment by alirezadir** [comment]
Yes I realized when I was running `sudo ./run.sh` it couldn't locate my CUDA. So my question is if it's possible to create the docker image with CUDA 9.1 if my current machine has cuda 8.0 or 9.0. Also, I was wondering if cuda 9.0 is not supported (i.e. only 9.1 works)?  Thanks for your help.

**Comment by Fhrozen** [comment]
@alirezadir I tried to do the same, running a docker cuda9.1 in a computer with 9.0 and had some other problems. I am not sure if it may be possible if you add cuda-9-1 in the apt-get install inside the docker container. 
About cuda, any version 7.5+ is supported, so there may be not problem with cuda 9.0

**Comment by alirezadir** [comment]
@Fhrozen I installed cuda 9.1 and cudnn 7 on my machine, and tried the run.sh again, but still it fails on warp-ctc step:
`Step 21/24 : RUN make venv/lib/python2.7/site-packages/torch USE_VENV=OFF && make warp-ctc USE_VENV=OFF
`
...
```
/espnet/tools/venv/local/lib/python2.7/site-packages/torch/utils/ffi/../../lib/include/TH/generic/THTensor.h:10:16: note: forward declaration of 'THTensor {aka struct THTensor}'
 typedef struct THTensor THTensor;
                ^
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
make: *** [warp-ctc] Error 1
[0mMakefile:37: recipe for target 'warp-ctc' failed
```
I appreciate your help.

**Comment by Fhrozen** [comment]
@alirezadir Now that is strange. I just built a docker container with cuda 9.1 4 days ago.
The cuda container 9.1 was built 2 weeks ago. Could you please give details about the docker and docker containers.
I am using a machine with centos 7.0, docker server 17.12-ce and run with the updated version of Espnet. As much as possible, try to prune your docker system just in case.
If this error continues, I am planning on prepare a downloadble docker container on the Docker Hub.

**Comment by alirezadir** [comment]
@Fhrozen Sure, here is my complete log: 
[log4.txt](https://github.com/espnet/espnet/files/2271665/log4.txt)
And here is my system info: 
Ubuntu 16.04 
Cuda compilation tools, release 9.1, V9.1.85
CUDNN 7.0.5
docker 18.06.0-ce
And here is the arguments in the run.sh file: 
```docker_gpu=0
docker_egs=
docker_folders=
docker_cuda=
docker_cudnn=
docker_user=0
ngpu=1 ```
Thanks for your help. It would be great also if you could push an image to dockerhub (with ENTRYPOINT bash).

**Comment by alirezadir** [comment]
@Fhrozen I was able to build the image pulling your latest commit on docker file :)

**Comment by Fhrozen** [comment]
Glad to read that. Just to confirm, could you please test the AN4 and voxforge examples and compare the results? This will help to check the correctness of the docker container.

**Comment by alirezadir** [comment]
Hi @Fhrozen , I was able to run An4 and voxforge examples on my docker. I was wondering which part of results you wanted me to share (training or decoding test)?

**Comment by Fhrozen** [comment]
I would like to know if there is a big difference between the results given by the RESULT files and the obtained by yourself. Just want to confirm that the training and the evaluation works well in docker. I did not have any problem. BTW, we are implementing new docker into a dockerhub repository. More info in #346.
