### ISSUE TITLE
Question about different torch sizes of decoding

### ISSUE THREAD

**Issue by Yixando** [espnet/espnet#3212]
Hi everyone,
I'm new in speech recognition and running now the script in dataset Tedlium2. In the last stage I got a failure feedback and in the decode log it's written as the picture shows. I don't know how to fix it. I really appreciate if someone could help me with this. Thanks in advance!
![RunTimeErrorr](https://user-images.githubusercontent.com/84092118/118011376-3f8ea280-b350-11eb-83b4-f852b3ad518a.PNG)

**Comment by sw005320** [comment]
Could you tell me your situation more exactly?
It would be great if you use our bug report as much as possible.

**Comment by sw005320** [comment]
From the log file, some mismatches of the token vocabulary size happen.
Again, if you give us more information, we can help.

**Comment by Yixando** [comment]
Thanks. I use "train_pytorch_transformer_maskctc.yaml" as train config and "decode_pytorch_transformer_maskctc.yaml" as decode config. The other settings are as same as defaults. The previous stages went normally but the problem happened in the stage 5 which is decoding stage. 
In addition to the task information: the task is ASR training on Tedlium2 using Espnet 0.9.8. The environment  information and the whole decode log is shown below too. I'm not so sure whether these are enough or not. Please tell me if you need more information. Thanks a lot!
![Decode_Log](https://user-images.githubusercontent.com/84092118/118150066-70cfa700-b412-11eb-80ac-5f7e473363c8.PNG)

![Environment](https://user-images.githubusercontent.com/84092118/118149428-d66f6380-b411-11eb-83d7-8197d51c5b4f.PNG)

**Comment by sw005320** [comment]
Thanks for your clarification and thanks for using mask CTC!
@YosukeHiguchi, could you answer it for us?
As I mentioned, there are some token vocabulary size mismatches.

**Comment by YosukeHiguchi** [comment]
Hi @Yixando, thanks for trying Mask-CTC. Current Mask-CTC framework doesn't support decoding with an LM. Can you run the decoding stage without an LM? (i.e., `--skip_lm_training true`)

**Comment by Yixando** [comment]
Thanks a lot for your help! It's working now.
