### ISSUE TITLE
Technical Question about Attention Plots

### ISSUE THREAD

**Issue by szmmm** [espnet/espnet#3216]
Hello, it is me again. I have a small question about the attention weights plotted. What does the color coding stand for? Does a brighter color stand for a higher probability (higher value of the weights)? For example for the following two plots:
![BNE239-XXXXXXXX-XXXXXX-en_MF2XXXX_0151159_0153133_att_ws](https://user-images.githubusercontent.com/64835377/118292399-7b507600-b4d0-11eb-8346-9bee9d0a19be.png)

![BNE239-XXXXXXXX-XXXXXX-en_FF0XXXX_0094419_0095025_att_ws](https://user-images.githubusercontent.com/64835377/118291930-0715d280-b4d0-11eb-9113-0ddf77e11cc6.png)

Am I right to say Figure 1 has much higher entropy compared to Figure 2, as the color coding suggests the attentions weights have smaller value?

Thank you very much

**Comment by szmmm** [comment]
Thank you, I have understood the reasoning behind, so there is no more question about this!

**Comment by 200987299** [comment]
may I ask about how to plot attention for all utt while decoding?

Thanks
