### ISSUE TITLE
Any plans to support Deep Context?

### ISSUE THREAD

**Issue by godzilla-123** [espnet/espnet#3219]
It seems like deep context is an important piece for context biasing in end-to-end models, but I haven't found any open source implementation for it. Is there any plan to implement it in the near future?

**Comment by sw005320** [comment]
Thanks for your suggestion and request.
We haven't worked on this yet and we will not implement it in the near future.
But it is an important topic, and we receive such a request several times, and we will increase the priority if we have more requests.
