### ISSUE TITLE
No module named 'espnet2.enh.decoder'

### ISSUE THREAD

**Issue by nellorebhanuteja** [espnet/espnet#3231]
Hi

I am trying to run the speech enhancement inference script given [here](https://github.com/espnet/espnet_model_zoo#speech-separation).

However, I am getting the following error:
```bash
ModuleNotFoundError: No module named 'espnet2.enh.decoder'
```

I have checked manually for decoder.py, but it doesn't exist.
I have checked in espnet 0.9.9 and 0.9.7 as well.

**Comment by sw005320** [comment]
We're now working on it.
If you check https://github.com/espnet/notebook/pull/19, you can monitor our progress.
We also appreciate it if you give us some feedback.

**Comment by LiChenda** [comment]
hi, @nellorebhanuteja. After the release ` 0.9.10`, now the problem has been solved.
