### ISSUE TITLE
Exists pretrained models for Spanish or German?

### ISSUE THREAD

**Issue by AMG222** [espnet/espnet#3241]
Please, I want to know if there is a pre-trained model in the Sapnish or German language. I was creating an implementation but I need this two languages for make it more accessible in my country. In other case if someone can explain me well how to train one model.  I was looking for some time, but i didn't find any. Thanks

**Comment by akreal** [comment]
Do you ask about ASR or TTS? My answer is about ASR.
You can get pre-trained ESPnet1 German model from here: https://drive.google.com/file/d/13tnsp2tzxZ4K8aAU2-qTy2rz7g8CM-7G/view?usp=sharing
It is trained using slightly modified Kaldi recipe: https://github.com/uhh-lt/kaldi-tuda-de
If you need ESPnet2 model, you can try to borrow data preparation scripts from that recipe and re-use some existing ESPnet2 recipe, e.g. LibriSpeech.

**Comment by AMG222** [comment]
Nop, for now I'm looking for the TTS model, but thanks if I need to add it in the future it will be helpful

**Comment by AMG222** [comment]
If it is not possible, exists is a translation English-Spanish English-German in espnet for TTS?

**Comment by sw005320** [comment]
@AMG222, I can answer your original questions.
We have pre-trained Spanish/German TTS models in https://drive.google.com/drive/folders/1omfaZppwtRzncZq_TKu-lC1cN0expFcd in espent1 based on https://github.com/espnet/espnet/tree/master/egs/m_ailabs/tts1

**Comment by AMG222** [comment]
Thank you so much, tomorrow i will check it out but seems good

**Comment by AMG222** [comment]
How can I use it, when I choose the model in my code I use:
`tc="fastspeech2/FastSpeech2/exp/tts_train_gst+xvector_conformer_fastspeech2_transformer_teacher_raw_phn_tacotron_g2p_en_no_space/config.yaml"
            mf="fastspeech2/FastSpeech2/exp/tts_train_gst+xvector_conformer_fastspeech2_transformer_teacher_raw_phn_tacotron_g2p_en_no_space/train.loss.ave_5best.pth"`
As is in the colab I choose the train configuration and the model file, but for that part of espnet i can't find the model file with the .pth extension.
I need to use the old espnet1, because this version uses other configuration?

**Comment by sw005320** [comment]
Yes, you need to use espnet1.

**Comment by AMG222** [comment]
Here I have an error when I launch the espnet1 as the colab of espnet1 with the correct path
`Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/home/netipc/Documents/espnet/main2.py", line 12, in loadModel
    loadModelv5(q, trans_type, dict_path, model_path, vocoder_tag)
  File "/home/netipc/Documents/espnet/main2.py", line 50, in loadModelv5
    model = model_class(idim, odim, train_args)
  File "/usr/local/lib/python3.7/dist-packages/espnet-0.9.9-py3.7.egg/espnet/nets/pytorch_backend/e2e_tts_transformer.py", line 520, in __init__
    TTSInterface.__init__(self)
  File "/usr/local/lib/python3.7/dist-packages/espnet-0.9.9-py3.7.egg/espnet/nets/tts_interface.py", line 36, in __init__
    self.reporter = Reporter()
TypeError: 'NoneType' object is not callable
`
Please, if someone know how to solve it, help me.
Thanks

**Comment by sw005320** [comment]
Did you correctly set `model_path`?
Could you check `idim`, `odim`, and `train_args` look normal?

**Comment by AMG222** [comment]
idim:  `46`
odim:  `80`
train_args:  `Namespace(accum_grad=1, aconv_chans=32, aconv_filts=15, adim=128, atype='location', backend='pytorch', batch_bins=2428800, batch_count='auto', batch_frames_in=0, batch_frames_inout=0, batch_frames_out=0, batch_size=0, batch_sort_key='input', bce_pos_weight=1.0, cbhg_conv_bank_chans=128, cbhg_conv_bank_layers=8, cbhg_conv_proj_chans=256, cbhg_conv_proj_filts=3, cbhg_gru_units=256, cbhg_highway_layers=4, cbhg_highway_units=128, config='conf/tuning/train_pytorch_tacotron2.v3.yaml', config2=None, config3=None, cumulate_att_w=1, debugmode=1, dlayers=2, dropout_rate=0.5, dunits=1024, early_stop_criterion='validation/main/loss', econv_chans=512, econv_filts=5, econv_layers=3, elayers=1, embed_dim=512, epochs=200, eps=1e-06, eunits=512, grad_clip=1, guided_attn_loss_lambda=1.0, guided_attn_loss_sigma=0.4, keep_all_data_on_mem=False, lr=0.001, maxlen_in=100, maxlen_out=200, minibatches=0, model_module='espnet.nets.pytorch_backend.e2e_tts_tacotron2:Tacotron2', ngpu=1, num_iter_processes=0, num_save_attention=5, opt='adam', outdir='exp/es_ES_karen_train_trim_pytorch_train_pytorch_tacotron2.v3/results', output_activation=None, patience=0, postnet_chans=512, postnet_filts=5, postnet_layers=5, prenet_layers=2, prenet_units=256, preprocess_conf=None, reduction_factor=1, report_interval_iters=100, resume=None, save_interval_epochs=1, seed=1, sortagrad=0, spc_dim=None, spk_embed_dim=None, tensorboard_dir='tensorboard/es_ES_karen_train_trim_pytorch_train_pytorch_tacotron2.v3', train_json='dump/es_ES_karen_train_trim/data.json', use_batch_norm=1, use_cbhg=False, use_concate=1, use_guided_attn_loss=1, use_masking=1, use_residual=0, use_second_target=False, use_speaker_embedding=False, valid_json='dump/es_ES_karen_dev_trim/data.json', verbose=0, weight_decay=0.0, zoneout_rate=0.1)`

**Comment by sw005320** [comment]
Thanks.
It looks normal and it might cause some issues related to the version difference, but not sure.
@kan-bayashi, could you give us some suggestions?

**Comment by AMG222** [comment]
It's been a week, how's the issue going?

**Comment by AMG222** [comment]
Now I find the solution, It was the trans_path that changes the word so much

**Comment by neuronx1** [comment]
@sw005320 Thanks for your work. I wanted to ask where I find the pretrained german vocoder. That would really help me.

**Comment by sw005320** [comment]
Actually, I don't know.
@kan-bayashi, can you answer it?

**Comment by kan-bayashi** [comment]
You can find `hui_acg_hokuspokus_parallel_wavegan.v1`, which is German female model.
https://github.com/kan-bayashi/ParallelWaveGAN#results

**Comment by neuronx1** [comment]
Thank you very much @kan-bayashi.
Do you know if this vocoder is compatible with the german female text to mel model provided here: https://github.com/espnet/espnet/tree/master/egs/m_ailabs/tts1

**Comment by kan-bayashi** [comment]
The recording quality of mailabs is not good and it is 16khz so you cannot use.
You can use HUI-ACG corpus pretrained models.
https://github.com/espnet/espnet/tree/master/egs2/hui_acg/tts1#pretrained-models

**Comment by neuronx1** [comment]
Thank you very much!
