### ISSUE TITLE
Expected 4-dimensional input for 4-dimensional weight with my own reference speech wav file

### ISSUE THREAD

**Issue by zubairahmed-ai** [espnet/espnet#3247]
In the Synthesis section of your [colab](https://colab.research.google.com/github/espnet/notebook/blob/master/espnet2_tts_realtime_demo.ipynb#scrollTo=o87zK1NLobne) when I try with my own wav file it gives me the following error

```
Input your favorite sentence in English.
The officer passed away following a traffic accident that he was exposed to while carrying out his duties and job duties on Mleiha Road.
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-16-ef907013696a> in <module>()
      6 with torch.no_grad():
      7     start = time.time()
----> 8     wav, c, *_ = text2speech(x, speech=speech, spembs=spembs)
      9     wav = vocoder.inference(c)
     10 rtf = (time.time() - start) / (len(wav) / fs)

13 frames
/usr/local/lib/python3.7/dist-packages/torch/nn/modules/conv.py in _conv_forward(self, input, weight, bias)
    394                             _pair(0), self.dilation, self.groups)
    395         return F.conv2d(input, weight, bias, self.stride,
--> 396                         self.padding, self.dilation, self.groups)
    397 
    398     def forward(self, input: Tensor) -> Tensor:

RuntimeError: Expected 4-dimensional input for 4-dimensional weight [32, 1, 3, 3], but got 5-dimensional input of size [1, 1, 1607, 2, 80] instead
```

**Basic environments:**
[you Google Colab](https://colab.research.google.com/github/espnet/notebook/blob/master/espnet2_tts_realtime_demo.ipynb#scrollTo=o87zK1NLobne)
 

**Task information:**
 - Task: TTS
 - ESPnet2

**To Reproduce**
1. supply a wav file
2. execute the Synthesis section

**Comment by sw005320** [comment]
Did you use the mono audio with the correct sampling rate?
Could you give us your audio information by using `soxi` or whatever?

**Comment by zubairahmed-ai** [comment]
Thanks @sw005320 for the tip, I recorded my voice using mono channel at 24100Hz instead of stereo and 44Khz to try this out. But the cloned voice doesn't sound like me at all.

**Comment by kan-bayashi** [comment]
Which model did you use?
If you use `xvector` based model(or `gst+xvector`), the reference speech is used to extract only for speaking style (not speaker characteristics).
If you want to change the speaker characteristics, you need to extract `xvector` from your speech.
But unfortunately this function is not supported in demo.
Another option is to use only `gst` model. This can reflect your speaker characteristics but the speaker modeling performance is less than `xvector` model.

**Comment by zubairahmed-ai** [comment]
> If you want to change the speaker characteristics, you need to extract xvector from your speech.
But unfortunately this function is not supported in demo.

Yes this is what I was looking to do

> Another option is to use only gst model. This can reflect your speaker characteristics but the speaker modeling performance is less than xvector model.

Please share how to do this?

**Comment by kan-bayashi** [comment]
Try GST-based model.
e.g. `kan-bayashi/vctk_gst_transformer` and `vctk_parallel_wavegan.v1.long`.

**Comment by zubairahmed-ai** [comment]
Thanks @kan-bayashi, will try this now, does this automatically extract speaker characteristics, or does it need some code changes too?

**Comment by kan-bayashi** [comment]
Just changing the reference speech is OK.

**Comment by zubairahmed-ai** [comment]
Thanks, tried with a obama speech reference, doesn't sound like him :(

**Comment by zubairahmed-ai** [comment]
Here's a sample with Obama voice with generated output [obama_gen.zip](https://github.com/espnet/espnet/files/6567985/obama_gen.zip)

**Comment by kan-bayashi** [comment]
`spembs=None` is OK.

**Comment by zubairahmed-ai** [comment]
Still it picks up random speakers from the training set, not my own voice @kan-bayashi

**Comment by kan-bayashi** [comment]
That is a kind of limitation of GST-based model.
It is difficult to generalize the all possible speaker with the GST-based model.

**Comment by zubairahmed-ai** [comment]
Thanks, whats the requirement to train my own ESPNet2 model, how much training data do I need to clone a voice properly or close to it? where are the steps documented?

**Comment by kan-bayashi** [comment]
Please check the following README.
https://github.com/espnet/espnet/blob/master/egs2/TEMPLATE/tts1/README.md

Maybe the recommended steps are:
- Run sample recipes to understand the steps
- Make your own recipe
- Try fine-tuning

**Comment by zubairahmed-ai** [comment]
Thanks @kan-bayashi

**Comment by zubairahmed-ai** [comment]
@kan-bayashi Sofar what I learned that if I need a model for 1 speaker I should use FastSpeech2, it would also extract speaker embeddings and would clone the voice
If I want a more than one speaker then use multi-speaker model with x-vector training.
My question also is, does the single speaker model by default extracts x-vector or speaker embeddings?

**Comment by kan-bayashi** [comment]
> it would also extract speaker embeddings and would clone the voice?
> My question also is, does the single speaker model by default extracts x-vector or speaker embeddings?

As a default, we do not use extra embedding for a single-speaker.

**Comment by zubairahmed-ai** [comment]
So how will single speaker clone voice sound like?

**Comment by kan-bayashi** [comment]
Sounds like the speaker.
You can try single speaker model in the demo, which does not use speaker embedding.

**Comment by zubairahmed-ai** [comment]
Ok it sounds like the speaker but without prosody

**Comment by kan-bayashi** [comment]
Prosody should be modeled with the single speaker model, but it depends on architecture, input representation, and so on.

**Comment by zubairahmed-ai** [comment]
Ok I think I should try both. Still finding it hard to understand training steps and required custom data and structure, I will post a question about it separately that I hope you can answer

Thanks for your help

**Comment by zubairahmed-ai** [comment]
@kan-bayashi How up to date is [this documentation](https://espnet.github.io/espnet/notebook/tts_cli.html)?
