### ISSUE TITLE
Typo in espnet2/tts/transformer.py

### ISSUE THREAD

**Issue by Hiroshiba** [espnet/espnet#3250]
**Describe the bug**
I found a typo in this line.
https://github.com/espnet/espnet/blob/4a60d8f39e9872b345bb3b32cf227832985b661d/espnet2/tts/transformer.py#L364
`init_dec_alpha=init_dec_alpha,` isn't it?

**Task information:**
 - Task: TTS
 - ESPnet2

**Comment by sw005320** [comment]
Thanks, @Hiroshiba!
I think you're right.

**Comment by kan-bayashi** [comment]
Thank you for your pointing, @Hiroshiba.
That is my mistake.
