### ISSUE TITLE
using cache in transducer tsd 

### ISSUE THREAD

**Issue by sanzimu** [espnet/espnet#3253]
the cache operation will cause duplicate character to appear in [https://github.com/espnet/espnet/blob/master/espnet/nets/beam_search_transducer.py](url) 271 line self.decoder.batch_score.
Is this trick for speed  or is it a bug

**Comment by b-flo** [comment]
Hi,

Can you give us more information please? I'm not sure I understand the issue.

Caching is performed in all beam search methods when we create new hypothesis/hypotheses, to avoid repeating evaluation/computation for same sequences. Pruning or duplication check is not performed in `batch_score(...)` and it's algorithm-dependant.

**Comment by sanzimu** [comment]
@b-flo  Thanks for reply. In max_sym_exp hyps expansion steps, the batch_score() func do the g_u = pred(g_u-1,y_u-1) operation and then out = joint_network(g_u,h_t). Will get the result of  g_u = g_u-1 , out = joint_network(g_u-1,h_t) when using cache ？why don't using g_u = pred(g_u-1,y_u-1)  with cached hypothesis and get new state ？Thanks

**Comment by b-flo** [comment]
> Will get the result of g_u = g_u-1 , out = joint_network(g_u-1,h_t) when using cache ? why don't using g_u = pred(g_u-1,y_u-1) with cached hypothesis and get new state ？Thanks

Hum, I think there is some confusion.
`cache` contains pre-computed `g_{u}` (decoder representation) for already seen `y_{u-1}`, Given a batch of hypothesis, we will compute `pred(y_{u-1}, g_{u-1})` for each hypotheses not found in `cache`. Final batch `g_{u}` will be constructed based on previous computation and the set of representation given by `cache`.

Also, I'm not sure I understand why it's an issue for TSD specifically as the same thing is done for ALSD and NSC. Am I missing something?

**Comment by sanzimu** [comment]
Thanks for correcting me 

> Also, I'm not sure I understand why it's an issue for TSD specifically as the same thing is done for ALSD and NSC. Am I missing something?

I don't  implement ALSD and NSC , so i didn't pay attention to their details

**Comment by b-flo** [comment]
> I don't implement ALSD and NSC , so i didn't pay attention to their details

OK thanks, I thought it was an issue with TSD specifically!

I'm closing the issue, feel free to re-open if you have following questions.
