### ISSUE TITLE
setup token_type=phn with g2p=none get error

### ISSUE THREAD

**Issue by wac81** [espnet/espnet#3254]
> `token_type=phn` with `g2p = none` indicates splitting by space: e.g. `bai2 wan4 yi4 liao2` -> `bai2, wan4, yi4, liao2`
> 
> https://github.com/espnet/espnet/blob/master/espnet2/text/phoneme_tokenizer.py#L103-L104
> 
> `token_type=char` is character level. e.g. `百万医疗` -> `百, 万, 医, 疗`

@kamo-naoyuki
are you sure 
`token_type=phn with g2p = none`
because i get error :
```
 File "/usr/local/lib/python3.6/dist-packages/espnet2/text/build_tokenizer.py", line 54, in build_tokenizer
    raise ValueError("g2p_type is required if token_type=phn")
ValueError: g2p_type is required if token_type=phn
```
and i found out code in build_tokenizer.py conflict
```
    elif token_type == "phn":
        if g2p_type is None:
            raise ValueError("g2p_type is required if token_type=phn")
```

**Comment by wac81** [comment]
mostly like version issue, let me check it

**Comment by kamo-naoyuki** [comment]
If token_type=phn with g2p=none , it doesn't work as it said. Please speacify g2p type.

**Comment by kamo-naoyuki** [comment]
Sorry, I forgot about g2p = none indicates splitting by space.
Your espnet version is old simply. See https://github.com/espnet/espnet/blob/master/espnet2/text/build_tokenizer.py
