### ISSUE TITLE
Speed alpha parameter in sythesize method for FastSpeech2 TTS

### ISSUE THREAD

**Issue by airenas** [espnet/espnet#3256]
**Now:** 

the *speed_control_alpha* parameter is configurable in Text2Speech class constructor. https://github.com/espnet/espnet/blob/39032a3011ecaa7b4fc0bc60979e3933835d2aea/espnet2/bin/tts_inference.py#L63

---

**Problem**: 

I'm successfully serving FastSpeech2 model using the Text2Speech class. The model is loaded into GPU memory once and serving many incoming web requests. I need implement a possibility to slower or speed up a speech. The current implementation would require recreate Text2Speech with different *speed_control_alpha*.

---

**Suggestion**: 

Add *speed_control_alpha* into the synthesize method: https://github.com/espnet/espnet/blob/39032a3011ecaa7b4fc0bc60979e3933835d2aea/espnet2/bin/tts_inference.py#L127 
If not provided here it could use the default one from the constructor, otherwise use the provided one.

---

I could provide a pull-request if you see a suggestion useful.

**Comment by sw005320** [comment]
That sounds like a reasonable option for me.
@kan-bayashi, what do you think?

**Comment by kan-bayashi** [comment]
Sorry for the late reply.
That seems reasonable, but be careful about the compatibility with the other models.
