### ISSUE TITLE
Transformer Decoding

### ISSUE THREAD

**Issue by zelabean** [espnet/espnet#3265]
Hello

I'm Using Transformers Decoder for Speech Recognition

I want Decoding with out beam search when inference or validation step.

It can perform just using beam_size=1?

Decoding is too slow...

**Comment by sw005320** [comment]
> It can perform just using beam_size=1?

Yes.

> Decoding is too slow...

Sorry that some of the recipes try to tune some search parameters to obtain the best performance by sacrificing speed.
In most cases, beam size = 5 or 10 would be good enough to get reasonable performance with relatively fast inference.

**Comment by zelabean** [comment]
Thank you for advice!
