### ISSUE TITLE
Can the WER/ACC figures reflect the final WER score?

### ISSUE THREAD

**Issue by tinghua-code** [espnet/espnet#3266]
I trained two models, they have similar patterns and values in the generated WER/ACC figures (as shown). But the final results are quite different. For Librispeech, the test_clean without LM one is 4.1, the other is 10.0. Is it normal? I use the same code for decoding. 
<img width="650" alt="Screen Shot 2021-06-02 at 3 20 13 PM" src="https://user-images.githubusercontent.com/36933028/120559530-104edc80-c3b6-11eb-9d08-864ca57963c2.png">

**Comment by sw005320** [comment]
Hmm, usually, if the validation score (acc, loss, error rate) is similar, the final decoding performance becomes similar.
So, it looks strange to me.
Can you tell me the breakdown of the word error rate (insertion, deletion, substitution)?
Also, typical mistakes are 1) forgot to model averaging 2) perform decoding with a training mode (then dropout etc. degrade the performance).

**Comment by tinghua-code** [comment]
The complete scores are below. 
<img width="884" alt="Screen Shot 2021-06-02 at 4 52 18 PM" src="https://user-images.githubusercontent.com/36933028/120566455-1fd52200-c3c4-11eb-9df0-1b7bc8469a68.png">
<img width="899" alt="Screen Shot 2021-06-02 at 4 59 09 PM" src="https://user-images.githubusercontent.com/36933028/120566454-1e0b5e80-c3c4-11eb-8977-605394e163e9.png">
The cmd I used for decoding is: .
```
/run_clean.sh --stage 1 --stop-stage 13 --ngpu 1  --skip_train true --use_lm false \
--asr_args "--batch_bins 400000000 --max_epoch 150 --scheduler_conf warmup_steps=22000 --optim_conf lr=0.005" \
--asr_config conf/tuning/train_asr_conformer_S.yaml \
--gpu_inference true --inference_nj 2;
```
