### ISSUE TITLE
How can I use "--init_param <file_path>:<src_key>:<dst_key>:<exclude_keys>" in espnet2.bin.asr_train?

### ISSUE THREAD

**Issue by PhyllisJi** [espnet/espnet#3267]
I follow the instruction in https://espnet.github.io/espnet/espnet2_training_option.html?highlight=fine%20tuning .
In espnet2.bin.asr_train.py  and espnet2.tasks.asr.py files, I can not find this parameter. 
So when I want to  fine tuning the pretrained model, it will report an error that this parameter cannot be recognized.

**Comment by XiaoJiQingZhou** [comment]
Sorry, unrecognized arguments are "required" and "distributed" in config.yaml. 
Can I just comment out these lines ?

**Comment by guoaoo** [comment]
--init_param <file_path>:<src_key>:<dst_key>:<exclude_keys>
https://github.com/espnet/espnet/blob/2ae70a1fd0e7f7a24a8ed41e55b87126ffb26bd0/espnet2/bin/asr_train.py#L19
https://github.com/espnet/espnet/blob/2ae70a1fd0e7f7a24a8ed41e55b87126ffb26bd0/espnet2/tasks/asr.py#L122
https://github.com/espnet/espnet/blob/2ae70a1fd0e7f7a24a8ed41e55b87126ffb26bd0/espnet2/tasks/abs_task.py#L589-L608

Maybe you should use
`python3 -m espnet2.bin.asr_train xxx  --init_param xxx`
