### ISSUE TITLE
Which epoch does train.loss.ave.pth refer to?

### ISSUE THREAD

**Issue by guoaoo** [espnet/espnet#3268]
After training a model, have some .pth in train folder, and I find 
`train.loss.ave.pth` link to `train.loss.ave_5best.pth`, 
which epoch does train.loss.ave.pth refer to? 
e.g. `train.loss.best.pth -> 322epoch.pth`, 
sorry I dont find an explanation in the document so open this issue😢

**Comment by danoneata** [comment]
The model `train.loss.ave_5best` is created by averaging the from multiple epochs: the n-best models (in this case n = 5 and best is decided based on the loss). The function performing this step is [`average_nbest_models.py`](https://github.com/espnet/espnet/blob/master/espnet2/main_funcs/average_nbest_models.py).

**Comment by guoaoo** [comment]
> The model `train.loss.ave_5best` is created by averaging models from _multiple_ epochs: the n-best models (in this case n = 5 and best is decided based on the loss). The function performing this step is [`average_nbest_models.py`](https://github.com/espnet/espnet/blob/master/espnet2/main_funcs/average_nbest_models.py).

Thank you so much! I will read this code and close this issue.
