### ISSUE TITLE
How to get tensors instead of texts when using ASR?

### ISSUE THREAD

**Issue by CHRIBUR0309** [espnet/espnet#3270]
I found here just a few days ago and I'd like to use it. I want to get tensors from a hidden layer instead of outputted texts when using ASR. How to do it?

**Comment by sw005320** [comment]
We don't have such options and you need to implement them by yourself.
You can write it with the usual numpy functions or you can use some `Writer` functions (https://github.com/espnet/espnet/search?q=Writer)
