### ISSUE TITLE
How to calculate RTF in espnet2?

### ISSUE THREAD

**Issue by Shengqiang-Li** [espnet/espnet#3272]
Excuse me, I need to calculate the RTF in egs2/aishell/asr1, is there some scripts in espnet2 can do this?

**Comment by sw005320** [comment]
We don't have such a function and people usually calculate it based on the log.
But I see that it is an important function, and some people already have such functions.
I just added a feature request tag, we will consider implementing it in the future.

**Comment by espnetUser** [comment]
@sw005320: I am currently looking into 
https://github.com/espnet/espnet/blob/master/utils/calculate_rtf.py
to make it work for espnet2. Has there been any work done on this topic already?

**Comment by sw005320** [comment]
No, we don't have any work for this.

**Comment by sw005320** [comment]
Thanks a lot!
