### ISSUE TITLE
Make DatadirWriter file handle flush by line?

### ISSUE THREAD

**Issue by tjysdsg** [espnet/espnet#3276]
[Currently](https://github.com/espnet/espnet/blob/master/espnet2/fileio/datadir_writer.py#L56), the file handler is initialized using default arguments which set [`buffering`](https://docs.python.org/3/library/functions.html#open) to `-1`, which means the contents are buffered first before writing to disk. In practice, I noticed a10 mins delay on my training server.

It would be nice if the data writer can flush the content to file eagerly so that if the program stops abruptly, the results are saved.

So
```python
if self.fd is None:
    self.path.parent.mkdir(parents=True, exist_ok=True)
    self.fd = self.path.open("w", encoding="utf-8")
```
should be 
```python
if self.fd is None:
    self.path.parent.mkdir(parents=True, exist_ok=True)
    self.fd = self.path.open("w", encoding="utf-8", buffering=1)
```
or maybe we can set the buffer size to something smaller than the default size.

I'm not sure how much impact it would have on the performance, but it might require some testing (I'm not sure which components use this class).

**Comment by kamo-naoyuki** [comment]
What is problem for you? It's normal behavior for output stream in many programs.

**Comment by tjysdsg** [comment]
Well it's not a very significant problem, I just wanted to have the results written to disk immediately. I haven't set up the clusters correctly and for some reason, I cannot decode using multiple processes. Therefore, the inference is quite slow, that's why I wanted to have the results immediately.
