### ISSUE TITLE
Question about ESPnet model deployment

### ISSUE THREAD

**Issue by AshrafMahdhi** [espnet/espnet#3277]
Hi @sw005320,
I want to deploy my ESPnet model using `espnet_model_zoo` but didn't know how to adapt my mgb2 model.
my `config.yaml` (of mgb2 model ) didn't have the same parameters as in the pre-trained models in [](https://zenodo.org/record/). 
Can you help me, please?

**Comment by sw005320** [comment]
`espnet_model_zoo` is only available in espnet2 and we don't have a conversion from espnet1 models to espnet2 models, unfortunately.
What I would like to suggest is to port an mgb2 recipe from espnet1 to espnet2 and train a model from scratch.
This porting is straightforward.

**Comment by AshrafMahdhi** [comment]
thank you @sw005320 for your quick answer! 
I will try!
Is there any easier way to deploy for your knowledge?!

**Comment by sw005320** [comment]
Maybe you can refer https://espnet.github.io/espnet/espnet2_tutorial.html#recipes-using-espnet2 and https://github.com/espnet/espnet/tree/master/egs2/TEMPLATE
