### ISSUE TITLE
what is architecture using rnn-transducer can use  for streaming in production?

### ISSUE THREAD

**Issue by trangtv57** [espnet/espnet#3279]
tks for great project.
i read a lot of paper of alexa amazon. And they use rnn encoder + rnn transducer in their production. But in their paper, they have many custom for optimization in decode and rescore phase to move it to production. And i wonder can i use espnet for build model using rnn-t and rnn encoder like this for my production. 
my question can be weird because im new in espnet. tks you.

**Comment by b-flo** [comment]
Hi,

I apologize for the very late answer. Could you share the papers you're talking about please? There are several paper on transducer models from Amazon, with different directions for improvement. 

ESPnet's transducer models could be used in production for offline decoding as performance and decoding speed are currently acceptable. Depending on the objectives, additional work may be needed such as porting some operations to C++ level, making current architecture quantization compatible, etc.

Concerning streaming transducer, I need to sort out some things before that but it'll be my focus in the near future.

**Comment by trangtv57** [comment]
tks for reply,
I follow [personalization-strategies-for-end-to-end-speech-recognition-systems](https://assets.amazon.science/7e/b7/58b36b8143a3bd504b784e6d30a3/personalization-strategies-for-end-to-end-speech-recognition-systems.pdf ). They have shallow fusion with FST for personalize noun, and rescore. But i care about how we can use this rnn tranducer + FST for streaming version.
Thanks you

**Comment by b-flo** [comment]
There is no plan to add the proposed approach for now but I may take a look after wFST decoding with k2 is added to ESPnet.
For now my main focus will be on adding streaming capacity for our transducer models. I can't give an ETA though, I need to sort some things before that.

**Comment by trangtv57** [comment]
tks @b-flo.
