### ISSUE TITLE
Using WaveGlow Vocoder with output of Text2Speech in TTS inference

### ISSUE THREAD

**Issue by Tirthankar-iiitb** [espnet/espnet#3295]
Hi,
I have trained a WaveGlow Vocoder with my own data corpus. I also trained a TTS model (ESPnet FastSpeech2) using the same corpus. As the Mel params differ, I get pure noise outputs. I need to know how I can have Text2Speech generate Mel outputs which I can use as input to my Vocoder.  

However, I checked with pretrained parallel_wavegan model ("ljspeech_parallel_wavegan.v1") with my TTS model and that works ok (with some amount of noise though).

I checked with the Text2Speech module and I find a dict param 'vocoder_conf' where perhaps I should be able to define the Mel details as required by my Vocoder. But, not sure how. Is there any example?

Do I need to retrain the TTS model?

I followed egs2 tts1 LJspeech recipe with my data corpus for the FastSpeech2 training. 

The relevant WaveGlow config are: 
"data_config": {
        "training_files": "train_files.txt",
        "segment_length": 16000,
        "sampling_rate": 22050,
        "filter_length": 1024,
        "hop_length": 256,
        "win_length": 1024,
        "mel_fmin": 0.0,
        "mel_fmax": 8000.0
    },
"waveglow_config": {
        "n_mel_channels": 80,
        "n_flows": 12,
        "n_group": 8,
        "n_early_every": 4,
        "n_early_size": 2,
        "WN_config": {
            "n_layers": 8,
            "n_channels": 256,
            "kernel_size": 3
        }
    }

Please advise.

Thanks/Tirthankar.
__________________

**Comment by kan-bayashi** [comment]
Maybe log basis is different.
You can refer this comment (this is inverse of what you want to do).
https://github.com/kan-bayashi/ParallelWaveGAN/issues/169#issuecomment-649320778
