### ISSUE TITLE
attention weights to decide CTC window in ctc_prefix_score

### ISSUE THREAD

**Issue by dangvansam98** [espnet/espnet#3307]
how can i use attention_weights to calculate start and end CTC window when decoding? like in [espnet/espnet/blob/master/espnet/nets/ctc_prefix_score.py](https://github.com/espnet/espnet/blob/master/espnet/nets/ctc_prefix_score.py)

thanks!

**Comment by sw005320** [comment]
You can refer to Section 3.3 in https://isca-speech.org/archive/Interspeech_2019/pdfs/2860.pdf

**Comment by dangvansam98** [comment]
> You can refer to Section 3.3 in https://isca-speech.org/archive/Interspeech_2019/pdfs/2860.pdf

Thanks for your response. I have read that paper, but can you tell me more clearly how this att_w is calculated and how much is its dimension?

**Comment by sw005320** [comment]
Sorry, I may not fully understand the questions, but my answers are below.

> how this att_w is calculated
Hybrid CTC/attention methods first compute the attention-based encoder-decoder. The attention weight comes from this computation.
For example, `att_w` computed in https://github.com/espnet/espnet/blob/dea57c52cd74d61e8838e492e564848691ab793c/espnet/nets/pytorch_backend/rnn/decoders.py#L778 is used in https://github.com/espnet/espnet/blob/dea57c52cd74d61e8838e492e564848691ab793c/espnet/nets/pytorch_backend/rnn/decoders.py#L825-L826

> how much is its dimension
If you're talking about the dimension of the feed-forward network in the attention mechanism, you can find it by checking `adim` in espnet1. It usually 256 or 512. If you're talking about the size of the attention weight, that is the length of the encoder sequence (subsampled length of the original input feature sequence).

**Comment by dangvansam98** [comment]
ok. thank you. that's what i need
