### ISSUE TITLE
index out of range error

### ISSUE THREAD

**Issue by shubham-IISc** [espnet/espnet#331]
Hello everyone! I was just running the chime5 baseline without making any changes.
During decoding, I am getting the following error:
![e](https://user-images.githubusercontent.com/35381101/43840720-f91c0c24-9b3e-11e8-8a46-d52be3d97f19.png)

Can someone please help me with this error. I tried but could not figure out that what exactly has went wrong.

Thanks

**Comment by sw005320** [comment]
Which version of pytorch are you using?

**Comment by shubham-IISc** [comment]
thanks a lot. i got it resolved. I reinstalled pytorch and then it did not come.
