### ISSUE TITLE
TTS improving Intonation for sentences ending with ? or !

### ISSUE THREAD

**Issue by sciai-ai** [espnet/espnet#3313]
I have been suing espnet recipes for TTS successfully. However I have noticed that the intonation does not change much especially for ? or  !

**Comment by sciai-ai** [comment]
@kan-bayashi I am looking at the Text2Speech class in tts_inference.py, I am using a Fastspeech2 model. I am aunable to find the pitch and durations vectors estimated. Can you help me identify how can i output the pitch and duration vectors that were used during synthesis. I am thinking if I can modify them to have some control over the speech synthesis.

**Comment by kan-bayashi** [comment]
> However I have noticed that the intonation does not change much especially for ? or !

Actually, I have no idea why the symbol has not so much effect.
@r9y9 Do you have any idea?

> For some use cases it would be very useful to have finer control on the synthesis output, for example, to be able to change the pitch or duation at a phoneme level. Similar functionality is implemented by Fastpitch nvidia github, is it possible to modify the fastpitch2 is espnet to support user supplied pitch/ time values?

This change is relative easy. I can add the option.

**Comment by r9y9** [comment]
That behavior depends on the dataset. If the database does not have a diversity of intonations regarding "!" and "?", these symbols would have little impact on the generated intonations.

**Comment by sciai-ai** [comment]
> > However I have noticed that the intonation does not change much especially for ? or !
> 
> Actually, I have no idea why the symbol has not so much effect.
> @r9y9 Do you have any idea?
> 
> > For some use cases it would be very useful to have finer control on the synthesis output, for example, to be able to change the pitch or duation at a phoneme level. Similar functionality is implemented by Fastpitch nvidia github, is it possible to modify the fastpitch2 is espnet to support user supplied pitch/ time values?
> 
> This change is relative easy. I can add the option.

That will be great, when can we expect this feature. I tried at my end as well but could only successfully scale the pitch up and down but not phoneme level. The pitch tensor is (1,Tmax,att_dim=384)

**Comment by sciai-ai** [comment]
@r9y9 How can one design a good TTS training dataset then to ensure it covers well the intonations?

**Comment by Freddy-pp** [comment]
> This change is relative easy. I can add the option.

@kan-bayashi, could it be possible to change the pitch and duration for a word, or even for a single token (phoneme)? This will probably help control the emphasis (sentence stress). That would be great if you add this option. Thanks.
