### ISSUE TITLE
Question about phone length does not match the pitch and energy lengths in Fastspeech2

### ISSUE THREAD

**Issue by Adliyan** [espnet/espnet#3318]
I used espnet2 to train the fastspeech2 model, but got an error like this.the input phone length does not match the pitch and energy lengths. I checked the input parameters of fastspeech2 and found that the pitch, energy, and duration lengths are T+1,Where did the +1 come from？

  File "/espnet/espnet2/tts/fastspeech2.py", line 472, in forward
    xs, ilens, ys, olens, ds, ps, es, spembs=spembs, is_inference=False
  File "/espnet/espnet2/tts/fastspeech2.py", line 575, in _forward
    hs = hs + e_embs + p_embs
RuntimeError: The size of tensor a (69) must match the size of tensor b (68) at non-singleton dimension 1
fastspeech2

There is such a piece of code in the fastspeech2 model, which causes the time length of text to change from T to T+1, why the length of pitch and duration is T+1？

`x

xs = F.pad(text, [0, 1], "constant", self.padding_idx)
 
 for i, l in enumerate(text_lengths):
       xs[i, l] = self.eos
       ilens = text_lengths + 1`

 Thanks in advance

**Comment by kan-bayashi** [comment]
+1 comes from `<eos>` token. You can add 0.

**Comment by talal-sen** [comment]
Why do we need the `eos` token, is it Different from `.` token?

**Comment by sciai-ai** [comment]
Why do we need the eos and sos tokens. Is the effect of eos different from '.' token?

**Comment by kan-bayashi** [comment]
sos is not used.
I think eos is similar but we have various language text.
Actually I have never compared w/ and w/o eos symbol.

**Comment by sciai-ai** [comment]
Now i wonder whether eos is causing problems to have pause after each sentence. As eos is only added to the last sentence and more after every '.' when several sentences are sent for inference.

Sen 1. Sen2. Eos

Can we change to

Sen1. Eos sen2. Eos
