### ISSUE TITLE
Questions about results file

### ISSUE THREAD

**Issue by ronitd** [espnet/espnet#3320]
Hello,
How to get the precision to 2 decimal instead of 1 and what do S.Err and Corr stand for in Result files?

**Comment by sw005320** [comment]
We use `sclite` for scoring and I don't know it has some flexible formatting, but you can compute it by yourself from the result file since it also provides the total errors, e.g., 
```
|====================================================================================================================|
|   Sum            |   3396        53663    |  43868        7047        2748         1381       11176        2531    |
|====================================================================================================================|
```

**Comment by ronitd** [comment]
Thank you for the quick response. This was helpful.
Could you tell me what does S.Err and Corr refers to? I search documentation could not find anything in particular.

**Comment by sw005320** [comment]
`S.Err`: sentence error
`Corr`:  correct words (we don't usually use them)

**Comment by ronitd** [comment]
Thank you so much.
