### ISSUE TITLE
CTC segmentation conformer6

### ISSUE THREAD

**Issue by abnerLing** [espnet/espnet#3322]
Just an observation with the CTC segmentations.  With the below conformer model, the timings are quite varied and the probabilities are low. I checked with a few other librispeech models and they all seem fine but this was the only one strange.
kamo-naoyuki/librispeech_asr_train_asr_conformer6_n_fft512_hop_length256_raw_en_bpe5000_scheduler_confwarmup_steps40000_optim_conflr0.0025_sp_valid.acc.ave
For example, when getting the timings for this short audio clip I get really different results each time I checked.
```
utt_0000 utt 2.12 3.44 -8.3675 WE WILL FOCUS ON CLASSICAL METHODS OF MACHINE LEARNING
utt_0000 utt 0.03 0.95 -7.8388 WE WILL FOCUS ON CLASSICAL METHODS OF MACHINE LEARNING
utt_0000 utt 0.62 1.94 -8.8062 WE WILL FOCUS ON CLASSICAL METHODS OF MACHINE LEARNING
```
But with other models like  Shinji/Watanabe/librispeech_asr_train_asr_transformer_e18_raw_bpe_sp_valid.acc.best
I get the following results (all the same):
```
utt_0000 utt 0.07 3.67 -0.0692 WE WILL FOCUS ON CLASSICAL METHODS OF MACHINE LEARNING
utt_0000 utt 0.07 3.67 -0.0692 WE WILL FOCUS ON CLASSICAL METHODS OF MACHINE LEARNING
utt_0000 utt 0.07 3.67 -0.0692 WE WILL FOCUS ON CLASSICAL METHODS OF MACHINE LEARNING
```

Any ideas why this may be the case? It's likely related to that specific model but I can't figure out why...
I'm not too familiar with CTC alignments so I apologise if the question is naive.

**Comment by lumaku** [comment]
The Transformer model acts as expected and gives a good score. The confidence score for the Conformer is quite bad.
Aligning the sentence to random audio data from `torch.random`, would also give a confidence score of around -8 with this model. 

There might be an issue with the audio data or the inference. Can you check speech recognition with these models? Also, are you using the script interface (asr_align.py) or the python module (CTCSegmentation)?

**Comment by abnerLing** [comment]
I was using the CTCSegmentation module but I now realized what I did wrong. 
When creating the aligner for the conformer6 model, I only inputted the config.yaml and I didn't include the model file (valid.acc.ave_10best.pth). When testing the transformer I just imported the model with ModelDownloader. After adding the model file in the aligner the problem goes away. 
```
aligner = CTCSegmentation('/home/abner/work/espnet/modelcache/librispeech_conformer6/exp/asr_train/config.yaml', fs=16000 )

```
vs.
```
d = ModelDownloader(cachedir="./modelcache")
libri_model = d.download_and_unpack("Shinji Watanabe/librispeech_asr_train_asr_transformer_e18_raw_bpe_sp_valid.acc.best")
aligner = CTCSegmentation( **libri_model , fs=16000 )
```
