### ISSUE TITLE
TTS: no pause between sentences

### ISSUE THREAD

**Issue by sciai-ai** [espnet/espnet#3323]
I have trained tacotron TTS model, I used MFA to remove front and end silence from my wav files and then added 0.2 seconds silence to the end of each wav file.  I did this so that  the period symbol `' . '` corresponds to 0.2 seconds silence after training. 

Now The model correctly produce pause  0.2 sec silence at the end of each wav file,  see below 

![image](https://user-images.githubusercontent.com/52277510/123499377-de553100-d668-11eb-87b3-b9c8febc0cb8.png)

however when I synthesise two or more sentences together, there is still no pause between them but only pause at the last `' . '`

**Comment by kan-bayashi** [comment]
How about concatenating the audio and augment the training data?

**Comment by sciai-ai** [comment]
1. Yes that is my plan to concatenate two sentences together, but I dont know if the pause will work correctly only for two sentences in inference. 
2. For new symbol I actually tried adding breathing at the beginning of each wav file and adding '~' to the beginning of each transcript and add new symbol `'~'` to the token list. But I found two problems,
a) Only the beginning of each sentence has breathing 
b) Even I do not add `'~' `symbol  at the beginning of a sentence I can always hear a breath, which means the model can add breath but has not properly linked to the `'~' `symbol.

**Comment by kan-bayashi** [comment]
Sorry for late reply.
You can use `--non_linguistic_symbols` option for extra symbols.
You can define the new symbols like `<pause>`.

**Comment by sciai-ai** [comment]
Hi, I created non_linguistic_symbols.txt with 
`~`

However tokens.txt created doesnot contain this new symbol.

Is there any difference whether we add new symbols using -`-addsymbol `vs `--non-liguistic_symbols?`

**Comment by kan-bayashi** [comment]
Sorry for less accurate answer.
`--non_linguistic_symbols` is used to keep the symbols in sentence as is.
If we use trans_type=char without nlsyms, `This is <pau> a pen` will be `T h i s <space> i s <space> < p a u > <space> a <space>  p e n` but if we specify the nlsyms, it will be `T h i s <space> i s <space> <pau> <space> a <space>  p e n`.
`--addsymbol` is just adding the symbol in the dict even if it is not included in `text`.

**Comment by sciai-ai** [comment]
Thanks for the detail answer. So if I add symbol `~` in `non_linguistic_symbols.txt `it should appear in `tokenlist/tokens.txt` right?

I do not see my new token in the tokenlist

**Comment by kan-bayashi** [comment]
Hmm. Did you already add `~` in each sentence as well?

**Comment by sciai-ai** [comment]
Yes, each sentence starts with `~`  for example. `~This is a pen.`

**Comment by kan-bayashi** [comment]
Oh I reproduced your behavior.

```bash 
$ cat dump/raw/srctexts
fash-an253-b <pau>GO
fbbh-cen8-b <pau>MARCH THIRD NINETEEN TWENTY EIGHT
mwhw-an152-b <pau>START
mwhw-cen8-b <pau>ELEVEN SEVENTEEN FIFTY ONE

$ cat ./nlsyms.txt
<pau>

# token_type = char case
$ python3 -m espnet2.bin.tokenize_text --token_type char -f 2- --input dump/raw/srctexts --output data/token_list/char/tokens.txt --non_linguistic_symbols ./nlsyms.txt --cleaner none --g2p none --write_vocabulary true --add_symbol '<blank>:0' --add_symbol '<unk>:1' --add_symbol '<sos/eos>:-1'
$ cat data/token_list/char/tokens.txt
<blank>
<unk>
E
T
N
<space>
<pau>
I
R
H
G
O
A
Y
S
V
F
M
C
D
W
L
<sos/eos>

# token_type phoneme case
$ python3 -m espnet2.bin.tokenize_text --token_type phn -f 2- --input dump/raw/srctexts --output data/token_list/phn/tokens.txt --non_linguistic_symbols ./nlsyms.txt --cleaner none --g2p g2p_en --write_vocabulary true --add_symbol '<blank>:0' --add_symbol '<unk>:1' --add_symbol '<sos/eos>:-1'

$ cat data/token_list/phn/tokens.txt
<blank>
<unk>
N
T

P
AW1
AA2
R
IY1
W
EH1
IY0
S
V
F
AO1
G
OW0
M
K
TH
ER1
D
AY1
EY1
AA1
L
IY2
EH0
AH0
IH1
AH1
<sos/eos>
```

@kamo-naoyuki Is this an expected behavior?

**Comment by sciai-ai** [comment]
Yes, so for --token_type phn we cannot add the new symbol

**Comment by Freddy-pp** [comment]
It seems to me that the reason of this issue with "~" token is the use of g2p_en. I use "--token_type none" and previously prepared phonetic text as input, and I can add any additional tokens to this text. @sciai-ai, perhaps this will be the possible way for you to get what you want.

**Comment by sciai-ai** [comment]
@Freddy-pp Don't think it's a token issue, when we add any non-lingusitic symbol g2p should not decode it into phonemes and  take it as a symbol
