### ISSUE TITLE
make gives error Found conflicts!

### ISSUE THREAD

**Issue by RuslanSel** [espnet/espnet#3328]
After ./setup_anaconda.sh anaconda espnet 3.8 make gives errors:

Found conflicts! Looking for incompatible packages.

UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:

Specifications:

  - brotlipy -> python[version='>=2.7,<2.8.0a0|>=3.5,<3.6.0a0']
  - pyopenssl -> python[version='>=3.9,<3.10.0a0']
  - wheel -> python[version='>=3.9,<3.10.0a0']

Your python: python=3.8
...
Package libgcc-ng conflicts for:
ncurses -> libgcc-ng[version='>=7.2.0|>=7.3.0']
setuptools -> python[version='>=3.8,<3.9.0a0'] -> libgcc-ng[version='>=7.2.0|>=7.3.0|>=7.5.0']
tqdm -> python[version='>=2.7'] -> libgcc-ng[version='>=7.2.0|>=7.3.0|>=7.5.0']
....

**Basic environments:**
- OS information: Linux 4.15.0-147-generic #151-Ubuntu SMP Fri Jun 18 19:21:19 UTC 2021 x86_64
PYTHON_VERSION=Python 3.8.10
IS_CONDA=0
USE_PIP=
TH_VERSION=1.9.0
CONDA_PYTORCH=pytorch=1.9.0 cudatoolkit=10.1 -c pytorch
PIP_PYTORCH=torch==1.9.0 -f https://download.pytorch.org/whl/cu101/torch_stable.html
CHAINER_VERSION=6.0.0
PIP_CHAINER=chainer==6.0.0

 - espnet version: 0.10.0
 - git hash: 0c65a0dcaa71c11fcefd881f22dbfb30d4348dea
 - commit date: Sat Jun 26 09:05:10 2021 -0400
 - pytorch version: 1.9.0
 
OS: Ubuntu 18.04
gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0

Thanks in advance.

**Comment by sw005320** [comment]
How about using python 3.7?
Please check the dimension that we tested with CI https://github.com/espnet/espnet#espnet-end-to-end-speech-processing-toolkit
If you stick to Python 3.8, you may check the environment in https://github.com/espnet/espnet/blob/master/.github/workflows/ci.yaml#L25 (but it is based on ubuntu20).

**Comment by kamo-naoyuki** [comment]
The conda package for pytorch1.9+cuda10.1  doesn't exist: https://anaconda.org/pytorch/pytorch/files
 
Sorry, I forgot to update https://github.com/espnet/espnet/blob/master/tools/check_pytorch_cuda_compatibility.py for pytorch1.9

**Comment by kamo-naoyuki** [comment]
I added cuda version checking in #3329.
