### ISSUE TITLE
vctk_tts_train_xvector_conformer_fastspeech2 seems to be broken!

### ISSUE THREAD

**Issue by h-shad** [espnet/espnet#3330]
Hello! I'm trying to fine-tune the vctk_tts_train_xvector_conformer_fastspeech2 model. After days of failure, I noticed even **the provided pre-trained model doesn't seem to work properly**.

Even in [the official provided Google Colab notebook](https://colab.research.google.com/github/espnet/notebook/blob/master/espnet2_tts_realtime_demo.ipynb), when you select the vctk_tts_train_xvector_conformer_fastspeech2, it produces bad or unintelligible speech samples for many speakers and sentences.

For example, here are two results I get from the Colab notebook:
[sample 1](https://soundcloud.com/hamed-shadbash/vctk_tts_train_xvector_conformer_fastspeech-failed-sample-1): "Now we provide only English multi-speaker pretrained model.", speaker: p318
[sample 2:](https://soundcloud.com/hamed-shadbash/vctk_tts_train_xvector_conformer_fastspeech2-failed-sample-2) "Input your favorite sentence in English.", speaker: p341

Can you please explain why are the samples like this and how can I prevent this type of behavior?
Thank you in advance!

**Comment by h-shad** [comment]
@kan-bayashi Do you have any thoughts on this?

**Comment by kan-bayashi** [comment]
Sorry for the late reply.
This is caused by the limited performance of the model so it is difficult to say how to prevent this kind of errors.
One possibility to improve the performance is  
- Using a larger reduction factor to make it more stable
- Trying GST + x-vector model
- Trying LibriTTS model

**Comment by h-shad** [comment]
Okay, thank you very much!
