### ISSUE TITLE
ASR Training with WAV files

### ISSUE THREAD

**Issue by dv66** [espnet/espnet#3333]
Hi, 
we are using ESPnet for training Bengali ASR model using the Librespeech recipe. We have our audio files in WAV format. But we see in the Librespeech demo recipe, FLAC audios are being used. 

Can we directly use WAV files with the Librespeech recipe for **asr_train** without converting them to FLAC? Also would it affect the model performance/convergence if we use WAV instead of FLAC?

Thanks in advance.

**Comment by mrazizi** [comment]
Hi @dv66, 

I used Commonvoice recipe and mixed common voice mp3 files with my own wav files. There was no problem.

**Comment by kamo-naoyuki** [comment]
About espnet2, wav file can be used as same as flac. Soundfile detects the file type automatically by the extension. 
Flac is loss less format, so the performance is always same.
