### ISSUE TITLE
Is it possible to train TTS model on texts which are already tokenized?

### ISSUE THREAD

**Issue by zzxiang** [espnet/espnet#3357]
When training TTS model in Japanese, there's a problem in my data where the phonemes and accents the speaker pronounced sometimes don't match the tokenized texts output by the preprocessor. For example, the word "日本" has two ways of pronunciation:

1. にほん, which corresponds to phoneme and accent token array `['n', '2', '-1', 'i', '2', '-1', 'h', '2', '0', 'o', '2', '0', 'N', '2', '1']`.
2. にっぽん, which corresponds to phoneme and accent token array `['n', '3', '-2', 'i', '3', '-2', 'cl', '3', '-1', 'p', '3', '0', 'o', '3', '0', 'N', '3', '1']`.

Both are correct. However, the speaker chose 1, but the preprocessor of ESPnet chooses 2, which produces a mismatch between speech and text data. The same problem also occurs due to some inconsistent accents between the speaker and ESPnet (i.e. pyopenjtalk).

Since it is really not convenient for us to require the speaker to follow strictly the tokenized text and re-collect the speech data, I'm going to

1. Start the training stages until stage 4 to output the tokenized (phoneme and accent) text to a text file A with the method `pyopenjtalk_g2p_accent_with_pause` which is from the source code of ESPnet.
2. Modify file A to make it match the speech data.
3. Resume the training stages from stage 5 but let ESPnet directly use file A, without preprocessing the text data to generate tokenized phonemes and accents again.

However, I don't know how to perform step 3 above, and I even don't know whether it's possible.

**Comment by Freddy-pp** [comment]
Maybe token_type == "phn" and g2p=none is what you are looking for?
https://github.com/espnet/espnet/commit/52018051182654562ba6638f2db3c1d1c37cb2e2

**Comment by zzxiang** [comment]
Thank you very much! Although I haven't tried yet, I think you're correct after reading the source code.
