### ISSUE TITLE
For new egs contribution, shall we go for egs or egs2?

### ISSUE THREAD

**Issue by underdogliu** [espnet/espnet#3359]
Hi and thanks a lot for such amazing toolkit! Sorry for stupid question first but since the release of espnet2, where we are supposed to wave away most utilities (if not all) of Kaldi, I have following questions as a learner:

1. If I would like to make new contributions in terms of new corpus and egs, shall I mainly follow egs or egs2? 
2. If it's not about any of the templates such as ASR, TTS and enhancement, should I develop a template first?

If there is instruction available for people willing to contribute, it would be very helpful.

**Comment by sw005320** [comment]
My suggestion is to go for egs2 as it has a better scalability and clean APIs.
You may find some documents in https://github.com/espnet/espnet/blob/master/egs2/TEMPLATE/README.md and https://github.com/espnet/espnet/blob/master/CONTRIBUTING.md#13-recipes, but if you want more information, please let us know.

Recently @ftshijt made a diarization template, and @LiChenda, @Emrys365, and @shincling are developing a speech enhancement template.
So, we will also make more documentations of how to make a new templates with them for you.

**Comment by underdogliu** [comment]
Thanks @sw005320 for the reply! As a guy who knows a bit about speaker recognition, I am quite interested in contributing from my perspective. I believe e2e has huge potential for speak recognition and there are already tons of good works presented. 

I did a quick go-through of both README links but did not find useful information or solid guidelines on adding new recipes for new functions. So shall I simply read the existed scripts (as what I'm doing) and create recipes with similar writing format/style and file arrangement?

**Comment by sw005320** [comment]
Cool!
Could you directly contact me by email? 
shinjiw@ieee.org
We actually have a speaker recognition plan and want some help.

**Comment by underdogliu** [comment]
@sw005320 Yep I have sent the mail. Will close the issue. Thanks!
