### ISSUE TITLE
Durations for phonemes in a FastSpeech2 model

### ISSUE THREAD

**Issue by joanna-aflr** [espnet/espnet#3361]
Hi,

I'm trying to extract the durations for phonemes in milliseconds for a FastSpeech2 model at inference. I modified the fastspeech2.py script to output the predicted durations, so I believe I now have the information about the number of frames for each input token (with the duration for <eos> as the last number). How do I convert this into milliseconds? What is the frame length and the overlap? I use `win_length: 1200` and `hop_length: 300` but this does not seem to match the frames used to extract the durations... The sampling rate is 24000Hz.

For example, for the tokens `['T', 'EH1', 'S', 'T']` I have the predicted durations `[ 1,  6, 15,  5, 25]`. So there are 52 frames of generated audio. The generated audio lasts 650ms. This gives 12.5ms per frame without any overlap. But is this the case and where is this defined?

Thank you!

**Comment by kan-bayashi** [comment]
12.5 ms = 300 pt / 24,000 pt, equal to shift size.
