### ISSUE TITLE
Accuracy Result Plots of egs/an4/asr1 examples are Different  in Two Different ESPNET Releases

### ISSUE THREAD

**Issue by Gouranga95** [espnet/espnet#3363]
Hi,
I was doing training using a older ESPNET release(60682e8823d8fb44bf54ef157ddf7ae2c8797fc0). Now I want to move to latest ESPNET. I installed it successfully. I ran the  egs/an4/asr1 and egs/yesno/asr1 and they ran well. But when I was comparing the train/valid acc plot of egs/an4/asr1 between old ESPNet and latest ESPNET, I found that this plot is different and acc of latest ESPNET is lesser than that of old ESPNET(about 15% drop in train/valid acc in latest ESPNET). CTC loss of the latest ESPNET is higher than the old ESPNET. Here the model architecure is same in both cases.

Could you please help me why this is happening?

**Comment by sw005320** [comment]
Thanks for your report.
Could you tell me more about the difference?
Are the pytorch, cuda, and cudnn versions exactly same?
Which ctc did you use? Warpctc or pytorch build-in CTC?

**Comment by Gouranga95** [comment]
Thanks for your quick reply.
Here are the details - 
Old ESPNET -
Pytorch version - 0.4.1.post2
cuda version - 10.0
cudnn version - CUDNN_MAJOR - 7, CUDNN_MAJOR - 6
ctc_type - warp_ctc

New ESPNET -
Pytorch version -  1.3.1
cuda version - 10.0
cudnn version - CUDNN_MAJOR - 7, CUDNN_MAJOR - 6
ctc_type - warp_ctc

Please let me know if you need any more information.

**Comment by sw005320** [comment]
Thanks.
Actually, there are a lot of internal changes based on Pytorch 0.4.1.post2 and 1.3.1.
Also, an4 is a very small recipe and the result is unstable.
So, this is an acceptable difference.
The difference becomes smaller if we use more standard scale corpora.
