### ISSUE TITLE
DefaultCPUAllocator: can't allocate memory

### ISSUE THREAD

**Issue by RuslanSel** [espnet/espnet#3368]
I'm trying to decode with spgispeech zenodo model on device = "cpu", but got
RuntimeError: [enforce fail at CPUAllocator.cpp:67] . DefaultCPUAllocator: can't allocate memory: you tried to allocate 9402044192 bytes. Error code 12 (Cannot allocate memory)
I have 126 Gb RAM.
I changed beam_size=1, and batch_size=0.
But seems like it doesn't have any effect.
What else I can do?

Thanks in advance.

**Comment by kamo-naoyuki** [comment]
It looks your side issue since You couldn't even allocate 9GB. I recommend you checking memory growth when the starting the program.

**Comment by RuslanSel** [comment]
I can see in Htop that memory usage rises to 126 Gb.

**Comment by kamo-naoyuki** [comment]
Which is your audio, the test file of spgispeech or your own data? 

If you meet same error with the official test data, I think the model has some problem, though I don't know the detail of spgispeech.

If it's for only your own data, one of the possibility is too long hypothesis, due to some mismatch condition or simply too long audio.

**Comment by RuslanSel** [comment]
The length of audio is 18 minutes.

**Comment by kamo-naoyuki** [comment]
It's too long. Offline E2E model can't handle such a long audio. You need to split your audio into short segments using some tools  in advance.


@sw005320 I don't know the detail of our `BeamSearchOnline`. Does it work for this case?

**Comment by RuslanSel** [comment]
Can I just create segments file Kaldi-style?

**Comment by danoneata** [comment]
> Can I just create segments file Kaldi-style?

I would also be interested in an answer to this question; previously, I have used the [`format_wav_scp.sh`](https://github.com/espnet/espnet/blob/master/egs2/TEMPLATE/asr1/scripts/audio/format_wav_scp.sh) script to chop audios based on a Kaldi-style `segments` file.

**Comment by sw005320** [comment]
Year, my general suggestion is to chop audios based on external VADs.
Then, you can use Kaldi-style segments in an off-line scenario or develop additional implementations in the decoding loop (we did it internally based on external VADs, CTC, or whatever).

> @sw005320 I don't know the detail of our `BeamSearchOnline`. Does it work for this case?

it was designed for streaming purposes (still it is not real streaming, but it is streamable or streaming-ready). Long recording issues still exist, but we can easily handle this issue based on the solution above.
