### ISSUE TITLE
Code linters

### ISSUE THREAD

**Issue by ShigekiKarita** [espnet/espnet#34]
Although @kan-bayashi cleaned up some lines in #25 , we still have bad lines

```
# there are too many bad lines violates E501: line too long (> 79 chars)
$ flake8 ./src/bin src/nets | grep -v E501
./src/bin/asr_recog.py:132:1: E303 too many blank lines (3)
./src/bin/asr_recog_th.py:97:5: E306 expected 1 blank line before a nested definition, found 0
./src/bin/asr_train_th.py:14:1: F401 'subprocess' imported but unused
./src/bin/asr_train_th.py:26:1: F401 'chainer.function' imported but unused
./src/bin/asr_train_th.py:54:9: F841 local variable 'eval_func' is assigned to but never used
./src/bin/asr_train_th.py:446:1: W293 blank line contains whitespace
./src/bin/asr_train_th.py:448:5: E303 too many blank lines (2)
./src/bin/asr_train.py:13:1: F401 'subprocess' imported but unused
src/nets/e2e_asr_attctc.py:628:13: W291 trailing whitespace
src/nets/e2e_asr_attctc.py:679:29: W291 trailing whitespace
src/nets/e2e_asr_attctc_th.py:784:32: E265 block comment should start with '# '
src/nets/e2e_asr_attctc_th.py:791:31: E265 block comment should start with '# '
```

Do you think it's time to wake up these linters in .travis.yml?

https://github.com/espnet/espnet/blob/d50a8c2f2377fbe12c013edb3ef598f25d499fe1/.travis.yml#L26-L32

**Comment by sw005320** [comment]
I like your idea. Let's do it.

**Comment by ShigekiKarita** [comment]
Because there are many bad lines, I will work on src/bin, src/nets and test at first.

**Comment by ShigekiKarita** [comment]
And E501 is also too much for current codes. I ignore it now.

**Comment by kan-bayashi** [comment]
If you use nice editor such as vim, we should use syntactic plugin (pycodestyle, pyflakes, ...) to keep the pep8.

**Comment by ShigekiKarita** [comment]
that is right. I'm using PyCharm that also help pep8

**Comment by sw005320** [comment]
@kan-bayashi do you want to fight with me (not only me, but 100 billion emacs users)? BTW, I'm kind of switching to pycharm for this development.

**Comment by ShigekiKarita** [comment]
@sw005320 this is good for my emacs https://melpa.org/#/py-autopep8

**Comment by ShigekiKarita** [comment]
I think it is ready to unleash the linters in #37  but three things have been ignored yet

```ini
[flake8]
ignore = H102
max-line-length = 120
exclude = src/utils
```

https://github.com/ShigekiKarita/espnet/blob/08104b080a56227a904c9e5c0a46412770294ffe/setup.cfg#L6-L10

1. `H102  Apache 2.0 license header not found`  I do not know how to deal
2. `max-line-length = 120` it can be painful to limit line-length to 79 chars
3. `exclude = src/utils` I did not touch this because I've never touched
