### ISSUE TITLE
Streaming decoding with Transducer model on ESPNETv1

### ISSUE THREAD

**Issue by nguyenhuy1209** [espnet/espnet#3402]
Hi everyone, I was trying to use streaming decoding with **espnet.nets.pytorch_backend.e2e_asr_transducer:E2E**, with the config like this:

![image](https://user-images.githubusercontent.com/47093934/127978048-7ec372c4-c84d-47d7-b9e0-15c5a4ca30a4.png)

But the log file returns an error: 

![image](https://user-images.githubusercontent.com/47093934/127978337-cb4198d0-13dd-4703-903e-44bdcbafc87b.png)

Is the transducer module in ESPNET1 able to perform streaming decoding?

**Comment by b-flo** [comment]
Hi,

It's currently not supported. I can't give an ETA but I'll probably start working on it next week or the week after. First, we need to finish the new version of the model and its features, and also update all models/recipes/configs.
