### ISSUE TITLE
spgispeech pretrained model poor performance

### ISSUE THREAD

**Issue by RuslanSel** [espnet/espnet#3413]
I've split file from earnings21 on 30 second segments and ran it via espnet2_asr_realtime_demo.ipynb with spgispeech asr model.
wer is 70% and there are words like ITLL, YOURE, etc.
Maybe I'm doing something wrong.

Thanks in advance.

**Comment by sw005320** [comment]
Could you share the ASR hypothesis and corresponding reference?

**Comment by RuslanSel** [comment]
[00_hyp.txt](https://github.com/espnet/espnet/files/6955870/00_hyp.txt)
[00_ref.txt](https://github.com/espnet/espnet/files/6955871/00_ref.txt)
Hyp and ref files.

**Comment by sw005320** [comment]
Got it. 
Could you use the same normalization (remove `'`, `<UNK>` etc.) for both reference and transcription when you compute the WER?
The other looks good, and it's working as an ASR task.

**Comment by RuslanSel** [comment]
Wth the same normalization wer is 48.00 and del is 44.00.

**Comment by sw005320** [comment]
I'm still thinking there would be an issue in the reference (or corresponding audio).
Can you double-check the large deletion part?

**Comment by RuslanSel** [comment]
This is the recognized file - https://drive.google.com/file/d/1InD_ICPWwvXdaA7ayfOSwoWhsdm1xlIc/view?usp=sharing.

**Comment by sw005320** [comment]
Have you listened to the audio?
It was chopped in the middle, and actually, the hypothesis is very correct.
The reference you prepared is wrong.

Again, please make sure to prepare the correct reference.

**Comment by RuslanSel** [comment]
Does it mean that espnet2_asr_realtime_demo.ipynb chops the audio?

**Comment by sw005320** [comment]
No.
You chopped the audio but you did not correctly remove the words in the chopped region of the reference file.

**Comment by RuslanSel** [comment]
No, I didn't. :-)
You can try to run it by yourself.

**Comment by Freddy-pp** [comment]
Hello @sw005320.
What do you mean by "chopped region". I listened the audio and do not hear any gap inside. Just monotonous speech with short pauses. The reference text is very similar to what was said.

**Comment by RuslanSel** [comment]
I split the file for a few seconds and the results improved significantly.
