### ISSUE TITLE
Question about getting the style embedding from espnet2 model

### ISSUE THREAD

**Issue by iiynjgef** [espnet/espnet#3416]
Hello,
I have been trained a x-vector+gst espnet2 model with my own dataset and I try to analyse the style embedding and token from GSTs. I read the document, but can't find something about how to get the style embedding or token from espnet2 model. 
Could you tell me how to  get the style embedding and token from the model.

**Comment by kan-bayashi** [comment]
We do not provide such a function and you need to dig into the code.
For example, tacotron2 case is as follows:
https://github.com/espnet/espnet/blob/4f94f5bdc67b722c7fb04601b3b705d972bbce64/espnet2/tts/tacotron2.py#L187-L198
https://github.com/espnet/espnet/blob/4f94f5bdc67b722c7fb04601b3b705d972bbce64/espnet2/tts/gst/style_encoder.py#L16
https://github.com/espnet/espnet/blob/4f94f5bdc67b722c7fb04601b3b705d972bbce64/espnet2/tts/tacotron2.py#L425-L427

**Comment by iiynjgef** [comment]
Ok, I see. Thank you for your reply! I will try.
