### ISSUE TITLE
Custom tool installation Issue 

### ISSUE THREAD

**Issue by SatwikDutta** [espnet/espnet#3426]
**Describe the issue**
I am following the steps as mentioned in `https://espnet.github.io/espnet/installation.html`, but while installing few of the custom tools I encounter error due to gcc version. Initially I started with installing warp-ctc , but based on the previous issues I read I downgraded from pytorch 1.7 to 1.6. But now I face issues with installing other tools. Initially I started with cuda 11.3, but realized there were some limitations. Any recommendations or suggestions will be helpful. I also noticed a warning about cuDNN, not sure how to fix that.   

**Show the `check_install.py` status by using the following command**

[x] python=3.8.5 (default, Sep  4 2020, 07:30:14)  [GCC 7.3.0]

Python modules:
[x] torch=1.6.0+cu92
[x] torch cuda=9.2
[x] torch cudnn=7603
[x] torch nccl
/scratch/sxd180020/anaconda3/lib/python3.8/site-packages/chainer/backends/cuda.py:142: UserWarning: cuDNN is not enabled.
Please reinstall CuPy after you install cudnn
(see https://docs-cupy.chainer.org/en/stable/install.html#install-cudnn).
  warnings.warn(
[x] chainer=6.0.0
[x] chainer cuda
[ ] chainer cudnn
[x] cupy=6.0.0
[x] cupy nccl
[x] torchaudio=0.6.0
[x] torch_optimizer=0.1.0
[x] warpctc_pytorch=0.2.2
[ ] warprnnt_pytorch
[ ] warp_rnnt
[ ] chainer_ctc
[ ] pyopenjtalk
[ ] kenlm
[ ] mmseg
[x] espnet=0.10.0
[ ] fairseq
[ ] phonemizer
[ ] gtn
[ ] s3prl

Executables:
[ ] sclite
[ ] sph2pipe
[ ] PESQ
[ ] BeamformIt

**Basic environments:**

- OS information: Linux 5.8.0-55-generic #62~20.04.1-Ubuntu SMP Wed Jun 2 08:55:04 UTC 2021 x86_64
- python version: `3.8.5 (default, Sep  4 2020, 07:30:14)  [GCC 7.3.0]`
- espnet version: `espnet 0.10.0`
- pytorch version: `pytorch 1.6.0+cu92`
- Git hash: `0a328de124f4105ba92bd3058a7c7f98e0452fb3`
  - Commit date: `Tue Aug 10 13:28:53 2021 -0400`

**Environments from `torch.utils.collect_env`:**
Collecting environment information...
PyTorch version: 1.6.0+cu92
Is debug build: No
CUDA used to build PyTorch: 9.2

OS: Ubuntu 20.04.2 LTS
GCC version: (Ubuntu 7.5.0-6ubuntu2) 7.5.0
CMake version: version 3.16.3

Python version: 3.8
Is CUDA available: Yes
CUDA runtime version: 9.2.148
GPU models and configuration: 
GPU 0: NVIDIA Tesla K80
GPU 1: NVIDIA Tesla K80
GPU 2: NVIDIA Tesla K80
GPU 3: NVIDIA Tesla K80
GPU 4: NVIDIA Tesla K80
GPU 5: NVIDIA Tesla K80

Nvidia driver version: 465.27
cuDNN version: Could not collect

Versions of relevant libraries:
[pip3] numpy==1.21.1
[pip3] numpydoc==1.1.0
[pip3] pytorch-ranger==0.1.1
[pip3] pytorch-wpe==0.0.1
[pip3] torch==1.6.0+cu92
[pip3] torch-complex==0.2.1
[pip3] torch-optimizer==0.1.0
[pip3] torchaudio==0.6.0
[pip3] warpctc-pytorch==0.2.2+torch16.cuda92
[conda] Could not collect

**To Reproduce**
Steps to reproduce the behavior by showing us the specific installation commands with their arguments, e.g.,
```
cd <espnet-root>/tools
. ./setup_cuda_env.sh /usr/local/cuda-9.2/
make TH_VERSION=1.6.0 CUDA_VERSION=9.2
./installers/install_warp-transducer.sh
./installers/install_warp-rnnt.sh
./installers/install_chainer_ctc.sh
```

**Error logs**
**./installers/install_warp-transducer.sh**
[  7%] Building NVCC (Device) object CMakeFiles/warprnnt.dir/src/warprnnt_generated_rnnt_entrypoint.cu.o
In file included from /usr/local/cuda-9.2/include/host_config.h:50,
                 from /usr/local/cuda-9.2/include/cuda_runtime.h:78,
                 from <command-line>:
/usr/local/cuda-9.2/include/crt/host_config.h:119:2: error: #error -- unsupported GNU version! gcc versions later than 7 are not supported!
  119 | #error -- unsupported GNU version! gcc versions later than 7 are not supported!
      |  ^~~~~
CMake Error at warprnnt_generated_rnnt_entrypoint.cu.o.cmake:220 (message):
  Error generating
  /scratch/sxd180020/espnet/tools/warp-transducer/build/CMakeFiles/warprnnt.dir/src/./warprnnt_generated_rnnt_entrypoint.cu.o

make[2]: *** [CMakeFiles/warprnnt.dir/build.make:65: CMakeFiles/warprnnt.dir/src/warprnnt_generated_rnnt_entrypoint.cu.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:191: CMakeFiles/warprnnt.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

**./installers/install_warp-rnnt.sh**
warp-rnnt was not tested with CUDA_VERSION=92. Skipping install.

**installers/install_chainer_ctc.sh**
-- Build files have been written to: /scratch/sxd180020/espnet/tools/chainer_ctc/ext/warp-ctc/build
[ 11%] Building NVCC (Device) object CMakeFiles/warpctc.dir/src/warpctc_generated_reduce.cu.o
In file included from /usr/local/cuda-9.2/include/host_config.h:50,
                 from /usr/local/cuda-9.2/include/cuda_runtime.h:78,
                 from <command-line>:
/usr/local/cuda-9.2/include/crt/host_config.h:119:2: error: #error -- unsupported GNU version! gcc versions later than 7 are not supported!
  119 | #error -- unsupported GNU version! gcc versions later than 7 are not supported!
      |  ^~~~~
CMake Error at warpctc_generated_reduce.cu.o.cmake:220 (message):
  Error generating
  /scratch/sxd180020/espnet/tools/chainer_ctc/ext/warp-ctc/build/CMakeFiles/warpctc.dir/src/./warpctc_generated_reduce.cu.o

make[2]: *** [CMakeFiles/warpctc.dir/build.make:72: CMakeFiles/warpctc.dir/src/warpctc_generated_reduce.cu.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:133: CMakeFiles/warpctc.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

**Comment by b-flo** [comment]
Hi,

> /usr/local/cuda-9.2/include/crt/host_config.h:119:2: error: #error -- unsupported GNU version! gcc versions later than 7 are not supported!

Someone else reported the error to me last week and I know how to fix it, but unfortunately I couldn't reproduce the error constantly so I was waiting for more report.
Could you try with different `CUDA_VERSION` please?

**Comment by SatwikDutta** [comment]
@b-flo Thanks for your response. I have re-installed using cuda 11.0 & torch 1.7.0. I will be working on a recipe now, if I find any errors due to version/installation, I will publish here/open a relevant issue.
