### ISSUE TITLE
BPE tokenizer for code-switching ASR in espnet2

### ISSUE THREAD

**Issue by caohongnga** [espnet/espnet#3427]
Hello, 
I use espnet2 for code-switching ASR.
I want to tokenize English by BPE and tokenize Chinese by char.

I separate English and Chinese data and run stage 5 to tokenize English in BPE and Chinese in char. 
Then copy Chinese tokens from data/token_list/char/tokens.txt to the end of  data/token_list/bpe.../tokens.txt file and change the values of sos and eos in  the lm/espnet_model.py and asr/espnet_model.py.
The result of WER (36.9%) is much higher than tokenizing both English and Chinese in BPE (28.6%).

What is wrong in my method?
Thank you

**Comment by sw005320** [comment]
espnet2 performs tokenization on the fly by using sentencepiecie.
So, you have to modify the sentencepiecie model in addition to the token list.

**Comment by caohongnga** [comment]
Thank you for your reply.
