### ISSUE TITLE
espnet package not found in docker image

### ISSUE THREAD

**Issue by nellorebhanuteja** [espnet/espnet#3446]
Hi

I am using espnet/espnet:gpu-cuda10.1-cudnn7-u18 image from dockerhub

After activating espnet conda environment inside it, I get the following error

```text
import espnet
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'espnet'
```

However, conda list says espnet verion 0.9.3. is installed.

**Comment by Fhrozen** [comment]
> After activating espnet conda environment inside it, I get the following error

How are activating? if you type `which python`, it must show you `/espnet/tools/<env>`

BTW, I would recommend to use the container `gpu-latest`

**Comment by Fhrozen** [comment]
If you are using the container type `docker run ...`, do not forget to mount the volumes.

```
vols="-v ${PWD}/egs:/espnet/egs
      -v ${PWD}/espnet:/espnet/espnet
      -v ${PWD}/test:/espnet/test 
      -v ${PWD}/utils:/espnet/utils"
```

These were erased from the container and required to be loaded.
You can check the command after using `./run.sh` at the `docker` folder

**Comment by nellorebhanuteja** [comment]
> How are activating? if you type `which python`, it must show you `/espnet/tools/<env>`

I am activating by 
```bash
cd /espnet/tools/
. ./activate_python.sh
```

which python gives
```bash
/miniconda/envs/espnet/bin/python
```

**Comment by nellorebhanuteja** [comment]
> BTW, I would recommend to use the container `gpu-latest`

I am using 'gpu-cuda10.1-cudnn7-u18' because I ran my previous experiments in the with these specs and want to repeat the same in docker.

**Comment by Fhrozen** [comment]
Did You mount they volumen?

**Comment by nellorebhanuteja** [comment]
Hey
I mounted the volumes and not the problem is solved.
Thank you!
