### ISSUE TITLE
Embedding scale

### ISSUE THREAD

**Issue by danpovey** [espnet/espnet#3454]
A  bug/prolem we noticed that may affect your code too, I tagged Shinji on an issue in speechbrain but not sure he noticed:

Decoder embedding does not train properly as it is initialzed with too large a variance (of 1).  Better to scale it by sqrt(dim) in the forward, and initialize it with stddev=1/sqrt(dim).

**Comment by danpovey** [comment]
... also the  tgt_key_padding_mask is useless and can be removed, as the masked positions are never used by any decoder output position that you actually look it (they are covered by the subsequent mask).

**Comment by sw005320** [comment]
Thanks, @danpovey for raizing the issue.
We'll check it.
@pengchengguo, could you test them?

**Comment by pengchengguo** [comment]
Sure, I will check it. Thanks so much @danpovey.
