### ISSUE TITLE
Output phonemes and accent type symbols of Japanese using espnet ASR

### ISSUE THREAD

**Issue by zzxiang** [espnet/espnet#3456]
With ESPnet ASR, we can convert a speech into text. In the case of Japanese, the output text is kanji and kana.

I wonder if I can do some modification to make the output text become phonemes and accent type symbols, the format of which is the same as the output of [`pyopenjtalk_g2p_accent_with_pause`](https://github.com/espnet/espnet/blob/4c7442ad8faad6a6d975337563fe7e1a795c00cb/espnet2/text/phoneme_tokenizer.py#L39)?

For example, for a speech of `お疲れ様です`, I want the output to be `o 8 -7 ts 8 -6 U 8 -6 k 8 -5 a 8 -5 r 8 -4 e 8 -4 s 8 -3 a 8 -3 m 8 -2 a 8 -2 d 8 -1 e 8 -1 s 8 0 U 8 0`.

Note that I want the phonemes and accent type symbols to be recognized directly from speech, instead of converting the speech to text of kanji and kana, and then to phonemes and accent type symbols. This is because texts of kanji may have multiple possible pronunciations, and texts of kana may have multiple possible accents, so that the phonemes and accent type symbols converted from kanji and kana text may not match that of speech.

**Comment by sw005320** [comment]
We don’t have a phoneme and accent type symbol models.

My recommendation is to still use some conversion tools. 
One way is to apply the conversion tools to the training data, and output the phonemes and accent type symbols directly from the system.
The other way is to apply the conversion tools to the ASR output.

As you mention, it would have some errors, but we don’t have sufficiently large database to well train the phonemes and accent type symbols, and the above options would be a practical solution.

**Comment by zzxiang** [comment]
Thank you very much for the advice!
