### ISSUE TITLE
Question about recipe for IWSLT 2021 speech translation

### ISSUE THREAD

**Issue by longdct** [espnet/espnet#3478]
**Describe the issue**
Hi, thank you for your awesome repo.

Currently I'm doing some research for a Speech Translation project so I want to try your [end-to-end model for IWSLT 2021 offline translation track](https://aclanthology.org/2021.iwslt-1.10/). 
However, when I read the recipe at `egs/iwslt21/st1`, there don't seem to be any part about SeqKD or Multi-Decoder architecture.

In the paper about [Multi-Decoder architecture](https://aclanthology.org/2021.naacl-main.151/), the authors state that `All code and models are released as part of the ESPnet toolkit`, but I cannot find the recipe or code for the paper.

So can you help me about the recipes of these two papers? Thank you in advance.

**Comment by sw005320** [comment]
Thanks for showing interest in our approaches.
Yes, we're working on it.
It may not be very short-term, but we're planning to support this in the future.
