### ISSUE TITLE
Question: During inference how to use average model instead of best accuracy model?

### ISSUE THREAD

**Issue by ronitd** [espnet/espnet#3488]

**Comment by sw005320** [comment]
Is it espnet1 or espnet2?

**Comment by ronitd** [comment]
@sw005320  espnet2.

**Comment by sw005320** [comment]
OK. 
The `keep_nbest_models` option averages the nbest models.
It is used in many recipes as default, e.g., 
https://github.com/espnet/espnet/blob/master/egs2/librispeech/asr1/conf/tuning/train_asr_conformer7_hubert_960hr_large.yaml#L12

**Comment by ronitd** [comment]
True. I have trained models with that option. 
While inference, the decoding folder is having a suffix
1. asr_model_valid.acc.best, if --use_lm false.
2. ave_asr_model_valid.acc.best, otherwise.
Also there are three model file that are saved,  valid.acc.ave_10best.pth, valid.acc.ave.pth and valid.acc.best.pth.
So how is the model selected during the inference?

**Comment by sw005320** [comment]
It's selected in https://github.com/espnet/espnet/blob/master/egs2/TEMPLATE/asr1/asr.sh#L102-L109

**Comment by ronitd** [comment]
Got it. Thank you so much.
