### ISSUE TITLE
Espnet2 mucs21_subtask1 has Kaldi dependency 

### ISSUE THREAD

**Issue by AdityaYadavalli1** [espnet/espnet#3491]
**Describe the bug**

**Basic environments:**
 - OS information: Linux 4.15.0-107-generic #108~16.04.1-Ubuntu SMP Fri Jun 12 02:57:13 UTC 2020 x86_64
 - python version: 3.8.11
 - espnet version: 2
 - Git hash: 3247125d7278554dfc344a2a7a1c9d74cea56f13
 - Commit date [e.g. Tue Sep 1 09:32:54 2020 -0400]
 - pytorch version: 1.9.0
 

**Environments from `torch.utils.collect_env`:**
Collecting environment information...
PyTorch version: 1.9.0
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 16.04.6 LTS (x86_64)
GCC version: (Ubuntu 5.5.0-12ubuntu1~16.04) 5.5.0 20171010
Clang version: 3.8.0-2ubuntu4 (tags/RELEASE_380/final)
CMake version: version 3.5.1
Libc version: glibc-2.23

Python version: 3.8 (64-bit runtime)
Python platform: Linux-4.15.0-107-generic-x86_64-with-glibc2.17
Is CUDA available: True
CUDA runtime version: 10.2.89
GPU models and configuration: 
GPU 0: GeForce GTX 1080 Ti
GPU 1: GeForce GTX 1080 Ti
GPU 2: GeForce GTX 1080 Ti

Nvidia driver version: 440.95.01
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.21.2
[pip3] pytorch-ranger==0.1.1
[pip3] pytorch-wpe==0.0.1
[pip3] torch==1.9.0
[pip3] torch-complex==0.2.1
[pip3] torch-optimizer==0.1.0
[pip3] torchaudio==0.9.0
[conda] blas                      1.0                         mkl  
[conda] cudatoolkit               10.2.89              hfd86e86_1  
[conda] mkl                       2021.3.0           h06a4308_520  
[conda] numpy                     1.21.2                   pypi_0    pypi
[conda] pytorch                   1.9.0           py3.8_cuda10.2_cudnn7.6.5_0    pytorch
[conda] pytorch-ranger            0.1.1                    pypi_0    pypi
[conda] pytorch-wpe               0.0.1                    pypi_0    pypi
[conda] torch-complex             0.2.1                    pypi_0    pypi
[conda] torch-optimizer           0.1.0                    pypi_0    pypi
[conda] torchaudio                0.9.0                    pypi_0    pypi

**Task information:**
 - Task: ASR
 - Recipe: mucs21_subtask1
 - ESPnet2

**To Reproduce**
1. move to a recipe directory, `cd /egs2/mucs21_subtask1/`
2. Finish data preparation with `local/check_audio_data_folder.sh`, `local/test_data_prep.sh`, `local/train_data_prep.sh` etc. 
2. execute `run.sh` with specific arguments, e.g., `run.sh`
3. Error log is below

**Error logs**
paste-feats --length-tolerance=2 "ark:compute-fbank-feats  --write-utt2dur=ark,t:dump/fbank_pitch/org/train/log/utt2dur.1    --verbose=2 --config=conf/fbank.conf scp,p:dump/fbank_pitch/org/train/log/wav_train.1.scp ark:- |" "ark,s,cs:compute-kaldi-pitch-feats --verbose=2       --config=conf/pitch.conf scp,p:dump/fbank_pitch/org/train/log/wav_train.1.scp ark:- |     process-kaldi-pitch-feats  ark:- ark:- |" ark:- | copy-feats --compress=true --write-num-frames=ark,t:dump/fbank_pitch/org/train/log/utt2num_frames.1 ark:- ark,scp:/home/aditya.yadavalli/espnet/egs2/mucs21_subtask1/asr1/dump/fbank_pitch/org/train/data/raw_fbank_pitch_train.1.ark,/home/aditya.yadavalli/espnet/egs2/mucs21_subtask1/asr1/dump/fbank_pitch/org/train/data/raw_fbank_pitch_train.1.scp  Started at Sat Aug 21 09:21:23 IST 2021

bash: line 1: paste-feats: command not found
bash: line 1: copy-feats: command not found
Accounting: time=0 threads=1
Ended (code 127) at Sat Aug 21 09:21:23 IST 2021, elapsed time 0 seconds

I think fbank_pitch feature extraction has a Kaldi dependency. Indeed, in the later stages in `asr.sh` you mention that. Would you be removing this dependency soon?

**Comment by sw005320** [comment]
Thanks for the report. I basically agree with you as an espnet2 basic policy, but I think it would be good to make a decision by comparing the performance.

@bloodraven66, can you compare the current Kaldi fbank based feature and espnet2 built-in feature?
