### ISSUE TITLE
Parallel TTS decoding

### ISSUE THREAD

**Issue by v-yunbin** [espnet/espnet#3506]
I use espnet to build a TTS server with “Asynchronous mechanism”，just for send parallel TTS requests. I send a requests to TTS server, it works but I send multiple requests to TTS server, get follows errors：
```
    y = text2wav(message,  model, inference_args, vocoder, config, idim, char_to_id)
  File "/home/zyb/miniconda3/lib/python3.8/site-packages/espnet/model/predict_utils.py", line 67, in text2wav
    c, _, _ = model.inference(x, inference_args)
  File "/home/zyb/miniconda3/lib/python3.8/site-packages/espnet/nets/pytorch_backend/e2e_tts_transformer.py", line 918, in inference
    att_ws = [
  File "/home/zyb/miniconda3/lib/python3.8/site-packages/espnet/nets/pytorch_backend/e2e_tts_transformer.py", line 919, in <listcomp>
    torch.cat([att_w, att_w_], dim=1)
RuntimeError: Sizes of tensors must match except in dimension 1. Got 11 and 12 in dimension 2 (The offending index is 1)
```

```
**Basic environments:**
 - OS information: Linux version 3.10.0-957.el7.x86_64
 - python version: 3.8.3 
 - espnet version: [ espnet 0.9.8
 - pytorch version pytorch 1.8.1
```

```
**Task information:**
 - Task: TTS
 - Recipe: [csmsc]
 - ESPnet1 
```

**Comment by v-yunbin** [comment]
anyone met same problem？thanks

**Comment by kan-bayashi** [comment]
Sorry for the late reply.
Maybe the same as
https://github.com/espnet/espnet/issues/3222

**Comment by v-yunbin** [comment]
@They were different，I use "Asynchronous mechanism", it means that i load model  many times at the same time. Same parallel codes for fastspeech model worked. but failed for transformer model.

**Comment by kan-bayashi** [comment]
> I use "Asynchronous mechanism", it means that i load model many times at the same time. 

You mean using a single instance in the multi-thread?

**Comment by v-yunbin** [comment]
> > I use "Asynchronous mechanism", it means that i load model many times at the same time.
> 
> You mean using a single instance in the multi-threads?
> Maybe constructing the model instance for each thread works.
I did it that  you said，constructing the model instance for each thread,  fastspeech model works, transfomer model met follows errors.

**Comment by v-yunbin** [comment]
> > I use "Asynchronous mechanism", it means that i load model many times at the same time.
> 
> You mean using a single instance in the multi-threads?
> Maybe constructing the model instance for each thread works.
I  did it that you said,  and construct the model instance for each thread, but fastspeech model works, transformer met follows errors.
