### ISSUE TITLE
can not find ASRTask.build_streaming_iterator function

### ISSUE THREAD

**Issue by 200987299** [espnet/espnet#3507]
Dear developers,

I couldn't find ASRTask.build_streaming_iterator called in espnet2/bin/asr_inference.py. Can anyone help me here?

Thanks
Dee

**Comment by kan-bayashi** [comment]
https://github.com/espnet/espnet/blob/325417aa693fbcce1ab9c0a82cbdaa04a839ff40/espnet2/tasks/abs_task.py#L1715

**Comment by 200987299** [comment]
> https://github.com/espnet/espnet/blob/325417aa693fbcce1ab9c0a82cbdaa04a839ff40/espnet2/tasks/abs_task.py#L1715

thanks
