### ISSUE TITLE
How to train Japanese ASR model?

### ISSUE THREAD

**Issue by ymzlygw** [espnet/espnet#3510]
Hi, for training ASR model, I want to know that :
1. what's the last output of asr model, and how it be converted to kanji or hirakana of japanese.
2. What should I prepare before training a japanese asr model?

**Comment by sw005320** [comment]
> Hi, for training ASR model, I want to know that :
> 
> 1. what's the last output of asr model, and how it be converted to kanji or hirakana of Japanese.

We directly output the normal sentence including kanji or hirakana of Japanese, since it is end-to-end.
You don't need any conversion.
But we usually drop the punctuation.

> 2. What should I prepare before training a japanese asr model?

You just need to prepare the Japanese text and corresponding audio files.

Please check https://github.com/espnet/espnet/tree/master/egs2/jsut/asr1

**Comment by ymzlygw** [comment]
> > Hi, for training ASR model, I want to know that :
> > 
> > 1. what's the last output of asr model, and how it be converted to kanji or hirakana of Japanese.
> 
> We directly output the normal sentence including kanji or hirakana of Japanese, since it is end-to-end.
> You don't need any conversion.
> But we usually drop the punctuation.
> 
> > 1. What should I prepare before training a japanese asr model?
> 
> You just need to prepare the Japanese text and corresponding audio files.
> 
> Please check https://github.com/espnet/espnet/tree/master/egs2/jsut/asr1

While, how to directly generate the normal sentence? I think there is any mapping between integer output of model(index) and japanese kanji/hirakana/.

**Comment by sw005320** [comment]
> While, how to directly generate the normal sentence? I think there is any mapping between integer output of model(index) and japanese kanji/hirakana/.

Yes, we have such a mapping, but it will be done inside the program.
I recommend you follow the recipe I listed.
It will do some preprocessing, dictionary creation, and main training/inference.

**Comment by ymzlygw** [comment]
> > While, how to directly generate the normal sentence? I think there is any mapping between integer output of model(index) and japanese kanji/hirakana/.
> 
> Yes, we have such a mapping, but it will be done inside the program.
> I recommend you follow the recipe I listed.
> It will do some preprocessing, dictionary creation, and main training/inference.

So it means  that I can know the mapping in your the recipe?

**Comment by sw005320** [comment]
jsut is a Japanese ASR recipe, and you can know how we make mapping and so on.
But basically, it will be done automatically, and you can just prepare the data by modifying https://github.com/espnet/espnet/blob/master/egs2/jsut/asr1/local/data.sh to your own data.

**Comment by ymzlygw** [comment]
ok , thanks, I will read it!

**Comment by ymzlygw** [comment]
> jsut is a Japanese ASR recipe, and you can know how we make mapping and so on.
> But basically, it will be done automatically, and you can just prepare the data by modifying https://github.com/espnet/espnet/blob/master/egs2/jsut/asr1/local/data.sh to your own data.

Hi, When I  want to download just asr model, I find the name:
