### ISSUE TITLE
Is speech enhancement model language dependent?

### ISSUE THREAD

**Issue by zzxiang** [espnet/espnet#3520]
I'm sorry to ask a newbie question since I have no knowledge on speech enhancement.

I tried the [speech enhancement demo](https://colab.research.google.com/drive/1fjRJCh96SoYLZPRxsjF9VDv4Q2VoIckI?usp=sharing) in README. It works well on the demo WAV which is an English speech. However, it failed on my own data of Japanese speech. The output WAV sounds much worse than the original.

So does the model ([chime_tasnet_singlechannel](https://drive.google.com/uc?id=17DMWdw84wF3fz3t7ia1zssdzhkpVQGZm)) provided in the demo only works on English speech?

If I want to perform speech enhancement on Japanese speech, do I have to train a new model on Japanese corpus such as JSUT or JVS?

**Comment by Emrys365** [comment]
This is a good question. In my experience, the speech enhancement task should have less dependence on the language  than others (say speech recognition or text-to-speech). However, it more or less will be impacted when there is some mismatch between the training and target language, especially when some phonemes in the target language are not covered by the training data.
> I made a quick search, and found some works aiming to solve this issue, such as [[Xu et al.; 2014]](Cross-language transfer learning for deep neural network based speech enhancement), [[Pascual et al.; 2017]](https://arxiv.org/abs/1712.06340), and [[Gogate et al; 2019]](https://arxiv.org/abs/1909.10407).

For your specific issue, my concern is that the [chime_tasnet_singlechannel](https://drive.google.com/uc?id=17DMWdw84wF3fz3t7ia1zssdzhkpVQGZm) model was trained on very limited data (CHiME-4 corpus) and it could not work well even on other unseen conditions.
> BTW, frequency-domain speech separation models tend to have better generalizability than time-domain models, according to [Liu et al.; 2021](https://arxiv.org/abs/2102.04945).

If your purpose is to enhance the audios from some specific corpus, I would recommend you to train a new model on the simulated data with a similar setup.

**Comment by zzxiang** [comment]
Thank you very much for the detailed answer!
