### ISSUE TITLE
ESPNET2 with fbank_pitch

### ISSUE THREAD

**Issue by hanna-dav** [espnet/espnet#3534]
Hey!
So ESPNET1 generates the fbank features with the make_fbank_pitch.sh script.
In ESPNET2, the feats_type options are "raw" or "fbank_pitch".
If I put "raw" stage 3 finishes successfully, however if I put "fbank_pitch" I get all sorts of errors.
Has anyone ran ESPNET2 with fbank_pitch and knows what I'm missing?
Thanks!
Hanna.

**Comment by sw005320** [comment]
What kind of errors did you encounter?
FYI, `fbank_pitch` requires the installation of Kaldi

**Comment by hanna-dav** [comment]
Yes I have Kaldi installed.
In dump/fbank_pitch/..log/make_fbank_pitch..*.log I get:

First a list of this warning over and over again:
WARNING (compute-fbank-feats[5.5.543~1-7249c]:Read():feat/wave-reader.h:197) Exception caught in WaveHolder::Read(). kaldi::KaldiFatalError
WARNING (compute-fbank-feats[5.5.543~1-7249c]:EnsureObjectLoaded():util/kaldi-table-inl.h:317) Failed to load object from downloads/LibriSpeech/train-clean-360/103/1240/103-1240-0000.flac
ERROR (compute-fbank-feats[5.5.543~1-7249c]:Read():wave-reader.cc:122) WaveData: expected RIFF or RIFX, got fLaC

It finally fails with this error:
terminate called after throwing an instance of 'kaldi::KaldiFatalError'
  what():  kaldi::KaldiFatalError
LOG (copy-feats[5.5.543~1-7249c]:main():copy-feats.cc:143) Copied 0 feature matrices.
# Accounting: time=0 threads=1
# Ended (code 1) at Mon Aug 30 12:57:05 UTC 2021, elapsed time 0 seconds

I have checked the data file paths and they are correct, and the data is all .flac files,
exactly the same with feats_type=raw finished successfully.

I also saw here:
https://github.com/espnet/espnet/issues/2694
Under "Regulation" the first bullet is:
Use feats_type=raw
Don't use feats_type=fbank_pitch

Any help would be much appreciated,
Thanks.

**Comment by kamo-naoyuki** [comment]
Kaldi can handle only wav format. You need to format flac to wav.
 
Librispeech provides the audio data as flac file originally, and to avoid duplication, I kept flac format in the data preparation script. i.e. Kaldi feature isn't supported in the recipe. 

To use Kaldi feats, use the original data preparation script in the espnet1 recipe.

**Comment by kamo-naoyuki** [comment]
Sorry, I misunderstood. Is it your original audio data? Anyway, you need to format them to wav.

wav.scp
```
flac /some/where.flac |
...
```
