### ISSUE TITLE
Installing specific version of espnet using Dockerfile

### ISSUE THREAD

**Issue by TalhaKhalil** [espnet/espnet#3547]
I am trying to install espnet but the issue is it keeps on installing the most latest release. How can I install espnet=0.9.7 specifically. 

Dockerfile:
`FROM python:3.8.9-slim-buster

RUN apt-get update
RUN apt-get install gcc -y
RUN apt-get install --reinstall build-essential -y
RUN apt-get install -y libsndfile1 
RUN apt-get install ffmpeg -y

COPY ./ /app
WORKDIR /app
RUN mv nltk_data ~/
RUN pip install --upgrade pip
RUN apt-get install libfontconfig1-dev -y
RUN pip install pyworld
RUN pip install espnet-model-zoo
RUN pip show pyworld
RUN pip install pydub
RUN pip install -r requirements.txt
CMD ["python", "/espnet/setup.py", "install","&&"," python","/espnet/setup.py"]
EXPOSE 8013

CMD ["python", "main.py"]
`

**Comment by nellorebhanuteja** [comment]
There are two ways you can do this

```text
git clone -b v.0.9.7 https://github.com/espnet/espnet.git
```

or 

```text
git clone https://github.com/espnet/espnet.git
cd espnet
git checkout tags/v.0.9.7
```

Later, check which tag your cloned repo belongs to
```text
cd espnet
git describe --tags
```

**Comment by TalhaKhalil** [comment]
Alright. Thanks
