### ISSUE TITLE
RNN-T beam search decoding

### ISSUE THREAD

**Issue by marcoyang1998** [espnet/espnet#3559]
Hi, thanks for the wonderful project. I am using ESPnet1 to train a conformer transducer ASR model and would like to use beam search decoding to get WER results with a transformer LM. However, I noticed that ESPnet1 only supports RNN LM for transducer decoding. I was wondering if there is a way to use transformer LM for transducer decoding in ESPnet? 

Thanks!

**Comment by b-flo** [comment]
Hi,

> I noticed that ESPnet1 only supports RNN LM for transducer decoding. I was wondering if there is a way to use transformer LM for transducer decoding in ESPnet?

It's already supported! Compared to other ASR model, only decoding with N-gram is not supported for Transducer.

**Comment by b-flo** [comment]
Closing the issue. Feel free to re-open it if you encounter a bug with Transformer LM or if you've additional questions!
