### ISSUE TITLE
Any pretrained model or sample wav could be shared for Tacotron 2?

### ISSUE THREAD

**Issue by butterl** [espnet/espnet#356]
Hi，
Thanks for sharing this project ！ 
I have tried locally to train but the due to the slow GPU，It runs much slow. Is there any  pretrained model or sample wav could be shared for the Tacotron 2 part? @kan-bayashi

BRs,
Butter

**Comment by kan-bayashi** [comment]
Hi @butterl.
The audio samples are available from 
(decoding with Griffin-Lim)
https://drive.google.com/drive/folders/1HswA8pIHmFoaNDdBAGWpoAghWyg3slDc?usp=sharing
(decoding with WaveNet vocoder)
https://drive.google.com/drive/folders/19z1Bndcp3hmofrVcZfPoJpLjQZkwEODK?usp=sharing

WaveNet vocoder is available from https://github.com/kan-bayashi/PytorchWaveNetVocoder

Pretrained model of LJspeech model is available from 
https://drive.google.com/file/d/1RD46x6yx3xyzbWJ9G1pohTIIYYdjZU0P/view?usp=sharing

**Comment by sw005320** [comment]
I think we shoud also use github release function to distribute models and data so that we can avoid version conflicts. See the draft of release v.0.1.4

**Comment by butterl** [comment]
@kan-bayashi  thanks for reaching out！
The wavenet audio is very good ,what about the training steps?

Also I find the tacotron output have a lot robot-like sound reverb . I only have found [samples ](https://github.com/syang1993/gst-tacotron/files/2102924/eval-87k-r2.zip)in @syang1993 's repo not having this effect. Does it mean with espnet we need more training steps or need introduce some more  attention to get better voice from tacotron

**Comment by kan-bayashi** [comment]
Hi @butterl, thank you for your comments. 
In the case of wavenet vocoder, we separately trained tacotron2 and wanvnet with same traininig data (LJSpeech), each of training requires about 3 days with single GPU.
If we perform joint training, the quality become better.

In the case of Griffin-lim samples, we do only 100 iterations to recover phase components.
This is the reason why the sample sounds like robot.
If we perform much number of iterations (~10k ?), the quality becomes better.

And I use inverse of mel basis ton convert mel-filterbank to linear spectrogram.
In tacotron (not tacotron2), they use CBHG module to convert mel-filterbank to linear spectrogram.
I will implement this module in the future.
