### ISSUE TITLE
`nvidia-smi` command show weird information when running with DDP

### ISSUE THREAD

**Issue by pengchengguo** [espnet/espnet#3563]
**Describe the bug**

Hi everyone, when running ASR experiments on 1 node w/ 4 RTX 3090 GPUs and w/ EPSnet2 DDP training, the `nvidia-smi` command shows weird information like this:

<img width="714" alt="image" src="https://user-images.githubusercontent.com/23135280/132123763-95037008-5e3d-4a57-b799-02589a81409e.png">

For the DPP params, I just use the default settings.
I am not sure why each job is spread to each GPU? Does anyone have the same problem?

**Basic environments:**
 - OS information: Linux 4.15.0-142-generic #146~16.04.1-Ubuntu SMP Tue Apr 13 09:27:15 UTC 2021 x86_64
 - python version: 3.8.11
 - espnet version: 0.10.2a1
 - pytorch 1.9
 - cuda: 11.1

**Environments from `torch.utils.collect_env`:**

PyTorch version: 1.9.0
Is debug build: False
CUDA used to build PyTorch: 11.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 16.04.7 LTS (x86_64)
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609
Clang version: Could not collect
CMake version: version 3.5.1
Libc version: glibc-2.23

Python version: 3.8 (64-bit runtime)
Python platform: Linux-4.15.0-142-generic-x86_64-with-glibc2.17
Is CUDA available: True
CUDA runtime version: 11.1.105
GPU models and configuration:
GPU 0: GeForce RTX 3090
GPU 1: GeForce RTX 3090
GPU 2: GeForce RTX 3090
GPU 3: GeForce RTX 3090
GPU 4: GeForce RTX 3090
GPU 5: GeForce RTX 3090
GPU 6: GeForce RTX 3090
GPU 7: GeForce RTX 3090

Nvidia driver version: 455.45.01

**Task information:**
 - Task: ASR
 - Recipe: Aishell
 - ESPnet2

**Comment by kan-bayashi** [comment]
I also confirmed this issue. But no harmful effect.

**Comment by pengchengguo** [comment]
Thanks for your reply. 

Yeah, it is no harm to the performance. Besides, when running experiments on 2 Tesla P40 GPUs and w/ Nvidia driver version equals to 450.66, it will be normal. So, the problem may be caused by DDP on different Nvidia drivers or GPUs.
