### ISSUE TITLE
Input phonemes as text input to generate audio output

### ISSUE THREAD

**Issue by wanwen1405** [espnet/espnet#3574]
Hi!

Does anybody know I can input phonemes to generate audio output instead of inputting a text sentence?

for example

Text = " HH AH0 L OW1 , HH AW1 AA1 R Y UW1 ?"

instead of

Text = "hello, how are you?"

**Comment by kan-bayashi** [comment]
You can use `g2p=none` in the recipe level.
https://github.com/espnet/espnet/tree/master/egs2/TEMPLATE/tts1#supported-text-frontend

If you want to overwrite the g2p in the pretrained model, you have two choices:
1. Edit `config.yaml` and change to `g2p: null` and `cleaner: null`.
2. Overwrite after loading in the python as follows:
```python
[ins] In [1]: from espnet2.bin.tts_inference import Text2Speech
# load your model
[ins] In [2]: tts = Text2Speech.from_pretrained("kan-bayashi/ljspeech_vits")
# overwrite g2p
[ins] In [3]: from espnet2.text.phoneme_tokenizer import split_by_space
[ins] In [4]: tts.preprocess_fn.tokenizer.g2p = split_by_space
# overwrite cleaner
[ins] In [5]: tts.preprocess_fn.text_cleaner.cleaner_types = []
# inference
[ins] In [6]: wav = tts("HH AH0 L OW1 , W ER1 L D")["wav"]
```

**Comment by wanwen1405** [comment]
@kan-bayashi  thank you for the prompt reply. I am giving it a try now.

Meanwhile, is there anywhere in this https://colab.research.google.com/gist/sayakmisra/2bf6e72fb9eed2f8cfb2fb47143726b6/-e2e-tts.ipynb#scrollTo=i8JXOfRfqMFN demo under Setup where I can try using phoneme as input instead of text language?

**Comment by kan-bayashi** [comment]
Just skip cleaner and g2p.
```python
    # before
    text = custom_english_cleaners(text)
    
    if trans_type == "phn":
        text = filter(lambda s: s != " ", g2p(text))
        text = " ".join(text)
        print(f"Cleaned text: {text}")
        charseq = text.split(" ")
    else:
        print(f"Cleaned text: {text}")
        charseq = list(text)
    
    # after
	charseq = text.split(" ")
```
