### ISSUE TITLE
New version got worse results

### ISSUE THREAD

**Issue by tzyll** [espnet/espnet#3582]
The espnet2 baselines of 2 datasets all got worse results than older one with the same machine.
Is that because default conf changed or something else?

# Env
Old version:
pytorch1.7.1-cuda9.2
New version:
pytorch1.9.0-cuda11.1

# WSJ
conf  | dev93 | eval92
-- | -- | --
conf/train_asr_transformer.yaml  | 6.2 | 3.9
conf/train_asr_transformer_new_version.yaml | 7.9 | 5.0

conf diff:
```
$ diff exp/asr_train_asr_transformer_raw_en_char/config.yaml exp/asr_train_asr_transformer_new_version_raw_en_char/config.yaml 
1c1
< config: conf/train_asr_transformer.yaml
---
> config: conf/train_asr_transformer_new_version.yaml
6c6
< output_dir: exp/asr_train_asr_transformer_raw_en_char
---
> output_dir: exp/asr_train_asr_transformer_new_version_raw_en_char
53a54,57
> wandb_entity: null
> wandb_name: null
> wandb_model_log_interval: -1
> detect_anomaly: false
55a60
> ignore_init_mismatch: false
175c180
<     ignore_nan_grad: false
---
>     ignore_nan_grad: true
225c230
< version: 0.9.7
---
> version: 0.10.0
```

# HKUST
conf | dev
--|--
conf/train_asr_transformer.yaml  | 21.2
 conf/train_asr_transformer_new_version.yaml  | 22.6

conf diff:
```
$ diff exp/asr_train_asr_transformer2_raw_zh_char_sp/config.yaml exp/asr_train_asr_transformer_new_version_raw_zh_char_sp/config.yaml 
1c1
< config: conf/tuning/train_asr_transformer2.yaml
---
> config: conf/train_asr_transformer_new_version.yaml
6c6
< output_dir: exp/asr_train_asr_transformer2_raw_zh_char_sp
---
> output_dir: exp/asr_train_asr_transformer_new_version_raw_zh_char_sp
53a54,57
> wandb_entity: null
> wandb_name: null
> wandb_model_log_interval: -1
> detect_anomaly: false
55a60
> ignore_init_mismatch: false
3825c3830
< version: 0.9.7
---
> version: 0.10.0
```

**Comment by sw005320** [comment]
Thanks for the report.
I'm expecting that it happened due to that we wrongly disabled the model averaging.
So, could you use `--inference_asr_model valid.acc.ave.pth`?
The latest one already fixed this issue.

**Comment by tzyll** [comment]
Thanks. OK now with --inference_asr_model valid.acc.ave.pth.
