### ISSUE TITLE
Sub-linear Multi-GPU scaling on LibriSpeech with Transformer

### ISSUE THREAD

**Issue by popcornell** [espnet/espnet#3583]
Hello ESPNet team, 

I have observed sub-linear scaling when more than 1 GPU is used at least on LibriSpeech ASR recipe with transformer.

I used this transformer config:  https://github.com/espnet/espnet/blob/master/egs2/librispeech/asr1/conf/tuning/train_asr_transformer.yaml

This is what i get: 
(NOTE: i disabled speed augmentation, so I iterate only on original LibriSpeech data.)

N GPUs | Time for 1 epoch
           1 | 39.1 min 
           2 | 29.1 min 
           3 | 26.3 min
           4 | 25.4 min 
           5 | 22.0 min
           6 | 18.2 min

The machine is a DGX A100. Data is not in network storage but on local SSD (NVMe, super fast). 
I tried to increase workers from 8 and 16 but did not observe any appreciable difference in my case. 
I also tried to use sharded_ddp from https://espnet.github.io/espnet/espnet2_distributed.html. 

**Basic environments:**
 - OS information: Linux 5.4.0-72-generic #80-Ubuntu SMP Mon Apr 12 17:35:00 UTC 2021 x86_64
 - python version: 3.8.11 (default, Aug  3 2021, 15:09:35)  [GCC 7.5.0]
 - espnet version: 0.10.0
 - Git hash 4f94f5bdc67b722c7fb04601b3b705d972bbce64
   - Commit date Fri Aug 6 13:48:44 2021 -0400
 - pytorch version: 1.9.0
 

**Environments from `torch.utils.collect_env`:**
```
PyTorch version: 1.9.0
Is debug build: False
CUDA used to build PyTorch: 11.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.2 LTS (x86_64)
GCC version: (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Clang version: Could not collect
CMake version: version 3.16.3
Libc version: glibc-2.31

Python version: 3.8 (64-bit runtime)
Python platform: Linux-5.4.0-72-generic-x86_64-with-glibc2.17
Is CUDA available: True
CUDA runtime version: 11.1
GPU models and configuration: 
GPU 0: A100-SXM4-40GB
GPU 1: A100-SXM4-40GB
GPU 2: A100-SXM4-40GB
GPU 3: A100-SXM4-40GB
GPU 4: A100-SXM4-40GB
GPU 5: A100-SXM4-40GB
GPU 6: A100-SXM4-40GB
GPU 7: A100-SXM4-40GB

Nvidia driver version: 450.119.03
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.21.0
[pip3] pytorch-ranger==0.1.1
[pip3] pytorch-wpe==0.0.1
[pip3] torch==1.9.0
[pip3] torch-complex==0.2.1
[pip3] torch-optimizer==0.1.0
[pip3] torchaudio==0.9.0
[conda] blas                      1.0                         mkl  
[conda] cudatoolkit               11.1.74              h6bb024c_0    nvidia
[conda] mkl                       2021.3.0           h06a4308_520  
[conda] pytorch                   1.9.0           py3.8_cuda11.1_cudnn8.0.5_0    pytorch
[conda] pytorch-ranger            0.1.1                    pypi_0    pypi
[conda] pytorch-wpe               0.0.1                    pypi_0    pypi
[conda] torch-complex             0.2.1                    pypi_0    pypi
[conda] torch-optimizer           0.1.0                    pypi_0    pypi
```

**Task information:**
 - Task: ASR
 - Recipe: librispeech
 - ESPnet2

**To Reproduce**
1. `cd egs2/librispeech/asr1`.
2.  disable use_lm in asr.sh for fast experimentation. 
3. execute `run.sh` with different number of GPUs and jobs, e.g., `run.sh  --ngpu 1 --nj 8`

**Comment by sw005320** [comment]
Thanks, @popcornell for pointing out the issue.
This is very important.
We actually had some internal discussion about it.
