### ISSUE TITLE
How to write a custom decoder and integrate it with BERT OR Transformer based LM model and to the output of accoustic model provided by other framework

### ISSUE THREAD

**Issue by abdul756** [espnet/espnet#3595]
### Discussed in https://github.com/espnet/espnet/discussions/3594

<div type='discussions-op-text'>

<sup>Originally posted by **abdul756** September 17, 2021</sup>
Please help me in writing a custom decoder for  integrating  it with BERT OR Transformer based LM model and to the output of accoustic model provided by other framework</div>

**Comment by sw005320** [comment]
Thanks for the discussion!
Actually, @akreal implemented the use of BERT in the post-processing of the encoder.
@akreal, can you explain it a bit to @abdul756?

**Comment by akreal** [comment]
Hi @abdul756!
I'm not sure I understand the question. Currently it is possible to put a pre-trained NLU (BERT or some other pre-trained Transformer) in the middle between Encoder and Decoder:

```
Encoder-->Post-encoder--->Decoder
```
This way, the output of Encoder gets processed by NLU and may have more information about its linguistic properties (e.g. semantics). Decoder is trained as usual and should learn how to decode this information.

Here is an example of how to enable such pre-trained NLU:

https://github.com/espnet/espnet/blob/3b1d78de9ef00d44714365ef9a1ab1b465d755b4/egs2/swbd_da/asr1/conf/tuning/train_asr_transformer_postencoder.yaml#L15-L23
