### ISSUE TITLE
The data download link in vcc20 does not exist anymore

### ISSUE THREAD

**Issue by zzxiang** [espnet/espnet#3598]
I'm trying the cross-lingual voice conversion recipe of https://github.com/espnet/espnet/tree/master/egs/vcc20

But failed at step -1 of data downloading. The data URL http://www.caito.de/data/ does not exist any more:

https://github.com/espnet/espnet/blob/3b1d78de9ef00d44714365ef9a1ab1b465d755b4/egs/vcc20/tts1_en_zh/local/download_mailabs.sh#L31

**Comment by sw005320** [comment]
Thanks for the report!
@unilight, could I ask you to handle it!

**Comment by unilight** [comment]
Hi @zzxiang, from https://www.caito.de/2019/01/the-m-ailabs-speech-dataset/, looks like they changed the links. I will send a PR to update the links as soon as possible. Meanwhile, you can download the dataset manually from the link above if you want to proceed!

**Comment by zzxiang** [comment]
> Hi @zzxiang, from https://www.caito.de/2019/01/the-m-ailabs-speech-dataset/, looks like they changed the links. I will send a PR to update the links as soon as possible. Meanwhile, you can download the dataset manually from the link above if you want to proceed!

Thank you very much!
