### ISSUE TITLE
segment_size in mini_librispeech decoding config

### ISSUE THREAD

**Issue by learnabitmore** [espnet/espnet#3601]
May I ask if an audio is longer than the segment_size, will the predictions have the same speaker order across all segments? Say if the predictions for both segments are [[1, 0], [1, 0], [1, 0]], i.e. only one speaker speaks in individual segments, do we know if the same speaker speaks in both segments or the speakers can be different?

**Comment by sw005320** [comment]
Are you talking about the diarization recipe?
If so, we cannot maintain the same speaker information across the segment.
We usually perform it for the entire recording or combine it with a clustering method.

**Comment by learnabitmore** [comment]
Yes it's about the diarization recipe. Thank you for your answer. 
When the recording is very long, what would be the best way to "combine it with a clustering method" using ESPnet2?

**Comment by sw005320** [comment]
> "combine it with a clustering method".

We can compute an x-vector of each speaker segment and perform clustering.
But we can also extend a network to explicitly have an embedding output like https://arxiv.org/pdf/2010.13366.pdf

https://arxiv.org/pdf/2006.02616.pdf does not require so much change in training
