### ISSUE TITLE
no module named tranformers

### ISSUE THREAD

**Issue by 200987299** [espnet/espnet#3609]
Dear developers,

I am using a recently downloaded espent version, and I got error when training asr, the error is:

  File "/espnet/espnet2/asr/postencoder/hugging_face_transformers_postencoder.py", line 9, in <module>
    from transformers import AutoModel
ModuleNotFoundError: No module named 'transformers'

I could not find this transformers module, can anyone help me here?

Bests

**Comment by sw005320** [comment]
Thanks for the report.
@akreal, could you answer it for me?
Maybe, we need to add a check for HF transformer libraries?

**Comment by akreal** [comment]
HF transformers is currently in the requirements and should be installed together with the other dependencies:

https://github.com/espnet/espnet/blob/a9c032b0bb3dcc64f1cb27896fd0746f8e1e4a59/setup.py#L50

If it is an old installation and requirements have changed since the installation was done, then the installation should be repeated, I guess.

**Comment by 200987299** [comment]
> HF transformers is currently in the requirements and should be installed together with the other dependencies:
> 
> https://github.com/espnet/espnet/blob/a9c032b0bb3dcc64f1cb27896fd0746f8e1e4a59/setup.py#L50
> 
> If it is an old installation and requirements have changed since the installation was done, then the installation should be repeated, I guess.

Dear Akreal,

Could you also update the docker file so that transformer is automaticly installed? 

Thanks

**Comment by sw005320** [comment]
@Fhrozen, could you do that for us?

**Comment by Fhrozen** [comment]
@sw005320, to confirm that the containers were updated and built with the `transformer` package.
I am currently uploading. will be ready in a few mins.

**Comment by 200987299** [comment]
> @sw005320, to confirm that the containers were updated and built with the `transformer` package.
> I am currently uploading. will be ready in a few mins.

Thank you!
