### ISSUE TITLE
Looking for Streaming ASR : RNN-T or Transformer Transducer Recipe

### ISSUE THREAD

**Issue by srikanthk20** [espnet/espnet#3612]
Hi,

I am new to Espnet and looking for streaming ASR support either with RNN-T or Transformer transducer.
Can someone guide me to the appropriate recipe to start for this and the documentation if any.
Thanks in advance

**Comment by b-flo** [comment]
Hi,

Streaming Transducer is not available right now but this is the next objective. I have to fix quantization and n-gram decoding, refactor my streaming utilities and we're good to go. It will be available in a few weeks I guess.

**Comment by srikanthk20** [comment]
Will look forward to it. Thanks to the team for the great work

**Comment by srikanthk20** [comment]
@b-flo ... are the updates available...

**Comment by b-flo** [comment]
Hi,

Sorry for the delay, I'm overloaded with some other works and we had some internal discussion related to streaming Transducer in ESPnet and production side which changed the scope of the work. The streaming part is mostly done but it'll take a bit more time before I push/present what we have in mind. I'll keep you updated.

**Comment by srikanthk20** [comment]
@b-flo ... thanks for the info and your contributions

**Comment by srikanthk20** [comment]
@b-flo ... is there a experiment branch that i can refer to in the meanwhile

**Comment by b-flo** [comment]
Sorry, all related branches and repo related to that work are currently private.

**Comment by tarun73** [comment]
Hi @b-flo , thanks for your contributions. Just curious if you can share the timeline for this feature. or any other relevant update.

**Comment by b-flo** [comment]
My apologies for the delay.

I'm aiming mid january for streaming alongside some other works. You can look at my comment in this [PR](https://github.com/espnet/espnet/pull/2533#issuecomment-992631822) for further details on the current situation with Transducer.
