### ISSUE TITLE
Speech classifier that can identify the PORN voice

### ISSUE THREAD

**Issue by wac81** [espnet/espnet#3627]
Speech classifier that can identify the PORN voice and NORMAL voice

which one i can use algorithm with ESPNET？

**Comment by Fhrozen** [comment]
Well, you could use a transformer encoder followed by an attention layer similar to X-vectors extractors and classify the voice. Now, I am not sure if there is any available corpus for the task. ;)

**Comment by Fhrozen** [comment]
You can also check for some ideas for sound event detection from the last DCASE challenge (http://dcase.community/challenge2021/task-sound-event-detection-and-separation-in-domestic-environments-results)
