### ISSUE TITLE
asr training stops in 2epoch

### ISSUE THREAD

**Issue by kiyosumaeda** [espnet/espnet#3630]
I'm using espnet2 to finetune models with our custom dataset.
During asr training on conformer and transformer, there are many warinigs.
```
(trainer:582) WARNING: The grad norm is nan. Skipping updating the model.
or
(ctc:71) WARNING: 5/42 samples got nan grad. These were ignored for CTC loss.
```

Finally, the training ended at 2epoch.
```
(trainer:404) WARNING: The gradients at all steps are invalid in this epoch. Something seems wrong. This training was stopped at 2epoch
```

Although I dealt with previous related issues (e.g. adding ignore nan grad in config file as described in [https://github.com/espnet/espnet/issues/3170](https://github.com/espnet/espnet/issues/3170)), there are still the above problems.

I also found in the training log a warning below:
```
(ctc:66) WARNING: All samples in this mini-batch got nan grad. Returning nan value instead of CTC loss
```

Since this warning, `WARNING: The grad norm is nan. Skipping updating the model.` seemed increased.

How can I solve this problem?

My environment was
```
python 3.8.7
pytorch 1.7.1+cu110
espnet 0.9.9
GPU RTX 2060
```

**Comment by sw005320** [comment]
This would often happen if the data preparation is not correctly done (especially when the (down-sampled) input feature is relatively shorter than the output length.
Could you check the audio file and corresponding text files again?

**Comment by kiyosumaeda** [comment]
thank you for your reply. I’ll check the audio and text files and report the result.

**Comment by kushagramahajan** [comment]
Any resolution to this?

**Comment by kiyosumaeda** [comment]
I could partly resolve this problem by setting `min_wav_duration` to 0.5 in `asr.sh` to remove too short audio segments.
Although there are sometimes the same warning messages, the finetune process does not stop anymore.

**Comment by kushagramahajan** [comment]
This doesn't seem to work for me though. Thanks anyways.

**Comment by ksoky** [comment]
Dear @sw005320,

In Espnet1, we can remove the "input feature is relatively shorter than the output length" by using the following:
[filtering sample](https://github.com/espnet/espnet/blob/master/egs/wsj/asr1/run.sh#L149).

However, I am not yet familiar with ESPnet2, does it have a similar script for this solution?

**Comment by sw005320** [comment]
We don't have such a script.
Instead, we can automatically skip the files that cause an issue in the gradient.
In normal speech corpora, this condition does not happen so often.
