### ISSUE TITLE
ESPnet2: How to train a multi-channel asr system on the CHiME4 corpus and use the WSJ0 data to help training.

### ISSUE THREAD

**Issue by guoyifan97** [espnet/espnet#3633]
I am trying to use the espnet2 to train a multi-channel asr system on the CHiME4 corpus.
And I am also trying to use the single-channel data from WSJ0 to help training the recognition backend.
In Espnet1, it has a category label like SINGLE-CHANNEL or MULTI-CHANNEL to create different channel data to separated mini-batch.
But it seems that Espnet2 does not have such a feature.
How can I deal with this problem?

Thanks!

**Comment by Emrys365** [comment]
@guoyifan97 
Do you mean ① training a multi-channel ASR system with a multi-channel frontend or ② just a single ASR model to process multi-channel features?

For the former purpose, we are currently in a PR to introduce the joint training task of the SE frontend and ASR, which supports the use of a `utt2category` file to specify the category of each sample, just like in ESPnet1.

For the latter purpose, currently we haven't prepared such features in the ASR training. If you have any suggestion on it, I think we could make some further actions.

**Comment by guoyifan97** [comment]
Cool! Thanks a lot!
