### ISSUE TITLE
failure at inference with multi-speaker on espnet1

### ISSUE THREAD

**Issue by r406** [espnet/espnet#3637]
Hi,  I trained multi-speaker TTS with around 100 users using template of "espnet/egs/Libritts" with non-English language. Before I successfully trained and tested non-English single speaker.  During my multi-speakaer inference testing I tried to use the speaker embedding generated in "exp" directory   and it fails at  e2e_tts_tacotron2.inference. with error message 
**Caught exception: AttributeError("'NoneType' object has no attribute 'norm'",)**

I even tried with LibriTTS speaker embedding for testing, but getting same error.   I am using espnet1 framework and not  espnet2.  Any help will be highly appreciated. below is the code snippet that throughs exception /espnet/nets/pytorch_backend/e2e_tts_tacotron2.py

if self.spk_embed_dim is not None:
            spemb = F.normalize(spemb, dim=0).unsqueeze(0).expand(h.size(0), -1)
            h = torch.cat([h, spemb], dim=-1)

**Comment by r406** [comment]
I have tested the non-English speaker embedding ( xvectors) with Libritts inference with example code for enspnet2  and no error is shown.

**Comment by kan-bayashi** [comment]
Give me the whole log?

**Comment by r406** [comment]
Number of speakers = 444
[nltk_data] Downloading package punkt to /home/posicube/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
Now ready to synthesize!
Input your favorite sentencne
종목별 허용 인원은 경기에 필요한 인원의 1.5배까지 가능합니다.
Cleaned text -: 종목뼐 허용 이눠는 경기에 피료하 니눠늬 일.오배까지 가능함니다.
 Speaker ID selected  = 426
Caught exception: AttributeError("'NoneType' object has no attribute 'norm'",)

**Comment by r406** [comment]
example code 
trans_type = "char"
dict_path = "dls/kr/multispeaker_tacotran2/data/lang_1char/train_clean_100_units.txt"
model_path = "dls/kr/multispeaker_tacotran2/exp/train_clean_100_pytorch_train_pytorch_tacotron2+spkemb/results/model.last1.avg.best"
vocoder_path = "dls/kr/multispeaker_wavgan_v1/checkpoint-1000000steps.pkl"
vocoder_conf = "dls/kr/multispeaker_wavgan_v1/config.yml"

from jamo import h2j, j2hcj


# define E2E-TTS model
from argparse import Namespace
from espnet.asr.asr_utils import get_model_conf
from espnet.asr.asr_utils import torch_load
from espnet.utils.dynamic_import import dynamic_import
idim, odim, train_args = get_model_conf(model_path)
model_class = dynamic_import(train_args.model_module)
model = model_class(idim, odim, train_args)
torch_load(model_path, model)
model = model.eval().to(device)
inference_args = Namespace(**{"threshold": 0.5, 
                              "minlenratio": 0.0, 
                              "maxlenratio": 10.0})

# define neural vocoder
import yaml
import parallel_wavegan.models
with open(vocoder_conf) as f:
    config = yaml.load(f, Loader=yaml.Loader)
vocoder_class = config.get("generator_type", "ParallelWaveGANGenerator")
vocoder = getattr(parallel_wavegan.models, vocoder_class)(**config["generator_params"])
vocoder.load_state_dict(torch.load(vocoder_path, map_location="cpu")["model"]["generator"])
vocoder.remove_weight_norm()
vocoder = vocoder.eval().to(device)


spemb = None
xvector_ark = "dls/kr/multispeaker_tacotran2/exp/xvector_nnet_1a/xvectors_train_clean_100/spk_xvector.ark"

xvectors = {k: v for k, v in kaldiio.load_ark(xvector_ark)}
spks = list(xvectors.keys())
print(" Number of speakers = {}".format(len(spks)))

from g2pk import G2p
g2p = G2p()
with open(dict_path) as f:
    lines = f.readlines()
lines = [line.replace("\n", "").split(" ") for line in lines]
char_to_id = {c: int(i) for c, i in lines}
def frontend(text):
    """Clean text and then convert to id sequence."""
    ptext = g2p(text)
    text = j2hcj(h2j(ptext))
    
    if trans_type == "phn":
        text = filter(lambda s: s != " ", g2p(text))
        text = " ".join(text)
        print(f"Cleaned text: {ptext}")
        charseq = text.split(" ")
    else:
        print(f"Cleaned text -: {ptext}")
        charseq = list(text)
    idseq = []
    for c in charseq:
        if c.isspace():
            idseq += [char_to_id["<space>"]]
        elif c not in char_to_id.keys():
            idseq += [char_to_id["<unk>"]]
        else:
            idseq += [char_to_id[c]]
    idseq += [idim - 1]  # <eos>
    return torch.LongTensor(idseq).view(-1).to(device)

import nltk
nltk.download('punkt')

import simpleaudio as sa
import soundfile
import time
pad_fn = torch.nn.ReplicationPad1d(
config["generator_params"].get("aux_context_window", 0))
use_noise_input = vocoder_class == "ParallelWaveGANGenerator"
while True:
    try:
        print("Input your favorite sentencne !")
        input_text = input()
        with torch.no_grad():
            start = time.time()
            x = frontend(input_text)
            random_spk_idx = np.random.randint(0, len(spks))
            spk = spks[random_spk_idx]
            spembs = xvectors[spk]
            c, _, _ = model.inference(x, inference_args, spembs=spembs)
            c = pad_fn(c.unsqueeze(0).transpose(2, 1)).to(device)
            xx = (c,)
            if use_noise_input:
                z_size = (1, 1, (c.size(2) - sum(pad_fn.padding)) * config["hop_size"])
                z = torch.randn(z_size).to(device)
                xx = (z,) + xx
            y = vocoder(*xx).view(-1)
        rtf = (time.time() - start) / (len(y) / config["sampling_rate"])
        x = y.cpu().detach().numpy()
        soundfile.write("test.wav", x, 24000, 'PCM_16')
        exit()
    except Exception as e:
        print("Caught exception: %s" % repr(e))
        exit()

**Comment by kan-bayashi** [comment]
I want to check the traceback log.

**Comment by r406** [comment]
random_spk_idx = np.random.randint(0, len(spks))
            spk = spks[random_spk_idx]
            spembs = torch.FloatTensor(xvectors[spk]).to(device)
            c, _, _ = model.inference(x, inference_args, spembs=spembs)

**Comment by r406** [comment]
i still get the same error. I even tried with Libritts dataset. Kindly could you please let me know how to get traceback log?

**Comment by kan-bayashi** [comment]
Please remove try except.

**Comment by r406** [comment]
Traceback (most recent call last):
  File "testlibri.py", line 100, in <module>
    c, _, _ = model.inference(x, inference_args, spembs=spembs)
  File "/home/work/ParallelWaveGAN/tools/venv/lib/python3.6/site-packages/espnet/nets/pytorch_backend/e2e_tts_tacotron2.py", line 820, in inference
    spemb = F.normalize(spemb, dim=0).unsqueeze(0).expand(h.size(0), -1)
  File "/home/work/ParallelWaveGAN/tools/venv/lib/python3.6/site-packages/torch/nn/functional.py", line 3031, in normalize
    denom = input.norm(p, dim, True).clamp_min(eps).expand_as(input)
AttributeError: 'NoneType' object has no attribute 'norm'

**Comment by r406** [comment]
Thanks for your help
