### ISSUE TITLE
AttributeError: module 'regex' has no attribute 'Pattern' 

### ISSUE THREAD

**Issue by yinxx** [espnet/espnet#3638]
just run demo of espnet2_tts_realtime_demo.ipynb there throw  an error:

AttributeError Traceback (most recent call last)
in ()
----> 1 from espnet2.bin.tts_inference import Text2Speech
2 from espnet2.utils.types import str_or_none
3
4 text2speech = Text2Speech.from_pretrained(
5 model_tag=str_or_none(tag),

9 frames
/usr/local/lib/python3.7/dist-packages/nltk/tokenize/casual.py in TweetTokenizer()
366
367 @Property
--> 368 def PHONE_WORD_RE(self) -> regex.Pattern:
369 """Secondary core TweetTokenizer regex"""
370 # Compiles the regex for this and all future instantiations of TweetTokenizer.

AttributeError: module 'regex' has no attribute 'Pattern'

**Comment by kan-bayashi** [comment]
I cannot reproduce. Which model did you try?

**Comment by inwadkar** [comment]
I had similar issue and after lot of search i got this details.
https://github.com/nltk/nltk/commit/6428c9288a86658cb3d9a1e91816c4bcf162a6f0#diff-a495c029b94d07b00b778131db573f6887583727f49bf7ffca83fb4b32c4d318

I had to access the source code of nltk/tokenize/casual.py and do the changes as mentioned above and the code worked.
![casual](https://user-images.githubusercontent.com/93640500/151419583-fddfe4be-aa9e-43e9-8b44-2e262b4d8a4b.png)
