### ISSUE TITLE
Nbest output after decoding

### ISSUE THREAD

**Issue by dneelagiri** [espnet/espnet#364]
Hello @Fhrozen ,

Currently there is only 1best hypothesis which can be output as part of espnet during decoding. Is there any possibility of supporting outputting nbest hypothesis similar to kaldi?

Thank you

**Comment by Fhrozen** [comment]
Dear @dneelagiri 
I was looking in the development plan #334 about your request. 
@sw005320 Could you give more details about this?.

**Comment by dneelagiri** [comment]
Thank you @Fhrozen . @sw005320 could you please let me know if the the nbest option will be available as part of next version?
Also I had one other question if you can please help with that too? Is the word-rnnlm support for espnet supported for chainer backend? 
I tried to incorporate the word-rnnlm into librispeech following the wsj run.sh script. Although I receive a numpy error when I try to load word rnnlm during decoding. Since I dont have WSJ data I wasnt able to check if that works.

**Comment by sw005320** [comment]
> Currently there is only 1best hypothesis which can be output as part of espnet during decoding. Is there any possibility of supporting outputting nbest hypothesis similar to kaldi?

This is already supported. https://github.com/espnet/espnet/blob/master/src/bin/asr_recog.py#L48-L49
If you specify the option, the nbest results will be written `data.xxx.json` in the recognition result directory.

>Also I had one other question if you can please help with that too? Is the word-rnnlm support for espnet supported for chainer backend?
> I tried to incorporate the word-rnnlm into librispeech following the wsj run.sh script. Although I receive a numpy error when I try to load word rnnlm during decoding. Since I dont have WSJ data I wasnt able to check if that works.

Yes, it is supported.
Please let me know the error message.

**Comment by kan-bayashi** [comment]
Please use `--nbest` option for `asr_recong.py`.
