### ISSUE TITLE
How to use Transducer in Librispeech with ESPnet2?

### ISSUE THREAD

**Issue by arabae** [espnet/espnet#3642]
Hi, thanks for the wonderful project.

I'm using ESPnet2 to train a conformer-transformer ASR model and would like to use RNN-T or Transformer transducer.
Can someone guide me to the appropriate recipe to start for this and the documentation if any.
Espnet Usage shows to add model_module to training config. but facing "asr_train.py: error: unrecognized arguments: model_module", and I don't know how to solve it.

Thanks!

**Comment by b-flo** [comment]
Transducer models are not available in ESPnet2, the documentation is intended for ESPnet1.
You can make a working ESPnet2 version using #2533, but most features  (e.g.: auxiliary tasks, FastEmit, mAES, etc) and optimizations won't be available compared to ESPnet1 version.
