### ISSUE TITLE
Speed perturbation error: "Utterance list differs between data/build_sp1.1/utt2spk and data/build_sp1.1/segments"

### ISSUE THREAD

**Issue by khassanoff** [espnet/espnet#3665]
Hi All,

I am getting the following error when I try to run my recipe (based on egs2) using my own data with the SpeedPerturb:

> 2021-10-15T10:41:31 (asr.sh:419:main) Stage 1: Data preparation for data/build, data/dev, etc.
2021-10-15T10:41:31 (data.sh:20:main) local/data.sh 
2021-10-15T10:41:31 (data.sh:44:main) stage 2: Data preparation
utils/fix_data_dir.sh: file data/dev/wav.scp is not in sorted order or not unique, sorting it
fix_data_dir.sh: kept all 27210 utterances.
fix_data_dir.sh: old files are kept in data/dev/.backup
utils/validate_data_dir.sh: Successfully validated data-directory data/dev
utils/fix_data_dir.sh: file data/build/wav.scp is not in sorted order or not unique, sorting it
fix_data_dir.sh: kept all 26402 utterances.
fix_data_dir.sh: old files are kept in data/build/.backup
utils/validate_data_dir.sh: Successfully validated data-directory data/build
2021-10-15T10:41:36 (data.sh:86:main) Successfully finished. [elapsed=5s]
2021-10-15T10:41:36 (asr.sh:426:main) Stage 2: Speed perturbation: data/build -> data/build_sp
scripts/utils/perturb_data_dir_speed.sh: generated speed-perturbed version of data in data/build, in data/build_sp1.1
utils/validate_data_dir.sh: Utterance list differs between data/build_sp1.1/utt2spk and data/build_sp1.1/segments 
utils/validate_data_dir.sh: Lengths are 26400 vs 26402
run.sh done.

I also tried other speed perturbation factors, such as 0.9, 0.95, 0.99, 1.05, and 1.2, but got the same error.

When I don't apply SpeedPerturb, my recipe runs completely without any error (including training, decoding, scoring stages)
Btw, I am using docker.

Please help to solve this issue and let me know if any other detail is needed.

Thank you!

**Comment by sw005320** [comment]
Can you identify which utterances cause this issue?
The audio might be broken or at least it would be an irregular file.

**Comment by khassanoff** [comment]
I found those two utterances and checked the corresponding audio files. The audio files are fine.
The utterances are very short and are the last segments of the audio files.
I presume that this might be the cause of the problem.

Actually, the utterances are valueless for my application and should be filtered out automatically at a later stage.
However, the recipe is failing at the 'SpeedPerturb' stage, i.e., before it reaches the 'long/short utterance removal' stage.

Maybe, I should write an additional routine that would apply "utterance pre-filtering" at the data preparation stage.
Or could it be the case that the root of the problem is something else, or there is a more optimal solution?

Thank you!

---
Here are the details of utts and audio files:

**First utterance**
>utt1 start_time: 352.435  
utt1 end_time: 352.440

Soxi output of the corresponding audio
> Input File     : 'audio1.wav'                                                                       
Channels       : 1                                                                                                                                                                                                                   
Sample Rate    : 8000                                                                                                                                                                                                                
Precision      : 16-bit                                                                                                                                                                                                              
Duration       : 00:05:52.44 = 2819520 samples ~ 26433 CDDA sectors                                                                                                                                                                  
File Size      : 5.64M                                                                                                                                                                                                               
Bit Rate       : 128k                                                                                                                                                                                                                
Sample Encoding: 16-bit Signed Integer PCM

**Second utterance**
>utt2 start_time: 600.095
utt2 end_time:  600.100

Soxi output of the corresponding audio
> Input File     : 'audio2.wav'                                                                       
Channels       : 1
Sample Rate    : 8000
Precision      : 16-bit
Duration       : 00:10:00.10 = 4800800 samples ~ 45007.5 CDDA sectors
File Size      : 9.60M
Bit Rate       : 128k
Sample Encoding: 16-bit Signed Integer PCM

**Comment by sw005320** [comment]
Year.
They are too short and useless utterances. So, you can remove them safely.
