### ISSUE TITLE
How to uninstall espnet +kaldi

### ISSUE THREAD

**Issue by stalevna** [espnet/espnet#3670]
**Describe the issue**
I would like to re-install espnet and kaldi because it seems like I am missing some folders that are supposed to be there
like this one

 $MAIN_ROOT/tools/venv/

But I couldn't find instructions on how uninstall espnet anywhere

[x] python=3.8.10 (default, Jun  2 2021, 10:49:15)  [GCC 9.4.0]

Python modules:
[x] torch=1.9.0+cpu
[ ] torch cuda
[ ] torch cudnn
[ ] torch nccl
[x] chainer=6.0.0
[ ] chainer cuda
[ ] chainer cudnn
[ ] cupy
[x] torchaudio=0.9.0
[x] torch_optimizer=0.1.0
[ ] warpctc_pytorch
[ ] warprnnt_pytorch
[ ] chainer_ctc
[ ] pyopenjtalk
[ ] tdmelodic_pyopenjtalk
[ ] kenlm
[ ] mmseg
[x] espnet=0.10.3a4
[ ] fairseq
[ ] phonemizer
[ ] gtn
[ ] s3prl
[ ] transformers

Executables:
[ ] sclite
[ ] sph2pipe
[ ] PESQ
[ ] BeamformIt

INFO:
Use 'installers/install_warp-ctc.sh' to install warpctc_pytorch
Use 'installers/install_warp-transducer.sh' to install warprnnt_pytorch
Use 'installers/install_chainer_ctc.sh' to install chainer_ctc
Use 'installers/install_pyopenjtalk.sh' to install pyopenjtalk
Use 'installers/install_tdmelodic_pyopenjtalk.sh' to install tdmelodic_pyopenjtalk
Use 'installers/install_kenlm.sh' to install kenlm
Use 'installers/install_py3mmseg.sh' to install mmseg
Use 'installers/install_fairseq.sh' to install fairseq
Use 'installers/install_phonemizer.sh' to install phonemizer
Use 'installers/install_gtn.sh' to install gtn
Use 'installers/install_s3prl.sh' to install s3prl
Use 'installers/install_transformers.sh' to install transformers
Use 'installers/install_sctk.sh' to install sclite
Use 'installers/install_sph2pipe.sh' to install sph2pipe
Use 'installers/install_pesq.sh' to install PESQ
Use 'installers/install_beamformit.sh' to install BeamformIt

```

**Basic environments:**
- OS information: Linux 5.11.0-37-generic #41~20.04.2-Ubuntu SMP Fri Sep 24 09:06:38 UTC 2021 x86_64
 - python version: `3.8.10 (default, Jun  2 2021, 10:49:15)  [GCC 9.4.0]`
- espnet version: `espnet 0.10.3a4`
- pytorch version: `pytorch 1.9.0+cpu`
Git hash: `66facd2859977d23349cf74d5c8f5394e5cb6784`
  - Commit date: `Sun Oct 3 12:14:15 2021 +0900`



**Environments from `torch.utils.collect_env`:**
PyTorch version: 1.9.0+cpu
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.2 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-6ubuntu2) 7.5.0
Clang version: Could not collect
CMake version: version 3.16.3
Libc version: glibc-2.31

Python version: 3.8 (64-bit runtime)
Python platform: Linux-5.11.0-37-generic-x86_64-with-glibc2.29
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.20.3
[pip3] pytorch-ranger==0.1.1
[pip3] pytorch-wpe==0.0.1
[pip3] torch==1.9.0+cpu
[pip3] torch-complex==0.2.1
[pip3] torch-optimizer==0.1.0
[pip3] torchaudio==0.9.0
[conda] Could not collect


**To Reproduce**
Steps to reproduce the behavior by showing us the specific installation commands with their arguments, e.g.,
```
cd <espnet-root>/tools
make TH_VERSION=1.3.1
```
expr: syntax error: unexpected argument ‘102’
Perform on CPU mode: CPU_ONLY=0
PYTHON=/home/stalevna/MultilingualASR/bin/python3
PYTHON_VERSION=Python 3.8.10
IS_CONDA=
USE_PIP=0
TH_VERSION=1.3.1
CONDA_PYTORCH=pytorch=1.3.1 cpuonly -c pytorch
PIP_PYTORCH=torch==1.3.1 -f https://download.pytorch.org/whl/cpu/torch_stable.html
CHAINER_VERSION=6.0.0
PIP_CHAINER=chainer==6.0.0
NO_CUPY=0
. ./activate_python.sh; . ./extra_path.sh; python3 check_install.py
[x] python=3.8.10 (default, Jun  2 2021, 10:49:15)  [GCC 9.4.0]

Python modules:
[x] torch=1.9.0+cpu
[ ] torch cuda
[ ] torch cudnn
[ ] torch nccl
[x] chainer=6.0.0
[ ] chainer cuda
[ ] chainer cudnn
[ ] cupy
[x] torchaudio=0.9.0
[x] torch_optimizer=0.1.0
[ ] warpctc_pytorch
[ ] warprnnt_pytorch
[ ] chainer_ctc
[ ] pyopenjtalk
[ ] tdmelodic_pyopenjtalk
[ ] kenlm
[ ] mmseg
[x] espnet=0.10.3a4
[ ] fairseq
[ ] phonemizer
[ ] gtn
[ ] s3prl
[ ] transformers

Executables:
[x] sclite
[x] sph2pipe
[ ] PESQ
[ ] BeamformIt

INFO:
Use 'installers/install_warp-ctc.sh' to install warpctc_pytorch
Use 'installers/install_warp-transducer.sh' to install warprnnt_pytorch
Use 'installers/install_chainer_ctc.sh' to install chainer_ctc
Use 'installers/install_pyopenjtalk.sh' to install pyopenjtalk
Use 'installers/install_tdmelodic_pyopenjtalk.sh' to install tdmelodic_pyopenjtalk
Use 'installers/install_kenlm.sh' to install kenlm
Use 'installers/install_py3mmseg.sh' to install mmseg
Use 'installers/install_fairseq.sh' to install fairseq
Use 'installers/install_phonemizer.sh' to install phonemizer
Use 'installers/install_gtn.sh' to install gtn
Use 'installers/install_s3prl.sh' to install s3prl
Use 'installers/install_transformers.sh' to install transformers
Use 'installers/install_pesq.sh' to install PESQ
Use 'installers/install_beamformit.sh' to install BeamformIt

**Error logs**

When running
./recog_wav.sh 48408848.wav 

I get the following 

./recog_wav.sh: line 78: basename: command not found

**Comment by kamo-naoyuki** [comment]
Is your problem `./recog_wav.sh: line 78: basename: command not found`?
You don't have `basename` command in your system, so you need to modify the part. https://github.com/espnet/espnet/blob/867484e1023a35e0e5a852df00e3a05847dc5b11/utils/recog_wav.sh#L193

To uninstall espnet module from python:

```
pip uninstall espnet
```

To remove python and reinstall fom scratch

```
rm -rf <your-python>
cd espnet/tools
make clean
```


To uninstall Kaldi

```
cd kaldi/tools
make clean
```

See also:

https://github.com/espnet/espnet/blob/867484e1023a35e0e5a852df00e3a05847dc5b11/tools/Makefile#L239-L253
