### ISSUE TITLE
GPU Decoding Segmentation Faults

### ISSUE THREAD

**Issue by supernirmesh** [espnet/espnet#3671]
Hi, while trying to decode model on GPU, we are getting segmentation fault error. Log file doesnot contain any error.  Decoding on CPU works  fine but it is taking too much time. We are using conformer-based model,

batchsize: 0
beam-size: 10
penalty: 0.0
maxlenratio: 0.0
minlenratio: 0.0
ctc-weight: 0.5
lm-weight: 0.7
ngram-weight: 0.3

----------------------------------
we have tried nj=1,2 4 8, etc.
---------------------------~

        ${decode_cmd} JOB=1:${nj} ${expdir}/${decode_dir}/log/decode.JOB.log \
            asr_recog.py \
            --config ${decode_config} \
            --ngpu 1 \
            --backend ${backend} \
            --batchsize 0 \
            --recog-json ${feat_recog_dir}/split${nj}utt/data.JOB.json \
            --result-label ${expdir}/${decode_dir}/data.JOB.json \
            --model ${expdir}/results/${recog_model}  \
            --rnnlm ${lmexpdir}/rnnlm.model.best \
            ${recog_v2_opts}

**Comment by sw005320** [comment]
Can you change `--batchsize 0` to `--batchsize 1`?

**Comment by qmpzzpmq** [comment]
yes I can
