### ISSUE TITLE
About ncnn deployment

### ISSUE THREAD

**Issue by guijuzhejiang** [espnet/espnet#3684]
I want to use the NCNN framework to deploy the ASR model on Android phones, is there any guidance?

**Comment by csukuangfj** [comment]
> I want to use the NCNN framework to deploy the ASR model on Android phones, is there any guidance?

@guijuzhejiang 

The subproject of Next-gen Kaldi
https://github.com/k2-fsa/sherpa-ncnn
is exactly what you are looking for.

It uses ncnn for real-time speech recognition and supports Android, iOS, Raspberry pi, etc.
