### ISSUE TITLE
White space in model names

### ISSUE THREAD

**Issue by huangruizhe** [espnet/espnet#3691]
I noticed there are some models in [espnet_model_zoo](https://github.com/espnet/espnet_model_zoo/blob/master/espnet_model_zoo/table.csv) having white space in their names. This can make bash to unexpectedly stop, when we try to download and evaluate the models, following the instruction [in the tutorial](https://espnet.github.io/espnet/espnet2_tutorial.html#evaluation-without-training-using-pretrained-model). For example, I did the following (with quotes around the model name):
```
bash run.sh --skip_data_prep true --skip_train true --download_model "Yuekai Zhang/swbd_asr_train_asr_cformer5_raw_bpe2000_sp_valid.acc.ave"
```

Then, the following error happened:
![Screen Shot 2021-10-24 at 11 20 21 PM](https://user-images.githubusercontent.com/28626513/138632028-3f06ccbc-5cab-4247-9235-2f9d9850a5c8.jpg)

The error is due to the parameters passed to `utils/split_scp.pl` having a white space in it. Here is a closer look at how `utils/split_scp.pl` was called and led to the error -- let's pay attention to the white space in the directory name:
![Screen Shot 2021-10-24 at 11 27 11 PM](https://user-images.githubusercontent.com/28626513/138632297-a604a1bc-4afd-4125-9ea6-198d434e315d.jpg)

I tried to modify the following codes to circumvent the trouble caused by the white spaces, but could not come up with a good idea -- adding extra quotes or adding back slashes in the dir names does not work for me.
https://github.com/espnet/espnet/blob/c31c1a132d7825aa4742ba0f89f5b55f8d5546e7/egs2/TEMPLATE/asr1/asr.sh#L1199-L1203
Instead, for the moment, I am doing some quick fix by modifying the dir names _manually_.

**Comment by Emrys365** [comment]
My workaround was replace the space symbols with underscores in this [line](https://github.com/espnet/espnet/blob/c31c1a132d7825aa4742ba0f89f5b55f8d5546e7/egs2/TEMPLATE/asr1/asr.sh#L1105):
```python
    asr_exp="${expdir}/${download_model// /_}
```
