### ISSUE TITLE
Questions regarding the CommonVoice asr recipe (inference quality, LM model, inference speed)

### ISSUE THREAD

**Issue by kormoczi** [espnet/espnet#3696]
Hi,
I am started to play with the commonvoice asr repice, until now with limited success.
(First, it looks strange for me, that the run.sh script referring to conf/tuning/train_asr_conformer5.yaml, as the asr_config directly, and not via the conf/train_asr.yaml link, but this is not a big issue...)
I have a small database (val: 12532 utterances, test: 3427, dev: 3058), so maybe the default parameters are not quite good, so I have tried to increase the epoch numbers both for the lm and conformer, but the inference quality is quite bad with the trained model, even with samples from the original dataset.
So my first question is, how I should play with the lm training parameters or how I can check the quality of the lm model? For example, the nbpe is a little unclear for me... When this should be higher (200, 300 or more), and when lower (e.g. 150)? And the bpe.vocab looks also strange. What should be the content of this file? Letters, syllables, words? When we can say, that the voca is good? And I cannot see any charts in the lm_stats folder (about regression, error rate, etc.)...
Second question is, with a small dataset like mine, which one is better, conformer5 or transformer?
Third question is, what shall I expect as an inference speed with a trained model? With short sentences I got the inference results in around 3 to 8 seconds, which looks a little slow for me (I am using GPU based inference). Can I check if the asr model is slow or the lm model? (And which one is faster, conformer5 or transformer?)
Thanks!

**Comment by ftshijt** [comment]
Just a note with the issue, we already have a notebook created by @DanBerrebbi at https://github.com/espnet/notebook/blob/master/espnet2_asr_transfer_learning_demo.ipynb
