### ISSUE TITLE
How can we deploy the ESPNET TTS model on Android 

### ISSUE THREAD

**Issue by ican24** [espnet/espnet#3702]
Dear Team,

Is it possible to deploy the ESPNET TTS model on Android?
If yes, could you advise right way for this purpose?

Thank you in advance!

**Comment by ican24** [comment]
Dear @Fhrozen,

I have 2 questions:
1. Is it correct to use  such frontend function taken from espnet1 examples?
`trans_type = "phn"
dict_path = "phn_train_no_dev_units2.txt"
device="cpu"
with open(dict_path) as f:
    lines = f.readlines()
lines = [line.replace("\n", "").split(" ") for line in lines]
char_to_id = {c: int(i) for c, i in lines}
print("char_to_id:")
print(char_to_id)

def frontend(text):
    """Clean text and then convert to id sequence."""
    #text = custom_english_cleaners(text)
    
    if trans_type == "phn":
        #text = filter(lambda s: s != " ", g2p(text))
        text = filter(lambda s: s != " ", text)
        text = " ".join(text)
        print(f"Cleaned text: {text}")
        charseq = text.split(" ")
    else:
        print(f"Cleaned text: {text}")
        charseq = list(text)
    idseq = []
    for c in charseq:
        if c.isspace():
            idseq += [char_to_id["<space>"]]
        elif c not in char_to_id.keys():
            idseq += [char_to_id["<unk>"]]
        else:
            idseq += [char_to_id[c]]
    idseq += [idim - 1]  # <eos>
    return torch.LongTensor(idseq).view(-1).to(device)
`
2. if yes, do I need to use units from config.yaml? It seems ESPnet2 has no  phn_train_no_dev_units.txt. Right now I am using FastSpeech2 model generated by ESPnet2

Thank you in advance!
I may move this question as separate issue, if it is needed

**Comment by Fhrozen** [comment]
I am wondering if you are looking for this: https://huggingface.co/julien-c/ljspeech_tts_train_tacotron2_raw_phn_tacotron_g2p_en_no_space_train/tree/main/exp/tts_stats_raw_phn_tacotron_g2p_en_no_space/train

> 1. Is it correct to use such frontend function taken from espnet1 examples?

I would recommend you to use frontend from ESPnet2. 
You can find plenty examples of using the frontend from ESPnet2 https://github.com/espnet/espnet/blob/08feae5bb93fa8f6dcba66760c8617a4b5e39d70/egs/vcc20/tts1_en_fi/local/clean_text_css10.py

> 2. if yes, do I need to use units from config.yaml?

Yes, even if you are using the frontend from from ESPnet 1, you will need to use units from config.yaml to map the input.

**Comment by ican24** [comment]
Thank you very much!
Firstly I'll try to move huggingface's ljspeech model to ONNX to understand full process and details than I'll try same for my custom model, which is used self-made g2p method for my language.

**Comment by ican24** [comment]
Dear @Fhrozen,
 
> I would recommend you to use frontend from ESPnet2. You can find plenty examples of using the frontend from ESPnet2 https://github.com/espnet/espnet/blob/08feae5bb93fa8f6dcba66760c8617a4b5e39d70/egs/vcc20/tts1_en_fi/local/clean_text_css10.py

This frontend exmaple does not explain converting from G2P list to tensor. 
Meanwhile in your exmaple frontend(input_text) returns value, which must be unsqueezed in the next step: 
xs = x.unsqueeze(0)

Below is my code. Practically just I need to solve this issue with the help of ESP2 to force it to work.

`from espnet2.bin.tts_inference import Text2Speech
from espnet2.utils.types import str_or_none
import torch
import subprocess
import sys
import numpy as np

from g2p_en import G2p
f_g2p = G2p()

import soundfile as sf
import time


model_tag="kan-bayashi/ljspeech_conformer_fastspeech2"
vocoder_tag="parallel_wavegan/ljspeech_style_melgan.v1"

text2speech = Text2Speech.from_pretrained(
    model_tag=str_or_none(model_tag),
    vocoder_tag=str_or_none(vocoder_tag),
    device="cuda",
    # Only for Tacotron 2 & Transformer
    threshold=0.5,
    # Only for Tacotron 2
    minlenratio=0.0,
    maxlenratio=10.0,
    use_att_constraint=False,
    backward_window=1,
    forward_window=3,
    # Only for FastSpeech & FastSpeech2 & VITS
    speed_control_alpha=1.0,
    # Only for VITS
    noise_scale=0.333,
    noise_scale_dur=0.333,
)

def main():
    print("\nInput your favorite sentence in English!")
    input_text = input()
    with torch.no_grad():
        #x = frontend(input_text)    
        #x = torch.tensor([ 10, 7, 20, 20, 15])
        x = np.squeeze(f_g2p(input_text))
        print(x)

        xs = x.unsqueeze(0)
        ilens_value = x.size(0)
        ilens = [ilens_value]
        print(x.shape,xs.shape,ilens_value,ilens)
        print(x)
        print(xs)

        ilens_tensor = torch.from_numpy(np.array(ilens))
        ilens_tensor = ilens_tensor.float()
        xs = xs.float()

        inputs = (xs, ilens_tensor)

        output = text2speech(xs,ilens_tensor)                          
        output = output.squeeze(0)
        print(output.shape)
        print('\n')

        print("inputs ONNX",inputs,xs.dtype,ilens_tensor.dtype)

        onnx_model_name = 'ESPnet2_TTS.onnx'
        torch.onnx.export(
        text2speech,
        inputs,
        onnx_model_name,
        export_params = True,
        opset_version = 12,
        do_constant_folding = True,
        input_names = ['input'],
        output_names = ['output'],
        dynamic_axes = {
            'input' : [0,1], # Variable axis
            'output' : [0,1], # Axis 0: batchsize, Axis 1: Frames
        })
        print("Done!")

main()
` 
Thank you in advance

**Comment by Fhrozen** [comment]
Ok, i will need to research a little longer. Some conditions are quite different from what I usually do.
For using TTS in real-time (No ONNX) it is just straightforward, you can even check here: https://github.com/espnet/notebook/blob/master/espnet2_tts_realtime_demo.ipynb

But, for ONNX I think that first, you will need to implement the FrontEnd as a previous step. 
In the Notebook, the input is pure text, because the frontend already check to the phonemes.

This line builds the preprocessor: https://github.com/espnet/espnet/blob/ff870699fafabd13f3a10610a78cb2da3e386a64/espnet2/bin/tts_inference.py#L112

I will try to check the fixes.
Just in case, some conversion from text to phn, and the remove the g2p and cleaner can be observe here:

https://github.com/espnet/espnet/tree/master/egs2/vctk/tts1#vctk_tts_train_full_band_multi_spk_vits_raw_phn_tacotron_espeak_ng_english_us_vits_traintotal_countave-1

**Comment by sciai-ai** [comment]
@Fhrozen Do you have a working example of TTS onxx with espnet? Thank you!

**Comment by Fhrozen** [comment]
@sciai-ai, Sorry I do not have any available example for TTS ONNX. 
I will try to prepare one later using a notebook or a gist.

**Comment by sciai-ai** [comment]
Thank you @Fhrozen it owuld be great if you can do one with Espnet 2 TTS as I have a custom model trained using egs2 ljspeech style recipe

**Comment by ican24** [comment]
> @sciai-ai, Sorry I do not have any available example for TTS ONNX. I will try to prepare one later using a notebook or a gist.

Thank you very much! It is so important to bring this wonderful solution to the wide-scale equipment. It could be a breakthrough solution in TTS like VOSK for Kaldi ASR. 
We look forward to it.

**Comment by sciai-ai** [comment]
@Fhrozen I am getting theis error while doing the conversion step

`---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/tmp/ipykernel_13419/3336720621.py in <module>
      3 text2speech,
      4 inputs,
----> 5 onnx_model_name
      6 )

/opt/conda/lib/python3.7/site-packages/torch/onnx/__init__.py in export(model, args, f, export_params, verbose, training, input_names, output_names, aten, export_raw_ir, operator_export_type, opset_version, _retain_param_name, do_constant_folding, example_outputs, strip_doc_string, dynamic_axes, keep_initializers_as_inputs, custom_opsets, enable_onnx_checker, use_external_data_format)
    274                         do_constant_folding, example_outputs,
    275                         strip_doc_string, dynamic_axes, keep_initializers_as_inputs,
--> 276                         custom_opsets, enable_onnx_checker, use_external_data_format)
    277 
    278 

/opt/conda/lib/python3.7/site-packages/torch/onnx/utils.py in export(model, args, f, export_params, verbose, training, input_names, output_names, aten, export_raw_ir, operator_export_type, opset_version, _retain_param_name, do_constant_folding, example_outputs, strip_doc_string, dynamic_axes, keep_initializers_as_inputs, custom_opsets, enable_onnx_checker, use_external_data_format)
     92             dynamic_axes=dynamic_axes, keep_initializers_as_inputs=keep_initializers_as_inputs,
     93             custom_opsets=custom_opsets, enable_onnx_checker=enable_onnx_checker,
---> 94             use_external_data_format=use_external_data_format)
     95 
     96 

/opt/conda/lib/python3.7/site-packages/torch/onnx/utils.py in _export(model, args, f, export_params, verbose, training, input_names, output_names, operator_export_type, export_type, example_outputs, opset_version, _retain_param_name, do_constant_folding, strip_doc_string, dynamic_axes, keep_initializers_as_inputs, fixed_batch_size, custom_opsets, add_node_names, enable_onnx_checker, use_external_data_format, onnx_shape_inference, use_new_jit_passes)
    674         _set_opset_version(opset_version)
    675         _set_operator_export_type(operator_export_type)
--> 676         with select_model_mode_for_export(model, training):
    677             val_keep_init_as_ip = _decide_keep_init_as_input(keep_initializers_as_inputs,
    678                                                              operator_export_type,

/opt/conda/lib/python3.7/contextlib.py in __enter__(self)
    110         del self.args, self.kwds, self.func
    111         try:
--> 112             return next(self.gen)
    113         except StopIteration:
    114             raise RuntimeError("generator didn't yield") from None

/opt/conda/lib/python3.7/site-packages/torch/onnx/utils.py in select_model_mode_for_export(model, mode)
     36 def select_model_mode_for_export(model, mode):
     37     if not isinstance(model, torch.jit.ScriptFunction):
---> 38         is_originally_training = model.training
     39 
     40         if mode is None:

AttributeError: 'Text2Speech' object has no attribute 'training'`

**Comment by Fhrozen** [comment]
It is because the Text2Speech is just an object and not the model to be moved to onnx. The model is found at `Text2speech.tts`

**Comment by sciai-ai** [comment]
Thanks @Fhrozen 

Now i am getting this error `TypeError: forward() missing 3 required positional arguments: 'text_lengths', 'speech', and 'speech_lengths'
`


`# Export the model
torch.onnx.export(text2speech.tts,               # model being run
                  x,                         # model input (or a tuple for multiple inputs)
                  "super_resolution.onnx",   # where to save the model (can be a file or file-like object)
                  export_params=True,        # store the trained parameter weights inside the model file
                  opset_version=10,          # the ONNX version to export the model to
                  do_constant_folding=True,  # whether to execute constant folding for optimization
                  input_names = ['input'],   # the model's input names
                  output_names = ['output'], # the model's output names
                  dynamic_axes={'input' : {0 : 1},    # variable length axes
                                'output' : {0 : 1}})`

**Comment by sciai-ai** [comment]
Thanks @Fhrozen 

Now i get another error 

`TypeError: forward() missing 3 required positional arguments: 'text_lengths', 'speech', and 'speech_lengths'`

**Comment by Fhrozen** [comment]
In this case, you will need to check the code of them call from Text2speech object https://github.com/espnet/espnet/blob/4615a5871ea886ebd9852ae9b5d2140f50a453b0/espnet2/bin/tts_inference.py#L154-L219

Here, you will need yo copy the configuration dict (cfg) for running the `.model` part

**Comment by sciai-ai** [comment]
@Fhrozen I think it actually comes from 

https://github.com/espnet/espnet/blob/08feae5bb93fa8f6dcba66760c8617a4b5e39d70/espnet2/tts/tacotron2.py

I only need x which is token ids for getting output but when converting to onxx input=x seems to be causing this error 

`def forward(
        self,
        text: torch.Tensor,
        text_lengths: torch.Tensor,
        speech: torch.Tensor,
        speech_lengths: torch.Tensor,
        spembs: torch.Tensor = None,
    ) -> Tuple[torch.Tensor, Dict[str, torch.Tensor], torch.Tensor]:
        """Calculate forward propagation.
        Args:
            text (LongTensor): Batch of padded character ids (B, Tmax).
            text_lengths (LongTensor): Batch of lengths of each input batch (B,).
            speech (Tensor): Batch of padded target features (B, Lmax, odim).
            speech_lengths (LongTensor): Batch of the lengths of each target (B,).
            spembs (Tensor, optional): Batch of speaker embeddings (B, spk_embed_dim).
        Returns:
            Tensor: Loss scalar value.
            Dict: Statistics to be monitored.
            Tensor: Weight value.`

**Comment by Fhrozen** [comment]
In the conversion code

**Comment by sciai-ai** [comment]
> In this case, you will need to check the code of them call from Text2speech object
> 
> https://github.com/espnet/espnet/blob/4615a5871ea886ebd9852ae9b5d2140f50a453b0/espnet2/bin/tts_inference.py#L154-L219
> 
> Here, you will need yo copy the configuration dict (cfg) for running the `.model` part

I am a bit confused as the code here is already doing inference, in lines 200-219. I thought that the inference part should be calculated within the Text2speech.tts so that the inference speed is faster when we convert to onxx?

**Comment by Fhrozen** [comment]
Yes, but when you use `Text2Speech.tts` to obtain the onnx model, you are skipping the preparation of the input for the `.tts` part. So you need to add each of the arguments for performing the inference that is done in L203. 
`output_dict = self.model.inference(**batch, **cfg) `

**Comment by sciai-ai** [comment]
I have prepared the batch and config dictionaries, but I am getting the error below. It seems that the durations need to be calculated before hand? My batch is just having the text in it.  

`/opt/conda/lib/python3.7/site-packages/espnet2/tts/tacotron2.py in forward(self, text, text_lengths, speech, speech_lengths, spembs)
    281 
    282         """
--> 283         text = text[:, : text_lengths.max()]  # for data-parallel
    284         speech = speech[:, : speech_lengths.max()]  # for data-parallel
    285 

AttributeError: 'NoneType' object has no attribute 'max'
cfg
`

**Comment by Fhrozen** [comment]
@sciai-ai @ican24 I wrote a gist for this issue: https://gist.github.com/Fhrozen/60b38bd3ee23492d28b602a0c9f92217
However, the it still required more tuning.
The issue is that some internal parts of the code employs python dicts, list that become constant and cannot be traced by ONNX.
I will try to check the code on weekend (or next week).

**Comment by sciai-ai** [comment]
Thanks @Fhrozen I tried your code and got another error 

RuntimeError: Exporting the operator _thnn_fused_lstm_cell to ONNX opset version 13 is not supported. Please feel free to request support or submit a pull request on PyTorch GitHub.

**Comment by Fhrozen** [comment]
@sciai-ai I think that it will be better to discuss inside the gist.
But for the moment change the version of the opset:
https://gist.github.com/Fhrozen/60b38bd3ee23492d28b602a0c9f92217#file-convert_tts2onnx-py-L118
Try: `opset_version=12,` or less

**Comment by unparalleled-ysj** [comment]
@ican24 @Fhrozen @sciai-ai Has anyone converted the tts model to onnx format and ran it successfully ？

**Comment by pukatana** [comment]
Is there any updates to run the espnet model on Android?

**Comment by Fhrozen** [comment]
If you want to obtain an ONNX model for an Android APP, you can use https://github.com/espnet/espnet_model_zoo to get the ONNX model.
Then, follow the guide at https://onnxruntime.ai/docs/tutorials/mobile/deploy-android.html to deploy your apk.

**Comment by pukatana** [comment]
Hi @Fhrozen ,
There is some problem to implement openjtalk on Android?
Is there any solution?

**Comment by Fhrozen** [comment]
I did not test openjtalk on Android, but you can check by deploying the library from CSharp (https://www.hanachiru-blog.com/entry/2022/05/16/120000) on android os and then moving it into your application.
