### ISSUE TITLE
Wandb 0.12.6 leads to Import Failure. Works on reverting to 0.12.2

### ISSUE THREAD

**Issue by gdebayan** [espnet/espnet#3708]
While Looking up ESPNet using this Tutorial: https://colab.research.google.com/drive/1L85G7jdhsI1QKs2o0qCGEbhm5X4QV2zN

I came across this issue when the Library "Wandb" is imported.

```
# python3 -m espnet2.bin.asr_train --collect_stats true --use_preprocessor true --bpemodel data/token_list/bpe_unigram30/bpe.model --token_type bpe --token_list data/token_list/bpe_unigram30/tokens.txt --non_linguistic_symbols none --cleaner none --g2p none --train_data_path_and_name_and_type dump/raw/train_nodev/wav.scp,speech,sound --train_data_path_and_name_and_type dump/raw/train_nodev/text,text,text --valid_data_path_and_name_and_type dump/raw/train_dev/wav.scp,speech,sound --valid_data_path_and_name_and_type dump/raw/train_dev/text,text,text --train_shape_file exp/asr_stats_raw_bpe30/logdir/train.32.scp --valid_shape_file exp/asr_stats_raw_bpe30/logdir/valid.32.scp --output_dir exp/asr_stats_raw_bpe30/logdir/stats.32 --frontend_conf fs=16k 
# Started at Wed Oct 27 16:36:43 EDT 2021
```

```
    from .wandb_init import _attach, init  # noqa: F401
  File "/home/debayan/.local/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 35, in <module>
    from .backend.backend import Backend
  File "/home/debayan/.local/lib/python3.8/site-packages/wandb/sdk/backend/backend.py", line 20, in <module>
    from ..interface import interface
  File "/home/debayan/.local/lib/python3.8/site-packages/wandb/sdk/interface/interface.py", line 21, in <module>
    from wandb.proto import wandb_internal_pb2 as pb
  File "/home/debayan/.local/lib/python3.8/site-packages/wandb/proto/wandb_internal_pb2.py", line 15, in <module>
    from wandb.proto import wandb_base_pb2 as wandb_dot_proto_dot_wandb__base__pb2
  File "/home/debayan/.local/lib/python3.8/site-packages/wandb/proto/wandb_base_pb2.py", line 21, in <module>
    create_key=_descriptor._internal_create_key,
AttributeError: module 'google.protobuf.descriptor' has no attribute '_internal_create_key
```

This was in Wandb version 0.12.6 .

However, when I reverted to Wandb version 0.12.2, it started working as expected.

Feel free to reach out if any questions!

**Comment by sw005320** [comment]
If the protobuf version is an issue, should we specify the version in https://github.com/espnet/espnet/blob/master/setup.py?

**Comment by kan-bayashi** [comment]
This is a little bit complicated.
Chainer requires lower version of protobuf, which will conflict.
I have no smart way to solve this problem :(

**Comment by Fhrozen** [comment]
Weeelll, ESPnet 1 employs chainer and not wandb, while ESPnet2 employs wandb and not chainer. IMO, the best solution will be to slip the projects, so we reduce the dependency on older pkg.

**Comment by sw005320** [comment]
> Weeelll, ESPnet 1 employs chainer and not wandb, while ESPnet2 employs wandb and not chainer. IMO, the best solution will be to slip the projects, so we reduce the dependency on older pkg.

I see. 
This would be a smart solution, but it may take some time.

For now, how about using older versions of wandb?
It is a little bit unfortunate, but I think this will be fixed in the future.

**Comment by henry034** [comment]
It also happend to me today with a fresh installation on Ubuntu 20.0.4. Python 3.8
Only downgrading **wandb** to 0.12.2 is not work for me.
I have to downgrande **protobuf** to 3.18.0 (from 3.19.1) too to fix the issue.

**Comment by kamo-naoyuki** [comment]
How about patching chainer=6.0.0 to use newer protobuf?   

```sh
git clone https://github.com/chainer/chainer/ -b v6.0.0
patch chainer/setup.py <patch> # Change ptorobuf requirement
pip install -e chainer/
```

**Comment by kan-bayashi** [comment]
+1 for kamo-san's idea :)

**Comment by kamo-naoyuki** [comment]
If there is no disagreement, I'll proceed in my direction.

**Comment by wjl1999** [comment]
> While Looking up ESPNet using this Tutorial: https://colab.research.google.com/drive/1L85G7jdhsI1QKs2o0qCGEbhm5X4QV2zN
> 
> I came across this issue when the Library "Wandb" is imported.
> 
> ```
> # python3 -m espnet2.bin.asr_train --collect_stats true --use_preprocessor true --bpemodel data/token_list/bpe_unigram30/bpe.model --token_type bpe --token_list data/token_list/bpe_unigram30/tokens.txt --non_linguistic_symbols none --cleaner none --g2p none --train_data_path_and_name_and_type dump/raw/train_nodev/wav.scp,speech,sound --train_data_path_and_name_and_type dump/raw/train_nodev/text,text,text --valid_data_path_and_name_and_type dump/raw/train_dev/wav.scp,speech,sound --valid_data_path_and_name_and_type dump/raw/train_dev/text,text,text --train_shape_file exp/asr_stats_raw_bpe30/logdir/train.32.scp --valid_shape_file exp/asr_stats_raw_bpe30/logdir/valid.32.scp --output_dir exp/asr_stats_raw_bpe30/logdir/stats.32 --frontend_conf fs=16k 
> # Started at Wed Oct 27 16:36:43 EDT 2021
> ```
> 
> ```
>     from .wandb_init import _attach, init  # noqa: F401
>   File "/home/debayan/.local/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 35, in <module>
>     from .backend.backend import Backend
>   File "/home/debayan/.local/lib/python3.8/site-packages/wandb/sdk/backend/backend.py", line 20, in <module>
>     from ..interface import interface
>   File "/home/debayan/.local/lib/python3.8/site-packages/wandb/sdk/interface/interface.py", line 21, in <module>
>     from wandb.proto import wandb_internal_pb2 as pb
>   File "/home/debayan/.local/lib/python3.8/site-packages/wandb/proto/wandb_internal_pb2.py", line 15, in <module>
>     from wandb.proto import wandb_base_pb2 as wandb_dot_proto_dot_wandb__base__pb2
>   File "/home/debayan/.local/lib/python3.8/site-packages/wandb/proto/wandb_base_pb2.py", line 21, in <module>
>     create_key=_descriptor._internal_create_key,
> AttributeError: module 'google.protobuf.descriptor' has no attribute '_internal_create_key
> ```
> 
> This was in Wandb version 0.12.6 .
> 
> However, when I reverted to Wandb version 0.12.2, it started working as expected.
> 
> Feel free to reach out if any questions!

It work for me！
