### ISSUE TITLE
How do I skip the installation of kaldi for espnet2 if a symbolic link to kaldi tools is still required??

### ISSUE THREAD

**Issue by psydok** [espnet/espnet#3730]
**Describe the bug**
You write on the [site ](https://espnet.github.io/espnet/installation.html) that you can skip the installation of Kaldi: 
![image](https://user-images.githubusercontent.com/47638600/139641552-b3f282b2-2871-4a55-bff7-e4727272345b.png)

At the same time, you will not be able to run the recipe from egs2 if you have not installed kaldi:
![image](https://user-images.githubusercontent.com/47638600/139641928-64e03473-0124-4d75-b87f-d0d2ffd7766d.png)
 
It is very strange.

**Comment by kan-bayashi** [comment]
For ESPnet2, kaldi compile is not needed but we use kaldi utility tools.
(Kaldi installation ~= kaldi compile)
Therefore, we need to put kaldi in `espnet/tools/`.

**Comment by psydok** [comment]
@kan-bayashi Sad, but understandable. Thank you very much!
