### ISSUE TITLE
about csmsc vits train

### ISSUE THREAD

**Issue by LinJinghuidev** [espnet/espnet#3737]
The Vits model of csmsc in colab is very effective. I use csmsc to do mono pronunciation training locally, batch_bins is 100000 and 150 epochs have been run, but the synthesis effect is still not good. How many epochs do you have to run for these 10000 data to make the effect obvious

**Comment by LinJinghuidev** [comment]
The csmsc + Vits model in colab is generated by how many epochs the 10000 pieces of csmsc data run

**Comment by LinJinghuidev** [comment]
This is the synthetic audio of 150 epochs, and the text is the first article of csmsc

https://user-images.githubusercontent.com/42993920/139800629-b3aa1c23-acb5-4ebe-a49b-425695331401.mp4

**Comment by kan-bayashi** [comment]
For demo, we use the following configs
https://github.com/espnet/espnet/blob/master/egs2/csmsc/tts1/conf/tuning/train_full_band_vits.yaml#L161-L162

The total iterations is 1M (1000 iters / epoch * 1000 epochs with batch_bins= 10000000).
(For GAN-based traning, `#iters` is more important than `#epochs`)
In my experiments, 500k iters can produce good quality.

**Comment by LinJinghuidev** [comment]
Can you confirm it for me

1、The dataset has only csmsc

2、The FS of the configuration file is 44100. Do I need to manually process the csmsc dataset from 48000 to 44100, or has it been uniformly processed in your step

3、Operation process is
     1、./run.sh --stage 1 --stop-stage 

     2、./run.sh \
    --stage 2 \
    --ngpu 4 \
    --fs 44100 \
    --n_fft 2048 \
    --n_shift 512 \
    --win_length null \
    --dumpdir dump/44k \
    --expdir exp/44k \
    --tts_task gan_tts \
    --feats_extract linear_spectrogram \
    --feats_normalize none \
    --train_config ./conf/tuning/train_full_band_vits.yaml \
    --inference_config ./conf/tuning/decode_vits.yaml \
    --inference_model latest.pth
 
4、if i run with batch_bins= 5000000（Half of 10000000）,Should I run 1000k iters

**Comment by LinJinghuidev** [comment]
> For demo, we use the following configs https://github.com/espnet/espnet/blob/master/egs2/csmsc/tts1/conf/tuning/train_full_band_vits.yaml#L161-L162
> 
> The total iterations is 1M (1000 iters / epoch * 1000 epochs with batch_bins= 10000000).
> 
> ```
> 2021-09-07 16:09:42,501 (abs_task:1494) INFO: [train] Batch sampler: NumElementsBatchSampler(N-batch=171, batch_bins=10000000, sort_in_
> batch=descending, sort_batch=descending)
> 2021-09-07 16:09:42,501 (abs_task:1496) INFO: [train] mini-batch sizes summary: N-batch=171, mean=57.3, min=30, max=134
> ```
> 
> (For GAN-based traning, `#iters` is more important than `#epochs`) In my experiments, 500k iters can produce good quality.

Can you confirm it for me

1、The dataset has only csmsc

2、The FS of the configuration file is 44100. Do I need to manually process the csmsc dataset from 48000 to 44100, or has it been uniformly processed in your step

3、Operation process is
       1、./run.sh --stage 1 --stop-stage

       2、./run.sh \
       --stage 2 \
       --ngpu 4 \
       --fs 44100 \
       --n_fft 2048 \
       --n_shift 512 \
       --win_length null \
       --dumpdir dump/44k \
       --expdir exp/44k \
       --tts_task gan_tts \
       --feats_extract linear_spectrogram \
       --feats_normalize none \
       --train_config ./conf/tuning/train_full_band_vits.yaml \
       --inference_config ./conf/tuning/decode_vits.yaml \
       --inference_model latest.pth
4、if i run with batch_bins= 5000000（Half of 10000000）,Should I run 1000k iters

**Comment by kan-bayashi** [comment]
> The dataset has only csmsc

Yes.

> The FS of the configuration file is 44100. Do I need to manually process the csmsc dataset from 48000 to 44100, or has it been uniformly processed in your step.

If you specify `--fs 44100`, the audio is automatically downsampled in stage 2. So you do not need to process manually.

> Operation process 

Right.

> if i run with batch_bins= 5000000（Half of 10000000）,Should I run 1000k iters

Not sure but the same iters with smaller batch size should work. So you can reduce only batch bins.

**Comment by LinJinghuidev** [comment]
OK, thank you very much

**Comment by LinJinghuidev** [comment]
With so many model combinations(tag+vocoder_tag), which combination has the best speech synthesis effect? For the Chinese multi speaker data set, similar to aishell3

**Comment by kan-bayashi** [comment]
For multi-spk case, vits is definitely better.

**Comment by LinJinghuidev** [comment]
You're great, too. It is always hard for me to imagine that when there is only csmsc data set and no pre training model, the synthesis effect is so good and the word coverage is so comprehensive

**Comment by LinJinghuidev** [comment]
Have you ever trained aishell 3 (multi speaker), and is the synthetic effect better than csmsc (single speaker)

**Comment by LinJinghuidev** [comment]
Have you ever trained aishell 3 (multi speaker), and is the synthetic effect better than csmsc (single speaker)?

**Comment by LinJinghuidev** [comment]
The csmsc model in colab is trained from scratch, and there is no pre training model, right?

**Comment by kan-bayashi** [comment]
> Have you ever trained aishell 3 (multi speaker), and is the synthetic effect better than csmsc (single speaker)?

Sorry, I've never touched aishell 3 corpus.
But in terms of sound quality, I think full-band (44.1 kHz) csmsc model is quite good (because csmsc recording itself is also very good). 

> The csmsc model in colab is trained from scratch, and there is no pre training model, right?

Yes, the model is trained with only csmsc data from scratch.
