### ISSUE TITLE
[ESPnet2-TTS] Espeak-ng realtime computational issues.

### ISSUE THREAD

**Issue by Fhrozen** [espnet/espnet#3740]
I have been testing VITS pre-trained models for audio generation (LibriTTS and VCTK)
The synthesis using espeak-ng seems better than g2p-no-space. However, I found some issues at decoding time I am not sure how to deal with.

The pre-trained model using g2p-no-space takes about 5 mins to generate around 8 utterances per each speakers-xv id available on the xvector.scp at train/dev/eval. (https://zenodo.org/record/5521416)

While, if I use the pre-trained model with espeak-ng, it takes about 8 minutes for each of eval and dev sets (16mins in total).
Also, when I try to synthesize using the x-vector at the train set, it freezes after the 112 speakers. I checked the memory, but I have enough swap memory. (https://zenodo.org/record/5560155)

One thing I notice is that the espeak-ng generates several (almost 4 each time is called) subprocesses which are not closed. If I try to kill any, the program dies. 
I try to trace the error but could not find any way to solve it. I wonder who do you trained for more than 100k iters if it freeze after some iterations. I tried to kill and launch again the Text2Speech object, but it did not release any of the threads.

**Comment by kan-bayashi** [comment]
Phonimizer with Espeak-ng is really slow.
So in my case, dump phonemized text in data prep stage.
See command section:
https://github.com/espnet/espnet/tree/master/egs2/vctk/tts1#vctk_tts_train_full_band_multi_spk_vits_raw_phn_tacotron_espeak_ng_english_us_vits_traintotal_countave-1

Recently, phonemizer is updated not to use subprocess.
https://github.com/bootphon/phonemizer/releases/tag/v3.0
It is worthwhile to try the latest phonemizer.
