### ISSUE TITLE
CUDA 11.0 compatibility

### ISSUE THREAD

**Issue by wangjg19** [espnet/espnet#3741]
I want to deploy Espnet on the Tesla A100, which can only install CUDA 11.0.  Does Espnet support CUDA 11.0？

**Comment by b-flo** [comment]
Hi,

I can't give an answer for all tasks but you shouldn't have any issues with ASR at least. I'm working with A100s and CUDA=11.1 currently.

**Comment by puvvadasaikiran** [comment]
am facing CUDA Error with ljspeech tts1 example execution on A100
is cuda 11 supported in tts?

**Comment by kamo-naoyuki** [comment]
ESPnet uses CUDA just depending on PyTorch, basically. So, the CUDA supported by ESPnet is always as same as PyTorch which you use. 

Yes, of course, it's supported. Please update PyTorch.
