### ISSUE TITLE
num_iters_per_epoch

### ISSUE THREAD

**Issue by sameerkhurana10** [espnet/espnet#3758]
Hi,

Maybe I don't understand `num_iters_per_epoch`. I saw the following explanation given [here](https://github.com/espnet/espnet/blob/master/espnet2/tasks/abs_task.py#L1421):
 
        Note that the definition of "epoch" doesn't always indicate
        to run out of the whole training corpus.
        "--num_iters_per_epoch" option restricts the number of iterations for each epoch
        and the rest of samples for the originally epoch are left for the next epoch.
        e.g. If The number of mini-batches equals to 4, the following two are same:
        - 1 epoch without "--num_iters_per_epoch"
        - 4 epoch with "--num_iters_per_epoch" == 4

Should it have been `- 4 epoch with "--num_iters_per_epoch" == 1` instead of `- 4 epoch with --num_iters_per_epoch" == 4`

**Comment by kan-bayashi** [comment]
Thank you for raising the issue.
I think your suggestion is correct.
