### ISSUE TITLE
Multi-speaker Japanese VITS pretrained model.

### ISSUE THREAD

**Issue by mudong0419** [espnet/espnet#3762]
Thanks to your great work on Japanese TTS. I'm working on Japanese TTS, and VITS model is so fast on inference on GPU. I'have found many single-speaker pretrained models, are there any multi-speaker Japanese VITS models? Thanks in advance.

**Comment by Fhrozen** [comment]
You can find all the available models at: https://huggingface.co/models?language=ja&library=espnet&pipeline_tag=text-to-speech&sort=downloads

**Comment by kan-bayashi** [comment]
There is no large-scale Japanese multi-speaker TTS corpus.
Therefore, unfortunately, we do not provide multi-speaker Japanese TT S model.

**Comment by dmjeonglib** [comment]
Thanks to your great work on korean TTS. I'm working on korean TTS, and VITS model is so fast on inference on GPU. I'have found many single-speaker pretrained models, are there any multi-speaker korean VITS models? Thanks in advance.
