### ISSUE TITLE
task stopped before asr starts

### ISSUE THREAD

**Issue by 200987299** [espnet/espnet#3763]
Dear developers,

I got this error but I don't know where to fix it. :
_

> token_type='char', train_data_path_and_name_and_type=[('dump/raw/train_sp/wav.scp', 'speech', 'sound'), ('dump/raw/train_sp/text', 'text', 'text')], train_dtype='float32', train_shape_file=['exp/asr_stats_raw_zh_char_sp/logdir/train.1.scp'], unused_parameters=False, use_amp=False, use_preprocessor=True, use_tensorboard=True, use_wandb=False, val_scheduler_criterion=['valid', 'acc'], valid_batch_bins=None, valid_batch_size=None, valid_batch_type=None, valid_data_path_and_name_and_type=[('dump/raw/dev/wav.scp', 'speech', 'sound'), ('dump/raw/dev/text', 'text', 'text')], valid_max_cache_size=None, valid_shape_file=['exp/asr_stats_raw_zh_char_sp/logdir/valid.1.scp'], version='0.10.4a1', wandb_entity=None, wandb_id=None, wandb_model_log_interval=-1, wandb_name=None, wandb_project=None, write_collected_feats=False)
> /opt/miniconda/lib/python3.7/site-packages/torch/_tensor.py:575: UserWarning: floor_divide is deprecated, and will be removed in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values.
> To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor'). (Triggered internally at  /pytorch/aten/src/ATen/native/BinaryOps.cpp:467.)

_
This happens after lm trained, and during generating asr_stats_raw_zh_char_sp folder. Does anyone has any idea where to fix it?

Bests

**Comment by sw005320** [comment]
This is not an error but a warning.

**Comment by 200987299** [comment]
> This is not an error but a warning.

Sorry, you are right, this is not the issue. I wrote a bug somewhere and caused the task stopped here.
