### ISSUE TITLE
ASR with s3prl model

### ISSUE THREAD

**Issue by liu-x-p** [espnet/espnet#3766]
Hi, I wonder how to use model pretrained by s3prl toolkit for ASR test. I found the script _espnet2/asr/frontend/s3prl.py_, but I'm not sure how to use it.

**Comment by sw005320** [comment]
@simpleoier, I think it's better to add more documentation about it, including the main README.md in addition to https://github.com/espnet/espnet/blob/2a3f8954f0fc820c32820cbae86747e2570c5407/README.md#L76. You can add more descriptions to the main README.md and add a section to the tutorial document.

Hi @liu-x-p, you can easily use it by adding a configuration, e.g., https://github.com/espnet/espnet/blob/master/egs2/slurp_entity/asr1/conf/tuning/train_asr_conformer_s3prl.yaml#L47-L63

**Comment by simpleoier** [comment]
Hi @sw005320, thanks for the comment. I will add more document about it.

**Comment by liu-x-p** [comment]
Thank you!

**Comment by liu-x-p** [comment]
Hi, when I use this toolkit for ASR, there are several lines for nltk_data in the log files in many different stages
```
[nltk_data] Error loading averaged_perceptron_tagger: <urlopen error
[nltk_data]     [Errno -2] Name or service not known>
[nltk_data] Error loading cmudict: <urlopen error [Errno -2] Name or
[nltk_data]     service not known>
```
it seems the scripts need to download nltk_data, but it can still work without it. Should it make any influence for the results?

**Comment by simpleoier** [comment]
@liu-x-p I think it makes no difference. Out of curiosity, at which stage did you get these errors?

**Comment by liu-x-p** [comment]
Stage 7(LM training), Stage 10(ASR collect stats), Stage 11(ASR Training) and Stage 12(Decoding)

**Comment by liu-x-p** [comment]
@simpleoier  Stage 7(LM training), Stage 10(ASR collect stats), Stage 11(ASR Training) and Stage 12(Decoding)

**Comment by simpleoier** [comment]
@liu-x-p Can you be more specific about where the error comes from? Is it from a specific bash script or a python script?

**Comment by liu-x-p** [comment]
I think it may come from s3prl fronend and maybe during the model-building. I tried to train a model without s3prl fronend and the problem disappeared

**Comment by simpleoier** [comment]
I tried not to uninstall NLTK from my environment and it works. I'm not sure.
s3prl frontend does not even import NLTK. If it comes from s3prl frontend, it is strange that stage7 (LM training) also output the error message.
