### ISSUE TITLE
完整的 tts 文本前端

### ISSUE THREAD

**Issue by lance6716** [espnet/espnet#3771]
这个仓库的中文文本前端只是用了 pypinyin, 缺少基础的文本正则化模块，在三声变调上表现地也不是很好，https://github.com/PaddlePaddle/DeepSpeech 里面有一些文本前端模块，还有哪些仓库提供了完整的文本前端呢（变调，多音字，停顿预测等）

**Comment by kan-bayashi** [comment]
Sorry I could not understand Mandarin. Please write in English.
