### ISSUE TITLE
asr.sh stops at stage 10, ASR stats collection with user warning.

### ISSUE THREAD

**Issue by arunbaby0** [espnet/espnet#3774]
`
[7340ae05d216] 2021-11-10 07:33:20,284 (abs_task:1150) INFO: Scheduler: WarmupLR(warmup_steps=25000)
[7340ae05d216] 2021-11-10 07:33:20,284 (abs_task:1159) INFO: Saving the configuration in exp/asr_stats_raw_hin_bpe5000/logdir/stats.1/config.yaml
[7340ae05d216] 2021-11-10 07:33:20,723 (abs_task:1170) INFO: Namespace(accum_grad=8, allow_variable_data_keys=False, batch_bins=40000000,.....

/opt/espnet2/espnet2/layers/stft.py:166: UserWarning: __floordiv__ is deprecated, and its behavior will change in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values. To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor').
  olens = (ilens - self.win_length) // self.hop_length + 1
[7340ae05d216] 2021-11-10 07:33:31,641 (collect_stats:110) INFO: Niter: 100
[7340ae05d216] 2021-11-10 07:33:40,902 (collect_stats:110) INFO: Niter: 200
[7340ae05d216] 2021-11-10 07:33:48,314 (collect_stats:110) INFO: Niter: 300
[7340ae05d216] 2021-11-10 07:33:56,091 (collect_stats:110) INFO: Niter: 400
Accounting: time=53 threads=1
Ended (code 0) at Wed Nov 10 07:34:04 UTC 2021, elapsed time 53 seconds`

**This happens only in the first run of docker. From the second time, it works perfectly fine.**

`- python version: `3.8.10 (default, Jun  4 2021, 15:09:15)  [GCC 7.5.0]`
- espnet version: `espnet 0.10.4a1`
- pytorch version: `pytorch 1.10.0`
(espnet) root@cfdbcb422965:/opt/espnet2/tools# cat << EOF
> - Git hash: \`$(git rev-parse HEAD)\`
>   - Commit date: \`$(git log -1 --format='%cd')\`
> EOF
- Git hash: `09044aa4e599687fb6e4e9becb76315e79c9d983`
  - Commit date: `Wed Nov 10 07:10:23 2021 +0000`
 
**Environments from `torch.utils.collect_env`:**
```
PyTorch version: 1.10.0
Is debug build: False
CUDA used to build PyTorch: 11.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.3 LTS (x86_64)
GCC version: (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Clang version: Could not collect
CMake version: version 3.16.3
Libc version: glibc-2.31

Python version: 3.8.10 (default, Jun  4 2021, 15:09:15)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-5.11.0-1020-aws-x86_64-with-glibc2.17
Is CUDA available: True
CUDA runtime version: 11.1.105
GPU models and configuration: GPU 0: NVIDIA Tesla V100-SXM2-16GB
Nvidia driver version: 465.19.01
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.0.5
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.20.3
[pip3] pytorch-ranger==0.1.1
[pip3] pytorch-wpe==0.0.1
[pip3] torch==1.10.0
[pip3] torch-complex==0.2.1
[pip3] torch-optimizer==0.3.0
[pip3] torchaudio==0.10.0
[conda] blas                      1.0                         mkl  
[conda] cudatoolkit               11.1.74              h6bb024c_0    nvidia
[conda] mkl                       2021.4.0           h06a4308_640  
[conda] mkl-service               2.4.0            py38h7f8727e_0  
[conda] mkl_fft                   1.3.1            py38hd3c417c_0  
[conda] mkl_random                1.2.2            py38h51133e4_0  
[conda] numpy                     1.20.3                   pypi_0    pypi
[conda] pytorch                   1.10.0          py3.8_cuda11.1_cudnn8.0.5_0    pytorch
[conda] pytorch-mutex             1.0                        cuda    pytorch
[conda] pytorch-ranger            0.1.1                    pypi_0    pypi
[conda] pytorch-wpe               0.0.1                    pypi_0    pypi
[conda] torch-complex             0.2.1                    pypi_0    pypi
[conda] torch-optimizer           0.3.0                    pypi_0    pypi
[conda] torchaudio                0.10.0               py38_cu111    pytorch
```

**Task information:**
 - Task: ASR
 - Recipe: custom
 - ESPnet2

**Comment by Fhrozen** [comment]
I can remember this behavior, and I think that it has nothing to do with `UserWarning` but I think that it is related to nltk. If I can remember, downloading some files from nltk for the first time on asr_stat_collects makes some of the other jobs break. 

If you see, this one ended with `Ended (code 0)`.
Can you check all of the `collect.logs` and confirm pls?

**Comment by arunbaby0** [comment]
yes, this looks like nltk error.
`[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Unzipping taggers/averaged_perceptron_tagger.zip.
Traceback (most recent call last):
  File "/miniconda/envs/espnet/lib/python3.8/site-packages/g2p_en/g2p.py", line 22, in <module>
    nltk.data.find('taggers/averaged_perceptron_tagger.zip')
  File "/miniconda/envs/espnet/lib/python3.8/site-packages/nltk/data.py", line 583, in find
    raise LookupError(resource_not_found)
LookupError: 
**********************************************************************
  Resource averaged_perceptron_tagger not found.
  Please use the NLTK Downloader to obtain the resource:

  >>> import nltk
  >>> nltk.download('averaged_perceptron_tagger')
  
  For more information see: https://www.nltk.org/data.html

  Attempted to load taggers/averaged_perceptron_tagger.zip

  Searched in:
    - '/root/nltk_data'
    - '/miniconda/envs/espnet/nltk_data'
    - '/miniconda/envs/espnet/share/nltk_data'
    - '/miniconda/envs/espnet/lib/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
**********************************************************************


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/miniconda/envs/espnet/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/miniconda/envs/espnet/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/opt/espnet2/espnet2/bin/asr_train.py", line 2, in <module>
    from espnet2.tasks.asr import ASRTask
  File "/opt/espnet2/espnet2/tasks/asr.py", line 61, in <module>
    from espnet2.text.phoneme_tokenizer import g2p_choices
  File "/opt/espnet2/espnet2/text/phoneme_tokenizer.py", line 9, in <module>
    import g2p_en
  File "/miniconda/envs/espnet/lib/python3.8/site-packages/g2p_en/__init__.py", line 1, in <module>
    from .g2p import G2p
  File "/miniconda/envs/espnet/lib/python3.8/site-packages/g2p_en/g2p.py", line 24, in <module>
    nltk.download('averaged_perceptron_tagger')
  File "/miniconda/envs/espnet/lib/python3.8/site-packages/nltk/downloader.py", line 776, in download
    for msg in self.incr_download(info_or_id, download_dir, force):
  File "/miniconda/envs/espnet/lib/python3.8/site-packages/nltk/downloader.py", line 641, in incr_download
    yield from self._download_package(info, download_dir, force)
  File "/miniconda/envs/espnet/lib/python3.8/site-packages/nltk/downloader.py", line 734, in _download_package
    for msg in _unzip_iter(filepath, zipdir, verbose=False):
  File "/miniconda/envs/espnet/lib/python3.8/site-packages/nltk/downloader.py", line 2249, in _unzip_iter
    zf.extractall(root)
  File "/miniconda/envs/espnet/lib/python3.8/zipfile.py", line 1647, in extractall
    self._extract_member(zipinfo, path, pwd)
  File "/miniconda/envs/espnet/lib/python3.8/zipfile.py", line 1697, in _extract_member
    os.mkdir(targetpath)
FileExistsError: [Errno 17] File exists: '/root/nltk_data/taggers/averaged_perceptron_tagger'
# Accounting: time=19 threads=1
# Ended (code 1) at Thu Nov 11 04:09:37 UTC 2021, elapsed time 19 seconds`

**Comment by arunbaby0** [comment]
this nltk crash can be observed for LM stats collection, ASR stats collection and ASR decode from a downloaded model. 
But only for the first time in docker.

**Comment by arunbaby0** [comment]
@Fhrozen How about pre-downloading all required packages in the dockerFile?

**Comment by Fhrozen** [comment]
If you setup the `NLTK_DATA` environmental variable to target one on your repository will be better.
This folder may change depending on the user.

**Comment by Pooookeman** [comment]
> this nltk crash can be observed for LM stats collection, ASR stats collection and ASR decode from a downloaded model. But only for the first time in docker.
May I know how did you solve this issue? Same nltk error occurs to me in Stage 6, even I delete the nltk_data in my path
