### ISSUE TITLE
Changing pitch and duration on a phoneme basis

### ISSUE THREAD

**Issue by imae-sound** [espnet/espnet#3775]
Is there a way to change the pitch, duration and maybe other parameters for each phoneme, so that I can fine tune the results of the speech synthesis? I have been looking at the code but I have not found a way to do so...

**Comment by kan-bayashi** [comment]
Could you clarify your motivation more clearer?
Currently we have an option to control the speed by multiplying the constant value for FastSpeech-based models.

**Comment by imae-sound** [comment]
We are working on TTS for Japanese and would like to modify the pitch accent for certain words. Additionally, we would also like to add custom stress to sentences by modifying the duration and loudness of certain phonemes.

**Comment by kan-bayashi** [comment]
So do you want to change these components in inference?

**Comment by kan-bayashi** [comment]
We did not provide such kind of options but you can modify e_outs and p_outs here
https://github.com/espnet/espnet/blob/eee2566f2395d676e3978376315a4cd116a4e335/espnet2/tts/fastspeech2/fastspeech2.py#L665
which are token averaged energy and pitch.

**Comment by imae-sound** [comment]
Thank you! I will have a look at it.
