### ISSUE TITLE
output from a beamformer

### ISSUE THREAD

**Issue by learnabitmore** [espnet/espnet#3776]
It says in the CHIME-5 paper that "Beamforming is performed by using four microphone signals attached to the reference array", I wonder what the input and output of the beamformer are? 
There are  6 Kinect devices each with 4 channels. Is the input to the beamformer a 6-array 4-channel audio, i.e. dimension is [6, 4, time] or a stack of all channels [24, time], and the output of the beamformer is a single channel audio (dimension is [time]) ?

**Comment by sw005320** [comment]
> There are 6 Kinect devices each with 4 channels

The reference array means that we used one Kinect device among 6 Kinect devices.
This reference array information is written in the original CHiME-5 annotations, and we used it.

Thus, the input audio file is [4, time], and the beamformed output is [1, time]

**Comment by learnabitmore** [comment]
Thank you!

In CHIME-6, it mentions that the alternative front-end applies BeamformIt to the reference array, but later sections indicate that SAD, Diarization and ASR all use U06 for simplicity. Does that mean the BeamformIt is applied to U06 instead of the reference array for Track 2 baseline while Track 1 baseline applies BeamformIt on the reference array?

**Comment by sw005320** [comment]
CHiME-6 is a different story.
They use all arrays.
