### ISSUE TITLE
Index error in Transducer beam search ALSD

### ISSUE THREAD

**Issue by maxwellzh** [espnet/espnet#3781]
**Describe the bug**
The index of `(t, u)` is wrong. Since indices of `u` and `i` are beginning with  0, the `t` should be `t = i - u`. In current impl, `t` is beginning with 1, and the encoder output at `t=0` is never used.
https://github.com/espnet/espnet/blob/3c30eab699d8c3a0c61331e3cac38050345527de/espnet/nets/beam_search_transducer.py#L467-L469

**Comment by b-flo** [comment]
Hi,

Seems right to me, thanks for catching that! Could you make a PR, please? If not, I will do it at the end of the week.

**Comment by maxwellzh** [comment]
@b-flo I have make the PR. Only one line changes. It should be easy to review.

**Comment by b-flo** [comment]
Fixed by #3794.
