### ISSUE TITLE
make: command: Command not found 

### ISSUE THREAD

**Issue by kan-bayashi** [espnet/espnet#3783]
**Describe the bug**

`$(shell command -v nvcc)` in Makefile causes `command: Command not found` error even if `command` is available as the shell built-in command.

https://github.com/espnet/espnet/blob/c6139d5f0dc79fc4676fd908bbce05486a6672e1/tools/Makefile#L14

Then, `CPU_ONLY = 0` is always used.

This is also caused in CI except for centos.
https://github.com/espnet/espnet/runs/4206382740?check_suite_focus=true#step:6:31

Maybe this is because in centos `which command` returns the path but the others return `shell built-in command`.

**Basic environments:**

```
- OS information: Linux 5.8.0-48-generic #54~20.04.1-Ubuntu SMP Sat Mar 20 13:40:25 UTC 2021 x86_64
```

**To Reproduce**

```bash
$ cd tools
$ ./setup_anaconda.sh venv espnet 3.8
$ make showenv
make: command: Command not found
Perform on CPU mode: CPU_ONLY=0
PYTHON=/home/t_hayashi/workspace6/espnet/tools/venv/envs/espnet/bin/python3
PYTHON_VERSION=Python 3.8.12
USE_CONDA=1
TH_VERSION=1.10.0
```

`command` itself in available in shell.
```
$ which command
command: shell built-in command
```

**Comment by kamo-naoyuki** [comment]
I see.

`command` is a builtin command for bash:  See [man command](https://linux.die.net/man/1/builtins),  but the shell of Makefile is POSIX-sh (/bin/sh) actually, so it can be not found.

CentOS7 has a shell script at `/usr/bin/command`, so this error doesn't happen on CentOS7.

`type` is also a builidin command for bash, so we should use `which` command for POSIX-sh compatible.
