### ISSUE TITLE
runtime error(need help)

### ISSUE THREAD

**Issue by 123srikanth** [espnet/espnet#3785]
## Describe issue
I am trying to train a TTS model for hindi language using espnet/egs/ljspeech/tts1/ model. I have prepared my own data for hindi dataset but when I run the script I'm getting the following error. I'm not sure what's wrong with my dataset. Can someone help me to sort out this issue.

compute-fbank-feats.py --fs 22050 --fmax 7600 --fmin 80 --n_fft 1024 --n_shift 256 --win_length --window hann --n
_mels 80 --write-num-frames=ark,t:exp/char_make_fbank/train/utt2num_frames.32 --compress=true --filetype mat --norm
alize 16 scp:exp/char_make_fbank/train/wav.32.scp ark,scp:/home/srikanth/espnet/egs/ljspeech/tts1/fbank/raw_fbank_c
har_train.32.ark,/home/srikanth/espnet/egs/ljspeech/tts1/fbank/raw_fbank_char_train.32.scp 
 Started at Mon Nov 15 08:29:46 UTC 2021

Traceback (most recent call last):
  File "/home/srikanth/espnet/tools/python_user_base/lib/python3.7/site-packages/kaldiio/matio.py", line 615, in re
ad_ascii_mat
    float(ma)
ValueError: could not convert string to float: 'ÿóDÄ\x00\x10¨f\x00\x00{\x06(I\x1b¤¨x\x8bñ`\x00r\x02×\x162¬Àì0QaÂ\t\
x14!Â4úK¬ØDUçÈ\x14\x16&\x00)wþpç÷3ÿ§õ(Áöµ*ýäÊ\x14\x00\x04\x010|\x1f.ó\x88R+:¹I8mCO»*\tÙ\x90\x87B`ÿóDÄ\x10\x10¨®<\x0
0ÃÆL¼<c\x89;Õ\x1cY '
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/srikanth/espnet/egs/ljspeech/tts1/../../../utils/compute-fbank-feats.py", line 134, in <module>
    main()
  File "/home/srikanth/espnet/egs/ljspeech/tts1/../../../utils/compute-fbank-feats.py", line 112, in main
    for utt_id, (rate, array) in reader:
  File "/home/srikanth/espnet/tools/python_user_base/lib/python3.7/site-packages/kaldiio/highlevel.py", line 136, i
n __iter__
    k, v = next(self.generator)
  File "/home/srikanth/espnet/tools/python_user_base/lib/python3.7/site-packages/kaldiio/matio.py", line 127, in lo
ad_scp_sequential
    mat = _load_mat(arkfd, offset, slices, endian=endian)
  File "/home/srikanth/espnet/tools/python_user_base/lib/python3.7/site-packages/kaldiio/matio.py", line 331, in _l
oad_mat
    array = read_kaldi(fd, endian)
  File "/home/srikanth/espnet/tools/python_user_base/lib/python3.7/site-packages/kaldiio/matio.py", line 441, in re
ad_kaldi
    array = read_ascii_mat(fd)
  File "/home/srikanth/espnet/tools/python_user_base/lib/python3.7/site-packages/kaldiio/matio.py", line 617, in re
ad_ascii_mat
    raise RuntimeError(ma + "is not a digit\nFile format is wrong?")
RuntimeError: ÿóDÄ^@^P¨f^@^@{^F(IESC¤¨x<U+008B>ñ`^@r^B×^V2¬Àì0QaÂ       ^T!Â4úK¬ØDUçÈ^T^V&^@)wþpç÷3ÿ§õ(Áöµ*ýäÊ^T^@
^D^A0|^_.ó<U+0088>R+:¹I8mCO»* Ù<U+0090><U+0087>B`ÿóDÄ^P^P¨®<^@ÃÆL¼<c<U+0089>;Õ^\Y is not a digit
File format is wrong?
 Accounting: time=1 threads=1
 Ended (code 1) at Mon Nov 15 08:29:47 UTC 2021, elapsed time 1 seconds

**Comment by kan-bayashi** [comment]
Could you attach the head of your `wav.scp`?
Maybe workaround is using acsii for filename and utt_ids.

**Comment by 123srikanth** [comment]
/home/srikanth/Documents/train_data/data_prep/char_train/wav.scp

**Comment by kan-bayashi** [comment]
I mean the contents of `wav.scp`.

**Comment by kan-bayashi** [comment]
Could you show me lines of your hindi corpus?

**Comment by 123srikanth** [comment]
you mean these 
LJ001-0001 एयरटेल ने रिलायंस जियो को टक्कर देने के इरादे से अपने प्रीपेड ग्राहकों
LJ001-0002 और उसे तीन स्टॉफ नर्सों की देखरेख में रखा गया था बावजूद इसके वह आवारा कुत्तों का शिकार बन गई
LJ001-0003 बैंक खाते खोलकर कई लोगों ने अपने काले धन को सफेद करने की कोशिश करने
LJ001-0004 इसके बाद अमित मिश्रा ने जैक
LJ001-0005 की मात्रा
LJ001-0006 अपने प्लान के बारे में बताते हुए बीएसएनएल के चेयरमैन अनुपम श्रीवास्तव ने कहा हम ऐसे प्लान पर काम कर रहे हैं जो मोबाइल
LJ001-0007 निकायों में कुल आठ सौ चवालीस वार्ड हैं जहां सत्तानवे वार्डों में शत प्रतिशत घर घर
LJ001-0008 बनाने की विधि में एकरूपता न
LJ001-0009 विशेषज्ञों का कहना है कि वेतनवृद्धि में भी कमजोर रुख
LJ001-0010 इस लिये सभी जिलों के अध्यक्षों को आवश्यक दिशा निर्देश दिये जा रहे हैं उन्होंने कहा कि रैली में पांच लाख

**Comment by kan-bayashi** [comment]
Ah, did you save your hindi audio as `downloads/LJSpeech-1.1/wavs/LJXXX-XXXX.wav`?

**Comment by 123srikanth** [comment]
yes

**Comment by kan-bayashi** [comment]
I see. Then, maybe the problem is your audio file format.
You can check your file format via `soxi`.
This is an example of LJspeech audio.
```
$ soxi downloads/LJSpeech-1.1/wavs/LJ001-0001.wav

Input File     : 'downloads/LJSpeech-1.1/wavs/LJ001-0001.wav'
Channels       : 1
Sample Rate    : 22050
Precision      : 16-bit
Duration       : 00:00:09.66 = 212893 samples ~ 724.126 CDDA sectors
File Size      : 426k
Bit Rate       : 353k
Sample Encoding: 16-bit Signed Integer PCM
```
If your audio is not `16-bit Signed Integer PCM`, it is better to convert.

**Comment by 123srikanth** [comment]
can you please suggest an application to convert them I'm using Qwinff but it has only sample rate and bitrate parameters to convert

**Comment by kan-bayashi** [comment]
Please use sox 
```
# e.g.
$ sox downloads/LJSpeech-1.1/wavs/LJ001-0001.wav -t wav -r 16000 -b 16 test.wav
```

**Comment by 123srikanth** [comment]
sox downloads/LJSpeech-1.1/wavs/LJ001-0001.wav -t wav -r 16000 -b 16 test.wav 
when I run the above command I'm facing the following error

sox FAIL formats: can't open input file `downloads/LJSpeech-1.1/wavs/LJ001-0001.wav': WAVE: RIFF header not found

**Comment by kan-bayashi** [comment]
The option depends on your file format.
```
# another example
$ sox -t wav downloads/LJSpeech-1.1/wavs/LJ001-0001.wav -t wav -r 16000 -b 16 test.wav
```

**Comment by 123srikanth** [comment]
even this option throws the same error

srikanth@instance-1:~/espnet/egs/ljspeech/tts1$ sox -t wav downloads/LJSpeech-1.1/wavs/LJ001-0001.wav -t wav -r 16000 -b 16 test.wav
sox FAIL formats: can't open input file `downloads/LJSpeech-1.1/wavs/LJ001-0001.wav': WAVE: RIFF header not found

**Comment by kan-bayashi** [comment]
Since I did not know your audio detail, I need to investigate by yourself.
Maybe if you provide the results of soxi command, I give you some insights.

**Comment by 123srikanth** [comment]
the output remains same with soxi command as well

srikanth@instance-1:~/espnet/egs/ljspeech/tts1$ soxi downloads/LJSpeech-1.1/wavs/LJ001-0001.wav 
soxi FAIL formats: can't open input file `downloads/LJSpeech-1.1/wavs/LJ001-0001.wav': WAVE: RIFF header not found

**Comment by kan-bayashi** [comment]
Then, I have no idea to determine your audio file format.
Please check your software used for the conversion.
