### ISSUE TITLE
which data to use (need help)

### ISSUE THREAD

**Issue by 123srikanth** [espnet/espnet#3799]
I have prepared the data inside the data folder with hindi dataset for espnet/egs/ljspeech/tts1 model and I have run the model it has successfully ran 3 stages and to proceed with 4th stage i.e training stage I had a doubt. Inside the dump folder for data2json file it is creating tokens in english even though I have prepared the data in hindi so later I have prepared the data in english and ran the model again which made no difference, again the data2json folder has tokens in english. So can someone please suggest me which data folder to use hindi or english to train the mode. I have attached both zip folders for reference.

[data_en.zip](https://github.com/espnet/espnet/files/7552980/data_en.zip)
[data_hi.zip](https://github.com/espnet/espnet/files/7552986/data_hi.zip)
l.

**Comment by 123srikanth** [comment]
@kan-bayashi  can you please clear this doubt for me.

**Comment by kan-bayashi** [comment]
It seems fine, I am not sure what is happened.

1. Prepare the `data` directory for your dataset
2. Run the recipe from stage 2. (Please check you did not overwrite data dir by running from stage 1)
