### ISSUE TITLE
Espnet1 TTS with EU languages

### ISSUE THREAD

**Issue by u-hubar** [espnet/espnet#3802]
Hello, I have a question related to pretrained TTS models for fr-FR, es-ES and it-IT languages. There are only demos for English, Japanese and Mandarin languages and usage of G2P isn't clear enough. Where can I find G2P modules for other languages? Otherwise, where can I found instruction how to use custom G2P modules to produce input for TTS models?

**Comment by kan-bayashi** [comment]
Do you need to stick to ESPnet1?
In the case of ESPnet2, you can find
https://github.com/espnet/espnet/blob/master/egs2/TEMPLATE/tts1/README.md#supported-text-frontend

**Comment by u-hubar** [comment]
> Do you need to stick to ESPnet1? In the case of ESPnet2, you can find https://github.com/espnet/espnet/blob/master/egs2/TEMPLATE/tts1/README.md#supported-text-frontend

ESPnet2 is also OK, but I haven't found any pretrained models for languages I need. Are there any pretrained TTS models for es-ES, fr-FR and it-IT for ESPnet2?

**Comment by u-hubar** [comment]
Or maybe I can use this text frontends with ESPnet1 TTS?

**Comment by kan-bayashi** [comment]
The pretrained models in EPSnet1 for these langs, we do not use G2P, just using char.
So if you want to just use the pretrained model, you do not need.

**Comment by u-hubar** [comment]
> For the pretrained models in EPSnet1 for these langs, we do not use G2P, just using char. So if you want to just use the pretrained model, you do not need.

Oh, I only have found this demo with the ESPnet1 usage: https://colab.research.google.com/github/espnet/notebook/blob/master/tts_realtime_demo.ipynb
And G2P is used here for audio synthesis. Where can I find some examples of usage with pretrained models without G2P?

**Comment by kan-bayashi** [comment]
You can skip cleaner part and follow trans_type=char processing.

**Comment by u-hubar** [comment]
> You can skip cleaner part and follow trans_type=char processing in the notebook.

Thanks a lot! Appreciate your help

**Comment by u-hubar** [comment]
Hello, I have one more question related to Espnet1 TTS.

Where can I find pretrained vocoders for this TTS models: https://drive.google.com/drive/folders/1AzB7xtNY1LJM9aMQMOWCvLnq07KbH7gJ ?

I'm interested in de-DE, es-ES, fr-FR and it-IT languages, but I've founded only de-DE vocoder: https://drive.google.com/drive/folders/1rwzpIwb65xbW5fFPsqPWdforsk4U-vDg

**Comment by kan-bayashi** [comment]
Unfortunately, I have not prepared the vocoders for these models, I think.

> I'm interested in de-DE, es-ES, fr-FR and it-IT languages, but I've founded only de-DE vocoder:

This german model is trained on different dataset, and the sampling rate is different form M-AILABS (The recording quality is much better). So you cannot use it.

**Comment by u-hubar** [comment]
> Unfortunately, I have not prepared the vocoders for these models, I think (Actually I did not remember...).
> 
> 
> 
> > I'm interested in de-DE, es-ES, fr-FR and it-IT languages, but I've founded only de-DE vocoder:
> 
> 
> 
> This german model is trained on different dataset, and the sampling rate is different form M-AILABS (The recording quality is much better). So you cannot use it.

Are there possibilities to train vocoders on my own or any other solution?

**Comment by kan-bayashi** [comment]
> Are there possibilities to train vocoders on my own or any other solution?

Since we have no good 16khz pretrained vocoder, it is better to train by yourself.
https://github.com/kan-bayashi/ParallelWaveGAN/tree/master/egs#how-to-make-the-recipe-for-your-own-dateset
