### ISSUE TITLE
An error occurred in the ASR task using the streaming conformer config on ESPnet2

### ISSUE THREAD

**Issue by lin-nerd** [espnet/espnet#3803]
- python=3.8.5
- torch=1.10.0+cu102
- torch cuda=10.2
- espnet=0.10.5a1

I want to use streaming conformer config for my dataset of the ASR task, but this error occurs after the first epoch training.
The log is:
[user] 2021-11-17 21:07:07,236 (trainer:668) INFO: 1epoch:train:26767-28253batch: iter_time=7.281e-05, forward_time=0.133, loss=150.549, loss_att=116.794, loss_ctc=229.310, acc=0.325, backward_time=0.169, optim_step_time=0.031, optim0_lr0=4.585e-04, train_time=0.425
[user] 2021-11-17 21:17:35,754 (trainer:668) INFO: 1epoch:train:28254-29740batch: iter_time=2.378e-04, forward_time=0.133, loss=142.284, loss_att=110.287, loss_ctc=216.944, acc=0.327, backward_time=0.166, optim_step_time=0.031, optim0_lr0=4.833e-04, train_time=0.422
Traceback (most recent call last):
  File "/home/user/espnet/tools/anaconda/envs/espnet/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/user/espnet/tools/anaconda/envs/espnet/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/user/espnet/espnet2/bin/asr_train.py", line 23, in <module>
    main()
  File "/home/user/espnet/espnet2/bin/asr_train.py", line 19, in main
    ASRTask.main(cmd=cmd)
  File "/home/user/espnet/espnet2/tasks/abs_task.py", line 1013, in main
    cls.main_worker(args)
  File "/home/user/espnet/espnet2/tasks/abs_task.py", line 1305, in main_worker
    cls.trainer.run(
  File "/home/user/espnet/espnet2/train/trainer.py", line 293, in run
    cls.validate_one_epoch(
  File "/home/user/espnet/tools/anaconda/envs/espnet/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "/home/user/espnet/espnet2/train/trainer.py", line 711, in validate_one_epoch
    retval = model(**batch)
  File "/home/user/espnet/tools/anaconda/envs/espnet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/user/espnet/espnet2/asr/espnet_model.py", line 142, in forward
    encoder_out, encoder_out_lens = self.encode(speech, speech_lengths)
  File "/home/user/espnet/espnet2/asr/espnet_model.py", line 244, in encode
    assert encoder_out.size(1) <= encoder_out_lens.max(), (
AttributeError: 'NoneType' object has no attribute 'max'
[user] 2021-11-17 21:17:44,911 (internal:139) INFO: Internal process exited.

But I can use a smaller data set for training, I would like to ask how can I solve this problem.
The log is:
[user] 2021-11-18 09:07:55,870 (trainer:668) INFO: 1epoch:train:257-272batch: iter_time=7.188e-05, forward_time=0.144, loss=188.445, loss_att=146.988, loss_ctc=285.178, acc=0.257, backward_time=0.172, optim_step_time=0.032, optim0_lr0=4.425e-06, train_time=0.449
[user] 2021-11-18 09:08:02,991 (trainer:668) INFO: 1epoch:train:273-288batch: iter_time=6.664e-05, forward_time=0.142, loss=237.047, loss_att=180.976, loss_ctc=367.880, acc=0.277, backward_time=0.170, optim_step_time=0.032, optim0_lr0=4.692e-06, train_time=0.445
[user] 2021-11-18 09:08:10,122 (trainer:668) INFO: 1epoch:train:289-304batch: iter_time=7.703e-05, forward_time=0.140, loss=278.296, loss_att=215.102, loss_ctc=425.748, acc=0.278, backward_time=0.185, optim_step_time=0.032, optim0_lr0=4.958e-06, train_time=0.445
[user] 2021-11-18 09:08:17,111 (trainer:668) INFO: 1epoch:train:305-320batch: iter_time=7.410e-05, forward_time=0.139, loss=205.749, loss_att=159.653, loss_ctc=313.307, acc=0.271, backward_time=0.170, optim_step_time=0.033, optim0_lr0=5.225e-06, train_time=0.437
[user] 2021-11-18 09:08:24,423 (trainer:668) INFO: 1epoch:train:321-336batch: iter_time=7.448e-05, forward_time=0.146, loss=235.820, loss_att=181.995, loss_ctc=361.411, acc=0.310, backward_time=0.178, optim_step_time=0.032, optim0_lr0=5.492e-06, train_time=0.457
[user] 2021-11-18 09:08:27,867 (trainer:328) INFO: 1epoch results: [train] iter_time=2.738e-04, forward_time=0.141, loss=319.074, loss_att=237.090, loss_ctc=510.369, acc=0.192, backward_time=0.172, optim_step_time=0.032, optim0_lr0=2.842e-06, train_time=0.442, time=2 minutes and 29.56 seconds, total_count=338, gpu_max_cached_mem_GB=9.566, [valid] loss=225.508, loss_att=171.193, loss_ctc=352.243, acc=0.288, cer=0.720, wer=1.284, cer_ctc=1.000, time=2.41 seconds, total_count=12, gpu_max_cached_mem_GB=9.566
[user] 2021-11-18 09:08:28,769 (trainer:375) INFO: The best model has been updated: valid.acc
[user] 2021-11-18 09:08:28,770 (trainer:262) INFO: 2/50epoch started. Estimated time to finish: 2 hours, 4 minutes and 55.87 seconds
[user] 2021-11-18 09:08:36,278 (trainer:668) INFO: 2epoch:train:1-16batch: iter_time=0.004, forward_time=0.148, loss=235.967, loss_att=180.346, loss_ctc=365.749, acc=0.316, backward_time=0.184, optim_step_time=0.033, optim0_lr0=5.792e-06, train_time=0.469
[user] 2021-11-18 09:08:43,533 (trainer:668) INFO: 2epoch:train:17-32batch: iter_time=7.638e-05, forward_time=0.143, loss=189.732, loss_att=145.995, loss_ctc=291.784, acc=0.321, backward_time=0.173, optim_step_time=0.034, optim0_lr0=6.058e-06, train_time=0.453
[user] 2021-11-18 09:08:50,837 (trainer:668) INFO: 2epoch:train:33-48batch: iter_time=7.702e-05, forward_time=0.146, loss=182.177, loss_att=138.910, loss_ctc=283.135, acc=0.321, backward_time=0.179, optim_step_time=0.033, optim0_lr0=6.325e-06, train_time=0.456

**Comment by sw005320** [comment]
> I want to use streaming conformer config for my dataset of the ASR task

Thanks for testing our new functions.
Could you tell me more details about the recipe and config?

**Comment by lin-nerd** [comment]
@sw005320 Thanks for your reply.
I use the recipe of Aishell and use my own Mandarin corpus.

The following is my config file:

# network architecture
# encoder related
encoder: contextual_block_conformer    # contextual_block_conformer is the core of streaming conformer
encoder_conf:
    output_size: 256    # dimension of attention
    attention_heads: 4
    linear_units: 2048  # the number of units of position-wise feed forward
    num_blocks: 12      # the number of encoder blocks
    dropout_rate: 0.1
    positional_dropout_rate: 0.1
    attention_dropout_rate: 0.0
    input_layer: conv2d # encoder architecture type
    normalize_before: true
    activation_type: swish
    macaron_style: true
    use_cnn_module: true
    cnn_module_kernel: 15
    block_size: 40      # streaming configuration
    hop_size: 16        # streaming configuration
    look_ahead: 16      # streaming configuration
    init_average: true  # streaming configuration
    ctx_pos_enc: true   # streaming configuration

# decoder related
decoder: transformer
decoder_conf:
    attention_heads: 4
    linear_units: 2048
    num_blocks: 6
    dropout_rate: 0.1
    positional_dropout_rate: 0.1
    self_attention_dropout_rate: 0.0
    src_attention_dropout_rate: 0.0

# hybrid CTC/attention
model_conf:
    ctc_weight: 0.3
    lsm_weight: 0.1     # label smoothing option
    length_normalized_loss: false

# minibatch related
batch_type: folded
batch_size: 32 #128
#valid_batch_size: 1
# optimization related
accum_grad: 1
grad_clip: 5
patience: 3
max_epoch: 50
val_scheduler_criterion:
    - valid
    - acc
best_model_criterion:
-   - valid
    - acc
    - max
early_stopping_criterion:
    - valid
    - cer_ctc
    - min
keep_nbest_models: 10

# NoamLR is deprecated. Use WarmupLR.
# The following is equivalent setting for NoamLR:
#
#    optim: adam
#    optim_conf:
#        lr: 10.
#    scheduler: noamlr
#    scheduler_conf:
#        model_size: 256
#        warmup_steps: 25000
#
optim: adam
optim_conf:
    lr: 0.0005
scheduler: warmuplr     # pytorch v1.1.0+ required
scheduler_conf:
    warmup_steps: 30000
num_att_plot: 0

specaug: specaug
specaug_conf:
    apply_time_warp: true
    time_warp_window: 5
    time_warp_mode: bicubic
    apply_freq_mask: true
    freq_mask_width_range:
    - 0
    - 30
    num_freq_mask: 2
    apply_time_mask: true
    time_mask_width_range:
    - 0
    - 40
    num_time_mask: 2

**Comment by sw005320** [comment]
Sorry again.
Does the aishell recipe have some issues or does your own data has some issues?
@D-Keqi, have you faced this issue?

**Comment by D-Keqi** [comment]
> Sorry again. Does the aishell recipe have some issues or does your own data has some issues? @D-Keqi, have you faced this issue?

No, I have not faced this issue. I think maybe you can check the data preparation stage of your own corpus. The encoder_out_lens shouldn't be None during the training stage.

**Comment by lin-nerd** [comment]
@sw005320 @D-Keqi I used the same Mandarin corpus to work on the transformer streaming config.
At the same time, I also ran through stage 2 to stage 4 and stage 9 before training, but still faced the same issue.

**Comment by D-Keqi** [comment]
> @sw005320 @D-Keqi Thanks for your reply. I used the same recipe and Mandarin corpus to work on the transformer streaming config, but doesn't face this issue. At the same time, I also ran through stage 2 to stage 4 and stage 9 before training, but still faced the same issue. But I observe my log file has a warning when I start training as follows:
> 
> ESPnetDataset( speech: {"path": "dump/raw/dev/wav.scp", "type": "sound"} text: {"path": "dump/raw/dev/text", "type": "text"} preprocess: <espnet2.train.preprocessor.CommonPreprocessor object at 0x7f09744d2460>) [user] 2021-11-24 09:22:08,484 (abs_task:1516) INFO: [valid] Batch sampler: FoldedBatchSampler(N-batch=455, batch_size=32, shape_files=['exp/asr_stats_raw_zh_char_sp_streaming_conformer_6938tokens_Mandarin_max_47/valid/speech_shape', 'exp/asr_stats_raw_zh_char_sp_streaming_conformer_6938tokens_Mandarin_max_47/valid/text_shape.char'], sort_in_batch=descending, sort_batch=descending) [user] 2021-11-24 09:22:08,484 (abs_task:1517) INFO: [valid] mini-batch sizes summary: N-batch=455, mean=4.9, min=1, max=32 [user] 2021-11-24 09:22:08,844 (trainer:274) INFO: 1/50epoch started /home/user/espnet/espnet2/layers/stft.py:166: UserWarning: **floordiv** is deprecated, and its behavior will change in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values. To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor'). olens = (ilens - self.win_length) // self.hop_length + 1
> 
> I just found out that there is a blank in front of --resume in stag 10, I will try to train once, if it is because of this problem, I will let you know. Thank you for your patience.

OK, thanks for your response.

**Comment by lin-nerd** [comment]
@D-Keqi Sorry again.
I ran again stage 2 to stage 4 and stage 9 before training, but still faced the same issue, and the blank of --resume seems to have nothing to do with this issue.

The log file as follow:
[user] 2021-11-24 12:46:01,219 (trainer:668) INFO: 1epoch:train:26767-28253batch: iter_time=1.183e-04, forward_time=0.134, loss=114.915, loss_att=123.177, loss_ctc=95.638, acc=0.348, backward_time=0.168, optim_step_time=0.031, optim0_lr0=4.585e-04, train_time=0.423
[user] 2021-11-24 12:56:27,561 (trainer:668) INFO: 1epoch:train:28254-29740batch: iter_time=6.829e-05, forward_time=0.133, loss=97.846, loss_att=103.810, loss_ctc=83.930, acc=0.421, backward_time=0.165, optim_step_time=0.031, optim0_lr0=4.833e-04, train_time=0.421
Traceback (most recent call last):
Traceback (most recent call last):
  File "/home/user/espnet/tools/anaconda/envs/espnet/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/user/espnet/tools/anaconda/envs/espnet/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/user/espnet/espnet2/bin/asr_train.py", line 23, in <module>
    main()
  File "/home/user/espnet/espnet2/bin/asr_train.py", line 19, in main
    ASRTask.main(cmd=cmd)
  File "/home/user/espnet/espnet2/tasks/abs_task.py", line 1013, in main
    cls.main_worker(args)
  File "/home/user/espnet/espnet2/tasks/abs_task.py", line 1305, in main_worker
    cls.trainer.run(
  File "/home/user/espnet/espnet2/train/trainer.py", line 293, in run
    cls.validate_one_epoch(
  File "/home/user/espnet/tools/anaconda/envs/espnet/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "/home/user/espnet/espnet2/train/trainer.py", line 711, in validate_one_epoch
    retval = model(**batch)
  File "/home/user/espnet/tools/anaconda/envs/espnet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/user/espnet/espnet2/asr/espnet_model.py", line 142, in forward
    encoder_out, encoder_out_lens = self.encode(speech, speech_lengths)
  File "/home/user/espnet/espnet2/asr/espnet_model.py", line 244, in encode
    assert encoder_out.size(1) <= encoder_out_lens.max(), (
AttributeError: 'NoneType' object has no attribute 'max'

And the Warning is still exist:
[user] 2021-11-24 09:22:08,844 (trainer:274) INFO: 1/50epoch started
/home/user/espnet/espnet2/layers/stft.py:166: UserWarning: __floordiv__ is deprecated, and its behavior will change in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values. To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor').
olens = (ilens - self.win_length) // self.hop_length + 1

**Comment by D-Keqi** [comment]
> @D-Keqi Sorry, but I still faced the same issue. I ran again stage 2 to stage 4 and stage 9 before training, but still faced the same issue, and the blank of --resume seems to have nothing to do with this issue.
> 
> The log file as follow: [user] 2021-11-24 12:46:01,219 (trainer:668) INFO: 1epoch🚋26767-28253batch: iter_time=1.183e-04, forward_time=0.134, loss=114.915, loss_att=123.177, loss_ctc=95.638, acc=0.348, backward_time=0.168, optim_step_time=0.031, optim0_lr0=4.585e-04, train_time=0.423 [user] 2021-11-24 12:56:27,561 (trainer:668) INFO: 1epoch🚋28254-29740batch: iter_time=6.829e-05, forward_time=0.133, loss=97.846, loss_att=103.810, loss_ctc=83.930, acc=0.421, backward_time=0.165, optim_step_time=0.031, optim0_lr0=4.833e-04, train_time=0.421 Traceback (most recent call last): Traceback (most recent call last): File "/home/user/espnet/tools/anaconda/envs/espnet/lib/python3.8/runpy.py", line 194, in _run_module_as_main return _run_code(code, main_globals, None, File "/home/user/espnet/tools/anaconda/envs/espnet/lib/python3.8/runpy.py", line 87, in _run_code exec(code, run_globals) File "/home/user/espnet/espnet2/bin/asr_train.py", line 23, in main() File "/home/user/espnet/espnet2/bin/asr_train.py", line 19, in main ASRTask.main(cmd=cmd) File "/home/user/espnet/espnet2/tasks/abs_task.py", line 1013, in main cls.main_worker(args) File "/home/user/espnet/espnet2/tasks/abs_task.py", line 1305, in main_worker cls.trainer.run( File "/home/user/espnet/espnet2/train/trainer.py", line 293, in run cls.validate_one_epoch( File "/home/user/espnet/tools/anaconda/envs/espnet/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context return func(*args, **kwargs) File "/home/user/espnet/espnet2/train/trainer.py", line 711, in validate_one_epoch retval = model(**batch) File "/home/user/espnet/tools/anaconda/envs/espnet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl return forward_call(*input, **kwargs) File "/home/user/espnet/espnet2/asr/espnet_model.py", line 142, in forward encoder_out, encoder_out_lens = self.encode(speech, speech_lengths) File "/home/user/espnet/espnet2/asr/espnet_model.py", line 244, in encode assert encoder_out.size(1) <= encoder_out_lens.max(), ( AttributeError: 'NoneType' object has no attribute 'max'
> 
> And the Warning is still exist: [user] 2021-11-24 09:22:08,844 (trainer:274) INFO: 1/50epoch started /home/user/espnet/espnet2/layers/stft.py:166: UserWarning: **floordiv** is deprecated, and its behavior will change in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values. To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor'). olens = (ilens - self.win_length) // self.hop_length + 1

Do you mean it is ok with the streaming Transformer but you come into some issues with the streaming Conformer? Have you tested it with the AISHELL-1 corpus?

**Comment by lin-nerd** [comment]
@D-Keqi 
I tried to use streaming Transformer config on Mandarin corpus and found that I also encountered this issue.
But I can be training with my corpus in streaming Transformer config before git pull to the current version.

**Comment by D-Keqi** [comment]
> @D-Keqi First, thank you for your patient reply. And I tried to use streaming Transformer config on my Mandarin corpus and found that I also encountered this issue.
> 
> But I can train with my corpus in streaming Transformer config before git pull to the current version. It seems that there was a problem when I was doing the pull update version. Is there any difference between this update? Is there any way to solve this issue?
> 
> The version of ESPnet I used previously is 0.10.0.

Can you check if you are using forward_train instead of forward_infer during training? https://github.com/espnet/espnet/blob/master/espnet2/asr/encoder/contextual_block_conformer_encoder.py#L222 If you use forward_infer, the encoder_out_lens will be None. But, normally, the forward_train should be employed during training.

**Comment by lin-nerd** [comment]
@D-Keqi 
I just confirmed that the forward part in contextual_block_transformer_encoder.py and contextyal_block_conformer_encoder.py is as follows:

    def forward(
        self,
        xs_pad: torch.Tensor,
        ilens: torch.Tensor,
        prev_states: torch.Tensor = None,
        is_final=True,
    ) -> Tuple[torch.Tensor, torch.Tensor, Optional[torch.Tensor]]:
        """Embed positions in tensor.

        Args:
            xs_pad: input tensor (B, L, D)
            ilens: input length (B)
            prev_states: Not to be used now.
        Returns:
            position embedded tensor and mask
        """
        if self.training or xs_pad.size(0) > 1:
            return self.forward_train(xs_pad, ilens, prev_states)
        else:
            return self.forward_infer(xs_pad, ilens, prev_states, is_final)

**Comment by lin-nerd** [comment]
@D-Keqi 
Sorry to ask again.
I re-built an ESPnet and used AISHELL corpus and didn't encounter this issue, but I also used my own Mandarin corpus to run train_asr_streaming_transformer.yaml and didn't encounter this problem, but I tried to use train_asr_streaming_conformer.yaml and still encountered the same issue.

**Comment by pkyoung** [comment]
the same error here with espnet.v.0.10.4

**Comment by D-Keqi** [comment]
> the same error here with espnet.v.0.10.4. not conformer setup but streaming_transformer.
> 
> I guess it occurred at the end of an epoch, and related to the batchsize. I will try some research and let you know.

Thanks for your response! It seems that using valid_batch_size to distinguish between forward_infer and forward_train is not stable. I habe made a PR to fix this issue.

**Comment by pkyoung** [comment]
@D-Keqi  I am afraid your PR patched to v.0.10.4 seems to cause another error as follows:
```
 File "/path/to/espnet.v.0.10.4/espnet/nets/pytorch_backend/transformer/contextual_block_encoder_layer.py", line 245, in forward_infer
    x[:, 0, 0, :] = past_ctx[:, layer_idx, :]
RuntimeError: The expanded size of the tensor (1) must match the existing size (42) at non-singleton dimension 0.  Target sizes: [1, 256].  Tensor sizes: [42, 256]
```

**Comment by D-Keqi** [comment]
> @D-Keqi I am afraid your PR patched to v.0.10.4 seems to cause another error as follows:
> 
> ```
>  File "/path/to/espnet.v.0.10.4/espnet/nets/pytorch_backend/transformer/contextual_block_encoder_layer.py", line 245, in forward_infer
>     x[:, 0, 0, :] = past_ctx[:, layer_idx, :]
> RuntimeError: The expanded size of the tensor (1) must match the existing size (42) at non-singleton dimension 0.  Target sizes: [1, 256].  Tensor sizes: [42, 256]
> ```

Could you tell me more details? Do you come into this issue during training or decoding?

**Comment by D-Keqi** [comment]
> @D-Keqi I am afraid your PR patched to v.0.10.4 seems to cause another error as follows:
> 
> ```
>  File "/path/to/espnet.v.0.10.4/espnet/nets/pytorch_backend/transformer/contextual_block_encoder_layer.py", line 245, in forward_infer
>     x[:, 0, 0, :] = past_ctx[:, layer_idx, :]
> RuntimeError: The expanded size of the tensor (1) must match the existing size (42) at non-singleton dimension 0.  Target sizes: [1, 256].  Tensor sizes: [42, 256]
> ```

Hi! Thanks for your response, I found the issue. And I have modified my PR accordingly. Please let me know if it works for you.

**Comment by pkyoung** [comment]
@D-Keqi I've confirmed your modified PR (patched on v.0.10.4) fixed the problem. Thank you.

**Comment by D-Keqi** [comment]
> @D-Keqi I've confirmed your modified PR (patched on v.0.10.4) fixed the problem. Thank you.

Thanks!

**Comment by srikanthk20** [comment]
@D-Keqi ... i have the same issue. The Streaming Transformer was training well and moved to Streaming Conformer and have the similar issue. I am only running the training stage and the data prep is common to both the algos. Updated the repo to the latest and still see the same issue.

**Comment by D-Keqi** [comment]
> 

Hi! I have made a PR to fix this issue, but it has not been merged yet. Here is my PR https://github.com/espnet/espnet/pull/3880, I think it will help you solve this issue.

**Comment by D-Keqi** [comment]
> @D-Keqi ... i have the same issue. The Streaming Transformer was training well and moved to Streaming Conformer and have the similar issue. I am only running the training stage and the data prep is common to both the algos. Updated the repo to the latest and still see the same issue.
> 
> File "/home/ec2-user/SageMaker/espnet_env/envs/espnet_srikk_env/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl result = self.forward(*input, **kwargs) File "/home/ec2-user/SageMaker/espnet_env/envs/espnet_srikk_env/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 705, in forward output = self.module(*inputs[0], **kwargs[0]) File "/home/ec2-user/SageMaker/espnet_env/envs/espnet_srikk_env/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl result = self.forward(*input, **kwargs) File "/home/ec2-user/SageMaker/srikanth/espnet/espnet2/asr/espnet_model.py", line 142, in forward encoder_out, encoder_out_lens = self.encode(speech, speech_lengths) File "/home/ec2-user/SageMaker/srikanth/espnet/espnet2/asr/espnet_model.py", line 244, in encode assert encoder_out.size(1) <= encoder_out_lens.max(), ( AttributeError: 'NoneType' object has no attribute 'max' Traceback (most recent call last): File "/home/ec2-user/SageMaker/espnet_env/envs/espnet_srikk_env/lib/python3.8/runpy.py", line 194, in _run_module_as_main return _run_code(code, main_globals, None,

Hi! I have made a PR to fix this issue, but it has not been merged yet. Here is my PR #3880, I think it will help you solve this issue.

**Comment by srikanthk20** [comment]
> > @D-Keqi ... i have the same issue. The Streaming Transformer was training well and moved to Streaming Conformer and have the similar issue. I am only running the training stage and the data prep is common to both the algos. Updated the repo to the latest and still see the same issue.
> > File "/home/ec2-user/SageMaker/espnet_env/envs/espnet_srikk_env/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl result = self.forward(*input, **kwargs) File "/home/ec2-user/SageMaker/espnet_env/envs/espnet_srikk_env/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 705, in forward output = self.module(*inputs[0], **kwargs[0]) File "/home/ec2-user/SageMaker/espnet_env/envs/espnet_srikk_env/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl result = self.forward(*input, **kwargs) File "/home/ec2-user/SageMaker/srikanth/espnet/espnet2/asr/espnet_model.py", line 142, in forward encoder_out, encoder_out_lens = self.encode(speech, speech_lengths) File "/home/ec2-user/SageMaker/srikanth/espnet/espnet2/asr/espnet_model.py", line 244, in encode assert encoder_out.size(1) <= encoder_out_lens.max(), ( AttributeError: 'NoneType' object has no attribute 'max' Traceback (most recent call last): File "/home/ec2-user/SageMaker/espnet_env/envs/espnet_srikk_env/lib/python3.8/runpy.py", line 194, in _run_module_as_main return _run_code(code, main_globals, None,
> 
> Hi! I have made a PR to fix this issue, but it has not been merged yet. Here is my PR #3880, I think it will help you solve this issue.

-- Thanks @D-Keqi ... its resolved

**Comment by lin-nerd** [comment]
Thanks @D-Keqi !! This issue is resolved.

**Comment by D-Keqi** [comment]
> Thanks @D-Keqi !! This issue is resolved.

That's cool!
