### ISSUE TITLE
Reference Example Result WER/CER for Hubert SSL librilight_limited_10hr

### ISSUE THREAD

**Issue by AdolfVonKleist** [espnet/espnet#3814]
Hi, I was wondering if there are still some reference example results pending for the Hubert SSL librilight_limited_10hr tuning, using either the pre-existing fairseq models, or the espnet-trained models referenced here:

 * https://github.com/espnet/espnet/tree/master/egs2/librispeech/ssl1
 * https://github.com/espnet/espnet/tree/master/egs2/librilight_limited/asr1
   * https://github.com/espnet/espnet/blob/master/egs2/librilight_limited/asr1/conf/tuning/train_asr_hubert_base_10h_finetuning.yaml

**Comment by AdolfVonKleist** [comment]
Any further update here?  Is this maybe an ongoing experiment?

**Comment by sw005320** [comment]
@simpleoier, can you explain our current examples?

**Comment by simpleoier** [comment]
@AdolfVonKleist Sorry for my late reply. I missed this thread before.
Yes, we have some results as reference.
* As for the librispeech ssl1 recipe, we have 2 iterations of training: 1st iteration using the KMeans clustering on MFCC feature, and 2nd iteration using KMeans clustering on the 6th-layer hidden vectors of the 1st iteration.
  * 1st iteration
     * After training 150k steps, the `mack_accuracy` reached `44.2%`.
     * Finetuning this model with 10h librilight data, we got WER `33.6%` on dev-other set w/o LM.
  * 2nd iteration
     * After training 190k steps, the `mack_accuracy` reached `53.3%`.
     * Finetuning this model with 10h librilight data, we got WER `21.7%` on dev-other set w/o LM.

**Comment by rinoji** [comment]
@simpleoier 
Hi! I am Japanese high school student. 
I have a question. How did you set up your "decode_asr"?

**Comment by simpleoier** [comment]
Hi @rinoji , you may refer to this [recipe](https://github.com/espnet/espnet/tree/master/egs2/librilight_limited/asr1) for your asr model fine-tuning and decoding.

**Comment by rinoji** [comment]
@simpleoier 
Sorry for my slow understanding...The recipe run.sh specifies infrence_config=conf/decode_asr.yaml, but I don't see such a file in the conf directory. Is it automatically created?

**Comment by simpleoier** [comment]
sorry, my fault. You can probably put the follwing in `decode_asr.yaml`
```
beam_size: 1
penalty: 0.0
maxlenratio: 0.0
minlenratio: 0.0
ctc_weight: 1.0
```

**Comment by rinoji** [comment]
> sorry, my fault. You can probably put the follwing in `decode_asr.yaml`
> 
> ```
> beam_size: 1
> penalty: 0.0
> maxlenratio: 0.0
> minlenratio: 0.0
> ctc_weight: 1.0
> ```

thank you!
I will try it right away.

**Comment by rinoji** [comment]
@simpleoier 
> sorry, my fault. You can probably put the follwing in `decode_asr.yaml`
> 
> ```
> beam_size: 1
> penalty: 0.0
> maxlenratio: 0.0
> minlenratio: 0.0
> ctc_weight: 1.0
> ```

Thank you!
I will try it right away.
