### ISSUE TITLE
Inference speed comparison 

### ISSUE THREAD

**Issue by sciai-ai** [espnet/espnet#3817]
@kan-bayashi I am comparing the inference time of PWG + taco2 vs Mbmelgan + taco2 in the notebook below. I believe mbmelgan should be much much faster than PWG however the RTF are the same. Can you please check?
[https://colab.research.google.com/github/espnet/notebook/blob/5102f52d01b6bcd191c1f428f95e3fa0a74813b7/espnet2_tts_realtime_demo.ipynb](url)

**Comment by kan-bayashi** [comment]
I think the calculation time of Tacotron 2 is dominant, and therefore, the vocoder effect for RTF is not so much.
For vocoder speed comparison, please check the following page.
https://github.com/kan-bayashi/ParallelWaveGAN#speed

**Comment by sciai-ai** [comment]
Yes i saw that but it needs .scp file but i do not find this file after i trained model with tts egs2 ljspeech on my data

**Comment by kan-bayashi** [comment]
Please check https://github.com/kan-bayashi/ParallelWaveGAN#decoding-with-espnet-tts-models-features
