### ISSUE TITLE
do you any plan for adaspeech or adaspeech2?

### ISSUE THREAD

**Issue by Pydataman** [espnet/espnet#3818]

**Comment by sw005320** [comment]
Thanks for the suggestion.
Could you give us more about adaspeech and adaspeech2 and how it is important for you and the community?
We're happy to increase the priority based on it.

**Comment by Pydataman** [comment]
personalized speech generation is now in high demand for many applications

**Comment by jerryuhoo** [comment]
I would love to see it. ADASpeeh 2 seems very interesting to me.
