### ISSUE TITLE
How can I use trained espnet/egs/ljspeech/tts1 model to generate audio

### ISSUE THREAD

**Issue by 123srikanth** [espnet/espnet#3820]
Hi, I have completed my espnet/egs/ljspeech/tts1 model training sucessfully can someone help me in how to generate realtime audios by passing text to model. In the internet I found this https://colab.research.google.com/github/espnet/notebook/blob/master/espnet2_tts_realtime_demo.ipynb#scrollTo=as4iFXid0m4f
to make use of model but it seems like it works for espnet2 and I'm not getting how to use it for espnet

**Comment by kan-bayashi** [comment]
Please check this one.
https://colab.research.google.com/github/espnet/notebook/blob/master/tts_realtime_demo.ipynb
