### ISSUE TITLE
Do I need metadata.csv file to train Parallel Wave Gan vocoder

### ISSUE THREAD

**Issue by 123srikanth** [espnet/espnet#3821]
Hi I want to train Parallel Wave Gan vocoder for my dataset for which I'm going through this documentation https://github.com/kan-bayashi/ParallelWaveGAN/blob/master/egs/README.md (Run training using ESPnet2-TTS recipe within 5 minutes) where I have made everything as relevant to espnet/egs/ljspeech/tts1 model but my doubt is do I actually need to create downloads folder with data because in the documentation it was not mentioned but when I ran the model for local dataset it was actually creating.

**Comment by kan-bayashi** [comment]
If you used ESPnet1, it is better to follow to create the recipe for your dataset.
https://github.com/kan-bayashi/ParallelWaveGAN/blob/master/egs/README.md#how-to-make-the-recipe-for-your-own-dateset
