### ISSUE TITLE
VITSの学習時に出力されるTensorboardのvalid_discriminator_loss_epochなどの計算式

### ISSUE THREAD

**Issue by nosuke505** [espnet/espnet#3823]
VITSでfine-tuningを行い、Tensorboardで学習状況の確認を行いました。
validationデータ数は5個になります。
なぜ下の画像のようにepoch数が増加するほどlossが増加しているのか分かりません。
<img width="353" alt="スクリーンショット 2021-11-29 15 03 04" src="https://user-images.githubusercontent.com/86777259/143818567-ba50a18c-9181-4128-9bbe-dd6867edef47.png">
trainのlossはepoch数が進むほど減少しているのですがvalidは増加しています。
<img width="366" alt="スクリーンショット 2021-11-29 15 01 18" src="https://user-images.githubusercontent.com/86777259/143819016-e7f899c0-49c6-4b6c-9420-e68f01d4fa80.png">
そのため、これらのlossの計算を行なっているコード部分を教えていただきたいです。
よろしくお願いいたします。

**Comment by kan-bayashi** [comment]
こんにちは、林です。
コードはこの辺になります。
https://github.com/espnet/espnet/blob/4615a5871ea886ebd9852ae9b5d2140f50a453b0/espnet2/gan_tts/vits/vits.py#L400-L412

VITSに限らず、少量のデータを使ったTTSモデルの学習は過学習のような学習曲線が見られる事が多いです。例えば以下はJVSの010の話者の適応時の学習曲線です。

<img width="590" alt="スクリーンショット 2021-11-30 9 18 40" src="https://user-images.githubusercontent.com/22779813/143963093-903d091b-f589-4f45-a45d-8339ed0cb60f.png">

同じような曲線かと思います。これで全く学習がうまく行っていないかというとそうでもなく、意外ときちんとした音声を生成することができます。
https://espnet.github.io/icassp2022-tts/
のExample of JVS (Japanese single speaker adaptation)を聞いてみてください。

ですので、TTSモデルにおいてはValidationベストが最も良い品質というわけではありません。逆にいうといつ止めればいいかかなり難しいところです。

**Comment by nosuke505** [comment]
お忙しい中、丁寧なご回答ありがとうございます！
