### ISSUE TITLE
Reduction in tacotron2 audio quality after the new update of espnet

### ISSUE THREAD

**Issue by sciai-ai** [espnet/espnet#3825]
@kan-bayashi I have recently upgraded to the latest release of espnet, I have noticed that the quality of LJSpeech taco2 + PWG (MBmelgan) is reduced after upgrading and it sounds more clean with the  0.10.0 release . I think this maybe due to a pytorch version issue. Can you check.

**Comment by kan-bayashi** [comment]
Could you attach the samples?

**Comment by sciai-ai** [comment]
[Archive 3.zip](https://github.com/espnet/espnet/files/7623978/Archive.3.zip)

**Comment by kan-bayashi** [comment]
Could you provide more detailed information?
E.g., pytorch version / espnet version / pwg version for both samples

**Comment by sciai-ai** [comment]
PWG: 0.5.1

espnet version is filename, 0.10.0 vs 0.10.4

pytorch 1.8

**Comment by sciai-ai** [comment]
@kan-bayashi The audio quality suggests that maybe it is griffin-lim vocoder without using the pwg or mlmelgan?

with torch.no_grad():
    start = time.time()
    wav = text2speech(x)["wav"]

**Comment by kan-bayashi** [comment]
It seems that the files are generated from the GL.
So, what is your question? Do you want to compare the GL vocoder quality?

**Comment by sciai-ai** [comment]
I relaized i needed to change the code for the latest relase of espnet to call text2speech. frompretrained model. I supplied vocoder tag but got this error 

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
/tmp/ipykernel_23477/2657595050.py in <module>
     59     # Only for FastSpeech & FastSpeech2
     60     speed_control_alpha=1.0,
---> 61     vocoder_tag=vocoder_path
     62 )
     63 text2speech.spc2wav = None  # Disable griffin-lim

/opt/conda/lib/python3.7/site-packages/espnet2/bin/tts_inference.py in from_pretrained(model_tag, vocoder_tag, **kwargs)
    306 
    307             else:
--> 308                 raise ValueError(f"{vocoder_tag} is unsupported format.")
    309 
    310         return Text2Speech(**kwargs)

ValueError: pwg_long_nsc/checkpoint-1000000steps.pkl is unsupported format.

**Comment by kan-bayashi** [comment]
If you want to use the vocoder model file in local, please use `vocoder_file` instead of `vocodoer_tag`.
Please check https://github.com/espnet/espnet/blob/master/egs2/TEMPLATE/tts1/README.md#how-to-use-trained-model-in-python

**Comment by sciai-ai** [comment]
Seems the problem with audio quality exists. i used the vocoder file and this is the output

[download (3).wav.zip](https://github.com/espnet/espnet/files/7625257/download.3.wav.zip)

**Comment by kan-bayashi** [comment]
Could you provide two samples which are generated by the different versions?
Actually, your provided three audio seems too different, so I'm wondering you made something wrong.
<img width="918" alt="スクリーンショット 2021-11-30 22 32 34" src="https://user-images.githubusercontent.com/22779813/144056910-2acb42b5-9ac6-43ce-a454-b45acf15dc85.png">

**Comment by sciai-ai** [comment]
The text is the same "Hello world" and you can listen it in the wav too. The 3 files are defined below:

0.10.0 is espnet 0.10.0 where i used vocoder file and it works fine
0.10.4  is espnet 0.10.4 where i forgot to add vocoder_file so its griffin lim vocoder
download(3) is espnet 0.10.4 where i specify vocoder file and it doesnot sound good. I tried both pwg and mmbmelgan and both don not work well

**Comment by sciai-ai** [comment]
I found the problem is stats.h5, I do not need it for version 0.10.0 but why do I need it for 0.10.4?

**Comment by kan-bayashi** [comment]
> I found the problem is stats.h5, I do not need it for version 0.10.0 but why do I need it for 0.10.4?

Sorry for the confusion.
From v.0.10.2, we integrated the vocoder part in Text2Speech.
If you use the vocoder, basically it assumes the existence of 
- config.yaml
- stats.h5
in the same directory of the model file.

The reason why we use stats.h5 is to use the vocoder which trained by the different dataset from the text2mel models.
The processing flow is as follows:
1. text -> text2mel -> normalized feature
2. normalized feature -> inverse normalization with text2mel stats -> original scale feature
3. original scale feature -> normalization with vocoder stats -> normalized feature
4. normalized feature -> vocodoer -> waveform

If text2mel model does not use normalizer, step2 is skipped.
If stats.h5 is not found, the step 3 will be skipped.

**Comment by kan-bayashi** [comment]
@sciai-ai Did you solve this issue? If you still have a problem, please re-open.
