### ISSUE TITLE
Issues with speech translation on COVOST2

### ISSUE THREAD

**Issue by D-Keqi** [espnet/espnet#3829]
Hi! @hirofumi0810 I am running the example on COVOST2, I want to translate English speech into Chinese text. During the stage 2: Dictionary and Json Data Preparation, it makes a joint source and target dictionary based on BPE. But for Chinese or Japanese, we always employ character units, is it proper to make a joint dictionary based on English and Chinese?

**Comment by c60603** [comment]
Hi, I have same issue. If I want to translate English speech into Chinese text, what the number of nbpe needs to set to means character-level ST? Thanks.

**Comment by sw005320** [comment]
@brianyan918, can you answer it for me?
What is the best practice for the Chinese text in ST?
