### ISSUE TITLE
Incorrect implementation of greedy search in transducer decoding

### ISSUE THREAD

**Issue by csukuangfj** [espnet/espnet#3837]
See the code below:
https://github.com/espnet/espnet/blob/9827dfe37f69e8e55f902dc4e340de5108596311/espnet/nets/beam_search_transducer.py#L229-L243

when `pred` is not `self.blank_id`, it should not update the time index. 
We go to the next time step only if `pred` is equal to `self.blank_id`.

The current implementation always goes to the next time step, no matter what it decoded.

**Comment by b-flo** [comment]
Hi,

> when pred is not self.blank_id, it should not update the time index.
> ...
> The current implementation always goes to the next time step, no matter what it decoded.

You're right! It's intended in our case, greedy search was limited to only one prediction by timestep.
However, I didn't use greedy search in a while and I don't have a strong opinion on the current implementation, we can change it to the normal behaviour if asked.
