### ISSUE TITLE
Can I delete audio files in "download" directory after steps/make_fbank_pitch.sh ?

### ISSUE THREAD

**Issue by mrazizi** [espnet/espnet#3841]
I'm using Commonvoice recipe in ESPNet V1. Inside step 1 (Feature Extraction), after running ``steps/make_fbank_pitch.sh``, my disk's free space becomes too low. Can I delete audio files in ``download`` directory  after the following piece of code in ``run.sh``?

https://github.com/espnet/espnet/blob/23bee1a584e1138b0a07ff8ff03f7c3eaec79904/egs/commonvoice/asr1/run.sh#L107-L121

**Comment by kamo-naoyuki** [comment]
Yes, it's okay.
