### ISSUE TITLE
where can I found the generated audio?

### ISSUE THREAD

**Issue by 123srikanth** [espnet/espnet#3843]
Hi I have completed my training of both the espnet and vocoder model and I'm trying to generate the audios using the script https://colab.research.google.com/github/espnet/notebook/blob/master/tts_realtime_demo.ipynb#scrollTo=nQDFNuQ2dK-M 
but ultimately I don't see any wave files generated in local while the output is as follows when I run the setup.py script:

sucessfully finished download.
Sucessfully finished download.
[nltk_data] Downloading package punkt to /home/srikanth/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
Now ready to synthesize!
Input your favorite sentence in English!
आप क्या कर रहे हो
Cleaned text: AAP KYAA KR RHE HO
RTF =  1.895758571397317 :5f
<IPython.lib.display.Audio object>

**Comment by kan-bayashi** [comment]
Please save by yourself.

```python
import soundfile as sf
sf.write("test.wav", y.view(-1).cpu().numpy(), fs, "PCM_16")
```
