### ISSUE TITLE
where to find the generate audios

### ISSUE THREAD

**Issue by 123srikanth** [espnet/espnet#3845]
I have completed training of espnet and vocoder for hindi language and trying to generate audios using E2E-TTS script (https://colab.research.google.com/github/espnet/notebook/blob/master/tts_realtime_demo.ipynb#scrollTo=gtSZpF-mCjTr) but I don't find any generated audios in my working directory and the output of the script is as follows

sucessfully finished download.
Sucessfully finished download.
[nltk_data] Downloading package punkt to /home/srikanth/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
Now ready to synthesize!
Input your favorite sentence in English!
आप क्या कर रहे हो
Cleaned text: AAP KYAA KR RHE HO
RTF =  2.0722268176216043 :5f
<IPython.lib.display.Audio object>

**Comment by kan-bayashi** [comment]
Duplicated.
https://github.com/espnet/espnet/issues/3843
