### ISSUE TITLE
vague output

### ISSUE THREAD

**Issue by 123srikanth** [espnet/espnet#3846]
Hi @kan-bayashi , I have trained espnet1 and parallel wave gan model with hindi dataset for hindi language but when I checked with output it was totally different and vague. /home/srikanth/Desktop/tts/out.wav

**Comment by 123srikanth** [comment]
Can you please tell me what could have went wrong with my taining.

**Comment by kan-bayashi** [comment]
At first, please check the following points:
https://github.com/espnet/espnet/tree/master/egs2/TEMPLATE/tts1#why-the-model-cannot-be-trained-well-with-my-own-dataset
Please report your status about each item.

**Comment by 123srikanth** [comment]
How can I know which model has G2P available?

**Comment by 123srikanth** [comment]
reduction factor how much I should keep for 5 hours of dataset

**Comment by 123srikanth** [comment]
and in ljspeech there is G2P available but what changes do I need to generate phonemes because currently I'm using ljspeech but I could only see tokens being created and nowhere I found phonemes

**Comment by 123srikanth** [comment]
in run.sh I can see trans_type = "char" if I change it to "phn"  will it solve my issue and could you please elaborate what is the difference betwenne "char" and "phn" trans_type

**Comment by 123srikanth** [comment]
I have changed trans_type to "phn" and this the output of my lang1_phn folder is this correct?
[phn_train_no_dev_units (1).txt](https://github.com/espnet/espnet/files/7665436/phn_train_no_dev_units.1.txt)

**Comment by 123srikanth** [comment]
@kan-bayashi can you please clear my doubts.

**Comment by kan-bayashi** [comment]
> reduction factor how much I should keep for 5 hours of dataset

Around 5 is good choice for the debugging.

> in run.sh I can see trans_type = "char" if I change it to "phn" will it solve my issue and could you please elaborate what is the difference betwenne "char" and "phn" trans_type

First of all, ljspeech recipe is prepared for English.
So the script assumes that the input text is English.
If you use different language, the results will be incorrect.

**Comment by 123srikanth** [comment]
can you please suggest which model I can use for hindi language

**Comment by kan-bayashi** [comment]
At first, in general the model structure is the same for all languages.
The different point is only the type of input token.
So what you need to do is convert your `text` file into phoneme.

Now you follow the ESPnet1 ljspeech recipe, right?
Since ESPnet1 does not support hindi G2P, it is necessary to prepare such a function.

https://github.com/espnet/espnet/blob/23bee1a584e1138b0a07ff8ff03f7c3eaec79904/egs/ljspeech/tts1/local/clean_text.py#L47-L50

You can replace this part with your cleaner and hindi G2P.
(Cleaner may not be needed.)

**Comment by 123srikanth** [comment]
sir we have tool to generate english phonemes for hindi text can we use english phonemes for hindi language?

**Comment by 123srikanth** [comment]
COMPOUND_WORD----- K AA M P AW N D W ER D this is the phoneme generated using tool
LOKSBHAA------- L AA1 K S B AA2 HH AH0 this are being generated in the model

the phonemes generated in the model looks very different than generated using tool and the phonemes from model conatins numbers i.e, "AA2" @kan-bayashi can you please explain why the phonemes generated from model are like that with numbers
