### ISSUE TITLE
changes required in ljspeech script for using it to other languages tts

### ISSUE THREAD

**Issue by sravani40** [espnet/espnet#3847]
i have 25 hours of telugu language voice recordings and transcriptions.  i want to train tacotron and fastspeech on this dataset. what are changes that are required when compared to english language training.  what changes should we do in run.sh file?

**Comment by kan-bayashi** [comment]
At first, I recommend creating the recipe for your corpus.
https://github.com/espnet/espnet/tree/master/egs2/TEMPLATE#run-espnet-with-your-own-corpus
https://github.com/espnet/espnet/blob/master/egs2/TEMPLATE/tts1/README.md

I did not know about telugu language.
If you want to use phn based TTS, you need to implement G2P by yourself.
https://github.com/espnet/espnet/blob/master/egs2/TEMPLATE/tts1/README.md#how-to-add-a-new-g2p-module

**Comment by sravani40** [comment]
if we use char instead of phn do we still need to use G2P??

**Comment by kan-bayashi** [comment]
If you use token_type=char, you do not need g2p.

**Comment by sravani40** [comment]
i am trying to use ljspeech dataset and thinking to use char instead of phone.. but ljspeech is for english..what other changes i might need to do for using  with other langugaes???

**Comment by kan-bayashi** [comment]
> ljspeech is for english..what other changes i might need to do for using with other languages???

Again, I recommend creating a recipe for your corpus as I wrote above. 
Creating the recipe is good for reproducible experiments.
Don't be afraid. It can be done by copy & paste.
Copy template / create data.sh by following ljspeech recipe / create run.sh
Language dependent part is only g2p and cleaner options.

**Comment by sravani40** [comment]
okay sir, thank you.

**Comment by kan-bayashi** [comment]
> Should we have to definitely change it for each language?

That is kind of the design of ESPnet. When we do some experiments, first, we create the recipe for each corpus, not language. Most of the parts is the same for each recipe, but only `local/data.sh` is corpus dependent. If your corpus format is the same as the ljspeech, you may reuse ljspeech data.sh script. If you master this recipe creation, you can do all tasks (asr, tts, se, ...) with the same manners.
