### ISSUE TITLE
Integrated SE + ASR

### ISSUE THREAD

**Issue by 91205074** [espnet/espnet#3850]
Hi,

I am wondering if ESPNET2 includes any integrated speech enhancement and ASR, how about integrated speech separation and ASR?
Thank you so much.

**Comment by Emrys365** [comment]
Hi @91205074 , we are still preparing the PR (https://github.com/espnet/espnet/pull/3226) for joint training of SE and ASR. Before we finish, you could try the forked branch (https://github.com/LiChenda/espnet/tree/develop_rebased/egs2/TEMPLATE/enh_asr1) which has been verified for some recipes.

**Comment by 91205074** [comment]
Thank you so much, it's so helpful.
