### ISSUE TITLE
Question about torch mismatch, when using the "egs/csmsc" TTS model for fine-tuning

### ISSUE THREAD

**Issue by chullin** [espnet/espnet#3851]
Hi everyone,
I'm new in speech recognition and running now the script in dataset egs/csmsc. In the stage4: Text-to-speech model fine-tuning.
I got an error(s) in loading state_dict for Transformer. It's written as the picture shows. I don't know how to fix it. I really appreciate if someone could help me with this.

![image](https://user-images.githubusercontent.com/26464609/145187020-6155b7f4-0545-4139-b35f-8e2d2d79d8c5.png)

**Basic environments:**
![image](https://user-images.githubusercontent.com/26464609/145189013-54b009fd-66be-4c90-b196-80726bc7a247.png)

**Task information:**
 - Task: I want to change the TTS model in task1 of egs/vcc20 to egs/csmsc TTS model
 - Recipe: uses egs/vcc20/vc1_task1/run.sh, in which I changed some information (more information in reproduce step 2)
   - spk: use Mandarin dataset (downloads/vcc20/TFM1)
   -  pretrained_model_name: named tts_zh (egs/csmsc of [Transformer](https://github.com/espnet/espnet/blob/master/egs/csmsc/tts1/RESULTS.md#:~:text=v.0.5.3%20Initial%20Transformer))
   - ESPnet1
 
**To Reproduce**
1. move to a recipe directory, `cd egs/vcc20/vc1_task1`
2. execute `run.sh` with specific arguments, `./run.sh --stage -1 --stop_stage 4  --spk TMF1  --pretrained_model_name tts1_zh` (The following steps are the changes in the script)
    - stage -1: download csmsc Transformer TTS model
    - stage 0: use vcc20/vc1_task2/locoal/clean_text_mandarin.py to turn Mandarin dateset into pinyin
    - stage 1: M_train_list.txt use `M10001-M10060` and M_dev_list.txt use `M10061-M10070` 
3. the error log, `exp/TEF1_train_pytorch_train_pytorch_transformer+spkemb.tts1/train.log`

![image](https://user-images.githubusercontent.com/26464609/145191643-6e4605a7-25cf-4779-adc3-2205a1c94667.png)

I know that the error message is that the torch size does not match, but I printed out `espnet/tts/pytorch_backend/tts.py`
The idim=261 and odim=80 in `train.log`, I don’t know what I did wrong, which caused torch.size to be 160 instead of 80

Please tell me if you need more information. Thanks a lot!

**Comment by kan-bayashi** [comment]
Sorry for the late reply. I miss your post.
Maybe this is because reduction_factor is set to 2.
Then, at each time step, the model outputs 2 frames so the dimension is doubled.

**Comment by chullin** [comment]
Thank you very much, I will try the way you said 😀
