### ISSUE TITLE
ModuleNotFoundError: No module named 'phonemizer'

### ISSUE THREAD

**Issue by 123srikanth** [espnet/espnet#3857]
Hi I'm facing the following error while running the espnet/egs2/ljspeech/tts1 model for hindi language with g2p = espeak_ng_hindi and language as hi. I have installed phonemizer but still it is giving no module phonemizer.
<code>$bash run.sh --stage 4 --stop-stage 4
</code>
<code>
2021-12-10T07:20:57 (tts.sh:205:main) ./tts.sh --lang hi --feats_type raw --fs 22050 --n_fft 1024 --n_shift 256 --token_type phn --cleaner tacotron --g2p espeak_ng_hindi --train_config conf/train.yaml --inference_config conf/decode.yaml --train_set tr_no_dev --valid_set dev --test_sets dev eval1 --srctexts data/tr_no_dev/text --audio_format wav --stage 4 --stop-stage 4
2021-12-10T07:20:57 (tts.sh:500:main) Stage 4: Generate token_list from data/tr_no_dev/text
/usr/bin/python3 /home/ubuntu/espnet/espnet2/bin/tokenize_text.py --token_type phn -f 2- --input dump/raw/srctexts --output dump/token_list/phn_tacotron_espeak_ng_hindi/tokens.txt --non_linguistic_symbols none --cleaner tacotron --g2p espeak_ng_hindi --write_vocabulary true --add_symbol '<blank>:0' --add_symbol '<unk>:1' --add_symbol '<sos/eos>:-1'
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/ubuntu/espnet/espnet2/bin/tokenize_text.py", line 271, in <module>
    main()
  File "/home/ubuntu/espnet/espnet2/bin/tokenize_text.py", line 267, in main
    tokenize(**kwargs)
  File "/home/ubuntu/espnet/espnet2/bin/tokenize_text.py", line 109, in tokenize
    g2p_type=g2p,
  File "/home/ubuntu/espnet/espnet2/text/build_tokenizer.py", line 57, in build_tokenizer
    remove_non_linguistic_symbols=remove_non_linguistic_symbols,
  File "/home/ubuntu/espnet/espnet2/text/phoneme_tokenizer.py", line 446, in __init__
    preserve_punctuation=True,
  File "/home/ubuntu/espnet/espnet2/text/phoneme_tokenizer.py", line 323, in __init__
    from phonemizer import phonemize
ModuleNotFoundError: No module named 'phonemizer'
</code>

 and here is the list packages installed which also has phonemizer in my system venv which I installed using pip3

pip3 list
Package                Version             Editable project location
---------------------- ------------------- ----------------------------
appdirs                1.4.4
argcomplete            1.12.3
asn1crypto             0.24.0
attrs                  21.2.0
audioread              2.1.9
Automat                0.6.0
blinker                1.4
cached-property        1.5.2
certifi                2018.1.18
cffi                   1.15.0
chardet                3.0.4
click                  6.7
clldutils              3.10.1
cloud-init             21.4
colorama               0.3.7
colorlog               6.6.0
command-not-found      0.3
ConfigArgParse         1.5.3
configobj              5.0.6
constantly             15.1.0
cryptography           2.1.4
csvw                   1.11.0
cycler                 0.10.0
decorator              5.1.0
Distance               0.1.3
distro-info            0.18ubuntu0.18.04.1
dlinfo                 1.2.1
ec2-hibinit-agent      1.0.0
espnet-tts-frontend    0.0.3
filelock               3.3.0
g2p-en                 2.1.0
gdown                  4.0.2
h5py                   3.4.0
hibagent               1.0.1
httplib2               0.9.2
hyperlink              17.3.1
idna                   2.6
importlib-metadata     4.8.1
incremental            16.10.1
inflect                5.3.0
isodate                0.6.0
jaconv                 0.3
Jinja2                 2.10
joblib                 1.1.0
jsonpatch              1.16
jsonpointer            1.10
jsonschema             2.6.0
kaldiio                2.17.2
keyring                10.6.0
keyrings.alt           3.0
kiwisolver             1.3.2
language-selector      0.1
librosa                0.8.1
llvmlite               0.37.0
MarkupSafe             1.0
matplotlib             3.4.3
netifaces              0.10.4
nltk                   3.6.5
numba                  0.54.1
oauthlib               2.0.6
packaging              21.0
PAM                    0.4.2
parallel-wavegan       0.5.3               /home/ubuntu/ParallelWaveGAN
pexpect                4.2.1
**phonemizer             3.0**
Pillow                 8.3.2
pip                    21.3.1
pooch                  1.5.2
protobuf               3.18.1
pyasn1                 0.4.2
pyasn1-modules         0.2.1
pycparser              2.20
pycrypto               2.6.1
PyGObject              3.26.1
PyJWT                  1.5.3
pyOpenSSL              17.5.0
pyparsing              2.4.7
pypinyin               0.44.0
pyserial               3.4
PySocks                1.7.1
python-apt             1.6.5+ubuntu0.7
python-dateutil        2.8.2
python-debian          0.1.32
pyxdg                  0.25
PyYAML                 3.12
regex                  2021.11.10
requests               2.18.4
requests-unixsocket    0.1.5
resampy                0.2.2
rfc3986                1.5.0
scikit-learn           1.0
scipy                  1.7.1
SecretStorage          2.3.1
segments               2.2.0
service-identity       16.0.0
setuptools             58.2.0
six                    1.11.0
sos                    4.1
SoundFile              0.10.3.post1
ssh-import-id          5.7
systemd-python         234
tabulate               0.8.9
tensorboardX           2.4
threadpoolctl          3.0.0
toml                   0.10.2
torch                  1.9.1
tqdm                   4.62.3
Twisted                17.9.0
typing-extensions      3.10.0.2
ubuntu-advantage-tools 27.4
ufw                    0.36
unattended-upgrades    0.1
Unidecode              1.3.2
uritemplate            4.1.1
urllib3                1.22
wheel                  0.30.0
xmltodict              0.12.0
yq                     2.12.2
zipp                   3.6.0
zope.interface         4.3.2

when I tried installing phonemizer using pip I got this error 
<code>
$ pip install phonemizer
</code>
<code>
/usr/lib/python2.7/dist-packages/secretstorage/dhcrypto.py:15: CryptographyDeprecationWarning: Python 2 is no longer supported by the Python core team. Support for it is now deprecated in cryptography, and will be removed in the next release.
  from cryptography.utils import int_from_bytes
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
Defaulting to user installation because normal site-packages is not writeable
ERROR: Could not find a version that satisfies the requirement phonemizer (from versions: none)
ERROR: No matching distribution found for phonemizer
WARNING: You are using pip version 20.3.4; however, version 21.3.1 is available.
You should consider upgrading via the '/usr/bin/python2.7 -m pip install --upgrade pip' command.
</code>

please help me with this, I'm trying to figure it out since past 2 days but nothing worked!

**Comment by 123srikanth** [comment]
@kan-bayashi can please guide in this

**Comment by anushiyarachel** [comment]
@123srikanth How did you handle the issue?
