### ISSUE TITLE
Every single value of speech_lengths is not different  in espnet2 asr

### ISSUE THREAD

**Issue by hagakure333** [espnet/espnet#3859]
Hi I often use espnet2 asr
I'd like each of the speech_lengths tensors to have a different value, like text_lengths.
speech_lengths is a series of identical values
In some cases, it is not, and I don't know the difference.

Below are the speech_lengths and text_lengths when running the an4 recipe by default.

speech_shape torch.Size([20, 32000]) 
speech_lengths tensor([32000, 32000, 32000, 32000, 32000, 32000, 30400, 30400, 30400, 30400,
        30400, 30400, 30400, 30400, 30400, 30400, 30400, 30400, 30400, 30400],
       device='cuda:0')

text_shape torch.Size([20, 25]) 
text_lengths tensor([10, 24, 20, 18, 10, 16, 22, 10, 18, 10, 14, 25, 21, 18, 10, 23, 21, 14,
        11, 10], device='cuda:0')

### espnet2.asr.espnet_model.py
   def forward(
        self,
        speech: torch.Tensor,
        speech_lengths: torch.Tensor,
        text: torch.Tensor,
        text_lengths: torch.Tensor,
    ) -> Tuple[torch.Tensor, Dict[str, torch.Tensor], torch.Tensor]:
        """Frontend + Encoder + Decoder + Calc loss

        Args:
            speech: (Batch, Length, ...)
            speech_lengths: (Batch, )
            text: (Batch, Length)
            text_lengths: (Batch,)
        """
        assert text_lengths.dim() == 1, text_lengths.shape
        # Check that batch_size is unified
        assert (
            speech.shape[0]
            == speech_lengths.shape[0]
            == text.shape[0]
            == text_lengths.shape[0]
        ), (speech.shape, speech_lengths.shape, text.shape, text_lengths.shape)
        batch_size = speech.shape[0]
        
        
        print("speech_shape",speech.shape,"speech_lengths",speech_lengths)
        print("text_shape",text.shape,"text_lengths",text_lengths)
        
        print("speech.shape",speech_lengths)
        print("text.shape",text_lengths)

**Comment by sw005320** [comment]
I don't fully understand your question, but this may happen before/after padding.

**Comment by hagakure333** [comment]
thank you for your reply
