### ISSUE TITLE
Incorrect usage of the `cache` in the method `score()` for transducer beam search

### ISSUE THREAD

**Issue by csukuangfj** [espnet/espnet#3863]
See the code below
https://github.com/espnet/espnet/blob/ae635955ff79efde9c4df007bb8324fea386c169/espnet/nets/pytorch_backend/transducer/rnn_decoder.py#L180-L183

It concatenates all the integers in `yseq` and uses it as a key into the `cache`.

The issue is that it places no separators during the concatenation. The consequence is that different `yseq` may map to the same key. For instance, both `[1, 11, 1, 2]` and `[1, 1, 1, 12]` map to the same key `11112`.
```python3
>>> ''.join(list(map(str, [1, 11, 1, 2])))
'11112'
>>> ''.join(list(map(str, [1, 1, 1, 12])))
'11112'
```

**Comment by b-flo** [comment]
Good catch, same bug for `batch_score`. It's surprising no one caught that before.
