### ISSUE TITLE
Transformer on WSJ without CTC training yields bad results

### ISSUE THREAD

**Issue by timolohrenz** [espnet/espnet#3866]
**Bug Description**
Hi,
    first some background: On this year's ASRU we introduced our novel relaxed attention method [(arXiv paper)](https://arxiv.org/abs/2107.01275). In the paper, we ran experiments with the fairseq espresso toolkit and already contributed our code there. Unfortunately, no joint CTC training is natively implemented there so I want to try out our method in espnet2 and upon success also make a PR for our method here. First I trained a standard transformer model from the egs2/wsj recipe and got expected good results. Second, to recreate the setting from the paper, I trained a transformer model using no CTC decoding (`ctc_weight=0.0`). Training looked totally fine, but when I run decoding with the following decoding parameters, the results are pretty bad.
```
lm_weight: 1.2
beam_size: 20
penalty: 0.0
maxlenratio: 0.0
minlenratio: 0.0
ctc_weight: 0.0
```
Basically ctc_weight is the only parameter that I touched. In the results, we note very short output hypotheses and thus a lot of deletions. Here are some examples

```
id: (4k0-4k0c0301)
Scores: (#C #S #D #I) 4 1 20 0
REF:  SAATCHI officials said the management RE:STRUCTURING MIGHT ACCELERATE ITS EFFORTS TO PERSUADE CLIENTS TO USE THE FIRM AS A ONE STOP SHOP FOR BUSINESS SERVICES 
HYP:  SUCH    officials said the management ************** ***** ********** *** ******* ** ******** ******* ** *** *** **** ** * *** **** **** *** ******** ******** 
Eval: S                                     D              D     D          D   D       D  D        D       D  D   D   D    D  D D   D    D    D   D        D        

id: (4k0-4k0c0302)
Scores: (#C #S #D #I) 3 0 16 0
REF:  "QUOTE it makes sense TO PUT THE DIVISIONS TOGETHER AT THE TOP STRATEGIC LEVEL "UNQUOTE A SAATCHI OFFICIAL SAID 
HYP:  ****** it makes sense ** *** *** ********* ******** ** *** *** ********* ***** ******** * ******* ******** **** 
Eval: D                     D  D   D   D         D        D  D   D   D         D     D        D D       D        D    

id: (4k0-4k0c0303)
Scores: (#C #S #D #I) 5 1 18 0
REF:  WITH THE INTEGRATIONS OF COMMUNICATIONS AND CONSULTING UNITS THERE MAY BE A GREATER DEGREE OF CROSS FIRE FERTILIZATION mr. MILLAR said in a statement 
HYP:  **** *** ************ ** ************** *** ********** ***** ***** *** ** * ******* ****** ** ***** **** ************* mr. MILLER said in a statement 
Eval: D    D   D            D  D              D   D          D     D     D   D  D D       D      D  D     D    D                 S                          

id: (4k0-4k0c0304)
Scores: (#C #S #D #I) 9 1 11 0
REF:  as he talks his wife and two teen age DAUGHTERS HURRY IN FROM THE RAIN AND KISS HIM ON THE CHEEK    
HYP:  as he talks his wife and two teen age ********* ***** ** **** *** **** *** **** *** ** *** DAUGHTER 
Eval:                                       D         D     D  D    D   D    D   D    D   D  D   S        
```

The results look like this:

```
,---------------------------------------------------------------------------------------------------------------------------.
|exp/asr_noctc/decode_lm_lm_train_lm_transformer_en_char_valid.loss.ave_asr_model_valid.acc.ave/test_dev93/score_wer/hyp.trn|
|---------------------------------------------------------------------------------------------------------------------------|
|               |    # Snt       # Wrd     |    Corr          Sub           Del          Ins           Err        S.Err     |
|===========================================================================================================================|
|    Sum/Avg    |     503         8234     |    21.9          2.8          75.3          0.4          78.5         95.8     |
|===========================================================================================================================|
|     Mean      |    50.3        823.4     |    21.9          2.9          75.2          0.4          78.4         95.8     |
|     S.D.      |     1.6         43.4     |     2.3          0.8           2.6          0.3           2.2          2.7     |
|    Median     |    50.0        814.5     |    22.0          2.7          75.6          0.4          78.3         96.0     |
`---------------------------------------------------------------------------------------------------------------------------'
```

I guess I could try tuning of the decoding parameters, but maybe you have some hints on what to adjust when training and testing without CTC.

Thank you!

**Comment by sw005320** [comment]
Thanks for your report!
(I missed your talk due to the conflict of the other meetings... but my colleagues checked yours, and I'll watch your video later)

Can you check https://espnet.github.io/espnet/tutorial.html#ctc-attention-and-hybrid-ctc-attention and set `maxlenratio` and `minlenratio` by changing the inference config?
Many tools (e.g., espresso) actually have such parameters to adjust the length.
We disable these parameters since CTC/attention joint decoding is very powerful and can eliminate these heuristics (but this causes the above confusions actually...)

About PR, you may also send me an email (shinjiw@ieee.org), if you want us to discuss it in advance.

**Comment by lumaku** [comment]
I observed similar effects with attention-only decoding of RNN-based networks with `ctc_weight = 0`, also described in [this](https://link.springer.com/chapter/10.1007/978-3-030-26061-3_27) paper. You may also observe word loops. Setting `maxlenratio` and `minlenratio` to reasonable values should fix this.
