### ISSUE TITLE
can we use phonemes generated using phonemizer for espnet/egs/ljspeech/tts1 model

### ISSUE THREAD

**Issue by 123srikanth** [espnet/espnet#3870]
Hi @kan-bayashi sir I have created data folder for espnet/egs/ljspeech/tts1 model for hindi language where I have created the text files inside data folder with the phonemes generated using the phonemizer for each corresponding line of text. This is how I have seen the data folder which is created for default data in the model with trans_type as phn. So in the same manner I have created for my own data. I'm facing a lot of errors in espnet2/egs/ljspeech/tts model so I want go with this method. Can you please suggest if it is a right method and is there a possibility that it will work so that I can proceed with my training.It has successfully ran all the pre training stages and before proceeding further I just wanted confirmation of what I'm doing is right. And if I can proceed then I have generated phonemes using phonemizer and phonemizer_EspeakBackend where both of them seem to differ slightly can you please clarify which phonemes I can use whether generated of phonemizer or phonemizer_EspeakBackend. 

[data_phonemizer_espeakbackend.zip](https://github.com/espnet/espnet/files/7722947/data_phonemizer_espeakbackend.zip)

[data_phonemizer.zip](https://github.com/espnet/espnet/files/7722945/data_phonemizer.zip)

**Comment by kan-bayashi** [comment]
If you want to use phn text, each phoneme should be separated with space.
In your case, it seems to each token is separated with double space, which should be single space.
```
LJ051-0001 hˈə  ʰχˈeː  ɖˈə  lˈə  ʰχˈiː   cˈə  ʰχˈaː  hˈə  tˈə  ʰχˈeː   tˈə  ʰχˈoː   ʋˈə  ʰχˈoː   kˈə  ʰχˈɛː  cˈə   cʰˈə  ʰχˈoː  ɖˈə  nˈʊktˌaː   bʰˈə  ʰχˈiː   sˈə  kˈə  tˈə  ʰχˈeː   tʰˈə  ʰχˈeː   lˈə  ʰχˈeː  kˈə  ʰχˈɪ  nˈə   ˈʊ  nˈə  həlˈʌnt  hˈə  ʰχˈoː  ʌnˈʊsʋəɾ  nˈə  ʰχˈeː   ˈɛː  sˈə  ʰχˈaː   nˈə  hˈə  ʰχˈiː  ʌnˈʊsʋəɾ   kˈə  ʰχˈɪ  jə  ʰχˈaː   ˈɔː  ɾˈə   ˈaː  sˈə  həlˈʌnt  ʈˈə  həlˈʌnt  ɾˈə  ʰχˈeː  lˈə  ʰχˈɪ  jə  ʰχˈaː  ˈi   pˈə  ʰχˈaː  ɾˈə  ʰχˈiː   kˈə  ʰχˈaː   dˈə  sˈə  ʋˈə  ʰχˈaː  ʌnˈʊsʋəɾ   ʋˈə  ʰχˈɪ  kˈə  ʰχˈeː  ʈˈə   hˈə  ʰχˈaː  sˈə  ʰχˈɪ  lˈə   kˈə  ɾˈə   ˈʊ  sˈə   pˈə  ʰχˈaː  ɾˈə  ʰχˈiː   mˈə  ʰχˈeː  ʌnˈʊsʋəɾ   ˈʌ  pˈə  nˈə  ʰχˈeː   ʋˈə  ʰχˈɪ  kˈə  ʰχˈeː  ʈˈə  ʰχˈoː  ʌnˈʊsʋəɾ   kˈə  ʰχˈaː   ˈaː  ʌnˈʊsʋəɾ  kˈə  ɖˈə  nˈʊktˌaː  ʰχˈaː   nˈə  ʰχˈɔː   kˈə  ɾˈə   dˈə  ʰχˈɪ  jə  ʰχˈaː 
```
And I'm not familiar with your language but splitting each token into each character is another option.
e.g.`LJ051-0001 hˈə ʰχˈeː ɖˈə lˈə` -> `LJ051-0001 h ˈ ə ʰ χ ˈ e ː ɖ ˈ ə l ˈ ə`
