### ISSUE TITLE
Training ESPNet TTS for new languages

### ISSUE THREAD

**Issue by saiakarsh193** [espnet/espnet#3872]
How do we train an existing TTS model for new languages? Can you please point out some resources to do this? The language I intend to train for is a very different writing system from that of English. How do we make changes to account for this?

**Comment by kan-bayashi** [comment]
First, I recommend making recipe for your dataset.
https://github.com/espnet/espnet/tree/master/egs2/TEMPLATE/tts1#how-to-make-a-new-recipe-for-my-own-dataset
To make the recipe, any language specific processing is not needed.

Then, you can try to build your TTS model using your created recipe with `--token_type char` and `--cleaner none` options, which will build char-based TTS model.

If you want to phoneme-based TTS model, you can add a new g2p module.
https://github.com/espnet/espnet/tree/master/egs2/TEMPLATE/tts1#how-to-add-a-new-g2p-module
Then, you can run your recipe with `--token_type phn` and `--g2p <your_created_g2p>` to build phoneme-based TTS model.
