### ISSUE TITLE
Too many configuration files

### ISSUE THREAD

**Issue by kamo-naoyuki** [espnet/espnet#3873]
There are too many configuration files to run espnet-experiment (Though this is my fault partially). This is troublesome especially for beginners. 

- path.sh (tools/extra_path.sh, local/path.sh)
- db.sh
- cmd.sh
- conf/slurm.conf, conf/queue.conf
- conf/train.yaml, conf/decode.yaml, etc

At least, `db.sh` is a bad idea, and now I think it should be written in `run.sh`. I might refactor them.

**Comment by ftshijt** [comment]
I would vote for combining `path.sh` and reflect `db.sh`

**Comment by lumaku** [comment]
For configuration files for networks:

* I'd prefer a single configuration file for each neural net that includes all relevant training, architecture and decoding parameters. Same for trained network configuration files, with the same stem name. A language model can be described in a separate configuration file.

* One thing to consider: When experimenting with network architecture, the code is often modified for different experiments (changing layers etc.), and that's where I sometimes encountered annoying compatibility issues: Here, the configuration file, the model and the code are required to be in synchronization. When saving a neural network, pytorch stores network parameters in a named dictionary. To reproduce the network, the python code (as during training) with the same variable names and structure is needed.
 To keep different network structures in the code, one may git-commit each variant or apply unelegant switch-case statements, extended with each experiment iteration... 
 Some toolkits (e.g. kaldi, speechbrain) solve this by exposing their network configuration to configuration files, shifting architecture description from code to the config. It is then often easier to restore a model from its configuration file than from its specific git commit hash.


About recipe organization:
 * The espnet 2 `asr.sh` takes many use cases into account, e.g., the type of token and different dataset structures but is quite complex.
  Maybe refactoring `asr.sh` into modules would be practical - a `run.sh` consisting of simple stages, similar to kaldi or espnet 1 recipes, would be easier to handle: The "old" espnet 1 recipes omit some complexities and feel more modular, i.e. it is easier to copy-paste parts of the `run.sh` after-another and observe the output files.
  After a training/benchmarking/uploading recipe is done, the run script in espnet 2 is not needed at all for inference, only the model files - therefore, any training run of the espnet 2 `asr.sh` only covers a single use-case.
 A beginner user would only want to have the best-practice recipe, and an advanced user would want to assemble his own training script, from the already extensive python interface and maybe from additional modules provided in `scripts`.

*   The folder `egs` has recipes named `asr1`, `tts1`, that is similar to the kaldi naming scheme, where "asr" stands for the type of task and the number for the training scripts version. For espnet2, we have a new folder egs2, also with a naming scheme `asr1`, `tts1`. By intuition, I would have expected espnet2 recipes in the old `egs` folder and naming them `asr2`, `tts2`...?
 And by the way, why is there a distinction between `scripts` and `pyscripts`?
