### ISSUE TITLE
why is the tts training duration reduced to half with reduction factor

### ISSUE THREAD

**Issue by 123srikanth** [espnet/espnet#3879]
I have 23 hours of data for training when I used reduction factor as 1 the training duration it showed was 8 days but when I changed the reduction factor to 2 the training duration reduced to 4 days why is like that. I just wanted to make it attention learning. and I think attention learning would increase the training duration but it happened vice versa.

**Comment by kan-bayashi** [comment]
I recommend reading the paper about reduction factor.
https://arxiv.org/pdf/1703.10135.pdf
If we increase the reduction factor, the number of output frames per time step is increased. 
(e,g., R = 3, the model output 3 frames at each time step)
This means the decoder loop is decreased w.r.t. reduction factor and therefore, the required time is halved in the case of R=2.

> I just wanted to make it attention learning.

I could not understand your meaning. You mean you want to make it easier to learn the diagonal attention?

**Comment by 123srikanth** [comment]
yes, I think if I make learning the diagonal attention easier I will get better output. as you mentioned the same in other issues.
