### ISSUE TITLE
[QUESTION] dict and cmvn equivalent in synth_wav.sh usage with xvector+phoneme tacotron2 model and pwg vocoder

### ISSUE THREAD

**Issue by seastar105** [espnet/espnet#3882]
I trained korean tacotron2 with xvector model(espnet2 recipe) and neural vocoder(parallelwavegan repo). Now, trying to generate wav files from arbitrary reference audio, by modifying synth_wav.sh

where can i find ${dict} file and ${cmvn} file when trained espnet2 tts recipe?

below is my training direcotry

![image](https://user-images.githubusercontent.com/30820469/146714244-2d5a9e3b-1a99-445e-93cc-9bf0bd5d0069.png)

**Comment by kan-bayashi** [comment]
You do not need to use synth_wav.sh, which is for espnet1.
Please check the following part
https://github.com/espnet/espnet/tree/master/egs2/TEMPLATE/tts1#how-to-test-my-model-with-an-arbitrary-given-text
Or
https://colab.research.google.com/github/espnet/notebook/blob/master/espnet2_tts_realtime_demo.ipynb

**Comment by seastar105** [comment]
It seems the demo has no speaker embedding(x-vector) extraction from arbitrary audio. Anyway, I could make speech from arbitrary audio with espnet2 tts recipe's stage 2 and stage 7. Thanks
