### ISSUE TITLE
[QUESTION] espnet2 jtubespeech data cleaning

### ISSUE THREAD

**Issue by jcn199729** [espnet/espnet#3883]
Hi, is there a data cleaning process in the espnet2-jtubespeech to identify if the audio files is spoken in the correct language? Since the jtubespeech data is from Youtube, so the source is not official and standard and the language spoken in the video may not be Japanese, I couldn't find the script for the language identification. Appreciate if there's a step to identify that.

**Comment by lumaku** [comment]
Yes, there were many videos with spoken English with Japanese subtitles. The alignment step computes a score how well the subtitles fit to the audio using CTC segmentation. The score of those videos with a different language is clearly distinguishable using this score, as in our setup, language-mismatches have a score less than `-5.0` (estimated by inspection), and "the good" audio has `>= -1.0`. Those videos are then automatically filtered out based on this score.

**Comment by jcn199729** [comment]
> Yes, there were many videos with spoken English with Japanese subtitles. The alignment step computes a score how well the subtitles fit to the audio using CTC segmentation. The score of those videos with a different language is clearly distinguishable using this score, as in our setup, language-mismatches have a score less than `-5.0` (estimated by inspection), and "the good" audio has `>= -1.0`. Those videos are then automatically filtered out based on this score.

Greatly thanks! Will try to run the alignment
