### ISSUE TITLE
-Infinity and Large Negative CTC Loss values in training Transformer,ESPNET-1

### ISSUE THREAD

**Issue by sairitwik27** [espnet/espnet#3885]
I am training a hybrid CTC+Attention Transformer ASR architecture on a custom English dataset in ESPNET-1.

While training, in certain epochs the CTC loss is a large negative value or -Infinity, as seen in the Logs below. Is it some bug? Am I encountering log(0) here? How does ESPNET deal with this when proceeding to train further? 

What could be some reasons this might happen, or any pointers on what I should look for to correct this? How can I avoid this from happening? 

I have pasted the Log info for the relevant epochs below:

This is in the 2nd epoch:

    {
        "main/loss_ctc": 108.71437326431274,
        "main/loss_att": 37.65539085388183,
        "main/acc": 0.8430992370614624,
        "main/loss": 58.973086261749266,
        "epoch": 1,
        "iteration": 8900,
        "elapsed_time": 4625.597098432947
    },
    {
        "main/loss_ctc": 110.13659646987915,
        "main/loss_att": 37.941686143875124,
        "main/acc": 0.8417587452432902,
        "main/loss": 59.60016016960144,
        "epoch": 1,
        "iteration": 9000,
        "elapsed_time": 4674.663548453944
    }

HERE IS THE BUG:

    {
        "main/loss_ctc": -1.0633823332454027e+35,
        "main/loss_att": 33.7449349117279,
        "main/acc": 0.8588202696569839,
        "main/loss": -3.190146999736208e+34,
        "main/cer_ctc": 0.5,
        "main/cer": 0.25806451612903225,
        "main/wer": 0.56,
        "validation/main/loss_ctc": 94.53634327835178,
        "validation/main/loss_att": 25.39011526107788,
        "validation/main/acc": 0.8954681877503573,
        "validation/main/cer_ctc": 0.2903944302370258,
        "validation/main/cer": 0.13007220444671863,
        "validation/main/wer": 0.40138911275437356,
        "validation/main/loss": 46.13398478490225,
        "epoch": 2,
        "iteration": 9100,
        "elapsed_time": 4900.8509092121385
    },

    {
        "main/loss_ctc": 107.66262237548828,
        "main/loss_att": 34.65400894641876,
        "main/acc": 0.8588821330866492,
        "main/loss": 56.55659395217896,
        "epoch": 2,
        "iteration": 9200,
        "elapsed_time": 4949.161990025081
    },
    {
        "main/loss_ctc": 105.64264076232911,
        "main/loss_att": 34.456401147842406,
        "main/acc": 0.8594218544011567,
        "main/loss": 55.81227375507355,
        "epoch": 2,
        "iteration": 9300,
        "elapsed_time": 4998.13778205798
    } 

This happens again in the 7th epoch:

    {
        "main/loss_ctc": 61.394277324676516,
        "main/loss_att": 14.41912658214569,
        "main/acc": 0.939583179521388,
        "main/loss": 28.51167245388031,
        "epoch": 7,
        "iteration": 35300,
        "elapsed_time": 18497.071233517025
    },
    {
        "main/loss_ctc": 63.5604776763916,
        "main/loss_att": 16.440751180648803,
        "main/acc": 0.930040720627006,
        "main/loss": 30.57666962623596,
        "epoch": 7,
        "iteration": 35400,
        "elapsed_time": 18546.422725314973
    },

HERE IS THE BUG AGAIN:

    {
        "main/loss_ctc": -Infinity,
        "main/loss_att": 15.544101314544678,
        "main/acc": 0.9344525899503685,
        "main/loss": -Infinity,
        "epoch": 7,
        "iteration": 35500,
        "elapsed_time": 18594.736651994055
    },

    {
        "main/loss_ctc": 65.15866382598877,
        "main/loss_att": 15.682408819198608,
        "main/acc": 0.9380623444817587,
        "main/loss": 30.52528594017029,
        "epoch": 7,
        "iteration": 35600,
        "elapsed_time": 18644.14574455493
    },
    {
        "main/loss_ctc": 62.12017169952392,
        "main/loss_att": 14.673978538513184,
        "main/acc": 0.9380897674552255,
        "main/loss": 28.90783706665039,
        "epoch": 7,
        "iteration": 35700,
        "elapsed_time": 18692.988422461087
    },

**Comment by sw005320** [comment]
This would happen when the output length is relatively longer than the input length (after downsample).
During training, we remove such irregular minibatch, so, if this only happens rarely, you can ignore it.
If it happens everywhere, I recommend you check the data of such particular files.
Usually, this is caused by noisy transcriptions or the error of VAD/segment information.

**Comment by sairitwik27** [comment]
Thanks! It happens about 5-7 times over 40 epochs. I would probably ignore it.
