### ISSUE TITLE
How can we adapt male voice to female voiced pretrained model

### ISSUE THREAD

**Issue by 123srikanth** [espnet/espnet#3905]
Hi I have a pretrained english model with female voice now I want to adapt the same to male voice using finetuning how can I do it?

**Comment by kan-bayashi** [comment]
For espnet1, you can follow https://espnet.github.io/espnet/tutorial.html?highlight=finetune#transfer-learning

**Comment by 123srikanth** [comment]
Thank you can you please suggest something for espnet2 as well.
