### ISSUE TITLE
How to run Hubert Training

### ISSUE THREAD

**Issue by godzilla-123** [espnet/espnet#3911]
I've glanced through the code in [this directory](https://github.com/espnet/espnet/tree/1c88acf771d19d824cca26d50fe2155ddd558bba/espnet2/hubert) but I can't find any recipe to train Hubert on my own data. 

Do we have plans to add Hubert training and inference recipe (like for LibriSpeech, use LibriLight with Hubert as pre-training stage before stage 10, then run the training in stage 10 to see if we can get better results)?

**Comment by simpleoier** [comment]
Hi, the recipe is in the egs2 directory. 
Here are the [pretraining](https://github.com/espnet/espnet/tree/master/egs2/librispeech/ssl1) and [finetuning](https://github.com/espnet/espnet/tree/master/egs2/librilight_limited/asr1) recipes.

**Comment by Cescfangs** [comment]
@simpleoier according to the config, 4nodes x 8gpu are used for pretraining librispeech, I was wondering how long it took to finish pretraining for 1 hubert iteration? and which gpu type for this exp(A100)?

**Comment by simpleoier** [comment]
We used V100. It took about 1 week  for each iteration

**Comment by Cescfangs** [comment]
> We used V100. It took about 1 week for each iteration

Thanks
