### ISSUE TITLE
can we adapt punctuation in TTS

### ISSUE THREAD

**Issue by 123srikanth** [espnet/espnet#3919]
Hi there, the audio output that was produced from my hindi TTS seems very flat. How can I adapt the punctuation in my training so that I can produce the output with variations based on the punctuation I give?

**Comment by kan-bayashi** [comment]
It highly depends on your text preprocessing part and dataset.
First, please make sure your training data included such samples.
Second, please check your input representation (g2p outputs) includes correct punctuation or symbols to control the pronunciation.
Maybe Japanese G2P is a good reference for the pronunciation symbol represents.
(Please check `pyopenjtalk_*` as examples)
https://github.com/espnet/espnet/tree/master/egs2/TEMPLATE/tts1#supported-text-frontend
Or if you train the model that uses explicit f0 / energy such as FastSpeech2, the pronunciation will be improved.

**Comment by 78sneha** [comment]
Thank you will check it!
