### ISSUE TITLE
Installation using "make -j" error

### ISSUE THREAD

**Issue by trangnm58** [espnet/espnet#392]
I follow the instructions and run "make -j" in tools/ folder. I got the error as follow:
...
gcc.compile.c++ bin.v2/libs/wave/build/gcc-5.4.0/release/link-static/threading-multi/cpplexer/re2clex/cpp_re.o
gcc.archive bin.v2/libs/wave/build/gcc-5.4.0/release/link-static/threading-multi/libboost_wave.a
common.copy /home/trangnm/workspace/espnet-v.0.2.0/tools/mosesdecoder/opt/lib/libboost_wave.a
...failed updating 34 targets...
...skipped 12 targets...
...updated 13984 targets...
contrib/Makefiles/install-dependencies.gmake:99: recipe for target '/home/trangnm/workspace/espnet-v.0.2.0/tools/mosesdecoder/opt/include/boost' failed
make[1]: *** [/home/trangnm/workspace/espnet-v.0.2.0/tools/mosesdecoder/opt/include/boost] Error 1
make[1]: Leaving directory '/home/trangnm/workspace/espnet-v.0.2.0/tools/mosesdecoder'
Makefile:58: recipe for target 'moses' failed
make: *** [moses] Error 2

I've installed all the libraries in the requirements.txt and set up CUDA environment.

**Comment by kan-bayashi** [comment]
Hi @trangnm58 .
Thank you for your report.
Could you run following commands step-by-step again?
```
$ cd tools
$ rm -rf mosesdecoder
$ git clone https://github.com/moses-smt/mosesdecoder.git
$ cd mosesdecoder 
$ make -f contrib/Makefiles/install-dependencies.gmake
$ ./compile.sh
$ ln -s mosesdecoder moses
```
Sometime `compile.sh` is failed if the server has the number of thread > 64.

And if you do not want to run speech translation recipe `egs/iwslt18`, you do not have to install moses.
You can skip it.

**Comment by sw005320** [comment]
@hirofumi0810, is this moses installation required? As far as I remember, you just use some moses scripts, and we may not have to install moses. Is that correct? If so, we can just git clone moses, and skip the installation.

**Comment by trangnm58** [comment]
Thank you, @kan-bayashi . I still got the same error but I will skip moses.
However, when I run "python check_install.py", I got warnings:

WARNING: --> chainer_ctc is not installed.
WARNING: --> warpctc_pytorch is not installed.

Can you show me where can I get these libraries?

**Comment by trangnm58** [comment]
I also got this error when I run "./run.sh --backend chainer" in "egs/an4/asr1/" directory:

`./run.sh: line 66: utils/parse_options.sh: No such file or directory`

**Comment by kan-bayashi** [comment]
It seems that the installation is totally failed.
Please check your tools directory.
If the install is  succeeded, the structure is as follows:
```sh
$ cd tools
$ ll
drwxr-xr-x 1 t_hayashi users  138 Aug 27 23:02 chainer_ctc
-rw-r--r-- 1 t_hayashi users 5144 Aug 29 14:01 check_install.py
-rw-r--r-- 1 t_hayashi users  776 Aug 28 18:09 conda.mk
lrwxrwxrwx 1 t_hayashi users   12 Aug 27 23:04 kaldi -> kaldi_github
drwxr-xr-x 1 t_hayashi users  182 Jun 30 11:27 kaldi_github
drwxr-xr-x 1 t_hayashi users  258 Aug 26 14:57 kaldi-io-for-python
-rw-r--r-- 1 t_hayashi users 2452 Aug 31 10:48 Makefile
lrwxrwxrwx 1 t_hayashi users   12 Aug 27 23:04 moses -> mosesdecoder
drwxr-xr-x 1 t_hayashi users  616 Aug 26 15:07 mosesdecoder
drwxr-xr-x 1 t_hayashi users   50 Aug 26 14:57 nkf
-rw-r--r-- 1 t_hayashi users 3235 Aug 27 22:59 prefetch.patch
-rw-r--r-- 1 t_hayashi users  153 Aug 28 18:09 requirements.txt
drwxr-xr-x 1 t_hayashi users  352 Aug 26 14:59 sentencepiece
-rw-r--r-- 1 t_hayashi users   83 Aug 27 22:59 test_requirements.txt
drwxr-xr-x 1 t_hayashi users   82 Aug 27 23:06 venv
drwxr-xr-x 1 t_hayashi users  186 Aug 27 23:02 warp-ctc
```
If there is no `nkf`, `kaldi`, `kaldi-io-for-python`, or `sentencepiece`, please install them via following commands:
```sh
$ cd tools
# install nkf
$ make nkf
# install kaldi
$ make -j kaldi
# kaldi-io-for-python
$ make kaldi-io-for-python
# install sentencepiece
$ make sentencepiece
```

**Comment by trangnm58** [comment]
I figured that there is something wrong with symlinks so I fixed it.
The problem is solved. Thank you!

**Comment by Ruhewang** [comment]
could you tell me how do you solve the symlinks problem?
