### ISSUE TITLE
fastspeech.v2 receipe for espnet ljspeech training

### ISSUE THREAD

**Issue by 78sneha** [espnet/espnet#3920]
I have completed my training for espnet/ train_pytorch_tacotron2.yaml model and I want to train for 2nd stage that is for train_fastspeech.v2.yaml where can I find the receipe for it?

**Comment by kan-bayashi** [comment]
What is the `fastspeech.v2`? You mean fastspeech2?
Unfortunately, fastspeech2 is not supported in espnet1.
Try espnet2 https://github.com/espnet/espnet/tree/master/egs2/TEMPLATE/tts1#how-to-run
