### ISSUE TITLE
fast speech training issue

### ISSUE THREAD

**Issue by sravani40** [espnet/espnet#3921]
I have trained with tacotron with espnet1 recipe. but now for finetuning with fastspeech conf files are not there that are based on tactotron. all finetuning conf files seems to be based on transformer recipe.

how to train fastspeech on tactotron model in espnet1?

**Comment by kan-bayashi** [comment]
> all finetuning conf files seems to be based on transformer recipe.

Why do you think so?
I think you can use tacotron2 as the teacher model.

**Comment by sravani40** [comment]
in espnet/egs/ljspeech/tts1   no conf file is there that is based on tacotron as teacher model.     in egs2 we have, but in egs all are based on transformer teacher model.

**Comment by kan-bayashi** [comment]
https://github.com/espnet/espnet/blob/master/egs/ljspeech/README.md
Please read README.
You can use Taco2 as the teacher model.
