### ISSUE TITLE
About value of PPL 

### ISSUE THREAD

**Issue by miziworld** [espnet/espnet#3922]
Hello, 
Thank you for always providing us with good project.

I trained egs2/ksponspeech ASR model(conformer), LM(transformer) about 50 epoch.
And trained transformer LM's ppl result was 8.17.
Usually, the ppl figures found in other papers are not this low, but is this result because the amount of kspon datasets is small?
Or is there a problem with the ppl calculation provided by Espnet?

I look forward to hearing from you.
Thank you.

**Comment by sw005320** [comment]
It would happen if the vocabulary size of the token is very small (e.g., the PPL with the English character unit would be less than 8).
Can you check the vocabulary size?

**Comment by miziworld** [comment]
Thank you for your reply.
ksponspeech's vocab size is 2309 and If it's this size, is that a natural value?

**Comment by sw005320** [comment]
I see. Then, it might be due to that the same sentences are used in the training and test sets.
