### ISSUE TITLE
how to generate phonemes for egs2/ljspeech/tts1

### ISSUE THREAD

**Issue by 123srikanth** [espnet/espnet#3923]
I want to train TTS for hindi language and what changes I need to make in espnet2/egs/ljspeech/tts1 receipe so that I can generate phonemes and token.txt file as per hindi language

**Comment by kan-bayashi** [comment]
Which do you mean, egs/ljspeech/tts1 or egs2/ljspeech/tts1?

**Comment by 123srikanth** [comment]
sorry I meant for egs2/ljspeech/tts1

**Comment by kan-bayashi** [comment]
Please change to `g2p=espeak_ng_hindi` and `cleaner=none`.
https://github.com/espnet/espnet/blob/80fb76330a53824bae4e72ac5933f2ca827e7b03/egs2/ljspeech/tts1/run.sh#L28
https://github.com/espnet/espnet/blob/80fb76330a53824bae4e72ac5933f2ca827e7b03/egs2/ljspeech/tts1/run.sh#L37

And I recommend using the latest master.
(I fixed the stability of phonemizer recently #3916)

**Comment by 123srikanth** [comment]
Thanks a lot @kan-bayashi

**Comment by 123srikanth** [comment]
how much slow is the espeak because it is taking so much time to generate tokens.txt file

**Comment by kan-bayashi** [comment]
> how much slow is the espeak because it is taking so much time to generate tokens.txt file

Did you use update to the current master?
#3916 will significantly accelerate the processing.

**Comment by 123srikanth** [comment]
I have cloned again the espnet and installed again will that not work?

**Comment by kan-bayashi** [comment]
Then, it is fine. Espeak hindi speed problem.
If you cannot be patient, please consider the following solutions.
See command section:
https://github.com/espnet/espnet/tree/master/egs2/ljspeech/tts1#ljspeech_tts_train_tacotron2_raw_phn_tacotron_espeak_ng_english_us_vits_trainlossave
