### ISSUE TITLE
monotonous tts audio files generated

### ISSUE THREAD

**Issue by sravani40** [espnet/espnet#3935]
i have finetuned ljpseech model for 2 hours of my recordings. It has produced monotonous recordings. is there any way it can produce some variation in the voice depending on the context.

**Comment by kan-bayashi** [comment]
Is your model English?
FS2 or VITS might improve the pronunciation.

**Comment by sravani40** [comment]
English model

**Comment by kan-bayashi** [comment]
Then, espeak-based english g2p might be better.
https://github.com/espnet/espnet/tree/master/egs2/ljspeech/tts1#ljspeech_tts_train_tacotron2_raw_phn_tacotron_espeak_ng_english_us_vits_trainlossave

**Comment by sravani40** [comment]
Is ljspeech fastspeech2 pretrained model available for finetuning with our
voice files??

**Comment by kan-bayashi** [comment]
See https://github.com/espnet/espnet/tree/master/egs2/ljspeech/tts1#ljspeech_tts_train_conformer_fastspeech2_raw_phn_tacotron_espeak_ng_english_us_vits_trainlossave

**Comment by sravani40** [comment]
I FINETUNED WITH 2 HOURS OF MY VOICE BY USING LJSPEECH FST SPEECH2 . STILL I DID NOT SEE NY IMPROVEMENT IN PRONOUNCITION...

**Comment by sravani40** [comment]
I FEEL LIKE STILL THERE IS SOME VIBRTION
