### ISSUE TITLE
mini_librispeech error

### ISSUE THREAD

**Issue by housebaby** [espnet/espnet#3939]
I run the egs, without changing configs,
the result is weird.
as follows 
exp/diar_train_diar_raw/diarized_simu/data/dev_clean_2_ns2_beta2_500/scoring/result_th0.3_med11_collar0.0: OVERALL SPEAKER DIARIZATION ERROR = 99.81 percent of scored speaker time  `(ALL)

|threshold_median_collar|DER|
|---|---|
|result_th0.0_med11_collar0.0|99.82|
|result_th0.0_med1_collar0.0|99.82|
|result_th0.3_med11_collar0.0|99.81|
|result_th0.3_med1_collar0.0|99.82|
|result_th0.4_med11_collar0.0|99.81|
|result_th0.4_med1_collar0.0|99.82|
|result_th0.5_med11_collar0.0|99.81|
|result_th0.5_med1_collar0.0|99.82|
|result_th0.6_med11_collar0.0|99.81|
|result_th0.6_med1_collar0.0|99.82|
|result_th0.7_med11_collar0.0|99.81|
|result_th0.7_med1_collar0.0|99.82|

**Comment by ftshijt** [comment]
Can you also post the training curves to help us diagnose the issue?

**Comment by housebaby** [comment]
> Can you also post the training curves to help us diagnose the issue?

https://github.com/espnet/espnet/issues/3939#issuecomment-1005072124

**Comment by housebaby** [comment]
![image](https://user-images.githubusercontent.com/9246556/148151233-5d2a93fe-ab69-4736-a85e-02f2f0179f20.png)

**Comment by housebaby** [comment]
![image](https://user-images.githubusercontent.com/9246556/148151326-d611ac36-9785-45d4-ae94-a31a811ad3ff.png)

**Comment by housebaby** [comment]
> Can you also post the training curves to help us diagnose the issue?

I have updated two pics. And looking forward for your suggestion

**Comment by ftshijt** [comment]
I doubt if the model is converged with 10 epochs. I remember it would take more than 50 epochs to converge. Can you @housebaby  first try to increase the epochs of training (also increase the patience to prevent early stop) @YushiUeda could you also check with your experiences?

**Comment by YushiUeda** [comment]
I ran the experiment again today but wasn't able to reproduce the bug. In my experience, around 20 epochs would be sufficient for getting DER=30% with this dataset.
![acc](https://user-images.githubusercontent.com/87093809/148156899-a854e10d-a447-449f-bf3c-d5b8e89da046.png)
![loss](https://user-images.githubusercontent.com/87093809/148156908-a1cdb261-aa33-498a-afe9-7fc3b011ab3d.png)

@housebaby there are 2 config files for the training (`train_diar.yaml` & `train_diar_eda.yaml`), which one are you using?
If you are using `train_diar.yaml`:

1. You have to make some modifications as mentioned [here](https://github.com/espnet/espnet/issues/3745). (This bug will be fixed in [this PR](https://github.com/espnet/espnet/pull/3900).) 

1. You also have to uncomment the last line of `decode_diar.yaml`.

If these are not modified, you should get an error. In your case, the training and decoding stages seem to be somewhat working, so these may not be the problem here.

**Comment by housebaby** [comment]
> train_diar
I use train_diar.yaml
in decode_diar.yaml, there is only two lines.  Do you mean that we don't need segment_size? 
 fs: 8000
 segment_size: 10

**Comment by housebaby** [comment]
> If these are not modified, you should get an error. In your case, the training and decoding stages seem to be somewhat working, so these may not be the problem here.

This is not the problem. I have fixed it before to run  with train_diar.yaml

**Comment by YushiUeda** [comment]
> in decode_diar.yaml, there is only two lines. Do you mean that we don't need segment_size?
fs: 8000
segment_size: 10

No, I mean you have to include `num_spk: 2` in `decode_diar.yaml`, i.e.,
```
fs: 8000
segment_size: 10
num_spk: 2
```

**Comment by housebaby** [comment]
> I doubt if the model is converged with 10 epochs. I remember it would take more than 50 epochs to converge. Can you @housebaby first try to increase the epochs of training (also increase the patience to prevent early stop) @YushiUeda could you also check with your experiences?

Even if it is not fully converged, it seem that the der on training/eval is about 0.3/0.45. But how comes that during inference most
Duplicate of #

> > in decode_diar.yaml, there is only two lines. Do you mean that we don't need segment_size?
> > fs: 8000
> > segment_size: 10
> 
> No, I mean you have to include `num_spk: 2` in `decode_diar.yaml`, i.e.,
> 
> ```
> fs: 8000
> segment_size: 10
> num_spk: 2
> ```
OK I think I have found the problem. It seems result from sample rate error in scoring stage.
I have another question. If I want to train dataset where number of speakers are unknown ( varied from 1 to 5, for example)
How should I set  num_spk?
If I didn't set num_spk,  there will be mistakes when comes to the decoder.
         decoder_class = decoder_choices.get_class(args.decoder)
         decoder = decoder_class(
            num_spk=args.num_spk,
             encoder_output_size=encoder.output_size(),
             **args.decoder_conf,
         )

**Comment by ftshijt** [comment]
Hi if you want to set unknown number of speakers, you should use diar_eda config instead of diar.

**Comment by housebaby** [comment]
> Hi if you want to set unknown number of speakers, you should use diar_eda config instead of diar.
Yeah , I use diar_eda.
As in the training set, speaker num vary from wav to wav.
Some problem occurs when build chunk iteratory .

   File "/home/storage15/work/tools/espnet-newest/egs2/AliMeeting/diar/espnet2/iterators/chunk_iter_factory.py", line 170, in build_iter
    cache_id_list, cache_chunks = yield from self._generate_mini_batches(
  File "/home/storage15/work/tools/espnet-newest/egs2/AliMeeting/diar/espnet2/iterators/chunk_iter_factory.py", line 208, in _generate_mini_batches
    tmp={k: torch.stack(v[:bs], 0) for k, v in batches.items()},
  File "/home/storage15/work/tools/espnet-newest/egs2/AliMeeting/diar/espnet2/iterators/chunk_iter_factory.py", line 208, in <dictcomp>
    tmp={k: torch.stack(v[:bs], 0) for k, v in batches.items()},
RuntimeError: stack expects each tensor to be equal size, but got [200000, 2] at entry 0 and [200000, 4] at entry 1

**Comment by YushiUeda** [comment]
In `diar_eda.yaml`, can you change the batch size to `batch_size: 1` and insert a line for accum_grad, say, `accum_grad: 10`?
This should work.

**Comment by housebaby** [comment]
> In `diar_eda.yaml`, can you change the batch size to `batch_size: 1` and insert a line for accum_grad, say, `accum_grad: 10`? This should work.

Another question is about the chunk. I notice that during training the default chunk is 200000 samples.  which is abount 6.25s for 16k. and 12.5s for 8k speech. how will this  affect the peformance. As for inference , there may be many different lengths of speech. Some maybe shorter, some mabye longer

**Comment by housebaby** [comment]
> In `diar_eda.yaml`, can you change the batch size to `batch_size: 1` and insert a line for accum_grad, say, `accum_grad: 10`? This should work.

Thank you. It works. Won't it be very slow with batch as 1?

**Comment by YushiUeda** [comment]
> Another question is about the chunk. I notice that during training the default chunk is 200000 samples. which is abount 6.25s for 16k. and 12.5s for 8k speech. how will this affect the peformance. As for inference , there may be many different lengths of speech. Some maybe shorter, some mabye longer

I haven't investigated the chunk size, so I have no answer to this question. If the recordings you are using are not long (~30sec in 8kHz), you can use the whole recording without chunking them.

> Thank you. It works. Won't it be very slow with batch as 1?

Might be. You can pretrain the model by using the 2-speaker-only data first, then adapt the model with a varied number of speakers with a fewer number of epochs (see `run_eda.sh` and its config files in `librimix/diar` recipe).
