### ISSUE TITLE
How can we change the speed and pitch of the output

### ISSUE THREAD

**Issue by 123srikanth** [espnet/espnet#3944]
How to change the speed and pitch of the output audio. I'm using the fastspeech_alpha but it doesnot make any change with change in its value

Only for fastspeech (lower than 1.0 is faster speech, higher than 1.0 is slower speech)
"fastspeech_alpha": 1.0,

**Comment by Ray8716397** [comment]
i also want to know how

**Comment by kan-bayashi** [comment]
Changing pitch is not support but it is possible for fastspeech2.
https://github.com/espnet/espnet/blob/9c24b3adddbde3402530080cb58ae08a6f4dd642/espnet2/tts/espnet_model.py#L271-L275
You can add bias here (note that the pitch is log domain).

Changing speed is supported in fastspeech 1 / 2, and vits.
Please change fastspeech_alpha.
