### ISSUE TITLE
sentencepiece error

### ISSUE THREAD

**Issue by miziworld** [espnet/espnet#3956]
Hello,
when I run the script in the following command: ./run --stage 2 and the error is like this.
![image](https://user-images.githubusercontent.com/17849068/148902995-475a967a-c91d-4644-b64e-9dd74ade18a2.png)

I did pip3 install sentencepiece and 
![image](https://user-images.githubusercontent.com/17849068/148903252-3254bd23-039e-44d4-a418-a2be5bfd73c5.png)
sentencepiece is already installed. 

my environment is like this.
![image](https://user-images.githubusercontent.com/17849068/148903359-c0c97b76-3ba1-4093-bb51-e16f99119f3d.png)
What's the problem..?

**Comment by sw005320** [comment]
Which installation did you use?
We encourage the user to install the package via conda (https://espnet.github.io/espnet/installation.html#step-2-installation-espnet).
We would not have such an issue with the conda based installation.

**Comment by miziworld** [comment]
I'm using the docker container.
I prefer to use docker than conda, is there any workaround for this? Also, is a sentencepiece essential when using the ksponspeech example?

**Comment by sw005320** [comment]
> I'm using the docker container.

Got it.
@Fhrozen, do you know why sentencepiece is not used?

**Comment by Fhrozen** [comment]
if you are running `run.sh` from the egs2 then you may have an error.
Is the docker container built by yourself?
You can try executing **https://github.com/espnet/espnet/blob/master/docker/run.sh** to check the command first.
