### ISSUE TITLE
AttributeError: 'ChainerDataLoader' object has no attribute 'previous_epoch_detail While trying to resume from snapshot

### ISSUE THREAD

**Issue by vinitunni** [espnet/espnet#3963]
**Describe the bug**
I am running a transducer experiment. However, when I try to resume my training from a snapshot, I see the following error
"return self._iterators['main'].previous_epoch_detail
AttributeError: 'ChainerDataLoader' object has no attribute 'previous_epoch_detail'"

**Basic environments:**
 - OS information: Ubuntu 18.04 (Kernel 4.15.0)
 - python version: 3.8.0 (gcc(8.4.0)
 - espnet version: espnet-0.10.4
 - Git hash commit eee2566f2395d676e3978376315a4cd116a4e335 (tag: v.0.10.4, master)
 - pytorch version '1.10.0+cu102'
 Collecting environment information...
PyTorch version: 1.10.0+cu102
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.5 LTS (x86_64)
GCC version: (Ubuntu 8.4.0-1ubuntu1~18.04) 8.4.0
Clang version: Could not collect
CMake version: version 3.10.2
Libc version: glibc-2.27

Python version: 3.8.0 (default, Feb 25 2021, 22:10:10)  [GCC 8.4.0] (64-bit runtime)
Python platform: Linux-4.15.0-143-generic-x86_64-with-glibc2.27
Is CUDA available: True
CUDA runtime version: 10.2.89
GPU models and configuration: 
GPU 0: NVIDIA GeForce RTX 2080 Ti
GPU 1: NVIDIA GeForce RTX 2080 Ti
GPU 2: NVIDIA GeForce RTX 2080 Ti
GPU 3: NVIDIA GeForce RTX 2080 Ti

Nvidia driver version: 470.42.01
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.2.2
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.2.2
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.2.2
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.2.2
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.2.2
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.2.2
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.2.2
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.20.3
[pip3] pytorch-ranger==0.1.1
[pip3] pytorch-wpe==0.0.1
[pip3] torch==1.10.0
[pip3] torch-complex==0.2.1
[pip3] torch-optimizer==0.3.0
[pip3] torchaudio==0.10.0
[pip3] warprnnt-pytorch==0.1
[conda] Could not collect

**Task information:**
 - Task:ASR
 - Recipe: librispeech
 - ESPnet1

**To Reproduce**
1. cd egs/librispeech/asr1
2. execute transducer run.sh (adapted from voxforge) for a few epochs
3. Run again with resume variable set for an epoch
3. error in exp/XXX/train.log

**Error logs**
2022-01-13 11:27:48,999 (asr:666) INFO: resumed from /home/vinit/exp/espnet-0.10.4/egs/librispeech/asr1/exp/XXXX/results/snapshot.ep.20
/home/vinit/exp/XXXX_ASR_repo_devp/tools/venv/lib/python3.8/site-packages/chainer/training/triggers/interval_trigger.py:91: UserWarning: The previous value of iteration is not saved. IntervalTrigger guesses it using current iteration. If this trigger is not called at every iteration, it may not work correctly.
  warnings.warn(
/home/vinit/exp/XXXX_ASR_repo_devp/tools/venv/lib/python3.8/site-packages/chainer/training/triggers/interval_trigger.py:103: UserWarning: The previous value of epoch_detail is not saved. IntervalTrigger uses the value of trainer.updater.previous_epoch_detail. If this trigger is not called at every iteration, it may not work correctly.
  warnings.warn(
Exception in main training loop: 'ChainerDataLoader' object has no attribute 'previous_epoch_detail'
Traceback (most recent call last):
  File "/home/vinit/exp/XXXX_ASR_repo_devp/tools/venv/lib/python3.8/site-packages/chainer/training/trainer.py", line 313, in run
    while not stop_trigger(self):
  File "/home/vinit/exp/XXXX_ASR_repo_devp/tools/venv/lib/python3.8/site-packages/chainer/training/triggers/interval_trigger.py", line 60, in __call__
    previous_epoch_detail = updater.previous_epoch_detail
  File "/home/vinit/exp/XXXX_ASR_repo_devp/tools/venv/lib/python3.8/site-packages/chainer/training/updaters/standard_updater.py", line 115, in previous_epoch_detail
    return self._iterators['main'].previous_epoch_detail
Will finalize trainer extensions and updater before reraising the exception.
Traceback (most recent call last):
  File "/home/vinit/exp/XXXX_ASR_repo_devp/egs/librispeech/asr1/../../../espnet/bin/asr_train.py", line 657, in <module>
    main(sys.argv[1:])
  File "/home/vinit/exp/XXXX_ASR_repo_devp/egs/librispeech/asr1/../../../espnet/bin/asr_train.py", line 643, in main
    train(args)
  File "/home/vinit/exp/XXXX_ASR_repo_devp/espnet/asr/pytorch_backend/asr.py", line 965, in train
    trainer.run()
  File "/home/vinit/exp/XXXX_ASR_repo_devp/tools/venv/lib/python3.8/site-packages/chainer/training/trainer.py", line 349, in run
    six.reraise(*exc_info)
  File "/home/vinit/exp/XXXX_ASR_repo_devp/tools/venv/lib/python3.8/site-packages/six.py", line 719, in reraise
    raise value
  File "/home/vinit/exp/XXXX_ASR_repo_devp/tools/venv/lib/python3.8/site-packages/chainer/training/trainer.py", line 313, in run
    while not stop_trigger(self):
  File "/home/vinit/exp/XXXX_ASR_repo_devp/tools/venv/lib/python3.8/site-packages/chainer/training/triggers/interval_trigger.py", line 60, in __call__
    previous_epoch_detail = updater.previous_epoch_detail
  File "/home/vinit/exp/XXXX_ASR_repo_devp/tools/venv/lib/python3.8/site-packages/chainer/training/updaters/standard_updater.py", line 115, in previous_epoch_detail
    return self._iterators['main'].previous_epoch_detail
AttributeError: 'ChainerDataLoader' object has no attribute 'previous_epoch_detail'

Similar issue has been mentgiones in https://github.com/espnet/espnet/issues/636#issuecomment-620667584 but unaddressed

**Comment by sw005320** [comment]
Do you observe it in the general configuration or only observer it with transducer run.sh?

**Comment by vinitunni** [comment]
I have noticed this in only the transducer as of now, I will confirm in a few hours and get back.

**Comment by b-flo** [comment]
```
Steps to reproduce the behavior:

    cd egs/librispeech/asr1
    execute transducer run.sh (adapted from voxforge) for a few epochs
    Run again with resume variable set for an epoch
    error in exp/XXX/train.log
```

Just tested with `an4` dataset, I couldn't reproduce the error... Resume feature was working as intended.
Not sure what's happening given current information.

**Comment by vinitunni** [comment]
I too am not able to reproduce the error right now for newer experiments. Will reopen the issue when I see it again

**Comment by sairitwik27** [comment]
Hi, I am facing the same issue with transformer architecture. I am training it on a custom dataset, but the architecture is the default architecture in the conf/train.yaml of the wsj ASR recipe. (Basically the same run.sh).

**Comment by b-flo** [comment]
As stated in my last message, I (and also OP) couldn't reproduce this issue.
If you have a minimal example to reproduce the error or additional information which could help pinpoint the issue, feel free to share! Otherwise it'll be difficult to help you.

**Comment by sairitwik27** [comment]
Unfortunately, I haven't been able to reproduce the error either with another dataset or model. But the error persists with my current model. 

By any chance, does early stopping have an effect on this behavior? Earlier I was trying to resume from an epoch after my training stopped because of early stopping and I encountered the error. But restarting from an epoch after the full training has the resume functionality working well.

**Comment by b-flo** [comment]
Resuming after an early stop or a manual stop in the middle of an epoch shouldn't yield an error. I'll do some additional testing.
