### ISSUE TITLE
Problem in decoding in AI shell recipe over Hindi Language

### ISSUE THREAD

**Issue by tarunsaib1997** [espnet/espnet#3964]
**Separate words are getting merged into one word while decoding in AI shell recipe over Hindi Language when I change the lm-weight parameter in decode configurations. I have highlighted few instances here below, but there are many such in the example below, as well as with many utterances. What might be the issue, can anyone help me out?**

Reference transcription : **उसे जयादा** **देर इनतजार** न करना पडा थोडी **देर बाद उसे विनायक** दिखाई दिया वह लगभग भागते हुए फलैट की तरफ जा रहा था
lm-weight=0 transcription: उसे ज्यादा देर इंतजार न करना पड़ा थोड़ी देर बाद उसे विनायक दिखाई दिया वह लगभग भागते हुए फ्लैट की तरफ जा रहा था
lm-weight=0.1 transcription: उसे जयादा देर इनतजार न करना पडा थोडी देर बाद उसे विनायक दिखाई दिया वह लगभग भागते हुए फलैट की तरफ जा रहा था
lm-weight=0.7 transcription: **उसेज्यादा** **देरइंतेजार** न करना पड़ाथोड़ी **देरबादउसेविनायक** दिखाई दिया वह लगभग भागते हुए फ्लैटकी तरफ जा रहाथा

**Comment by tarunsaib1997** [comment]
@sw005320 could you please help me out?

**Comment by sw005320** [comment]
Sorry, I have no idea due to the limited information.
Can you give me more information about the data, configuration, and so on?

Also, I cannot understand your question.
It is very natural that the result would be changed when you change the lm-weight parameter.

**Comment by tarunsaib1997** [comment]
I trained a E2E conformer model of AI shell recipe on Hindi Language. I fixed this model and performed decoding with the following configuration:

batchsize: 0
beam-size: 10
penalty: 0.0
maxlenratio: 0.0
minlenratio: 0.0
ctc-weight: 0.5
lm-weight: 0
ngram-weight: 0.3

I changed lm-weight from 0 to 0.7 by keeping all other parameters constant as above. This change in lm-weight resulted in merging of two words into a single word. I have highlighted few instances below. For example, you can see in the reference transciption **देर बाद उसे विनायक** are separate words, but the hypothesized transcription with lm-weight=0.7 has these words merged into a single word *देरबादउसेविनायक**. Why is it so? I hope it's clear now @sw005320, otherwise, please let me know.

Reference transcription : **उसे जयादा** **देर इनतजार** न करना पडा थोडी **देर बाद उसे विनायक** दिखाई दिया वह लगभग भागते हुए फलैट की तरफ जा रहा था
Hypothesized lm-weight=0 transcription: **उसे ज्यादा** **देर इंतजार** न करना पड़ा थोड़ी **देर बाद उसे विनायक** दिखाई दिया वह लगभग भागते हुए फ्लैट की तरफ जा रहा था
Hypothesized lm-weight=0.7 transcription: **उसेज्यादा** **देरइंतेजार** न करना पड़ाथोड़ी **देरबादउसेविनायक** दिखाई दिया वह लगभग भागते हुए फ्लैटकी तरफ जा रहाथा

**Comment by sw005320** [comment]
The larger lm-weight means that the effectiveness of the LM becomes more dominant, and your LM seems to tend to give a higher score for the single word. 
Also, we usually do not set a very high `lm-weight` (like 0.7) unless you train an LM with large matched external text.

**Comment by tarunsaib1997** [comment]
So, is it natural that, when we have a poorly trained Language Model, if we decode with larger lm-weight, merging of words takes place?

**Comment by sw005320** [comment]
Not sure that “merging of words takes place” would be a general trend, but in general, higher LM weights with a poor LM just degrade the ASR performance.
