### ISSUE TITLE
A new high-quality single speaker speech dataset for English 

### ISSUE THREAD

**Issue by roholazandie** [espnet/espnet#3970]
I just want to open this issue to let you know about a new speech dataset with a very high-quality voice (recorded in-studio) by an English professional male speaker. It is more than 10hrs of speech with aligned text. I published a paper about it with the model that was trained using your amazing ESPnet on Interpseech 2021. Here is a link to download the dataset:

http://mohammadmahoor.com/ryanspeech-request-form/

the paper:
https://www.isca-speech.org/archive/pdfs/interspeech_2021/zandie21_interspeech.pdf

Since I want it to be seen and used by other researchers I wanted to know How can I share the eggs with you?

**Comment by sw005320** [comment]
That looks very cool!
Can you make a PR and upload a model?
Please check https://github.com/espnet/espnet/blob/master/CONTRIBUTING.md
