### ISSUE TITLE
[espnet2-asr] Prevent recreating all wav files when feats_type is raw

### ISSUE THREAD

**Issue by pkyoung** [espnet/espnet#3973]
While training asr model with espnet2,
if I set feats_type=raw, then all input wav files are recreated in flac (or wav) format into disk.
Can I prevent this and just use existing wav.scp (which is in kaldi format), and audio files in various formats?

It seems rather wasted to re-write all those files which goes over a few hundreds of GBs easily.

**Comment by kamo-naoyuki** [comment]
Hi, you can specify `--feats_type wav` to avoid converting the format:  https://github.com/espnet/espnet/blob/a62f16800341e726a5a5484a5c57828761750453/egs2/aishell/asr1/run.sh#L25

**Comment by pkyoung** [comment]
@kamo-naoyuki I assume you mean `--audio_format` not `--feats_type`.

I tried that, but with my input `wav.scp` having something like
`uttidxxx sox -t raw input.pcm -t wav |', 
the all files are converted  into wav files in `dump/raw/org/train/data/` dir.

**Comment by kamo-naoyuki** [comment]
> @kamo-naoyuki I assume you mean --audio_format not --feats_type.

Sorry, yes.

`sox -t raw input.pcm -t wav |'` indicates dumping audio files using the command of sox.  To avoid it, please write the file path instead.

```
utt some/where/utt.wav
```

Also note that, espnet2 supports only 16bit signed-integer PCM  and, file format must be flac or wav. If not so, you need to convert them anyway.
(I'm not sure what your pcm is actually. If raw format, it's necessary to convert it.)

**Comment by pkyoung** [comment]
@kamo-naoyuki I got it. Thanks!

**Comment by pkyoung** [comment]
I was fickle and reopened the issue.
Do you happen to have any near plan to support pipe input
as like shown above?
I know espnet2 is trying to implement all the processing of input files
like augmentation internally, but still pipe notation is very powerful and convenient way to apply various mappings to input audio.

**Comment by kamo-naoyuki** [comment]
Do you mean that on the fly processing when training for pipe line input?

It's possible, but it's good way because forking subprocess takes much cost, especially when the parent process allocates much memory.

However, torchaudio already supports APIs for sox effects. It's better way. I might add an option for torchaudio.sox_effects.

**Comment by pkyoung** [comment]
I see. I will keep my eyes on it.
I am done. You may close this issue.
Thank you.
