### ISSUE TITLE
real-time decoding in ASR system

### ISSUE THREAD

**Issue by miziworld** [espnet/espnet#3974]
Hello, I'm using the egs2/asr1 examples.
I am using various examples of espnet. Is there a real-time (ex. microphone) decoding function instead of using the recorded voice file when decoding?

**Comment by david9ml** [comment]
same issue here

**Comment by sw005320** [comment]
We have a demo here
https://github.com/espnet/notebook/blob/master/ESPnet2/Demo/ASR/streaming_asr_demo.ipynb
