### ISSUE TITLE
Any way to find out the name or sample id of each audio file in batches

### ISSUE THREAD

**Issue by asadolahzade** [espnet/espnet#3975]
Hi there,
How to access the file name or file path of each speech signal of train data in espnet2 when applying feature extraction or secaugment in the following functions? In these functions, I just have audio and their lengths. I need their names (or their paths) too.
	https://github.com/espnet/espnet/blob/a62f16800341e726a5a5484a5c57828761750453/espnet2/asr/espnet_model.py#L269

https://github.com/espnet/espnet/blob/a62f16800341e726a5a5484a5c57828761750453/espnet2/asr/espnet_model.py#L273

Thanks a lot.

**Comment by kamo-naoyuki** [comment]
Hi.

ESPnet2 can't provide the utterance names for now. You need to modify trainer.py

https://github.com/espnet/espnet/blob/e4fbff3dc128c1cfde5b080fcf05ed9e2d8e1d21/espnet2/train/trainer.py#L498-L515

```python
 for iiter, (names, batch) in enumerate( 
     reporter.measure_iter_time(iterator, "iter_time"), 1 
 ): 
    ...
             retval = model(names=names, **batch) 

```

Could you tell me why you need the name just for reference?

**Comment by asadolahzade** [comment]
Hi, 
Thanks for your answer.
I need the name of each speech because I want to use some info (stored in a text file) about each speech signal in the "forward" and "encode" functions. So I need their name.
Thanks again.
