### ISSUE TITLE
any plan to convert kaldi's xvector to some other library's xvector?

### ISSUE THREAD

**Issue by seastar105** [espnet/espnet#3980]
Hi, thanks for good framework. always.

is there any plan to use non kaldi's xvector for tts model? It's bit hard to use xvector when inference with arbitrary reference voice. There're some python libraries can make speaker embedding.(e.g resemblyzer, speechbrain)

**Comment by sw005320** [comment]
Great suggestion.
We're definitely considering it. 
One plan is in https://github.com/espnet/espnet/issues/3421

**Comment by seastar105** [comment]
I really hope it happens soon. Thanks!
