### ISSUE TITLE
float division by zero when Using ngpu 0 on pytorch

### ISSUE THREAD

**Issue by Fhrozen** [espnet/espnet#400]
Currently, I am testing the docker containers and found that when I tried to run the pytorch training (on AN4/ASR1) using cpu it breaks due to this setup:
https://github.com/espnet/espnet/blob/76f6d177752d9706279937a4126ba53b040252ee/src/asr/asr_pytorch.py#L122
The chainer training in cpu has not this problem.

**Comment by kan-bayashi** [comment]
Sorry, this is my mistake.
I’ve fixed it (#401).

**Comment by Fhrozen** [comment]
Reported, PR and closing =)
