### ISSUE TITLE
Are there any Japanese lexicon for MFA?

### ISSUE THREAD

**Issue by yt605155624** [espnet/espnet#4000]
I don't known Japanese at all，but I want to train fastspeech2 with the durations generated from MFA(which is different from your repo, you get the durations from Tacotron2), I want to try JSUT datasets, there are only Japanese characters(no phones), are there any lexicon in Japanese TTS, such as CMUDict in English and pinyin -> initial, final in Chinese?
I have asked some people who known Japanese, they tell me Fifty tones of Japanese, maybe this map will help me https://jp.hjenglish.com/subject/pronounce/, but did a lexion with 100 keys enough? If there are Chinese in a sentence , are there any lexicon to map Chinese Characters to Fifty tones of Japanese?

**Comment by iamanigeeit** [comment]
> I don't known Japanese at all，but I want to train fastspeech2 with the durations generated from MFA(which is different from your repo, you get the durations from Tacotron2),

MFA has been added. 

>  I want to try JSUT datasets, there are only Japanese characters(no phones), are there any lexicon in Japanese TTS, such as CMUDict in English and pinyin -> initial, final in Chinese? I have asked some people who known Japanese, they tell me Fifty tones of Japanese, maybe this map will help me https://jp.hjenglish.com/subject/pronounce/, but did a lexion with 100 keys enough? If there are Chinese in a sentence , are there any lexicon to map Chinese Characters to Fifty tones of Japanese?

I think what you want is a phonemizer, this is included in ESPnet.
