### ISSUE TITLE
Speech enhancement parameters

### ISSUE THREAD

**Issue by takashin3391** [espnet/espnet#4004]
I am trying to create a new model of speech enhancement.
However, I don't know what the parameters mean.
Is there a document where I can find the meaning of the parameters to create a new model?
Or is there some other better way to create a new model?

**Comment by sw005320** [comment]
Could you tell me more exactly what parameters are you checking?
If you mean to say the options, you'd find some descriptions in
https://espnet.github.io/espnet/apis/espnet2_bin.html?highlight=speech%20enhancement#enh-inference-py
https://espnet.github.io/espnet/apis/espnet2_bin.html?highlight=speech%20enhancement#enh-train-py

**Comment by takashin3391** [comment]
Thank you for your answer.
I now understand what the options mean.

Additionally, I would like to know the meaning of the parameters listed in the yaml file.
Please let me know the easy way for me to run all the networks (dprnn, transformer, dnn-wpe, etc.) that are implemented in speech enhancement.

I want to do a performance comparison of each model.

**Comment by takashin3391** [comment]
I want to run the networks supported by the speech enhancement task and compare the performance of each network.
I need to know the meaning of yaml parameters.
Is there any documentation explaining the meaning of the parameters in the yaml file?

**Comment by takashin3391** [comment]
I noticed that all the networks I wanted to work (Transformer, Comformer, Dual path RNN, Conv-Tasnet) were in gs2\wsj0_2mix\enh1\conf\tuning.

However, the meaning of the parameters in the yaml file will be needed in the future and I would appreciate the documentation.
