### ISSUE TITLE
Potential bugs in b-flo/warp-transducer

### ISSUE THREAD

**Issue by csukuangfj** [espnet/espnet#4005]
I find that ESPnet is using

https://github.com/espnet/espnet/blob/dbcdca1c2919064e735dd7f7940b92de18804546/tools/installers/install_warp-transducer.sh#L16

https://github.com/espnet/espnet/blob/dbcdca1c2919064e735dd7f7940b92de18804546/espnet/nets/pytorch_backend/transducer/transducer_tasks.py#L87-L89

There is some [report](https://github.com/HawkAaron/warp-transducer/issues/93) saying that the gradients computed on CPU and CUDA are.not.the.same using `warp_transducer`.

I just created a [colab notebook](https://colab.research.google.com/drive/1vMkH8LmiCCOiCo4KTTEcv-NU8_OGn0ie?usp=sharing) to reproduce that issue and found that not only the gradients differ but also the losses.

Just want to let you know that there may be some bugs in `warp_transducer`.

**Comment by b-flo** [comment]
Hi,

Thanks for the report and example! To be honest, I'm aware of the issue in the CPU part but I don't think I'll fix it. Relying on a fork of `warp-transducer` was a temporary solution, we want to move on to something else anyway. I have a transducer loss computation module in the work but it's on low priority on my todo list so I'm also contemplating using other solutions.

On that note, is `optimized_transducer` open for feature requests (or directly PR)? I'm interested in using your project for the next ESPnet2 version but I would like to keep supporting [FastEmit ](https://arxiv.org/pdf/2010.11148.pdf).

**Comment by csukuangfj** [comment]
Yes, PRs are very welcome.

Feature requests are also welcome, but I may be slow to implement them.

**Comment by b-flo** [comment]
Great, let me finish my current work and I'll open a PR to add `FastEmit`!

Also, I'm closing this issue.
