### ISSUE TITLE
vibration in the audio

### ISSUE THREAD

**Issue by 78sneha** [espnet/espnet#4008]
the output generated from the model has lot of vibration in it. I have used bce_pos_weight = 10.0. is it because of high bce_pos_weight value?

Thanks

**Comment by kan-bayashi** [comment]
What does it mean "vibration"? I do not understand your issue, but `bce_pos_weight = 10.0` may not be related.
In my experiments, it affects the stop prediction accuracy but does not affect the quality itself.
