### ISSUE TITLE
espnet2, about FoldedBatchSampler

### ISSUE THREAD

**Issue by imdanboy** [espnet/espnet#4010]
Hi,
The docs says (https://espnet.github.io/espnet/espnet2_training_option.html#batch-type-folded)
When --batch_type folded, 
It creates mini-batch which has the size of base_batch_size // max_i(1 + L_i // f_i). 
Where L_i is the maximum length in the mini-batch for ith feature.

However, it seems L_i is minimum length in the batch currently because keys are sorted in ascending order and the keys decide the length L.
https://github.com/espnet/espnet/blob/master/espnet2/samplers/folded_batch_sampler.py#L57
```
# Sort samples in ascending order
# (shape order should be like (Length, Dim))
keys = sorted(first_utt2shape, key=lambda k: first_utt2shape[k][0])
```
Maybe keys should be sorted in descending order. 

Sorry if i misunderstood, thanks.

**Comment by kamo-naoyuki** [comment]
Thanks, I think you are right. This is my fault... I'll think about how to deal with it.
