### ISSUE TITLE
Streaming Conformer

### ISSUE THREAD

**Issue by Stasiche** [espnet/espnet#4012]
Hello! I'm interested to try ASR by streaming conformer. It looks like I need to use Speech2TextStreaming and  ContextualBlockConformerEncoder (at least because of this assert https://github.com/espnet/espnet/blob/master/espnet2/bin/asr_inference_streaming.py#L84). Am I right? and if I'm right, where can I find an information about the details of ideas, using to stream conformer? Of cause, one of the way to read the code carefully, but may be there are some docs somewhere?

**Comment by sw005320** [comment]
See https://github.com/espnet/notebook/blob/master/espnet2_streaming_asr_demo.ipynb
If you have any questions/requests, please post them.

@D-Keqi
Maybe, you can emphasize this streaming demo in our main document more.

**Comment by Stasiche** [comment]
I saw it, thank you. That why I decided that I should use ContextualBlockConformerEncoder :) 
The main question, __how__ does it work? Is there any bird-view scheme? Or smth like this to learn the basic principles?

**Comment by D-Keqi** [comment]
> See https://github.com/espnet/notebook/blob/master/espnet2_streaming_asr_demo.ipynb If you have any questions/requests, please post them.
> 
> @D-Keqi Maybe, you can emphasize this streaming demo in our main document more.

Sure! I'm going to use boldface to highlight it, is that OK?

**Comment by D-Keqi** [comment]
> I saw it, thank you. That why I decided that I should use ContextualBlockConformerEncoder :) The main question, **how** does it work? Is there any bird-view scheme? Or smth like this to learn the basic principles?

Hi, I think you might want to refer to this paper https://arxiv.org/abs/2006.14941.

**Comment by sw005320** [comment]
@D-Keqi, can you add this reference to the notebook and somewhere in the source code?

**Comment by D-Keqi** [comment]
> @D-Keqi, can you add this reference to the notebook and somewhere in the source code?

Sure!

**Comment by Stasiche** [comment]
> > I saw it, thank you. That why I decided that I should use ContextualBlockConformerEncoder :) The main question, **how** does it work? Is there any bird-view scheme? Or smth like this to learn the basic principles?
> 
> Hi, I think you might want to refer to this paper https://arxiv.org/abs/2006.14941.

Оh, yes! thank you very much!

**Comment by Stasiche** [comment]
btw, I think we need 'Question' tag here
