### ISSUE TITLE
egs1's checkpoint and trained model

### ISSUE THREAD

**Issue by miziworld** [espnet/espnet#4026]
Hello, I'm using the examples : /espnet/egs1/ksponspeech
While training in stage 4, the following error occurred and the training phase was stopped.
![image](https://user-images.githubusercontent.com/17849068/152309740-9e546323-f897-44e2-ad0a-0c32da1d09c3.png)
![image](https://user-images.githubusercontent.com/17849068/152309764-be8bb242-2603-43a3-985a-7bfd7533834d.png)
First, I don't know what this has to do with.
- My environment is V100 32G x 4

Second, When Example 2 was used, the checkpoints and the model trained in the middle were saved separately, but in Example 1, the intermediate results are not saved. Also, when you restart stage4, the training starts from the very beginning rather than where it left off. Is it impossible to continue training from the last point?

Third, When you try to run only stage 5 with the pretrained model you provided, there is no log file, so if you comment out average_checkpoint.py corresponding to line 235 of run.sh, it seems to stop without progressing to the next step.
![image](https://user-images.githubusercontent.com/17849068/152334073-58ca308e-51d3-41b7-9253-c6775e10e2c2.png)
![image](https://user-images.githubusercontent.com/17849068/152334128-3f2d4744-867d-4d5f-816e-6ac9befe6d26.png)

**Comment by sw005320** [comment]
> I don't know what this has to do with.

Is it reproducible?
It does not seem so.

> * My environment is V100 32G x 4
> 
> Second, When Example 2 was used, the checkpoints and the model trained in the middle were saved separately, but in Example 1, the intermediate results are not saved. Also, when you restart stage4, the training starts from the very beginning rather than where it left off. Is it impossible to continue training from the last point?

Please specify the snapshot in `resume` option.
See https://github.com/espnet/espnet/blob/master/egs/ksponspeech/asr1/run.sh#L20

> Third, When you try to run only stage 5 with the pretrained model you provided, there is no log file, so if you comment out average_checkpoint.py corresponding to line 235 of run.sh, it seems to stop without progressing to the next step. ![image](https://user-images.githubusercontent.com/17849068/152334073-58ca308e-51d3-41b7-9253-c6775e10e2c2.png) ![image](https://user-images.githubusercontent.com/17849068/152334128-3f2d4744-867d-4d5f-816e-6ac9befe6d26.png)

Sorry, I cannot understand what you mean to say.
Could you elaborate your question?

**Comment by miziworld** [comment]
Thank you for your reply.
The purpose of the first question is how to solve that valueerror. I don't know if the problem is cuda-related or memory-related.
![image](https://user-images.githubusercontent.com/17849068/152371417-4949b3cf-da8f-4be1-b54e-8e8cbf2e9cca.png)


The third question is a problem that occurs when performing stage 5 using the pretrained model you provided.
The following error seems to occur because checkpoints are not included in the provided pretrained model and compressed files. How do I proceed with decoding with the pretrained model you provided?

**Comment by miziworld** [comment]
Thank you.
I would like to use recog_wav.py as your advice, but it seems to be limited to the models I can use. Could it be possible to use a conformer_large model as well?

**Comment by sw005320** [comment]
yes.
the models in the list are just examples.

**Comment by miziworld** [comment]
I'm very sorry, but I need some simple help.
I downloaded the model_conformer.tar file from the following Google Drive(https://drive.google.com/file/d/1A2Gg18v-_z3dcw794aKL7SrPKHTyDbOU/view).
 But I don't know how to define the $model mentioned in recog_wav.sh.
How should I modify it to fit the data I have downloaded?

**Comment by sw005320** [comment]
Please check an example usage in https://github.com/espnet/espnet/blob/master/utils/recog_wav.sh#L64-L65
After you untar the files, you can find the necessary files.

**Comment by miziworld** [comment]
Thank you very much!
I did the decoding with recorded wav file.
The accuracy came out as expected, but the decoding speed took quite a long time despite my PC environment being good. When I used the ksponspeech example of egs2 and the inference python script of https://github.com/hchung12/espnet-asr, the speed was relatively good on the PC even if I put several test voices, but in recog_wav.sh, it took too long to do one. It takes. Why is the decoding time difference so large?

**Comment by sw005320** [comment]
There might be an issue with the wrong configuration in the decoder.
https://espnet.github.io/espnet/tutorial.html#ctc-attention-and-hybrid-ctc-attention
It is better to change some of them.

**Comment by miziworld** [comment]
Hmm...
I tried tweaking the options as per your advice, but it didn't change much. It takes about 1 minute to decode a sentence containing 13 characters. When using the same type of conformer model, it took about 2-3 seconds in egs2. Is it a difference in the decoding tool espnet1 and espnet2 use?
