### ISSUE TITLE
Shape mismatch for the decoder.output_layer when loading pre-trained model in ESPnet1

### ISSUE THREAD

**Issue by Daniel-asr** [espnet/espnet#4028]
Hi,

I want to train an ASR model on a new dataset using a pre-trained model as a starting point and we want to use the same tokens as before.

We used nBPE=31 for training the pre-trained model.

After running stages 1-3, I copied the three lang_char files (train_clean_100_unigram31_units.txt, train_clean_100_unigram31.model and train_clean_100_unigram31.vocab) and then continued with stage 4.
When loading the pre-trained weights, I get the error:
```
RuntimeError: Error(s) in loading state_dict for E2E:
	size mismatch for decoder.embed.0.weight: copying a param with shape torch.Size([33, 256]) from checkpoint, the shape in current model is torch.Size([31, 256]).
	size mismatch for decoder.output_layer.weight: copying a param with shape torch.Size([33, 256]) from checkpoint, the shape in current model is torch.Size([31, 256]).
	size mismatch for decoder.output_layer.bias: copying a param with shape torch.Size([33]) from checkpoint, the shape in current model is torch.Size([31]).
	size mismatch for ctc.ctc_lo.weight: copying a param with shape torch.Size([33, 256]) from checkpoint, the shape in current model is torch.Size([31, 256]).
	size mismatch for ctc.ctc_lo.bias: copying a param with shape torch.Size([33]) from checkpoint, the shape in current model is torch.Size([31]).
# Accounting: time=4 threads=1
```
I understand that two tokens are always added to nBPE: < blank > and < eos >, which makes 33 possible output tokens.
But why is my new model not taking those two in account and generating this mismatch between the pre-trained model and the one I am trying to load the weights on?

**Comment by sw005320** [comment]
Could you share the token list of the two models?

**Comment by chenAsaraf** [comment]
Hi, I am with Daniel.

The token list of the pre-trained model : 
<unk> 1
' 2
A 3
B 4
C 5
D 6
E 7
F 8
G 9
H 10
I 11
J 12
K 13
L 14
M 15
N 16
O 17
P 18
Q 19
R 20
S 21
T 22
U 23
V 24
W 25
X 26
Y 27
Z 28
ZZ 29
THE 31


The token list of the new model :

<unk> 1
' 2
A 3
B 4
C 5
D 6
E 7
F 8
G 9
H 10
I 11
J 12
K 13
L 14
M 15
N 16
O 17
P 18
Q 19
R 20
S 21
T 22
U 23
V 24
W 25
X 26
Y 27
Z 28
THE 30

**Comment by sw005320** [comment]
I see.
Maybe, I do not fully understand it, but does `ZZ 29` cause some issues?

**Comment by chenAsaraf** [comment]
Maybe, I just don't understand why the length of the two lists is different, that's the problem.
Why does it happen even though in both runs I state that "nbpe" = 31?

**Comment by sw005320** [comment]
They will make a list based on the occurrence in the text data.
So, instead of making a new sentencepiece model from the text data in the new dataset, it is better to reuse old one.

**Comment by chenAsaraf** [comment]
So if I understand correctly, if the new data contains less vocabulary - will it produce a shorter token list?
And you suggest not training a new language model at all but using an old one (though it will not know, for example, the words that only appear in the new data set) ?

**Comment by sw005320** [comment]
> So if I understand correctly, if the new data contains less vocabulary - will it produce a shorter token list?

It does not depend on the vocabulary size of the new data.
It depends on the occurrence of the text data in the new data.
But probably, I'm wrong. I did not fully understand what you're doing.
Sorry about it.

> And you suggest not training a new language model at all but using an old one (though it will not know, for example, the words that only appear in the new data set) ?

No.
I recommend you skip the **sentencepiece model** training (`spm_train`) in https://github.com/espnet/espnet/blob/master/egs/librispeech/asr1/run.sh#L157
Instead, you can reuse the sentencepiece model obtained in a pre-trained model.
