### ISSUE TITLE
Self-Conditioned CTC is Malformed for Multi-GPU Training - Can we discuss how to PR a fix?

### ISSUE THREAD

**Issue by brianyan918** [espnet/espnet#4031]
Has anyone been able to run self-conditioned CTC on multiple GPUs? I just tried but I get this error:
```
File "/project/ocean/byan/espnet-accent/tools/anaconda/envs/espnet/lib/python3.8/site-packages/torch/nn/functional.py", line 1753, in linear
    return torch._C._nn.linear(input, weight, bias)
RuntimeError: Expected tensor for 'out' to have the same device as tensor for argument #3 'mat2'; but device 1 does not equal 0 (while checking arguments for addmm)
```

I believe the reason for this is the way that we init the encoder with a pointer to the ctc.softmax: https://github.com/espnet/espnet/blob/12e18b4daeed5bb44852670f3279d572cd367e5a/espnet/nets/pytorch_backend/e2e_asr_conformer.py#L77

This is a bit of an unusual method it seems. I do not see it anywhere else in ESPnet. What happens in this way is that the parameters of ctc_lo will end up being on some incorrect device. Can we think of a different way to make the encoder class have access to the ctc.softmax?

I fixed this locally by passing the ctc.softmax during the forward pass of e2e_asr_transformer instead of during the init.
```
hs_pad, hs_mask, hs_intermediates = self.encoder(xs_pad, src_mask, ctc_softmax=self.ctc.softmax if self.self_conditioning else None)
```

This works fine, but perhaps it's not a good style. @sw005320 @ftshijt or others do you have any suggestions?

**Comment by sw005320** [comment]
Thanks for the report!
I think this sounds reasonable changes to me.
@YosukeHiguchi, @ftshijt, do you have any comments?
