### ISSUE TITLE
TTS inference lacks an option to explicitly use normalized features over denormalized

### ISSUE THREAD

**Issue by G-Thor** [espnet/espnet#4033]
https://github.com/espnet/espnet/blob/12e18b4daeed5bb44852670f3279d572cd367e5a/espnet2/bin/tts_inference.py#L211-L217

When synthesizing speech using an AM which produces both normalized and denormalized output and a vocoder model which expects normalized inputs, I had some trouble getting the Text2Speech inference object to obtain meaningful output.

I noticed upon reviewing the code that the object always prefers denormalized features as vocoder input and accepts no runtime parameters for choosing norm/denorm inputs. Would you consider including a parameter on the Text2Speech object's call method or initalization which would bypass this preference?

**Comment by kan-bayashi** [comment]
Sorry for the late reply. Now we have no such option.
As workaround, we can edit `config.yaml` in the model directory to skip de-normalization.

```
# before
normalize: global_mvn
normalize_conf:
    stats_file: exp/tts_stats_raw_phn_none/train/feats_stats.npz

# after 
normalize: null
normalize_conf: {}
```

It this case, feat_gen_denorm is not created, so feat_gen is pass to the vocoder.

**Comment by kan-bayashi** [comment]
Sorry, the above solution does not work.
I will consider implementing option.

**Comment by G-Thor** [comment]
I've opened a pull request which implements this option. 
The option is an initialization parameter for the espnet2.bin.tts_inference.Text2Speech object
#4250
