### ISSUE TITLE
Questions about streaming ASR tutorial

### ISSUE THREAD

**Issue by Stasiche** [espnet/espnet#4034]
Hello! I have some questions about recognize function in https://github.com/espnet/notebook/blob/master/espnet2_streaming_asr_demo.ipynb

1.  What is 32767.0 in "speech = data.astype(np.float16)/32767.0"?
2. Is there any connection between sim_chunk_length and chunk size in model training process? (because D-Keqi use chunk size 500 [https://huggingface.co/D-Keqi/espnet_asr_train_asr_streaming_transformer_raw_en_bpe500_sp_valid.acc.ave/blob/main/exp/asr_train_asr_streaming_transformer_raw_en_bpe500_sp/config.yaml#L77] during the training but in this notebook it's using 640)

**Comment by sw005320** [comment]
@D-Keqi, can you answer it for me,?

**Comment by D-Keqi** [comment]
> @D-Keqi, can you answer it for me,?

Sure!

**Comment by D-Keqi** [comment]
> Hello! I have some questions about recognize function in https://github.com/espnet/notebook/blob/master/espnet2_streaming_asr_demo.ipynb
> 
> 1. What is 32767.0 in "speech = data.astype(np.float16)/32767.0"?
> 2. Is there any connection between sim_chunk_length and chunk size in model training process? (because D-Keqi use chunk size 500 [https://huggingface.co/D-Keqi/espnet_asr_train_asr_streaming_transformer_raw_en_bpe500_sp_valid.acc.ave/blob/main/exp/asr_train_asr_streaming_transformer_raw_en_bpe500_sp/config.yaml#L77] during the training but in this notebook it's using 640)

Hi! Thanks for your response.
1. For the first question, 32767 is for the normalization of int to float, 36767 is the upper limit of 16-bit binary numbers, and this normalization is a common convention in signal processing techniques.
2. there is no connection between  the sim_chunk_length and chunk size.

**Comment by Stasiche** [comment]
> > Hello! I have some questions about recognize function in https://github.com/espnet/notebook/blob/master/espnet2_streaming_asr_demo.ipynb
> > 
> > 1. What is 32767.0 in "speech = data.astype(np.float16)/32767.0"?
> > 2. Is there any connection between sim_chunk_length and chunk size in model training process? (because D-Keqi use chunk size 500 [https://huggingface.co/D-Keqi/espnet_asr_train_asr_streaming_transformer_raw_en_bpe500_sp_valid.acc.ave/blob/main/exp/asr_train_asr_streaming_transformer_raw_en_bpe500_sp/config.yaml#L77] during the training but in this notebook it's using 640)
> 
> Hi! Thanks for your response.
> 
> 1. For the first question, 32767 is for the normalization of int to float, 36767 is the upper limit of 16-bit binary numbers, and this normalization is a common convention in signal processing techniques.
> 2. there is no connection between  the sim_chunk_length and chunk size.


Thank you!

**Comment by sw005320** [comment]
> For the first question, 32767 is for the normalization of int to float, 36767 is the upper limit of 16-bit binary numbers, and this normalization is a common convention in signal processing techniques.

@D-Keqi, can you add this comment to the notebook?

**Comment by D-Keqi** [comment]
> > For the first question, 32767 is for the normalization of int to float, 36767 is the upper limit of 16-bit binary numbers, and this normalization is a common convention in signal processing techniques.
> 
> @D-Keqi, can you add this comment to the notebook?

of course!
