### ISSUE TITLE
An error occurred while executing the language model under the Aishell dataset

### ISSUE THREAD

**Issue by CrazyTaobean** [espnet/espnet#4040]
![image](https://user-images.githubusercontent.com/37605608/152755823-fc717fb2-5538-4636-880f-82554077ca7e.png)
i don't know how to fix..

**Comment by b-flo** [comment]
Hi,

Could you check #1925, please?

**Comment by CrazyTaobean** [comment]
tks a lot, i just found this issue and i am tring to degrade my chainer version. If this does work i will close this issue.
