### ISSUE TITLE
Original data training in a speech enhancement task

### ISSUE THREAD

**Issue by takashin3391** [espnet/espnet#4045]
Thank you for all your help and support.
I want to train with original data in a speech enhancement task, but the samples in the egs2 folder use a specific dataset (WHAM!, WSJ1, etc.).

Let me ask you a few questions.
 How can I train on the original data?
 Is there a procedure manual?

**Comment by Emrys365** [comment]
Hi @takashin3391, there is documentation for creating a new speech enhancement recipe here: https://github.com/espnet/espnet/blob/master/egs2/TEMPLATE/enh1/README.md#instructions-on-creating-a-new-recipe

To be brief, if you want to use your own data for training, the main effort you need is the preparation of stage 1 in [enh.sh](https://github.com/espnet/espnet/blob/master/egs2/TEMPLATE/enh1/enh.sh#L253-L257), which should generate some necessary files in the directory `egs2/<your_recipe_name>/enh1/data/<dataset_name>`.

> For example, if the names of the training, development and evaluation sets are `train`, `dev`, and `eval` respectively, you should create three subset folders `train/`, `dev/` and `eval/` under `egs2/<your_recipe_name>/enh1/data/`. In each subset folder, the following files need to be generated (either manually or by a script):
> ```bash
> wav.scp      (input noisy signal)
>
> spk1.scp     (corresponding clean signals)
>
> utt2spk      (mapping from utt ids to speaker ids)
>
> spk2utt      (generated by running `utils/utt2spk_to_spk2utt.pl /path/to/utt2spk > /path/to/spk2utt`)
> ```
>
> If the noise signal is available, you can also create a `noise1.scp` file in each subset folder, containing the path to the corresponding noise audio file in each line.

**Comment by takashin3391** [comment]
Thank you for your prompt reply.
I now understand how to learn with the original data.
Thank you very much for your help.

**Comment by takashin3391** [comment]
Hi @Emrys365,
Sorry for the repeated questions.

I tried to do the original data training based on your post, but I couldn't figure out what to put in the files.
For example, in the following folder structure, how should I describe the contents of the files (wav.scp, spk1.scp, utt2spk, spk2utt)?


egs2/<my_recipe_name>/enh1/data/<dataset_name>
├── ref   (clean speech references directory)
 │　    ├── ref1.wav
 │ 　   ├── ref2.wav
 │    　├── ref3.wav
 │    　└── ref4.wav
└── mix   (noisy speech directory)
   　　      ├── mix1.wav
 　 　       ├── mix2.wav
  　   　    ├── mix3.wav
 　      　  └── mix4.wav

**Comment by simpleoier** [comment]
Hi @takashin3391 . I assume you are already familiar with the Kaldi style data structure.
In `wav.scp`, the format looks like this
```
utt_name1 data/<dataset_name>/mix/mix1.wav
utt_name2 data/<dataset_name>/mix/mix2.wav
...
```

In `spk1.scp`, the format looks like this
```
utt_name1 data/<dataset_name>/ref/ref1.wav
utt_name2 data/<dataset_name>/ref/ref2.wav
...
```

In `utt2spk`, the format looks like this
```
utt_name1 speaker_id1
utt_name2 speaker_id2
...
```

Finally, you can just use `egs2/<my_recipe_name>/enh1/utils/utt2spk_to_spk2utt.pl <utt2spk_file>  > <spk2utt_file> `

**Comment by Emrys365** [comment]
In addition to Xuankai's reply, I would like to add that if you do not know the speaker identity of each utterance, then you can construct a simple `utt2spk` file by using the utterance ID as the speaker ID:
```bash
awk '{print $1, $1}' /path/to/wav.scp > /path/to/utt2spk
```

**Comment by takashin3391** [comment]
@simpleoier @Emrys365 
Thank you for your answers.
Thanks to your help, I was able to create 4 files (wav.scp, spk1.scp, utt2spk, spk2utt).
However, the symbolic link of `egs2/<my_recipe_name>/enh1/utils` is broken, so I got the following error in enh.sh
(So I made my own spk2utt_file)

> . /enh.sh: line 187: utils/parse_options.sh: No such file or directory

Where should I link `egs2/<my_recipe_name>/enh1/utils`?
Currently, `egs2/<my_recipe_name>/enh1/utils` is linked to `../../../tools/kaldi/egs/wsj/s5/utils`, but there is no such directory.

**Comment by Emrys365** [comment]
> @simpleoier @Emrys365 
> Thank you for your answers.
> Thanks to your help, I was able to create 4 files (wav.scp, spk1.scp, utt2spk, spk2utt).
> However, the symbolic link of `egs2/<my_recipe_name>/enh1/utils` is broken, so I got the following error in enh.sh
> (So I made my own spk2utt_file)
> 
> > . /enh.sh: line 187: utils/parse_options.sh: No such file or directory
> 
> Where should I link `egs2/<my_recipe_name>/enh1/utils`?
> Currently, `egs2/<my_recipe_name>/enh1/utils` is linked to `../../../tools/kaldi/egs/wsj/s5/utils`, but there is no such directory.

Have you installed espnet from source by following the scripts under `<espnet_root>/tools/`? After that, the above directory should be created.

You could refer to https://espnet.github.io/espnet/installation.html for detailed instructions.

**Comment by takashin3391** [comment]
@Emrys365 
Sorry for the basic mistake.
I have installed espnet. The symbolic link problem has been solved.

However, I tried to prepare `local/data.sh` by referring to `egs2/wsj0_2mix/enh1/local/data.sh`, but I don't know how to write it.
What do I need to put in `local/data.sh`?
I tried to write data.sh as follows.
> \#!/usr/bin/env bash
> 
> \# Copyright 2020  Shanghai Jiao Tong University (Authors: Chenda Li, Wangyou Zhang)
> \# Apache 2.0
> set -e
> set -u
> set -o pipefail
> 
> log() {
>     local fname=${BASH_SOURCE[1]##*/}
>     echo -e "$(date '+%Y-%m-%dT%H:%M:%S') (${fname}:${BASH_LINENO[0]}:${FUNCNAME[1]}) $*"
> }
> 
> . ./db.sh
> 
> . utils/parse_options.sh
> 
> train_set=train
> train_dev=dev
> recog_set=eval

However, I got an error message.
> 2022-02-25T10:53:44 (enh.sh:184:main) ./enh.sh --lang en --train_set train --valid_set dev --test_sets eval --fs 16k --ngpu 1 --spk_num 1 --local_data_opts  --enh_config ./conf/train.yaml --use_dereverb_ref false --use_noise_ref true --max_wav_duration 30
2022-02-25T10:53:44 (enh.sh:254:main) Stage 1: Data preparation for data/train, data/dev, etc.
2022-02-25T10:53:44 (enh.sh:279:main) Skip stage 2: Speed perturbation
2022-02-25T10:53:44 (enh.sh:289:main) Stage 3: Format wav.scp: data/ -> dump/raw
utils/copy_data_dir.sh: copied data from data/train to dump/raw/org/train
utils/validate_data_dir.sh: Successfully validated data-directory dump/raw/org/train
2022-02-25T10:53:44 (format_wav_scp.sh:42:main) scripts/audio/format_wav_scp.sh --nj 32 --cmd run.pl --out-filename spk1.scp --audio-format flac --fs 16k data/train/spk1.scp dump/raw/org/train dump/raw/org/train/logs/spk1 dump/raw/org/train/data/spk1
2022-02-25T10:53:44 (format_wav_scp.sh:110:main) [info]: without segments
run.pl: 8 / 8 failed, log is in dump/raw/org/train/logs/spk1/format_wav_scp.*.log

**Comment by Emrys365** [comment]
Since you've already prepared the subsets directories, you could simply skip stage 1.

For the format_wav_scp error, it seems to be due to the relative path of wav files. Could you try replacing the paths in wav.scp and spk*.scp with absolute paths?

**Comment by takashin3391** [comment]
@Emrys365 
Thank you for your answer. Thanks to your help, I have reached Stage 6.
However, I got a RuntimeError and KeyError in Stage 6. The following log was displayed.
Is there any other information I need in order to determine the cause?

> 2022-02-25T16:26:32 (enh.sh:509:main) Stage 6: Enhancemnt Frontend Training: train_set=dump/raw/train, valid_set=dump/raw/dev
> 2022-02-25T16:26:32 (enh.sh:564:main) Generate 'exp/enh_train_raw/run.sh'. You can resume the process from stage 6 using this script
> 2022-02-25T16:26:32 (enh.sh:567:main) enh training started... log: 'exp/enh_train_raw/train.log'
> 2022-02-25 16:26:32,938 (launch:95) INFO: /root/espnet/tools/anaconda/envs/espnet/bin/python3 /root/espnet/espnet2/bin/launch.py --cmd 'run.pl --name exp/enh_train_raw/train.log' --log exp/enh_train_raw/train.log --ngpu 1 --num_nodes 1 --init_file_prefix exp/enh_train_raw/.dist_init_ --multiprocessing_distributed true -- python3 -m espnet2.bin.enh_train --train_data_path_and_name_and_type dump/raw/train/wav.scp,speech_mix,sound --train_data_path_and_name_and_type dump/raw/train/spk1.scp,speech_ref1,sound --train_data_path_and_name_and_type dump/raw/train/noise1.scp,noise_ref1,sound --valid_data_path_and_name_and_type dump/raw/dev/wav.scp,speech_mix,sound --valid_data_path_and_name_and_type dump/raw/dev/spk1.scp,speech_ref1,sound --valid_data_path_and_name_and_type dump/raw/dev/noise1.scp,noise_ref1,sound --train_shape_file exp/enh_stats_16k/train/speech_mix_shape --train_shape_file exp/enh_stats_16k/train/speech_ref1_shape --train_shape_file exp/enh_stats_16k/train/noise_ref1_shape --valid_shape_file exp/enh_stats_16k/valid/speech_mix_shape --valid_shape_file exp/enh_stats_16k/valid/speech_ref1_shape --valid_shape_file exp/enh_stats_16k/valid/noise_ref1_shape --fold_length 80000 --fold_length 80000 --fold_length 80000 --resume true --output_dir exp/enh_train_raw --config ./conf/train.yaml
> 2022-02-25 16:26:32,954 (launch:349) INFO: log file: exp/enh_train_raw/train.log
> run.pl: job failed, log is in exp/enh_train_raw/train.log
> Command '['run.pl', '--name', 'exp/enh_train_raw/train.log', '--gpu', '1', 'exp/enh_train_raw/train.log', 'python3', '-m', 'espnet2.bin.enh_train', '--train_data_path_and_name_and_type', 'dump/raw/train/wav.scp,speech_mix,sound', '--train_data_path_and_name_and_type', 'dump/raw/train/spk1.scp,speech_ref1,sound', '--train_data_path_and_name_and_type', 'dump/raw/train/noise1.scp,noise_ref1,sound', '--valid_data_path_and_name_and_type', 'dump/raw/dev/wav.scp,speech_mix,sound', '--valid_data_path_and_name_and_type', 'dump/raw/dev/spk1.scp,speech_ref1,sound', '--valid_data_path_and_name_and_type', 'dump/raw/dev/noise1.scp,noise_ref1,sound', '--train_shape_file', 'exp/enh_stats_16k/train/speech_mix_shape', '--train_shape_file', 'exp/enh_stats_16k/train/speech_ref1_shape', '--train_shape_file', 'exp/enh_stats_16k/train/noise_ref1_shape', '--valid_shape_file', 'exp/enh_stats_16k/valid/speech_mix_shape', '--valid_shape_file', 'exp/enh_stats_16k/valid/speech_ref1_shape', '--valid_shape_file', 'exp/enh_stats_16k/valid/noise_ref1_shape', '--fold_length', '80000', '--fold_length', '80000', '--fold_length', '80000', '--resume', 'true', '--output_dir', 'exp/enh_train_raw', '--config', './conf/train.yaml', '--ngpu', '1', '--multiprocessing_distributed', 'True']' returned non-zero exit status 1.
> Traceback (most recent call last):
>   File "/root/espnet/tools/anaconda/envs/espnet/lib/python3.8/runpy.py", line 194, in _run_module_as_main
>     return _run_code(code, main_globals, None,
>   File "/root/espnet/tools/anaconda/envs/espnet/lib/python3.8/runpy.py", line 87, in _run_code
>     exec(code, run_globals)
>   File "/root/espnet/espnet2/bin/launch.py", line 385, in <module>
>     main()
>   File "/root/espnet/espnet2/bin/launch.py", line 376, in main
>     raise RuntimeError(
> RuntimeError: 
> \################### The last 1000 lines of exp/enh_train_raw/train.log ###################
> \# python3 -m espnet2.bin.enh_train --train_data_path_and_name_and_type dump/raw/train/wav.scp,speech_mix,sound --train_data_path_and_name_and_type dump/raw/train/spk1.scp,speech_ref1,sound --train_data_path_and_name_and_type dump/raw/train/noise1.scp,noise_ref1,sound --valid_data_path_and_name_and_type dump/raw/dev/wav.scp,speech_mix,sound --valid_data_path_and_name_and_type dump/raw/dev/spk1.scp,speech_ref1,sound --valid_data_path_and_name_and_type dump/raw/dev/noise1.scp,noise_ref1,sound --train_shape_file exp/enh_stats_16k/train/speech_mix_shape --train_shape_file exp/enh_stats_16k/train/speech_ref1_shape --train_shape_file exp/enh_stats_16k/train/noise_ref1_shape --valid_shape_file exp/enh_stats_16k/valid/speech_mix_shape --valid_shape_file exp/enh_stats_16k/valid/speech_ref1_shape --valid_shape_file exp/enh_stats_16k/valid/noise_ref1_shape --fold_length 80000 --fold_length 80000 --fold_length 80000 --resume true --output_dir exp/enh_train_raw --config ./conf/train.yaml --ngpu 1 --multiprocessing_distributed True 
> \# Started at Fri Feb 25 16:26:32 UTC 2022
> \#
> /root/espnet/tools/anaconda/envs/espnet/bin/python3 /root/espnet/espnet2/bin/enh_train.py --train_data_path_and_name_and_type dump/raw/train/wav.scp,speech_mix,sound --train_data_path_and_name_and_type dump/raw/train/spk1.scp,speech_ref1,sound --train_data_path_and_name_and_type dump/raw/train/noise1.scp,noise_ref1,sound --valid_data_path_and_name_and_type dump/raw/dev/wav.scp,speech_mix,sound --valid_data_path_and_name_and_type dump/raw/dev/spk1.scp,speech_ref1,sound --valid_data_path_and_name_and_type dump/raw/dev/noise1.scp,noise_ref1,sound --train_shape_file exp/enh_stats_16k/train/speech_mix_shape --train_shape_file exp/enh_stats_16k/train/speech_ref1_shape --train_shape_file exp/enh_stats_16k/train/noise_ref1_shape --valid_shape_file exp/enh_stats_16k/valid/speech_mix_shape --valid_shape_file exp/enh_stats_16k/valid/speech_ref1_shape --valid_shape_file exp/enh_stats_16k/valid/noise_ref1_shape --fold_length 80000 --fold_length 80000 --fold_length 80000 --resume true --output_dir exp/enh_train_raw --config ./conf/train.yaml --ngpu 1 --multiprocessing_distributed True
> [c3842a7195a7] 2022-02-25 16:26:35,942 (abs_task:1157) INFO: pytorch.version=1.10.1, cuda.available=True, cudnn.version=8005, cudnn.benchmark=False, cudnn.deterministic=True
> [c3842a7195a7] 2022-02-25 16:26:35,943 (abs_task:1158) INFO: Model structure:
> ESPnetEnhancementModel(
>   (encoder): STFTEncoder(
>     (stft): Stft(n_fft=512, win_length=512, hop_length=128, center=True, normalized=False, onesided=True)
>   )
>   (separator): DPRNNSeparator(
>     (dprnn): DPRNN(
>       (row_rnn): ModuleList(
>         (0): SingleRNN(
>           (rnn): LSTM(257, 256, batch_first=True, bidirectional=True)
>           (dropout): Dropout(p=0.1, inplace=False)
>           (proj): Linear(in_features=512, out_features=257, bias=True)
>         )
>         (1): SingleRNN(
>           (rnn): LSTM(257, 256, batch_first=True, bidirectional=True)
>           (dropout): Dropout(p=0.1, inplace=False)
>           (proj): Linear(in_features=512, out_features=257, bias=True)
>         )
>         (2): SingleRNN(
>           (rnn): LSTM(257, 256, batch_first=True, bidirectional=True)
>           (dropout): Dropout(p=0.1, inplace=False)
>           (proj): Linear(in_features=512, out_features=257, bias=True)
>         )
>         (3): SingleRNN(
>           (rnn): LSTM(257, 256, batch_first=True, bidirectional=True)
>           (dropout): Dropout(p=0.1, inplace=False)
>           (proj): Linear(in_features=512, out_features=257, bias=True)
>         )
>       )
>       (col_rnn): ModuleList(
>         (0): SingleRNN(
>           (rnn): LSTM(257, 256, batch_first=True, bidirectional=True)
>           (dropout): Dropout(p=0.1, inplace=False)
>           (proj): Linear(in_features=512, out_features=257, bias=True)
>         )
>         (1): SingleRNN(
>           (rnn): LSTM(257, 256, batch_first=True, bidirectional=True)
>           (dropout): Dropout(p=0.1, inplace=False)
>           (proj): Linear(in_features=512, out_features=257, bias=True)
>         )
>         (2): SingleRNN(
>           (rnn): LSTM(257, 256, batch_first=True, bidirectional=True)
>           (dropout): Dropout(p=0.1, inplace=False)
>           (proj): Linear(in_features=512, out_features=257, bias=True)
>         )
>         (3): SingleRNN(
>           (rnn): LSTM(257, 256, batch_first=True, bidirectional=True)
>           (dropout): Dropout(p=0.1, inplace=False)
>           (proj): Linear(in_features=512, out_features=257, bias=True)
>         )
>       )
>       (row_norm): ModuleList(
>         (0): GroupNorm(1, 257, eps=1e-08, affine=True)
>         (1): GroupNorm(1, 257, eps=1e-08, affine=True)
>         (2): GroupNorm(1, 257, eps=1e-08, affine=True)
>         (3): GroupNorm(1, 257, eps=1e-08, affine=True)
>       )
>       (col_norm): ModuleList(
>         (0): GroupNorm(1, 257, eps=1e-08, affine=True)
>         (1): GroupNorm(1, 257, eps=1e-08, affine=True)
>         (2): GroupNorm(1, 257, eps=1e-08, affine=True)
>         (3): GroupNorm(1, 257, eps=1e-08, affine=True)
>       )
>       (output): Sequential(
>         (0): PReLU(num_parameters=1)
>         (1): Conv2d(257, 514, kernel_size=(1, 1), stride=(1, 1))
>       )
>     )
>     (nonlinear): ReLU()
>   )
>   (decoder): STFTDecoder(
>     (stft): Stft(n_fft=512, win_length=512, hop_length=128, center=True, normalized=False, onesided=True)
>   )
> )
> 
> Model summary:
>     Class Name: ESPnetEnhancementModel
>     Total Number of model parameters: 9.63 M
>     Number of trainable parameters: 9.63 M (100.0%)
>     Size: 38.52 MB
>     Type: torch.float32
> [c3842a7195a7] 2022-02-25 16:26:35,943 (abs_task:1161) INFO: Optimizer:
> Adam (
> Parameter Group 0
>     amsgrad: False
>     betas: (0.9, 0.999)
>     eps: 1e-08
>     lr: 0.001
>     weight_decay: 0
> )
> [c3842a7195a7] 2022-02-25 16:26:35,943 (abs_task:1162) INFO: Scheduler: <torch.optim.lr_scheduler.ReduceLROnPlateau object at 0x7efe9953af10>
> [c3842a7195a7] 2022-02-25 16:26:35,943 (abs_task:1171) INFO: Saving the configuration in exp/enh_train_raw/config.yaml
> [c3842a7195a7] 2022-02-25 16:26:36,033 (abs_task:1525) INFO: [train] dataset:
> ESPnetDataset(
>   speech_mix: {"path": "dump/raw/train/wav.scp", "type": "sound"}
>   speech_ref1: {"path": "dump/raw/train/spk1.scp", "type": "sound"}
>   noise_ref1: {"path": "dump/raw/train/noise1.scp", "type": "sound"}
>   preprocess: None)
> [c3842a7195a7] 2022-02-25 16:26:36,033 (abs_task:1526) INFO: [train] Batch sampler: FoldedBatchSampler(N-batch=4, batch_size=2, shape_files=['exp/enh_stats_16k/train/speech_mix_shape', 'exp/enh_stats_16k/train/speech_ref1_shape', 'exp/enh_stats_16k/train/noise_ref1_shape'], sort_in_batch=descending, sort_batch=descending)
> [c3842a7195a7] 2022-02-25 16:26:36,033 (abs_task:1527) INFO: [train] mini-batch sizes summary: N-batch=4, mean=2.0, min=2, max=2
> [c3842a7195a7] 2022-02-25 16:26:36,041 (abs_task:1525) INFO: [valid] dataset:
> ESPnetDataset(
>   speech_mix: {"path": "dump/raw/dev/wav.scp", "type": "sound"}
>   speech_ref1: {"path": "dump/raw/dev/spk1.scp", "type": "sound"}
>   noise_ref1: {"path": "dump/raw/dev/noise1.scp", "type": "sound"}
>   preprocess: None)
> [c3842a7195a7] 2022-02-25 16:26:36,041 (abs_task:1526) INFO: [valid] Batch sampler: FoldedBatchSampler(N-batch=4, batch_size=2, shape_files=['exp/enh_stats_16k/valid/speech_mix_shape', 'exp/enh_stats_16k/valid/speech_ref1_shape', 'exp/enh_stats_16k/valid/noise_ref1_shape'], sort_in_batch=descending, sort_batch=descending)
> [c3842a7195a7] 2022-02-25 16:26:36,041 (abs_task:1527) INFO: [valid] mini-batch sizes summary: N-batch=4, mean=2.0, min=2, max=2
> [c3842a7195a7] 2022-02-25 16:26:36,049 (abs_task:1525) INFO: [plot_att] dataset:
> ESPnetDataset(
>   speech_mix: {"path": "dump/raw/dev/wav.scp", "type": "sound"}
>   speech_ref1: {"path": "dump/raw/dev/spk1.scp", "type": "sound"}
>   noise_ref1: {"path": "dump/raw/dev/noise1.scp", "type": "sound"}
>   preprocess: None)
> [c3842a7195a7] 2022-02-25 16:26:36,049 (abs_task:1526) INFO: [plot_att] Batch sampler: UnsortedBatchSampler(N-batch=8, batch_size=1, key_file=exp/enh_stats_16k/valid/speech_mix_shape, 
> [c3842a7195a7] 2022-02-25 16:26:36,049 (abs_task:1527) INFO: [plot_att] mini-batch sizes summary: N-batch=3, mean=1.0, min=1, max=1
> [c3842a7195a7] 2022-02-25 16:26:36,099 (trainer:280) INFO: 1/100epoch started
> Traceback (most recent call last):
>   File "/root/espnet/tools/anaconda/envs/espnet/lib/python3.8/runpy.py", line 194, in _run_module_as_main
>     return _run_code(code, main_globals, None,
>   File "/root/espnet/tools/anaconda/envs/espnet/lib/python3.8/runpy.py", line 87, in _run_code
>     exec(code, run_globals)
>   File "/root/espnet/espnet2/bin/enh_train.py", line 23, in <module>
>     main()
>   File "/root/espnet/espnet2/bin/enh_train.py", line 19, in main
>     EnhancementTask.main(cmd=cmd)
>   File "/root/espnet/espnet2/tasks/abs_task.py", line 1019, in main
>     cls.main_worker(args)
>   File "/root/espnet/espnet2/tasks/abs_task.py", line 1315, in main_worker
>     cls.trainer.run(
>   File "/root/espnet/espnet2/train/trainer.py", line 286, in run
>     all_steps_are_invalid = cls.train_one_epoch(
>   File "/root/espnet/espnet2/train/trainer.py", line 522, in train_one_epoch
>     retval = model(**batch)
>   File "/root/espnet/tools/anaconda/envs/espnet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
>     return forward_call(*input, **kwargs)
>   File "/root/espnet/espnet2/enh/espnet_model.py", line 82, in forward
>     speech_ref = [
>   File "/root/espnet/espnet2/enh/espnet_model.py", line 83, in <listcomp>
>     kwargs["speech_ref{}".format(spk + 1)] for spk in range(self.num_spk)
> KeyError: 'speech_ref2'
> \# Accounting: time=4 threads=1
> \# Ended (code 1) at Fri Feb 25 16:26:36 UTC 2022, elapsed time 4 seconds

**Comment by Emrys365** [comment]
It looks like your model expects `num_spk=2` while your data only has one speaker.
Did you modify the value of `num_spk` in the model configuration file, i.e., `conf/train.yaml` in your case?

**Comment by takashin3391** [comment]
@Emrys365 
Thank you for all your help. And sorry for the repeated questions.

I changed the `num_spk` in `conf/train.yaml` to 1 and was able to proceed to stage 7. Thank you very much.
However, unfortunately, I am getting the following error

> 2022-02-26T00:07:47 (enh.sh:601:main) Stage 7: Enhance Speech: training_dir=exp/enh_train_raw
2022-02-26T00:07:47 (enh.sh:611:main) Generate 'exp/enh_train_raw/run_enhance.sh'. You can resume the process from stage 7 using this script
2022-02-26T00:07:47 (enh.sh:640:main) Enhancement started... log: 'exp/enh_train_raw/enhanced_dev/logdir/enh_inference.*.log'
run.pl: 8 / 8 failed, log is in exp/enh_train_raw/enhanced_dev/logdir/enh_inference.*.log

The following log was left in the `exp/enh_train_raw/enhanced_dev/logdir/enh_inference.8.log`.
> \# python3 -m espnet2.bin.enh_inference --ngpu 0 --fs 16k --data_path_and_name_and_type dump/raw/dev/wav.scp,speech_mix,sound --key_file exp/enh_train_raw/enhanced_dev/logdir/keys.8.scp --train_config exp/enh_train_raw/config.yaml --model_file exp/enh_train_raw/valid.si_snr.ave.pth --output_dir exp/enh_train_raw/enhanced_dev/logdir/output.8 --normalize_output_wav true 
> \# Started at Sat Feb 26 00:07:47 UTC 2022
> \#
> /root/espnet/tools/anaconda/envs/espnet/bin/python3 /root/espnet/espnet2/bin/enh_inference.py --ngpu 0 --fs 16k --data_path_and_name_and_type dump/raw/dev/wav.scp,speech_mix,sound --key_file exp/enh_train_raw/enhanced_dev/logdir/keys.8.scp --train_config exp/enh_train_raw/config.yaml --model_file exp/enh_train_raw/valid.si_snr.ave.pth --output_dir exp/enh_train_raw/enhanced_dev/logdir/output.8 --normalize_output_wav true
> Traceback (most recent call last):
>   File "/root/espnet/tools/anaconda/envs/espnet/lib/python3.8/runpy.py", line 194, in _run_module_as_main
>     return _run_code(code, main_globals, None,
>   File "/root/espnet/tools/anaconda/envs/espnet/lib/python3.8/runpy.py", line 87, in _run_code
>     exec(code, run_globals)
>   File "/root/espnet/espnet2/bin/enh_inference.py", line 523, in <module>
>     main()
>   File "/root/espnet/espnet2/bin/enh_inference.py", line 519, in main
>     inference(**kwargs)
>   File "/root/espnet/espnet2/bin/enh_inference.py", line 348, in inference
>     separate_speech = SeparateSpeech.from_pretrained(
>   File "/root/espnet/espnet2/bin/enh_inference.py", line 285, in from_pretrained
>     return SeparateSpeech(**kwargs)
>   File "/root/espnet/espnet2/bin/enh_inference.py", line 64, in __init__
>     enh_model, enh_train_args = EnhancementTask.build_model_from_file(
>   File "/root/espnet/espnet2/tasks/abs_task.py", line 1832, in build_model_from_file
>     model.load_state_dict(torch.load(model_file, map_location=device))
>   File "/root/espnet/tools/anaconda/envs/espnet/lib/python3.8/site-packages/torch/serialization.py", line 594, in load
>     with _open_file_like(f, 'rb') as opened_file:
>   File "/root/espnet/tools/anaconda/envs/espnet/lib/python3.8/site-packages/torch/serialization.py", line 230, in _open_file_like
>     return _open_file(name_or_buffer, mode)
>   File "/root/espnet/tools/anaconda/envs/espnet/lib/python3.8/site-packages/torch/serialization.py", line 211, in __init__
>     super(_open_file, self).__init__(open(name, mode))
> FileNotFoundError: [Errno 2] No such file or directory: 'exp/enh_train_raw/valid.si_snr.ave.pth'
> \# Accounting: time=2 threads=1
> \# Ended (code 1) at Sat Feb 26 00:07:49 UTC 2022, elapsed time 2 seconds

**Comment by Emrys365** [comment]
If `exp/enh_train_raw/valid.si_snr.ave.pth` does not exist, you could simply replace it with someother existing checkpoints, such as `exp/enh_train_raw/valid.loss.best.pth`.

This is specified by passing the argument `--inference_model` to `enh.sh`, which is by default `valid.si_snr.ave.pth` as defined in [egs2/<recipe_name>/enh1/enh.sh#L75](https://github.com/espnet/espnet/blob/master/egs2/TEMPLATE/enh1/enh.sh#L75)

**Comment by takashin3391** [comment]
@Emrys365 
Thank you very much for your support.
Thanks to you, I successfully completed all the stages.

I would like to ask an additional question.
1. Why was valid.si_snr.ave.pth not generated? Is this due to having too little data? The number of data I used is 8 files.
Also, the training stopped at 13 epochs.

2. When I checked the loss.png, I saw that the loss was gradually increasing.
Is this due to the small number of files I used for training?
We plan to use about 10000 files for the actual training.

**Comment by Emrys365** [comment]
> 1. Why was valid.si_snr.ave.pth not generated? Is this due to having too little data? The number of data I used is 8 files.
> Also, the training stopped at 13 epochs.

It depends on your model config. If your config file contains the following lines (like in [egs2/wsj0_2mix/enh1/conf/tuning/train_enh_rnn_tf.yaml#L15-L21](https://github.com/espnet/espnet/blob/master/egs2/wsj0_2mix/enh1/conf/tuning/train_enh_rnn_tf.yaml#L15-L21)):
```yaml
best_model_criterion:
-   - valid
    - si_snr
    - max
-   - valid
    - loss
    - min
```
it will generate both `valid.si_snr.best.pth` and `valid.loss.best.pth` after each epoch.
And after the training is finished, both `valid.si_snr.ave.pth` and `valid.loss.ave.pth` should be generated.
To understand how the argument `best_model_criterion` works, you could search `best_model_criterion` in [espnet2/train/trainer.py](https://github.com/espnet/espnet/blob/master/espnet2/train/trainer.py).


> 2. When I checked the loss.png, I saw that the loss was gradually increasing.
> Is this due to the small number of files I used for training?
> We plan to use about 10000 files for the actual training.

Do both training and validation losses increase or only the validation loss increase? Only 8 utterance-level audio files are apparently not enough for training a generalizable model. I think 10000 audios should be enough for training a reasonably working model.

**Comment by takashin3391** [comment]
The train.yaml has the following settings.

```
best_model_criterion:
-   - valid
    - si_snr
    - max
-   - valid
    - loss
    - min
```

However, `valid.si_snr.best.pth` and `valid.loss.best.pth` are not generated.
The learning and validation losses increase.
I think these are caused by having too few files.

I can now train with the original data. Thank you very much for your help.
