### ISSUE TITLE
Question about positionwise/feedforward layers

### ISSUE THREAD

**Issue by danpovey** [espnet/espnet#4048]
This is just a question,

I noticed you guys have "positionwise" layers in place of the conventional feedforward layers in conformers, where you replace the Linear with a Conv1d that has typically kernel size 3.  This looks like it would nearly double the number of parameters in the model.   Does it give a significant WER improvement for ASR tasks, and would this still be true if you were to keep the number of parameters constant, for instance by halving the positionwise/feedforward dim?

**Comment by pengchengguo** [comment]
Sorry @danpovey, I am not fully getting your question. I don't remember which block contains a Conv1d with kernel size 3. For the performance of keeping the number of parameters almost constant with Transformer (halving the dim of positoinwise layer), we have only investigated in speech translation task, following are the results.

<img width="600" alt="image" src="https://user-images.githubusercontent.com/23135280/153379929-3085bb5e-3884-444f-be50-3abb0589fdc4.png">

After halving the dim of positionwise layer (conformer-small), the model still outperforms Transformer model. I think the additional convolutional block in Conformer model indeed captures the local dependencies of speech and give some improvement.

**Comment by danpovey** [comment]
Oh, I see now that the positionwise_layer_type defaults to "linear" which does not actually do convolution.
