### ISSUE TITLE
How to change the architecture to bi-encoder-decoder on ASR Task in ESPnet2

### ISSUE THREAD

**Issue by lin-nerd** [espnet/espnet#4050]
Hello everyone, I want to develop a dual encoder-decoder architecture for ASR tasks.
I would like to ask where should I start?
In the espnet_model, the Encoder and Decoder only import AbsEncoder,  AbsDecoder.
What does Abs mean?

**Comment by MaGuodong0712** [comment]
The second question. Intuitively, it may denote the absolute position
encoding (PE). You can check the PE code of Encoder/Decoder.

lin-nerd ***@***.***> 于2022年2月10日周四 09:48写道：

**Comment by lin-nerd** [comment]
> The second question. Intuitively, it may denote the absolute position encoding (PE). You can check the PE code of Encoder/Decoder. lin-nerd ***@***.***> 于2022年2月10日周四 09:48写道：
> […](#)

Thanks for your reply.
I got it.
