### ISSUE TITLE
How to make inference with gen_tts_model?

### ISSUE THREAD

**Issue by adsf0078** [espnet/espnet#4051]
Dear

Thank you for your good work!
Currently, I am training speaker models using the joint text2wav training method from scratch with your Fastspeech2 + HiFiGan config.
Now, I want to make inference with these models generated during the training course but I am a littel bit confused.
In the saparately trained model, we used espnet2.bin.tts_inference which calls Text2Speech class.
However, in the gan_tts model, I can't find the corresponding inferece module and it seems that the gan_tts version of Text2Speech class is needed.
How can I make inference with the gan_tts model?

Your sincerely

**Comment by kan-bayashi** [comment]
You can use the same `Text2Speech` for `gan_tts`, which is compatible for both `tts` and `gan_tts`.
https://github.com/espnet/espnet/tree/master/egs2/TEMPLATE/tts1#how-to-use-trained-model-in-python

**Comment by adsf0078** [comment]
> You can use the same `Text2Speech` for `gan_tts`, which is compatible for both `tts` and `gan_tts`. https://github.com/espnet/espnet/tree/master/egs2/TEMPLATE/tts1#how-to-use-trained-model-in-python

Thank you, I got it.
