### ISSUE TITLE
RNNT beam search unit test

### ISSUE THREAD

**Issue by sw005320** [espnet/espnet#4059]
**Describe the bug**
RNNT beam search unit test is often failed, e.g., https://github.com/espnet/espnet/runs/5142345933?check_suite_focus=true#step:8:397

**Basic environments:**
 - randomly happens in a CI test
 
It is an important unit test and we do not have to change it.
Instead, I think it is better to increase the time larger than 2.0 seconds.

**Comment by b-flo** [comment]
We need to add some real tests for beam search algorithms. Right now, we test the whole pipeline with a random model, and some parts are not reached or can behave differently depending on the run (like here).
It's on my TODO list for ESPnet2 new version, I'll add equivalent tests for ESPnet1 in a separated PR.

**Comment by b-flo** [comment]
> This is an urgent issue as we need to re-run CI frequently due to this.
> So, I want to have a very quick fix by just increasing the time.

This is surprising, it wasn't an issue previously. Do you know when the issue began?
I updated the tests to improve coverage and increased some values (batchsize, dimension, etc), it could be the cause but it was several months ago (october-november IIRC).

**Comment by kan-bayashi** [comment]
> This is surprising, it wasn't an issue previously. Do you know when the issue began?

I'm not sure but sometimes the containers in github ci are slower than usual, maybe it depends on the time or resource allocation in GIthub.

Made the execution time longer in #4072.
