### ISSUE TITLE
Quantization development plan

### ISSUE THREAD

**Issue by miziworld** [espnet/espnet#4063]
Hello,

I'm using espnet ASR recipe very well and I've asked many times for quantization, which is an essential function for me.
As a result of searching, it seems that only dynamic quantization is supported in espnet1.
However, in order to further improve performance, it seems beneficial to introduce QAT using static quantization and fake quantization. I know that this option is not yet at the top of the developers' priorities, but is there any code or content developed by espnet among developers?
Also, if I want to implement these functions, what part of the training code should I modify?
And Is it impossible to change the training dtype in espnet1 now?

**Comment by sw005320** [comment]
Thanks for your suggestion.
We will discuss it internally.

**Comment by miziworld** [comment]
Thank you.
I look forward to the rapid development plan.
