### ISSUE TITLE
Mispronunciation of specific words in TTS

### ISSUE THREAD

**Issue by gafsd** [espnet/espnet#4068]
Hello,

I still have issue with pronunciation of oil. Tried a few different configuraitons but they all have issue pronounce "oil" (either become very quiet or don't even attempt to pronounce at all)
Also I wondered if it's possible to get an index for each word in the output wav? For example is there a mapping for the third input word into an output timestamp when it starts to pronounce third word?

**Comment by kan-bayashi** [comment]
> I still have issue with pronunciation of oil.
I'm not sure but I pick up some points:
- Did you check g2p outputs that corresponds to the word? Is it correct?
- Does the word in included in the training data? Is it correctly pronunciated?

> For example is there a mapping for the third input word into an output timestamp when it starts to pronounce third word?

If you use taco2 / fastspeech 1 2 / vits, you can calculate mapping between input and outputs from `durations` file, which is calculated from attention weight or duration predictors.

**Comment by gafsd** [comment]
Yes g2p puts it as OY1 L (and VITS also have same issue)
Word is in training data pronounced correctly
Seems like specific phonemes OY1 L will cause this issue

**Comment by kan-bayashi** [comment]
How about using different g2p?

**Comment by gafsd** [comment]
You want me to retrain my models with different g2p?
Both g2p_en and the espeak_ng english VITS g2p have this problem

**Comment by kan-bayashi** [comment]
Is the problem happened for models trained on your dataset?
LJSpeech or VCTK or LibriTTS models work correctly?

**Comment by gafsd** [comment]
Yes it happen for all model on separate datasets even 4-5 tried
All ljspeech with finetune confs

**Comment by kan-bayashi** [comment]
If ljspeech / vctk / libritts models are fine, it seems your dataset has a problem.
Does the training dataset contain the word "oil"? Is it correctly pronounced when using training sample? (e.g., teacher forcing)

**Comment by gafsd** [comment]
THe problem happen for multiple datasets that contain the word. It seem to be those two phonemes and the network just not pronounce them (even in different words like Toil Boil etc.)
I will need time to try with default pjspeech/vctk/libriittts
