### ISSUE TITLE
Fairseq and Espnet

### ISSUE THREAD

**Issue by sameerkhurana10** [espnet/espnet#4081]
Hi,

I sometimes like to train large ASR models with fairseq but I like the ESPnet decoding setup.

I would like to take the fairseq model and be able to decode with espnet. How much work do you think it would take to enable that integration?

**Comment by sw005320** [comment]
We're actually working on it. @ftshijt, can you share your situation?

**Comment by ftshijt** [comment]
Thanks for sharing your issues. We are currently working on importing ESPNet model to fairseq setting but not exactly the revise (but we are seriously thinking about that). The current issue lies is that the feature extraction is a bit different from the codebase. Please stay tuned! We will be working to connect the two in the future.

**Comment by test-dan-run** [comment]
Hi @ftshijt , has there been any progress on this front?

**Comment by ftshijt** [comment]
Hi, thanks for your following up. I do not think we have further updates on the direction, especially considering that 
- most fairseq models are supported in huggingface and espnet also supports huggingface models; 
- fairseq is actively changing and will have some big movements (sorry, no details for the public so far) in the future. After their version is stable, we may resume the integration more.
