### ISSUE TITLE
Question: Optimising batch_bins size

### ISSUE THREAD

**Issue by arunbaby0** [espnet/espnet#4085]
**Is there any standard way to optimise the batch_bins and accum_grad based on the GPU memory?**

I tried to train one model with approx 500hrs of private data, for which a batch_bins size of 600K was failing for 16GB of GPU memory. This one failed because of lack of GPU memory:
`RuntimeError: CUDA out of memory. Tried to allocate 356.00 MiB (GPU 0; 15.78 GiB total capacity; 13.63 GiB already allocated; 267.75 MiB free; 13.81 GiB reserved in total by PyTorch)`

However, a subset of the same data around 80hrs got trained with batch_bins of 100M on a 24GB GPU.

**Comment by sunotsue** [comment]
Hi, were you able to resolve this?
