### ISSUE TITLE
Question about the definition of batch_bins?

### ISSUE THREAD

**Issue by rrr613** [espnet/espnet#4093]
I am doing the TTS. I use a dataset which has **260 data**.
I know that  
`(1 epoch) = iterate * batch-size. `
`Iteration = （Data set size / Batch size）* Epoch`

I set the `batch_size = 20 `and` batch_bins = 15000000.`
I want to run **200 epoch.**
So the iteration is 2600.

But, I was so confused that what is the batch_bins?
What is it used for?

**Comment by kan-bayashi** [comment]
https://espnet.github.io/espnet/espnet2_training_option.html#change-mini-batch-type
This may help you.
