### ISSUE TITLE
expdir for single speaker TTS recipe in multi speaker corpus

### ISSUE THREAD

**Issue by G-Thor** [espnet/espnet#4096]
I'm working on developing a recipe for Talrómur, an Icelandic TTS corpus consisting of recordings of 8 voices, with over 20 hours per voice.
This corpus is suitable for single-speaker model training for each of the 8 voices in the corpus, and I accept the desired speaker ID as input in my training script.
I was wondering if there was a preferred way to handle multiple speakers within the same corpus/recipe in terms of exp folders. Locally I've used exp_<spk_id> directories, but I noticed that creates a bit of clutter in the project root. Would exp/<spk_id>/<tag> cause any issues with other components?

**Comment by kan-bayashi** [comment]
I think it is no problem.
Maybe you can change dumpdir and expdir for each spk, e.g., dumpdir=dump/<spk> & expdir=exp/<spk>
https://github.com/espnet/espnet/blob/9c24b3adddbde3402530080cb58ae08a6f4dd642/egs2/TEMPLATE/tts1/tts.sh#L41-L42
