### ISSUE TITLE
a missing Indent symbol

### ISSUE THREAD

**Issue by dalision** [espnet/espnet#4102]
I guess there a missing Indent symbol, but everything goes well when training. You may have a look.
https://github.com/espnet/espnet/blob/650472b45a67612eaac09c7fbd61dc25f8ff2405/espnet2/samplers/num_elements_batch_sampler.py#L92

**Comment by sw005320** [comment]
Thanks!
I think you're right.
@pyf98, could I ask you to confirm it and fix this error?

**Comment by kamo-naoyuki** [comment]
This is correct.

**Comment by pyf98** [comment]
The `else` part only deals with the last few samples which haven't been added to the batches, so it is correct.

**Comment by dalision** [comment]
Thanks for your response! I get it, it is correct!

> The `else` part only deals with the last few samples which haven't been added to the batches, so it is correct.

Thanks for your response! I get it, it is correct!
