### ISSUE TITLE
Pretrained Diarization Model has version conflict

### ISSUE THREAD

**Issue by EmreOzkose** [espnet/espnet#4103]
**Describe the bug**
I downloaded [pretrained model](https://zenodo.org/record/5264020) and run [run.sh](https://github.com/espnet/espnet/blob/master/egs2/mini_librispeech/diar1/run.sh). I didn't skip data preparation and skipped training part. Then I came to stage 6. When I run stage 6, I got this error:

```
/path/to/espnet/tools/anaconda/envs/espnet/bin/python3 /path/to/espnet/espnet2/bin/diar_inference.py --ngpu 0 --fs 8k --data_path_and_name_and_type dump/raw/simu/data/dev_clean_2_ns2_beta2_500/wav.scp,speech,sound --key_file exp/diar_train_diar_raw/diarized_simu/data/dev_clean_2_ns2_beta2_500/logdir/keys.1.scp --train_config exp/diar_train_diar_raw/config.yaml --model_file exp/diar_train_diar_raw/valid.acc.best.pth --output_dir exp/diar_train_diar_raw/diarized_simu/data/dev_clean_2_ns2_beta2_500/logdir/output.1 --config conf/decode_diar.yaml
Traceback (most recent call last):
  File "/path/to/espnet/tools/anaconda/envs/espnet/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/path/to/espnet/tools/anaconda/envs/espnet/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/path/to/espnet/espnet2/bin/diar_inference.py", line 480, in <module>
    main()
  File "/path/to/espnet/espnet2/bin/diar_inference.py", line 476, in main
    inference(**kwargs)
  File "/path/to/espnet/espnet2/bin/diar_inference.py", line 329, in inference
    diarize_speech = DiarizeSpeech.from_pretrained(
  File "/path/to/espnet/espnet2/bin/diar_inference.py", line 278, in from_pretrained
    return DiarizeSpeech(**kwargs)
  File "/path/to/espnet/espnet2/bin/diar_inference.py", line 58, in __init__
    diar_model, diar_train_args = DiarizationTask.build_model_from_file(
  File "/path/to/espnet/espnet2/tasks/abs_task.py", line 1821, in build_model_from_file
    model = cls.build_model(args)
  File "/path/to/espnet/espnet2/tasks/diar.py", line 289, in build_model
    model = ESPnetDiarizationModel(
TypeError: __init__() got an unexpected keyword argument 'loss_type'
```

I checked previous versions and found `loss_type` variable in [this commit](https://github.com/espnet/espnet/commit/3d793ab4243710c1429ffe333ead52a72802fdc6) (3 commit before from latest). I guess pretrained model is trained with this version of Espnet and it doesn't work now. 

**Basic environments:**
 - OS information: Linux
 - python version: 3.8.12
 - espnet version: espnet 0.10.7a1
 

**Task information:**
 - Task: Diarization
 - Recipe: mini librispeech
 - ESPnet2

**Comment by EmreOzkose** [comment]
I changed config(espnet/egs2/mini_librispeech/diar1/exp/diar_train_diar_raw/config.yaml) file as follows:

from
```
111 model_conf:
112     loss_type: pit
```

to
```
111 model_conf:
112     attractor_weight: 1.0
```

I removed `loss_type` and I put a default value to model_conf part.

**Comment by sw005320** [comment]
Thanks for the report!
I think it is easier to make a model and upload it again.
@YushiUeda, can you do it?

**Comment by YushiUeda** [comment]
Thanks @EmreOzkose!
I've uploaded the model I've made recently. Please let me know if you encounter any problems again.
https://huggingface.co/espnet/YushiUeda_mini_librispeech_diar_train_diar_raw_valid.acc.best
