### ISSUE TITLE
Support for pytorch 0.3

### ISSUE THREAD

**Issue by creatorscan** [espnet/espnet#411]
https://github.com/espnet/espnet/blob/1a28505220fd3bfe44574c027a4e299f9415594d/src/asr/asr_pytorch.py#L237

@kan-bayashi I guess this is specific to pytorch 0.4. Is this part of the plan to completely switch to pytorch 0.4 ?

**Comment by ShigekiKarita** [comment]
Yes, we switched https://github.com/espnet/espnet/issues/316 (we forget to update README)

I think this PR is the turning point https://github.com/espnet/espnet/pull/332
You can use the last commit before merging this PR for 0.3 https://github.com/espnet/espnet/commit/70e06b78755b840aaec756809b72a8a3fbe86195
