### ISSUE TITLE
how to upgrade ESPnet to the latest version 

### ISSUE THREAD

**Issue by asadolahzade** [espnet/espnet#4119]
Hi,
I want to upgrade the installed ESPnet to its latest version. 
Could you let me know how to do that?
Should I make a new installation in a new separate directory? Or is there a better way? 
Thank you.

**Comment by kamo-naoyuki** [comment]
- If you are using espnet as a python module; i.e. if you installed espnet by  `pip install espnet`, please use `pip install -U espnet`


- If you are using the recipes in espnet repository, and to upgrade existing one, please use `git pull`

```
cd ${espnet_repo}
git pull
```


- To create a new one with the python environment of old one

```
git clone https://github.com/espnet/espnet

cd ${espnet_repo}
cd tools

ln -s ${old_repo}/tools/kaldi kaldi

# Generate activate_python.sh, e.g. as following
cp ${old_repo}/tools/activate_python.sh activate_python.sh 

# Please copy the other tools from the old repository, or create symbolic links to them, 
# if any other tools are required depending on each recipe
```
