### ISSUE TITLE
pronouncing Acronyms and Abbreviations by TTS

### ISSUE THREAD

**Issue by roholazandie** [espnet/espnet#4120]
I have a general question regarding TTS that can pronounce acronyms like NFL, NIH, etc, and abbreviations like NASA, NATO, AIDS. I searched in the help and issues and couldn't find anything relevant. Is there any way to make the TTS pronounce them correctly?

**Comment by kan-bayashi** [comment]
If you use g2p, it may have the pronunciation dictionary.
You can extend it by registering the new words.

**Comment by roholazandie** [comment]
I am using tactron with parallel_wavegan. Do you have any example or part of the documentation that can help me understand it?

**Comment by kan-bayashi** [comment]
I assume that you use g2p=g2p_en.
g2p_en used cmu_dict from nltk, 
https://github.com/Kyubyong/g2p/blob/c6439c274c42b9724a7fee1dc07ca6a4c68a0538/g2p_en/g2p.py#L70
https://github.com/Kyubyong/g2p/blob/c6439c274c42b9724a7fee1dc07ca6a4c68a0538/g2p_en/g2p.py#L175-L176
You can extend this dict to register new words.

**Comment by kan-bayashi** [comment]
You may find cmudict in `$HOME/nltk_data/corpora/cmudict/cmudict`.

```
$ head ~/nltk_data/corpora/cmudict/cmudict
A 1 AH0
A. 1 EY1
A 2 EY1
A42128 1 EY1 F AO1 R T UW1 W AH1 N T UW1 EY1 T
AAA 1 T R IH2 P AH0 L EY1
AABERG 1 AA1 B ER0 G
AACHEN 1 AA1 K AH0 N
AACHENER 1 AA1 K AH0 N ER0
AAKER 1 AA1 K ER0
AALSETH 1 AA1 L S EH0 TH
```

**Comment by roholazandie** [comment]
Thanks for the answer. I checked it and it works fine. But is there any way that I can programmatically add the new words to cmu dict without modifying the actual file? I tried the following and it works but I want to integrate it with ```Text2Speech```:

```
from g2p_en import G2p
g2p = G2p()
g2p.cmu['co'].insert(0, ['K', 'AA2', 'L',  'ER0',  'AA1',  'D', 'OW0'])
x = g2p("CO")
print(x)
```

**Comment by kan-bayashi** [comment]
How about this one?
```python
text2speech = Text2Speech.from_pretrained(
    model_tag=str_or_none(tag),
    vocoder_tag=str_or_none(vocoder_tag),
    device="cuda",
    # Only for Tacotron 2 & Transformer
    threshold=0.5,
    # Only for Tacotron 2
    minlenratio=0.0,
    maxlenratio=10.0,
    use_att_constraint=False,
    backward_window=1,
    forward_window=3,
    # Only for FastSpeech & FastSpeech2 & VITS
    speed_control_alpha=1.0,
    # Only for VITS
    noise_scale=0.333,
    noise_scale_dur=0.333,
)

# define your custom dict
custom_dict = {
    "hogehoge": [['AAAAAAAAAAAAAAAAAA']],
    "fugafuga": [['AAAAAAAAAAAAAAAAAA']]
}

# iniatialize g2p instance
text2speech.preprocess_fn.tokenizer.g2p("initialize")

# check
print(text2speech.preprocess_fn.tokenizer.g2p("hogehoge"))
# >>> ['HH', 'AA1', 'G', 'HH', 'OW2', 'JH']

# update dict
text2speech.preprocess_fn.tokenizer.g2p.g2p.cmu.update(custom_dict)

# check
print(text2speech.preprocess_fn.tokenizer.g2p("hogehoge"))
# >>> ['AAAAAAAAAAAAAAAAAA']
```

**Comment by roholazandie** [comment]
Thank you so much! it's working. Final question: Is there any standard way (like a script) to convert IPA to CMU phonemes?

**Comment by kan-bayashi** [comment]
Not sure but maybe this one can be used? 
https://github.com/chdzq/ARPAbetAndIPAConvertor

**Comment by roholazandie** [comment]
That code was useful. Thansk!

**Comment by nellorebhanuteja** [comment]
@kan-bayashi 
Can i similarly customize pronunciations while using espeak_ng?
