### ISSUE TITLE
Tensorboard and staging

### ISSUE THREAD

**Issue by underdogliu** [espnet/espnet#4138]
**Describe the bug**
I am currently running a mocker script with the AISHELL dataset, which can be automatically downloaded. However, I found in the pipeline there are two issues:
1. Tensorboard was not set as a necessity in the installation, but AISHELL's ASR runner needs it by default and if we don't have it in advance, an error will pop. Maybe we can add it to the necessities/requirements?
2. The main interface `run.sh` does not have staging for AISHELL. I am not sure if that is the case for every egs. I suggest adding it if so because every time running from the beginning is time-consuming.

**Basic environments:**
 - OS information: Ubuntu 18.04, Server
 - python version: Python 3.9.2 [GCC 10.2.1 20210110] on linux
 - espnet version: 0.10.7
 - pytorch version pytorch 1.10.2, nvcc 11.2

**Task information:**
 - Task: ASR
 - Recipe: AISHELL
 - ESPnet2

**To Reproduce**
1. move to a recipe directory, e.g., `cd egs2/aishell/asr1`
3. execute `run.sh` with specific arguments.
4. specify the error log, e.g., `exp/xxx/yyy.log`

**Comment by kamo-naoyuki** [comment]
`tensorboard` is installed by default.

https://github.com/espnet/espnet/blob/a04a98c98797b314f2425082bc40261757fd47de/setup.py#L46

**Comment by underdogliu** [comment]
Yes I spot that thanks. But I want to ask if it is installed by default when initializing via virtualenv, i.e. via option B from [the installation doc](https://espnet.github.io/espnet/installation.html).

Also, if using the same approach, seems matplotlib is also missing.

**Comment by kamo-naoyuki** [comment]
`tensorboard` and `matplotlib` are installed both, always.  If you installed espnet following the instruction, any errors shouldn't happen, of course.

**Comment by underdogliu** [comment]
OK. Let me go back and play with it a bit more. Sorry for bothering.
