### ISSUE TITLE
How to use no dynamic shape tensors in tts training?

### ISSUE THREAD

**Issue by seastar105** [espnet/espnet#4139]
Maybe this question is not suitable for this repo, sorry. There's nowhere to ask.....

I'm trying to train tts model on tpu now, but dynamic shape tensors are not suitable for tpu. I found it from [here](https://cloud.google.com/tpu/docs/tpus)

It seems dynamic shape is common in asr, and tts, like `numel`, `length`, `folded` type in espnet. How can i make all tensors used during tts training static? I think zero padding may affect harm for synthesized speech.

**Comment by kamo-naoyuki** [comment]
https://espnet.github.io/espnet/espnet2_training_option.html#change-mini-batch-type

Please use `unsorted` or `sorted`

**Comment by cedilla1312** [comment]
@seastar105 have you or anybody implemented this for TPU, yet? I believe it is only needed to edit only these files https://github.com/espnet/espnet/tree/master/espnet2/samplers ?
