### ISSUE TITLE
bugs in dokcer run.sh for root access

### ISSUE THREAD

**Issue by alirezadir** [espnet/espnet#414]
Hello, I was trying to run the docker in root access, but faced two issues (potential bugs):
I think for root access `--docker_user` needs to be set as empty rather than `false`. Setting it to `false`, still passes the condition in shell script. 

Also, in https://github.com/espnet/espnet/blob/f5a1dc148ad0f9b34aec02c9f46768555eefd3f0/docker/run.sh#L127
we need to add `cmd2="./run.sh $@"` beforehands, otherwise `${cmd2}` is empty.

**Comment by sw005320** [comment]
It seems that #415 fixed the issue, and I'm closing this issue.
