### ISSUE TITLE
X-vector VITS multi-speaker TTS with new speaker. 

### ISSUE THREAD

**Issue by mudong0419** [espnet/espnet#4141]
Thanks for your great work. I'v read your new paper [ESPnet2-TTS: Extending the Edge of TTS Research](https://arxiv.org/abs/2110.07840), and I'm very interested in the result of table 4 which shows impressive results with x-VITS model. In the [tts demo](https://colab.research.google.com/github/espnet/notebook/blob/master/espnet2_tts_realtime_demo.ipynb), is it possible to extract x-vector of an audio file, and synthesis speech with this x-vector? How to extract the x-vector? Many thanks in advance.

**Comment by unparalleled-ysj** [comment]
@kan-bayashi According to the results of the paper, as long as the unseen target speaker's audio is used to extract the xvector, can the speaker's speech be generated without finetune?

**Comment by kan-bayashi** [comment]
> According to the results of the paper, as long as the unseen target speaker's audio is used to extract the xvector, can the speaker's speech be generated without finetune?

If the unseen speaker is not so different from the training speakers, it can be.
But for example, if the unseen speaker has a very high pitch like anime characters, it is difficult.

**Comment by unparalleled-ysj** [comment]
> > According to the results of the paper, as long as the unseen target speaker's audio is used to extract the xvector, can the speaker's speech be generated without finetune?
> 
> If the unseen speaker is not so different from the training speakers, it can be. But for example, if the unseen speaker has a very high pitch like anime characters, it is difficult.

Is it the same for xvector-joint(cfs2+hfg)?

**Comment by kan-bayashi** [comment]
> Is it the same for xvector-joint(cfs2+hfg)?

In my experiments, mutli-spk cfs2 is not good. Multi-spk VITS is definitely better.
I've never tried joint xvector cfs2, but the tendency may not be changed.

**Comment by unparalleled-ysj** [comment]
> > Is it the same for xvector-joint(cfs2+hfg)?
> 
> In my experiments, mutli-spk cfs2 is not good. Multi-spk VITS is definitely better. I've never tried joint xvector cfs2, but the tendency may not be changed.
thank you for your sharing ！

**Comment by unparalleled-ysj** [comment]
> > Is it the same for xvector-joint(cfs2+hfg)?
> 
> In my experiments, mutli-spk cfs2 is not good. Multi-spk VITS is definitely better. I've never tried joint xvector cfs2, but the tendency may not be changed.

thank you for your sharing !

**Comment by kan-bayashi** [comment]
@mudong0419 
> The x-vits model in the paper are trained on English data, is it possible to train on Chinese or Japanese data?

Of course. You can do it.

> By the way, xvector in kaldi is also trained mainly on English data, so for Chinese or Japanese x-vits model, is it necessary to train an xvector extracting model?

In my experience, x-vector seems to be language independent.
So it can be used for any language.

**Comment by mudong0419** [comment]
@kan-bayashi Thanks for your elaborated reply. I'm planing to train an x-vits model for voice clone with Chinese-English code switched data. And I have tried [YourTTS](https://coqui.ai/demo), but the cloned voice seems to be not good enough. With your information I'm more confident with x-vits, and will have a try. Thanks again.

**Comment by keshawnhsieh** [comment]
> @kan-bayashi Thanks for your elaborated reply. I'm planing to train an x-vits model for voice clone with Chinese-English code switched data. And I have tried [YourTTS](https://coqui.ai/demo), but the cloned voice seems to be not good enough. With your information I'm more confident with x-vits, and will have a try. Thanks again.

Hi, @mudong0419. Do you have any further great result on that topic about training a Chinese-English combined tts with x-vector? I recently move to that interest and have tried with SV2TTS on Chinese data like aishell3 but do not get any promising result. I am wondering if the implementation of x-vector based voice cloning can make me a suprise.
