### ISSUE TITLE
The sample rate of VITS for csmsc

### ISSUE THREAD

**Issue by yt605155624** [espnet/espnet#4176]
the origin sample rate of csmsc(same as vctk, aishell3) is 48kHZ, but you used to use 24khz in espnet and ParallelWaveGAN, the origin sample rate of ljspeech is 22.05kHZ, so you use  22.05khz in your config, but in VITS, you use 22.05khz and 41khz, could you please tell me why? Did this just follow the config of  https://github.com/jaywalnut310/vits/ ?

**Comment by kan-bayashi** [comment]
Yes, I followed the official config. 
We can use 24khz but I wanted to make the difference minimal to check the behavior so I used 22.05khz with the same hyperparmeters.

**Comment by yt605155624** [comment]
thx for your reply~
