### ISSUE TITLE
How to add an extra encoder for transformer transducer?

### ISSUE THREAD

**Issue by gyc666** [espnet/espnet#4184]
### Discussed in https://github.com/espnet/espnet/discussions/4169

<div type='discussions-op-text'>

<sup>Originally posted by **gyc666** March 18, 2022</sup>
How to add an extra encoder 【an pretrained bert or BLSTM】 for transformer transducer?

How I modify the train.yaml and where should i modify on espnet.nets.pytorch_backend.e2e_asr_transducer:E2E ?

What should I pay attention to?

I would be most grateful if you could answer my questions！</div>

**Comment by b-flo** [comment]
I'm closing the issue, answered in #4169.
