### ISSUE TITLE
Plz help me about model summary of ESPNet model

### ISSUE THREAD

**Issue by miziworld** [espnet/espnet#4218]
#4205 
Since this is a really important question for me, I will ask again without any excuses.
When using a conformer or transformer model and using torchsummary, it seems that the parameters defined in forward() are more necessary in addition to the input size as an argument.
this is my error result (egs2/ksponspeech/asr1 example) when I put the argument like summary(model, (1,2309,1), batch_size=-1, device='cpu')
![image](https://user-images.githubusercontent.com/17849068/160591430-ed65090b-5ba4-4dae-a726-2f66deefea18.png)
Can you help me how can I check the number of parameters per layer using torchsummary?

**Comment by b-flo** [comment]
Hi,

The error seems rather straightforward to me. `forward(...)` requires 4 positional arguments and you only provided one through `summary(...)`. You need to supply the other input tensors like this (if I'm reading the correct documentation): 

```
summary(asr_model, <speech>, <speech_lengths>, <text>, <text_lengths>, ...)
```

Also, you should consider opening a [Discussion](https://github.com/espnet/espnet/discussions) instead of an issue. The problems you're encountering are not directly related to ESPnet.

**Comment by miziworld** [comment]
thank you. Is it possible to put the audio file, length, etc. for one input audio file as arguments for this problem?

I haven't been able to confirm that the discussion tab is active. We will move on to the rest of the questions.

**Comment by b-flo** [comment]
> thank you. Is it possible to put the audio file, length, etc. for one input audio file as arguments for this problem?

I'm not sure I understand what you mean? The batch dim for each tensor can be equal to one, yes.

**Comment by b-flo** [comment]
> I am not sure what to put in speech, text, speech_length, etc.

Hum, did you take a look at the method documentation for the one throwing the error? What you're asking is mentioned or documented.
Anyways, it should be:

speech: speech sequences  -> (batch, max_len_seq, dim_in)
speech_lengths: speech sequence lengths -> (batch,)
text: label ID sequences -> (batch, max_len_seq)
text_lengths: label ID sequence lengths -> (batch,)

**Comment by b-flo** [comment]
> Can you tell me a little bit more about what to do when forward() requires more speech_lengths, text, and text_lengths?

I can't help if you don't share the error you encounter or/and a full code snippet to reproduce the issue.
The only thing I can do with current pieces of information is to explain the issue with `forward(...)` and point out the documentation cases I found for torch-summary ([here](https://pypi.org/project/torch-summary/)).
