### ISSUE TITLE
ljspeech TTS recipe - not getting good audio

### ISSUE THREAD

**Issue by samin9796** [espnet/espnet#4225]
Hello! I am a newbie here. I installed ESPnet and ran the run.sh inside the /egs2/ljspeech/tts1 directory. Initially I got **Cuda: out of memory** error (GPU model: Nvidia 3080Ti Single GPU - 12 GB) and so I reduced the **batch_bins** value to 51200 randomly. All the other hyper-parameters were kept as it was set as default. The Tacotron 2 model got trained then for 200 epochs. After stage 7, I got the decoded audio files, however, the quality of the generated speech is really bad. I also gave some new inputs to the model (added with a pre-trained vocoder), the result is still so bad. Is this happening because I changed the batch_bins value?

**Comment by kan-bayashi** [comment]
You mean 5120000 -> 51200? It looks too small.
You can check the actual batch size in train.log (maybe around 1?).
Maybe the diagonal attention weight could not be obtained due to too small batchsize.

**Comment by samin9796** [comment]
I increased the batch_bins value to 2560000 and now the quality has improved but still it sounds so monotonous. If I use the default batch_bins value (5120000), I get the following error:

`RuntimeError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 11.76 GiB total capacity; 8.78 GiB already allocated; 16.44 MiB free; 9.77 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF`

In the train.yaml file, it says the following-

`This configuration is for ESPnet2 to train Tacotron 2. Compared to the original paper, this configuration additionally use the guided attention loss to accelerate the learning of the diagonal attention. It requires only a single GPU with 12 GB memory and it takes ~3 days to finish the training on Titan V.`

I am using a 12GB GPU (Nvidia 3080 Ti). Could you please provide any solution here?

**Comment by kan-bayashi** [comment]
Please use accum_grad. 
E.g.,
```
num_iters_per_epoch: 1000    # number of iterations per epoch
max_epoch: 200              # number of epochs
grad_clip: 1.0              # gradient clipping norm
accum_grad: 2               # gradient accumulation
batch_bins: 2560000         # batch bins (for feats_type=raw, *= n_shift / n_mels)
```
