### ISSUE TITLE
Realtime ASR-demo on my own model

### ISSUE THREAD

**Issue by miziworld** [espnet/espnet#4231]
Hello, I'm using the realtime-ASR demo code you provided in the documentation.
 In the case of this example, the model registered in espnet_model_zoo is downloaded and used, but I want to use the model I trained.
 In my opinion, I think I can use espnet2/bin/asr_inference.py and put it in the speech2text function.
 I have the zip file (data, exp, meta.yaml) in the same format when downloaded according to the model tag, but I am not sure how to put my model and path in the __init__ parameters of Speech2Text. Can you please help?
```

    def __init__(
        self,
        asr_train_config: Union[Path, str] = None,
        asr_model_file: Union[Path, str] = None,
        transducer_conf: dict = None,
        lm_train_config: Union[Path, str] = None,
        lm_file: Union[Path, str] = None,
        ngram_scorer: str = "full",
        ngram_file: Union[Path, str] = None,
        token_type: str = None,
        bpemodel: str = None,
        device: str = "cpu",
        maxlenratio: float = 0.0,
        minlenratio: float = 0.0,
        batch_size: int = 1,
        dtype: str = "float32",
        beam_size: int = 20,
        ctc_weight: float = 0.5,
        lm_weight: float = 1.0,
        ngram_weight: float = 0.9,
        penalty: float = 0.0,
        nbest: int = 1,
        streaming: bool = False,
    ):
```
Also, can I use asr_inference_k2.py instead of asr_inference.py?

**Comment by biscayan** [comment]
Hi, did you solve the problem?
Can you tell me the way how to use my own model for real-time asr
