### ISSUE TITLE
pyopenjtalk_accent_with_pause trained finetuning model  just reads out symbols one by one instead of creating sentence

### ISSUE THREAD

**Issue by dtfasteas** [espnet/espnet#4237]
hi,

I finetuned  a model with g2p  pyopenjtalk_accent_with_pause, but at inference when I use

...

text = "こんにちは。"
text = pt.pyopenjtalk_g2p_accent_with_pause(text)
text = ' '.join(text)

or

text2 = "k 1 0 o 1 0 pau k 5 -4 o 5 -4 N 5 -3 n 5 -2 i 5 -2 ch 5 -1 i 5 -1 w 5 0 a 5 0"

...

it just reads out the symbols one by one. 

When i just submit text withouth parsing it trough pyopenjtalk at inference the outcome is as expected and sounds ok. 

The config file of the base and the finetuned model both state that they were trained using pyopenjtalk_accent_with_pause, so I was wondering why it reads out symbols one by one.

. ./run.sh \
    --stage 6 \
    --g2p pyopenjtalk_accent_with_pause \
    --min_wav_duration 0.38 \
    --fs 44100 \
    --n_fft 2048 \
    --n_shift 512 \
    --dumpdir dump/44k \
    --win_length null \
    --tts_task gan_tts \
    --feats_extract linear_spectrogram \
    --feats_normalize none \
    --train_config ./conf/tuning/finetune_full_band_vits.yaml \
    --train_args "--init_param downloads/full_band_vits_accent_with_pause_pretrain/exp/tts_train_full_band_vits_raw_phn_jaconv_pyopenjtalk_accent_with_pause/train.total_count.ave_10best.pth:tts:tts" \
    --tag full_band_vits

**Comment by kan-bayashi** [comment]
You do not need to apply g2p by yourself.
Please feed raw text as is.

**Comment by dtfasteas** [comment]
thank u very much for your answer. 

i found some collab online where it was using g2p, so maybe its not the same codebase.

https://colab.research.google.com/drive/1xfYw2VeNOs_87pqsudLk9mg2DxLzN8i9?usp=sharing#scrollTo=0hGZ6mJZWTx-

**Comment by kan-bayashi** [comment]
You can change the g2p in `config.yaml` to accept g2p applied text.
Please check https://github.com/espnet/espnet/tree/master/egs2/TEMPLATE/tts1#supported-text-frontend
