### ISSUE TITLE
have you tested the effect of postnet on sound quality?

### ISSUE THREAD

**Issue by Pydataman** [espnet/espnet#4282]
FYI

**Comment by iamanigeeit** [comment]
@Pydataman I've raised a similar issue at [https://github.com/espnet/espnet/issues/4684](url) if your problem is with FastSpeech2. Tacotron2 postnets are important. From the original paper:

> we compared our model with and without the post-net,
> and found that without it, our model only obtains a MOS score of
> 4.429 ± 0.071, compared to 4.526 ± 0.066 with it, meaning that em-
> pirically the post-net is still an important part of the network design.
