### ISSUE TITLE
How add librispeech_100h egs?

### ISSUE THREAD

**Issue by flp1990** [espnet/espnet#4292]
I have installed espnet, the asr scripts(960h) in libripseech execute correctly.
But in my installed version, there no egs2/librispeech_100h script.
How can I add librispeech_100h to my espnet?

**Comment by sw005320** [comment]
How to install it?
Docker?

**Comment by flp1990** [comment]
> How to install it? Docker?

Yeah, i don't know how to add it. 

When I installed espnet, I noticed that it created a mini conda environment that automatically invoked conda when running run.sh

**Comment by sw005320** [comment]
@Fhrozen, does it happen?
I see from https://hub.docker.com/repository/docker/espnet/espnet that the latest one is pushed 21 days ago.
At that time, the `librispeech_100` recipe already exists.

**Comment by flp1990** [comment]
> How to install it? Docker?
I try it with the website “https://espnet.github.io/espnet/docker.html”
./run.sh --docker-gpu 0 --is-egs2 --docker-egs librispeech_100/asr1 --ngpu1 
like this?

**Comment by flp1990** [comment]
> 
Then, i get this error as follow:
~/fanpeng/espnet_/espnet/docker$ ./run.sh --docker-gpu 0 --is-egs2 --docker-egs librispeech_100/asr1 --ngpu1
./run.sh: 行 92: docker: 未找到命令
./run.sh: 行 98: docker: 未找到命令
./run.sh: 行 111: docker: 未找到命令
Building docker image...
Now running docker build --build-arg FROM_TAG=gpu-latest --build-arg THIS_USER=wise --build-arg THIS_UID=1000 --build-arg EXTRA_LIBS=false -f prebuilt/Dockerfile -t espnet/espnet:gpu-latest-user-wise .
./run.sh: 行 120: docker: 未找到命令

**Comment by flp1990** [comment]
Thanks, I installed espnet again.
There have librispeech_100, it looks like it should work fine.

**Comment by Fhrozen** [comment]
dont forget to keep up to date your installation using git pull

**Comment by flp1990** [comment]
> 

yeah,  thanks.
