### ISSUE TITLE
TTS dataset download from speech.cs.cmu.edu connection refused

### ISSUE THREAD

**Issue by sakibchowdhury131** [espnet/espnet#4294]
I was following the tts recipe from here: https://espnet.github.io/espnet/notebook/tts_cli.html

but at stage -1, the following error occurred. I'm sharing the output here: 

stage -1: Data Download
local/download_and_untar.sh: downloading data (64 MB) from http://www.speech.cs.cmu.edu/databases/an4//an4_sphere.tar.gz.
--2022-04-20 10:49:39--  http://www.speech.cs.cmu.edu/databases/an4//an4_sphere.tar.gz
Resolving [www.speech.cs.cmu.edu](http://www.speech.cs.cmu.edu/) ([www.speech.cs.cmu.edu](http://www.speech.cs.cmu.edu/))... 128.2.220.147
Connecting to [www.speech.cs.cmu.edu](http://www.speech.cs.cmu.edu/) ([www.speech.cs.cmu.edu)|128.2.220.147|:80](http://www.speech.cs.cmu.edu%29%7C128.2.220.147%7C/)... failed: Connection refused.
local/download_and_untar.sh: error executing wget http://www.speech.cs.cmu.edu/databases/an4//an4_sphere.tar.gz

the site speech.cs.cmu.edu is down. how may I solve this problem?

**Comment by sw005320** [comment]
I confirmed the issue, and I'm asking my colleagues.

**Comment by ciphurus** [comment]
Hi - any resolution or workaround for this? Following this collab https://colab.research.google.com/github/espnet/notebook/blob/master/espnet2_tutorial_2021_CMU_11751_18781.ipynb and still getting the error

**Comment by sw005320** [comment]
It may not be fixed soon.
We'll host the data in a different place.

**Comment by sw005320** [comment]
See https://github.com/espnet/espnet/pull/4427

We copied it in a huggingface space.

**Comment by sw005320** [comment]
@ciphurus and @sakibchowdhury131, can you test it?

**Comment by ciphurus** [comment]
Thanks. I tested it and it now the tutorial works. The data gets downloaded from the alternative site.
