### ISSUE TITLE
Two times sqrt in utterance_mvn.py

### ISSUE THREAD

**Issue by boeddeker** [espnet/espnet#4296]
https://github.com/espnet/espnet/blob/c7881c215e019324257620bc1dd83cec898ba6a9/espnet2/layers/utterance_mvn.py#L73-L80

I was checking what `utterance_mvn` does and recognized that `sqrt` was used two times instead of just once to convert the variance to the standard deviation in `espnet2`.

**Comment by Emrys365** [comment]
Thanks @boeddeker, this is indeed a bug. I will fix it immediately.
