### ISSUE TITLE
How to run various networks with own data in Speech Enhancement task.

### ISSUE THREAD

**Issue by takashin3391** [espnet/espnet#4299]
I want to compare the performance of various networks (e.g. Transformer, Conformer, DPRNN, etc.) using my own data.
I copied the `run.sh` and `train.yaml` files from the `wsj0_2mix` directory to my recipe.
Then I modified the options to match my own data.
However, I could not run the training with some errors.

What is the best way to get the various networks to work with own data?
(I copied the `run.sh` and `train.yaml` from the vctk_noisy recipe to my recipe and was able to make it work with own data)

**Comment by Emrys365** [comment]
Does your data only contains a single speaker for each sample? If so, you will need to modify the value of `num_spk` in the yaml files you copied from wsj0_2mix, because it is a two-speaker mixture dataset.

**Comment by takashin3391** [comment]
Thank you very much for your reply.

I modified the `num_spk` in the yaml file to 1 as advised.
The learning worked.

Thank you very much.
