### ISSUE TITLE
RNNT modified_adaptive_expansion_search is too slow.

### ISSUE THREAD

**Issue by kobenaxie** [espnet/espnet#4303]
Hi, I try to use `modified_adaptive_expansion_search` with beam_size 5 to recognize one wav, which costs 52.9s, while `ALSD` costs 0.87S. why the speed is so slow.

**Comment by b-flo** [comment]
Hi,

Can you give information? recipe, architecture, units, etc?

Nevertheless, I'm assuming you are modeling BPE? If so, the issue is known for ESPnet1 and due to `select_k_expansions(...)`, see [here](https://github.com/espnet/espnet/pull/4032#issuecomment-1073682573)

> mAES: Fixed select_top_k_candidates loop taking a long time with a big vocab size. It also improves decoding time in general.

I'll fix it in ESPnet1 when I have time, for the moment please either use the changes from PR #4032 or use another time-synchronous algorithm.

**Comment by kobenaxie** [comment]
Thank you for your reply, The dataset is AISHELL, vocab_size = 4442, encoder consist of 11 blocks. And I tried your PR, find the new implement cost 0.32s, which is faster than `ALSD`. but another problem is that the hyps in final beam are all same(beam_width=5). Can you take a look ?

**Comment by b-flo** [comment]
> And I tried your PR, find the new implement cost 0.32s, which is faster than ALSD. but another problem is that the hyps in final beam are all same(beam_width=5). Can you take a look ?

Oh, thank you for asking that! The original algorithm (in ESPnet1) doesn't include a duplication check but I wanted to try adding the merging procedure (from ALSD) in #4032, applied at each timestep. Could you please test by replacing the following:

```python
  kept_hyps = sorted(list_b, key=lambda x: x.score, reverse=True)[: self.beam_size]
  #... and
  kept_hyps = sorted(list_b + list_exp, key=lambda x: x.score, reverse=True)[: self.beam_size]
```

with:

```python
  kept_hyps = self.recombine_hyps(sorted(list_b, key=lambda x: x.score, reverse=True))[: self.beam_size]
  # ... and
  kept_hyps = self.recombine_hyps(
         sorted(list_b + list_exp, key=lambda x: x.score, reverse=True)
  )[: self.beam_size]
```

Note that depending on `expansion_gamma` and `expansion_beta` values, the pruning may be aggressive. Thus, you can end-up with 1) less final hypothesis than specified and 2) the final hypothesis will be almost identical.

**Comment by kobenaxie** [comment]
I will try it today.<br>
```
kept_hyps = sorted(self.recombine_hyps(list_b), key=lambda x: x.score, reverse=True)[: self.beam_size]
# ... and
kept_hyps = sorted(self.recombine_hyps(list_b + list_exp), key=lambda x: x.score, reverse=True)[: `self.beam_size
```
Should `recombine_hyps` first, and then `sorted` ?

**Comment by b-flo** [comment]
It shouldn't make a difference in practice but yes, it should be `recombine_hyps` + `sorted` instead of `sorted` + `recombine_hyps` (pruning should be applied at the end anyway). Will change that in #4032.
