### ISSUE TITLE
TTS language ID embedding architecture

### ISSUE THREAD

**Issue by rrr613** [espnet/espnet#4305]
I use the language ID embedding in my model.

I want to know the architecture of it.

What is this architecture reference to?
Where could I read the document?

Thanks

**Comment by kan-bayashi** [comment]
Lang ID -> Embedding layer -> Replicated -> concat with encoder state
https://github.com/espnet/espnet/blob/a3c7c50bccf84c1f40bf79d40bdd735f1b02d79f/espnet2/tts/tacotron2/tacotron2.py#L402-L414
