### ISSUE TITLE
VITS Training on CSMSC corpus from scratch, but bad performance on rhythm at the beginning of a sentence 

### ISSUE THREAD

**Issue by Mortyzhou-Shef-BIT** [espnet/espnet#4308]
VITS Training on CSMSC corpus from scratch, but bad performance on rhythm at the beginning of every sentences，the first words cannot synthesis well, and also with the end words on every sentences. 

we trained to 69epoch now. Is the reason of this issue **untrained**?

**Comment by kan-bayashi** [comment]
Not sure but at first, why don't you check the behavior of the pretrained model?
You can try it on colab.
https://colab.research.google.com/github/espnet/notebook/blob/master/espnet2_tts_realtime_demo.ipynb

**Comment by Mortyzhou-Shef-BIT** [comment]
> Not sure but at first, why don't you check the behavior of the pretrained model? You can try it on colab. https://colab.research.google.com/github/espnet/notebook/blob/master/espnet2_tts_realtime_demo.ipynb

Thank you for your help, I prefer to train a model with **strict=False** in g2p function:
![image](https://user-images.githubusercontent.com/54799259/165081470-d984d991-6557-4aa2-a0b5-aab6529fdfa1.png)
Cause some phonemes with strict=True is not suitable for our corpus. 
For example, “养” map to "yang3", but strict=True to generate "iang3", so some special words generate not suitable.

**Comment by kan-bayashi** [comment]
I see. I'm not familiar with Mandarin, but you can add your own g2p function.
1. make your function by following https://github.com/espnet/espnet/blob/4323c523b4583671346b2d0532b0ddcbb99aa49f/espnet2/text/phoneme_tokenizer.py#L191-L206
2. add elif condition for your new g2p https://github.com/espnet/espnet/blob/4323c523b4583671346b2d0532b0ddcbb99aa49f/espnet2/text/phoneme_tokenizer.py#L385-L388
3. add choice https://github.com/espnet/espnet/blob/4323c523b4583671346b2d0532b0ddcbb99aa49f/espnet2/text/phoneme_tokenizer.py#L17
4. you can use via `--g2p your_own_g2p`

**Comment by Mortyzhou-Shef-BIT** [comment]
> I see. I'm not familiar with Mandarin, but you can add your own g2p function.
> 
> 1. make your function like this: https://github.com/espnet/espnet/blob/4323c523b4583671346b2d0532b0ddcbb99aa49f/espnet2/text/phoneme_tokenizer.py#L191-L206
> 2. add elif condition for your new g2p here: https://github.com/espnet/espnet/blob/4323c523b4583671346b2d0532b0ddcbb99aa49f/espnet2/text/phoneme_tokenizer.py#L385-L388
> 3. add choice of your g2p function: https://github.com/espnet/espnet/blob/4323c523b4583671346b2d0532b0ddcbb99aa49f/espnet2/text/phoneme_tokenizer.py#L17
> 4. you can use via `--g2p your_own_g2p`

Awesome！ Thank you so much!

**Comment by yt605155624** [comment]
Could you please share the training log of vits csmsc?
I want to see the train loss and eval loss's order of magnitude
@[Mortyzhou-Shef-BIT](https://github.com/Mortyzhou-Shef-BIT)

**Comment by yt605155624** [comment]
I reproduce VITS csmsc with paddlepaddle, and have trained for 1000 epoch(about 153000 iter) now, the eval/generator_loss is about 30+ , I want to known if the order of magnitude of loss is correct, I have trained HiFiGAN, the final eval/generator_loss is 24.927, so I think 30+ is normal for vits?
