### ISSUE TITLE
Is it possible in espnet version >= 0.10.6 to configure output of recognition confidence for each word and sentence?

### ISSUE THREAD

**Issue by psydok** [espnet/espnet#4313]
I was able to get the recognition confidence for the entire sentence, but only when the model was initialized with `nbest > 1`. Then I used _softmax_ and got the probabilities. 
But what if `nbest = 1`? Or if I need to gain confidence in every word?

**Comment by kan-bayashi** [comment]
`nbest=1` should have `score`.
https://github.com/espnet/espnet/blob/a3c7c50bccf84c1f40bf79d40bdd735f1b02d79f/espnet2/bin/asr_inference.py#L300
`hyp` has `score` attribute.

**Comment by psydok** [comment]
Can you please tell me how to correctly translate these values ​​into probabilities from 0 to 1?

**Comment by triumph9989** [comment]
> Can you please tell me how to correctly translate these values ​​into probabilities from 0 to 1?
> 
> ```
> >>> nbests[0][-1].scores
> {'decoder': tensor(-11.7745, device='cuda:0'),
>  'lm': tensor(-13.6482, device='cuda:0'),
>  'ctc': tensor(-64.4095, device='cuda:0')}
> ```

Maybe use the sigmoid function?

**Comment by kan-bayashi** [comment]
The score of each module (e.g., 'decoder') is sum of log softmax so applying exp will be probability, but I think it is not meaningful value.

**Comment by psydok** [comment]
I don't know if I'm right in calculating the probability in this way. You can view, pls?
```python
>>> scores = [float(v.cpu().numpy()) for i, v in nbests[0][-1].scores.items()]
>>> sum = np.sum([np.exp(i) for i in scores])
>>> [(np.exp(i)/sum)*100 for i in scores]
[86.68860545760266, 13.311394542397338, 1.1991122815365162e-21]
```

**Comment by kan-bayashi** [comment]
I may misunderstand the value meaning.
Each score represents the sum of log softmax of each components.
What do you want to calculate?
If you want to get the score of sentence, you can use `score` instead of `scores`.

**Comment by psydok** [comment]
I want to get the probability that the recognition is correct (confidence)... But I'm completely confused about the meanings.

**Comment by kan-bayashi** [comment]
>  the probability that the recognition is correct (confidence)

The confidence is `score`.
The `score` is basically calculated in log scale to avoid underflow, and the `score` is calculated by weighted sum of `scores`.

**Comment by AdityaYadavalli1** [comment]
@kan-bayashi is it possible to get word level confidence score from the hypothesis object? Can I get it from the `states` key?

**Comment by b-thebest** [comment]
@AdityaYadavalli1 Have you got any idea about obtaining Word level confidences

**Comment by AdityaYadavalli1** [comment]
@b-thebest
I couldn't get it from ASR directly. However, you can do the following:
1. Get predicted text from the ASR.
2. Next, input predicted text word by word into an aligner to get word level confidence score. 

Hope this helps!

**Comment by ken19980727** [comment]
Hi @AdityaYadavalli1 
Could you explain more detail about aligner
Thanks!
