### ISSUE TITLE
Model deployment issues

### ISSUE THREAD

**Issue by unparalleled-ysj** [espnet/espnet#4318]
How to use C++ to call the trained vits model without relying on the pytorch environment, onnx or torch.jit.trace? Is there an example for reference?

**Comment by Fhrozen** [comment]
once you get the model, you may follow the code written here: https://github.com/royshil/obs-backgroundremoval/tree/main/src
It is completely different, but it can help you to initialize, stream and run the model in CPP.

**Comment by unparalleled-ysj** [comment]
@Fhrozen Thank you for your reply, but my focus is on how to convert the VITS model to onnx format, or use JIT to export, I have found your related work, but you seem to have stopped updating
https://gist.github.com/Fhrozen/60b38bd3ee23492d28b602a0c9f92217?permalink_comment_id=4145051#gistcomment-4145051

**Comment by sw005320** [comment]
See this project
https://github.com/Masao-Someki/espnet_onnx
We can request @Masao-Someki to support TTS

**Comment by unparalleled-ysj** [comment]
@Masao-Someki That's great, looking forward to your support ！

**Comment by unparalleled-ysj** [comment]
@Masao-Someki Hello, how is the progress, is it going well?

**Comment by Masao-Someki** [comment]
@unparalleled-ysj 
I'm working on it now!
I will merge TTS scripts in the next PR, and it will be finished by the end of this week at the latest.

**Comment by Masao-Someki** [comment]
Hi, I'm working on TTS exportation with this PR [#21](https://github.com/Masao-Someki/espnet_onnx/pull/21) and I cannot merge it today. The code can export models and can be used for inference, but there are still some bugs, and the inference result is not correct. (and the code is not yet refactored, so it may be messy.)
I continue to work on this for this week and tell you when it's completed.

**Comment by Masao-Someki** [comment]
Hi @unparalleled-ysj ,
I just finished implementing the TTS model and released it on pypi.
You can export your VITS model as follows:

```python
from espnet2.bin.tts_inference import Text2Speech
from espnet_onnx.export import TTSModelExport

trained = Text2Speech.from_pretrained(<your model>)
m = TTSModelExport()
m.export(trained, 'tag_name', quantize=True)
```
The exported model is located under `${HOME}/.cache/espnet_onnx/<tag_name>`.  I tested with `kan-bayashi/ljspeech_vits`, but if you have any problem with converting your model, please tell me then!

**Comment by sciai-ai** [comment]
@Masao-Someki Can you add onnx support for tacotron2 and fastspeech2

**Comment by Masao-Someki** [comment]
Hi @sciai-ai,
Thank you for your request!
I want to concentrate on model optimization of Transformer and Conformer based models this weekend, so I will add that two models next week.

**Comment by sciai-ai** [comment]
hi @Masao-Someki any news on this. Thanks

**Comment by sciai-ai** [comment]
Can the mbmelgan vocoder is converted to onnx too?

**Comment by Masao-Someki** [comment]
@sciai-ai
No, you cannot export your mbmelgan vocoder. Currently, only hifigan, melgan, and parallell_wavegan are supported.
However, you can export your custom vocoder by modifying the following scripts.
- `espnet_onnx.export.tts.models.__init__.py` to import your custom vocoder.
- `espnet_onnx.export.tts.models.vocoders.<create your vocoder file>` to define your exportation, such as dummy input and output names

**Comment by Jackiexiao** [comment]
do you have any plan to support export espnet model to torchscript/jit?

**Comment by Masao-Someki** [comment]
Currently, I don't have any plan to support torchscript/jit.

**Comment by csukuangfj** [comment]
> How to use C++ to call the trained vits model without relying on the pytorch environment, onnx or torch.jit.trace? 

The original issue is asking about C++ support. It has been marked as closed, but I cannot find
C++ support in https://github.com/espnet/espnet_onnx

Is it possible to run the exported ONNX model with C++?

**Comment by Fhrozen** [comment]
@csukuangfj, As I previously mentioned, you can use the code at https://github.com/royshil/obs-backgroundremoval/tree/main/src as reference.

More specifically, you can use the code at
https://github.com/obs-ai/obs-backgroundremoval/blob/154036cdb18a4934688386c6649630a58dd0e94e/src/background-filter.cpp#L232-L272

For initializing and loading the ONNX model in CPP.
