### ISSUE TITLE
How to make frontend trainable in ESPNet2?

### ISSUE THREAD

**Issue by tarunsaib1997** [espnet/espnet#4334]
**I was using the following conf in front-end part**

frontend: s3prl
frontend_conf:
   frontend_conf:
      upstream: modified_cpc  # Note: If the upstream is changed, please change the input_size in the preencoder.
   download_dir: ./hub
   multilayer_feature: True

preencoder: none
preencoder_conf:
   input_size: 256  # Note: If the upstream is changed, please change this value accordingly.
   output_size: 256

**I ran for two epochs and saw that there are no changes in the frontend weights.**

**Will the gradients back-prop through the modified_cpc model frontend without any changes in the pipeline? If not, can you suggest a way how to do that?**

**Comment by simpleoier** [comment]
@tarunsaib1997 Do you have `freeze_param` in your config file and `frontend` is in the `freeze_param`?

**Comment by tarunsaib1997** [comment]
**Below is the entire conf file content used:**

# This configuration requires Tesla V100-SXM2(32GB) x 16 GPUs It takes about 1.5 days.
batch_type: folded #numel
batch_bins: 5000000 #140000000
batch_size: 8
accum_grad: 2 #1
max_epoch: 100
patience: none
init: none
best_model_criterion:
-   - valid
    - acc
    - max
keep_nbest_models: 10

encoder: conformer
encoder_conf:
    output_size: 512
    attention_heads: 8
    linear_units: 2048
    num_blocks: 12
    dropout_rate: 0.1
    positional_dropout_rate: 0.1
    attention_dropout_rate: 0.1
    input_layer: conv2d
    normalize_before: true
    macaron_style: true
    pos_enc_layer_type: "rel_pos"
    selfattention_layer_type: "rel_selfattn"
    activation_type: "swish"
    use_cnn_module:  true
    cnn_module_kernel: 15

decoder: transformer
decoder_conf:
    attention_heads: 8
    linear_units: 2048
    num_blocks: 6
    dropout_rate: 0.1
    positional_dropout_rate: 0.1
    self_attention_dropout_rate: 0.1
    src_attention_dropout_rate: 0.1

model_conf:
    ctc_weight: 0.3
    lsm_weight: 0.1
    length_normalized_loss: false

optim: adam
optim_conf:
    lr: 0.0015
scheduler: warmuplr
scheduler_conf:
    warmup_steps: 25000

#frontend_conf:
#  n_fft: 512
#  hop_length: 256

frontend: s3prl
frontend_conf:
   frontend_conf:
      upstream: modified_cpc  # Note: If the upstream is changed, please change the input_size in the preencoder.
   download_dir: ./hub
   multilayer_feature: True

preencoder: none
preencoder_conf:
   input_size: 256  # Note: If the upstream is changed, please change this value accordingly.
   output_size: 256

specaug: specaug
specaug_conf:
    apply_time_warp: true
    time_warp_window: 5
    time_warp_mode: bicubic
    apply_freq_mask: true
    freq_mask_width_range:
    - 0
    - 30
    num_freq_mask: 2
    apply_time_mask: true
    time_mask_width_range:
    - 0
    - 40
    num_time_mask: 2

**Comment by simpleoier** [comment]
Did you update to the latest espnet?

**Comment by tarunsaib1997** [comment]
Will try pulling out the latest repo and let you know @simpleoier in a while

**Comment by tarunsaib1997** [comment]
@simpleoier, any suggestions on how to rectify this?

**Comment by tarunsaib1997** [comment]
> **The latest code-repo with the same conf is giving the following error in the training stage**
> 
> File "/home/taruns/.conda/envs/esp/lib/python3.9/runpy.py", line 197, in _run_module_as_main return _run_code(code, main_globals, None, File "/home/taruns/.conda/envs/esp/lib/python3.9/runpy.py", line 87, in _run_code exec(code, run_globals) File "/raid/home/taruns/espnet/espnet2/bin/asr_train.py", line 23, in main() File "/raid/home/taruns/espnet/espnet2/bin/asr_train.py", line 19, in main ASRTask.main(cmd=cmd) File "/raid/home/taruns/espnet/espnet2/tasks/abs_task.py", line 1019, in main cls.main_worker(args) File "/raid/home/taruns/espnet/espnet2/tasks/abs_task.py", line 1315, in main_worker cls.trainer.run( File "/raid/home/taruns/espnet/espnet2/train/trainer.py", line 286, in run all_steps_are_invalid = cls.train_one_epoch( File "/raid/home/taruns/espnet/espnet2/train/trainer.py", line 589, in train_one_epoch loss.backward() File "/home/taruns/.conda/envs/esp/lib/python3.9/site-packages/torch/_tensor.py", line 307, in backward torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs) File "/home/taruns/.conda/envs/esp/lib/python3.9/site-packages/torch/autograd/**init**.py", line 154, in backward Variable._execution_engine.run_backward( RuntimeError: cudnn RNN backward can only be called in training mode

**This got solved by pulling the latest stable release. I am checking the weights updation of the frontend weights with this stable release.**

**Comment by tarunsaib1997** [comment]
@sw005320 @simpleoier **I pulled the latest stable release but the front-end weights are not changing. Can you please help me out?**

**Comment by simpleoier** [comment]
I'll test it.

**Comment by tarunsaib1997** [comment]
Can you use this config?

batch_type: folded #numel
batch_bins: 5000000 #140000000
batch_size: 8
accum_grad: 2 #1
max_epoch: 100
patience: none
init: none
best_model_criterion:
-   - valid
    - acc
    - max
keep_nbest_models: 10

encoder: conformer
encoder_conf:
    output_size: 512
    attention_heads: 8
    linear_units: 2048
    num_blocks: 12
    dropout_rate: 0.1
    positional_dropout_rate: 0.1
    attention_dropout_rate: 0.1
    input_layer: conv2d
    normalize_before: true
    macaron_style: true
    pos_enc_layer_type: "rel_pos"
    selfattention_layer_type: "rel_selfattn"
    activation_type: "swish"
    use_cnn_module:  true
    cnn_module_kernel: 15

decoder: transformer
decoder_conf:
    attention_heads: 8
    linear_units: 2048
    num_blocks: 6
    dropout_rate: 0.1
    positional_dropout_rate: 0.1
    self_attention_dropout_rate: 0.1
    src_attention_dropout_rate: 0.1

model_conf:
    ctc_weight: 0.3
    lsm_weight: 0.1
    length_normalized_loss: false

optim: adam
optim_conf:
    lr: 0.0015
scheduler: warmuplr
scheduler_conf:
    warmup_steps: 25000

#frontend_conf:
#  n_fft: 512
#  hop_length: 256

frontend: s3prl
frontend_conf:
   frontend_conf:
      upstream: modified_cpc  # Note: If the upstream is changed, please change the input_size in the preencoder.
   download_dir: ./hub
   multilayer_feature: False

preencoder: linear
preencoder_conf:
   input_size: 256  # Note: If the upstream is changed, please change this value accordingly.
   output_size: 80

specaug: specaug
specaug_conf:
    apply_time_warp: true
    time_warp_window: 5
    time_warp_mode: bicubic
    apply_freq_mask: true
    freq_mask_width_range:
    - 0
    - 30
    num_freq_mask: 2
    apply_time_mask: true
    time_mask_width_range:
    - 0
    - 40
    num_time_mask: 2

**Comment by simpleoier** [comment]
Hi @tarunsaib1997 ,

**Comment by tarunsaib1997** [comment]
If I comment out that line and rerun the code, the graidents should back-prop right? @simpleoier

**Comment by simpleoier** [comment]
Yes. In my case, the parameters in the frontend have non-zero gradient during back-prop. As a consequence, the optimizer would update the parameters.

**Comment by tarunsaib1997** [comment]
Thanks, will check this out.
