### ISSUE TITLE
Working on multi-lingual branch 

### ISSUE THREAD

**Issue by alirezadir** [espnet/espnet#434]
Hi I would like to try multi-lingual experiments. However, it seems the multilingual branch is not updated to the latest changes of the branch master. Do you think it needs updates or it's in a good working condition?
Also, I see all the egs from master exist there, but isn't it supposed to be tested on a multi lingual dataset such as voxforge?

**Comment by sw005320** [comment]
Are you talking about https://github.com/espnet/espnet/tree/master/egs/li10/asr1 or https://github.com/espnet/espnet/tree/master/egs/jsalt18e2e/asr1? Yes, they are not updated so much, but I think you can do some basic experiments. If you check https://github.com/espnet/espnet/tree/master/egs/li10/asr1, the recipe includes the voxforge data. To run it, we need to run the voxforge recipe (and others if you want) in advance
