### ISSUE TITLE
Float16  or Half precision not supported by torch for training conformer

### ISSUE THREAD

**Issue by tarun73** [espnet/espnet#4340]
Hi,
We tried training an ASR model -

- conformer transducer on 
- espnet 2
- librispeech
- **train_dytpe = Float16**
- torch version - 1.7.1

When we run STAGE: 10 (collect stats) 
we face this error:
`RuntimeError: "arange_cpu" not implemented for 'Half'`

Is float16 supported for ASR training?

**Comment by sw005320** [comment]
Thanks for the report.
It is a bug.
However, we usually use the mixed-precision based on `amp` (`use_amp: true`), which is more stable.
So, I recommend you use this.
