### ISSUE TITLE
Chainer requirement in setup.py

### ISSUE THREAD

**Issue by Ore-an** [espnet/espnet#4342]
Chainer was set as optional and is not installed by default, but some not particularly optional modules using the pytorch backend still import it, such as
espnet/lm/pytorch_backend/lm.py 
espnet/nets/pytorch_backend/e2e_asr.py
espnet/nets/pytorch_backend/e2e_asr_transducer.py

**Comment by sw005320** [comment]
It's optional for espnet2.
