### ISSUE TITLE
Frequently get the index error of my streaming ASR application.

### ISSUE THREAD

**Issue by KennyChiou** [espnet/espnet#4346]
**Describe the bug**
It can work above half times but still could get like "IndexError: index 791 is out of bounds for dimension 0 with size 778".

**Basic environments:**
 - OS information: Linux 4.15.0-142-generic #146~16.04.1-Ubuntu SMP Tue Apr 13 09:27:15 UTC 2021 x86_64
 - python version: 3.8.12 (default, Oct 12 2021, 13:49:34)  [GCC 7.5.0]
 - espnet version: espnet 0.10.5a1
 - Git hash: 285146e5b9f94e1b29e9261b65f67d3fd65ee145
 - Commit date: Sun Dec 19 20:32:04 2021 -0500
 - pytorch version: pytorch 1.7.1+cu101
 

**Environments from `torch.utils.collect_env`:**
```
Collecting environment information...
PyTorch version: 1.7.1+cu101
Is debug build: False
CUDA used to build PyTorch: 10.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 16.04.7 LTS (x86_64)
GCC version: (Ubuntu 4.9.4-2ubuntu1~16.04) 4.9.4
Clang version: Could not collect
CMake version: version 3.12.1

Python version: 3.8 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: GeForce GTX 1080 Ti
Nvidia driver version: 418.56
cuDNN version: /usr/local/cuda-9.0/targets/x86_64-linux/lib/libcudnn.so.7.1.4
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.21.2
[pip3] pytorch-ranger==0.1.1
[pip3] pytorch-wpe==0.0.1
[pip3] torch==1.7.1+cu101
[pip3] torch-complex==0.2.1
[pip3] torch-optimizer==0.3.0
[pip3] torchaudio==0.7.2
[pip3] torchvision==0.8.2+cu101
[conda] _pytorch_select           0.1                       cpu_0  
[conda] blas                      1.0                         mkl  
[conda] cpuonly                   2.0                           0    pytorch
[conda] cudatoolkit               10.1.243             h6bb024c_0  
[conda] mkl                       2021.4.0           h06a4308_640  
[conda] mkl-service               2.4.0            py38h7f8727e_0  
[conda] mkl_fft                   1.3.1            py38hd3c417c_0  
[conda] mkl_random                1.2.2            py38h51133e4_0  
[conda] numpy                     1.20.3                   pypi_0    pypi
[conda] numpy-base                1.21.2           py38h79a1101_0  
[conda] pytorch-mutex             1.0                         cpu    pytorch
[conda] pytorch-ranger            0.1.1                    pypi_0    pypi
[conda] pytorch-wpe               0.0.1                    pypi_0    pypi
[conda] torch                     1.7.1+cu101              pypi_0    pypi
[conda] torch-complex             0.2.1                    pypi_0    pypi
[conda] torch-optimizer           0.3.0                    pypi_0    pypi
[conda] torchaudio                0.7.2                    pypi_0    pypi
[conda] torchvision               0.8.2+cu101              pypi_0    pypi
```

**Task information:**
 - Task: ASR
 - ESPnet2

**Error logs**
```
INFO:werkzeug:140.117.169.197 - - [09/May/2022 13:45:21] "POST /messages1 HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/tpchiou/espnet/tools/anaconda/envs/espnet/lib/python3.8/site-packages/flask/app.py", line 2091, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/tpchiou/espnet/tools/anaconda/envs/espnet/lib/python3.8/site-packages/flask/app.py", line 2076, in wsgi_app
    response = self.handle_exception(e)
  File "/home/tpchiou/espnet/tools/anaconda/envs/espnet/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/tpchiou/espnet/tools/anaconda/envs/espnet/lib/python3.8/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/tpchiou/espnet/tools/anaconda/envs/espnet/lib/python3.8/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/tpchiou/espnet/tools/anaconda/envs/espnet/lib/python3.8/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/tpchiou/espnet/egs2/ibtp/asr1/demo_project/flaskpack/app.py", line 365, in api_message1
    nbests = speech2text1(speech)
  File "/home/tpchiou/espnet/tools/anaconda/envs/espnet/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 26, in decorate_context
    return func(*args, **kwargs)
  File "/home/tpchiou/espnet/espnet2/bin/asr_inference_streaming.py", line 268, in __call__
    nbest_hyps = self.beam_search(
  File "/home/tpchiou/espnet/tools/anaconda/envs/espnet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/tpchiou/espnet/espnet/nets/batch_beam_search_online.py", line 166, in forward
    ret = self.process_one_block(h, block_is_final, maxlen, maxlenratio)
  File "/home/tpchiou/espnet/espnet/nets/batch_beam_search_online.py", line 187, in process_one_block
    best = self.search(self.running_hyps, h)
  File "/home/tpchiou/espnet/espnet/nets/batch_beam_search.py", line 238, in search
    part_scores, part_states = self.score_partial(running_hyps, part_ids, x)
  File "/home/tpchiou/espnet/espnet/nets/batch_beam_search.py", line 181, in score_partial
    scores[k], states[k] = d.batch_score_partial(
  File "/home/tpchiou/espnet/espnet/nets/scorers/ctc.py", line 127, in batch_score_partial
    return self.impl(y, batch_state, ids)
  File "/home/tpchiou/espnet/espnet/nets/ctc_prefix_score.py", line 187, in __call__
    log_psi[si, self.eos] = r_sum[self.end_frames[si // n_hyps], si]
IndexError: index 791 is out of bounds for dimension 0 with size 778
```

**The following is how I call my ASR model**
```
speech2text1 = Speech2TextStreaming(
    asr_train_config = stream_config1,
    asr_model_file = stream_model1,
    lm_train_config = lm_train_config1,
    lm_file =lm_file1,
    token_type="char",
    device="cuda",
    minlenratio=0.0,
    maxlenratio=0.0,
    ctc_weight=0.6,
    beam_size=10, #20
    batch_size=1,
    lm_weight= 0.3,
    nbest=1,
    disable_repetition_detection=True,
    decoder_text_length_limit=0,
    encoded_feat_length_limit=0,
)
  speech, rate = soundfile.read("{}.wav".format('tmp2'))
  nbests = speech2text1(speech)
  text, *_ = nbests[0]
```

**Comment by sw005320** [comment]
Thanks for your report.
@D-Keqi, could you take a look at this error?
Babel is one of the most important recipes, and it would be great if we fix this issue.

**Comment by D-Keqi** [comment]
> Thanks for your report. @D-Keqi, could you take a look at this error? Babel is one of the most important recipes, and it would be great if we fix this issue.

OK!

**Comment by D-Keqi** [comment]
> **Describe the bug** It can work above half times but still could get like "IndexError: index 791 is out of bounds for dimension 0 with size 778".
> 
> **Basic environments:**
> 
> * OS information: Linux 4.15.0-142-generic [Babel recipe #146](https://github.com/espnet/espnet/issues/146)~16.04.1-Ubuntu SMP Tue Apr 13 09:27:15 UTC 2021 x86_64
> * python version: 3.8.12 (default, Oct 12 2021, 13:49:34)  [GCC 7.5.0]
> * espnet version: espnet 0.10.5a1
> * Git hash: [285146e](https://github.com/espnet/espnet/commit/285146e5b9f94e1b29e9261b65f67d3fd65ee145)
> * Commit date: Sun Dec 19 20:32:04 2021 -0500
> * pytorch version: pytorch 1.7.1+cu101
> 
> **Environments from `torch.utils.collect_env`:**
> 
> ```
> Collecting environment information...
> PyTorch version: 1.7.1+cu101
> Is debug build: False
> CUDA used to build PyTorch: 10.1
> ROCM used to build PyTorch: N/A
> 
> OS: Ubuntu 16.04.7 LTS (x86_64)
> GCC version: (Ubuntu 4.9.4-2ubuntu1~16.04) 4.9.4
> Clang version: Could not collect
> CMake version: version 3.12.1
> 
> Python version: 3.8 (64-bit runtime)
> Is CUDA available: True
> CUDA runtime version: Could not collect
> GPU models and configuration: GPU 0: GeForce GTX 1080 Ti
> Nvidia driver version: 418.56
> cuDNN version: /usr/local/cuda-9.0/targets/x86_64-linux/lib/libcudnn.so.7.1.4
> HIP runtime version: N/A
> MIOpen runtime version: N/A
> 
> Versions of relevant libraries:
> [pip3] numpy==1.21.2
> [pip3] pytorch-ranger==0.1.1
> [pip3] pytorch-wpe==0.0.1
> [pip3] torch==1.7.1+cu101
> [pip3] torch-complex==0.2.1
> [pip3] torch-optimizer==0.3.0
> [pip3] torchaudio==0.7.2
> [pip3] torchvision==0.8.2+cu101
> [conda] _pytorch_select           0.1                       cpu_0  
> [conda] blas                      1.0                         mkl  
> [conda] cpuonly                   2.0                           0    pytorch
> [conda] cudatoolkit               10.1.243             h6bb024c_0  
> [conda] mkl                       2021.4.0           h06a4308_640  
> [conda] mkl-service               2.4.0            py38h7f8727e_0  
> [conda] mkl_fft                   1.3.1            py38hd3c417c_0  
> [conda] mkl_random                1.2.2            py38h51133e4_0  
> [conda] numpy                     1.20.3                   pypi_0    pypi
> [conda] numpy-base                1.21.2           py38h79a1101_0  
> [conda] pytorch-mutex             1.0                         cpu    pytorch
> [conda] pytorch-ranger            0.1.1                    pypi_0    pypi
> [conda] pytorch-wpe               0.0.1                    pypi_0    pypi
> [conda] torch                     1.7.1+cu101              pypi_0    pypi
> [conda] torch-complex             0.2.1                    pypi_0    pypi
> [conda] torch-optimizer           0.3.0                    pypi_0    pypi
> [conda] torchaudio                0.7.2                    pypi_0    pypi
> [conda] torchvision               0.8.2+cu101              pypi_0    pypi
> ```
> 
> **Task information:**
> 
> * Task: ASR
> * ESPnet2
> 
> **Error logs**
> 
> ```
> INFO:werkzeug:140.117.169.197 - - [09/May/2022 13:45:21] "POST /messages1 HTTP/1.1" 500 -
> Traceback (most recent call last):
>   File "/home/tpchiou/espnet/tools/anaconda/envs/espnet/lib/python3.8/site-packages/flask/app.py", line 2091, in __call__
>     return self.wsgi_app(environ, start_response)
>   File "/home/tpchiou/espnet/tools/anaconda/envs/espnet/lib/python3.8/site-packages/flask/app.py", line 2076, in wsgi_app
>     response = self.handle_exception(e)
>   File "/home/tpchiou/espnet/tools/anaconda/envs/espnet/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
>     response = self.full_dispatch_request()
>   File "/home/tpchiou/espnet/tools/anaconda/envs/espnet/lib/python3.8/site-packages/flask/app.py", line 1518, in full_dispatch_request
>     rv = self.handle_user_exception(e)
>   File "/home/tpchiou/espnet/tools/anaconda/envs/espnet/lib/python3.8/site-packages/flask/app.py", line 1516, in full_dispatch_request
>     rv = self.dispatch_request()
>   File "/home/tpchiou/espnet/tools/anaconda/envs/espnet/lib/python3.8/site-packages/flask/app.py", line 1502, in dispatch_request
>     return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
>   File "/home/tpchiou/espnet/egs2/ibtp/asr1/demo_project/flaskpack/app.py", line 365, in api_message1
>     nbests = speech2text1(speech)
>   File "/home/tpchiou/espnet/tools/anaconda/envs/espnet/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 26, in decorate_context
>     return func(*args, **kwargs)
>   File "/home/tpchiou/espnet/espnet2/bin/asr_inference_streaming.py", line 268, in __call__
>     nbest_hyps = self.beam_search(
>   File "/home/tpchiou/espnet/tools/anaconda/envs/espnet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
>     result = self.forward(*input, **kwargs)
>   File "/home/tpchiou/espnet/espnet/nets/batch_beam_search_online.py", line 166, in forward
>     ret = self.process_one_block(h, block_is_final, maxlen, maxlenratio)
>   File "/home/tpchiou/espnet/espnet/nets/batch_beam_search_online.py", line 187, in process_one_block
>     best = self.search(self.running_hyps, h)
>   File "/home/tpchiou/espnet/espnet/nets/batch_beam_search.py", line 238, in search
>     part_scores, part_states = self.score_partial(running_hyps, part_ids, x)
>   File "/home/tpchiou/espnet/espnet/nets/batch_beam_search.py", line 181, in score_partial
>     scores[k], states[k] = d.batch_score_partial(
>   File "/home/tpchiou/espnet/espnet/nets/scorers/ctc.py", line 127, in batch_score_partial
>     return self.impl(y, batch_state, ids)
>   File "/home/tpchiou/espnet/espnet/nets/ctc_prefix_score.py", line 187, in __call__
>     log_psi[si, self.eos] = r_sum[self.end_frames[si // n_hyps], si]
> IndexError: index 791 is out of bounds for dimension 0 with size 778
> ```
> 
> **The following is how I call my ASR model**
> 
> ```
> speech2text1 = Speech2TextStreaming(
>     asr_train_config = stream_config1,
>     asr_model_file = stream_model1,
>     lm_train_config = lm_train_config1,
>     lm_file =lm_file1,
>     token_type="char",
>     device="cuda",
>     minlenratio=0.0,
>     maxlenratio=0.0,
>     ctc_weight=0.6,
>     beam_size=10, #20
>     batch_size=1,
>     lm_weight= 0.3,
>     nbest=1,
>     disable_repetition_detection=True,
>     decoder_text_length_limit=0,
>     encoded_feat_length_limit=0,
> )
>   speech, rate = soundfile.read("{}.wav".format('tmp2'))
>   nbests = speech2text1(speech)
>   text, *_ = nbests[0]
> ```

Hi! @KennyChiou Have you ever made some modifications to the code of ESPnet. It seems that the issue is unrelated with streaming system, but related with the CTC prefix score calculation of EOS? I think the way you call your ASR model is right.

**Comment by KennyChiou** [comment]
@D-Keqi Hi, thank you for your help.
I don't remember that I modified "ctc_prefix_score.py".
But I copy the file from another server, and the same error still exists.

**Comment by yotaro-shimose** [comment]
I found that passing "cuda:1" as "device" parameter to CTCSegmentation Class will result in this "index -415 out of bounds" error.
"device" is a wrong parameter for CTCSegmentation, but I thought it would be valid parameter because it works for Speech2Text class. And if you pass it as keyword arguments, no specific error will be raised before you get this index out of bounds error.

My environment:
OS: ubuntu18.04 inside nvidia docker container
GPU: 4 x RTX 3090

Code to reproduce:
```python
def ctc_segmentation(wav_path: Path, sentenses: list[str], device: str):
    d = ModelDownloader()
    wsjmodel = d.download_and_unpack("kamo-naoyuki/wsj")
    speech, rate = soundfile.read(wav_path)
    aligner = CTCSegmentation(
        **wsjmodel, fs=rate, gratis_blank=True, kaldi_style_text=False, device=device
    )
    segments = aligner(speech, sentenses)
```


I'm not sure this is related to this issue, but it should be noted that passing wrong parameters might cause this issue.
**I also suggest to make sure that basic modules like CTCSegmentation and Speech2Text have the same interface for controlling device.**

I love this awesome open source framework. Hope this saves someone's time.
