### ISSUE TITLE
speeding up training Tacotron 2with multiple GPUs 

### ISSUE THREAD

**Issue by AliNGatGeeks** [espnet/espnet#4353]
Hi 

I am using 4GPUs for training TTS model and I have 24G ram on each GPU.  
To speech up the process I changed the number of batch bins from 5120000 to 20400000 however, I didnt gain any speed!

what do I need to change in the setting to get best speed up? 
this is my GPU utilization 

![GPU util](https://user-images.githubusercontent.com/96764993/167698231-f59c1ef6-d14b-45d5-8c0a-918100e17767.png)

in all cases each epoch takes around 14-16minutes

**Comment by kan-bayashi** [comment]
Please attach your config.

**Comment by kan-bayashi** [comment]
If you use the default one, you can find the following parameters:
https://github.com/espnet/espnet/blob/beb3360276aa9ff65fe84f4c5e99c0c063c2a6be/egs2/ljspeech/tts1/conf/tuning/train_tacotron2.yaml#L56-L57
`num_iters_per_epoch` decides the number of iterations of each epoch, so in the above case, the total iterations will be 500 * 200 = 100,000.
This iteration value is independent from the batch size.
So in your case, even if you increase the batch bins, the total number of iterations is not changed, and therefore, the required time is not changed.

**Comment by kan-bayashi** [comment]
If you still have a question, please re-open.

**Comment by Jackiexiao** [comment]
I am still confuse, why increase the batch bins, but batch size per gpu is not changed.

**Comment by kan-bayashi** [comment]
> each gpu will process #batch / #gpus batch
