### ISSUE TITLE
using ESPNet2 (not ESPNet1) as a library

### ISSUE THREAD

**Issue by WZLHQ** [espnet/espnet#4363]
Could you please give me a example that using ESPNet2 as a library. 
Thanks!

**Comment by ftshijt** [comment]
We have a range of demo in colab at https://github.com/espnet/espnet#readme you may refer those for using espnet2 as a library

**Comment by WZLHQ** [comment]
> We have a range of demo in colab at https://github.com/espnet/espnet#readme you may refer those for using espnet2 as a library

Thanks!

**Comment by kan-bayashi** [comment]
@WZLHQ If you satisfied, please close the issue by yourself.
