### ISSUE TITLE
Question on check_short_utt

### ISSUE THREAD

**Issue by akreal** [espnet/espnet#4366]
I use `Conv2dSubsampling2` and have a tensor of size `[1, 5, 80]` that can not be processed by this subsampling module. If I pad it to `[1, 7, 80]`, then it works, but with `[1, 6, 80]` it does not, so I assume the minimum length is 7 frames for `Conv2dSubsampling2`. However, `check_short_utt` requires it to be at least 3 frames:
https://github.com/espnet/espnet/blob/afa8f8ec5b8ec77deb1a3c1531915ebbee7b80e6/espnet/nets/pytorch_backend/transformer/subsampling.py#L33-L34
Should it be changed to 7 or I get something wrong?

**Comment by ftshijt** [comment]
Thanks for your investigation. I think it should be a bug here. When I was adding this check, I checked the other cases but not this one. Since it has two 3-kernel without padding, 7 should be a valid number. Could you start a PR to fix the issue?

**Comment by akreal** [comment]
Thank you for the answer! Sure, will do.
