### ISSUE TITLE
Possible error with number of returned values in transformer encoder.

### ISSUE THREAD

**Issue by Ore-an** [espnet/espnet#4368]
I'm not sure if development in espnet1 is still ongoing, but I found that in this line:

https://github.com/espnet/espnet/blob/afa8f8ec5b8ec77deb1a3c1531915ebbee7b80e6/espnet/nets/pytorch_backend/e2e_asr_transformer.py#L193

The transformer expects hs_intermediates to be returned by the encoder in every case. Looking at the encoder code, if the intermediate layers are not specified, it will return 2 values instead of 3:

https://github.com/espnet/espnet/blob/afa8f8ec5b8ec77deb1a3c1531915ebbee7b80e6/espnet/nets/pytorch_backend/transformer/encoder.py#L344-L346

This would result in a crash, since it would be unable to unpack 3 values. Returning a None or an empty list might be fine because if you don't set intermediate_ctc_weight the hs_intermediates won't be used for anything in the e2e_asr_transformer forward.

**Comment by sw005320** [comment]
Thanks for the report.
@YosukeHiguchi, could you check this issue?
