### ISSUE TITLE
[Question] LibriSpeech ASR recipe with wav2vec2.0

### ISSUE THREAD

**Issue by bofenghuang** [espnet/espnet#4386]
Hello,

Could you please tell me where I can find the results of this recipe [train_asr_transformer3_w2v_large_lv60_960h_finetuning_last_1layer](https://github.com/espnet/espnet/blob/master/egs2/librispeech/asr1/conf/tuning/train_asr_transformer3_w2v_large_lv60_960h_finetuning_last_1layer.yaml) on the librispeech ? Is there a big difference from the other wav2vec recipe [train_asr_conformer7_wav2vec2_960hr_large](https://github.com/espnet/espnet/blob/master/egs2/librispeech/asr1/conf/tuning/train_asr_conformer7_wav2vec2_960hr_large.yaml) ?
I'm trying to launch an ASR recipe on a french dataset of ~200h and would like to know which one I should use.

cc @sw005320 @simpleoier 

Thanks in advance :)

**Comment by simpleoier** [comment]
Sorry, there is no result for the first config. 
The first config uses wav2vec2 as the encoder and finetune only the last layer during training. The second config uses wav2vec2 as the frontend (feature extraction) and the parameters are fixed. I suggest you to use the second config, and also try the some other techniques (like changing upstream model to xls-r, use [fused](https://espnet.github.io/espnet/_gen/espnet2.asr.html?highlight=fuse#module-espnet2.asr.frontend.fused), or [transfer learning](https://espnet.github.io/espnet/notebook/espnet2_asr_transfer_learning_demo.html)).
