### ISSUE TITLE
[Question] Training TTS model on English word input instead of Char/Phones

### ISSUE THREAD

**Issue by jefflai108** [espnet/espnet#4388]
Hi, 

Is it possible to train TTS models on word-level inputs? I see the default options are either character / phone inputs. What would be the difficulties of training such TTS models? 

Thanks!

**Comment by kan-bayashi** [comment]
In terms of the implementation, that can be even if with the current implementation.
Prepare `text` as word split by space and use `token_type=phn` and `g2p=none`.

Basically, TTS dataset is not so large (in the case of single speaker around 10 ~ 100 hours).
Such a case, word representations are too sparse so I think it is impossible with only word representations as the inputs.
