### ISSUE TITLE
longformer report an error

### ISSUE THREAD

**Issue by Uriel-w** [espnet/espnet#4389]
Excuse me, when running the source code longformer, there will be a problem that xs_pad.size(1) is greater than olens.max(). Is there any problem with the source code?

![cd171e2b498e3ba5f8607f7dc53282d](https://user-images.githubusercontent.com/60969278/170044634-71b8d4fa-4f6f-4a1d-a674-2e2d0b025c7f.png)

**Comment by sw005320** [comment]
Which data (recipes) are you using?
Do you make it work with the other network, e.g., transformer/conformer?
