### ISSUE TITLE
Dead link described in espnet1 jsut-based pretrained tts installer

### ISSUE THREAD

**Issue by supikiti** [espnet/espnet#4390]
I tried to install the pretrained tts model, jsut.24k.phn.transformer, by using [this codes](https://github.com/espnet/espnet/blob/047d0c474c18a87c205e566948410be16787e477/egs/jvs/tts1/run.sh#L73). 
However, I could not install it. 
Could you please check if the link is valid ? 
Or could you tell me if I can install it in another way ?

**Comment by kan-bayashi** [comment]
Sorry, this is my fault. I changed permission.
BTW, ESPnet1-TTS (egs/*/tts1) is deprecated, so I recommend trying `egs2/*/tts1`.
