### ISSUE TITLE
Espnet2 inference Profile

### ISSUE THREAD

**Issue by srikanthk20** [espnet/espnet#4395]
Hi, 
I am trying to infer the CTC+Attention network with the following two different configuration in Espnet2

Config1:
---------
beam_size: 5
ctc_weight: 0.0
lm_weight: 0.0

Config2:
---------
beam_size: 5
ctc_weight: 1.0
lm_weight: 0.0

For a particular test data set the Config1 take ~170sec and for the same dataset the Config2 takes ~350sec.
Is it expected that the ctc_weight: 1.0 (CTC only decoding) will take double the time as  ctc_weight: 0.0 (Attention only decoding). Since the ctc_weight: 0.0 is recursive in nature, shouldnt it take more time

**Comment by sw005320** [comment]
Thanks for raising the question.
This is an important behavior in joint CTC/attention and I'll explain it in a bit more detail for our future reference.

This is related to whether we use the pre beam or not for CTC prefix score calculations.
First, CTC prefix score calculations are heavy.
To remove the computations, our joint CTC/attention decoding only performs the CTC prefix score calculations for limited hypotheses obtained by the main attention decoding.

However, in the pure CTC mode, we cannot use the limited hypotheses obtained by the main attention decoding.
Therefore, the CTC prefix score calculations are performed for all hypotheses (full vocabulary).
This is the reason that the pure CTC mode takes longer computation time especially when the vocabulary size is large.

FYI, this part switches the full vocabulary (pure CTC) or limited vocabulary (CTC/attention with the pre beam)
https://github.com/espnet/espnet/blob/b008ac7d58e9ced1a9f8c89cc85ee69d9e9461ab/espnet2/bin/asr_inference.py#L190
Actual pre beam setups (`part_ids`) are written in https://github.com/espnet/espnet/blob/b008ac7d58e9ced1a9f8c89cc85ee69d9e9461ab/espnet/nets/beam_search.py#L289-L303

There are two solutions.
1. use the K2 CTC decoder.
2. to implement a time-synchronous CTC decoder.

We're planning to implement a time-synchronous CTC decoder.
