### ISSUE TITLE
tensorboard graphs

### ISSUE THREAD

**Issue by nellorebhanuteja** [espnet/espnet#4410]
In the current setup when I type 
```
tensorboard --logdir <log_dir>
```

i can visualize model training progress.
Can i also generate tensorboard graphs?
It will help me understand the architecture of underlying model

**Comment by kamo-naoyuki** [comment]
No, it's not supported. I'll consider it.

**Comment by nellorebhanuteja** [comment]
@kamo-naoyuki 

thanks for the update
I am trying to run tacotron2 training on LJSpeech
I am still not able to see graphs

**Comment by kamo-naoyuki** [comment]
Tensorboard graph is not always added because it depends on torch script.  If it's failed, there are no ways to see it.

> Also the training has failed

Oh... I'll check it.

**Comment by nellorebhanuteja** [comment]
I also noticed the GPU usage is going to 100 % and stagnating there

**Comment by kamo-naoyuki** [comment]
> Also the training has failed


I fixed it.

**Comment by kamo-naoyuki** [comment]
Once again, tensorboard graph is not always added. If it's failed, it is impossible to add the graph.
