### ISSUE TITLE
"datasets/wideband/acoustic_params_wideband" and "datasets/wideband/dev_testset_wideband/track1" are required for DNS challenge recipe

### ISSUE THREAD

**Issue by kamo-naoyuki** [espnet/espnet#4414]
The  local/data.sh for dns_ins21 recipe says that "datasets/wideband/acoustic_params_wideband" and "datasets/wideband/dev_testset_wideband/track1" are required.

https://github.com/espnet/espnet/blob/45e8cb9173a072f85ee7a7ccbcae06af7c5c484a/egs2/dns_ins21/enh1/local/data.sh#L22

I couldn't find any clues to get them.  Could you tell me how to get them? I'm not familiar with DNS challenge.

**Comment by YoshikiMas** [comment]
You could find them from [interspeech/adddata branch](https://github.com/microsoft/DNS-Challenge/tree/interspeech2021/adddata/datasets). I will add this description in data.sh.
