### ISSUE TITLE
how to calcualating asr recognition confidence

### ISSUE THREAD

**Issue by luweishuang** [espnet/espnet#442]
I need to calcualate  recognition confidence just like other asr engine do, but I don't know how to do it , Would somebody gave some advice about this?

**Comment by ShigekiKarita** [comment]
Hi,

If you are talking about the decoding score like `log P_encdec(y|x) + log P_ctc(y|x) + log P_lm(y)`,
https://github.com/espnet/espnet/blob/95eb4be0245d4c9acb7b89cef9ef3e330e168d83/src/nets/e2e_asr_th.py#L2148

this function saves the n-best metrics in somewhere like `egs/wsj/exp/train_xxx/decode_yyy/data.json`
https://github.com/espnet/espnet/blob/95eb4be0245d4c9acb7b89cef9ef3e330e168d83/src/asr/asr_utils.py#L424
