### ISSUE TITLE
Bengali TTS Model Using LJSpeech Recipe - Attention Plots Are Not Diagonal - Decoded Clips Are Totally Silent

### ISSUE THREAD

**Issue by dv66** [espnet/espnet#4421]
Hello,

We have been using Espnet successfully for Bengali ASR training for about 2 years now. 

Currently we are trying to train a Bengali TTS model using LJSpeech/tts1 recipe. We are using [https://github.com/espnet/espnet/blob/master/egs/ljspeech/tts1/conf/tuning/train_pytorch_transformer.v1.single.yaml](url) with a reduced batch size (batch_bins: 341550) due to smaller video memory (8G VRAM RTX 3070). For other configs, defaults are used.

But it seems the model training is not going OK. The generated attention plots are either blank or non-diagonal (random patterns) like these:
![image](https://user-images.githubusercontent.com/16955174/171907302-12ca4c90-7566-4648-b075-48d222960fed.png)
![image](https://user-images.githubusercontent.com/16955174/171907409-1773e388-d335-4bad-8b70-609f5ec35706.png)

The fbank-coefficient plots look somewhat normal:
![image](https://user-images.githubusercontent.com/16955174/171907549-3b2c5faf-6252-4efb-adca-cc60eeee65c0.png)

The loss curves are going like this:
![image](https://user-images.githubusercontent.com/16955174/171907690-cc201fa5-d2a5-49bf-b131-a9f3277be9ee.png)

## Audio File Statistics compared with LJSpeech Dataset
The table below shows the comparison of dataset statistics between the LJSpeech English dataset and Our (Bengali) Audio Dataset. Our dataset is a **multi-speaker** (815 speakers in total) audio dataset.
![image](https://user-images.githubusercontent.com/16955174/171913809-6b1ad7ea-6645-41c8-a6e5-d04c681f8817.png)

## Audio File properties 
A sample audio file in our dataset has these properties:
![image](https://user-images.githubusercontent.com/16955174/171914089-5b0652b9-3e45-4887-8481-9b3a67d88c18.png)

## metadata.csv File (sample lines)
We follow LJSpeech's metadata.csv format.
- non linguistic symbols are removed from text 
- numbers are converted to words

```
LJ0000000000|ব্রিটিশ লেবার পার্টির নেতা এড মিলিব্যান্ড বলেছেন টনি বেন ছিলেন আমাদের সময়ের একজন উজ্জ্বল ব্যক্তিত্ব|ব্রিটিশ লেবার পার্টির নেতা এড মিলিব্যান্ড বলেছেন টনি বেন ছিলেন আমাদের সময়ের একজন উজ্জ্বল ব্যক্তিত্ব
LJ0000000001|তেত্রিশ হাজার টিকিটের মধ্যে মাত্র পাঁচ হাজার টিকিট সাধারণ মানুষের জন্য বরাদ্দ করায় বিক্ষুব্ধ ভক্তরা বিক্ষোভও করে|তেত্রিশ হাজার টিকিটের মধ্যে মাত্র পাঁচ হাজার টিকিট সাধারণ মানুষের জন্য বরাদ্দ করায় বিক্ষুব্ধ ভক্তরা বিক্ষোভও করে
LJ0000000002|বাংলাদেশের পোশাক খাতে একের পর এক ভয়াবহ দুর্ঘটনায় তারা মানুষকে সহজে বোঝাতে পারছে এত সস্তায় কাপড় কিভাবে আসছে|বাংলাদেশের পোশাক খাতে একের পর এক ভয়াবহ দুর্ঘটনায় তারা মানুষকে সহজে বোঝাতে পারছে এত সস্তায় কাপড় কিভাবে আসছে
LJ0000000003|শেষ পর্যন্ত সমাবেশ ও হরতাল কর্মসূচি স্থগিত করার পর লোকজনের মধ্যে কিছুটা স্বস্তি ফিরে এসেছে|শেষ পর্যন্ত সমাবেশ ও হরতাল কর্মসূচি স্থগিত করার পর লোকজনের মধ্যে কিছুটা স্বস্তি ফিরে এসেছে
LJ0000000004|দেশটির সেনা প্রধান স্থানীয় সময় রাত দশ থেকে ভোর পাঁচটা পর্যন্ত এই কারফিউ বলবত রাখার আদেশ দেন|দেশটির সেনা প্রধান স্থানীয় সময় রাত দশ থেকে ভোর পাঁচটা পর্যন্ত এই কারফিউ বলবত রাখার আদেশ দেন
LJ0000000005|বিশেষ করে ড্যান্ডি নামক এক ধরনের নতুন এবং সহজলভ্য মাদকে আসক্ত হয়ে পড়েছে এসব শিশুরা|বিশেষ করে ড্যান্ডি নামক এক ধরনের নতুন এবং সহজলভ্য মাদকে আসক্ত হয়ে পড়েছে এসব শিশুরা
```

## run.sh configurations
```
# feature extraction related
fs=22050      # sampling frequency
fmax=7600     # maximum frequency
fmin=80       # minimum frequency
n_mels=80     # number of mel basis
n_fft=1024    # number of fft points
n_shift=256   # number of shift points
win_length="" # window length

# char or phn
# In the case of phn, input transcription is convered to phoneem using https://github.com/Kyubyong/g2p.
trans_type="char"

# decoding related
model=model.loss.best
n_average=1 # if > 0, the model averaged with n_average ckpts will be used instead of model.loss.best
griffin_lim_iters=64  # the number of iterations of Griffin-Lim
```

A notable observation is that the text set prepared during the dataset preparation stage contains non Bengali characters but the latin characters make the similar pronunciation. Like this:
```
LJ0000000000 BRITTISH LEBAAR PAARTTIR NETAA EDD MILIBYAANDD BLECHEN TTNI BEN CHILEN AAMAADER SMY'ER EKJN UJJBL BYKTITB
LJ0000000001 TETRISH HAAJAAR TTIKITTER MDHYE MAATR PAANC HAAJAAR TTIKITT SAADHAARNN MAANUSSER JNY BRAADD KRAAY' BIKSSUBDH BHKTRAA BIKSSOBHO KRE
```

We also tried the tacotron2 config but still it is producing attention plots which are non-diagonal  and "silence-only" audio clips after decoding. We badly need your direction on this. 

Thanks in advance.

**Comment by kan-bayashi** [comment]
I leave some comments:
- `egs/*/tts1` is deprecated. It is better to switch `egs2/*/tts1` (ESPnet2 based)
- Please check the following points https://github.com/espnet/espnet/tree/master/egs2/TEMPLATE/tts1#why-the-model-cannot-be-trained-well-with-my-own-dataset
- Please check the related issues
  - https://github.com/espnet/espnet/issues/2327
  - https://github.com/espnet/espnet/issues/2565 
- `non linguistic symbols` like pause is very important for TTS. Re-consider the preprocessing.

**Comment by dv66** [comment]
Thank you very much. It seems there was silence at both ends of the audio files. After trimming those, we are seeing TTS audios are generated - attention plots are much better. (Although the audio files sounds a bit robotic)

**Comment by kan-bayashi** [comment]
> Although the audio files sounds a bit robotic

This is because the outputs are generated by Griffin-LIm.
Please combine with neural vocoder.
