### ISSUE TITLE
Question about Speech2TextStreaming

### ISSUE THREAD

**Issue by Macsim2** [espnet/espnet#4429]
Hi, I'm trying to train Speech2TextStreaming model using Speech2Text params which use LegacyRelPositionMultiHeadedAttention with ConformerEncoder
pos_emb is missing during forwarding self-attention layer..
So. my question below are
1. For using Speech2TextStreaming, is it essential to use MultiHeadedAttention..?
2. If not 1. answer is false, what should i do..?

**Comment by Macsim2** [comment]
@sw005320 Thank your response.

I didn't mean to.. 
I see my train config now that "rel_pos_type:latest" option is missing
I think that's why LegacyRelPositionMultiHeadedAttention was used though I wrote "selfattention_layer_type: rel_selfattn"

As your question, is it proper to use RelPositionMultiHeadedAttention in my situation?

**Comment by Macsim2** [comment]
I Have additional question..
I use TransducerDecoder but stopped because of below codes
`non_batch = [
            k
            for k, v in beam_search.full_scorers.items()
            if not isinstance(v, BatchScorerInterface)
        ]
assert len(non_batch) == 0
`
in espnet2/bin/asr_inference_streaming.py
this codes mean that non_batch scorers have to be None. but TransducerDecoder was non_batch
So how can i use TransducerDecoder with Speech2TextStreaming..?

**Comment by sw005320** [comment]
> As your question, is it proper to use RelPositionMultiHeadedAttention in my situation?

Yes, it is proper to use RelPositionMultiHeadedAttention. Legacy one is not maintained.

**Comment by sw005320** [comment]
> I Have additional question.. I use TransducerDecoder but stopped because of below codes `non_batch = [ k for k, v in beam_search.full_scorers.items() if not isinstance(v, BatchScorerInterface) ] ` `assert len(non_batch) == 0` in espnet2/bin/asr_inference_streaming.py this codes mean that non_batch scorers have to be None. but TransducerDecoder was non_batch To inference Speech2TextStreaming class with TransducerDecoder using espnet2/bin/asr_inference_streaming.py is not available..? how can i use TransducerDecoder with Speech2TextStreaming..?

We do not have the implementation yet since TransducerDecoder does not use the ScorerInterface interface.

**Comment by Macsim2** [comment]
I appreciate your reply..!
I hope the implementation will be completed ASAP
