### ISSUE TITLE
Why not use normalized text for kss recipe?

### ISSUE THREAD

**Issue by imdanboy** [espnet/espnet#4440]
Although normalizing korean text (such as digit or english --> valid korean) is supported by `g2pk` implicitly or by `korean_cleaner` explictly, it does not guarantee the result match the recorded text.
For example, digit conversion for 1/1_0033.wav by `korean_cleaner` is wrong in that the digit is recorded as "이십" actually.
```
정신분석학은 20세기에 급격히 발전했다. # original text
정신분석학은 이영세기에 급격히 발전했다. # result of korean_cleaner
정신분석학은 이십 세기에 급격히 발전했다. # normalized text (actually pronounced by the speaker)
```

Since kss dataset (https://www.kaggle.com/datasets/bryanpark/korean-single-speaker-speech-dataset) already provide normalized text as the third column of transcript.v.1.4.txt, using normalized text is as simple as modifying the line 
https://github.com/espnet/espnet/blob/master/egs2/kss/tts1/local/data_prep.sh#L45
```
awk -F "|" -v spk=kss '{print spk "_" $1 " " $2}' | # before
awk -F "|" -v spk=kss '{print spk "_" $1 " " $3}' | # after
```

**Comment by kan-bayashi** [comment]
I agree with your suggestion. Let us use the normalized one.
