### ISSUE TITLE
Can we replicate fbank-pitch results for WSJ dataset in ESPNET2 as in ESPNet?

### ISSUE THREAD

**Issue by tarunsaib1997** [espnet/espnet#4443]
***Claimed fbank-pitch results for WSJ with conformer setup as in paper***
--> dev93/ eval92 -- 7.7 / 5.3

***Tried replicating the resutls of WSJ Conformer recipe with ESPNet2 recipe***
--> Results we got -- 17.2/14.8
**Attaching the config files used**

**Train Config:**

batch_type: folded
batch_bins: 5000000 #140000000
batch_size: 8
accum_grad: 2 
max_epoch: 100
patience: none
init: none
best_model_criterion:
-   - valid
    - acc
    - max
keep_nbest_models: 10

encoder: conformer
encoder_conf:
    output_size: 512
    attention_heads: 8
    linear_units: 2048
    num_blocks: 12
    dropout_rate: 0.1
    positional_dropout_rate: 0.1
    attention_dropout_rate: 0.1
    input_layer: conv2d
    normalize_before: true
    macaron_style: true
    pos_enc_layer_type: "rel_pos"
    selfattention_layer_type: "rel_selfattn"
    activation_type: "swish"
    use_cnn_module:  true
    cnn_module_kernel: 15

decoder: transformer
decoder_conf:
    attention_heads: 8
    linear_units: 2048
    num_blocks: 6
    dropout_rate: 0.1
    positional_dropout_rate: 0.1
    self_attention_dropout_rate: 0.1
    src_attention_dropout_rate: 0.1

model_conf:
    ctc_weight: 0.3
    lsm_weight: 0.1
    length_normalized_loss: false

optim: adam
optim_conf:
    lr: 0.0015
scheduler: warmuplr
scheduler_conf:
    warmup_steps: 25000

frontend_conf:
  n_fft: 512
  hop_length: 256

specaug: specaug
specaug_conf:
    apply_time_warp: true
    time_warp_window: 5
    time_warp_mode: bicubic
    apply_freq_mask: true
    freq_mask_width_range:
    - 0
    - 30
    num_freq_mask: 2
    apply_time_mask: true
    time_mask_width_range:
    - 0
    - 40
    num_time_mask: 2

**Decode Config:**
lm_weight: 1.2
beam_size: 20
penalty: 0.0
maxlenratio: 0.0
minlenratio: 0.0
ctc_weight: 0.3

**Can anyone help this out?**

**Comment by tarunsaib1997** [comment]
We have used the configuration that were put in this [conformer paper](https://arxiv.org/pdf/2010.13956.pdf). Also I have pasted the entire training and decoding configurations used in the first comment of this issue itself. I want to replicate the results that were produced in paper mentioned.

**Comment by sw005320** [comment]
I recommend you start from our config file.
We have tried the config in the conformer paper, but we did not get enough performance.

> Can you please point out to the config files of conformer recipe with fbank-pitch features used for WSJ corpus in this [paper](https://arxiv.org/pdf/2010.13956.pdf)?

This is an espnet1 config.
https://github.com/espnet/espnet/blob/master/egs/wsj/asr1/RESULTS.md

**Comment by Akash182004** [comment]
Great
