### ISSUE TITLE
No information about remaining time in train.log

### ISSUE THREAD

**Issue by Yerzhaisang** [espnet/espnet#4444]
I believe in the log file there should be information about left time. I left below the full content of train.log.

python3 -m espnet2.bin.lm_train --ngpu 1 --use_preprocessor true --bpemodel none --token_type char --token_list data/kz_token_list/char/tokens.txt --non_linguistic_symbols none --cleaner none --g2p none --valid_data_path_and_name_and_type dump/raw/dev/text,text,text --valid_shape_file exp/lm_stats_kz_char/valid/text_shape.char --fold_length 150 --resume true --output_dir exp/lm_train_lm_transformer_kz_char --config conf/train_lm_transformer.yaml --train_data_path_and_name_and_type dump/raw/lm_train.txt,text,text --train_shape_file exp/lm_stats_kz_char/train/text_shape.char --ngpu 1 --multiprocessing_distributed True 
Started at Tue Jun 14 11:03:52 +06 2022

WARNING:root:Torch AMP is not available on this platform
/raid/yerzhaisang_taskali/my_work/espnet/tools/anaconda/envs/espnet/bin/python3 /raid/yerzhaisang_taskali/my_work/espnet/espnet2/bin/lm_train.py --ngpu 1 --use_preprocessor true --bpemodel none --token_type char --token_list data/kz_token_list/char/tokens.txt --non_linguistic_symbols none --cleaner none --g2p none --valid_data_path_and_name_and_type dump/raw/dev/text,text,text --valid_shape_file exp/lm_stats_kz_char/valid/text_shape.char --fold_length 150 --resume true --output_dir exp/lm_train_lm_transformer_kz_char --config conf/train_lm_transformer.yaml --train_data_path_and_name_and_type dump/raw/lm_train.txt,text,text --train_shape_file exp/lm_stats_kz_char/train/text_shape.char --ngpu 1 --multiprocessing_distributed True

**Comment by seastar105** [comment]
Left train time would appear after training 1 epoch maybe? https://github.com/espnet/espnet/blob/43ce0c69fb32961235534b348700dc6c74ad5792/espnet2/train/trainer.py#L261

**Comment by Yerzhaisang** [comment]
> Left train time would appear after training 1 epoch maybe?
> 
> https://github.com/espnet/espnet/blob/43ce0c69fb32961235534b348700dc6c74ad5792/espnet2/train/trainer.py#L261

thank you for your comment. However, there is already 18 epoch

**Comment by Yerzhaisang** [comment]
Thank you. The issue was solved by re-installation
