### ISSUE TITLE
unidirectional lstm do not convergence

### ISSUE THREAD

**Issue by fanlu** [espnet/espnet#445]
I want to use unidirectional lstm in network structure due to on line decoder, but add param bidirectional=False to Class BLSTM or BLSTMP made network unconvergece, Have you met this problem? @sw005320 
this is my env below: base on kaldi aishell dataset
```
./run.sh --stage 4 --queue g.q --etype vgglstm --maxlen_in 1000 --epochs 30 --elayers 5
29          29100       75.7932     97.4162        54.1703        81.2621               100.726                   61.7985                   0.545857    0.514054             26025.4       1e-50
./run.sh --stage 4 --queue g.q --etype vgglstmp --maxlen_in 1000 --epochs 30 --elayers 5
29          29100       68.2759     83.0502        53.5016        73.6391               85.6171                   61.661                    0.559013    0.527418             27662.8       1e-36
```

**Comment by sw005320** [comment]
I did not try it personally, but someone told me that they tried, but they did not report like that. It seems that the encoder is not trained well anyway. Can you try it with a shallow network? You could also increase the number of units in the LSTM by following Librispeech or WSJ recipe.

**Comment by fanlu** [comment]
yes, I setted elayers 3 and 1, the results seems very well like vggblstm and vggblstmp.
But why 5 elayers lstm or lstmp will lead to the acc around 0.5 in two epochs and can't decrease more in the last 28 epochs, seems to be a local minimum, and the local minimun are same when runing many exps use same default config

**Comment by fanlu** [comment]
I also set mtlalpha to 0 and 1, this two mode both can converge. both loss seems very smaller.
another question: why ctc only mode do not output main/acc and validation/main/acc?
@sw005320 
```
./run.sh --stage 4 --queue g.q --etype vgglstm --maxlen_in 1000 --epochs 30 --elayers 5 --mtlalpha 0
15          15100       2.35731                    2.35731        9.87785                                         9.87785                   0.980437    0.907387             12165.7       1e-08
./run.sh --stage 4 --queue g.q --etype vgglstm --maxlen_in 1000 --epochs 30 --elayers 5 --mtlalpha 1
15          15100       10.2104     10.2104                       13.5837               13.5837                                                                              8185.24       1e-08
```

**Comment by sw005320** [comment]
Simply because we don't implement it. Using a beam search would be a bit heavy, but we can do it by using greedy search of CTC (frame-by-frame argmax, and convert it to the corresponding label sequence.)

**Comment by fanlu** [comment]
mtlalpha equal 0 or 1 can converge, but why default 0.5 can not converge?
