### ISSUE TITLE
Is it possible to make mini-batch with speaker-equally sampled without reformatting data folder explicitly?

### ISSUE THREAD

**Issue by seastar105** [espnet/espnet#4458]
I'm trying to make finetuning pipeline using espnet2-tts, now, and wanna do some experiment on finetuning. 

From [Adapting TTS models For New Speakers using Transfer Learning](https://arxiv.org/abs/2110.05798), making mini-batch contain same sample number of original speaker and new speaker helps finetuning with single speaker model.

For example, when finetuning fintuning model trained on ljspeech to new Speaker A. Make mini-batch half of ljspeech sample, and another half new speaker's sample.

Of course it can be done manipulating data/ or dump/ explicitly and train with unsorted batches. but is there any programmatic way to make batches like this in espnet? if not, some hints for implementing this functionality? I'm gonna try then

**Comment by kan-bayashi** [comment]
I think it can be done by implementing sampler function.
https://github.com/espnet/espnet/tree/master/espnet2/samplers
And add it to build_batch_sampler's choice.
https://github.com/espnet/espnet/blob/305e974e553ec0b36c74c2d8f52fc5fc06631e32/espnet2/samplers/build_batch_sampler.py#L12-L69
https://github.com/espnet/espnet/blob/305e974e553ec0b36c74c2d8f52fc5fc06631e32/espnet2/samplers/build_batch_sampler.py#L105-L160
