### ISSUE TITLE
data loader

### ISSUE THREAD

**Issue by wyunj** [espnet/espnet#4460]
Hi,
I have a question about the difference in data loading between ESPnet1 and ESPnet2. Espnet1 stores the processed data in a data.json file that is loaded directly during model training. Espnet2 seems to preprocess data in every epoch, including word segmentation, etc. What is the advantage of this over ESPnet1?
BTW, I wonder if subsequent epochs all use the data preprocessed in epoch1 instead of being repreprocessed each time, How should I modify it? Use the parameter cache?
Thanks in advance!

Task: ASR
Recipe: Librispeech

**Comment by sw005320** [comment]
espnet2 actually supports the processed data.
Please check https://github.com/espnet/espnet/blob/master/egs2/TEMPLATE/asr1/asr.sh#L507-L564

**Comment by wyunj** [comment]
Thanks for you reply! But I'm sorry I didn't make it clear. The preprocessing I'm talking about is the preprocessing for text during training, tokenization to characters, or sentencepieces.

**Comment by sw005320** [comment]
Sorry.
I think you can still do that by providing a list and regarding the pre-processed token as a word.
https://github.com/espnet/espnet/blob/master/egs2/TEMPLATE/asr1/asr.sh#L668
