### ISSUE TITLE
How can I proceed training with the last epoch?

### ISSUE THREAD

**Issue by Yerzhaisang** [espnet/espnet#4461]
During the ASR training (11 stage) I got the following error:

Process SpawnProcess-1:
OSError: [Errno 28] No space left on device

How can I proceed training with the last epoch? Thank you

**Comment by sw005320** [comment]
You do not seem to have enough disk space.
Please increase it by deleting files or adding more disks.

**Comment by sw005320** [comment]
Yes, you can use the resume function.

**Comment by Yerzhaisang** [comment]
Cool, I was just afraid of losing information if I start from that stage. Thank you so much
