### ISSUE TITLE
ModuleNotFoundError: No module named 'espnet2.diar.layers' in Colab SE demo

### ISSUE THREAD

**Issue by cycentum** [espnet/espnet#4465]
When running the Colab notebook of SE demo, I encountered the error 

> ModuleNotFoundError: No module named 'espnet2.diar.layers'

at “Enhance your own pre-recordings” cell.

I found the error is caused by espnet/espnet2/diar and espnet/espnet2/layer not properly installed.

In my local environment, I could fix the error by adding __init__.py in these directories.

Can I open a pull request to fix this bug?

**To Reproduce**
Run cells sequentially from the top in ESPnet SSE Demonstration.ipynb

**Comment by Emrys365** [comment]
Yes, I can reproduce this bug. @cycentum It would be great if you could make a PR to fix it!
