### ISSUE TITLE
Key mismatch while training LM on huge data which has been split into small sets

### ISSUE THREAD

**Issue by chiayuli** [espnet/espnet#4468]
Hello, 
I was training transformer LM on huge data which has been split into 4 subsets (--num_splits_lm 4), but got "KeyError" during the training.
It turns out that some keys from lm_train.txt and text_shape.bpe in the same split are mismatched. 
For example, some keys in lm_train.txt/split.0 are not found in text_shape.bpe/split.0

I looked into espnet/espnet2/bin/split_scps.py and found the suspicious piece of code from line 48 to line 52

![split_scps](https://user-images.githubusercontent.com/20842187/175558280-00095120-0f6f-442d-acf1-694f4f69bced.png)

The prev_key is always None, so it never raise RuntimError when the keys are mismatched. 

Besides, it looks that the split_scps.py expects the keys from the input files (in LM case, they are "lm_train.txt" and "text_shape.bpe") have the same order.
I think it would be nice to add two lines in egs2/TEMPLATE/asr1/asr.sh to sort both files before line 818 to prevent from keymismatched issue. What do you think ?
```
sort -k1,1 -o ${data_feats}/lm_train.txt ${data_feats}/lm_train.txt
sort -k1,1 -o ${lm_stats_dir}/train/text_shape.${lm_token_type} ${lm_stats_dir}/train/text_shape.${lm_token_type}
```

![asr](https://user-images.githubusercontent.com/20842187/175560651-60f20047-75bb-4623-bcf3-b31e3f0c772c.png)

**Task information:**
 - Task: ASR
 - Recipe: librispeech
 - ESPnet2
 - Data: my personal data

**To Reproduce**
1. move to a recipe directory, e.g., `cd egs/librispeech/asr1`
2. execute `run.sh` with specific arguments, e.g., `run.sh --stage 7 --ngpu 8 --num_splits_lm 4 --use_lm true `

**Comment by kamo-naoyuki** [comment]
Thank you for using the feature for huge data.  

> The prev_key is always None, so it never raise RuntimError when the keys are mismatched.

I think this is a bug. Thanks.

> I think it would be nice to add two lines in egs2/TEMPLATE/asr1/asr.sh to sort both files before line 818 to prevent from keymismatched issue. What do you think ?

I think the following line is better to run the sort command

https://github.com/espnet/espnet/blob/57c05436bf72366333671fc7e4267b5216208c8a/egs2/TEMPLATE/asr1/asr.sh#L633

`text_shape` is always sorted if the source text is sorted.

**Comment by chiayuli** [comment]
Thanks for the advice. It works for me. 
Shall I close this issue ? You're gonna push the fix for the bug in espnet/espnet2/bin/split_scps.py, right ?

**Comment by kamo-naoyuki** [comment]
Thanks. Please keep it open until I fix this bug, then I'll close.
