### ISSUE TITLE
Symbolic link not working for AmericasNLP baseline

### ISSUE THREAD

**Issue by danperazzo** [espnet/espnet#4469]
**Describe the bug**
I have been trying to test the baseline for the [AmericasNLP2022 competition,](https://github.com/espnet/espnet/tree/master/egs2/americasnlp22/asr1) and have been following the steps at [hugging_face](https://huggingface.co/espnet/americasnlp22-asr-gn). 

However, the symbolic link in `utils` seens to been broken, and this is causing it to not work in the run script.
**Basic environments:**
 - OS information: [\ubuntu 18.04
 - python version: 3.9
 - espnet version: Followed the commit at huggingFace

**To Reproduce**
1.  `git clone --recursive  https://github.com/espnet/espnet.git`
2. `cd espnet`
3. `git checkout fc62b1ce3e50c5ef8a2ac8cedb0d92ac41df54ca`
4. `pip install -e .`
5. `cd egs2/americasnlp22/asr1`
6. `./run.sh --skip_data_prep false --skip_train true --download_model espnet/americasnlp22-asr-gn`

**Error logs**
`022-06-24T18:14:51 (asr.sh:252:main) ./asr.sh --lang tav --ngpu 1 --nbpe 100 --use_lm false --max_wav_duration 38 --speed_perturb_factors 0.9 1.0 1.1 --feats_normalize utterance_mvn --asr_config conf/train_asr_transformer.yaml --inference_config conf/decode_asr.yaml --inference_asr_model valid.cer_ctc.best.pth --inference_nj 1 --gpu_inference true --local_data_opts --lang tav --train_set train_tav --valid_set dev_tav --test_sets dev_tav --lm_train_text data/train_tav/text --bpe_train_text data/train_tav/text --skip_data_prep false --skip_train true --download_model espnet/americasnlp22-asr-gn
./asr.sh: line 255: utils/parse_options.sh: No such file or directory
`

**Comment by sw005320** [comment]
Thanks for your report.
We haven’t tested it for this huggingface description way and it may not be working.
@akreal, it is not your charge, but could I ask you to take a look at it? `pip install` may not be enough for this usage.

**Comment by akreal** [comment]
Yes, `pip install` is not enough here, because it does not download Kaldi.
This huggingspace description comes from here:
https://github.com/espnet/espnet/blob/a2abaf11c81e58653263d6cc8f957c0dfd9677e7/egs2/TEMPLATE/asr1/scripts/utils/TEMPLATE_HF_Readme.md?plain=1#L18-L27
It assumes that ESPnet dependencies are already installed. Maybe the template could be updated to reflect this assumption, but already existing models will still have the old description.

@danperazzo you can try to run these lines and see if it solves the issue for you:
```
cd espnet/tools
make kaldi
```

**Comment by akreal** [comment]
@danperazzo 
Additionally the last command needs some more arguments in this recipe:
```
./run.sh --skip_data_prep false --skip_train true --download_model espnet/americasnlp22-asr-gn --lang gn --local_data_opts "--lang gn"  --train_set train_gn --dev_set dev_gn --test_sets dev_gn --gpu_inference false --inference_nj 8
```
(you can set `inference_nj` to number of CPU threads or desired number of parallel jobs)
I'll update it in the description when we'll decide how to handle the kaldi problem.

**Comment by danperazzo** [comment]
Hello @akreal and @sw005320, thank you for your response!

I managed to perform the steps detailed in the [instalation docs](https://espnet.github.io/espnet/installation.html) and, later, I performed the command you wrote (however, I took the dev_test argument since it was causing an error)

However, in this case I got another error, I anex the error log in this comment. (thanks for the help!)

[error_log_test.txt](https://github.com/espnet/espnet/files/8985630/error_log_test.txt)

**Comment by akreal** [comment]
Two more tools (certain versions) also need to be installed:
```
cd tools
make fairseq.done
make s3prl.done
```

And here is corrected decoding command:
```
./run.sh --skip_data_prep false --skip_train true --download_model espnet/americasnlp22-asr-gn --lang gn --local_data_opts "--lang gn"  --train_set train_gn --valid_set dev_gn --test_sets dev_gn --gpu_inference false --inference_nj 8 --lm_train_text data/train_gn/text --bpe_train_text data/train_gn/text
```

**Comment by danperazzo** [comment]
Thanks for the help! I managed to run the example, however, the program froze my computer (I think I do not have enough RAM memory). Is there any parameter that I can diminish so that it can fit in my computer?

**Comment by akreal** [comment]
You can try to decrease `inference_nj` to 1 in order to have only one decoding job. If it's not enough, you could try quantization (add `quantize_asr_model: True` in `conf/decode_asr.yaml`), but I have not tried it and don't know if it works with this model or helps to decrease memory usage at all.

**Comment by danperazzo** [comment]
Thanks! Quantize the model actually resulted in a error but setting the `inference_nj` to 1 solved the problem!

**Comment by sw005320** [comment]
Thanks a lot!
I think we collected enough information to fix this issue.
@akreal, could I ask you to make a PR to fix https://github.com/espnet/espnet/blob/master/egs2/TEMPLATE/asr1/scripts/utils/TEMPLATE_HF_Readme.md#demo-how-to-use-in-espnet2 ?
