### ISSUE TITLE
cython version monotonic_align is better than 'EXPERIMETAL' numba version

### ISSUE THREAD

**Issue by yt605155624** [espnet/espnet#4475]
As an experimental result, cython version monotonic_align is better than 'EXPERIMETAL' numba version

Do anyone has the same result?

cython version monotonic_align will get bad duration even though I train 320k x4 GPUs, but after I install cpython version monotonic_align and train more small iters, the result become better !

I test on my paddlepaddle version of VITS, do any one has the same result on espnet vits???

**Comment by kan-bayashi** [comment]
numba version is a kind of fallback method when cpython version is not available.
Therefore, I recommend using cpython version.
