### ISSUE TITLE
Error while uncompress model.v1.tar.gz

### ISSUE THREAD

**Issue by li563042811** [espnet/espnet#4481]
Hi,
    I'm using the egs/lrs/avsr1. But when I run run.sh and it exit at step 1 like this

stage 1: Data preparation
Download pretrained video feature extractor and check directory configuration
--2022-06-30 11:38:31--  https://docs.google.com/uc?export=download&confirm=t&id=1ITgdZoa8vQ7lDwi1jLziYGXOyUtgE2ow
Connecting to 172.18.18.131:80... connected.
Proxy request sent, awaiting response... 303 See Other
Location: https://doc-0k-3k-docs.googleusercontent.com/docs/securesc/ha0ro937gcuc7l7deffksulhg5h7mbp1/qpbdpr3ivh9ldo31ktoh4tupbq16831p/1656560250000/04626072373573315601/*/1ITgdZoa8vQ7lDwi1jLziYGXOyUtgE2ow?e=download&uuid=5dfc9b48-b0ae-45a3-9816-f3b65a6994fb [following]
Warning: wildcards not supported in HTTP.
--2022-06-30 11:38:31--  https://doc-0k-3k-docs.googleusercontent.com/docs/securesc/ha0ro937gcuc7l7deffksulhg5h7mbp1/qpbdpr3ivh9ldo31ktoh4tupbq16831p/1656560250000/04626072373573315601/*/1ITgdZoa8vQ7lDwi1jLziYGXOyUtgE2ow?e=download&uuid=5dfc9b48-b0ae-45a3-9816-f3b65a6994fb
Connecting to 172.18.18.131:80... connected.
Proxy request sent, awaiting response... 200 OK
Length: 707592192 (675M) [application/gzip]
Saving to: 'model.v1.tar.gz'

100%[==============================================================================================================================>] 707,592,192 5.75MB/s   in 1m 57s 

2022-06-30 11:40:29 (5.74 MB/s) - 'model.v1.tar.gz' saved [707592192/707592192]

gzip: stdin: unexpected end of file
tar: Unexpected EOF in archive
tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now

I have tried many times but it all put this error. I don't know how to do with this.

**Comment by sw005320** [comment]
Thanks for the report.
@wentaoxandry, could you check this issue?

**Comment by wentaoxandry** [comment]
I will check this issue tomorrow

**Comment by wentaoxandry** [comment]
@li563042811 I have checked the compressed file. It seems that the compressed file is corrupted. I'm trying to reconstruct these files and upload them again. It costs some times. I will tell you when I finish.

**Comment by li563042811** [comment]
@wentaoxandry  I tried again according to your commitment and it worked. Thanks a lot.
