### ISSUE TITLE
Black formatting issue for test CLI ESPNET

### ISSUE THREAD

**Issue by chorongi** [espnet/espnet#4482]
**Describe the bug**
PR error for git CLI test for Centos7 and Debian9 when already used black to reformat all my files.

**Error logs**
Error Message is the following:
![image](https://user-images.githubusercontent.com/35532722/176608263-e5f9090e-59c4-4d07-a7cc-3665fcdd1f56.png)

**Basic environments:**
python==3.7.13
black==22.6.0
 

**Comments**
I would like to know exactly which black version is used for CLI test on espnet! Also, currently I can only find ways to install black 22.6.0 (not able to install older versions) so installing an older version of black doesn't seem to be an option.

**Comment by kamo-naoyuki** [comment]
We don't fix the version of black in CI tests, the latest version of black is automatically used.

The latest version is 22.6, and it shouldn't change the code. I think you had some mistakes.

**Comment by kamo-naoyuki** [comment]
Please open the PR. I can investigate the problem if needed.
