### ISSUE TITLE
Fastspeech2 attention default dimension

### ISSUE THREAD

**Issue by rrr613** [espnet/espnet#4487]
I am reading the code.
I have a question but I couldn't find the reason.
Why the dimension of attention (or the feature) is 384?

I had read some papers that the dimension is set to 256.
Are there any specific reason for set to 384?

https://github.com/espnet/espnet/blob/d837c97c88f13ffe655a30bcff93d814f212b225/espnet2/tts/fastspeech2/fastspeech2.py#L53

Thanks

**Comment by kan-bayashi** [comment]
I forgot the reason but maybe it is based on preliminary experiments.
So, there is no strong reason to choose this parameters.
