### ISSUE TITLE
Inference with Ngram

### ISSUE THREAD

**Issue by Miamoto** [espnet/espnet#4491]
Hi! 

I have trained the recipe in egs2/librispeech_100. This model uses BPE for the tokens. Now I was trying to perform decoding with an LM. I was trying to use the 4gram librispeech model available in https://www.openslr.org/11/. I converted to a binary format using kenlm and after decoding with a beam size of 60 and several ngram weights the model seems to not improve. With weight 0.1 in the ngram the model stays the same and when I increase it starts to degrade. 

Do you have any idea why the Ngram is not working?

Thanks a lot

**Comment by sw005320** [comment]
How to use the ngram language model?
I think it would be difficult to make it work with shallow fusion since ngram is based on a word while the ASR model is based on the BPE token.
Or are you using k2?
If so, please share the details (e.g, config files).

**Comment by Miamoto** [comment]
Hmm, I am using BPE (This is the model I am doing experiments on: https://huggingface.co/jkang/espnet2_librispeech_100_conformer). So what do you recommend to do so that someone can replicate results easily with an available language model? If I need it to train myself, do you recommend I use the available text from training data or more? Or can I try to use available LMs from ESPnet?

Thanks a lot

**Comment by sw005320** [comment]
OK.
Can you tell me the exact command to perform decoding with your LM shallow fusion?

**Comment by sw005320** [comment]
There are several ways to incorporate an n-gram LM and I want to identify what is your current issue.

**Comment by Miamoto** [comment]
And this is my config file for decoding: 

beam_size: 60
ctc_weight: 0.3
lm_weight: 0
ngram_weight: 0.1
ngram_file: /exp/ngram/4gram.bin
maxlenratio: 0.0
minlenratio: 0.0
penalty: 0.0

**Comment by sw005320** [comment]
Thanks a lot.
I recommend you make an ngram language model that is the same vocabulary as the ASR model.
You can process the librispeech text with the ASR BPE model and make an ngram LM by using kenlm or whatever.

@qmpzzpmq, do you think it is expected behavior?
It seems that the current ngram code can accept a ngram language model that has a different vocabulary from ASR.

**Comment by Miamoto** [comment]
I did what [sw005320](https://github.com/sw005320) mentioned. I used the text from here https://www.openslr.org/11/. Then  I executed espnet2.bin.tokenize_text to tokenise the file with BPE, and after that, I executed only stage 9 from the asr.sh file with 6-gram.

By decoding with this LM, I can go from 17.4 WER on the test other to 14.70 WER, and from 8.50 CER to 7.6 CER. I guess it is a reasonable improvement. What do you think? 

Thanks a lot!

**Comment by sw005320** [comment]
I think so!
Glad to hear that you successfully make it work.

**Comment by omshrivastava26** [comment]
@Miamoto can you please help me with inference on n-gram.I have generated arpa file on a text using 6-gram Kelnm.I am not quite sure where to place the arpa file in cloned esp folder
