### ISSUE TITLE
Fine-tuning a pre-trained ASR model on Accent English Corpus

### ISSUE THREAD

**Issue by gyc666** [espnet/espnet#4497]
Hello!

I'm trying to fine-tune a pre-trained GigaSpeech Espnet2 ASR model on a new dataset,

1. Do I need change the BPE model and Token list?
2. Is  better to freeze part of the network (e.g., the encoder) or to fine-tune the entire network?

Thank you!

**Comment by sw005320** [comment]
> I'm trying to fine-tune a pre-trained GigaSpeech Espnet2 ASR model on a new dataset,
> 
> 1. Do I need change the BPE model and Token list?

Please check
https://github.com/espnet/espnet/blob/master/egs2/mini_an4/asr1/transfer_learning.md
https://github.com/espnet/notebook/blob/master/espnet2_asr_transfer_learning_demo.ipynb
You can use the original BPE model or new models.

> 2. Is  better to freeze part of the network (e.g., the encoder) or to fine-tune the entire network?

My experience is that we may not need to freeze a part of the network if we want to get the primary effect of fine-tuning. However, if you want to get marginal improvements or want to reduce the training time, you can use the freezing option.

**Comment by kelseyjd** [comment]
@gyc666 did fine-tuning work for you? Or did you have to train a model from scratch for your accented english dataset?
