### ISSUE TITLE
Use of Multi-speaker TTS system based on x-vector?

### ISSUE THREAD

**Issue by picheny-nyu** [espnet/espnet#4500]
I would like to use one of the pretrained models that use x-vectors to synthesize speech for a speaker not in the training set. From what I understand from other discussions, x-vectors work better than GST. I would like to try such a system, but could really benefit from a pointer for how to extract the x-vectors at inference for the new speaker. All the examples seem to suggest I have to create a "new" speaker in the training directory and point to that. A code example (even a pseudo-code example) would be very helpful.

Thanks
Michael

**Comment by kan-bayashi** [comment]
The pretrained models used kaldi's x-vector.
You can refer this part to extract x-vector.
https://github.com/espnet/espnet/blob/ae99a1dcd3af8628f3cf8518e296cbef24f6e94f/utils/synth_wav.sh#L288-L314

However, this is based on kaldi, it is not so useful when you want to run in python API.
Now we support speech-brain's x-vector, so if you can train multi-spk model with the x-vector by yourself, it will be easier to extract x-vector in python.
https://github.com/espnet/espnet/tree/master/egs2/TEMPLATE/tts1#2-wav-dump--embedding-preparation:~:text=Additionally%2C%20We%20support,please%20be%20careful.

**Comment by picheny-nyu** [comment]
Thanks. Could you clarify the following? 

Some of the TTS pretrained multi speaker models in the model zoo use xvectors.  

1. Do they also require kaldi to run? If so, is the Kaldi model downloaded with the TTS model?  
2. If they use the speechbrain xvectors, is that model downloaded with the TTS model?
3. There seem to be some speechbrain xvector models available through huggingface. I assume to use them I would need to retrain the TTS model with them. Is that correct? 

Thanks
Michael

**Comment by kan-bayashi** [comment]
> Do they also require kaldi to run?

Right. 

> If so, is the Kaldi model downloaded with the TTS model?

No. You need to do it manually.
https://github.com/espnet/espnet/blob/ae99a1dcd3af8628f3cf8518e296cbef24f6e94f/utils/synth_wav.sh#L305-L311

> If they use the speechbrain xvectors, is that model downloaded with the TTS model?

No. You need to do it manually.

> I assume to use them I would need to retrain the TTS model with them. Is that correct?

Right. You need to train by yourself.

**Comment by picheny-nyu** [comment]
The multi speaker TTS model (trained on libritts) in synth_wav.sh above is very slow for waveform generation with the default wavenet model. Do you have a pretrained multispeaker model that is based on something faster, say, parallel wavegan?

**Comment by kan-bayashi** [comment]
Right.

**Comment by 1nlplearner** [comment]
I want to use trained multi-speaker model to inference with exacted x-vector, how to use exacted x-vector
Thanks

**Comment by kan-bayashi** [comment]
See example notebook.
https://colab.research.google.com/github/espnet/notebook/blob/master/espnet2_tts_realtime_demo.ipynb#scrollTo=3TTAygALqY6T

**Comment by 1nlplearner** [comment]
> See example notebook. https://colab.research.google.com/github/espnet/notebook/blob/master/espnet2_tts_realtime_demo.ipynb#scrollTo=3TTAygALqY6T

thanks for your reply

**Comment by 1nlplearner** [comment]
> See example notebook. https://colab.research.google.com/github/espnet/notebook/blob/master/espnet2_tts_realtime_demo.ipynb#scrollTo=3TTAygALqY6T

![image](https://user-images.githubusercontent.com/52569141/183583052-3bc747ee-c7fa-48db-9727-0c1f91909fb3.png)
I use the recording file under the corresponding speaker folder as  speech，but it perform worse than initialing speech with torch.randn, any tips?

**Comment by picheny-nyu** [comment]
I found the different multi-speaker TTS models behave very differently, but did not do a comprehensive study. There are many of them:

vctk_gst_tacotron2
vctk_gst_transformer
vctk_xvector_tacotron2
vctk_xvector_transformer
vctk_xvector_conformer_fastspeech2
vctk_gst+xvector_tacotron2
vctk_gst+xvector_transformer

vctk_gst+xvector_conformer_fastspeech2
libritts_xvector_transformer
libritts_xvector_conformer_fastspeech2
libritts_gst+xvector_transformer
libritts_gst+xvector_conformer_fastspeech2
libritts_xvector_vits

**Comment by apzl** [comment]
> > See example notebook. https://colab.research.google.com/github/espnet/notebook/blob/master/espnet2_tts_realtime_demo.ipynb#scrollTo=3TTAygALqY6T
> 
> ![image](https://user-images.githubusercontent.com/52569141/183583052-3bc747ee-c7fa-48db-9727-0c1f91909fb3.png) I use the recording file under the corresponding speaker folder as speech，but it perform worse than initialing speech with torch.randn, any tips?

which model did you use? 
I'm getting `RuntimeError: Missing required argument: 'spembs'` for all the vits models.
