### ISSUE TITLE
How to load a pre-trained and encoder and decoder ?

### ISSUE THREAD

**Issue by karthik19967829** [espnet/espnet#4516]
Hi I would like to load pre-trained conformer RNN-T .
I would like to load both the pre-trained encoder and decoder .
https://github.com/siddhu001/espnet/blob/936917515557de1dd8519d67c9b455670b166536/egs2/slurp_transcript/asr1/run.sh#L22 

In the above I see we can load encoder , but how do we load encoder and decoder ?

**Comment by ftshijt** [comment]
You can fetch the corresponding modules by https://github.com/siddhu001/espnet/blob/master/espnet2/torch_utils/load_pretrained_model.py
