### ISSUE TITLE
About the use of run.pl

### ISSUE THREAD

**Issue by semicarryispig** [espnet/espnet#4518]
When run the code of espnet, I get the log below:
```
stage 1: Feature Generation
~/work/espnet/egs/an4/tts1/../../../utils/make_fbank.sh --cmd run.pl --nj 4 --fs 16000 --fmax  --fmin  --n_fft 1024 --n_shift 256 --win_length  --n_mels 80 data/train exp/make_fbank/train fbank
utils/validate_data_dir.sh: Successfully validated data-directory data/train
~/work/espnet/egs/an4/tts1/../../../utils/make_fbank.sh: [info]: no segments file exists: assuming pcm.scp indexed by utterance.
usage: run.pl log-file command-line arguments... at utils/parallel/run.pl line 26.
```

It gets error when come acoss the run.pl command. 

I find that in kaldi https://github.com/kaldi-asr/kaldi/tree/master/egs/wsj/s5/steps/make_fbank.sh，the code looks like this:
![image](https://user-images.githubusercontent.com/7950895/179758630-e7134da6-ae1f-45c8-b731-08e31388bd2f.png)

while in espnet, the code looks like this:
![image](https://user-images.githubusercontent.com/7950895/179758796-2b2e890c-7ca7-44e0-8c5e-f0c0bf7ead68.png)
it replace the command with a python script

How can I make the code here execute smoothly?

**Comment by Fhrozen** [comment]
if the python script is not included in the $PATH env variable, then you will need to replace `compute-fbank-feats.py`  with `python <dir_file>/compute-fbank-feats.py`

**Comment by semicarryispig** [comment]
The problem is solved. 
The reason is that my kaldi version is too old.
