### ISSUE TITLE
What is the proper way to train FastSpeech2 with MFA?

### ISSUE THREAD

**Issue by iamanigeeit** [espnet/espnet#4521]
I have read the [TTS training guide](https://github.com/espnet/espnet/blob/master/egs2/TEMPLATE/tts1/README.md) and i follow [this issue](https://github.com/espnet/espnet/issues/2712).

Now i want to summarize the process to help everyone. Please correct if i'm wrong.

- Use `MFA validate` to get OOVs, run `MFA g2p` on OOVs and `MFA align` with expanded dictionary to obtain `.TextGrid` files
- Generate  `data/train/text` file to use phoneme transcription instead of text, according to [this]. Add punctuation marks and silences to maintain alignments (see [below](https://github.com/espnet/espnet/issues/4521#issuecomment-1194993281)).
- Generate `data/train/durations` file from `.TextGrid` in [this format](https://github.com/espnet/espnet/issues/2632#issuecomment-734211026). Convert TextGrid seconds into # melspec frames. Add durations for punctuation and silences, then add 0 to each line according to [this](https://github.com/espnet/espnet/issues/4113). Total durations should match total #melspec frames in audio.
- In `run.sh`, set `--cleaner none` and `--g2p none` as we're using MFA g2p -- [see issue here](https://github.com/espnet/espnet/issues/3340)
- Edit `local/data.sh`: comment out the lines with `rm ${text}` and `paste -d ... > ${text}` which will overwrite your `data/train/text` file 
- Run stage 1-4 as usual
- Run stage 5 with `./run.sh    --stage 5    --stop_stage 5    --train_config conf/tuning/train_fastspeech2.yaml    --teacher_dumpdir data     --tts_stats_dir data/stats`: [reference](https://github.com/espnet/espnet/issues/2712#issuecomment-732671515)
- Train the rest normally

For inference, you should first do normal inference to extract features:
```
./run_mfa.sh --stage 7 --stop-stage 7 \
    --tts_exp exp/default_fastspeech2 \
    --inference_config conf/tuning/decode_fastspeech.yaml \
    --inference_model valid.loss.ave_5best.pth \
    --test_sets eval1
```

Then go to https://github.com/kan-bayashi/ParallelWaveGAN and install it. Download your chosen vocoder `.pkl`, `stats.h5`and `config.yml` and run 
```
parallel-wavegan-decode \
    --checkpoint parallel_wavegan/checkpoint-3000000steps.pkl \
    --feats-scp exp/*/decode_fastspeech_valid.loss.ave_5best/eval1/norm/feats.scp \
    --outdir exp/*/parallel_wavegan
```

I don't know why, but running stage 7 directly with `--vocoder_file` makes the generated audio too soft and noisy.

**Comment by kan-bayashi** [comment]
> Use MFA to obtain the .TextGrid files (done)

OK

> Train stage 1-3 as usual (done)

OK 

> Create tokens.txt with the MFA phonemes. But since the default is https://github.com/espnet/espnet/issues/3340 we need to set cleaner=none and g2p=none during training and edit every data/*/text file to use phoneme transcription instead of text, according to https://github.com/espnet/espnet/issues/3870. Correct?

Right.

> Create durations file in https://github.com/espnet/espnet/issues/2632#issuecomment-734211026, add 0 to each line according to https://github.com/espnet/espnet/issues/4113, and put it https://github.com/espnet/espnet/issues/2712#issuecomment-732671515. The durations are melspec frames. Since MFA TextGrids use seconds, i have to convert it based on fs, n_fft and n_shift. Correct?

Right. But you should add 0 at the end of each line of `durations` file, which if for `<eos>` symbol (`<eos>` is added internally).

> Run stage 5 according to https://github.com/espnet/espnet/issues/2712#issuecomment-732671515
Train the rest normally

Right.

**Comment by iamanigeeit** [comment]
@kan-bayashi Thanks for the reply, i will try it and maybe send a PR if i succeed.

To clarify: for each line in the `durations` file, adding all the numbers should give me the number of melspec frames, right? The MFA phoneme transcription does not have any silence or punctuation marks, so i need to add them back into the `data/*/text` and insert their duration into `durations`?

Example text: "yes, but" with 30 frames

`data/*/text` file:
```
sample1 j ɛ s b ɐ t 
```
`durations` file:
```
sample1 3 5 3 4 5 3
```

Will be changed to insert the `,` and duration for it
`data/*/text` file:
```
sample1 j ɛ s , b ɐ t <sil>
```
`durations` file:
```
sample1 3 5 3 6 4 5 3 1
```

**Comment by kan-bayashi** [comment]
@iamanigeeit Sorry for the late reply.

> for each line in the durations file, adding all the numbers should give me the number of melspec frames, right?

Right. It assumes that `sum(duration) == #mel frames`.

> so i need to add them back into the data/*/text and insert their duration into durations?

Right. You need to restore them. And please add 0 for `<eos>` like:

| data/*/text | sample1 | j | ɛ | s | , | b | ɐ | t | sil | |
|-------------|---------|---|---|---|---|---|---|---|-----|--|
| durations   | sample1 | 3 | 4 | 3 | 7 | 3 | 5 | 3 | 2   | 0 |

**Comment by iamanigeeit** [comment]
I have updated the first post to reflect the actual process and will submit a PR for it once i have solved my issues running FastSpeech2.

**Comment by iamanigeeit** [comment]
@kan-bayashi Is there a process for submitting PRs? Also i have put my MFA-related scripts in `egs2/ljspeech/tts1` as i am using LJSpeech. Should i move it somewhere else? Thanks.

**Comment by kan-bayashi** [comment]
@iamanigeeit That is COOL :) I think we can put the conversion script from MFA results to `text` and `duration` files in `pyscripts` or `scripts` since it can be used in the other recipe.
For the other tips about PR, please check https://github.com/espnet/espnet/blob/master/CONTRIBUTING.md

**Comment by iamanigeeit** [comment]
I have managed to get good results, so i'm closing the issue. Updated guide is at the top. Thanks!

**Comment by 1nlplearner** [comment]
In code https://github.com/espnet/espnet/blob/master/espnet2/tts/feats_extract/dio.py, pitch lengths are adjusted according the parameter feats_lengths, but they are not equal to sum(duration) from mfa, there is an error of plus or minus 1, so how to deal with this, adjusting pitch according durations or adjusting  feat according durations?
thanks!
![image](https://user-images.githubusercontent.com/52569141/196104144-4ae621d3-b629-4be5-a118-4398a2248299.png)

**Comment by iamanigeeit** [comment]
@1nlplearner Just saw this -- i think closed issues don't get attention. Maybe open a new issue?

**Comment by nayanjha16** [comment]
Hi All  ,

I have extracted the phone level alignments from kaldi in a .txt format.  kindly suggest a way to convert it to .textgrid format so that it can be used for Fastspeech2 training

**Comment by iamanigeeit** [comment]
@nayanjha16 Have you tried the Praat library?
