### ISSUE TITLE
How to use SeparateSpeech class in Torchserve

### ISSUE THREAD

**Issue by Shin-ichi-Takayama** [espnet/espnet#4524]
Thank you for all your help.

I am trying to API the Transformer model for the speech enhancement task using torchserve.
I have confirmed that the noise is suppressed using `run.sh` before APIing.

To use torchserve, I need a handler to instantiate the model.
To try to instantiate the model, I created the following Python file in the espnet/espnet2/bin directory.

```python:enh_inference_test.py
#!/usr/bin/env python3
from enh_inference import SeparateSpeech
import soundfile

def main():
    separate_speech = SeparateSpeech("enh_config.yml", "enh.pth")
    audio, rate = soundfile.read("speech.wav")
    separate_speech(audio)

if __name__ == "__main__":
    main()
```

However, I am getting the following import error.
```
(base) root@f967f3aa451f:~/espnet/espnet2/bin# python3 enh_inference_test.py
Traceback (most recent call last):
  File "/root/espnet/espnet2/bin/enh_inference_test.py", line 2, in <module>
    from enh_inference import SeparateSpeech
  File "/root/espnet/espnet2/bin/enh_inference.py", line 9, in <module>
    import humanfriendly
ModuleNotFoundError: No module named 'humanfriendly'
```

Looking at the library list with the `conda list` command, `humanfriendly` was not installed.
However, I was able to perform inference in `run.sh`. 

Why am I getting an import error?
Please let me know if there is a better way to instantiate the SeparateSpeech class.

Best regards.

**Comment by sw005320** [comment]
I think these conda libraries are activated via `path.sh` in `run.sh`
https://github.com/espnet/espnet/blob/master/egs2/TEMPLATE/enh1/path.sh
Can you check it?

If you're only interested in inference, you can also check https://github.com/espnet/espnet_model_zoo#python-api-for-inference

**Comment by Shin-ichi-Takayama** [comment]
Thank you for your response.
I found that the library is activated using `path.sh`.
Does that mean that I cannot instantiate the model with a python script?

**Comment by kan-bayashi** [comment]
Why don't you just install humanfriedly?

**Comment by Shin-ichi-Takayama** [comment]
> Note that humanfriendly is a requirement of espnet

Yes, I understand that.
My question is why the library import error occurs even though `run.sh` is working.

Is it safe to install additional `humanfriendly` and `pytorch` in an environment where `run.sh` is working properly?

**Comment by kan-bayashi** [comment]
I don't know how to setup your environment but in a standard way, espnet create portable virtualenv in `tools`.
And if you source `path.sh`, the environment is activated.
Therefore, when we run `run.sh` we always use virtualenv created in `tools` since `path.sh` is sourced in `run.sh`.
So maybe when you run your API, you may not use the virtualenv.

**Comment by Shin-ichi-Takayama** [comment]
Thank you for your response.
Is there any documentation on how to build an environment without a virtual environment?

I create an environment with the following Dockerfile.
```
FROM nvidia/cuda:11.3.0-devel-ubuntu18.04

RUN apt-get update && apt-get -y upgrade && \
	apt-get install -y build-essential && \
	apt-get install -y software-properties-common && \
	apt-get install -y cmake sox ffmpeg flac curl git man unzip vim wget sudo && \
	apt-get install -y libfreetype6 libfreetype6-dev

#install Anaconda
RUN \
	apt-get install libgl1-mesa-glx libegl1-mesa libxrandr2 libxrandr2 libxss1 libxcursor1 libxcomposite1 libasound2 libxi6 libxtst6 wget -y && \
	wget -P /opt https://repo.anaconda.com/archive/Anaconda3-2021.11-Linux-x86_64.sh && \
	bash /opt/Anaconda3-2021.11-Linux-x86_64.sh -b -p /opt/anaconda3 && \
	rm /opt/Anaconda3-2021.11-Linux-x86_64.sh && \
	echo "export PATH=/opt/anaconda3/bin:$PATH" >> ~/.bashrc && \
	. ~/.bashrc && \
	conda init

#install espnet
RUN  \
	cd ~ && \
	git clone https://github.com/espnet/espnet && \
	cd ~/espnet/tools && \
	./setup_anaconda.sh anaconda espnet 3.8 && \
	cd ~/espnet/tools && \
	make TH_VERSION=1.10.1 && \
	cd ~/espnet/tools && \
	. ./activate_python.sh; python3 check_install.py
```

**Comment by kan-bayashi** [comment]
If you just want to use as the library, simply do `pip install espnet`.
Please check the following notebook as an example.
https://colab.research.google.com/github/espnet/notebook/blob/master/espnet2_tts_realtime_demo.ipynb

And in your dockerfile case, you can add entrypoint to source `~/espnet/tools/activate_python.sh`.

**Comment by Shin-ichi-Takayama** [comment]
Thank you for your response.
Thanks to your help, the import error has been resolved.
However, when I instantiate the model as in the following code, the error occurs.
```Python
from espnet2.bin.enh_inference import *
import soundfile

def main():
    separate_speech = SeparateSpeech("train_enh_transformer_tf.yaml", "valid.loss.best.pth")
    audio, rate = soundfile.read("Mix.wav")
    separate_speech(audio)

if __name__ == "__main__":
    main()
```

> root@e43b6b75eb45:~/transformer# python3 transformer_test.py
Traceback (most recent call last):
  File "transformer_test.py", line 11, in <module>
    main()
  File "transformer_test.py", line 5, in main
    separate_speech = SeparateSpeech("./train_enh_transformer_tf.yaml", "./valid.loss.best.pth")
  File "/usr/local/lib/python3.6/dist-packages/espnet2/bin/enh_inference.py", line 61, in __init__
    enh_train_config, enh_model_file, device
  File "/usr/local/lib/python3.6/dist-packages/espnet2/tasks/abs_task.py", line 1781, in build_model_from_file
    model = cls.build_model(args)
  File "/usr/local/lib/python3.6/dist-packages/espnet2/tasks/enh.py", line 186, in build_model
    encoder=encoder, separator=separator, decoder=decoder, **args.model_conf
AttributeError: 'Namespace' object has no attribute 'model_conf'

How can I resolve this issue?
Best regards.

**Comment by kan-bayashi** [comment]
Not sure for me.
@Emrys365 @LiChenda Could you help him?

**Comment by Emrys365** [comment]
@Shin-ichi-Takayama Did you use the latest codebase to train the model? If so, there should be a key named `model_conf` in the config file `train_enh_transformer_tf.yaml`.

If you trained the model with an older version of espnet, then it is likely that the key `model_conf` is missing. To make it compatible with the latest code, you need to manually add the following content to the config file:
```yaml
model_conf:
    stft_consistency: false
    loss_type: mask_mse
    mask_type: null
```

**Comment by Shin-ichi-Takayama** [comment]
Thank you for your response.
I cloned and trained in early July. So I think it is an older version.
I added the following content to the config file.
```yaml
model_conf:
    stft_consistency: false
    loss_type: mask_mse
    mask_type: null
```
The error in instantiating the model has been resolved.
However, the following new error occurred in the inference process.
> root@e43b6b75eb45:~/transformer# python3 transformer_test.py
Traceback (most recent call last):
  File "transformer_test.py", line 11, in <module>
    main()
  File "transformer_test.py", line 7, in main
    separate_speech(audio)
  File "/usr/local/lib/python3.6/dist-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/espnet2/bin/enh_inference.py", line 121, in __call__
    assert speech_mix.dim() > 1, speech_mix.size()
AssertionError: torch.Size([64000])

I am attaching the config file, the wav file and the python file.
[wav_yaml_py_files.zip](https://github.com/espnet/espnet/files/9194642/wav_yaml_py_files.zip)

Best regards.

**Comment by Emrys365** [comment]
The SeparateSpeech instance requires a batch of audio data as input. So you need to add a singleton dimension to the left if your input has only one dimension.

**Comment by Shin-ichi-Takayama** [comment]
Thank you for your response.
Thanks to your help, I got the following warning, but the inference worked.

> root@e43b6b75eb45:~/transformer# python3 transformer_test.py
/usr/local/lib/python3.6/dist-packages/torch/functional.py:573: UserWarning: stft will soon require the return_complex parameter be given for real inputs, and will further require that return_complex=True in a future PyTorch release. (Triggered internally at  ../aten/src/ATen/native/SpectralOps.cpp:659.)
  normalized, onesided, return_complex)
/usr/local/lib/python3.6/dist-packages/espnet2/layers/stft.py:109: UserWarning: __floordiv__ is deprecated, and its behavior will change in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values. To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor').
  olens = (ilens - self.win_length) // self.hop_length + 1
/usr/local/lib/python3.6/dist-packages/torch/functional.py:648: UserWarning: istft will require a complex-valued input tensor in a future PyTorch release. Matching the output from stft with return_complex=True.  (Triggered internally at  ../aten/src/ATen/native/SpectralOps.cpp:811.)
  normalized, onesided, length, return_complex)

I have one question.
The amplitude of the results of inference after instantiating the model is different from the results of inference in `run.sh`.
(The amplitude of the result inferred by `run.sh` is higher)
I think this is because the `--normalize_output_wav` option was set to True in `enh.sh`.
Is it possible to match the inferred results?

**Comment by Emrys365** [comment]
> Thanks to your help, I got the following warning, but the inference worked.

These warnings do not impact the inference result. So you can just ignore them.

>I have one question.
> The amplitude of the results of inference after instantiating the model is different from the results of inference in run.sh.
(The amplitude of the result inferred by run.sh is higher)
> I think this is because the --normalize_output_wav option was set to True in enh.sh.

Yes, `--normalize_output_wav True` is the cause.
To achieve the same effect, you could pass an additional argument when instantiating SeparateSpeech:
```python
SeparateSpeech(..., normalize_output_wav=True)
```

**Comment by Shin-ichi-Takayama** [comment]
Thank you very much.
Thanks to your help I was able to get it to work.
