### ISSUE TITLE
Text to Speech inference cant find espeak-ng error 

### ISSUE THREAD

**Issue by AliNGatGeeks** [espnet/espnet#4525]
Hi 

I am trying to train a model for text to speech in German.. I Have been able to train the model using espeak-ng backend, but at inference time I cant get the model to do inference. I am using Amazon Linux 2 as OS 

**For training I run the following code**
I am using espak-ng german for training using the following commands

```
!./tts.sh  --stage 2  --ngpu 1  --train_set train  --valid_set valid  --test_sets test  --stop-stage 2
!./tts.sh --stage 3 --stop-stage 3
!./tts.sh --stage 4 --stop-stage 4 --srctexts "data/train/text" --cleaner tacotron  --token_type phn --g2p espeak_ng_german
!./tts.sh --stage 5 --stop-stage 5 --cleaner tacotron  --token_type phn --g2p espeak_ng_german
!./tts.sh --stage 6 --stop-stage 6  --cleaner tacotron  --token_type phn --g2p espeak_ng_german --train_config '/home/ec2-user/SageMaker/espnet/egs2/German_Male/tts1/conf/tuning/train_tacotron2.yaml'
```

**For inference I run**
I tried both the espnet environment created using the ESPNET GitHub repo or using the Colab recipe 
`tts_WGAN = Text2Speech.from_pretrained(model_file=model_file,vocoder_file=vocoder_file)`
or 
'tts_GL = Text2Speech.from_pretrained(model_file=model_file)'
 and I always endup with the same error 

### this is what I get
```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
Input In [19], in <cell line: 1>()
----> 1 backend = EspeakBackend('en-us')

File ~/anaconda3/envs/espnet/lib/python3.8/site-packages/phonemizer/backend/espeak/espeak.py:44, in EspeakBackend.__init__(self, language, punctuation_marks, preserve_punctuation, with_stress, tie, language_switch, words_mismatch, logger)
     36 def __init__(self, language,
     37              punctuation_marks=Punctuation.default_marks(),
     38              preserve_punctuation=False,
   (...)
     42              words_mismatch='ignore',
     43              logger=get_logger()):
---> 44     super().__init__(
     45         language, punctuation_marks=punctuation_marks,
     46         preserve_punctuation=preserve_punctuation, logger=logger)
     48     self._espeak.set_voice(language)
     49     self._with_stress = with_stress

File ~/anaconda3/envs/espnet/lib/python3.8/site-packages/phonemizer/backend/espeak/base.py:36, in BaseEspeakBackend.__init__(self, language, punctuation_marks, preserve_punctuation, logger)
     32 def __init__(self, language,
     33              punctuation_marks=Punctuation.default_marks(),
     34              preserve_punctuation=False,
     35              logger=get_logger()):
---> 36     self._espeak = EspeakWrapper()
     37     logger.debug('loaded %s', self._espeak.library_path)
     39     super().__init__(
     40         language,
     41         punctuation_marks=punctuation_marks,
     42         preserve_punctuation=preserve_punctuation,
     43         logger=logger)

File ~/anaconda3/envs/espnet/lib/python3.8/site-packages/phonemizer/backend/espeak/wrapper.py:59, in EspeakWrapper.__init__(self)
     56 self._voice = None
     58 # load the espeak API
---> 59 self._espeak = EspeakAPI(self.library())
     61 # lazy loading of attributes only required for the synthetize method
     62 self._libc_ = None

File ~/anaconda3/envs/espnet/lib/python3.8/site-packages/phonemizer/backend/espeak/wrapper.py:149, in EspeakWrapper.library(cls)
    **145 library = (
    146     ctypes.util.find_library('espeak-ng') or
    147     ctypes.util.find_library('espeak'))
    148 if not library:  # pragma: nocover
--> 149     raise RuntimeError(
    150         'failed to find espeak library')
    151 return library**

RuntimeError: failed to find espeak library
```

When I check my installation I see that phonemizer is installed .

any ideas how I can resolve this issue?

**Comment by kan-bayashi** [comment]
You need add path for espeak library.
When running `run.sh`, `tools/extra_path.sh` is sourced. 
And then, LD_LIBRRARY_PATH is updated.

Before running inference scripts, you need to add their path.
https://github.com/espnet/espnet/blob/695c9954e20800875b22d985e9c0b0a70e8e2082/tools/extra_path.sh#L27-L28

**Comment by AliNGatGeeks** [comment]
I did some tests, in my case, 
TOOL_DIR = /home/ec2-user/SageMaker/espnet/tools

no lib or lib64 where present in this path (is this going to be a problem?)

in TOOL_DIR/espean-ng/lib
I can see espeak-ng.so (but is seems to be hidden)

in any case running the commands 

 export LD_LIBRARY_PATH="${TOOL_DIR}"/lib:"${TOOL_DIR}"/lib64:"${LD_LIBRARY_PATH:-}" 
 export LD_LIBRARY_PATH="${TOOL_DIR}"/espeak-ng/lib:"${LD_LIBRARY_PATH:-}" 

and printing LD_LIBRARY_PATH gives me:
bash: /opt/amazon/efa/lib64:/opt/amazon/openmpi/lib64:/usr/local/lib:/usr/lib:/lib:/opt/amazon/efa/lib64:/opt/amazon/openmpi/lib64:/usr/local/lib:/usr/lib:/lib:/opt/amazon/efa/lib64:/opt/amazon/openmpi/lib64:/usr/local/lib:/usr/lib:/lib:: No such file or directory

and I still get the same error!

any thoughts?

**Comment by AliNGatGeeks** [comment]
I managed to solve the problem by using this command:

from phonemizer.backend.espeak.wrapper import EspeakWrapper
EspeakWrapper.set_library('/home/ec2-user/SageMaker/espnet/tools/espeak-ng/src/.libs/libespeak-ng.so.1.1.51')

Thank you very much
