### ISSUE TITLE
long outputs in beam search

### ISSUE THREAD

**Issue by fotwo** [espnet/espnet#453]

**Comment by fotwo** [comment]
Hi all, 
I encounter an issue when try to reproduce the result of attention-based model(only using attention via setting `mtlalpha` to 0.0). 
While, the final model seems to output as long as the input sequence in beam search. Although `maxlenratio` can be used, it also harm the performance. I consider whether there are better solutions in both training and recognition procedure? 
Thanks for help and tips?

**Comment by sw005320** [comment]
@fotwo, did you observe it after our recent change by #318?
If so, @mn5k, can you handle this?

**Comment by fotwo** [comment]
what's more, both of two trained models(one is trained with `mtlalpha==0.0`, and the other is with `mtlalpha==0.5`) have the similar best performance on train-dev set which is about 65% acc.

**Comment by fotwo** [comment]
It seems that when using ctc in decoding, it will produce `ctc_beam` to prune the score first. 
Therefore, I try to change the `beam_size` to 1, and the decoding results look normal(length is similar with groundtruth).
However, when I changed `beam_size` to other value, e.g., 2, 5, 10. The decoding results will be very very long again.

**Comment by sw005320** [comment]
OK. @takaaki-hori, could you check this issue?

**Comment by fotwo** [comment]
Hi, @takaaki-hori , @sw005320 , I have figured out the reason. 
It is my fault that setting `ctc_weight==0.3` when `mtlalpha==0.0`. So the `lpz` will be used in decoding, but do bad things(because CTC component was not optimized). Very sorry for this fault and thanks so much for help.
