### ISSUE TITLE
Official aishell3 generate

### ISSUE THREAD

**Issue by wflrz123** [espnet/espnet#4534]
# I want to use the official aishell3 model to generate audio, how to solve it?
from espnet2.bin.tts_inference import Text2Speech

model = Text2Speech.from_pretrained("ftshijt/ESPnet2_pretrained_model_ftshijt_aishell3_tts_train_raw_phn_pypinyin_g2p_phone_train.loss.best")

speech, *_ = model("text to generate speech from")

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
/tmp/ipykernel_54104/3861487702.py in <module>
      3 model = Text2Speech.from_pretrained("ftshijt/ESPnet2_pretrained_model_ftshijt_aishell3_tts_train_raw_phn_pypinyin_g2p_phone_train.loss.best")
      4 
----> 5 speech, *_ = model("text to generate speech from")

~/miniconda3/envs/espnetv2/lib/python3.7/site-packages/torch/autograd/grad_mode.py in decorate_context(*args, **kwargs)
     25         def decorate_context(*args, **kwargs):
     26             with self.__class__():
---> 27                 return func(*args, **kwargs)
     28         return cast(F, decorate_context)
     29 

~/i_liaoruizhi/espnet/espnet2/bin/tts_inference.py in __call__(self, text, speech, durations, spembs, sids, lids, decode_conf)
    161         # check inputs
    162         if self.use_speech and speech is None:
--> 163             raise RuntimeError("Missing required argument: 'speech'")
    164         if self.use_sids and sids is None:
    165             raise RuntimeError("Missing required argument: 'sids'")

RuntimeError: Missing required argument: 'speech'

**Comment by kan-bayashi** [comment]
The model may use GST, which requires additional reference speech.
You need to pass speech as well. Please check the multi-spk with GST example.
https://colab.research.google.com/github/espnet/notebook/blob/master/espnet2_tts_realtime_demo.ipynb

**Comment by wflrz123** [comment]
Thank you~
