### ISSUE TITLE
transducer loss impl formula diff in cpu and gpu

### ISSUE THREAD

**Issue by zh794390558** [espnet/espnet#4542]
@b-flo I read the source of transducer loss impl, but confused with cpu and gpu grad implementation, which has `Tp grad = exp(alphas[col] + betas[col] + logpk - logll[mb]);` in gpu grad kernel, but not in cpu. Can you give some explanation for that, thx very much.

**Comment by b-flo** [comment]
Hi,

> Can you give some explanation for that, thx very much.

Sorry, I don't know why Mingkun (the author of `warp-transducer`) made the CPU and GPU grad differ nor if it's intended.
I was made aware of the issue in a few instances but, well, the CPU version is not used so we didn't bother to rework it in our fork.

Btw,

https://espnet.github.io/espnet/tutorial.html#transducer
> Important: If you encounter any issue related to Transducer loss, please open an issue in [our fork of warp-transducer](https://github.com/b-flo/warp-transducer).

I'm closing the issue but feel free to open a new one in the highlighted repo. You can ask for a fix/rework but be aware that it's a low priority for us right now!
