### ISSUE TITLE
Memory leak on FastSpeech2?

### ISSUE THREAD

**Issue by iamanigeeit** [espnet/espnet#4544]
When i train my FastSpeech2 model, it consistently gets killed after 102 epochs by OOM Killer due to too much RAM used. When i start training, it uses about 4.3 GB memory but by the time it is killed it has doubled to around 8.8 GB. 

Is there a rough guide to how much RAM is required for training based on model parameters? Should i include `gc.collect()` after each epoch?

**Comment by kan-bayashi** [comment]
https://github.com/espnet/espnet/blob/92ea573f44e252644860b6b7906916218e4ab78b/egs2/ljspeech/tts1/conf/tuning/train_conformer_fastspeech.yaml#L1
You can check header of yaml file.

**Comment by iamanigeeit** [comment]
> https://github.com/espnet/espnet/blob/92ea573f44e252644860b6b7906916218e4ab78b/egs2/ljspeech/tts1/conf/tuning/train_conformer_fastspeech.yaml#L1
> 
> 
> You can check header of yaml file.

Thanks for the reply, i understood the 12 GB as GPU memory. On default settings it takes about 15 GB of GPU memory but the RAM usage keeps growing (at 244 epochs RAM usage is 11 GB).

**Comment by iamanigeeit** [comment]
I can confirm that this problem has to do with the Tensorboard graph creation in https://github.com/espnet/espnet/issues/4543

If i comment out lines 517-546 of https://github.com/espnet/espnet/blob/master/espnet2/train/trainer.py the RAM usage does not exceed 5 GB.

**Comment by kan-bayashi** [comment]
Thank you for your investigation, @iamanigeeit. This is very helpful.
