### ISSUE TITLE
Mel spectrogram extraction from TTS

### ISSUE THREAD

**Issue by saiakarsh193** [espnet/espnet#4547]
I want to directly get the mel-spectrogram rather than the wav array.

Currently to get the wav file from a sentence we do,
```python
from espnet2.bin.tts_inference import Text2Speech
import soundfile as sf

text2speech = Text2Speech.from_pretrained(train_config=config_path, model_file=model_path)
wav = text2speech(sentence)["wav"]
sf.write(outpath, wav.numpy(), text2speech.fs, "PCM_16")
```

But this saves the wav file directly. How do i get the intermediate mel spectrogram and its configuration?

**Comment by kan-bayashi** [comment]
That is quite easy.

```python
# output dict contains some keys including feat_gen and feat_gen_denorm, which are generated mel-spectrogram
output_dict = text2speech(sentence)
```

And you can find `feat_extract_conf` in `train_config`, which shows the hyperparameters of mel-spectrogram.
