### ISSUE TITLE
ModuleNotFoundError: No module named 'chainer'

### ISSUE THREAD

**Issue by cjgdo** [espnet/espnet#4550]
i have install chainer and the version of chainer is Version: 5.4.0  ,but still say  ModuleNotFoundError: No module named 'chainer',can someone good people help me 

[train.log](https://github.com/espnet/espnet/files/9231879/train.log)

**Comment by kan-bayashi** [comment]
Please follow the installation instruction. Then, you do not need to install chainer manually.
https://espnet.github.io/espnet/installation.html
