### ISSUE TITLE
does the process stuck?

### ISSUE THREAD

**Issue by zdyupup** [espnet/espnet#4559]
I'm training the librispeech scipe in espnet2,  but it's not update train_log file, and the process is stucking like this:

[f3d8bac11bcb] 2022-08-08 08:47:09,516 (trainer:275) INFO: 1/50epoch started
[f3d8bac11bcb] 2022-08-08 08:47:10,257 (trainer:537) WARNING: summary_writer.add_graph() is failed for the model. The graph can't be added for tensorboard.
/opt/miniconda/lib/python3.7/site-packages/torch/_tensor.py:575: UserWarning: floor_divide is deprecated, and will be removed in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values.
To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor'). (Triggered internally at  /pytorch/aten/src/ATen/native/BinaryOps.cpp:467.)
  return torch.floor_divide(self, other)
/espnet/espnet2/train/trainer.py:639: FutureWarning: Non-finite norm encountered in torch.nn.utils.clip_grad_norm_; continuing anyway. Note that the default behavior will change in a future release to error out if a non-finite total norm is encountered. At that point, setting error_if_nonfinite=false will be required to retain the old behavior.
  norm_type=grad_clip_type,
[f3d8bac11bcb] 2022-08-08 08:47:11,459 (trainer:647) WARNING: The grad norm is nan. Skipping updating the model.
[f3d8bac11bcb] 2022-08-08 08:47:12,425 (trainer:647) WARNING: The grad norm is nan. Skipping updating the model.
[f3d8bac11bcb] 2022-08-08 08:47:13,454 (trainer:647) WARNING: The grad norm is nan. Skipping updating the model.
[f3d8bac11bcb] 2022-08-08 08:47:14,401 (trainer:647) WARNING: The grad norm is inf. Skipping updating the model.
[f3d8bac11bcb] 2022-08-08 08:47:15,353 (trainer:647) WARNING: The grad norm is inf. Skipping updating the model.
[f3d8bac11bcb] 2022-08-08 08:47:24,328 (trainer:647) WARNING: The grad norm is inf. Skipping updating the model.
[f3d8bac11bcb] 2022-08-08 08:47:43,944 (trainer:647) WARNING: The grad norm is inf. Skipping updating the model.

I used one GPU device to test whether the scipe is work well，and the conf file is  conf/train_asr_conformer.yaml.
Could you tell me what happened?

**Comment by sw005320** [comment]
I think it just took a very long time.
Please wait for a while.
It is not a good idea to test Librispeech with a single GPU.
Please use the other smaller recipe (e.g., Librispeech 100hours) or more GPUs.

**Comment by ftshijt** [comment]
You may also check the process or GPU usage to validate if it is in running

**Comment by zdyupup** [comment]
Thank you, the smaller recipe such as an4 and Librispeech 100hours are working well, next I will use more GPUs on  Librispeech.
