### ISSUE TITLE
How to install requirements related to test or doc

### ISSUE THREAD

**Issue by kan-bayashi** [espnet/espnet#456]
In the current master, `test_requirements.txt` and `requirements.txt` are replaced by `setup.py`.
We can use `python setup.py test` to run `pytest`, but requirements for test is not installed in virtualenv.
Therefore, we cannot use linter libraries such `flake8` or `autopep8` written in test_requires of `setup.py`.

@kamo-naoyuki How do we install test or doc requirements written in `setup.py`?

**Comment by kan-bayashi** [comment]
What I want to do is to update the contribution guide.
https://github.com/espnet/espnet/blob/master/CONTRIBUTING.md
I will update it if I understand how-to-install test requirements.

**Comment by kamo-naoyuki** [comment]
You can install them manually as following,

```bash
pip install -e $REPOSITORY[test]
pip install -e $REPOSITORY[doc]
```

However,  `python setup.py test` also should install the requirements in my understanding. Could you check it again?  @kan-bayashi

**Comment by kamo-naoyuki** [comment]
We also need to update https://github.com/espnet/espnet/blob/master/doc/README.md.

**Comment by kan-bayashi** [comment]
I will close.
