### ISSUE TITLE
Can not obtain the model

### ISSUE THREAD

**Issue by zgplvyou** [espnet/espnet#4583]
I use espnet as the step in https://zenodo.org/record/4105763#.Yv2uHW9Bz0p. I got an error  
huggingface_hub.utils._errors.RepositoryNotFoundError: 401 Client Error: Repository Not Found for url:  
 https://huggingface.co/api/models/kamo-naoyuki/aishell_asr_train_asr_conformer3_raw_char_batch_bins4000000_accum_grad4_sp_valid.acc.ave/revision/main. If the repo is private, make sure you are authenticated. (Request ID: OiIGdJgVURrc_jW4ERRf1)
and in huggingface.co page I didn`t find the model.  
although the model is in the end of https://zenodo.org/record/4105763#.Yv2uHW9Bz0p, I download it but don`t konw how to use it. So anyone can upload the model to huggingface?

**Comment by zgplvyou** [comment]
@kamo-naoyuki

**Comment by kan-bayashi** [comment]
You can download from bottom of the page.
Or you can use `from_pretrained` function as follows:
```
from espnet2.bin.asr_inference import Speech2Text
speech2text = Speech2Text.from_pretrained(
    "https://zenodo.org/record/4105763/files/asr_train_asr_conformer3_raw_char_batch_bins4000000_accum_grad4_sp_valid.acc.ave.zip?download=1",
)
```
