### ISSUE TITLE
Suggestion for long audio decoding

### ISSUE THREAD

**Issue by BSen007** [espnet/espnet#4586]
Hello Team,

Thanks for this wonderful Espnet project. I did train a model (conformer-ctc) with custom data and it works well for shot audios, but miserably fails on longer audio lets say more than >10 minutes. I can see a lot of deletion and repetition of words in the hypothesis. Is there any special settings/configs for long audio files?

**Comment by b-flo** [comment]
Hi,

VAD is recommended to cut the audio into smaller parts before feeding it to the ASR system.

**Comment by BSen007** [comment]
I wonder it it could be feature to chunk a long audio inside the decoder like Nemo Does.

**Comment by b-flo** [comment]
I'm not sure I understand what you mean, could you point out the related code in NeMo?

Btw, we're talking about offline decoding, right? If we're talking about online decoding, chunks are fed so there may be some overhead in the contextual block approach (i.e.: some items growing over time which would impact decoding speed / resources)

**Comment by BSen007** [comment]
Yes, I meant offline decoding. I have not dive deep in Nemo. I have tried it and it is very fast on long audios.

**Comment by b-flo** [comment]
Which NeMo model you're talking about? a CTC-based one?
Also, I still don't understand which chunk mechanism you refering to, could you provide a link please? You mention CTC and talk about optimizations within a decoder so I'm lost here.

**Comment by BSen007** [comment]
yes CTC based one:-  https://catalog.ngc.nvidia.com/orgs/nvidia/teams/nemo/models/stt_enes_conformer_ctc_large_codesw
Even for 30 mins audio it took around 2-3 min with good accuracy. I am not very sure, but I assume they are not decoding whole audio once. I assume they do some chunk based decoding to process it fast.

**Comment by b-flo** [comment]
As far as I know, chunks are only used in the case of the "chunk-aware lookahead" with streaming models. The whole audio is fed during offline decoding.
Note that they rely on multiple optimizations we don't have in ESPnet and also saw mention of non-autoregressive "mode" for CTC. All that would explain the difference in terms of RTF.

**Comment by b-flo** [comment]
I'm closing this issue as the initial question was answered. Feel free to re-open it if needed or transfer it to Discussion.

Btw, you can also try mask CTC (non-autoregressive CTC) or Transducer if you're looking to lower RTF.
