### ISSUE TITLE
How can i use more gpu mem

### ISSUE THREAD

**Issue by yan-rui** [espnet/espnet#4587]
I am training  Conformer + specaug + speed perturbation: feats=raw, n_fft=512, hop_length=128 With Transformer LM 
here is my command which batch_size upto 160(original 20)，but gpu mem always `gpu_max_cached_mem_GB=2.773`. My GPU has 32GB mem.

`python3 -m espnet2.bin.asr_train --use_preprocessor true --bpemodel none --token_type char --token_list data/zh_token_list/char/tokens.txt --non_linguistic_symbols none --cleaner none --g2p none --valid_data_path_and_name_and_type dump/raw/dev/wav.scp,speech,kaldi_ark --valid_data_path_and_name_and_type dump/raw/dev/text,text,text --valid_shape_file exp/asr_stats_raw_zh_char_sp/valid/speech_shape --valid_shape_file exp/asr_stats_raw_zh_char_sp/valid/text_shape.char --resume true --init_param --ignore_init_mismatch false --fold_length 51200 --fold_length 150 --output_dir exp/asr_train_asr_conformer_raw_zh_char_sp --config conf/tuning/train_asr_conformer.yaml --frontend_conf fs=16k --normalize=global_mvn --normalize_conf stats_file=exp/asr_stats_raw_zh_char_sp/train/feats_stats.npz --train_data_path_and_name_and_type dump/raw/train_sp/wav.scp,speech,kaldi_ark --train_data_path_and_name_and_type dump/raw/train_sp/text,text,text --train_shape_file exp/asr_stats_raw_zh_char_sp/train/speech_shape --train_shape_file exp/asr_stats_raw_zh_char_sp/train/text_shape.char --ngpu 8 --multiprocessing_distributed True --batch_size=160`

I want to speed up training since ` Estimated time to finish: 4 days, 23 hours and 13 minutes`

Help~

Here is my config.yaml and run.sh at `espnet/egs2/aishell/asr1/exp/asr_train_asr_conformer_raw_zh_char_sp`

run.sh
`
./asr.sh --nj 32 --inference_nj 32 --ngpu 4 --lang zh --audio_format flac.ark --feats_type raw --token_type char --use_lm false --use_word_lm false --lm_config conf/train_lm_transformer.yaml --asr_config conf/train_asr_branchformer.yaml --inference_config conf/decode_asr_branchformer.yaml --train_set train --valid_set dev --test_sets 'dev test' --speed_perturb_factors '0.9 1.0 1.1' --asr_speech_fold_length 512 --asr_text_fold_length 150 --lm_fold_length 150 --lm_train_text data/train/text --ngpu 8 --stage 10 --asr_config conf/tuning/train_asr_conformer.yaml --lm_config conf/tuning/train_lm_transformer.yaml --stage 11 "$@"; exit $?
`

config.yaml

`
[config.txt](https://github.com/espnet/espnet/files/9382494/config.txt)

`

**Comment by kan-bayashi** [comment]
You can increase `batch_bins` instead of `batch_size` and reduce the `accum_grads`.
See more info
https://espnet.github.io/espnet/espnet2_training_option.html#change-mini-batch-type
https://espnet.github.io/espnet/espnet2_training_option.html#gradient-accumulating

**Comment by yan-rui** [comment]
Thanks a lot，I reslove my problem. I increased the training speed by  700%
