### ISSUE TITLE
ASR: Stage 12/13 does not generate final output

### ISSUE THREAD

**Issue by Tonyyouyou** [espnet/espnet#4588]
**Describe the bug**
When I run stage 12/13 for ASR, there is no final output for my model
 
<img width="419" alt="Screen Shot 2022-08-20 at 2 53 43 pm" src="https://user-images.githubusercontent.com/53552303/185762350-1eaccffd-cc76-44bc-b0d7-1eb4670ca6e3.png">
<img width="404" alt="Screen Shot 2022-08-20 at 2 53 56 pm" src="https://user-images.githubusercontent.com/53552303/185762411-088e6ba0-c86c-44e5-b4f2-f764fd9786ad.png">

```
In the logs file, I can see the output in each process, 
However, It does not generate the final result for scoring(text file), therefore, my WER and CER got 100.
It can generate results for the dev set, but can not generate outputs for the test set.
```

**Comment by kan-bayashi** [comment]
Please provide the log file.

**Comment by ftshijt** [comment]
@Tonyyouyou found the issue, which does not relate to our codebase. Will close it
