### ISSUE TITLE
A bug in HiFiGANScaleDiscriminator

### ISSUE THREAD

**Issue by JoeyHeisenberg** [espnet/espnet#4595]
seems that weight norm doesn't work in HiFiGANScaleDiscriminator, in which we only get conv1d

https://github.com/espnet/espnet/blob/f274ebed88e3b4820b23ea71fb7f9f6d56706be9/espnet2/gan_tts/hifigan/hifigan.py#L410-L573

**Comment by kan-bayashi** [comment]
Thank you for your report, you are right.

**Comment by kan-bayashi** [comment]
Related: https://github.com/kan-bayashi/ParallelWaveGAN/issues/309
