### ISSUE TITLE
Where is doc of Stages？

### ISSUE THREAD

**Issue by yan-rui** [espnet/espnet#4599]
Hi， I’m new  to espnet. I want to know where is the doc demonstrating what does echo stage do.
How can I find these docs plz？

**Comment by kan-bayashi** [comment]
It depends on the main developer of each task.
Which task do you want to know? (e.g., ASR, TTS, ...)

**Comment by yan-rui** [comment]
I'm trying to run [espnet](https://github.com/espnet/espnet)/[egs2](https://github.com/espnet/espnet/tree/master/egs2)/[aishell](https://github.com/espnet/espnet/tree/master/egs2/aishell)/asr1/.

**Comment by kan-bayashi** [comment]
Maybe this notebook?
https://github.com/espnet/notebook/blob/master/espnet2_tutorial_2021_CMU_11751_18781.ipynb
The stages are shared among the recipe.

**Comment by yan-rui** [comment]
THX!
