### ISSUE TITLE
accum_grad >1 is not supported in GAN-based training 

### ISSUE THREAD

**Issue by smallham** [espnet/espnet#4610]
I am trying to increate accu_grad from 1 to 2 as my cuda memory is only 8GB and currently batch_bins configured as 200,000 which is much smaller than the default value for my VITS TTS training, however I am getting error accum_grad >1 is not supported in GAN-based training. I saw advise to other people to increase this for practical high batch size.

Can you please advise if any other method to improve model? currently maximum iteration per epoch is 1000, epoch is 200 with 1200 datasets doing transfer training based on pretrained model. Thanks in advance.

**Comment by kamo-naoyuki** [comment]
How about using torch.utils.checkpoint? https://pytorch.org/docs/stable/checkpoint.html

**Comment by smallham** [comment]
@kamo-naoyuki  Hi Kamo, thanks for the reply. However this is beyond my knowledge as I can't see how to tune the configuration parameter in the config.yaml to make it happen. I would prefer something simpler inside espnet to tune the parameter. Please advise.

**Comment by kan-bayashi** [comment]
The possible solution without any code modification is only:
- reducing batch size 
- reducing segment_size

**Comment by smallham** [comment]
> The possible solution without any code modification is only:
> 
> * reducing batch size
> * reducing segment_size

Hi, @kan-bayashi thanks for the suggestion. I can see under the current configuration file segment_size is 32, batch_size is not shown as I think it maybe related to the batch_bins? So do I need to manually put batch_size here in the yaml file or just change batch_bins (I tested 640K OK). Could you please explain more how batch size is calculated here? 

Also, shall I increase iteration of each epoch if I reduce batch size? I got around 1500 voices in dataset, currently 1000 iteration. Batch_size shown under config.yaml under exp folder is 20.

(espnet) smallham@DESKTOP-NGAT8QM:~/espnet/egs2/TEST/tts1/conf/tuning$ more finetune_full_band_vits.yaml | grep segment                                                                                                                                                                                                          segment_size: 32                                                                                                                                                                                                                                                                                                     (espnet) smallham@DESKTOP-NGAT8QM:~/espnet/egs2/TEST/tts1/conf/tuning$ more finetune_full_band_vits.yaml | grep batch                                                                                                                                                                                                    batch_bins: 200000      # batch bins (feats_type=raw)                                                                                                                                                                                                                                                                        batch_type: numel         # how to make batch                                                                                                                                                                                                                                                                                sort_in_batch: descending # how to sort data in making batch                                                                                                                                                                                                                                                                 sort_batch: descending    # how to sort created batches

**Comment by kan-bayashi** [comment]
> Could you please explain more how batch size is calculated here?

Sorry for confusing. You can reduce `batch_bins`.
Please refer https://espnet.github.io/espnet/espnet2_training_option.html#change-mini-batch-type about the detail of minibatch creation.

> Also, shall I increase iteration of each epoch if I reduce batch size? I got around 1500 voices in dataset, currently 1000 iteration. Batch_size shown under config.yaml under exp folder is 20.

In the case of adaptation, ~200k iterations should generate good sounds.
I recommend checking generated voices every around 50k iters.

**Comment by smallham** [comment]
> > Could you please explain more how batch size is calculated here?
> 
> Sorry for confusing. You can reduce `batch_bins`. Please refer https://espnet.github.io/espnet/espnet2_training_option.html#change-mini-batch-type about the detail of minibatch creation.
> 
> > Also, shall I increase iteration of each epoch if I reduce batch size? I got around 1500 voices in dataset, currently 1000 iteration. Batch_size shown under config.yaml under exp folder is 20.
> 
> In the case of adaptation, ~200k iterations should generate good sounds. I recommend checking generated voices every around 50k iters.

@kan-bayashi Thanks for the advise. I will try and see if improvement. Just to ask when do we need to increase maximum iteration value of each epoch from default 1000 to 1500 e.g. to increase iteration or just simply change epoch number is good enough.

**Comment by kan-bayashi** [comment]
You can change the following two parameters as you want:
https://github.com/espnet/espnet/blob/66edc5939b2da85828f57efd2a1739a326b67017/egs2/jvs/tts1/conf/tuning/finetune_vits.yaml#L160-L161
The total iterations will be `num_iters_per_epoch` * `num_epochs`.

**Comment by smallham** [comment]
Thanks @kan-bayashi,  if my understanding correct, even num_iters_per_epoch is 1000, I can still keep the parameter with this value and all my dataset (say, 3000 voices) will still be completely trained under 1 epoch. Is this correct?

**Comment by kan-bayashi** [comment]
Right. You can use the default value.
Or you can comment out `num_iters_per_epoch` line to use the standard epoch.
Since ESPnet does not have iteration-based specification, `num_iters_per_epoch` is an alternative to realize to specify the total number of iterations.
