### ISSUE TITLE
utils/parse_options.sh No such file or directory error

### ISSUE THREAD

**Issue by morcellinus** [espnet/espnet#4613]
Hi, I'm trying to train multi speaker gst-tacotron2 tts moduleusing vctk corpus

I've set my cd as follows:
 cd espnet/egs2/vctk/tts1

and tried to run the training with command:

./run.sh --train_config ./conf/tuning/train_gst_tacotron2.yaml

and this returns an error : "./tts.sh: line 214: utils/parse_options.sh: No Such file or directory

I'm new to this toolkit so my description might be confusing.

please ask me any further details you need to know to solve this issue

thx.

**Comment by kan-bayashi** [comment]
Did you follow the instructions?
https://espnet.github.io/espnet/installation.html

**Comment by morcellinus** [comment]
OMG

after following the instructions, it works well

Thank you so much
