### ISSUE TITLE
Male Voice TTS Worse Than Female

### ISSUE THREAD

**Issue by MMingabc** [espnet/espnet#4618]
I am training a male voice TTS using Fastspeech2. I found male voice converges much slower than female and the sound quality is worse. What do I do to improve male TTS sound quality?
Thank you!

**Comment by kan-bayashi** [comment]
In the most of cases, all you need is data cleaning.
https://github.com/espnet/espnet/blob/master/egs2/TEMPLATE/tts1/README.md#why-the-model-cannot-be-trained-well-with-my-own-dataset
The following discussion may be related.
https://github.com/espnet/espnet/discussions/4367
