### ISSUE TITLE
How can I use GPU to infer ?

### ISSUE THREAD

**Issue by yan-rui** [espnet/espnet#4622]
I want to use GPU to infer my model.
I follow this recipe https://zenodo.org/record/4105763#.YxVuAXZBwuV.
I use following cmd to infer,  but not work
CUDA_VISIBLE_DEVICES=0 ./run.sh --ngpu 1 --stage 12 --stop_stage 12  --asr_config conf/tuning/train_asr_conformer.yaml --lm_config conf/tuning/train_lm_transformer.yaml

**Comment by imdanboy** [comment]
Are you using asr.sh?
Then, have you checked the argument 'gpu_inference'? at
https://github.com/espnet/espnet/blob/master/egs2/TEMPLATE/asr1/asr.sh#L37

**Comment by yan-rui** [comment]
Thank you
