### ISSUE TITLE
Requesting pre-trained models for Indic TTS

### ISSUE THREAD

**Issue by nellorebhanuteja** [espnet/espnet#4641]
Hi
There are TTS recipes provided for IndicSpeech corpus and CMUIndic corpus as well.
Can the corresponding persons provide pretrained models as well for reference ?

**Comment by nellorebhanuteja** [comment]
@peter-yh-wu

**Comment by peter-yh-wu** [comment]
Hi, thanks for your interest in this recipe. @soumimaiti has the latest/best version of these models. Otherwise, I'm happy to reproduce that version and share it with you in about 3 weeks. If you need it sooner, we're definitely willing to walk you through how to train it. - Peter

**Comment by nellorebhanuteja** [comment]
thank you peter
i was trying to run the recipe provided [here ](https://github.com/espnet/espnet/tree/master/egs2/indic_speech/tts1)

For some reason, run.pl is failing 

This is the log
```
# pyscripts/audio/format_wav_scp.py --fs 48000 --audio-format wav dump/raw/org/tr_no_dev_phn/logs/wav.1.scp dump/raw/org/tr_no_dev_phn/data/format.1 
# Started at Fri Sep 16 11:43:24 UTC 2022
#
2022-09-16 11:43:26,058 (format_wav_scp:43) INFO: /mnt/miniconda3/envs/espnet/bin/python3 pyscripts/audio/format_wav_scp.py --fs 48000 --audio-format wav dump/raw/org/tr_no_dev_phn/logs/wav.1.scp dump/raw/org/tr_no_dev_phn/data/format.1

0it [00:00, ?it/s]
269it [00:00, 2684.85it/s]
394it [00:00, 2688.85it/s]
# Accounting: time=2 threads=1
# Ended (code 0) at Fri Sep 16 11:43:26 UTC 2022, elapsed time 2 seconds
```

how shall we connect ?

**Comment by nellorebhanuteja** [comment]
@soumimaiti
Can you please share recipe and models you have for indic tts ?

**Comment by soumimaiti** [comment]
Hi @nellorebhanuteja,   You can find hin_ab cmu_indic transformer tts model here https://huggingface.co/espnet/transformer_tts_cmu_indic_hin_ab . You can also use a better model https://huggingface.co/espnet/transformer_tts_cmu_indic_hin_ab_finetune for the same voice which is finetuned.
