### ISSUE TITLE
teacher_dumpdir is not used during TTS inference

### ISSUE THREAD

**Issue by iamanigeeit** [espnet/espnet#4643]
I set `teacher_dumpdir` in the command line as i wanted teacher forcing during inference. However, it is ignored as it's set to False in `tts.sh`.

Suggest to edit `tts.sh`

```
 if [ -n "${teacher_dumpdir}" ]; then
                # Use groundtruth of durations
                _teacher_dir="${teacher_dumpdir}/${dset}"
                _ex_opts+="--data_path_and_name_and_type ${_teacher_dir}/durations,durations,text_int "
```

to add this line 
```
_ex_opts+="--use_teacher_forcing true "
```

**Comment by kan-bayashi** [comment]
This is intensional because we usually do not want to use `teacher_forcing`.
Therefore, the option is set to False as a default.
