### ISSUE TITLE
Issue in enh_asr.sh

### ISSUE THREAD

**Issue by YoshikiMas** [espnet/espnet#4650]
**Describe the bug**
As discussed with @Emrys365, [these lines](https://github.com/YoshikiMas/espnet/blob/6d5236553b7fb3e653907c447bbbbb0790a013f9/egs2/TEMPLATE/enh_asr1/enh_asr.sh#L795-L801) in `enh_asr.sh` rely on the outputs of stages 3 and 4 but are called even with `--stop_stage 1`.
It seems not to cause a bad effect to the generated data, but can we avoid the following error?

**Basic environments:**
 - OS information: Ubuntu 20.04.3 LTS (x86_64)
 - python version: 3.7.4 (default, Aug 13 2019, 20:35:49)  [GCC 7.3.0] (64-bit runtime)
 - espnet version: espnet 202207
 - Git hash 6d5236553b7fb3e653907c447bbbbb0790a013f9
 - pytorch version 1.10.1+cu111 
 

**Task information:**
 - Task: ENH_ASR
 - Recipe: wsj0_2mix_spatialized
 - ESPnet2

**To Reproduce**
1. move to docker directory
2. execute `run.sh` as `bash run.sh --docker-gpu 0 --is-egs2 --docker-egs wsj0_2mix_spatialized/enh_asr1 --ngpu 1 --stage 1 --stop-stage 1`
3. I got the error in the command line.

**Error logs**
```
./enh_asr.sh: line 799: dump/raw/lm_dev.txt: No such file or directory                                                                     
awk: fatal: cannot open file `dump/raw/cv_spatialized_anechoic_multich_max_16k/text_spk1' for reading (No such file or directory)

```

**Comment by Emrys365** [comment]
@simpleoier It seems we should move [these lines](https://github.com/espnet/espnet/blob/master/egs2/TEMPLATE/enh_asr1/enh_asr.sh#L796-L801) inside some stage, so that no error will occur if `--stage 1 --stop_stage 1` is specified.

```bash
if ! "${skip_train}"; then
    if "${use_lm}"; then
        if [ "$lm_dev_text" = "${data_feats}/${valid_set}/text" ]; then
            for n in $(seq ${spk_num}); do
                awk -v spk=$n '{$1=$1 "_spk" spk; print $0}' "${data_feats}/${valid_set}/text_spk${n}"
            done | awk ' { if( NF != 1 ) print $0; } '  > "${data_feats}/lm_dev.txt"
            lm_dev_text="${data_feats}/lm_dev.txt"
        fi

        if [ ${stage} -le 6 ] && [ ${stop_stage} -ge 6 ]; then
            log "Stage 6: LM collect stats: train_set=${data_feats}/lm_train.txt, dev_set=${lm_dev_text}"

            _opts=
            if [ -n "${lm_config}" ]; then
                # To generate the config file: e.g.
                #   % python3 -m espnet2.bin.lm_train --print_config --optim adam
                _opts+="--config ${lm_config} "
            fi
...
```

**Comment by Emrys365** [comment]
BTW, it might be better to replace the argument [`--init_param` in stage 11](https://github.com/espnet/espnet/blob/master/egs2/TEMPLATE/enh_asr1/enh_asr.sh#L1340) as follows to allow specifying this argument either in command line or the yaml file:

```diff
        # shellcheck disable=SC2086
        ${python} -m espnet2.bin.launch \
            --cmd "${cuda_cmd} --name ${jobname}" \
            --log "${enh_asr_exp}"/train.log \
            --ngpu "${ngpu}" \
            --num_nodes "${num_nodes}" \
            --init_file_prefix "${enh_asr_exp}"/.dist_init_ \
            --multiprocessing_distributed true -- \
            ${python} -m espnet2.bin.enh_s2t_train \
                --use_preprocessor true \
                --text_name ${text_names} \
                --bpemodel "${bpemodel}" \
                --token_type "${token_type}" \
                --token_list "${token_list}" \
                --non_linguistic_symbols "${nlsyms_txt}" \
                --cleaner "${cleaner}" \
                --g2p "${g2p}" \
                --resume true \
-                --init_param ${pretrained_model} \
+                ${pretrained_model:+--init_param $pretrained_model} \
                --ignore_init_mismatch ${ignore_init_mismatch} \
                --output_dir "${enh_asr_exp}" \
                ${_opts} ${enh_asr_args}
```

**Comment by simpleoier** [comment]
Hi @Emrys365 I agree with the `init_param` replacements. It also happens for `asr.sh` and `enh_st.sh`.
About the error of lm_dev_txt, we could also move it. One option is [here](https://github.com/espnet/espnet/blob/85bef5609cfd78b4756b52fbc3880bb0e7865517/egs2/TEMPLATE/enh_asr1/enh_asr.sh#L690). What do you think of it?

**Comment by YoshikiMas** [comment]
The change related to `--init_param` works well in my environment.

**Comment by Emrys365** [comment]
> Hi @Emrys365 I agree with the `init_param` replacements. It also happens for `asr.sh` and `enh_st.sh`.
> 
> About the error of lm_dev_txt, we could also move it. One option is [here](https://github.com/espnet/espnet/blob/85bef5609cfd78b4756b52fbc3880bb0e7865517/egs2/TEMPLATE/enh_asr1/enh_asr.sh#L690). What do you think of it?

Thanks. It looks fine to me.

**Comment by YoshikiMas** [comment]
This issue was addressed by the [PR](https://github.com/espnet/espnet/pull/4706).
