### ISSUE TITLE
does 【utils/subset_data_dir.sh data/train 250 data/dev】 split all files in the data/train?

### ISSUE THREAD

**Issue by 1nlplearner** [espnet/espnet#4653]
i want to generate duration when executing [https://github.com/espnet/espnet/blob/master/egs2/aishell3/tts1/local/data.sh](url)
at stege 1, the shell executes [https://github.com/espnet/espnet/blob/master/egs2/aishell3/tts1/local/data_prep.py](url)
i modify the file like this
`import argparse
import os
import textgrid
from convert_textgrid_to_duration import get_alignment
from espnet2.utils.types import str2bool

SPK_LABEL_LEN = 7

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--src", type=str)
    parser.add_argument("--dest", type=str)
    parser.add_argument("--external_g2p", type=str, default='pypinyin_g2p_phone')

    args = parser.parse_args()

    wav_dir = os.path.join(args.src, "wav")
    transcript = open(os.path.join(args.src, "content.txt"), "r", encoding="utf-8")

    wavscp = open(os.path.join(args.dest, "wav.scp"), "w", encoding="utf-8")
    utt2spk = open(os.path.join(args.dest, "utt2spk"), "w", encoding="utf-8")
    text = open(os.path.join(args.dest, "text"), "w", encoding="utf-8")
    duration = None
    if args.external_g2p == 'mfa_g2p_phone':
        duration = open(os.path.join(args.dest, 'durations'), 'w', encoding="utf-8")

    while True:
        utt_info = transcript.readline()
        if not utt_info:
            break
        (wav_name, text_info) = utt_info.strip().split("\t")
        spk_id = wav_name[:SPK_LABEL_LEN]
        utt_id = wav_name[:-4]
        
        if args.external_g2p == 'pypinyin_g2p_phone':
            text_info = "".join(text_info.split(" ")[::2])
        # my code
        elif args.external_g2p == 'mfa_g2p_phone':
            tg = textgrid.TextGrid()
            tg.read(os.path.join('AISHELL3/train/wav_aligned', spk_id, utt_id+'.TextGrid'))
            tiers = tg.tiers[1]
            text_info, durations = get_alignment(tiers)
            duration.write(durations+'\n')
        # my code end
        else:
            text_info = " ".join(text_info.split(" ")[1::2])

        wavscp.write("{} {}\n".format(utt_id, os.path.join(wav_dir, spk_id, wav_name)))
        utt2spk.write("{} {}\n".format(utt_id, spk_id))
        text.write("{} {}\n".format(utt_id, text_info))

    transcript.close()
    wavscp.close()
    utt2spk.close()
    text.close()
`
can duration be split with text at stage 3 in data.sh?
thanks

**Comment by kan-bayashi** [comment]
You can use the following option:
https://github.com/espnet/espnet/blob/4138010fb66ad27a43e8bee48a4932829a0847ae/egs2/TEMPLATE/tts1/tts.sh#L500-L509
