### ISSUE TITLE
Why use "../../utils/calculate_rft.py" instead of  "calcaulate_rft.py" in asr.sh

### ISSUE THREAD

**Issue by nuaalixu** [espnet/espnet#4658]
https://github.com/espnet/espnet/blob/85bef5609cfd78b4756b52fbc3880bb0e7865517/egs2/TEMPLATE/asr1/asr.sh#L1272

When I copy files in a example of egs2 to my own directory，and run `run.sh` in the directory. A error occurs that is “../../utils/caculate_rft.py: No such file or directory ”. Because the current directory is not under the espnet root directory, the script `caculate_rft.py` cannot be found with the path `../../utils`.
I found the path `espnet/utils` was already set as a environment variable in `path.sh`, so why not call `calcaulate_rft.py` in `asr.sh` directly?

**Comment by sw005320** [comment]
This is a good suggestion!
I made a PR.
Thanks!
