### ISSUE TITLE
Can't create 'activate_python.sh'

### ISSUE THREAD

**Issue by dnjdsxor21** [espnet/espnet#4661]
**Describe the issue**
Hello, I'm using Anaconda on Windows. python 3.7
I'm trying to install epsnet. With step 2.3, I wrote this code in anaconda prompt : 

cd <my espnet_root>/tools
setup_anaconda.sh anaconda espnet 3.7

However, 'activate_python' is never created in ' <my espnet_root>/tools ' . Thank you

**Comment by sw005320** [comment]
Are you making `tools` under a root directory?
It is better to make it under the home or other working directory.

**Comment by dnjdsxor21** [comment]
I'm making under `User/PycharmProjects/pythonProjects/espnet/tools`  as espnet root

**Comment by dnjdsxor21** [comment]
I'm making under `User/PycharmProjects/pythonProjects/espnet/tools`  as espnet root
