### ISSUE TITLE
lattice produce

### ISSUE THREAD

**Issue by zhhao-cn** [espnet/espnet#4665]
**Describe the bug**
I want to perform fusion of multiple speech recognition systems by using lattice. Is there a recipe for generating lattices in espnet2?

**Comment by sw005320** [comment]
Please use k2 integration.
Please check https://github.com/espnet/espnet/blob/master/egs2/librispeech/asr1/README.md#ctc-decoding-with-nbest-rescoring-from-decoder-and-lm-using-k2

**Comment by zhengzheng-yay** [comment]
> Please use k2 integration. Please check https://github.com/espnet/espnet/blob/master/egs2/librispeech/asr1/README.md#ctc-decoding-with-nbest-rescoring-from-decoder-and-lm-using-k2

I want to ask that using the K2 integration, we can achieve great results just by using the ctc decoding to creat lattices, instead of using the attention decode for joint decoding.Am I right?

**Comment by sw005320** [comment]
Right.

**Comment by zhhao-cn** [comment]
> Right.

Thanks for your answer. Another question is the multi-model decoding. In fairseq, fariseq-generate can accept multi checkpoints with different structure. In each decode time step, it will average the predicted probability of different model. Does espnet2 support such operation?

**Comment by sw005320** [comment]
We do not support it as an option, but the espnet scorer (https://github.com/espnet/espnet/blob/b008ac7d58e9ced1a9f8c89cc85ee69d9e9461ab/espnet/nets/scorer_interface.py) is designed for such purposes.

For example, in espnet, all scores from multiple models (e.g., language model, encoder-decoder model, CTC model, etc.) are written as this scorer, and the final score during beam search was obtained by the weighted summation over these scores https://github.com/espnet/espnet/blob/b008ac7d58e9ced1a9f8c89cc85ee69d9e9461ab/espnet/nets/beam_search.py#L199.
So, you need to implement this scorer for multiple models, but it is not difficult.
The above example is in the label synchronous beam search version, but we're preparing it for the time-synchronous beam search version.

**Comment by zhhao-cn** [comment]
> 

Thanks for your answer.

**Comment by zhhao-cn** [comment]
> We do not support it as an option, but the espnet scorer (https://github.com/espnet/espnet/blob/b008ac7d58e9ced1a9f8c89cc85ee69d9e9461ab/espnet/nets/scorer_interface.py) is designed for such purposes.
> 
> For example, in espnet, all scores from multiple models (e.g., language model, encoder-decoder model, CTC model, etc.) are written as this scorer, and the final score during beam search was obtained by the weighted summation over these scores
> 
> https://github.com/espnet/espnet/blob/b008ac7d58e9ced1a9f8c89cc85ee69d9e9461ab/espnet/nets/beam_search.py#L292-L306
> 
> .
> So, you need to implement this scorer for multiple models, but it is not difficult.
> The above example is in the label synchronous beam search version, but we're preparing it for the time-synchronous beam search version.

Sorry to bother you again. If i have two model, and both of them perform joint ctc/attention decode, can i merge there scores for the time-synchronous. Supposed the final weighted scores are weighted_scores1 and weighted_scores2, which is calculate as you point above.
weighted_scores_final = weight1*weighted_scores1  + weight2*weighted_scores2
I want to know such operation is reasonable or not.

**Comment by sw005320** [comment]
It is doable in the time-synchronous manner, where you combine the attention score similar to the LM score.
It's not in the current espnet, but we have that internally, and we'll release it soon.
