### ISSUE TITLE
Transfer learning for TTS task

### ISSUE THREAD

**Issue by saiakarsh193** [espnet/espnet#4666]
Hey,
I am wondering how to use a pre-trained model and perform transfer learning on a smaller dataset for TTS.  
I looked into the docs and issues. I was not able to find anything. Can someone point me in the right direction?
Thanks

**Comment by kan-bayashi** [comment]
Please check https://github.com/espnet/espnet/blob/master/egs2/TEMPLATE/tts1/README.md
