### ISSUE TITLE
There are tasks that ESPNET does with S3PRL that fail

### ISSUE THREAD

**Issue by abcdbosh** [espnet/espnet#4675]
File "/media/shiyanshi/E/espnet/espnet2/asr/frontend/s3prl.py", line 26, in init
import s3prl.nn
ModuleNotFoundError: No module named 's3prl.nn'
Error: S3PRL is not properly installed.
Please install S3PRL: cd ${MAIN_ROOT}/tools && make s3prl.done

But S3PRL is successfully installed and can also be imported successfully in the terminal，How do I fix it?

**Comment by bofenghuang** [comment]
Hi, I tried to pull the new update of s3prl and worked for me.

**Comment by bofenghuang** [comment]
Hi @simpleoier , should this last line be removed ? As the new [espnet/tools/installers/install_s3prl.sh](https://github.com/espnet/espnet/blob/ebdd5c792a5003dacc7f149f043835727f927be4/tools/installers/install_s3prl.sh) doesn't clone to `tools` any more.

https://github.com/espnet/espnet/blob/ebdd5c792a5003dacc7f149f043835727f927be4/tools/extra_path.sh#L29
