### ISSUE TITLE
WavLM precompute feature

### ISSUE THREAD

**Issue by cyaaronk** [espnet/espnet#4690]
Hello,

As the best ASR models now mostly use some pretrained large models as input feature and are further finetuned on some specific domain, it will be very convenient to have the large model features precomputed so the forward pass can be skipped, and to save huge amount of training cost.

Is this possible? Are there something similar already implemented?
If not, I would like to know where to start and your suggestions.

Best regards,
Aaron

**Comment by sw005320** [comment]
This is a great suggestion!
Although it would consume disk space a lot, it is still valid.
@simpleoier, do you have such an implementation?
Is it possible?

**Comment by simpleoier** [comment]
@cyaaronk Sorry I don't have such implementations. But one thing I want to note is that sometimes we use the weighted-sum of the large model features. You should care about this when you implement it. You'll need to care about the model.

To implement it, here are some points I could think of:

1. Before stage 3, dumping the large-model features in kaldi ark style
2. In stage 3 & 4 and the later stages, use `feats_type=extracted` 
3. In the model, add a learnable parameter used for feature layerwise weights.

**Comment by cyaaronk** [comment]
@simpleoier Thank you. I didn't know about feats_type=extracted. Good thing it exists!

**Comment by ftshijt** [comment]
The process should be possible @sw005320 . One of my recent projects will add that to the whole stream. Though it would include in the new task, but probably we could also make that for other tasks as well? It would be quite efficient in terms of time (for our case, almost 10x faster)

**Comment by sw005320** [comment]
Very cool.
We can add it later, then.

**Comment by cyaaronk** [comment]
I have implemented part of the feature
#4711

**Comment by cyaaronk** [comment]
Let me know if there are issues
