### ISSUE TITLE
CPU decoding speed of batch processing

### ISSUE THREAD

**Issue by sw005320** [espnet/espnet#470]
I'm testing my Librispeech recipe, and found significant speed degradation of the decoding (x10~x100 slower) due to #318. I used a default setup (CPU based and batch size = 1).

@mn5k, do you have any idea?

**Comment by sw005320** [comment]
OK. For now, I disabled it. Can we make only CTC-prefix score computation original one in the batch processing? This would solve the issue I think.

**Comment by kan-bayashi** [comment]
I also confirmed that decodig is quite slow in the case of CSJ recipe.
I will change the recipe default to batchsize=0.

**Comment by sw005320** [comment]
@mn5k, I think it's better to use original CTC-prefix score computation even during the batch processing. Can you consider it?

**Comment by nipengmath** [comment]
> I also confirmed that decoding is quite slow in the case of CSJ recipe.
> I will change the recipe default to batchsize=0.

I found that batchsize=64 is slower than batchsize=0, so what is the reason, can you give me some insight please, thanks.

**Comment by sw005320** [comment]
@nipengmath, what kind of tasks did you use?
Also, this batch decoding has significant benefits when we use GPU. Please also consider it.

@mn5k, again if the problem comes from the CTC and other parts get some speed benefits, we could need to find some solutions (e.g., partly disable the parallelization of CTC).

**Comment by qmpzzpmq** [comment]
@sw005320 I still wondering. is the single GPU decoding work or not at librispeech script?

**Comment by sw005320** [comment]
The bottleneck above comes from the softmax computation with a large character set (e.g., BPE used in Librispeech). This can be efficiently (very fastly) computed by a GPU. GPU decoding could not have this issue.
