### ISSUE TITLE
Separate iter stats from epoch stats?

### ISSUE THREAD

**Issue by iamanigeeit** [espnet/espnet#4702]
I was testing variable TTS learning rates by parameter and used `warmup_steps = 1` and `num_iters_per_epoch = 50` just to see the effect.

![image](https://user-images.githubusercontent.com/13131208/194842463-0f87a314-a72b-4d14-a2e0-7c595e95b2ff.png)

The spikes happen every 50 steps because `summary_writer` is reporting the epoch scalar, not the iter scalar. 

Should we separate out the epoch scalars?

**Comment by kan-bayashi** [comment]
There is a discussion about this format.
https://github.com/espnet/espnet/pull/3910#discussion_r783897727
@siddalmia How do you think?
