### ISSUE TITLE
Installing Error when install relevant packages using tools/installers

### ISSUE THREAD

**Issue by lidl2019** [espnet/espnet#4704]
**Describe the bug**
This happens when I try to run espnet tutorials 2021 in colab

**Basic environments:*
 - python version: 3.9
 - espnet version: 2022.07
 - Git hash [e.g. b88e89fc7246fed4c2842b55baba884fe1b4ecc2]
   - Commit date [e.g. Tue Sep 1 09:32:54 2020 -0400]
 - pytorch version [e.g. pytorch 1.12.1]
![issue1](https://user-images.githubusercontent.com/59629076/194942116-35eb7f18-19b5-45f8-a06b-85ac62f9b367.jpg)
![issue2](https://user-images.githubusercontent.com/59629076/194942119-a2566628-1170-4e28-853c-6a8045c09699.jpg)

 
When I try to download using the installer provided (phonemizer or sctk) for example, the installing process finished but the "check_install.py" cannot detect the package.

Thank you and appreciate your help!

**Comment by kamo-naoyuki** [comment]
Please be aware of the python environment to be used.

```sh
. activate_python.sh && ./installers/install_phonemizer.sh
```

or

```sh
make phonemizer.done
```
