### ISSUE TITLE
[st.sh] Processing groundtruth references leaves blank lines, which inturn throws Runtime error whle computing BLEU scores

### ISSUE THREAD

**Issue by skesiraju** [espnet/espnet#4715]
The lines below from [st.sh](https://github.com/espnet/espnet/blob/master/egs2/TEMPLATE/st1/st.sh) process the `reference` text and removes non-linguistic symbols like `(Applause)` which results in empty lines for some segments (because some segments have only `Applause`). This throws ```RuntimeError: Empty or `None` reference sentence found.```
https://github.com/espnet/espnet/blob/4138010fb66ad27a43e8bee48a4932829a0847ae/egs2/TEMPLATE/st1/st.sh#L1471-L1481

The line below also removes text enclosed in parenthesis, which means words like `(Applause)`. But unlike the `hypotheses` the `reference` text does not have utterance IDs enclosed in parenthesis appended at the end of sentence.
https://github.com/espnet/espnet/blob/4138010fb66ad27a43e8bee48a4932829a0847ae/egs2/TEMPLATE/st1/st.sh#L1496

The equivalent script in [mt.sh](https://github.com/espnet/espnet/blob/master/egs2/TEMPLATE/mt1/mt.sh) avoids such processing of `reference` text. The lines are commented (see blow)
https://github.com/espnet/espnet/blob/4138010fb66ad27a43e8bee48a4932829a0847ae/egs2/TEMPLATE/mt1/mt.sh#L1177-L1187

The issue is observed on `MUST-C` corpus which is made from TED-talks.

Since both MT and ST evaluate using BLEU, they should have same processing steps. A simple fix would be to comment the respective lines in `st.sh`, just like in `mt.sh`, but should we keep non-linguistic symbols while evaluating BLEU scores ?

**Comment by sw005320** [comment]
Thanks for the report.
@brianyan918, can you confirm this case?

**Comment by brianyan918** [comment]
Hi @skesiraju! On Must-C, the ST community has been removing non-linguistic symbols. You are correct that we should fix mt.sh to match - in fact both scripts should allow for specification of this behavior per dataset.

Regarding this error that you receive:
RuntimeError: Empty or `None` reference sentence found.

Is this thrown by sacrebleu? If so, can you tell me which version of sacrebleu? And does the same error occur with sacrebley 1.5.1?

**Comment by skesiraju** [comment]
Thanks @brianyan918 
Yes, it is thrown by sacrebleu version `2.0.0`. Seems like empty lines in references was a known issue [#116](https://github.com/mjpost/sacrebleu/issues/161)  in sacrebleu, and got fixed in [v2.2.0](https://github.com/mjpost/sacrebleu/releases/tag/v2.2.0)
