### ISSUE TITLE
日本語版espnetにおいて、モデルの感情量の調整をすることは可能ですか？

### ISSUE THREAD

**Issue by mule-engineer13** [espnet/espnet#4721]
日本語で失礼いたします。
※私が英語に堪能でない点、日本語espnetに関する質問である点、メンバーに日本人の方がいらした点から、日本語でご質問させていただきました。以後、英語によるやりとりの方が適切と判断された場合にはご指摘ください。

★質問概要ーーーーーーーーーーーーーーーーーーーーーーー
●日本語版espnetの推論において、以下ふたつは可能でしょうか？
・質問１、1つの文章中でモデルを切り替えて読みあげることは可能ですか？
・質問２、複数の推論モデルを混ぜ合わせることは可能ですか？
ーーーーーーーーーーーーーーーーーーーーーーーーーーーーー

★質問１でやりたいことの具体例ーーーーーーーーーーーーーー
●前提：以下２種類のモデルがあるとします。
・普通に読み上げるモデル
・悲しい気持ちを込めて読み上げるモデル

●推論に用いる文章
「私は冷静ではありません。非常に悲しいです」

●以下のように推論して自然に読み上げることは可能でしょうか
・「私は冷静ではありません」だけを「普通に読み上げるモデル」で読み上げる
・「非常に悲しいです」だけを「悲しい気持ちを込めて読み上げるモデル」で読み上げる
ーーーーーーーーーーーーーーーーーーーーーーーーーーーーーー

★質問２でやりたいことの具体例ーーーーーーーーーーーーーー
●前提：以下２種類のモデルがあるとします。
・普通に読み上げるモデル
・悲しい気持ちを込めて読み上げるモデル

●以下を実践することは可能でしょうか
・「普通に読み上げるモデル」と「悲しい気持ちを込めて読み上げるモデル」を用いて「少し悲しい読み上げ」をする。
（モデルを混ぜて推論する）
・その際に「普通70%」、「悲しみ30%」のように感情の量を調整する
ーーーーーーーーーーーーーーーーーーーーーーーーーーーーーー

お忙しいところ恐縮ですが、ご教授いただけますと幸いです。
何卒よろしくお願いいたします。

**Comment by kan-bayashi** [comment]
質問1

残念ながら現状の実装では一度の推論でやりたいことを実現することはできません。
推論を2回に分けて結合する等の処理が必要になるでしょう。

質問2

こちらも残念ながら現状のモデルでは明示的にサポートされていません。
各感情の音声を別話者と見做し、GSTやspeaker embeddingを使ったモデルを学習後、推論時にembeddingを足し合わせたりすることで似たようなことはできるかもしれません。

**Comment by mule-engineer13** [comment]
ご回答ありがとうございます！
GST・speaker embedding等試してみます。
