### ISSUE TITLE
RuntimeError: NCCL error, invalid usage, NCCL version 2.7.8 when Multi-processing with 2-HOST jobs with 1-GPU for each host, Multi host, DistributedDataParallel

### ISSUE THREAD

**Issue by yfyeung** [espnet/espnet#4726]
### Error log
```
Traceback (most recent call last):
  File "/home/yfy62/espnet/tools/anaconda/envs/espnet/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/yfy62/espnet/tools/anaconda/envs/espnet/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/yfy62/espnet/espnet2/bin/asr_train.py", line 23, in <module>
    main()
  File "/home/yfy62/espnet/espnet2/bin/asr_train.py", line 19, in main
    ASRTask.main(cmd=cmd)
  File "/home/yfy62/espnet/espnet2/tasks/abs_task.py", line 1019, in main
    cls.main_worker(args)
  File "/home/yfy62/espnet/espnet2/tasks/abs_task.py", line 1315, in main_worker
    cls.trainer.run(
  File "/home/yfy62/espnet/espnet2/train/trainer.py", line 221, in run
    dp_model = torch.nn.parallel.DistributedDataParallel(
  File "/home/yfy62/espnet/tools/anaconda/envs/espnet/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 446, in __init__
    self._sync_params_and_buffers(authoritative_rank=0)
  File "/home/yfy62/espnet/tools/anaconda/envs/espnet/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 457, in _sync_params_and_buffers
    self._distributed_broadcast_coalesced(
  File "/home/yfy62/espnet/tools/anaconda/envs/espnet/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 1155, in _distributed_broadcast_coalesced
    dist._broadcast_coalesced(
RuntimeError: NCCL error in: /opt/conda/conda-bld/pytorch_1616554793803/work/torch/lib/c10d/ProcessGroupNCCL.cpp:825, invalid usage, NCCL version 2.7.8
ncclInvalidUsage: This usually reflects invalid usage of NCCL library (such as too many async ops, too many collectives at once, mixing streams in a group, etc).
```

### Case
-  Multi-processing with 2-HOST jobs with 1-GPU for each host, Multi host, DistributedDataParallel
- DDP HOST 1
```
#!/usr/bin/env bash

python -m espnet2.bin.asr_train \
	--use_preprocessor true \
	--bpemodel data/en_token_list/bpe_unigram5000/bpe.model \
	--token_type bpe \
	--token_list data/en_token_list/bpe_unigram5000/tokens.txt \
	--non_linguistic_symbols none \
	--cleaner none \
	--g2p none \
	--valid_data_path_and_name_and_type dump/raw/dev/wav.scp,speech,kaldi_ark \
	--valid_data_path_and_name_and_type dump/raw/dev/text,text,text \
	--valid_shape_file exp/asr_stats_raw_en_bpe5000/valid/speech_shape \
	--valid_shape_file exp/asr_stats_raw_en_bpe5000/valid/text_shape.bpe \
	--resume true \
	--init_param \
	--ignore_init_mismatch false \
	--fold_length 80000 \
	--fold_length 150 \
	--output_dir exp/asr_train_asr_rnnt_raw_en_bpe5000 \
	--config conf/train_asr_rnnt.yaml \
	--frontend_conf fs=16k \
	--normalize=global_mvn \
	--normalize_conf stats_file=exp/asr_stats_raw_en_bpe5000/train/feats_stats.npz \
	--train_data_path_and_name_and_type dump/raw/train/wav.scp,speech,kaldi_ark \
	--train_data_path_and_name_and_type dump/raw/train/text,text,text \
	--train_shape_file exp/asr_stats_raw_en_bpe5000/train/speech_shape \
	--train_shape_file exp/asr_stats_raw_en_bpe5000/train/text_shape.bpe \
	--multiprocessing_distributed True \
	--ngpu 1 \
	--dist_rank 0 \
	--dist_world_size 2 \
	--dist_master_addr <ip_addr> \
	--dist_master_port <port>
```
- DDP Host 2
```
#!/usr/bin/env bash

python -m espnet2.bin.asr_train \
	--use_preprocessor true \
	--bpemodel data/en_token_list/bpe_unigram5000/bpe.model \
	--token_type bpe \
	--token_list data/en_token_list/bpe_unigram5000/tokens.txt \
	--non_linguistic_symbols none \
	--cleaner none \
	--g2p none \
	--valid_data_path_and_name_and_type dump/raw/dev/wav.scp,speech,kaldi_ark \
	--valid_data_path_and_name_and_type dump/raw/dev/text,text,text \
	--valid_shape_file exp/asr_stats_raw_en_bpe5000/valid/speech_shape \
	--valid_shape_file exp/asr_stats_raw_en_bpe5000/valid/text_shape.bpe \
	--resume true \
	--init_param \
	--ignore_init_mismatch false \
	--fold_length 80000 \
	--fold_length 150 \
	--output_dir exp/asr_train_asr_rnnt_raw_en_bpe5000 \
	--config conf/train_asr_rnnt.yaml \
	--frontend_conf fs=16k \
	--normalize=global_mvn \
	--normalize_conf stats_file=exp/asr_stats_raw_en_bpe5000/train/feats_stats.npz \
	--train_data_path_and_name_and_type dump/raw/train/wav.scp,speech,kaldi_ark \
	--train_data_path_and_name_and_type dump/raw/train/text,text,text \
	--train_shape_file exp/asr_stats_raw_en_bpe5000/train/speech_shape \
	--train_shape_file exp/asr_stats_raw_en_bpe5000/train/text_shape.bpe \
	--multiprocessing_distributed True \
	--ngpu 1 \
	--dist_rank 1 \
	--dist_world_size 2 \
	--dist_master_addr <ip_addr> \
	--dist_master_port <port>
```

### Reason
The argument of `torch.nn.parallel.DistributedDataParallel`, `model`,  of Hosts 1 and 2 are both on the same CUDA.
```
dp_model = torch.nn.parallel.DistributedDataParallel(
	model,
	device_ids=(
		# Perform multi-Process with multi-GPUs
		[torch.cuda.current_device()]
		if distributed_option.ngpu == 1
		# Perform single-Process with multi-GPUs
		else None
	),
	output_device=(
		torch.cuda.current_device()
		if distributed_option.ngpu == 1
		else None
        ),
	find_unused_parameters=trainer_options.unused_parameters,
)
```

**Comment by kamo-naoyuki** [comment]
I'm not sure, but I think your suggestion is incorrect. 
 
Please explain what problem happens. At least, `set_device(self.dist_rank)` is incorrect because RANK is not always the same as the gpu device ID to be used even if ngpu=1.

**Comment by yfyeung** [comment]
> ### Error log
> ```
> Traceback (most recent call last):
>   File "/home/yfy62/espnet/tools/anaconda/envs/espnet/lib/python3.8/runpy.py", line 194, in _run_module_as_main
>     return _run_code(code, main_globals, None,
>   File "/home/yfy62/espnet/tools/anaconda/envs/espnet/lib/python3.8/runpy.py", line 87, in _run_code
>     exec(code, run_globals)
>   File "/home/yfy62/espnet/espnet2/bin/asr_train.py", line 23, in <module>
>     main()
>   File "/home/yfy62/espnet/espnet2/bin/asr_train.py", line 19, in main
>     ASRTask.main(cmd=cmd)
>   File "/home/yfy62/espnet/espnet2/tasks/abs_task.py", line 1019, in main
>     cls.main_worker(args)
>   File "/home/yfy62/espnet/espnet2/tasks/abs_task.py", line 1315, in main_worker
>     cls.trainer.run(
>   File "/home/yfy62/espnet/espnet2/train/trainer.py", line 221, in run
>     dp_model = torch.nn.parallel.DistributedDataParallel(
>   File "/home/yfy62/espnet/tools/anaconda/envs/espnet/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 446, in __init__
>     self._sync_params_and_buffers(authoritative_rank=0)
>   File "/home/yfy62/espnet/tools/anaconda/envs/espnet/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 457, in _sync_params_and_buffers
>     self._distributed_broadcast_coalesced(
>   File "/home/yfy62/espnet/tools/anaconda/envs/espnet/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 1155, in _distributed_broadcast_coalesced
>     dist._broadcast_coalesced(
> RuntimeError: NCCL error in: /opt/conda/conda-bld/pytorch_1616554793803/work/torch/lib/c10d/ProcessGroupNCCL.cpp:825, invalid usage, NCCL version 2.7.8
> ncclInvalidUsage: This usually reflects invalid usage of NCCL library (such as too many async ops, too many collectives at once, mixing streams in a group, etc).
> ```
> 
> ### Case
> * Multi-processing with 2-HOST jobs with 1-GPU for each host, Multi host, DistributedDataParallel
> * DDP HOST 1
> 
> ```
> #!/usr/bin/env bash
> 
> python -m espnet2.bin.asr_train \
> 	--use_preprocessor true \
> 	--bpemodel data/en_token_list/bpe_unigram5000/bpe.model \
> 	--token_type bpe \
> 	--token_list data/en_token_list/bpe_unigram5000/tokens.txt \
> 	--non_linguistic_symbols none \
> 	--cleaner none \
> 	--g2p none \
> 	--valid_data_path_and_name_and_type dump/raw/dev/wav.scp,speech,kaldi_ark \
> 	--valid_data_path_and_name_and_type dump/raw/dev/text,text,text \
> 	--valid_shape_file exp/asr_stats_raw_en_bpe5000/valid/speech_shape \
> 	--valid_shape_file exp/asr_stats_raw_en_bpe5000/valid/text_shape.bpe \
> 	--resume true \
> 	--init_param \
> 	--ignore_init_mismatch false \
> 	--fold_length 80000 \
> 	--fold_length 150 \
> 	--output_dir exp/asr_train_asr_rnnt_raw_en_bpe5000 \
> 	--config conf/train_asr_rnnt.yaml \
> 	--frontend_conf fs=16k \
> 	--normalize=global_mvn \
> 	--normalize_conf stats_file=exp/asr_stats_raw_en_bpe5000/train/feats_stats.npz \
> 	--train_data_path_and_name_and_type dump/raw/train/wav.scp,speech,kaldi_ark \
> 	--train_data_path_and_name_and_type dump/raw/train/text,text,text \
> 	--train_shape_file exp/asr_stats_raw_en_bpe5000/train/speech_shape \
> 	--train_shape_file exp/asr_stats_raw_en_bpe5000/train/text_shape.bpe \
> 	--multiprocessing_distributed True \
> 	--ngpu 1 \
> 	--dist_rank 0 \
> 	--dist_world_size 2 \
> 	--dist_master_addr <ip_addr> \
> 	--dist_master_port <port>
> ```
> 
> * DDP Host 2
> 
> ```
> #!/usr/bin/env bash
> 
> python -m espnet2.bin.asr_train \
> 	--use_preprocessor true \
> 	--bpemodel data/en_token_list/bpe_unigram5000/bpe.model \
> 	--token_type bpe \
> 	--token_list data/en_token_list/bpe_unigram5000/tokens.txt \
> 	--non_linguistic_symbols none \
> 	--cleaner none \
> 	--g2p none \
> 	--valid_data_path_and_name_and_type dump/raw/dev/wav.scp,speech,kaldi_ark \
> 	--valid_data_path_and_name_and_type dump/raw/dev/text,text,text \
> 	--valid_shape_file exp/asr_stats_raw_en_bpe5000/valid/speech_shape \
> 	--valid_shape_file exp/asr_stats_raw_en_bpe5000/valid/text_shape.bpe \
> 	--resume true \
> 	--init_param \
> 	--ignore_init_mismatch false \
> 	--fold_length 80000 \
> 	--fold_length 150 \
> 	--output_dir exp/asr_train_asr_rnnt_raw_en_bpe5000 \
> 	--config conf/train_asr_rnnt.yaml \
> 	--frontend_conf fs=16k \
> 	--normalize=global_mvn \
> 	--normalize_conf stats_file=exp/asr_stats_raw_en_bpe5000/train/feats_stats.npz \
> 	--train_data_path_and_name_and_type dump/raw/train/wav.scp,speech,kaldi_ark \
> 	--train_data_path_and_name_and_type dump/raw/train/text,text,text \
> 	--train_shape_file exp/asr_stats_raw_en_bpe5000/train/speech_shape \
> 	--train_shape_file exp/asr_stats_raw_en_bpe5000/train/text_shape.bpe \
> 	--multiprocessing_distributed True \
> 	--ngpu 1 \
> 	--dist_rank 1 \
> 	--dist_world_size 2 \
> 	--dist_master_addr <ip_addr> \
> 	--dist_master_port <port>
> ```
> 
> ### Reason
> The argument of `torch.nn.parallel.DistributedDataParallel`, `model`, of Hosts 1 and 2 are both on the same CUDA.
> 
> ```
> dp_model = torch.nn.parallel.DistributedDataParallel(
> 	model,
> 	device_ids=(
> 		# Perform multi-Process with multi-GPUs
> 		[torch.cuda.current_device()]
> 		if distributed_option.ngpu == 1
> 		# Perform single-Process with multi-GPUs
> 		else None
> 	),
> 	output_device=(
> 		torch.cuda.current_device()
> 		if distributed_option.ngpu == 1
> 		else None
>         ),
> 	find_unused_parameters=trainer_options.unused_parameters,
> )
> ```

**Comment by yfyeung** [comment]
> I'm not sure, but I think your suggestion is incorrect.
> 
> Please explain what problem happens. At least, `set_device(self.dist_rank)` is incorrect because RANK is not always same as the gpu device ID to be used even if ngpu=1. It must be LOCAL_RANK always.

You are right. I didn't set CUDA_VISIBLE_DEVICES correctly.

**Comment by kamo-naoyuki** [comment]
Okay, thanks.
