### ISSUE TITLE
the model used in ESPNET_SLU 

### ISSUE THREAD

**Issue by tjlujianqiao** [espnet/espnet#4727]
Could you let me know the size of the hubert pretrained model used in the espnet_slu model?

I mean, the hubert is large  or base or X-large?

**Comment by sw005320** [comment]
We mostly use `hubert_large_ll60k`

**Comment by tjlujianqiao** [comment]
> We mostly use `hubert_large_ll60k`
got it,

Thanks for the prompt reply ;)
