### ISSUE TITLE
Multiple encoders achieved significant performance improvement, but...

### ISSUE THREAD

**Issue by sw005320** [espnet/espnet#473]
@ruizhilijhu's study of multiple encoders https://arxiv.org/pdf/1811.04897.pdf is quite impressive (the best WER (3.6%) in the WSJ task among the end-to-end ASR systems), and I want to incorporate it to the main ESPnet repository, but the current architecture is a little bit too complicated.

Do someone has some ideas of making multiple encoders more simple (I mean less parameters, less GPU memory)?

**Comment by ShigekiKarita** [comment]
I agree with your opinion but there might be no heuristic solution for this.  One plausible solution is  model parallel. Data parallel does not always work for large models. Actually, model parallel is not difficult in chainer/pytorch when we do not use data parallel at the same time.

```python
class ParallelModule(torch.nn.Module):
    def __init__(self, modules):
        super().__init__()
        self.modules = modules

    def cuda(self):
        n = torch.cuda.device_count()
        for i, m in enumerate(self.modules):
            m.cuda(i % n)

    def forward(self, x):
        n = torch.cuda.device_count()
        for i, m in enumerate(self.modules):
            yield m(x.cuda(i % n))
```

**Comment by creatorscan** [comment]
@ruizhilijhu @ShigekiKarita The following paper discusses few solutions to handle the hierarchical structure  in section 3.
Here they mix data parallelism and model parallelism. 
https://arxiv.org/pdf/1701.06538.pdf
