### ISSUE TITLE
inference using generated model in ASR

### ISSUE THREAD

**Issue by Ishihara-Masabumi** [espnet/espnet#4732]
At asr, I have trained using jsut corpus and made 100epoch.pth.
Next, I'd like to do the inference using 100epoch.pth.
Please tell me the command line with ./run.sh.

**Comment by sw005320** [comment]
It’s stage 12
Please check our document, e.g., 
https://github.com/espnet/notebook/blob/master/espnet2_recipe_tutorial_CMU_11751_18781_Fall2022.ipynb

**Comment by Ishihara-Masabumi** [comment]
Thank you for your information.
But, there is an error "No such file: train_asr_demo_transformer.yaml" in the notebook above at the stage 10 and 11.
