### ISSUE TITLE
Upload the generated model in ASR

### ISSUE THREAD

**Issue by Ishihara-Masabumi** [espnet/espnet#4733]
At asr, I have trained using jsut corpus and made valid.acc.ave_10best.pth.
Next, I'd like to upload the generated model like valid.acc.ave_10best.pth to espnet_model_zoo.
Please tell me the command line with ./run.sh.

**Comment by sw005320** [comment]
You can check
https://github.com/espnet/espnet_model_zoo/blob/master/README.md
https://github.com/espnet/espnet/blob/master/CONTRIBUTING.md#132-espnet2-recipes

**Comment by Ishihara-Masabumi** [comment]
Thank you for your information.
But after the instruction from "https://github.com/espnet/espnet_model_zoo/blob/master/README.md",
the following error message occurs.

```
espnet_zenodo_upload: command not found
```

**Comment by Ishihara-Masabumi** [comment]
Thank you for your information.
But after the instruction from "https://github.com/espnet/espnet/blob/master/CONTRIBUTING.md#132-espnet2-recipes",
the following error message occurs.

```
Repository Not Found for url: https://huggingface.co/api/models/********/jsutasr1/revision/main.
Please make sure you specified the correct `repo_id` and `repo_type`.
If the repo is private, make sure you are authenticated.
Invalid username or password.
```
