### ISSUE TITLE
Missing key(s) in state_dict: "ctc.ctc_lo.weight", "ctc.ctc_lo.bias"

### ISSUE THREAD

**Issue by pengaoao** [espnet/espnet#4738]
**Describe the bug**
https://github.com/espnet/espnet/tree/master/egs2/librispeech/asr1
**Basic environments:**
 - OS information: x86 ubuntu 18.04
 - python version: 3.7.5
 - espnet version: espnet 0.10.7a1
 - Git hash    21d19be00089678ca27f7fce474ef8d787689512
 - pytorch version [e.g. pytorch 1.12.0]
 
**To Reproduce**
1. move to a recipe directory, e.g.,
cd egs2/librispeech/asr1
bash run.sh --stage 12

**Error logs**
Paste the error logs. If applicable, add screenshots to help explain your problem.
Missing key(s) in state_dict: "ctc.ctc_lo.weight", "ctc.ctc_lo.bias

The pretrained model is:
https://github.com/espnet/espnet/tree/master/egs2/librispeech/asr1
Conformer-RNN Transducer
Environments
date: Wed Apr 27 09:30:57 EDT 2022
espnet version: espnet 0.10.7a1
Git hash: 21d19be00089678ca27f7fce474ef8d787689512
Commit date: Wed Mar 16 08:06:52 2022 -0400
ASR config: [conf/tuning/transducer/train_conformer-rnn_transducer.yaml](https://github.com/espnet/espnet/blob/master/egs2/librispeech/asr1/conf/tuning/transducer/train_conformer-rnn_transducer.yaml)
Decode config: [conf/tuning/transducer/decode.yaml](https://github.com/espnet/espnet/blob/master/egs2/librispeech/asr1/conf/tuning/transducer/decode.yaml)
Pretrained model: https://huggingface.co/espnet/chai_librispeech_asr_train_conformer-rnn_transducer_raw_en_bpe5000_sp

1、the first error is:
![image](https://user-images.githubusercontent.com/12378083/198915176-9727dd6f-05e4-4e7f-a55a-0e5e8c15a706.png)

so I remove the fastemiut_lambda parameter

2、 then the second error is bellow when i tried to infer the given pretrained model
[Missing key(s) in state_dict: "ctc.ctc_lo.weight", "ctc.ctc_lo.bias"](https://github.com/espnet/espnet/issues/4738#top)
#4738

**Comment by b-flo** [comment]
Hi,

> 1、the first error is:
> ...
> so I remove the fastemiut_lambda parameter

How did you install `warp-transducer`? If `fastemit_lambda` is not found, it may be because you have the wrong one. We use [this branch from our fork](https://github.com/b-flo/warp-transducer/tree/espnet_v1.1).

> then the second error is bellow when i tried to infer the given pretrained model

I'm not sure why this one happened, this case should be covered. Could you update your repo just to be sure please?
@chintu619 Not sure if you've used the model since then but did you encounter a state dict mismatch?

**Comment by pengaoao** [comment]
> Hi,
> 
> > 1、the first error is:
> > ...
> > so I remove the fastemiut_lambda parameter
> 
> How did you install `warp-transducer`? If `fastemit_lambda` is not found, it may be because you have the wrong one. We use [this branch from our fork](https://github.com/b-flo/warp-transducer/tree/espnet_v1.1).
> 
> > then the second error is bellow when i tried to infer the given pretrained model
> 
> I'm not sure why this one happened, this case should be covered. Could you update your repo just to be sure please? @chintu619 Not sure if you've used the model since then but did you encounter a state dict mismatch?

the first problem has been solved by rebuilding the warp-transducer, but the second problem still exists, the similar problem appeared in espnet_onnx  https://github.com/espnet/espnet_onnx/issues/41 and it has been solved by checking if the ctc is None...

**Comment by pengaoao** [comment]
> > Hi,
> > > 1、the first error is:
> > > ...
> > > so I remove the fastemiut_lambda parameter
> > 
> > 
> > How did you install `warp-transducer`? If `fastemit_lambda` is not found, it may be because you have the wrong one. We use [this branch from our fork](https://github.com/b-flo/warp-transducer/tree/espnet_v1.1).
> > > then the second error is bellow when i tried to infer the given pretrained model
> > 
> > 
> > I'm not sure why this one happened, this case should be covered. Could you update your repo just to be sure please? @chintu619 Not sure if you've used the model since then but did you encounter a state dict mismatch?
> 
> the first problem has been solved by rebuilding the warp-transducer, but the second problem still exists, the similar problem appeared in espnet_onnx [espnet/espnet_onnx#41](https://github.com/espnet/espnet_onnx/issues/41) and it has been solved by checking if the ctc is None...

I will check it again
