### ISSUE TITLE
How to extract SpeechBrain x-vector from wav to inference??

### ISSUE THREAD

**Issue by oohara1202** [espnet/espnet#4748]
Hi!

I  try to inference using Tacotron2 with SpeechBrain x-vector.
I checked [ESPnet2-TTS realtime demonstration](https://espnet.github.io/espnet/notebook/espnet2_tts_realtime_demo.html), but that document showed only how to use  pre-extracted x-vector (maybe speaker averaged x-vector?)

I want to know hot to extract x-vector, especially SpeechBrain x-vector when using `espnet2.bin.tts_inference.Text2Speech` like reference speech selection for GST.
(I checked [#4500](https://github.com/espnet/espnet/issues/4500), however, that method may need Kaldi?? I don't want to do Kaldi if possible...)

**Comment by kan-bayashi** [comment]
You can follow this code
https://github.com/espnet/espnet/blob/af70425293e6c15fb56f83cced78afe17878b757/egs2/TEMPLATE/asr1/pyscripts/utils/extract_xvectors.py#L68-L111

**Comment by oohara1202** [comment]
Thanks all for the lighting fast response!
I am able to extract SpeechBrain x-vector.
