### ISSUE TITLE
TTS training stuck at stage 4

### ISSUE THREAD

**Issue by nihonium286** [espnet/espnet#4754]
Hello, sorry if I'm missing something obvious, I'm only starting to figure out espnet. 
I tried training TTS to my own data using [this guide](https://github.com/espnet/espnet/tree/master/egs2/TEMPLATE#how-to-makeport-new-recipe), and it's running stage 4 for a hour already, btw i`m using Collab with Tesla T4 GPU, is this hardware not enough? Would be thankful for any advise on how to train/fine-tune TTS on my voice using espnet in general.

**Comment by kan-bayashi** [comment]
Reducing nj may solve this issue.
