### ISSUE TITLE
Python3 support for scripts using numpy

### ISSUE THREAD

**Issue by ShigekiKarita** [espnet/espnet#476]
https://docs.scipy.org/doc/numpy-1.14.1/neps/dropping-python2.7-proposal.html

Since numpy will drop python2 from Jan. 2019, we should rewrite python2 scripts with numpy under `utils` to python3 compatible. Here is a list of python2-only numpy scripts under `utils`

- splitjson.py

(EDITED these files seem to be python3 compatible already)

- compute-fbank-feats.py
- compute-stft-feats.py
- convert_fbank_to_wav.py

Do you have any other python2-only script with numpy in espnet?

**Comment by sas91** [comment]
@sw005320 run_wpe.py works on python3, I can modify the shebang. Are you going to change the default python installed in tools to be python3?

**Comment by sw005320** [comment]
It's fine if it's working with python3.

**Comment by kan-bayashi** [comment]
> - compute-fbank-feats.py
> - compute-stft-feats.py
> - convert_fbank_to_wav.py

These above function is compatible with python3.

Some data prep scripts are working on only python2.
For example:
https://github.com/espnet/espnet/blob/master/egs/hkust/asr1/local/hkust_segment.py

This function uses `mmseg` which only support python2.
https://github.com/42qu/mmseg

**Comment by kan-bayashi** [comment]
Sorry, I missed `using numpy`.
Please forget about it.

**Comment by ShigekiKarita** [comment]
Thanks. Anyway we need to make the scripts python3 compatible until EOL of python2, Jan 2020.

**Comment by ShigekiKarita** [comment]
Maybe this PR can fix it. https://github.com/42qu/mmseg/pull/2
