### ISSUE TITLE
outputing word pronounciation time in TTS

### ISSUE THREAD

**Issue by pavel1860** [espnet/espnet#4761]
Hi, I need to create word reveal subtitles for the outputted TTS audio file. is there a way to extract the timing of each word in the TTS output audio file, sort of in place CTC ?  is this inforamtion even included in the outputs of the TTS model or I need to align the text with the audio using seperate CTC task?

**Comment by kan-bayashi** [comment]
If you use the model that explicit predict durations, you can get duration of each phoneme.
Maybe you can calculate the word duration using this phoneme duration.

**Comment by pavel1860** [comment]
yes. the model outpute a duration array. I am using PhonemeTokenizer to much between the input text and the duration. it mostly works, but because I don't get the phonemes back from the model, I need to seperatly much between the text and the phonemes. the problem is that there is some sort of missmuch between the durations and the phonemes from the tokenizer. usually the duration vector is longer by a length of 1 or 2 then the output of the tokenizer. I don't really understand why.

**Comment by kan-bayashi** [comment]
> usually the duration vector is longer by a length of 1 or 2 then the output of the tokenizer.

Maybe this is because `<eos>` symbol is added in the end of inputs.
