### ISSUE TITLE
推論時にアクセント・イントネーション調整を行うことは可能ですか？

### ISSUE THREAD

**Issue by mule-engineer13** [espnet/espnet#4763]
日本語で失礼いたします。
1点、質問させていただきます

●質問概要
espnetにおいて、推論時にアクセント・イントネーション調整を行うことは可能ですか。

●やりたいこと
推論時に、テキストにアクセント情報・イントネーション情報を付与して、それを読み上げ音声に反映する。

こちらでデモ等探しましたが、発見することができませんでした。
・現状機能としてできるのでしょうか？
・デモコード等がありますでしょうか？

伺えますと幸いです。
よろしくお願いいたします。

**Comment by kan-bayashi** [comment]
g2p=`pyopenjtalk_prosody` を利用し、g2pの処理結果を手動で改変することである程度実現可能です。https://github.com/espnet/espnet/tree/master/egs2/TEMPLATE/tts1#supported-text-cleaner:~:text=Based%20on%20Prosodic,i%2C%20w%2C%20a%2C%20%24%5D
