### ISSUE TITLE
How2 dataset downloading link unavailable

### ISSUE THREAD

**Issue by chlorane** [espnet/espnet#4767]
**Describe the bug**
I'm using your example program in eg2/how2_2000h, but when I run local/run_asr.sh --asr_tag asr_pretrain, the command line shows that the link to the dataset is corrupted. 

Access denied with the following error:

        Cannot retrieve the public link of the file. You may need to change
        the permission to 'Anyone with the link', or have had many accesses.

You may still be able to access the file from the browser:

         https://drive.google.com/uc?id=sharing

Can you provide a new link?

**Comment by sw005320** [comment]
Thanks for the report!
@roshansh-cmu, could you check the status?

**Comment by roshansh-cmu** [comment]
Thanks for the question and interest in the How2 data. The data will be available for access within the next 2-3 days through a Google form. I will update here once that happens, and make a PR to the ESPNet How2 recipe page.

**Comment by chlorane** [comment]
If I have the dataset, where shall I put under the directory, and which file?

**Comment by roshansh-cmu** [comment]
Please request the dataset using the data release form from the How2 data repository : https://github.com/srvk/how2-dataset.

We follow ESPNet2/ Kaldi format for the training and inference. Please refer to documentation for ESPnet2. 

Thank you for your patience

**Comment by roshansh-cmu** [comment]
You may refer to our PR #4805- this when merged should be used to prepare data from the downloaded dataset bz2 file. 

Thank you!
