### ISSUE TITLE
Can gst be used for the joint conformer fastspeech2 hifigan in ljspeech? How do you use it?

### ISSUE THREAD

**Issue by zhxiru997** [espnet/espnet#4781]
Can gst be used for the joint conformer fastspeech2 hifigan in ljspeech? How do you use it?

**Comment by George-2022-7** [comment]
are you ok

**Comment by kan-bayashi** [comment]
Please add the following lines
https://github.com/espnet/espnet/blob/ca2193d54031eb469b5a02cf60c6ff0b185d7ca4/egs2/libritts/tts1/conf/tuning/train_gst%2Bxvector_conformer_fastspeech2.yaml#L68-L70
into
https://github.com/espnet/espnet/blob/ca2193d54031eb469b5a02cf60c6ff0b185d7ca4/egs2/ljspeech/tts1/conf/tuning/train_joint_conformer_fastspeech2_hifigan.yaml#L17
