### ISSUE TITLE
setup_anaconda.sh cannot create venv directory

### ISSUE THREAD

**Issue by lunar333** [espnet/espnet#4785]
I just use the commond ./setup_anaconda.sh /data/softwares/anaconda3/ espnet 3.7, and it just create activate_python.sh , but did not create venv directory

**Comment by lunar333** [comment]
./setup_anaconda.sh /data/softwares/anaconda3/ espnet 3.7
Warning: activate_python.sh already exists. It will be overwritten
Collecting package metadata (current_repodata.json): done
Solving environment: \
Warning: >10 possible package resolutions (only showing differing packages):
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/linux-64/linux-64::conda-22.9.0-py37h06a4308_0, https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/linux-64/linux-64::ld_impl_linux-64-2.38-h1181459_1, https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/linux-64/linux-64::libstdcxx-ng-11.2.0-h1234567_1, https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/linux-64/linux-64::ncurses-6.3-h5eee18b_3
  - defaults/linux-64::conda-22.9.0-py37h06a4308_0, https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/linux-64/linux-64::ld_impl_linux-64-2.38-h1181459_1, https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/linux-64/linux-64::libstdcxx-ng-11.2.0-h1234567_1, https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/linux-64/linux-64::ncurses-6.3-h5eee18b_3
  - defaults/linux-64::ld_impl_linux-64-2.38-h1181459_1, https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/linux-64/linux-64::conda-22.9.0-py37h06a4308_0, https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/linux-64/linux-64::libstdcxx-ng-11.2.0-h1234567_1, https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/linux-64/linux-64::ncurses-6.3-h5eee18b_3
  - defaults/linux-64::conda-22.9.0-py37h06a4308_0, defaults/linux-64::ld_impl_linux-64-2.38-h1181459_1, https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/linux-64/linux-64::libstdcxx-ng-11.2.0-h1234567_1, https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/linux-64/linux-64::ncurses-6.3-h5eee18b_3
  - defaults/linux-64::ld_impl_linux-64-2.38-h1181459_1, defaults/linux-64::libstdcxx-ng-11.2.0-h1234567_1, https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/linux-64/linux-64::conda-22.9.0-py37h06a4308_0, https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/linux-64/linux-64::ncurses-6.3-h5eee18b_3
  - defaults/linux-64::conda-22.9.0-py37h06a4308_0, defaults/linux-64::ld_impl_linux-64-2.38-h1181459_1, defaults/linux-64::libstdcxx-ng-11.2.0-h1234567_1, https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/linux-64/linux-64::ncurses-6.3-h5eee18b_3
  - defaults/linux-64::libstdcxx-ng-11.2.0-h1234567_1, https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/linux-64/linux-64::conda-22.9.0-py37h06a4308_0, https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/linux-64/linux-64::ld_impl_linux-64-2.38-h1181459_1, https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/linux-64/linux-64::ncurses-6.3-h5eee18b_3
  - defaults/linux-64::conda-22.9.0-py37h06a4308_0, defaults/linux-64::libstdcxx-ng-11.2.0-h1234567_1, https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/linux-64/linux-64::ld_impl_linux-64-2.38-h1181459_1, https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/linux-64/linux-64::ncurses-6.3-h5eee18b_3
  - defaults/linux-64::libstdcxx-ng-11.2.0-h1234567_1, defaults/linux-64::ncurses-6.3-h5eee18b_3, https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/linux-64/linux-64::conda-22.9.0-py37h06a4308_0, https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/linux-64/linux-64::ld_impl_linux-64-2.38-h1181459_1
  - defaults/linux-64::ncurses-6.3-h5eee18b_3, https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/linux-64/linux-64::conda-22.9.0-py37h06a4308_0, https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/linux-64/linux-64::ld_impl_linux-64-2.38-h1181459_1, https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/linux-64/linux-64::libstdcxx-ng-11.2.0-h1234567_1
  ... and othedone


==> WARNING: A newer version of conda exists. <==
  current version: 4.14.0
  latest version: 22.9.0

Please update conda by running

    $ conda update -n base -c https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/linux-64 conda



# All requested packages already installed.

Retrieving notices: ...working... done
Collecting package metadata (current_repodata.json): done
Solving environment: |
Warning: >10 possible package resolutions (only showing differing packages):
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/linux-64/linux-64::libstdcxx-ng-11.2.0-h1234567_1, https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/linux-64/linux-64::tqdm-4.64.1-py37h06a4308_0, https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/linux-64/linux-64::yaml-0.2.5-h7b6447c_0, https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/noarch/noarch::wheel-0.37.1-pyhd3eb1b0_0
  - defaults/noarch::wheel-0.37.1-pyhd3eb1b0_0, https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/linux-64/linux-64::libstdcxx-ng-11.2.0-h1234567_1, https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/linux-64/linux-64::tqdm-4.64.1-py37h06a4308_0, https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/linux-64/linux-64::yaml-0.2.5-h7b6447c_0
  - defaults/linux-64::libstdcxx-ng-11.2.0-h1234567_1, https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/linux-64/linux-64::tqdm-4.64.1-py37h06a4308_0, https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/linux-64/linux-64::yaml-0.2.5-h7b6447c_0, https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/noarch/noarch::wheel-0.37.1-pyhd3eb1b0_0
  - defaults/linux-64::libstdcxx-ng-11.2.0-h1234567_1, defaults/noarch::wheel-0.37.1-pyhd3eb1b0_0, https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/linux-64/linux-64::tqdm-4.64.1-py37h06a4308_0, https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/linux-64/linux-64::yaml-0.2.5-h7b6447c_0
  - defaults/linux-64::libstdcxx-ng-11.2.0-h1234567_1, defaults/linux-64::tqdm-4.64.1-py37h06a4308_0, https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/linux-64/linux-64::yaml-0.2.5-h7b6447c_0, https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/noarch/noarch::wheel-0.37.1-pyhd3eb1b0_0
  - defaults/linux-64::libstdcxx-ng-11.2.0-h1234567_1, defaults/linux-64::tqdm-4.64.1-py37h06a4308_0, defaults/noarch::wheel-0.37.1-pyhd3eb1b0_0, https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/linux-64/linux-64::yaml-0.2.5-h7b6447c_0
  - defaults/linux-64::tqdm-4.64.1-py37h06a4308_0, https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/linux-64/linux-64::libstdcxx-ng-11.2.0-h1234567_1, https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/linux-64/linux-64::yaml-0.2.5-h7b6447c_0, https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/noarch/noarch::wheel-0.37.1-pyhd3eb1b0_0
  - defaults/linux-64::tqdm-4.64.1-py37h06a4308_0, defaults/noarch::wheel-0.37.1-pyhd3eb1b0_0, https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/linux-64/linux-64::libstdcxx-ng-11.2.0-h1234567_1, https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/linux-64/linux-64::yaml-0.2.5-h7b6447c_0
  - defaults/linux-64::tqdm-4.64.1-py37h06a4308_0, defaults/linux-64::yaml-0.2.5-h7b6447c_0, https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/linux-64/linux-64::libstdcxx-ng-11.2.0-h1234567_1, https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/noarch/noarch::wheel-0.37.1-pyhd3eb1b0_0
  - defaults/linux-64::yaml-0.2.5-h7b6447c_0, https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/linux-64/linux-64::libstdcxx-ng-11.2.0-h1234567_1, https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/linux-64/linux-64::tqdm-4.64.1-py37h06a4308_0, https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/noarch/noarch::wheel-0.37.1-pyhd3eb1b0_0
  ... and othedone


==> WARNING: A newer version of conda exists. <==
  current version: 4.14.0
  latest version: 22.9.0

Please update conda by running

    $ conda update -n base -c https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/linux-64 conda



# All requested packages already installed.

Retrieving notices: ...working... done

**Comment by kamo-naoyuki** [comment]
`setup_anaconda.sh` doesn't create a directory named as `venv` if you didn't give `venv` string to the command

e.g. `setup_anaconda.sh venv espnet 3.8`
