### ISSUE TITLE
I want to run training using multiple GPUs.

### ISSUE THREAD

**Issue by Taruguchi** [espnet/espnet#4788]
Hello.
I want to know how to run training using multiple GPUs.
I refer to the learning of vctk_noisy.
I found the item of "--ngpu" in .yaml file, and default value is 1.
For example, when I want to use 2 GPUs, I have to change this value 1 to 2 only?
If this is wrong, please tell me about correct method.

**Comment by Fhrozen** [comment]
In case you want to use the 2 GPUs you have, set `--ngpu` to 2: `--ngpu 2`.
As you mentioned, the default value 1, is set to use 1 GPU even if you have 2.
For CPU, use `--ngpu 0`

**Comment by Taruguchi** [comment]
@Fhrozen 
Thank you for your comment.
I tried change `--ngpu` value, and as a result:
  set `--ngpu` to 2 : The learning finished successfully, but process took more time than `--ngpu` is 1.
  set `--ngpu` to 4 : The learning did'nt finish successfully.
                            (The process finished, but the model files was'nt made.)
If you have any idea, please tell me.

**Comment by Fhrozen** [comment]
In `vctk_noisy/enh1`, you will find a run.sh file that executes the `enh.sh` file for performing the training and testing. To use multiple GPU, use `./run.sh --ngpu 2` or `./run.sh --ngpu 0`.
Also, remember that the batch size is not automatically increased when you use multiple GPU, so you will need to increase the batch size according to the number of GPUs:

https://github.com/espnet/espnet/blob/cb06bb1a9e5e5355a02d8c1871a8ecfafd54754d/egs2/vctk_noisy/enh1/conf/tuning/train_enh_conv_tasnet.yaml#L5

in case of 4, then use 8 times 4 = 32 as batch size.
Also, the time will not hugely decrease when using multiple GPUs (here a discussion #4377)
