### ISSUE TITLE
mtlalpha experiments

### ISSUE THREAD

**Issue by JaejinCho** [espnet/espnet#480]
I am just curious about setting a proper value for mtlalpha. Recently I compared 0.2 and 0.5 for fisher_callhome_spanish and a model w/ 0.2 performed better than 0.5 as shown in the table (I set ctc_weight for decoding same as 0.3). I thought this is not ignorant difference.

mtlalpha | Fisher_dev | Fisher_test | Callhome_train | Callhome_dev | Callhome_test
-- |-- | -- | -- | -- | --
0.5 | 35 | 30.3 | 54.4 | 55.2 | 56.4
0.2 |33.7 | 29.6 | 53.8 | 54.3 | 55.6

According to what I've look at the current recipes, almost all recipes are having its value as 0.5 other than Chime5 (0.1) and WSJ (0.2).

Is there any thought or intuition from setting this value reasonble thought not the best (something like roughly 0.2 for read speech and 0.5 for conversational speech, etc., or some value for BPE training and the other value for Character-level training)?

**Comment by creatorscan** [comment]
One way to speculate is that CTC behaves better over attention with lesser amount of training data (eg: TIMIT, AN4, Voxforge). So setting mtlalpha=0.5 is fruitful. 
Whereas, for bigger corpus such as: 
WSJ  --- mtlalpha=0.2 was better.
Librespeech --- mtlalpha=0.5 achieves 4.6 over 4.8 (mtlalpha=0.2). I guess with bit more hyper-parameter search this difference can be closed.

**Comment by sw005320** [comment]
I agree with @creatorscan. I just don't tune mtlalpha so much, but I also empirically found that it would be good to set a smaller value for larger corpora.
