### ISSUE TITLE
3card training speed is close to one card

### ISSUE THREAD

**Issue by lzl-mt** [espnet/espnet#4802]
Hey, 
I run the AIshell demo use [https://github.com/espnet/espnet/blob/master/egs2/aishell/asr1/run_streaming.sh](url)
When i use single V100, the first epoch cost:
`2022-12-02 10:16:49,542 (trainer:330) INFO: 1epoch results: [train] iter_time=2.763e-04, forward_time=0.133, loss_ctc=82.949, loss_att=68.302, acc=0.232, loss=72.696, backward_time=0.122, optim_step_time=0.073, optim0_lr0=9.193e-05, train_time=0.429, time=1 hour, 18 minutes and 52.65 seconds, total_count=11029, gpu_max_cached_mem_GB=14.514, [valid] loss_ctc=27.347, cer_ctc=0.440, loss_att=30.635, acc=0.587, cer=0.821, wer=0.984, loss=29.649, time=1 minute and 3.74 seconds, total_count=441, gpu_max_cached_mem_GB=14.514`
While i use 3 V100 to speed up, i got:
`:0/3] 2022-12-02 10:00:49,474 (trainer:330) INFO: 1epoch results: [train] iter_time=1.570e-04, forward_time=0.071, loss_ctc=83.667, loss_att=68.555, acc=0.230, loss=73.089, backward_time=0.096, optim_step_time=0.068, optim0_lr0=9.193e-05, train_time=0.323, time=59 minutes and 24.89 seconds, total_count=11029, gpu_max_cached_mem_GB=9.873, [valid] loss_ctc=27.844, cer_ctc=0.455, loss_att=31.161, acc=0.580, cer=0.695, wer=0.984, loss=30.166, time=1 minute and 3.24 seconds, total_count=441, gpu_max_cached_mem_GB=9.873`
And i found when only use one card, bsz 64 will cost 15G/16G, however, when i use multi GPUs, the GPU memory usage is wired:
<img width="693" alt="image" src="https://user-images.githubusercontent.com/114667476/205274985-770db9a8-2e89-4b55-8ba1-bee79326fa6c.png">
So how can i speed up my training use multi cards, thanks a lot

**Comment by lzl-mt** [comment]
Config：conf/train_asr_streaming_conformer.py

**Comment by sw005320** [comment]
Please check https://espnet.github.io/espnet/espnet2_tutorial.html#relationship-between-mini-batch-size-and-number-of-gpus
You need to increase the batch size accordingly.
