### ISSUE TITLE
Where is preprocessed SpeechBrain X-vector extraction?

### ISSUE THREAD

**Issue by oohara1202** [espnet/espnet#4816]
Hi!

When using SpeechBrain X-vector, I found [egs2/TEMPLATE/asr1/pyscripts/utils/extract_xvectors.py](https://github.com/espnet/espnet/blob/af70425293e6c15fb56f83cced78afe17878b757/egs2/TEMPLATE/asr1/pyscripts/utils/extract_xvectors.py#L68-L111) is running.
Also, accoding to SpeechBrain docs, we have to  make sure the sample rate of wavforms to extract X-vector is 16kHz.

In tts recipe, which code is resampling waveforms to 16kHz?

**Comment by kan-bayashi** [comment]
https://github.com/speechbrain/speechbrain/blob/d7ce2225af33dbf42278e1edfe2c4832d67588a1/speechbrain/dataio/preprocess.py#L7-L44
AudioNormalizer do it.
