### ISSUE TITLE
How to infer single wav file?

### ISSUE THREAD

**Issue by muntasir2000** [espnet/espnet#482]
How can I get the transcription of a single wav file? Is there any other way to run `asr_recog.py` for a single wav file? I have looked into kaldi tools used to extract filterbank and pitch features like `make_fbank_pitch.sh `. They all seems to take a directory as input, not a single file. Any thought?

**Comment by sw005320** [comment]
This recognition script is designed for off-line experiments, which is good enough for research purpose or off-line decoding purpose, but not for on-line decoding purpose or recognizing a single WAV file.

**Comment by gtache** [comment]
What I've used to do that is [create_corpus](https://github.com/kaldi-asr/kaldi/blob/master/egs/apiai_decode/s5/local/create-corpus.sh) with a single file, and then make_fbank, dump, data2json, etc. like in any run.sh    
Obviously it's way too slow for online decoding but if you just want to decode some files it's good enough.

**Comment by tsauri** [comment]
espnet is based off kaldi. Kaldi is quite notorious to be put on production/deployment (bash scripts, python, c++, perl eveywhere)
until we can fully detach kaldi off espnet, deployment remains hard.

**Comment by sw005320** [comment]
Check #581
