### ISSUE TITLE
Improvements, additions, fixes

### ISSUE THREAD

**Issue by gtache** [espnet/espnet#483]
Hi, thanks for the framework, it does a good job given how small and easy to use it is, which also allows to easily modify it !     
I'm using it for a project and had to make quick modifications, but now that I have more time I'd want to merge them to allow everyone else to benefit from them. It may take some time to rewrite them (I want to do it in a cleaner way) but here are some things I've already implemented in my version:    
- Additions
- - [x] GRU/LSTM choice #496
- - [ ] Encoder customization #551 
- - [x] Sortagrad #550 
- - [ ] ColdFusion #566 
- - [ ] Dynamic batchsize #580
- - [ ] Incremental scheduled sampling #576 
- Fixes
- - [x] Fix for deterministic behavior #497 
- - [x] Typos #484
- Improvements
- - [x] Consistent documentation #484
- - [x] Code modularization #484
- - [ ] Various other optimizations    
- QoL
- - [x] Tensorboard logging #506 
- - [x] EarlyStop trigger #508 
- - [x] Stop stage for run.sh #539 

You can tell if you want to put priority on some or want to remove others.

Note that some of these modifications are only on pytorch for now but if it isn't too complicated I may implement them on chainer too (I have no experience with chainer though).

The first PR #484 is just for typos, docs and modularization (no functionality change)

**Comment by sw005320** [comment]
Thanks!
All of them look very interesting. Yes, let's try to incorporate it one-by-one.
I'm also curious how these additions will improve the performance, e.g., Sortagrad and Dynamic batchsize.
