### ISSUE TITLE
stage5 failed

### ISSUE THREAD

**Issue by huaiche** [espnet/espnet#4842]
bash: line 1: 25413 Killed                  ( python3 -m espnet2.bin.tts_train --collect_stats true --write_collected_feats true --use_preprocessor true --token_type phn --token_list dump/token_list/phn_g2p_en_no_space/tokens.txt --non_linguistic_symbols none --cleaner none --g2p g2p_en_no_space --normalize none --pitch_normalize none --energy_normalize none --train_data_path_and_name_and_type dump/raw/hz_test_train/text,text,text --train_data_path_and_name_and_type dump/raw/hz_test_train/wav.scp,speech,sound --valid_data_path_and_name_and_type dump/raw/hz_test_dev/text,text,text --valid_data_path_and_name_and_type dump/raw/hz_test_dev/wav.scp,speech,sound --train_shape_file exp/tts_hz_test/decode_use_teacher_forcingtrue_train.loss.ave/stats/logdir/train.3.scp --valid_shape_file exp/tts_hz_test/decode_use_teacher_forcingtrue_train.loss.ave/stats/logdir/valid.3.scp --output_dir exp/tts_hz_test/decode_use_teacher_forcingtrue_train.loss.ave/stats/logdir/stats.3 --config conf/tuning/train_conformer_fastspeech2_lanemb.yaml --feats_extract fbank --feats_extract_conf n_fft=2048 --feats_extract_conf hop_length=300 --feats_extract_conf win_length=1200 --feats_extract_conf fs=22050 --feats_extract_conf fmin=80 --feats_extract_conf fmax=7600 --feats_extract_conf n_mels=80 --pitch_extract_conf fs=22050 --pitch_extract_conf n_fft=2048 --pitch_extract_conf hop_length=300 --pitch_extract_conf f0max=400 --pitch_extract_conf f0min=80 --energy_extract_conf fs=22050 --energy_extract_conf n_fft=2048 --energy_extract_conf hop_length=300 --energy_extract_conf win_length=1200 --train_data_path_and_name_and_type exp/tts_hz_test/decode_use_teacher_forcingtrue_train.loss.ave/hz_test_train/durations,durations,text_int --valid_data_path_and_name_and_type exp/tts_hz_test/decode_use_teacher_forcingtrue_train.loss.ave/hz_test_dev/durations,durations,text_int --train_data_path_and_name_and_type dump/raw/hz_test_train/utt2lid,lids,text_int --valid_data_path_and_name_and_type dump/raw/hz_test_dev/utt2lid,lids,text_int ) 2>> exp/tts_hz_test/decode_use_teacher_forcingtrue_train.loss.ave/stats/logdir/stats.3.log >> exp/tts_hz_test/decode_use_teacher_forcingtrue_train.loss.ave/stats/logdir/stats.3.log

Did someone have this problem?

**Comment by sw005320** [comment]
There would be some more error messages in `exp/tts_hz_test/decode_use_teacher_forcingtrue_train.loss.ave/stats/logdir/stats.3.log`
Please check them.

**Comment by huaiche** [comment]
File "/home/mit/espnet/tools/anaconda/envs/espnet/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1133, in _try_get_data
    raise RuntimeError('DataLoader worker (pid(s) {}) exited unexpectedly'.format(pids_str)) from e
RuntimeError: DataLoader worker (pid(s) 26933) exited unexpectedly

It shows in exp/tts_hz_test/decode_use_teacher_forcingtrue_train.loss.ave/stats/logdir/stats.3.log

**Comment by sw005320** [comment]
Is it reproducible?
I feel that this issue happens due to some file server, job scheduler, or other system-level issues in your setup.

**Comment by kan-bayashi** [comment]
Maybe reducing nj solves the problem.
Your job seems to be killed due to cpu OOM.

**Comment by saiakarsh193** [comment]
reducing nj solved the issue in my case.
