### ISSUE TITLE
Why batch-beam search is different from non batch-beam search

### ISSUE THREAD

**Issue by ShigekiKarita** [espnet/espnet#488]
@mn5k @takaaki-hori @sw005320 
First, I apologize my late catchup (not reviewed). Because I am trying to refactor the beam search implementation for various models like transformer now, I want to understand this change between them.

## prunning (topk)

non-batch implementation does prunning (topk) before ctc and lm scoring
https://github.com/espnet/espnet/blob/60682e8823d8fb44bf54ef157ddf7ae2c8797fc0/espnet/nets/e2e_asr_th.py#L2205-L2218

batch implementation does prunning after ctc and lm scoring
https://github.com/espnet/espnet/blob/60682e8823d8fb44bf54ef157ddf7ae2c8797fc0/espnet/nets/e2e_asr_th.py#L2373-L2391

Isn't this make difference?

(EDIT: several questions I deleted here was solved by myself)

**Comment by mn5k** [comment]
Sorry for the late reply.
Yes, it causes the difference of recognition performance.

I compared the batch-beam search with the non-batch one in some tasks,
and the batch-beam search obtained the same (and sometimes better) performance as the non-batch beam search though it is just heuristic.

**Comment by ShigekiKarita** [comment]
OK, maybe I will also investigate it in next implementation. Thanks!
