### ISSUE TITLE
Whisper breaks the CI

### ISSUE THREAD

**Issue by sw005320** [espnet/espnet#4886]
@slSeanWU, it seems that whisper breaks the CI
https://github.com/espnet/espnet/actions/runs/4005928925/jobs/6876869037#step:7:864

Not sure if this is due to their temporal bug (if so, we may wait for their bug fix and use the older version) or some interface changes (if so, can you fix it?).
Could you check this?

**Comment by sw005320** [comment]
We seem to need the latest python to pass it.
I'll figure it out.

**Comment by sw005320** [comment]
@slSeanWU, I was trying to fix it, but there are several whisper test codes, and it is not easy to check everything by myself.
Could you do it for me?
We could use the following to skip the test (we should only use python 3.8+) (thanks @Emrys365 and @nateanl)
```
is_python_3_8_plus = sys.version_info[0] >= (3, 8)

@pytest.mark.skipif(is_python_3_8_plus)
```

**Comment by nateanl** [comment]
sorry I made a bug in the skip code, this should work
```python
is_python_3_8_plus  = sys.version_info >= (3, 8)
```
