### ISSUE TITLE
Discussion to refactor beam search

### ISSUE THREAD

**Issue by ShigekiKarita** [espnet/espnet#489]
Recently, we have several issues like #429, #436, #470 etc and improvements like #318, #478 etc related to beam search. As far as I know, every PRs related to beam search (except for the wide refactoring #484) has been merged at this time. Maybe it is good time to refactor current complex and adhoc implentations to be simpler and generalized for v0.3.0.

These are my thoughts on the problems in current beam search
- Beam search should not be inside the Decoder class because it requires to reimplement beam search in very different model like Transformer.
- Beam search should not hard code initialization and state updates of scoring models (decoder, CTC, LM, etc)
- Hard to read many lines. Some lines should be function or class.
- Hard to add new scoring models (e.g., #429)

I propose two changes
- Define explicit interface class for scoring model (Decoder, CTC, LM, etc) that can be used in beam search
- Beam search class only call `.init_state`, `.score` and `.select_state` method of the scoring models.

This is just my draft what the new BeamSearch class looks like
```python
# interface for Decoder, CTC, RNNLM, etc
class ScoringBase(object):
    def score(self, token, enc_output, state):
        """return log_prob, new_state"""
        pass

    def init_state(self, src, src_lengths, enc_output, args):
        """return batch/beam state object"""
        pass

    def select_state(self, state, index):
        """return batch/beam state object selected on the index"""
        pass


class BeamSearch(object):
    def __init__(self, encoder, scorers, weight_dict, sos, eos):
        ...

    def init_state(self, n_batch, n_beam, device):
        ...

    def prune(self, global_best_score, local_best_score, eos_mask):
        ...

    def update_tokens(self, global_best_token_id, global_best_tokens, eos_mask):
        ...

    def recognize(self, src, src_length, args, device):
        # forward encoder
        enc_output = self.encoder(src, src_lengths)

        # prepare states
        states = dict():
        for s in self.scorers:
            states[s] = s.init_state(src, src_lengths, enc_output, args)

        n_batch = len(src_length)
        n_beam = args.beam_size
        global_best_token_seq = [[[] for _ in range(n_beam)] for _ in range(n_batch)]
        global_best_token, global_best_score, eos_mask = self.init_state(n_batch, n_beam, device)

        # prefix search
        for step in range(args.maxlen_decode):
            # forward scorers
            local_score = 0
            new_scores = dict()
            new_states = dict()
            for s in self.scorers:
                new_scores[s], new_states[s] = s.score(
                    global_best_token,
                    enc_output,
                    states[s])
                # (n_batch, n_beam, n_token)
                local_score += self.weight_dict[s] * new_scores[s]

            # prune hypotheses
            global_best_score, global_best_hyp_id, global_best_token \
                = self.prune(global_best_score, local_best_score, eos_mask)

            # update results
            self.update_tokens(global_best_token, global_best_token_seq, eos_mask)
            for s in self.scorers:
                states[s] = s.select_state(new_states[s], global_best_hyp_id)

            # end detection
            eos_mask |= batch_end_detect(global_best_score, global_best_token_seq)
            if all(eos_mask):
                break  # no hypotheses remained

        return global_best_tokens, global_best_score
```
You can find more detailed implementation in my head [here](https://gist.github.com/ShigekiKarita/f06d093a7f868eef38dfbc03c6f93b78)
Anyway, this is incomplete idea. I want to discuss this topic for new development plan.

**Comment by sw005320** [comment]
I like this idea. I have to admit that my initial beam search was not well implemented to consider such flexibilities. Your idea of `BeamSearch` class and providing the scoring interface is more flexible. Since this would affect a lot of people, I newly created the v.0.3.0 branch. I fully agree with your implementation, and I ask you to work on this branch.

**Comment by sw005320** [comment]
@kan-bayashi, do you think this way will be applied to the TTS inference?

**Comment by kan-bayashi** [comment]
In the case of TTS, we do not perform beam search (Just perform a kind of one-best decoding), because TTS model has only score of eos.

**Comment by ShigekiKarita** [comment]
I'm working on prototype on transformer. https://github.com/ShigekiKarita/espnet/blob/pytorch-transformer/espnet/nets/beam_search.py

I think it is possible to share the almost all part of `BeamSearch` between chainer and pytorch if `prune` and `init_state` functions are implemented separately.

**Comment by kobenaxie** [comment]
what's the difference of beam search between E2E model and Transformer ? I realize your new beam-search in transformer .
