### ISSUE TITLE
Question on FastSpeech 2 Training and Decoding

### ISSUE THREAD

**Issue by timljj** [espnet/espnet#4921]
![image](https://user-images.githubusercontent.com/39835563/217176401-1742eb00-626a-4171-bb3b-1a6c23e04b14.png)

Hi, I noticed that for FastSpeech2 "Training", the command given after the teacher forcing decoding runs from stage 5 onwards. This means that in addition to TTS Stage 6 (TTS Training), TTS Stage 7 (TTS Decoding) is run as well. 

Is this expected or is there a different command for FastSpeech2 TTS Stage 7 ?

**Comment by kan-bayashi** [comment]
The first command for the preparation of `durations` files, which is needed for training of fastspeech2.
And then, the second command performs the training and decoding of fastspeech2.

**Comment by baixf-xyz** [comment]
I want to know the first command why is MUST to use teacher forcing in decoding? Thanks
