### ISSUE TITLE
synthesize problem(GSTs)

### ISSUE THREAD

**Issue by huaiche** [espnet/espnet#4939]
I trained the TTS model, Fastspeech2 + GST
when I synthesize the model,what parameter should i give in "speech"

**Comment by Fhrozen** [comment]
The parameter should be a torch tensor 1-ch audio,  in a size of [1 x Length] or [Batch x Length] 
https://github.com/espnet/espnet/blob/ff841366229d539eb74d23ac999cae7c0cc62cad/espnet2/tts/fastspeech2/fastspeech2.py#L711
