### ISSUE TITLE
importlib.import_module in test codes

### ISSUE THREAD

**Issue by kamo-naoyuki** [espnet/espnet#494]
The test codes in espnet often use dynamically importing  by ``importlib.import_module``, why?
I believe `importlib.import_module`` should not be used as possible. It is unreadable and easy to make some bugs because static code analysis can't work.

**Comment by sw005320** [comment]
I'm actually not sure about this. @kan-bayashi, do you have any comments? If this is true, we can avoid to use this.

**Comment by kan-bayashi** [comment]
I followed the Shigeki’s manner to implement test codes.
So @ShigekiKarita may have some comments.

**Comment by ShigekiKarita** [comment]
As pytorch backend starts as optional, it did not import torch directly. However, we should not care now.
