### ISSUE TITLE
Original data training in a speech separation task 

### ISSUE THREAD

**Issue by linhnd34tt** [espnet/espnet#4951]
Thank you very much for all your help and support.
I want to train with original data in a speech seperation task, but the samples in the egs2 folder use a specific dataset (WHAM!, WSJ1, etc.).

How can I create utt2spk and wav.scp for 2 speakers mixed like WSJ mixed dataset?
wav.scp      (input mixed signal)
spk1.scp     (corresponding clean signals of speaker 1)
spk2.scp     (corresponding clean signals of speaker 2)
utt2spk       (mapping from utt ids to speaker ids) -> Can a utterance map to 2 speakers id? since it may not create a one on one spk2utt
spk2utt      (generated by running `utils/utt2spk_to_spk2utt.pl /path/to/utt2spk > /path/to/spk2utt`)

It would be very great help if there are examples of utt2spk and wav.scp

**Comment by Emrys365** [comment]
Hi @linhnd34tt, below are examples of the required data files for one subset:

```
==> data/train/wav.scp <==
011_012_011c0213_0.85538_012o030a_-0.85538_011c020z /path/to/mix/011c0213_0.85538_012o030a_-0.85538.wav
011_012_011c0213_0.85538_012o030a_-0.85538_012c020n /path/to/mix/011c0213_0.85538_012o030a_-0.85538.wav
011_013_011a010q_1.159_013a0102_-1.159_011o0307 /path/to/mix/011a010q_1.159_013a0102_-1.159.wav

==> data/train/spk1.scp <==
011_012_011c0213_0.85538_012o030a_-0.85538_011c020z /path/to/s1/011c0213_0.85538_012o030a_-0.85538.wav
011_012_011c0213_0.85538_012o030a_-0.85538_012c020n /path/to/s1/011c0213_0.85538_012o030a_-0.85538.wav
011_013_011a010q_1.159_013a0102_-1.159_011o0307 /path/to/s1/011a010q_1.159_013a0102_-1.159.wav

==> data/train/spk2.scp <==
011_012_011c0213_0.85538_012o030a_-0.85538_011c020z /path/to/s2/011c0213_0.85538_012o030a_-0.85538.wav
011_012_011c0213_0.85538_012o030a_-0.85538_012c020n /path/to/s2/011c0213_0.85538_012o030a_-0.85538.wav
011_013_011a010q_1.159_013a0102_-1.159_011o0307 /path/to/s2/011a010q_1.159_013a0102_-1.159.wav

==> data/train/utt2spk <==
011_012_011c0213_0.85538_012o030a_-0.85538_011c020z 011_012
011_012_011c0213_0.85538_012o030a_-0.85538_012c020n 011_012
011_013_011a010q_1.159_013a0102_-1.159_011o0307 011_013
```

All files above follow the [Kaldi style](https://kaldi-asr.org/doc/data_prep.html), with two columns (separated by space) in each row.

* The first column is the utterance ID of each sample.
* The second column has different meanings depending on the file name:
  * `wav.scp`: Path to the audio file of the speech mixture sample
  * `spk1.scp`: Path to the audio file of the corresponding clean speech of speaker 1
  * `spk2.scp`: Path to the audio file of the corresponding clean speech of speaker 2
  * `utt2spk`: speaker ID of the mixture sample
    > You cannot map an utterance to 2 speaker IDs in `utt2spk`. This file is actually only used in the data preparation stage and not used in training or inference stages. (Same for `spk2utt`)
    >
    > If you do not know the speaker identity in all mixture samples, the simplest way is to use the utterance ID as the sample ID, such as
    > ```
    > ==> data/train/utt2spk <==
    > 011_012_011c0213_0.85538_012o030a_-0.85538_011c020z 011_012_011c0213_0.85538_012o030a_-0.85538_011c020z
    > 011_012_011c0213_0.85538_012o030a_-0.85538_012c020n 011_012_011c0213_0.85538_012o030a_-0.85538_012c020n
    > 011_013_011a010q_1.159_013a0102_-1.159_011o0307 011_013_011a010q_1.159_013a0102_-1.159_011o0307
    > ```

**Comment by linhnd34tt** [comment]
Thank you so much for fast and detailed response.
As I understand that speaker ID (e.g 011_012_011c0213_0.85538_012o030a_-0.85538_011c020z) will be used as a key to determined to mixture version, the original speaker 1 and speaker 2 version.
For utt2spk, speaker ID is just a reference that may not actually be used in the training process. it just a reference like 011_012 means mixture version of person id 011 and another person id 012, is it correct?

**Comment by Emrys365** [comment]
For WSJ0-2mix, yes. But it is not necessary for your customized datasets to follow the same convention. You could simply use any unique utterance IDs for different samples.

**Comment by linhnd34tt** [comment]
Thank you I was able to follow, I will close the issue
