### ISSUE TITLE
decoding using Fastspeech2 + conformer + HiFi vocoder jointly trained and use_teacher_forcing parameter

### ISSUE THREAD

**Issue by BassamMattar** [espnet/espnet#4957]
to test whether changing the decoding option "use_teacher_forcing" will affect the quality or not, I run the decoding stage with "use_teacher_forcing" set to false, and the output wasn't affected that much therefore I think it is a good idea to change this line of readme file in TTS template folder 
"The procedure is almost the same as FastSpeech but we **MUST** use teacher forcing in decoding."
to be 
"The procedure is almost the same as FastSpeech but we **had better** to use teacher forcing in decoding."
I might miss something but it is not clear to me why it is a **MUST**?
### Discussed in https://github.com/espnet/espnet/discussions/4948
<div type='discussions-op-text'>

<sup>Originally posted by **BassamMattar** February 20, 2023</sup>
I want to run the decoding stage in TTS using Fastspeech2 + conformer + HiFi-GAN vocoder.
I ran it with the "use_teacher_forcing"  parameter set to true
I found an error in inference:
TypeError: inference() got an unexpected keyword argument 'speech'
by tracing the code I found that the speech keyword is generated when use_teacher_forcing is set to true
so I set it to false and the decoding stage was completed successfully.
I wondered what is the functionality of use_teacher_forcing and how it affects the decoding ? as it is mentioned in the Readme of TTS task "The procedure is almost the same as FastSpeech but we **MUST** use teacher forcing in decoding."</div>

**Comment by kan-bayashi** [comment]
The use of teacher forcing is for preparation of `durations`, which is calculated from attention weights of AR models.
Fastspeech2 uses groundtruth of acoustics features so the length durations must be the same as them.
Therefore, we need to use teacher forcing when preparing durations files.
For decoding of fastspeech2, teacher forcing is not needed (Please check docs carefully).

**Comment by BassamMattar** [comment]
> The use of teacher forcing is for preparation of `durations`, which is calculated from attention weights of AR models.
> Fastspeech2 uses groundtruth of acoustics features so the length durations must be the same as them.
> Therefore, we need to use teacher forcing when preparing durations files.
> For decoding of fastspeech2, teacher forcing is not needed (Please check docs carefully).

Thank you for replying 😃
I realized that I misunderstood the word "decoding". I thought it is referring to the "decoding stage" not the decoding during training. Is that right interpretation or I missed something?

**Comment by kan-bayashi** [comment]
FS2 training consists of two-stage: 1st one is AR model training & duration generation and 2nd one is FS2 training.
`teacher_forcing` is needed for the decoding stage of 1st one.

**Comment by BassamMattar** [comment]
things become more clear now. thank you
