### ISSUE TITLE
RTF calculation in Espnet2

### ISSUE THREAD

**Issue by Zth9730** [espnet/espnet#4968]
Hello, I have used espnet2 for my experiments in ASR, is there a tool in espnet for RTF calculation? Thank you very much!

**Comment by sw005320** [comment]
We have the following tool
https://github.com/espnet/espnet/blob/master/utils/calculate_rtf.py

In the ASR recipe, we can use this to calculate the RTF for the test sets.
https://github.com/espnet/espnet/blob/master/egs2/TEMPLATE/asr1/asr.sh#L1404-L1417
