### ISSUE TITLE
[BUG]there are incompatible upgrade in parratio==6.0.0

### ISSUE THREAD

**Issue by yt605155624** [espnet/espnet#4973]
please check https://github.com/timmahrt/praatIO/issues/54

**Comment by timmahrt** [comment]
@yt605155624 Hello, I've created a PR that should fix the issue.

I'm not able to test the PR so I'm not familiar with espnet. Can you test it?

Alternatively you should be able to resolve the issue with:
```
pip uninstall praatio
pip install praatio==5.1.1
```

**Comment by yt605155624** [comment]
I'm not the maintainer neither， PaddleSpeech's users report this bug to me，and I have noticed this to espnet and  MFA，I thought the maintainer will review  your PR soon @kan-bayashi
