### ISSUE TITLE
Running JETS

### ISSUE THREAD

**Issue by gafsd** [espnet/espnet#4980]
What arguments should I use for JETS? I'm using this:
```
--n_fft 1024 \
--n_shift 256 \
--win_length null \
--tts_task gan_tts \
```
But I get this: 
```
RuntimeError: The expanded size of the tensor (64) must match the existing size (0) at non-singleton dimension 1.  Target sizes: [256, 64].  Tensor sizes: [256, 0]
```

**Comment by kan-bayashi** [comment]
Could you share the entire command and log?

```bash
# example command for single speaker jets
./run.sh \
    --ngpu 4 \
    --fs 22050 \
    --n_fft 1024 \
    --n_shift 256 \
    --win_length null \
    --tts_task gan_tts \
    --write_collected_feats true \
    --nj 16 \
    --train_config conf/tuning/train_jets.yaml
```

**Comment by gafsd** [comment]
./run.sh --stage 6 --nj 12 --fs 22050 \
--min_wav_duration 0.38 \
--n_fft 1024 \
--n_shift 256 \
--win_length null \
--tts_task gan_tts \
--train_config ./conf/tuning/train_jets.yaml \
--inference_config ./conf/tuning/decode_fastspeech.yaml \
--train_config conf/tuning/train_jets.yaml \
--train_args "--init_param pretrain/jets/*.pth"

**Comment by gafsd** [comment]
[log.txt](https://github.com/espnet/espnet/files/10887330/log.txt)

**Comment by kan-bayashi** [comment]
This is min wav duration issue.
default segment size is x2 of other models.
Please increase min_wav_duration or decrease segment size.
