### ISSUE TITLE
vits change noise_scale param have no effect when inference

### ISSUE THREAD

**Issue by dolphin17** [espnet/espnet#4987]
```
tts = Text2Speech.from_pretrained(
    model_file="kan-bayashi/ljspeech_conformer_fastspeech2",
    vocoder_tag=str_or_none("none"),
    device="cpu",
    # Only for Tacotron 2 & Transformer
    threshold=0.5,
    # Only for Tacotron 2
    minlenratio=0.0,
    maxlenratio=10.0,
    use_att_constraint=False,
    backward_window=1,
    forward_window=3,
    # Only for FastSpeech & FastSpeech2 & VITS
    speed_control_alpha=1.0,
    # Only for VITS
    noise_scale=0.666,
    noise_scale_dur=0.777,
)
```
when I change noise_scale to 1.0 or 0.1.the synthesized voice does not change.How to use noise_scale and noise_scale_dur?

**Comment by kan-bayashi** [comment]
> model_file="kan-bayashi/ljspeech_conformer_fastspeech2",

You used FS2, not VITS.

**Comment by dolphin17** [comment]
sorry.I copied it wrong.This is the code I use
`
tts = Text2Speech.from_pretrained(
    model_tag="kan-bayashi/ljspeech_vits",
    vocoder_tag=str_or_none("none"),
    device="cpu",
    # Only for Tacotron 2 & Transformer
    threshold=0.5,
    # Only for Tacotron 2
    minlenratio=0.0,
    maxlenratio=10.0,
    use_att_constraint=False,
    backward_window=1,
    forward_window=3,
    # Only for FastSpeech & FastSpeech2 & VITS
    speed_control_alpha=1.0,
    # Only for VITS
    noise_scale=0.666,
    noise_scale_dur=0.777,
)
wav = tts("what's your name")["wav"]
`

**Comment by kan-bayashi** [comment]
https://github.com/espnet/espnet/blob/89ebca463c544dfaa19e5f76ad5f615f473f6957/espnet2/bin/tts_inference.py#L156
You can use `decode_conf` in call:
```python
wav = tts("what's your name", decode_conf=dict(noise_scale=0.333))["wav"]
```

**Comment by dolphin17** [comment]
Thanks.And other question.Does it support the same voice line to speak different languages?such as ja, korean, etc.If I want to do this, what do I need to do？
