### ISSUE TITLE
CPU decoding uses a lot of threads

### ISSUE THREAD

**Issue by kan-bayashi** [espnet/espnet#5]
Decoding process uses a lot of threads.
If we use the default recipe, load average becomes very big number.

![img076](https://user-images.githubusercontent.com/22779813/33977523-9aa85da2-e0de-11e7-99a6-87cf851386d5.jpg)

Why don't you add the regularization for the use of cpus when decoding?

**Comment by sw005320** [comment]
I did not have this issue.
Try to use one of the followings (put it in path.sh)

export MKL_NUM_THREADS=1
export NUMEXPR_NUM_THREADS=1
export OMP_NUM_THREADS=1

This happens when you use some blas libraries, although it would be better to put this inside the code.

**Comment by kan-bayashi** [comment]
Thank you for quick response!
The problem is fixed!

I'll add these lines into path.sh.
