### ISSUE TITLE
.  utils/parse_options.sh: Not a directory

### ISSUE THREAD

**Issue by xuhan1202** [espnet/espnet#500]
I haved installed the toolkit successfully, but  when I try to run the run.sh file in egs. It comes to error like this.

**Comment by sw005320** [comment]
Probably you did not set the Kaldi path correctly. Could you check it?

**Comment by xuhan1202** [comment]
I have solved the problem, thank you.

**Comment by Ruhewang** [comment]
i just met the same problem. Could you tell me how you fixed it? thank you

**Comment by Ruhewang** [comment]
Do i need to install Kaldi toolkit separately, then set to path to Kaldi?

**Comment by sw005320** [comment]
If you simply follow one of the installation instructions in https://github.com/espnet/espnet, you'll fix the issue.

**Comment by Ruhewang** [comment]
thank you, the problem fixed. i found the cause is that an4/ars1/utils file vanishes accidentally. I just redo the installation then everything goes fine.
