### ISSUE TITLE
Impact of batch size on librispeech

### ISSUE THREAD

**Issue by Magic-Bubble** [espnet/espnet#503]
I was trying to increase batch size on Librispeech, but I got a drop performance on WER. When I use batch size of 24 in default config, I got exactly the same WER as the reported result (4.1%). But when I increase batch size to 40 (without modify any other hyper parameters), I got 4.7%.

I don't know why just add batch size causes this significant drop on WER. Maybe I need to modify some other hyper parameters to adapt to this batch size? 

Seek for your kindly help, thank you!

**Comment by ZhuoranLyu** [comment]
> I was trying to increase batch size on Librispeech, but I got a drop performance on WER. When I use batch size of 24 in default config, I got exactly the same WER as the reported result (4.1%). But when I increase batch size to 40 (without modify any other hyper parameters), I got 4.7%.
> 
> I don't know why just add batch size causes this significant drop on WER. Maybe I need to modify some other hyper parameters to adapt to this batch size?
> 
> Seek for your kindly help, thank you!

@Magic-Bubble Same situation, may be because of padding for different lengths in a batch.

**Comment by kobenaxie** [comment]
@Magic-Bubble @ZhuoranLyu what is label in you experiment, english chars or words ?

**Comment by Magic-Bubble** [comment]
@kobenaxie using the default config, 5000 unigrams

**Comment by ZhuoranLyu** [comment]
default config. @kobenaxie

**Comment by Magic-Bubble** [comment]
> Same situation, may be because of padding for different lengths in a batch.

The padding will be masked in an batch, maybe it is not the key point for this issue. @ZhuoranLyu

**Comment by gtache** [comment]
I'm not sure if that's the case here, but it could be simply due to the fact that [having a bigger batch size means in general poorer results](https://stats.stackexchange.com/questions/164876/tradeoff-batch-size-vs-number-of-iterations-to-train-a-neural-network).

**Comment by Magic-Bubble** [comment]
>           I have some similar experience with fixed optimizer configurations, and I saw the other people's report on the attention based ASR.

I changed the optimizer from Adadelta to Adam, but the convergence seems too slowly! Have you got some other ideas from other people's report?
