### ISSUE TITLE
New version of "typeguard" causes ImportError: cannot import name 'check_argument_types' from 'typeguard'

### ISSUE THREAD

**Issue by MosaabMuhammed** [espnet/espnet#5033]
## Error Description
`typeguard version 3.0.1` is now incompatible with Espnet, and it shows the following error when using `Text2Speech` class:
```
ImportError: cannot import name 'check_argument_types' from 'typeguard'
```

## Temporary Solution:
downgrade `typeguard` to `2.13.3` using:
```bash
pip install typeguard==2.13.3
```

## Permanent Solution:
Downgrade `typeguard` in the setup.py file from `"typeguard>=2.7.0"` to `"typeguard==2.13.3"`.

**Comment by kamo-naoyuki** [comment]
Thanks, we already fixed it. #5009
