### ISSUE TITLE
AttributeError: 'Namespace' object has no attribute 'use_ddp' in ars.py train

### ISSUE THREAD

**Issue by mera-mike** [espnet/espnet#5037]
hi guyz i am having trouble training using the voxforge recipes under espnet/egs/voxforge during stage 3 neural network training it says

run.pl: job failed, log is in exp/tr_it_pytorch_train/train.log
and in the log it is

AttributeError: 'Namespace' object has no attribute 'use_ddp'

can anyone help

**Comment by kamo-naoyuki** [comment]
Could you show all traceback?

**Comment by mera-mike** [comment]
thanks for replying soon kamo

error log looks like

# asr_train.py --config conf/train.yaml --preprocess-conf conf/no_preprocess.yaml --ngpu 0 --backend pytorch --outdir exp/tr_it_pytorch_train/results --tensorboard-dir tensorboard/tr_it_pytorch_train --debugmode 1 --dict data/lang_1char/tr_it_units.txt --debugdir exp/tr_it_pytorch_train --minibatches 0 --verbose 0 --resume --train-json dump/tr_it/deltafalse/data.json --valid-json dump/dt_it/deltafalse/data.json 
# Started at Mon Mar 20 10:12:30 EAT 2023
#
Skip DEBUG/INFO messages
/home/mera/espnet/egs/vcc4/asr1/../../../espnet/bin/asr_train.py:25: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  is_torch_1_2_plus = LooseVersion(torch.__version__) >= LooseVersion("1.2")
Traceback (most recent call last):
  File "/home/mera/espnet/egs/vcc4/asr1/../../../espnet/bin/asr_train.py", line 641, in <module>
    main(sys.argv[1:])
  File "/home/mera/espnet/egs/vcc4/asr1/../../../espnet/bin/asr_train.py", line 627, in main
    train(args)
  File "/home/mera/anaconda3/envs/espnets/lib/python3.8/site-packages/espnet/asr/pytorch_backend/asr.py", line 465, in train
    if args.use_ddp:
AttributeError: 'Namespace' object has no attribute 'use_ddp'
# Accounting: time=0 threads=1
# Ended (code 1) at Mon Mar 20 10:12:30 EAT 2023, elapsed time 0 seconds

./run went good until stage 3

**Comment by kamo-naoyuki** [comment]
I guess a version mismatch exists.

>  /home/mera/espnet/egs/vcc4/asr1/../../../espnet/bin/asr_train.py

> /home/mera/anaconda3/envs/espnets/lib/python3.8/site-packages/espnet/asr/pytorch_backend/asr.py

You mistakenly have two espnet.

**Comment by mera-mike** [comment]
how am i supposed supposed to undo the mistake then

**Comment by mera-mike** [comment]
which espnet should i use then 
/home/mera/espnet/egs/vcc4/asr1/../../../espnet/bin/asr_train.py
or

/home/mera/anaconda3/envs/espnets/lib/python3.8/site-packages/espnet/asr/pytorch_backend/asr.py

**Comment by mera-mike** [comment]
i succesfully removed espnet but still

# asr_train.py --config conf/train.yaml --preprocess-conf conf/no_preprocess.yaml --ngpu 0 --backend pytorch --outdir exp/tr_it_pytorch_train/results --tensorboard-dir tensorboard/tr_it_pytorch_train --debugmode 1 --dict data/lang_1char/tr_it_units.txt --debugdir exp/tr_it_pytorch_train --minibatches 0 --verbose 0 --resume --train-json dump/tr_it/deltafalse/data.json --valid-json dump/dt_it/deltafalse/data.json 
# Started at Mon Mar 20 10:12:30 EAT 2023
#
Skip DEBUG/INFO messages
/home/mera/espnet/egs/vcc4/asr1/../../../espnet/bin/asr_train.py:25: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  is_torch_1_2_plus = LooseVersion(torch.__version__) >= LooseVersion("1.2")
Traceback (most recent call last):
  File "/home/mera/espnet/egs/vcc4/asr1/../../../espnet/bin/asr_train.py", line 641, in <module>
    main(sys.argv[1:])
  File "/home/mera/espnet/egs/vcc4/asr1/../../../espnet/bin/asr_train.py", line 627, in main
    train(args)
  File "/home/mera/anaconda3/envs/espnets/lib/python3.8/site-packages/espnet/asr/pytorch_backend/asr.py", line 465, in train
    if args.use_ddp:
AttributeError: 'Namespace' object has no attribute 'use_ddp'
# Accounting: time=0 threads=1
# Ended (code 1) at Mon Mar 20 10:12:30 EAT 2023, elapsed time 0 seconds

**Comment by kamo-naoyuki** [comment]
You still have /home/mera/anaconda3/envs/espnets/lib/python3.8/site-packages/espnet/asr/pytorch_backend/asr.py

**Comment by mera-mike** [comment]
still error in

# asr_train.py --config conf/train.yaml --preprocess-conf conf/no_preprocess.yaml --ngpu 0 --backend pytorch --outdir exp/tr_it_pytorch_train/results --tensorboard-dir tensorboard/tr_it_pytorch_train --debugmode 1 --dict data/lang_1char/tr_it_units.txt --debugdir exp/tr_it_pytorch_train --minibatches 0 --verbose 0 --resume --train-json dump/tr_it/deltafalse/data.json --valid-json dump/dt_it/deltafalse/data.json 
# Started at Tue Mar 21 15:54:11 EAT 2023
#
/home/mera/espnet/egs/vcc4/asr1/../../../espnet/bin/asr_train.py:25: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  is_torch_1_2_plus = LooseVersion(torch.__version__) >= LooseVersion("1.2")
Traceback (most recent call last):
  File "/home/mera/espnet/egs/vcc4/asr1/../../../espnet/bin/asr_train.py", line 641, in <module>
    main(sys.argv[1:])
  File "/home/mera/espnet/egs/vcc4/asr1/../../../espnet/bin/asr_train.py", line 541, in main
    model_class = dynamic_import(model_module)
  File "/home/mera/espnet/espnet/utils/dynamic_import.py", line 22, in dynamic_import
    m = importlib.import_module(module_name)
  File "/home/mera/anaconda3/envs/espnet/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/mera/espnet/espnet/nets/pytorch_backend/e2e_asr_conformer.py", line 14, in <module>
    from espnet.nets.pytorch_backend.e2e_asr_transformer import E2E as E2ETransformer
  File "/home/mera/espnet/espnet/nets/pytorch_backend/e2e_asr_transformer.py", line 15, in <module>
    from espnet.nets.e2e_asr_common import end_detect
  File "/home/mera/espnet/espnet/nets/e2e_asr_common.py", line 18, in <module>
    from espnet.nets.beam_search_transducer import BeamSearchTransducer
  File "/home/mera/espnet/espnet/nets/beam_search_transducer.py", line 11, in <module>
    from typeguard import check_argument_types
ImportError: cannot import name 'check_argument_types' from 'typeguard' (/home/mera/anaconda3/envs/espnet/lib/python3.8/site-packages/typeguard/__init__.py)
# Accounting: time=1 threads=1
# Ended (code 1) at Tue Mar 21 15:54:12 EAT 2023, elapsed time 1 seconds

**Comment by mera-mike** [comment]
this is the list which gives in the python3 check_install.py


expr: syntax error: unexpected argument ‘102’
Perform on CPU mode: CPU_ONLY=0
PYTHON=/home/mera/anaconda3/envs/espnet/bin/python3
PYTHON_VERSION=Python 3.8.16
IS_CONDA=0
USE_PIP=
TH_VERSION=1.4.0
CONDA_PYTORCH=pytorch=1.4.0 cpuonly
PIP_PYTORCH=torch==1.4.0 -f https://download.pytorch.org/whl/cpu/torch_stable.html
CHAINER_VERSION=6.0.0
PIP_CHAINER=chainer==6.0.0
NO_CUPY=0
. ./activate_python.sh; . ./extra_path.sh; python3 check_install.py
[x] python=3.8.16 (default, Mar  2 2023, 03:21:46)  [GCC 11.2.0]

Python modules:
[x] torch=1.4.0
[ ] torch cuda
[x] torch cudnn=7605
[x] torch nccl
[x] chainer=6.0.0
check_install.py:70: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  if LooseVersion(chainer.__version__) != LooseVersion("6.0.0"):
[ ] chainer cuda
[ ] chainer cudnn
[ ] cupy
[x] torchaudio=0.4.0
[x] torch_optimizer=0.1.0
[ ] warpctc_pytorch
[ ] warprnnt_pytorch
[ ] warp_rnnt
[ ] chainer_ctc
[x] pyopenjtalk
[x] kenlm
[ ] mmseg
[x] espnet=0.9.7

Executables:
[x] sclite
[x] sph2pipe
[ ] PESQ
[ ] BeamformIt

INFO:
Use 'installers/install_warp-ctc.sh' to install warpctc_pytorch
Use 'installers/install_warp-transducer.sh' to install warprnnt_pytorch
Use 'installers/install_warp-rnnt.sh' to install warp_rnnt
Use 'installers/install_chainer_ctc.sh' to install chainer_ctc
Use 'installers/install_py3mmseg.sh' to install mmseg
Use 'installers/install_pesq.sh' to install PESQ
Use 'installers/install_beamformit.sh' to install BeamformIt

**Comment by kamo-naoyuki** [comment]
Please downgrade typeguard: https://github.com/espnet/espnet/blob/0b24151788879b3e6d8bd6e1ef3c88a641b968fd/setup.py#L14
 (Please search before asking us)

**Comment by kamo-naoyuki** [comment]
No. You simply still have latest typeguard.

**Comment by kamo-naoyuki** [comment]
I can't understand why you can't downgrade typeguard.  It's very basic of python. 

```sh
pip install typeguard==2.13.3
```

**Comment by kamo-naoyuki** [comment]
Pleaes note that you need to activate your conda before pip

**Comment by mera-mike** [comment]
and thanku @kamo u save the day

**Comment by mera-mike** [comment]
yes the typeguard thing worked but it took me to other error kkk

**Comment by mera-mike** [comment]
hey @kamo-naoyuki  can u help to trace this error during decoding using this command


../../../utils/recog_wav.sh --api v1 --cmvn cmvn.ark --lang_model model/results/rnnlm.model.best --recog_model model/results/model.loss.best --decode_config conf/decode_ctcweight0.5.yaml audio_16k_enhanced.wav


it says

# asr_recog.py --config conf/decode_ctcweight0.5.yaml --ngpu 0 --backend pytorch --debugmode 1 --verbose 1 --recog-json decode/audio_16k_enhanced/dump/data.json --result-label decode/audio_16k_enhanced/result.json --model model/results/model.loss.best --api v1 --rnnlm model/results/rnnlm.model.best 
# Started at Mon Apr  3 15:02:37 EAT 2023
#
2023-04-03 15:02:37,834 (asr_recog:353) INFO: python path = /home/mera/espnet/tools/RawNet/python/RawNet3:/home/mera/espnet/tools/RawNet/python/RawNet3/models:/home/mera/espnet/tools/s3prl:
2023-04-03 15:02:37,834 (asr_recog:358) INFO: set random seed = 1
2023-04-03 15:02:37,834 (asr_recog:369) INFO: backend = pytorch
Traceback (most recent call last):
  File "/home/mera/espnet/egs/tig/asr1/../../../espnet/bin/asr_recog.py", line 411, in <module>
    main(sys.argv[1:])
  File "/home/mera/espnet/egs/tig/asr1/../../../espnet/bin/asr_recog.py", line 389, in main
    recog(args)
  File "/home/mera/espnet/espnet/asr/pytorch_backend/asr.py", line 1237, in recog
    rnnlm_args.layer,
AttributeError: 'tuple' object has no attribute 'layer'
# Accounting: time=2 threads=1
# Ended (code 1) at Mon Apr  3 15:02:39 EAT 2023, elapsed time 2 seconds
