### ISSUE TITLE
[Info] Tensorboard-like experiment browser prototype

### ISSUE THREAD

**Issue by ShigekiKarita** [espnet/espnet#504]
As suggested in #483 by @gtache, some people including me want tensorboard integration. Because I found that tensorboard integration with chainer reporters can be hell, I made tiny flask based web app, which explore `espnet/egs/**/exp/results` and report something useful for me.

demo: https://shigekikarita.github.io/espnet-browser/
repo: https://github.com/ShigekiKarita/espnet-browser/tree/v0.0.1

Although this is a mock app (~140 lines, 1 day to develop),  it has already helped me to explore good settings in a brand new architecture #465. It also shows what I need for tensorboard integration. So I want to share this with you.

**Comment by Fhrozen** [comment]
Thank for contribution. I am using it to check the progress of the experiments.
It will be better if you put the version of python. I tried with python 2.7 and I got indent errors. Python 3.6 has no problem. 
Is the implementation for mainly python3.6?

**Comment by ShigekiKarita** [comment]
Yes, this heavily uses f-string in python3.6 https://www.python.org/dev/peps/pep-0498/
