### ISSUE TITLE
Broken ASR url in espnet/egs/libri_css/asr1/run.sh

### ISSUE THREAD

**Issue by boeddeker** [espnet/espnet#5048]
**Describe the bug**
I get a 404 error, when I try to open the `asr_url` from `espnet/egs/libri_css/asr1/run.sh`.
The link is: https://drive.google.com/open?id=17cOOSHHMKI82e1MXj4r2ig8gpGCRmG2p

Code: https://github.com/espnet/espnet/blob/f3e5ce080505d1d49c4a16248aa0a61e4c04a27e/egs/libri_css/asr1/run.sh#LL23C9-L23C75

**Task information:**
 - Task: ASR
 - Recipe: libri_css
 - ESPnet1

**To Reproduce**
1. Copy value of `asr_url` from `espnet/egs/libri_css/asr1/run.sh`
2. Paste link in browser and press enter

**Comment by ShigekiKarita** [comment]
Oh sorry, it was accidentally deleted. I've just uploaded to https://drive.google.com/file/d/17dbjr805hMSSsbDT-UWMVtn1xhaHpxUD/view?usp=share_link
Should I simply replace the URL? OR can you re-uploaded it to elsewhere, e.g. zenodo?

**Comment by sw005320** [comment]
I copied it to my Google Drive.
https://drive.google.com/file/d/1RHYAhcnlKz08amATrf0ZOWFLzoQphtoc/view?usp=share_link
We used to centralize the espent1 model there. So, we can use this link.
Can you make a PR to fix this libri_css recipe and the above Librispeech README link?

I agree that it would be more reliable if put to zenodo or HFhub but espnet1 pre-trained models would not have so many requests in the future, and we may leave it with this solution.
