### ISSUE TITLE
Error: stop at stage1 Feature generation

### ISSUE THREAD

**Issue by Ruhewang** [espnet/espnet#505]
Hi, I'm total a newbie of ASR. Thank you for sharing such great toolkit sincerely. But there comes a problem when i strictly follow the instructions step by step. 
In command `source venv/bin/activate && python check_install.py` , everything goes well. But when i try examples with `$ ./run.sh --backend chainer`, here comes error
`stage -1: Data Download`
`local/download_and_untar.sh: an4 directory already exists in ./downloads`

`stage 0: Data preparation`

`stage 1: Feature Generation`
`steps/make_fbank_pitch.sh --cmd run.pl --mem 2G --nj 8 --write_utt2num_frames true data/test exp/make_fbank/test fbank`
`utils/validate_data_dir.sh: Successfully validated data-directory data/test
steps/make_fbank_pitch.sh: [info]: no segments file exists: assuming wav.scp indexed by utterance.`
`run.pl: 8 / 8 failed, log is in exp/make_fbank/test/make_fbank_pitch_test.*.log
`
Do you know why? thank you

**Comment by gtache** [comment]
Hello, could you post the content of the exp/make_fbank/test/make_fbank_pitch_test.1.log file ?

**Comment by Ruhewang** [comment]
yep. of course.
`# paste-feats --length-tolerance=2 "ark:compute-fbank-feats  --verbose=2 --config=conf/fbank.conf scp,p:exp/make_fbank/test/wav.8.scp ark:- |" "ark,s,cs:compute-kaldi-pitch-feats --verbose=2 --config=conf/pitch.conf scp,p:exp/make_fbank/test/wav.8.scp ark:- | process-kaldi-pitch-feats  ark:- ark:- |" ark:- | copy-feats --compress=true --write-num-frames=ark,t:exp/make_fbank/test/utt2num_frames.8 ark:- ark,scp:/home/user/CARL_remote/espnet/egs/an4/asr1/fbank/raw_fbank_pitch_test.8.ark,/home/user/CARL_remote/espnet/egs/an4/asr1/fbank/raw_fbank_pitch_test.8.scp `
`# Started at Mon Dec 17 18:28:00 HKT 2018`
`#`
`bash: line 1: copy-feats: command not found`
`bash: line 1: paste-feats: command not found`
`# Accounting: time=0 threads=1`
`# Ended (code 127) at Mon Dec 17 18:28:00 HKT 2018, elapsed time 0 seconds`

**Comment by Ruhewang** [comment]
thank you for the reply
`your_espnet_root/tools/kaldi/src/featbin` does contain copy-feats.cc and paste-feats.cc.
and the `path.sh` in `egs/an4/asr1` is exactly same as yours

personal hypothesis:  In `path.sh` file, i don't find that we export `my_kaldi/src/featbin` path to any environment variable. So it leads to `copy-feats: command not found`? (it's just a silly guess, i know it must be much more complicated than i thought) XD

**Comment by gtache** [comment]
It's not good if it only contains .cc files, it means that they haven't been compiled. My `ls` output looks like this      
![2018-12-18_12h34_14](https://user-images.githubusercontent.com/14289171/50151489-520c6b00-02c1-11e9-916c-68633dcc8e83.png)
To install kaldi, go to : 
- kaldi/tools/extras, run check_dependencies.sh and check that everything is okay
- kaldi/tools, run `make OPENFST_VERSION=1.6.9 -j 8`
- kaldi/src, run `./configure --shared && make depend && make -j 8`
- kaldi/tools, run `./install_srilm.sh` (optional)

Then it should work!

**Comment by Ruhewang** [comment]
i got it,i didnt compile cc file to executable file. Thank you for the generous help. it works now.

**Comment by kamyararshi** [comment]
Hello everyone,

Thanks for the thread. I have the same problem however, the cc files are compiled as well and for instance I have "compute-spectrogram-feats", "compute-spectrogram-feats.cc", and "compute-spectrogram-feats.o" in the src/featbin/. Still I get the errors "copy-feats" and "compute-spectrogram-feats" commands not found.
I have installed kaldi in the root directory of where I run a bash file that needs those commands:
-root
    - kaldi
        - src
        - tools
        - ...
    - bash.sh

**Comment by kamyararshi** [comment]
Just solved it by easily doing a 

```bash
export PATH=./kaldi/src/featbin:$PATH
```
