### ISSUE TITLE
Question regarding the ASR output

### ISSUE THREAD

**Issue by xixihahaggg** [espnet/espnet#5051]
Hi,

  I have a question regarding the ASR output. I'm trying to evaluate the confidence of the ASR output. And I find the token-level and sentence-level cores of decoder/ctc/lm . 

  I'm wondering if there is an option to obtain the word-level probability from the output.

  Thank you in advance.

**Comment by sw005320** [comment]
https://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=8639693 can perform the word level scoring during beam search, and you can find its implementation in espnet1, and can get the word-level probability.
But this one is based on character-based E2E models.
If we use BPE tokens, it is not straightforward.

**Comment by xixihahaggg** [comment]
Thank you for your answer! I will take a closer look.

**Comment by xixihahaggg** [comment]
Sorry to bother you again, but I have a quick question. Do you know where the implementation of this function is? I had a hard time finding it out.

**Comment by sw005320** [comment]
Check LookAheadWordLM in espnet/espnet/espnet/lm/pytorch_backend/extlm.py
I think you can refer to it to some extent, but this is a technique to estimate char-level scores from word LMs, and it is different from what you want.
