### ISSUE TITLE
Is this a bug in splitjson.py?

### ISSUE THREAD

**Issue by GaofengCheng** [espnet/espnet#507]
Under python3.7 the splitjson.py will break down, at least under my setup.

Should this line: https://github.com/espnet/espnet/blob/master/utils/splitjson.py#L47
be:     utt_id_lists = np.array_split(np.array(list(utt_ids)), args.parts) ?

**Comment by gtache** [comment]
Yes, the splitjson on master only supports Python2, however the new utils scripts on the v0.3.0 branch should support Python3 too.
