### ISSUE TITLE
question about feature params in TTS 

### ISSUE THREAD

**Issue by asr-pub** [espnet/espnet#5078]
I found the feature params in most tts recipes is:
```
fs=24000
n_fft=2048
n_shift=300
win_length=1200
```
Why the n_fft, n_shift and win_length set these, is these a best combination ?

**Comment by kan-bayashi** [comment]
This is based on Tacotron2 paper.
Not so much investigated, and several configs use 1024 / 256.

**Comment by asr-pub** [comment]
3Q
