### ISSUE TITLE
RuntimeError: The size of tensor a (2) must match the size of tensor b (80) at non-singleton dimension 2

### ISSUE THREAD

**Issue by iamsashank09** [espnet/espnet#5079]
Task: ASR
Data: Custom Data

Config: Using Wav2Vec and finetuning the last layer
https://github.com/espnet/espnet/blob/master/egs2/librispeech/asr1/conf/tuning/train_asr_transformer3_w2v_large_lv60_960h_finetuning_last_1layer.yaml

This is my Stage 11 command:

`./asr.sh --stage 11 --stop_stage 11 --train_set traindir --valid_set validdir --test_sets testdir \
 --asr_config "conf/tuning/train_asr_transformer3_w2v_large_lv60_960h_finetuning_last_1layer.yaml" --asr_tag "cordi_wav2vec_ft_50wav_500token_training" \
 --ngpu 1 --ignore_init_mismatch true`

I get this error:

> Model summary:
>     Class Name: ESPnetASRModel
>     Total Number of model parameters: 392.58 M
>     Number of trainable parameters: 89.74 M (22.9%)
>     Size: 358.95 MB
>     Type: torch.float32
> [dgx001] 2023-04-03 10:08:35,415 (abs_task:1194) INFO: Optimizer:
> Adam (
> Parameter Group 0
>     amsgrad: False
>     betas: (0.9, 0.999)
>     capturable: False
>     differentiable: False
>     eps: 1e-08
>     foreach: None
>     fused: False
>     initial_lr: 0.001
>     lr: 4e-08
>     maximize: False
>     weight_decay: 0
> )
> [dgx001] 2023-04-03 10:08:35,415 (abs_task:1195) INFO: Scheduler: WarmupLR(warmup_steps=25000)
> [dgx001] 2023-04-03 10:08:35,418 (abs_task:1204) INFO: Saving the configuration in exp/asr_cordi_wav2vec_ft_50wav_500token_training/config.yaml
> [dgx001] 2023-04-03 10:08:35,753 (asr:471) INFO: Optional Data Names: ('text_spk2', 'text_spk3', 'text_spk4')
> [dgx001] 2023-04-03 10:08:35,894 (abs_task:1559) INFO: [train] dataset:
> ESPnetDataset(
>   speech: {"path": "dump/raw/traindir/wav.scp", "type": "sound"}
>   text: {"path": "dump/raw/traindir/text", "type": "text"}
>   preprocess: <espnet2.train.preprocessor.CommonPreprocessor object at 0x7fbc4c6bce50>)
> [dgx001] 2023-04-03 10:08:35,894 (abs_task:1560) INFO: [train] Batch sampler: NumElementsBatchSampler(N-batch=48, batch_bins=15000000, sort_in_batch=descending, sort_batch=descending)
> [dgx001] 2023-04-03 10:08:35,895 (abs_task:1561) INFO: [train] mini-batch sizes summary: N-batch=48, mean=161.7, min=32, max=527
> [dgx001] 2023-04-03 10:08:35,919 (asr:471) INFO: Optional Data Names: ('text_spk2', 'text_spk3', 'text_spk4')
> [dgx001] 2023-04-03 10:08:35,931 (abs_task:1559) INFO: [valid] dataset:
> ESPnetDataset(
>   speech: {"path": "dump/raw/validdir/wav.scp", "type": "sound"}
>   text: {"path": "dump/raw/validdir/text", "type": "text"}
>   preprocess: <espnet2.train.preprocessor.CommonPreprocessor object at 0x7fbc4c7f5c70>)
> [dgx001] 2023-04-03 10:08:35,931 (abs_task:1560) INFO: [valid] Batch sampler: NumElementsBatchSampler(N-batch=7, batch_bins=15000000, sort_in_batch=descending, sort_batch=descending)
> [dgx001] 2023-04-03 10:08:35,931 (abs_task:1561) INFO: [valid] mini-batch sizes summary: N-batch=7, mean=138.3, min=19, max=267
> [dgx001] 2023-04-03 10:08:35,934 (asr:471) INFO: Optional Data Names: ('text_spk2', 'text_spk3', 'text_spk4')
> [dgx001] 2023-04-03 10:08:35,957 (abs_task:1559) INFO: [plot_att] dataset:
> ESPnetDataset(
>   speech: {"path": "dump/raw/validdir/wav.scp", "type": "sound"}
>   text: {"path": "dump/raw/validdir/text", "type": "text"}
>   preprocess: <espnet2.train.preprocessor.CommonPreprocessor object at 0x7fbc4c7f9220>)
> [dgx001] 2023-04-03 10:08:35,957 (abs_task:1560) INFO: [plot_att] Batch sampler: UnsortedBatchSampler(N-batch=968, batch_size=1, key_file=exp/asr_stats_raw_bpe500/valid/speech_shape, 
> [dgx001] 2023-04-03 10:08:35,957 (abs_task:1561) INFO: [plot_att] mini-batch sizes summary: N-batch=3, mean=1.0, min=1, max=1
> [dgx001] 2023-04-03 10:08:36,047 (trainer:284) INFO: 1/100epoch started
> Traceback (most recent call last):
>   File "/home/skakarap/Research/espnet/espnet/tools/anaconda/envs/espnet/lib/python3.9/runpy.py", line 197, in _run_module_as_main
>     return _run_code(code, main_globals, None,
>   File "/home/skakarap/Research/espnet/espnet/tools/anaconda/envs/espnet/lib/python3.9/runpy.py", line 87, in _run_code
>     exec(code, run_globals)
>   File "/home/skakarap/Research/espnet/espnet/espnet2/bin/asr_train.py", line 23, in <module>
>     main()
>   File "/home/skakarap/Research/espnet/espnet/espnet2/bin/asr_train.py", line 19, in main
>     ASRTask.main(cmd=cmd)
>   File "/home/skakarap/Research/espnet/espnet/espnet2/tasks/abs_task.py", line 1043, in main
>     cls.main_worker(args)
>   File "/home/skakarap/Research/espnet/espnet/espnet2/tasks/abs_task.py", line 1348, in main_worker
>     cls.trainer.run(
>   File "/home/skakarap/Research/espnet/espnet/espnet2/train/trainer.py", line 290, in run
>     all_steps_are_invalid = cls.train_one_epoch(
>   File "/home/skakarap/Research/espnet/espnet/espnet2/train/trainer.py", line 567, in train_one_epoch
>     retval = model(**batch)
>   File "/home/skakarap/Research/espnet/espnet/tools/anaconda/envs/espnet/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
>     return forward_call(*input, **kwargs)
>   File "/home/skakarap/Research/espnet/espnet/espnet2/asr/espnet_model.py", line 217, in forward
>     encoder_out, encoder_out_lens = self.encode(speech, speech_lengths)
>   File "/home/skakarap/Research/espnet/espnet/espnet2/asr/espnet_model.py", line 366, in encode
>     feats, feats_lengths = self.normalize(feats, feats_lengths)
>   File "/home/skakarap/Research/espnet/espnet/tools/anaconda/envs/espnet/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
>     return forward_call(*input, **kwargs)
>   File "/home/skakarap/Research/espnet/espnet/espnet2/layers/global_mvn.py", line 86, in forward
>     x -= self.mean
> RuntimeError: The size of tensor a (2) must match the size of tensor b (80) at non-singleton dimension 2
> 

I don't have an idea of how to get started with fixing this? Would really appreciate some advice on this.

**Comment by sw005320** [comment]
Thanks for the report.
@simpleoier, do you have any idea about it?

**Comment by iamsashank09** [comment]
Please let me know if you need any more information from my end.

**Comment by simpleoier** [comment]
@iamsashank09 You are using global_mvn while your stats are computed from FBank feature. My suggestion is to use `--feats_normalize utt_mvn` in run.sh

**Comment by iamsashank09** [comment]
Thanks @simpleoier ! I'll try it out and update this thread. So, I should be passing `'--feats_normalize utt_mvn'` to the asr.sh through the `'run.sh'` right?

**Comment by simpleoier** [comment]
Correct!

**Comment by iamsashank09** [comment]
Thank you, `utt_mvn` worked!
