### ISSUE TITLE
Language model training time

### ISSUE THREAD

**Issue by Ruhewang** [espnet/espnet#509]
Hi 
I'm trying to train a ASR model of 100-hrs-librispeech data with 1 GPU, and mainly follow the `run.sh` script in `egs`. 
However, in Stage 3, the training of the language model `librispeech-lm-norm` has already taken me 8 hrs and there is no sign to stop. I wonder that is it normal? Should i keep waiting.
best regard
Ruhe

**Comment by Ruhewang** [comment]
oh, just found that i can check it in train.log. it estimates three days to train the language model. Is it because my CPU is too slow? cuz I dint even enter stage 4 to train network.

**Comment by sw005320** [comment]
RNNLM training for the Librispeech takes long time (3-4 days). You can reduce the training data or only use the transcriptions.

**Comment by Daniel-asr** [comment]
@sw005320 what do you mean with "or only use the transcriptions"?

**Comment by sw005320** [comment]
Librispeech has external text data for language model training. 
We usually mix the external text data and ASR transcriptions for language model training (see https://github.com/espnet/espnet/blob/master/egs/librispeech/asr1/run.sh#L181-L184).
The above suggestion is to only use ASR transcriptions that is `data/local/lm_train/${train_set}_text.gz`

**Comment by Daniel-asr** [comment]
Got it. Thank you!
