### ISSUE TITLE
multi_head_multi_res_loc attention type decode error

### ISSUE THREAD

**Issue by wbgxx333** [espnet/espnet#510]
hi,
   when i use the multi_head_multi_res_loc attention type,the training is ok.but decode is error.and is 
 File "/*/espnet/espnet/asr/asr_pytorch.py", line 464, in recog
    nbest_hyps = e2e.recognize_batch(feats, args, train_args.char_list, rnnlm=rnnlm)
  File "/*/espnet/espnet/nets/e2e_asr_th.py", line 515, in recognize_batch
    y = self.dec.recognize_beam_batch(hpad, hlens, lpz, recog_args, char_list, rnnlm)
  File "/*/espnet/espnet/nets/e2e_asr_th.py", line 2427, in recognize_beam_batch
    a_prev = torch.index_select(att_w.view(n_bb, -1), 0, vidx)
AttributeError: 'list' object has no attribute 'view'

and the decode isn't support the multi_head_multi_res_loc attention type?

**Comment by kan-bayashi** [comment]
Hi @wbgxx333.
Sorry for late reply.
This is fixed in #481.
Could you test this patch?

**Comment by wbgxx333** [comment]
yes, it test ok.but use the multi_head_multi_res_loc attention type is worse than default.
