### ISSUE TITLE
import libs.common as common_lib ModuleNotFoundError: No module named 'libs' when trying EEND-SS

### ISSUE THREAD

**Issue by kaiwei890604** [espnet/espnet#5101]
When I run /egs2/librimix/enh_diar1/run.sh
It's fail at stage 2

Traceback (most recent call last):
  File "steps/segmentation/convert_utt2spk_and_segments_to_rttm.py", line 30, in <module>
    import libs.common as common_lib
ModuleNotFoundError: No module named 'libs'

Basic environments:

 OS information: Ubuntu x86-64
 python version: 3.8.16
 espnet version: espnet202301
 torch version: 1.13.1

**Comment by sw005320** [comment]
Thanks for the report.
Could you test to install libs?
`pip install libs`

If it works, we may consider including it in our `setpu.py`

**Comment by kaiwei890604** [comment]
Hi.Thanks for your replying.
But I have already tried pip install libs before.
And the error changed to

Traceback (most recent call last):
  File "steps/segmentation/convert_utt2spk_and_segments_to_rttm.py", line 30, in <module>
    import libs.common as common_lib
ModuleNotFoundError: No module named 'libs.common'

**Comment by sw005320** [comment]
I think I found the issues.
We need to include `https://github.com/kaldi-asr/kaldi/blob/master/egs/wsj/s5/steps/libs/common.py`

Could you test it by copying it to `espnet/egs2/TEMPLATE/asr1/steps/libs` ?

**Comment by kamo-naoyuki** [comment]
Sorry, this is a mistake on my side. I'll fix

**Comment by kaiwei890604** [comment]
After I put common.py to espnet/egs2/TEMPLATE/asr1/steps/libs,
it's still missing convert_rttm.py on egs2/librimix/enh_diar1/pyscripts/utils.
I copied my old espnet files,and it works now.

Thanks for your help!

Can I ask another question?
After I run ./run.sh on egs2/librimix/enh_diar1/,
the der in DIAR_RESULTS.md is

diarized_enhanced_test
|threshold_median_collar|DER|
|---|---|
|result_th0.3_med11_collar0.0|9.35|
|result_th0.3_med1_collar0.0|9.41|
|result_th0.4_med11_collar0.0|10.43|
|result_th0.4_med1_collar0.0|10.48|
|result_th0.5_med11_collar0.0|11.52|
|result_th0.5_med1_collar0.0|11.58|
|result_th0.6_med11_collar0.0|12.68|
|result_th0.6_med1_collar0.0|12.72|
|result_th0.7_med11_collar0.0|13.91|
|result_th0.7_med1_collar0.0|13.95|

Der's performance in libri2mix is much higher than EEND-SS's paper.
I only change the batch size from 16 to 8.
Did I miss something?

**Comment by sw005320** [comment]
Cool!
It might be better to make another issue for this performance.
I added @soumimaiti to this thread.
She will answer it.
