### ISSUE TITLE
Shouldn't skip stage 14 if `--skip_upload_hf` is true when calling `asr.sh`

### ISSUE THREAD

**Issue by tjysdsg** [espnet/espnet#5148]
**Describe the bug**
When running `asr.sh`, stage 14 (packing model) is skipped even if `--skip_upload_hf` is set to true.
This is because the script doesn't add `14` to `skip_stages` only if both `--skip_upload` and `--skip_upload_hf` are set to true.
However, a common usecase is to upload a model only to huggingface but not zendoo.

This bug is introduced by 09ce6405 @kamo-naoyuki

**Comment by kamo-naoyuki** [comment]
Oh, thanks, your are right.
