### ISSUE TITLE
Place support wav2letter by pytorch

### ISSUE THREAD

**Issue by shanguanma** [espnet/espnet#516]
We hope you to add a variant of CTC (ASG) 
reference: Letter-Based Speech Recognition with Gated ConvNets.
and gate cnn lm:
reference: Language Modeling with Gated Convolutional Networks.

**Comment by sw005320** [comment]
Thanks for the suggestion.
Gated ConvNet is one of our future plans, but for now we set higher priorities on the transformer #465.
