### ISSUE TITLE
I want to know how the data of this structure is generated, please help me, thank you very much

### ISSUE THREAD

**Issue by zhangkg2016** [espnet/espnet#5161]
When executing step 5 of the run.sh script in aishell, how should the parameters of this step be adjusted to generate the following data structure, or is there another method?
![333](https://user-images.githubusercontent.com/12874343/236982063-10552246-46a2-46ae-8d20-7f60d22b4691.png)

This is the target data structure，
![111](https://user-images.githubusercontent.com/12874343/236981334-b5670c7c-15dc-4464-be63-040087dc9f4f.png)
![222](https://user-images.githubusercontent.com/12874343/236981360-64eed64b-f9fa-4b19-b713-2fecfceb6913.png)

**Comment by sw005320** [comment]
This json file is generated from https://github.com/espnet/espnet/blob/master/egs/aishell/asr1/run.sh#L150

**Comment by zhangkg2016** [comment]
> This json file is generated from https://github.com/espnet/espnet/blob/master/egs/aishell/asr1/run.sh#L150

Thank you for your help, but there is no full_scores in my generated json file, what should I do？
