### ISSUE TITLE
broken links in must_c dataset

### ISSUE THREAD

**Issue by csukuangfj** [espnet/espnet#5190]
https://github.com/espnet/espnet/blob/13b986ce0595b4366c6e3381a981379600b958a4/egs/must_c/st1/local/download_and_untar.sh#L36-L53

https://github.com/espnet/espnet/blob/13b986ce0595b4366c6e3381a981379600b958a4/egs/must_c/st1/local/download_and_untar.sh#L57-L59

All the above google drive URLs are broken and they lead to `Error 404`.

**Comment by sw005320** [comment]
Thanks for the report.
@brianyan918 or @pyf98, can you fix them?

**Comment by notegeek** [comment]
Hi authors, I also find the Google drive link of mustc v1 and v2 datasets are 404. Could you fix them? Thank you.

**Comment by sw005320** [comment]
@csukuangfj and @notegeek, sorry for the late response.
Please check https://github.com/espnet/espnet/pull/5516 or https://github.com/espnet/espnet/discussions/5506
