### ISSUE TITLE
How to reproduce Corr with “Conformer + specaug + speed perturbation: feats=raw, n_fft=512, hop_length=128“”

### ISSUE THREAD

**Issue by yan-rui** [espnet/espnet#5225]
II cannot reproduce conformer Corr as described in the documentation. I can only score **Corr 95.1**.
I trained with 8 Gpus. In order to speed up the training, I increased the batch_bins to 64000000, while accum_grad was reduced to 1.

My training script is as follows:
./run.sh --ngpu 8  --asr_config conf/tuning/train_asr_conformer.yaml --lm_config conf/tuning/train_lm_transformer.yaml

Please help me get **Corr 95.4** in doc, it will help me a lot, thank you very much.

**Basic environments:**
 - OS information:   Linux 3a1c85302a95 5.4.0-148-generic 

 - python version: 3.7.9 (default, Aug 31 2020, 12:42:55)[GCC 7.3.0]
 - Git hash 0216f854c2dfc855c17b986b0c67938eecd9ea1c 
   - Commit date  Tue Jun 6 12:05:06 2023 -0700
 - pytorch version pytorch 1.10.2
 - num of GPUs： 8
 - GPU mem： 32GB

**Comment by sw005320** [comment]
This small difference would be expected since you change `batch_bins,` and also, the espnet result is not deterministic.

**Comment by yan-rui** [comment]
> This small difference would be expected since you change `batch_bins,` and also, the espnet result is not deterministic.

Can you give me the training parameters of Corr 95.4?
The links given in the document are for inference. Checkout  to the same commit id and cannot be installed with the current installation document.

**Comment by sw005320** [comment]
The small difference comes not only from the version but also from the GUP card type, cuda, cudnn versions, etc. Also, some operations are not deterministic; even if they are completely the same, they would not be reproducible.
