### ISSUE TITLE
Something wrong with the LRS3 asr1 pipeline

### ISSUE THREAD

**Issue by MrSupW** [espnet/espnet#5232]
Hello,  I'm working on ASR using LRS3 dataset and the pipeline espnet provides. But I find something wrong. Here is my acc chart and decode result. It looks  like the trained model only use a few words, and I checked the transcription that is all right, so is there anything wrong with my bpe model?  
![image](https://github.com/espnet/espnet/assets/57617568/bb337c7b-0e5c-4425-90d2-db6851b81768)
![image](https://github.com/espnet/espnet/assets/57617568/26e1b16d-664c-42dd-a849-88796a87108a)
Here is my run.sh:
set -e
set -u
set -o pipefail

train_set="train_all"
valid_set="dev"
test_sets="test"

ngpu=8
device="0,1,2,3,4,5,6,7"

expdir=exp/train_all
dumpdir=../dump_train_all_ark_sp

asr_config=conf/train_asr_e_branchformer_e24.yaml
lm_config=conf/train_lm_transformer.yaml

inference_config=conf/decode_asr_beam20_ctc0.5_lm0.1.yaml
inference_asr_model=13epoch.pth

lm_config=conf/train_lm_transformer.yaml
use_lm=false
use_word_lm=false

speed_perturb_factors="0.9 1.0 1.1"

CUDA_VISIBLE_DEVICES=${device} ./asr.sh \
    --ngpu ${ngpu} \
    --expdir ${expdir} \
    --dumpdir ${dumpdir} \
    --nj 64 \
    --inference_nj 32 \
    --inference_asr_model ${inference_asr_model}  \
    --lang en \
    --audio_format "wav.ark" \
    --nbpe 5000 \
    --speed_perturb_factors "${speed_perturb_factors}" \
    --feats_type raw \
    --use_lm "${use_lm}" \
    --use_word_lm "${use_word_lm}" \
    --max_wav_duration 30 \
    --train_set "${train_set}" \
    --valid_set "${valid_set}" \
    --test_sets "${test_sets}" \
    --asr_config "${asr_config}" \
    --inference_config "${inference_config}" \
    --lm_config ${lm_config} \
    --lm_train_text "data/${train_set}/text" \
    --bpe_train_text "data/${train_set}/text" "$@"

Here is my train asr config
# network architecture
# encoder related
encoder: e_branchformer
encoder_conf:
    output_size: 256
    attention_heads: 4
    attention_layer_type: rel_selfattn
    pos_enc_layer_type: rel_pos
    rel_pos_type: latest
    cgmlp_linear_units: 2048
    cgmlp_conv_kernel: 31
    use_linear_after_conv: false
    gate_activation: identity
    num_blocks: 24
    dropout_rate: 0.1
    positional_dropout_rate: 0.1
    attention_dropout_rate: 0.1
    input_layer: conv2d
    layer_drop_rate: 0.0
    linear_units: 1024
    positionwise_layer_type: linear
    use_ffn: true
    macaron_ffn: true
    merge_conv_kernel: 31

# decoder related
decoder: transformer
decoder_conf:
    attention_heads: 4
    linear_units: 2048
    num_blocks: 6
    dropout_rate: 0.1
    positional_dropout_rate: 0.1
    self_attention_dropout_rate: 0.0
    src_attention_dropout_rate: 0.0

# hybrid CTC/attention
model_conf:
    ctc_weight: 0.3
    lsm_weight: 0.1     # label smoothing option
    length_normalized_loss: false

# minibatch related
batch_type: numel
batch_bins: 40000000

# optimization related
accum_grad: 1
grad_clip: 5
max_epoch: 50
val_scheduler_criterion:
    - valid
    - acc
best_model_criterion:
-   - valid
    - acc
    - max
-   - train
    - acc
    - max
keep_nbest_models: 10

optim: adam
optim_conf:
   lr: 0.001
   weight_decay: 0.000001
scheduler: warmuplr
scheduler_conf:
   warmup_steps: 35250 # 10epoch

num_workers: 8      # num of workers of data loader
use_amp: true      # automatic mixed precision
unused_parameters: false    # set as true if some params are unused in DDP

specaug: specaug
specaug_conf:
    apply_time_warp: true
    time_warp_window: 5
    time_warp_mode: bicubic
    apply_freq_mask: true
    freq_mask_width_range:
    - 0
    - 27
    num_freq_mask: 2
    apply_time_mask: true
    time_mask_width_ratio_range:
    - 0.
    - 0.05
    num_time_mask: 10

**Comment by sw005320** [comment]
It seems that the model is not trained at all.
The accuracy is too low.
Please tune the optimizer-related parameters or use a smaller-size model

**Comment by MrSupW** [comment]
@sw005320 Thanks for your reply!  I modify the model size to a smaller one and It goes well now! Thx Again!
