### ISSUE TITLE
GPUs training freezes ?

### ISSUE THREAD

**Issue by cjjjy** [espnet/espnet#525]
HI ,when I run the 
   cd espnet-master/egs/an4/asr1
   ./run.sh --ngpu 1

The train.log 's content in exp directory seems did not change  after a long time.

but when i run the command without GPU 
 cd espnet-master/egs/an4/asr1
   ./run.sh 
it seems OK.

**Comment by sw005320** [comment]
Can you check whether your GPU environments are appropriately configured by following https://github.com/espnet/espnet#step-3-installation-check?

**Comment by rhoposit** [comment]
@sw005320 I am having a similar issue and the url linked above is stale. What is the check that I can do?

**Comment by sw005320** [comment]
Check https://github.com/espnet/espnet/pull/2360
I added the document about the check installation.
