### ISSUE TITLE
Espnet2/ljspeech (VITS) - is it possible to train with a 24GB GPU? (Experimenting)

### ISSUE THREAD

**Issue by BillDH2k** [espnet/espnet#5270]
Just wanted to learn and experiment with Espnet2/ljspeech (VITS). But I only have a 24GB GPU (RTX 3090) at the moment. Tried the default setting (train_vits.yaml), got "Cuda out of memory" error at state 6 (training). Any adjustments I could make so the training can proceed?  Or is it at all possible?  Thanks!

**Comment by kan-bayashi** [comment]
Please reduce this value not to cause OOM.
https://github.com/espnet/espnet/blob/abd3aa7674e34acb0c490031c92b64d874099351/egs2/ljspeech/tts1/conf/tuning/train_vits.yaml#L164C1-L164C1

See also:
https://espnet.github.io/espnet/espnet2_training_option.html?highlight=batch#change-mini-batch-type

**Comment by BillDH2k** [comment]
Thank you for your quick reply.  **Another question:** does it help to resolve the "out of memory" issue by adding a 2nd GPU (e.g. 3090 for a total of 48GB)? Or, the issue is bound to the single GPU? 

Thanks in advance to your answer!

**Comment by kan-bayashi** [comment]
If you use several gpus, the batch will be split into #gpus, as a result, the required gpu memory per gpu is reduced.
