### ISSUE TITLE
About LayerNorm eps value in Conformer...

### ISSUE THREAD

**Issue by mindmapper15** [espnet/espnet#5277]
https://github.com/espnet/espnet/blob/3651c2e67126c4544820cf148407be7f2679866c/espnet/nets/pytorch_backend/transformer/layer_norm.py#L12-L24

I discovered that the epsilon of LayerNorm in espnet set to 1e-12,
which is way lower compare to the default value 1e-05 in PyTorch LayerNorm class.

My questions are,

1) Could you tell me the reference of this epsilon value?

2) Could this may result negative impact in Automatic Mixed Precision training?
(Currently, I have trouble to train VITS TTS with mixed precision training...)

**Comment by sw005320** [comment]
Thanks for raising an issue.
@ShigekiKarita, could you answer this?

@mindmapper15, could you test it with `1e-05` to see if your VITS AMP training becomes stable or not?

**Comment by mindmapper15** [comment]
> Thanks for raising an issue. @ShigekiKarita, could you answer this?
> 
> @mindmapper15, could you test it with `1e-05` to see if your VITS AMP training becomes stable or not?


I have been trying to train VITS TTS model using AMP with KsponSpeech dataset but the gradient keeps explode during training...

I'll train 3 VITS TTS model with the LJSpeech :
1) no AMP
2) using AMP
3) using AMP with eps 1e-05 in LayerNorm

And I'll be back to post the result here :)

**Comment by ShigekiKarita** [comment]
I believe this is from early OpenNMT but they currently uses 1e-6 though https://opennmt.net/OpenNMT-py/_modules/onmt/decoders/transformer.html

**Comment by ShigekiKarita** [comment]
I remember AMP excludes the layer normalization layers in low precision mode https://github.com/NVIDIA/apex/blob/8ffc901e50bbf740fdb6d5bccb17f66a6ec8604e/apex/amp/lists/functional_overrides.py#L43

**Comment by ShigekiKarita** [comment]
See also https://pytorch.org/docs/stable/amp.html#cuda-ops-that-can-autocast-to-float32

**Comment by mindmapper15** [comment]
The result is here!

Good news is, the eps of LayerNorm is not the cause of problem.
Bas news is, AMP training in VITS still doesn't work even with the default configuration in LibriTTS dataset

AMP with LayerNorm eps 1e-12 (default in espnet), the Discriminator loss goes to Nan in 36 epoch,
AMP with LayerNorm eps 1e-05 (default in PyTorch), the Discriminator loss goes to Nan in 31 epoch.

I only doubled the batch_bins in default conf/train_xvector_vits.yaml in libritts recipe and used speechbrain xvector instead of kaldi xvector.

Here is the train.log of each experiment

[train.log (AMP with LayerNorm eps 1e-12)](https://github.com/espnet/espnet/files/12002636/train.log)
[train.log (AMP with LayerNorm eps 1e-05)](https://github.com/espnet/espnet/files/12002648/train.log)

I'll close this issue since the LayerNorm eps value is not the cause of the AMP training problem.
Maybe I'll open another issue and keep discussing about how to train VITS with AMP succesfully...
