### ISSUE TITLE
Forum announcement

### ISSUE THREAD

**Issue by ShigekiKarita** [espnet/espnet#528]
We are planning many improvements in v0.3.0 https://github.com/espnet/espnet/issues/444 (e.g., modularization, hdf5, and transformer). I have discussed with @sw005320 and @Fhrozen where to announce this release. For example,
- Library forum: chainer, pytorch
- ASR community: kaldi
- General: reddit
If you know something else, please let us know.

**Comment by sw005320** [comment]
Thanks. 
We should also announce it on facebook, twitter, linkedin.
