### ISSUE TITLE
Check the value of n_shift, upsample_factor in GAN_TTS

### ISSUE THREAD

**Issue by imdanboy** [espnet/espnet#5283]
In GAN_TTS such as VITS or JETS, `n_shift` decides the number of speech frames and affects the size of speech segment aligned to an input token.
The `upsample_factor` (set by `upsample_scales` in HiFiGANGenerator for example) decides how many to upsample its input tensor on time-axis and it usually equals to `n_shift`.

When `n_shift` > `upsample_factor`, the model training seems to work well but the generated speech is cut off at last some portions. I think this is error prone thus checking would be helpful.
For example,

```
diff --git a/espnet2/gan_tts/espnet_model.py b/espnet2/gan_tts/espnet_model.py
index 81d898df1..5a339aace 100644
--- a/espnet2/gan_tts/espnet_model.py
+++ b/espnet2/gan_tts/espnet_model.py
@@ -55,6 +55,15 @@ class ESPnetGANTTSModel(AbsGANESPnetModel):
             tts, "discriminator"
         ), "discriminator module must be registered as tts.discriminator"

+        if feats_extract is not None:
+            if hasattr(tts.generator, "vocoder"):
+                upsample_factor = tts.generator["vocoder"].upsample_factor
+            else:
+                upsample_factor = tts.generator.upsample_factor
+            assert (
+                feats_extract.get_parameters()["n_shift"] == upsample_factor
+            ), "n_shift must be equal to upsample_factor"
+
```

**Comment by ftshijt** [comment]
Yeah, that would be a very helpful function to add for users that are not familiar with the settings. It would be great if you can  make a PR with regarding your suggestion~

**Comment by kan-bayashi** [comment]
Thanks @imdanboy for fixing !
