### ISSUE TITLE
[Feature Request] inherit training/decoding options from other yaml file

### ISSUE THREAD

**Issue by tjysdsg** [espnet/espnet#5284]
AFAIK no one brought this up before and this feature doesn't exist in current version.
But would it be possible to allow a training config file to inherit options from another one. For example, often times we have a file that is mostly the same as another one but with a small amount of options being overridden. Instead of copying most of the options, we can do something like:

```yaml
based-on: path/to/another/train_xxx.yaml

model_conf:
    ctc_weight: 0.5
```

In theory, a yaml file should be able to inherit options from another yaml file that inherits from another file (grandson.yaml -> son.yaml -> parent.yaml)?

I believe this feature is very useful for managing research experiments or implementing new architectures. Also, it reduces the burden of maintaining large recipes.
If this is something we can merge into ESPnet, I'm very happy to contribute an implementation.

**Comment by b-flo** [comment]
It's a more straightforward approach but the script `tools/change_yaml.sh` was created for that purpose. I don't think it's used outside our integration tests in ESPnet1 though.

> I believe this feature is very useful for managing research experiments or implementing new architectures. Also, it reduces the burden of maintaining large recipes.
> If this is something we can merge into ESPnet, I'm very happy to contribute an implementation.

I'm much more nuanced on the usefulness of the feature but it won't harm to have the option anyway! I think it can be safely added.
