### ISSUE TITLE
Conda installation instructions cause "Not a directory" error

### ISSUE THREAD

**Issue by iamanigeeit** [espnet/espnet#5287]
`${CONDA_EXE}/../..` is not a valid path as CONDA_EXE is a file. Then setup_anaconda will fail.

https://espnet.github.io/espnet/installation.html
```
$ cd <espnet-root>/tools
$ CONDA_ROOT=${CONDA_EXE}/../..  # CONDA_EXE is an environment variable set by ${CONDA_ROOT}/etc/profile.d/conda.sh
$ ./setup_anaconda.sh ${CONDA_ROOT} [conda-env-name] [python-version]
# e.g.
$ ./setup_anaconda.sh ${CONDA_ROOT} espnet 3.8
```

Fix: use `${CONDA_PREFIX}` or `$(dirname $(dirname ${CONDA_EXE}))`

**Comment by kamo-naoyuki** [comment]
Thanks, you are right. I'll fix it
