### ISSUE TITLE
pysptk and pyworld install error

### ISSUE THREAD

**Issue by Atupon0302** [espnet/espnet#5309]
During the installation of espnet, errors occur when installing pysptk and pyworld. These errors are the same as the ones encountered in the current CI build of the espnet repository.

https://github.com/espnet/espnet/actions/runs/5583844030/jobs/10204579248
```
Failed to build pysptk pyworld
ERROR: Could not build wheels for pysptk, pyworld, which is required to install pyproject.toml-based projects
```
Could you please provide a solution or workaround for this issue?

**Comment by sqnian** [comment]
i met too.
maybe you can have a try:

pip install numpy
pip install pyworld --no-build-isolation
pip install pysptk --no-build-isolation

# or lower cython
pip3 install cython==0.29.36

BR

**Comment by kan-bayashi** [comment]
Try to fix in https://github.com/espnet/espnet/pull/5310

**Comment by kan-bayashi** [comment]
PySPTK seems to be fixed. Thanks @r9y9 for quick fixing.
https://github.com/r9y9/pysptk/releases/tag/v0.2.1
