### ISSUE TITLE
mergejson.py out of memory

### ISSUE THREAD

**Issue by lilian0118** [espnet/espnet#533]
I have 10,000h 16K audio data, when load all *.json in mergejson.py, it will out of memory. My computer only have 128GB memory, can we split big jsons to small piece? and run every small piece one by one?

**Comment by kamo-naoyuki** [comment]
For my reference, can you tell me the number of lines of your feats.scp file?

**Comment by lilian0118** [comment]
> For my reference, can you tell me the number of lines of your feats.scp file?

2019-01-10 11:36:41,138 (mergejson:41) INFO: data/train_nodev/tmp-FO1kr/feat.json: has 43873228 utterances
2019-01-10 11:41:53,678 (mergejson:41) INFO: data/train_nodev/tmp-FO1kr/idim.json: has 43873228 utterances
2019-01-10 11:49:17,102 (mergejson:41) INFO: data/train_nodev/tmp-FO1kr/ilen.json: has 43873228 utterances
2019-01-10 11:56:36,597 (mergejson:41) INFO: data/train_nodev/tmp-FO1kr/odim.json: has 43873228 utterances
2019-01-10 12:09:55,194 (mergejson:41) INFO: data/train_nodev/tmp-FO1kr/olen.json: has 43873228 utterances
2019-01-10 12:20:15,494 (mergejson:41) INFO: data/train_nodev/tmp-FO1kr/text.json: has 43873228 utterances
Killed

**Comment by kan-bayashi** [comment]
I think this problem is the same as #449.
Could you try to use `--output-json` option for `mergejson.py`?

**Comment by kamo-naoyuki** [comment]
@kan-bayashi This problem is not related to #449. That memory error happens when writing JSON file, but @lilian0118 met it when loading time.

**Comment by sw005320** [comment]
@lilian0118, thanks for the report.
I'm curious why the number of utterances is so large (43,873,228).
For example, in the Librispeech cases (~1000 hours), the number of utterances is 281,241. If you use the spontaneous speech, the number of utterances tend to be larger than the read speech one, but I feel that yours is still too large.
There might be some problems in the data preparation.

But, regardless of this, I'm expecting this happens, as our JSON file is quite redundant and consumes a lot of memory (but I decided this format, as it is easy to debug).
We may need to compress it (we have a lot of redundant field), using binary JSON format, or integrate it with HDF5.

**Comment by lilian0118** [comment]
@sw005320 , thanks for you kind reply.
Because I have 10,000 hours audio data, and I also run perturb_data_dir_speech_3way.sh on this dataset.
I also trained on Kaldi, I believe the data is all right.

**Comment by sw005320** [comment]
I see. Then, it happens. Thanks to try such large-scale data to ESPnet. This has to be solved then.

**Comment by sw005320** [comment]
> can we split big jsons to small piece? and run every small piece one by one?

Yes, this seems to be an easy solution for now.

**Comment by lixx0105** [comment]
hi @lilian0118 and @kamo-naoyuki 
I plan to test espnet on internal large volume dataset and I believe I'm going to face the same issue as you pointed out. 
After reading your comments, i think there're two problems here:
1. memory issue when try merge scp files into one json file
2. memory issue of loading a huge json file when we input this json file to asr train code

@kamo-naoyuki: problem 1 is solved by  your latest merge_scp2json.py, is it? 
@lilian0118 can you give some advice for problem 2?

thanks a lot.
