### ISSUE TITLE
Poor synthesis quality for an Indian English dataset.

### ISSUE THREAD

**Issue by anushaprakash90** [espnet/espnet#534]
Hi,

I used ESPNet's Tacotron code (ljspeech/tts1 folder) to build a TTS using ljspeech dataset. Speech synthesis quality was ok. I am now training Tacotron on an Indian English dataset. The dataset is of duration 8 hours and sampling frequency of wave files is 48KHz. After making necessary changes in run.sh, the code ran without errors with a batch size of 8 (to avoid memory issues). But the synthesis quality of wave files in eval/wav was very poor. I also reduced decoder attributes (dlayers=1, dunits=256) and ran the code. Synthesis quality was still poor.

Can you suggest if I need to modify any specific parameters (working with 48KHz) or is it a data insufficiency problem?

**Comment by kan-bayashi** [comment]
I’ve never tried 48k Hz setting, so I have no clear idea.ft
But I have some questions and suggestions:
- Have you ever checked the attention weights? Is it clear compared with LJspeech model?
   If there is not clear diagonal attention pattern, the model cannot generate speech.
   The point to check the training is success or not is that clear attention is appeared or not.
- In the case of 48k Hz, we should change feature extraction setting, especially `n_fft` and `n_shift`.
  In my experience, using a large shift make attention learning easier and faster.
- Also using big `reduction_factor` helps to learn attention.

**Comment by kan-bayashi** [comment]
I also recommend that at first, build 24k Hz setting with downsampled data in order to check that the reason of poor quality is comes from a small amount of training data.

**Comment by anushaprakash90** [comment]
Hi Tomoki,

Thanks for your reply. I will perform experiments as you suggested and see what happens. I checked the attention weights for the Indian English data. There is no clear attention at all.

I heard that you got ESPNet working for Japanese. If possible can you give me specifications about the dataset, like duration of data, sampling frequency, and specific parameters of the code that you tuned.

**Comment by kan-bayashi** [comment]
For Japanese TTS, we use JUST corpus (~10 hours, 48k Hz).
https://arxiv.org/pdf/1711.00354.pdf
It is general to perform resampling to 24k Hz or 22.05k Hz at first, (I’ve never seen 48k Hz setting E2E-TTS).
In some studies of Japanese E2E-TTS, the network setting is the same as original one, but using extra symbol about pronunciation is often used to improve the pronunciation.

**Comment by anushaprakash90** [comment]
I downsampled the data from 48 kHz to 24 kHz and trained the model. The synthesis quality is slightly better compared to the previous quality, but is still poor and attention is also not clear (attached). I have now increased the reduction factor to see if attention is captured.  A couple of questions:
1) What values did you change for feature extraction, especially n_fft and n_shift for a sampling rate of 24 kHz?
2) Did you change any network parameters to suit a smaller amount of data (10 hours versus 24 hours of ljspeech). For example, reducing the decoder layers and decoder units.

**Comment by kan-bayashi** [comment]
> 1.

I think in the case of 24kHz the same setting is OK (n_fft=1024, n_shift=256).

> 2.

Sorry, I have no idea about the network size.
I have tried to change only feature extraction, reduction_factor, and attention type.

BTW, how did you clean your transcription?
(In the case of ljspeech, the transcription is really clean)

**Comment by anushaprakash90** [comment]
The transcription was cleaned previously, by manual checking. Text is at the sentence level and contains few punctuation marks.

**Comment by kan-bayashi** [comment]
I see. 
I think it requires a lot of iterations to learn attention.
So maybe it is needed to set a large epochs than usual.

**Comment by kan-bayashi** [comment]
@anushaprakash90 

I and @takenori-y have tried to build several language datasets (Japanese, German, Italy). 
If you are still trying, maybe following tips will help you.

1. 48k setting can be trained with only 10 hours training data.
@takenori-y have made Japanese TTS recipe using JSUT dataset (#569), this recipe tries to build Japanese TTS model with 10 hours of 48k audios.
Without any change of network hyper parameters, we successfully trained the model.
You can listen to the sample [here](https://drive.google.com/open?id=1fEgS4-K4dtgVxwI4Pr7uOA1h4PE-zN7f).
Note that we convert all of the text into hiragana.

2. Trimming the silence parts at the beginning and the end of audio is important.
You can see the effect in #562.
If we combine the trimming and `forward_ta`, we can learn attention much faster.

**Comment by anushaprakash90** [comment]
@kan-bayashi,

Sorry for the delayed reply, I missed your post.

I am still working on this. I will try trimming silence at the beginning and end of the audio files and change to atype=forward_ta. But, I don't understand what attention_type is forward_ta?

**Comment by kan-bayashi** [comment]
`forward_ta` is Forward Attention with Transition Agent proposed in following paper.
https://arxiv.org/abs/1807.06736

**Comment by anushaprakash90** [comment]
Thanks I will go through the paper.

**Comment by anushaprakash90** [comment]
@kan-bayashi 

I was finally able to get it working for Indian English. Had somehow missed the fact that the text is case sensitive. We also cleaned up the data. Thanks a lot for your help.

**Comment by EsmaeilFarhang** [comment]
> For Japanese TTS, JUST corpus (~10 hours, 48k Hz) is often used.
> https://arxiv.org/pdf/1711.00354.pdf
> It is general to perform resampling to 24k Hz or 22.05k Hz at first, (I’ve never seen 48k Hz setting E2E-TTS).
> In some studies of Japanese E2E-TTS, the network setting is the same as original one, but they use extra symbol about pronunciation to improve the pronunciation.

HI,
Im trained transformer model in egs/just/tts1 config file with 11 hours data, and the result is so good   But there is still the problem of missing words, 
can I try fastspeech with use this model as a teacher mode? Have you tried the fstspeech model with Japanese data? Does the lack of data cause problems?

**Comment by kan-bayashi** [comment]
You can find some results.
https://github.com/espnet/espnet/blob/master/egs/jsut/tts1/RESULTS.md

**Comment by EsmaeilFarhang** [comment]
> You can find some results.
> https://github.com/espnet/espnet/blob/master/egs/jsut/tts1/RESULTS.md

thank you,
I'm trained fastspeech.v1 from egs/jsut for my data but only the first line of each paragraph has good sound quality. And the continuation of the paragraph is not qualitative.
(training with char base trans_type)
Which one config do you suggest?
Does the fastspeech.v4( Knowledge distillation) model supports the transformer as a teacher mode?

**Comment by kan-bayashi** [comment]
>  only the first line of each paragraph has good sound quality.

How long is your input sentence? For better quality, it is better to crop your paragraph into each sentence in decoding. And phoneme is better in the case of Japanese.

> Does the fastspeech.v4( Knowledge distillation) model supports the transformer as a teacher mode?

Yes. Please follow the procedure in egs/ljspeech/README.md.

**Comment by EsmaeilFarhang** [comment]
> > only the first line of each paragraph has good sound quality.
> 
> How long is your input sentence? For better quality, it is better to crop your paragraph into each sentence in decoding. And phoneme is better in the case of Japanese.
> 
> > Does the fastspeech.v4( Knowledge distillation) model supports the transformer as a teacher mode?
> 
> Yes. Please follow the procedure in egs/ljspeech/README.md.

thanks
