### ISSUE TITLE
How are the WER values obtained

### ISSUE THREAD

**Issue by SreeramGanji** [espnet/espnet#535]
Hi everyone
Sorry for asking a noob question, I am new to ESPNET.
If i understand it correctly, we are modelling characters throughout the ASR pipeline and thus it makes sense to obtain Character Error Rate as output. But I have noticed that we also get WER values in result.wrd.txt . How is the mapping from CER to WER in the toolkit? I would really appreciate if anybody can help me with the appropriate links.

Thanking you in advance.

**Comment by kan-bayashi** [comment]
In the case of English, the words in sentence are separated with <space>.
The target characters of character-based E2E model includes <space>, so we can easily convert the sequence of characters into that of words.
e.g., T H I S <space> I S <space> A <space> P E N . -> THIS IS A PEN.
