### ISSUE TITLE
KeyError: u'ilen' with the an4/asr1 setup

### ISSUE THREAD

**Issue by yonasdw** [espnet/espnet#536]
I’ve tried to run the ‘an4/asr1’ setup. While the data preparation and feature generation stages work fine, network training returns error as shown below. Tried to debug what KeyError: u'ilen'
is, but I didn’t fix it yet. Do you have any idea? thanks in advance!

/espnet/egs/an4/asr1$ sudo ./run.sh --ngpu 1 --backend pytorch
stage -1: Data Download
local/download_and_untar.sh: an4 directory already exists in ./downloads
stage 0: Data preparation
stage 1: Feature Generation
steps/make_fbank_pitch.sh --cmd run.pl --mem 2G --nj 8 --write_utt2num_frames true data/test exp/make_fbank/test fbank
steps/make_fbank_pitch.sh: moving data/test/feats.scp to data/test/.backup
Checking data/test/text ...
--> reading data/test/text
--> text seems to be UTF-8 or ASCII, checking whitespaces
--> text contains only allowed whitespaces
utils/validate_data_dir.sh: Successfully validated data-directory data/test
steps/make_fbank_pitch.sh: [info]: no segments file exists: assuming wav.scp indexed by utterance.
Succeeded creating filterbank & pitch features for test
steps/make_fbank_pitch.sh --cmd run.pl --mem 2G --nj 8 --write_utt2num_frames true data/train exp/make_fbank/train fbank
steps/make_fbank_pitch.sh: moving data/train/feats.scp to data/train/.backup
Checking data/train/text ...
--> reading data/train/text
--> text seems to be UTF-8 or ASCII, checking whitespaces
--> text contains only allowed whitespaces
utils/validate_data_dir.sh: Successfully validated data-directory data/train
steps/make_fbank_pitch.sh: [info]: no segments file exists: assuming wav.scp indexed by utterance.
Succeeded creating filterbank & pitch features for train
utils/subset_data_dir.sh: reducing #utt from 948 to 100
utils/subset_data_dir.sh: reducing #utt from 948 to 848
compute-cmvn-stats scp:data/train_nodev/feats.scp data/train_nodev/cmvn.ark 
LOG (compute-cmvn-stats[5.3.24~1392-c948]:main():compute-cmvn-stats.cc:168) Wrote global CMVN stats to data/train_nodev/cmvn.ark
LOG (compute-cmvn-stats[5.3.24~1392-c948]:main():compute-cmvn-stats.cc:171) Done accumulating CMVN stats for 848 utterances; 0 had errors.
dictionary: data/lang_1char/train_nodev_units.txt
stage 2: Dictionary and Json Data Preparation
28 data/lang_1char/train_nodev_units.txt
cp: cannot stat 'data/train_nodev/utt2num_frames': No such file or directory
Traceback (most recent call last):
  File "/home/yonasd/1111/espnet/egs/an4/asr1/../../../utils/mergejson.py", line 63, in <module>
    in_dic[unicode('shape', 'utf-8')] = (int(dic[unicode('ilen', 'utf-8')]), int(dic[unicode('idim', 'utf-8')]))
KeyError: u'ilen'
cp: cannot stat 'data/train_dev/utt2num_frames': No such file or directory
Traceback (most recent call last):
  File "/home/yonasd/1111/espnet/egs/an4/asr1/../../../utils/mergejson.py", line 63, in <module>
    in_dic[unicode('shape', 'utf-8')] = (int(dic[unicode('ilen', 'utf-8')]), int(dic[unicode('idim', 'utf-8')]))
KeyError: u'ilen'
cp: cannot stat 'data/train_dev/utt2num_frames': No such file or directory
Traceback (most recent call last):
  File "/home/yonasd/1111/espnet/egs/an4/asr1/../../../utils/mergejson.py", line 63, in <module>
    in_dic[unicode('shape', 'utf-8')] = (int(dic[unicode('ilen', 'utf-8')]), int(dic[unicode('idim', 'utf-8')]))
KeyError: u'ilen'
stage 3: Network Training
run.pl: job failed, log is in exp/train_nodev_pytorch_blstmp_e4_subsample1_2_2_1_1_unit320_proj320_d1_unit300_location_aconvc10_aconvf100_mtlalpha0.5_adadelta_sampprob0.0_bs30_mli800_mlo150/train.log

**Comment by yonasdw** [comment]
The log says:
# asr_train.py --ngpu 1 --backend pytorch --outdir exp/train_nodev_pytorch_blstmp_e4_subsample1_2_2_1_1_unit320_proj320_d1_unit300_location_aconvc10_aconvf100_mtlalpha0.5_adadelta_sampprob0.0_bs30_mli800$
# Started at Thu Jan 10 19:10:46 CET 2019
#
2019-01-10 19:10:46,424 (asr_train:187) WARNING: CUDA_VISIBLE_DEVICES is not set.
2019-01-10 19:10:46,424 (asr_train:193) INFO: python path = (None)
2019-01-10 19:10:46,424 (asr_train:196) INFO: random seed = 1
2019-01-10 19:10:46,425 (asr_train:213) INFO: backend = pytorch
/home/yonasd/1111/espnet/tools/venv/local/lib/python2.7/site-packages/chainer/backends/cuda.py:98: UserWarning: cuDNN is not enabled.
Please reinstall CuPy after you install cudnn
(see https://docs-cupy.chainer.org/en/stable/install.html#install-cudnn).
  'cuDNN is not enabled.\n'
2019-01-10 19:10:46,770 (asr_pytorch:179) INFO: torch type check is disabled
Traceback (most recent call last):
  File "/home/yonasd/1111/espnet/egs/an4/asr1/../../../espnet/bin/asr_train.py", line 225, in <module>
    main()
  File "/home/yonasd/1111/espnet/egs/an4/asr1/../../../espnet/bin/asr_train.py", line 219, in main
    train(args)
  File "/home/yonasd/1111/espnet/espnet/asr/asr_pytorch.py", line 193, in train
    valid_json = json.load(f)['utts']
  File "/usr/lib/python2.7/json/__init__.py", line 291, in load
    **kw)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
# Accounting: time=1 threads=1
# Ended (code 1) at Thu Jan 10 19:10:47 CET 2019, elapsed time 1 seconds

**Comment by sw005320** [comment]
I just tested it but it's working in my environment. I'm curious about why it says `cp: cannot stat 'data/train_nodev/utt2num_frames': No such file or directory`, as I did not observe this message.
