### ISSUE TITLE
conformer transducer ASR system without CTC loss

### ISSUE THREAD

**Issue by wyunj** [espnet/espnet#5367]
Hi!

I want to ask whether CTC loss greatly improves conformer transducer ASR system on large data sets? I see that the default weight of CTC loss on Librispeech 960 dataset is 0.3. So how does the conformer transducer ASR system's performance without CTC loss compare to the default recipe?

Thanks a lot！

**Comment by b-flo** [comment]
Hi,

For Librispeech-960, auxiliary tasks improved the WER by 0.2/0.3% IIRC? It acts as a soft regularization and may also help to reduce the number of emitted symbols at each timestep. It's less useful with large datasets though.

**Comment by b-flo** [comment]
Closing the issue but feel free to ask if you have follow-up questions.
