### ISSUE TITLE
Babel datasets error

### ISSUE THREAD

**Issue by yonasdw** [espnet/espnet#537]
I’m working on babel datasets to create a network trained on Amharic and Swahili and tests on both. I’ve added a lexicon for both languages and edited the lexicon related paths in the lang.conf file in /espnet/egs/babel/asr1/conf. 

./run.sh --langs "307 202" --recog "307 202" --ngpu 1 --backend pytorch, complains “ls: cannot access '/home/yonasd/1111/espnet/egs/babel/AMHSWA/data/307/data/raw_train_data/transcription/*.txt': No such file or directory” for both languages. I guess the script run.sh assumed to download both the audio and the transcription files. Did I miss anything? Thanks in advance!

Here is the complete log:
stage 0: Setting up individual languages
Stage 0: Setup Language Specific Directories
 --------------------------------------------
Languagues: 307 202
---------------------------------------------------------------------
---------------------------------------------------------------------
Preparing acoustic training lists in data/train on Fri Jan 11 05:23:34 CET 2019
---------------------------------------------------------------------
Preparing acoustic training lists in data/train on Fri Jan 11 05:23:34 CET 2019
---------------------------------------------------------------------
local/prepare_acoustic_training_data.pl --vocab /home/user/1111/kaldi/lang/dict/lexicon.txt --fragmentMarkers -*~ /home/yonasd/1111/espnet/egs/babel/AMHSWA/data/307/data/raw_train_data data/train.tmp
local/prepare_acoustic_training_data.pl: /home/yonasd/1111/espnet/egs/babel/AMHSWA/data/307/data/raw_train_data data/train.tmp
	Limiting transcriptions to words in /home/user/1111/kaldi/lang/dict/lexicon.txt
	Mapping OOV tokens to "<unk>"
	if they remain OOV even after removing [-*~] from either end
local/prepare_acoustic_training_data.pl --vocab /home/user/1111/ALFFA_PUBLIC/ASR/SWAHILI/lang/lexicon.txt --fragmentMarkers -*~ /home/yonasd/1111/espnet/egs/babel/AMHSWA/data/202/data/raw_train_data data/train.tmp
local/prepare_acoustic_training_data.pl: /home/yonasd/1111/espnet/egs/babel/AMHSWA/data/202/data/raw_train_data data/train.tmp
	Limiting transcriptions to words in /home/user/1111/ALFFA_PUBLIC/ASR/SWAHILI/lang/lexicon.txt
	Mapping OOV tokens to "<unk>"
	if they remain OOV even after removing [-*~] from either end
Read 51364 unique words from /home/user/1111/kaldi/lang/dict/lexicon.txt
ls: cannot access '/home/yonasd/1111/espnet/egs/babel/AMHSWA/data/307/data/raw_train_data/transcription/*.txt': No such file or directory
local/prepare_acoustic_training_data.pl ERROR: No .txt files found /home/yonasd/1111/espnet/egs/babel/AMHSWA/data/307/data/raw_train_data/transcription
---------------------------------------------------------------------
Preparing acoustic training lists in data/train on Fri Jan 11 05:23:34 CET 2019
---------------------------------------------------------------------
local/prepare_acoustic_training_data.pl --vocab /home/user/1111/kaldi/lang/dict/lexicon.txt --fragmentMarkers -*~ /home/yonasd/1111/espnet/egs/babel/AMHSWA/data/307/data/raw_dev10h_data data/dev10h.pem
local/prepare_acoustic_training_data.pl: /home/yonasd/1111/espnet/egs/babel/AMHSWA/data/307/data/raw_dev10h_data data/dev10h.pem
	Limiting transcriptions to words in /home/user/1111/kaldi/lang/dict/lexicon.txt
	Mapping OOV tokens to "<unk>"
	if they remain OOV even after removing [-*~] from either end
Read 81223 unique words from /home/user/1111/ALFFA_PUBLIC/ASR/SWAHILI/lang/lexicon.txt
ls: cannot access '/home/yonasd/1111/espnet/egs/babel/AMHSWA/data/202/data/raw_train_data/transcription/*.txt': No such file or directory
local/prepare_acoustic_training_data.pl ERROR: No .txt files found /home/yonasd/1111/espnet/egs/babel/AMHSWA/data/202/data/raw_train_data/transcription
---------------------------------------------------------------------
Preparing acoustic training lists in data/train on Fri Jan 11 05:23:34 CET 2019
---------------------------------------------------------------------
local/prepare_acoustic_training_data.pl --vocab /home/user/1111/ALFFA_PUBLIC/ASR/SWAHILI/lang/lexicon.txt --fragmentMarkers -*~ /home/yonasd/1111/espnet/egs/babel/AMHSWA/data/202/data/raw_dev10h_data data/dev10h.pem
local/prepare_acoustic_training_data.pl: /home/yonasd/1111/espnet/egs/babel/AMHSWA/data/202/data/raw_dev10h_data data/dev10h.pem
	Limiting transcriptions to words in /home/user/1111/ALFFA_PUBLIC/ASR/SWAHILI/lang/lexicon.txt
	Mapping OOV tokens to "<unk>"
	if they remain OOV even after removing [-*~] from either end
Read 51364 unique words from /home/user/1111/kaldi/lang/dict/lexicon.txt
ls: cannot access '/home/yonasd/1111/espnet/egs/babel/AMHSWA/data/307/data/raw_dev10h_data/transcription/*.txt': No such file or directory
local/prepare_acoustic_training_data.pl ERROR: No .txt files found /home/yonasd/1111/espnet/egs/babel/AMHSWA/data/307/data/raw_dev10h_data/transcription
cat: data/train.tmp/segments: No such file or directory
subset_data_dir.sh: no such file data/train.tmp/utt2spk
awk: fatal: cannot open file `data/train_dev/utt2spk' for reading (No such file or directory)
awk: fatal: cannot open file `data/train.tmp/utt2spk' for reading (No such file or directory)
subset_data_dir.sh: no such file data/train.tmp/utt2spk
Prepend 307 to data dir
copy_data_dir.sh: no such file data/train/utt2spk
copy_data_dir.sh: no such file data/train_dev/utt2spk
copy_data_dir.sh: no such file data/dev10h.pem/utt2spk
Read 81223 unique words from /home/user/1111/ALFFA_PUBLIC/ASR/SWAHILI/lang/lexicon.txt
ls: cannot access '/home/yonasd/1111/espnet/egs/babel/AMHSWA/data/202/data/raw_dev10h_data/transcription/*.txt': No such file or directory
local/prepare_acoustic_training_data.pl ERROR: No .txt files found /home/yonasd/1111/espnet/egs/babel/AMHSWA/data/202/data/raw_dev10h_data/transcription
cat: data/train.tmp/segments: No such file or directory
subset_data_dir.sh: no such file data/train.tmp/utt2spk
awk: fatal: cannot open file `data/train_dev/utt2spk' for reading (No such file or directory)
awk: fatal: cannot open file `data/train.tmp/utt2spk' for reading (No such file or directory)
subset_data_dir.sh: no such file data/train.tmp/utt2spk
Prepend 202 to data dir
copy_data_dir.sh: no such file data/train/utt2spk
copy_data_dir.sh: no such file data/train_dev/utt2spk
copy_data_dir.sh: no such file data/dev10h.pem/utt2spk
./utils/combine_data.sh data/train data/202/data/train_202 data/307/data/train_307
./utils/combine_data.sh: no such file data/202/data/train_202/utt2spk

**Comment by sw005320** [comment]
Did you get the Babel data (e.g., Swahili https://catalog.ldc.upenn.edu/LDC2017S05), and correctly set the paths in https://github.com/espnet/espnet/blob/master/egs/babel/asr1/conf/lang.conf?

**Comment by yonasdw** [comment]
thanks Shinji! As I couldn't find the Amharic corpus in both LDC and IARPA, I tried to use the datasets available in http://www.openslr.org/25/ and set all the necessary paths in lang.conf. But sudo ./run.sh --langs "307 202" --recog "307 202" --ngpu 1 --backend pytorch, keeps failing. Have you tried the setup with non-Babel languages? Or do you've any idea where I could get the Amharic (IARPA-babel307b-v1.0b)?

thanks inadvance!



stage 0: Setting up individual languages
Stage 0: Setup Language Specific Directories
 --------------------------------------------
Languagues: 307 202
First command-line parameter to subset_scp.pl must be an integer, got "0" at /home/user/1111/kaldi-trunk/kaldi/egs/wsj/s5/utils/subset_scp.pl line 55.
First command-line parameter to subset_scp.pl must be an integer, got "0" at /home/user/1111/kaldi-trunk/kaldi/egs/wsj/s5/utils/subset_scp.pl line 55.
./utils/subset_data_dir.sh: reducing #utt from 0 to 0
Prepend 202 to data dir
./utils/subset_data_dir.sh: reducing #utt from 0 to 0
Prepend 307 to data dir
./utils/copy_data_dir.sh: copied data from data/train to data/train_202
./utils/copy_data_dir.sh: file utt2uniq exists in dest data/train_202 but not in src data/train.  Moving it to
 ... data/train_202/.backup/utt2uniq
./utils/copy_data_dir.sh: copied data from data/train to data/train_307
./utils/copy_data_dir.sh: file utt2uniq exists in dest data/train_307 but not in src data/train.  Moving it to
 ... data/train_307/.backup/utt2uniq
/home/user/1111/kaldi-trunk/kaldi/egs/wsj/s5/utils/validate_data_dir.sh: empty file spk2utt
/home/user/1111/kaldi-trunk/kaldi/egs/wsj/s5/utils/validate_data_dir.sh: empty file spk2utt
apply_map.pl: undefined key 16k-emission_swahili_05h30_-_06h00_tu_20101124_part001g in data/dev_202/utt_map
apply_map.pl: undefined key 01_d501021 in data/dev_307/utt_map
./utils/copy_data_dir.sh: copied data from data/dev10h.pem to data/eval_202
./utils/copy_data_dir.sh: file utt2uniq exists in dest data/eval_202 but not in src data/dev10h.pem.  Moving it to
 ... data/eval_202/.backup/utt2uniq
/home/user/1111/kaldi-trunk/kaldi/egs/wsj/s5/utils/validate_data_dir.sh: empty file spk2utt
./utils/copy_data_dir.sh: copied data from data/dev10h.pem to data/eval_307
./utils/copy_data_dir.sh: file utt2uniq exists in dest data/eval_307 but not in src data/dev10h.pem.  Moving it to
 ... data/eval_307/.backup/utt2uniq
/home/user/1111/kaldi-trunk/kaldi/egs/wsj/s5/utils/validate_data_dir.sh: empty file spk2utt
./utils/combine_data.sh data/train data/202/data/train_202 data/307/data/train_307
./utils/combine_data.sh [info]: not combining utt2uniq as it does not exist
./utils/combine_data.sh: combined segments
./utils/combine_data.sh: combined utt2spk
./utils/combine_data.sh [info]: not combining utt2lang as it does not exist
./utils/combine_data.sh [info]: not combining utt2dur as it does not exist
./utils/combine_data.sh [info]: not combining feats.scp as it does not exist
./utils/combine_data.sh: combined text
./utils/combine_data.sh [info]: not combining cmvn.scp as it does not exist
./utils/combine_data.sh [info]: not combining vad.scp as it does not exist
./utils/combine_data.sh [info]: not combining reco2file_and_channel as it does not exist
./utils/combine_data.sh: combined wav.scp
./utils/combine_data.sh [info]: not combining spk2gender as it does not exist
Empty list of recordings (bad file data/train/segments)?

**Comment by sw005320** [comment]
I haven't tried it. @creatorscan, @m-wiesner, do you have some comments?

**Comment by creatorscan** [comment]
@sw005320 , Martin has replied to  @yonasdw  by email to obtain Amharic corpus. Hope it solves the issue. Thanks.

**Comment by m-wiesner** [comment]
I think what you'll want to do is write a separate ./local/prepare_data.sh for the new set of data you are hoping to combine. Check local/setup_languages.sh to see what sorts of directories are assumed to be created in local/prepare_data.sh so that your script conforms to that.

We really only wrote the prep script with the BABEL languages in mind and it will require more tweaking than just setting paths to add in new datasets.

Best of luck!
