### ISSUE TITLE
 ASR stage 13 scoring issue : sclite not found

### ISSUE THREAD

**Issue by Lhx94As** [espnet/espnet#5373]
**Describe your question**
I tried the SEAME recipe and saw:
2023-07-26T14:39:28 (asr.sh:1293:main) Stage 13: Scoring
/home/hexin/anaconda3/envs/espnet/bin/python3 /home/hexin/Desktop/espnet/espnet2/bin/tokenize_text.py -f 2- --input - --output - --token_type char --non_linguistic_symbols none --remove_non_linguistic_symbols true --cleaner none
/home/hexin/anaconda3/envs/espnet/bin/python3 /home/hexin/Desktop/espnet/espnet2/bin/tokenize_text.py -f 2- --input - --output - --token_type char --non_linguistic_symbols none --remove_non_linguistic_symbols true
./asr.sh: line 1389: sclite: command not found

I then manually installed sctk via the espnet installer (install_sctk.sh), but:

make[2]: Leaving directory '/home/hexin/Desktop/espnet/tools/sctk-20159b5/src/sclite'
(cd rfilter1 && if test -f makefile ; then make install ; fi)
make[2]: Entering directory '/home/hexin/Desktop/espnet/tools/sctk-20159b5/src/rfilter1'
install rfilter1 /home/hexin/Desktop/espnet/tools/sctk/bin
make[2]: install: Command not found
make[2]: *** [makefile:34: install] Error 127
make[2]: Leaving directory '/home/hexin/Desktop/espnet/tools/sctk-20159b5/src/rfilter1'
make[1]: *** [makefile:14: install] Error 2
make[1]: Leaving directory '/home/hexin/Desktop/espnet/tools/sctk-20159b5/src'
make: *** [makefile:20: install] Error 2

Could you please help me with this issue?

**Comment by sw005320** [comment]
What OS are you using?
I think `make` is not installed.
Please check https://espnet.github.io/espnet/installation.html

**Comment by kamo-naoyuki** [comment]
> make[2]: install: Command not found

You don't have `install` command, but Linux should have the command in `/usr/bin`. Your system is perhaps broken.

**Comment by Lhx94As** [comment]
> What OS are you using? I think `make` is not installed. Please check https://espnet.github.io/espnet/installation.html

I am using Linux. I checked my workstation, and I think @kamo-naoyuki is correct that this is an issue with my workstation.

**Comment by tahmaz** [comment]
Go to tools directory(espnet/tools/) then run ./installers//install_sctk.sh
installed files must be in tools
