### ISSUE TITLE
torch.inf is not available on old pytorch versions

### ISSUE THREAD

**Issue by tjysdsg** [espnet/espnet#5374]
**Describe the bug**

[This line](https://github.com/espnet/espnet/blob/a7996593d466d10b79c973b7d2a4b23dc2a8d41b/espnet2/schedulers/warmup_reducelronplateau.py#L5) imports inf from pytorch, but it is not available on old pytorch versions

**Basic environments:**

- python version: `3.9.12 (main, Apr  5 2022, 06:56:58)  [GCC 7.5.0]`
- espnet version: `espnet 202304`
- pytorch version: `pytorch 1.8.1`

Please ignore this issue if pytorch<1.10 support is dropped.

**Comment by kamo-naoyuki** [comment]
Yes, pytorch<1.10 is already  dropped (see  https://github.com/espnet/espnet#readme)
