### ISSUE TITLE
Question about usage of espnet docker image

### ISSUE THREAD

**Issue by hiranoyu0830** [espnet/espnet#5405]
I'm trying to use the ESPnet docker image to avoid kaldi installation.
Then I plan to use espnet1 to do some experiments.

I run following command ,
```shell
$ cd docker
$./build.sh local 10.0
``` 
but it returned this error.
```shell
2023-08-11T14:10:22 (build.sh:289:main) Using Docker Ver.23.0.6
2023-08-11T14:10:22 (build.sh:124:build_local) Building docker container: base image, and image for cpu
2023-08-11T14:10:23 (build.sh:130:build_local) Reconstructing the local repository from the last commit
2023-08-11T14:10:25 (build.sh:146:build_local) building ESPnet CPU Image with ubuntu:22.04
[+] Building 0.0s (0/0)                                                                                                                         
ERROR: could not find prebuilt/local: stat prebuilt/local: no such file or directory
``` 
I checked the prebuilt directory, and I couldn't find any file named "local ".
Additionally,  I have no idea what prebuilt is. 

How can I solve this error?
Thank you.

**Comment by sw005320** [comment]
@Fhrozen, can you answer it for me?

**Comment by Fhrozen** [comment]
@hiranoyu0830, I am fixing the issue for local builds. 
FYI, for Cuda local builds, the command is: `./build.sh --build-ver gpu local`
Currently, the local builds are supporting CUDA 11.7 only.
I am checking the correct way for supporting other versions of CUDA, but it may take a little longer.

**Comment by hiranoyu0830** [comment]
Thank you so much @Fhrozen -san!
Thanks to the command and codes you provided, I could successfully build my container.

> Currently, the local builds are supporting CUDA 11.7 only.

I got it. So, does it mean the docker image that contains a kaldi installation is not currently available?

**Comment by Fhrozen** [comment]
> I got it. So, does it mean the docker image that contains a kaldi installation is not currently available?

What do you mean?
All the images contain the kaldi installation.

**Comment by hiranoyu0830** [comment]
I thought only the image "espnet/espnet:runtime-latest" contains the kaldi installation. 
Probably, that was my misunderstanding. 

Anyway, I could run some examples using espnet1, and it's clear now.
Thank you for answering my question.

**Comment by Fhrozen** [comment]
>I thought only the image "espnet/espnet:runtime-latest" contains the kaldi installation.
Probably, that was my misunderstanding.

Ahh, if you check the dockerfile, the runtime is the only one that has the installation of kaldi (code). But, the final images (cpu/gpu/cuda) uses as base the runtime images, so all of the images have the installation. ;)

**Comment by hardmstar** [comment]
kaldi is in /opt/ folder of the image
