### ISSUE TITLE
type of argument "text" must be one of (Dict[str, Tuple], torch.Tensor, numpy.ndarray); got str instead

### ISSUE THREAD

**Issue by AbdullahMustafa040** [espnet/espnet#5422]
I am trying to use the SingingGenerate class from the espnet2.bin.svs_inference module to generate a singing voice for some text. However, I am getting a TypeError with the message "type of argument "text" must be one of (Dict[str, Tuple], torch.Tensor, numpy.ndarray); got str instead". Here is my code:

```python
import soundfile
from espnet2.bin.svs_inference import SingingGenerate
import torch
import numpy as np
svs = SingingGenerate("/content/opencpop_svs_train_visinger2_raw_phn_None_zh_latest/exp/44k/svs_train_visinger2_raw_phn_None_zh/config.yaml", "/content/opencpop_svs_train_visinger2_raw_phn_None_zh_latest/exp/44k/svs_train_visinger2_raw_phn_None_zh/100epoch.pth")
text = 'hello world'


wav = svs(text)[0]
soundfile.write("out.wav", wav.numpy(), svs.fs, "PCM_16")
```
And here is the error message I am getting:
---------------------------------------------------------------------------
```TypeError                                 Traceback (most recent call last)
<ipython-input-26-ed572d25f986> in <cell line: 10>()
      8 
      9 
---> 10 wav = svs(text)[0]
     11 soundfile.write("out.wav", wav.numpy(), svs.fs, "PCM_16")

2 frames
/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py in decorate_context(*args, **kwargs)
    113     def decorate_context(*args, **kwargs):
    114         with ctx_factory():
--> 115             return func(*args, **kwargs)
    116 
    117     return decorate_context

/usr/local/lib/python3.10/dist-packages/espnet2/bin/svs_inference.py in __call__(self, text, singing, label, midi, duration_phn, duration_ruled_phn, duration_syb, phn_cnt, slur, pitch, energy, spembs, sids, lids, decode_conf)
    136         decode_conf: Optional[Dict[str, Any]] = None,
    137     ):
--> 138         assert check_argument_types()
    139 
    140         # check inputs

/usr/local/lib/python3.10/dist-packages/typeguard/__init__.py in check_argument_types(memo)
    873                 check_type(description, value, expected_type, memo)
    874             except TypeError as exc:  # suppress unnecessarily long tracebacks
--> 875                 raise TypeError(*exc.args) from None
    876 
    877     return True

TypeError: type of argument "text" must be one of (Dict[str, Tuple], torch.Tensor, numpy.ndarray); got str instead
```
I have checked the documentation and it seems that passing a string as the text argument should work. Here is an example from the documentation:

```Examples:
    >>> import soundfile
    >>> svs = SingingGenerate("config.yml", "model.pth")
    >>> wav = svs("Hello World")[0]
    >>> soundfile.write("out.wav", wav.numpy(), svs.fs, "PCM_16")
```

Is there anything else you would like to know? 😊

**Comment by AbdullahMustafa040** [comment]
@ftshijt hey i am waiting for response!!!

**Comment by ftshijt** [comment]
Hi, thanks for your interest in the toolkit. I think the documentation is kind of wrong as it was inherited from tts's. We will be fixing that soon!

For singing synthesis, we would expect the music score and corresponding lyrics for synthesis. The correct inference procedure is at:
https://github.com/espnet/espnet/blob/master/espnet2/bin/svs_inference.py#L419
(where it would take input as indicated in the function at https://github.com/espnet/espnet/blob/master/espnet2/svs/espnet_model.py#L451)

**Comment by ftshijt** [comment]
Umm, I do not think we have documentation saying that text only would be ok for the scenario, Could you kindly let me know where you find the doc for that?

**Comment by AbdullahMustafa040** [comment]
I truly appreciate your response and the clarifications you've provided regarding the toolkit and singing synthesis.

**Comment by AbdullahMustafa040** [comment]
In reference to your previous message:

Commercial Use: I'm seeking clarification on whether the toolkit and its singing synthesis functionality are suitable for commercial use. If you could provide insights into any licensing considerations related to commercial applications, that would be extremely valuable.

Music Score and Lyrics: Your explanation about the necessity of music scores and corresponding lyrics for synthesis was enlightening. Could you recommend any preferred sources or datasets where I can access these music scores and lyrics for my experimentation? If there's a particular dataset that the toolkit developers suggest, I'd be grateful for the information.

**Comment by AbdullahMustafa040** [comment]
Creating Custom input: I'm intrigued by the possibility of creating my own input for singing synthesis. Could you provide some pointers or resources that would help me get started with creating custom inputs? It would be wonderful to learn more about this aspect of the toolkit.

Best Practices and Models: In your experience, what would be the best approach or model for creating music from lyrics using the toolkit? Are there any specific procedures or techniques that you would recommend for someone starting out? Any insights you can provide would be invaluable.

**Comment by ftshijt** [comment]
> In reference to your previous message:
> 
> Commercial Use: I'm seeking clarification on whether the toolkit and its singing synthesis functionality are suitable for commercial use. If you could provide insights into any licensing considerations related to commercial applications, that would be extremely valuable.
> 
> Music Score and Lyrics: Your explanation about the necessity of music scores and corresponding lyrics for synthesis was enlightening. Could you recommend any preferred sources or datasets where I can access these music scores and lyrics for my experimentation? If there's a particular dataset that the toolkit developers suggest, I'd be grateful for the information.

The toolkit itself is OK for commercial use (we are under Apache license). However, the model and data might not be commercially granted, given the license of the dataset. I would recommend you to check the detailed license of the dataset or contact the creator for more guidance. As for us, we probably cannot get to offer any help regarding that.

We usually first test our models at Opencpop (https://github.com/espnet/espnet/tree/master/egs2/opencpop/svs1) and Ofuton (https://github.com/espnet/espnet/tree/master/egs2/ofuton_p_utagoe_db/svs1) as two well-contructed datasets. The link I provide should include the recipe to train the model.

We also have a general documentation maintained at https://github.com/espnet/espnet/tree/master/egs2/TEMPLATE/svs1#readme

**Comment by ftshijt** [comment]
> Creating Custom input: I'm intrigued by the possibility of creating my own input for singing synthesis. Could you provide some pointers or resources that would help me get started with creating custom inputs? It would be wonderful to learn more about this aspect of the toolkit.
> 
> Best Practices and Models: In your experience, what would be the best approach or model for creating music from lyrics using the toolkit? Are there any specific procedures or techniques that you would recommend for someone starting out? Any insights you can provide would be invaluable.

For custom input, we have some instructions here https://github.com/espnet/espnet/tree/master/egs2/TEMPLATE/svs1#1-database-dependent-data-preparation, but you may also refer to our existing recipe on public datasets.

For using the framework, I would recommend you go through a recipe to get to know every stage including data preparation, training, inference, (possibly) evaluation.

**Comment by ftshijt** [comment]
> > Umm, I do not think we have documentation saying that text only would be ok for the scenario, Could you kindly let me know where you find the doc for that?
> 
> https://espnet.github.io/espnet/_gen/espnet2.bin.html#espnet2-bin-svs-inference-1

I see. It is indeed problematic, I will fix that soon. Thanks for noting that.

**Comment by AbdullahMustafa040** [comment]
@ftshijt  Do these models work in English or were they made for Chinese?”

**Comment by ftshijt** [comment]
Opencpop is for Mandarin, while Ofuton is for Japanese. Apology, but we do not have a good source of English dataset yet. If you have any recommendations, please let us know. We would want to support more languages if possible

**Comment by AbdullahMustafa040** [comment]
so in espnet lyrics to song  is not possible? i was searching on this from last three days!!.

**Comment by ftshijt** [comment]
Not possible (and I believe no other toolkits can do it if you do not provide related melody)

**Comment by AbdullahMustafa040** [comment]
what does mean by melody.


companies who do this(song to lyrics):
uberduck.ai
https://www.voicemod.net/text-to-song/
https://www.youtube.com/watch?v=zRjLFFU3INg&pp=ygUgdHQgc2luZ2luZyB2b2l2ZSBzeW50aGVzaXMgY29sYWI%3D

**Comment by ftshijt** [comment]
If you check the input of any of the systems you provide, it does not only input a text, but a real-song to provide melodies. In that case, you can get to know the melody and text at least (additional alignment with melody and lyrics are needed). But still, they are not "text-to-song/lyric-to-song", but instead "text+melody -> song

**Comment by AbdullahMustafa040** [comment]
Can you suggest any English models for the combination of 'text+melody -> song'? I have listed some, but I'm not sure if they work in English:

- ESPnet
- Diffsinger
- NNSVS
- MLP_Singer
- Muskit

Are there any others that you can suggest and that work in English?

**Comment by ftshijt** [comment]
Per my understanding, none of the above toolkits support good English synthesizers. Muskits, which we had been working on, has a CSD recipe with English voices, but the quality of the dataset is not very good, resulting in bad quality singing voices.

**Comment by AbdullahMustafa040** [comment]
Ok thanks sir @ftshijt Nice to talk with you.

**Comment by ftshijt** [comment]
If you just want to play for fun, you may try ACEStudio for singing synthesis (they have some support for  English voice) But their tools are not good for massive production or API, mostly for single-song production.

**Comment by AbdullahMustafa040** [comment]
My main objective was to make a service/feature like uberduck(lyric+melody -> song) and add in my app.

**Comment by AbdullahMustafa040** [comment]
But thanks you saving my 3 more day to put effort in that open-source repository.
