### ISSUE TITLE
Why is gelu missing in cgMLP module?

### ISSUE THREAD

**Issue by lawlict** [espnet/espnet#5435]
task: ASR
code: https://github.com/espnet/espnet/blob/master/espnet2/asr/layers/cgmlp.py#L84

As described, I found that there is the ```gelu``` activation function in the cgMLP paper, but not in espnet's implementation. Is there any consideration?
<img width="1298" alt="image" src="https://github.com/espnet/espnet/assets/35951198/85015bfc-3a70-4bb5-bf65-58a64dd8473d">

**Comment by sw005320** [comment]
Thanks for the question.
@pyf98, can you answer it?

**Comment by lawlict** [comment]
> Thanks for the question. @pyf98, can you answer it?

Sorry for my carelessness. There is `gelu` but I missed it.
