### ISSUE TITLE
About data acquisition in CSJ training and evaluation

### ISSUE THREAD

**Issue by underdogliu** [espnet/espnet#5442]
**Describe your question**

Task: ASR
Recipe: CSJ

Hi all and thanks for the amazing work! I am now working on some related ASR experiments using CSJ. While investigating the dataset, I have an out-of-curiosity question: why the lecture sessions start with "S" are not included in training? I have listened to some of them and found they are in good quality. And according to the metadata, they have transcriptions and do not overlap with the real lecures (starting with "A") in terms of speakers.

I do found them in 

I have referred to the paper indicated in the original Kaldi repo [1] and related preparation script, but cannot find the answer.

As one of the authors of the kaldi repo and [1], I wonder if @sw005320 can kindly recall the reason. Thanks in advance!

[1] https://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=7404852

**Comment by sw005320** [comment]
Thanks for pointing out the issue.
I think "A" only and all are often used setups, and we should support both.

BTW, I thought that the current recipe included all data (e.g., https://github.com/espnet/espnet/blob/master/egs/csj/asr1/local/csj_data_prep.sh#L39).
Can you identify where the subset is created?

**Comment by underdogliu** [comment]
@sw005320 Thanks a lot for your answer! Yes I confirm that we have 2672 speakers from both "real" and "simulated" lectures.
I think I might be only using those two for training. In earlier experiments, I think due to inheritance from kaldi, I used the old script. Sorry for my mistake and potential confusions.
