### ISSUE TITLE
Query based on computing statistics.

### ISSUE THREAD

**Issue by Naramkeshav59** [espnet/espnet#5446]
I have gone through the [documentation](https://espnet.github.io/espnet/notebook/tts_cli.html?highlight=stage#:~:text=stage%20%2D1%3A%20Download,using%20Griffin%2DLim.) of espnet where I have found these :

stage -1: Download data if the data is available online.

stage 0: Prepare data to make kaldi-stype data directory.

stage 1: Extract feature vector, calculate statistics, and perform normalization.

stage 2: Prepare a dictionary and make json files for training.

stage 3: Train the E2E-TTS network.

stage 4: Decode mel-spectrogram using the trained network.

stage 5: Generate a waveform from a generated mel-spectrogram using Griffin-Lim.

Stages " -1" and " 0" are not needed for me because I have preprocessed the data into kaldi format.

I have started the process from stage 1 and ended at stage 13 as given in "run.sh", to reproduce:
```bash
# !/usr/bin/env bash
# Set bash to 'debug' mode, it will exit on :
# -e 'error', -u 'undefined variable', -o ... 'error in pipeline', -x 'print commands',
set -e
set -u
set -o pipefail

CUDA_VISIBLE_DEVICES=0 ./asr.sh \
    --stage 1 \
    --stop_stage 13 \
    --nj 4 \
    --ngpu 1 \
    --gpu_inference true \
    --inference_nj 1 \
    --use_lm false \
    --lang en \
    --token_type word \
    --speed_perturb_factors "0.9 1.0 1.1"\
    --asr_config conf/train_asr_demo_branchformer.yaml \
    --inference_args "--beam_size 10 --ctc_weight 0.3" \
    --train_set train_nodev \
    --valid_set train_dev \
    --test_sets "train_dev test" \
    --bpe_train_text "data/train_nodev/text" \
    --lm_train_text "data/train_nodev/text" "$@"
```
I have used this configuration file "train_asr_demo_branchformer.yaml", to reproduce:

```bash
# Trained with Ampere A6000(48GB) x 2 GPUs. It takes about 10 days.
batch_type: numel
batch_bins: 40000000
accum_grad: 3
max_epoch: 35
patience: none
init: none
best_model_criterion:
-   - valid
    - acc
    - max
keep_nbest_models: 10
unused_parameters: true
freeze_param: [
"frontend.upstream"
]

frontend: s3prl
frontend_conf:
    frontend_conf:
        upstream: wavlm_large  # Note: If the upstream is changed, please change the input_size in the preencoder.
    download_dir: ./hub
    multilayer_feature: True

preencoder: linear
preencoder_conf:
    input_size: 1024  # Note: If the upstream is changed, please change this value accordingly.
    output_size: 80

encoder: conformer
encoder_conf:
    output_size: 512
    attention_heads: 8
    linear_units: 2048
    num_blocks: 12
    dropout_rate: 0.1
    positional_dropout_rate: 0.1
    attention_dropout_rate: 0.1
    input_layer: conv2d2
    normalize_before: true
    macaron_style: true
    pos_enc_layer_type: "rel_pos"
    selfattention_layer_type: "rel_selfattn"
    activation_type: "swish"
    use_cnn_module:  true
    cnn_module_kernel: 31

decoder: transformer
decoder_conf:
    attention_heads: 8
    linear_units: 2048
    num_blocks: 6
    dropout_rate: 0.1
    positional_dropout_rate: 0.1
    self_attention_dropout_rate: 0.1
    src_attention_dropout_rate: 0.1

model_conf:
    ctc_weight: 0.3
    lsm_weight: 0.1
    length_normalized_loss: false
    extract_feats_in_collect_stats: false   # Note: "False" means during collect stats (stage 10), generating dummy stats files rather than extract_feats by forward frontend.

optim: adam
optim_conf:
    lr: 0.0025
scheduler: warmuplr
scheduler_conf:
    warmup_steps: 40000

specaug: specaug
specaug_conf:
    apply_time_warp: true
    time_warp_window: 5
    time_warp_mode: bicubic
    apply_freq_mask: true
    freq_mask_width_range:
    - 0
    - 30
    num_freq_mask: 2
    apply_time_mask: true
    time_mask_width_range:
    - 0
    - 40
    num_time_mask: 2
```
Using this setting I got the following error:

```bash
Traceback (most recent call last):
  File "/DATA/anaconda3/envs/KeshavEspnet/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/DATA/anaconda3/envs/KeshavEspnet/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/DATA/Sougata/BTech/espnet/espnet2/bin/asr_train.py", line 23, in <module>
    main()
  File "/DATA/Sougata/BTech/espnet/espnet2/bin/asr_train.py", line 19, in main
    ASRTask.main(cmd=cmd)
  File "/DATA/Sougata/BTech/espnet/espnet2/tasks/abs_task.py", line 1082, in main
    cls.main_worker(args)
  File "/DATA/Sougata/BTech/espnet/espnet2/tasks/abs_task.py", line 1192, in main_worker
    model = cls.build_model(args=args)
  File "/DATA/Sougata/BTech/espnet/espnet2/tasks/asr.py", line 515, in build_model
    normalize = normalize_class(**args.normalize_conf)
  File "/DATA/Sougata/BTech/espnet/espnet2/layers/global_mvn.py", line 40, in __init__
    stats = np.load(stats_file)
  File "/DATA/anaconda3/envs/KeshavEspnet/lib/python3.9/site-packages/numpy/lib/npyio.py", line 405, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: 'exp/asr_stats_raw_en_word_sp/train/feats_stats.npz'
# Accounting: time=126 threads=1
# Ended (code 1) at Mon Sep 25 19:38:09 IST 2023, elapsed time 126 seconds
```
and the I saw the following parameter in the config file mentioned above:
```bash
    extract_feats_in_collect_stats: false   # Note: "False" means during collect stats (stage 10), generating dummy stats files rather than extract_feats by forward frontend.
```
I thought this should be set to "true" and stage 10 it worked fine, stage 11 kept on running so long without any error but then I have seen https://github.com/espnet/espnet/issues/5444#issuecomment-1733737443 and tried that config file and got the same error as mentioned above. 

Questions:

1. where can I include the calculation of statistics in the stage 1 as I have included stage 1 already in my script?
2.  Is it a wise decision to change   ```extract_feats_in_collect_stats``` to true?

**Comment by sw005320** [comment]
@wanchichen, can you answer it?
I'm not sure why we need `exp/asr_stats_raw_en_word_sp/train/feats_stats.npz` but maybe I misunderstood something.

**Comment by wanchichen** [comment]
Hi @Naramkeshav59 , could you clarify if you want to do ASR or TTS? Sorry I am a bit confused here.

The code you are currently running is for ASR.  Since you are using a self-supervised model,  `extract_feats_in_collect_stats` can be false. You just need to add `—feats_normalize utt_mvn \ `to the flags in run.sh
/

**Comment by Naramkeshav59** [comment]
> Hi @Naramkeshav59 , could you clarify if you want to do ASR or TTS? Sorry I am a bit confused here.
> 
> The code you are currently running is for ASR. Since you are using a self-supervised model, `extract_feats_in_collect_stats` can be false. You just need to add `—feats_normalize utt_mvn \ `to the flags in run.sh. That should fix the error.

Hello @wanchichen Thank you for the help and sorry for the confusion caused. Yes, I wanted to do ASR . I have referenced the documentation containing TTS only because it contained about the stages related to statistics computation. The error got resolved after adding the flag ```--feats_normalize utt_mvn```. Thank you once again.
