### ISSUE TITLE
Muskits library import 

### ISSUE THREAD

**Issue by peongk** [espnet/espnet#5450]
I am trying to import SingingGenerate from muskits but it shows ModuleNotFoundError: No module named 'muskit' even after using the muskits installer in tools. How do I import muskits library in espnet?

**Comment by ftshijt** [comment]
We do not depend on muskits as it is completely merged into espnet already. Could you please paste the error msg, so that I can better help you?

**Comment by peongk** [comment]
does that mean instead of muskits.bin.svs_inference i should use espnet2.bin.svs_inference?

**Comment by ftshijt** [comment]
Yeah, you can just use espnet2's (FYI, the installer in espnet is not for installing muskits, but other necessary packages that are needed to enable svs training in ESPnet)
