### ISSUE TITLE
ML-SUPERB: LID and multilingual ASR training script

### ISSUE THREAD

**Issue by nervjack2** [espnet/espnet#5486]
The main directory of ML-SUPERB is at /espnet/egs2/ml_superb/asr1/

According to README.md, the running command of multilingual ASR is: 
`./run_multi.sh --asr_config <your_training_config> --duration {10min, 1h}`
and the running command of LID is:
`./run_multi.sh --asr_config <your_training_config> --duration {10min, 1h} --only_lid true`

Since the default value of the variable "only_lid" is true, 
it seems that the running command of LID and multilingual ASR are identical.
I am not sure whether it is correct.

Thanks a lot!

**Comment by sw005320** [comment]
@ftshijt, can you answer this question?

**Comment by ftshijt** [comment]
Oh, thanks for the note! 

You are correct. We should change only_lid to false in default with regard to readme. will start a PR to fix it

**Comment by ftshijt** [comment]
@nervjack2 hi, the fixed PR has been merged. As the issue has been solved with the update, I will close the issue. But if you find anything else, feel free to let us know.
