### ISSUE TITLE
Protobuf version requirement

### ISSUE THREAD

**Issue by MalekItani** [espnet/espnet#5488]
In https://github.com/espnet/espnet/pull/4407, a requirement was added for the `protobuf` version to be <= 3.20.1. This is now incompatible with newer releases of other packages, such as `onnx==1.14.1` which depends on `protobuf>=3.20.2`.

Since, the issue was titled "Temporary fix", and the link describing the issue it caused is now dead (or at least, inaccessible), I was wondering if this is still required. I can install the package without an issue if I remove the requirement from setup.py.

**Comment by sw005320** [comment]
Thanks a lot!
I'll test it at https://github.com/espnet/espnet/pull/5490

**Comment by sw005320** [comment]
Thanks for your note. We also confirmed it!
