### ISSUE TITLE
How to finetune whisper using my own dataset?

### ISSUE THREAD

**Issue by mukherjeesougata** [espnet/espnet#5493]
**Describe your question**
I want to directly decode whisper pretrained models and also want to get the decoded results after  finetuning them with my own language dataset for ASR task. After searching in the github issues and doing a google search I have come across 3 links which uses different configuration files for finetuning. Those are [1.](https://github.com/espnet/espnet/pull/5344), [2.](https://huggingface.co/espnet/shihlun_asr_whisper_medium_finetuned_librispeech100) and  [3.](https://github.com/espnet/espnet/pull/5342). Can anyone kindly please suggest me what would be the appropriate recipes and configurations both for getting decoded results directly from the whisper pretrained models and also for finetuning and decoding them with my own dataset?

**Comment by mukherjeesougata** [comment]
@sw005320 Can you kindly please answer this?

**Comment by sw005320** [comment]
You can just follow the second one.

**Comment by mukherjeesougata** [comment]
But, sir how to do the decoding directly from the whisper pretrained model on my own dataset?

**Comment by mukherjeesougata** [comment]
I am following [this](https://huggingface.co/espnet/shihlun_asr_whisper_medium_finetuned_librispeech100) recipe for whisper finetuning as per the previous suggestion. I have prepared a run.sh script which contains the following:-
```
#!/usr/bin/env bash
# Set bash to 'debug' mode, it will exit on :
# -e 'error', -u 'undefined variable', -o ... 'error in pipeline', -x 'print commands',
# cd espnet
# pip install -e .
# cd egs2/librispeech_100/asr1

set -e
set -u
set -o pipefail

train_set="train_clean_100"
valid_set="dev"
test_sets="test_clean test_other dev_clean dev_other"
asr_tag=whisper_medium_finetune_lr1e-5_adamw_wd1e-2_3epochs
asr_config=conf/tuning/train_asr_whisper_full.yaml
inference_config=conf/decode_asr_whisper_noctc_greedy.yaml

./asr.sh \
    --skip_data_prep false \
    --skip_train true \
    --skip_eval false \
    --lang en \
    --ngpu 1 \
    --nj 4 \
    --stage 1 \
    --stop_stage 1 \
    --gpu_inference true \
    --inference_nj 1 \
    --token_type whisper_multilingual \
    --feats_normalize '' \
    --max_wav_duration 30 \
    --speed_perturb_factors "0.9 1.0 1.1" \
    --audio_format "flac.ark" \
    --feats_type raw \
    --use_lm false \
    --cleaner whisper_en \
    --asr_tag "${asr_tag}" \
    --asr_config "${asr_config}" \
    --inference_config "${inference_config}" \
    --inference_asr_model valid.acc.ave.pth \
    --train_set "${train_set}" \
    --valid_set "${valid_set}" \
    --test_sets "${test_sets}" "$@"
```
when I am running this run.sh script it is throwing the following error:-
```
2024-10-29T15:57:25 (asr.sh:283:main) ./asr.sh --skip_data_prep false --skip_train true --skip_eval false --lang en --ngpu 1 --nj 4 --stage 1 --stop_stage 1 --gpu_inference true --inference_nj 1 --token_type whisper_multilingual --feats_normalize  --max_wav_duration 30 --speed_perturb_factors 0.9 1.0 1.1 --audio_format flac.ark --feats_type raw --use_lm false --cleaner whisper_en --asr_tag whisper_medium_finetune_lr1e-5_adamw_wd1e-2_3epochs --asr_config conf/tuning/train_asr_whisper_full.yaml --inference_config conf/decode_asr_whisper_noctc_greedy.yaml --inference_asr_model valid.acc.ave.pth --train_set train_clean_100 --valid_set dev --test_sets test_clean test_other dev_clean dev_other
2024-10-29T15:57:26 (asr.sh:565:main) Skipped stages:  2 4 5 6 7 8 9 10 11 14 15 16 
2024-10-29T15:57:26 (asr.sh:572:main) Stage 1: Data preparation for data/train_clean_100, data/dev, etc.
2024-10-29T15:57:26 (data.sh:20:main) local/data.sh 
stage 1: Data Download to downloads
local/download_and_untar.sh: no such directory downloads
```
I have also cheked the db.sh file, there it is written 
Set the path of your corpus. "downloads" means the corpus can be downloaded by the recipe automatically.
Can anybody kindly please help me in solving this error?

**Comment by mukherjeesougata** [comment]
@sw005320 I followed the recipe that you mentioned. But I am getting the error mentioned in the above comment. Can you kindly please mention the solution to this?

**Comment by mukherjeesougata** [comment]
> I am following [this](https://huggingface.co/espnet/shihlun_asr_whisper_medium_finetuned_librispeech100) recipe for whisper finetuning as per the previous suggestion. I have prepared a run.sh script which contains the following:-
> 
> ```
> #!/usr/bin/env bash
> # Set bash to 'debug' mode, it will exit on :
> # -e 'error', -u 'undefined variable', -o ... 'error in pipeline', -x 'print commands',
> # cd espnet
> # pip install -e .
> # cd egs2/librispeech_100/asr1
> 
> set -e
> set -u
> set -o pipefail
> 
> train_set="train_clean_100"
> valid_set="dev"
> test_sets="test_clean test_other dev_clean dev_other"
> asr_tag=whisper_medium_finetune_lr1e-5_adamw_wd1e-2_3epochs
> asr_config=conf/tuning/train_asr_whisper_full.yaml
> inference_config=conf/decode_asr_whisper_noctc_greedy.yaml
> 
> ./asr.sh \
>     --skip_data_prep false \
>     --skip_train true \
>     --skip_eval false \
>     --lang en \
>     --ngpu 1 \
>     --nj 4 \
>     --stage 1 \
>     --stop_stage 1 \
>     --gpu_inference true \
>     --inference_nj 1 \
>     --token_type whisper_multilingual \
>     --feats_normalize '' \
>     --max_wav_duration 30 \
>     --speed_perturb_factors "0.9 1.0 1.1" \
>     --audio_format "flac.ark" \
>     --feats_type raw \
>     --use_lm false \
>     --cleaner whisper_en \
>     --asr_tag "${asr_tag}" \
>     --asr_config "${asr_config}" \
>     --inference_config "${inference_config}" \
>     --inference_asr_model valid.acc.ave.pth \
>     --train_set "${train_set}" \
>     --valid_set "${valid_set}" \
>     --test_sets "${test_sets}" "$@"
> ```
> 
> when I am running this run.sh script it is throwing the following error:-
> 
> ```
> 2024-10-29T15:57:25 (asr.sh:283:main) ./asr.sh --skip_data_prep false --skip_train true --skip_eval false --lang en --ngpu 1 --nj 4 --stage 1 --stop_stage 1 --gpu_inference true --inference_nj 1 --token_type whisper_multilingual --feats_normalize  --max_wav_duration 30 --speed_perturb_factors 0.9 1.0 1.1 --audio_format flac.ark --feats_type raw --use_lm false --cleaner whisper_en --asr_tag whisper_medium_finetune_lr1e-5_adamw_wd1e-2_3epochs --asr_config conf/tuning/train_asr_whisper_full.yaml --inference_config conf/decode_asr_whisper_noctc_greedy.yaml --inference_asr_model valid.acc.ave.pth --train_set train_clean_100 --valid_set dev --test_sets test_clean test_other dev_clean dev_other
> 2024-10-29T15:57:26 (asr.sh:565:main) Skipped stages:  2 4 5 6 7 8 9 10 11 14 15 16 
> 2024-10-29T15:57:26 (asr.sh:572:main) Stage 1: Data preparation for data/train_clean_100, data/dev, etc.
> 2024-10-29T15:57:26 (data.sh:20:main) local/data.sh 
> stage 1: Data Download to downloads
> local/download_and_untar.sh: no such directory downloads
> ```
> 
> I have also cheked the db.sh file, there it is written Set the path of your corpus. "downloads" means the corpus can be downloaded by the recipe automatically. Can anybody kindly please help me in solving this error?

This issue was resolved after manually creating a directory with name downloads.
