### ISSUE TITLE
IEMOCAP SER recipe

### ISSUE THREAD

**Issue by 1itang** [espnet/espnet#5498]
In the espnet/egs2/iemocap/asr1/README.md,I saw " Using Transformer based encoder-decoder and self-supervised learning features [HuBERT_large_ll60k, Transformer, utt_mvn](conf/tuning/train_asr_transformer_hubert_960hr_large.yaml) and predicting transcript along with emotion".But the asr.sh is a model about asr task.There is nothing about the emotion recognition.How can I use espnet to do the SER task.
I would greatly appreciate it if you could answer my questions.

**Comment by sw005320** [comment]
@siddhu001, can you respond to this?

**Comment by siddhu001** [comment]
Hi @itang,

Thanks for your interest in our work!

As detailed in our related publication (https://arxiv.org/abs/2111.14706), we train our SLU models with an auxiliary ASR objective, meaning the model initially generates emotion labels and then the ASR transcript. Our findings indicate that this ASR multi-tasking approach significantly enhances SLU performance.

In this context, the ultimate task becomes a sequence-to-sequence problem. Consequently, we can utilize the ASR recipe where the `text` file contains the emotion label followed by the ASR transcript, for example: `<ang> isn't there anything you can do, just call over and ask them if I can go to the front of the line in the other line`.

Emotion recognition accuracy is then calculated from the inference files using the `local/score.sh `script (https://github.com/espnet/espnet/blob/master/egs2/iemocap/asr1/local/score.sh), which specifically assesses accuracy in predicting the first word. Hope this reply helps!

**Comment by 1itang** [comment]
Thank you for your reply!
