### ISSUE TITLE
pyopenjtalk issue

### ISSUE THREAD

**Issue by sw005320** [espnet/espnet#5528]
There is a windows installation issue in pyopenjtalk https://github.com/espnet/espnet/actions/runs/6736679956/job/18354953375
@r9y9, could you take a look at this?

**Comment by Runtrons** [comment]
Having the same issue on Mac too.

**Comment by r9y9** [comment]
Thanks for the report. Tthe new release v0.3.3 (https://github.com/r9y9/pyopenjtalk/releases/tag/v0.3.3) should fix this issue.

**Comment by sw005320** [comment]
Thanks a lot, @r9y9!

**Comment by r9y9** [comment]
Shall we close this?

**Comment by sw005320** [comment]
Sorry. I'm closing the issue.
