### ISSUE TITLE
Questions aboout egs2/wenetspeech/asr1/

### ISSUE THREAD

**Issue by sst0715** [espnet/espnet#5530]

**Comment by sw005320** [comment]
@pengchengguo, can you answer it for me?

**Comment by pengchengguo** [comment]
Hi @sst0715, can you describe your questions?

**Comment by sst0715** [comment]
> Hi @sst0715, can you describe your questions?

I am sorry for accidentally deleting the content of the question. The original question was that I found this in a paper titled "BA-SOT: Boundary-Aware Serialized Output Training for Multi-Talker ASR" (https://arxiv.org/abs/2305.13716), but it seems that the authors have not uploaded the improved code content to ESPnet, or I could not find it, so I would like to ask.😂

**Comment by sst0715** [comment]
> Hi @sst0715, can you describe your questions?

I am sorry for accidentally deleting the content of the question. The original question was that I found this in a paper titled "BA-SOT: Boundary-Aware Serialized Output Training for Multi-Talker ASR" (https://arxiv.org/abs/2305.13716), but it seems that the authors have not uploaded the improved code content to ESPnet, or I could not find it, so I would like to ask.😂

**Comment by pengchengguo** [comment]
Hi @sst0715, I think the author means the Conformer model trained on Wenetspeech corpus is used to initialize their BA-SOT model. The detailed implementation of BA-SOT is not included in ESPnet.

**Comment by sst0715** [comment]
> Hi @sst0715, I think the author means the Conformer model trained on Wenetspeech corpus is used to initialize their BA-SOT model. The detailed implementation of BA-SOT is not included in ESPnet.

Got it. Thanks for your reply!
