### ISSUE TITLE
[ASR] Query regarding ASR inference using `espnet2.bin.mt_inference.Text2Text`

### ISSUE THREAD

**Issue by ThishRaj** [espnet/espnet#5554]
Hi,

I would like to obtain inferences on audio files using a model trained using wavlm features (following the asr2 recipe). I am able to directly pass the raw audio tensor to `espnet2.bin.asr_inference.Speech2Text` object and obtain text inferences for models trained using asr1 recipe (since the asr_model itself holds information about the frontend feature extraction). But I am unable to understand how I can extract the features from the raw audio for mt_inference. During training the `pyscripts/feats/dump_ssl_feature.py` does this for all the files in the train, test and dev folders. Similarly, during inference is there any utility that converts audio files into the src_token sequence that `espnet2.bin.mt_inference.Text2Text` expects ? Or am I missing some obvious step ?

Thanks and regards,
Thishyan

**Comment by sw005320** [comment]
Thanks for the question.
@simpleoier, can you answer the question?
I think this is a very good trial to simplify the inference part and may make asr2 run in the normal speech2text interface.

**Comment by simpleoier** [comment]
Hi @ThishRaj ,

Thanks for pointing out this! I didn't consider this case yet, but I will update the asr2.sh based on your suggestion.

Suppose your have run the data dump part as : `./run.sh --stage 3 --stop-stage 3 --skip_train true`
What I will do is to update stage 4, so you may run as: `./run.sh --stage 4 --stop-stage 4 --skip_train true`
```
if ${skip_train}; then
    _stage=3
    _train_set=""
    _valid_set=""
   other_sets="${test_sets}"
else
    _stage=1
    _train_set="${train_set}"
    _valid_set="${valid_set}"
    other_sets="${test_sets} ${train_sp_sets}"
fi

    scripts/feats/perform_kmeans.sh \
        --stage ${_stage} --stop-stage 4 \
        --train_set "${_train_set}" \
        --dev_set "${_valid_set}" \
        --other_sets "${other_sets}" \
        --datadir "${data_audio}" \
        --featdir "${data_extract}" \
        --audio_format "${audio_format}" \
        --feature_type "${kmeans_feature_type}" \
        --layer "${layer}" \
        --feature_conf "${kmeans_feature_conf}" \
        --km_dir "${km_dir}" \
        --portion "${portion}" \
        --nclusters "${nclusters}" \
        --storage_save_mode ${storage_save_mode} \
        --use_gpu ${gpu_kmeans} \
        --nj ${nj} \
        --cpu_cmd "${train_cmd}" \
        --cuda_cmd "${cuda_cmd}" \
        ${kmeans_opts}
```
This is my plan. But there is one concern about whether the kmeans model stays in the right place `exp/kmeans`. If you are in a hurry, you may try in this direction. I'll make a PR asap.

**Comment by ThishRaj** [comment]
Thanks for your reply @sw005320 and @simpleoier.

I will try your suggestion for sure.

However my requirement is as follows:

I would like to pass an unlabeled audio file to the trained ASR model and use the inference from the model for downstream ASR tasks. I am still not sure how to convert my unlabeled audio file into the input format expected by `espnet2.task.mt_inference.Text2Text`. In `espnet2.task.asr_inference.Speech2Text`, it is pretty straightforward to convert the audio into a tensor and pass the tensor to the loaded ASR model. Whereas, `espnet2.task.mt_inference.Text2Text` expects a text tensor as input, which is not clear to me. My understanding is that, I have to use `espnet2.asr.frontend.s3prl.S3prlFrontend` to extract the features from the audio (which I am able to do).

My doubts are as follows:
1. I am yet to figure out how to map the WavLM features to discrete tokens determined using k-means. 
2. After discretization is done should I give the cluster indices as input to the `espnet2.task.mt_inference.Text2Text`? Or is there any intermediate step that I am missing? 

Kindly let me know if my direction is correct.

Thanks and Regards,
Thishyan

**Comment by simpleoier** [comment]
Hi @ThishRaj ,

> espnet2.task.mt_inference.Text2Text expects a text tensor as input, which is not clear to me

The text input is the discrete speech unit (probably + deduplication if necessary)

> I am yet to figure out how to map the WavLM features to discrete tokens determined using k-means.

In the script `scripts/feats/perform_kmeans.sh`, stage 3 performs the k-means clustering. The corresponding script can either map the WavLM feature to discrete unit or directly take the waveform and generate the discrete unit.

> After discretization is done should I give the cluster indices as input to the espnet2.task.mt_inference.Text2Text? Or is there any intermediate step that I am missing?

You can follow [these lines](https://github.com/espnet/espnet/blob/master/egs2/TEMPLATE/asr2/asr2.sh#L706-L758) to map cluster indices to (de-duplicated) CJK chars, which is the input to espnet2.task.mt_inference.Text2Text.

**Comment by ThishRaj** [comment]
Thank you for the reply @simpleoier.

It makes sense to me now.

Thank you,
Thishyan.
