### ISSUE TITLE
Questions about TALCS corpus

### ISSUE THREAD

**Issue by sst0715** [espnet/espnet#5557]
I recently discovered a Mandarin-English mixed dataset named TALCS(https://arxiv.org/ftp/arxiv/papers/2206/2206.13135.pdf). The experimental section of its paper used the ESPnet toolkit to conduct baseline experiments, but I couldn't find related information in the egs2 folder. I would like to know whether any relevant content has been created for it?
Here are the results :
![image](https://github.com/espnet/espnet/assets/118809740/b63dc337-18e2-4679-90f2-590b021bb1ea)

**Comment by sw005320** [comment]
No, we don't have such a recipe.
You can contact the authors.

**Comment by sst0715** [comment]
> No, we don't have such a recipe. You can contact the authors.

OK, thanks for your reply!
