### ISSUE TITLE
Attention, LM and decoding parameters

### ISSUE THREAD

**Issue by b-flo** [espnet/espnet#556]
Hi,

 I'm currently re-doing some experiments using only attention (mtlalpha=0.0, ctc_weight=0.0) and I came across a similar problem as in #135 : using a language model leads to increased WER/CER, with an high number of insertions compared to deletions. However there are some differences :

- Without a LM my best results are with a wide beam and no decoding parameters. Tuning any coverage terms (length penality & min/max length ratio) or decreasing the beam size increase the number of deletions and CER/WER.

- With a LM (rnnlm=0.3 in my case) -edit: and wide beam- the balance between deletions and insertions is correct however the CER/WER is much worse than using no LM. Same as previously, tuning any coverage or decreasing beam size increase the number of deletions and CER/WER. Decreasing the LM weight brings the CER/WER close to the CER/WER I have without LM.

- On my experiments with subwords I observe the same behaviours but with an high number of insertions instead of deletions.

For CTC and Joint CTC-Att, the results are really good without and with a language model, using any acoustic units.

Do you have an idea of what could be the cause? I tried a lot of things at different levels but couldn't find a good solution. In my previous experiments on the same dataset and without LM, I didn't have the problem I described in the first bullet.
If you need a complete report, I will edit this post later with the detailed results of all the experiments I did.

**Comment by sw005320** [comment]
> If you need a complete report, I will edit this post later with the detailed results of all the experiments I did.

Could you share your complete report? I want to figure out what happened in more details with these results.

**Comment by b-flo** [comment]
Sorry for the delay.
You can find below results for some tests I did using attention-only model. I'll update it later, I currently can't access all my directories as we have some network issues in my lab.
If you want I can send you by email decode logs (with verbose=1) for different decoding, recipe details, extra informations, some fix I tried, etc. Just tell me what you want!

| Beam | RNNLM | Len. penalty | Minlen  | Maxlen | Sub. | Del. | Ins. | CER |
|:-:|:-:|:-:|:-:|:-:|:-:|:-:|:-:|:-:|
| 10 | None | 0.0 | 0.0 | 0.0 | 4.9 | 7.9 | 4.1 | 16.9 |
| | None | 0.0 | 0.1 | 0.9 | 4.6 | 12.3 | 3.8 | 20.8 |
| | None | 0.0 | 0.2 | 0.8 | 3.8 | 29.9 | 2.9 | 36.6 |
| | char RNNLM (w=0.3) | 0.0 | 0.0 | 0.0 | 5.7 | 11.1 | 6.9 | 23.7 |
| | char RNNLM (w=0.3) | 0.0 | 0.2 | 0.8 | 4.5 | 32.5 | 3.9 | 40.9 |
| 30 | None | 0.0 | 0.0 | 0.0 | 4.9 | 6.7 | 4.2 | 15.8 |
| | None | 0.0 | 0.1 | 0.9 | 4.7 | 10.2 | 3.8 | 18.8 |
| | None | 0.0 | 0.2 | 0.8 | 4.0 | 23.5 | 3.0 | 30.6 |
| | char RNNLM (w=0.3) | 0.0 | 0.0 | 0.0 | 6.9 | 9.4 | 9.0 | 25.3 |
| | char RNNLM (w=0.3) | 0.0 | 0.2 | 0.8 | 5.9 | 24.7 | 4.7 | 35.3 |

Some notes : 
 - I made a mistake in my last post : I have an high number deletions with characters units, not the other way around. For subwords it's indeed an high number of insertions.
 - My current version of ESPNET is :  v.0.2.0-217-g55d07e1
 - Perplexity of my RNNLM is 3.11 on this set.
 - In these tests, the networks I used for the AM and LM are similar to ones used for HKUST. 
 - I tried with almost all possible values for beam size, length penalty, minlen, maxlen and rnnlm weight. The range of errors for intermediate values is as expected compared to the results in the previous table : if I increase rnnlm weight or add more restrictions to seq length, I increase the deletions errors.

**Comment by sw005320** [comment]
Which task are you working on, and which data are you using to train RNNLM?
Also, please send email to me with logs.

**Comment by b-flo** [comment]
I'm currently doing an analysis of several end-to-end SR approaches for French language using the broadcast news corpora ESTER and EPAC. The sentences from the training set (reconstructed from segments) and slightly augmented with data from other works are used to train the RNNLM.
Note that I also made, with the same data, a 3-gram and a RNNLM for a phone-based system to compare with the 3-gram provided by the LIUM for the this specific task. Being perplexity or WER for the system using it, the results were not far to each other despite the difference in volume.

I guess some logs are redundant as I tested almost all values for length control parameters. Which ones would like me to send you? I will send you an email as soon possible (i.e when our network issues are resolved...).

**Comment by b-flo** [comment]
Hi,

 I still can not access some of my directories but I sent some logs to your John Hopkins' email address.
Thanks for your help.

**Comment by sw005320** [comment]
That's interesting project. Yes, please send them (normal one and one with RNNLM (w=0.3) are fine) to my JHU address.

**Comment by b-flo** [comment]
Hi @sw005320,

I am retraining some of my models as my latest experiment demonstrated great performances (+3% WER difference with subword units, joint ctc-attention model and RNNLM against chain model and 62,3K lexicon + word 3-gram LM from LIUM)
I'll sent you the new logs if I observe some differences using my retrained attention-only model!
