### ISSUE TITLE
Question on Non Auto regressive Streaming 

### ISSUE THREAD

**Issue by kbramhendra** [espnet/espnet#5566]
Hi ,
     I am exploring NAR streaming methods, I have found out this interesting paper [Streaming End-to-End ASR based on Blockwise Non-Autoregressive Models
](https://arxiv.org/abs/2107.09428) is there implementation for it in espnet. I have tried to implement this overlap based decoding in contextual block conformer but couldn't get what i wanted. Is there a implementation for it in espnet ? In this [NL,NC,NR], if do overlap decoding the future context of previous block is becoming left context for overlap block how to adjust this. and how to adjust encoder context appropriately ?

**Comment by kbramhendra** [comment]
Thanks for replying. Can you please shed on how to do this overlap greedy decoding with contextual block transformer. Do we have to make right context(Nr) zero ?

**Comment by siddhu001** [comment]
Yes @sw005320 I will make a PR for this soon!

So with contextual block transformer, I obtain predictions from both left and right context to ensure overlap in predictions. You can potentially also looks at alignment greedy decoding proposed here: https://arxiv.org/abs/2309.10926.
I will make the code public for both overlap and alignment greedy decoding soon.

**Comment by kbramhendra** [comment]
Thanks for replying.
