### ISSUE TITLE
Inference

### ISSUE THREAD

**Issue by ErnstTmp** [espnet/espnet#557]
Hello,
thank you very much for creating ESP-Net, this is great!!!

We have trained a model on LibriSpeech, and now I would like to due inference on real sentences (WAV-Files). Can you point to a resource how this can be done or give me a short outline what I need to do?

Thanks and kind regards
Ernst

**Comment by sw005320** [comment]
We developed ESPnet for the research purpose and did not spend so much efforts on such cases.
The simple answer is that we still follow our `run.sh` as follows:
1. Make a data directory based on your real sentences in the stage 0. 
2. Perform feature extraction in the stage 1
3. Make a `data.json` file with the data directory and feature file (scp) information in the stage 2
4. Perform inference in the stage 5.

The stage 0 requires to make a new script for your real sentences. You may put some dummy text for the `text` file if you don't have their transcriptions.

**Comment by ErnstTmp** [comment]
Thank you very much for your fast answer, it is very helpful.
I will try as you suggest!
Kind regards
Ernst
