### ISSUE TITLE
Increasing the beam size can sometimes lead to the elimination of inference in ASR on custom dataset.

### ISSUE THREAD

**Issue by hagakure333** [espnet/espnet#5573]
I'm training a speech recognition model on a custom dataset. When I increase the beam size, inference disappearance sometimes occurs. What could be potential reasons for this? Thank you.

beam size =50， wer=23.0
![消失](https://github.com/espnet/espnet/assets/67449891/fe7763d0-4ff0-43ce-a7ee-709f0b554274)

beam size =20，wer=22.1
![消失なし](https://github.com/espnet/espnet/assets/67449891/0d08a72f-628d-4834-9df8-5bc9313d0308)

inference config
`beam_size: 20
lm_weight: 0.0
minlenratio: 0.05
penalty: 0
ctc_weight: 0.0`

asr config
`batch_type: folded
batch_size: 64
accum_grad: 2
max_epoch: 70
patience: 5

init: xavier_uniform
best_model_criterion:
-   - valid
    - acc
    - max
keep_nbest_models: 10

encoder: transformer
encoder_conf:
    output_size: 256
    attention_heads: 4
    linear_units: 2048
    num_blocks: 12
    dropout_rate: 0.1
    positional_dropout_rate: 0.1
    attention_dropout_rate: 0.1
    input_layer: conv2d
    normalize_before: true

decoder: transformer
decoder_conf:
    attention_heads: 4
    linear_units: 2048
    num_blocks: 6
    dropout_rate: 0.1
    positional_dropout_rate: 0.1
    self_attention_dropout_rate: 0.1
    src_attention_dropout_rate: 0.1

model_conf:
    ctc_weight: 0.0
    lsm_weight: 0.1
    length_normalized_loss: false

optim: adam
optim_conf:
    lr: 0.0002
scheduler: warmuplr
scheduler_conf:
    warmup_steps: 20000
specaug: specaug
specaug_conf:
    apply_time_warp: true
    time_warp_window: 2
    time_warp_mode: bicubic
    apply_freq_mask: true
    freq_mask_width_range:
    - 0
    - 15
    num_freq_mask: 2
    apply_time_mask: true
    time_mask_width_range:
    - 0
    - 20
    num_time_mask: 2
`

espnet version ==0.10.0

**Comment by sw005320** [comment]
Can you increase `minlenratio`?
This may avoid having too short sentences.

**Comment by hagakure333** [comment]
I set the beam_size to 50 and varied the minlenratio from 0.05, 0.1, 0.2, 0.3, 0.4, to 0.5, but all resulted in the same WER of 23.0 (including values for Sub Del Ins).

**Comment by sw005320** [comment]
Thanks a lot for your detailed analysis.
We may find some critical bugs in the beam search function based on your analysis.
We're now checking it.

**Comment by jctian98** [comment]
@hagakure333  
Hi, we believe we possibly have found the reason. Please check the explanation in this PR : https://github.com/espnet/espnet/pull/5581
We would also appreciate it if you could test this PR and see if the problem is solved (it solves the problem in our internal test

Thanks!

**Comment by hagakure333** [comment]
thank you!!
