### ISSUE TITLE
How to debug with vscode？

### ISSUE THREAD

**Issue by zuowanbushiwo** [espnet/espnet#5575]
**Describe your question**
espnet is a complex project that contains many scripts, and the model training process is too hidden. How to use vscode to single-step debug and track the entire process? thanks!
For example, I have used the run.sh script to develop and run the first project(egs2/wsj0_2mix/tse1), but I have little understanding of how it runs.
​
![image](https://github.com/espnet/espnet/assets/3354428/c37d3e07-78bf-4a75-aac3-af7d56f1224b)

**Comment by Fhrozen** [comment]
You can debug by focusing on the task file.
bin/launch.py is for parallel node/gpu processing distribution. (You can skip/remove it if you want to debug a task.)
The important part is bin/enh_tse_train. It will call the related task located at espnet2/tasks/<>.py.

You can use the task as entrypoint for the debugger. 
Then, you can use the config file and additional arguments using the python args as in https://code.visualstudio.com/docs/python/debugging#_pythonargs

**Comment by fmbao** [comment]
same question
