### ISSUE TITLE
graph-pit in skim model

### ISSUE THREAD

**Issue by xiaosimao** [espnet/espnet#5597]
In the skim paper， graph-pit loss is used. But in the config file, i.e train_enh_skim_causal_small.yaml, it use pit loss wrapper.
![image](https://github.com/espnet/espnet/assets/13148274/4d41efca-07dd-4af4-9602-ae0cb6936dbd)
![image](https://github.com/espnet/espnet/assets/13148274/b98f4d39-f482-4a9c-9a8c-a04c953dbd77)

My question:  the pit is graph-git?

Thanks

**Comment by sw005320** [comment]
@LiChenda, can you answer for it.

**Comment by xiaosimao** [comment]
您好，您的邮件已经收到，尽快给您回复。

**Comment by LiChenda** [comment]
Hi @xiaosimao , this config file is for reproducing results in Table 4 in the SkiM paper. Graph PIT was applied in continuous speech separation. I haven't summarized CSS as a recipe in ESPnet-SE. WSJ0-2mix is an utterance-level separation recipe, so we just use PIT here.

**Comment by xiaosimao** [comment]
> Hi @xiaosimao , this config file is for reproducing results in Table 4 in the SkiM paper. Graph PIT was applied in continuous speech separation. I haven't summarized CSS as a recipe in ESPnet-SE. WSJ0-2mix is an utterance-level separation recipe, so we just use PIT here.

Got it.
