### ISSUE TITLE
Installation cannot be proceeded properly with latest/default python version on Honda

### ISSUE THREAD

**Issue by underdogliu** [espnet/espnet#5625]
**Describe the issue**
I am installing espnet from scratch under the default setup, where the python version is 3.11. However, I ran into installtion error when running `make`. This issue can be fixed by using an older python version (I used 3.8).
Is it because of some in-compatibility in my environment or something?

**Show the `check_install.py` status by using the following command**
```
cd <espnet-root>/tools
. ./activate_python.sh; python3 check_install.py
```

**Basic environments:**
 - OS information: Linux
 - python version: 3.11 (no issue with 3.8.18)
 - espnet version: 202310
 - Git hash: 1f7280b5732f489614e266f18a07d0fcc893d432
   - Commit date `Thu Jan 18 11:36:51 2024 +0900`
 - pytorch version: 2.1.0

**Environments from `torch.utils.collect_env`:**
e.g.,
```
Collecting environment information...
PyTorch version: 1.4.0
Is debug build: No
CUDA used to build PyTorch: 10.0

OS: CentOS Linux release 7.5.1804 (Core)
GCC version: (GCC) 7.2.0
CMake version: version 2.8.12.2

Python version: 3.11
Is CUDA available: No

Versions of relevant libraries:
[pip3] numpy==1.23.5
[pip3] pytorch-ranger==0.1.1
[pip3] torch==2.1.0
[pip3] torch-complex==0.4.3
[pip3] torch-optimizer==0.3.0
[pip3] torchaudio==2.1.0
[pip3] triton==2.0.0
[conda] blas                      1.0                         mkl
[conda] cpuonly                   2.0                           0    pytorch
[conda] mkl                       2023.1.0         h213fc3f_46344
[conda] mkl-service               2.4.0            py38h5eee18b_1
[conda] mkl_fft                   1.3.8            py38h5eee18b_0
[conda] mkl_random                1.2.4            py38hdb19cb5_0
[conda] numpy                     1.23.5           py38hf6e8229_1
[conda] numpy-base                1.23.5           py38h060ed82_1
[conda] pytorch                   2.1.0               py3.8_cpu_0    pytorch
[conda] pytorch-mutex             1.0                         cpu    pytorch
[conda] pytorch-ranger            0.1.1                    pypi_0    pypi
[conda] torch-complex             0.4.3                    pypi_0    pypi
[conda] torch-optimizer           0.3.0                    pypi_0    pypi
[conda] torchaudio                2.1.0                  py38_cpu    pytorch
[conda] triton                    2.0.0                    pypi_0    pypi
```

**Comment by sw005320** [comment]
Thanks for the report!
@kamo-naoyuki, can you check it?

**Comment by kamo-naoyuki** [comment]
ESPnet doesn't support python=3.11 now. Please use python<=3.10.

@sw005320 #5532 should fix this problem, but the new sentencepiece changed something relating to the output. I think it's better to ask some in the know, as I said before. At least, we need to merge  #5532 in the future.

https://github.com/espnet/espnet/actions/runs/6800721506/job/18489922853?pr=5532#step:8:358

**Comment by underdogliu** [comment]
OK I will use python3.8 for now.
