### ISSUE TITLE
New recipe for THCHS30 database

### ISSUE THREAD

**Issue by kelvin-pfp** [espnet/espnet#564]
I'm trying to perform ASR experiment on Chinese. Although there is a HKUST recipe, I cannot access the database. 
Would there be any plan on adding a new recipe for another Chinese (Mandarin) database such as THCHS30, please?

**Comment by sw005320** [comment]
We can work on making a recipe upon request, but `THCHS30` seems to be too small database (30 hours) to build end-to-end ASR.

**Comment by kelvin-pfp** [comment]
Yes, I understand that but I just want an available sample for experiment.

**Comment by nshmyrev** [comment]
There are [Surfingtech](http://openslr.org/38/) and [Aishell](
http://openslr.org/33/) and [Primewords](
http://openslr.org/47/), all available on OpenSLR.

**Comment by sw005320** [comment]
Thanks.
Aishell seems to be good. I'll play with it.

**Comment by sw005320** [comment]
I just finished to port the Kaldi aishell recipe to the ESPnet recipe. I summarized the procedure of how we port the Kaldi recipe to the ESPnet recpe. Please follow this instruction when you want to create a new recipe:
https://github.com/espnet/espnet/wiki/How-to-port-the-Kaldi-recipe-to-the-ESPnet-recipe%3F

**Comment by sw005320** [comment]
See #571

**Comment by kelvin-pfp** [comment]
Thank you very much! I will try it later.

**Comment by sw005320** [comment]
I did not do any tuning, but the aIshell number is quite competitive to the one in Kaldi.
https://github.com/espnet/espnet/blob/v.0.3.0/egs/aishell/asr1/RESULTS#L1
