### ISSUE TITLE
Support for new typeguard version

### ISSUE THREAD

**Issue by albertz** [espnet/espnet#5660]
Currently you pin to an old typeguard version. This is a problem for me, because I want to use it together with some other code which requires a newer typeguard version.

As I understand https://github.com/espnet/espnet/pull/5009, just no-one so far has invested some effort in updating the code? But in principle, you are ok with updating the code?

As I understand it, instead of using `check_argument_types()` and `check_return_type()`, use the `@typechecked` decorator on the function.

Note, I also asked whether we can maybe get back `check_argument_types()` and `check_return_type()` in newer versions of typeguard, but I doubt that they would add it back. https://github.com/agronholm/typeguard/issues/437

**Comment by sw005320** [comment]
Thanks, @albertz.

@kamo-naoyuki, can you answer it?

**Comment by kamo-naoyuki** [comment]
@albertz Yes. It's great if you'll update.

**Comment by sw005320** [comment]
We can successfully update `typeguard`
