### ISSUE TITLE
Automatic doc build & deploy based on Travis-CI and travis-sphinx

### ISSUE THREAD

**Issue by ShigekiKarita** [espnet/espnet#57]
Manual deploy is troublesome. I've already tested [travis-sphinx](https://github.com/Syntaf/travis-sphinx)  that automates sphinx-doc build & gh-pages deploy with Travis-CI.

- [.travis.yml](https://github.com/ShigekiKarita/espnet/blob/master/.travis.yml#L46)
- [gh-pages](https://shigekikarita.github.io/espnet/apis/nets.html#nets.e2e_asr_attctc.Encoder)
  - I confirmed that my fix of typo `ENCODER NE(W)TWORK CLASS` was deployed automatically
- you can build HTML doc locally by `travis-sphinx build --source=doc --nowarn` and see `doc/build/index.html`

This enables us to add and confirm documentation rapidly.
Do you have any problem to automate this?

**Comment by kan-bayashi** [comment]
Thanks @ShigekiKarita !
It is what I wanted :)

**Comment by r9y9** [comment]
Is this still working now?

**Comment by ShigekiKarita** [comment]
Yes

**Comment by r9y9** [comment]
Ah okay, doc building system is working but API docs are just missing in https://github.com/espnet/espnet/blob/master/doc/apis/nets.rst.

**Comment by ShigekiKarita** [comment]
https://espnet.github.io/espnet/apis/nets.html
this page is listed in the left column. maybe it is nice to add index.rst

**Comment by ShigekiKarita** [comment]
this nets page has not been updated so far... we need to add more (ASR/TTSInterface, Transformer, Frontend, etc)
