### ISSUE TITLE
Upgrade typeguard version

### ISSUE THREAD

**Issue by duguyue100** [espnet/espnet#5701]
**Describe the issue**

I'm using `jedi-language-server` which uses `pygls` under the hood. `pygls` in general requires `typeguard > 3`. However `espnet` requires a specific version of `typeguard=2.13.3`. As you can see, after installing `espnet` my code completion stops working. If I simply upgrade `typeguard`, then the `espnet` will stop working.

I'm not an expert on `typeguard` but I guess you chose this specific version for a reason.
Is it possible to upgrade the `typeguard` version in the next release?

I think there are many users like me who have this setup.

**A workaround**: I can downgrade `jedi-language-server` to 0.40.0 and `pygls` to 1.0.0 manually to avoid this problem. But it will become annoying when I accidentally upgrade the package and have to do the whole downgrading again.

**Comment by sw005320** [comment]
We can successfully update `typeguard`
