### ISSUE TITLE
USES `ref_channel` usage

### ISSUE THREAD

**Issue by faroit** [espnet/espnet#5716]
The `USES` model implements `TAC` and has an option to pass in the reference channel but it seems not to be implemented according to

https://github.com/espnet/espnet/blob/eed7751c910977290ef9a177ea0942a0e3c2fd35/espnet2/enh/layers/uses.py#L392-L407

**Comment by sw005320** [comment]
Thanks!
@Emrys365, can you confirm it?

**Comment by faroit** [comment]
Hi, and thanks @sw005320 for looking into this. I guess this is fine and just something left from a previous implementation. The reference channels is used in the paths blocks:

https://github.com/espnet/espnet/blob/eed7751c910977290ef9a177ea0942a0e3c2fd35/espnet2/enh/layers/uses.py#L262-L263

**Comment by Emrys365** [comment]
Thank you for your report! Yes, you are correct. This is from a previous implementation that handles the `ref_channel` inside the ChannelTAC block. Later I decided to move it to the outer `ATFBlock` block for more unified processing. So this argument will have no effect for now. But I leave it there for possible extensions in the future.

**Comment by faroit** [comment]
Thanks @sw005320 @Emrys365 all good then!
