### ISSUE TITLE
Character sequence to word mapping algorithm

### ISSUE THREAD

**Issue by SreeramGanji** [espnet/espnet#573]
Hello everyone.
It would be really helpful if someone could please help me understanding the algorithm used for mapping character sequence to words while calculating WER.
While decoding, it may happen that one of the characters in a word is deleted/substituted/inserted. Thus simple mapping of character sequence to words will give rise to many <unk>s and hence a large WER. I guess that there must a closest character sequence to word mapping based on metrics like edit distance which would be taking place. Could somebody guide me if my guess is correct and it would be really helpful if you could also point out towards the script which is doing the same.
Thanking you in advance.

**Comment by sw005320** [comment]
We don't have a such mapping. The WER is computed by simply mapping a character sequence with the space symbol to the corresponding word sequence in most cases. In the WSJ recipe, we have advanced word-level decoding by considering a word constraint (see https://github.com/espnet/espnet/blob/master/egs/wsj/asr1/run.sh).
