### ISSUE TITLE
asr_train.py: error: unrecognized arguments: use_lora 

### ISSUE THREAD

**Issue by pywang89** [espnet/espnet#5734]
Hi, I want to use Whisper model for my asr task.
So I install install_whisper.sh, install_lora.sh and add
asr_config=conf/tuning/train_asr_whisper_medium_lora_finetune.yaml
inference_config=conf/tuning/decode_asr_whisper_noctc_beam10.yaml
to my run.sh
however, I got:
asr_train.py: error: unrecognized arguments: use_lora (from conf/tuning/train_asr_whisper_medium_lora_finetune.yaml)
# Accounting: time=4 threads=1

**Comment by ily6** [comment]
Hi, I've encountered the same issue as well. I'm wondering how you resolved it?

**Comment by hengbohu** [comment]
https://giters.com/espnet/espnet/issues/5779
