### ISSUE TITLE
Espnet Collect stats: s3prl Upstream 'hubert-large-ll60k' 

### ISSUE THREAD

**Issue by MisakiWho** [espnet/espnet#5737]
**Describe the bug**
Use recipe: conf/tuning/train_asr_conformer7_hubert_ll60k_large.yaml
(s3prl upstream as frontend)

But collect stats too slow(a day) and get unknown errors.

I've already set --nj to 4 to reduce parallel jobs considering memory usage.

**Error logs**
![Uploading error.PNG…]()

**Comment by MisakiWho** [comment]
2024-04-08T11:15:41 (asr.sh:283:main) ./asr.sh --lang en --ngpu 4 --nbpe 5000 --max_wav_duration 30 --speed_perturb_factors 0.9 1.0 1.1 --nj 4 --stage 10 --stop_stage 10     --ngpu 4 --asr_config conf/prompt_asr/train_asr_conformer7_hubert_ll60k_large.yaml --lm_config conf/tuning/train_lm_transformer2.yaml --inference_config conf/decode_asr    .yaml --train_set train_960 --valid_set dev --test_sets test_clean test_other dev_clean dev_other --lm_train_text data/train_960/text data/local/other_text/text --bpe_tr    ain_text data/train_960/text
  2 2024-04-08T11:15:41 (asr.sh:565:main) Skipped stages:  9 14 15 16
  3 2024-04-08T11:15:41 (asr.sh:1190:main) Stage 10: ASR collect stats: train_set=dump/raw/train_960_sp, valid_set=dump/raw/dev
  4 2024-04-08T11:15:43 (asr.sh:1241:main) Generate 'exp/asr_stats_raw_en_bpe5000_sp/run.sh'. You can resume the process from stage 10 using this script
  5 2024-04-08T11:15:43 (asr.sh:1245:main) ASR collect-stats started... log: 'exp/asr_stats_raw_en_bpe5000_sp/logdir/stats.*.log'
  6 bash: line 1: 113342 Killed                  ( python3 -m espnet2.bin.asr_train --collect_stats true --use_preprocessor true --bpemodel data/en_token_list/bpe_unigram500    0/bpe.model --token_type bpe --token_list data/en_token_list/bpe_unigram5000/tokens.txt --non_linguistic_symbols none --cleaner none --g2p none --train_shape_file exp/as    r_stats_raw_en_bpe5000_sp/logdir/train.4.scp --valid_shape_file exp/asr_stats_raw_en_bpe5000_sp/logdir/valid.4.scp --output_dir exp/asr_stats_raw_en_bpe5000_sp/logdir/st    ats.4 --config conf/prompt_asr/train_asr_conformer7_hubert_ll60k_large.yaml --frontend_conf fs=16k --train_data_path_and_name_and_type dump/raw/train_960_sp/wav.scp,spee    ch,sound --valid_data_path_and_name_and_type dump/raw/dev/wav.scp,speech,sound --train_data_path_and_name_and_type dump/raw/train_960_sp/text,text,text --valid_data_path    _and_name_and_type dump/raw/dev/text,text,text ) 2>> exp/asr_stats_raw_en_bpe5000_sp/logdir/stats.4.log >> exp/asr_stats_raw_en_bpe5000_sp/logdir/stats.4.log
  7 bash: line 1: 113338 Killed                  ( python3 -m espnet2.bin.asr_train --collect_stats true --use_preprocessor true --bpemodel data/en_token_list/bpe_unigram500    0/bpe.model --token_type bpe --token_list data/en_token_list/bpe_unigram5000/tokens.txt --non_linguistic_symbols none --cleaner none --g2p none --train_shape_file exp/as    r_stats_raw_en_bpe5000_sp/logdir/train.2.scp --valid_shape_file exp/asr_stats_raw_en_bpe5000_sp/logdir/valid.2.scp --output_dir exp/asr_stats_raw_en_bpe5000_sp/logdir/st    ats.2 --config conf/prompt_asr/train_asr_conformer7_hubert_ll60k_large.yaml --frontend_conf fs=16k --train_data_path_and_name_and_type dump/raw/train_960_sp/wav.scp,spee    ch,sound --valid_data_path_and_name_and_type dump/raw/dev/wav.scp,speech,sound --train_data_path_and_name_and_type dump/raw/train_960_sp/text,text,text --valid_data_path    _and_name_and_type dump/raw/dev/text,text,text ) 2>> exp/asr_stats_raw_en_bpe5000_sp/logdir/stats.2.log >> exp/asr_stats_raw_en_bpe5000_sp/logdir/stats.2.log

**Comment by MisakiWho** [comment]
Thanks for your reply.


Sorry, the file storage system in the lab cluster is currently malfunctioning, so I'm unable to log in to the server and capture error logs. 


Regarding the errors with stats.*.log earlier, they were displayed in slurm-out, with different errors reported each time. I suspect it may be a memory issue, so I reduced the --nj parameter from 32 to 1. 


It's true that stage 10 only involves data-related information. Therefore, I used the config of the conformer+transformer that I previously used successfully on the LibriSpeech dataset to execute stage 10. However, I encountered a problem with the collect stats process being very slow, with a gap of 10 minutes between log entries like "Nither 400" and "Nither 500".


Once the lab server is fixed (maybe tomorrow), I will retry the steps for utterance-level ASR stage 10. If there are any issues, I will provide more specific descriptions with images and text. 


Additionally, I may attempt to set the extrac_collect_feats parameter to False to avoid some of the errors caused by large models.












------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "espnet/espnet"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年4月8日(星期一) 晚上7:26
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [espnet/espnet] Espnet Collect stats: s3prl Upstream 'hubert-large-ll60k'  (Issue #5737)





 
Can you check the error message in exp/asr_stats_raw_en_bpe5000_sp/logdir/stats.2.log and let us know it?
 
@simpleoier, can you answer this?
 This step only checks the size of the data, and it should not take a very long time.

**Comment by MisakiWho** [comment]
Sorry, the file storage system in the lab cluster is currently malfunctioning, so I'm unable to log in to the server and capture error logs. 

Regarding the errors with stats.*.log earlier, they were displayed in slurm-out, with different errors reported each time. I suspect it may be a memory issue, so I reduced the --nj parameter from 32 to 1. 

It's true that stage 10 only involves data-related information. Therefore, I used the config of the conformer+transformer that I previously used successfully on the LibriSpeech dataset to execute stage 10. However, I encountered a problem with the collect stats process being very slow, with a gap of 10 minutes between log entries like "Nither 400" and "Nither 500".

Once the lab server is fixed (maybe tomorrow), I will retry the steps for utterance-level ASR stage 10. If there are any issues, I will provide more specific descriptions with images and text. 

Additionally, I may attempt to set the 'extract_collect_feats' parameter to False to avoid some of the errors caused by large models.

**Comment by simpleoier** [comment]
Hi @MisakiWho , can I ask two questions:
1. what is the RAM limit of each job?
2. are there any long utterances in your data, especially in the split 2 and 4 (that cannot fit in the RAM)?

BTW, please set the flag of extract collect feats to false. Otherwise, the input utterance will go through the large model, and the RAM consumption may be large.

**Comment by MisakiWho** [comment]
Thanks for your advice.


I followed your advice and reconfigured the settings. The memory errors did not occur again, but stage 10 is still slow. This might not be an issue with the espnet code. For now, I have utilized pre-processed stats from someone else and temporarily set aside the previous problem.

**Comment by MisakiWho** [comment]
I followed your advice and reconfigured the settings. The memory errors did not occur again, but stage 10 is still slow. This might not be an issue with the espnet code. For now, I have utilized pre-processed stats from someone else and temporarily set aside the previous problem.
