### ISSUE TITLE
[Discussion] The configuration system for experiments

### ISSUE THREAD

**Issue by kamo-naoyuki** [espnet/espnet#575]
This is a discussion for the general configuration for experiments. This topic is also related to #551 #555

Epsnet depends on `argparase` and `parse_options.sh` for configuration. This style works well only for a simple tool, but now espnet becomes a large project and is going to be more. I will also implement a big feature about dnn-frontend for asr.
I think now is the time to reconsider the style.

## Issue
For example, considering to implement new architecture.

```python
class MyEncoder:
    def __init__(self, param_a, param_b):
        self.param_a = param_a
        self.param_b = param_b
```

In order to integrate it to the master branch, he needs to do the following three:

- Add parser options
```python
parser.add_argument('--param-a')
parser.add_argument('--param-b')
```
- Give args to the Encoder
```
MyEncoder(param_a=args.param_a, param_b=param_b)
```
- Modify `run.sh`
```
param_a=foo
param_b=bar
. parse_options.sh

(...)

expdir=exp/..._param_a${param_a}_param_b${param_b}

(...)

asr_train.py --param-a ${param_a} --param-b ${param_b} ...
```

This is a little hard works and lacks much maintainability. 
Additionally, sometimes an experimenter add options temporally, but these steps seems too many for temporal action. Ideally, he may want to do this only by modifying his model.

## Sacred
 I usually use [sacred](https://github.com/IDSIA/sacred) for DNN experiments. Briefly, you can consider it as a more suitable replacement of `argparase` for experiments.

- argpase
```python
import argparse
if __name__ == '__main__':
    paraser = argparre.ArgumentParser()
    parase.add_argument('--a', type=int, default=3)
    parase.add_argument('--b', type=float, default=4.5)
    args = parser.parse_args()
    some_func(args.a, args.b)
```
```bash
python main.py --a=5 --b=2.3
```
- sacred
```python
from sacred import Experiment
ex = Experiment('exp')
@ex.config
def cfg():
    a = 3
    b = 4.5

@ex.automain
def run(a, b):
    some_func(a, b)
```
```bash
python main.py with a=5 b=2.3
```

### The benefits of sacred
`sacred` has many good features, but I point out two:

- Supports JSON inputting way: These two are equivalent each other.

```bash
% python main.py with a=5 b=2.3 c='foo'
```
```bash
echo '{"a": 5, "b": 2.3}' > config.json
python main.py with config.json c='foo'
```
- Supports hierarchical options by using `dict`
```python
from sacred import Experiment
ex = Experiment('exp')
@ex.config
def cfg():
    encoder_conf = {'a': 4, 'b': 8.4}

@ex.automain
def run(encoder_conf):
    Encoder(**encoder_conf)
```
```bash
python main.py with encoder_conf.a=4 encoder_conf.b=2.3 encoder_conf.c='foo'
```

The particular important thing is that you can use additional arguments without modifying any main codes as`encoder_conf.c='foo'`.

## The new style for an experiment
- run.sh
```bash
# As default configuration
train_conf=conf/training.json  
encoder_conf=conf/encoder.json

. parse_options.sh

asr_train.py with ${train_conf} ${encoder_conf}
```
- For single experiment
```bash
expdir=exp/foo
generate_training_conf.py > ${expdir}/training.json
generate_encoder_conf.py > ${expdir}/encoder.json
./run.sh --train_conf=${expdir}/training.json --encoder_conf=${expdir}/encoder.json
```
- If your new model is to be integrated with master branch: `RESULTS`
```
# conf/conventional/*.json
CER:  ...
WER: ...
# TITLE (summary of the configuration): conf/your/*.conf
CER:  ...
WER: ...
```

I launched this topic without thinking much, so this probably doesn't work in some cases.
I was told `sacred` by @LukasDrude a while ago, so he might have a better idea.

**Comment by LukasDrude** [comment]
Sacred has been our tool of choice for a few years now. The main benefits we make use of are:

- [File Storage Observer](https://sacred.readthedocs.io/en/latest/observers.html#file-observer): Most importantly, this logs the config, the code actually ran with. This simplifies reconstruction.
- Arbitrarily deep config: We pull the config of all child objects into the config such that the resulting log is complete, e.g. the log `config.json` will contain all parameters of `trainer`, `VAE`, `encoder` and `decoder` (in a VAE example).

However, Sacred is a little bit less expressive when it comes to choices or data types. Here is an example of `lm_train.py` from [here](https://github.com/espnet/espnet/blob/master/espnet/bin/lm_train.py):

``` python
import sacred

experiment = sacred.Experiment('lm_train')

@experiment.config
def config():
    # General configuration
    ngpu = 0  # Number of GPUs
    backend = 'chainer'  # chainer or pytorch
    assert backend in 'chainer pytorch'.split(), backend

    # If the outdir is sane should be checked by the trainer itself
    outdir = None  # Output directory

    # Debugmode should be true or false, not 0 or 1.
    debugmode = True

    # Can not be named `dict` since this is a Python buildin
    dictionary = None  # Debugmode

    seed = 1  # Random seed
    resume = []  # Resume the training from list of snapshots
    verbose = False

    # Task related
    train_label = None  # Filename of train label data
    valid_label = None  # Filename of validation label data
    test_label = None  # Filename of test label data
```

Subsequent code, e.g. the trainer then needs to do the validity check for `outdir`.

To illustrate what I mean with "pull in all child configurations", here is a small example of the config defined in the Sacred main file:

``` python
@ex.config
def config():
    debug = False
    batch_size = 4

    train_dataset = "mix_2_spk_min_tr"
    validate_dataset = "mix_2_spk_min_cv"

    # Start with an empty dict to allow tracking by Sacred
    trainer = {
        "model": {
            "factory": pt.models.bss.PermutationInvariantTrainingModel
        },
        "storage_dir": None,
        "optimizer": {
            "factory": pt.optimizer.Adam
        },
    }
    pt.Trainer.get_config(trainer)
    if trainer['storage_dir'] is None:
        trainer['storage_dir'] = get_new_folder(path_template, mkdir=False)
```

Later, the entire config which you can see when running  `python train.py print_config` will look like this:
``` python
Configuration (modified, added, typechanged, doc):
  batch_size = 4
  debug = False
  seed = 312777302                   # the random seed for this experiment
  train_dataset = 'mix_2_spk_min_tr'
  validate_dataset = 'mix_2_spk_min_cv'
  trainer:                           # Start with an empty dict to allow tracking by Sacred
    checkpoint_trigger = [1, 'epoch']
    factory = 'padertorch.train.trainer.Trainer'
    model:
      F = 257
      K = 2
      dropout_hidden = 0.0
      dropout_input = 0.0
      dropout_linear = 0.0
      factory = 'padertorch.models.bss.PermutationInvariantTrainingModel'
      output_activation = 'identity'
      recurrent_layers = 2
      units = 600
    optimizer:
      amsgrad = False
      betas = [0.9, 0.999]
      eps = 1e-08
      factory = 'padertorch.train.optimizer.Adam'
      gradient_clipping = 10000000000.0
      lr = 0.001
      weight_decay = 0
```

**Comment by sw005320** [comment]
That looks really cool. I was actually feeling about the limitation of the current ways of configurations, especially when I reviewed the PR of #551. We had to add a lot of options everywhere and this makes the python binary files (handling argparse options) and run.sh complicated, as @kamo-naoyuki pointed out. Also there are some certain requests of using config based configuration handling. This solution seems to satisfy both issues. @gtache, do you have some comments?

**Comment by gtache** [comment]
I'd never heard of sacred, but it seems to be a lot better than the current implementation (you can see that I tried to at least simplify the argparse part in my refactoring branch, but that didn't help with the run.sh files), and it seems that we would just have modify one file (`generate_x_conf`) to change an argument, which would be amazing!     
So if it delivers like expected it would be a lot better for further development.

**Comment by sw005320** [comment]
@gtache and @kamo-naoyuki, do you think custom layer configurations (e.g., #551) can be included? We may need to define the model definition configuration with a little bit more structured ways.

**Comment by ShigekiKarita** [comment]
Dear all, 

Long time no see but recently @kamo-naoyuki have proposed PR #722. Maybe it is time to make our first decision. He chooses https://github.com/bw2/ConfigArgParse rather than Sacred. I agree with him because sacred requires too many changes and decisions in our chaotic development in v0.4.0 (#650). Instead, @kamo-naoyuki implemented minimal CLI tools to support the config generation (log) and single inheritance. See #722 for details, we are still open for discussion.

(BTW my favorite is sacred. I wanna use it later after our recipe will get matured in v0.4.0)
