### ISSUE TITLE
How to extract voice embeddings?

### ISSUE THREAD

**Issue by maxpain** [espnet/espnet#5783]
Hello.

I have speech recordings in wav files, about 1-5 minutes each.
How do we extract embeddings using the `espnet/voxcelebs12_ecapa_wavlm_joint` SOTA model?

Documentation is overcomplicated. I can't find any Python examples of how to load a wav file and get embeddings without using some weird bash scripts.

**Comment by sw005320** [comment]
Thanks for your questions.
@Jungjee, can you answer it?
We have a nice Python interface to extract features, but we may need to refine our documents.

**Comment by ftshijt** [comment]
@maxpain We have a colab demonstration for the embedding extraction, you may check this https://colab.research.google.com/drive/1gizVM0T0O41cgY_sEHkf7eN-Xxl5YbWB?usp=sharing

**Comment by maxpain** [comment]
> https://colab.research.google.com/drive/1gizVM0T0O41cgY_sEHkf7eN-Xxl5YbWB?usp=sharing

Thanks!
How exactly this colab should be found in the docs? I didn't find it, I only found [this](https://github.com/espnet/notebook/tree/master/ESPnet2/Course) repository, but there are only assignments.

**Comment by ftshijt** [comment]
Hi @maxpain, thanks for your following up. We have not yet officially released the colab. The colab I shared is mostly for tentative view (though the API to embeddings is fixed already, so feel free to refer to the usage examples in the notebook). 

We expect to release the official notebook with regarding to our ESPnet-SPK paper in around two month later.

**Comment by maxpain** [comment]
Thanks!

**Comment by maxpain** [comment]
@sw005320 @ftshijt do you have some colab for speaker Diarization tasks?
