### ISSUE TITLE
Whisper attribute error tokenizer object has no attribute tokenizer

### ISSUE THREAD

**Issue by Yuanyuan-888** [espnet/espnet#5792]
Hi, I am using the latest version espnet 202402. The openai-whisper is also the latest one 202311. I would like to use whisper_large V3 to fine-tune. when at stage 5 in asr.sh, it shows the error of "Whisper attribute error tokenizer object has no attribute tokenizer"

**Comment by IceCreamWW** [comment]
for a quick fix, `pip install openai-whisper==20230308`, see https://github.com/jumon/whisper-punctuator/issues/7#issuecomment-1492913765
you may want to run `pip install openai-whisper==20230308 --no-dependencies` to prevent pip from installing another torch version, then run `pip install python-ffmpeg`  for whisper ffmpeg dependency

**Comment by Yuanyuan-888** [comment]
Hi thank you for your answer, then with whisper 20231117, I can use whisper large V3 to decode and finetune, if use version 20230308, I can only use whisper large V2. Could you please let me know if there is any solution to fix this bug but still use whisper large V3
