### ISSUE TITLE
How to download transformer LM from this repo?

### ISSUE THREAD

**Issue by Pooookeman** [espnet/espnet#5796]
Hi I'm currently starting to learn the espnet framework, and found confused in LM. When reading the Branchformer paper, I found that they mentioned they were using the transformer LM downloaded from ESPnet. I failed to find the LM checkpoint in the huggingface link, may I know how to download and use the LM from espnet? For example, if I were to use the pretrained transformer LM in the Librispeech/asr1, what argument would I use in the run.sh or asr.sh for that purpose? Thank you for your help~

**Comment by sw005320** [comment]
Thanks for your question.
@pyf98, can you tell me the pointer of which LM and its usage?

**Comment by pyf98** [comment]
Hi @Pooookeman , you can find the pre-trained model checkpoints in our hugging face repos, e.g.: https://huggingface.co/pyf98/librispeech_branchformer_e18_linear3072/tree/main/exp/lm_train_lm_transformer2_bpe5000_scheduler_confwarmup_steps25000_batch_bins500000000_accum_grad2_use_amptrue

You can pass this argument `--download_model pyf98/librispeech_branchformer_e18_linear3072` in `asr.sh` (or `run.sh`) to automatically download and uncompress a pre-trained ASR model: https://github.com/espnet/espnet/blob/master/egs2/TEMPLATE/asr1/asr.sh#L1447

**Comment by Pooookeman** [comment]
> Hi @Pooookeman , you can find the pre-trained model checkpoints in our hugging face repos, e.g.: https://huggingface.co/pyf98/librispeech_branchformer_e18_linear3072/tree/main/exp/lm_train_lm_transformer2_bpe5000_scheduler_confwarmup_steps25000_batch_bins500000000_accum_grad2_use_amptrue
> 
> You can pass this argument `--download_model pyf98/librispeech_branchformer_e18_linear3072` in `asr.sh` (or `run.sh`) to automatically download and uncompress a pre-trained ASR model: https://github.com/espnet/espnet/blob/master/egs2/TEMPLATE/asr1/asr.sh#L1447

Great, Thank you~
