### ISSUE TITLE
Regarding usage of parameters "num_iters_per_epoch" and "num_splits_asr" in ASR Task.

### ISSUE THREAD

**Issue by venkat01010** [espnet/espnet#5809]
Hi Thanks for great speech tool kit.  
I am using the Librispeech ASR recipe for training with my custom data. Due to CPU memory limitations, I am utilizing "num_splits_asr." Additionally, because of the large size of the data, I am using "num_iters_per_epoch" to save the checkpoints before processing the entire training dataset. My concern is whether, in the consecutive epoch, the same subset of each split is loaded for training or if subsets that were not used in the previous epoch are loaded.

To clarify, here are the example statistics:
Total number of batches in the training data: 100,000
num_splits_asr: 10
num_iters_per_epoch: 10,000
With these settings, by the end of the 10th epoch, will the model have seen the entire training dataset?
May be my question is too trivial. Can anyone give answer for the above question.

**Comment by sw005320** [comment]
> To clarify, here are the example statistics: Total number of batches in the training data: 100,000 num_splits_asr: 10 num_iters_per_epoch: 10,000 With these settings, by the end of the 10th epoch, will the model have seen the entire training dataset? May be my question is too trivial. Can anyone give answer for the above question.

Yes, the model would see the entire training dataset, then.

**Comment by venkat01010** [comment]
Thank you, @sw005320, for your reply; it helps a lot. I have a follow-up question. Suppose a model has been trained for 5 epochs and is then interrupted. When resuming the training, will the model only see the remaining training data (which was not seen during the previous 5 epochs) for the next consecutive 5 epochs?
