### ISSUE TITLE
<unk> and non-lang-symbols

### ISSUE THREAD

**Issue by gtache** [espnet/espnet#582]
I was wondering if leaving \<unk\> out of non-lang-syms makes sense. The problem right now is that \<unk\> is tokenized as `< u n k >` by data2json.sh.
![2019-02-12_12h22_04](https://user-images.githubusercontent.com/14289171/52632073-d265db80-2ec0-11e9-9641-7bfd1ab71a52.png)
You can see that if text2token.py isn't supplied with \<unk\> as a nls, it will be split, and other OOV words will be mapped to the non-split \<unk\> by sym2int I presume.     
I don't exactly know everything that is happening, but I know that the final result is that `<unk>` is split into `< u n k >` , whereas it should probably stay as a single token. The solution would be to include \<unk\> in non-lang-syms.txt for all recipes, or modify the other scripts to always consider it as a nls.

Example of the problem : 
![2019-02-12_12h35_19](https://user-images.githubusercontent.com/14289171/52632758-b5320c80-2ec2-11e9-8b56-6f298f87c7b7.png)

**Comment by sw005320** [comment]
Thanks for raising an issue.

> The solution would be to include <unk> in non-lang-syms.txt for all recipes,

This would be better, as it makes the whole recipe consistent. But I'm not sure whether it solves the issue or not. Could you test it with your case?

**Comment by b-flo** [comment]
Hi,

I faced the problem for some experiments a little time ago and I supplied `<unk>` as nlsyms as @gtache described. I can confirm it worked for me.

```
           "output": [                                                                                                                                                                                     
               {                                                                                                                                                                                           
                   "name": "target1",                                                                                                                                                                      
                   "shape": [                                                                                                                                                                              
                       91,                                                                                                                                                                                 
                       46                                                                                                                                                                                  
                   ],                                                                                                                                                                                      
                   "text": "qu' il persistait justement dans ce sens là <unk>",                                                                              
                   "token": "q u ' <space> i l <space> p e r s i s t a i t <space> j u s t e m e n t <space> d a n s <space> c e <space> s e n s <space> l à <space> <unk>",                                                                                               
                    "tokenid": "21 25 4 3 13 16 3 20 9 22 23 13 23 24 5 13 24 3 14 25 23 24 9 17 9 18 24 3 8 5 18 23 3 7 9 3 23 9 18 23 3 16 31 3 1"                                       
                } 
``` 

However I'm still wondering if it make sense to do a one-to-one mapping from word level to character level for unknown words?
On the same note, for BPE I had to remove `<unk>` when training model (it was not recognized and we can't specify `<unk>` as user_defined_symbols) and map `<unk>` to another non-used symbols to force sym2Int to map to the correct `<unk>` id (supplied to nlsyms).

**Comment by gtache** [comment]
Yes, that solves it as @b-flo said. I can work on a PR for this.     
And I confirm the same problem with BPE.
