### ISSUE TITLE
batch decoding for ASR

### ISSUE THREAD

**Issue by WZLHQ** [espnet/espnet#5861]
**batch decoding for ASR**
hi
Would you plan to implement batch decoding for ASR? Until now, the batch size of ASR decoding has been restricted to 1. This makes decoding **extremely slow**, especially for a **large model** (like Whisper-medium) and a **large test set** (like 100+ hours). Toolkits, like Transformers and Wenet, all provide batch decoding. I am looking forward to your reply.

task: ASR
recipe: aishell/asr1
GPU: NVIDIA 3090

**Comment by sw005320** [comment]
@WZLHQ, thanks for your input.
If you test it, could you give us the numbers?

Note that we did not observe a large slowness before since we already performed the batch decoding across the hypothesis. 
The transformer encoder has parallelization across the frame.
By considering most use cases, we thought that the current support would be enough.
However, we did not test it with a large model.

**Comment by WZLHQ** [comment]
> @WZLHQ, thanks for your input. If you test it, could you give us the numbers?
> 
> Note that we did not observe a large slowness before since we already performed the batch decoding across the hypothesis. The transformer encoder has parallelization across the frame. By considering most use cases, we thought that the current support would be enough. However, we did not test it with a large model.


For sure. I fine-tuned Whisper-medium on my private corpus. I use the **egs2**/aishell/asr1 recipe. 
In the run.sh, I set the following args:
> inference_nj=2, gpu_inference=true, ngpu=1


The calculate_rtf.log of one of my test set is as follow. As you can see, Espnet needs 3.68 hours to decode 2.31-hour test set. In fact, the audio duration all my test sets is around 180 hours, which means it will cost me 290 hours (=12 days). This might be unacceptable.
> Total audio duration: 2.31 hours 
> Total decoding time: 3.68 hours
> RTF: 1.593
> Latency: 9100.779 [ms/sentence]


Two factors might cause this slow-decoding issue. One is that the Whisper-medium is too large, having 0.7 billion parameters. The other might be Epsenet2 only surport batch size of 1 during decoding see: https://github.com/espnet/espnet/blob/5acc3c876254204830256dd8d85795359addae74/espnet2/bin/asr_inference.py#L751-L752
Therefore, I am kindly asking if you have plans to implement batch decoding. If the implementation process is inconvenient, that's fine too. However, I might consider using other toolkits. 

have a nice day. I am looking forward to your reply.

by the way:
> I try the batch gpu decoding by setting _ngpu_ to 2,  still only one GPU is used.
> I also try large inference_nj, like 8, only 2 asr_inference.*.log files are created at the same time (actually, 8 asr_inference.*.log files should be created at the same time).

**Comment by sw005320** [comment]
Thanks for the details.
I'm not sure that batch decoding will solve this since the model is too large, and we may not be able to increase the batch size so much.
Also, this sounds too slow to me compared with others' reports.
You may decrease the beam size.
You can also try the other framework.

**Comment by WZLHQ** [comment]
> Thanks for the details. I'm not sure that batch decoding will solve this since the model is too large, and we may not be able to increase the batch size so much. Also, this sounds too slow to me compared with others' reports. You may decrease the beam size. You can also try the other framework.

Thanks for your advice, decreasing the beam size helps a lot.
