### ISSUE TITLE
When will the next release happen?

### ISSUE THREAD

**Issue by duguyue100** [espnet/espnet#5907]
**Describe your question**

The latest version was released in February, since then, more than 1.5k commits have been merged. Is there a planned release in the coming month(s)?

Having a release would be great as there are many interesting new features and we can stop installing the cutting-edge version which may or may not break. Furthermore, there are places that block downloading arbitrary code from Github, and pypi is a more secured place.

**Comment by sw005320** [comment]
Thanks a lot for pinging it.
We're a bit lazy about this.

@kan-bayashi, can you initiate it?

**Comment by Fhrozen** [comment]
@duguyue100 , you can find the new release at https://github.com/espnet/espnet/releases/tag/v.202409.

**Comment by duguyue100** [comment]
Awesome, thanks!

**Comment by duguyue100** [comment]
@Fhrozen I assume this will be available in pypi very quickly?
