### ISSUE TITLE
RNN transducer

### ISSUE THREAD

**Issue by sw005320** [espnet/espnet#591]
There are several requests for the RNN transducer implementation. For me, transformer #555 is higher priority, but since Google spends a lot of efforts on this direction (mainly due to the online processing I believe), we could also consider to implement it. I welcome any comments and suggestions. Also, it would be great if someone volunteer to help the development.

**Comment by b-flo** [comment]
Hi,

I started working on a RNN implementation two months ago for my current analysis but I discarded it as I couldn't reproduce state-of-art performances and lacked time. I wanted to work on it again starting mid-march so I would gladly help the development!

**Comment by sw005320** [comment]
This is great!

**Comment by fanlu** [comment]
May [https://github.com/HawkAaron/warp-transducer/tree/master](url) [https://github.com/awni/transducer](url) will be helpful.

**Comment by b-flo** [comment]
Hi,

 Sorry for the delay, I had to finish some papers and projects before working on the RNN Transducer. I'll start working on the implementation this week!
