### ISSUE TITLE
Possibility to access the model.bin and config.json of this Spanish Hubert?

### ISSUE THREAD

**Issue by Mixomo** [espnet/espnet#5917]
https://huggingface.co/espnet/mediaspeech-spanish-hubert/tree/main

It would be of great importance to have access to these files, as it would allow using this Spanish Hubert in projects like RVC to extract the characteristics of a dataset in Spanish before passing the training.
Thank you.

**Comment by sw005320** [comment]
Our recipe only supports the French version
https://github.com/espnet/espnet/blob/master/egs2/mediaspeech/asr1/README.md#hugging-face
The Spanish version seems to be uploaded without our standard upload protocol.
So, it would be better to ask it at https://huggingface.co/espnet/mediaspeech-spanish-hubert, and you seemed to do so.
So, I hope you get a response there.

**Comment by Mixomo** [comment]
All right, thank you very much.
