### ISSUE TITLE
wsj0_2mix_data_prep

### ISSUE THREAD

**Issue by buptzzy2018** [espnet/espnet#5928]
I would like to ask how the mix_2_stpk_max_tr-mix/mix_2_stpk_max_cv_ix/mix_2_stpk_max_tx_tt_mix file is obtained when processing wsj0 data. The downloaded script for processing WSJ data in deep clustering does not include these files

**Comment by sw005320** [comment]
it is generated via https://github.com/espnet/espnet/blob/master/egs2/wsj0_2mix/enh1/local/wsj0_create_mixture.sh
this is called in the data preparation stage via https://github.com/espnet/espnet/blob/master/egs2/wsj0_2mix/enh1/local/data.sh
