### ISSUE TITLE
Assistance with Finetuning OWSM-CTC Model on Custom Dataset

### ISSUE THREAD

**Issue by Zilai-WANG** [espnet/espnet#5930]
I’m currently working on finetuning your OWSM-CTC model on a custom dataset, but I’ve encountered some challenges. It seems that finetuning OWSM-CTC differs from the standard OWSM finetuning process, and I’ve noticed the following differences:

	1.	The trainer.py file in the local Espnet repository (yifan's version) only accepts dump files, whereas the main Espnet repository allows the use of CSV files.
	2.	Finetuning the OWSM-CTC requires additional files such as prefix and text_prev, which are not needed when finetuning the regular OWSM models that only require audio, text, and text_ctc.

Could you kindly provide any guidance, hints, or scripts to help with finetuning the OWSM-CTC model on custom datasets? Your assistance would be greatly appreciated!

Reference Links:
OWSM-CTC Model:       https://huggingface.co/pyf98/owsm_ctc_v3.1_1B
OWSM Finetuning Tutorial:     https://espnet.github.io/espnet/notebook/ESPnetEZ/ASR/ASR_finetune_owsm.html

**Comment by Masao-Someki** [comment]
@Zilai-WANG  
Thank you for creating this issue. After reviewing the code, I believe that if we want to fine-tune OWSM-CTC with ESPnetEZ, we first need to merge the code into the ESPnet library. Alternatively, you could clone or fork Yifan’s repository and then merge the latest ESPnet version.

If you try fine-tuning OWSM-CTC without ESPnetEZ, it will only accept dump files, and we may need to ask Yifan for assistance with data preparation.

@pyf98  
Could you create a PR to add OWSM-CTC to ESPnet? I think it would be helpful for others looking to train and fine-tune the model.

Also, I have a few questions regarding data preparation for OWSM-CTC:
- Is there any difference in the `text_prev` input between OWSM-v3.1 and OWSM-CTC?
  - If not, can we simply set `<na>` as `text_prev` for fine-tuning OWSM-CTC? Should this parameter vary depending on the task?
- Which script did you use to prepare the `prefix` and `text_prev`? It would be helpful if you could share the link.
- Is there any difference between `text_ctc` and `text` in OWSM-v3.1 and OWSM-CTC?

**Comment by pyf98** [comment]
Thanks for the discussion. I will work on merging OWSM-CTC into ESPnet this week. It requires some work.

**Comment by pyf98** [comment]
OWSM-CTC will be added in this PR: https://github.com/espnet/espnet/pull/5933

Please check `S2TCTCPreprocessor` for `prefix`. It is the embeddings of the task and language tokens.

For data format:

> The training data follows the same format as the encoder-decoder OWSM v3.1, except that timestamps are removed from the `text` file. Please first follow the `egs2/owsm_v3.1/s2t1` recipe to prepare OWSM data, and then convert `text` into the new format by running `python local/convert_owsm_data.py` (the path to the BPE tokenizer needs to be modified to your path).

**Comment by pyf98** [comment]
The OWSM-CTC PR has been merged into the main branch. @Masao-Someki Can we start to prepare a fine-tuning example?

**Comment by Houss3m** [comment]
Were you able to finetune the model from espnet? As in the s2t.sh I can't see --pretrained_mode, --init_param or --resume to initiate the weights from a pretrained model as it is in asr.sh files. Any thoughts or tutorials on fine tuning owsm ctc model using espnet?
