### ISSUE TITLE
copy_data_dir.sh: no such file data//utt2spk in stage1

### ISSUE THREAD

**Issue by CClemonjj** [espnet/espnet#5934]
日本語で失礼いたします。
1点、質問させていただきます

質問概要：
egs2/jvs/tts1において、finetune_vits.yamlを用いて学習しようとしているのですが、stage1にて「copy_data_dir.sh: no such file data//utt2spk」というエラーが発生し、エラーが治らなくて困っています。

環境：
・python version: 3.8.19
・espnet version: 202402
・pytorch version: 2.0.1

run.sh　ファイル：
`
#!/usr/bin/env bash
# Set bash to 'debug' mode, it will exit on :
# -e 'error', -u 'undefined variable', -o ... 'error in pipeline', -x 'print commands',
set -e
set -u
set -o pipefail

fs=24000
n_fft=2048
n_shift=300
win_length=1200

#opts=
#if [ "${fs}" -eq 24000 ]; then
    # To suppress recreation, specify wav format
    #opts="--audio_format wav "
#else
    #opts="--audio_format flac "
#fi

opts="--audio_format wav "

spk=jvs010
train_set=${spk}_tr_no_dev
valid_set=${spk}_dev
test_sets="${spk}_dev ${spk}_eval1"

#train_set=tr_no_dev
#valid_set=dev
#test_sets="dev eval1"

train_config=conf/tuning/finetune_vits.yaml
inference_config=conf/decode.yaml

# Input example: こ、こんにちは

# 1. Phoneme + Pause
# (e.g. k o pau k o N n i ch i w a)
g2p=pyopenjtalk

# 2. Kana + Symbol
# (e.g. コ 、 コ ン ニ チ ワ)
# g2p=pyopenjtalk_kana

# 3. Phoneme + Accent
# (e.g. k 1 0 o 1 0 k 5 -4 o 5 -4 N 5 -3 n 5 -2 i 5 -2 ch 5 -1 i 5 -1 w 5 0 a 5 0)
# g2p=pyopenjtalk_accent

# 4. Phoneme + Accent + Pause
# (e.g. k 1 0 o 1 0 pau k 5 -4 o 5 -4 N 5 -3 n 5 -2 i 5 -2 ch 5 -1 i 5 -1 w 5 0 a 5 0)
# g2p=pyopenjtalk_accent_with_pause

# 5. Phoneme + Prosody symbols
# (e.g. ^, k, #, o, _, k, o, [, N, n, i, ch, i, w, a, $)
# g2p=pyopenjtalk_prosody

export CUDA_VISIBLE_DEVICES=3

./tts.sh \
    --lang jp \
    #--local_data_opts "--spk ${spk}" \
    --feats_type raw \
    --fs "${fs}" \
    --n_fft "${n_fft}" \
    --n_shift "${n_shift}" \
    --win_length "${win_length}" \
    --token_type phn \
    --cleaner jaconv \
    --g2p "${g2p}" \
    --train_config "${train_config}" \
    --inference_config "${inference_config}" \
    --train_set "${train_set}" \
    --valid_set "${valid_set}" \
    --test_sets "${test_sets}" \
    --srctexts "data/${train_set}/text" \
    --tts_task gan_tts \
    --use_spk_embed true \
    --spk_embed_tag xvector \
    --spk_embed_gpu_inference true \
    --spk_embed_tool kaldi \
    ${opts} "$@"
`

エラー文：

```
s266170@jupytergpu:~/notebooks6/espnet/egs2/jvs/tts1$ ./run.sh --stage 1 --stop-stage 1
2024-10-23T17:46:53 (tts.sh:216:main) ./tts.sh --lang jp
2024-10-23T17:46:54 (tts.sh:312:main) Stage 1: Data preparation for data/, data/, etc.
2024-10-23T17:46:54 (data.sh:17:main) local/data.sh 
2024-10-23T17:46:55 (data.sh:40:main) stage -1: local/data_download.sh
Already exists. Skipped.
2024-10-23T17:46:55 (data.sh:45:main) stage 0: local/data_prep.sh
finished making wav.scp, utt2spk, spk2utt.
finished making text.
finished making segments.
fix_data_dir.sh: kept all 100 utterances.
fix_data_dir.sh: old files are kept in data/jvs010_parallel100/.backup
finished making wav.scp, utt2spk, spk2utt.
finished making text.
finished making segments.
utils/fix_data_dir.sh: file data/jvs010_nonpara30/text is not in sorted order or not unique, sorting it
utils/fix_data_dir.sh: filtered data/jvs010_nonpara30/wav.scp from 30 to 29 lines based on filter /tmp/kaldi.zjii/recordings.
fix_data_dir.sh: kept 29 utterances out of 30
fix_data_dir.sh: old files are kept in data/jvs010_nonpara30/.backup
Successfully finished data preparation.
2024-10-23T17:46:58 (data.sh:50:main) stage 2: utils/subset_data_dir.sh
utils/copy_data_dir.sh: copied data from data/jvs010_parallel100 to data/jvs010_tr_no_dev
utils/validate_data_dir.sh: WARNING: you have only one speaker.  This probably a bad idea.
   Search for the word 'bold' in http://kaldi-asr.org/doc/data_prep.html
   for more information.
utils/validate_data_dir.sh: Successfully validated data-directory data/jvs010_tr_no_dev
utils/subset_data_dir.sh: reducing #utt from 29 to 15
utils/subset_data_dir.sh: reducing #utt from 29 to 15
2024-10-23T17:46:58 (data.sh:57:main) Successfully finished. [elapsed=4s]
2024-10-23T17:46:58 (tts.sh:328:main) Stage 2: Format wav.scp: data/ -> dump/raw/
copy_data_dir.sh: no such file data//utt2spk
```

**Comment by sw005320** [comment]
`data//utt2spk`となっています
本来は`data/<data directory>/utt2spk`となるはずなので
https://github.com/espnet/espnet/blob/master/egs2/TEMPLATE/tts1/tts.sh#L329
のどれかの`dset`がemptyだと思います
確認してください

**Comment by CClemonjj** [comment]
![スクリーンショット 2024-10-24 112759](https://github.com/user-attachments/assets/3ac1c759-db6c-417d-9598-def373b61ada)
上の画像のとおり、dsetが存在していると思われます。

**Comment by CClemonjj** [comment]
![スクリーンショット 2024-10-24 144057](https://github.com/user-attachments/assets/ca2bb51e-9f05-47a8-afd1-cf6982ab7f10)
中身もしっかり入っていることが確認できました

**Comment by kamo-naoyuki** [comment]
>  data//utt2spk
//のようになっているのは//の間にシェル変数が入っていて、しかし、そのシェル変数が空という意味です（ディレクトリーが存在していないという意味ではないです）。
こうした場合、まず動作方法が間違っていることをまず疑います。

espnetのシェルスクリプトは、渡された引数をログとして表示するようになっていて、

> 2024-10-23T17:46:53 (tts.sh:216:main) ./tts.sh --lang jp

のように引数が渡っていないことがわかります。

それで、

```
./tts.sh
--lang jp
#--local_data_opts "--spk ${spk}"
```

単純に、コメントアウトのせいで、コマンドが途中で切れていると思われます。

**Comment by CClemonjj** [comment]
問題なく実行できました。お忙しい所丁寧に教えていただきありがとうございました。
