### ISSUE TITLE
Some questions related to the multi-speaker ASR recipe on librimix

### ISSUE THREAD

**Issue by hiranoyu0830** [espnet/espnet#5935]
Hello👋
I have some questions related to [the multi-speaker ASR recipe on librimix](https://github.com/espnet/espnet/tree/master/egs2/librimix/asr1)

1. Is this recipe based on any papers?
2. Can the model trained using this recipe recognize (theoretically) a flexible number of speakers? 
3. If the answer of Q2 is no, is there any way to make the model to be able to recognize a flexible number of speakers? (e.g. adaptation)

Thank you in advance!

**Comment by sw005320** [comment]
1. This recipe is based on SOT https://arxiv.org/abs/2003.12687
2. theoretically yes, but it depends on the training data

**Comment by hiranoyu0830** [comment]
Thank you for your answer, but you seem to be referring to the recipe in `egs2/librimix/sot_asr1`.
What about the recipe in `egs2/librimix/asr1`? I mean the one that involves permutation invariant training (PIT).
Sorry for my ambiguous question.

**Comment by hiranoyu0830** [comment]
Thank you very much!
I will take a look at those papers.
