### ISSUE TITLE
Do you have any plans to upload the data preparation script for the AMUSE recipe?

### ISSUE THREAD

**Issue by ashi-ta** [espnet/espnet#5937]
Thank you for all the work on this project; it’s been incredibly helpful!

I have a question regarding the AMUSE recipe.
I'm trying to reproduce several neural codec models, but it seems that the data preparation files for AMUSE have not been uploaded yet.

For example, based on my understanding, a `data.sh` file is generally needed for data preprocessing, but there doesn’t appear to be any data preparation shell script available (i.e., https://github.com/espnet/espnet/tree/master/egs2/amuse/codec1/local).

Do you have any plans to upload the preparation shell script file?

Thanks again!

**Comment by sw005320** [comment]
@ftshijt, can you answer it?

**Comment by ftshijt** [comment]
Thanks for reaching out! We do have plans to release the data preparation scripts (as similar to other recipes) before the SLT conference (where the paper was accepted)

As indicated in the paper, AMUSE is a collection of datasets from other corpora. The main difficulty is to deal with various sources from its raw format. While the codec-task only needs specific wav.scp, you may consider creating scp on your own before our official release if you would like to go ahead sooner. I'm happy to help you with the train-val-test split upon requests~

**Comment by ashi-ta** [comment]
Thank you for your detailed response and the information on the data preparation scripts.

I am currently downloading all the necessary corpora.
Since this process takes a while, I may have additional questions (or re-open this issue) regarding data splitting once it’s complete.

For now, I will close this issue. Thank you again for your project!
