### ISSUE TITLE
Bug appear when prepare dataset for owsm_v1 in Stage 3 

### ISSUE THREAD

**Issue by oggyfaker** [espnet/espnet#5952]
hi @pyf98 
I got the bug when run data preparation for stage 3 for only librispeech dataset. 

Here is my bug:

<img width="1484" alt="Screenshot 2024-11-13 at 10 37 23" src="https://github.com/user-attachments/assets/f91eee03-d101-4137-ae38-a3a7c6721f16">

My `run.sh` contains:
<img width="801" alt="Screenshot 2024-11-13 at 10 39 32" src="https://github.com/user-attachments/assets/2aca1a59-351f-455c-bd9e-3c2b1a06b0e1">

And my wav.scp contains the content like this : 
`
LibriSpeech_1001_134707 sox /Users/fruit/Desktop/espnet/egs2/owsm_v1/s2t1/downloads/mp3/1001/134707/134707.mp3 -t wav -c 1 -r 16000 - |
LibriSpeech_1001_134708 sox /Users/fruit/Desktop/espnet/egs2/owsm_v1/s2t1/downloads/mp3/1001/134708/134708.mp3 -t wav -c 1 -r 16000 - |
LibriSpeech_1006_135212 sox /Users/fruit/Desktop/espnet/egs2/owsm_v1/s2t1/downloads/mp3/1006/135212/135212.mp3 -t wav -c 1 -r 16000 - |
LibriSpeech_100_121669 sox /Users/fruit/Desktop/espnet/egs2/owsm_v1/s2t1/downloads/mp3/100/121669/121669.mp3 -t wav -c 1 -r 16000 - |
`

Although i install all the package `kaldiio`, my system cant understand the `sox` command.
Hope to see your answer !

**Comment by pyf98** [comment]
Hi, it says "sox: command not found". Did you install `sox`? If you follow the full ESPnet installation, it will need to install `sox`: https://espnet.github.io/espnet/installation.html

Sometimes, the raw audio is in `flac` format, so we often need `sox` with `flac` support.
