### ISSUE TITLE
TypeError: unsupported operand type(s) for *: 'NoneType' and 'int'

### ISSUE THREAD

**Issue by CriDora** [espnet/espnet#5955]
Hello, when I used fastspeech2 in espnet to train the TTS model, the following error occurred when running to stage5. I have been troubleshooting for a long time but have not found the problem. The detailed error information is as follows

Model summary:
    Class Name: ESPnetTTSModel
    Total Number of model parameters: 37.10 M
    Number of trainable parameters: 37.10 M (100.0%)
    Size: 148.4 MB
    Type: torch.float32
Optimizer:
Adam (
Parameter Group 0
    amsgrad: False
    betas: (0.9, 0.999)
    capturable: False
    differentiable: False
    eps: 1e-08
    foreach: None
    fused: None
    initial_lr: 1.0
    lr: 2.0171788261496964e-07
    maximize: False
    weight_decay: 0
)
Scheduler: NoamLR(model_size=384, warmup_steps=4000)
Saving the configuration in exp/tts_stats_raw_char/logdir/stats.9/config.yaml
Namespace(accum_grad=8, allow_variable_data_keys=False, batch_bins=3000000, batch_size=20, batch_type='numel', best_model_criterion=[['valid', 'loss', 'min'], ['train', 'loss', 'min']], bpemodel=None, chunk_excluded_key_prefixes=[], chunk_length=500, chunk_shift_ratio=0.5, cleaner=None, collect_stats=True, config='conf/train_fastspeech2.yaml', create_graph_in_tensorboard=False, cudnn_benchmark=False, cudnn_deterministic=True, cudnn_enabled=True, detect_anomaly=False, dist_backend='nccl', dist_init_method='env://', dist_launcher=None, dist_master_addr=None, dist_master_port=None, dist_rank=None, dist_world_size=None, distributed=False, drop_last_iter=False, dry_run=False, early_stopping_criterion=('valid', 'loss', 'min'), energy_extract='energy', energy_extract_conf={'fs': 22050, 'n_fft': 1024, 'hop_length': 256, 'win_length': None, 'reduction_factor': 1}, energy_normalize=None, energy_normalize_conf={}, exclude_weight_decay=False, exclude_weight_decay_conf={}, feats_extract='fbank', feats_extract_conf={'n_fft': 1024, 'hop_length': 256, 'win_length': None, 'fs': 22050, 'fmin': 80, 'fmax': 7600, 'n_mels': 80}, fold_length=[], freeze_param=[], g2p=None, grad_clip=1.0, grad_clip_type=2.0, grad_noise=False, ignore_init_mismatch=False, init_param=[], iterator_type='sequence', keep_nbest_models=5, local_rank=None, log_interval=None, log_level='INFO', max_cache_fd=32, max_cache_size=0.0, max_epoch=1000, model_conf={}, multiple_iterator=False, multiprocessing_distributed=False, nbest_averaging_interval=0, ngpu=2, no_forward_run=False, non_linguistic_symbols=None, normalize=None, normalize_conf={}, num_att_plot=3, num_cache_chunks=1024, num_iters_per_epoch=800, num_workers=1, odim=None, optim='adam', optim_conf={'lr': 1.0}, output_dir='exp/tts_stats_raw_char/logdir/stats.9', patience=None, pitch_extract='dio', pitch_extract_conf={'fs': 22050, 'n_fft': 1024, 'hop_length': 256, 'f0max': 400, 'f0min': 80, 'reduction_factor': 1}, pitch_normalize=None, pitch_normalize_conf={}, pretrain_path=None, print_config=False, required=['output_dir', 'token_list'], resume=False, scheduler='noamlr', scheduler_conf={'model_size': 384, 'warmup_steps': 4000}, seed=0, sharded_ddp=False, shuffle_within_batch=False, sort_batch='descending', sort_in_batch='descending', token_list=['<blank>', '<unk>', 'i', '<space>', 'a', 'E', 'n', 'l', 'r', 't', 'u', 'K', 'A', 'm', 'y', 'k', 'd', 's', 'x', 'b', 'o', 'p', 'e', 'N', 'v', 'q', 'z', 'G', 'g', 'w', 'H', 'O', 'h', 'j', 'f', 'Z', '<sos/eos>'], token_type='char', train_data_path_and_name_and_type=[('dump/raw/train/text', 'text', 'text'), ('dump/raw/train/wav.scp', 'speech', 'sound')], train_dtype='float32', train_shape_file=['exp/tts_stats_raw_char/logdir/train.9.scp'], tts='fastspeech2', tts_conf={'adim': 384, 'aheads': 2, 'elayers': 4, 'eunits': 1536, 'dlayers': 4, 'dunits': 1536, 'positionwise_layer_type': 'conv1d', 'positionwise_conv_kernel_size': 3, 'duration_predictor_layers': 2, 'duration_predictor_chans': 256, 'duration_predictor_kernel_size': 3, 'postnet_layers': 5, 'postnet_filts': 5, 'postnet_chans': 256, 'use_masking': True, 'use_scaled_pos_enc': True, 'encoder_normalize_before': True, 'decoder_normalize_before': True, 'reduction_factor': 1, 'init_type': 'xavier_uniform', 'init_enc_alpha': 1.0, 'init_dec_alpha': 1.0, 'transformer_enc_dropout_rate': 0.2, 'transformer_enc_positional_dropout_rate': 0.2, 'transformer_enc_attn_dropout_rate': 0.2, 'transformer_dec_dropout_rate': 0.2, 'transformer_dec_positional_dropout_rate': 0.2, 'transformer_dec_attn_dropout_rate': 0.2, 'pitch_predictor_layers': 5, 'pitch_predictor_chans': 256, 'pitch_predictor_kernel_size': 5, 'pitch_predictor_dropout': 0.5, 'pitch_embed_kernel_size': 1, 'pitch_embed_dropout': 0.0, 'stop_gradient_from_pitch_predictor': True, 'energy_predictor_layers': 2, 'energy_predictor_chans': 256, 'energy_predictor_kernel_size': 3, 'energy_predictor_dropout': 0.5, 'energy_embed_kernel_size': 1, 'energy_embed_dropout': 0.0, 'stop_gradient_from_energy_predictor': False}, unused_parameters=False, use_amp=False, use_matplotlib=True, use_preprocessor=True, use_tensorboard=True, use_wandb=False, val_scheduler_criterion=('valid', 'loss'), valid_batch_bins=None, valid_batch_size=None, valid_batch_type=None, valid_data_path_and_name_and_type=[('dump/raw/dev/text', 'text', 'text'), ('dump/raw/dev/wav.scp', 'speech', 'sound')], valid_iterator_type=None, valid_max_cache_size=None, valid_shape_file=['exp/tts_stats_raw_char/logdir/valid.9.scp'], version='202308', wandb_entity=None, wandb_id=None, wandb_model_log_interval=-1, wandb_name=None, wandb_project=None, write_collected_feats=False)
/home/lhw523/anaconda3/envs/espnet/bin/python3 /s1home/lhw523/espnet/espnet2/bin/tts_train.py --collect_stats true --write_collected_feats false --use_preprocessor true --token_type char --token_list dump/token_list/char/tokens.txt --non_linguistic_symbols none --cleaner none --g2p none --normalize none --pitch_normalize none --energy_normalize none --train_data_path_and_name_and_type dump/raw/train/text,text,text --train_data_path_and_name_and_type dump/raw/train/wav.scp,speech,sound --valid_data_path_and_name_and_type dump/raw/dev/text,text,text --valid_data_path_and_name_and_type dump/raw/dev/wav.scp,speech,sound --train_shape_file exp/tts_stats_raw_char/logdir/train.9.scp --valid_shape_file exp/tts_stats_raw_char/logdir/valid.9.scp --output_dir exp/tts_stats_raw_char/logdir/stats.9 --config conf/train_fastspeech2.yaml --feats_extract fbank --feats_extract_conf n_fft=1024 --feats_extract_conf hop_length=256 --feats_extract_conf win_length=null --feats_extract_conf fs=22050 --feats_extract_conf fmin=80 --feats_extract_conf fmax=7600 --feats_extract_conf n_mels=80 --pitch_extract_conf fs=22050 --pitch_extract_conf n_fft=1024 --pitch_extract_conf hop_length=256 --pitch_extract_conf f0max=400 --pitch_extract_conf f0min=80 --energy_extract_conf fs=22050 --energy_extract_conf n_fft=1024 --energy_extract_conf hop_length=256 --energy_extract_conf win_length=null
/s1home/lhw523/espnet/espnet2/schedulers/noam_lr.py:40: UserWarning: NoamLR is deprecated. Use WarmupLR(warmup_steps=4000) with Optimizer(lr=0.0008068715304598786)
  warnings.warn(
The length of the text output exceeds 500, which may cause OOM on the GPU.Please ensure that the data processing is correct and verify it.
Traceback (most recent call last):
  File "/home/lhw523/anaconda3/envs/espnet/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/lhw523/anaconda3/envs/espnet/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/s1home/lhw523/espnet/espnet2/bin/tts_train.py", line 22, in <module>
    main()
  File "/s1home/lhw523/espnet/espnet2/bin/tts_train.py", line 18, in main
    TTSTask.main(cmd=cmd)
  File "/s1home/lhw523/espnet/espnet2/tasks/abs_task.py", line 1082, in main
    cls.main_worker(args)
  File "/s1home/lhw523/espnet/espnet2/tasks/abs_task.py", line 1272, in main_worker
    collect_stats(
  File "/home/lhw523/anaconda3/envs/espnet/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/s1home/lhw523/espnet/espnet2/main_funcs/collect_stats.py", line 72, in collect_stats
    data = data_parallel(
  File "/home/lhw523/anaconda3/envs/espnet/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 234, in data_parallel
    outputs = parallel_apply(replicas, inputs, module_kwargs, used_device_ids)
  File "/home/lhw523/anaconda3/envs/espnet/lib/python3.8/site-packages/torch/nn/parallel/parallel_apply.py", line 89, in parallel_apply
    output.reraise()
  File "/home/lhw523/anaconda3/envs/espnet/lib/python3.8/site-packages/torch/_utils.py", line 644, in reraise
    raise exception
TypeError: Caught TypeError in replica 0 on device 0.
Original Traceback (most recent call last):
  File "/home/lhw523/anaconda3/envs/espnet/lib/python3.8/site-packages/torch/nn/parallel/parallel_apply.py", line 64, in _worker
    output = module(*input, **kwargs)
  File "/home/lhw523/anaconda3/envs/espnet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/s1home/lhw523/espnet/espnet2/torch_utils/forward_adaptor.py", line 33, in forward
    return func(*args, **kwargs)
  File "/s1home/lhw523/espnet/espnet2/tts/espnet_model.py", line 198, in collect_feats
    pitch, pitch_lengths = self.pitch_extract(
  File "/home/lhw523/anaconda3/envs/espnet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/s1home/lhw523/espnet/espnet2/tts/feats_extract/dio.py", line 110, in forward
    durations = durations * self.reduction_factor
TypeError: unsupported operand type(s) for *: 'NoneType' and 'int'

**Comment by sw005320** [comment]
My concern is this error.
`TypeError: Caught TypeError in replica 0 on device 0.`
Can you check that your GPU environment is correct?

**Comment by sw005320** [comment]
I see that the error brings the device error.
Thanks for the clarification.
`fastspeech2` is the most frequent method, and we have to fix it.

Could you tell me your environment, command lines, etc.?
It would be great if you use our bug report template.

**Comment by CriDora** [comment]
> I see that the error brings the device error. Thanks for the clarification. `fastspeech2` is the most frequent method, and we have to fix it.
> 
> Could you tell me your environment, command lines, etc.? It would be great if you use our bug report template.

OK, where can I find a template for the report?

**Comment by sw005320** [comment]
When you create an issue, you'd have an option to select it.

<img width="1462" alt="image" src="https://github.com/user-attachments/assets/684bc8ce-ec75-4d8f-b478-dbdab29b8b3c">

**Comment by ftshijt** [comment]
Closing it as it is duplicated to https://github.com/espnet/espnet/issues/5956
