### ISSUE TITLE
inference with owsm_v3.1_ebf_small

### ISSUE THREAD

**Issue by bloodraven66** [espnet/espnet#5973]
I am decoding with [owsm 3.1 small model](https://huggingface.co/espnet/owsm_v3.1_ebf_small) and having the following error while building the model - 

TypeError: __init__() got an unexpected keyword argument 'attention_qk_norm'

I see that the config file of the pretrained model has attention_qk_norm in ebranchformer encoder config, but current version of ebranchformer no longer has this. Should this be changed to [qk_norm](https://github.com/espnet/espnet/blob/master/espnet2/asr/encoder/e_branchformer_encoder.py)?

 

**Basic environments:**
 - Python 3.8.20 (default, Oct 15 2024, 11:13:24) 
 - espnet version: 202412 (latest as of December 5th 2024)
 - pytorch version - 2.3.0+cu121

**Task information:**
 - Task: S2T
 - Recipe: librispeech
 - ESPnet2

**To Reproduce**
1. download owsm 3.1 small pretrained model - huggingface_hub.snapshot_download(repo_id="espnet/owsm_v3.1_ebf_small")
2. fix paths for feats_stats.npz and bpe.model in pretrained config
3. run inference

```
dataset="librispeech"
test_sets="$dataset/test-clean $dataset/test-other"
inference_config=conf/decode_ctc1_bs1_lang-en_task-asr.yaml

./s2t.sh \
    --stage 12 \
    --lang en \
    --ngpu 0 \
    --gpu_inference false \
    --inference_nj 8 \
    --feats_type raw_copy \
    --use_lm false \
    --skip_data_prep false \
    --inference_s2t_model "valid.total_count.ave_5best.pth" \
    --skip_train true \
    --s2t_exp "<path>/s2t_train_s2t_ebf_conv2d_size768_e9_d9_piecewise_lr5e-4_warmup60k_flashattn_raw_bpe50000" \
    --inference_config "${inference_config}" \
    --test_sets "${test_sets}" "$@"
```
```
beam_size: 1
penalty: 0.0
maxlenratio: 0.0
minlenratio: 0.0
ctc_weight: 1.0
lm_weight: 0.0
lang_sym: <eng>
task_sym: <asr>
predict_time: false
```

**Error logs**
    main()
  File "/mnt/matylda4/udupa/exps/ctc_spec_decoding/espnet/espnet2/bin/s2t_inference.py", line 1103, in main
    inference(**kwargs)
  File "/mnt/matylda4/udupa/exps/ctc_spec_decoding/espnet/espnet2/bin/s2t_inference.py", line 809, in inference
    speech2text = Speech2Text.from_pretrained(
  File "/mnt/matylda4/udupa/exps/ctc_spec_decoding/espnet/espnet2/bin/s2t_inference.py", line 707, in from_pretrained
    return Speech2Text(**kwargs)
  File "/mnt/matylda4/udupa/exps/ctc_spec_decoding/espnet/espnet2/bin/s2t_inference.py", line 206, in __init__
    s2t_model, s2t_train_args = S2TTask.build_model_from_file(
  File "/mnt/matylda4/udupa/exps/ctc_spec_decoding/espnet/espnet2/tasks/abs_task.py", line 2301, in build_model_from_file
    model = cls.build_model(args)
  File "/mnt/matylda4/udupa/exps/ctc_spec_decoding/espnet/espnet2/tasks/s2t.py", line 502, in build_model
    encoder = encoder_class(input_size=input_size, **args.encoder_conf)
TypeError: __init__() got an unexpected keyword argument 'attention_qk_norm'

Note: owsm 3.1 base decoding runs successfully, it does not have `attention_qk_norm` in it's config.

**Comment by sw005320** [comment]
Thanks for the report, @bloodraven66.
@pyf98, can you answer this?

**Comment by pyf98** [comment]
Hi, thanks for the report. I removed those arguments from the model config. Can you try this model again? Please let us know if there is any issue.

**Comment by bloodraven66** [comment]
Works fine now, thank you @pyf98 !

**Comment by kalvinchang** [comment]
Fixed for the owsm_v3.1_ebf_small_lowrestriction model as well:

https://huggingface.co/espnet/owsm_v3.1_ebf_small_lowrestriction/blob/main/exp/s2t_train_s2t_ebf_conv2d_size768_e9_d9_piecewise_lr5e-4_warmup60k_flashattn_raw_bpe50000/config.yaml
