### ISSUE TITLE
VAD on fbank_pitch features

### ISSUE THREAD

**Issue by brijmohan** [espnet/espnet#598]
Hi @sw005320 @kan-bayashi ,

I want to `compute_vad_decision` on the features obtained from `make_fbank_pitch.sh`. Could you please help me set the proper configurations in conf/vad.conf?

Here are the default configurations for mfcc features.
```
--vad-energy-threshold=5.5
--vad-energy-mean-scale=0.5
--vad-proportion-threshold=0.12
--vad-frames-context=2
```

Any idea how to deduce right values for fbank_pitch features?

**Comment by sw005320** [comment]
I haven't played with it.
How about simply using `make_fbank.sh` or `make_mfcc.sh`?
We'd not have big difference with this change.

**Comment by brijmohan** [comment]
Ok. As David Snyder suggested, if I use `--use-energy=true` with fbank_pitch features, I might get desired results with the `sid/compute_vad_decision` script. I will test this and get back with results.

Thanks!

**Comment by brijmohan** [comment]
After using `--use-energy=true` in `conf/fbank.conf` I am able to use `sid/compute_vad_decision` as expected. Closing this issue. Thanks!
