### ISSUE TITLE
Duration mismatch of text, pitch and energy in FastSpeech2 training in ESPnet2-TTS

### ISSUE THREAD

**Issue by unilight** [espnet/espnet#5990]
I am facing the same issue as #3318. That is, I also have the following error when training ESPnet2-TTS FastSpeech2.

```
  File "/data/group1/z44476r/Experiments/espnet/espnet2/tts/fastspeech2/fastspeech2.py", line 544, in forward
    before_outs, after_outs, d_outs, p_outs, e_outs = self._forward(
  File "/data/group1/z44476r/Experiments/espnet/espnet2/tts/fastspeech2/fastspeech2.py", line 676, in _forward
    hs = hs + e_embs + p_embs
RuntimeError: The size of tensor a (62) must match the size of tensor b (61) at non-singleton dimension 1
```

So I try to print `xs`, `es` and `ps` at this line: https://github.com/espnet/espnet/blob/master/espnet2/tts/fastspeech2/fastspeech2.py#L622, and this is what I get:

```
xs torch.Size([32, 62])
ps torch.Size([32, 61, 1])
es torch.Size([32, 61, 1])
```

I see that we pad 0 at the end of text at this line: https://github.com/espnet/espnet/blob/master/espnet2/tts/fastspeech2/fastspeech2.py#L532,
but we don't do that for pitch and energy right? Although here: https://github.com/espnet/espnet/blob/master/espnet2/tts/fastspeech2/fastspeech2.py#L508-L511 the document says their length should be `T_text + 1`, but as I printed them, they aren't.

I wonder if anyone has successfully trained a FastSpeech2 model recently?

For context, I am trying to train a FastSpeech2 on JVS, and I wrote my own scripts to get the duration of each phoneme (I used Julius). It might be difficult to reproduce this error, but I just wonder where the padding of the pitch and energy was performed.

**Comment by longtou-2024** [comment]
I am not sure also but in my understanding, espnet `durations` file already consider text eos token by appending 0 value

https://github.com/espnet/espnet/blob/master/egs2/TEMPLATE/asr1/pyscripts/utils/mfa_format.py#L317

**Comment by sw005320** [comment]
Thanks, @unilight and @longtou-2024, for raising an issue and discussion.
@kan-bayashi, can you clarify it?

**Comment by kan-bayashi** [comment]
eos is added as the last token, and therefore, the length of input text will be the length of original text + 1.
Since we need to match the length of duration with the input text, we can add 0 in each duration as @longtou-2024 said.

**Comment by unilight** [comment]
I see, thanks for the clarification!

For now, I am removing the eos token in the text, and I haven't encountered any problems so far.

I am not sure if other people are experiencing the same problem, so I'll just close this comment for now.
