### ISSUE TITLE
Download failed in the installation of mecab-ipadic-NEologd

### ISSUE THREAD

**Issue by tfygg** [espnet/espnet#606]
install-mecab-ipadic-NEologd] : Make mecab-ipadic-NEologd
[make-mecab-ipadic-NEologd] : Start..
[make-mecab-ipadic-NEologd] : Check local seed directory
[make-mecab-ipadic-NEologd] : Check local seed file
[make-mecab-ipadic-NEologd] : Check local build directory
[make-mecab-ipadic-NEologd] : create /home/luban/tongfeiyang/speech/espnet/tools/mecab/mecab-ipadic-neologd/libexec/../build
[make-mecab-ipadic-NEologd] : Download original mecab-ipadic file
Makefile:105: recipe for target 'mecab.done' failed
make: *** [mecab.done] Error 7

**Comment by kan-bayashi** [comment]
Could you test the patch #608?

**Comment by ZhishengWang** [comment]
same error occured on ubuntu16.04, tested on patch #622：
[make-mecab-ipadic-NEologd] : Check local seed directory
[make-mecab-ipadic-NEologd] : Check local seed file
[make-mecab-ipadic-NEologd] : Check local build directory
[make-mecab-ipadic-NEologd] : create /home/zswang/githubs/espnet/tools/mecab/mecab-ipadic-neologd/libexec/../build
[make-mecab-ipadic-NEologd] : Download original mecab-ipadic file
Makefile:105: recipe for target 'mecab.done' failed
make: *** [mecab.done] Error 7

**Comment by kan-bayashi** [comment]
I could find the reason from this error.
Could you run `make` without `-j` option?

**Comment by kan-bayashi** [comment]
I checked NEologd installation code, It uses google drive to download files.
I doubt that you cannot use google drive.

**Comment by ZhishengWang** [comment]
Thanks. Google service is blocked in my country, I will try to figure out if this is the reason for the issue. Belowings are the logs realted to NEologd installation when run with **make mecab.done**:

cd mecab && git clone --depth 1 https://github.com/neologd/mecab-ipadic-neologd.git
Cloning into 'mecab-ipadic-neologd'...
remote: Enumerating objects: 75, done.
remote: Counting objects: 100% (75/75), done.
remote: Compressing objects: 100% (74/74), done.
remote: Total 75 (delta 5), reused 55 (delta 0), pack-reused 0
Unpacking objects: 100% (75/75), done.
Checking connectivity... done.
cd mecab/mecab-ipadic-neologd && export PATH=/home/zswang/githubs/espnet/tools/mecab/bin:/home/zswang/anaconda3/envs/pytorch-py37/bin:/home/zswang/bin:/home/zswang/.local/bin:/home/zswang/anaconda3/bin:/usr/local/cuda-9.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/zswang/eclipse-workspace/kaldi/tools/openfst:/home/zswang/eclipse-workspace/kaldi/src/featbin:/home/zswang/eclipse-workspace/kaldi/src/gmmbin:/home/zswang/eclipse-workspace/kaldi/src/bin:/home/zswang/eclipse-workspace/kaldi/src/nnetbin && ./bin/install-mecab-ipadic-neologd -n -y -p /home/zswang/githubs/espnet/tools/mecab/mecab-ipadic-neologd
[install-mecab-ipadic-NEologd] : Start..
[install-mecab-ipadic-NEologd] : Check the existance of libraries
[install-mecab-ipadic-NEologd] :     find => ok
[install-mecab-ipadic-NEologd] :     sort => ok
[install-mecab-ipadic-NEologd] :     head => ok
[install-mecab-ipadic-NEologd] :     cut => ok
[install-mecab-ipadic-NEologd] :     egrep => ok
[install-mecab-ipadic-NEologd] :     mecab => ok
[install-mecab-ipadic-NEologd] :     mecab-config => ok
[install-mecab-ipadic-NEologd] :     make => ok
[install-mecab-ipadic-NEologd] :     curl => ok
[install-mecab-ipadic-NEologd] :     sed => ok
[install-mecab-ipadic-NEologd] :     cat => ok
[install-mecab-ipadic-NEologd] :     diff => ok
[install-mecab-ipadic-NEologd] :     tar => ok
[install-mecab-ipadic-NEologd] :     unxz => ok
[install-mecab-ipadic-NEologd] :     xargs => ok
[install-mecab-ipadic-NEologd] :     grep => ok
[install-mecab-ipadic-NEologd] :     iconv => ok
[install-mecab-ipadic-NEologd] :     patch => ok
[install-mecab-ipadic-NEologd] :     which => ok
[install-mecab-ipadic-NEologd] :     file => ok
[install-mecab-ipadic-NEologd] :     openssl => ok
[install-mecab-ipadic-NEologd] :     awk => ok

[install-mecab-ipadic-NEologd] : mecab-ipadic-NEologd is already up-to-date

[install-mecab-ipadic-NEologd] : mecab-ipadic-NEologd will be install to /home/zswang/githubs/espnet/tools/mecab/mecab-ipadic-neologd

[install-mecab-ipadic-NEologd] : Make mecab-ipadic-NEologd
[make-mecab-ipadic-NEologd] : Start..
[make-mecab-ipadic-NEologd] : Check local seed directory
[make-mecab-ipadic-NEologd] : Check local seed file
[make-mecab-ipadic-NEologd] : Check local build directory
[make-mecab-ipadic-NEologd] : create /home/zswang/githubs/espnet/tools/mecab/mecab-ipadic-neologd/libexec/../build
[make-mecab-ipadic-NEologd] : Download original mecab-ipadic file
make: *** [mecab.done] Error 7
Makefile:105: recipe for target 'mecab.done' failed

**Comment by kan-bayashi** [comment]
Actually, the installation of `mecab.done` is needed for only the Japanese TTS recipe `egs/just/tts1`.
So maybe you can skip it.
I made minimum installation in Makefile (#628).
It will help you.

**Comment by ZhishengWang** [comment]
The installation succeeded withou installing mecab, thanks @kan-bayashi !

**Comment by kan-bayashi** [comment]
I will close this issue.
