### ISSUE TITLE
Unable to train on multi GPU

### ISSUE THREAD

**Issue by SujathaSIyer** [espnet/espnet#607]
I tried training on 2 GPU's (GeForce 1080Ti) with the same hyper parameters as specified in the code on the LibriSpeech 100 hour clean dataset using the attention mode and Pytorch as backend. Both the GPU utilisation is always 0% and there is no progress in training even after 2-3 hours. 
Pytorch version : 0.4.1
I tried with Pytorch 1.0 too and I faced the same problem again. 
PS : Training on single GPU works fine. 
Please let me know if I am missing out on something.

**Comment by sw005320** [comment]
@kan-bayashi, could you reply? I haven't used multiple GPUs for a while....

**Comment by kan-bayashi** [comment]
I will test it.

**Comment by kan-bayashi** [comment]
I tested with csj recipe using default conda setting (python 3.7).
It looks woking correctly. GPU utilization of both gpus is around 80~90 %.

```bash
# Running on aventador.sp.m.is.nagoya-u.ac.jp
# Started at Wed Feb 27 00:11:42 JST 2019
# SLURMD_NODENAME=aventador
# SLURM_CHECKPOINT_IMAGE_DIR=/var/slurm/checkpoint
# SLURM_CLUSTER_NAME=dsplab_cluster
# SLURM_CPUS_ON_NODE=1
# SLURM_EXPORT_ENV=PATH
# SLURM_GET_USER_ENV=1
# SLURM_GTIDS=0
# SLURM_JOBID=278241
# SLURM_JOB_CPUS_PER_NODE=1
# SLURM_JOB_GID=1000001
# SLURM_JOB_GPUS=1,3
# SLURM_JOB_ID=278241
# SLURM_JOB_NAME=train.sh
# SLURM_JOB_NODELIST=aventador
# SLURM_JOB_NUM_NODES=1
# SLURM_JOB_PARTITION=hpc
# SLURM_JOB_UID=1000032
# SLURM_JOB_USER=t_hayashi
# SLURM_LOCALID=0
# SLURM_NNODES=1
# SLURM_NODEID=0
# SLURM_NODELIST=aventador
# SLURM_NODE_ALIASES='(null)'
# SLURM_NPROCS=1
# SLURM_NTASKS=1
# SLURM_NTASKS_PER_NODE=1
# SLURM_OPEN_MODE=a
# SLURM_PRIO_PROCESS=0
# SLURM_PROCID=0
# SLURM_SUBMIT_DIR=/work4/t_hayashi/debug/espnet/egs/csj/asr1
# SLURM_SUBMIT_HOST=chikaku1.sp.m.is.nagoya-u.ac.jp
# SLURM_TASKS_PER_NODE=1
# SLURM_TASK_PID=16590
# SLURM_TOPOLOGY_ADDR=aventador
# SLURM_TOPOLOGY_ADDR_PATTERN=node
# SLURM_WORKING_CLUSTER=dsplab_cluster:192.168.1.50:6817:8448
# asr_train.py --ngpu 2 --backend pytorch --outdir exp/train_nodup_sp_pytorch_vggblstm_e4_subsample1_2_2_1_1_unit1024_proj1024_d1_unit1024_location_adim1024_aconvc10_aconvf100_mtlalpha0.5_adadelta_sampprob0.0_drop0.2_bs32_mli800_mlo150/results --tensorboard-dir tensorboard/train_nodup_sp_pytorch_vggblstm_e4_subsample1_2_2_1_1_unit1024_proj1024_d1_unit1024_location_adim1024_aconvc10_aconvf100_mtlalpha0.5_adadelta_sampprob0.0_drop0.2_bs32_mli800_mlo150 --debugmode 1 --dict data/lang_1char/train_nodup_sp_units.txt --debugdir exp/train_nodup_sp_pytorch_vggblstm_e4_subsample1_2_2_1_1_unit1024_proj1024_d1_unit1024_location_adim1024_aconvc10_aconvf100_mtlalpha0.5_adadelta_sampprob0.0_drop0.2_bs32_mli800_mlo150 --minibatches 0 --seed 1 --verbose 0 --resume --train-json dump/train_nodup_sp/deltafalse/data.json --valid-json dump/train_dev/deltafalse/data.json --etype vggblstm --elayers 4 --eunits 1024 --eprojs 1024 --subsample 1_2_2_1_1 --dlayers 1 --dunits 1024 --atype location --adim 1024 --awin 5 --aheads 4 --aconv-chans 10 --aconv-filts 100 --mtlalpha 0.5 --batch-size 32 --maxlen-in 800 --maxlen-out 150 --sampling-probability 0.0 --dropout-rate 0.2 --opt adadelta --sortagrad 0 --epochs 8 --patience 3
2019-02-27 00:11:43,200 (asr_train:195) WARNING: Skip DEBUG/INFO messages
2019-02-27 00:11:49,459 (e2e_asr:85) WARNING: Subsampling is not performed for vgg*. It is performed in max pooling layers at CNN.
epoch       iteration   main/loss   main/loss_ctc  main/loss_att  validation/main/loss  validation/main/loss_ctc  validation/main/loss_att  main/acc    validation/main/acc  main/cer_ctc  validation/main/cer_ctc  elapsed_time  eps
0           100         204.682     224.515        184.849                                                                                  0.148742                         1.01079                                129.63        1e-08
     total [..................................................]  0.06%
this epoch [..................................................]  0.44%
       100 iter, 0 epoch / 8 epochs
       inf iters/sec. Estimated time to finish: 0:00:00.

0           200         185.751     205.201        166.302                                                                                  0.208365                         0.99983                                260.074       1e-08
     total [..................................................]  0.11%
this epoch [..................................................]  0.88%
       200 iter, 0 epoch / 8 epochs
   0.76661 iters/sec. Estimated time to finish: 2 days, 17:28:48.128461.
```

Which environment do you use? (e.g. conda with python3)
And could you attach your train.log?

**Comment by SujathaSIyer** [comment]
> # asr_train.py --ngpu 2 --backend pytorch --outdir exp/train_100_pytorch_vggblstm_e5_subsample1_2_2_1_1_unit1024_proj1024_d2_unit1024_location_aconvc10_aconvf100_mtlalpha0.0_adadelta_sampprob0.0_bs20_mli800_mlo150/results --debugmode 1 --dict data/lang_char/train_100_unigram5000_units.txt --debugdir exp/train_100_pytorch_vggblstm_e5_subsample1_2_2_1_1_unit1024_proj1024_d2_unit1024_location_aconvc10_aconvf100_mtlalpha0.0_adadelta_sampprob0.0_bs20_mli800_mlo150 --minibatches 0 --verbose 0 --resume --train-json dump/train_100/deltafalse/data_unigram5000.json --valid-json dump/dev/deltafalse/data_unigram5000.json --etype vggblstm --elayers 5 --eunits 1024 --eprojs 1024 --subsample 1_2_2_1_1 --dlayers 2 --dunits 1024 --atype location --adim 1024 --aconv-chans 10 --aconv-filts 100 --mtlalpha 0.0 --batch-size 20 --maxlen-in 800 --maxlen-out 150 --sampling-probability 0.0 --opt adadelta --epochs 10 
# Started at Wed Feb 27 05:51:34 IST 2019
#
2019-02-27 05:51:35,098 (asr_train:169) WARNING: Skip DEBUG/INFO messages
2019-02-27 05:51:36,806 (e2e_asr_th:257) WARNING: Subsampling is not performed for vgg*. It is performed in max pooling layers at CNN.
/home/Sujatha/ESPNet/espnet/tools/venv/local/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py:24: UserWarning: 
    There is an imbalance between your GPUs. You may want to exclude GPU 1 which
    has less than 75% of the memory or cores of GPU 0. You can do so by setting
    the device_ids argument to DataParallel, or by setting the CUDA_VISIBLE_DEVICES
    environment variable.
  warnings.warn(imbalance_warn.format(device_ids[min_pos], device_ids[max_pos]))



This is my train.log. Using pip virtual environment on Python 3.6. On trying to find out more about htis error, I came across this issue thread on Pytorch thread.
https://discuss.pytorch.org/t/waining-there-is-an-imbalance-between-your-gpus/17157/3

Both my GPU's are of the same config (1080Ti)I tried doing what was suggested there (**from future import division**). I still seem to run into the same issue. 
Apologies for forgetting to post the  train.log earlier.
