### ISSUE TITLE
vocab 

### ISSUE THREAD

**Issue by zh794390558** [espnet/espnet#612]
https://github.com/espnet/espnet/blob/cb3e479b33d9d23eb58f6d8f30ed207dcd20846b/utils/data2json.sh#L77

https://github.com/espnet/espnet/blob/afc458e988aabeff1ede336e443f491e9d326d04/egs/librispeech/asr1/run.sh#L181

Does this conflict?

I think the vocab maybe like below:
```
blank  0
unk   1
xxx
xx
...
xxx    20
<s>    21
</s>  22
```

**Comment by zh794390558** [comment]
@sw005320 Does it ?

**Comment by sw005320** [comment]
Sorry that I don't fully get the point. Our usual vocab set is like that
```
<unk> 1
! 2
" 3
& 4
' 5
( 6
) 7
* 8
, 9
- 10
. 11
/ 12
: 13
; 14
<*IN*> 15
<*MR.*> 16
<NOISE> 17
<space> 18
? 19
A 20
B 21
C 22
D 23
E 24
F 25
G 26
H 27
I 28
J 29
K 30
L 31
M 32
N 33
O 34
P 35
Q 36
R 37
S 38
T 39
U 40
V 41
W 42
X 43
Y 44
Z 45
_ 46
` 47
{ 48
} 49
~ 50
```
And then, internally, we'll add two additional symbols (which corresponds to the comment of "+2 comes from CTC blank and EOS ")
```
<blank> 0
<eos> 51
```

**Comment by zh794390558** [comment]
thanks, my fault , i think the last two symbols is <blank> and <eos>. Maybe adding doc of vocab is useful.

**Comment by sw005320** [comment]
Thanks. Will do.
