### ISSUE TITLE
Error while install mecab-python3

### ISSUE THREAD

**Issue by coalboss** [espnet/espnet#621]
while **PATH=$(PWD)/swig/bin:$(PWD)/mecab/bin:$(PATH) pip install mecab-python3**, there is a error:

1. Collecting mecab-python3
2.   Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7fe4446514a8>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /simple/mecab-python3/
3.   Using cached https://files.pythonhosted.org/packages/ac/48/295efe525df40cbc2173748eb869290e81a57e835bc41f6d3834fc5dad5f/mecab-python3-0.996.1.tar.gz
4. Building wheels for collected packages: mecab-python3
5.   Building wheel for mecab-python3 (setup.py) ... error
6.   Complete output from command /home/hangchen/.conda/envs/espnet_py37/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-xaezj77b/mecab-python3/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-gzdbrlct --python-tag cp37:
7.   running bdist_wheel
8.   running build
9.   running build_py
10.   running build_ext
11.   building '_MeCab' extension
12.   swigging MeCab.i to MeCab_wrap.cpp
13.   swig -python -shadow -c++ -I/home/hangchen/tools/espnet-master/tools/mecab/include -o MeCab_wrap.cpp MeCab.i
14.   swig: error while loading shared libraries: libpcre.so.1: cannot open shared object file: No such file or directory
15.   error: command 'swig' failed with exit status 127
16.   
17.   ----------------------------------------
18.   Failed building wheel for mecab-python3
19.   Running setup.py clean for mecab-python3
20. Failed to build mecab-python3
21. Installing collected packages: mecab-python3
22.   Running setup.py install for mecab-python3 ... error
23.     Complete output from command /home/hangchen/.conda/envs/espnet_py37/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-xaezj77b/mecab-python3/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-68m2p1fo/install-record.txt --single-version-externally-managed --compile:
24.     running install
25.     running build
26.     running build_py
27.     running build_ext
28.     building '_MeCab' extension
29.     swigging MeCab.i to MeCab_wrap.cpp
30.     swig -python -shadow -c++ -I/home/hangchen/tools/espnet-master/tools/mecab/include -o MeCab_wrap.cpp MeCab.i
31.     swig: error while loading shared libraries: libpcre.so.1: cannot open shared object file: No such file or directory
32.     error: command 'swig' failed with exit status 127
33.     
34.     ----------------------------------------
35. Command "/home/hangchen/.conda/envs/espnet_py37/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-xaezj77b/mecab-python3/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-68m2p1fo/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-xaezj77b/mecab-python3/
36. Makefile:105: recipe for target 'mecab.done' failed
37. make: *** [mecab.done] Error 1
But, i already install libprce3-dev, what can do with this error?

**Comment by EgorLakomkin** [comment]
Same thing

**Comment by kan-bayashi** [comment]
I will check it. Could you tell your environment?

**Comment by EgorLakomkin** [comment]
Mine is Ubuntu 16.04

**Comment by kan-bayashi** [comment]
@coalboss @EgorLakomkin Could you test this patch #622?

**Comment by coalboss** [comment]
I use this method to install mecab successfully.
sudo apt-get install mecab mecab-ipadic-utf8 libmecab-dev swig
pip install mecab-python3

**Comment by EgorLakomkin** [comment]
@kan-bayashi worked like a charm, thank you!

**Comment by MohammedAmmar2** [comment]
Running setup.py install for mecab-python3 ... error
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\My PC\Anaconda3\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\MYPC~1\\AppData\\Local\\Temp\\pip-install-jfc1zfzx\\mecab-python3\\setup.py'"'"'; __file__='"'"'C:\\Users\\MYPC~1\\AppData\\Local\\Temp\\pip-install-jfc1zfzx\\mecab-python3\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\MYPC~1\AppData\Local\Temp\pip-record-l3ui5_pw\install-record.txt' --single-version-externally-managed --compile
         cwd: C:\Users\MYPC~1\AppData\Local\Temp\pip-install-jfc1zfzx\mecab-python3\
    Complete output (9 lines):
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.7
    creating build\lib.win-amd64-3.7\MeCab
    copying src\MeCab\__init__.py -> build\lib.win-amd64-3.7\MeCab
    running build_ext
    error: [WinError 2] The system cannot find the file specified
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Users\My PC\Anaconda3\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\MYPC~1\\AppData\\Local\\Temp\\pip-install-jfc1zfzx\\mecab-python3\\setup.py'"'"'; __file__='"'"'C:\\Users\\MYPC~1\\AppData\\Local\\Temp\\pip-install-jfc1zfzx\\mecab-python3\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\MYPC~1\AppData\Local\Temp\pip-record-l3ui5_pw\install-record.txt' --single-version-externally-managed --compile Check the logs for full command output.

please help me, error in anaconda promt
