### ISSUE TITLE
Decoding Results 

### ISSUE THREAD

**Issue by karanMal** [espnet/espnet#626]
After decoding is done there is a file generated results.wrd.txt in which there are two rows Sum/Avg and mean like in the following screenshot 
![image](https://user-images.githubusercontent.com/15909866/53898923-15017a80-405f-11e9-9af3-16ee65dd0808.png)
So which of the value should be considered if I want to post my results somewhere.

**Comment by sw005320** [comment]
Please use the `Sum/Avg` line.

**Comment by karanMal** [comment]
Okay, thanks.
