### ISSUE TITLE
Resume acoustic model training

### ISSUE THREAD

**Issue by dbj15** [espnet/espnet#636]
Hi,

My neural network training (stage 4 in run.sh) in ESPnet using Chainer back-end was stopped because of a gpu machine crash problem. The training was stopped at the 13th epoch out of 15 epoches.

I see that there is an option --resume to continue the training in run.sh and asr_train.py. However, it is not clear how I can pass this option to the run.sh script to continue the training. I have been trying with this option for a while but it did now work. The name of the snapshot file that I want to resume the training from is snapshot.ep.13

Could you please help with this?

Many thanks!
JD

**Comment by b-flo** [comment]
Hi,

You have to specify the path to the snapshot file. It should look like this : 

`--resume ${expdir}/results/snapshot.ep.5`

**Comment by dbj15** [comment]
It works.
Thank you very much.

**Comment by Sunny-Hui** [comment]
Hello, I come across following issue when resuming acoustic model following this,
  "return self._iterators['main'].previous_epoch_detail
AttributeError: 'ChainerDataLoader' object has no attribute 'previous_epoch_detail'"
  Have you also come across this?
  Thanks a lot!
