### ISSUE TITLE
inference speed is really slow

### ISSUE THREAD

**Issue by lixx0105** [espnet/espnet#652]
Hi there,

I've been testing ctc+attention joint method on AISHELL 1 CHINESE dataset recently. The WER result looks very good but the inference speed is really slow... like it takes 15sec to predict a 5sec long audio..
Can you kindly give some advice on this? Thanks a lot. 

ps. i'm using pytorch and following the code in egs/aishell

**Comment by lixx0105** [comment]
Hi,
i just did a quick test and found the speed per utterance is much faster if i reduce the #jobs.
Bigger OMP_NUM_THREADS also helps. 
thanks.

**Comment by kan-bayashi** [comment]
In the recipe, we decode recog set using 32 parallel jobs, so we limit OMP_NUM_THREADS=1.
If your machine has less than 32 threads, it is better to resuce #jobs.

Also, we provide gpu / cpu batch decoding.
It is much faster than usual decoding.
(But it has a problem in the case of large vocabulary size now #470)

**Comment by lixx0105** [comment]
@kan-bayashi Thanks for your reply. From your experience, what is RTF we can achieve for this joint decoding method?
My test shows that decoding with beam size 3 or 5 has roughly 1x RTF for the aishell case (4233 vocabulary size), does this make sense to you? 
If I want to achieve 10x RTF, definitely I need to reduce the model size and most probably degrade the WER performance.

Thanks again.

**Comment by sw005320** [comment]
> My test shows that decoding with beam size 3 or 5 has roughly 1x RTF for the aishell case (4233 vocabulary size), does this make sense to you?

I observed the similar speed.

> If I want to achieve 10x RTF, definitely I need to reduce the model size and most probably degrade the WER performance.

Or you can use GPU for decoding.
Making the decoder faster is one of our ongoing items.

**Comment by lixx0105** [comment]
hi @sw005320 , thanks for your advice and I'll try GPU decoding.
