### ISSUE TITLE
How to save model within epoch

### ISSUE THREAD

**Issue by lixx0105** [espnet/espnet#657]
hi,
I found the code only save model once per epoch. Can we do the evaluation and model saving after some training steps rather than after one whole epoch?

thanks.

**Comment by sw005320** [comment]
You can do it by changing the following line
```
    trainer.extend(torch_snapshot(), trigger=(1, 'epoch'))
```
to (e.g., every 100 training iterations)
```
    trainer.extend(torch_snapshot(), trigger=(100, 'iteration'))
```
in https://github.com/espnet/espnet/blob/master/espnet/asr/pytorch_backend/asr.py#L370

You can do the same thing for the evaluator by adding `trigger = (100, 'iteration')` in the argument of the CustomEvaluator

**Comment by lixx0105** [comment]
@sw005320 thanks, it works.
