### ISSUE TITLE
ami recipe: RuntimeError: The keys are mismatch

### ISSUE THREAD

**Issue by shinotk15** [espnet/espnet#659]
In run.sh in the ami recipe, the following command is skipped in the default setting.
   if [ ! -d data/local/downloads ]; then
       local/ami_text_prep.sh data/local/downloads
   fi
But then, the following error occurs.
Error: File data/local/annotations/train.txt no found (run ami_text_prep.sh).

If we comment out the "if" condition and force the ami_text_prep.sh script is executed, data/local/annotations/train.txt is created.

However, then we encounter the following error:
RuntimeError: The keys are mismatch at 64th line between "data/ihm_train/tmp-5tXmf/input/feat.scp" and "data/ihm_train/tmp-5tXmf/output/shape.scp":

Could you give us a hint was is wrong?

**Comment by sw005320** [comment]
@kamo-naoyuki, can you check it?
I also have the same error
```
/export/a08/shinji/201707e2e/espnet_dev6/egs/ami/asr1/../../../utils/data2json.sh --feat dump/ihm_train/deltafalse/feats.scp data/ihm_train data/lang_1char/ihm_train_units.txt
/export/a08/shinji/201707e2e/espnet_dev6/egs/ami/asr1/../../../utils/feat_to_shape.sh --cmd run.pl --nj 1 --filetype  --preprocess-conf  --verbose 0 dump/ihm_train/deltafalse/feats.scp data/ihm_train/tmp-tZGl1/input/shape.scp
Traceback (most recent call last):
  File "/export/a08/shinji/201707e2e/espnet_dev6/egs/ami/asr1/../../../utils/merge_scp2json.py", line 180, in <module>
    first.rstrip(), line.rstrip()))
RuntimeError: The keys are mismatch at 64th line between "data/ihm_train/tmp-tZGl1/input/feat.scp" and "data/ihm_train/tmp-tZGl1/output/shape.scp":
>>> AMI_EN2001a_H00_MEE068_0225260_0225392 /export/a08/shinji/201707e2e/espnet_dev6/egs/ami/asr1/dump/ihm_train/deltafalse/feats.1.ark:745507
>>> AMI_EN2001a_H00_MEE068_0218806_0218816 3,35
```

**Comment by kamo-naoyuki** [comment]
@sw005320 Can you apply `validate_data_dir.sh` to data/ihm_train? 
The feats.scp or text seems to have a problem. They must have same and sorted ids due to my recent changing.

**Comment by kamo-naoyuki** [comment]
It is possible if the feature extraction was failed, then we need to use `fix_data_dir.sh`.

https://github.com/kaldi-asr/kaldi/blob/1ac8c922cbf6b2c34756d4b467cfa6067a6dba90/egs/wsj/s5/steps/make_fbank_pitch.sh#L170-L173

The duration time, i.e. 0218816 - 0218806 = 100ms, looks too short, but I'm not sure.

**Comment by sw005320** [comment]
@shinotk15, can you confirm whether #660 fix your issue?

**Comment by shinotk15** [comment]
Thank you for the update and I'm sorry for my late response.
I have confirmed that the "RuntimeError: The keys are mismatch at 64th line" has been solved.
The same level of WERs as the RESULT file is obtained.
When I run run.sh, I manually commented out "if [ ! -d data/local/downloads ]; then" condition.
I tested it on a CentOS7 machine with NVIDIA driver of version 410.78.

**Comment by Fahim-F** [comment]
In run.sh in the commonvoice with the language=fa, the following error has occurred:

make json files
/../../espnet/egs/commonvoice/asr1/../../../utils/data2json.sh --feat dump/train_fa/deltafalse/feats.scp --bpecode data/fa_lang_char/train_fa_unigram150.model data/train_fa data/fa_lang_char/train_fa_unigram150_units.txt
/../../espnet/egs/commonvoice/asr1/../../../utils/feat_to_shape.sh --cmd run.pl --nj 1 --filetype  --preprocess-conf  --verbose 0 dump/train_fa/deltafalse/feats.scp data/train_fa/tmp-1qGUk/input_1/shape.scp
Traceback (most recent call last):
  File "/../../espnet/egs/commonvoice/asr1/../../../utils/merge_scp2json.py", line 207, in <module>
    concat[0][1], concat[count][1]
**RuntimeError: The number of lines mismatch between: "data/train_fa/tmp-1qGUk/input_1/feat.scp" and "data/train_fa/tmp-1qGUk/output/shape.scp"**

I did not change anything in the run.sh except lang=fa
How can I resolve this problem?
