### ISSUE TITLE
AttributeError: 'list' object has no attribute 'repeat' in recognize_batch( ) because hlens is not a torch.tensor( )

### ISSUE THREAD

**Issue by sknadig** [espnet/espnet#661]
Linux ppc64le GNU/Linux
PyTorch  0.4.1
Ubuntu 18.04

In /espnet/espnet/nets/pytorch_backend/e2e_asr.py [line 355](https://github.com/espnet/espnet/blob/master/espnet/nets/pytorch_backend/e2e_asr.py#L355)
`y = self.dec.recognize_beam_batch(hpad, hlens, lpz, recog_args, char_list, rnnlm)`
throws an error `AttributeError: 'list' object has no attribute 'repeat'` during decoding.

If I convert the array to `torch.tensor(hlens)`
`y = self.dec.recognize_beam_batch(hpad, torch.tensor(hlens), lpz, recog_args, char_list, rnnlm)`
I get `RuntimeError: Could not infer dtype of numpy.int64`

I tried this solution from [PyTorch issue 8365](https://github.com/pytorch/pytorch/issues/8365#issuecomment-447657233)
`hlens = list(map(int, hlens))`
`y = self.dec.recognize_beam_batch(hpad, torch.tensor(hlens), lpz, recog_args, char_list, rnnlm)`
This fixes the issue.

I have not tested this one PyTorch 1.0 (PyTorch issue 8365 says it is fixed in 1.0).

**Comment by sw005320** [comment]
Thanks for the report! 
Could you make a PR for this with the above comments?

**Comment by kan-bayashi** [comment]
Fixed (#680)
