### ISSUE TITLE
How to do multilingual training using your code?

### ISSUE THREAD

**Issue by gentaiscool** [espnet/espnet#662]
I cannot find any way to do multilingual training in your documentation. Is there any way to reproduce "Language Independent End-to-End Architecture For Joint Language and Speech Recognition" results using this code?

Thanks

**Comment by kan-bayashi** [comment]
That is the recipe `egs/li10/asr1`, please check it.

**Comment by gentaiscool** [comment]
I checked the code. Is it only concatenating all datasets? or you did some sampling in the training? Do you have any special argument for multilingual training?

**Comment by kan-bayashi** [comment]
In the preparation, language code is added to the front of text and then all of data are concatenated. 
I think the difference is only the use of language code compared with standard  e2e-asr training.
@sw005320 Is it right?

**Comment by sw005320** [comment]
The recipe does not even include the language code. This recipe simply combines the data directories obtained by `egs/voxforge/asr1/run.sh`, `egs/wsj/asr1/run.sh`, `egs/csj/asr1/run.sh`, and `egs/hkust/asr1/run.sh`.

**Comment by gentaiscool** [comment]
@sw005320 for multilingual training, we don't need to do any sampling?

**Comment by sw005320** [comment]
Maybe better to do it, but I did not test it.

**Comment by gentaiscool** [comment]
thanks
