### ISSUE TITLE
Computing oracle WER on N-best hypotheses list

### ISSUE THREAD

**Issue by khassanoff** [espnet/espnet#663]
Hi All,

Is there any script that computes the oracle WER from the N-best list?

I have a 50-best list and want to know what is the minimum achievable WER.
I know how to compute oracle WER on KALDI (http://kaldi-asr.org/doc/lattices.html#lattices_operations_oracle),
but I need to compute it for N-best output generated by ESPNET.

Thank you,
Khassan

**Comment by sw005320** [comment]
We don't prepare a such tool, unfortunately, but an edit distance computation module is included. You could compute the oracle WER by yourself by referring https://github.com/espnet/espnet/blob/a54a001dcc3a8797febbb9c332df17f03e9afdd5/espnet/nets/pytorch_backend/e2e_asr.py#L223 as an example.
