### ISSUE TITLE
Inconsistenant calculation of WER/CER

### ISSUE THREAD

**Issue by boeddeker** [espnet/espnet#667]
I found two ways of calculating the CERs in espnet.
The first has problems with zero length reference transcriptions.
AFAIK is the second the way kaldi calculates the WER.

https://github.com/espnet/espnet/blob/a54a001dcc3a8797febbb9c332df17f03e9afdd5/espnet/nets/pytorch_backend/e2e_asr.py#L222-L225

https://github.com/espnet/espnet/blob/a54a001dcc3a8797febbb9c332df17f03e9afdd5/espnet/nets/pytorch_backend/e2e_asr_mix.py#L314-L318

Edit:
Sorry, I was not carefully reading the second use. Both are the same.

Nevertheless, I think the way of calculating the WER/CER is different from KALDI.
Is this intended?

```python
kalid_wer = sum(editdistances) / sum(reference_lengthes) 
espnet_wer = mean(e / r for e, r in zip(editdistances, reference_lengthes))
```

**Comment by sw005320** [comment]
Thanks. This must be done with the KALDI way.
@simpleoier and @takenori-y, could you fix this scoring part to compute it from the summation of all errors and chars.

@simpleoier, also `ref_words` in https://github.com/espnet/espnet/blob/a54a001dcc3a8797febbb9c332df17f03e9afdd5/espnet/nets/pytorch_backend/e2e_asr_mix.py#L318 should be `ref_chars`?

**Comment by simpleoier** [comment]
OK, I will take care of this as soon as possible.
