### ISSUE TITLE
Training data size of csj

### ISSUE THREAD

**Issue by karanMal** [espnet/espnet#668]
in the script it is mentioned training data is 233 hrs in case of CSJ
![image](https://user-images.githubusercontent.com/15909866/55334413-d96b9c00-54b6-11e9-9ec3-3d52afddafe7.png)

But online it is mentioned that the data is around 600 hrs.
After calculating form utt2num_frames in folder train_nodup it is coming to be around 512hrs.

**Comment by sw005320** [comment]
Thanks. This is a typo when we copied it from the original Kaldi CSJ recipe. It should be ~500 hours.

**Comment by karanMal** [comment]
Thanks for confirming.
