### ISSUE TITLE
How to use transfer learning ?

### ISSUE THREAD

**Issue by kobenaxie** [espnet/espnet#670]
https://github.com/espnet/espnet/blob/f7e3dbb8f1e011c41973c4c77403edf8ac684126/espnet/bin/asr_train.py#L182-L184

Hi, I can't find where the `--asr-model` arg is used, anyone do me a favor please ?

**Comment by sw005320** [comment]
Sorry, this option was added with some pending projects. If you want to perform transfer learning, you can check some ongoing PR (e.g., https://github.com/espnet/espnet/pull/563).

**Comment by desothier1** [comment]
Hi, do I understand it correctly that in current version, resuming is possible, but transfer learning not yet ?

**Comment by sw005320** [comment]
> Hi, do I understand it correctly that in current version, resuming is possible, but transfer learning not yet?

You're right.

> Would be great if transfer learning is possible

Yes, several people internally use it.
I think it's relatively simple. We may use the resume function or check the recognition codes to load the pre-trained model and reuse that part of codes for the transfer learning. 

I'd not support it officially since I want to stick to use the flat start (no pre-training) for the official recipe to fully make use of the benefit of simple end-to-end ASR/TTS procedure.
Speech translation recipe would support it as the pre-training is critical. (@hirofumi0810, could you comment on it?)
But I'll change my mind upon the request. If you tell me some use cases, I'll do it for you.

**Comment by desothier1** [comment]
Hi,
About a transfer learning use case,
For instance, instead of resuming with the same train data set,
It would be interesting if one could just start another training using another train data set (of course within the same target language).
With a ESPnet version of about a year ago that I used, I tried a resume training, using another train data set, but that yielded errors.

Thanks

Thierry

**Comment by sw005320** [comment]
@creatorscan, could you share your experience? I guess this is exactly what you did last year.

**Comment by desothier1** [comment]
Hi,
are there still plans to adapt your code to do transfer learning?
I try to train ASR using different datasets for training, but I cannot use ESPnet as transfer learning

Thanks for your info

**Comment by kan-bayashi** [comment]
If you want to use exactly the same model, what you need is just changing following line.
https://github.com/espnet/espnet/blob/58dd32248d6a065e7d5a654b6380e460db136f8a/espnet/asr/pytorch_backend/asr.py#L383

```
     torch_load(args.resume, model)
``` 
And then use `--resume <your_pretrained_model_path>`.

**Comment by desothier1** [comment]
OK, previously I used  --resume <your_pretrained_model_path>
for resuming, and continuing training, starting from a previously trained model, but using exactly the same train data i used previously

I mean, transfer learning, starting from a previously trained model, but using different train data.
with just specifying the path to the previously trained model, --resume <your_pretrained_model_path>, this did not work.

Or do you simply mean that on top of using --resume <your_pretrained_model_path> I should change torch_resume(args.resume, trainer)  into torch_load(args.resume, model) first (i guess not...)?

Thanks for your answer

**Comment by kan-bayashi** [comment]
Yes, just change `torch_resume(args.resume, model)` to `torch.load(args.resume, model)` and then use --resume option.

**Comment by desothier1** [comment]
Hi,

For trying out transfer learning
I tried what you proposed,
changing torch_resume(args.resume, model) to torch_load(args.resume, model) and then use --resume option.
This seems to be a first step, but I guess some other code should be modified

-So I took an existing trained model with ESPnet
-option resume used, for instance,
     resume=./exp/train_nodev_pytorch_blstmp_e4_subsample1_2_2_1_1_unit320_proj320_d1_unit300_location_aconvc10_aconvf100_mtlalpha0.5_adadelta_sampprob0.0_bs30_mli800_mlo150/results/snapshot.ep.6

-My goal is to continue training, starting with snapshot.ep.6, but training on another, smaller dataset.
-When I start training, I get the error message,

  File "..../espnet3/espnet/tools/venv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 769, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for E2E:
	size mismatch for ctc.ctc_lo.weight: copying a param with shape torch.Size([135, 320]) from checkpoint, the shape in current model is torch.Size([95, 320]).
	size mismatch for ctc.ctc_lo.bias: copying a param with shape torch.Size([135]) from checkpoint, the shape in current model is torch.Size([95]).
	size mismatch for dec.embed.weight: copying a param with shape torch.Size([135, 300]) from checkpoint, the shape in current model is torch.Size([95, 300]).
	size mismatch for dec.output.weight: copying a param with shape torch.Size([135, 300]) from checkpoint, the shape in current model is torch.Size([95, 300]).
	size mismatch for dec.output.bias: copying a param with shape torch.Size([135]) from checkpoint, the shape in current model is torch.Size([95]).

Of course the generated dictionary for the new (smaller) training data set is different from the one from which I resume.
I tried using the old dictionary that is bigger, but I get a similar message.

I understand that the general issue is about transfer learning with different model shapes, or that convlearner should be used, but I don't know currently how to do that.

So any help, or info about how and to where to modify the code is very welcome

Thanks!

**Comment by b-flo** [comment]
If you're using the resume function, the pre-trained model architecture should match the architecture you specified in your training config. In your case the only mismatched parameter is odim (your output dimension with extra labels included) so two possibilities :

  - The "bigger" dictionnary you used didn't have the same size as the pre-trained model you use, same problem as the smaller you used which produced the logs you sent.
  - You use an old ESPNET model and there was a change for odim (for the extra labels I guess). But I guess it should have been obvious from the logs.

I don't use the resume function when doing transfer learning but it should behave the same from what I see.

**Comment by kan-bayashi** [comment]
This may help you.
https://discuss.pytorch.org/t/how-to-load-part-of-pre-trained-model/1113
You can customize `torch_load` based on the above thread info.

**Comment by desothier1** [comment]
ok, thx for the info.
Last question, model version I use is v.0.3.1.
In this version  
change torch_resume(args.resume, model) to torch_load(args.resume, model) and then use --resume option 
not applicable yet ?

thanks

**Comment by LamDang** [comment]
Hello, 

I would like to do transfer learning from pretrained models to a new data set. But the SentencePiece model trained on target data set is not aligned with the pretrained model and the original SentencePiece model is not provided. 

Is there any way I can work around it? Is it possible to include in the models export the SentencePiece model used for training? 

Thanks,

**Comment by sw005320** [comment]
Which model (recipe) are you using?
You can ask people who upload the model to do it for the corresponding sentence piece model as well.
Now, we try to include the sentence piece model for newly uploaded models.

**Comment by LamDang** [comment]
Thanks, it is the fisher_callhome_spanish. Indeed having some standard format for models is great since it seems to take an important part in the package now.

@hirofumi0810 I sent you an email asking for the wordpiece model, wonder if you had a chance to look at it? Thanks again

**Comment by sw005320** [comment]
@hirofumi0810, could you repack the model including the sentencepiece model?
You could use https://github.com/espnet/espnet/blob/master/utils/pack_model.sh with `--dict` to include it.

**Comment by dipeshhoncho07** [comment]
Hey, I went through the entire thread, I just want to ask, I want to use librispeech pretrained model for my other small dataset initialization. Is it possible to do so? If yes, then how?
Second question is that my small corpus has most of the utterances as long utterance. So, how to use those long utterance in training, because when I try to put the corpus on training then the out of memory problem came to me then I used the script for removing long utterances and now it works but in that process most of the utterance actually got eliminated, so is there any way to use it?
Hope to hear from you soon.

**Comment by b-flo** [comment]
Hi,

> Hey, I went through the entire thread, I just want to ask, I want to use librispeech pretrained model for my other small dataset initialization. Is it possible to do so? If yes, then how?

Sure, please refer to https://espnet.github.io/espnet/tutorial.html#how-to-use-finetuning on how to use transfer learning!

> Second question is that my small corpus has most of the utterances as long utterance. So, how to use those long utterance in training, because when I try to put the corpus on training then the out of memory problem came to me then I used the script for removing long utterances and now it works but in that process most of the utterance actually got eliminated, so is there any way to use it?

Given your corpus mostly contains long utterances, I would suggest segmenting them manually or with some external tools. Not sure what is freely available thought, IIRC Kaldi may have some scripts for that.

**Comment by atiklt1972** [comment]
Dear sw005320, 
I am a beginner for an  end-to-end ASR concept and get  confused about a text used for language model   in non  end-to-end conventional approach. I haven't seen a way to use that text in end-to-end toolkits like espnet. am I right or not? I need a witness. On the other hand, the result (WER) found in espnet  is bad as compared to a result of the Kaldi toolkit. I am afraid of the result since my expectation was to improve the result. I need an explanation badly. please help me.

**Comment by atiklt1972** [comment]
Dear sw005320,
Sorry for your information I prepared only training and test data of speech utterances with their corresponding texts for espnet experiment.

**Comment by b-flo** [comment]
Hi,

Not sure if I correctly understood what you're asking so bear with me:

>  I haven't seen a way to use that text in end-to-end toolkits like espnet. am I right or not?

Most recipes have a LM training step included in the run script, e.g.: https://github.com/espnet/espnet/blob/master/egs/librispeech/asr1/run.sh#L172-L201
We usually use the transcriptions from the training set used to train the LM but you can use or augment with additional data.

> On the other hand, the result (WER) found in espnet is bad as compared to a result of the Kaldi toolkit.

The statement is too broad, more information is needed if you want us to comment on the WER difference: datasets used, compared systems, etc.

**Comment by AdolfVonKleist** [comment]
@dipeshhoncho07 if you are still looking for segmentation tools, aside from kaldi as already mentioned:

 * https://github.com/ina-foss/inaSpeechSegmenter
 * https://github.com/wiseman/py-webrtcvad

work very well together.   still requires some elbow-grease but the quality is excellent, especially if you need to cut out things like noise and music from real world recordings.

**Comment by atiklt1972** [comment]
Dear b-flo ,
Thank your fast response. I will reach out with the detail problem of my second question (bad WER result).
