### ISSUE TITLE
Difference between docker images

### ISSUE THREAD

**Issue by GabrielLin** [espnet/espnet#671]
There two types of docker in https://hub.docker.com/r/espnet/espnet/tags.
gpu-cuda-xxxxxxx 
cuda-xxxxx

What are the difference? Thanks.

**Comment by sw005320** [comment]
@Fhrozen, could you answer it?

**Comment by Fhrozen** [comment]
@GabrielLin, `cuda-xxxxx` based images are intermediate images without ESPnet, `gpu-cuda-xxxxxxx` are the final images that are used for the egs. 
I suppose the intermediate images should be removed from hub.docker to avoid this kind of problem. 
I will clean up the hub in the next update.

**Comment by GabrielLin** [comment]
OK. Got it. Thanks.
