### ISSUE TITLE
Github commit hash and docker tag

### ISSUE THREAD

**Issue by GabrielLin** [espnet/espnet#672]
Could you please add the Github commit hash to the tag of docker. I am afraid that time is not a good element to match the docker image to the Github version.

By the way, could you please tell me the current 20190321 docker image link to which commit of Github version? Thanks.

**Comment by Fhrozen** [comment]
@GabrielLin Could you please tell me where I am using time in the tag of docker. None of the tags in hub.docker uses time. The only moment the time tag are used is during docker run, so you can execute multiple docker images for the same example. I think this could be modified later.

Docker images are built after a large commit in git. Right now, all images were built with ESPnet v0.3.1

Let me know any additional detail or problem about the docker images.

**Comment by GabrielLin** [comment]
Thanks for your reply. I meant that I can see the building time of docker images and those time might be used to match the Github commit version, though it is not a good method.

**Comment by Fhrozen** [comment]
I understand your point of view, but given that docker is supported for the last version it seems unnecessary. Anyway, is one more thing to concern about later for the implementation of docker environments.
Thank you for your advice.

**Comment by GabrielLin** [comment]
OK. Thanks.
