### ISSUE TITLE
Run decoding on local cpu

### ISSUE THREAD

**Issue by vkothapally** [espnet/espnet#674]
We have two machines, one has GPUs built in it with only 8 cores. On the other server, we have no GPUs but many computing nodes to speed up tasks. I was able to install Espnet successfully on the GPU machine and use it to train end-to-end architectures. However, it consumes a lot of my time to decode (which makes sense - Espnet doesn't use GPUs to decode and my machine has only 8 cores). So, I was planning on installing Espnet on the second machine which can handle the decoding well. As mentioned earlier, it doesn't have GPU and so it lacks cuda and cudnn ( I have no access to install them on this machine). I'm here to see if there is any way around this. All I'm trying to do is use one machine with GPUs to train and the other with more cpu nodes to decode.

Any help is appreciated. Thanks in Advance.!

**Comment by Fhrozen** [comment]
If you want to install ESPnet in nogpu pc, you just only need to remove the cupy lines from Makefile.
as example you can check the Dockerfile that remove the cupy install to generate the CPU images:
https://github.com/espnet/espnet/blob/master/docker/prebuilt/devel/Dockerfile

**Comment by sw005320** [comment]
Yes, if you remove the cupy lines you can install even with such machines, but maybe we can think of supporting the cpu only installation with Makefile options. @Fhrozen, could you make such options and corresponding documents?

@vkothapally, you could also enjoy the GPU decoding by using --ngpu 1 and --batchsize 8.

**Comment by Fhrozen** [comment]
@sw005320 How should be this implemented? to disable cupy installation automatically or by user selection. In case of be automatically, I can move the commands from the dockerfile to makefile that disable cupy installation if nvcc is not detected or if it does not return a response. So there is no need for user to set any additional flag.

**Comment by sw005320** [comment]
A user selection is easier.

**Comment by vkothapally** [comment]
Thanks a lot for the help. I was able to decode using GPU (I guess for now it is just limited to using a single GPU). Also, I edited the Makefile and checkinstall.py files to remove any cupy instances. It worked for me.
