### ISSUE TITLE
Python version in docker

### ISSUE THREAD

**Issue by GabrielLin** [espnet/espnet#675]
It seems that the default python version is 2 in docker. How to switch to Python 3? I am afraid that Python 2 is going to die within one year. Thanks.

**Comment by Fhrozen** [comment]
It is true that the main runtime file install python2. This is only for kaldi.
If you access to the containers, activate venv and check the python version, it will show for all the containers that the version of python is 3.7.2.

It seems better to check the version of ubuntu and probably move to 18.04, given the deadline for python 2 is approaching. 

Best.

**Comment by GabrielLin** [comment]
OK. Thank you @Fhrozen .
