### ISSUE TITLE
pytorch own trainer without chainer

### ISSUE THREAD

**Issue by ShigekiKarita** [espnet/espnet#686]
Hi, all

I'm one of authors of chainer trainer used in pytorch. From beginning, I would reimplement pytorch's trainer without chainer.

Pros:
- **main purpose** integrate with pytorch distributed data sampler and iterator
- no chainer/cupy installation and knowledge for pytorch only users 
- free from bug and monkey patch at chainer.MultiProcessIterator https://github.com/espnet/espnet/blob/master/tools/prefetch.patch

Cons:
- need to reimplement several things (plot, resume, tensorboard)

For plot functionalities, I already have done with my private fork https://github.com/nttcslab-sp/espnet-semi-supervised/blob/master/python/results.py For resuming and tensorboard, I do not think it is difficult.

Or maybe we can adopt some cool trainer library (e.g., ignite, tnt, etc) instead of reimplemeting these. How do you think?

**Comment by vyouman** [comment]
I think this is cool. It may make it easier and more flexible to work in a pytorch-only way.

**Comment by fanlu** [comment]
Cool!!!

**Comment by ShigekiKarita** [comment]
https://github.com/pytorch/pytorch/releases/tag/v1.1.0
