### ISSUE TITLE
ESPnet toolkit for Spoken Translation

### ISSUE THREAD

**Issue by adarshjaju** [espnet/espnet#689]
Hi,
I am using the ESPnet toolkit for the task of Spoken Translation(ST) on the Augmented Librispeech dataset. Trained a char level end to end ASR system which worked fine (using char level librispeech recipe, enabling only the attention loss, mtalpha set to zero, ctc weight set to 0). Using the same recipe for the ST task (changed the English transcriptions to French translations and increasing the decoding layers to three) and training a model predicts the same French sentences for each utterance suggesting that no learning is happening. What might be going wrong?

**Comment by sw005320** [comment]
Probably you should follow https://github.com/espnet/espnet/pull/563 by @hirofumi0810. This includes a lot of TIPS to make ST work.

**Comment by adarshjaju** [comment]
Ok. Thanks
