### ISSUE TITLE
Drop Python 2.7 support in v.0.4.0

### ISSUE THREAD

**Issue by kan-bayashi** [espnet/espnet#693]
As you know, several libraries (matplotlib, numpy, etc.) discontinue Python2 support.

- https://github.com/numpy/numpy/blob/master/doc/neps/nep-0014-dropping-python2.7-proposal.rst
- https://github.com/matplotlib/matplotlib/issues/9404

ESPnet will also drop Python2 support in v.0.4.0.
If you have any suggestion about this change, please discuss here.

**Comment by sw005320** [comment]
I'm fine with this. We can keep our current style, but in the near future (next next version?), we can just remove python 2.X treatments in our code.
