### ISSUE TITLE
plot spectrogram on istft enhanced signal

### ISSUE THREAD

**Issue by ShigekiKarita** [espnet/espnet#695]
I happened to find bug (?) in the chime4 recipe during my PR #690 
https://github.com/espnet/espnet/blob/a58b032d866af027ecf5cc74c10d2afedf6b025f/espnet/asr/pytorch_backend/asr.py#L664-L719
In this code block, `write enhanced wav` -> `plot spectrogram` will cause error on enhanced signal because the variable `enh` is already `istft` and is not spectrogram anymore. I think it should be  `plot spectrogram` -> `write enhanced wav`. Is it right? @kamo-naoyuki @sw005320

**Comment by ShigekiKarita** [comment]
I think the fix works well (this enhance model is not fully trained)
![F01_050C010G_BUS_SIMU](https://user-images.githubusercontent.com/6745326/56579483-3ae0df80-660b-11e9-9472-6b71554ded1e.png)

**Comment by sw005320** [comment]
I see. This must be a bug. @kamo-naoyuki, could you fix it?

**Comment by sw005320** [comment]
#690 seems to fix this.
