### ISSUE TITLE
Interspeech 2019 tutorial

### ISSUE THREAD

**Issue by sw005320** [espnet/espnet#696]
Dear all,

Our tutorial proposal was accepted at  Interspeech 2019! ("Advanced methods for neural end-to-end speech processing – unification, integration, and implementation". See https://www.interspeech2019.org/program/tutorials/). Although this tutorial was not purely aimed for ESPnet, the second part of the tutorial will cover the use of ESPnet. Toward this tutorial, we'll boost our developments and want you to give us some inputs about desired functions/extensions/modifications and help some developments. You could find the main development plan at #650. If you volunteer to work on our project, please contact me (`shinjiw@ieee.org`) directly.

**Comment by sw005320** [comment]
We can also have an offline meeting at ICASSP.

**Comment by sjonathans** [comment]
Enhancement proposal:
Integrate a pre-trained Speech2Vec embedding layer for Speech To Text models 

Train an embedding using all audio data in the train set - optional setting in config file
Use it in the data layer instead of audio features only
Based on the paper:
https://arxiv.org/abs/1803.08976

**Comment by sw005320** [comment]
@sjonathans, thanks for the proposal!
This is interesting.
Another idea came up to me.
We actually found that the bottleneck feature is super powerful especially in the multilingual setup (@karaf or @creatorscan).

**Comment by ShigekiKarita** [comment]
In ICASSP19 discussion, we consider using Google Colab for demonstrating practical things. I'm making minimal ASR recipe/demo on notebook. I will ask your feedback later.
