### ISSUE TITLE
make installing pytorch-cpu instead of pytorch

### ISSUE THREAD

**Issue by jan-schuchardt** [espnet/espnet#701]
When trying to build espnet today, I noticed the following problem:

Even though I have a GPU and CUDA is installed, conda always installs pytorch-cpu into the virtual environment that is created upon executing _make_.

I think this problem can be traced back to 1f758b5445dc8963d0785a612fae8c886342cc10

```
ifeq (($shell which nvidia-smi),) # No 'nvcc' found
CONDA_PYTORCH := pytorch=$(TH_VERSION) cudatoolkit=$(CUDA_VERSION)
else
CONDA_PYTORCH := pytorch-cpu=$(TH_VERSION)
endif
```

1.) Syntactically, shouldn't the condition be `$(shell which nvidia-smi)` instead of `($shell which nividia-smi)` ?
2.) Semantically, shouldn't the body of the two conditions be switched? When no nvidia-smi / nvcc is found, we want to install pytorch-cpu. Not the other way around.

**Comment by jan-schuchardt** [comment]
Created a pull request https://github.com/espnet/espnet/pull/702

**Comment by kan-bayashi** [comment]
Thank you for your contribution!
The PR has been merged.
