### ISSUE TITLE
computing validation accuracy while training

### ISSUE THREAD

**Issue by newlunsu** [espnet/espnet#706]
Hi, all,

I got a validation accuracy of 82% after convergence while training but got the Corr 62.1%, Sub 24% Del 14.1% Ins 12.3% CER 50.2% after using beam search for decoding. How could it be possible to get a higher validation accuracy without beam search? Thank you!

**Comment by sw005320** [comment]
The validation accuracy during the training is computed based on teacher forcing and it would be better in general.
