### ISSUE TITLE
Missing file in iwslt18st recipe

### ISSUE THREAD

**Issue by gruly** [espnet/espnet#707]
Line 106 in run.sh from egs/iwslt18st/st1/: 
    local/data_prep_train.sh ${datadir}
--> data_prep_train.sh is missing in local/ directory

**Comment by sw005320** [comment]
@hirofumi0810, can you upload this?

**Comment by bravewolf** [comment]
I switched to branch iwslt18st then i found the working recipe 
[https://github.com/espnet/espnet/tree/iwslt18/egs/iwslt18st/st1/local](url)
However, at stage 4 - Network Training, the training process always be idle after training some epochs without reporting any error.

**Comment by sw005320** [comment]
@hirofumi0810, could you answer it?

**Comment by adarshjaju** [comment]
Can you please upload the file local/data_prep_train.sh

**Comment by hirofumi0810** [comment]
@gruly @bravewolf @adarshjaju 
Very sorry for the late reply.
I already have the correct files in the local repo.
I will soon complete this issued after PR #563 because there are some conflicts between them.

**Comment by Natalia-T** [comment]
There are several other files that are missing:
local/parse_xml.py
local/remove_punctuation.pl
local/ctm2segments.py

**Comment by adarshjaju** [comment]
Can you please update on the issue?

**Comment by hirofumi0810** [comment]
@adarshjaju 
OK. I'm back on this.

**Comment by adarshjaju** [comment]
Thank you for making the changes.
The updated code for IWSLT18 ST runs without any errors. But in the last phase of stage 2: Dictionary and JSON Data Preparation, the JSON files are updated, and it contains target sequences for both the languages. But in the training phase,  in the Custom batch converter function, LoadInputsAndTargets utility is called with 'ASR' mode, which returns the batch only with the one target sequence and the second target sequence is ignored. There you have also mentioned that the option (second target) is only used for 'tts' mode. Then why are you updating the JSON file in stage 2? ( my doubt is where exactly the second target sequence is used while training the ST model)

**Comment by hirofumi0810** [comment]
@adarshjaju 
I prepared 2nd target references for multi-task learning. I just used it for my internal experiments. 
I'll make it option for v.0.4.0 branch. Thank you for letting me know.
I recommend you to follow v.0.4.0 branch if you want to do it ASAP.

**Comment by gruly** [comment]
In the iwslt18 st1 recipe:

by default the $set variable of the local/data_prep_eval.sh is defined as the second argument ${part} in line 127 of the run.sh script:

126     for part in dev2010 tst2010 tst2013 tst2014 tst2015; do
127         local/data_prep_eval.sh ${st_ted} ${part}
128     done


Then, in local/data_prep_eval.sh, line 26, there is:
26     yml=$src/test-db.yaml


Last, the yml variable will be used in line 138 to make segment files.


But test-db.yaml files do not exist in the downloaded data.

To create these files, it seems that we must uncomment the lines 120 to 130 that use the LIUM speaker diarization tool:

120 # (1b) Segmente audio file with LIUM diarization tool
121 # if [ $set != tst2018 ]; then
122 #     echo "" > $src/test-db.yaml
123 #     for f in `cat $src/FILE_ORDER`; do
124 #         java -jar ../../../tools/lium_spkdiarization-8.4.1.jar --fInputSpeechThr=0.0 --fInputMask=$wav_dir/$f.wav --sOutputMask=$wa    v_dir/$f.seg $f --saveAllStep
125 #         # using *.s.seg for now, we live with possibly bad segmentation instead of throwing away to much stuff
126 #         # also sort by start offset of utterance
127 #         cat $wav_dir/$f.s.seg | grep --invert-match ";;" | sort -n -k3 | awk '{print "- {\"wav\": \"PATH/wavs/" $1 ".wav\", \"offse    t\":" $3/100 ", \"duration\":" ($4)/100 "}"}' >> $src/test-db.yaml
128 #     done
129 #     sed -i 's\PATH\'$src'\g' $src/test-db.yaml
130 # fi
131 # NOTE: audio segmentaion and golden transcripts don't match here
132 # After finishing the training stage, hyp and ref are aligned by a RWTH tool
133 


The problem is that without uncommenting lines 120-130, the recipe cannot work. 
But why are they commented? Any reason?

In addition, by uncommenting these lines, we need to install a tool (LIUM_SpkDiarization) that is not listed in the ESP.net requirements. (LIUM_SpkDiarization is a Java tool easy to install).

**Comment by sw005320** [comment]
Thanks, @gruly for pointing out the issue. I just checked that these yaml files are not so large and I'm fine for either option of creating them from LIUM_SpkDiarization or uploading these files in the local directory as a part of recipe.
@hirofumi0810. do you have comments?
```
$ ls -hl /export/b08/inaguma/IWSLT/*/IWSLT*/test-db.yaml
-rw-r--r-- 1 ws18hinag fax 119K Oct  2  2018 /export/b08/inaguma/IWSLT/dev2010/IWSLT.dev2010/test-db.yaml
-rw-r--r-- 1 ws18hinag fax 202K Sep 20  2018 /export/b08/inaguma/IWSLT/tst2010/IWSLT.tst2010/test-db.yaml
-rw-r--r-- 1 ws18hinag fax 152K Sep 20  2018 /export/b08/inaguma/IWSLT/tst2013/IWSLT.tst2013/test-db.yaml
-rw-r--r-- 1 ws18hinag fax 173K Sep 20  2018 /export/b08/inaguma/IWSLT/tst2014/IWSLT.tst2014/test-db.yaml
-rw-r--r-- 1 ws18hinag fax 169K Sep 20  2018 /export/b08/inaguma/IWSLT/tst2015/IWSLT.tst2015/test-db.yaml
```

**Comment by hirofumi0810** [comment]
@sw005320 Can I upload them? LIUM_SpkDiarization is not perfect, so it's possible to enhance segmentation using better VAD (will be implemented in future ESPnet?).
I mean we can update them by overwriting segmentation files in `local`.

**Comment by sw005320** [comment]
@hirofumi0810, in `iwslt18/asr1`, I found the following error:
```
Traceback (most recent call last):
  File "/export/a08/shinji/201707e2e/espnet_iwslt18/egs/iwslt18/asr1/../../../espnet/bin/asr_recog.py", line 140, in <module>
    main(sys.argv[1:])
  File "/export/a08/shinji/201707e2e/espnet_iwslt18/egs/iwslt18/asr1/../../../espnet/bin/asr_recog.py", line 128, in main
    recog(args)
  File "/export/a08/shinji/201707e2e/espnet_iwslt18/espnet/asr/pytorch_backend/asr.py", line 505, in recog
    new_js[name] = add_results_to_json(js[name], nbest_hyps, train_args.char_list)
  File "/export/a08/shinji/201707e2e/espnet_iwslt18/espnet/asr/asr_utils.py", line 470, in add_results_to_json
    out_dic = dict(js['output'][0].items())
```
It seems that `data.json` does not include the output text, which may be come from https://github.com/espnet/espnet/blob/master/egs/iwslt18/asr1/run.sh#L280-L283
Can you fix it?

**Comment by hirofumi0810** [comment]
dev2010.en and tst*.en should not include any outputs becasue there is no reference per utterance.
So that is the correct observation. Instead i will fix in the recognition part.

**Comment by sw005320** [comment]
oh I see.
thanks for the clarification!

**Comment by gruly** [comment]
> @sw005320 Can I upload them? LIUM_SpkDiarization is not perfect, so it's possible to enhance segmentation using better VAD (will be implemented in future ESPnet?).
> I mean we can update them by overwriting segmentation files in `local`.

My opinion is that you could indeed consider these test-db.yaml files as a part of the recipe (as suggested by sw005320) and upload them. And write an information about this somewhere in the recipe, maybe simply as a comment.

**Comment by hirofumi0810** [comment]
@gruly Yes. Please follow #808. You can check how to obtain test-db.yaml.
Another option is to upload other types of segmentation files (time information) then modify scripts in `local`.
Do you have segmentation files in your local environments? And is it possible to upload them Google Drive if you have?

**Comment by gruly** [comment]
Thank you @hirofumi0810.
I have segmentation files provided by IWSLT18 organizers last year: https://sites.google.com/site/iwsltevaluation2018/Lectures-task

I can share if you are interested. They also were computed with LIUM_SpkDiarization (by organizers)

**Comment by hirofumi0810** [comment]
@gruly Accutually I was a participant of IWSLT2018.
But their segmentation files were very noisy, which was a crucial problem for evaluation.
Almost all participants implemented their own VAD to obtain better segmentation.

**Comment by gruly** [comment]
OK. So, I do not have other files.
