### ISSUE TITLE
"multichannel end-to-end setup" can not reach the results in the paper 

### ISSUE THREAD

**Issue by Rpersie** [espnet/espnet#710]
Does anyone run the PR #120 "added multichannel end-to-end setup" ? I run the PR #120 but I can not get the reasonable results as the description in the paper.
![image](https://user-images.githubusercontent.com/12673020/56936463-23818500-6b2a-11e9-95fd-8f6e08a90391.png)
Then I compare the paper configuration and the github configuration. In the paper , the fbank is 40-dim, the encoder is 4-layer, mtlalpha=0.9. In the github configuration, the fbank is 80-dim, the encoder is 6-layer, mtlalpha=0.5. I change the confguration like the paper, but the results is worse
![image](https://user-images.githubusercontent.com/12673020/56936491-37c58200-6b2a-11e9-83f5-55a0d3b66e55.png)

**Comment by sw005320** [comment]
@Rpersie, again I strongly recommend you to try https://github.com/espnet/espnet/blob/v.0.4.0/egs/chime4/asr1_multich
