### ISSUE TITLE
How to feed aishell2(or my own corpus)  to espnet?

### ISSUE THREAD

**Issue by jennifer1995** [espnet/espnet#718]
If I want to feed aishell2(1000h) into espnet, comparing to the origin aishell part, what should I do to change the format of aishell2?

**Comment by sw005320** [comment]
If you import the data preparation part from Kaldi (https://github.com/kaldi-asr/kaldi/blob/master/egs/aishell2/s5/local/prepare_all.sh#L34-L38) and follow the other parts in the aishell1 recipe (https://github.com/espnet/espnet/tree/master/egs/aishell), I believe you could make it.

**Comment by jennifer1995** [comment]
Thank you !

**Comment by xdcesc** [comment]
@jennifer1995 Where can aishell2 be downloaded?

**Comment by jennifer1995** [comment]
> @jennifer1995 Where can aishell2 be downloaded?

you can contact them in []((http://www.aishelltech.com/aishell_2)) , and ask for permission. 
It can't be downloaded by yourself without permission
