### ISSUE TITLE
Why the aishell result(CER) is different with the official one? 

### ISSUE THREAD

**Issue by jennifer1995** [espnet/espnet#719]
I train the model on aishell, and the result shows that err is 11.9(test) and 10.6(dev), does it refer to the value of CER?Or where can i see the CER? Why the result is different with the official one? Does batchsize affect the result? Backend is chainer. Thank you!

**Comment by sw005320** [comment]
This would be CER. I cannot tell why because you use the different setup. Please try to use the exactly same setup.
