### ISSUE TITLE
When infer the audio file, AttributeError: 'NoneType' object has no attribute 'startswith'

### ISSUE THREAD

**Issue by jennifer1995** [espnet/espnet#723]
When I infer the audio file, the stage 3 Decoding encounters a problem, the error log is below:
Traceback (most recent call last):
  File "/espnet/egs/aishell/asr1/../../../espnet/bin/asr_recog.py", line 135, in <module>
    main(sys.argv[1:])
  File "/espnet/egs/aishell/asr1/../../../espnet/bin/asr_recog.py", line 120, in main
    recog(args)
  File "/espnet/espnet/asr/chainer_backend/asr.py", line 491, in recog
    model_module = import_module(train_args.model_module)
  File "/espnet/tools/venv/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
TypeError: 'NoneType' object is not subscriptable

Why the model_module is none? Thank you!

**Comment by kan-bayashi** [comment]
Which recipe did you use?

**Comment by jennifer1995** [comment]
> Which recipe did you use?

I use the  recog_wav.sh to infer audio

**Comment by jennifer1995** [comment]
> Which recipe did you use?
The below is in recog_wav.sh line 119
` --result-label ${decode_dir}/result.json \`
But I can't find the file result.json in corresponding folder, maybe it's the reason?

**Comment by kan-bayashi** [comment]
> --result-label ${decode_dir}/result.json \

This file will be created.
Could you tell me the all of commands?

**Comment by kan-bayashi** [comment]
I checked the behavior with current v.0.4.0 as follows:

```
# chainer backend without language model
$ local/recog_wav.sh \
    --cmvn data/train_si284/cmvn.ark \
    --lm_weight 0 \
    --recog_model exp/train_si284_chainer_vggblstmp_e6_subsample1_2_2_1_1_unit320_proj320_d1_unit300_location_aconvc10_aconvf100_mtlalpha0.2_adadelta_sampprob0.0_bs30_mli800_mlo150_lsmunigram0.05/results/model.acc.best \
    sample.wav

stage 0: Data preparation
stage 1: Feature Generation
steps/make_fbank_pitch.sh --cmd slurm.pl --nj 1 --write_utt2num_frames true decode/sample/data decode/sample/log decode/sample/fbank
utils/validate_data_dir.sh: WARNING: you have only one speaker.  This probably a bad idea.
   Search for the word 'bold' in http://kaldi-asr.org/doc/data_prep.html
   for more information.
utils/validate_data_dir.sh: Successfully validated data-directory decode/sample/data
steps/make_fbank_pitch.sh: [info]: no segments file exists: assuming wav.scp indexed by utterance.
Succeeded creating filterbank & pitch features for data
/home/t_hayashi/workspace5/work/espnet_dev/egs/wsj/asr1/../../../utils/dump.sh --cmd slurm.pl --nj 1 --do_delta false decode/sample/data/feats.scp data/train_si284/cmvn.ark decode/sample/log decode/sample/dump
stage 2: Json Data Preparation
/home/t_hayashi/workspace5/work/espnet_dev/egs/wsj/asr1/../../../utils/data2json.sh --feat decode/sample/dump/feats.scp decode/sample/data decode/sample/dict
/home/t_hayashi/workspace5/work/espnet_dev/egs/wsj/asr1/../../../utils/feat_to_shape.sh --cmd run.pl --nj 1 --filetype  --preprocess-conf  --verbose 0 decode/sample/dump/feats.scp decode/sample/data/tmp-wWxlu/input/shape.scp
sym2int.pl: replacing X with 1
** Replaced 1 instances of OOVs with 1
stage 3: Decoding

Recognized text: <NOISE> BUT THAT OF THE BANK OF THREE FILED TO THE CONTROL

Finished
```

I will check the behavior with language model soon.

**Comment by jennifer1995** [comment]
> > --result-label ${decode_dir}/result.json \
> 
> This file will be created.
> Could you tell me the all of commands?

```
./recog_wav.sh \
 --cmvn decode/cmvn.ark \     
 --recog_model decode/model.acc.best \
 ID0415W0344.wav
```
I used the command above, but still failed to recognize, and it just stop at the step3 decoding
It shows: 
```
** Replaced 1 instances of OOVs with 1
stage 3: Decoding
run.pl: job failed, log is in /espnet/egs/aishell/asr1/decode/ID0415W0344/log/decode.log

```

And the log is just as before, and file  `result.json` isn't created.
Thank you

**Comment by kan-bayashi** [comment]
Please add `--lm_weight 0` option.

**Comment by jennifer1995** [comment]
Is it related to the python version? I use python 2.7

**Comment by jennifer1995** [comment]
> Please add `--lm_weight 0` option.

I add it, but it remains the same
```

stage 0: Data preparation
stage1 done
stage 1: Feature Generation
steps/make_fbank_pitch.sh --cmd run.pl --nj 1 --write_utt2num_frames true /espnet/egs/aishell/asr1/decode/ID0415W0344/data /espnet/egs/aishell/asr1/decode/ID0415W0344/log /espnet/egs/aishell/asr1/decode/ID0415W0344/fbank
steps/make_fbank_pitch.sh: moving /espnet/egs/aishell/asr1/decode/ID0415W0344/data/feats.scp to /espnet/egs/aishell/asr1/decode/ID0415W0344/data/.backup
utils/validate_data_dir.sh: WARNING: you have only one speaker.  This probably a bad idea.
   Search for the word 'bold' in http://kaldi-asr.org/doc/data_prep.html
   for more information.
utils/validate_data_dir.sh: Successfully validated data-directory /espnet/egs/aishell/asr1/decode/ID0415W0344/data
steps/make_fbank_pitch.sh: [info]: no segments file exists: assuming wav.scp indexed by utterance.
Succeeded creating filterbank & pitch features for data
/espnet/egs/aishell/asr1/../../../utils/dump.sh --cmd run.pl --nj 1 --do_delta false /espnet/egs/aishell/asr1/decode/ID0415W0344/data/feats.scp decode/cmvn.ark /espnet/egs/aishell/asr1/decode/ID0415W0344/log /espnet/egs/aishell/asr1/decode/ID0415W0344/dump
stage 2: Json Data Preparation
/espnet/egs/aishell/asr1/../../../utils/data2json.sh --feat /espnet/egs/aishell/asr1/decode/ID0415W0344/dump/feats.scp /espnet/egs/aishell/asr1/decode/ID0415W0344/data /espnet/egs/aishell/asr1/decode/ID0415W0344/dict
/espnet/egs/aishell/asr1/../../../utils/feat_to_shape.sh --cmd run.pl --nj 1 --filetype  --preprocess-conf  --verbose 0 /espnet/egs/aishell/asr1/decode/ID0415W0344/dump/feats.scp /espnet/egs/aishell/asr1/decode/ID0415W0344/data/tmp-xpbhO/input/shape.scp
sym2int.pl: replacing X with 1
** Replaced 1 instances of OOVs with 1
stage 3: Decoding
run.pl: job failed, log is in /espnet/egs/aishell/asr1/decode/ID0415W0344/log/decode.log
```

**Comment by kan-bayashi** [comment]
According to your log, you look using python 3.7.
> `File "/espnet/tools/venv/lib/python3.7/importlib/init.py", line 127, in import_module`

**Comment by jennifer1995** [comment]
> According to your log, you look using python 3.7.
> 
> > `File "/espnet/tools/venv/lib/python3.7/importlib/init.py", line 127, in import_module`

yes but I use command `python --version` ,it prints `python  2.7.12`

**Comment by kan-bayashi** [comment]
Maybe I got the reason.
Make sure that `model.json` in the same directory of `recog_model`.
(In your case `decode`)
Please check the `"model_module"` parameter in `model.json`.
It should be as follows in the case of chainer.
```
        "maxlenratio": 0.0,
        "minibatches": 0,
        "minlenratio": 0.0,
        "model_module": "espnet.nets.chainer_backend.e2e_asr",
        "mt_model": false,
        "mtlalpha": 0.2,
        "n_iter_processes": 0,
        "n_mels": 80,
        "nbest": 1,
```
If not, please modify the parameter to be the same as above example.

**Comment by kan-bayashi** [comment]
If you setup using default Makefile, we create python3 conda env in `tools/venv`.
The environment is activated in `path.sh`, which is sourced at the top of `recog_wav.sh` script.

And maybe you try to use the model trained on old version, right?

**Comment by jennifer1995** [comment]
> Maybe I got the reason.
> Make sure that `model.json` in the same directory of `recog_model`.
> (In your case `decode`)
> Please check the `"model_module"` parameter in `model.json`.
> It should be as follows in the case of chainer.
> 
> ```
>         "maxlenratio": 0.0,
>         "minibatches": 0,
>         "minlenratio": 0.0,
>         "model_module": "espnet.nets.chainer_backend.e2e_asr",
>         "mt_model": false,
>         "mtlalpha": 0.2,
>         "n_iter_processes": 0,
>         "n_mels": 80,
>         "nbest": 1,
> ```
> 
> If not, please modify the parameter to be the same as above example.

Oh . I made it!! Thank you very much.
By the way, the recognize text for Chinese is in the format of UNICODE, is it right?

**Comment by jennifer1995** [comment]
> If you setup using default Makefile, we create python3 conda env in `tools/venv`.
> The environment is activated in `path.sh`, which is sourced at the top of `recog_wav.sh` script.
> 
> And maybe you try to use the model trained on old version, right?

yes , I train it on python2.7, but recognize the text on python3

**Comment by jennifer1995** [comment]
Can I infer batch audio files instead of a single one per time?

**Comment by kan-bayashi** [comment]
> By the way, the recognize text for Chinese is in the format of UNICODE, is it right?

If you want to get the human-readable results, use `echo -en "$(cat result.json)"`
Or please add `ensure_ascii=False` in `json.dumps` here
https://github.com/espnet/espnet/blob/049b8236b160d2e48cfd13dd2891363ade9a13ec/espnet/asr/chainer_backend/asr.py#L545

I think it is better to use `ensure_ascii=False` as default. I will fix this issue later.

> Can I infer batch audio files instead of a single one per time?

Currently, we do not have such a scripts, but maybe you can update following part in `recog_wav.sh` to make the list of multiple wavfiles.
https://github.com/espnet/espnet/blob/049b8236b160d2e48cfd13dd2891363ade9a13ec/egs/wsj/asr1/local/recog_wav.sh#L70-L77

**Comment by kan-bayashi** [comment]
If you want to fix the result not readable issue, please check #730.

**Comment by jennifer1995** [comment]
> Maybe I got the reason.
> Make sure that `model.json` in the same directory of `recog_model`.
> (In your case `decode`)
> Please check the `"model_module"` parameter in `model.json`.
> It should be as follows in the case of chainer.
> 
> ```
>         "maxlenratio": 0.0,
>         "minibatches": 0,
>         "minlenratio": 0.0,
>         "model_module": "espnet.nets.chainer_backend.e2e_asr",
>         "mt_model": false,
>         "mtlalpha": 0.2,
>         "n_iter_processes": 0,
>         "n_mels": 80,
>         "nbest": 1,
> ```
> 
> If not, please modify the parameter to be the same as above example.

When I train on the aishell2, in the stage4 Network Training, it comes to the error that
```
stage 4: Network Training
run.pl: job failed, log is in exp/train_sp_chainer_vggblstm_e3_subsample1_2_2_1_1_unit1024_proj1024_d2_unit1024_location_aconvc10_aconvf100_mtlalpha0.5_adadelta_sampprob0.0_bs30_mli800_mlo150/train.log
```
and the log is as below:
```
Traceback (most recent call last):
  File "/espnet/data/aishell2/asr1/../../../espnet/bin/asr_train.py", line 259, in <module>
    main(sys.argv[1:])
  File "/espnet/data/aishell2/asr1/../../../espnet/bin/asr_train.py", line 244, in main
    train(args)
  File "/espnet/espnet/asr/chainer_backend/asr.py", line 248, in train
    logging.info('import model module: ' + args.model_module)
AttributeError: 'Namespace' object has no attribute 'model_module'
```

Is it the same reason with the parameter of  `model.json` you said before?

**Comment by kan-bayashi** [comment]
It looks the same.
It is better to avoid using different version at the same time.

**Comment by jennifer1995** [comment]
> It looks the same.
> It is better to avoid using different version at the same time.
I add the parameter to` model.json `, it remains the same error.
So, if I want to use the same version as before(python 2.7), I should set it in `path.sh`?

**Comment by kan-bayashi** [comment]
I do not understand how you setup your environment.
I assume that you have two espnet directories.
One is master and the other is v.0.4.0, right?
You should only use v.0.4.0 espnet with v.0.4.0 espnet/tools.

**Comment by jennifer1995** [comment]
> I do not understand how you setup your environment.
> I assume that you have two espnet directories.
> One is master and the other is v.0.4.0, right?
> You should only use v.0.4.0 espnet with v.0.4.0 espnet/tools.

How should I check the version of espnet?

**Comment by kan-bayashi** [comment]
```
Traceback (most recent call last):
  File "/espnet/data/aishell2/asr1/../../../espnet/bin/asr_train.py", line 259, in <module>
    main(sys.argv[1:])
  File "/espnet/data/aishell2/asr1/../../../espnet/bin/asr_train.py", line 244, in main
    train(args)
  File "/espnet/espnet/asr/chainer_backend/asr.py", line 248, in train
    logging.info('import model module: ' + args.model_module)
AttributeError: 'Namespace' object has no attribute 'model_module'
```
`model_module` argument is defined here.
https://github.com/espnet/espnet/blob/049b8236b160d2e48cfd13dd2891363ade9a13ec/espnet/bin/asr_train.py#L50-L51

The error comes from here.
https://github.com/espnet/espnet/blob/049b8236b160d2e48cfd13dd2891363ade9a13ec/espnet/asr/chainer_backend/asr.py#L248

So, this error should not be happend.
Maybe your `/espnet` directory is old, and you source `venv` which is located at another place.
(The version of `asr_train.py` and `asr.py` are different.)

It is better to use `/espnet/tools/venv` environment to match the version.
You can re-setup python venv as follows.

```bash
cd /espnet/tools
make clean_python
make python
```

**Comment by kan-bayashi** [comment]
> How should I check the version of espnet?

```
$ cd <your_aishell2_recipe>
$ . ./path.sh
$ pip list | grep espnet
# check the path of espnet is the same as the your recipe location.
```

**Comment by jennifer1995** [comment]
> > How should I check the version of espnet?
> 
> ```
> $ cd <your_aishell2_recipe>
> $ . ./path.sh
> $ pip list | grep espnet
> # check the path of espnet is the same as the your recipe location.
> ```

It shows that
`espnet                 0.3.1    /espnet `

**Comment by jennifer1995** [comment]
> > How should I check the version of espnet?
> 
> ```
> $ cd <your_aishell2_recipe>
> $ . ./path.sh
> $ pip list | grep espnet
> # check the path of espnet is the same as the your recipe location.
> ```

The  espnet directory is `/espnet/...`
My recipe location is `/espnet/data/aishell2/asr1/..`
Is it right?

**Comment by kan-bayashi** [comment]
Hmm... I have no idea anymore :(
Please check the parts mentioned above to fix the error.

**Comment by jennifer1995** [comment]
> It loos ok (but recipe should be located in egs directory).
> Hmm... I have no idea anymore :(
> Please check the parts mentioned above to fix the error.

Thank you very much! I will check it

**Comment by jennifer1995** [comment]
> It loos ok (but recipe should be located in egs directory).
> Hmm... I have no idea anymore :(
> Please check the parts mentioned above to fix the error.

I update the file `asr_train.py` for the latest version and it works 👍

**Comment by kan-bayashi** [comment]
Great!

**Comment by kan-bayashi** [comment]
I will close this issue.
