### ISSUE TITLE
Why the "asr1_multich" results  in espnet v0.4.0  can not reach the official results ? 

### ISSUE THREAD

**Issue by Rpersie** [espnet/espnet#724]
![image](https://user-images.githubusercontent.com/12673020/57581650-e08dbd00-74ec-11e9-9305-8df19b0a34cc.png)

The first line is the official results and the second line is my results.
I just run the official scripts and use only 1 gpu.  But the results is worse than the official results.
It is normal ? Thank you!

**Comment by sw005320** [comment]
This is normal. The result can be changed depending on the environment, and we cannot control it across the environment (but you can compare the result within the same environment).
