### ISSUE TITLE
Stage2 Dictionary preparation got the error : the value of $nj

### ISSUE THREAD

**Issue by jennifer1995** [espnet/espnet#727]
When I train the model with a dataset of 1000 hours, it comes to the error as below:

Stage 2 Dictionary and Json Data Preparation
> 
split_scp.pl: error: empty input scp file dump/dev/deltafalse/feats.scp , You are splitting into too many pieces! [reduce $nj] at utils/split_scp.pl line 209.

Is it the value of $nj in stage1 when create feats.scp is too big?
What rules should I follow to set the value of nj?
Thank you very much!

**Comment by kan-bayashi** [comment]
> error: empty input scp file dump/dev/deltafalse/feats.scp

Is the `feats.scp` generated correctly?
Or you can set $nj to be less than #speakers.

**Comment by jennifer1995** [comment]
> > error: empty input scp file dump/dev/deltafalse/feats.scp
> 
> Is the `feats.scp` generated correctly?
> Or you can set $nj to be less than #speakers.

Thank you for your reply. There is something wrong with  `feats.scp` , and i will try it again!
