### ISSUE TITLE
How can I generate  audio feats without speaker information ?

### ISSUE THREAD

**Issue by ictnlp-wshugen** [espnet/espnet#735]
Hi, recently, I want to use the [zh-TW common voice dataset ](https://voice.mozilla.org/zh-CN/datasets) to train a ASR model. 

After running your example provided in README file, i.e. egs/an4/as1. I try to follow the spirit of the example, but was stuck in the Feature Generation step due to the dataset I try to preprocessed with is lacked in speakers information, i.e. common voice dataset is anonymous. 

So how can I extract the necessary information with existing text and wav.scp both in the format indexed by sampled id then followed by a tokenized transcript or wav path to feed into your toolkit's network ?

**text** file example:
- 482 若 活 在 世界 上
- 15811 为 了 赚钱
- 6692 被 他 拉 着 往 前

**wav.scp** file example:
- 482 /home2/user/zh-TW/wav_db/482.wav
- 15811 /home2/user/zh-TW/wav_db/15811.wav
- 6692 /home2/user/zh-TW/wav_db/6692.wav

**Comment by sw005320** [comment]
You can just use one global speaker for all utterances, e.g., 
- utt2spk
```
482 global
15811 global
: 
```
- spk2utt
```
global 482 15811
```
etc.

Also, please check some Mandarin recipes for details (`egs/{aishell,hkust}`)

**Comment by ictnlp-wshugen** [comment]
Thanks for your helpful advice, I have used different speaker ids, i.e. I use sample id as the speaker id.
