### ISSUE TITLE
kaldi-free recipe

### ISSUE THREAD

**Issue by ShigekiKarita** [espnet/espnet#736]
Recent espnet already has an ability to generate fbank (make_fbank.sh, espnet.transform module) thanks to @kan-bayashi  @kamo-naoyuki. Maybe it is time to discuss kaldi-free roadmap. However I know kaldi is an only way to format legacy dataset. Here is my opinion for v0.4.0 or later:

- start from an4 or tiny dataset
- copy minimal scripts that we need from kaldi/egs/wsj/s5/{steps,utils} and kaldi/egs/*/local 
- replace fbank generation with espnet's impl
- replace fbank+pitch with fbank in existing recipe or make python binding of [compute-kaldi-pitch-feats](https://github.com/kaldi-asr/kaldi/blob/master/src/featbin/compute-kaldi-pitch-feats.cc)

Let me know something else that depend on Kaldi.
maybe @kamo-naoyuki has some information on degradation from fbank+pitch -> fbank

**Comment by sw005320** [comment]
`fbank+pitch -> fbank` does not have so much degradation except for the HKUST recipe. I'm fine to use `fbank` because it's differentiable.

**Comment by kamo-naoyuki** [comment]
Another choice is using [pykaldi](https://github.com/pykaldi/pykaldi). It can be installed by conda. All feature types in kaldi are supported and they can be also integrated in `espnet.transform`.

**Comment by sw005320** [comment]
I like it as a temporal solution to replace the kaldi feature with the pykaldi feature. But switching to fbank only and using espnet's impl seem to be straightforward.

**Comment by ShigekiKarita** [comment]
I am working on "sclite" (another C dependency in Kaldi) replacement here https://github.com/ShigekiKarita/kaldi-edit-distance
