### ISSUE TITLE
Modify speaker info in Tedlium 

### ISSUE THREAD

**Issue by karanMal** [espnet/espnet#743]
![image](https://user-images.githubusercontent.com/15909866/58154350-1110ec00-7c8f-11e9-8e15-994738a94346.png)
In the above image of the script to run tedium asr, the train, test, dev speaker's information is changed with the spk2utt file being changed. I was wondering that is the spk2utt and utt2spk files are affecting training of the network as mean and variance are calculated globally.
![image](https://user-images.githubusercontent.com/15909866/58154583-96949c00-7c8f-11e9-9a7a-d71dcec050e1.png)

Are there any speaker based transforms used in the pipeline of the training that I may be missing, or just for decoding results these files are being used.
I am performing a task in which I don't want to use any speaker based information of the data while training.

**Comment by kan-bayashi** [comment]
Currently, we do not perform any speaker based processing in ASR.
So speaker information in `utt2spk` and `spk2utt` can be dummy.

**Comment by karanMal** [comment]
Thanks.
