### ISSUE TITLE
Any plan for Trigger Attention as a option of streaming decoder?

### ISSUE THREAD

**Issue by zhengyiuestc** [espnet/espnet#744]
Dear all,

It seems that the newly released paper "Triggered Attention for End-to-End Speech Recognition" can be a opiton of streaming deocoer. Is there any official plan or other information about the implemention of this new idea?

**Comment by sw005320** [comment]
@takaaki-hori, can you consider this possibility?

**Comment by sky1170447398** [comment]
Does anyone consider this problem?

**Comment by takaaki-hori** [comment]
Niko might be able to work on that, but we need to solve our internal issues before starting that. I will talk to some related people.
