### ISSUE TITLE
cer_ctc is not working for the transformer

### ISSUE THREAD

**Issue by sw005320** [espnet/espnet#755]
It is always 0...
@ShigekiKarita, could you fix it?

![image](https://user-images.githubusercontent.com/11741550/58335658-0d58a300-7e10-11e9-9f4e-b82df0a56d0f.png)

**Comment by sw005320** [comment]
Monitoring the CTC CER is quite important to see whether the encoder is well trained.

**Comment by Fhrozen** [comment]
Fixed in #774
