### ISSUE TITLE
Which version of pytorch is used?

### ISSUE THREAD

**Issue by jnishi** [espnet/espnet#756]
Pytorch 1.1 was released. I'll fix espnet to use  it.

Now espnet supports pytorch of 0.4.0 and 1.0.1. Older versions of pytorch need to be supported?

**Comment by sw005320** [comment]
This is great. I think it's good to keep 0.4.0 due to the warp CTC issue, which is critical for the multispeaker ASR #669. If we solve the warp CTC issue, I think we could stop the support for 0.4.0. So, it would be great if you keep supporting the older versions for now.

**Comment by Geish** [comment]
I'm interested in helping with this. Any work in progress or pointers to where changes need to be made?

**Comment by sw005320** [comment]
Thanks, @Geish. @jnishi, could you share your current status of using Pytorch 1.1 for ESPnet?

**Comment by jnishi** [comment]
I merged original repository's patch which supports pytorch 1.1 into `pytorch-1.1` branch https://github.com/espnet/warp-ctc/tree/pytorch-1.1

However, espnet needs to be fixed to use pytorch 1.1, because interface of some functions differ from pytorch 1.0. (Sorry for missing of latest versions of error message.)

@Geish
Could you use `pytorch-1.1` branch and fix espnet?

**Comment by Geish** [comment]
@jnishi I already tried that but I'm seeing an error running espnet and imoprting `ctcdecode` with that branch:
```
import ctcdecode
  File ".../espnet/tools/venv/lib/python3.6/site-packages/ctcdecode/__init__.py", line 1, in <module>
    from ._ext import ctc_decode
ImportError: .../espnet/tools/venv/lib/python3.6/site-packages/ctcdecode/_ext/ctc_decode.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN2at19UndefinedTensorImpl10_singletonE
```
I looked online and the suggested fix is insufficient (to import `torch` first, which is what espnet does). Any pointers to why this is the case?

**Comment by jnishi** [comment]
Hi, I run current ``master` branch of espnet with `pytorch-1.1` of warpctc. It looks fine in my environment.

Your error seems to be due to lack of binary library. Are there any error in compiling of the warpctc or pytorch binding?
