### ISSUE TITLE
dump.sh issue

### ISSUE THREAD

**Issue by desothier1** [espnet/espnet#762]
Hi

When running dump.sh 
a UnicodeDecodeError occurs 
'utf-8' codec can't decode byte 0xc3 in position 0: unexpected end of data
More precisly in
espnet/tools/venv/lib/python3.7/site-packages/kaldiio/matio.py, line 306, in read_token

the error is generated in a log file in exp/dump_feats folder

The reason of the error are filename containing characters with accents such as Ï,é,à ..., but only for the read file names.

As I have only a few such file names, I can easily rename those, but this error did not occur in a previous Espnet version

Thanks

**Comment by kamo-naoyuki** [comment]
This should be a bug of kaldiio due to multibyte character. I'll fix it.

**Comment by kamo-naoyuki** [comment]
Maybe it was fixed, please try it again with ``pip install -U kadiio``
