### ISSUE TITLE
It takes a long time to infer the audio file in Chinese

### ISSUE THREAD

**Issue by jennifer1995** [espnet/espnet#765]
For an audio file about 5 seconds, it will take more than 30 seconds to recognize and output the text with gpu. Is there anything wrong? Or it is normal? 
Thank you.

**Comment by sw005320** [comment]
Could you please explicitly specify `--batchsize 0` during decoding (e.g., https://github.com/espnet/espnet/blob/master/egs/hkust/asr1/run.sh#L319)? There is a bottleneck for the CTC prefix score computations when we use larger outputs. If it does not solve, you may reduce the beam size. Making decoder faster is one of our important action items now #748.

**Comment by jennifer1995** [comment]
> Could you please explicitly specify `--batchsize 0` during decoding (e.g., https://github.com/espnet/espnet/blob/master/egs/hkust/asr1/run.sh#L319)? There is a bottleneck for the CTC prefix score computations when we use larger outputs. If it does not solve, you may reduce the beam size. Making decoder faster is one of our important action items now #748.

ok, i will try it 
Thank you
