### ISSUE TITLE
First layer_norm in transformer {encoder,decoder}_layer

### ISSUE THREAD

**Issue by kan-bayashi** [espnet/espnet#766]
Hi @ShigekiKarita. I have a question about transformer `{encoder,decoder}_layer` op.

https://github.com/espnet/espnet/blob/88c81722113bb83a20128c38eceeb951c2d7964e/espnet/nets/pytorch_backend/transformer/encoder_layer.py#L25-L35
https://github.com/espnet/espnet/blob/88c81722113bb83a20128c38eceeb951c2d7964e/espnet/nets/pytorch_backend/transformer/decoder_layer.py#L28-L42

Here, we first apply `layer_norm`, but in my understanding, in paper not applied.
Do you have any intention about this op?

**Comment by kan-bayashi** [comment]
In my understanding, `decoder_layer` op should be as follows:

```python
    def forward(self, tgt, tgt_mask, memory, memory_mask):
        """Compute decoded features

        :param torch.Tensor tgt: decoded previous target features (batch, max_time_out, size)
        :param torch.Tensor tgt_mask: mask for x (batch, max_time_out)
        :param torch.Tensor memory: encoded source features (batch, max_time_in, size)
        :param torch.Tensor memory_mask: mask for memory (batch, max_time_in)
        """
        x = tgt
        x = x + self.dropout(self.self_attn(x, x, x, tgt_mask))
        x = self.norm1(x)
        x = x + self.dropout(self.src_attn(x, memory, memory, memory_mask))
        x = self.norm2(x)
        x = x + self.dropout(self.feed_forward(x)), tgt_mask, memory, memory_mask
        return self.norm3(x)
```

**Comment by ShigekiKarita** [comment]
So your question is if we need layernorm on the first input (i.e., embedding)?

Yeah, the paper does not mention on that but it has in fact.
- tensor2tensor default (according to fairseq https://github.com/pytorch/fairseq/blob/8ce2c35d8e2dfb2b6dd220058710f81df5eb5729/fairseq/models/transformer.py#L814)
- opennmt https://github.com/OpenNMT/OpenNMT-py/blob/master/onmt/decoders/transformer.py#L69

**Comment by ShigekiKarita** [comment]
If you wanna remove that on TTS, you can add some options like fairseq. I do not have strong opinion about that. I just wanna followed the default impl (t2t)

**Comment by kan-bayashi** [comment]
I see. Thanks.
