### ISSUE TITLE
Warning in installation

### ISSUE THREAD

**Issue by takenori-y** [espnet/espnet#791]
In `v.0.4.0`, the default value of `TH_VERSION` is 1.0.1 in `tools/Makefile`, but the value is not included in `tools/check_install.py`. This causes a warning.
https://github.com/espnet/espnet/blob/94fdb49217c7d632b2ccdbd45c3e867246ada3e4/tools/Makefile#L8-L9
https://github.com/espnet/espnet/blob/94fdb49217c7d632b2ccdbd45c3e867246ada3e4/tools/check_install.py#L23

**Comment by kan-bayashi** [comment]
When installing pytorch == 1.0.1, the version name became "1.0.1.post2".
So I added "1.0.1.post2" in `check_install.py`.
```
$ pip list | grep torch
torch                  1.0.1.post2
torch-complex          0.0.0
warpctc-pytorch        0.1.1
```
