### ISSUE TITLE
- or _

### ISSUE THREAD

**Issue by kamo-naoyuki** [espnet/espnet#792]
Very trivial matter. 
The name of scripts in utils sometimes has `-` and the other has `_`.

- `make_stft.sh`
-  `compute-fbank-feats.py`

I want to unify them.

**Comment by kan-bayashi** [comment]
When I implemented this function, I wanted to replace kaldi commands, so I used "-".
It is OK to replace all of "-" with "_" in file name.

**Comment by r9y9** [comment]
A bit different topic though, we may also need to be consistent with the use of `A-to-B` or `A2B`. https://github.com/espnet/espnet/tree/master/utils
