### ISSUE TITLE
Default value of ngpu

### ISSUE THREAD

**Issue by takenori-y** [espnet/espnet#794]
The default value of `ngpu` in `run.sh` is 0 or 1. I think it should be same in all the recipes to avoid confusion.

**Comment by sw005320** [comment]
I agree with you. I'm trying to make everything `ngpu=0`, but it seems that I could not carefully check everything. It would be great if you fix it to `ngpu=0`.

**Comment by kan-bayashi** [comment]
Why don’t you use `ngpu=1` as default?
I think non-cuda users are less than the others.

**Comment by sw005320** [comment]
OK. Let's do it.
