### ISSUE TITLE
map int instead of float

### ISSUE THREAD

**Issue by ShigekiKarita** [espnet/espnet#8]
Hi,

I think that this float cast from str might be wrong
https://github.com/espnet/espnet/blob/384b3450ee5b7e3b9147c28c6064b119ab766fda/src/nets/e2e_asr_attctc.py#L150

it could be
``` python
ys = [self.xp.array(map(int, i[1]['tokenid'].split()), dtype=np.int32) for i in data]
```

**Comment by sw005320** [comment]
Thanks!
I'll fix it.

**Comment by sw005320** [comment]
This is fixed.
