### ISSUE TITLE
fisher_callhome_spanish/asr1 is not working

### ISSUE THREAD

**Issue by sw005320** [espnet/espnet#804]
@JaejinCho, I just ran your recipe, but it did not work in the beginning stage.
The number of transcription directories is 755, not 819.
Could you please fix it?

```
 ./run.sh
stage 0: Data preparation
Incorrect number of files in the data directories
DISC1 and DISC2 should contain 411 and 408 .sph files respectively (Total = 819)
The transcripts should contain 819 files
```

**Comment by JaejinCho** [comment]
I am sorry @sw005320 that I couldn't respond to this request at the time for some reason.
