### ISSUE TITLE
Incorrect number of feature dimensions with VGG + RNN

### ISSUE THREAD

**Issue by jan-schuchardt** [espnet/espnet#807]
Hi,

I just ran into the following problem when trying to train with the VGG convnet (encoder type 'vggblstmp').

For an input of size B x T x F, VGG always returns a tensor of size Batch x T/4 x 128.
One would assume that the number of feature dimensions for the subsequent RNN should also be 128.

But to determine the number of feature dimensions for the RNN, we call

```
def get_vgg2l_odim(idim, in_channel=3, out_channel=128):
    idim = idim / in_channel
    idim = np.ceil(np.array(idim, dtype=np.float32) / 2)  # 1st max pooling
    idim = np.ceil(np.array(idim, dtype=np.float32) / 2)  # 2nd max pooling
    return int(idim) * out_channel  # numer of channels
```

which yields F / 4 / in_channel * 128, causing a dimension mismatch.
Shouldn't that method just return the number of filters of the final convolutional layer (128)?

If this is the case, I can create a pull request.

**Comment by sw005320** [comment]
Thanks. This might be a problem, but I just want to understand.
I thought that VGG (normal 2-D CNN) returns Batch x T/4 x F/4 x 128... (Batch x (2-d image) x out_channel). Am I wrong?

**Comment by jan-schuchardt** [comment]
The problem was actually on my side, because I passed the wrong in_channel parameter to the VGG constructor.

It returns Batch x T/4 x (128 * F/4). This is consistent with what is calculated in get_vgg2l_odim.

I think only the docstring of the forward() method must be corrected. That is what got me confused in the first place.

**Comment by sw005320** [comment]
Sure, I'll fix it.

**Comment by sw005320** [comment]
This part?
https://github.com/espnet/espnet/blob/master/espnet/nets/pytorch_backend/encoders.py#L163-L165

**Comment by jan-schuchardt** [comment]
Exactly. It should be

'return: batch of padded hidden state sequences (B, Tmax // 4, 128 * D // 4)'

**Comment by sw005320** [comment]
Done. Thanks!
