### ISSUE TITLE
TTS synthesis using yes-no dataset

### ISSUE THREAD

**Issue by desothier1** [espnet/espnet#811]
HI

For using the yes-no dataset to train a TTS model,
training and testing generated no errors.

However the final wav files in outputs_model.loss.best_th0.5_mlr0.0-10.0_denorm,
generated with convert_fbank.sh, that convertes fbank features,

are empty.

Any help is welcome

Thanks!

**Comment by kan-bayashi** [comment]
Hi @desothier1.
`egs/yes-no/tts1` recipe is for just debugging.
The trained model cannot generate any speech because the dataset is too small.
I recommend to use `egs/ljspeech/tts1` or `egs/m_ailabs/tts1` to build speech generatable model.

**Comment by kamo-naoyuki** [comment]
Empty is strange, it should generate some sound files though It's not like speech.
I ran the run.sh just now and I can see some wav files at 'exp/train_nodev_pytorch_train_pytorch_tacotron2/outputs_model.loss.best_decode_denorm/test_yesno/wav/, so maybe your script may was exited with some errors.

**Comment by desothier1** [comment]
hi, yes, indeed it generated sound files, but not like speech.
As suggested by kan-bayashi, using egs/m_ailabs/tts1, works.
I let it run on only one epoch, and this time wav files with (garbled) speech generated.
Now running it on the 200 default epochs...
Thx!
