### ISSUE TITLE
question - check which train data/acoustic features used for test data

### ISSUE THREAD

**Issue by desothier1** [espnet/espnet#814]
Hi

This is a question, and maybe not the right place to ask:
With ESPnet ASR, is there a way to check which train data, or which acoustic features from the train data are most used is test data, in order to check the quality of the train data,
or from certain speakers in the train data.

Thx for helping

**Comment by sw005320** [comment]
If you want to check the speaker overlap between training and test data, you could check `data/train_960/spk2utt` to get the speaker information. But it is difficult to check the `quality` in general.
