### ISSUE TITLE
Error in SentencePiece installation.

### ISSUE THREAD

**Issue by Natalia-T** [espnet/espnet#832]
From June, SentencePiece has started to use Bazel instead of CMake. This causes an installation error for SentencePiece.

**Comment by sw005320** [comment]
Thanks for your report.
@jnishi, could you test it?

**Comment by sw005320** [comment]
Maybe we can use `pip install`?

**Comment by jnishi** [comment]
According to the README, `Note: We're actively refactoring the codebase to simplify support for open source releases and Google internal needs. During this time, builds and tests will be unstable and not all features will be supported.` , and python binding is removed.

We'd better use latest released(v0.1.82) tagged version until their refactoring is finished.

**Comment by sw005320** [comment]
> We'd better use latest released(v0.1.82) tagged version until their refactoring is finished.

Thanks. Could you make a PR to fix to use v0.1.82 temporally?

**Comment by sw005320** [comment]
@Natalia-T, we just used v0.1.82 to avoid the issue. We fixed this at https://github.com/espnet/espnet/tree/v.0.4.0 (v.0.4.0 branch), which will be merged to the master soon.

**Comment by Natalia-T** [comment]
Thank you.
