### ISSUE TITLE
json2trn_mt.py is missing

### ISSUE THREAD

**Issue by Natalia-T** [espnet/espnet#841]
An error message appears in the IWSLT18 recipe, in local/score_bleu.sh. 

local/score_bleu.sh: line 28: json2trn_mt.py: command not found
 
https://github.com/espnet/espnet/blob/master/egs/iwslt18/st1/local/score_bleu.sh
 
json2trn_mt.py ${dir}/data.json ${dic_tgt} --ref ${dir}/ref.trn.org \
    --hyp ${dir}/hyp.trn.org --src ${dir}/src.trn.org --dict-src ${dic_src}

**Comment by sw005320** [comment]
Thanks for the report. 
@hirofumi0810, I checked master, v.0.4.0, and your PR, but I could not find it. Could you prepare it?

**Comment by hirofumi0810** [comment]
@Natalia-T , thank you for letting me know. I fixed it in #808.

**Comment by kan-bayashi** [comment]
Fixed #808
