### ISSUE TITLE
Error when installing espnet

### ISSUE THREAD

**Issue by ghost** [espnet/espnet#856]
Hello,

I am getting an error when installing espnet. 

Warning: IRSTLM is not installed by default anymore. If you need IRSTLM
Warning: use the script extras/install_irstlm.sh
All done OK.
make[1]: Leaving directory '/home/nvm/espnet/tools/kaldi/tools'
cd kaldi/src; ./configure --shared --use-cuda=no; make depend; make all
Configuring KALDI to use MKL.
Checking compiler g++ ...
Checking OpenFst library in /home/nvm/espnet/tools/kaldi/tools/openfst-1.6.7 ...
Doing OS specific configurations ...
On Linux: Checking for linear algebra header files ...
Configuring MKL library directory: ***configure failed: MKL libraries could not be found. Please use the switch --mkl-libdir or try another math library, e.g. --mathlib=ATLAS (would be slower) ***
make[1]: Entering directory '/home/nvm/espnet/tools/kaldi/src'
Makefile:30: kaldi.mk: No such file or directory
kaldi.mk does not exist; you have to run ./configure
Makefile:90: recipe for target 'kaldi.mk' failed
make[1]: *** [kaldi.mk] Error 1
make[1]: Leaving directory '/home/nvm/espnet/tools/kaldi/src'
make[1]: Entering directory '/home/nvm/espnet/tools/kaldi/src'
Makefile:30: kaldi.mk: No such file or directory
kaldi.mk does not exist; you have to run ./configure
Makefile:90: recipe for target 'kaldi.mk' failed
make[1]: *** [kaldi.mk] Error 1
make[1]: Leaving directory '/home/nvm/espnet/tools/kaldi/src'
Makefile:42: recipe for target 'kaldi.done' failed
make: *** [kaldi.done] Error 2

Pleas help in resolving.

**Comment by ShigekiKarita** [comment]
Recently, kaldi assume MKL as default BLAS library. See also
https://github.com/kaldi-asr/kaldi/pull/3257
https://github.com/kaldi-asr/kaldi/pull/3194

You have two options
- install MKL https://kaldi-asr.org/doc/matrixwrap.html#matrixwrap_mkl
- patch this line as `cd kaldi/src; ./configure --shared --use-cuda=no --mathlib=ATLAS; $(MAKE) depend; $(MAKE) all `
https://github.com/espnet/espnet/blob/06271abde64d81f2579fc8c1ba105261a23de362/tools/Makefile#L44

**Comment by nvidiaman** [comment]
@ShigekiKarita  thank you! i am on a gpu machine, will use-cuda==no still be true?

**Comment by nvidiaman** [comment]
@ShigekiKarita now i get:


2019-06-15 17:25:20,039 (lm:311) INFO: #tokens in the validation$
2019-06-15 17:25:20,039 (lm:312) INFO: oov rate in the validatio$
2019-06-15 17:25:20,040 (lm:321) INFO: #iterations per epoch = 3
2019-06-15 17:25:20,040 (lm:322) INFO: #total iterations = 60
Traceback (most recent call last):
  File "/home/nvm/espnet/egs/an4/asr1/../../../espnet/bin/lm$
    main(sys.argv[1:])
  File "/home/nvm/espnet/egs/an4/asr1/../../../espnet/bin/lm$
    train(args)
  File "/home/nvm/espnet/espnet/lm/chainer_backend/lm.py", l$
    chainer.cuda.get_device_from_id(gpu_id).use()
  File "/home/nvm/espnet/tools/venv/lib/python3.7/site-packa$
    check_cuda_available()
  File "/home/nvm/espnet/tools/venv/lib/python3.7/site-packa$
    raise RuntimeError(msg)
RuntimeError: CUDA environment is not correctly set up
(see https://github.com/chainer/chainer#installation).No module $
# Accounting: time=3 threads=1
# Ended (code 1) at Sat Jun 15 17:25:20 EDT 2019, elapsed time 3$

i isntalled cupy and can import cupy in python console. please help.

**Comment by sw005320** [comment]
Can you perform `make check_install` at `espnet/tools` directory, and show me the log?
If this looks normal, the problem might be your GPU/CUDA environment.

**Comment by ShigekiKarita** [comment]
Or you can try `--backend pytorch` to check your CUDA is sane.
