### ISSUE TITLE
How to put data in babel experiment

### ISSUE THREAD

**Issue by ghost** [espnet/espnet#870]
Hi

I followed the babel ReadMe and in this step:

./run.sh --langs "102" --recog "102"

I get the error:

Unable to open vocabulary file /export/babel/data/102-assamese/release-current/conversational/reference_materials/lexicon.txt at local/prepare_acoustic_training_data.pl line 131.
cat: data/train.tmp/segments: No such file or directory
./utils/subset_data_dir.sh: no such file data/train.tmp/utt2spk
awk: fatal: cannot open file `data/train_dev/utt2spk' for reading (No such file or directory)
awk: fatal: cannot open file `data/train.tmp/utt2spk' for reading (No such file or directory)
./utils/subset_data_dir.sh: no such file data/train.tmp/utt2spk
Prepend 102 to data dir
copy_data_dir.sh: no such file data/train/utt2spk
copy_data_dir.sh: no such file data/train_dev/utt2spk
copy_data_dir.sh: no such file data/dev10h.pem/utt2spk
./utils/combine_data.sh data/train data/102/data/train_102

There is a data folder in my experiment folder but the train folder inside it is empty.

How to use the data in this example?

./utils/combine_data.sh: no such file data/102/data/train_102/utt2spk

**Comment by creatorscan** [comment]
You need to change the path ("/export/babel/data/102-assamese/") of your BABEL data directory in conf/lang.conf, as the default setup works only at JHU.
