### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by r9y9** [espnet/espnet#876]
Current documentation in README explains how to install the toolkit and how to run examples. However, I don't think this is enough for users who want to make some changes to the existing recipes or make their own new recipe. In that case, one needs to understand what `run.sh` does step by step, but I think docs for that are missing at the moment. It would be great if we provide documentation for:

- Data format used in the espnet. How data.json is structured?
- Core command line tools: https://github.com/espnet/espnet/tree/master/espnet/bin. What is the input and output format?
- Utility tools https://github.com/espnet/espnet/tree/master/utils. Looks like there are many tools but when should I use them?
- espnet python packages https://github.com/espnet/espnet/tree/master/espnet (ref https://github.com/espnet/espnet/issues/57) I can see very limited docs on https://espnet.github.io/espnet/.

I think docs for the above items (and possibly more) help users get started to hack the toolkit.

EDIT: I meant *new users* or developers except for the current core developers.

**Comment by ShigekiKarita** [comment]
Maybe it is time to enrich 
- CONTRIBUTING.md https://github.com/espnet/espnet/blob/master/CONTRIBUTING.md or docs
- sphinx doc https://github.com/espnet/espnet/tree/master/doc

**Comment by ShigekiKarita** [comment]
Everything is undocumented as you mentioned but I just gather info

> - Data format used in the espnet. How data.json is structured?

See https://github.com/espnet/espnet/pull/493#issuecomment-447731276

> - Core command line tools: https://github.com/espnet/espnet/tree/master/espnet/bin. What is the input and output format?

Never documented but I do not think it is difficult to make doc on these. Their input and output are just NN models and `data.json` with its external files basically.

> - Utility tools https://github.com/espnet/espnet/tree/master/utils. Looks like there are many tools but when should I use them?

For documenting input/output of tools under `utils/`, these tests are helpful. https://github.com/espnet/espnet/tree/master/test_utils

> - espnet python packages https://github.com/espnet/espnet/tree/master/espnet (ref #57) I can see very limited docs on https://espnet.github.io/espnet/.

It is very limited but I think it is the best place to place docs

**Comment by r9y9** [comment]
Thank you for the information! As for the json format, I already looked into the actual data and your mentioned thread, but I was a little confused because the format used in ljspeech/tts1 recipe is a bit different from what mentioned in the thread:

```json
{
    "utts": {
        "LJ049-0008": {
            "input": [
                {
                    "feat": "/Users/ryuichi/espnet/egs/ljspeech/tts1/dump/dev/feats.1.ark:11",
                    "name": "input1",
                    "shape": [
                        511,
                        80
                    ]
                }
            ],
```

As you can see, there's no `filetype` field. Anyway, it would be nice if its format is documented.

As for the CLI tools, I'm thinking about something similar to https://fairseq.readthedocs.io/en/latest/command_line_tools.html. It's much easier for me to understand than reading source code written with argparser.

**Comment by ShigekiKarita** [comment]
Maybe in the later discussion, we decided `filetype` is optional because we can see the extensions `.ark`, `.h5`, etc. Thanks for the good example. Fairseq always shows us the best way to go...

**Comment by sw005320** [comment]
Thanks for raising the issue.
Yes, you're right.
We'll need to have a special project to enrich the document...

@ShigekiKarita and @kan-bayashi, could you make one or two hours to do it?
Let's try to distribute our efforts to fix the above items.
We basically update https://espnet.github.io/espnet/. `README.md` is also getting bigger, and we should move some contents to https://espnet.github.io/espnet/.

**Comment by kamo-naoyuki** [comment]
As it is very hard to create the documentation for all `utils`, and I believe that there are not need to do much, so we must prioritize them. The highest priority is data.json, as @r9y9 said. 
Small tutorial using Jupyter notebook is also helpful, like

```python
[1] import json
[4] from espnet.utils.training.batchfy import make_batchset
[5] from espnet.utils.io_utils import LoadInputsAndTargets
[7] from espnet.asr.pytorch_backend.asr import CustomConverter
[9] from espnet.nets.pytorch_backend.e2e_asr import E2E
[2] with open('data.json') as f
...     data_json = json.load(f)['utts']
[3] print(data_json)
{...}
[6] loadfunc = LoadInputsAndTargets(...)
[8] converter = CustomConverter
[10] model = E2E(...)
[11]  # 0. Batchfy the dict information from "data.json"
[12] dataset = make_batchset(data_json, ...)
[13] for batch in dataset: # batch: List[Tuple[str, dict]]
...      # 1. Load data and create np.ndarray from the information of "batch"
...     xs, ys = loadfunc(batch) # xs, ys: List[np.ndarray]
...     # 2. Changed the list of np.ndarray to a contiguous tensor and zero padding
...     xs_pad, ilens, ys_pad = converter([xs, ys]) # xs_pad, ilens, ys_pad: torch.Tensor
...     # 3. Give them to the model
...     loss = E2E(xs_pad, ilens, ys_pad)
```

I wanna create ci building for such jupyter notebook to avoid using obsolete method.

We may also need to categorize `utils` to make self documented. 
Currently shell scripts and python scripts are stored in one directory. Some scripts are always invoked by another script there, but the dependency is not clear. 

What I'm thinking just now is as following, 

- **Unset** $PATH of `utils` . This is very confusing.
- Place it as egs/*/ss1/scripts. and make utils more structured, e.g.
```
scripts/
   feat/
      python/  # Invoked scripts? Or, We can set PATH only for python scripts.
   text/
   json/
   yaml/
   score/ 
```
- I am also thinking to replace run.pl, slurm.pl, etc. because, inevitably, it requires deep wrapping by shell script and it is a reason of too many shell scripts there.  Actually this is hard work. Probably I won't.

Unfortunately, I have already al lot of tasks, so I wouldn't help you about this matter.

**Comment by sw005320** [comment]
Today, I, @ShigekiKarita, and @kan-bayashi discussed this issue.

1. We'll automatically generate the `class`, `binary`, and `utils/*.{sh.py}` descriptions, and update them to our webpage.

2. We'll add some descriptions by basically following @kamo-naoyuki's suggestions using Jupyter 
 notebook, constantly (at least data structure, main loop etc.)

We are now working on 1.

**Comment by ShigekiKarita** [comment]
Item 1 is done. Now the `ci/doc.sh` script generates all the modules under `espnet` and tools under `espnet/bin` and `utils` automatically.

See updated master doc https://espnet.github.io/espnet/
