### ISSUE TITLE
Enhancing Transformer TTS

### ISSUE THREAD

**Issue by r9y9** [espnet/espnet#889]
S. Yang et al, "Enhancing Hybrid Self-attention Structure with Relative-position-aware Bias for Speech Synthesis,", Proc of ICASSP, 2019. 

- Paper: https://ieeexplore.ieee.org/document/8682861
- Samples: https://syang1993.github.io/relation-aware/

It's worth trying the following two ideas:

- Relative position aware self-attention
- Hybrid architecture using both self-attention and RNN in encoder.

See also 

- ICASSP2019音声＆音響論文読み会 論文紹介（合成系） #icassp2019jp https://www.slideshare.net/tomokikoriyama/icassp2019-149042508
- Youtube live: https://www.youtube.com/watch?v=2E-dvGem27g

Ref #752 #848

**Comment by sw005320** [comment]
> Hybrid architecture using both self-attention and RNN in the encoder.

I have a similar idea for ASR, but we always have some GPU memory issues.
Maybe it's not serious in TTS?

**Comment by kan-bayashi** [comment]
Thank you for your information.
This is related to my interspeech paper, i.e. dual-stream encoder Tacotron2.
In the case of TTS, the lengths of input sequence is not so large, and therefore, GPU memory might be a problem but not serious.

**Comment by r9y9** [comment]
This is on my todo list.
