### ISSUE TITLE
How to train iwslt18 and tedlium2 together

### ISSUE THREAD

**Issue by CherrieWang97** [espnet/espnet#896]
I'd like to train an ASR model using iwslt18 data and tedlium2 data together, should I pre-process these two corpus with the same process or can I just use the pre-process methods from the two recipe and train them together? 
BTW, is there any better segmentation tools for iwslt18 audio? It seems that the official segmentation files are noisy.
Thanks

**Comment by sw005320** [comment]
@hirofumi0810 could you answer the questions?

**Comment by hirofumi0810** [comment]
@CherrieWang97 
For dataset concatenation, please refer to the multilingual recipe such as jsalt18e2e.
You should compute fbank in tedlium2 and iwslt18 at first, then concatenate these datasets.

For segmentation, we removed noisy utterances after forced alignments.
You can use filtered, clean utterances in the current recipe.
