### ISSUE TITLE
pytorch exp

### ISSUE THREAD

**Issue by ShigekiKarita** [espnet/espnet#9]
Hi, @sw005320 

this is not an issue, just my homework for fun. I'm making pytorch backend on your script for chainer. 

https://github.com/ShigekiKarita/espnet/blob/pytorch/src/bin/asr_train_th.py

Unless nothing is wrong (well, I don't think so ... for example, the lack of CTC loss implementation), pytorch seems twice faster than chainer in my poor environment (GTX760).

**Comment by sw005320** [comment]
Great!!!
I think it would be nice to have two implementations (like Keras that uses several backends).
We can discuss it tomorrow.
I'm really excited.

I would say that my chainer-based implementation is already very nice level in terms of training speed, and if it would be twice faster, it is super duper.

**Comment by ShigekiKarita** [comment]
Training BLSTMP on WSJ in 4 hours by pytorch and 1080ti

```
chainer:
this epoch [#####.............................................] 10.92%
       200 iter, 0 epoch / 15 epochs
   0.50112 iters/sec. Estimated time to finish: 15:07:17.560377.

pytorch:
this epoch [##########........................................] 21.83%                                              
       400 iter, 0 epoch / 15 epochs                      
    1.8472 iters/sec. Estimated time to finish: 4:04:20.062329.
```

**Comment by sw005320** [comment]
This is amazing.
We should definitely consider to have both backends.
Please continue on it, and also try to include CTC and try to make it similar to the chainer backend.

**Comment by ShigekiKarita** [comment]
@sw005320 I've implemented the CTC loss function with [WarpCTC binding](https://github.com/SeanNaren/warp-ctc) (not push yet). It does not matter at all in speed.

```
this epoch [#####.............................................] 10.92%
       200 iter, 0 epoch / 15 epochs
    1.9304 iters/sec. Estimated time to finish: 3:55:31.877189.
```

**Comment by ShigekiKarita** [comment]
Pytorch backend is finally merged. As @sw005320 noted in #17, we need to add pytorch backend not only in WSJ but also in all the egs. It is not difficult for me and also for anyone else.

However there is a new concern about results. Here are WSJ-BLSTMP results by chainer and pytorch.

- chainer

![acc](https://user-images.githubusercontent.com/6745326/34089579-73f5c028-e3f4-11e7-9811-774a1fdbd7df.png)

![loss](https://user-images.githubusercontent.com/6745326/34089665-48bd8228-e3f5-11e7-90b7-83c2b60b1641.png)


exp/train_si284_ch_blstmp_ctc_1080ti_fix/decode_test_dev93_beam20_eacc.best_p0_len0.3-0.8/result.txt:|   SPKR     |  # Snt      # Wrd   |  Corr        Sub       Del        Ins       Err      S.Err   |
exp/train_si284_ch_blstmp_ctc_1080ti_fix/decode_test_dev93_beam20_eacc.best_p0_len0.3-0.8/result.txt:|   Sum/Avg  |   503       49334   |  91.8        3.9       4.3        2.5      10.7       95.0   |
exp/train_si284_ch_blstmp_ctc_1080ti_fix/decode_test_eval92_beam20_eacc.best_p0_len0.3-0.8/result.txt:|   SPKR     |  # Snt      # Wrd   |   Corr       Sub        Del        Ins       Err      S.Err   |
exp/train_si284_ch_blstmp_ctc_1080ti_fix/decode_test_eval92_beam20_eacc.best_p0_len0.3-0.8/result.txt:|   Sum/Avg  |   333       33740   |   93.7       3.1        3.3        2.0       8.3       90.1   |

- pytorch

![acc](https://user-images.githubusercontent.com/6745326/34089585-81c13822-e3f4-11e7-85e1-fedad9c3197c.png)

![loss](https://user-images.githubusercontent.com/6745326/34089655-38c03500-e3f5-11e7-9d26-43de675839ee.png)

(accidentally, I forgot to turn on ctc-loss plot. please minus attn-loss in your eyes)

exp/train_si284_th_blstmp_ctc_1080ti_fix/decode_test_dev93_beam20_eacc.best_p0_len0.3-0.8/result.txt:|   SPKR     |  # Snt      # Wrd   |  Corr        Sub       Del        Ins       Err      S.Err   |
exp/train_si284_th_blstmp_ctc_1080ti_fix/decode_test_dev93_beam20_eacc.best_p0_len0.3-0.8/result.txt:|   Sum/Avg  |   503       49334   |  87.8        5.4       6.8        3.5      15.6       97.6   |
exp/train_si284_th_blstmp_ctc_1080ti_fix/decode_test_eval92_beam20_eacc.best_p0_len0.3-0.8/result.txt:|   SPKR     |  # Snt      # Wrd   |   Corr       Sub        Del        Ins       Err      S.Err   |
exp/train_si284_th_blstmp_ctc_1080ti_fix/decode_test_eval92_beam20_eacc.best_p0_len0.3-0.8/result.txt:|   Sum/Avg  |   333       33740   |   89.8       4.1        6.0        2.8      13.0       97.0   |


As you can see in training curves, pytorch should have different loss-normalization behavior or weight initialization. I'm gonna work on investigations around them now.

**Comment by ShigekiKarita** [comment]
I summarize the differences between **default** behaviors in chainer and pytorch. I'm always trying to make pytorch's setting **consistent to chainer** in espnet.

this is a compatible options tested in `test/test_loss.py`

### CTC

``` python
# NOTE: warpctc_pytorch.CTCLoss does not normalize itself by batch-size unlike chainer's default
ch_loss = F.connectionist_temporal_classification(ch_pred, ch_target, 0, input_length, label_length)
th_loss = CTCLoss()(th_pred, th_target, th_ilen, th_olen) / n_batch
```

Cross-entropy loss and accuracy in decoder is also tested in https://github.com/ShigekiKarita/espnet/blob/test-pytorch-loss/test/test_loss.py



## Weight initialization

- pytorch global default: `W, b ~ Uniform(-fan_in**-0.5, fan_in**-0.5)`
- chainer global default: `W ~ Normal(0.0, fan_in**-0.5), b = 0` known as LeCun init http://yann.lecun.com/exdb/publis/pdf/lecun-98b.pdf
- chainer & pytorch exception: `EmbedID.W ~ Normal(0.0, 1.0)`. this is reasonable because many initialization and misc normalization methods assumes input data distribution is standardized like this way.
- only chainer exception: As famous forget-bias init `LSTM.bias[forget_part] = 1.0` but `NStepLSTM` does not have such a initialization.

Those behavior and consistency in my implementation are tested in https://github.com/ShigekiKarita/espnet/blob/test-pytorch-loss/test/test_initialization.py

In my WSJ exp, chainer's method used in pytorch

![acc](https://user-images.githubusercontent.com/6745326/34187461-d72ee288-e574-11e7-89bf-8833ed8bbad1.png)


showed a better learning-curve than pytorch's default one (see previous comment)

## Optimizer hyper-parameters

- Adadelta: `rho=0.95` in chainer but `rho=0.9` in pytorch
- Adam: implementations seem to be different in mean-square computations

In my WSJ exp, adadelta parameter `rho=0.95` seems to be better .

![acc](https://user-images.githubusercontent.com/6745326/34187545-5cbb8154-e575-11e7-81f8-714cc09cdee5.png)

However, we can still see something missing in pytorch implementation. I'm checking decoder implementation.

**Comment by kan-bayashi** [comment]
I had following error in tedlium recipe with pytorch.
```
# asr_train_th.py --gpu 0 --outdir exp/train_trim_blstmp_e4_subsample1_2_2_1_1_unit320_proj320_d1_unit300_location_ac
onvc10_aconvf100_mtlalpha0.5_adadelta_bs30_mli800_mlo150/results --debugmode 1 --dict data/lang_1char/train_trim_unit
s.txt --debugdir exp/train_trim_blstmp_e4_subsample1_2_2_1_1_unit320_proj320_d1_unit300_location_aconvc10_aconvf100_m
tlalpha0.5_adadelta_bs30_mli800_mlo150 --minibatches 0 --verbose 0 --train-feat scp:dump/train_trim/deltafalse/feats.
scp --valid-feat scp:dump/dev_trim/deltafalse/feats.scp --train-label dump/train_trim/deltafalse/data.json --valid-la
bel dump/dev_trim/deltafalse/data.json --etype blstmp --elayers 4 --eunits 320 --eprojs 320 --subsample 1_2_2_1_1 --d
layers 1 --dunits 300 --atype location --aconv-chans 10 --aconv-filts 100 --mtlalpha 0.5 --batch-size 30 --maxlen-in
800 --maxlen-out 150 --opt adadelta --epochs 15
2017-12-21 14:48:35,318 (asr_train_th:375) WARNING: Skip DEBUG/INFO messages
epoch       iteration   main/loss   main/loss_ctc  main/loss_att  validation/main/loss  validation/main/loss_ctc  val
idation/main/loss_att  main/acc    validation/main/acc  elapsed_time  eps
ESC[J0           100         3911.38                    433.47
                            0                                171.865       1e-08
ESC[J     total [..................................................]  0.14%
this epoch [#.................................................]  2.06%
       100 iter, 0 epoch / 15 epochs
       inf iters/sec. Estimated time to finish: 0:00:00.
:
ESC[J     total [..................................................]  1.10%
this epoch [########..........................................] 16.44%
       800 iter, 0 epoch / 15 epochs
   0.81688 iters/sec. Estimated time to finish: 1 day, 0:32:34.790102.
ESC[4AException in main training loop: the given numpy array has zero-sized dimensions. Zero-sized dimensions are not supported in PyTorch
Traceback (most recent call last):
  File "/work3/t_hayashi/work/espnet_debug/tools/venv/lib/python2.7/site-packages/chainer/training/trainer.py", line 299, in run
    update()
  File "/work3/t_hayashi/work/espnet_debug/tools/venv/lib/python2.7/site-packages/chainer/training/updater.py", line 223, in update
    self.update_core()
  File "/work3/t_hayashi/work/espnet_debug/egs/tedlium/asr1/../../../src/bin/asr_train_th.py", line 126, in update_core
    loss = self.model(x)
  File "/work3/t_hayashi/work/espnet_debug/tools/venv/lib/python2.7/site-packages/torch/nn/modules/module.py", line 325, in __call__
    result = self.forward(*input, **kwargs)
  File "/work3/t_hayashi/work/espnet_debug/src/nets/e2e_asr_attctc_th.py", line 102, in forward
    loss_ctc, loss_att, acc = self.predictor(x)
  File "/work3/t_hayashi/work/espnet_debug/tools/venv/lib/python2.7/site-packages/torch/nn/modules/module.py", line 325, in __call__
    result = self.forward(*input, **kwargs)
  File "/work3/t_hayashi/work/espnet_debug/src/nets/e2e_asr_attctc_th.py", line 178, in forward
    ys = [to_cuda(self, Variable(torch.from_numpy(y))) for y in ys]
Will finalize trainer extensions and updater before reraising the exception.
ESC[JTraceback (most recent call last):
  File "/work3/t_hayashi/work/espnet_debug/egs/tedlium/asr1/../../../src/bin/asr_train_th.py", line 567, in <module>
    main()
  File "/work3/t_hayashi/work/espnet_debug/egs/tedlium/asr1/../../../src/bin/asr_train_th.py", line 563, in main
    trainer.run()
  File "/work3/t_hayashi/work/espnet_debug/tools/venv/lib/python2.7/site-packages/chainer/training/trainer.py", line 313, in run
    six.reraise(*sys.exc_info())
  File "/work3/t_hayashi/work/espnet_debug/tools/venv/lib/python2.7/site-packages/chainer/training/trainer.py", line 299, in run
    update()
  File "/work3/t_hayashi/work/espnet_debug/tools/venv/lib/python2.7/site-packages/chainer/training/updater.py", line 223, in update
    self.update_core()
  File "/work3/t_hayashi/work/espnet_debug/egs/tedlium/asr1/../../../src/bin/asr_train_th.py", line 126, in update_core
    loss = self.model(x)
  File "/work3/t_hayashi/work/espnet_debug/tools/venv/lib/python2.7/site-packages/torch/nn/modules/module.py", line 325, in __call__
    result = self.forward(*input, **kwargs)
  File "/work3/t_hayashi/work/espnet_debug/src/nets/e2e_asr_attctc_th.py", line 102, in forward
    loss_ctc, loss_att, acc = self.predictor(x)
  File "/work3/t_hayashi/work/espnet_debug/tools/venv/lib/python2.7/site-packages/torch/nn/modules/module.py", line 325, in __call__
    result = self.forward(*input, **kwargs)
  File "/work3/t_hayashi/work/espnet_debug/src/nets/e2e_asr_attctc_th.py", line 178, in forward
    ys = [to_cuda(self, Variable(torch.from_numpy(y))) for y in ys]
RuntimeError: the given numpy array has zero-sized dimensions. Zero-sized dimensions are not supported in PyTorch
```
I will investigate the reason.

**Comment by ShigekiKarita** [comment]
@kan-bayashi Hmm, you seem to use blstmp not vgg blstmp. I think the zero-size should be happened in Encoder's subsample part. And tedlium has really short utt (please turn on verbose=2 to see the length). I will also check that.

**Comment by ShigekiKarita** [comment]
BTW, I might finally figure out the last reason why pytorch's convergence is worse than chainer. The diff is ctc gradient that is also unormalized by batchsize as forward prop. I've fixed and tested in #20 

![acc](https://user-images.githubusercontent.com/6745326/34245678-62203172-e66e-11e7-89cd-42d495851000.png)

current tested list

- https://github.com/ShigekiKarita/espnet/blob/test-pytorch-loss/test/test_e2e_model.py chainer/pytorch's loss output and grad equality test with constant weight normalization
- https://github.com/ShigekiKarita/espnet/blob/test-pytorch-loss/test/test_initialization.py chainer/pytorch's random weight stats (mean/stddev) equality test
- https://github.com/ShigekiKarita/espnet/blob/test-pytorch-loss/test/test_optimizer.py
chainer/pytorch's optimizer equality test
- https://github.com/ShigekiKarita/espnet/blob/test-pytorch-loss/test/test_torch.py several pytorch specific helper functions test

**Comment by ShigekiKarita** [comment]
@kan-bayashi 
I think this `ys` is a seq of target tokens. isnt it?

``` python
File "/work3/t_hayashi/work/espnet_debug/src/nets/e2e_asr_attctc_th.py", line 178, in forward
    ys = [to_cuda(self, Variable(torch.from_numpy(y))) for y in ys]
```

I wonder if chainer could ignore zero-size array for input in that case, we can also filter it out manually. Would you try to insert zero-size target assertion at `E2E.__call__` in `e2e_asr_attctc_th.py` like
``` python
class E2E(chainer.Chain):
    ...
    def __call__(self, data):
        '''

        :param data:
        :return:
        '''
        # utt list of frame x dim
        xs = [i[1]['feat'] for i in data]
        # utt list of olen
        ys = [self.xp.array(list(map(int, i[1]['tokenid'].split())), dtype=np.int32) for i in data]
        ys = [chainer.Variable(y) for y in ys]
        for y in ys:
             assert y.shape[0] > 0
```

**Comment by ShigekiKarita** [comment]
BTW, I might finally figure out the last reason why pytorch's convergence is worse than chainer. The diff is ctc gradient that is also unormalized by batchsize as forward prop. I've fixed and tested in #20 

![acc](https://user-images.githubusercontent.com/6745326/34245678-62203172-e66e-11e7-89cd-42d495851000.png)

current tested list

- https://github.com/ShigekiKarita/espnet/blob/test-pytorch-loss/test/test_e2e_model.py chainer/pytorch's loss output and grad equality test with constant weight normalization
- https://github.com/ShigekiKarita/espnet/blob/test-pytorch-loss/test/test_initialization.py chainer/pytorch's random weight stats (mean/stddev) equality test
- https://github.com/ShigekiKarita/espnet/blob/test-pytorch-loss/test/test_optimizer.py
chainer/pytorch's optimizer (Adam and Adadelta) equality test
- https://github.com/ShigekiKarita/espnet/blob/test-pytorch-loss/test/test_torch.py
several pytorch specific helper functions test
- https://github.com/ShigekiKarita/espnet/blob/test-pytorch-loss/test/test_loss.py
chainer/pytorch's loss (CTC, cross-enropy and accuracy) equality test
- https://github.com/ShigekiKarita/espnet/blob/test-pytorch-loss/test/test_io_voxforge.py
kaldi_io equality test with kaldi-python and kaldi-io-for-python

**Comment by kan-bayashi** [comment]
@ShigekiKarita 
Yes, I checked the `tokenid` in `data.json`.
And I found that it includes empty tokenid. 
```
$ less dump/train_trim/deltafalse/data.json | grep "\"tokenid\": \"\","
            "tokenid": "",
            "tokenid": "",
            "tokenid": "",
            "tokenid": "",
            "tokenid": "",
            "tokenid": "",
```
I agree with your idea, we should check the length of `ys` to skip or stop.

**Comment by ShigekiKarita** [comment]
wow nice hack 👍 

so as a workaround we will follow chainer at first. but it can be better to filter them out in data prep.

**Comment by sw005320** [comment]
We can make to use the following script as a default for all egs.
https://github.com/espnet/espnet/blob/master/egs/voxforge/asr1/local/remove_longshortdata.sh

**Comment by kan-bayashi** [comment]
@sw005320 i
In the tedlium recipe, `remove_longshortdata.sh` is already performed in `run.sh`.
But `data.json` includes empy token. 
Is it a bug of `remove_longshortdata.sh` or needs some option?

**Comment by ShigekiKarita** [comment]
I've submitted the workaround and test for pytorch in PR #20 . 

In this commit, I notice that chainer also fails when all the target have zero-length in a minibatch because of zero-div-error in CTC.

**Comment by ShigekiKarita** [comment]
I'd like to report this as a result of the final pytorch backend because this is very close to the one of the chainer backend in https://github.com/espnet/espnet/issues/9#issuecomment-352322057

exp/train_si284_th_blstmp_ctc_adadelta/decode_test_dev93_beam20_eacc.best_p0_len0.3-0.8/result.txt:|  SPKR     |   # Snt     # Wrd   |  Corr        Sub       Del       Ins        Err     S.Err   |
exp/train_si284_th_blstmp_ctc_adadelta/decode_test_dev93_beam20_eacc.best_p0_len0.3-0.8/result.txt:|  Sum/Avg  |    503      49334   |  91.6        3.9       4.5       2.7       11.1      94.6   |
exp/train_si284_th_blstmp_ctc_adadelta/decode_test_eval92_beam20_eacc.best_p0_len0.3-0.8/result.txt:|  SPKR     |   # Snt     # Wrd   |   Corr       Sub        Del       Ins        Err     S.Err   |
exp/train_si284_th_blstmp_ctc_adadelta/decode_test_eval92_beam20_eacc.best_p0_len0.3-0.8/result.txt:|  Sum/Avg  |    333      33740   |   93.9       3.0        3.1       2.0        8.2      91.0   |

also see updated figures of training progress in https://github.com/espnet/espnet/issues/9#issuecomment-353284921

However we still have a issue for inconsistency in the VGG part. I'm going to add more tests to check their equalities.
