### ISSUE TITLE
matplotlib.use('Agg') fail

### ISSUE THREAD

**Issue by naxingyu** [espnet/espnet#904]
It result in plot fail 
```
_tkinter.TclError: no display name and no $DISPLAY environment variable
```
I fixed this by applying a patch on `espnet/nets/pytorch_backend/transformer/plot.py`
```
@@ -1,5 +1,6 @@
 import logging
-
+import matplotlib
+matplotlib.use('Agg')
 import matplotlib.pyplot as plt

 from espnet.asr import asr_utils
```

**Comment by sw005320** [comment]
Oh yes, it's better to have that (we put everywhere except for this file).
Could you make a PR? (or @ShigekiKarita, can you do it?)

**Comment by naxingyu** [comment]
ok, I'll make a PR.
