### ISSUE TITLE
Make impossible due to warp_ctc error

### ISSUE THREAD

**Issue by TParcollet** [espnet/espnet#911]
Hi there,

I'm trying to install ESPNET in a cluster where Kaldi is already installed. So I basically follow the make KALDI=... CUDA=... cmd. Nonetheless, I obtain this weird error where apparently warp_ctc is not installed while the build of it seems ok ? 
<img width="959" alt="Capture d’écran 2019-06-21 à 20 43 00" src="https://user-images.githubusercontent.com/11910731/59944580-6a726380-9465-11e9-8ccb-33d8acc73b42.png">

Any ideas ? 
Thanks you !

**Comment by sw005320** [comment]
It seems that the pytorch warp CTC installation has some issues.
Can you reinstall it (`rm warp-ctc.done; make warp-ctc.done`), and show us the error logs?

**Comment by TParcollet** [comment]
Hi,

Here is the log file attached to these cmd. Please note that few hundreds lines of "warning: Instruction 'shfl' without '.sync' is deprecated since PTX ISA version 6.0" are also showing.
[log.log](https://github.com/espnet/espnet/files/3316672/log.log)

 I also have a final warning of cc1plus: warning: command line option'-Wstrict-prototype' is valid for C/ObjC but not for C++. 

![Capture d’écran 2019-06-22 à 10 49 23](https://user-images.githubusercontent.com/11910731/59961684-6c770980-94db-11e9-980a-a260af2e17b3.png)

Thanks you !

**Comment by naxingyu** [comment]
What's your gcc version?

**Comment by TParcollet** [comment]
7.3.0 according to gcc --version

**Comment by kamo-naoyuki** [comment]
Can you show the error message when import warpctc? 
```python
import warpctc_pytorch
```

**Comment by TParcollet** [comment]
So, after sourcing tools/venv and import warpctc_pytorch I have:

![Capture d’écran 2019-06-23 à 10 35 46](https://user-images.githubusercontent.com/11910731/59973635-ad862100-95a2-11e9-82bb-d594ead6b492.png)

**Comment by kamo-naoyuki** [comment]
I think you could get the following answer easily if you search the error message.

https://discuss.pytorch.org/t/undefined-symbol-when-import-lltm-cpp-extension/32627/5

As this thread said, the error comes from the ABI mismatching between pytorch and the pytorch extension. The warpctc_pytorch is built with GLIBCXX_USE_CXX11_ABI=0 by default, so I guess your pytorch was built with GLIBCXX_USE_CXX11_ABI=1.

**Comment by TParcollet** [comment]
@kamo-naoyuki Interestingly this error is showing while installing with the embedded venv (not a pre-installed environnement). Why isn't pytorch installing with the right flags ? I will check that, thanks you .

**Comment by kamo-naoyuki** [comment]
How did you install PyTorch? I mean, How did you run Makefile? I'm not sure.
`conda install -c pytorch pytorch` install the binary with `GLIBCXX_USE_CXX11_ABI=0`, or pip install pytorch is also, if my memory is correct, so basically this problem doesn't happen in normal setup of espnet.

**Comment by TParcollet** [comment]
Well, I literally just tipped "make KALDI=myKaldiRoot CUDA=9.2". Then I sourced tools/venv and checked 'import warpctc_pytorch'.

**Comment by kamo-naoyuki** [comment]
Can you check torch._C._GLIBCXX_USE_CXX11_ABI? Is it True?

**Comment by TParcollet** [comment]
It is, I will check how to force this variable to be false when installing Pytorch.

**Comment by sw005320** [comment]
Did you solve it or not yet? If you solved it, could you share your TIPS on how you solve this issue?

**Comment by TParcollet** [comment]
Of course sorry. Well, it turns out that in my cluster, the automatic install was installing PyTorch with torch._C._GLIBCXX_USE_CXX11_ABI=1 . I, therefore, installed PyTorch inside a conda env manually following the advice of: [https://discuss.pytorch.org/t/undefined-symbol-when-import-lltm-cpp-extension/32627/2](url) . torch._C._GLIBCXX_USE_CXX11_ABI went to False and i eventually installed espnet normaly.

**Comment by sw005320** [comment]
That's good to know. Thanks!
