### ISSUE TITLE
[Bug] 'espnet.nets.pytorch_backend.e2e_asr_transformer:E2E' object has no attribute 'recognize_batch'

### ISSUE THREAD

**Issue by Emrys365** [espnet/espnet#916]
Hi,

When decoding with a trained Transformer model, the following error occurred:

```bash
  File "$ESPNET_ROOT/espnet/bin/asr_recog.py", line 159, in <module>
    main(sys.argv[1:])
  File "$ESPNET_ROOT/espnet/bin/asr_recog.py", line 147, in main
    recog(args)
  File "$ESPNET_ROOT/espnet/asr/pytorch_backend/asr.py", line 600, in recog
    nbest_hyps = model.recognize_batch(feats, args, train_args.char_list, rnnlm=rnnlm)
  File "$ESPNET_ROOT/tools/venv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 535, in __getattr__
    type(self).__name__, name))
AttributeError: 'E2E' object has no attribute 'recognize_batch'
```
I found the definition of `recognize_batch()` in `$ESPNET_ROOT/espnet/nets/pytorch_backend/e2e_asr.py`, but not in `$ESPNET_ROOT/espnet/nets/pytorch_backend/e2e_asr_transformer.py`. So I guess there is some undone work in the Transformer part.

**Comment by Fhrozen** [comment]
Yesm you are right. The transformer has not yes implemented batch decoding or gpu decoding. This is the situation for both backends (pytorch and chainer). Probably will be added as a task for v0.5.0 #849
