### ISSUE TITLE
How to reproduce the results

### ISSUE THREAD

**Issue by fotwo** [espnet/espnet#919]
Hi, I am currently working on reproducing some SOTA results mentioned in the README.md. However, the memory error happens when the model is very large(e.g, using single gpu to run 12 encooders and 6 decoders.).
So what is your gpu device(e.g. GTX1080ti)?
I think smaller batch size and multiple gpus maybe relieve the problem, e.g. `1xgpu batch32 --> 4gpu batch8`, but the results may be damaged? So are there any better methods? Thanks.

**Comment by sw005320** [comment]
Which recipe are you talking about?
We'll also put such information soon (GPU type, number of GPUs) for our recipe for the reproducibility.
I mostly used single GPU (GTX1080ti) to get the SOTA performance for most recipes (aishell, hkust, librispeech, tedlium2) based on the default setup without having the memory errors. If you have GPU memory issues, you can just slightly reduce the batch size.

**Comment by fotwo** [comment]
Thanks, I will try it and the work was on hkust. 
Another interesting thing is that the memory usage seems to decrease after conducting resume-training(i.e., using `--resume` option), so is there any 'implicit mechanism' under this phenomenon (maybe some useless memory does not be released during direct training?). And could we utilize this 'mechanism' to reduce the memory usage further? 
|  GPU   |    PID  | Type  | Process name  |  Usage |
|--------|--------|--------|--------|--------|
|    1   |   3957   |   C |  python  |    6095MiB |
|    2   |   4043   |   C  | python   |   10561MiB |

**Comment by sw005320** [comment]
I did not observe it, and I cannot tell what happened. In my experience, the GPU  memory usage is quite stable, and GPU memory shortage errors are reproducible.

**Comment by fotwo** [comment]
ok, thanks again.
