### ISSUE TITLE
The file order is not match in iwslt18 st test set

### ISSUE THREAD

**Issue by CherrieWang97** [espnet/espnet#922]
I notice that the file order in test set of iwslt18 is not match between .yaml and text

for example,  the dev2010.de file has 654 lines but the test-db-dev2010.yaml has 974 lines.
It makes the hypothesis generated by the model has 974 lines. And the file order is different. So I can't compute the bleu score. How to fix it?

**Comment by sw005320** [comment]
@hirofumi0810, could you answer it?

**Comment by hirofumi0810** [comment]
@CherrieWang97 

> I notice that the file order in test set of iwslt18 is not match between .yaml and text

This is true and expected.

> So I can't compute the bleu score.

This is not true. I prepared scripts for this. Can you show me log files if there is some bugs?
