### ISSUE TITLE
Too deep directly structre

### ISSUE THREAD

**Issue by kamo-naoyuki** [espnet/espnet#942]
`espnet/nets/pytorch_backend/transformer` looks too deep. What do you think, guys?

**Comment by kan-bayashi** [comment]
I agree but I have no good idea.
Do you have any suggestions?

**Comment by kamo-naoyuki** [comment]
I just asked, so I don't have. Possible patterns are

- Use suffix
```
 espnet/
    nets_th/
    nets_ch/
```
- Another root directory
```
espnet_utils/
espnet_pytorch/
espnet_chainer/
```
- Throw away chainer.

**Comment by sw005320** [comment]
If we just want to avoid the deep directory structure, the following seems to be reasonable.

> - Use suffix
> ```
>  espnet/
>     nets_th/
>     nets_ch/
> ```

**Comment by kamo-naoyuki** [comment]
I got another idea.

- Remove nets and pull up rnn, etc.
```
espnet/
   lm/
     pytorch_backend/
     chainer_backend/
   frontend/
     pytorch_backend/
   ctc/
   interfaces/  # Not good?
      asr_interface.py
      tts_interface.py
   rnn/
     pytorch_backend/
         e2e_asr.py
     chainer_backend/
         e2e_asr.py
   transformer/
     pytorch_backend/
     chainer_backend/
   tacotron2/
     pytorch_backend/
   mix/
     pytorch_backend/
          e2e_asr_mix.py
```

Or

```
espnet/
  pytorch_backend/
     rnn/
     ...
  chainer_backend/
  utils/
  ...
```

**Comment by qmpzzpmq** [comment]
>  espnet/
>   pytorch_backend/
>      rnn/
>      ...
>   chainer_backend/
>   utils/
>   ...
sound reasonable
