### ISSUE TITLE
Scoring error in iwslt18 for asr1 and st1

### ISSUE THREAD

**Issue by Natalia-T** [espnet/espnet#944]
There are similar scoring errors in both scripts for iwslt18: asr1 and st1.

Scoring works for dev.de and  test.de,  but does not work for dev2010.de tst2010.de tst2013.de tst2014.de tst2015.de

This works:
`if [ ${rtask} = "dev.en" ] || [ ${rtask} = "test.en" ]; then
local/score_sclite.sh --case ${case} --nlsyms ${nlsyms} --wer true ${expdir}/${decode_dir} ${dict}`
This fails:
`else
set=$(echo ${rtask} | cut -f -1 -d ".")
local/score_sclite_reseg.sh --case ${case} --nlsyms ${nlsyms} --wer true ${expdir}/${decode_dir} ${dict} ${st_ted} ${set}
fi`

with the following error:
`(concatjson:31) INFO: .../espnet/tools/venv/bin/python .../espnet/egs/iwslt18/asr1/../../../utils/concatjson.py exp/train_nodevtest_sp.en_lc.rm_pytorch_train/decode_tst2010.en_decode/data.1.json exp/train_nodevtest_sp.en_lc.rm_pytorch_train/decode_tst2010.en_decode/data.10.json exp/train_nodevtest_sp.en_lc.rm_pytorch_train/decode_tst2010.en_decode/data.11.json exp/train_nodevtest_sp.en_lc.rm_pytorch_train/decode_tst2010.en_decode/data.12.json exp/train_nodevtest_sp.en_lc.rm_pytorch_train/decode_tst2010.en_decode/data.13.json exp/train_nodevtest_sp.en_lc.rm_pytorch_train/decode_tst2010.en_decode/data.14.json exp/train_nodevtest_sp.en_lc.rm_pytorch_train/decode_tst2010.en_decode/data.15.json exp/train_nodevtest_sp.en_lc.rm_pytorch_train/decode_tst2010.en_decode/data.16.json exp/train_nodevtest_sp.en_lc.rm_pytorch_train/decode_tst2010.en_decode/data.2.json exp/train_nodevtest_sp.en_lc.rm_pytorch_train/decode_tst2010.en_decode/data.3.json exp/train_nodevtest_sp.en_lc.rm_pytorch_train/decode_tst2010.en_decode/data.4.json exp/train_nodevtest_sp.en_lc.rm_pytorch_train/decode_tst2010.en_decode/data.5.json exp/train_nodevtest_sp.en_lc.rm_pytorch_train/decode_tst2010.en_decode/data.6.json exp/train_nodevtest_sp.en_lc.rm_pytorch_train/decode_tst2010.en_decode/data.7.json exp/train_nodevtest_sp.en_lc.rm_pytorch_train/decode_tst2010.en_decode/data.8.json exp/train_nodevtest_sp.en_lc.rm_pytorch_train/decode_tst2010.en_decode/data.9.json
(concatjson:41) INFO: new json has 1656 utterances
(json2trn_reorder:29) INFO: reading exp/train_nodevtest_sp.en_lc.rm_pytorch_train/decode_tst2010.en_decode/data.json
(json2trn_reorder:33) INFO: reading data/lang_1char/train_nodevtest_sp.en_units_lc.rm.txt
(json2trn_reorder:40) INFO: writing hyp trn to exp/train_nodevtest_sp.en_lc.rm_pytorch_train/decode_tst2010.en_decode/hyp.trn.org
(reorder_text:26) INFO: reading data/tst2010.en/text_noseg.lc.rm
  File "...../espnet/tools/mwerSegmenter/sgm2mref.py", line 84
    except IOError, ioError:
                  ^
SyntaxError: invalid syntax`

This is because sgm2mref.py should be run in python 2, but not in python 3.

**Comment by sw005320** [comment]
Thanks a lot for the report.
@hirofumi0810 told me that he could fix it in his local, but `mwerSegmenter` is an external tool, and we could not directly fix it. Instead, I'm asking @hirofumi0810 to prepare a patch to fix this issue. @hirofumi0810 will follow up it.

**Comment by Kuzhuahu** [comment]
> Thanks a lot for the report.
> @hirofumi0810 told me that he could fix it in his local, but `mwerSegmenter` is an external tool, and we could not directly fix it. Instead, I'm asking @hirofumi0810 to prepare a patch to fix this issue. @hirofumi0810 will follow up it.

I meet the same probelm as above ,and how can i fix it in my local? thanks a lot
