### ISSUE TITLE
How to improve outputs?

### ISSUE THREAD

**Issue by robothubtokyo** [espnet/espnet#945]
I tried JSUT corpus and couldn't get good result, especially when I use original sentences.

ex)
sentences from JSUT corpus
REF:  水をマレーシアから買わなくてはならないのです。 
HYP:  水をマレーシャーからなくてはならないのです。
REF:  木曜日、停戦会談は、何の進展もないまま終了しました。 
HYP:  木曜日、定戦界団は、何の信点もないましました。 

original sentences
REF:  お電話ありがとうございます。
HYP:  よどうな人がないます。
REF:  ありがとうございました。
HYP:  あちょうかいなしていないしなしていな。

What can I do to improve the outputs?

**Comment by kan-bayashi** [comment]
JSUT is a small corpus and contains only single female speaker’s speech.
It is difficult to achieve an enough performance in decoding of original sentence (you mean original speech?).
It is better to try more large recipe e.g. CSJ.

**Comment by robothubtokyo** [comment]
@kan-bayashi Thank you. I will try CSJ.
