### ISSUE TITLE
Process after output for Japanese

### ISSUE THREAD

**Issue by robothubtokyo** [espnet/espnet#951]
I'm developing ASR for Japanese.
So I want to know WHAT is the type of the outputs from endtoend network, and
HOW are they converted to Japanese sentences.
Thank you.

**Comment by Fhrozen** [comment]
Hey there, you can check at egs/csj/asr1 to look for japanese asr. 
The output is japanese character such as the following sentence:
```と後相関性の高いニューロン間のシナプス結合は強くなるというヘブの学習則的観点からですまヘブのす学習則的観点ていう面をもうちょっとお説明しますと```
It can mix hiragana, katakana and kanji.
There is not conversion, the output of the network is a softmax layer with an index for each japanese character.
