### ISSUE TITLE
ESPnet inference error:  CUDA error: out of memory

### ISSUE THREAD

**Issue by fuzhengjia** [espnet/espnet#958]
When we try the inference using GPU for decoding, we always got this "CUDA error: out of memory". We have tried different combination of batch size / thread / gpu, including different gpu types 1080ti, 2080ti and v100 (32G), even set the batchsize = 1. 

Does any one experience similar issue before? 

Thanks

**Comment by sknadig** [comment]
I think reducing `nj` helps.
You can have less number of jobs with `nj`, say `nj=2`, and a larger batch, say `batchsize=16`.
But, if you have a larger `nj`, it will load the model `nj` times in parallel. Since the model takes large amount of memory, you end up with the CUDA error.

**Comment by fuzhengjia** [comment]
Hi thanks. 
We suddenly realize that this problem appears because our inference is based on transformer framework which at the moment is not supported, am I right?

**Comment by sw005320** [comment]
> We suddenly realize that this problem appears because our inference is based on transformer framework which at the moment is not supported, am I right?

Right. We don't support GPU decoding for the transformer (one of our important action items).

**Comment by Sunny-Hui** [comment]
Hello, to confirm, could I ask whether GPU decoding is supported for the transformer now?

**Comment by dqqcasia** [comment]
could I ask again whether GPU decoding is supported for the transformer now?
