### ISSUE TITLE
some questions about param num-spkrs in asr_train.py

### ISSUE THREAD

**Issue by Pydataman** [espnet/espnet#960]
hello,
in **asr_train.py**, param **num-spkrs** only is chosen one of [1, 2], but in aishell recipe and so on, number of speaker is more than 2. different speakers say the same thing, the asr features are different. If this parameter is defaulted to 1，why design **asr_mix.py**, and can only handle 2 speakers。

I am looking forward to reply
thanks！

**Comment by sw005320** [comment]
This is designed for multispeaker speech recognition (more than one speaker are speaking at the same time). @simpleoier, could you add more comments on the multispeaker setup in the `asr_train.py` to avoid such confusions.

**Comment by simpleoier** [comment]
ok, I will take care of this.

**Comment by Pydataman** [comment]
@simpleoier thanks
