### ISSUE TITLE
Customizing to recognize personal OOVs

### ISSUE THREAD

**Issue by robothubtokyo** [espnet/espnet#963]
We want to recognize personal OOVs (out of vocabulary).
For example, people usually connect a Japanese word "O-ta" with "太田" or "大田", but sometimes with "多田". It happens especially when the listener's frequency in use of "多田" is higher than that of "太田" or "大田". In this case, "多田" is one of the listener's OOVs.
Assume that we already know someone's OOVs and pronunciations of each, can we customize ESPnet and recognize those OOVs ?

Thank you.

**Comment by sw005320** [comment]
This is one of the issues that end-to-end methods cannot easily handle. The current ESPnet does not handle it.

**Comment by robothubtokyo** [comment]
Thank you for your reply.
How about using synthesized speech to solve the problem ?
If we could make synthesized speech that contains OOVs, can we use it as an additional corpus ?

**Comment by sw005320** [comment]
Yes, this is one way (see https://arxiv.org/pdf/1807.10893.pdf).

**Comment by robothubtokyo** [comment]
Thank you so much !
We will try the way.
