### ISSUE TITLE
Cupy Import Error.

### ISSUE THREAD

**Issue by Xiaofei-Wang** [espnet/espnet#969]
Does someone have the cupy import error during making the ESPnet?
For example, if I 
`make KALDI=/path/to/kaldi CUDA_VERSION=9.0`
The cupy 6.0 still tries to find libraries of CUDA 10.0 on default, although I have correctly set the environment.

Instead of using 
`cupy.done: espnet.done
ifneq ($(strip $(CUPY_VERSION)),)
	. venv/bin/activate && pip install cupy==$(CUPY_VERSION)
	touch cupy.done
endif`

I have to manually change the code to
`cupy.done: espnet.done
ifneq ($(strip $(CUPY_VERSION)),)
	. venv/bin/activate && pip install cupy-cuda90==$(CUPY_VERSION)
	touch cupy.done
endif`

I would suggest making a small modification of the Makefile: )

**Comment by sw005320** [comment]
Thanks for the report.
If so, it would be better to switch to use `cupy-cuda80`, `cupy-cuda90`, `cupy-cuda100`, etc.(?)
Hmm, this is not so cool option.
