### ISSUE TITLE
some ideas about chinese asr

### ISSUE THREAD

**Issue by Pydataman** [espnet/espnet#983]
for chinese asr, the target of model base on word,maybe beneficial for large amounts of asr data, avoid oov, but for small amount of data, base on phone or pinyin, maybe better.
I have read two articles and compared various unit targets.

1、A Comparison of Modeling Units in Sequence-to-Sequence Speech Recognition
with the Transformer on Mandarin Chinese 
2、Syllable-Based Sequence-to-Sequence Speech Recognition with the
Transformer in Mandarin Chinese

**Comment by mowayao** [comment]
However, Paper 2 shows the experimental results on HKUST that characters is better modeling units than pinyin.

**Comment by Pydataman** [comment]
@mowayao 
there are some errors in pinyin to character，I guess.

**Comment by mowayao** [comment]
> @mowayao
> there are some errors in pinyin to character，I guess.

Have you ever done some experiments to compare these two modeling units with different models such as ctc, ctc+attention?

**Comment by sw005320** [comment]
I'm not a big fan of using some language-specific process including the use of phoneme/pinyin dictionary on the e2e ASR. In the ESPnet Mandarin tasks (HKUST and AISHELL), both methods are comparable/superior to Kaldi-based hybrid systems based on phoneme dictionary and I think this is good enough, but it would be great if someone shows the effectiveness of introducing such methods.
