### ISSUE TITLE
The scoring script is incorrect if any pruning is done on the dictionary or in the case of word models

### ISSUE THREAD

**Issue by siddalmia** [espnet/espnet#993]
Hi @sw005320 and other developers,

The command `json2trn.py ${dir}/data.json ${dic} --num-spkrs ${num_spkrs} --refs ${dir}/ref.trn --hyps ${dir}/hyp.trn` in the `score_sclite.sh` replaces all units in reference that are not in the dictionary with unk and then scores it.

This is wrong because you are modifying the reference transcription to match your dictionary. Let's say I train a model with dictionary with only 1 term "Mr" and the hypothesis is 
"Mr unk unk" and reference is "Mr John Doe". This would give a WER of 0% because the reference would be modified to "Mr unk unk".

**Comment by sw005320** [comment]
Thanks. You're right. Let me try to fix it.
